### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by chays77** [johngodley/redirection#1000]
Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
JavaScript: http://upscapetravel.com/wp-content/plugins/redirection/redirection.js
REST API: http://upscapetravel.com/wp-json/

**Comment by chays77** [comment]
Reinstalling the plugin did not work for me.

**Comment by johngodley** [comment]
http://upscapetravel.com/wp-content/plugins/redirection/redirection.js does not exist?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
