### ISSUE TITLE
Redirect to 410

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#1001]
I am confused. I came across screen shots for setting a redirect as a 410 Gone. But when I click the button to add a redirect in the 404 log I see no such options. 

If I am on the redirect tab then there is a cog and the options come up for setting as 410. Why not from the 404 log too? I have a few obsolete pages now and want to 410 them and it would be nice to enter them without typing the source links.

**Comment by YipYup** [comment]
I like the idea of adding 410 as an option. This would be especially useful for bots (search engines/spiders/indexers/web crawlers) to tell the search engine to stop attempting to revisit the 404 removed page any more.

**Comment by johngodley** [comment]
Added in #1232
