### ISSUE TITLE
[Feature] Autocompletion for redirection target

### ISSUE THREAD

**Issue by strarsis** [johngodley/redirection#1004]
### Summary
Provide autocompletion for redirection target (input field).

It would be very helpful if the redirection target URL can be picked from an autocompletion field 
(for posts/pages/custom post types) like it is possible for hyperlinks in WordPress editor.

**Comment by johngodley** [comment]
Added in #1614 and available in beta at https://github.com/johngodley/redirection/releases/tag/4.2-beta-1
