### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by Remzi1993** [johngodley/redirection#1009]
```
Uncaught SyntaxError: Invalid or unexpected token https://allincassobureau.nl/wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75 12
```

Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 7.2.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
JavaScript: https://allincassobureau.nl/wp-content/plugins/redirection/redirection.js
REST API: https://allincassobureau.nl/wp-json/

**Comment by johngodley** [comment]
Your JS file seems to be corrupt:

![https___allincassobureau_nl_wp-content_plugins_redirection_redirection_js_ver_3_2-df1f37ef3f6aba1189b89b37737a9a75](https://user-images.githubusercontent.com/1277682/41542185-45990e86-730c-11e8-83b0-4c4de094dd74.jpg)

You will need to install uncorrupted versions of the files.

**Comment by Remzi1993** [comment]
Hi @johngodley I have already reinstalled twice and manual via FTP.
I think there's something going on with your plugin.

**Comment by johngodley** [comment]
The file included in the plugin is here:

https://plugins.trac.wordpress.org/browser/redirection/trunk/redirection.js

You can see it contains no corruption.

When I now look at your file I do not see the corruption, so whatever you have done recently has cleared it up. If an error is still occurring for you then I would try clearing your browser cache as it may have cached the older version.

If you still get an error then open your browser's developer console and see if any extra details are shown. At this point it is likely another plugin that is throwing an error that is stopping Redirection from running.

**Comment by Remzi1993** [comment]
Hi @johngodley my sincere apologies. It was a hosting issue which is resolved.
Thank you very much for your assistance and you afford 👍

**Comment by stefkicks** [comment]
@Remzi1993 I have the same issue. How dit you resolve this issue with your hosting?

**Comment by Remzi1993** [comment]
@stefkicks We were had some hosting issue, a datacenter had an electrical outrage. So some servers were corrupted and some dns issue. My webhosting company had fixed these issue, so actually they fixed it.

Better to contact your hosting company.
