### ISSUE TITLE
Can't get a workable solution

### ISSUE THREAD

**Issue by ManfredMeise** [johngodley/redirection#1010]
Hi John,

I'm still running into situations, where the version 3.2 (and earlier) does not allow me to match i.e.

https://www.mmi-consult.de/XING-Willkommensgeschenk/
https://www.mmi-consult.de/XING-Willkommensgeschenk
https://www.mmi-consult.de/XING-willkommensgeschenk
https://www.mmi-consult.de/xing-willkommensgeschenk
https://www.mmi-consult.de/xing-willkommengeschenk

by regex other than specifing 5 rules in total. Any ideas/hints?

Regards,
Manfred

**Comment by johngodley** [comment]
https://github.com/johngodley/redirection/issues/166

**Comment by johngodley** [comment]
Closing in favour of 166
