### ISSUE TITLE
REST API Error

### ISSUE THREAD

**Issue by LeeStuttaford** [johngodley/redirection#1011]
Hi John,

https://www.mukuru.com | UN:  XXXX | pw : XXXXX

We are trying to add more redirects, to a total of of just over 300 currently, (we have your plugin working on a couple of other sites with higher totals too).

We get an alert saying that there is a REST API issue:
https://www.dropbox.com/s/z352566gejcnzjo/Screenshot%202018-06-18%2017.32.27.PNG

Yet, visiting the test url for JSON : 
https://www.mukuru.com/wp-json/redirection/v1/ - is showing a response - both when logged in as admin and also when not logged in?

Lee - CTO @ Semantica.co.za

Environment
PHP 7 / Nginx / MySQL 5.6

Chrome (Mac), v 67 / Safari  v11.11, WordPress v 4.9.6 and Redirection v 3.2

**Comment by johngodley** [comment]
Can you paste the error here? Typically a server will block the actual POST requests to the API, but allow GET requests, and that's probably happening here

**Comment by LeeStuttaford** [comment]
The error is simply that we can’t add more redirections and it shows an
issue with the REST API.

Do you require server logs perhaps ?

*Lee Stuttaford*

Co-founder & director of Projects & Technology

t : 021 .555 .1050 <//021%20.555%20.1050>  · c : 072 .247 .7087  · m :
lee@semantica.co.za  · w : semantica.co.za
*M2011/009277/07 | SEMANTICA DIGITAL (Pty) Ltd*

From: John <notifications@github.com> <notifications@github.com>
Reply: johngodley/redirection
<reply@reply.github.com>
<reply@reply.github.com>
Date: 18 June 2018 at 17:47:16
To: johngodley/redirection <redirection@noreply.github.com>
<redirection@noreply.github.com>
Cc: LeeStuttaford <lee@semantica.co.za> <lee@semantica.co.za>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [johngodley/redirection] REST API Error (#1011)

Can you paste the error here? Typically a server will block the actual POST
requests to the API, but allow GET requests, and that's probably happening
here

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/johngodley/redirection/issues/1011#issuecomment-398100864>,
or mute the thread

**Comment by TBarregren** [comment]
I've got similar problem.

When visiting Tools » Redirection I get 401 Unauthorized. This is what's happening:

REQUEST: GET https://www.hager.se/magasin/wp-json/redirection/v1/redirect/?orderby=id&_wpnonce=d2c627ff88
RESPONSE: 301 Location: https://www.hager.se/magasin/wp-json/redirection/v1/redirect
REQUEST: GET https://www.hager.se/magasin/wp-json/redirection/v1/redirect
RESPONSE: 401 Unauthorized

**Comment by johngodley** [comment]
@LeeStuttaford I just noticed that you pasted your login details here. Please be aware this is a public place and you should change your login ASAP. I've edited the details here, but they have been available for 30 days

The screenshot you posted is probably a false positive. Are you seeing another error?

@TBarregren your message seems different and indicates that something on your site is blocking the REST API. Are you running a plugin that may do this?

**Comment by LeeStuttaford** [comment]
Thanks John, I kept replying by email and didn’t realize !

**Comment by TBarregren** [comment]
@johngodley I get the same message even when disabling all plugins.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
