### ISSUE TITLE
?et_core_page_resource=

### ISSUE THREAD

**Issue by BS187Chicago** [johngodley/redirection#1012]
I have this code  ?et_core_page_resource=  coming up In my google webmaster = For so far that I checked Two of my websites = When I redirect the code properly = I redirected from cPanel , Then I'm move the code To the top In the HT access file. = It then breaks my sites. Thanks.

https://www.citystrip.us 

<img width="1440" alt="screen shot 2018-06-18 at 1 14 08 pm" src="https://user-images.githubusercontent.com/20387376/41556002-09608c8a-72ff-11e8-81b1-d7590a0d21cc.png">

**Comment by johngodley** [comment]
Are you using Redirection to add the redirect? If so, can you show me what redirect you created in Redirection

Things can take a while to update in Google.

**Comment by BS187Chicago** [comment]
Are you using Redirection to add the redirect? NO IM NOT = I redirected from cPanel , Then I'm move the code To the top In the HT access file. ====== thanks I figured it out I added this code to my .HTaccess file ===== It's working now.

RewriteEngine On
RewriteCond %{HTTP_HOST} ^(www.)?citystrip.us$
RewriteCond %{QUERY_STRING} ^et_core_page_resource\=$
RewriteRUle ^(.*)$ https://www.citystrip.us/? [R=301,L]
