### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by deep8** [johngodley/redirection#1013]
Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 7.0.25
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
JavaScript: https://www.meruaccounting.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.meruaccounting.com/wp-json/

**Comment by johngodley** [comment]
Are there any more details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
