### ISSUE TITLE
Redirection with #

### ISSUE THREAD

**Issue by d090** [johngodley/redirection#1015]
### Summary
Redirection plugin will not redirect URL's of the form:  
http://www.whiterockgallery.com/bob-kebic/#WRG-1/12/1063-36x48-Bob_Kebic.jpg
to
http://www.whiterockgallery.com/bob-kebic-archive/#WRG-1/2/1063-36x48-Bob_Kebic.jpg 

it is probably the # symbol causing the problem, I would guess.
This problem has become critical to our website.
Is there a solution?

### Environment
Redirection ver.  3.2
Wordpress ver. 4.9.5

**Comment by johngodley** [comment]
It is impossible to redirect these on the server using Redirection or anything else - the # is not sent to the server.

Your only solution is to do the redirect in the client using JavaScript.

**Comment by d090** [comment]
Is it possible in Redirection to use a regex, I see the feature there.  Is is possible to use a regex to identify the incoming URL , stripped of the #?

**Comment by johngodley** [comment]
Yes, you can use a regular expression. However, in this instance you will only ever receive `/bob-kebic/`, nothing after the `#` is sent by the browser to the server.

**Comment by d090** [comment]
Interesting. But people can bookmark these links with the #, and share them on Pinterest and Facebook etc. and they work... (sorry to go on about this, but I need to understand so I can find a solution. )

**Comment by johngodley** [comment]
Sure, and it's handled in the browser by Facebook or Pinterest:

https://web.archive.org/web/20090508005814/http://www.mikeduncan.com/named-anchors-are-not-sent/

**Comment by d090** [comment]
Ok, so you said the only solution was in the client using Javascript. At what point would I be able to intercept the incoming url and redirect it?

**Comment by johngodley** [comment]
You need to add some JavaScript to the original page that will perform the redirect, which has to be loaded by the browser and then executed.

**Comment by d090** [comment]
I am going to need someone to help me with this, my JavaScipt is OK, but I don't know much about Wordpress or how browsers handle redirects.  

Thank you very much for your explanation's and help.
