### ISSUE TITLE
Tried adding new redirects but they are not working? 

### ISSUE THREAD

**Issue by jshirk15** [johngodley/redirection#1018]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

So first off, thanks for the awesome plugin, it has made my life much much easier! 

So I have used it on the site https://www.austinaffordabletattooremoval.com/ for a while and it has been working fine. However, I just tried to add 4 new redirects and they dont seem to be working. I also noticed that there is not Last Accessed date listed for these redirects. Any help is greatly appreciated! 

Also I cleared the cache and it still isnt working. 

I have attached a screenshot of the URLs I am trying to redirect to.
![screen shot 2018-06-21 at 2 25 06 pm](https://user-images.githubusercontent.com/40474836/41743748-f8ee81d8-755e-11e8-939b-314f22a3bd3b.png)

I am running an iMac with Google Chrome and have the latest versions available of WordPress and Redirection. 

Once again thanks for the awesome plugin and thanks for your time helping out!

**Comment by johngodley** [comment]
Those URLs are redirecting for me.

```
curl -v -I https://www.austinaffordabletattooremoval.com/tattoo-removal-laser/                                                                           
*   Trying 18.144.40.182...
* TCP_NODELAY set
* Connected to www.austinaffordabletattooremoval.com (18.144.40.182) port 443 (#0)
*  SSL certificate verify ok.

> HEAD /tattoo-removal-laser/ HTTP/1.1
> Host: www.austinaffordabletattooremoval.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 21 Jun 2018 21:04:20 GMT
< Server: Apache/2.4.27 (Amazon) OpenSSL/1.0.2k-fips PHP/5.6.35
< X-Powered-By: PHP/5.6.35
< Expires: Thu, 21 Jun 2018 22:04:21 GMT
< Cache-Control: max-age=3600
< Location: https://www.freshstartlaserclinic.com/about/
< X-Redirect-Agent: redirection
```

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
