### ISSUE TITLE
Redirect part of plugin seems to make it easy to accidentally create a redirect loop for root URL

### ISSUE THREAD

**Issue by metamocap** [johngodley/redirection#1020]
### Summary

The redirect part of the plugin seems to make it easy to accidentally create a redirect loop for the main page.

### Actual Behavior

Recently tried to create a redirect from https://www.thedoctorwithin.com to https://thedoctorwithin.com. Basically the redirect ended up as: redirect / to https://thedoctorwithin.com essentially, this would block anyone that tried to use the correct URL to reach the main page of the site.

This is the second time I've seen this sort of thing happen, trying to create a 301 redirect, starting with one of the 404 errors displayed. Unfortunately, the first time it happened, I didn't notice the problematic redirect. Created a loop that potentially rejected a lot of traffic.

Redirect / is potentially dangerous.

In the future, I suppose I should take the regex approach, though this sort of thing might bear investigating.

### Steps to reproduce

Just playing around with variations on the theme indicated above, in the first example.

### Environment

Chrome Version 67.0.3396.87 (Official Build) (64-bit) PC, 4.9.6 WP,

**Comment by metamocap** [comment]
Plugin version  3.2

WordPress REST API | Good WordPress REST API is working at https://thedoctorwithin.com/wp-json/
-- | --
Good Redirection routes are working
Good All tables present
Good Valid groups detected
Good All redirects have a valid group
Good Post monitor group is valid

**Comment by johngodley** [comment]
Noting that there is now a warning system that will catch when you paste a URL with a different domain.
