### ISSUE TITLE
How do I export list of 404 errors?

### ISSUE THREAD

**Issue by metamocap** [johngodley/redirection#1021]
### Summary

Recently revamped site has tons of 404 errors (~2500) (changes from http://www.domain.com to https://domain.com, as well as /section/page/ -> /page/.

### Actual Behavior

I would have thought that Log, or Import/Export would let me export a list of 404 errors. Perhaps my assumption is wrong. I suppose I'll have to export the redirection table through phpMyAdmin and export from there.

### Steps to reproduce

Set up the plugin, collect 404 errors, try to output to a list. 

### Environment

Chrome Version 67.0.3396.87 (Official Build) (64-bit) PC, 4.9.6 WP, Redirection v. 3.2

**Comment by metamocap** [comment]
WordPress REST API | Good WordPress REST API is working at https://thedoctorwithin.com/wp-json/
-- | --
Good Redirection routes are working
Good All tables present
Good Valid groups detected
Good All redirects have a valid group
Good Post monitor group is valid

**Comment by johngodley** [comment]
Please see this:

https://redirection.me/support/tracking-404-errors/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
