### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by stefkicks** [johngodley/redirection#1022]
```
Uncaught SyntaxError: Invalid or unexpected token http://skondras.stijlweb.nl/wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75 12
```

Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 5.5.38
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
JavaScript: http://skondras.stijlweb.nl/wp-content/plugins/redirection/redirection.js
REST API: http://skondras.stijlweb.nl/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

**Comment by johngodley** [comment]
The error suggests that another plugin is creating an error that is stopping Redirection from working. Can you try disabling other plugins and see if Redirection works?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
