### ISSUE TITLE
REST API issue with Redirects

### ISSUE THREAD

**Issue by MC1171611** [johngodley/redirection#1025]
I'm getting an error Redirection is unable to access the REST API for some reason. Nothing changed that I'm aware of, so I don't know where this came from.

`Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 5.6.27-0+deb8u1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
JavaScript: https://www.kjvchurches.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.kjvchurches.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

Error: Cookie nonce is invalid (unknown)

Error: Cookie nonce is invalid (unknown)`

**Comment by johngodley** [comment]
Can you try version 3.3? The error implies that your server is blocking the request in some way - maybe mod_security, or some other security software

**Comment by MC1171611** [comment]
Hi John,

I updated and it appears to be working (no errors on the 404s page), but the REST API issue is still there. It might be a one-off thing that just popped up on my site. Thank you for the quick response.

**Comment by johngodley** [comment]
Is it showing the same error or another one?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
