### ISSUE TITLE
Wrong redirect with HTTP

### ISSUE THREAD

**Issue by lfilippi** [johngodley/redirection#1027]
Hi. I have a problem to redirect some links.

Look at this:

http://www.priscilamaboni.com/curso/photoshop/ (This redirects to the wrong page)
https://www.priscilamaboni.com/curso/photoshop/ (This redirects to the right page)

Both have the same configuration. Where am I missing the point?

Thank you.

**Comment by johngodley** [comment]
What is the right page?

The first one is not being redirected by Redirection, the second one is.

**Comment by lfilippi** [comment]
The second one have the correct redirect. But both links, with and without HTTPS, are important for me.

Do you have any idea why this is happening?

**Comment by johngodley** [comment]
As mentioned, the first redirect is not from Redirection. I don't know why it is happening and you'll need to investigate your site setup to see

**Comment by lfilippi** [comment]
How do you know that the first example of the redirect is not done with the plugin? Where do you see this?

**Comment by johngodley** [comment]
```
curl -v -I http://www.priscilamaboni.com/curso/photoshop/                                                                                                       
*   Trying 104.31.95.250...
* TCP_NODELAY set
* Connected to www.priscilamaboni.com (104.31.95.250) port 80 (#0)
> HEAD /curso/photoshop/ HTTP/1.1
> Host: www.priscilamaboni.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 25 Jun 2018 15:09:20 GMT
< Content-Type: text/html; charset=iso-8859-1
< Connection: keep-alive
< Location: https://www.priscilamaboni.com/index.php
< Cache-Control: max-age=3600
< Expires: Mon, 25 Jun 2018 16:09:20 GMT
< Server: cloudflare
< CF-RAY: 43085acb44e634fa-LHR
```

Redirection will identify itself there and does on your second URL, but not the first.

**Comment by lfilippi** [comment]
For some reason Cloudflare ignores some links I configured to redirect in plugin. In HTTPS all works fine, but not in HTTP.

Well, I solved that by creating a Fowarding URL in Cloudflare Page Rules option.
