### ISSUE TITLE
Network Connection Error/Not Private Connection for 301 Redirect

### ISSUE THREAD

**Issue by christina-sill** [johngodley/redirection#1028]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

I set up several redirects from my wordpress blog to my shopify site and now I'm getting this message:
Your connection is not private
Attackers might be trying to steal your information from theplanthunter.thesill.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do
 Need this to actually redirect to the target I want

Explain what actually happened. If suggesting a new feature then explain what currently happens.

search for "planthunter the sill mushrooms" click on the planthunter.thesill.com article and get directed to this warning page
![image](https://user-images.githubusercontent.com/40570689/41854957-781bff50-785f-11e8-9f55-563862bf859b.png)

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Chrome Version 67.0.3396.87 (Official Build) (64-bit) and Microsoft Edge
WP WP Engine Plugin v3.2.1

**Comment by johngodley** [comment]
This is not caused by Redirection.

https://windowsreport.com/err_cert_common_name_invalid-error/

Your site doesn't exist for me.
