### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by pravinparmar2404** [johngodley/redirection#1029]
```
Uncaught SyntaxError: Unexpected end of input http://www.example.com/wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75 28
```

Plugin: 3.2
WordPress: 4.6.1 (single)
PHP: 5.6.30-0+deb8u1
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
JavaScript: http://www.example.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.example.com/wp-json/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
