### ISSUE TITLE
URL and Server match does not work

### ISSUE THREAD

**Issue by dotsam** [johngodley/redirection#1033]
### Summary

_URL and Server_ match does not work, stored server format seems to have changed during development

### Actual Behavior

The redirect rule is not matched and no redirect occurs

### Steps to reproduce

1. Assuming domain `a.test` and domain `b.test` both point to the same document root, and Wordpress's home/site_url is configured to `http://a.test`
2. Create a redirect rule of type _URL and Server_ with a Source URL of `/` and any match action. Set the server to `b.test`
3. Visit http://b.test/
4. Observe that the redirect action is not done

### Environment

Apache 2.4.33, PHP 7.1.18, Wordpress 4.9.6, Redirection 3.3.1

### Details

Looking at e64ef59ebdcec2a3fc95fb56874498553772a34d and 452149c96961410bca109abb929efc2b2520f4b5 in `matches/server.php`, it appears that the format of data that the `sanitize_server()` method returns was changed from a full URI to just the host portion. Subsequently, when just a hostname is run through `parse_url()` in the `get_target()` method,  `parse_url()` is only resolving the hostname as a path and returning `NULL` when queried for the `PHP_URL_HOST` component, so the match will always fail.

Setting `$server` to `$this->server` instead seems to resolve the issue for me, but I'm unsure if you'd like to do further sanitize the value by running it through `sanitize_server()` again.

**Comment by johngodley** [comment]
Hmm, not sure why I removed that code. Added back in 125c929a28c4dae104c1e3fae41ee92ce2d454e7 - thanks!
