### ISSUE TITLE
Wrong auto-redirect

### ISSUE THREAD

**Issue by Sostanza18** [johngodley/redirection#1043]
### Summary

If I clic on this link: http://www.i-designgroup.it/en/creation/san-rocco-new-york/
there's a wrong re-direct to http://www.i-designgroup.it/en/en/creation/hotel-canazei

### Steps to reproduce

You can replicate from here: http://www.i-designgroup.it/en/creations
click on SAN ROCCO NEW YORK

### Environment

Any browser, WordPress 4.9.6, 
Redirection plugin: Redirection (never used to redirect these pages)

**Comment by johngodley** [comment]
http://www.i-designgroup.it/en/creation/san-rocco-new-york/ redirects to http://www.i-designgroup.it/en/creation/

Can you explain your problem further and what you have configured Redirection to do

**Comment by Sostanza18** [comment]
I have never configured Redirection for this pages; 
I'm try to understand why 
http://www.i-designgroup.it/en/creation/san-rocco-new-york/
turns automatically to a different link: http://www.i-designgroup.it/en/en/creation/hotel-canazei

**Comment by johngodley** [comment]
The redirect is not powered by Redirection - something else on your server is doing it.

**Comment by Sostanza18** [comment]
Any idea about it?

**Comment by johngodley** [comment]
It really could be anything, and I can't provide support for things outside of Redirection.

**Comment by Sostanza18** [comment]
thanks anyway
