### ISSUE TITLE
Latest version requirement for PHP 5.4

### ISSUE THREAD

**Issue by peterbam** [johngodley/redirection#1044]
Current Redirection now requires PHP 5.4

I am running 5.3 and can't upgrade

Do you have link for an older version that works with PHP 5.3?

**Comment by johngodley** [comment]
You can find all older versions here:

https://wordpress.org/plugins/redirection/advanced/

I would strongly recommend upgrading your PHP as version 5.3 is not included in security updates and you will leave yourself open to any number of security issues. Even version 7.0 is being phased out by the end of the year:

https://secure.php.net/supported-versions.php

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
