### ISSUE TITLE
404s not being logged - possible conflict with wpHoot Dispatch theme

### ISSUE THREAD

**Issue by doccrispy** [johngodley/redirection#1045]
### Summary

Noticed that no 404s have been logged on my WP site since around 20th June.

### Steps to reproduce

Have wpHoot's Dispatch theme installed. Under their '404 Page' settings panel choose a custom 404 page rather than using the Theme's default 404 page. Go to non-existent page. Redirection does not log the 404. Reset the Dispatch 404 Page setting back to Theme's default page and 404 is logged properly.

This setup worked fine until around 20th June, but no 404s logged since then. I suspect this is a problem with Dispatch theme rather than Redirection plugin and will report issue to them but thought it's worth logging here.

### Environment

Wordpress version 4.9.6
Redirection plugin version 3.3.1
Dispatch theme version 4.5.3

**Comment by doccrispy** [comment]
Have received following from theme designers (wpHoot)

> Nothing has changed in the theme regarding the 404 error page code. Dispatch has always had a 404 custom page option since version 1.0 when it was released, so if the redirection plugin was working earlier, it should continue to work even after theme updation since the code is the same as earlier for handling 404.

They also suggested briefly resetting the permalink setting to plain/default then changing back, and checking that the custom 404 page had not been set to private or draft. Neither of which resolved the problem: The custom 404 page was displaying ok

**Comment by johngodley** [comment]
If it has a custom 404 page then it's possible that it's doing something that causes a problem with the 404 logging of Redirection. I don't have access to the theme so I can't really proceed further. If you could locate the 404 handling code in the theme that might be all I need.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
