### ISSUE TITLE
Sub-Domain Links are not getting redirected

### ISSUE THREAD

**Issue by learnermind** [johngodley/redirection#1058]
I had a blog (subdomain) for my site but I moved the subdomain content to main website.
ie blog.mysite.com to now mysite.com/blog
When I try and add a redirection from old link to new link. The link repeats itself. Example:
When I redirect from blog.mysite.com/xyz-abc/ to mysite.com/blog/xyz-abc, I get mysite.com/blog/xyz-abc/ with below mention error message:
This page isn’t working
www.mysite.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
How to fix this issue?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
