### ISSUE TITLE
Redirection continues after deleting plugin

### ISSUE THREAD

**Issue by rsclmumbai** [johngodley/redirection#1062]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary
I deleted the plugin rules, but redirection is still happening.
I deleted the plugin, but the redirection is still happening.
There are no other redirection plugins.
I tried disabling Yoast but still the same.
I do use a few caching plugin but I do not suspect them to cause any issues.

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior
https://www.31west.net/blog/category/outsourcing
The above pages was previously redirected to https://www.31west.net/blog/ using your plugin.
I've deleted your plugin, but its still redirecting.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce
Can't say. I can give you access to my WP-Admin if that helps. Its a live site.

Explain the steps involved to reproduce the problem

### Environment
CentOS, Nginx, Digital Ocean, Latest WP & Latest Redirection plugin.

Please list your browser, browser version, version of WordPress and Redirection plugin.
Tested on latest Chrome, & latest Safari & using online redirection checker tools.

PS: I accidentally created this issue from another login. Since GH does not have delete option, I could not delete it. Pls delete the other blank issue. Sorry for the trouble.

**Comment by johngodley** [comment]
https://www.31west.net/blog/category/outsourcing is not being redirected by Redirection. Please investigate other places on your server that may be causing the redirection

**Comment by JoelsBlog** [comment]
Hello after uninstalling ur pluging... Redirection still continues why? For e. G https://joelsblog.com.ng redirects to https://joelsblogmedia.com I no longer want to redirect what's happening

**Comment by johngodley** [comment]
@JoelsBlog please clear your browser cache

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
