### ISSUE TITLE
Unable to access the plugin - generates error 404

### ISSUE THREAD

**Issue by moses10960** [johngodley/redirection#1068]
### Summary

Unable to access the plugin

### Actual Behavior

Every time I try to access the plugin to see the redirects, log, 404s etc, the plugin doesn't load. Instead, I get a 404 page. The problem started today.

### Steps to reproduce

On WordPress, go to Tools> Redirection

### Environment

Latest chrome, latest version of WordPress as well as Redirection plugin.

**Comment by moses10960** [comment]
Not that I'm aware of. I've actually tested the plugin in my other sites and it's fine. What could have happened in the one site? Any advice?
Thanks

**Comment by johngodley** [comment]
Things generally don't just stop working, so something is likely to have changed somewhere, and it sounds like it might be your setup. First I would check if the plugin is activated and exists within the plugin directory. If you installed or upgraded any other plugins recently then it might be worth temporarily disabling those

**Comment by moses10960** [comment]
Thanks. Let me scrutinize the latest activities. I'll get back to you, hopefully with good news.

**Comment by moses10960** [comment]
Hi John,
I'm unable to pinpoint exactly what could have happened. What if I deactivate the plugin then reactivate? Will I lose the existing redirects?

**Comment by moses10960** [comment]
What happens if I deactivate the plugin in the "installed plugins" section then reactivate? Will I lose all my redirects?

**Comment by johngodley** [comment]
No, redirects are only deleted if you delete the plugin. You can try and deactivate and then reactivate it.

If it still doesnt work can you include a screenshot of your browser here when displaying the redirection page?

**Comment by johngodley** [comment]
Closing for now, please reopen with more detials
