### ISSUE TITLE
Shitty Plugin

### ISSUE THREAD

**Issue by KensonPlays** [johngodley/redirection#1071]
I have logged out and in again... multiple times (5-6x) and it refuses to work with my install. I will be giving it a 1 star review and never using again.

**Comment by johngodley** [comment]
You're welcome

**Comment by Producdevity** [comment]
@KensonPlays it's a free plugin that you probably used incorrectly. You can't demand something with that tone, definitely not if you didn't pay anything at all and didn't even take the time to have someone help you out.
