### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by nketola** [johngodley/redirection#1072]
```
Plugin: 3.4
WordPress: 4.9.7 (single)
PHP: 5.6.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
JavaScript: https://tbox.org/wp-content/plugins/redirection/redirection.js
REST API: https://tbox.org/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/bulk/redirect/delete/?orderby=id&rows=&rows=&rows=&rows=&rows=&&total=5&status=STATUS_COMPLETE&table=&per_page=200 POST
Params: {"items":"8"}
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/redirect/7/ POST
Params: {"id":7,"url":"https://tbox.org/tickets/","title":"","regex":false,"match_type":"url","action_type":"url","position":4,"group_id":1,"action_code":301,"action_data":{"url":"https://www.tbox.org/chicago-bar-crawl-tickets/"}}
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

Hi-

Taking over for a client and somehow something has happened where redirections are not working. An example is where the green button should go to /tickets (which is really a redirect). Any help would be appreciated!

**Comment by johngodley** [comment]
Can you try logging out and logging in again?

**Comment by nketola** [comment]
Hi John-

Apologies as I was waiting on the site owner to reply. I guess this is till
not working. Only lowercase works- for example just try www.tbox.org/tickets
vs www.tbox.org/TICKETS - should go to
https://tbox.org/chicago-bar-crawl-tickets/  - only lowercase does


or try www.tbox.org/tbox vs www.tbox.org/TBOX should go to
https://tbox.org/tbox2018-the-original-festa-12-bars-of-xmas-crawl/

Any insight would be helpful.

Nancy


*Nancy Ketola*

c: +1.734.730.1825
w: www.scoutforce.com
t: @nketola
li: www.linkedin.com/in/nketola

**Comment by johngodley** [comment]
The plugin is case sensitive so you will need to add another redirect for the uppercase variant.
