### ISSUE TITLE
Redirects not working for external linked images from Pinterest and Facebook

### ISSUE THREAD

**Issue by che222018** [johngodley/redirection#1074]
Hi John, thanks in advance for your help. I want to update my permlinks in Wordpress to help with SEO for my blog. So, I changed the permalink from month and name to post name, and then added Redirects for every post. However, after doing this, when I click on any of my Pinterest pins or Facebook images that should be linked to the posts, I get 404 not found errors. 

Grateful for your assistance to resolve this.

 browser - Chrome, browser version - Version 67.0.3396.87 (Official Build) (64-bit)
version of WordPress- version 4.9.7 and Redirection plugin - Version 3.4.

**Comment by johngodley** [comment]
Can you give an example of a URL?

**Comment by che222018** [comment]
so here's an example of link to a facebook post. It's working right now because I reverted back to my initial permalink format. However, when I change to post name permalink format, and add redirect, clicking on image in the post leads to 404 error on my website

https://www.facebook.com/thismamaandherkids/posts/923481581192621

**Comment by che222018** [comment]
Hi john, have you been able to look into this? I didn't think you worked on sundays and so took so long to respond yesterday as I didn't check. Hope you haven't forgotten me. Thanks so much.

**Comment by johngodley** [comment]
I haven't, this is just a hobby so it's when time allows.

So the page is https://thismamaandherkids.com/2018/07/10-things-never-say-divorced-single-mama/ ?

What redirect did you create for this?

**Comment by che222018** [comment]
I completely understand. here's the redirect
<img width="1003" alt="screen shot 2018-07-24 at 6 10 04 am" src="https://user-images.githubusercontent.com/41545195/43134687-7cd63c58-8f08-11e8-8952-f4f03661fcca.png">

is this wrong? so grateful for your help

**Comment by che222018** [comment]
my website used to be http and I switched to https about 1 month ago, I'm wondering if this could be part of the problem?

**Comment by che222018** [comment]
please help me,....
