### ISSUE TITLE
Redirect caused loss of social share count 

### ISSUE THREAD

**Issue by girlbossesrock** [johngodley/redirection#1075]
I recently installed your plugin to redirect a few posts that I had updated the URL slug to be more SEO-friendly. It was only 2 posts that I redirected.  The redirects are working fine, however, my social share counts are now missing (I use the Shareaholic plugin for my social sharing)

I am using Google Chrome for my browser (most updated version) and am up-to-date on my Wordpress version as well as all plugins that I currently have installed.

**Comment by johngodley** [comment]
The counts are missing from the redirected pages? Do you need to update whatever is counting them with the new URL?

**Comment by girlbossesrock** [comment]
The plugin (Shareaholic) isn't set up for specific pages/URLs.  It provides
sharing icons on all my pages/posts. The only thing I updated on the URL
was the slug for it.

Blessings,
LeeAnn Fox
Girl Boss | Blogging & Business Coach

https://girlbossesrock.com

*https://girlbossesrock.teachable.com
<https://girlbossesrock.teachable.com>*

**Comment by johngodley** [comment]
I don't know how shareaholic works but I imagine it uses the page URL to determine how many shares have been made on that page. If you change the URL then you will need to get shareaholic to copy the shares across to the new URL

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
