### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by PushkaCom** [johngodley/redirection#1079]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

redirect pages - not working, settings page just loads for a long time and has an error message 

### Actual Behavior

nothing / settings page has an error

### Steps to reproduce

it just suddenly stopped working

### Environment

not working on all client browsers, 
we have an old version of wp - but it just suddenly stopped working without us updating any of the plugins...
$wp_version = '4.7.11';
I updated redircetion - but it's still the same
Unable to load Redirection ☹️ v3.2

**Comment by johngodley** [comment]
Sorry for the delay. What is the error you are seeing?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
