### ISSUE TITLE
Hebrew page names not working

### ISSUE THREAD

**Issue by rbabayoff** [johngodley/redirection#1081]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

Create a page with a permalink in hebrew, such as:

צור-קשר

Try and redirect from it to contactus

It won't redirect

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Latest google chrome, wordpress and your plugin.
****

**Comment by johngodley** [comment]
You will need to URL encode the content in Hebrew. For example, using this:

https://meyerweb.com/eric/tools/dencoder/

%D7%A6%D7%95%D7%A8-%D7%A7%D7%A9%D7%A8
