### ISSUE TITLE
Redirection Error… Really ticking me off...

### ISSUE THREAD

**Issue by KensonPlays** [johngodley/redirection#1089]
```
Plugin: 3.4
WordPress: 4.9.7 (single)
PHP: 7.0.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
JavaScript: https://kensonplays.com/wp-content/plugins/redirection/redirection.js
REST API: https://kensonplays.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```
I am about ready to just give up on my whole website because of this. I have tried all my browsers (in both regular and private/incognito modes) -- Chrome, Edge, Firefox, Vivaldi. None of them are working so I don't think it's a browser issue. My host says it's not on their end.

ModSecurity is disabled. I've never used CloudFlare. I've attempted disabling all plugins but Redirection and Xpress (it's a bridge script for Xenforo, which is essential, my site is broken without it), and Elementor, the page builder. I do have "Members" for custom membergroups installed, but deactivated.

My host is *HawkHost* and I'm on their "Shared Professional" plan since I'm so low-traffic.

**Comment by YipYup** [comment]
Your session expired. Log out and back into wordpress.

**Comment by KensonPlays** [comment]
Don't you think I've tried that? Read my OP. (Tried all my browsers in reg/incognito) so multiple sessions..........

**Comment by YipYup** [comment]
Do you use any caching / performance plugins? If so, which ones?

**Comment by KensonPlays** [comment]
Redis cache is in the list but has been deactivated since this problem started.

There is a plugin called Xpress which is a bridge from Xenforo to WordPress but I don't think that's the problem.

**Comment by johngodley** [comment]
@KensonPlays if this problem still exists would it be possible to get a login to your site to see if I can debug it further? If that's ok I can be contacted here: https://redirection.me/contact/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
