### ISSUE TITLE
Can't enable monitoring

### ISSUE THREAD

**Issue by ghost** [johngodley/redirection#109]
I am running the plugin version 2.4.4 on WP 4.5.1 and on another site on 4.4.2.  On neither site can I enable monitoring for changes of posts.

Please advise

**Comment by mdwish** [comment]
I am having this issue as well.  I am not able to turn on monitoring on one of my sites but it works perfectly on another one.  Any thought as to what could be different and causing the "Monitor changes to posts:" to only show "Don't monitor"

**Comment by karenumans** [comment]
Is there a timeline for when this bug is expected to be fixed?

**Comment by johngodley** [comment]
Do you mean the monitoring setting doesn't allow you to pick a group? Or that if you enable it, it doesnt work?

**Comment by johngodley** [comment]
Closing for now, but please reopen if you have more information
