### ISSUE TITLE
Redirection Fatal error

### ISSUE THREAD

**Issue by fan22** [johngodley/redirection#1091]
Plugin : 3.4
Wordpress : 4.6.12 avec le thème 15Zine Child.
PHP : 7.0
Browser : Google Chrome
------------------------------------------
Hello,

I use the Redirection plugin for several months. The version originally downloaded was version 2.10.1

Everything worked fine, several redirections were added.

Plugin updates have been made regularly.

The latest version is version 3.4 (update made a few days ago).

Today, when I go to "Tools" and "Redirection", the following message is displayed:

---------------------------

Fatal error: Uncaught Error: Call to undefined function get_user_locale() in /homepages/12/d36106446/htdocs/LISBONNE.NET/wp-content/plugins/redirection/redirection-admin.php:328 Stack trace: #0 /homepages/12/d36106446/htdocs/LISBONNE.NET/wp-content/plugins/redirection/redirection-admin.php(221): Redirection_Admin->get_i18n_data() #1 /homepages/12/d36106446/htdocs/LISBONNE.NET/wp-includes/plugin.php(524): Redirection_Admin->redirection_head('') #2 /homepages/12/d36106446/htdocs/LISBONNE.NET/wp-admin/admin.php(212): do_action('load-tools_page...') #3 /homepages/12/d36106446/htdocs/LISBONNE.NET/wp-admin/tools.php(10): require_once('/homepages/12/d...') #4 {main} thrown in /homepages/12/d36106446/htdocs/LISBONNE.NET/wp-content/plugins/redirection/redirection-admin.php on line 328

--------------------------------

Same message when I access the plugin settings.

Thank you in advance for your help.

**Comment by johngodley** [comment]
Please upgrade your version of WordPress.
