### ISSUE TITLE
Rewrite issue special case index.php

### ISSUE THREAD

**Issue by itdahde** [johngodley/redirection#1093]
To help track problems please follow this template. If you can provide screenshots then that will help.

*We are trying to setup an special use case for a redirection. From an onld URL containing "/de.strategam.usersystem/index.php" we want to rewrite to "/" 301 moved permanently. When calling the URL, we get an 500er error and no further information by logging. The URL "/de.strategam.usersystem/index.php" is not an existing directory/file, nor any kind of content.*

### Summary

I created an rewrite rule to rewrite from "/de.strategam.usersystem/index.php" to "/" with moved permanently.

### Actual Behavior

500er on rewriting the special case use, i will send you URL in PN, because it's live to a customers homepage

### Steps to reproduce

Follow the URL, i will give you in PM, if possible or by mail.

### Environment

Chrome, FF, WP 4.7.x, PHP 7, Redirections Plugin v3.4

**Comment by johngodley** [comment]
I didn't receive an email. Closing for now, but please reopen with more details.
