### ISSUE TITLE
Single quotes (') in URLs not escaped

### ISSUE THREAD

**Issue by strarsis** [johngodley/redirection#1098]
### Summary
Creating a new redrection from a 404 entry results in a redirection with a non-matching source URL.
Only manually navigating to that URL and using the browser-escaped URL results in matching redirection.

### Actual Behavior
Single quotes in source URL in 404 entry are not escaped when used for new redirection.

### Steps to reproduce
1. Request a non-existing URI on a WordPress site with Redirection plugin which contains at least one single quote (').
2. Go to '404' tab of Redirection plugin backend page.
3. Create new redirection from logged 404.
4. Request the non-existing URI again (as in step 1), notice that the redirection doesn't match, no redirect is made.

5. Copy the URL from browser address bar.
6. Manually create a new redirection and use the copied URL as source URI (without the host part).
7. Request the non-existing URI again (as in step 1 + 4), notice that the redirection now works correctly.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Browser: `Chrome` `67.0.3396.99 (official build) 64-bit`
WordPress `4.9.7`
Redirection plugin `3.4`

**Comment by johngodley** [comment]
Fixed in [4.3 alpha 1](https://github.com/johngodley/redirection/releases/tag/4.3-alpha-1), which will be released at some point in the future. Please let me know how it goes.

Closing this issue as complete.
