### ISSUE TITLE
Problem starting Redirection 3.4

### ISSUE THREAD

**Issue by standoutsites** [johngodley/redirection#1099]
Plugin: 3.4
WordPress: 4.9.7 (single)
PHP: 5.6.37
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
JavaScript: http://pwpweb.com/wp-content/plugins/redirection/redirection.js
REST API: http://pwpweb.com/wp-json/

**Comment by standoutsites** [comment]
when the database of 404 errors is too large, redirection plugin fails to load sometimes

**Comment by johngodley** [comment]
Can you give more details? How large is too large? How does it fail to load? Are the redirects still working?

**Comment by johngodley** [comment]
CLosing for now, please reopen with more details
