### ISSUE TITLE
Activating plugin creates fatal database error

### ISSUE THREAD

**Issue by DaisyFountain** [johngodley/redirection#1100]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Download, install and activate plugin through WordPress CMS on plugin page. Plugin could not activate due to fatal database error.

### Actual Behavior

On activation, received this error:

WordPress database error: [Unknown character set: 'utf8_general_ci']
CREATE TABLE IF NOT EXISTS `wp_triarkredirection_items` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `url` mediumtext NOT NULL, `regex` int(11) unsigned NOT NULL DEFAULT '0', `position` int(11) unsigned NOT NULL DEFAULT '0', `last_count` int(10) unsigned NOT NULL DEFAULT '0', `last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `group_id` int(11) NOT NULL DEFAULT '0', `status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled', `action_type` varchar(20) NOT NULL, `action_code` int(11) unsigned NOT NULL, `action_data` mediumtext, `match_type` varchar(20) NOT NULL, `title` text, PRIMARY KEY (`id`), KEY `url` (`url`(191)), KEY `status` (`status`), KEY `regex` (`regex`), KEY `group_idpos` (`group_id`,`position`), KEY `group` (`group_id`) ) DEFAULT CHARACTER SET utf8_general_ci

WordPress database error: [Unknown character set: 'utf8_general_ci']
CREATE TABLE IF NOT EXISTS `wp_triarkredirection_items` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `url` mediumtext NOT NULL, `regex` int(11) unsigned NOT NULL DEFAULT '0', `position` int(11) unsigned NOT NULL DEFAULT '0', `last_count` int(10) unsigned NOT NULL DEFAULT '0', `last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `group_id` int(11) NOT NULL DEFAULT '0', `status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled', `action_type` varchar(20) NOT NULL, `action_code` int(11) unsigned NOT NULL, `action_data` mediumtext, `match_type` varchar(20) NOT NULL, `title` text, PRIMARY KEY (`id`), KEY `url` (`url`(191)), KEY `status` (`status`), KEY `regex` (`regex`), KEY `group_idpos` (`group_id`,`position`), KEY `group` (`group_id`) ) DEFAULT CHARACTER SET utf8_general_ci

Fatal error: Uncaught Exception: There was a database error installing Redirection - please post these details to https://github.com/johngodley/redirection/issues - CREATE TABLE IF NOT EXISTS `wp_triarkredirection_items` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `url` mediumtext NOT NULL, `regex` int(11) unsigned NOT NULL DEFAULT '0', `position` int(11) unsigned NOT NULL DEFAULT '0', `last_count` int(10) unsigned NOT NULL DEFAULT '0', `last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `group_id` int(11) NOT NULL DEFAULT '0', `status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled', `action_type` varchar(20) NOT NULL, `action_code` int(11) unsigned NOT NULL, `action_data` mediumtext, `match_type` varchar(20) NOT NULL, `title` text, PRIMARY KEY (`id`), KEY `url` (`url`(191)), KEY `status` (`status`), KEY `regex` (`regex`), KEY `group_idpos` (`group_id`,`position`), KEY `group` (`group_id`) ) DEFAULT CHARACTER SET utf8_general_ci = in /home in /home/triark/triark-pumps/public_html/wp-content/plugins/redirection/models/database.php on line 112

### Steps to reproduce

Download & activate.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Chrome Version 67.0.3396.99 on Mac, WP 4.9.7, Redirection 3.4 

![screen shot 2018-07-31 at 09 54 39](https://user-images.githubusercontent.com/38524554/43449257-e15c65a4-94a7-11e8-9a1b-4d5b5a7a62cc.png)

**Comment by johngodley** [comment]
Redirection uses whatever you have configured WordPress to use in `wp-config.php` - look there for the database collation and change it to something that your database supports.
