### ISSUE TITLE
Problem starting Redirection 3.4

### ISSUE THREAD

**Issue by romanovart125** [johngodley/redirection#1101]
Plugin: 3.4
WordPress: 4.9.7 (single)
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 YaBrowser/18.6.1.770 Yowser/2.5 Safari/537.36
JavaScript: https://asiablog.acumatica.com/wp-content/plugins/redirection/redirection.js
REST API: https://asiablog.acumatica.com/wp-json/

**Comment by YipYup** [comment]
You posted environmental details but no error messages at all. There is no error message content. You'll need to post the error message content so we can help you out.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
