### ISSUE TITLE
Redirection Won't load my redirections

### ISSUE THREAD

**Issue by callmehippy** [johngodley/redirection#1103]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

My redirection list won't show up and there's this error displaying: "WordPress returned an unexpected message. This could be caused by your REST API not working, or by another plugin or theme."

### Actual Behavior

Pluggin just won't work

### Steps to reproduce

Everytime I load a pluggin page in the admin, it shows this error message.

### Environment

I've attached the error details displayed in the error.
[redirection.txt](https://github.com/johngodley/redirection/files/2250050/redirection.txt)

**Comment by johngodley** [comment]
Your REST API is returning a 404 error page. You will need to allow it to return the REST API.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
