### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Erin82** [johngodley/redirection#1109]
Below is the error I have received & I'm not sure what I'm doing wrong.  I am logged in to Google webmaster & originally wanted to set my preferred domain.  I use httpS & am unable to set a preferred domain using this.  Per Google recommendations to index my site, I have verified all 4 possible URLs: http, httpS, http://www, & httpS://www.  My preferred domain is simply, "https://"  So I am trying to redirect the other three so they are not seen as separate sites.  I was able to complete one redirection & now I'm getting error messages.  What am I doing wrong?
Thanks,
Erin

```
Plugin: 3.4
WordPress: 4.9.8 (single)
PHP: 7.0.31
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
JavaScript: https://cauliflowerandcupcakes.com/wp-content/plugins/redirection/redirection.js
REST API: https://cauliflowerandcupcakes.com/wp-json/

Error: Invalid source URL (29)
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"https://www.cauliflowerandcupcakes.com","title":"","regex":false,"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"https://cauliflowerandcupcakes.com"}}
Code: 400 Bad Request
Raw: {"code":"redirect","message":"Invalid source URL","data":{"status":400,"error_code":29}}
```

**Comment by johngodley** [comment]
Can you try adding a slash to the end of the source URL? This bug will be fixed in the future
