### ISSUE TITLE
Redirection not working

### ISSUE THREAD

**Issue by ColinMDC** [johngodley/redirection#1113]
### Summary

URL's with forward slash don't work

### Actual Behavior
This works https://mdcomputers.com.au/networking
This doesn't https://mdcomputers.com.au/networking/

### Steps to reproduce

Enter https://mdcomputers.com.au/networking into a browser and it will redirect to new URL. Enter https://mdcomputers.com.au/networking/ with forward slash on end of URL and it will result in an error.

### Environment

Firefox Version 61.0.1 (64-bit)
WordPress Version 4.9.8
Redirection Version 3.4

**Comment by ColinMDC** [comment]
Has anyone looked at this yet?

**Comment by johngodley** [comment]
Redirection does not automatically add a trailing slash - you will need to do this yourself.
