### ISSUE TITLE
Problem starting Redirection 3.4

### ISSUE THREAD

**Issue by uhanna** [johngodley/redirection#1114]
```
Uncaught SyntaxError: Unexpected token : http://esfahantamir.com/wp-content/plugins/redirection/redirection.js?ver=3.4-c643b29f00d56bfe6df627b69aabfd3b 33
```

Plugin: 3.4
WordPress: 4.9.8 (single)
PHP: 7.1.19
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
JavaScript: http://esfahantamir.com/wp-content/plugins/redirection/redirection.js
REST API: http://esfahantamir.com/wp-json/

**Comment by johngodley** [comment]
You have another plugin running that is preventing Redirection from working. You will need to disable the other plugins to see which one is causing the problem.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
