### ISSUE TITLE
all redirections have stopped working. 

### ISSUE THREAD

**Issue by jackactaylor** [johngodley/redirection#1118]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

The plugin has stopped redirecting pages all the pages we have added.

[screen shot 2018-08-13 at 10 55 54 am](https://user-images.githubusercontent.com/24478064/44025244-84ad3f14-9ee7-11e8-90fe-76c85454968b.png)
![screen shot 2018-08-13 at 10 56 10 am](https://user-images.githubusercontent.com/24478064/44025245-84c4daac-9ee7-11e8-87ff-e11c0fa9e417.png)

### Steps to reproduce

Testing all redirects put into the plugin, also adding new redirects and checking to see if they redirect (they don't)

### Environment

Chrome - Version 68.0.3440.106 - WordPress 4.9.8 - Redirection version 3.4

**Comment by johngodley** [comment]
The SSL certificate on your site has expired. If you renew that then it will be easier to test the redirects

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
