### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by slushman** [johngodley/redirection#1119]
```
Plugin: 3.4
WordPress: 4.9.8 (single)
PHP: 7.0.31-1~dotdeb+8.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
JavaScript: https://api.slushman.com/wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

Redirection is installed on a site being used as the backend for a headless frontend built in React. The REST API is definitely working (or nothing would display in React), but I can't fetch anything from Redirection or use the plugin on the backend.

* Plugin status shows all greens.
* Redirect Tester shows up as a working.
* I don't have security software blocking the REST API.
* My hosting is Cloudways, so I'm using their Breeze caching plugin as well as Redis. I've cleared both, but that doesn't seem to affect anything.
* I also tried disabling all other plugins.

After trying all these suggestions, I received the above error.

**Comment by johngodley** [comment]
Can you try logging out and logging in again? This usually clears the problem

**Comment by slushman** [comment]
I believe this was related to Varnish caching. Once I turned that off, most of my other issues cleared up too. Closing this issue.
