### ISSUE TITLE
Allow redirect of absolute URLs

### ISSUE THREAD

**Issue by marcelturi** [johngodley/redirection#112]
Not sure why only relative URLs are forced to be accepted, but if it's easily possible you should allow absolute URLs to be redirected too.

**Comment by johngodley** [comment]
What are you trying to achieve with an absolute URL?

Absolute URLs don't make sense in the context of a redirection - you can only redirect from the site the plugin is running on, not from an external site over which the plugin has no control.

**Comment by MarceI** [comment]
An example is if you run a WP multisite and one of the sites is no longer in service but you still resolve the domain name to your network setup. I think it would be reasonable to manage all respective redirects in the default site running Redirection as they relate to the old network site specifically.

Another is if you resolve a short URL to your main site but want more flexibility in the pathname so use Redirection but only want to catch URLs like "http://short.url/serial" or "http://short.url/atp" which should redirect to "http://properwp.com/referral/podcast-visitor?ga-tracking-tags-etc".

I've dealt with many sites where an old domain still points traffic at a website but you only want to route traffic on the aliased domain name and not a relative path of the primary domain.
Another is if you resolve a short URL to your main site but want more flexibility in the pathname so use Redirection but only want to catch URLs like "http://short.url/serial" or "http://short.url/atp" which should redirect to "http://properwp.com/referral/podcast-visitor?ga-tracking-tags-etc".

I've dealt with many sites where an old domain still points traffic at a website but you only want to route traffic on the aliased domain name and not a relative path of the primary domain.

**Comment by j** [comment]
Just tried doing this and it didn't work.  Uninstalled plugin. Boo.

**Comment by johngodley** [comment]
This is now in the 3.3 beta with 'match with server'.
