### ISSUE TITLE
trailing forward slash

### ISSUE THREAD

**Issue by tomcat90** [johngodley/redirection#113]
So some of my redirects look like this /foo/bar/ redirects to some other url. I noticed the way it's written the trailing slash is treated as a separate rule. So /foor/bar isn't caught unless it's /foo/bar/

**Comment by YesThatAllen** [comment]
I've seen this as well, and will sometimes click the regex box and add `*` after `/foor/bar` to catch `/foor/bar/` as well

I'd love to have a more exact regex - to only match the trailing `/` 

As far as changes to the plugin, maybe a checkbox to auto-add the /, would be great.

**Comment by Zyniker13** [comment]
This is already possible: `^\/foo\/bar\/?$`

**Comment by johngodley** [comment]
Merging with #176
