### ISSUE TITLE
Cannot create new redirects, but old ones keep working

### ISSUE THREAD

**Issue by bgodawa** [johngodley/redirection#1134]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I have been updated on my WP plug ins. But all of a sudden I went to create a new redirection and I got the error.

### Actual Behavior

I don't know that I was doing anything, other than maybe updating apps and other plug ins, but I don't really work much or check up on it, so I just noticed the problem when I tried to create a recent redirect. I did everything that was suggested, like checking cache and deactivating other plug ins. But the error still there.

### Steps to reproduce

Everytime I open the plug in, it won't allow me to create a new redirection.

### Environment

Plugin: 3.4
WordPress: 4.9.8 (single)
PHP: 7.0.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15
JavaScript: http://godawa.com/wp/wp-content/plugins/redirection/redirection.js
REST API: http://godawa.com/wp-json/

Error: Preflight response is not successful

Error: Preflight response is not successful

<img width="1194" alt="screen shot 2018-08-24 at 12 25 34 pm" src="https://user-images.githubusercontent.com/42682073/44603794-d7ab5e80-a798-11e8-8a3f-53fde616460f.png">

**Comment by johngodley** [comment]
Answered over email
