### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by atulk16** [johngodley/redirection#1141]
When I am trying to save any redirection. I got an error and then I tried all suggested steps but still, I am getting the following error.

```
Plugin: 3.4
WordPress: 4.9.8 (single)
PHP: 5.6.14
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
JavaScript: https://www.fabhotels.com/blog/wp-content/plugins/redirection/redirection.js
REST API: https://www.fabhotels.com/blog/wp-json/

Error: Unexpected token < in JSON at position 0
Raw: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

**Comment by YipYup** [comment]
Delete the redirection plugin from your file system first. Access wordpress admin so it realizes the plugin is gone. Then, use S/FTP and upload a new copy manually. Reactivate and see how things go.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
