### ISSUE TITLE
Redirect  /?page_id and /?m 

### ISSUE THREAD

**Issue by Blogfish41** [johngodley/redirection#1142]
How do I setup a redirect for a url like "/?m " and  "/?page_id=4324&replytocom=291 ?

If I do "/?(.+)$)" the entire site ends up in error.

**Comment by YipYup** [comment]
What do you want to redirect from, and what do you want to redirect to? Exact URLs would be needed.

Also the Regex you mentioned in the first comment is missing an expected opening parenthesis
`/?(.+)$)`

You have `()` and then a second `)` but without an opening `(` for the second `)`.

**Comment by Blogfish41** [comment]
I wish to redirect these 2:
/?page_id=505 to my frontpage

/?m=20110826 to my frontpage.

**Comment by johngodley** [comment]
You need to escape the `?` in your URL, otherwise it will be treated as a regular expression character:

`/\?(.+)$`
