### ISSUE TITLE
Rest Forbidden on redirection/v2/export

### ISSUE THREAD

**Issue by emaildano** [johngodley/redirection#1144]
### Summary

I'm trying to get a JSON output of all the redirects using the REST API.

`/wp-json/redirection/v1/export/all/json`

1. Is that the correct path?
2. Is that route protected?
3. If it is protected how can I get working?

### Actual Behavior

When accessing that route I get the following JSON output error.

```
{
"code": "rest_forbidden",
"message": "Sorry, you are not allowed to do that.",
"data": {
"status": 401
}
}
```

### Environment

Running WordPress locally, using Chrome. Clean/Fresh install with only the Redirection plugin installed.

**Comment by johngodley** [comment]
Yes, you need an authenticated user that has access to Redirection (an admin). More details here:

https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

**Comment by sagive** [comment]
what do you mean "Awesome, thanks!" - what are we supposed to do? exactly? and how come this plugin became a developer only plugin?

**Comment by johngodley** [comment]
@sagive what are you trying to find out? What are you supposed to do for what?

This is a question by a developer wanting to develop something using Redirection. The plugin is not developer only.
