### ISSUE TITLE
Redirection not working with Wordpress Caching (Swift Performance)

### ISSUE THREAD

**Issue by giulianorapoz** [johngodley/redirection#1146]
### Summary

I am trying to utilise mobile redirects - so to redirect the user to a new page if they land on a specific page and if they are on a mobile device.

### Actual Behavior

When cache is cleared on wordpress site and then then I quickly test the redirection on the mobile. It works. However once the cache is built (Swift Performance) then the redirection stops functioning. 

Is there a setting in the redirection plugin to override this?

### Steps to reproduce

Test out redirection with not cached wordpress site, and then test with a cached version.

### Environment

Chrome. Version 68.0.3440.106 (Official Build) (64-bit). Wordpress 4.9.8.

**Comment by giulianorapoz** [comment]
Hi @johngodley - Is there no workaround to this? Perhaps by PHP code or .htaccess modification

**Comment by johngodley** [comment]
It's not something that requires a workaround or is a problem with Redirection - it's just how caching works. I don't know what Swift Performance is, but if it caches the whole page then that page is 'saved' as-is. If your page has dynamic content that changes depending on something (cookie, browser agent etc) then it's not possible to cache it like this - you can either have a cached page or dynamic content.

You will need to look at your caching system and see what features it has that might help.

**Comment by giulianorapoz** [comment]
Okay, appreciate the in-depth explanation. I'll investigate to see what's possible within the cache plugin.
