### ISSUE TITLE
Redirection error ("NotFoundError")

### ISSUE THREAD

**Issue by xaviarnl** [johngodley/redirection#1147]
Redirection keeps producing this error, even after emptying the browser cache and the site cache:

Plugin: 3.4
WordPress: 4.9.8 (single)
PHP: 5.6.37
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
JavaScript: https://wie-is-de-weerwolf.nl/wp-content/plugins/redirection/redirection.js
REST API: https://wie-is-de-weerwolf.nl/wp-json/
Buster: 3.4 === 3.4

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in a
    in div
    in t
    in Connect(t)
    in r
    in pl
    in t

**Comment by johngodley** [comment]
Another plugin on your site is probably causing an error. Can you try disabling other plugins and see if the problem goes away?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
