### ISSUE TITLE
Feature Request: Ability to hide certain links from the 404 log

### ISSUE THREAD

**Issue by The-Fireplace** [johngodley/redirection#1150]
### Summary

I would like to be able to hide certain 404s from the log, or not log them in the first place. This would be useful for hiding pages like /404 and this_is_a_404.html, which are frequently checked for by friendly bots, so my 404 log isn't cluttered up with 404s that aren't a problem.
### Actual Behavior

Currently, they all show up in the log, and it's anoying to have to scroll through all of the non-issue 404s to find the actual 404s that need to be fixed.

### Steps to reproduce

N/A

### Environment

Wordpress 4.9.8
Redirection 3.4

**Comment by YipYup** [comment]
Maybe a feature enhancement for a list of strings of file paths for the 404 logging to ignore. +1

**Comment by johngodley** [comment]
Closing in favour of #541
