### ISSUE TITLE
Problem starting Redirection 3.4

### ISSUE THREAD

**Issue by manivasagam** [johngodley/redirection#1152]
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined https://mykalvi.com/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,thickbox&ver=4.9.8 246
```

Plugin: 3.4
WordPress: 4.9.8 (single)
PHP: 5.6.37
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
JavaScript: https://mykalvi.com/wp-content/plugins/redirection/redirection.js
REST API: https://mykalvi.com/wp-json/

**Comment by johngodley** [comment]
Another plugin is causing an error on your site. Please try disabling some of your plugins to see which one it might be

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
