### ISSUE TITLE
matched target does not take $1 in match mode: url and server

### ISSUE THREAD

**Issue by aaronluan** [johngodley/redirection#1162]
### Summary
<img width="1208" alt="redirection2" src="https://user-images.githubusercontent.com/13211959/45261218-64762f00-b3cb-11e8-901d-b2cfeae1c4ba.png">

matched target does not take $1 in match mode: url and server

### Actual Behavior

variable $1 is not recognized. 

### Steps to reproduce

1. config a redirection rule as in the picture.
2. type in www.aaa.com/example/
3. should expect www.bbb.com/example/, but got www.bbb.com/1

**Comment by johngodley** [comment]
Added in #1232
