### ISSUE TITLE
redirection not working after moving from apache to nginx

### ISSUE THREAD

**Issue by arabdebate** [johngodley/redirection#1166]
hello,

we face a problem when we move from apache2 to nginx the old redirection links still working but if i add new link it will not works.

Support page show this problems

WordPress REST API | Problem REST API returns an error code (40x https://www.arabdebate.net/wp-json/)
-- | --
Problem REST API is not working so routes not checked

Thank you!

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
