### ISSUE TITLE
Feature request: More informative 404s error log

### ISSUE THREAD

**Issue by Theremingenieur** [johngodley/redirection#1168]
After I created a few 410 redirects to stop the bots revisiting pages or posts which are definitely deleted, I see these still as "normal" 404 errors listed in the log. Thus, I can't see if it was a true 404 or if my 410 had worked. 
Thus, I suggest to add a column to the log, indicating the real 4xx code which had been resent. 
Thank you in advance!

**Comment by johngodley** [comment]
Merging with #1024
