### ISSUE TITLE
Feature request: Adding URLs in bulk

### ISSUE THREAD

**Issue by dausruddin** [johngodley/redirection#1170]
Hi. Thanks for this awesome plugin. Can you add field to add URLs in bulk? I have 2-4 old posts to redirect to my new post. Would be much easier if there is a field where I can paste all links at once rather than adding them 1 by 1.

**Comment by brendanmullan** [comment]
Hey this can be achieved by exporting your redirects to .csv - open it with something like excel and paste in all your new redirects and then import it back into the plugin.

**Comment by johngodley** [comment]
Yep, you can use an import for this. Closing for now, but please reopen with more details.
