### ISSUE TITLE
Bug Involving Actions on Redirections

### ISSUE THREAD

**Issue by jmatthewyoung** [johngodley/redirection#1172]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

In the redirections section of the plugin, I am trying to edit/delete/disable or enable a single or a few redirects yet any action, whether multiple are checked or not applies to all. I just searched for 4 redirects, selected them and deleted them and it wiped all my entire redirections. I just added a few for testing and found that I could not even enable or disable a single one. Clicking disable on one disables the entire list. Editing a redirect doesnt save over the redirect, it creates a new one. Deleting a single one deletes the entire list. Unusable.

### Actual Behavior

When in redirects instead of being able to apply actions to a single or few redirections any and all actions are applied to the entire list.

### Steps to reproduce

1) Open wordpress
2) Go to tools > redirections
3) In the redirection tab you will find your list
4a) If you click disable/enable on a single (or just a few using checkboxes) redirect it will disable/enable the whole list
4b) If you do the same with delete it is the same
4c) If you edit a redirect and save a new redirect is created with the edited details and now both exist. And because you can't delete a single one without deleting the entire list it is there permanently.

### Environment

Chrome 68, Wordpress 4.9.8, Redirection Version 3.4.1 

**NOTE**
All my redirects that I had before are gone because of this bug so if there is any way to retrieve them via a cache or log please let me know.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
