### ISSUE TITLE
Problem starting Redirection 3.4.1

### ISSUE THREAD

**Issue by andrij200390** [johngodley/redirection#1179]
```
Uncaught SyntaxError: Invalid or unexpected token http://meta.loc/wp-content/plugins/redirection/redirection.js?ver=3.4.1-ed91efb805c3bb9d59d2bc74f23b6ddd 33
```

Plugin: 3.4.1
WordPress: 4.9.8 (single)
PHP: 5.6.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
JavaScript: http://meta.loc/wp-content/plugins/redirection/redirection.js
REST API: http://meta.loc/wp-json/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
