### ISSUE TITLE
Problem with plugin

### ISSUE THREAD

**Issue by santyrubio** [johngodley/redirection#1181]
Hello! From today that shows me the following error

Plugin: 3.4.1
WordPress: 4.9.8 (single)
PHP: 7.1.21
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
JavaScript: https://improntamusic.com/wp-content/plugins/redirection/redirection.js
REST API: https://improntamusic.com/wp-json/

Error: Unexpected token < in JSON at position 0
Raw: <br />
<b>Warning</b>:  include(/improntamusic.com/wp-content/plugins/redirection/models/log.php): failed to open stream: No such file or directory in <b>/home/santirub/public_html/improntamusic.com/wp-content/plugins/redirection/redirection.php</b> on line <b>36</b><br />
<br />
<b>Warning</b>:  include(): Failed opening '/improntamusic.com/wp-content/plugins/redirection/models/log.php' for inclusion (include_path='.:/usr/local/php71/pear') in <b>/improntamusic.com/wp-content/plugins/redirection/redirection.php</b> on line <b>36</b><br />
{"settings":{"support":false,"token":"8c875c889cec043a65e6c32ba527d6cf","monitor_post":0,"monitor_types":[],"associated_redirect":"","auto_target":"","expire_redirect":7,"expire_404":7,"modules":[],"newsletter":false,"redirect_cache":1,"ip_logging":1,"last_group_id":1,"rest_api":0,"https":false,"version":"3.4.1"},"groups":[{"text":"WordPress","value":[{"text":"Redirecciones","value":1},{"text":"Entradas modificadas","value":2}]}],"installed":"/improntamusic.com\/","canDelete":true,"post_types":{"post":"Entradas","page":"P\u00e1ginas","trash":"Trash"}}

Error: Unexpected token < in JSON at position 0
Raw: <br />
<b>Warning</b>:  include(/improntamusic.com/wp-content/plugins/redirection/models/log.php): failed to open stream: No such file or directory in <b>/improntamusic.com/wp-content/plugins/redirection/redirection.php</b> on line <b>36</b><br />
<br />
<b>Warning</b>:  include(): Failed opening '/improntamusic.com/wp-content/plugins/redirection/models/log.php' for inclusion (include_path='.:/usr/local/php71/pear') in <b>/improntamusic.com/wp-content/plugins/redirection/redirection.php</b> on line <b>36</b><br />
[{"name":"REST API de WordPress","id":"rest","status":"problem","message":"REST API returned invalid JSON data. This is probably an error page of some kind and indicates it has been disabled - Syntax error (200 - https:\/\/improntamusic.com\/wp-json\/)"},{"name":"Rutas de redirecci\u00f3n","id":"routes","status":"problem","message":"La REST API no est\u00e1 funcionando, as\u00ed que las rutas no se comprueban"},{"id":"db","name":"Tablas de la base de datos","status":"good","message":"Est\u00e1n presentes todas las tablas"},{"name":"Grupos v\u00e1lidos","id":"groups","message":"Detectados grupos v\u00e1lidos","status":"good"},{"name":"Grupo de redirecci\u00f3n v\u00e1lido","id":"redirect_groups","message":"Todas las redirecciones tienen un grupo v\u00e1lido","status":"good"},{"name":"Grupo de monitoreo de entradas","id":"monitor","message":"Post monitor group is valid","status":"good"},{"name":"Protocolo de portada y el sitio","id":"redirect_url","message":"Portada y sitio son consistentes","status":"good"}]

**Comment by johngodley** [comment]
That looks like your plugin is not installed properly.

**Comment by johngodley** [comment]
Yep, which indicates that the files don't exist. I dont know what may have changed since yesterday, but you can verify if those files exist and are readable.

**Comment by santyrubio** [comment]
How should I do? Should I delete and re-upload the plugin?

**Comment by johngodley** [comment]
Use whatever file management tool you have on your server (cPanel, FTP etc) and see if the files are in that directory. If you need to re-install the plugin then you can delete the plugin folder and re-install. Do not press 'delete plugin' from inside WordPress as this will also delete your data, including all redirects.

If you're not sure you can make a backup or export your data.
