### ISSUE TITLE
The .htaccess file is writeable, but nothing ever gets added to it

### ISSUE THREAD

**Issue by ShawnCorrigan** [johngodley/redirection#1182]
If I enter the path to the htaccess file in the Apache Module" options screen: eg. /home/user/public_html/.htaccess, nothing ever gets added to it.

Also, if I enter a different filename, the file gets created, but is empty:
/home/user/public_html/.htaccess_tmp

 If I refresh the page the "Apache Module" option is now empty again.

_Originally posted by @sgjackman in https://github.com/johngodley/redirection/issues/754#issuecomment-376022358_

**Comment by YipYup** [comment]
So the redirections made by this plugin do not actually get written into that file. They are handled at the wordpress  and wordpress plugin layer. They are stored in a new SQL table and incoming queries are evaluated against the rules stored for a possible match.

**Comment by ShawnCorrigan** [comment]
What is the purpose of this option in that case, and why is a new file
created once I enter it in there? I am not quite understanding.

**Comment by sgjackman** [comment]
@ShawnCorrigan you beat me to it! 
Why have an .htaccess option if it's not doing anything?

**Comment by johngodley** [comment]
The .htaccess option does have a function. Have you added redirects to an Apache group, as described in https://redirection.me/support/groups/ ?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
