### ISSUE TITLE
Problem starting Redirection 3.4.1

### ISSUE THREAD

**Issue by hazikmaqsood** [johngodley/redirection#1183]
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined http://hazikvu.epizy.com/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check&ver=4.9.8 246
```

Plugin: 3.4.1
WordPress: 4.9.8 (single)
PHP: 7.0.19
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
JavaScript: http://hazikvu.epizy.com/wp-content/plugins/redirection/redirection.js
REST API: http://hazikvu.epizy.com/wp-json/

**Comment by johngodley** [comment]
You are probably running another plugin that is causing a JavaScript error. If you open your browser's developer console you may see more information. You can also try disabling other plugins to see which one it is.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
