### ISSUE TITLE
Class 'Red_Item' not found

### ISSUE THREAD

**Issue by tarpey** [johngodley/redirection#119]
Out of the blue today I started getting a bunch of errors like this:

PHP Fatal error:  Class 'Red_Item' not found in D:\home\site\wwwroot\wp-content\plugins\redirection\modules\wordpress.php on line 43

Can you help?

**Comment by johngodley** [comment]
Sorry for taking so long to reply. This error shouldn't be possible. Are you still experiencing it?

**Comment by johngodley** [comment]
Maybe fixed here fe1b1467e8c4ddcc13166cae3a9a6e2812830091
