### ISSUE TITLE
Problem starting Redirection 3.5

### ISSUE THREAD

**Issue by ictboy** [johngodley/redirection#1190]
Plugin: 3.5
WordPress: 4.9.8 (single)
PHP: 7.0.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
JavaScript: https://noticiasguerrero.com/wp-content/plugins/redirection/redirection.js
REST API: https://noticiasguerrero.com/wp-json/

**Comment by johngodley** [comment]
Can you try disabling other plugins and then re-enabling them to see if any is causing the problem?
