### ISSUE TITLE
Special characters like é don't match for a redirect, but it works fine directly in an .htaccess file

### ISSUE THREAD

**Issue by kylelondonuk** [johngodley/redirection#1192]
Hi,

I am trying to match a URL like /oldsite/author/Cécile/ to redirect to our new URLS, but special characters don't seem to work within the plugin. I assume the character is getting encoded at some point in a way that doesn't match?

When I do a redirect directly in a .htaccess file like this, it's fine:

RewriteRule ^oldsite/author/Cécile/?$ https://www.example.com/author/cecile/ [R=301,L]

I am using version 4.9.8 of WordPress and version 3.5 of Redirection.

Thanks!

**Comment by johngodley** [comment]
You will need to encode the characters yourself. This will be improved in #19
