### ISSUE TITLE
Redirecting 301 to a diferent page, Help

### ISSUE THREAD

**Issue by Harvito87** [johngodley/redirection#1193]
Hi everyone!

### Actual Behavior

https://www.alahas.com.do/anillos-de-boda/  Redirecting 301 to >
https://www.alahas.com.do/product-category/anillos-de-boda/

Problem is that is redirecting to: https://www.alahas.com.do/blocks/anillos-de-boda-banner-prinicpal/ 
Only when is typed alahas.com.do/anillos-de-boda

If you type like this https://www.alahas.com.do/anillos-de-boda/  ( Only like this Is working )

### Steps to reproduce

Type: alahas.com.do/anillos-de-boda/ to reproduce the wrong redirection

### Environment

Google Chrome is up to date
Version 69.0.3497.100 (Official Build) (64-bit), WordPress 4.9.8 running Flatsome Child theme and Redirection Version 3.5 .

**Comment by johngodley** [comment]
I don't really understand the problem. Can you show me with screenshots?

**Comment by johngodley** [comment]
Closing for now please reopen with more information
