### ISSUE TITLE
Trim trailing whitespace

### ISSUE THREAD

**Issue by tynielsen** [johngodley/redirection#120]

**Comment by johngodley** [comment]
No details so closing

**Comment by jdruiter** [comment]
I guess the user means any trailing whitespace in the source or destination pattern should get trimmed - but the plugin is already doing that right?

**Comment by tynielsen** [comment]
It's been long enough I don't recall what I was referring to, which definitely backs the decision to close it from a lack of detail. But the above comment is a solid assumption. ...It was an incomplete issue either way.
