### ISSUE TITLE
Case Sensitive

### ISSUE THREAD

**Issue by sdcagle** [johngodley/redirection#1207]
### Summary

It appears the redirection is case senstive, for example www.7hills.org/welcome, redirects to https://www.7hills.org/admissions/visit-seven-hills/, however www.7hills.org/Welcome gets a 404 error.

Is there any way around this? We have several redirects?

### Environment

All major browsers, WP version 4.9.8

Thanks,
Scott Cagle

**Comment by Chris6284** [comment]
We have the same problem. Is there a possibility to add an Option per Url to lowercase (or Uppercase) an Url before executing a rule?

**Comment by johngodley** [comment]
Closing in favour of #166
