### ISSUE TITLE
Feature request: Match by Response/Status code

### ISSUE THREAD

**Issue by IvanRF** [johngodley/redirection#1208]
I have a taxonomy that creates URLs with consecutives numbers at the end for posts that have the same name. When some of these posts are removed, I want to redirect them to an specific URL.

For example:

URL | Status Code
------------ | -------------
https://colbalcarce.com/turnos/farmacia-freitas-128/ | 200 OK
https://colbalcarce.com/turnos/farmacia-freitas-999/ | 404 Not Found

I can't define a simple redirect with a regular expression, since some numbers exist and some others don't.

So, what I thought is to redirect only those pages in which the `Status Code` is `404 Not Found`.

I couldn't find a way to use the `URL and HTTP header` match option since the server returns `HTTP/1.1 404 Not Found` for the `name` and an empty `value`. (I used [this page](http://www.webconfs.com/http-header-check.php) to quickly check that)

Am I missing something or there is no way to use the response/status code as a matching condition?

**Comment by IvanRF** [comment]
@johngodley any thoughts on this matter?

If it is not possible to accomplish what I mentioned in the current version, then the feature request will be to add a new match option in order to compare [`http_response_code()`](http://php.net/manual/en/function.http-response-code.php) against a number value provided by the user.

**Comment by IvanRF** [comment]
@johngodley any thoughts on this matter?

If it is not possible to accomplish what I mentioned in the current version, then the feature request will be to add a new match option in order to compare [`http_response_code()`](http://php.net/manual/en/function.http-response-code.php) against a number value provided by the user.

**Comment by johngodley** [comment]
Closing in favour of #686
