### ISSUE TITLE
Illegal mix of collations

### ISSUE THREAD

**Issue by jd440** [johngodley/redirection#121]
I get little issue of mix collation with this module

>  WordPress Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '=' pour la requ\xc3\xaate SELECT Wp_redirection_items.*,Wp_redirection_groups.position AS group_pos FROM Wp_redirection_items INNER JOIN Wp_redirection_groups ON Wp_redirection_groups.id=Wp_redirection_items.group_id AND Wp_redirection_groups.status='enabled' AND Wp_redirection_groups.module_id=1 WHERE (Wp_redirection_items.regex=1 OR Wp_redirection_items.url='/blog/wp-content/uploads/2013/09/facile-\xe0-faire.png') faite par require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WordPress_Module->init, Red_Item::get_for_url

I notice 
- Wp_redirection_items and Wp_redirection_groups are in latin1_swedish_ci
- The database are in latin1_swedish_ci
- But must of table are in utf8

Did you already see this kind of error?

**Comment by johngodley** [comment]
I think it will be best if you use the 'delete plugin' option in Redirection's settings menu and then reactivate the plugin. This will ensure that all tables are created with the default WordPress collation.
