### ISSUE TITLE
Cannot delete or edit redirects

### ISSUE THREAD

**Issue by vedransisic** [johngodley/redirection#1212]
I keep getting an error after an upgrade from 3.2 to 3.5 telling me that the items parameter is missing, however, I can clearly see that it is passed in.

I have no clue what the issue could be. 

```
Plugin: 3.5
WordPress: 4.9.8 (single)
PHP: 7.2.7
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
JavaScript: http://localhost:8080/wp-content/plugins/redirection/redirection.js
REST API: http://localhost:8080/api/

Error: Missing parameter(s): items (rest_missing_callback_param)
Action: redirection/v1/bulk/redirect/delete/?orderby=url&filter=%2Frecipes%2F POST
Params: {"items":"15237"}
Code: 400 Bad Request
Raw: {"code":"rest_missing_callback_param","message":"Missing parameter(s): items","data":{"status":400,"params":["items"]}}
```

I ended up downgrading back to 3.2 and everything works again.

**Comment by johngodley** [comment]
What action are you performing to cause this to happen?

**Comment by vedransisic** [comment]
@johngodley 
It was happening in the admin view when I clicked "Delete" on an individual redirection item, or when I selected multiple items via the checkbox, and did a batch delete.

**Comment by johngodley** [comment]
I've not seen this problem before, and I wonder if maybe another plugin is somehow affecting the REST API. The difference between 3.2 and 3.5 may be a difference in parameters that doesn't get triggered in 3.2. You can test this by temporarily disabling everything else and seeing if that helps.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
