### ISSUE TITLE
Redirection: Failed to Fetch

### ISSUE THREAD

**Issue by aewhite77** [johngodley/redirection#1214]
### Summary

Entering a lot of redirects - after entering them git teh Check Redirect button and all has been fine.  All of a sudden - start receiving failed to Fetch errors

### Actual Behavior

Not able to test new redirects

### Steps to reproduce

Enter a new redirect - click on Check redirect.  Sometimes the first one will work  Go down the list to a previous valid and tested one and hit check redirect = Failed to Fetch Error

### Environment
Please list your browser, browser version, version of WordPress and Redirection plugin.
Chrome 69.0.3497.100
Safari Version 12.0 (13606.2.11)
Redirection plugin 3.5
WordPress: 4.9.8

<img width="1083" alt="screen shot 2018-10-05 at 3 21 30 pm" src="https://user-images.githubusercontent.com/7199548/46560770-eff7b880-c8c2-11e8-82a1-ed976023171a.png">

**Comment by johngodley** [comment]
What URL is failing?

**Comment by johngodley** [comment]
Closing for now please reopen with more information
