### ISSUE TITLE
Problem starting Redirection 3.5

### ISSUE THREAD

**Issue by StrikingLoo** [johngodley/redirection#1215]
Plugin: 3.5
WordPress: 4.9.8 (single)
PHP: 7.0.31
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
JavaScript: http://www.dataden.tech/wp-content/plugins/redirection/redirection.js
REST API: http://www.dataden.tech/wp-json/

(I'm just pasting the output, but I'm using chrome)

**Comment by johngodley** [comment]
Sorry for the delay. Another plugin on your site is probably stopping Redirection from running. Can you disable other plugins and try again?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
