### ISSUE TITLE
Update Failed (trying to update from 3.4 to 3.5)

### ISSUE THREAD

**Issue by skyphoxx** [johngodley/redirection#1219]
### Summary

I'm trying to run the update from 3.4 to 3.5 within the wordpress admin area.

### Actual Behavior

Throws this error: Update Failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.

### Steps to reproduce

Clicking 'Update Now' from Plugins -- Installed Plugins -- Redirection

### Environment

Google Chrome Version 69.0.3497.100 (Official Build) (64-bit);  Wordpress Version 4.9.8

**Comment by johngodley** [comment]
This is something specific to your WordPress and your file setup, and is unrelated to Redirection itself.

**Comment by skyphoxx** [comment]
All other plugins update fine.  Just this one is throwing the issue.  Can I get a copy of the update script so I can manually trace it step-by-step?

**Comment by skyphoxx** [comment]
also, thanks for replying so quickly!! :)

**Comment by johngodley** [comment]
There is no update script - it's all handled by WordPress, and the plugin isn't involved. It's probably that the plugin directory or files have the wrong permissions (for whatever reason), and you need to reset them. You can use FTP or whatever file management tool your host provides to check this

**Comment by skyphoxx** [comment]
Thanks!
