### ISSUE TITLE
Problem starting Redirection 3.5

### ISSUE THREAD

**Issue by StrikingLoo** [johngodley/redirection#1223]
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined http://www.dataden.tech/wp-admin/load-scripts.php?c=1&load%5B%5D=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check&ver=4.9.8 246
```

Plugin: 3.5
WordPress: 4.9.8 (single)
PHP: 7.0.31
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
JavaScript: http://www.dataden.tech/wp-content/plugins/redirection/redirection.js
REST API: http://www.dataden.tech/wp-json/

**Comment by johngodley** [comment]
A plugin on your site is causing an error. Please disable other plugins and reactive them individually to determine what is causing the problem
