### ISSUE TITLE
Unknown Column 'ip'

### ISSUE THREAD

**Issue by mhair** [johngodley/redirection#1228]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

WordPress database error Unknown column 'ip' in 'field list' for query INSERT INTO `wp_redirection_404` (`url`, `created`, `ip`, `agent`) VALUES ('/communications_center/press_releases/archive/2006/08_09_06.pdf', '2018-10-19 22:52:24', 'redacted ip', 'Googlebot/2.1 (+http://www.google.com/bot.html)') made by require('redacted domain information\wp-blog-header.php'), require_once('redacted domain information\wp-includes\template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->template_redirect, RE_404::create

Our PHP error logs are suddenly being flooded with the above. I believe I updated to the latest version last week when this started. I have turned off all logging temporarily. Should I revert?

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Redirection version 3.5
Chrome Version 69.0.3497.100 (Official Build) (64-bit)
WordPress version 4.9.8

Upon further investigation it appears that the "ip" column is indeed in the table.

![image](https://user-images.githubusercontent.com/331056/47308602-479a6180-d5ef-11e8-9bfe-68d951f525b8.png)

**Comment by johngodley** [comment]
Answered via email. Involved manually adding the IP column
