### ISSUE TITLE
Trailing slash and URL params

### ISSUE THREAD

**Issue by sebastienrdn** [johngodley/redirection#1234]
I've been investigating and I found no satisfying answer.
I would to see an option that redirects anything that looks like my URL to it.

/whatever/
/whatever?asdf
/whatever/?asdf

To have all these (and more?) redirect to /somethingelse

I tried using regex with no success (I can get /whatever/ to /somethingelse or /whatever?asdf to /somethingelse?asdf but not all three at the same time).

I think it would be a nice option to add ("Ignore/Pass on post URL params")

Otherwise, all links paste into facebook for example create an error (due to ?fb=...)

Thanks in advance!

**Comment by sebastienrdn** [comment]
I found a regex that works. Not very nice as it has to be implemented to every single one of them, but still:

^/whatever[/]?(\?.*)?$
redirects to: /somethingelse$1

**Comment by johngodley** [comment]
Generally WordPress handles trailing slashes.

I'm going to close this in favour of other issues that have already been logged that are for query params etc.
