### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Andrey-sprint** [johngodley/redirection#1238]
```
Plugin: 3.5
WordPress: 4.9.8 (single)
PHP: 7.1.19
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
JavaScript: https://sprint-rnd.ru/wp-content/plugins/redirection/redirection.js
REST API: https://sprint-rnd.ru/wp-json/

Error: Неверный параметр nonce в cookie (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 nonce \u0432 cookie","data":{"status":403}}

Error: Неверный параметр nonce в cookie (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 nonce \u0432 cookie","data":{"status":403}}
```

**Comment by Andrey-sprint** [comment]
Plugin: 3.5
WordPress: 4.9.8 (single)
PHP: 7.1.19
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
JavaScript: https://sprint-rnd.ru/wp-content/plugins/redirection/redirection.js
REST API: https://sprint-rnd.ru/wp-json/

Error: Неверный параметр nonce в cookie (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 nonce \u0432 cookie","data":{"status":403}}

Error: Неверный параметр nonce в cookie (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440 nonce \u0432 cookie","data":{"status":403}}
 @ Andrey-Спринт

**Comment by romxam** [comment]
Please logout and login again

**Comment by johngodley** [comment]
Closing for now please reopen with more information
