### ISSUE TITLE
Opening / clicking on a redirection link from Facebook

### ISSUE THREAD

**Issue by potoclips** [johngodley/redirection#1248]
### Opening / clicking on a redirection link from Facebook

Previously, activating a redirection link from Facebook was easy and with no issues.

### Actual Behavior

Now it systematically leads to an error 404 message.

### Steps to reproduce

Go to the following Facebook Group: 
https://www.facebook.com/groups/gainsbourgstories/

Click on the redirection link showed in the first post published by Man Tabary : http://www.potoclips.com/gainsbourgstories

or

Click on the redirection link showed at the bottom of the group DESCRIPTION : http://www.potoclips.com/gainsbourgstories

### Environment

Browser: Opera
Browser version: 56.0.3051.52
Wordpress version: 4.9.8
Redirection plugin version: 3.5

**Comment by johngodley** [comment]
Facebook adds extra parameters to URLs, and you will need to accommodate these in your redirect until #410 is added.

**Comment by potoclips** [comment]
Ok.

"you will need to accommodate these in your redirect"
What does it mean technically in redirection? Is there a way to manage it in the current version ?
or
Is it a nice way to invite me to wait for till the release f a new fix that will manage this problem?
Thanks

**Comment by johngodley** [comment]
The current version allows you to match a URL with query parameters and you will need to use that in order to match whatever Facebook adds.

A future version will include additional options to make this easier.

**Comment by johngodley** [comment]
You can put `.*` anywhere you want in the expression.

`^/gainsbourgstories\?fbclid=.*`

Would match all Facebook URLs

**Comment by johngodley** [comment]
I'm confused as to what is working and what isn't? Your source URL does not look like the one I put above, and includes the domain.

**Comment by potoclips** [comment]
Hey John,

Thanks for your feedback.

Yes, I just added the domain as both of them works.

**What is Working**
**1/2** 
Source URL: http://www.potoclips.com/gainsbourgstories
Target URL: http//www.potoclips.com/?s=&category=8638&sort=recent&filter=1
Match: URL Only
When matched: Redirect to URL with HTTP code: 301 - Moved Permanently

- Direct: OK, **Works Fine**

**2/2** 
Source URL: /gainsbourgstories
Target URL: /?s=&category=8638&sort=recent&filter=1
Match: URL Only
When matched: Redirect to URL with HTTP code: 301 - Moved Permanently

- Direct: OK, **Works Fine**

BUT if I try to add any kind of regex to one of theses directions, it doesn't work anymore.

Regards,
Potoman

**Comment by 1balint** [comment]
Hey, I have issues with this as well.

I have created an extra redirect to not mix the normal URL (/pro) and with the wildcarded one (/pro?fbclid=.*)
The second doesn't redirect at all. 
What shall I do?

**Comment by johngodley** [comment]
Please ensure you have the regex checkbox enabled. Also `?` is a regular expression character and will need to be escaped, as shown above.

**Comment by 1balint** [comment]
what do you mean by need to be escaped?
\ do you mean putting this before? I don't have that now

**Comment by johngodley** [comment]
Yes, as shown above.

I'm going to lock this issue as it's not really designed for regular expression support. Please use http://regex101.com to test regular expressions, and see https://redirection.me/support/redirect-regular-expressions/ for details of how to use them in Redirection
