### ISSUE TITLE
How to redirect argument url?

### ISSUE THREAD

**Issue by rvpatel** [johngodley/redirection#125]
Please review this url we wants to redirect on homepage instead of 404 page.

http://www.sitename.com/?cat=6
to 
http://www.sitename.com/

https://wordpress.org/support/topic/how-to-redirect-url-to-homepage-now-go-on-404-page?replies=3#post-8565538

**Comment by johngodley** [comment]
It's a long time since this was posted and somehow I missed it. If you want to redirect an argument then that's entirely possible:

`/?cat=6` => `/`

I will close this as either solved, or no longer needed
