### ISSUE TITLE
404 log is deleted when fixing single redirection

### ISSUE THREAD

**Issue by Joeheg** [johngodley/redirection#1251]
When going through the 404 log, if I check the "delete all logs for this 404" box, it deletes the entire 404 log. 

If i leave the box unchecked, it is fine. I can go and delete the items one by one. 

This has only been occurring over the last 2-3 days. 

I'm using Chrome for Mac Version 70.0.3538.77
Redirection version is 3.6.1 and I'm running on Wordpress.com site.

**Comment by Martynas91** [comment]
I have encountered the same problem after updating ti 3.6.1 version. (Chrome for Windows Version 70.0.3538.77)

**Comment by maddoctor** [comment]
Me to! I add one redirection and check to delete the 404 message and all 404 messages delete!

**Comment by nickwells451** [comment]
Hi, I have exactly the same problem. Please resolve because this plugin is, otherwise, excellent.

**Comment by johngodley** [comment]
Fixed in 36c47535ea04e1d0b401dd33e8e5c0050d69e29c, released in next version.
