### ISSUE TITLE
Redirection breaks the built-in "_wp_old_slug" functionality

### ISSUE THREAD

**Issue by DrLightman** [johngodley/redirection#1259]
### Summary

As you may know when you edit a published post and change the permalink by editing the slug, for example from `article` to `new-article`, Wordpress backups the old slug of that post in wp_postmeta table as:

post_id: `<the post ID>`
meta_key: `_wp_old_slug`
meta_value: `article`

If you load in the browser `http://exampl.org/article/` you'll get a 301 redirect to `http://exampl.org/new-article/`, so that nothing is broken or 404ed.

### Actual Behavior

This works well but after installing Redirection all previously saved old slugs don't work anymore, no more 301 redirect to the newly updated and edited version.

### Steps to reproduce

1 - Setup a vanilla Wordpress
2 - add a new post with permalink /article/ and publish it
3 - edit the post later and change the permalink from "article" to "new-article" and publish it
4 - both /article/ and /new-article/ still work; /article/ will redirect correctly to /new-article/

introducing the bug:

5 - now install and activate Redirection, options don't matter

6 - try again the step 4 and you'll see how /article/ will result in an ugly 404 page not found. **[BUG]**

### Environment

WP 4.9.8 and Redirection 3.6.1

**Comment by johngodley** [comment]
This is expected behaviour and is designed to prevent redirect clashes. If you want to continue using the old redirects you will need to import from the import page.

**Comment by DrLightman** [comment]
Thanks for replying.

I personally don't like the choice since I've never been warned about this break and the mandatory import action upon plugin's activation (I name it quite mandatory since it would cause a SEO damage).

(a) However, I just tried it, the import worked but the source permalinks looks wrong:

![redimpslugs](https://user-images.githubusercontent.com/4699807/48207843-d211ed80-e371-11e8-9e62-feba6081820c.png)

Infact the redirects don't work and need manual tweak to remove those escapes and adding a trailing slash to avoid a 404. The trailing slash also needs to be added otherwise the default WP redirect for canonical fails.

(b) But let's assume they were imported correctly.

With the default WP old slug management, an old /<oldslug>/amp/ url would still redirect to /<editedslug>/amp/ version with no break (tested with https://it.wordpress.org/plugins/amp/ plugin). Instead with Redirection the /oldslug>/ base imported alone doesn't suffice and if you visit /<editedslug>/amp/ you'll get no redirect but a 404 instead.

--

My final suggestion here is for you to strive in order to make the deafult WP behavior and Redirection's one, coexist, for past and future compatibility stuff.

**Comment by johngodley** [comment]
That's a fair point. The plugin has always worked like this and nobody has complained, so the decision has never been revisited.

I'm not able to reproduce the backslash issue, but I'll add something to the next version to remove them anyway.

I am unaware of how the Amp plugin works, but will look at it. It's not the default behaviour of WordPress.

**Comment by LuukvH** [comment]
It would be nice to have _wp_old_slug as a fallback at least, since some plugins write the _wp_old_slug directly. These redirect are then not handled by redirection and result in a 404.

**Comment by dx908** [comment]
Same thing happened with me. I had hundreds of redirects in wp_old_slug which were broken and I had no idea why. There should be atleast some prior warning that this plugin will break them.

I have deactivated the plugin and my previous redirects now work.

**Comment by freeaanzee** [comment]
We just discovered the same unexpected behaviour last week! It would be nice if _wp_old_slug redirections could be re-enabled in an (advanced) option.

**Comment by lucrus73** [comment]
Same here, we need _wp_old_slug to keep working at least as fallback.

**Comment by johngodley** [comment]
This is fixed in 4.6 beta 1, if you want to try it before release:

https://github.com/johngodley/redirection/releases/tag/4.6-beta-1
