### ISSUE TITLE
Redirected pages unindexable by google.

### ISSUE THREAD

**Issue by zandergrin** [johngodley/redirection#1272]
### Summary
We are trying to connect our site to the google search site to index new URLS. It should pick up redirected pages and register the redirection. So `http://mysite.com/oldurl` should register as a 301 redirect in the search console.

### Actual Behavior
Google search console is detecting the redirected pages as un-indexable. When you check a URL with the URL tester it is coming up as `http://mysite.com/oldurl - URL is not available to Google ` because `
Indexing allowed? No: 'noindex' detected in 'robots' meta tag`.

### Steps to reproduce
Can't reproduce because it requires search console access. Maybe change the entire URL structure of a site and check the console!!

### Environment
chrome, redirection 3.6.2, WordPress 4.9.8, Yoast 9.1

Specific example. `https://www.boycehatton.co.uk/c/45/medical-negligence-claims` redirects to `https://www.boycehatton.co.uk/categories/medical-negligence-guides/`  search console results in screenshot.
![snip20181113_17](https://user-images.githubusercontent.com/1317985/48415240-bc6f4000-e744-11e8-8d78-b2e9f205bb69.png)

**Comment by johngodley** [comment]
This would seem to be the problem:

`'noindex' detected in 'robots' meta tag`

**Comment by zandergrin** [comment]
Hi - yes - but where is that coming from? The page doesn't exist - so how does it think there is a noindex in the meta tag?

**Comment by johngodley** [comment]
I don't know. Redirection doesn't do anything with `noindex`, so it must be somewhere else. Also bear in mind that Google can take a few days to properly update

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
