### ISSUE TITLE
Problem starting Redirection 3.6.2

### ISSUE THREAD

**Issue by madawa1** [johngodley/redirection#1276]
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined http://intermart.lk/wp-admin/load-scripts.php?c=1&load%5B%5D=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check&ver=4.9.8 246
```

Plugin: 3.6.2
WordPress: 4.9.8 (single)
PHP: 5.6.38
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
JavaScript: http://intermart.lk/wp-content/plugins/redirection/redirection.js
REST API: http://intermart.lk/wp-json/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details

**Comment by madawa1** [comment]
Thanks it soved
