### ISSUE TITLE
Images no longer redirect

### ISSUE THREAD

**Issue by byronshell** [johngodley/redirection#1277]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

Images were 301 redirecting to other pages. These no longer work and I get 404 pages for the image redirection. The site is https://www.toptenz.net
This is an example of one that doesn't work. DrDre.jpg should redirect to the musical producers page. 
/wp-content/uploads/2011/04/DrDre.jpg
http://www.toptenz.net/top-10-music-producers.php

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

clicking image link takes me to a 404 page instead of assigned 301 redirect.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

All of the redirects are months old and used to work. Now they don't

Explain the steps involved to reproduce the problem

Check out the Redirects and click them. 

Please list your browser, browser version, version of WordPress and Redirection plugin.
Chrome (newest version) 
Wordpress 4.9.8
Redirection:  3.6.3

**Comment by johngodley** [comment]
I'm a little confused by the report, but can you show the redirect you've created?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
