### ISSUE TITLE
Leading forward slash breaking redirection

### ISSUE THREAD

**Issue by mikestopcontinues** [johngodley/redirection#128]
I'm running a dev wordpress install on the most recent version of MAMP on OSX. And I'm using Redirection to add htaccess rules for changed slugs.

When I change a post slug, the plugin adds a new rule beginning with a forward slash. But the rewrite rule only matches when the leading forward slash is removed.

What's going on there?

**Comment by derpoho** [comment]
Same here!

**Comment by johngodley** [comment]
Sorry for the delay in replying, can you give an example?

**Comment by mikestopcontinues** [comment]
Sure. Using htaccess redirects.

Old slug: `/post/post-1`
New slug: `/post/post-2`

Redirection adds a rule redirecting from `/post/post-1`, but it should add `post/post-1` or it doesn't match. Really, I think it should do the opposite. Matches should always have to start with a forward slash.

**Comment by johngodley** [comment]
Thanks. If you are referring to the rules in a .htaccess file then they should already not have the leading slash. What version of Redirection are you using?

**Comment by mikestopcontinues** [comment]
I'm using the most recent version of Redirection with the most recent version of WordPress. That said, I just checked the new redirects made when changing slugs and they worked fine. Maybe @johngodley would be better help. I think my issue's resolved.
