### ISSUE TITLE
Redirects only worked for logged in users

### ISSUE THREAD

**Issue by toomuchpete** [johngodley/redirection#1280]
### Summary

Redirect only works for logged in users. Possibly only for the user that created it.

### Actual Behavior

I created a redirect. It works for me, while I am logged in. If I log out, use a different browser, or use chrome incognito, the redirect does not work.

I was logged in to the blog admin in Chrome when I created the redirect. All tests of the redirect worked just fine. Other users reported that the redirect wasn't working properly.

I tried in incognito mode, only to find that the redirect did not work.

I tried in MS Edge and the redirect did not work. When I then logged into the WP Admin dashboard in Edge, the redirect started working again.

### Environment

 - Chrome and Edge on Windows
 - WP Version 4.9.8
 - Redirection Version 3.6.3

### Configuration for the redirect

![image](https://user-images.githubusercontent.com/407747/48634829-888a5980-e994-11e8-9b74-34a056bf3af9.png)

**Comment by johngodley** [comment]
I'm unable to reproduce this behaviour. Do you have a URL I can test?

**Comment by toomuchpete** [comment]
When I went to look at this, it's now working. I suspect some kind of wp-side caching / user error. Apologies for the false alarm and thanks for the quick reply!
