### ISSUE TITLE
automatic redirection not working in gutenberg

### ISSUE THREAD

**Issue by hosseinfarnia** [johngodley/redirection#1284]
Hi,
Redirection is not fully compatible with gutenberg.
In plugin options I have selected monitor changes to posts, page and trash and I have selected url monitor changes to modified posts. But automatic redirection is not working in gutenberg, although everything is ok in classic editor.

**Comment by johngodley** [comment]
Should be fixed with https://github.com/johngodley/redirection/commit/c95b546b610057efb4dfdc4edb11843c255439da in the next release
