### ISSUE TITLE
Customizing the target URL

### ISSUE THREAD

**Issue by twosg** [johngodley/redirection#1287]
I want to dynamically change the target URL by using code. Currently I have hacked into `/redirection/actions/url.php`, changed the `redirect_to` method to use my basic customization:

`$redirect = wp_redirect( str_replace(["_", "__"],"-",strtolower($target)), $code );`

Is there a filter method I can hook on or a general better way of doing this?

**Comment by johngodley** [comment]
You can use the custom filter option here:

https://redirection.me/support/matching-redirects/

**Comment by twosg** [comment]
Hey thanks for your quick reply, unfortunately I am not 100% sure how to use it. What I want is something like this, instead of providing fixed targets (matched or unmatched via the UI) I need to return the matched URL dynamically:

```
add_filter( 'my_custom_filter', function( $result, $url ) {
  if ( my_custom_logic_has_found_a_target_for_urlParam($url) ) {
    //return true;
    $customUrl = get_my_dynamic_target_url();
    return_or_redirect($customUrl);
  }
  return false;
}, 10, 2 );
```

I assume that $url will be the source URL?
