### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by piogil** [johngodley/redirection#1290]
```
Plugin: 3.6.3
WordPress: 4.9.8 (single)
PHP: 7.2.12
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
JavaScript: http://fm.factorymedical.es/wp-content/plugins/redirection/redirection.js
REST API: http://factorymedical.es/wp-json/

Error: Failed to fetch

Error: Failed to fetch

Error: Failed to fetch
```

I'm getting this error despite following all the suggestions of the plugin to solve it.

I installed it to try to find out a redirection problem on the web. The wp is installed in a subdomain and redirected to the root. There are things like the customizer that does not work, the font-awesome icons do not appear and some other things.

Thanks and best regards
Pío

**Comment by johngodley** [comment]
It's because you have different URLs on your Settings > General page. You can either make them the same, or follow the instructions in the error message about changing the REST API

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
