### ISSUE TITLE
All 404s are deleted when I make a 301 redirect

### ISSUE THREAD

**Issue by ilse1988** [johngodley/redirection#1291]
First of all, thanks for making this awesome plugin! Works really good.

Second, my problem ;). Unfortunately all found 404 errors disappear when I make 1 redirect and hereby choose to remove all 404 errors with this url from the list. What is going wrong here? Normally only the customized URL disappeared from the list.

Thanks in advance and a really nice day today.

Kind regards, Ilse

**Comment by johngodley** [comment]
What version of the plugin are you using?

What are you deleting and from what page? Can you include some screenshots?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
