### ISSUE TITLE
307 temporary redirect

### ISSUE THREAD

**Issue by julianabarnet** [johngodley/redirection#1296]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by julianabarnet** [comment]
Hi, I am rolling out a website page by page. I would like, in the meantime, to temporarily redirect visitors who click on links I'm not ready to show by creating temporary redirects for them to an under construction/info page, and then remove the redirects from each page as I complete them and want to make them public. I have not yet installed the Redirection plugin but have read articles and looked at some tutorials, and while the 307 temporary redirect option is occasionally mentioned I find hardly any info on it, so wanted to be sure this plugin is useful for this purpose. Also, while I think it is the 307 redirect I want, I'd like to verify this, and make sure it is not instead the 302 redirect option, which I assume is available but have not seen mentioned at all in connection with the Redirection plugin. 

I work in Firefox in Wordpress 4.9.8 using Elementor. I would very much appreciate further info about using Redirection in the way I describe. Thanks very much.

**Comment by johngodley** [comment]
You may find the WordPress.org support forums a better place for this kind of support.

You can do a 302 or 307 redirect with Redirection. I can point you to 302 vs 307 information here:

https://stackoverflow.com/questions/2467664/do-i-need-to-use-http-redirect-code-302-or-307

**Comment by julianabarnet** [comment]
Thanks very much. I will do so.
