### ISSUE TITLE
Allowing the role `editor` locks out administrators

### ISSUE THREAD

**Issue by di5abled** [johngodley/redirection#1305]
### Summary

Allowing the role `editor` locks out administrators.

### Actual Behavior

Changing the 'redirection_rule' should respect roles with are higher than this role and also provide them access to the backend.

### Steps to reproduce

Add this filter to your functions.php:
```
add_filter('redirection_role', function($role) {
    return 'editor';
});
```

Visiting `/wp-admin/tools.php?page=redirection.php` results in: "Sorry, you are not allowed to access this page."

### Environment

Newest WordPress and Plugin Version.

**Comment by johngodley** [comment]
User roles have been deprecated in WordPress and no longer work in the same way. You should use a capability from https://codex.wordpress.org/Roles_and_Capabilities. I will update the Redirection documentation
