### ISSUE TITLE
Please add information about how to map 404 errors to a 301 redirect to some target

### ISSUE THREAD

**Issue by COLABORATI** [johngodley/redirection#131]
For gods sake, **please** add some documentation, just some sentences, about how to map all 404 errors to some random page or to some other target, I can not understand how to do it. 
I see in the 404 tab that there are 404s logged and I could add a redirect for that specific 404 _after the fact_ - however I would like to add a redirect for all potential 404, let's say redirect all 404s to a page.
How can this be done? Thank you very much for your attention!

**Comment by johngodley** [comment]
There is no option to do this, and I do not think it would be a good idea. A 404 error is the correct response to return for a page that does not exist. If you redirect these then you are indicating that a page used to exist at that URL, and now exists somewhere else - this is not the meaning same as a 404.
