### ISSUE TITLE
Need to restore the SORT functionality

### ISSUE THREAD

**Issue by twiginteractive** [johngodley/redirection#132]
Still not giving up in the hope that this crucial feature can be restored to this plugin. Cascading rules that you can't sort defeats the whole purpose - PLEASE restore this much-needed feature.

**Comment by johngodley** [comment]
Just a note to say that this feature is coming back soon! Sorry it was removed for so long

**Comment by twiginteractive** [comment]
This is seriously great news John - thanks so much for getting the feature back in!

**Comment by johngodley** [comment]
Added in #268

**Comment by twiginteractive** [comment]
This is great to see in v2.7 and works in a pinch - but may I ask if you plan to bring back the simple drag-and-drop interface to set the Position? 

Even if it were only enabled on individual Group redirect list pages (so you wouldn't have to worry about mixing positions between groups) it would really helpful in quickly updating the priority of regex redirects.

If you say "yes", a crisp $20 donation will be coming your way 👍 

Thanks!

**Comment by twiginteractive** [comment]
Also it looks like we can currently assign the same priority number to multiple redirects in the same group.. which kinda defeats the point? I would think each priority would be unique within the group so we know which order they will be executed in.

also is it 0 > 1 or 1 > 0 in terms of precedence?

**Comment by johngodley** [comment]
Yes, as mentioned in #268 this is just basic support, and eventually it will be replaced by a drag-and-drop UI. The way ordering currently works isn't ideal and I want to try and change this. However, it's a fairly fundamental change that could break things so... it's tricky.

And yes, the value of the position is totally up to you and you can assign the same value if you want to. Remember this is the most basic support so... don't assign the same value if you don't want that 😃 

By the sounds of it you use ordering in a fairly advanced way, probably more so than I originally designed for. If it's ok with you it would be very helpful to have a copy of your redirects (or subset) such that I can test against them and make sure they continue to work the same.

**Comment by twiginteractive** [comment]
@johngodley I sent you an email to your gmail address with some more info.
