### ISSUE TITLE
Redirect does not save

### ISSUE THREAD

**Issue by CedriqueGeense** [johngodley/redirection#1320]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I'm trying to save a Redirect

### Actual Behavior

The message tells me it saved succesfully, but it does not show in the overview. When i check on https://redirect.li/http/ it also not set

### Steps to reproduce

Try to save a redirect

### Environment

Wordpress 4.8.9

**Comment by johngodley** [comment]
Are you running any caching software?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
