### ISSUE TITLE
File in Root Folder of Wordpress Install

### ISSUE THREAD

**Issue by Codyberman** [johngodley/redirection#1325]
Getting this error when trying to use an old redirect as a Pretty Link:

"ERROR: This Pretty Link Slug is already taken. Check to make sure it isn't being used by another pretty link, post, page, category or tag slug. If none of these are true then check to see that this slug isn't the name of a file in the root folder of your wordpress install."

The slug seems to be the name of a file in the root folder of the Wordpress install, but I can't find it anywhere. I reached out to wordpress support, but they couldn't locate it either.

**Comment by johngodley** [comment]
What is a pretty link? Is that a plugin?

**Comment by Codyberman** [comment]
Hi John, 

Yes, Pretty Links is a plugin to disguise affiliate links.

This issue has been resolved. I was able to create a page with the slug name to overwrite the previous redirect and that seemed to work. Thanks for checking this out.
