### ISSUE TITLE
404

### ISSUE THREAD

**Issue by yadavavnish** [johngodley/redirection#1326]
Plugin: 3.6.3
WordPress: 4.9.8 (single)
PHP: 5.4.45
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
JavaScript: http://yadavavnish.com/wp-content/plugins/redirection/redirection.js
REST API: http://yadavavnish.com/wp-json/

**Comment by johngodley** [comment]
I'm not sure what you are reporting, but your REST API does not work:

http://yadavavnish.com/wp-json/

**Comment by yadavavnish** [comment]
How to resolve REST API

**Comment by johngodley** [comment]
I can't provide any help with that as it is specific to your site. The REST API is enabled by default with WordPress, and something on your site is preventing it working. You will need to find out what that is and allow the REST API to work. This will be more important to fix before WordPress 5 arrives as that also uses the REST API
