### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by scott8035** [johngodley/redirection#1327]
Hi. I just installed Redirection, and when I went to configure the settings for the first time I was taken to a page telling me about an error as described below. I cleared the local and Cloudflare cache with no impact on the problem. I'm really hesitant to try disabling all the other plugins unless it's absolutely the last resort.

```
Plugin: 3.6.3
WordPress: 4.9.8 (single)
PHP: 7.1.11
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0 X-Middleton/1
JavaScript: http://www.healthy-holistic-living.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.healthy-holistic-living.com/wp-json/

Error: NetworkError when attempting to fetch resource.

Error: NetworkError when attempting to fetch resource.
```

**Comment by johngodley** [comment]
Closing in favour of https://github.com/johngodley/redirection/issues/1328
