### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by scott8035** [johngodley/redirection#1328]
Hi, me again... I tried everything suggested by the error screen (attached)... To my knowledge, there is no security software blocking anything, I cleared the local Varnish cache and the Cloudflare cache, I disabled all other plugins...nothing seems to be working.

![healthy holistic living com wp json](https://user-images.githubusercontent.com/4405585/49501421-6a4ba700-f838-11e8-82d7-f97171cf94e9.png)
![redirection healthy holistic living wordpress](https://user-images.githubusercontent.com/4405585/49501422-6a4ba700-f838-11e8-85cb-689e735adc57.png)

```
Plugin: 3.6.3
WordPress: 4.9.8 (single)
PHP: 7.1.11
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0 X-Middleton/1
JavaScript: http://www.healthy-holistic-living.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.healthy-holistic-living.com/wp-json/

Error: NetworkError when attempting to fetch resource.

Error: NetworkError when attempting to fetch resource.
```

**Comment by scott8035** [comment]
Hmm, the plot thickens... We're a customer of Ezoic, an online advertising company. Our DNS points to their servers, which retrieve the pages from our origin server over http, add the advertising, and transmit back-and-forth to the user agents via https.

I've inherited this setup, so I'm not 100% up-to-speed with everything yet. I checked the General Settings, and see they are using the "//hostname/pagename/" syntax, which doesn't even pass the WP validation if you try to update it (see screenshot).

Have you run into this kind of setup before, and/or do you have any tips on how to proceed?

![image](https://user-images.githubusercontent.com/4405585/49532164-832c7a80-f881-11e8-8451-223da0e1bfb4.png)

**Comment by johngodley** [comment]
Interesting, I'm surprised that even works!

`//` is used in HTML to indicate 'the same protocol as the current page'. It doesn't really make sense to have it as WordPress site URL, and I think it should be safe to prefix both those URLs with `https:` to turn them into full URLs
