### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jimmyessbee** [johngodley/redirection#1338]
This just happened when I updated to Wordpress 5.0. I'm pretty sure it is related to finding wp-json, but I'm not sure how to fix it. 
```
Plugin: 3.6.3
WordPress: 5.0 (single)
PHP: 7.0.32-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
JavaScript: http://www.montpelier.k12.nd.us/wordpress/wp-content/plugins/redirection/redirection.js
REST API: http://www.montpelier.k12.nd.us/index.php?rest_route=/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/setting/ GET
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/plugin/ GET
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment]
Can you use the new Gutenberg editor without problem?

**Comment by johngodley** [comment]
Your site is blocking all the REST API routes:

http://www.montpelier.k12.nd.us/index.php?rest_route=/

**Comment by jimmyessbee** [comment]
No. I mean, I can use it but I cannot publish it. And I believe that’s because the path to wp-json doesn’t work. Because I’ve not got a lot of time right now, I just disabled it.

And I can dig in further, but I am sure this is because my wordpress install was flubbed a bit from the get go. Now, paths are screwy. And I assumed that is the same problem with redirection.

Thank you.



Jim Bear
Principal and Tech
Montpelier Public School
www.montpelier.k12.nd.us

**Comment by johngodley** [comment]
Yep, it will be the same problem. I will close this for now, but you can reopen if you get any further.
