### ISSUE TITLE
Redirections sometimes fail

### ISSUE THREAD

**Issue by kovy1000** [johngodley/redirection#1341]
Hello

I am trying to set a redirections and it just happens that sometimes the redirections fail. I am not sure why. 

Our page was penalized by google and now i am trying to figure out why. I have narrowed the problem back to our redirections. Because they are not working correctly, the google indexes more pages with same content. Because it happens on same domain, page gets penalized. Although i have many times checked all the redirects, it still seems that sometimes not all redirections are working correctly. Now i am trying to figure out why.

Can someone please help?

Tried to make a check if the plugin is working correctly and i got this:
![zajeta slika](https://user-images.githubusercontent.com/45756581/49725864-0a586480-fc6d-11e8-881d-176d66f8f203.JPG)

**Comment by kovy1000** [comment]
Right now i have also disabled caching the header. 

To describe the issue. We have tried removing /article/ in our URL. developer implemented function that does this but forgot to make 301 redirects. That caused the mess. But after trying to solve the issue, i have made redirects with your plugin. But it still happens that googlebot doesnt recognize the page is redirected. Also when i check redirect it returns me an error. URLs are correct so spelling error is not a problem.

Example:
https://safer-turn.com/honda-shadow-2018-buyers-guide/ 301 redirect to https://safer-turn.com/article/honda-shadow-2018-buyers-guide/

When Google crawls our site it doesn't recognize that one page is redirected so it indexes it.  Which redirect doesnt work happens randomly.. This night the problem was page in example

**Comment by johngodley** [comment]
Ok, so that URL is redirecting correctly. It can take a while for Google to update itself, so you might just be seeing old results. Redirects in Redirection don't stop working unless you change them, or something outside of Redirection causes the change.

What do you mean by disabled caching the header?

**Comment by kovy1000** [comment]
i saw that sometimes the header caching can cause problems. 

yes as i have already said. Redirects work ok, but it happens sometimes that for some strange reason redirect doesnt work.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
