### ISSUE TITLE
Referer missing in 404's export

### ISSUE THREAD

**Issue by Stonetatara** [johngodley/redirection#1342]
Hello, first of all, thank you for this plugin which, in my opinion, is the best redirection plugin on the market.

So, when I export the 404s from the "404" tab, I also want to export the referents / Users agent to be able to process the 404 pages crawled by search engines as a priority.

But in the CSV export, this information is not exported.
Is it a bug or is it just not planned?

My configuration: 
WordPress 4.9.8
Redirection Version 3.6.3

Thank You
Regards

**Comment by SherylHohman** [comment]
How are you exporting 404 errors?  I would like this feature, but I do not see how to do it.  
The Import/Export tab: I only see the ability to export the redirects.  
The 404 tab, does not have an export option that I can see.

**Comment by Stonetatara** [comment]
Hi Sheryl, you have to go to "404" tab, to go down and click the "export" button at the bottom left of the page.

**Comment by johngodley** [comment]
The referrer is already being exported, however user agent was not. Added for next release.
