### ISSUE TITLE
HTML 401 Error - Site behind HTML Basic Auth user/pass

### ISSUE THREAD

**Issue by leftsideways** [johngodley/redirection#1347]
``
Plugin: 3.6.3
WordPress: 5.0 (single)
PHP: 7.2.10-0ubuntu0.18.04.1
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
JavaScript: http://your.websitehere.com/wp-content/plugins/redirection/redirection.js
REST API: http://your.websitehere.com/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/plugin/ GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/setting/ GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
``
### Summary
The site is behind basic authentication and may need a user/pass.

### Actual Behavior
Was setting up your plugin for the first time (thank you!) and the support tab came up. The above paste is the "Important Details" as requested. All three REST API options in the dropdown do not fix this error. The "Magic Fix" button did not work for me. The redirect tester is "Unable to load details". 

### Steps to reproduce
Click on Tools -> Redirection. The error screen appears.

### Environment
See above paste for this information.

Granted my solution is to remove the authentication, but I am working on a "demo copy behind closed doors" and would like to implement my redirects prior to moving the site from behind said "doors". Thank you for the time you have spent on this project, I apprecate it.

christopher

**Comment by johngodley** [comment]
Your REST API is returning a `rest_forbidden` error. This is not related to basic authentication, but is something on your site.

https://redirection.me/support/problems/rest-api/

**Comment by leftsideways** [comment]
I will be launching the site live without any plugin change and we can revisit this then. Thank you for your time, I apprecate your work.

christopher
