### ISSUE TITLE
Redirection Problem

### ISSUE THREAD

**Issue by ampleom** [johngodley/redirection#1348]
Hello, I install this & create one link. It created like "mydomain.com/wp-admin/thekeyword". As you can see it's creating link in /wp-admin & not redirecting to the offer page I selected!!
What to do?﻿
Sorry for my ignorance

**Comment by johngodley** [comment]
What is the redirect you created?

**Comment by ampleom** [comment]
an affiliate link

**Comment by johngodley** [comment]
Can you tell me what the redirect source URL and target URL are? The only way I can provide any help is by knowing what you have done.

**Comment by ampleom** [comment]
please have a look
https://vimeo.com/user71559312/review/307312459/bbe10c737e

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
