### ISSUE TITLE
Redirect with regex or import all url?

### ISSUE THREAD

**Issue by itisme64** [johngodley/redirection#1349]
Hi,

I am trying to redirect a bunch of url and  could import them but there are a lot. Using regex option but can`t get it working

**/abcdef_p_20004.html** >  **/abcdef** where “number” can be any number. So i need to remove all from p till .html

i use 

1. /(.*?)\.html
2. /.$1

_other example_

/ABC_t_*.html
/tag/abc/

works but _t_ can have different numbers

abcdef_t_p3.html > tag/abcdef 

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Well the pages stay in same structure

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
I can't really provide help about regular expressions as it's outside the scope of Redirection.

From a quick look your regular expression will match everything that ends in .html, which I don't think you want. Also, your target doesn't need the `.` (unless you really want a `.` there)

You can use http://regex101.com to test your expressions.

Please ensure you have checked the regex checkbox in Redirection.
