### ISSUE TITLE
Joomla links not redirecting to WP hosting

### ISSUE THREAD

**Issue by Abhinav1606** [johngodley/redirection#1352]
Hi,
I have migrated from Joomla hostgator to WP godaddy
but I am not able to redirect Joomla URL's to WP via Redirection plugin
error is coming as "No input file specified"

Plz help 
site is dreamozone.com

**Comment by johngodley** [comment]
Where is this error? That looks like a generic PHP error and not something related to Redirection?

**Comment by Abhinav1606** [comment]
![image](https://user-images.githubusercontent.com/45877427/50008192-69093f80-ffd9-11e8-9570-5abc68c9712e.png)

this is on all the links of joomla eg.
http://www.dreamozone.com/index.php/privacy-policy is not redirecting to http://www.dreamozone.com/privacy-policy/

**Comment by johngodley** [comment]
Please see https://redirection.me/support/faq/#pdf - it applies here.
