### ISSUE TITLE
can't change the permalink

### ISSUE THREAD

**Issue by davehilgendorf** [johngodley/redirection#136]
the permalink for one of my draft posts was the same as my title, which started with a number 009 followed by some words.  I then decided I wanted the post to only be the number 009 without any words to make it easier for the user to look up the post, but when I changed the permalink it then showed up as 009-2 and I can't get it to be 009.  Tech support at Bluehost thought it might have something to do with my redirection plugin.

**Comment by johngodley** [comment]
The plugin doesn't have any control over your post URLs. WordPress itself will rename a URL if it's the same as an existing one.
