### ISSUE TITLE
just a quick support question really.....

### ISSUE THREAD

**Issue by ripthorn74** [johngodley/redirection#1360]
Apologies if I shouldn't be posting a support question here.

I'm following this guide, https://premium.wpmudev.org/blog/keep-static-site-running-while-building-new-wordpress-site/, to create a new WordPress site and then remove the old static one. Will redirection still work or will I have to update the .htaccess file on the root for the google bots to still find the new pages/pdf etc....

thank you.

**Comment by johngodley** [comment]
Sorry, I can't advise on such a large amount of text from an external site. Redirection needs to be running for redirects to work.

**Comment by johngodley** [comment]
Closing for now, please reopen with a more specific question.
