### ISSUE TITLE
Redirection not working

### ISSUE THREAD

**Issue by ankur-1110** [johngodley/redirection#1362]
Redirection is not working. I am getting 200 response and my wordpress home page loads on hitting the old url instead of seeing a 301 redirect to new url. 
  
-Attaching screenshot of my Redirection url configuration and result of 'Check Direct' test. I have tried deactivating all my other plugins and cleaning browser cache. None of them helped. 

![image](https://user-images.githubusercontent.com/5540409/50369935-7a4ae100-05c3-11e9-9f29-01ad44c967aa.png)

![image](https://user-images.githubusercontent.com/5540409/50369938-8040c200-05c3-11e9-807e-e52e56525ef2.png)

-Old URL: https://getmeroof.com/blog/2018/11/guide-to-understanding-property-score-on-get-me-roof/
-New URL: https://getmeroof.com/blog/guide-to-understanding-property-score-on-get-me-roof/

**Steps to reproduce:**
Step 1: Hit old URL: https://getmeroof.com/blog/2018/11/guide-to-understanding-property-score-on-get-me-roof/
Step 2: Loads blog home page: https://getmeroof.com/blog but the browser URL remains same as old url: https://getmeroof.com/blog/2018/11/guide-to-understanding-property-score-on-get-me-roof/

![image](https://user-images.githubusercontent.com/5540409/50369940-89319380-05c3-11e9-9a03-9f1a9ffca40f.png)

Step 3: Expected 301 redirect url:  https://getmeroof.com/blog/guide-to-understanding-property-score-on-get-me-roof/ doesn't load. 

**Environment**
Chrome Version 71.0.3578.98 (Official Build) (64-bit) on MacOS High Sierra 10.13.6
Wordpress: 4.9.9
Redirection: 3.6.3

**Comment by johngodley** [comment]
You have a server redirect - is there a particular reason you are using this instead of a standard redirect? You will probably find that changing to a standard redirect will fix the problem.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
