### ISSUE TITLE
Network Random Redirects Not Working

### ISSUE THREAD

**Issue by indigiti** [johngodley/redirection#1367]
In Network Random Redirects  Not working.

in Advance redirect Method "When matched = Redirect To random Post Post " Set Redirecting to the wordpress root

www.example.com/test/random
redirect Method "When matched = Redirect To random Post Post " 

![capture](https://user-images.githubusercontent.com/34906944/50452928-1b8abc00-0963-11e9-9d93-ba2eb6024d48.JPG)

Result Log shows
redirection done to 
www.example.com/random-url/

it remove multisite (test).

i am using subdirectory Network

**Comment by johngodley** [comment]
Can you explain the problem more? I don't understand your description.

**Comment by indigiti** [comment]
Yes it is picking random post from site
it is bug in code as said earlier issue found in wordpress Network


www.example.com  main wordpress install
www.example.com/i/ subdirectory configured on   example.com 

so when we try to redirect www.example.com/i/ post to random it should give results like

www.example.com/i/[random-post]  but unfortunately it gives result www.example.com/[random-post]

**Comment by indigiti** [comment]
www.example.com is Main Website and Wordpress Network Activated by Subdirectory Install
www.example.com/i/ 

We activated Redirections on Network

**Comment by indigiti** [comment]
so when we try to redirect www.example.com/i/ post to random it should give results like

www.example.com/i/[random-post] but unfortunately it gives result www.example.com/[random-post]

**Comment by johngodley** [comment]
Ok, so as I said, this is not how the plugin is designed to work and it will pick random posts from the site it is installed on. You have it installed on the main site and so it will pick posts from that site.

**Comment by johngodley** [comment]
I'm going to close this one for now

**Comment by indigiti** [comment]
As you said plugin is designed to work and it will pick random posts from the site it is installed on.

I am saying for Wordpress Network Activated Redirection is pick random posts from that network but redirecting  to main site

exp: 
https://example.com/random/ 
should pick random url from https://example.com/ it is works ok

but when come to network another site


https://example.com/agri/random/  random url is taking url of https://example.com/[random]
not https://example.com/agri[random]

this issue you have to activate wordpress network with 2 or more sites
main site redirection is working fine
but other network site  redirection is not working

**Comment by indigiti** [comment]
Wordpress Network activated on https://example.com/

and Three sites added from network dashboard
https://example.com/agri/
https://example.com/test/
https://example.com/center/

issue apperers in https://example.com/agri/
https://example.com/test/
https://example.com/center/ when we try to redirect random post

when tested on  https://example.com/agri/
it always redirect to https://example.com/[random-url]
instead of  https://example.com/agri/[random-url] 

something for test  https://example.com/test/
it always redirect to https://example.com/[random-url]
instead of  https://example.com/test/[random-url]
