### ISSUE TITLE
Feature request: Allow more settings in import

### ISSUE THREAD

**Issue by kosmiq** [johngodley/redirection#137]
It would be awesome if the plugin would allow us to set more parameters in the CSV that we import.

Like:
- Type of redirect (the HTTP code, 301/302/307)
- Regexp (false/true)
- Match (URL only etc, could be defined with numbers 0-3 for type)
- Action (same here, numbers or similar for wanted action)

And perhaps only enforce source and target URL and default the others to 302, false, URL Only and Redirect to URL.

**Comment by mrjustin** [comment]
If there's a plan to roll this enhancement out in phases, the feature I'd appreciate most is regex support.

**Comment by johngodley** [comment]
CSV exports now have the option of HTTP code and regex flag. There will be a JSON export which exactly matches the data being exported
