### ISSUE TITLE
Redirect subsites

### ISSUE THREAD

**Issue by Igorowytsch** [johngodley/redirection#1371]
Hi there

I have/had several domains with endings like .ch, .de and .at which should redirect to .com.
Now the main domain also does it, but all subsites which Google finds have still for example the .ch ending.

How can I redirect them without adding all separately? Cause my website is a lising service and there are to many pages.

Hope I can handle this somehow more easy.

Thanks in advance
Igorowytsch

**Comment by johngodley** [comment]
Not sure what you mean by adding all separately. You can redirect a server using a server match:

https://redirection.me/support/matching-redirects/#server

**Comment by Igorowytsch** [comment]
Hi John

What I want is to redirect all pages from shishabarguide.ch to shishabarguide.com. Including the subpages like shishabarguide.com/page1 to shishabarguide.com/page1. What I would like to avoid is to add every single page if possible.

That‘s all. 

Regards
Igor

Am 04.01.2019 um 09:53 schrieb John <notifications@github.com>:

Not sure what you mean by adding all separately. You can redirect a server using a server match:

https://redirection.me/support/matching-redirects/#server

**Comment by johngodley** [comment]
Ok, please see the guide above and also https://redirection.me/support/redirect-regular-expressions/
