### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by melblom12345** [johngodley/redirection#1373]
Good Day, after updating the Redirection plugin on our website, non of the redirection works anymore. We can't no longer acces any page of the website and only get the following error page 

````
Not Found
The requested URL /promotions was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request
````

When trying to access the settings of the plugin, I get the following error:

```
Plugin: 3.6.3
WordPress: 4.5.16 (single)
PHP: 5.6.39
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: http://visionsoptical.com/wp-content/plugins/redirection/redirection.js
REST API: Array

Error: Failed to fetch
```

We have tried to deactivate the other plugins but nothing works. Right now, we cannot acces any page of our website other than the home page and this is a big problem.

Can you please advise on what to do. Thank you.

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
