### ISSUE TITLE
Redirection Error when Importing CSV

### ISSUE THREAD

**Issue by dustinpitcher** [johngodley/redirection#1376]
```
Plugin: 3.6.3
WordPress: 5.0.2 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://delta.ar15discounts.com/wp-content/plugins/redirection/redirection.js
REST API: https://delta.ar15discounts.com/wp-json/

Error: Failed to fetch
```

Unable to import.

This was when I tried to import a small CSV file with about 20 redirects. 

I tried changing the extension of the file to txt as that has solved some woocommerce import issues but that didn't help.

I'm getting all green lights on the status page. 

CSV can be found here: https://transfer.sh/rkgQD/redirects-3.csv

**Comment by johngodley** [comment]
Your import is likely being blocked by something on your server. You may find more information here:

https://redirection.me/support/problems/rest-api/

**Comment by dustinpitcher** [comment]
Hey John, happy new year and thank you so much for your response. 


I did refer to that support document when troubleshooting this. I use the rest API myself with custom endpoints for various front-end features and haven't had any issues. I know a couple other plugins are making use of it as well.


I did disable all plugins and switch to the default them when troubleshooting and the problem persisted. I updated permalinks, and manually cleared out all but the essential lines of my htaccess and that didn't help either. 


I'm not getting



rest_forbidden


rest_no_route


or any http error codes. 


Just the "fetch failed" error.


I'm also not getting any errors in my debug.log


I don't know, I'm stumped by this one.

—
Dustin Pitcher

--- original message ---
On January 1, 2019, 1:40 AM PST notifications@github.com wrote:


Your import is likely being blocked by something on your server. You may find more information here:

https://redirection.me/support/problems/rest-api/

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by dustinpitcher** [comment]
You’re really kind to offer that. I happened upon a solution where if I went into a private browser mode it would let me upload once. I tried clearing the cache and stuff previous to that and that didn’t do the trick but once I went incognito it allowed me to upload. Over my head as to why but maybe that will help someone with a similar situation in the future. 


Thanks again for the great plugin and for your time. 

-Dustin

—
Dustin Pitcher

--- original message ---
> Sat, Jan 5 at 11:24 AM, <notifications@github.com> wrote:


> I suspect it's a server configuration issue. Something is stopping the upload from happening, which is probably not triggered by most other situations. If you're willing to give me access to the server then I'd be happy to take a look and see if I can see what's going on.

> —

> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---
