### ISSUE TITLE
tables don't seem to create for multisite.

### ISSUE THREAD

**Issue by Lewiscowles1986** [johngodley/redirection#138]
I Recently helped setup a client on multisite and it seems that whilst the root site can use the plugin, the sub-sites cannot. I'm sure it's only a small change to branch on multisite or not, if so loop over all sites changing blog and setting up the db tables **_n**_ times.

**Comment by Lewiscowles1986** [comment]
working on a PR now, it looks like the test-suite is crashing, even on a clone of your master branch.

```
There was 1 error:
1) FlusherTest::testNothingScheduled
Error: __clone method called on non-object
/tmp/wordpress-tests-lib/includes/testcase.php:232
/tmp/wordpress-tests-lib/includes/testcase.php:98
```

Any help you can offer would help me to push this PR your way. It only uses built-in WordPress functions and a foreach loop I use in another code that's been in production tested for a while now; the rest is all your plugin code.

**Comment by Lewiscowles1986** [comment]
https://github.com/johngodley/redirection/pull/139

**Comment by carloscaro** [comment]
Any solution on this problem? We have installed this plugin under WordPress multisite environment. For the main domain works great, but not on subdirectory multisite network.

**Comment by johngodley** [comment]
This was added in 2.10
