### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by legitdev** [johngodley/redirection#1380]
```
Plugin: 3.4
WordPress: 4.8.8 (single)
PHP: 7.0.28-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: http://www.sourcefurniture.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.sourcefurniture.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/redirect/?orderby=id GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/group/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

Hi, it was working and stop working out of nowhere! Please help  As Soon As Possible!

Thank you!

**Comment by johngodley** [comment]
Please logout and login again

**Comment by legitdev** [comment]
I did and I still having the same issue.


Respectfully,

Roger Reyes
*Web Developer / SEO Specialist*
m: 305.244.7764
w: RogerReyes.net <http://rogerreyes.net/>
<https://www.facebook.com/roger.reyes.927>
<https://www.linkedin.com/in/legitdev/>
<https://www.instagram.com/legitdev/>

**Comment by kbrodhagen-amplify** [comment]
I see the same rest_cookie_invalid_nonce error.  We do have a CDN in front.  Currently we whitelist these cookies:
comment_author_*
comment_author_email_*
comment_author_url_*
state
wordpress_test_cookie
wp-settings-*

Do I need to whitelist another cookie or disable caching on another path?  We currently disable cache on /wp/wp-admin/*

Plugin details:

Plugin: 3.6.3
WordPress: 4.9.7 (single)
PHP: 7.2.13
Browser: Amazon CloudFront
JavaScript: https://www.amplify.com/app/plugins/redirection/redirection.js
REST API: https://www.amplify.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

**Comment by kbrodhagen-amplify** [comment]
@johngodley thanks for the timely response!  It turns out what I had to do was update the CDN (AWS CloudFront in this case) to skip caching on the path /index.php/wp-json/*

I think the part that threw me off at first is the plugin shows "/wp-json/" in the UI but I saw in the Chrome Network inspector that it was calling "/index.php/wp-json/" .  So on my first try I got the path wrong in the CDN configuration.
