### ISSUE TITLE
Rest API error

### ISSUE THREAD

**Issue by youneselazizi** [johngodley/redirection#1381]
Plugin: 3.6.3
WordPress: 5.0.2 (single)
PHP: 7.1.1
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://www.juvasa.com/es/blog/wp-content/plugins/redirection/redirection.js
REST API: https://www.juvasa.com/es/blog/wp-json/

Error: Unexpected token < in JSON at position 0
Raw: <?php/* © 2018 Seolyzer.io */require_once($_SERVER['DOCUMENT_ROOT'].'/seolyzer-5f18ce03cbadd36c2be30ce74895ccbf.php');?>{"settings":{"support":false,"token":"82a620253da999b5485bed43215992f2","monitor_post":0,"monitor_types":[],"associated_redirect":"","auto_target":"","expire_redirect":7,"expire_404":7,"modules":[],"newsletter":false,"redirect_cache":1,"ip_logging":1,"last_group_id":1,"rest_api":0,"https":false,"version":"3.6.3"},"groups":[{"text":"WordPress","value":[{"text":"Redirecciones","value":1},{"text":"Entradas modificadas","value":2}]}],"installed":"\/home\/blog\/","canDelete":true,"post_types":{"post":"Entradas","page":"P\u00e1ginas","tcb_symbol":"Thrive Symbols","trash":"Trash"}}

Error: Unexpected token < in JSON at position 0
Raw: <?php/* © 2018 Seolyzer.io */require_once($_SERVER['DOCUMENT_ROOT'].'/seolyzer-5f18ce03cbadd36c2be30ce74895ccbf.php');?>[{"name":"REST API de WordPress","id":"rest","status":"problem","message":"REST API returned invalid JSON data. This is probably an error page of some kind and indicates it has been disabled - Syntax error (200 - https:\/\/www.juvasa.com\/es\/blog\/wp-json\/)"},{"name":"Rutas de redirecci\u00f3n","id":"routes","status":"problem","message":"La REST API no est\u00e1 funcionando, as\u00ed que las rutas no se comprueban"},{"id":"db","name":"Tablas de la base de datos","status":"good","message":"Est\u00e1n presentes todas las tablas"},{"name":"Grupos v\u00e1lidos","id":"groups","message":"Detectados grupos v\u00e1lidos","status":"good"},{"name":"Grupo de redirecci\u00f3n v\u00e1lido","id":"redirect_groups","message":"Todas las redirecciones tienen un grupo v\u00e1lido","status":"good"},{"name":"Grupo de monitoreo de entradas","id":"monitor","message":"El grupo de monitoreo de entradas es v\u00e1lido","status":"good"},{"name":"Protocolo de portada y el sitio","id":"redirect_url","message":"Portada y sitio son consistentes","status":"good"}]

**Comment by johngodley** [comment]
As the message indicates, there is some bad data in your WordPress REST API:

https://www.juvasa.com/es/blog/wp-json/

If you click on that you will see:

`<?php/* © 2018 Seolyzer.io */require_once($_SERVER['DOCUMENT_ROOT'].'/seolyzer-5f18ce03cbadd36c2be30ce74895ccbf.php');?>`

I don't know what it is, but it should be there.

**Comment by johngodley** [comment]
Closing for now please reopen with more details
