### ISSUE TITLE
Redirection Error on Primary Domain in Wordpress Multi-site Environment

### ISSUE THREAD

**Issue by naumanbilytica** [johngodley/redirection#1383]
Hi,

My Old domain is bilytica.co.za
My new domain is bilyticaafrica.co.za

When i apply redirection , it does not work.I am using following expressions

source: /bilytica.co.za/(.*)
target: /bilyticaafrica.co.za/$1

Please help

**Comment by naumanbilytica** [comment]
Hi,
I tried to use as per your advise but its not working 
Source :
/https://www.bilytica.co.za/(.*)

Target:
/https://www.bilyticaafrica.co.za/$1

Plugin for works for all multi-sites except the primary domain

For example the following works fine . say we have a website www.bilytica.co.za/oldsite and we want to redirect all pages to www.bilytica.co.za/newsite then following expressions works fine 

source : /oldsite/(.*)
target: /newsite/$1

but its not working for primary/main root

**Comment by johngodley** [comment]
Those are still not URLs, and should not have the `/` at the start.

`https://www.bilytica.co.za/(.*)` => `https://www.bilyticaafrica.co.za/$1`

**Comment by johngodley** [comment]
Can you post a screenshot of the redirect? Is bilytica.co.za going through your new WordPress?

**Comment by benique** [comment]
It always creates faulty redirects like this when I try to redirect a domain. I tried many different ways but nothing worked.

```
RewriteCond %{HTTP_HOST} ^**https\://**domain1\.com$ [NC]
RewriteRule .* https://domain2.com/page/ [R=301,L]
```

**Comment by johngodley** [comment]
Domain redirects are not currently supported in htaccess files. I'm going to close this issue as it's gotten off-topic
