### ISSUE TITLE
No route was found 

### ISSUE THREAD

**Issue by elerili** [johngodley/redirection#1384]
Plugin: 3.6.3
WordPress: 5.0.2 (single)
PHP: 7.2.10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
JavaScript: http://hotelantonius.ee/wp-content/plugins/redirection/redirection.js
REST API: http://hotelantonius.ee/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/redirect/17/ POST
Params: {"id":17,"url":"http://hotelantonius.ee/en/menu-item-type/erimenuu/","title":"","regex":false,"match_type":"url","action_type":"url","position":4,"group_id":2,"action_code":301,"action_data":{"url":"http://hotelantonius.ee/en/erimenuu/"}}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment]
Closing for now please reopen with more details
