### ISSUE TITLE
Redirection Error when clicking on import/export link

### ISSUE THREAD

**Issue by 1776Swampfox** [johngodley/redirection#1393]
### Summary

Updated to Redirection3.7. Clicked on the link to import export and was directed to a "something went wrong page". I deleted Cache twice with no change.

### Actual Behavior
Plugin: 3.7
WordPress: 5.0.3 (multi)
PHP: 7.2.6
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
JavaScript: https://burneralert.com/wp-content/plugins/redirection/redirection.js
REST API: https://burneralert.com/wp-json/
Buster: 3.7 === 3.7

TypeError: r is not a function

    in t
    in div
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in Hf
    in t
----------------------------------------------------------------
Error code from firefox browser
TypeError: "r is not a function"
valuehttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:62:228671sahttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:59754uahttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:59551dahttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:63274Xahttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:78872Jahttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:79249Rihttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:85773Nihttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:85153Mihttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:91484Cnhttps://burneralert.com/wp-content/plugins/redirection/redirection.js?ver=3.7-a8cd1180d55c0a52bf8791f84d62b27a:33:30434

Using Firefox browser 62.0.3

Thanks for the help

**Comment by jerry-hudgins** [comment]
I'm seeing this error as well.

![redirection37_error](https://user-images.githubusercontent.com/31598239/51079983-f64abd00-1687-11e9-97f4-c3e89c6f18fd.jpg)

**Comment by findersky** [comment]
me  too  

Plugin: 3.7
WordPress: 5.0.3 (single)
PHP: 5.5.30
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: /wp-content/plugins/redirection/redirection.js
REST API: /wp-json/
Buster: 3.7 === 3.7

TypeError: r is not a function

    in t
    in div
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in Hf
    in t

Error code from Google Chrome browser
![20190113100341](https://user-images.githubusercontent.com/2289549/51080645-a0732500-171a-11e9-949f-74f372e0dedf.jpg)
