### ISSUE TITLE
Redirection error message on all sites after plugin update

### ISSUE THREAD

**Issue by Tribulatio** [johngodley/redirection#1394]
### Summary

I am using Redirection on a dozen of sites, with three different hosting companies, all running 4.9.9 and PHP 7 or above. After updating the plugin, I see an error message on all of them - the same error message on all of them when clicking on Import/export. I tested with several browsers. Some of the sites use WP Rocket, other ones not. But the outcome is the same on all sites.

### Actual Behavior

I get no warning window. I see the issue only when I click on the Import/Export section of the plugin. Otherwise, no warning appears.

On some sites, the update took place without any trouble. On a few other sites, I was asked to upgrade the database. On some sites, in the status section, everything is green. On some other sites, I get the following error messages on the first two lines (exactly the same ones on all sites on which it occurs):
cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received
Problème L’API REST ne fonctionne pas. Les routes n’ont pas été vérifiées.

When clicking on Import/Export, I am getting the following error message (I copy it from one of the sites, one on which everything is green in the status section and on which I do not have WP Rocket; I only hide the URL):

Plugin: 3.7
WordPress: 4.9.9 (single)
PHP: 7.3.0-1+0~20181206202752.23+jessie~1.gbp076afd
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
JavaScript: https://www.......info/wp-content/plugins/redirection/redirection.js
REST API: https://www......info/wp-json/
Buster: 3.7 === 3.7

TypeError: r is not a function

    in t
    in div
    in t

The error message is exactly the same on all sites (except for the URL of the site, obviously).

### Steps to reproduce
Obviously, it cannot be reproduced. I did not do anything, merely updated the plugin the the newest version. It would be interesting to know if other users are having the same issue.

### Environment

I tested on Firefox, Safari, Chromium. 
WP 4.9.9 on all sites.
PHP 7 or above on all sites (between 7.1 and 7.3 depending on the sites).
A majority of the sites using Genesis framework theme, two of them RoughPixels themes, another one another theme.
Hosting with three different companies: WP Serveur (France); SwissCenter (Switzerland); The PrimeHost (USA):

**Comment by johngodley** [comment]
The version was built using the wrong version of a file drag/drop library, and this will be fixed in 3.7.1 (which I will release tomorrow). Thanks for letting me know.

Regarding the sites where you had to upgrade the database, were these upgrading from an older version? This is expected if the version if the database does need to be upgraded.

**Comment by Tribulatio** [comment]
Thank you very much for your prompt answer.

No, I updated all sites from the latest version (I do carefully keep all my plugins up to date). Strangely, it was a warning appearing on the top of the welcome page and asking me to update to version 2.4. I was slightly puzzled, since I could not see how v. 2.4 related to v. 3.7 of the plugin. I assumed it had something to do with a database version, different from the plugin version. The database update itself went smoothly. I felt only perplexed that I was required to conduct it on half the sites, not on the other ones, although they had all the same version of the plugin installed before the upgrade took place. (On some sites, the upgrade was done manually, on other ones automatically, but this was not related.)

Let's hope that the upgrade to 3.7.1 will also solve the yellow boxes in the status section of some of the sites.

Your plugin is wonderful and robust. Thank you very much for your work in maintaining it.

**Comment by suzyo** [comment]
Same, TypeError: r is not a function
`in t
in div
in t`

I second Tribulatio - thanks for the great plugin.

**Comment by matto15** [comment]
Same error for me.

**Comment by johngodley** [comment]
Fixed in f6a102fc2572e0035d693d83708acfb6c891007c
