### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by faygoldkatz** [johngodley/redirection#1395]
Plugin: 3.7
WordPress: 5.0.2 (single)
PHP: 5.6.38-0+deb8u1.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://hungrygoldkatz.com/wp-content/plugins/redirection/redirection.js
REST API: https://hungrygoldkatz.com/wp-json/
Buster: 3.7 === 3.7

TypeError: t.substr is not a function

    in t
    in Connect(t)

**Comment by johngodley** [comment]
Fixed in f6a102fc2572e0035d693d83708acfb6c891007c
