### ISSUE TITLE
Set redirections to /.*

### ISSUE THREAD

**Issue by toyotaruss** [johngodley/redirection#1396]
I set redirections to every user, every ip, basically I can not access wp-admin now.

I have been trying to find a way to modify htaccess to get in but I am either redirected or I get a 500 error.

I am sure someone else has done this but could not find the fix anywhere - please help :)

**Comment by johngodley** [comment]
`/wp-admin/` should never be blocked. Have you tried accessing it directly?

If you want to disable the plugin you can rename the `redirection` directory in your plugins directory.

**Comment by toyotaruss** [comment]
I tried that but didn't clear my cache, that worked easily, thank you. Problem solved in 11 minutes - you rock!
