### ISSUE TITLE
Add x-robots-tag support

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#1399]
Add option to include `x-robots-tag noindex/nofollow` in a redirect.

See https://wordpress.org/support/topic/support-for-x-robots-tag/

**Comment by cdils** [comment]
+1 for this feature.

I use Redirection for affiliate links (i.e. mydomain.com/go/affiliate) and Google is indexing these links. These are considered [thin content](https://www.webfx.com/blog/seo/thin-content/) and Google actively penalizes sites for them.

Is there a plan to add the `noindex/nofollow` feature to the plugin?

**Comment by amarilindra** [comment]
Much needed feature. Been waiting for this option for a very long time.

**Comment by B-e-n-G** [comment]
+1 for this feature

It is really SEO relevant!

**Comment by johngodley** [comment]
Added to the 4.5 beta here:

https://github.com/johngodley/redirection/releases/tag/4.5-beta-1
