### ISSUE TITLE
Redirection not working if sourse URL has a russian-language chars

### ISSUE THREAD

**Issue by Woart** [johngodley/redirection#1401]
Problem: if source URL contains russian language (UTF) chars redirection doesnt work
partialy solved: if replace source URL as urlencoded like /%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D....
then redirections works.

Need to do: apply urlencode()  after submit new rule

**Comment by johngodley** [comment]
Yes, it needs to be manually encoded. Closing in favour of #19
