### ISSUE TITLE
monitor_post initial value appears invalid

### ISSUE THREAD

**Issue by laupow** [johngodley/redirection#1402]
### Summary
The initial saved value of `monitor_post` appears invalid. 

### Actual Behavior

Checking the boxes as shown below is insufficient to start monitoring posts.
<img width="907" alt="screen shot 2019-01-16 at 8 26 11 am" src="https://user-images.githubusercontent.com/6674176/51255720-664b9280-1969-11e9-9ab3-5a0cb0c3cd9e.png">

I must also toggle the dropdown to a different group (like Modified Posts) for the monitoring to start working. 

Then, if I change it back to Redirects (the apparent initial value in the UI), monitoring continues to work. (This is unintuitive)

Toggling the dropdown to a different group causes `monitor_post` to get set in the options array. 

### Steps to reproduce
1) Activate/install plugin
1) In the plugin Options tab, check a couple post types to monitor
1) Save options
1) Open a post and edit a post slug
1) The URL Monitor misses this redirect 👎 
1) In the plugin Options tab, change the URL Monitor Group to anything but its current value.
1) Save options 
1) Edit the post slug again
1) The URL monitor captures this redirect 👍 

### Environment
WordPress 4.9.9
Redirection 3.7.1

**Comment by johngodley** [comment]
Confirmed. Well spotted

**Comment by johngodley** [comment]
Fixed by 5f4e9200d254d0d28accef4b543513af11fed856, released in next version

**Comment by laupow** [comment]
Thanks, @johngodley, for plugin & quick fix!
