### ISSUE TITLE
Conflict with plugin AccessPress Social Pro

### ISSUE THREAD

**Issue by Tribulatio** [johngodley/redirection#1405]
### Summary
I am receiving yellow warnings for the status API Rest WordPress and Redirection Roads on 5 out of 15 websites. After testing, I have discovered there is a conflict with AccessPress Social Pro. When I deactivate it, all lights turn to green.

### Actual Behavior
When checking the status, I was receiving the following error messages on the first two lines of status for five of my fifteen sites:

cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received
API Rest does not work

Using iControlWP, I checked which plugin was installed only on those five sites, and not on the other ones. I saw that it was AccessPress Social Pro. As soon as I deactivated it, everything went back to normal.

I assume that the only solution for me will be to remove AccessPress Social Pro and to find another plugin for replacing it?

**Comment by johngodley** [comment]
This is maybe something that can fixed or worked around. I don't have access to that plugin, but if you had a site with it installed that I could look at I might be able to see what's causing the problem and see if anything can be done.  If that's a possibility then I can be contacted at https://redirection.me/contact/

**Comment by johngodley** [comment]
Fixed in 8f772964cae2af1ec6e7a36c67914a97f3862c37. It wasn't really an issue, more that the testing code was unable to run because of something the other plugin was doing. The next version of Redirection won't show the message. Thanks for the access!
