### ISSUE TITLE
Not Redirecting

### ISSUE THREAD

**Issue by ByronLevey** [johngodley/redirection#1407]
Hi John,

I've setup a redirect using your plugin but it doesn't seem to be redirecting. 

REDIRECT PAGES
I want to redirect this page
http://www.ledtubes.co.za/2015/09/03/why-delamping-with-led-tubes-maximizes-energy-savings/

to this page: 
https://www.clearskyleds.co.za/delamping-fluorescent-tubes-with-less-led-tubes

PLUGIN SETUP IS: 
![redirect](https://user-images.githubusercontent.com/46815208/51386138-1f58cb00-1b2a-11e9-8415-cff52c8ac845.jpg)

CHECKER REPORT: 
![redirect_200](https://user-images.githubusercontent.com/46815208/51386194-46170180-1b2a-11e9-879f-8bba991667c3.jpg)

Please would you help.
Kinds Regards,
Byron

**Comment by johngodley** [comment]
You have created a server redirect. Change the 'match' to just 'URL'

**Comment by ByronLevey** [comment]
Perfect. Thanks John. Have a good weekend mate and thanks for the plugin.
