### ISSUE TITLE
regex doesn't match as expected (with or without trailing slash)

### ISSUE THREAD

**Issue by marcodeppe** [johngodley/redirection#1408]
### Summary

regex doesn't match as expected (with or without trailing slash)

### Goal

https://example.com/oldfolder AND https://example.com/oldfolder/ should redirect to https://example.com/newfolder

### Steps to reproduce

Check Regex
Source URL \/oldfolder\/?
Target URL: /newfolder/

https://example.com/oldfolder gives a 404.
https://example.com/oldfolder/ redirects to https://example.com/newfolder/ as expected.

### Environment

Redirection Plugin 3.7.2.
WordPress Version: 5.0.3
PHP Version: 7.2

**Comment by johngodley** [comment]
This works fine for me. Please clear your browser cache

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
