### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by dariojoffily** [johngodley/redirection#1413]
### Summary

Hello :)
I have five different redirections, two of them are working, but the other three are not, cause they are finding a 200, and not the 301. I've used the redirect tester of cache and it didn't help :/ 
I don't know a lot of coding, so I've printed everything that I could hehe

### Actual Behavior

![captura de tela 2019-01-19 as 18 59 08](https://user-images.githubusercontent.com/46851826/51432346-1563c480-1c1d-11e9-9e0d-367ea30fce4c.png)
![captura de tela 2019-01-19 as 18 59 32](https://user-images.githubusercontent.com/46851826/51432347-1563c480-1c1d-11e9-880b-5f728cf3d342.png)
![captura de tela 2019-01-19 as 18 59 54](https://user-images.githubusercontent.com/46851826/51432345-14cb2e00-1c1d-11e9-9328-400678240de2.png)
![captura de tela 2019-01-19 as 19 00 05](https://user-images.githubusercontent.com/46851826/51432344-14cb2e00-1c1d-11e9-820f-4867c8d511b4.png)
![captura de tela 2019-01-19 as 19 03 36](https://user-images.githubusercontent.com/46851826/51432343-14cb2e00-1c1d-11e9-8aff-92dc4692ac20.png)
![captura de tela 2019-01-19 as 19 03 56](https://user-images.githubusercontent.com/46851826/51432342-14cb2e00-1c1d-11e9-92cd-2b6c6da89390.png)

### Environment

Chrome 71.0.3578.98
WordPress 5.0.3 
Redirection 3.7.2.

Thanks!

**Comment by johngodley** [comment]
I've just tested https:/monnas3.dream.press/2019/01/18/estudio/ and it seems to be redirecting fine. If you use caching in any way then it can prevent redirects being updated until the cache is cleared.

**Comment by dariojoffily** [comment]
Yes, it's working now, but still don't know what happened haha
Thanks anyway, great support :)
