### ISSUE TITLE
Issue with 'Match: URL and WordPress page type' and 404s log

### ISSUE THREAD

**Issue by dademaru** [johngodley/redirection#1414]
Hello,

I need to redirect product 404s (the shop owner often removes old / discontinued products) to product catalog, to avoid 404 errors and related SEO issues.
I've added the REGEX redirect:
```
Source URL: /products/(.*)
Target URL: /products/
```
And chosen 'Match: URL and WordPress page type', which shows:
Page Type: 
> Only the 404 page type is currently supported. Please do not try and redirect all your 404s - this is not a good thing to do.
(I think there is a typo in 'Please do not try _and_ redirect all your 404s').
I need that this redirect only runs when the WP 404 page it's hit and not always, leaving other products reachable.
And it seems to work as expected.

But, after a few days, I've noticed that **404s logging stopped working** at all.

After several attempts I found that the problem was precisely this type of redirect.
The worst thing is that even if you disable this redirect, the 404s log still doesn't work.
The only solution is to remove this redirect rule at all.

I think there is a kind of issue somewhere, because in fact the redirect works as expected, however it creates some problems that I could not identify in the logging of 404 errors.

Is there another way to redirect products not found in the catalog only when it is a 404 error?

Thanks
Davide

**Comment by johngodley** [comment]
Fixed in 1ef00feec9a52c44519757c3f0d5da7d091d2969, thanks. Included in next release.

**Comment by dademaru** [comment]
Thanks @johngodley
