### ISSUE TITLE
Redirection Plugin Error

### ISSUE THREAD

**Issue by XESIVDigital** [johngodley/redirection#1416]
Hello Sir,

I created redirects sometime ago. 

I recently changes host and got an SSL certificate installed.

Looking to delete these 301 redirects. These redirects are still showing up in Screaming Frog when URL is searched

Have tried everything listed on plug-in and still error is persistent.

Below is the message i'm being shown:

Plugin: 3.7.2
WordPress: 4.9.9 (single)
PHP: 7.2.13-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://www.xesivdigital.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.xesivdigital.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/rest-api/ and https://redirection.me/support/problems/cloudflare/ for more details

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
