### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by yshanthipriya** [johngodley/redirection#1417]
Hi 

We are trying to update Redirections plugin to latest version, after updating plugin we are getting following error in settings page. we have tried disabling security plugins, tried logging out and re-login but still did not help,  Can you please look into this?

```
Plugin: 3.7.2
WordPress: 4.9.8 (single)
PHP: 5.6.38
Browser: desktop
JavaScript: /wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/plugin/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/setting/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/rest-api/ and https://redirection.me/support/problems/cloudflare/ for more details

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
