### ISSUE TITLE
Redirects Fail w/ Parameters / UTMs + Are Case Sensitive

### ISSUE THREAD

**Issue by aaronleming** [johngodley/redirection#1419]
Redirects are working just fine when they are used exactly as they were originally created, but if any extra parameters are added or if any characters are capitalized, the redirect goes to 404. I am using 301 redirects.

Examples:
**xxxx.com/redirect-path** - routes to target URL fine
**xxxx.com/Redirect-path** - 404
**xxxx.com/redirect-path?utm_campaign=test** - 404

Ideally the redirect will pass any UTMs appended to the URL and will work no matter what capitalization is used.

I'm not very technical but I know that Shopify's redirects work exactly in the way I expect.

**Comment by johngodley** [comment]
Redirects need to match exactly, including query parameters.

**Comment by johngodley** [comment]
You can use a regular expression to match dynamic parameters:

https://redirection.me/support/redirect-regular-expressions/

Case insensitivity is a feature that will be added in version 4.0, which you can test here:

https://github.com/johngodley/redirection/releases/tag/4.0-alpha-1
