### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by lawrencejohnsons49** [johngodley/redirection#1423]
Happy to provide wp-admin if needed?

Plugin: 3.7.2
WordPress: 4.9.9 (single)
PHP: 7.1.25-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://www.drainstore.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.drainstore.com/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by johngodley** [comment]
Discussed over email
