### ISSUE TITLE
Agent: Not using Redirection Error

### ISSUE THREAD

**Issue by llenny23** [johngodley/redirection#1424]
We have split our existing site onto 2 different websites. They are [www.actor-headshots.co.uk](url) and [www.lumosia.co.uk](url). I am trying to direct a blog post from the original site (from lumosia to actor-headshots).

I am copying the url's from the 2 sites and pasting them into the relevant boxes 

This is from the existing site - https://www.lumosia.co.uk/tim-blore/ which should be redirected to -
https://www.actor-headshots.co.uk/tim-blore/
 
However when I check the redirect I'm getting the following error message

Check redirect for: https://www.lumosia.co.uk/tim-blore/
Expected: 301 to https://www.actor-headshots.co.uk/tim-blore/

Found: 200

Agent: Not using Redirection

Any Ideas?

**Comment by johngodley** [comment]
Are the domains on the same WordPress installation?

**Comment by llenny23** [comment]
No. It's a completely different installation. There are other diverts from the old site (lumosia) to the new site (actor-headshots) which are working fine.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
