### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by edgoldswain** [johngodley/redirection#1427]
```
Plugin: 3.7.2
WordPress: 5.0.3 (single)
PHP: 7.3.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://www.staging.nosweatshakespeare.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.staging.nosweatshakespeare.com/wp-json/

Error: Unexpected token < in JSON at position 0
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/plugin/database/
on this server.<br />
</p>
</body></html>
```
I uninstalled redirection plug into remove all existing redirections, and am now trying to reinstall, but recieving the attached error message:

![redirectio issue](https://user-images.githubusercontent.com/47083390/51802945-11e8c280-2247-11e9-8f6e-fa7395beaa1f.jpg)

I checked with my hosting company who have told me the below. Any ideas on how to resolve?

> We've checked the plugin you've been using and it does not look as a ModSecurity issue by itself.
>
> The issue is caused by a zero length of the JSON request of the plugin.
>
> You should contact the plugin developers for more information about this issue.
>
> Here is the official information that you can provide to them.

Offical error:

```[Sun Jan 27 05:59:45.932389 2019]
ModSecurity: JSON parser error: parse error: premature EOF
[hostname "www.staging.nosweatshakespeare.com"]
[uri "/wp-json/redirection/v1/plugin/database/"]
```

More details:

```
27/Jan/2019:05:59:45 --0600] XE2dMc4uNt1AOHRmgdb7ggAAAeQ 51.6.80.89 54695 67.202.92.16 80
POST /wp-json/redirection/v1/plugin/database/?_wpnonce=XXXX HTTP/1.1                                                                      Host: www.staging.nosweatshakespeare.com
Connection: keep-alive
Content-Length: 0
Origin: http://www.staging.nosweatshakespeare.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
content-type: application/json; charset=utf-8
Accept: /
Referer: http://www.staging.nosweatshakespeare.com/wp-admin/tools.php?pa
ge=redirection.php&sub=options
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
```

```
HTTP/1.1 403 Forbidden
Content-Length: 248
Keep-Alive: timeout=3, max=248
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1                             

Message: JSON parser error: parse error: premature EOF
```

**Comment by johngodley** [comment]
Interesting. It seems that [modsecurity](https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/modsecurity-advanced-topic-of-the-week-json-support/) appears to be trying to validate the JSON in the empty POST, and causing the error.

I'll look at trying to reproduce this.

**Comment by edgoldswain** [comment]
great, ta

**Comment by johngodley** [comment]
Can you try this beta release?

https://github.com/johngodley/redirection/releases/tag/3.7.3-beta-1

I wasn't able to reproduce the ModSecurity issue, but I don't know what configuration your host has. However, I think this version should help.

**Comment by johngodley** [comment]
Closing this on the assumption the problem is fixed.
