### ISSUE TITLE
Are automatic Redirects only supposed to work for WP Posts, but not WP Pages?

### ISSUE THREAD

**Issue by keithkrn** [johngodley/redirection#143]
Is this plugin supposed to automatically create new redirects only for Posts upon modifying their permalinks? Or should it also work for Pages?  The plugin description states, “Automatically add a 301 redirection when a post’s URL changes” -- I'm not sure what that all includes.  

For me, it does seem to work for Posts, but not Pages. I was hoping to get a definite answer on this...

**Comment by jrchamp** [comment]
It looks automatic redirects are only created for non-hierarchical post types. If you look in models/monitor.php can_monitor_post() uses is_post_type_hierarchical(), which disqualifies Pages.

**Comment by richardgabriel** [comment]
Just want to chime in that it would be grand to have an option to monitor Pages as well as Posts.

**Comment by Inglsmit** [comment]
i've commented this line 
`if ( is_post_type_hierarchical( $post->post_type ) ) {
    return false;
 }`
and autoadd work's now.
But what reason block this option? Maybe some bug will reveal?

**Comment by jrchamp** [comment]
Actually, it will probably work just fine because of how WordPress handles automatic slug redirection. Normally the issue would be that if you edited a parent-page, it would need to add entries for all child pages, but as long as the last piece is a valid post slug, it'll redirect you to the canonical URL for that post no matter where it lives now.

**Comment by johngodley** [comment]
Page support will be added in #291

**Comment by ehausen** [comment]
I installed the plugin from wordpress.org a couple of days ago and looking at #291 It looks like it was merged 10 days ago.. But I don't have that functionality I think. Doing something wrong?

**Comment by johngodley** [comment]
It was merged into master here on Github, but is not in 2.7.3 on WordPress.org - it will go out in 2.8
