### ISSUE TITLE
Problem starting Redirection 3.7.2

### ISSUE THREAD

**Issue by cyril31** [johngodley/redirection#1431]
Plugin: 3.7.2
WordPress: 5.0.3 (single)
PHP: 5.6.39-1+ubuntu14.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://ctrteatro.com/wp-content/plugins/redirection/redirection.js
REST API: https://ctrteatro.com/wp-json/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
