### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by kfairris** [johngodley/redirection#1439]
```
Plugin: 3.7.2
WordPress: 5.0.3 (single)
PHP: 7.2.14-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://familylifeblended.com/wp-content/plugins/redirection/redirection.js
REST API: http://familylifeblended.com/index.php?rest_route=/

Error: Failed to fetch
```

**Comment by kfairris** [comment]
I uninstalled the plugin and then reinstalled.  It made me go through the setup again and this time it showed there were "different URLs configured on your Wordpress Settings > General page".  That's when I noticed the site is HTTP, but the line for Javascript is pointing to HTTPS.  I tried updating the settings on the General page and for some reason it's not letting me change it to http://.  The site does not have an SSL.  (I know...bad form!).

![image](https://user-images.githubusercontent.com/8039226/52085700-c26a0580-256a-11e9-88c2-985815f3f303.png)

**Comment by johngodley** [comment]
Saying that, I can see you have the URLs correct in the original message

**Comment by johngodley** [comment]
Yep, confirmed the plugin is incorrectly showing the double colon `::`

Does the 'relative wp-json' option work? I'm not sure why WordPress would prevent you updating the protocol on your settings.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
