### ISSUE TITLE
Add ability to filter post types for automatic redirections on modifcation

### ISSUE THREAD

**Issue by jb510** [johngodley/redirection#144]
We're using Tribe's The Events Calendar (same issue as in #142). It triggers a rename for recurring events, which rather quickly put 50,000 301s into Redirection...  ouch.

I've been clearing them out periodically with SQL commands
```
DELETE FROM `wp_redirection_items` WHERE `url` LIKE '%events%'
```
However, it would be cool to add a filter so we could exclude certain custom post types from being included in that otherwise awesome feature.

**Comment by johngodley** [comment]
I've tried Events Calendar but don't really understand how it's used, and can't recreate the problem. Can you tell me what the redirects are?

**Comment by jb510** [comment]
Setup a recurring event, let TEC run it's update/create routine (happens on cron) to generate recurring events.  I get something that looks like this in Redirection:

https://cloudup.com/ck2I_ymG6VC

I can probably get you access to a dev server (there is a fair bit of custom code on this site, but I don't _think_ it'd be causing this).

**Comment by jb510** [comment]
oops

**Comment by johngodley** [comment]
Thanks! I'll have a try using your description first - hopefully that should do it

**Comment by johngodley** [comment]
Sadly I wasn't able to reproduce the problem. If you're ok with giving me access to your dev server that would probably be the fastest way to track the problem down.

**Comment by jb510** [comment]
Can do.  Trying to figure out how to reach out to get your email address for an account. Can you ping me on WP slack? @jb510?

**Comment by johngodley** [comment]
I missed this when posted. The plugin should no longer create for custom post types unless you tell it do so.
