### ISSUE TITLE
Feature Request: let grouped URLs be sorted by count, then name.

### ISSUE THREAD

**Issue by YesThatAllen** [johngodley/redirection#1444]
### Summary

I'm trying to manage a lot of 404s which have built up over the years. When I use the Group by URL feature, Redirection brilliantly sorts the most frequent to the top.

### Actual Behavior

If I have 20 URLs which have 1 hit, when I go to delete one, the page refreshes and the remaining 19 are re-sorted in an arbitrary fashion.

This causes me to lose place/my train of thought, etc. and makes cleanup hard.

### Desired behavior

When viewing 20 URLs, each with 1 hit, have them sorted alphabetically, so that deleting one doesn't re-shuffle the remaining 19.

### Steps to reproduce

Visit redirection's page.
click 404s
click Group by URL.
View the list, which is sorted by hit count (awesome) and seems to have no secondary sort.

### Environment

Latest chrome for mac, using Wordpress 5.0.3, and Redirection 3.7.2. Hosted on ubuntu 16 under nginx and php7.0.

**Comment by johngodley** [comment]
Added in 5be2b9065b79cddd86d3cd2e1504a8b25f6223e2, will be in the next release
