### ISSUE TITLE
Feature request: Compatibility with AWPCP plugin

### ISSUE THREAD

**Issue by hosseinfarnia** [johngodley/redirection#1447]
Hi,
Would you please consider to add support for [AWPCP](https://wordpress.org/plugins/another-wordpress-classifieds-plugin/) Plugin?
Thanks

**Comment by johngodley** [comment]
In what way would support be added?

**Comment by hosseinfarnia** [comment]
When the title of an ad is changed, it can be redirected to the new title url automatically, like posts and pages.

**Comment by johngodley** [comment]
You can use the hooks described here to create your own support plugin for AWPCP:

https://github.com/johngodley/redirection

This is not something that is suitable for going into the core plugin.
