### ISSUE TITLE
“Fix URL monitor not triggering” in version 2.4.2 - what does this mean?

### ISSUE THREAD

**Issue by keithkrn** [johngodley/redirection#145]
In the changelog for version 2.4.2, one of the changes listed was “Fix URL monitor not triggering” — what does this mean or refer to? What had been malfunctioning and how was it fixed?

We are considering updating to 2.4.2 or later, but want to know first what this is.

**Comment by johngodley** [comment]
Sorry for not responding earlier. Going to close this due to the age
