### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by tbba** [johngodley/redirection#1451]
```
Plugin: 3.7.3
WordPress: 5.0.3 (single)
PHP: 7.2.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0
JavaScript: https://www/plugins/redirection/redirection.js
REST API: https://www/wp-json/

Error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Action: redirection/v1/redirect/?orderby=id&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&&total=69&status=STATUS_IN_PROGRESS&table= GET
Code: 414 Request-URI Too Long
Raw: -no data-
```

**Comment by johngodley** [comment]
Can you describe what you are doing when this happens?

**Comment by tbba** [comment]
I reported it because the plugin asked me to :-)

I think to remember I was jumping back and forth between Redirections/Logs/404....
If I find a reproducible case, I let you know.

I think that was on a website which also hosts itSecuity and Ninja Firewall, in case that help (I think they monitor URI).

If you want to close this, fine with me... I can reopen this any time, if I find a reproducible case.

**Comment by johngodley** [comment]
There have been a few reports of this before, but so far no one has been able to describe the steps involved to reproduce it. I'll close this for now, but if you do trigger it again then please do comment again here - I'd like to be able to fix it!
