### ISSUE TITLE
JSON-Import creates group instead of using mentioned one

### ISSUE THREAD

**Issue by ppc1337** [johngodley/redirection#1458]
### Summary

I try to import URLs for 410-redirects. I figured the format for the import hopefully correctly out, but looks like the importer doesn't import the urls in the mentioned group, but creates everytime a new group.

### Actual Behavior

With every import of my JSON-File a new group is created instead of using the mentioned one.

### Steps to reproduce

Create a JSON-file with the following content:

```
{
    "redirects": [
       {
            "url": "\/in-italien-gibt-es-jetzt-pizza-automaten\/amp\/",
            "action_code": 410,
            "action_type": "error",
            "action_data": "",
            "title": "",
            "match_type": "url",
            "regex": false,
            "group_id": 17,
            "enabled": true
        }
    ]
}
```

### Environment

Redirection 3.7.3
Wordpress 5.0.3

**Comment by johngodley** [comment]
Yes, this is how the plugin works. You will need to move across any redirects to existing groups.

**Comment by ppc1337** [comment]
I really like your plugin, but its "awesome" how fast issues were closed, especially without any well created documentation e.g. how the json-file should look like. Also looks like there is no interest to make it more userfriendly or explain why it is as it is.

**Comment by johngodley** [comment]
I actually do spend a lot of time [writing documentation](https://redirection.me/support/) as well as answering countless support requests (here, on the WordPress.org forums, and by email). This is all done in my free time.

In order to have any time left to develop the plugin I have to reply to issues succinctly and directly. I believe I answered your question with the necessary information. I'm sorry this wasn't awesome enough, but that's how it goes. None of the things you have now brought up were mentioned in the original request.

If you think the plugin can be improved then please do make a feature enhancement request. If there's additional information that can be documented then mention that too.

You can export JSON from the plugin to see the format.

Do remember this is free software.

**Comment by ppc1337** [comment]
Thats what I did: export in JSON and look in the structure. Doing this there are quite a lot of information which are not needed for the import or break the import - and thats what e.g. meant. Why should I provide a group for redirects, when its not used? Sounds like a bug, so I opened an issue (second one after asking a question, which gots also closed immediately with some kind of "it is what it is, live with it"-comment) to let you know. And again, the only thing, which happend is "its how it works"

I know your documentation (as written, I searched a lot for solutions before bothering you), but as you can see: no infos about JSON-import, no info about the structure. And a "do a export" isn't very helpful especially my case showed.

Anyways - I appreciate your work and of course the free time you spend for me and every user, who is working with your awesome plugin. But it should be okay to let you know that the support (or answers or how the answers are provided) very differs.

PS: I don't have to remember its a free software. Pls remember that a free software does not mean nobody can complain about problems or missleading functions. In the end its just feedback which can help you to make it better. On the other hand: if you believe free software should taken by people and everyone has to shut up his mouth ... pls stop making free software. Thats not how it should work, really.

**Comment by johngodley** [comment]
Ok, let's take a step back. It seems I am saying things in a way that you are interpreting wrongly.

At no point have I suggested that anyone has to 'live with it', or that everyone has to shut their mouth. It's not helpful to make these straw man assertions, and it's always better to assume good intentions.

I am trying to state that I have limited time to spend on this project, and that it is not complete. There is a deluge of things to deal with, including writing documentation. It's all a work in progress and, as with any free software (including WordPress itself), you (as a user of the software) need to accept this is the case - it's not perfect, it's not complete, and it may have problems.

Yes it's fine to point out some of these problems and ways to improve it - this is constructive feedback and is the entire reason why issues can be created on Github. However, it's not helpful to complain or expect things to exist. This is not how free software works, and is not constructive feedback.

Regarding your questions. Yes, there is no documentation for the JSON file format. I'm sorry. Maybe one day there will be. And yes, there is data in the format that isn't needed when importing. Maybe one day it will be.

In both cases I closed your tickets with an alternative path forward. It might not be exactly what you wanted, but the tickets were not dismissed out of hand, as you keep suggesting. Again, this is how free software works - you ask a question, I reply saying it's not possible and here's how to work around it.

So, again I'm sorry you feel my responses are not good, or that the plugin doesn't contain everything you need. I am doing the best I can given a limited amount of time. It's always better to assume good intentions, and at no point in this discourse have I intended anything negative. I will assume the same of you.
