### ISSUE TITLE
Redirection Plugin won't redirect: Unable to perform action - bad nonce

### ISSUE THREAD

**Issue by cattig** [johngodley/redirection#146]
Since the upgrade to 2.4.5, the redirection tool won't work - it gives this error:

"Unable to perform action - bad nonce"

I see a lot of complaints about this in the wordpress.org forums, so it appears it may be widespread? 

Thanks for any assistance.

**Comment by johngodley** [comment]
I don't think it is widespread, but equally I know that it affects some people and I haven't been able to reproduce it. If you can consistently reproduce it then please do provide more details

**Comment by johngodley** [comment]
Closing until further details provided

**Comment by True-Design** [comment]
Hi, 

I am now experiencing the same problem. Can you please advise?

**Comment by mhjb** [comment]
Me too
