### ISSUE TITLE
ServiceWorker cause frone-end data update error?

### ISSUE THREAD

**Issue by hawm** [johngodley/redirection#1460]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

PWA(ServiceWorker) may cause front-end data not update. Not sure if the Redirection problem.

### Actual Behavior

When enable "Super Progressive Web Apps" and "Redirection" both, then try update(any CRUD operate) your redirect rule in Redirection after you refresh page nothing to change. The operate do in back-end but not make effect for front-end.

### Steps to reproduce

Enable "Super Progressive Web Apps" and "Redirection" both then update Redirection's rule.

### Environment

Wordpress 5.0.3
Redirection 3.7.3
Super Progressive Web Apps 2.0.2
Chrome Version 72.0.3626.81 (Official Build) (64-bit)

**Comment by johngodley** [comment]
Where is 'Super Progressive Web App'?

**Comment by hawm** [comment]
> Where is 'Super Progressive Web App'?

The Wordpress Plugin https://wordpress.org/plugins/super-progressive-web-apps/

**Comment by johngodley** [comment]
I've tried the plugin and I'm not sure what problem you are seeing. Can you explain it further?

**Comment by hawm** [comment]
Before reproduce the bug I was disable all the other plugins in my WordPress withoud SuperPWA and Redirectin.

And then I open a new incognito windows using Chrome(all extensions are disable).
Login my admin and go `/wp-admin/tools.php?page=redirection.php` to add new redirection 
```
source /foo 
target /bar
group Modified Posts
```
Click add redirection that the redirection will show on the page, its fine when now.

**situation 1**
The next step is do modify the redirection which you just add. For example, I tried delete the redirection which just add, it will disappear on page and notification "Redirection saved" show on the bottom right, now refresh the page then you will found the redirection which you were deleted still exist.

**situation 2**
Refresh page then all redirection you just add will disappear and it will show again after you add new redirection, refresh page make it disapper again that cause a loop.

Not a problem about how many time you refresh and cache, even disable cache on DevTools. And the situation above not happen every time.

After unregister the ServiceWorker for SuperPWA and refresh page(it cause the SW register again), all work fine. But will fall into a loop if you try operate redirection and still using SW.

All seems fine after Disable SuperPWA .

**Comment by johngodley** [comment]
Ok, as mentioned I tried the plugin and couldnt get this to happen. Do you have it set up in a particular way?

What you described usually happens when something is caching the REST API.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
