### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by snowbird** [johngodley/redirection#1462]
```
Plugin: 3.7.3
WordPress: 5.0.3 (single)
PHP: 5.6.35
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: http://www.cazda.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.cazda.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/bulk/redirect/disable/?orderby=id&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&rows=&&total=28&addTop=true&status=STATUS_COMPLETE&table= POST
Params: {"items":"29"}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment]
Can you describe what you were doing to get this error? Can you reproduce it?

**Comment by snowbird** [comment]
Hi,

Never happenned again. If I encounter same error again I will let you know. Thank you.

 

Erhan

 

Kimden: John <notifications@github.com>
Yanıtla: johngodley/redirection <reply@reply.github.com>
Tarih: 8 Şubat 2019 Cuma 23:57
Kime: johngodley/redirection <redirection@noreply.github.com>
Bilgi: Snowbird <erhanas@gmail.com>, Author <author@noreply.github.com>
Konu: Re: [johngodley/redirection] Redirection Error (#1462)

 

Can you describe what you were doing to get this error? Can you reproduce it?

**Comment by snowbird** [comment]
I see same error once again when I disable a few redirection record. Opened new threat. 
I use Multilanguage plug-in, does that affect this plug-in?

**Comment by johngodley** [comment]
How are you deleting? When it happens can you add a screenshot?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
