### ISSUE TITLE
WordPress REST API Issue

### ISSUE THREAD

**Issue by kileyplett** [johngodley/redirection#1463]
Please see the attachment.  Redirection isn't working and I tried changing it to RAW Rest API
<img width="759" alt="screen shot 2019-02-07 at 10 10 34 am" src="https://user-images.githubusercontent.com/47427584/52429228-dd83ca80-2ac0-11e9-9399-0c49e71f80be.png">

**Comment by johngodley** [comment]
Your REST API is returning a 401 error. You may find more information here:

https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
