### ISSUE TITLE
Redirect entire folder using WP Plugin Redirection

### ISSUE THREAD

**Issue by buddman04** [johngodley/redirection#1464]
I am looking to use the WordPress Plugin called "Redirection"
I am looking for the way to redirect anything in a specific path to one locations.

Example: I want any URL with /mobile_usa/ to redirect to the home page:
![image](https://user-images.githubusercontent.com/10285062/52431318-fa76c880-2ad5-11e9-8518-a25203be1645.png)

**Comment by johngodley** [comment]
Please see https://redirection.me/support/redirect-regular-expressions/
