### ISSUE TITLE
Error: Failed to Fetch

### ISSUE THREAD

**Issue by BreMiche123** [johngodley/redirection#1467]
![image](https://user-images.githubusercontent.com/47464666/52510850-53705a80-2bc3-11e9-8984-dbca278a956d.png)

So I'm seeing this page giving me the green light but then when I go to add a redirect it shows this: 

![image](https://user-images.githubusercontent.com/47464666/52510877-6daa3880-2bc3-11e9-8b33-363c26ccfa49.png)

I did check the Force HTTPS box by mistake but went and corrected it. I've already gone through every step to fix this as well, including deleting and re-installing the plugin.

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/rest-api/ for details about REST API problems

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
