### ISSUE TITLE
Problem starting Redirection 3.7.3

### ISSUE THREAD

**Issue by Blacklotis2** [johngodley/redirection#1476]
Plugin: 3.7.3
WordPress: 5.0.3 (single)
PHP: 7.2.9-1+0~20180910100423.5+jessie~1.gbpdaac35
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
JavaScript: https://mangazuki.me/wp-content/plugins/redirection/redirection.js
REST API: https://mangazuki.me/wp-json/

**Comment by johngodley** [comment]
How does this relate to your other issue? https://github.com/johngodley/redirection/issues/1452

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
