### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by mquisao** [johngodley/redirection#1477]
```
Plugin: 3.7.3
WordPress: 4.9.9 (single)
PHP: 7.2.14-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: https://erexpress.wpengine.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.erexpress.com/wp-json/

Error: Failed to fetch
```

John-

Everything is working every well. We just pushed our new site live and while the redirection plugin is working, for some reason the UI is telling us that It's not.

Any Ideas?  We've tried the Magic button and tested the urls and are seeing JSON and the Javascript.

Thanks,
Mark

**Comment by mquisao** [comment]
In addition the tester doesn't work, but live links work when we plug-in to the Browser.

Also including Rest API error

WordPress REST API | Problem cURL error 60: SSL certificate problem: unable to get local issuer certificate
-- | --
Problem REST API is not working so routes not checked
Good All tables present
Good Valid groups detected
Good All redirects have a valid group
Good Post monitor group is valid
Good Site and home are consistent

**Comment by johngodley** [comment]
The first problem is because you have different URLs in your Settings > General - one is the real address and another is a wpengine address. They should probably both be the real address.

The second is because your SSL certificate does not appear to be correct. You can use something like https://www.sslshopper.com/ssl-checker.html to check this.

**Comment by mquisao** [comment]
John-

Thanks for the quick response, we will check-it out.  Great plugin btw, fantastic work.

**Comment by mquisao** [comment]
John-

Regarding Issue 1 above.  If we switch the Wordpress Admin URL to www.erexpress.com from https://erexpress.wpengine.com, that won't affect how the site is working / our DNS resolving to the Wpenging wordpress host?



![image](https://user-images.githubusercontent.com/47568784/52650982-59af5100-2eb9-11e9-9c28-540ae43462e0.png)

**Comment by johngodley** [comment]
The settings have nothing to do with DNS. I haven't used WPEngine so can't say if there is anything special needed there, but as the description says the difference is usually for when you have WordPress in another directory. You can always change things back

**Comment by mquisao** [comment]
John-

That worked. We are good.  Thank you very much.
