### ISSUE TITLE
Problems with redirection's yarn install on Windows

### ISSUE THREAD

**Issue by davidshq** [johngodley/redirection#1478]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I'm trying to edit in PhpStorm the code for the redirection plugin. I ran yarn install but it threw a few errors. Hoping you can help me resolve them.

### Actual Behavior
`"C:\Program Files\nodejs\node.exe" C:\Users\myusername\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js install
yarn install v1.13.0
[1/5] Validating package.json...
warning redirection@3.7.2-beta-1: The engine "wordpress" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning "request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
warning " > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > request-promise@4.2.2" has unmet peer dependency "request@^2.34".
[5/5] Building fresh packages...
[1/2] ⢀ node-sass
error E:\WordPressVC\redirection\node_modules\shared-git-hooks: Command failed.
Exit code: 1
Command: node index.js
Arguments:
Directory: E:\WordPressVC\redirection\node_modules\shared-git-hooks
Output:
Symlinking shared-git-hooks runner in .git/hooks

'sh' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:677
    throw err;
    ^

Error: Command failed: sh -c 'echo ${PATH}'
'sh' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:637:11)
    at execSync (child_process.js:674:13)
    at Object.saveHookRunner (E:\WordPressVC\redirection\node_modules\shared-git-hooks\index.js:26:33)
    at installHooks (E:\WordPressVC\redirection\node_modules\shared-git-hooks\index.js:72:11)
    at Object.<anonymous> (E:\WordPressVC\redirection\node_modules\shared-git-hooks\index.js:89:3)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)

Process finished with exit code 1`

### Steps to reproduce

Run yarn install on a Windows 10 Pro computer. Unsure if this occurs on other Windows versions.

**Comment by davidshq** [comment]
This is what I've found thus far:

1. The [documentation for npm](https://docs.npmjs.com/files/package.json) seems to emphasize using the engines section for specifying the node version as opposed to more generally, though it also seems to hint that it is usable more generally. So I'm guessing this probably gives a warning on all OS'es?
2. sh is *nix specific, but [Git Bash](https://stackoverflow.com/questions/26522789/how-to-run-sh-on-windows-command-prompt) allows one to use a compatible shell.
3. But the Git Bash shell does not include wget.
4. One can use the Windows Subsystem for Linux and get a few steps farther but running the command outputs:
bin/install-wp-tests.sh: line 2: $'\r': command not found
bin/install-wp-tests.sh: line 19: syntax error near unexpected token `$'{\r''
'in/install-wp-tests.sh: line 19: `install_wp() {

And that is as far as I've gotten so far.

**Comment by johngodley** [comment]
Yeah, it's just not designed to run on Windows at all!

**Comment by davidshq** [comment]
I figured. :) I made it pretty far in my comment above, but can't spend any more time on it now, will try to get it running on WSL later.

**Comment by jg314** [comment]
I'm unfortunately having this same issue. I'd love to be able to work on the plugin, but `yarn install` fails for me on Windows. Have there been any updates on Windows support since February? @johngodley, if you have any other suggestions please let me know. Thanks a ton in advance for the help.

**Comment by davidshq** [comment]
Jonathan - I haven't had a chance to work on this further, with WSL 2 I expect this will become significantly easier. At the moment for other development needs I've been using a DO droplet for $5/mo.

**Comment by jg314** [comment]
Thanks Dave, I really appreciate the response. I tried to use WSL (not sure if it was 1 or 2), but unfortunately still got errors. I also tried using `npm install` instead, but that didn't work either.

**Comment by johngodley** [comment]
There haven't been any updates to Windows support. None of the setup that involves MySQL, unit tests, or SVN are needed to build the plugin - this is all purely for releasing to wordpress.org.

**Comment by jg314** [comment]
That's helpful to know @johngodley. Thanks a ton.
