### ISSUE TITLE
Mailchimp plugin not working when Redirection active.

### ISSUE THREAD

**Issue by mavjt** [johngodley/redirection#1479]
### Summary

I have installed a new plugin "Mailchimp for Woocommerce" https://mailchimp.com/integrations/woocommerce/ on a  5.0.3  Wordpress install.  The site already had Redirection on it which I've now updated to 3.7.3

### Actual Behavior

When in the Settings for Mailchimp plugin, any operation that calls out to mailchimp eg setting the API key, produces an error on screen:
Mailchimp says: API Request Error - cURL error 28: Operation timed out after 60001 milliseconds with 0 bytes received

If I disable the Redirection plugin, then the Mailchimp plugin starts to work without issue.  Enabling Redireciton and it breaks again.

**Comment by johngodley** [comment]
I don't really know how to test this. When I install the plugin and enter a dummy API key it shows 401 Unauthorized, which indicates it is connecting to Mailchimp and returning an error.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
