### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by snowbird** [johngodley/redirection#1480]
```
Plugin: 3.7.3
WordPress: 5.0.3 (single)
PHP: 5.6.35
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
JavaScript: http://www.cazda.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.cazda.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/bulk/redirect/delete/?orderby=id POST
Params: {"items":"30"}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/bulk/redirect/disable/?orderby=id POST
Params: {"items":"30,29"}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/rest-api/ for more information.

**Comment by snowbird** [comment]
Hi John,

 

I thing this problem occurs with BWS Multilanguage plug-in. When I switch to different language this error happens. Because it makes language specific domain parameter alteration. For example for English my URL became www.domain.com/en_US/my_english_article

 

Hope this helps investigating the problem.

 

Erhan

 

 

Kimden: John <notifications@github.com>
Yanıtla: johngodley/redirection <reply@reply.github.com>
Tarih: 16 Şubat 2019 Cumartesi 22:13
Kime: johngodley/redirection <redirection@noreply.github.com>
Bilgi: Snowbird <erhanas@gmail.com>, Author <author@noreply.github.com>
Konu: Re: [johngodley/redirection] Redirection Error (#1480)

 

Please see https://redirection.me/support/problems/rest-api/ for more information.

**Comment by johngodley** [comment]
Ok. I don't know how BWS works and have no access to it. It should be easy to test disabling the plugin. If the plugin is causing the problem then you will need to investigate why it is affecting the REST API.

**Comment by snowbird** [comment]
Yeah, I will switch to another Multilanguage plug-in. Disabling or switching back to standard language solves the problem. I’m not a programmer that I cannot investigate how that plug-in works and affects REST API.

 

Plug-in web page is BestWebSoft

I will email them to check their code to correct this. 

 

Thanks

Erhan

 

Kimden: John <notifications@github.com>
Yanıtla: johngodley/redirection <reply@reply.github.com>
Tarih: 17 Şubat 2019 Pazar 10:47
Kime: johngodley/redirection <redirection@noreply.github.com>
Bilgi: Snowbird <erhanas@gmail.com>, Author <author@noreply.github.com>
Konu: Re: [johngodley/redirection] Redirection Error (#1480)

 

Ok. I don't know how BWS works and have no access to it. It should be easy to test disabling the plugin. If the plugin is causing the problem then you will need to investigate why it is affecting the REST API.

**Comment by snowbird** [comment]
Reperted this in  their support page

 

I understand that my page REST API www.cazda.com/wp-json/ becames www.cazda.com/en_US/wp-json/ when continue in English and this page generates 404 error

 

Erhan

 

Kimden: John <notifications@github.com>
Yanıtla: johngodley/redirection <reply@reply.github.com>
Tarih: 17 Şubat 2019 Pazar 10:47
Kime: johngodley/redirection <redirection@noreply.github.com>
Bilgi: Snowbird <erhanas@gmail.com>, Author <author@noreply.github.com>
Konu: Re: [johngodley/redirection] Redirection Error (#1480)

 

Ok. I don't know how BWS works and have no access to it. It should be easy to test disabling the plugin. If the plugin is causing the problem then you will need to investigate why it is affecting the REST API.
