### ISSUE TITLE
How to install the plugin in a programmatic way without going through the back office?

### ISSUE THREAD

**Issue by leopoiroux** [johngodley/redirection#1481]
Hello,
I use the Bedrock distribution of Wordpress and I install all my plugins with composer. Since the last updates, we are obliged to go through the back office to finish the installation of the plugin. Can we run this procedure with a wp-cli command or another method?
Thanks

**Comment by johngodley** [comment]
Yes, there is a wp cli command to setup the database. All the commands are under `redirection`

**Comment by leopoiroux** [comment]
YES !!! thks you very much
