### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by gzuaps** [johngodley/redirection#1483]
Hi,
problem on prod server but not on dev.
Authenticated user hast REST access.
Is the resource local or remote.

Thanks,
GZU

```
Plugin: 3.7.3
WordPress: 5.0.3 (multi)
PHP: 5.4.16
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
JavaScript: https://xxxxxx.anu.edu.au/wp-content/plugins/redirection/redirection.js
REST API: http://xxxxxx.anu.edu.au/index.php?rest_route=/

Error: NetworkError when attempting to fetch resource.
```

**Comment by johngodley** [comment]
You have a http and https URL in your WordPress settings. This is preventing your browser from loading the REST API. If you make them both https then it will work

**Comment by gzuaps** [comment]
Hi John,
Thanks for getting back to me so quickly, I've now got matching https however on this server
https://xxxxxx.edu.au/yoursite.com/?rest_route=/
works, but
https://xxxxxx.anu.edu.au/wp-json/
fails with a 500 internal server error, which may or may not be what is causing the problem?
Regards,
GZU

**Comment by johngodley** [comment]
Have you changed the Redirection REST API option from the default?

**Comment by gzuaps** [comment]
Hi John,
I've got round this by temporarily disabling forced SSL for the admin panel.
Thanks for your help.
Regards,
GZU
