### ISSUE TITLE
CSV Import Problems

### ISSUE THREAD

**Issue by oempire** [johngodley/redirection#1493]
[Book1.zip](https://github.com/johngodley/redirection/files/2876827/Book1.zip)

### Summary

Having problems importing CSV (yoast export), i have tried everything to build the CSV. creating in excel and google docs with no luck,

Even as simple as 2 columns source and target are failing

Ive tried with headers / without header columns, tried building one even in notepad++ 

### Actual Behavior

import, get the message 

Total redirects imported: 0

Double-check the file is the correct format!

### Steps to reproduce

import any CSV even the most simplest

ive uploaded an example with 1 redirect in there

**Comment by johngodley** [comment]
The file uploads perfectly for me. Have you picked a group from the group dropdown? Can you visit the 'support' page and see if any problems are identified?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
