### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by kjetisve** [johngodley/redirection#1494]
Can't get Redirection working on multisite.

```
Plugin: 3.7.3
WordPress: 5.0.3 (multi)
PHP: 7.0.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0
JavaScript: https://nettsteder.regjeringen.no/klsredirection/wp-content/plugins/redirection/redirection.js
REST API: https://nettsteder.regjeringen.no/klsredirection/wp-json/

Error: Cookie nonce er ugyldig (rest_cookie_invalid_nonce)
Action: redirection/v1/redirect/?orderby=id GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce er ugyldig","data":{"status":403}}
```

Tried using the other REST-options.

When checking, I always get the "Not using Redirection" message

Expected: 301 to http://nettsteder.regjeringen.no/klsredirection/testside
Found: 404 to http://nettsteder.regjeringen.no/klsredirection/testside
Agent: Not using Redirection

We've set up a custom 404 page the template is using.
Possible related plugins
Nginx Helper
Redis object cache

**Comment by johngodley** [comment]
Please logout, clear all your caches, and login again

**Comment by kjetisve** [comment]
Hi,
Thanks for getting in touch.
Tried purging cache in WP, logging out, clearing cache in browser, logging in again.
Got this in the Redirection page:

Plugin: 3.7.3
WordPress: 5.0.3 (multi)
PHP: 7.0.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
JavaScript: https://nettsteder.regjeringen.no/klsredirection/wp-content/plugins/redirection/redirection.js
REST API: http://nettsteder.regjeringen.no/klsredirection/index.php?rest_route=/

Error: Failed to fetch
Error: Failed to fetch

**Comment by johngodley** [comment]
Ok, now you have the problem described here:

https://redirection.me/support/problems/rest-api/#url

**Comment by kjetisve** [comment]
Ok, now changed to Default REST in options, and I got only green OK boxes. But it still does not work. Trying a redirection I've set gives me
"Check redirect for: https://nettsteder.regjeringen.no/klsredirection/asd
Expected: 301 to http://nettsteder.regjeringen.no/klsredirection/testside
Found: 404 to http://nettsteder.regjeringen.no/klsredirection/testside
Agent: Not using Redirection"

**Comment by johngodley** [comment]
What other plugins do you have running? It is not correct to have a 404 and a redirect location, so something else on your site is modifying things.

**Comment by soderlind** [comment]
Hi @johngodley. I'm working together with @kjetisve. Did some testing using `curl`, and  found that accessing the url with 2, not one, question marks at the triggers the 301. :-o

We're not using regexp in the "check redirect for" url.
 
Here's the header output from running curl:

`curl -I https://nettsteder.regjeringen.no/klsredirection/asd/\?\?`
 
```bash
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Wed, 06 Mar 2019 12:08:55 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.0.33
X-Frame-Options: SAMEORIGIN
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Location: https://nettsteder.regjeringen.no/klsredirection/asd/
Vary: Origin
```

`curl -v -L https://nettsteder.regjeringen.no/klsredirection/asd/\?\?`

```bash
*   Trying 146.192.221.36...
* TCP_NODELAY set
* Connected to nettsteder.regjeringen.no (146.192.221.36) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=nettsteder.regjeringen.no
*  start date: Feb 28 10:15:38 2019 GMT
*  expire date: May 29 10:15:38 2019 GMT
*  subjectAltName: host "nettsteder.regjeringen.no" matched cert's "nettsteder.regjeringen.no"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /klsredirection/asd/?? HTTP/1.1
> Host: nettsteder.regjeringen.no
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Wed, 06 Mar 2019 11:41:20 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/7.0.33
< X-Frame-Options: SAMEORIGIN
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Location: https://nettsteder.regjeringen.no/klsredirection/asd/
< Vary: Origin
<
* Ignoring the response-body
* Connection #0 to host nettsteder.regjeringen.no left intact
* Issue another request to this URL: 'https://nettsteder.regjeringen.no/klsredirection/asd/'
* Found bundle for host nettsteder.regjeringen.no: 0x7fcdcac01810 [can pipeline]
* Re-using existing connection! (#0) with host nettsteder.regjeringen.no
* Connected to nettsteder.regjeringen.no (146.192.221.36) port 443 (#0)
> GET /klsredirection/asd/ HTTP/1.1
> Host: nettsteder.regjeringen.no
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Wed, 06 Mar 2019 11:41:20 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Powered-By: PHP/7.0.33
< Location: //nettsteder.regjeringen.no/klsredirection/hogan-downloads/
< X-Frame-Options: SAMEORIGIN
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Link: <https://nettsteder.regjeringen.no/klsredirection/wp-json/>; rel="https://api.w.org/"
```

**Comment by johngodley** [comment]
@soderlind those redirects do not appear to occur from Redirection, which identifies itself in the HTTP response with `X-Redirect-Agent`.

I don't know what is causing them, but you can debug further with https://redirection.me/support/problems/why-is-it-redirecting/

Also, looking at the last redirect you have a 404 response in addition to a `Location`:

```
< HTTP/1.1 404 Not Found
< Location: //nettsteder.regjeringen.no/klsredirection/hogan-downloads/
```

I wasn't able to reproduce this, but you shouldn't have a 404 and a `Location` header together. The only time I've seen this is when another plugin is incorrectly adding redirects.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
