### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by fairyangel266** [johngodley/redirection#1497]
My website is on php but the blog of my website is on WordPress and lastly I made some redirection which is working but when I redirect my 
https://www.essaymafia.co.uk/index.php to 
https://www.essaymafia.co.uk/ this one is not working

**Comment by johngodley** [comment]
See https://redirection.me/support/faq/#pdf for problems redirecting .php files

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
