### ISSUE TITLE
PHP notice "Trying to get property 'position' of non-object" since last update

### ISSUE THREAD

**Issue by mundschenk-at** [johngodley/redirection#1504]
### Summary

Since the update to 4.0, the log is full of `Trying to get property 'position' of non-object` PHP notices on the frontend.

### Stacktrace

1. do_action('init')
wp-settings.php:505
2. WordPress_Module->init()
wp-includes/class-wp-hook.php:286
3. Red_Item::get_for_url()
wp-content/plugins/redirection/modules/wordpress.php:108
4. Red_Item::get_old_url()
wp-content/plugins/redirection/models/redirect.php:110
5. usort()
wp-content/plugins/redirection/models/redirect.php:157
6. Red_Item::sort_urls()
Unknown
7. wp-content/plugins/redirection/models/redirect.php:184

### Environment

WordPress 5.1, Redirection 4.0

**Comment by johngodley** [comment]
Did you complete the database upgrade?

**Comment by mundschenk-at** [comment]
Didn't see the admin notice until I checked after your question. The plugin is network activated on a multisite and the admin notices are only displayed on individual sites.

**Comment by johngodley** [comment]
Interesting, thanks. I wasn't aware of the multisite notice situation, and will try and improve that (as well as stop the warnings when running without having upgraded)

**Comment by mundschenk-at** [comment]
Oh, and for large networks, a dedicated WP-CLI command might be helpful.

**Comment by johngodley** [comment]
Upgrades are performed under user control because they can and do fail, and it's in everyone's interest to make this as explicit as possible. However I accept this is not ideal for a large multisite

There is a full set of WP CLI commands, including database upgrading.

**Comment by mundschenk-at** [comment]
Great. Then I think just throwing a Network Admin Notice with that information would be a great multisite enhancement.
