### ISSUE TITLE
List of Redirects has vanished after changing WP theme

### ISSUE THREAD

**Issue by DavidOfDublin** [johngodley/redirection#1514]
Hi there

We have used the Redirection plug in for a few years successfully and had perhaps 30 or more 301 redirects set up. Our site was created in a bespoke theme and we have just switched over to Avada.

Most of the redirects we set up are still functioning, though having switched Theme some stopped working so we went in to Redirection to check/adjust the links. 

However, we discovered two things: first the list of all our redirects had vanished and was completely empty and second, (slap of the wrist) our version of Redirection was out of date and needs updating.

Q- Is it possible to recover the view of all our links? (perhaps they'll come back when we update the plug-in? Should re re-enter them all again?)

(NB Unfortunately we didn't have a record of the plugins as a cvs that we could reload.)

Many thanks in advance, and apology for any cross-posting.. I did hunt through the existing threads but couldn't see this issue elsewhere.

![yikes they ve all gone](https://user-images.githubusercontent.com/48093919/53571637-5080de00-3b61-11e9-9855-9bd6d8796229.JPG)

**Comment by johngodley** [comment]
Based on the screenshot you have no redirects. This could happen if you deleted the plugin, or deleted the redirects. I can't suggest anything that would bring them back if this is the case.

**Comment by DavidOfDublin** [comment]
Hi John

Thanks so much for responding. We do indeed have redirects set up (some of which are now going to the wrong location), they're just no longer visible via the plug-in.

When I try to amend / set-up a new redirect all I'm getting is this error:

![redirect error message](https://user-images.githubusercontent.com/48093919/53882514-6df4f280-400e-11e9-9b29-475d2f06987b.JPG)

Example:

olh.ie/trek   should redirect to: https://olh.ie/fundraising/calendar-of-events/trek-croatia-2019/

but instead redirects to: https://olh.ie/fundraising/calendar-of-events/trek/ (which is last year's link we set up through the plug in)

I'm thinking even if I uninstall and reinstall the plug in, the existing 301's set up would remain active

Any advice / steps I might try here?

Kind regards

**Comment by johngodley** [comment]
What version of the plugin are you using?

**Comment by DavidOfDublin** [comment]
Version 2.4.5

(I've flagged with our developers that 3.7.3 is available but do not have usage rights to update)

Will upgrading resolve the issue do you think?

**Comment by johngodley** [comment]
Yeah, I can't really help with a version that's over 3 years old! If you update then we'll be able to see what the situation is.

**Comment by DavidOfDublin** [comment]
Thanks for the swift response. I'll chase our designers again and will revert if the problem persists

Kind regards
