### ISSUE TITLE
4.0.1 beta.3 solves DB upgrade issues for me

### ISSUE THREAD

**Issue by thomasplevy** [johngodley/redirection#1517]
Just wanted to let you know that I was running into `Index column size too large` attempting to upgrade to 4.0.0 on my dev site. I'm running the plugin on a Pagely's managed WP hosting and they use Amazon Aurora DBs which frequently run into issues like this unless `DYNAMIC_ROW_FORMAT` is enabled.

I didn't look too closely at what the beta does differently than 4.0.0 but I wanted to let you know that I was able to upgrade without issue on the dev site that was having this problem.

Thanks so much <3

**Comment by johngodley** [comment]
Thanks!
