### ISSUE TITLE
Problem starting Redirection 4.0.1

### ISSUE THREAD

**Issue by thriken** [johngodley/redirection#1519]
```
Uncaught ReferenceError: Set is not defined https://gufengmi.com/wp-content/plugins/redirection/redirection.js?ver=4.0.1-894a7909eeb2e5b85bc90a6470e9c6bc 33
```

Plugin: 4.0.1
WordPress: 4.9.9 (single)
PHP: 5.6.36
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.3.4000 Chrome/30.0.1599.101 Safari/537.36
JavaScript: https://gufengmi.com/wp-content/plugins/redirection/redirection.js
REST API: https://gufengmi.com/wp-json/

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any more error details are shown?

**Comment by thriken** [comment]
i change Google chrome ,then it work well.
😀
