### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by TAKatie** [johngodley/redirection#1521]
```
Plugin: 4.0.1
WordPress: 5.1 (single)
PHP: 5.6.39
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
JavaScript: https://www.thinaer.io/wp-content/plugins/redirection/redirection.js
REST API: https://www.thinaer.io/wp-json/

Error: Failed to fetch
```

**Comment by TAKatie** [comment]
Can't upgrade database. Receive "failed to communicate with API" error.

Plugin: 4.0.1
WordPress: 5.1 (single)
PHP: 5.6.39
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
JavaScript: https://www.thinaer.io/wp-content/plugins/redirection/redirection.js
REST API: https://www.thinaer.io/wp-json/

Error: Failed to fetch

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
