### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by shggold** [johngodley/redirection#1527]
Plugin: 4.0.1
WordPress: 5.0.3 (single)
PHP: 7.1.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
JavaScript: https://intheknowcycling.com/wp-content/plugins/redirection/redirection.js
REST API: https://intheknowcycling.com/wp-json/

Error: Unexpected token < in JSON at position 749
Action: redirection/v1/plugin/ GET
Code: 200 OK
Raw: [{"name":"WordPress REST API","id":"rest","status":"good","message":"WordPress REST API is working at https:\/\/intheknowcycling.com\/wp-json\/"},{"name":"Redirection routes","id":"routes","status":"good","message":"Redirection routes are working"},{"id":"db","name":"Database tables","status":"good","message":"All tables present"},{"name":"Valid groups","id":"groups","message":"Valid groups detected","status":"good"},{"name":"Valid redirect group","id":"redirect_groups","message":"All redirects have a valid group","status":"good"},{"name":"Post monitor group","id":"monitor","message":"Post monitor group is valid","status":"good"},{"name":"Site and home protocol","id":"redirect_url","message":"Site and home are consistent","status":"good"}]<br />
<b>Warning</b>:  Error while sending QUERY packet. PID=21450 in <b>/home/dzdyytryayf6/public_html/wp-includes/wp-db.php</b> on line <b>1924</b><br />

**Comment by johngodley** [comment]
You can see the problem at the bottom:

`Warning: Error while sending QUERY packet. PID=21450 in /home/dzdyytryayf6/public_html/wp-includes/wp-db.php on line 1924`

This seems related to your database configuration:

https://stackoverflow.com/questions/30753674/error-while-sending-query-packet

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
