### ISSUE TITLE
Last Access bug after 4.0.1 upgrade

### ISSUE THREAD

**Issue by eslindsey** [johngodley/redirection#1528]
### Summary

I just performed an automatic upgrade through the WordPress interface, from 3.x version to 4.0.1. I performed the automatic database upgrade that Redirection requested. Now my Last Access column is displaying a weird date. Not a big deal, but kind of strange.

![Screen Shot](https://i.imgur.com/zfvEsme.png)

### Actual Behavior

Last Access column displays the date "March 3, 8952" until I visit the link, then the Last Accessed column correctly displays today's date.

### Steps to reproduce

Unknown

### Environment

- Google Chrome Version 72.0.3626.119 (Official Build) (64-bit)
- WordPress 4.9.9
- Redirection Version 4.0.1
- Debian buster/sid
- Server version: Apache/2.4.38 (Debian)
Server built:   2019-01-31T20:54:05
- mysqld  Ver 10.1.37-MariaDB-3 for debian-linux-gnu on x86_64 (Debian buildd-unstable)
- PHP 7.3.2-3 (cli) (built: Feb  8 2019 15:05:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2-3, Copyright (c) 1999-2018, by Zend Technologies

**Comment by johngodley** [comment]
Did you happen to download a backup before updating?

**Comment by eslindsey** [comment]
No, sorry. It's a low-priority personal server so I wasn't taking the usual precautions. Just clicked my way through to get rid of the upgrade notifications.

If the software takes its own backup before upgrades, I can retrieve that for you.

**Comment by johngodley** [comment]
The plugin doesn't make its own backup so there's no way to know what the data was before the upgrade took place. Saying that, the upgrade doesn't touch the last access date at all so I'm not sure why it would suddenly change in such a way.

Still, it's good to know the plugin will be usable in the year 8952!

For the moment it seems like the date will be corrected when next accessed so there's nothing I more I can do other than keep an eye out for other reports. I'll close this for now, but if it happens again please let me know. Thanks for the report

**Comment by eslindsey** [comment]
Hey, I just had the same thing happen when the plugin upgraded my database from 2.4 to 4.0. This time it offered me a backup, and I took it. :)
[redirection-www-dyingcats-com-march-16-2019.json.txt](https://github.com/johngodley/redirection/files/2974019/redirection-www-dyingcats-com-march-16-2019.json.txt)

**Comment by johngodley** [comment]
Ah great, I'll take a look and let you know if I see anything!
