### ISSUE TITLE
CVS Redirection import issues

### ISSUE THREAD

**Issue by MatthieuDara** [johngodley/redirection#1530]
Hello,

First of all, thank you for this amazing plugin which is working really good.

But I have a small issue with the CSV import method.

I've created a CSV file following your instructions. 
When I upload it, the plugin can find my redirection, but my "source URL" are cut at a point.

For example, I have this link : 
https://www.samuiimmobilier.com/index.php?option=com_jea&view=property&id=728:appartement-a-vendre-1-chambre-vue-sur-mer-plai-laem-koh-samui&Itemid=160&lang=fr

And the imported link will be : 
https://www.samuiimmobilier.com/index.php

The plugin doesn't save what's after the index.php chain.

Do you have any ideas why ?

Waiting for your updates.

Thank you in advance for your help.

Regards,

Matthieu

**Comment by hreidco** [comment]
I have the same issue. I have set the default to "Ignore and pass" all query parameters, but none are passed along to the target.
Using Redirection 4.0.1 with a fresh CSV import, WP 5.1, PHP 7.2

**Comment by johngodley** [comment]
@MatthieuDara I wasn't able to reproduce the problem. Can you paste the full line from your CSV file?

@hreidco that sounds like a different problem. Can you create a separate issue with the details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
