### ISSUE TITLE
Why isn't the update feature working?

### ISSUE THREAD

**Issue by karencole37** [johngodley/redirection#1535]
I updated the Redirect plugin recently from the version working up to WordPress 5.0.3 to the one working with 5.1. Then when I checked, the update was gone, and it is only up to 5.0.3 again. I don't understand what happened to my update. What can I do to ensure it makes and keeps the update? I am using Google Chrome browser the latest version. You can email me at karen (at) rainbowriting.com (only one "w" in rainbowriting) Karen S. Cole, Ghost Writer, Inc. rainbowriting.com

**Comment by johngodley** [comment]
Answered by email

**Comment by davegaeddert** [comment]
I'd be curious to hear the answer to this, and think it might be helpful to have it written here in case anybody else comes across it and doesn't have to bug you again! Thanks in advance @johngodley.
