### ISSUE TITLE
I set a redirection for a whole site and cant login to the backend anymore

### ISSUE THREAD

**Issue by Delane** [johngodley/redirection#1542]
Hi. I think I screwed up. I installed the plugin and redirected the whole site (as I wanted).
This results in me not being able to log in to the backend, which I didn't think through.
How can I redirect a whole site EXCEPT the backend?
And how can I gain access again?

**Comment by johngodley** [comment]
You can disable the plugin by renaming it's directory in `wp-content/plugins/direction`.

You can create a 'do nothing' action for the pages you don't want to redirect.

**Comment by Delane** [comment]
I tried, it didnt work. 
I set two "do nothing" rules additionally to the /.* rule.
One for /wp-admin and one for /wp-login.
I still get redirected when using these urls.

**Comment by johngodley** [comment]
Please can you show a screenshot of what you created?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details

**Comment by brasofilo** [comment]
Just letting this here for anyone looking for a solution, I did as John suggested and it works perfectly:

> ![image](https://user-images.githubusercontent.com/1542052/212493542-db4f8bde-44a6-48dc-b326-311a96255a1f.png)
