### ISSUE TITLE
Custom role not redirecting

### ISSUE THREAD

**Issue by studioleland** [johngodley/redirection#1557]
Using latest version of plugin.  I have several custom roles related to Woocommerce pricing options.  The custom roles appear to work for various purposes around the site so far except when I use them for user "role" matching with redirects it doesn't follow the match rule even if that role is applied to user.   Does this allow for multiple roles per user?  Can I enter a comma delimited list of roles in that field?  Any feedback helpful here.  Thank you.

**Comment by johngodley** [comment]
How are you creating a custom role?

It does not allow multiple roles.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
