### ISSUE TITLE
Problems with Redirect

### ISSUE THREAD

**Issue by Nimros1** [johngodley/redirection#1559]
### Summary

I'm trying to redirect from my old WIX url to new WP url.

### Actual Behavior

When checking redirect I get this message:
Check redirect for: http://www.godognashville.com/
Expected: 301 to http://185.225.236.101/~godognas/
Found: 301 to https://www.godognashville.com/
Agent: Not using Redirection

WordPress REST API | Good WordPress REST API is working at http://185.225.236.101/~godognas/wp-json/
-- | --
Good Redirection routes are working
Good All tables present
Good Valid groups detected
Good All redirects have a valid group
Good Post monitor group is valid
Good Site and home are consistent

### Environment

I just cleared my browser cache (Chrome) Using latest version of WP and Version 3.7.3 Redirection plugin.

**Comment by johngodley** [comment]
Your redirect will need to be on Wix, not your new site.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
