### ISSUE TITLE
Redirection Error after update

### ISSUE THREAD

**Issue by divya6893** [johngodley/redirection#1561]
Hello,
kindly provide the support for the plugin, which is not working on the server after the update.

Plugin: 3.7.3
WordPress: 4.9.5 (single)
PHP: 5.4.45
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
JavaScript: https://uat1.lendingkart.com/wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/setting/ GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

What we are tried:
1.Disable security plugins
2. Change default API options.
3. Disable all plugins temporary.
4. All suggested options of plugin guide.

**Comment by divya6893** [comment]
![screenshot-uat1 lendingkart com-2019 03 15-13-01-41](https://user-images.githubusercontent.com/48517523/54415558-996c9100-4722-11e9-8d04-c5840e16e419.png)

**Comment by johngodley** [comment]
Answered via email
