### ISSUE TITLE
Problem starting Redirection 4.1

### ISSUE THREAD

**Issue by ProDevIr** [johngodley/redirection#1565]
Plugin: 4.1
WordPress: 5.1.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: http://www.nabesaman.ir/wp-content/plugins/redirection/redirection.js
REST API: http://www.nabesaman.ir/wp-json/

**Comment by johngodley** [comment]
Please open your browser's developer console and see if any more error details are shown.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
