### ISSUE TITLE
Not working with Nginx

### ISSUE THREAD

**Issue by fabineves** [johngodley/redirection#157]
Since the last update to version 2.5, redirection stopped working.

I have a blog that I have to use Nginx Helper Plugin and since I made the update of redirection to 2.5, all urls returned 404. I disabled Nginx Helper plugin and it worked fine. 

Since I can't leave my website without Nginx Helper plugin, I had to downgrade redirection to 2.4.5. 

Is there anything to fix it?

Thanks in advance.

**Comment by Lewiscowles1986** [comment]
This works on nginx, I'm running it on 2 sites.

**Comment by fabineves** [comment]
If you use a plugin called Nginx helper, all the urls will return 404 with the new version. That's my issue. 
It was working fine before the last update.

**Comment by johngodley** [comment]
I don't use Nginx Helper, and running the plugin alongside Redirection doesn't break my site. I can't see anything obvious that would cause a problem between these two plugins.

The commits are listed here:

https://github.com/johngodley/redirection/commits/master

If it's possible for you to use 'git bisect' to help me locate the commit that caused the issue then it will help me make whatever changes are needed.

**Comment by matt-h** [comment]
I have been having this issue as well. I just tested the commit history and this commit is where it breaks. Anything from then on has the issue.
https://github.com/johngodley/redirection/commit/f44b730d07a8c08832cf8ef7c1f5507a633a2ac3

**Comment by matt-h** [comment]
I see the issue Nginx Helper overrides the wp_redirect function but doesn't return true on success.
https://github.com/rtCamp/nginx-helper/blob/master/nginx-helper.php#L360-L377

**Comment by johngodley** [comment]
Ah, thanks @matt-h that's super helpful!

**Comment by matt-h** [comment]
^ I created that pull request to Nginx Helper which fixes this.

**Comment by fabineves** [comment]
Thanks Matt, I don't understand about this much, so I'm glad you could help the developer.

**Comment by chandra-patel** [comment]
Hi @matt-h @fabineves 

I have released Nginx Helper plugin which address this issue. Please check and let me know if its fine.

Regards,
Chandra

**Comment by fabineves** [comment]
Thank you very much! Everything working fine now!

**Comment by johngodley** [comment]
Thanks everyone, closing this ticket
