### ISSUE TITLE
Regexps with ^ $ getting additional ^$ for nginx (and maybe other formats) export

### ISSUE THREAD

**Issue by samlowry** [johngodley/redirection#1573]
I'm using strict rules for regexps with leading ^ and trailing $. When I export rules for nginx most of them became folded into additional ^ and $. Example:

`rewrite ^^/il-ads\.html\?p=(\d+)$$ /ads-location/il/page/$1/ permanent;`

**Comment by johngodley** [comment]
Yep, this will be fixed in the next version. Thanks
