### ISSUE TITLE
DB upgrade/REST issues with WP_DEBUG enabled

### ISSUE THREAD

**Issue by sporkman** [johngodley/redirection#1575]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Upgrade to 4.1, but run into this on my staging site at other times.

### Actual Behavior

REST handler always returns an error, no matter which of the 3 REST dropdown options I try.

### Steps to reproduce

Enable WP_DEBUG, go to the plugin settings page

### Environment

OS-X Chrome and Safari latest, WP 5.1, Redirection 4.1

My thoughts are that whatever is parsing the REST responses freaks out if there are any PHP "NOTICES".  I figure that given the state of PHP development in WP, it's probably fair to assume a decent amount of sites are throwing "notice" alerts - perhaps ignore a line if it includes that string?

(Unrelated, but the backup function and prompt is awesome and so helpful for big upgrades like this, nice touch!)

Guessing at this based on the debug info the plugin (helpfully!) supplies:

```
Plugin: 4.1
WordPress: 5.1 (single)
PHP: 5.6.40-1+ubuntu16.04.1+deb.sury.org+2+will+reach+end+of+life+in+april+2019
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: http://staging.rf-production.flywheelsites.com/wp-content/plugins/redirection/redirection.js
REST API: http://staging.rf-production.flywheelsites.com/wp-json/

Error: Unexpected token N in JSON at position 1
Action: redirection/v1/group/?per_page=100 GET
Code: 200 OK
Raw: 
Notice: A non well formed numeric value encountered in /www/wp-includes/functions.php on line 265
{"items":[{"id":25,"name":"Multipurpose Furniture","redirects":3,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":24,"name":"Wall Beds","redirects":4,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":23,"name":"Convertible Coffee to Dining Tables","redirects":1,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":22,"name":"Products to Replace Products","redirects":22,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":20,"name":"Bunk Beds","redirects":6,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":19,"name":"Space Saving Furniture","redirects":3,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":18,"name":"Studio Apartments","redirects":1,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":17,"name":"Tables","redirects":12,"module_id":1,"moduleName":"WordPress","enabled":true},{
```

**Comment by johngodley** [comment]
Yes, unfortunately that is one of the many ways that the REST API can be broken. The problem also breaks the API for everything else, including Gutenberg.

Looking for and skipping PHP errors would be a fairly error-prone thing to do, and doesn't really solve the problem - the API is still broken. I think it's better to be up-front about this problem and show it clearly to the user. 

Saying that, I am working on changing the API detection so this kind of situation is more visible, and shows a set of actions to fix it.
