### ISSUE TITLE
Regex checkbox missing

### ISSUE THREAD

**Issue by BackSpaceTech** [johngodley/redirection#1581]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do
- Regex to select all url in a directory

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.
- Message "Remember to enable the "regex" checkbox if this is a regular expression." but there is no checkbox anywhere.

### Steps to reproduce

Explain the steps involved to reproduce the problem
/courses/(.*)

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Latest version of WordPress and plugin off wordpress site.
![Capture](https://user-images.githubusercontent.com/16330741/54790448-4d719d00-4c8a-11e9-89a9-8baaa31f1fee.PNG)

**Comment by johngodley** [comment]
It's now in the dropdown in the right corner. I will update the text

<img width="273" alt="regex" src="https://user-images.githubusercontent.com/1277682/54805328-89970480-4c6e-11e9-9e6a-ab5faf2a5111.png">
