### ISSUE TITLE
REST API is working but Redirection is unable to connect (forbidden)

### ISSUE THREAD

**Issue by bkmacdaddy** [johngodley/redirection#1584]
```
Plugin: 4.1
WordPress: 5.1.1 (single)
PHP: 7.2.15-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: https://dazzling-fun.flywheelsites.com/wp-content/plugins/redirection/redirection.js
REST API: https://dazzling-fun.flywheelsites.com/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

I am able to access https://dazzling-fun.flywheelsites.com/wp-json/ and it appears the API is working. I've used this plugin on hundreds of sites on this same server without issue. The host (Flywheel) is looking into it

**Comment by johngodley** [comment]
Usually this is caused by a security plugin. Are you running anything on this site?

**Comment by bkmacdaddy** [comment]
No security plugin. I tried all the troubleshooting steps, disabled all plugins, tried using the default theme. No joy no matter what I try.

**Comment by johngodley** [comment]
Ok, there's a few things to try:

- The [new 4.2 beta](https://github.com/johngodley/redirection/releases/tag/4.2-beta-1). This has an improved API problem detection, which may help
- Temporarily disable all other plugins and see if that helps

Are you running any language plugins like qTranslate?

**Comment by bkmacdaddy** [comment]
Thanks for your help, @johngodley 

I will try the beta. I already tried disabling all other plugins and even other themes but no luck. Not running any translate plugins either. The site it's on is pretty much a mess - been pieced together over several years and "Frankensteined" a bit, so I'm willing to chalk it up to the site since it's not happening to any other sites on the server.
