### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by GregthewpGuy** [johngodley/redirection#1585]
Hi I had created a over 80 redirects that worked perfectly prior to adding really simple ssl. Below is the code asked to attach. I have not changed the rest api it is in default mode. I am not a tekkie and do not want to endanger my work so far. I had created the .html redirects that worked when my site was not https .  I can access my site without issue but not from any old .html links existing in the Google search results.   

I am using wordfence for security and the redirection plugin.

Below are settings for Really SimpleSSL

![Really_simple_SSL_setings](https://user-images.githubusercontent.com/48858100/54866282-24afdd00-4d48-11e9-8934-227de180a863.png)
 

Here are  error details
```
Plugin: 4.1
WordPress: 5.1.1 (single)
PHP: 7.2.8
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: https://www.your-lawn-care-basics-coach.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.your-lawn-care-basics-coach.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/redirect/?orderby=id GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/group/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```
I realise there maybe a simple solution right in front of me but not being a tech guy I would rather seek out more knowledgeable folks so I can learn from these issues.

TIA

**Comment by johngodley** [comment]
Please logout, clear all your caches, and login again

Please see https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
