### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Damienchrn** [johngodley/redirection#1586]
Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 7.3.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: https://modele-cv.org/wp-content/plugins/redirection/redirection.js
REST API: https://modele-cv.org/wp-json/

Error: Le nonce du cookie n’est pas valide (rest_cookie_invalid_nonce)
Raw: 

{"code":"rest_cookie_invalid_nonce","message":"Le nonce du cookie n\u2019est pas valide","data":{"status":403}}

Error: Le nonce du cookie n’est pas valide (rest_cookie_invalid_nonce)
Raw: 

{"code":"rest_cookie_invalid_nonce","message":"Le nonce du cookie n\u2019est pas valide","data":{"status":403}}

**Comment by johngodley** [comment]
Please logout, clear all your caches, and login again

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
