### ISSUE TITLE
Redirection Error [rest_no_route]

### ISSUE THREAD

**Issue by alordiel** [johngodley/redirection#1591]
```
Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
JavaScript: https://bepf-bg.org/bepf2015/wp-content/plugins/redirection/redirection.js
REST API: https://bepf-bg.org/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```
Hi, I've tried to update the database but this error pop up. I've read you [article](https://redirection.me/support/problems/rest-api/) and disable iThemes security but this didn't helped. The error stayed the same. The I activated it and changed the setting for the REST API to be allowed. Tested the wp-json link and it worked well. One thought though - the page was automatically redirected to `https://bepf-bg.org/wp-json/?lang=en` as the site is using qTranslate-X.

**Comment by alordiel** [comment]
Just to confirm, I have disabled the qTranslate-X and updated the database successfully. Then I activate it again. You can add this to your article as a possible solution to this error. 
Cheers and thanks for the create plugin.

**Comment by johngodley** [comment]
Thanks for posting all the details. How do you have qTranslate configured?

**Comment by alordiel** [comment]
There are the config json file for WP SEO qTranslate X (I'm posting it too as it might have also something to do with the issue.
`
{"vendor":{"plugins/wp-seo-qtranslate-x":"1.0"},
"admin-config":{
"post":{
	"pages":{"post.php":"", "post-new.php":""},
	"forms":{
		"post":{
			"fields":{
				"yoast_wpseo_title":{},
				"yoast_wpseo_focuskw":{},
				"yoast_wpseo_metadesc":{"encode":"{"},
				"yoast_wpseo_metakeywords":{},
				"wpseosnippet_title":{"encode":"display"}
			}
		}
	}
}
,
"edit-tag":{
	"pages":{"edit-tags.php":"action=edit"},
	"forms":{
		"edittag":{
			"fields":{
				"wpseo_title":{},
				"wpseo_desc":{},
				"wpseo_metakey":{},
				"wpseo_canonical":{}
			}
		}
	}
}
}
,
"front-config":{
"all-pages":{
	"filters":{
		"text":{
			"wpseo_title":"20",
			"wpseo_meta":"20",
			"wpseo_metadesc":"20",
			"wpseo_replacements":"20"
		}
	}
}
}
}
`

And here is the  qTranslate-x

`
{"vendor":{"plugins/qtranslate-x":"3.4"},
"admin-config":{
"post":{
	"pages":{"post.php":"", "post-new.php":""},
	"anchors":{"post-body-content":{"where":"first last"}},
	"forms":{
		"post":{
			"fields":{
				"title":{},
				"excerpt":{},
				"attachment_caption":{},
				"attachment_alt":{},
				"view-post-btn":{"encode":"display"},
				"wp-editor-area":{"jquery":".wp-editor-area"},
				"gallery-caption":{"jquery":".gallery-caption", "encode":"none"},
				"wp-caption-text":{"jquery":".wp-caption-text", "encode":"display"}
			}
		},
		"wpbody-content":{
			"fields":{
				"wrap-h1":{"jquery":".wrap h1", "encode":"display"},
				"wrap-h2":{"jquery":".wrap h2", "encode":"display"}
			}
		}
	},
	"js-exec":{"post-exec":{"src":"./admin/js/post-exec.min.js"}}
}
,
"options-general":{
	"preg_delimiter":"#",
	"pages":{"options-general.php":"^(?!.*page=[^=&]+).*$"},
	"forms":{
		"options":{
			"fields":{
				"blogname":{},
				"blogdescription":{},
				"head-title":{"jquery":"head title", "encode":"display"}
			}
		}
	}
}
,
"widgets":{
	"pages":{"widgets.php":""},
	"anchors":{"widgets-right":{"where":"before after"}},
	"forms":{
		"widgets-right":{
			"fields":{
				"widget-title":{"jquery":"input[id^='widget-'][id$='-title']"},
				"widget-text-text":{"jquery":"textarea[id^='widget-text-'][id$='-text']"},
				"in-widget-title":{"jquery":"span.in-widget-title", "encode":"display"}
			}
		}
	},
	"js-exec":{"widgets-exec":{"src":"./admin/js/widgets-exec.min.js"}}
}
,
"edit-tag":{
	"pages":{"term.php":"","edit-tags.php":"action=edit"},
	"forms":{
		"edittag":{
			"fields":{
				"name":{},
				"description":{},
				"parent":{ "encode":"display" }
			}
		}
	},
	"js-exec":{"edit-tag-exec":{"src":"./admin/js/edit-tag-exec.min.js"}}
}
,
"edit-tags":{
	"preg_delimiter":"#",
	"pages":{"edit-tags.php":"^(?!.*action=edit).*$"},
	"anchors":{
		"posts-filter":{"where":"before after"}
	},
	"forms":{
		"addtag":{
			"fields":{
				"tag-name":{},
				"tag-description":{},
				"parent":{"encode":"display"}
			}
		},
		"col-left":{
			"fields":{
				"tagcloud":{"jquery":".tagcloud > a", "encode":"display"}
			}
		},
		"the-list":{
			"fields":{
				"row-title":{"jquery":".row-title", "encode":"display"},
				"description":{"jquery":".description", "encode":"display"}
			}
		}
	},
	"js-exec":{"edit-tags-exec":{"src":"./admin/js/edit-tags-exec.min.js"}}
}
,
"nav-menus":{
	"pages":{"nav-menus.php":"action=edit|menu=\\d+|^$"},
	"anchors":{"menu-to-edit":{"where":"before after"}},
	"forms":{
		"update-nav-menu":{
			"fields":{
				"title":{"jquery":"[id^=edit-menu-item-title-]"},
				"attr-title":{"jquery":"[id^=edit-menu-item-attr-title-]"},
				"description":{"jquery":"[id^=edit-menu-item-description-]"},
				"span.title":{"jquery":"span.menu-item-title", "encode":"display"},
				"link-to-original":{"jquery":".link-to-original >a", "encode":"display"}
			}
		},
		"side-sortables":{
			"fields":{
				"label.title":{"jquery":"label.menu-item-title", "encode":"display"},
				"accordion-section-title":{"jquery":"h3.accordion-section-title", "encode":"display"}
			}
		}
	},
	"js-exec":{"nav-menus-exec":{"src":"./admin/js/nav-menus-exec.min.js"}}
}
,
"all-pages":{
	"filters":{
		"text":{ "admin_title":"20" }
	}
}
}
,
"front-config":{
"all-pages":{
	"filters":{
		"text":{
			"widget_title":"20",
			"widget_text":"20",
			"the_title":"20",
			"category_description":"20",
			"list_cats":"20",
			"wp_dropdown_cats":"20",
			"term_name":"20",
			"get_comment_author":"20",
			"the_author":"20",
			"tml_title":"20",
			"term_description":"20"
		},
		"term":{
			"cat_row":"0",
			"cat_rows":"0",
			"wp_get_object_terms":"0",
			"single_cat_title":"0",
			"single_tag_title":"0",
			"single_term_title":"0",
			"the_category":"0",
			"get_term":"0",
			"get_terms":"0",
			"get_category":"0"
		},
		"url":{
			"author_feed_link":"10",
			"author_link":"10",
			"get_comment_author_url_link":"10",
			"post_comments_feed_link":"10",
			"day_link":"10",
			"month_link":"10",
			"year_link":"10",
			"page_link":"10",
			"post_link":"10",
			"category_link":"10",
			"category_feed_link":"10",
			"tag_link":"10",
			"term_link":"10",
			"the_permalink":"10",
			"feed_link":"10",
			"tag_feed_link":"10"
		}
	}
}
}
}
`
Also the used style for pointing a page language is `?lang=en`. The site is bilingual and the main language is Bulgarian, so all English pages will show  with the suffix above.

**Comment by johngodley** [comment]
Wonderful, thanks! I'll see if I can workaround the problem

**Comment by johngodley** [comment]
I was able to reproduce a similar problem. It is indeed qTranslate, and it is because it is redirecting the REST API to an invalid URL. Looking at qTranslate the plugin has not been updated in a long time, and it may cause other issues.

There's not a lot Redirection can do about this situation, however it should be possible to change the REST API setting in Redirection to something else.
