### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by RB-H** [johngodley/redirection#1592]
```
Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 7.3.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: https://timbamerchant.net/wp-content/plugins/redirection/redirection.js
REST API: https://timbamerchant.net/wp-json/

Error: Failed to fetch
```

![redirection](https://user-images.githubusercontent.com/44923251/54909506-4b098000-4ee2-11e9-9ec5-1ad027a65e18.PNG)

Hi I just wanted to add some redirects. This has happened before intermittently, now it seems to be constant.

**Comment by johngodley** [comment]
Your WordPress URL settings are different and this usually indicates a problem. Please see https://redirection.me/support/problems/rest-api/#url

**Comment by RB-H** [comment]
My url settings are fine but I do have a parked domain in a second
language, connected by WPML. the two sites are .net and .es. This is not
alterable. Are you saying Redirection plugin will not work with this
configuration?

**Comment by johngodley** [comment]
Your screenshot shows timbamerchant.es and timbamerchant.net. Because these are on different domains your browser blocks access, and so Redirection can't continue.

You can try changing the REST API setting as described in step 1 and it may help.

**Comment by RB-H** [comment]
Thanks, that's working now. Can changing from the REST API default have any
side effects?

**Comment by johngodley** [comment]
No, it's the same API so there's no difference other than it may allow it to work around problems such as above.
