### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jarle0db** [johngodley/redirection#1594]
```
Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 7.0.32-1~dotdeb+8.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
JavaScript: https://example.com/wp-content/plugins/redirection/redirection.js
REST API: https://examle.com/wp-json/

Error: Unable to update redirect (57): Unknown column 'match_data' in 'field list'
Raw: {"code":"redirect","message":"Unable to update redirect","data":{"status":400,"error_code":57,"wpdb":"Unknown column 'match_data' in 'field list'"}}
```

Getting this when trying to edit or add new redirect.

None of the redirects are working.

https://www.dropbox.com/s/dvo751d0fo2g7zp/Skjermbilde%202019-03-26%2000.11.31.png?dl=0

**Comment by johngodley** [comment]
Somehow you have upgraded the plugin without it being upgraded. Did you get an upgrade notice? Do you have any caching software on your site?

**Comment by jarle0db** [comment]
Hi John, not sure if there could have been file permission problems when it was upgraded. The database should have been updated.

I have tried to re-install the files, but that did not help.

Could you let me know what I can do to make this work again?

**Comment by johngodley** [comment]
A handful of people have reported the same problem, but I’m having trouble figuring out how the plugin could think it was upgraded, but the database wasn't changed.

If you have the time I’ve released a new beta version here which should help in tracking the problem down. The idea is that you run the upgrade again and send me the plugin’s state before and after.

https://github.com/johngodley/redirection/releases/tag/4.2-beta-1

If you could try these steps:

- Install 4.2 beta as explained in the link
- Export a JSON backup of your redirects and send it to me
- If you have access to phpMyAdmin, export your wp_redirection_items table as a SQL file and send that to me
- Go to the Support page in Redirection and set the database version to 2.4
- Proceed through the upgrade again - this shouldn’t cause any negative affects for your existing data
- If the upgrade works then great, problem solved. If you get the same error then can you export your wp_redirection_items table again and send that to me

I can be contacted at https://redirection.me/contact/

**Comment by jarle0db** [comment]
Thank you John, that fixed it for us :)
