### ISSUE TITLE
Problem starting Redirection 4.1.1

### ISSUE THREAD

**Issue by Alpacorp1** [johngodley/redirection#1597]
Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: http://www.centroholistico.com.co/wp-content/plugins/redirection/redirection.js
REST API: http://www.centroholistico.com.co/wp-json/

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any other errors are shown?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
