### ISSUE TITLE
JSON import does not disable group when "enabled":false is set

### ISSUE THREAD

**Issue by markhm** [johngodley/redirection#1602]
### Summary
When importing a group and its new redirections via Redirection JSON, it seems that the group setting "enabled":false is not (correctly) processed and the group is created "enabled":true. 

I note that setting "enabled":false dóes work for the respective redirects that are part of this group; these are created _strikethrough_ (disabled). 

I assume that this is nót expected behaviour, because it is possible to manually disable the group (which in turn has an effect on the associated redirects, as expected).

### Steps to reproduce
1. Create a JSON import file that with the "enabled": false setting for a particular group, as indicated at the bottom of the following snippet:
```
"groups": [{
        "module_id": 1,
        "name": "Group name",
        "moduleName": "WordPress",
        "id": 50,
        "enabled": false
    }]
```
Full sample file here:
[wordpress_redirection_import.json.txt](https://github.com/johngodley/redirection/files/3007919/wordpress_redirection_import.json.txt)

2. Import the file and observe that the new group is created with "enabled": true. 

### Environment
Redirection plugin v4.1.1 on WordPress version 5.1.1 in Docker on macOS. 
Using Google Chrome on macOS as browser. 

Thanks...!

**Comment by johngodley** [comment]
This will be fixed in the next released version.
