### ISSUE TITLE
MALWARE

### ISSUE THREAD

**Issue by heykymmie** [johngodley/redirection#1603]
Name: Kym
Website: www.heykymmie.com

Steps to Reproduce:
1. Navigate to www.heykymmie.com
2. Click on the first post "Long Road Home"

Actual Result: At first, it will get you to my page but the favicon keeps on spinning until it redirects you to a different website. (There were 3 links and I didn't quite catch them as they seem to have redirections for 3 links) so far, I saw this link "http://thebiggestfavoritemake.com"

Expected Result: I should be able to get redirected to my website page without it redirecting to a different one.

Alternate Solution: So, I was able to pinpoint that your plugin was the one causing this. I tried to open a Support ticket from my hosting provider and we tried to disabled each plugins. 

Once we have enabled all plugins except Redirections, I was able to see my website without problems. Now, I have updated the Redirections plugin to version 4.1.1 and tried to activate it last, and now I am not encountering the problem anymore.

Just want to put this out there to those who may have encountered the same issue.

**Comment by johngodley** [comment]
It sounds like you encountered a bug that was fixed in a later version. Is there any reason you marked this ticket as MALWARE?

**Comment by daniel-barrows** [comment]
This bug report seems like spam.
