### ISSUE TITLE
Redirection - I need at least one Get/Post redirection for the plugin to work

### ISSUE THREAD

**Issue by karencole37** [johngodley/redirection#1605]
I need at least one Get/Post redirect or listing for the plugin to work, it said. How do I do this exactly? I need it step by step, help!

Browser is Google Chrome, latest version, WordPress is latest version and Redirection is latest version as of March 26, 2019.

**Comment by johngodley** [comment]
What problems do you currently have?

**Comment by karencole37** [comment]
Dear John,

Well, the plugin stated that I had to have at least one Get/Post redirect
or whatever it was for the plugin to function properly. That's all I know.

Karen S. Cole
Executive Director
*Ghost Writer, Inc. | Rainbow Writing, Inc. <https://rainbowriting.com/>*
200+ ghosts, editors, marketers, publishing and optioning assistance
services

*425.205.9707 *West Coast Time - Seattle, weekday mornings and evenings
best. Text or leave a message *anytime,* replies within one to three
business day. *DO NOT OPEN ANY ATTACHMENTS OR CLICK ON ANY LINKS NOT
MENTIONED IN THIS EMAIL!*

Click on any of our business links:
*www.rainbowriting.com <https://rainbowriting.com/> *- main website
www.ghost-writer-book.com <https://ghost-writer-book.com/>* - *blog website
www.ghostwriterwriting.com <https://ghostwriterwriting.com/>* - *stories
website

**Comment by johngodley** [comment]
Sure, but is it showing an error? When it displays this message it should show you what is working and what isn't working. What isn't working?

**Comment by karencole37** [comment]
Dear John,

I'm not sure if anything isn't working. I just recell it said something
about how I needed to create at least one Get/Post redirect for the plugin
to work.

Karen S. Cole
Executive Director
*Ghost Writer, Inc. | Rainbow Writing, Inc. <https://rainbowriting.com/>*
200+ ghosts, editors, marketers, publishing and optioning assistance
services

*425.205.9707 *West Coast Time - Seattle, weekday mornings and evenings
best. Text or leave a message *anytime,* replies within one to three
business day. *DO NOT OPEN ANY ATTACHMENTS OR CLICK ON ANY LINKS NOT
MENTIONED IN THIS EMAIL!*

Click on any of our business links:
*www.rainbowriting.com <https://rainbowriting.com/> *- main website
www.ghost-writer-book.com <https://ghost-writer-book.com/>* - *blog website
www.ghostwriterwriting.com <https://ghostwriterwriting.com/>* - *stories
website

**Comment by johngodley** [comment]
If everything is working then you have all you need setup. The plugin handles this for you.
