### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Ushi50** [johngodley/redirection#1611]
```
Plugin: 4.1.1
WordPress: 5.1.1 (single)
PHP: 5.4.45
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
JavaScript: http://ursulanieuwoudt.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.ursulanieuwoudt.com/wp-json/

Error: Failed to fetch
```

**Comment by Ushi50** [comment]
Hi, please forgive me, but I think I am on the wrong site here. The redirect popped up on my site and I tried to do so. but I am not a programmer? Do I need this then please?

**Comment by johngodley** [comment]
Please see this link here and update your WordPress URL settings:

https://redirection.me/support/problems/rest-api/#url

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
