### ISSUE TITLE
Redirection updating database update question:

### ISSUE THREAD

**Issue by lettyskitchen** [johngodley/redirection#1619]
Redirection updating database update question:
Thank you for this plugin.

I updated your Redirection plugin for my Wordpress site from 2.4 to 4.1.1. Before updating my database, I first downloaded the backup from the link. 
Now before I update the database I want to know if I am going need to install that code afterwards and where, or is the backup download just for safety? (I have Vaultpress as backup plugin)

I use Google Chrome Version 72.0.3626.121. I use WP version 5.1.1 and updated to Redirection 4.1.1
Thank you.
Letty

**Comment by johngodley** [comment]
The backup is just a backup in case something goes wrong. If you have VaultPress then that can probably also provide a backup.

**Comment by lettyskitchen** [comment]
Thank you! Make it an awesome day!
Letty

Letty Flatt
lettyflatt@gmail.com

Vegetarian and healthy dessert recipes: www.lettyskitchen.com
Subscribe <http://eepurl.com/KzEtn> to my newsletter.

Follow me on Instagram @lettyskitchen <http://instagram.com/lettyskitchen>
I'm on Twitter @lettyskitchen <https://twitter.com/lettyskitchen>
Pinterest: Letty's Kitchen <https://www.pinterest.com/lettyskitchen/>
And Facebook Letty's Kitchen <https://www.facebook.com/lettyskitchen?ref=hl>
