### ISSUE TITLE
Have a "function" to add a redirection from a theme or plugin

### ISSUE THREAD

**Issue by leopoiroux** [johngodley/redirection#1624]
Hi, is it possible to have a "function" to add a redirection from a theme or plugin? I tried to use "Red_Item::create" but this class does not work outside the back office.
Thank you very much.

**Comment by johngodley** [comment]
All functions are exposed through the WordPress REST API, including creating a redirect

**Comment by leopoiroux** [comment]
Hello,
In my case, it is not very practical to use the REST API. I developed a method that analyzes when I'm on a 404. I have a system that can create an automatic redirection based on the url (based on an external repository). However, in this context, I am not connected to the back office (I am not even in the back office).

But I found the solution. Only the "Red_Group" class is not available in this context. So here is the code I was able to add to my plugin.

```
$params = [
    'url' => $url,
    'match_url' => $match_url,
    'group_id' => $group_id,
    'last_access' => gmdate('Y-m-d H:i:s'),
    'action_type' => 'url',
    'action_code' => 301,
    'action_data' => [
        'url' => $action_data
    ],
    'match_type'  => 'url',
];

include WP_PLUGINS_DIR . '/redirection/models/group.php';
Red_Item::create($params);
```

Have a good day
