### ISSUE TITLE
Trouble with unicode dashes

### ISSUE THREAD

**Issue by daniel-barrows** [johngodley/redirection#1625]
I have a redirect to replace a string containing "-–-" aka "-%E2%80%93-". The redirect is not functioning at all; I'm just getting a 404 at the target page with no redirection happening.

It's possible that it isn't working for some other reason, but I don't see another reason why.

### Environment

Firefox 66.0.2
WordPress 5.1.1
Redirection 4.1.1

**Comment by johngodley** [comment]
Have you URL encoded the dash in the redirect source? Currently you need to do this manually, although the 4.3 alpha does this automatically:

https://github.com/johngodley/redirection/releases/tag/4.3-alpha-1

**Comment by daniel-barrows** [comment]
@johngodley : Entering the escaped redirect URL worked fine. I am 80% sure that the original unescaped URL was automatically generated from the 404 viewer page, aka. [client/page/logs404/create-redirect.js](https://github.com/johngodley/redirection/blob/master/client/page/logs404/create-redirect.js), so you may want to add a test case to ensure that whatever fix you apply also works for redirects created via that method.

**Comment by johngodley** [comment]
Yep, that's something that is handled in the 4.3 alpha!
