### ISSUE TITLE
redirection error

### ISSUE THREAD

**Issue by bourafai** [johngodley/redirection#1633]
Plugin: 2.8.1
WordPress: 4.8.8
PHP: 7.0.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Buster: 2.8.1 === 2.8.1
TypeError: Cannot read property 'find' of undefined

**Comment by johngodley** [comment]
Version 2.8.1 was released nearly 2 years ago. Please update to the new version
