### ISSUE TITLE
Redirection issue with | character

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#1639]
Please see this image:

![Redirect](https://user-images.githubusercontent.com/7985331/55682333-f0344780-5929-11e9-8612-de4cf3a12237.jpg)

I am using the latest release. So it should redirect to:

`/meeting-schedule-assistant/#googtrans(en|da)`

But as you can see, the `|` is bring stripped when I perform a test.

![Redirect2](https://user-images.githubusercontent.com/7985331/55682351-312c5c00-592a-11e9-9591-730a4230415f.jpg)

How can I resolve this? Thank you.

**Comment by johngodley** [comment]
The `|` is remove by WordPress itself, which treats it as an invalid character. The only way around this is to modify a core WordPress file

**Comment by ajtruckle** [comment]
@johngodley OK. Can you please direct me to where this is in the WordPress core so that I can direct a request on the WordPress forum about this issue? Understandably I do not want to blindly alter core files myself.

**Comment by johngodley** [comment]
`wp_sanitize_redirect` in `pluggable.php`, specifically:

`$location = preg_replace( '|[^a-z0-9-~+_.?#=&;,/:%!*\[\]()@]|i', '', $location );`

It will be possible supply your own `wp_sanitize_redirect` function which will override this.
