### ISSUE TITLE
False redirection "check" result

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#1640]
I am using the latest version. When I perform a check on the link it says:

![RedirectBug](https://user-images.githubusercontent.com/7985331/55682447-5d94a800-592b-11e9-82f5-302daddc2fee.jpg)

It thinks that my redirect:

`https://www.publictalksoftware.co.uk/public_talks/helponline/source/control_panel_loop.html`

is supposed to be:

`https://www.publictalksoftware.co.uk/public_talks/helponline/source/LOOPDLG.HTM`

This is wrong. It gets stuck in an infinite loop of redirects if I do that.

The link I have specified is the correct one.

![RedirectBug2](https://user-images.githubusercontent.com/7985331/55682462-9f255300-592b-11e9-866d-0f120f3bef84.jpg)

How to resolve?

**Comment by johngodley** [comment]
The URL doesn't appear to redirect at all currently - it's returning a valid page?

**Comment by ajtruckle** [comment]
@johngodley I think you miss understand.

The Source URL is:

`https://www.publictalksoftware.co.uk/public_talks/helponline/source/LOOPDLG.HTM`

The Target URL is:

`https://www.publictalksoftware.co.uk/public_talks/helponline/source/control_panel_loop.html`

I can navigate directly to the target URL in a browser, but if I use the source URL:

`https://www.publictalksoftware.co.uk/public_talks/helponline/source/LOOPDLG.HTM`

I end up getting:

![Error](https://user-images.githubusercontent.com/7985331/55684829-a8241d80-5947-11e9-81b7-25968820713f.jpg)

So the redirect is failing. If I use the Check feature in the plugin:

![Check](https://user-images.githubusercontent.com/7985331/55684835-d0138100-5947-11e9-80de-ecf34596a524.jpg)

That also fails like I have shown you.

I tried deleting the redirect and adding it again. No joy.

![Error2](https://user-images.githubusercontent.com/7985331/55684865-21237500-5948-11e9-89a6-f8cb8e57e20b.jpg)

**Comment by johngodley** [comment]
Do you have any other redirects that may be matching?

**Comment by ajtruckle** [comment]
@johngodley I am trying to export my logs to a CSV file but when I click Download no File Dialog comes up.

**Comment by ajtruckle** [comment]
@johngodley I created a new issue for the export / view error.

But I confirm there is not another loop redirect there. Not that I can tell.

**Comment by ajtruckle** [comment]
![Error4](https://user-images.githubusercontent.com/7985331/55685332-baed2100-594c-11e9-80a3-b1d782138e29.jpg)

This is wrong. It is completely ignoring my target URL. Is this a cache issue?

**Comment by johngodley** [comment]
It's not wrong in the sense that this is what the URL is being redirected to - the checker is reporting correctly. I couldn't say if it's a cache issue. If you try exporting as JSON then I can take a look at that.

**Comment by ajtruckle** [comment]
[redirection-www-publictalksoftware-co-uk-07_04_2019.zip](https://github.com/johngodley/redirection/files/3051637/redirection-www-publictalksoftware-co-uk-07_04_2019.zip)

**Comment by ajtruckle** [comment]
You seem to have a bug because look:

```
       {
            "id": 179,
            "url": "/msa/HelpOnline/index.html?page=source/helpsmeditor.htm",
            "match_url": "/msa/helponline/index.html",
            "match_data": {
                "source": {
                    "flag_query": "exact",
                    "flag_case": true,
                    "flag_trailing": false,
                    "flag_regex": false
                }
            },
            "action_code": 301,
            "action_type": "url",
            "action_data": {
                "url": "https://help-msa.publictalksoftware.co.uk/mwb-editor.html"
            },
            "match_type": "url",
            "title": "",
            "hits": 0,
            "regex": false,
            "group_id": 9,
            "position": 65,
            "last_access": "-",
            "enabled": true
        },
        {
            "id": 180,
            "url": "/sound_rota_dan.htm",
            "match_url": "/sound_rota_dan.htm",
            "match_data": {
                "source": {
                    "flag_query": "exact",
                    "flag_case": true,
                    "flag_trailing": false,
                    "flag_regex": false
                }
            },
            "action_code": 301,
            "action_type": "url",
            "action_data": {
                "url": "/meeting-schedule-assistant/#googtrans(en|da)"
            },
            "match_type": "url",
            "title": "",
            "hits": 3,
            "regex": false,
            "group_id": 3,
            "position": 51,
            "last_access": "07/04/2019",
            "enabled": true
        },
```

See the first redirect?:

```
            "url": "/msa/HelpOnline/index.html?page=source/helpsmeditor.htm",
            "match_url": "/msa/helponline/index.html",
```

That is how I expect it. But the redirects added this morning all have the same source / target. Not as I have input it.

**Comment by johngodley** [comment]
What part of that do you think is a bug?

You have a redirect that is catching your original U RL

`/public_talks/HelpOnline/(.*)` => `https://www.publictalksoftware.co.uk/public_talks/helponline/$1`

**Comment by ajtruckle** [comment]
Oh - thanks. Does this mean that this redirect like LOOPDLG needs to placed higher up the list and given priority over the catachall redirect.

**Comment by johngodley** [comment]
I dont think you need that redirect all. It seems to be redirecting the camelcase `HelpOnline` to `helponline`, yet it is marked as 'ignore case', so will match everything

**Comment by ajtruckle** [comment]
This is because you never sued to have that feature. I will disable it.

**Comment by johngodley** [comment]
Sure. I made sure not enable it by default so that people had a chance to disable rules like this, but equally I accept that it's easy to miss these things.

**Comment by ajtruckle** [comment]
Thanks. Looks good now.
