### ISSUE TITLE
Error exporting CSV

### ISSUE THREAD

**Issue by brendanmullan** [johngodley/redirection#1642]
Hi there! When trying to export a CSV of the redirects it doesn't seem to work at all. I see this error in the WordPress error log:

> WordPress database error Table 'redacted_redacted.wp_rank_math_redirections' doesn't exist for query SELECT COUNT(*) FROM wp_rank_math_redirections made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, Redirection_Api_Import->route_plugin_import_list, Red_Plugin_Importer::get_plugins, Red_RankMath_Importer->get_data

```
Plugin: 4.2
WordPress: 5.1.1 (single)
PHP: 7.2.16

**Comment by johngodley** [comment]
That is from `wp_rank_math_redirections` not Redirection?

**Comment by brendanmullan** [comment]
That's the strange thing - That plugin isn't installed at all. But that error is generated when trying to export the CSV in Redirection. I've cleared the error log to make sure. Any idea why that would be happening?

**Comment by brendanmullan** [comment]
It's possibly some kind of conflict with [wp-rocket](https://wp-rocket.me/) as one site that has never had it installed seems to be fine where all others have the same issue. Although disabling the plugin doesn't seem to resolve the issue.

**Comment by brendanmullan** [comment]
Just installed a brand new clean install of WP + Redirection with no other plugins or themes installed and it throws the same error when trying to download the CSV export. Seems pretty bizarre?

**Comment by brendanmullan** [comment]
Just tested Redirection 4.1 and it works fine. It's broken in 4.1.1

**Comment by johngodley** [comment]
Ok, I discovered a typo in the CSV download link that is fixed in 4.2.1

**Comment by brendanmullan** [comment]
Thanks for the super fast fix / update and for building such an awesome plugin :-)
