### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by FreshspaceHQ** [johngodley/redirection#1644]
Hi,

We get the following error message, we don't host the site but want to be able to report back to them what the issue is.

Plugin: 3.7.3
WordPress: 5.0.3 (multi)
PHP: 7.0.33-0ubuntu0.16.04.3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
JavaScript: /app/plugins/redirection/redirection.js
REST API: https://www.brokk.com/uk/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment]
Please logout, clear your cache, and login again

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
