### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Johan-Labuschagne** [johngodley/redirection#1645]
```
Plugin: 4.2
WordPress: 5.1.1 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
JavaScript: https://www.furniture-depot.co.za/wp-content/plugins/redirection/redirection.js
REST API: https://www.furniture-depot.co.za/wp-json/

Error: Unable to add new redirect (41): Unknown column 'match_url' in 'field list'
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"/product-category/home-office-c","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"/product-category/home-office"}}
Code: 400 Bad Request
Raw: {"code":"redirect","message":"Unable to add new redirect","data":{"status":400,"error_code":41,"wpdb":"Unknown column 'match_url' in 'field list'"}}
```

**Comment by johngodley** [comment]
Please go to the plugin 'support' page, change the database version to `2.4`, and follow the instructions to upgrade your database again.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details

**Comment by JiveDig** [comment]
Same issue, this fixed it for me. TY!

**Comment by binhwpo** [comment]
Thank you! This save me!

**Comment by axeltaussig** [comment]
> Please go to the plugin 'support' page, change the database version to `2.4`, and follow the instructions to upgrade your database again.

-------------------------------------------------------------------------------------------------

Hi, we've installed the plugin and are getting the same error when trying to create a redirect.

I can do the same as suggested above and in the article (https://github.com/johngodley/redirection/issues/1948) and change the Database version to 2.4, but as we have the database connected to our back-end/payment gateway and don't want to break anything we are wondering what are the changes that will occur when we go from 4.2 current DB version to the suggested 2.4. I need to be sure that those changes wont affect our current back-end, or if so, in what way.

**FYI the error we are getting is as follow:**
Bad data
There was a problem making a request to your site. This could indicate you provided data that did not match requirements, or that the plugin sent a bad request.
Please review your data and try again.

Debug Information:
Please check the support site before proceeding further.
If that did not help then create an issue or send it in an email.

Create An Issue Email
Include these details in your report along with a description of what you were doing and a screenshot.

Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
JavaScript: https://www.tradeview.com.au/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.tradeview.com.au/wp-json/
Query: ?page=redirection.php

Action: https://www.tradeview.com.au/wp-json/redirection/v1/redirect/?orderby=id&direction=desc&per_page=25 POST
Params: {"id":0,"url":"https://www.tradeview.com.au/product/member-portal/","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"},"options":{}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"https://www.tradeview.com.au/tradeview_x/#getstarted"}}
Code: 400 Bad Request

Error: Unable to add new redirect (redirect_create_failed)
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":295,"wpdb":"Unknown column 'match_data' in 'field list'"}}

Thank you for your time and help, appreciate it.

Axel Taussig

**Comment by johngodley** [comment]
@axeltaussig Nothing changes when you go to 2.4. Your database will be re-upgraded when you then go from 2.4 back to the current version, which will fix the error message.

**Comment by axeltaussig** [comment]
> @axeltaussig Nothing changes when you go to 2.4. Your database will be re-upgraded when you then go from 2.4 back to the current version, which will fix the error message.

Thank you johngodley, I'll give it a go. Cheers!
