### ISSUE TITLE
I have duplicate content where /? and /?amp and /?amp/?amp are showing up

### ISSUE THREAD

**Issue by karencole37** [johngodley/redirection#1649]
My site is at https://rainbowriting.com - and I have a duplicate content issue. A serious one that is affecting my SERPs standings, especially on Google. Take for example my home page at https://rainbowriting.com - ever since I had and then deactivated and deleted the original AMP Wordpress plugin (Automattic), the site is showing up in duplicate pages.

As in this manner, using for example the Home page, but this applies to EVERY page in the site including all the blog pages:

https://rainbowriting.com/?
https://rainbowriting.com/?amp
https://rainbowriting.com/?amp/
https://rainbowriting.com/?amp/?amp
https://rainbowriting.com/?amp/?amp/?amp repeating endlessly. You can keep adding in the /?amp and it will continue forever!

I need the site to NOT SHOW UP at all in any URLs that include ? - if a code could be written just indicating that, no URLs allowed to show up that include ? in the URL that might work!

Is there a way to eliminate this duplicate content? Or will I have to republish to before I added in the AMP plugin and then maybe the issue will go away? I'm afraid maybe the issue has been there all along, as when the site was first created it had the Google/Automattic AMP plugin installed and activated. So republishing probably just wouldn't work at all.

Browser I tend to use is Google Chrome, version of WordPress is the latest one and so is the Redirection plugin.

**Comment by johngodley** [comment]
You can redirect a URL that ends in `?amp`, or return a 410 error. I would not advise doing it for any URL that has `?` though, as that will break your site search and possibly other things.

**Comment by karencole37** [comment]
So, that leaves me without a method. I don't want to do what you said and break my site. What other method could I use to redirect or otherwise eliminate the /? and /?amp pages in question?

**Comment by johngodley** [comment]
As I said, you can create a redirect for URLs ending in `?amp`. I would not do it for all URL with a`?` in though.

**Comment by karencole37** [comment]
Is there a better way, so I can get rid of all the duplicate content including URLs like https://rainbowriting.com/? and https://rainbowriting.com/?amp

**Comment by johngodley** [comment]
Really I don't think any of those are going to cause duplicate content issues. Your site has the `canonical` setting, and they are correctly all the same.  Google generally doesn't treat things after `?` as different pages, and `/?amp/?amp` is not a valid URL.

You can redirect them if you want though - just create a redirect with a source and target.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
