### ISSUE TITLE
Feature Request: Restrict Menu Options by role

### ISSUE THREAD

**Issue by syhc** [johngodley/redirection#1653]
I would like to hide some of the sub menu options based on user role. I want some users to be able to add redirects and view the 404s and logs but not able to make new groups or configure the options.

"Redirects | Groups | Log | 404s | Import/Export | Options | Support"

**Comment by leymannx** [comment]
Indeed a more fine-grained access check would be a really necessary enhancement. As often you may want to have editors or SEO persons maintain redirects, but they must not access all the plugin's options.

I'm wondering if it would be a good idea to simply add another `redirection_role`. Maybe something like `redirection_redirects_role` and prevent it to access any `/wp-admin/tools.php?page=redirection.php&sub=` tabs?

**Comment by syhc** [comment]
I would prefer multiple capabilities over multiple role for granularity . https://codex.wordpress.org/Roles_and_Capabilities

Something like this:
- `redirection_redirects`
- `redirection_groups`
- `redirection_log`
- ...
