### ISSUE TITLE
CSV import failing with "Double-check the file is the correct format!"

### ISSUE THREAD

**Issue by joeczucha** [johngodley/redirection#1654]
### Summary

I've created a number of test CSVs and I'm trying to import these into Redirection.

### Actual Behavior

Despite the format being correct - as far as I can see - it's failing with "Total redirects imported: 0. Double-check the file is the correct format!"

### Steps to reproduce

I tried CSVs in the following format (all were saved out as plain text using Sublime with the extension `.csv`):

**a.csv**
   
    "/product/geofencing/","/product/alerts/",0,301

**b.csv** (dropping end slashes)

    "/product/geofencing","/product/alerts",0,301

**c.csv** (dropping regex and type)

    "/product/geofencing/","/product/alerts/"

**d.csv** (dropping end slashes again)

    "/product/geofencing","/product/alerts"

**e.csv** (dropping quotes)

    /product/geofencing/,/product/alerts/

**f.csv** (dropping end slashes again)

    /product/geofencing,/product/alerts

**g.csv** (with headers)

    source URL,target URL
    /product/geofencing,/product/alerts

**h.csv** (with full urls)

    https://staging.mydomain.com/product/geofencing,https://staging.mydomain.com/product/alerts

I'm not sure if I'm missing something here :) I always select the Group "redirects" as the one to import into.

### Environment

I'm using Chrome 73 on the latest OSX. Redirection plugin is version 4.2.1.
              
    == Server Environment ==
      Operating System: Linux
      Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.8
      MySQL version: MariaDB Server v10.3.8
      PHP Version: 7.2.8
      PHP Max Input Vars: 1000
      PHP Max Post Size: 8M
      GD Installed: Yes
      ZIP Installed: Yes
      Write Permissions: All right
      Elementor Library: Connected

    == WordPress Environment ==
      Version: 5.1.1
      Site URL: https://staging.mydomain.com/wordpress
      Home URL: https://staging.mydomain.com
      WP Multisite: No
      Max Upload Size: 8 MB
      Memory limit: 256M
      Permalink Structure: /%category%/%postname%/
      Language: en-US
      Timezone: 0
      Debug Mode: Inactive

Thanks for your work on this plugin.

**Comment by johngodley** [comment]
Can you upload these CSV files? You might need to zip them up for Github

**Comment by geminorum** [comment]
might help: parsecsv/parsecsv-for-php#167

**Comment by joeczucha** [comment]
Sure thing...

[test_csvs.zip](https://github.com/johngodley/redirection/files/3069143/test_csvs.zip)

**Comment by johngodley** [comment]
Those files all imported fine for me. Do you have any security software that may be affecting a CSV import? Could your server be configured to block CSVs?

**Comment by joeczucha** [comment]
Hmm, very strange. I've just checked the server logs and I'm getting the following: 

    [Thu Apr 11 18:32:09.507771 2019] [php7:notice] [pid 17757] [client xx.xx.xx.xx:60483] WordPress database error Unknown column 'match_data' in 'field list' for query INSERT INTO `wp_redirection_items` (`regex`, `match_data`, `match_type`, `url`, `match_url`, `title`, `group_id`, `position`, `action_type`, `action_code`, `action_data`, `status`) VALUES ('0', '{\\"source\\":{\\"flag_regex\\":false}}', 'url', '/product/geofencing/', '/product/geofencing', NULL, '1', '94', 'url', '301', '/product/alerts/', 'enabled') made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, Redirection_Api_Import->route_import_file, Red_FileIO::import, Red_Csv_File->load, Red_Csv_File->load_from_file, Red_Item::create, referer: https://staging.mydomain.com/wordpress/wp-admin/tools.php?page=redirection.php&sub=io

Which explains it... as I don't seem to have a `match_data` column.

    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `url` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
    `regex` int(11) unsigned NOT NULL DEFAULT 0,
    `position` int(11) unsigned NOT NULL DEFAULT 0,
    `last_count` int(10) unsigned NOT NULL DEFAULT 0,
    `last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `group_id` int(11) NOT NULL DEFAULT 0,
    `status` enum('enabled','disabled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'enabled',
    `action_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
    `action_code` int(11) unsigned NOT NULL,
    `action_data` mediumtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `match_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
    `title` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `url` (`url`(191)),
    KEY `status` (`status`),
    KEY `regex` (`regex`),
    KEY `group_idpos` (`group_id`,`position`),
    KEY `group` (`group_id`)

**Comment by johngodley** [comment]
Ok, if you go to the 'support' page and change the database version to 2.4 and then follow the instructions to re-upgrade the plugin it should fix things.

**Comment by joeczucha** [comment]
Yep that worked. Nice one 👍 

Not sure how that happened though as I just installed it and it seemed to default to those settings. 

Thanks for your help.

**Comment by johngodley** [comment]
> Not sure how that happened though as I just installed it and it seemed to default to those settings.

That's interesting. So this was a new installation of the plugin? Had you previously installed the plugin on the same site?

**Comment by joeczucha** [comment]
No, it was the first installation. It went through the process of creating the tables and that all seemed to work, but it looks like it just defaulted to the wrong version. 

When I've got a bit more time, I'll spin up a Docker container with a clean WP install and see if the same thing happens.
