### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by ashleywoodford** [johngodley/redirection#1655]
```
Plugin: 4.2.1
WordPress: 5.1.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
JavaScript: http://lowcarbonenergycentre.co.uk/wp-content/plugins/redirection/redirection.js
REST API: http://lowcarbonenergycentre.co.uk/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/group/ GET
Code: 200 OK
Raw: <hr/><pre>/wp-json/redirection/v1/group/?_wpnonce=224e9dcbd7</pre><hr/>{"items":[{"id":2,"name":"Modified Posts","redirects":0,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":1,"name":"Redirections","redirects":0,"module_id":1,"moduleName":"WordPress","enabled":true,"default":true}],"total":2}
```

**Comment by johngodley** [comment]
What are you doing when this message is shown?

**Comment by ashleywoodford** [comment]
Hi John,

When I go to the plugin admin page to try and add a redirect in.

Kind regards,

Ashley Woodford
Lead Designer

[cid:image002.png@01D39555.F5927010]
Web Design – Web Development – SEO

Tel: 01202 665855
Email: ashley@southcoastweb.co.uk<mailto:ashley@southcoastweb.co.uk>
Web: www.southcoastweb.co.uk<http://www.southcoastweb.co.uk/>

**Comment by johngodley** [comment]
Do you have any other plugin running that uses the REST API? Something is outputting `<hr/><pre>/wp-json/redirection/v1/group/?_wpnonce=224e9dcbd7</pre><hr/>` on your REST API and it's not Redirection.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
