### ISSUE TITLE
Ignore Case Flag

### ISSUE THREAD

**Issue by Zyniker13** [johngodley/redirection#166]
Is it currently possible to flag redirects to ignore case (i.e., `\i`)? If not, I guess this is a feature request.

**Comment by Zyniker13** [comment]
Before someone points out the obvious: It is already possible to do this with regex, but `^something$` with `\i` set is much cleaner (and easier to enter) than `^(S|s)(O|o)(M|m)(E|e)(T|t)(H|h)(I|i)(N|n)(G|g)$` without `\i`.

**Comment by nhankla** [comment]
Hi, 
I put this fix in place under Models > Redirect.php Line 223.
Should be on by default in my opinion. 

```
public function matches( $url ) {
		if ( ! $this->is_enabled() ) {
			return false;
		}
		
		// Fix for upper, lower, camel case
		$url = strtolower($url);
		$this->url = str_replace( ' ', '%20', $this->url );
		$this->url = strtolower($this->url);
		$matches   = false;

/* // old url function for spaces
		$this->url = str_replace( ' ', '%20', $this->url );
		$matches   = false;
*/ 
```

**Comment by DimeZilla** [comment]
Hi, Let me first say that I love this plugin and am very thankful for everyone who works on it! Much love and respect.

I don't know if this is helpful to others finding this thread but to get around this issue right now in my theme I hooked into the `redirection_url_source` filter like so:
```
add_filter('redirection_url_source', function ($url) {
    // lets do a pre-flight-check of the matches to see if we'll get
    // anything on this exact url match. if we don't but we do have
    // possible redirect targets, lets do a case insensitive binary
    // string comparison against the item urls
    if(class_exists('Red_Item')) {
         // here we are basically just borrowing from \WordPress_Module::init()
        $redirects = \Red_Item::get_for_url($url, 'wp');

        $matches = [];
        foreach ((array) $redirects as $item) {
            if ($item->matches($url)) {
                $matches[] = $item;
            }
        }

        // if we didn't match based on the rules then lets see if we can get a case insensitive
        //  match and redirect to it
        if (empty($matches) && !empty($redirects)) {
            foreach ( (array) $redirects as $item) {
                // we don't want to accidentally match on something that
                // already has its own regex rules for how to match.
                if (!$item->is_regex()) {
                    $target = $item->get_url();
                    if (strcasecmp($url, $target) === 0) {
                        return $target;
                    }
                }
            }
        }
    }

    return $url;
});
```

I'm curious what you all think for this as a temporary solution. I also think it'd be nice to have have a few more hooks and filters in this plugin generally. Like in `Red_Item::matches` it'd be nice if it had a filter on the binary return so that I could hook into it there instead of above.

Thanks again!

**Comment by ajtruckle** [comment]
Any ETA for this? And what about the target? For example, if the source has uppercase but the target you want lowercase.

**Comment by ajtruckle** [comment]
I gave up on it. I don't know how to do the coding. But after so long ....

If anything happens then great!

**Comment by johngodley** [comment]
It's not a simple addition, and the suggestions above likely won't work or won't work properly.

I am actively working on this and other changes to URL handling, but as it's something that can potentially break over a million sites I am being particularly careful.

A beta will be released, probably early next year, and any testing is appreciated.

**Comment by cdCorey** [comment]
Ok, thanks for the update. We need this for a client site so I'll have to setup a temporary workaround in the meantime. If we can offer testing or any other assistance, let me know.

**Comment by johngodley** [comment]
This will be added as part of #1377

This is marked as alpha. If you are interested in testing it then you can find a download at https://github.com/johngodley/redirection/releases/tag/4.0-alpha-1

I would appreciate any feedback, either here on Github, or directly at https://redirection.me/contact/

I'll close this as 'done'.
