### ISSUE TITLE
Prevent from adding duplicate redirections from the same page

### ISSUE THREAD

**Issue by khalyomede** [johngodley/redirection#1660]
### Summary

This is a feature request where I think this would be pertinent to prevent / warn the user that he/she tries to add a redirection from a page that has already been registered.

### Actual Behavior

We can have multiple duplicate redirection from the same route.

### Steps to reproduce

Add a redirection from /contact to /contact-us.
Add another redirection from /contact to /contact-us-now.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Chrome : Version 72.0.3626.119 (Build officiel) (64 bits)
Wordpress : 5.1.1
Redirection plugin : 4.2.1

**Comment by johngodley** [comment]
Closing in favour of #82. Thanks!
