### ISSUE TITLE
BUG - Home Page Redirecting

### ISSUE THREAD

**Issue by fidelisartprints** [johngodley/redirection#1661]
I recently installed Redirection and the redirects appeared to be work fine, then I noticed that the my home page was redirecting to the last post I redirected.

Can you check over my attachments to see if there is something that can be done to fix the home page redirect?

Due to the home page redirecting, I have the plugin temporarily disabled. If you need me to re-enable it, please let me know.

I've double-checked on multiple machines (Mac) and browsers (Chrome & Safari) and the problem is the same. I'm running WordPress 5.1.1 with Redirection 4.2.1.

Any help would be very much appreciated?

Alan

<img width="1440" alt="Screen Shot 2019-04-12 at 11 05 04 AM" src="https://user-images.githubusercontent.com/49569075/56058280-d2922400-5d15-11e9-85f3-fafbc56652fa.png">
<img width="1440" alt="Screen Shot 2019-04-12 at 10 57 36 AM" src="https://user-images.githubusercontent.com/49569075/56058282-d2922400-5d15-11e9-89d6-163d73b55919.png">
<img width="1440" alt="Screen Shot 2019-04-12 at 11 27 52 AM" src="https://user-images.githubusercontent.com/49569075/56058373-17b65600-5d16-11e9-8e3f-42ea50d5ebbb.png">

**Comment by johngodley** [comment]
That first redirect is invalid: `/?=2057`. It is probably being interpreted as a redirect for the home page. Did you mean it to be `/?p=2057`?

**Comment by fidelisartprints** [comment]
Thanks for such a fast response. The typo seems to have been the problem.  :)
