### ISSUE TITLE
Automatic Detection Question

### ISSUE THREAD

**Issue by Shyzer** [johngodley/redirection#1668]
Hello, I'm looking for clarification on how the automatic detection of deleted content works. I couldn't find anything in the support doc on how this feature behaviors correctly. Is there supposed to be any sort of pop-up box to enter the redirect, similar to Yoast's redirect option, when a post is deleted?

Currently, when I delete a post, the [redirect is partially created](https://gyazo.com/a1a499190ad119fb26e93f979bf17148) and I have to remember to set the redirect manually. 

I'v noticed that I don't have a "Monitor trashed items" option, as [seen in the support doc](https://redirection.me/support/options/#monitor). My settings only have a "[Monitor changes to trash](https://gyazo.com/a20c44018a4ec0b152f941ea18e92c40)" option. I assume these are the same, but I'm not 100%

I confirmed this behavior with the [Health & Check plugin](https://wordpress.org/plugins/health-check/) with only Redirect activated.

Chrome: 73.0.3683.103
Wordpress: 5.1.1
Redirect: 4.2.2

Thanks!

**Comment by johngodley** [comment]
That is working as expected.

**Comment by Shyzer** [comment]
Cheers, thank you for the clarification and great plugin.
