### ISSUE TITLE
Folder directory Redirect to Page

### ISSUE THREAD

**Issue by jim954** [johngodley/redirection#1675]
Thanks for the great plugin.

Want to redirect all requests for old folder directory, were the wp install was hosted for the blog portion of the web site,  to a page.

www.xyz.com/blog/posts1,2,3.. (were blog is a folder inside the main directoy)
Redirect to 
www.xyz.com/blog (were blog is a created page in the main directory)

Possible? Thanks

**Comment by johngodley** [comment]
You can use a regular expression, as described here:

https://redirection.me/support/redirect-regular-expressions/
