### ISSUE TITLE
redirect not working for image but counts hits

### ISSUE THREAD

**Issue by schnizZzla** [johngodley/redirection#168]
I am trying to redirect an image e.g.

/wp-content/uploads/2016/07/n26-open-graph-image.png
to
/content/uploads/2016/07/n26-open-graph-image.png

What I have observed is that without the redirection I receive a WP 404 page, so WP code is definitely triggered. 

As soon as I add the redirection I receive a 404 but not from WP, it seems a standard 404 sent from the server without any visible content triggering an error message in the browser "This ... page can't be found"

When this happens hits are counted in the redirection plugin!

This is weird, any ideas?

**Comment by Sophist-UK** [comment]
Please provide full details of the redirect you set up esp. whether it is a Wordpress or Apache module redirect.

**Comment by schnizZzla** [comment]
Here are some more details and an example:

WP 4.7
Redirection Version 2.5

The redirection is using the WordPress module (the other modules apache, nginx are not in use at all)
The server is running nginx

Redirect type is 301
source: /wp-content/uploads/2016/12/1612-n26-opengraph.png
target: /content/uploads/2016/12/1612-n26-opengraph

screenshot of the config:
https://snag.gy/B6dxrq.jpg

**Comment by johngodley** [comment]
Sorry for the delay in replying.

Does the original image still exist? If so, can you delete it.

It sounds like your server and WP are competing to do redirects. If it's possible can you provide a real URL that I can test to see this not working?

**Comment by johngodley** [comment]
Closing for now, please reopen if you have more details
