### ISSUE TITLE
Redirection Error for 4.2.3 update

### ISSUE THREAD

**Issue by littlefishweb** [johngodley/redirection#1680]
Redirection 4.2.3 update breaks my site

After updating all my plugins and checking to make sure the site was OK, I got this error and a broken site:

Fatal error: Class Url_Action contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Red_Action::needs_target) in C:\xampp\htdocs\wp-content\plugins\redirection\actions\url.php on line 16 

Miraculously the dashboard still worked. I updated the data base as per Redirection instructions, but that didn't help. 

I then deactivated all of the plugins, turning them back on individually, checking the site front end at each step. When I activated Redirection the error came back. 

The plugin is currently deactivated.

I'm using Chrome, WP 5.1, Redirection 4.2.3.

**Comment by johngodley** [comment]
Your site failed to update Redirection correctly. Please re-install the plugin files.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
