### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by tombond999** [johngodley/redirection#1681]
Hello guys,

I really need your help, i'm trying to use the redirection plugin and the database upgrade is always crashing.

Screenshot: https://pasteboard.co/IaAZ6Me.png

```
Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://monpeintre.ca/wp-content/plugins/redirection/redirection.js
REST API: https://monpeintre.ca/wp-json/

Error: Le nonce du cookie n’est pas valide (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Le nonce du cookie n\u2019est pas valide","data":{"status":403}}
```

**Comment by tombond999** [comment]
I did re-install the plugin, but still not working

**Comment by johngodley** [comment]
The plugin should provide some guidance about what to do, and I suspect it will say that you should logout, clear your cache, and login again.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
