### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by RavanH** [johngodley/redirection#1682]
```
Plugin: 4.2.1
WordPress: 5.1.1 (multi)
PHP: 7.2.16-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://xxxxx/wp-content/plugins/redirection/redirection.js
REST API: https://xxxxx/wp-json/

Error: Unable to add new redirect (41): Unknown column 'match_url' in 'field list'
Raw: {"code":"redirect","message":"Unable to add new redirect","data":{"status":400,"error_code":41,"wpdb":"Unknown column 'match_url' in 'field list'"}}
```

Not sure what happened but it looks like the recent DB upgrade did not complete. Instead of clicking the button I chose the link "Manual upgrade" first (seeing the upgrade SQL) and then used the "Proceed upgrade" (or similar text) button, expecting the plugin to execute said SQL. Maybe it didn't?

**Comment by johngodley** [comment]
The manual upgrade option requires you to execute the SQL manually. You will need to go the support page and change the database version to 2.4 and then re-run the upgrade without picking the manual option.

**Comment by RavanH** [comment]
OK my mistake. The button gave me the impression that it would still do the upgrade automatically... Thanks for the instructions :)
