### ISSUE TITLE
All 301 redirects stopped working

### ISSUE THREAD

**Issue by neotel2000** [johngodley/redirection#1693]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

All 301 redirects stopped working

### Actual Behavior

All 301 redirects stopped working. Suddenly. I cleared all cache

### Steps to reproduce

Simply All 301 redirects stopped working

### Environment

Firefox Quantum, 66.0.3 (64-bit), 5.1.1, 4.2.3

**Comment by johngodley** [comment]
Closing as duplicate. Please only post in one location
