### ISSUE TITLE
Forcing HTTPS on localhost?

### ISSUE THREAD

**Issue by mmazanec22** [johngodley/redirection#1695]
### Summary

I checked the force HTTPS box and then recloned my db from live to my machine.  Could no longer run the site locally after that.  Also upgraded my machine to Mojave, which maybe contributed?

### Actual Behavior

Forcing HTTPS and then copying the db locally resulted in redirects to https://localhost and err_connection_refused messages.  Unchecking force HTTPS and recloning db and also setting ports differently seemed to fix it.

### Steps to reproduce

Check force HTTPS box, clone db, try to run locally, does not work.  Delete redirection plugin from freshly cloned repo and switch from using default MAMP ports (8889 and 8888) to 80 and 3306... and the site runs fine.  Uncheck force HTTPS box on live, re-clone db, run from repo with redirection plugin, everything is fine.  Switch back to default MAMP ports and it stops working.  ???

### Environment

Using MAMP on a MacBook running Mojave.  Issue persisted across browsers.

I'm back in business but wanted to open an issue because this appeared to be at least in part due to the redirection plugin forcing HTTPS when running locally.

Thanks for supporting this plugin!  My content team was very excited about it.

**Comment by johngodley** [comment]
Yes, you have told the plugin to force https. If your localhost is not setup for that then it won't work.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
