### ISSUE TITLE
Redirection Error 200

### ISSUE THREAD

**Issue by BarbaraSilviaDesign** [johngodley/redirection#1704]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I have found Redirection error 200 when I tried to redirect the english version of a page (italian main website). I tried to redirect the english link of the page, but it keeps saying that the page can be found only in the italian website.

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by BarbaraSilviaDesign** [comment]
I have found Redirection error 200 when I tried to redirect the english version of a page (italian main website). I tried to redirect the english link of the page, but it keeps saying that the page can be found only in the italian website.

**Comment by johngodley** [comment]
I have responded to your email. Please only report issues in one place. Closing this.
