### ISSUE TITLE
woocommerce checkout spinning for ever

### ISSUE THREAD

**Issue by botsolutions** [johngodley/redirection#1710]
![image](https://user-images.githubusercontent.com/16782062/56755810-a3a59480-6790-11e9-8f77-1a468db5ab69.png)

This setting will cause woocommerce's ajax to fail on the checkout page
I tested on different sites with different setups

using the latest version: 4.2.3 

Weird thing is that if I create a redirect like this, it won't break the checkout page.
However changing the first setting to this one will also not work, only if I create a new redirect.
(no cookies or cache when tested)

![image](https://user-images.githubusercontent.com/16782062/56755955-fd0dc380-6790-11e9-92f2-ccf80d7b19b4.png)

I understand that maybe I should not create redirects like this.
Currently using javascript redirect which will work just fine now.
Maybe you can add meta and javascript redirects to the plugin? :)

**Comment by johngodley** [comment]
Why are you creating a redirect like that?

**Comment by botsolutions** [comment]
I want to show a certain product on the homepage, so I figured this method which was working all good.

Unfortunately, the new update broke both of my sites.

**Comment by johngodley** [comment]
Do you have a target URL? I'm confused about what you are reporting.

With a source URL of `/` then Redirection will redirect your home page elsewhere. It won't add a product to your home page.

**Comment by botsolutions** [comment]
sorry for the confusion

in the target url field there would be a relative path like
/product/something/

**Comment by johngodley** [comment]
Ok, that makes more sense.

That redirect will redirect everything that accesses `/`. If WooCommerce sends ajax requests there then it will also be included.

If you want to add a product to your home page it would be better to add the appropriate HTML to your home page that then links to the product page.

Redirecting your home page to a product will likely cause much confusion for Google as it will think your home page has moved.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
