### ISSUE TITLE
Editing new groups shows incorrect name

### ISSUE THREAD

**Issue by BobJonkman** [johngodley/redirection#1712]
### Summary
Editing a new Group, name in form is the name of previous group 

### Actual Behavior
Create new group "Advertisements", then click on "Edit", form opens prompting name "Modified Posts" instead of "Advertisements"

### Steps to reproduce
Create new group "Advertisements", then click on "Edit", form opens prompting name "Modified Posts" instead of "Advertisements"
Now create new group "Some Name", then click on "Edit", form opens prompting name "Advertisements" instead of "Some Name"

### Environment
Chromium, Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9.8 (64-bit)

WordPress v5.1.1
Redirection v4.2.3 

Note, this is a cosmetic error, doesn't affect operation of the plug-in (which  plug-in is pretty marvellous!)

Thanx,
--Bob.

**Comment by johngodley** [comment]
Fixed in eea6503e3a53a0b51d47154b5a6ca78112530dcc, will be in the next release. Thanks!
