### ISSUE TITLE
query parameter's key as digit is redirected with key changed to 0

### ISSUE THREAD

**Issue by umairj** [johngodley/redirection#1713]
### Summary

I just updated to the latest version 4.2.3 and while testing I noticed that a query parameter passed with the key as an integer is forwarded to the target url but with the key replaced by 0. This happens with the feature ignore and pass parameters to the target.

Example: Source URL is /new-slug?some=thing&2=245. In this case the redirected URL will have the following parameters: ?some=thing&0=245.

### Actual Behavior

The actual behavior should be that the parameter isn't modified and stays the same.

### Environment

Chrome on Mac Version 73.0.3683.103 (Official Build) (64-bit)
WordPress 4.9.10
Redirection 4.2.3

**Comment by johngodley** [comment]
Fixed in #1715, will be released in version 4.3

**Comment by umairj** [comment]
Thank you very much for the speedy response and a fix.
