### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by azivf** [johngodley/redirection#1716]
Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://latecheasy.com/wp-content/plugins/redirection/redirection.js
REST API: http://latecheasy.com/wp-json/

**Comment by johngodley** [comment]
Please open your browser's developer console and see if any other errors are shown

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
