### ISSUE TITLE
Impossible to import CSV

### ISSUE THREAD

**Issue by nicomollet** [johngodley/redirection#1729]
Hello

I am unable to import any redirections CSV file into my WordPress.
Thank you.

### Summary

I just want to import a simple "source,target" CSV file, which is just:
`"/source/","/target/"`

### Actual Behavior
After selecting my CSV file, I am getting the message:
`Total redirects imported: 0 Double-check the file is the correct format!`

Checking my debug log, I see this line:
```
PHP error table doesn't exist for query 
SELECT COUNT(*) FROM wp_rank_math_redirections by require('wp-blog-header.php'),
wp, WP->main, WP->parse_request, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded,
WP_REST_Server->serve_request, WP_REST_Server->dispatch, Redirection_Api_Import->route_plugin_import_list,
Red_Plugin_Importer::get_plugins, Red_RankMath_Importer->get_data" while reading response header from upstream, 
```

### Steps to reproduce

Tools > Redirection > Import/Export > Add a file > Selecting my csv file > Selecting "Redirections" group > Upload.

### Environment

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.11.9
	MySQL version: (Debian) v5.5.44
	PHP Version: 7.1.25-1+0~20181207224605.11+jessie~1.gbpf65b84
	PHP Max Input Vars: 1000
	PHP Max Post Size: 10M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right

== WordPress Environment ==
	Version: 5.0.4
	WP Multisite: No
	Max Upload Size: 10 MB
	Memory limit: 256M
	Permalink Structure: /%category%/%postname%/
	Language: fr-FR
	Timezone: Europe/Paris
	Debug Mode: Inactive

== Theme ==
	Name: Chocolat 2018 OceanWP Child
	Version: 1.0
	Author: Nick
	Child Theme: Yes
	Parent Theme Name: OceanWP
	Parent Theme Version: 1.6.7
	Parent Theme Author: Nick

== User ==
	Role: administrator
	WP Profile lang: fr_FR
	User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36

== Plugins ==
	Advanced Order Export For WooCommerce
		Version: 2.1.1
		Author: AlgolPlus

	BackWPup
		Version: 3.6.8
		Author: Inpsyde GmbH

	Disable Gutenberg
		Version: 1.8.1
		Author: Jeff Starr

	Easy Updates Manager
		Version: 8.0.5
		Author: Easy Updates Manager Team

	Elementor
		Version: 2.5.14
		Author: Elementor.com

	Elementor Pro
		Version: 2.3.1
		Author: Elementor.com

	FG PrestaShop to WooCommerce Premium
		Version: 3.27.1
		Author: Frédéric GILLES

	GitHub Updater
		Version: 8.7.3
		Author: Andy Fragen

	Google Tag Manager for Wordpress
		Version: 1.9.2
		Author: Thomas Geiger

	Gravity Forms
		Version: 2.4.8
		Author: rocketgenius

	Imagify
		Version: 1.8.4.1
		Author: WP Media

	La Poste Tracking for WooCommerce
		Version: 1.0.1
		Author: Remi Corson

	Mailjet for WordPress
		Version: 5.0.11
		Author: Mailjet SAS

	Ocean Extra
		Version: 1.5.4
		Author: OceanWP

	Payline
		Version: 1.3.6
		Author: Monext

	Redirection
		Version: 4.2.3
		Author: John Godley

	TMSM Admin Cleanup
		Version: 1.1.3
		Author: Nicolas Mollet

	TMSM Frontend Optimizations
		Version: 1.1.2
		Author: Nicolas Mollet

	TMSM WooCommerce Billing Fields
		Version: 1.0.4
		Author: Nicolas Mollet

	WooCommerce
		Version: 3.5.3
		Author: Automattic

	WP Crontrol
		Version: 1.7.1
		Author: John Blackbourn & crontributors

	WP Rocket
		Version: 3.3.1.1
		Author: WP Media

	Yoast SEO
		Version: 11.1
		Author: Team Yoast

**Comment by johngodley** [comment]
Can you attach your CSV file?

**Comment by nicomollet** [comment]
Well I was going to attach the file, and saw it is a `.txt` file.
Just tested again after changing the extension to `.csv` and it worked.

Sorry for the inconvenience.
