### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by dandick** [johngodley/redirection#1739]
Lest someone simply say "Read the instructions...", in my Settings > General page, there is no entry for selecting http or https, and selecting relative URL or the other two does not resolve this.

I cannot copy what's on the page for this entry, but it looks something like this with three radio buttons for Protocol-Relative, Relative, and Ignore as well as one checkbox for Relative format will only affect internal links.  Nowhere on this page is there any reference to http or https either above or below this part of the page.

URL Format
    Protocol-Relative  //example.com/sample-post/ 
    Relative  /sample-post/ 
    Ignore external links
Relative format will only affect internal links.

--------------------------------------------------------------------------------

Now, to give a little info on my website or websites,

- It runs on an ordinary Ubuntu VPS.
- There is no c-panel or anything of the sort.
- I'm running Nginx.
- Wordpress is running multi-site.
- The main domain and default domain is godsblogs.com
- Most sites are simple subdomains and they work fine.
- Two or three of them are set up so their main domain is different including danieljdick.com, and they work fine for the most part.
- Wordpress is running under Docker and Docker-Compose.
- There are containers for nginx, mariadb, and wordpress.
- Wordpress is running on php7.3-fpm
- When people come into any of the domains, they come in through a proxy Nginx on the VPS and are referred to a Docker container for nginx--a sort of microservice if you will.
- I am using the nginx helper whereas before that became available, I was coding the domains by hand.  Internally, both are nearly identical but the helper makes things easier and more automatic.
- I use letsencrypt for ssl.
- It's pretty heavily firewalled and cached, performance optimized.
- I had the problem yesterday running Wordpress 5.1 and today with 5.2.
- Plugins and themes are kept up-to-date.
- Unix, db, php permissions, etc. are kept pretty tight.
- Anti-spam stuff is pretty tight.

I tried turning off cacheing and some other things prior to attempting to update the redirect database but to no avail.

If anything comes to mind I would be thankful to know or to share what I find myself if it could help anyone else.  Meanwhile, I'll cruise through the /var/log stuff.

Thanks!!!

```
Plugin: 4.2.3
WordPress: 5.2 (multi)
PHP: 7.3.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
JavaScript: http://danieljdick.com/wp-content/plugins/redirection/redirection.js
REST API: http://danieljdick.com/wp-json/

Error: Failed to fetch
```

**Comment by johngodley** [comment]
Your WordPress is configured to use http://danieljdick.com/wp-json/ however your site is actually https://danieljdick.com/wp-json/ and a redirect is taking you from http => https.

As your WordPress settings are for http then the browser prevents JavaScript resources being redirected, and the error is shown.

If you set your URLs to https then everything will work. If you are using multisite then this may be done through the network admin rather than the settings page.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details

**Comment by dandick** [comment]
I am so sorry I didn't get your reply or respond with thanks earlier.  Someone created a plugin that made setting up https almost trivial, and it has been working great for me for several months now.  But thanks again for the tip, John.
