### ISSUE TITLE
Disable redirection monitoring on particular posts?

### ISSUE THREAD

**Issue by mishtershmart** [johngodley/redirection#174]
Hi there,

I'm wondering if there is a way for me to disable the redirection monitoring when saving a 'type' of post? In our case, we have a scenario where we don't want certain posts having their URL changes monitored, as it's causing issues (we have a system where sub posts are created within a post and the sub posts are triggering redirects on save).

My first thought was to unhook the `Red_Monitor->post_updated()` method in certain contexts, but the `Red_Monitor` instance's visibility on the `Redirection_Admin` object is **private**.

Any tips?

Cheers,
Phil

**Comment by johngodley** [comment]
There will be a WP hook `redirection_permalink_changed` that you can use to determine if a permalink has changed. You should be able to use this to override the default
