### ISSUE TITLE
Multisite database upgrade only does the first 100 sites.

### ISSUE THREAD

**Issue by pfiled** [johngodley/redirection#1740]
The `get_sites()` call here:

https://github.com/johngodley/redirection/blob/master/database/database.php#L86

Defaults to 100 sites. The fix is easy, just pass  `[ 'number' => 1000 ]` or some other large number to the `get_sites()` function.

Thanks for the great plugin!

**Comment by johngodley** [comment]
Good point. This will be added in 4.3, which you can test here:

https://github.com/johngodley/redirection/releases/tag/4.3-beta-1
