### ISSUE TITLE
A redirection redirects to an unexpected page

### ISSUE THREAD

**Issue by potoclips** [johngodley/redirection#1742]
### Summary

A redirection redirects to an unexpected page.

A post is expected to redirect to a specific page.
Direction
http://www.potoclips.com/pin/61143/
-->> /pin/61143?.* post
-->> /radiohead-thomyorke-stories/ page

### Actual Behavior

http://www.potoclips.com/pin/61143/
redirects to
http://www.potoclips.com/depeche-mode-stories/

How can I investigate to understand what leads to this issue. I've tried to delete the initial redirection, but the issue was still not fixed.

### Steps to reproduce

Enter the following address:
http://www.potoclips.com/pin/61143/

### Environment

Opera, Version 58.0.3135.132, WordPress Version 5.0.4 and Redirection Version 4.2.3.

Thanks for your help,
Regards,
Potoman

**Comment by johngodley** [comment]
You likely have another redirect that is causing the redirect. Try looking through your list to see what else may be active

**Comment by potoclips** [comment]
I have already done it.

I did a search on "61143" in  Source URL field

301 | /pin/61143?.*/radiohead-thomyorke-stories/
301 | /de/pin/61143?.*/de/radiohead-thomyorke-stories/
301 | /fr/pin/61143?.*/fr/radiohead-thomyorke-stories/
they all redirect to /radiohead-thomyorke-stories/

I did a search on "depeche-mode-stories" in  Target URL field

301 | /de/pin/61149?.*/de/depeche-mode-stories/
301 | /fr/pin/61149?.*/fr/depeche-mode-stories/
301 | /pin/61149?.*/depeche-mode-stories/
Only three redirections integrate this key word.

By the way, there's an issue with the search function.
The search is only browsing the Source field and NOT the Target field.

When you say active, you mean embedding either "61149" or "depeche-mode-stories" ?
If yes, there's nothing else active.
If not, what should be considered as active ?

Thanks
Potoman

**Comment by johngodley** [comment]
A regular expression may not show up under a search for '61143'

Yes, the search does not include the target.

By active I meant any other redirect that could be affecting that URL

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
