### ISSUE TITLE
Mobile redirection

### ISSUE THREAD

**Issue by acarlomagno** [johngodley/redirection#1751]
Hi,
I would to redirect from homepage to another page only if the source is mobile
I have created the rule .. but not works and not logged anything

where I wrong?

see the attachment

regards
Antonello
![Schermata 2019-05-13 alle 15 20 33](https://user-images.githubusercontent.com/2254217/57624744-df16d000-7592-11e9-8d45-cd1c94dab015.png)

**Comment by johngodley** [comment]
You have a regular expression user agent, but haven't checked the 'regex' checkbox.

Your target is not a valid URL. It will also need https/http

**Comment by acarlomagno** [comment]
great! now works fine!
