### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by alwatwaat** [johngodley/redirection#1759]
Plugin: 4.2.3
WordPress: 5.2 (single)
PHP: 7.0.19
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
JavaScript: http://alwatwaat.byethost3.com/wp-content/plugins/redirection/redirection.js
REST API: http://alwatwaat.byethost3.com/wp-json/

**Comment by johngodley** [comment]
Please open your browsers developer console and see if any other errors are shown.

**Comment by johngodley** [comment]
Closing for now, please open with more details
