### ISSUE TITLE
Trailing forward slash not handled?

### ISSUE THREAD

**Issue by jdruiter** [johngodley/redirection#176]
Example: 
Source: www.adventuretickets.nl/via-ferrata/
Target: http://www.adventuretickets.nl/?s=via+ferrata&post_type=product

The current behaviour is that /via-ferrata/ is accepted, but /via-ferrata is not accepted when entering the URL in the browser. 

The expected behaviour for most users is that source urls with and without trailing slash are seen as the same URL. 

For use cases in which an admin really wants to distinguish them, an option could be given when entering the redirection url. 

Regular expressions like: 
/via-ferrata/?$ 
seem to sometimes work and sometimes not. Regardless, most users don't understand regular expressions so a solution without regular expression should be provided.

**Comment by jdruiter** [comment]
Update: sometimes it does work, sometimes not. 

There might be a cashing problem on our side - though we have only varnish cache running. 

Waiting for answer from developer how plugin is handling a trailing slash.

**Comment by MatthewRobert** [comment]
I've had the same concerns myself. I've seen other redirect plugins that use a wildcard * in place of the trailing slash. I agree, this should be simpler than doubling up on entries or using regular expression to accommodate for the trailing slash.

**Comment by ehausen** [comment]
Anything happening?

How do you usually handle this? It's pretty common case. Always with a slah or not? Or both?

**Comment by FlixFlix** [comment]
Right now we have to create regex rules, i.e. /old-url/?$ for redirects to work with or without a trailing slash. I suggest having the option for this to be handled automatically.

**Comment by jdruiter** [comment]
@johngodley bump )

**Comment by spieglio** [comment]
Sounds obvious to me. I'd love to see this option as well. Otherwise, we just clutter the list of redirects (or have to do regex everything).

Is there an ETA for this?

**Comment by johngodley** [comment]
This will be added as part of #1377

This is marked as alpha. If you are interesting in testing it then you can find a download at https://github.com/johngodley/redirection/releases/tag/4.0-alpha-1

I would appreciate any feedback, either here on Github, or directly at https://redirection.me/contact/

I'll close this as 'done'.

**Comment by nylen** [comment]
Hi @johngodley I came here looking for this feature.  I've done it with regexes for now but that is not ideal for clients and non-dev collaborators to use.

I'll be trying out this alpha next week and submitting issues/PRs for anything I find.

From https://github.com/johngodley/redirection/issues/29#issuecomment-272630316:

> There are complications around it and other changes like this that I'd like to see tackled at the same time, once confident it won't break any site using the plugin.

Do you have any more details about what these potential complications are, how to test, what to look for etc?  Do you think these issues are mostly solved or is there still potential breakage lurking?

**Comment by johngodley** [comment]
The complications are generally to do with existing sites where things can change in unexpected ways. Some sites have data going back 10+ years and it's not always in the best shape.

So far I've not heard anything about this happening, but it's possible that any side-effects have just gone unnoticed.

Version 4.0 is now in beta, and I'm planning to release to wordpress.org once I've got a clear weekend.

**Comment by nylen** [comment]
Just got a chance to try out the latest beta, and it's working well.  I was able to get rid of all the regex redirects on this site :tada: 

I would have expected the "ignore trailing slashes" option to be enabled by default, but I can see how that might cause problems with existing sites.

Nice work!
