### ISSUE TITLE
"Ignore Case" dose not ignore querystring case

### ISSUE THREAD

**Issue by internic99** [johngodley/redirection#1760]
### Summary

I'm attempting to create a redirect that has a querystring, and I'm applying the Ignore Case flag so that if the querystring comes through in upper or lower case, it still redirects to the correct place.

### Actual Behavior

If the case does not match the source URL exactly in the querystring portion, Redirection does not see it as a match.

### Steps to reproduce

Create a new redirect with a querystring in the source url.
Attempt to go to that URL with a different case querystring.

### Environment

Browser: Firefox Quantum 66.0.5 (64-bit)
WordPress Version 5.2
Redirection Version 4.2.3, Database Version 4.1

**Comment by johngodley** [comment]
Fixed in 8617dfc5d82002f358dec187156e944f97e0b346 and available here:

https://github.com/johngodley/redirection/releases/tag/4.3-beta-1

Thanks
