### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by troycono** [johngodley/redirection#1761]
```
Plugin: 4.2.3
WordPress: 5.1.1 (single)
PHP: 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
JavaScript: https://zooatlanta.org/wp-content/plugins/redirection/redirection.js
REST API: https://zooatlanta.org/wp-json/

Error: Unable to update redirect (57): Unknown column 'match_url' in 'field list'
Raw: {"code":"redirect","message":"Unable to update redirect","data":{"status":400,"error_code":57,"wpdb":"Unknown column 'match_url' in 'field list'"}}
```
After updating from Version 3.6.3, we are now unable to add or edit any redirections, with the above error message being thrown upon trying.

This issue is NOT happening on our dev instance of this exact same site, which is what has me scratching my head. Wordpress and PHP versions are identical between both environments, but 4.2.3 works perfectly fine on our dev instance, and not at all on live.

Going to have to roll back to 3.6.3 until we receive a response to this ticket.

Thanks in advance for any help you can provide, and please let me know if you need anything else from us here.

**Comment by johngodley** [comment]
Please go to the 'support' page, change the database version to 2.4, and follow the instructions.

**Comment by troycono** [comment]
When you say, "go to the 'support' page," do you mean, within the plugin settings, or on the plugin website?

In either scenario, I don't see a way to "change the database version to 2.4."

Thanks, and sorry if I'm missing something very obvious here...

**Comment by johngodley** [comment]
The support page within the plugin, as found in the top menu:

https://redirection.me/support/getting-started/

**Comment by troycono** [comment]
Sorry John. I'm just not seeing anyway to "change the database version"

![Screen Shot 2019-05-20 at 11 14 34 AM](https://user-images.githubusercontent.com/18485803/58032401-898d7680-7af0-11e9-99f7-17e4a78d9bd4.png)

**Comment by troycono** [comment]
Sorry. I was still looking at the older version of the plugin I had working. Updated to latest, and immediately saw what you were talking about. Changed database version. Problem solved.

Thank you SO MUCH for your extremely fast responses. You're a real pro. Much obliged.
