### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by turhangu** [johngodley/redirection#1765]
```
Uncaught SyntaxError: Invalid or unexpected token https://soyer.com.tr/wp-content/plugins/redirection/redirection.js?ver=4.2.3-832f7155834bcdc64325009360c6273b 17
```

Plugin: 4.2.3
WordPress: 5.2 (single)
PHP: 7.3.5
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
JavaScript: https://soyer.com.tr/wp-content/plugins/redirection/redirection.js
REST API: https://soyer.com.tr/wp-json/

**Comment by johngodley** [comment]
Your redirection.js contains invalid characters. I don't know how they got there, but you should re-install the plugin.

https://soyer.com.tr/wp-content/plugins/redirection/redirection.js

<img width="1342" alt="https___soyer_com_tr_wp-content_plugins_redirection_redirection_js_ver_4_2_3-832f7155834bcdc64325009360c6273b" src="https://user-images.githubusercontent.com/1277682/57982110-cac24f80-7a38-11e9-81fe-81d6316baf01.png">

**Comment by turhangu** [comment]
Thank you johngodley  I will ...
