### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by Jmm001** [johngodley/redirection#1767]
Plugin: 4.2.3
WordPress: 5.2 (single)
PHP: 7.2.17
Browser: Mozilla/5.0 (Linux; Android 8.1.0; itel A32F Build/O11019) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36
JavaScript: https://geektuto.com/wp-content/plugins/redirection/redirection.js
REST API: https://geektuto.com/wp-json/

**Comment by johngodley** [comment]
Please open your browser's developer console and see if there are other errors. This is likely caused by another plugin

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
