### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by lvlupstudios** [johngodley/redirection#1768]
```
Uncaught SyntaxError: Invalid or unexpected token https://www.msphayscloset.com/wp-content/plugins/redirection/redirection.js?ver=4.2.3-832f7155834bcdc64325009360c6273b 17
```

Plugin: 4.2.3
WordPress: 5.2 (single)
PHP: 7.3.5
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
JavaScript: https://www.msphayscloset.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.msphayscloset.com/wp-json/

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any other information is shown?

**Comment by lvlupstudios** [comment]
Hey Jo

> Can you open your browser's developer console and see if any other information is shown?

Hey Jo,
Thanks for replying. I was able to solve the problem. It turns out it was another plugin that was causing the issue. The Redirection plugin is working fine as expected.
