### ISSUE TITLE
Documentation on input patterns

### ISSUE THREAD

**Issue by jdruiter** [johngodley/redirection#177]
Where is the documentation on input patterns accepted?

We are getting strange behaviour with redirects like: 
/via-ferrata/?$

The following questions are pondering me: 
* How is the source url trailing slash handled?
* What regular expression format is accepted? Different styles exist on the web. Some examles would help. E.g. apparently not accepted is: 
Source:  ^/via-ferrata/?$ with a leading ^
Target: //google.com  (// stands for http or https)

**Comment by jamesheazlewood** [comment]
I too would like this.

I spent about an hour trial and error to figure out how to use regex. Found that you can use `/page/(.*)` as the source to redirect to `/new-page/$1` which will keep any params in the URL. But it was only a guess.

**Comment by johngodley** [comment]
It uses PHP's regular expressions, which are fairly standard - http://www.regular-expressions.info/

`^` is supported
`//` isn't a regular expression - it's a browser feature
