### ISSUE TITLE
redirection_groups table problem

### ISSUE THREAD

**Issue by zszymczyk** [johngodley/redirection#1775]
### Summary

Plugin was installed and activated. 
Then after going to: 
/wp-admin/tools.php?page=redirection.php

I see:
WordPress database error: [Table 'XX.wor340_redirection_groups' doesn't exist]
SELECT COUNT(*) FROM wor340_redirection_groups

WordPress database error: [Table 'XXX.wor340_redirection_groups' doesn't exist]
SHOW FULL COLUMNS FROM `wor340_redirection_groups`

WordPress database error: [Table 'XXX.wor340_redirection_groups' doesn't exist]
SHOW FULL COLUMNS FROM `wor340_redirection_groups`

WordPress database error: [Table 'XXX.wor340_redirection_groups' doesn't exist]
SELECT * FROM wor340_redirection_groups LIMIT 1

### Environment

Google Chrome Version 74.0.3729.157 (Official Build) (64-bit)
Wordpress Version 5.2.1

**Comment by johngodley** [comment]
Please go to the support page and see what it says there

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
