### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by ssofnosaj** [johngodley/redirection#1777]
```
Uncaught SyntaxError: Invalid or unexpected token https://www.almostanything.com.au/wp-content/plugins/redirection/redirection.js?ver=4.2.3-832f7155834bcdc64325009360c6273b 17
```

Plugin: 4.2.3
WordPress: 5.2.1 (single)
PHP: 7.2.18
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: https://www.almostanything.com.au/wp-content/plugins/redirection/redirection.js
REST API: https://www.almostanything.com.au/wp-json/

**Comment by johngodley** [comment]
Please open your browser's developer console and see if there are any other errors. This is likely caused by another plugin.

**Comment by ssofnosaj** [comment]
Hi John,

I disabled every other plugin so that Redirection was the only one enabled and still got the same error.

Should I be checking the Developer Console on the home page or the Redirection plugin error page?

On the home page, errors are:

JQMIGRATE: Migrate is installed, version 1.4.1
www-widgetapi.js:106 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://www.almostanything.com.au').
k.C @ www-widgetapi.js:106
util.js:222 Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

On the Redirection error page:

JQMIGRATE: Migrate is installed, version 1.4.1
tools.php?page=redirection.php:348 Uncaught SyntaxError: Invalid or unexpected token
window.onerror @ tools.php?page=redirection.php:348
redirection.js:17 Uncaught SyntaxError: Invalid or unexpected token

Thanks!

**Comment by johngodley** [comment]
How did you install the plugin? When I look at your redirection.js file:

https://www.almostanything.com.au/wp-content/plugins/redirection/redirection.js

I see many instances of this:

<img width="582" alt="https___www_almostanything_com_au_wp-content_plugins_redirection_redirection_js" src="https://user-images.githubusercontent.com/1277682/58752640-7c866500-84aa-11e9-9c5a-8129f1ff1c97.png">

Those black question marks are invalid characters. This indicates that the file is corrupt, and is likely what is causing the error.

If you re-install the plugin it may clear the corruption.

**Comment by ssofnosaj** [comment]
Ah yes - it was part of as migration (using UpdraftPlus I think) - deleting and reinstalling fixed it. Sorry for bothering you, I should have tried that first.

Thanks heaps!
