### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by sanjayhb** [johngodley/redirection#1778]
Plugin: 4.2.3
WordPress: 5.2.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: https://www.studygate.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.studygate.com/wp-json/

**Comment by johngodley** [comment]
Please open your browser developer console and see if any other details are shown. This is likely caused by another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
