### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by binnythap** [johngodley/redirection#1780]
Plugin: 4.2.3
WordPress: 5.2.1 (single)
PHP: 7.0.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: https://www.mysite.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.mysite.com/index.php?rest_route=/

**Comment by johngodley** [comment]
Please open your browser developer console and see if any other details are shown. This is likely an error from another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
