### ISSUE TITLE
Feature Request: Custom capabilities for more access control

### ISSUE THREAD

**Issue by stefanduerrenberger** [johngodley/redirection#179]
As it is at the moment, a user has to have admin rights to change/add redirects and look at 404s. 

I'd like to give my editors access to these pages (but not the plugin options) without giving them full administrator access.

That would be possible by implementing custom capabilities that can then be managed by plugins like Members or User Role Manager.

**Comment by johngodley** [comment]
There is now a filter, please see details on the main description - https://github.com/johngodley/redirection

**Comment by stefanduerrenberger** [comment]
Thank you!
