### ISSUE TITLE
Save regex rules

### ISSUE THREAD

**Issue by webtech-jomase** [johngodley/redirection#1790]
Hello, I'm a guy who does not donate but collaborates reporting errors. Sorry, i'm a poor man.

When i try to save a regex rule with '+' (plus symbol), its save like a " " (space).

Ex.
   ^/(.+)/foo_to_redirect(.*)$
results on
   ^/(. )/foo_to_redirect(.*)$

This has happened since the last week and I have plugins automatic updates. I am solving it from the database but I understand that you would like to correct it if it is a bug.

Thank you very much for your work, it is a very very comfortable and useful plugin.

**Comment by johngodley** [comment]
Fixed in 94f2119863034ecfca733ffd40ff4c13d734b1fb, released in next version
