### ISSUE TITLE
Check Redirect does not support non-standard ports

### ISSUE THREAD

**Issue by emaildano** [johngodley/redirection#1796]
### Summary

When testing a redirect using the `Check Redirect` feature within the redirect list, the check redirect feature does not account for the port number of the site.

### Actual Behavior

For example: If the domain is example.com:8443, and you create a redirect from `/sample-page` to `/new-sample-page` it checks for `example.com/sample-page` and not `example.com:8443/sample-page`

### Steps to reproduce

1. Install WordPress on any non-standard port
2. Create a simple redirect
3. Check the redirect using the `Check Redirect` function

### Screenshot

<img width="1440" alt="Screen Shot 2019-06-05 at 2 51 25 PM" src="https://user-images.githubusercontent.com/1872327/58982433-6f1af480-87a2-11e9-9032-4dd48e50ed9d.png">

**Comment by johngodley** [comment]
Yes, the feature does not allow different ports.

**Comment by emaildano** [comment]
@johngodley, this is a bug? You do support IPv6. Ports are in the same scheme, right?

IMO, it should be a part of the redirect check feature. The redirect does in fact work but it's not clear i the current UI.

**Comment by johngodley** [comment]
For security reasons it intentionally does not support other ports. Maybe in the future, but right now no.
