### ISSUE TITLE
Problem starting Redirection 4.3

### ISSUE THREAD

**Issue by carimi** [johngodley/redirection#1799]
Plugin: 4.3
WordPress: 5.2.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
JavaScript: http://facultymembers.sbu.ac.ir/hosseiny/wordpress/wp-content/plugins/redirection/redirection.js
REST API: http://facultymembers.sbu.ac.ir/hosseiny/wp-json/

**Comment by johngodley** [comment]
Please open your browser's developer console and see if any other information is shown. This is likely caused by another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
