### ISSUE TITLE
Special char / Vowel / Umlaut + regex

### ISSUE THREAD

**Issue by joachimdostal** [johngodley/redirection#1808]
### Summary

regex redirection with vowel/umlaut like:
^/category/Kräuter für die Seele.* -> /category/kraeuter-fuer-die-seele

### Actual Behavior

since 4.3? regex with vowel/umlaut does not trigger redirect. Vowels(+special chars like space) are now shown in the gui decoded with regex (different to the past)

### Steps to reproduce

redirect with vowel(+special chars) (without regex) still works fine:

/category/Kräuter für die Seele -> /category/kraeuter-fuer-die-seele

Shown decoded in the GUI, but encoded in the DB in matched_url field: "/category/kr%c3%a4uter%20f%c3%bcr%20die%20seele"

### Environment

plugin-version: 4.3.1
browser: 
- Version 74.0.3729.169 (Offizieller Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit)
- 67.0.1 (64-Bit) - Firefox

**Comment by johngodley** [comment]
Available in 4.3.2 beta 1 here:

https://github.com/johngodley/redirection/releases/tag/4.3.2-beta-1

**Comment by joachimdostal** [comment]
Thanks a lot for fast fixing.
