### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by seb332** [johngodley/redirection#1811]
```
hi,

Plugin: 4.3.1
WordPress: 5.2.1 (single)
PHP: 7.2.19
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
JavaScript: https://www.drone-ardeche.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.drone-ardeche.com/wp-json/

Error: Unable to add new redirect (58)
Raw: {"code":"redirect","message":"Unable to add new redirect","data":{"status":400,"error_code":58}}
```

**Comment by seb332** [comment]
More details ?

**Comment by johngodley** [comment]
What is the redirect you are trying to add?

**Comment by seb332** [comment]
Hi,

The issue is fixed. The server was temporaly unavailable during trying to add the redirection. Don't know why. I'll submit an other URL if the issue repeats itself.

**Comment by seb332** [comment]
Hi,
The issue repeats it.
/wp-content/uploads/2017/06/Mus%E9e-ferrari-drone-Italie-vid%E9o-photos-TV1-1030
/wp-content/uploads/2018/06/prestataire-drone-en-ard%E8che-1030

but not with https://www.drone-ardeche.com/wp-content/uploads/2017/06/Mus?e-ferrari-drone-Italie-vid?o-photos-TV1-1030 or /wp-content/uploads/2018/06/prestataire-drone-en-ard?che-1030

Best regards.

**Comment by johngodley** [comment]
Is it the same problem?

**Comment by seb332** [comment]
Quite. The API Rest is recomputed during several seconds to see if the blog is still working. It seems that some kind of characters are not well interpretetaded. Example : %E9 %E8 ...

**Comment by johngodley** [comment]
Ok, I understand now what you are saying. Yes, the URL `/wp-content/uploads/2017/06/Mus%E9e-ferrari-drone-Italie-vid%E9o-photos-TV1-1030` is invalid - `%E9` is not a valid encoding. What character are you trying to use?

**Comment by seb332** [comment]
é

**Comment by johngodley** [comment]
You should be able to use that directly in the plugin without encoding. The correct encoding is %C3%A9

**Comment by seb332** [comment]
ok. Thks. Have a nice Sunday.
