### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by julianpm** [johngodley/redirection#1813]
Hello,

I've been using your plugin for some time now and when I upgraded the database it began throwing the errors listed below.

I have gone through all the steps listed here:
https://redirection.me/support/problems/cloudflare/

But nothing resolves this issue. Locally I have upgraded the database with no issues. My WP and PHP versions both exceed the minimum versions required by Redirection.

UPDATE: I downgraded my database, downloaded a backup of the json data, and tried upgrading the DB again. Issue remains.

```
Plugin: 4.3.1
WordPress: 5.2.1 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
JavaScript: https://soapboxhq.com/wp-content/plugins/redirection/redirection.js
REST API: https://soapboxhq.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/log/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment]
Please logout, clear your browser cache, and login in.

**Comment by julianpm** [comment]
I did this and the issue remains.

**Comment by johngodley** [comment]
I am unable to reproduce this problem. If it is possible to access a site where this problem is happening then I can try and track it down. If this is ok then please contact me directly at https://redirection.me/contact/

**Comment by julianpm** [comment]
This issue has now been resolved. Thank you.

**Comment by julianpm** [comment]
Hi the plugin was working and then a couple of days later the same issue recurred.

**Comment by johngodley** [comment]
Ok, please see my comment https://github.com/johngodley/redirection/issues/1813#issuecomment-501977515

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
