### ISSUE TITLE
Redirects Do Not Work if URL Has a Parameter of 0

### ISSUE THREAD

**Issue by jvtcafma** [johngodley/redirection#1819]
### Summary

Any URL that has a parameter of 0 (&param=0) will not redirect.

### Actual Behavior

We have a number of links off of our old site on Google and in other places that end with a final parameter of 0 (e.g. http://www.cazfire.org/index.cfm?Section=10&pagenum=291&titles=0)

When adding a redirect to a URL with any parameter of =0, the redirect will not function. I have tested multiple URLs, and if any single parameter = 0, the redirect will not work.

Here is a copy of the redirect of the above URL

![image](https://user-images.githubusercontent.com/51752005/59359266-e260c100-8ce2-11e9-8dfb-72bb032ec7c9.png)

However, if I simply change the URL to http://www.cazfire.org/index.cfm?Section=10&pagenum=291&titles=1, the redirect works as expected.

### Steps to reproduce

Create a 404 by visiting a non-existent URL and add any parameter that = 0. Add a redirect to that URL and test. Change URL so that no parameters = 0. Add redirect to the 404 and test.

### Environment

Chrome 75.0.3770, Wordpress 5.2.1, Redirection 4.3.1

**Comment by johngodley** [comment]
Fixed in 53d04731ce019f4fb1919610033fb3e670e7c8db, released in the next version

**Comment by jvtcafma** [comment]
Great, thanks! Appreciate your work.
