### ISSUE TITLE
Doesn't work with non-PHP files, even with .htaccess method

### ISSUE THREAD

**Issue by JacobDB** [johngodley/redirection#182]
I'm having an issue trying to redirect a PDF file; the redirect I have configured simply doesn't work. I've double, triple, and quadruple checked everything, and all settings are correct, but still nothing. I tried enabling the Apache .htaccess rewrite method, which correctly output to my .htaccess, but the redirect still isn't happening.

Any ideas why this would be, or how to remedy it? I could just delete the old PDF, which would result in a 404, and therefore allow the PHP redirect to take place, but that's a bit more complicated than it should be.

**Comment by johngodley** [comment]
It's likely that your server is configured such that files that exist will be served directly from Apache before anything else - this makes static files faster.

If your file exists then you will need to delete it first - there's no way round this as it's imposed before Redirection get's chance to do anything.

**Comment by JacobDB** [comment]
Ah, makes sense, thanks much!
