### ISSUE TITLE
Red_Source_Flags not found???

### ISSUE THREAD

**Issue by jjxtra** [johngodley/redirection#1822]
Seeing this in my logs after adding this plugin:

PHP Fatal error:  Class 'Red_Source_Flags' not found 

Any idea where Red_Source_Flags is defined?

**Comment by johngodley** [comment]
It is included in the plugin. The problem is likely that your plugin is not installed properly. Please remove it and re-install.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.

**Comment by jjxtra** [comment]
It was a file permission issue. Some of the include files could not be opened.
