### ISSUE TITLE
Add 'edit_posts' as redirection_role will cause 403 rest_forbidden error

### ISSUE THREAD

**Issue by Twansparant** [johngodley/redirection#1824]
### Summary

When I add `edit_posts` as a custom capability in the `redirection_role` filter (like the FAQ states), accessing the **Redirection** menu will throw `403 rest_forbidden errors` for users with the editor role.

### Actual Behavior
```
Something went wrong 🙁
Je hebt geen toestemming om dat te doen. (rest_forbidden)

Your REST API is probably being blocked by a security plugin. Please disable this, or configure it to allow REST API requests.

REST API: Unavailable
Summary: Your REST API is not working and the plugin will not be able to continue until this is fixed.

Default REST API
URL: http://mydomain.test/wp-json/
rest_forbidden

Raw REST API
URL: http://mydomain.test/index.php?rest_route=/
rest_forbidden

Relative REST API
URL: /wp-json/
rest_forbidden
```

### Steps to reproduce
Add this filter to your **functions.php**:
```php
add_filter( 'redirection_role', function( $role ) {
  return 'edit_posts';
} );
```
And login as editor user and access the `/wp-admin/tools.php?page=redirection.php` plugin page.

### Environment
Redirection Plugin: 4.3.1
WordPress: 5.2.1 (single)
PHP: 7.1.20-1+ubuntu16.04.1+deb.sury.org+1
Browser: Not browser specific

Thanks!

**Comment by johngodley** [comment]
I am unable to reproduce this. Are you running any other plugins that might affect this situation?

**Comment by Twansparant** [comment]
> I am unable to reproduce this. Are you running any other plugins that might affect this situation?

Sorry, I only just read your response! I'm running these plugins:
```
Advanced Custom Fields
Classic Editor
iThemes Security
Soil
W3 Total Cache
WPML Media
WPML Multilingual CMS
WPML String Translation
WPML Translation Management
Yoast SEO
```
But even when I deactivate all of them, the problem persists for me?

The weird thing is, when logged in as an editor user, I can actually access `/wp-json` and it gives me the full REST API response without any errors?

In my console I get these **403** errors when accessing the **Redirection** page:
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
http://mydomain.test/wp-json/redirection/v1/group/?_wpnonce=4effccd579
http://mydomain.test/wp-json/redirection/v1/redirect/?orderby=id&_wpnonce=4effccd579
http://mydomain.test/wp-json/redirection/v1/plugin/test/?_wpnonce=4effccd579
http://mydomain.test/index.php?rest_route=/redirection/v1/plugin/test/&_wpnonce=4effccd579
```
and a `Sorry, you are not allowed to do that` error for this file:
`http://mydomain.test/app/plugins/redirection/redirection.js?ver=4.3.1-76c2e333a0fb0e417d3c1937d0c4045c`

So when I try to access `http://mydomain.test/wp-json/redirection/v1/` I still get a response, but as soon as I try to access the `group`, `redirection` or `plugin` slugs, I get the `Sorry, you are not allowed to do that` response?

These url's are accessible when visiting them as an admin user.
Seems like a problem with the **wpnonce** cookie?

Thanks!

**Comment by johngodley** [comment]
Accessing the `/wp-json/` URLs like that won't necessarily show anything - some require data to be posted.

Using the exact same code you posted the plugin works fine for me when logged in as an editor. The errors seem to indicate this is something specific to your setup. Regardless of which user you are logged in as, accessing `redirection.js` should work fine. The fact it doesn't on yours further indicates a problem specific to your site.

**Comment by Twansparant** [comment]
> The errors seem to indicate this is something specific to your setup.

Thanks for your reply!
You we're right, stupidly I added the `redirection_role` filter in an `is_admin` conditional, which caused the 403's. It works now!
