### ISSUE TITLE
Problem starting Redirection 4.3.1

### ISSUE THREAD

**Issue by jecofish** [johngodley/redirection#1825]
```
SyntaxError: "" literal not terminated before end of script https://thancfoundation.org/wp-content/plugins/redirection/redirection.js?ver=4.3.1-76c2e333a0fb0e417d3c1937d0c4045c 33
```

Plugin: 4.3.1
WordPress: 5.2.1 (single)
PHP: 7.2.18-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0
JavaScript: https://thancfoundation.org/wp-content/plugins/redirection/redirection.js
REST API: https://thancfoundation.org/wp-json/

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any other information is shown?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
