### ISSUE TITLE
Is there a way to make a redirection open in a new TAB or new Window?

### ISSUE THREAD

**Issue by mariosalinas** [johngodley/redirection#183]
I love your product.  I just can't get it to open redirects in new tabs or windows.  Am I missing something?  Is there any setting that I'm missing?  If not, can anyone recommend something that does allow for this?

Thanks,

Mario Salinas

**Comment by johngodley** [comment]
Redirection manages server based redirections, and it's not possible for the server to open links in new tabs. If you want to do that then add `target="_blank"` to your link.
