### ISSUE TITLE
Missing regex \+ (plus escaping)

### ISSUE THREAD

**Issue by warrenwhipple** [johngodley/redirection#1833]
Regex plus escaping stopped working.
Misses `^/cat\+.jpg`
But catches other escaping `^/cat\~.jpg` no problem.

**Comment by johngodley** [comment]
What URL are you trying to match?

**Comment by warrenwhipple** [comment]
I had been redirecting some old Plone theme URLs that another server was pointed at. For example
```
/portal_css/som.SOMTheme/++theme++SOMTheme/css/theme.css
/portal_javascripts/som.SOMTheme/++theme++SOMTheme/js/bootstrap.min.js
```
and similar. It's a temporary duct tape job migration from Plone to WP. The original regex match replace was
```
^/.+/\+\+theme\+\+SOMTheme/(.+)
https://www.example.net/www/++theme++SOMTheme/$1
```
Pointed at the remaining Plone server. This was working at some point. But WordPress and/or your plugin got upgraded out from under me. Sorry I can't be more specific, I'm not doing the upgrades or even being informed of them... But the regex redirect broke. I created a workaround with
```
^/.+/..theme..SOMTheme/(.+)
https://www.example.net/www/++theme++SOMTheme/$1
```
So I'm good. But the escaping `\+` match miss looked like a bug to me so I thought you'd like to know.

[Working `\+` example on regex101](https://regex101.com/r/IyNCYw/1)

**Comment by warrenwhipple** [comment]
Though I'm not sure which WP + Redirection versions did work before... I can tell you on fresh install of WP 5.2.2 and Redirection plugin 4.3.1:

This regex redirect
```
^/hello\+world
to
/
```
fails to catch https://whippress.com/hello+world

While this regex redirect
```
^/hello\.world
to
/
```
is good to catch https://whippress.com/hello.world

**Comment by johngodley** [comment]
Ok, that's great - thanks for the extra details. I'll look into this more

**Comment by johngodley** [comment]
This should be fixed in https://github.com/johngodley/redirection/releases/tag/4.3.2-beta-1
