### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by GreenixMKTG** [johngodley/redirection#1834]
```
Plugin: 4.3.1
WordPress: 5.2.1 (single)
PHP: 7.3.6
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
JavaScript: https://www.lswrep.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.lswrep.com/wp-json/

Error: Unexpected end of JSON input (SyntaxError)
Raw: -no data-
```

**Comment by johngodley** [comment]
Are you running a security plugin?

**Comment by GreenixMKTG** [comment]
Hi John.
I am now, but don't recall if I was at the time. ithemes security. Your plugin along with that one is included in my standard revamp setup, so no other problems on other websites.

Thanks!

**Comment by johngodley** [comment]
This kind of message is usually associated with a security plugin blocking your WordPress REST API. If you have it working on one site and not the other then I would look for the differences between the two.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
