### ISSUE TITLE
Problem starting Redirection 4.3.1

### ISSUE THREAD

**Issue by fherny** [johngodley/redirection#1835]
Plugin: 4.3.1
WordPress: 5.1.1 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: https://botach.net/wp-content/plugins/redirection/redirection.js
REST API: https://botach.net/wp-json/

**Comment by johngodley** [comment]
Try accessing this file:

https://botach.net/wp-content/plugins/redirection/redirection.js

`Forbidden
You don't have permission to access /wp-content/plugins/redirection/redirection.js on this server.
Server unable to read htaccess file, denying access to be safe`

**Comment by fherny** [comment]
I get a 403 error, I clear the cache and still the same issue.

**Comment by johngodley** [comment]
Ok. But you'll still need to fix the problem. It does not appear to be caused by Redirection.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
