### ISSUE TITLE
Redirection old site to new site issue

### ISSUE THREAD

**Issue by jwyeung** [johngodley/redirection#1837]
Hi
I migrated to a new domain with my original content and pages/posts. So I'm redirecting www.thestandarddrink.com to www.thestandarddrink.com.au using wildcard so that every old page and post, will redirect to the same page or post on the new domain:

Source: ^/(.*)
Target: https://www.thestandarddrink.com.au/$1/
Regex

However, I still need to ocassionally get into the backend of the old wordpress site, so I entered a redirect for the old site/wp-admin when matched do nothing, and positioned it as 0 to take priority before the above wildcard redirect. 

This caused a major error i the plugin, and I was not able to bring up the /wp-admin page. I was going to send error message, but the page shut down at that point. Sorry there was no time to grab a screen shot. Fortunately, there was still a tab open with backend admin access, and I found the plugin seemed to have automatically deleted that wildcard redirect to get rid of the error. 

Could you tell me what I did wrong and what redirect approach I should use to achieve what I need?

Thanks

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Using chrome, Version 74.0.3729.169 (Official Build) (64-bit)
Wordpress 5.2.1
Redirection plugin Version 4.3.1

**Comment by johngodley** [comment]
What do you mean by major error? The plugin has no feature to automatically delete things to get rid of errors.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
