### ISSUE TITLE
importer doesn't work

### ISSUE THREAD

**Issue by amitai52** [johngodley/redirection#184]
Tried .htaccess format, and CSV
neither works.

- .htaccess imports the last 2 items from this line:
http://localhost/haipo/test1/article/67	[R=301,NC,L]
which is wrong, the target doesn't even make sense

- CSV says it imported - but really did nothing

D

**Comment by leepeterson** [comment]
Same for me. Says 70 imported, one of which was the table header with two columns "old" and "new" and only 1 redirect was created for "old" which redirects to "new".

**Comment by johngodley** [comment]
Using version 2.6 I've tried importing from both a CSV and it worked, although the redirect code wasn't set correctly - this will be fixed soon. A .htaccess file imported fine.

If you have a file that doesn't import can you make it available somewhere online and I'll add whatever is special into the unit tests.

Thanks!

**Comment by Simongreen123** [comment]
I have a similar issue, 
3 test lines but only 1 imported.
attached is a test file. 
[testredirect.csv.zip](https://github.com/johngodley/redirection/files/1050089/testredirect.csv.zip)

**Comment by johngodley** [comment]
Thanks @Simongreen123 - it seems to be a line ending problem. I'm not sure where the CSV is generated from, but the line endings make it appear a single line. I've added something in #204 which should fix it for CSV

**Comment by Simongreen123** [comment]
File created with Excel for Mac.  Sorry not sure exactly what you mean,  do i have to add code to my install to get it to work ?

**Comment by johngodley** [comment]
I think I've fixed the problem in the development version of the plugin here - you can download it and try, if you want. The version here will eventually be released on wordpress.org

**Comment by Simongreen123** [comment]
Thanks, worked out how to update the CSV.php file and yes it is working.   One other thing, as i was testing the import, it duplicated the import as i processed the same file a few times.   however the click statistics only applies to first row created even when all the other duplicated lines are the same. 
 If you delete the  duplicated line that contains the current stats, the remaining lines will no longer measure stats.  Is there a way to Overwrite if there is an existing link the same ? 
See attached screen  - link name PNWM
![screen shot 2017-06-04 at 5 19 56 pm](https://cloud.githubusercontent.com/assets/29170430/26759734/4781b744-494a-11e7-9617-9728fe51d798.png)

**Comment by johngodley** [comment]
Closing as fixed. There's a ticket for duplicate rules at #82
