### ISSUE TITLE
Monitor media replace action

### ISSUE THREAD

**Issue by webmaster-cob** [johngodley/redirection#1841]
### Summary

When using Enable Media Replace plugin to upload a PDF over an existing PDF with the option to use a new file name and update links, a redirect isn't created. It would be great to have an option for Redirection to monitor the Media Library so select file types have redirects automatically created for them if they're renamed. While the rename process updates links on the site, other  external links to PDFs won't get redirected (e.g. Google search index, links on other sites, etc.). It's likely this isn't needed for images, MP3s, etc. But it could be configured by file type if that kind of granularity is desired. This really stems from a practical need to replace PDFs with different file names often. 

### Steps to reproduce

- Install Enable Media Replace plugin. 
- Upload a PDF into the Media Library
- Use the Replace Media option for the PDF in the Media Library
- Select a second PDF with a different name than the first to upload
- Choose the "Replace the file, use new file name and update all links" option

Result is no redirect is created.

### Environment

WordPress 5.2.2
Redirection 4.3.1

Thanks for considering this enhancement request.

**Comment by johngodley** [comment]
What is the enabled media replace plugin?

**Comment by webmaster-cob** [comment]
The [Enable Media Replace](https://wordpress.org/plugins/enable-media-replace/) plugin allows you to upload a file over an existing file in the WordPress Media Library. It gives you two options - replace and keep the same file name and replace and update file name. The desired behavior would be to have a redirect created if the file name is updated. The Enable Media Replace plugin as over 300,000 installs, so is in broad use.

**Comment by johngodley** [comment]
Moving to #3349
