### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by lobamo** [johngodley/redirection#1843]
```
Plugin: 4.3.1
WordPress: 5.1.1 (single)
PHP: 7.3.6
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
JavaScript: http://dc01psrvweb01v.atempo.com/wp-content/plugins/redirection/redirection.js
REST API: http://dc01psrvweb01v.atempo.com/index.php?rest_route=/

Error: Failed to fetch
```
Hi, I have an issue with the plugin redirection. it appears to redirect the website to https as soon as I activate the plugin. so the api files can't be fetched properly. 
My site_url and home are set to  http://dc01psrvweb01v.atempo.com/ . It's a web server I did a migration yesterday from a production website. 
it also show me the error on google net::err_connection_refused. If someone has a clue of where the issues come from please let me know.

**Comment by johngodley** [comment]
Have you enabled the 'force https' option?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
