### ISSUE TITLE
with / or without and plugin failure - redirects emptied...

### ISSUE THREAD

**Issue by vguadalupe** [johngodley/redirection#1848]
Hi, we just recover from a plugin failure and all my redirects got emptied. I'm trying to import from my dev environment but the plugin tell me that import 0 registers from that export file. 
However, in other sites we noticed that with the new update all our redirects finished with / discriminates of the redirects without /. and all our redirects starts to fail.

Please how can I fix by one side the import or recover the redirects of the plugin failure, and the other side the / in other redirects.

Thanks in advance...

**Comment by johngodley** [comment]
What was the plugin failure? Can you include the export file? What do you mean by 'finished with / discriminates of the redirections with /'?

**Comment by vguadalupe** [comment]
Hi, finished with /, I'm talking of the URL. and 

[export.zip](https://github.com/johngodley/redirection/files/3315977/export.zip)

**Comment by vguadalupe** [comment]
the plugin failure just tell us that we have to switch the API but none worked, today we noticed that the plugin ask for a initial configuration but all data was cleared.

**Comment by johngodley** [comment]
Sorry, I don't understand what you are asking. The export file contains redirects and imports ok.

**Comment by vguadalupe** [comment]
The plugin just crashed then the plugin itself ask me to choose another API, this didn't fix anything till the update, when I updated the plugin all my redirections dissapeared and the plugin ask me to complete the initial set-up.
when this happend I put a buckup in my developers environment to get the file that I sent to you but, I'm trying to import the file but in my site just imports one entry.

**Comment by johngodley** [comment]
Ok, so it didn't crash it just showed an error message. How are you importing the file?

**Comment by vguadalupe** [comment]
just drag n drop the file in the importer of the redirection plugin

**Comment by vguadalupe** [comment]
so, can you help me to review why I can't import the file?

**Comment by johngodley** [comment]
What is the error message?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
