### ISSUE TITLE
Geo IP error

### ISSUE THREAD

**Issue by jim-moe** [johngodley/redirection#1850]
Wordpress 5.2.2
Redirection 4.3.1
Firefox v60.7.0

in 404s list, whenever I select "Filter by IP", or click on an IP, I receive the error:

Geo IP Error
Something went wrong obtaining this information
NetworkError when attempting to fetch resource.

For instance, <https://redirect.li/map/?ip=66.249.79.245> produces the above error message.

What is required to have this feature perform?

**Comment by johngodley** [comment]
https://redirect.li/map/?ip=66.249.79.245 is working fine, as is the IP feature in Redirection.

Have you blocked the redirect.li website?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
