### ISSUE TITLE
Cancel Redirect for Logged in users

### ISSUE THREAD

**Issue by desweisen** [johngodley/redirection#1857]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

Hello, awesome plugin, thank you! How do I cancel the redirect for logged in users, or a logged in admin user to be more specific? I am using your plugin to redirect anyone who comes to the site to a mailchimp landing page (not using a coming soon plugin) and the mailchimp landing page has it's own URL. So I used your plugin to redirect all traffic to that page while building the new site.

Right now, whiel I'm logged into the back end of WordPress and I go to the main URL to try and see changes on pages (home page for example) it redirect to the Mailchimp landing page and I need to see the home page edits I'm making.

So I would like it to recognize that I'm an admin, logged in, and need to see home page URL, NOT the redirect URL....

Thank you so much!

Chrome browser: 75.0.3770.100 (Official Build) (64-bit)
WordPress: 5.2.2
Windows 10 64 bit
Redirection version: 4.3.1

**Comment by johngodley** [comment]
You can create a 'do nothing' redirect for admin users. This will prevent any further redirects taking place.

https://redirection.me/support/redirect-actions/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
