### ISSUE TITLE
error cuando direcciono

### ISSUE THREAD

**Issue by Orbitapps** [johngodley/redirection#186]
Buena tarde, estoy creando un sitio en Wordpress con la plantilla DIVI, esta tiene un modulo que se llama portafolio, el cual me solicita crear un proyecto para cada item, estoy usándolo para crear un carrusel con el logo de mis aliados, pero la idea es que al hacer clic sobre cada logo me lleve al sitio de mi aliado, pero no es así, me lleva a la pagina interna de mi sitio que corresponde al proyecto. 

Es por esto que estoy usando "redirection", pero no se si estoy haciendo algo mal en la configuracion, pues al dar clic sobre el logo, me sale el siguiente error "Request-URI Too Long - The requested URL's length exceeds the capacity limit for this server. - Additionally, a 414 Request-URI Too Long error was encountered while trying to use an ErrorDocument to handle the request."

Esta es la url que me genera, en la que me aparece el error: http://ciev.orbitapps.co/index.php/project/acien/www.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/www.aciemvalle.org/portal/index.phpwww.aciemvalle.org/portal/index.php

Anexo dos imágenes, en la primera muestra la configuración que tengo y en la otra la pantalla de error:

![config](https://cloud.githubusercontent.com/assets/27022354/24812464/cdd280aa-1b8f-11e7-8ae3-9c9f095eab3c.png)

![error](https://cloud.githubusercontent.com/assets/27022354/24812483/d676022c-1b8f-11e7-8272-a8d78f6e88bb.png)

**Comment by johngodley** [comment]
You have created an infinite redirect. Disabled the 'regular expression' option otherwise it will continue to match itself each time it is redirected.
