### ISSUE TITLE
Regex backreference strips out spaces in url

### ISSUE THREAD

**Issue by jwsopko** [johngodley/redirection#1860]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

Using the following regex:

^/xcms/(.*)
https://www.cs.unc.edu/xcms/$1

And a url with spaces:
https://cs.unc.edu/xcms/wpfiles/graduate-program/student-progress/CS-04%20MS%20Outside%20Review%20Option.pdf

the redirect backreference strips out the spaces:

https://www.cs.unc.edu/xcms/wpfiles/graduate-program/student-progress/CS-04MSOutsideReviewOption.pdf

Please list your browser, browser version, version of WordPress and Redirection plugin.
Fails on latest chrome and firefox.
Wordrpes 5.2.1, Our campus hosts multi-site Wordpress and manages the plugins, I do not see a version of the plugin on the settings page and don't have access to the server. I attached a screen shot from the plugin support page. Thanks for you help.

<img width="785" alt="backref" src="https://user-images.githubusercontent.com/52323654/60348627-f9afd780-998d-11e9-81fb-8115cbfd7695.png">

<img width="767" alt="redirect-err" src="https://user-images.githubusercontent.com/52323654/60348504-b190b500-998d-11e9-8d4d-180989ccd120.png">

**Comment by jwsopko** [comment]
I checked with the maintainers of our Wordpress site, we are running the latest Redirect 4.3.1 plugin.

**Comment by johngodley** [comment]
Yes, the plugin does not currently URL encode the target. This will be added in the next major version.

**Comment by jwsopko** [comment]
Thanks!


On Sat, Aug 3, 2019 at 11:15 AM John <notifications@github.com> wrote:
>
> Yes, the plugin does not currently URL encode the target. This will be added in the next major version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
John W. Sopko Jr.
University of North Carolina
Computer Science Dept CB 3175
Chapel Hill, NC 27599-3175

Fred Brooks Building; Room 140
Computer Services Systems Specialist
email: sopko AT cs.unc.edu
phone: 919-590-6144

**Comment by ooker777** [comment]
when will it release?

**Comment by johngodley** [comment]
Fixed in 3cc1624fc8c78ce42948458fc7303b6c4a8827ec, released in next version

**Comment by ooker777** [comment]
I wonder why only the encoding character of space (`%20`) is stripped? Other punctuations, symbols, and unicode characters' encoding are fine
