### ISSUE TITLE
Problem starting Redirection 4.3.1

### ISSUE THREAD

**Issue by Happy-Flow** [johngodley/redirection#1862]
Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.2.19
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
JavaScript: https://happyflow.pt/wp-content/plugins/redirection/redirection.js
REST API: https://happyflow.pt/wp-json/

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any other information is shown? This is probably caused by another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
