### ISSUE TITLE
Problem starting Redirection 4.2.3

### ISSUE THREAD

**Issue by Steno753** [johngodley/redirection#1865]
```
SyntaxError: illegal character https://microbiologiemedicale.fr/wp-content/plugins/redirection/redirection.js?ver=4.2.3-832f7155834bcdc64325009360c6273b 17,SyntaxError: illegal character https://microbiologiemedicale.fr/wp-content/plugins/google-analytics-for-wordpress/lite/assets/vue/js/chunk-vendors.js?ver=7.7.1 14
```

Plugin: 4.2.3
WordPress: 5.2.2 (single)
PHP: 7.2.18
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
JavaScript: https://microbiologiemedicale.fr/wp-content/plugins/redirection/redirection.js
REST API: https://microbiologiemedicale.fr/wp-json/

**Comment by johngodley** [comment]
The message describes the problem - your redirection.js file contains illegal characters.

<img width="1151" alt="https___microbiologiemedicale_fr_wp-content_plugins_redirection_redirection_js_ver_4_2_3-832f7155834bcdc64325009360c6273b" src="https://user-images.githubusercontent.com/1277682/60516720-38b79300-9cd6-11e9-86c9-51c0cd098e7a.png">

You will need to fix this, possibly by re-installing the plugin.

**Comment by Steno753** [comment]
Hi,

I don't understand why this plugin don't work since this morning.
Coul you help me ?

Best regards

**Comment by Steno753** [comment]
I re-install it but that's not change

**Comment by johngodley** [comment]
The file is now no longer corrupt. You should clear your browser cache.
