### ISSUE TITLE
URL redirects to wrong URL

### ISSUE THREAD

**Issue by MarketingEbike4Delivery** [johngodley/redirection#1866]
We want to redirect an URL to our new URL. We've entered the redirect the same way we did the other URL's, but when we save it, it places /de before https://. So the URL looks like this:

/dehttps://www.ebike4delivery.nl/service/ 

It should be: https://www.ebike4delivery.de/service

When you visit the link, you get: 
![Github_3](https://user-images.githubusercontent.com/52289443/60520403-999a9780-9ce5-11e9-8009-938cdc5dc6e6.jpg)

In our editing field we (of course) only entered https://. 

We deleted the redirection and entered it again, but that didn't work.

How do we get rid of the /de before the https://? 

See the screenshots:
![Github_1](https://user-images.githubusercontent.com/52289443/60519917-c4d0b700-9ce4-11e9-96de-90df77d6b42a.jpg)
![Github_2](https://user-images.githubusercontent.com/52289443/60520038-fa75a000-9ce4-11e9-8132-4e1d77b5fb2f.jpg)

_Our Wordpress is up-to-date. We do use the WPML translation plug-in and WP forms on this page._

**Comment by johngodley** [comment]
The `de` is the country code for Germany. You say you are using WPML so it is likely it is adding the `de`. You will need to stop it doing that

**Comment by MarketingEbike4Delivery** [comment]
@johngodley I can't stop using the plug-in, because I have other URL's that do redirect correctly to the other URL's. If I delete the plug-in I lose the other redirections.

**Comment by johngodley** [comment]
Sure, I'm not saying stop using the plugin. But if WPML is breaking a redirect then it is not functioning correctly. Redirection does not randomly add country codes to redirects. WPML is a plugin that is involved with country codes. If you disable WPML and clear your browser cache you should see the redirect work. If that is the case then you will need to contact WPML and ask them to fix the bug.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
