### ISSUE TITLE
Example using PHP API

### ISSUE THREAD

**Issue by emaildano** [johngodley/redirection#1867]
### Summary

Do you have an example of how to use the Redirection PHP API? I'm trying to use [this](https://github.com/johngodley/redirection/blob/1f4f1a68d850f81c52416c42aa7cfd958041ada1/models/file-io.php#L70).

I want to write a custom plugin that will export the redirects as JSON to a directory within WordPress.

Something like this:

```
function export_redirects() {
  Red_FileIO::export();
}

add_action( 'redirection_save_options', 'export_redirects' );
```

### Notes

I do prefer to use the WP REST API but most of my dev environments are using a self-signed cert which is difficult to authenticate with. The PHP API should work fine and in both cases.

**Comment by johngodley** [comment]
All current information is available here:

https://redirection.me/developer/

You can call the REST API internally by using `rest_do_request `. It doesnt make HTTP requests so you wont need to be authenticated and certs don't apply.

**Comment by emaildano** [comment]
Thank you! `rest_do_request` was exactly what I was looking for.

For reference, if anyone is doing something similar here's a working example so far.

```
public function get_redirects() {
		$request  = new WP_REST_Request( 'GET', '/redirection/v1' );
		$response = rest_do_request( $request );

		if ( $response->is_error() ) {
			$message    = $response->get_error_message();
			$error_data = $response->get_error_data();
			wp_die( esc_html( printf( '<p>An error occurred: %s (%d)</p>', $message, $error_data ) ) );
		}

			$data = $response->get_data();
			return $data;
	}

	public function save_redirects() {

		$upload_dir = wp_get_upload_dir();
		$file       = $upload_dir['basedir'] . '/redirects.json';
		$dirname    = dirname( $save_path );
		$data       = self::get_redirects();
		$data_json  = json_encode($data);

		if ( ! is_dir( $dirname ) ) {
			mkdir( $dirname, 0755, true );
		}

		file_put_contents( $file, print_r( $data_json, true ) );

	}
```
