### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by shaileshbizspice** [johngodley/redirection#1869]
```
Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
JavaScript: http://petersonwashandblast.com/wp-content/plugins/redirection/redirection.js
REST API: http://petersonwashandblast.com/wp-json/

Error: Invalid parameter(s): page (rest_invalid_param)
Action: redirection/v1/redirect/?orderby=id GET
Code: 400 Bad Request
Raw: {"code":"rest_invalid_param","message":"Invalid parameter(s): page","data":{"status":400,"params":{"page":"page is not of type integer."}}}
```

and also this one

Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
JavaScript: http://petersonwashandblast.com/wp-content/plugins/redirection/redirection.js
REST API: http://petersonwashandblast.com/wp-json/

Error: Invalid parameter(s): page (rest_invalid_param)
Action: redirection/v1/group/ GET
Code: 400 Bad Request
Raw: {"code":"rest_invalid_param","message":"Invalid parameter(s): page","data":{"status":400,"params":{"page":"page is not of type integer."}}}

Getting these errors after upgrading the plugin

[Lightshot screenshot.pdf](https://github.com/johngodley/redirection/files/3361551/Lightshot.screenshot.pdf)

**Comment by johngodley** [comment]
Can you click the 'screen options' in the top right corner of the page, and set a number there?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
