### ISSUE TITLE
Missing user agent check. Gives Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by essensx** [johngodley/redirection#187]
redirect.php:349 line, gives `Undefined index: HTTP_USER_AGENT`. Need to add isset shorthand statement, because of possibility user agent is not set.

Full line: 	`$log = RE_Log::create( $url, $target, $_SERVER['HTTP_USER_AGENT'], $ip, isset( $_SERVER['HTTP_REFERER'] ) ? $_SERVER['HTTP_REFERER'] : '', array( 'redirect_id' => $this->id, 'group_id' => $this->group_id ) );`

**Comment by johngodley** [comment]
This should be fixed in 2.6
