### ISSUE TITLE
Problem starting Redirection 4.3.1

### ISSUE THREAD

**Issue by rogerperkin** [johngodley/redirection#1880]
```
Uncaught SyntaxError: Invalid or unexpected token https://www.rogerlapin.co.uk/wp-content/plugins/redirection/redirection.js?ver=4.3.1-76c2e333a0fb0e417d3c1937d0c4045c 33
```

Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.2.19
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
JavaScript: https://www.rogerlapin.co.uk/wp-content/plugins/redirection/redirection.js
REST API: https://www.rogerlapin.co.uk/wp-json/

**Comment by johngodley** [comment]
Your plugin is corrupt. If you look at this file https://www.rogerlapin.co.uk/wp-content/plugins/redirection/redirection.js?ver=4.3.1-76c2e333a0fb0e417d3c1937d0c4045c you will see corrupt characters:

<img width="548" alt="https___www_rogerlapin_co_uk_wp-content_plugins_redirection_redirection_js_ver_4_3_1-76c2e333a0fb0e417d3c1937d0c4045c" src="https://user-images.githubusercontent.com/1277682/61202807-79ed7100-a6e0-11e9-9345-706dbfce1c96.png">

Try reinstalling the plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
