### ISSUE TITLE
Redirect is not working for a given PHP file 

### ISSUE THREAD

**Issue by lengyelkatalin** [johngodley/redirection#1881]
hello,
we relaunched our website in WP just yesterday, and face some problems in case of certain redirections.

eg,:
old link: [https://lurkovilag.hu/index-mob.php?c=1388](url)
new link should be: [https://lurkovilag.hu](url)

**Our present setting in Redirection plugin is:**
![image](https://user-images.githubusercontent.com/52953209/61276516-7c1f0080-a7b0-11e9-83e1-dc2081ba4a4e.png)

Can it be managed somehow? All our trials go to 404 error page:

![image](https://user-images.githubusercontent.com/52953209/61276616-ab357200-a7b0-11e9-94ff-677600514797.png)

**Comment by johngodley** [comment]
That error page is not part of WordPress, and so Redirection is not able to run. You will need to reconfigure your server to allow 404s to go through to WordPress. This is similar to the problem described here:

https://redirection.me/support/faq/#pdf

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
