### ISSUE TITLE
sometimes it does not work

### ISSUE THREAD

**Issue by jheerce** [johngodley/redirection#1887]
sometimes it does not work

**Comment by johngodley** [comment]
I'll need a lot more information than that. What doesn't work? What times? How doesn't it work?

**Comment by jheerce** [comment]
sometimes the redirects do not work but sometimes it works, as in print.


Em sex, 19 de jul de 2019 às 17:43, John <notifications@github.com<mailto:notifications@github.com>> escreveu:

I'll need a lot more information than that. What doesn't work? What times? How doesn't it work?

**Comment by johngodley** [comment]
Again I will need a lot more information.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
