### ISSUE TITLE
The property WP_API_nonce is undefined

### ISSUE THREAD

**Issue by Dacobah** [johngodley/redirection#1888]
### Summary

The javascript can't find Redirectioni10n.api object so the plugin returns me an error.

### Actual Behavior

In wp-admin/tools.php?page=redirection.php it returns me an error `TypeError: Cannot read property 'WP_API_nonce' of undefined`

In the redirection.js file, the plugin is looking for a Redirectioni10n.api object but when you test Redirectioni10n you can see there is no "api" property. Instead, you can access directly to WP_API_nonce.

That's why redirect plugin returns me an error `TypeError: Cannot read property 'WP_API_nonce' of undefined`

### Environment

Plugin: 4.3.1
WordPress: 5.1.1 (multi)
PHP: 7.2.20-1+0~20190710.23+debian9~1.gbp2428c5
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
JavaScript: /fr/wp-content/plugins/redirection/redirection.js
REST API: /fr/wp-json/
Buster: 4.3.1 === 4.3.1

**Comment by johngodley** [comment]
That suggests you are using an older version of the plugin. Is your site cached in anyway?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
