### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by amarichev** [johngodley/redirection#1893]
Plugin: 3.0.1
WordPress: 4.8.9
PHP: 7.1.25
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

Error: Unexpected token < in JSON at position 0
Action: redirection/v1/redirect?orderby=id GET
Code: 404 Not Found
Raw:
[error.txt](https://github.com/johngodley/redirection/files/3425827/error.txt)

**Comment by johngodley** [comment]
The error message shows the problem - your WordPress REST API does not exist:

http://www.tonus.nnov.ru/wp-json/

**Comment by amarichev** [comment]
Thanks!
