### ISSUE TITLE
Redirect everything after slash

### ISSUE THREAD

**Issue by Webmyday1** [johngodley/redirection#1896]
To help track problems please follow this template. If you can provide screenshots then that will help.

Redirect everything behind a slash

### Summary

This is the situation I want to create:
I have a lot of pages under /product-categorie/onderdelen/*
I want to redirect them all (350) to 1 new page. How can I do this in the Redirection plug-in. Regex is not explained that well in the plug-in.

### Steps to reproduce

I want to know them.

### Environment

Latest Wordpress version

**Comment by johngodley** [comment]
You can find more details about regular expressions here:

https://redirection.me/support/redirect-regular-expressions/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
