### ISSUE TITLE
Cannot create or make changes to redirects

### ISSUE THREAD

**Issue by djmonzyk** [johngodley/redirection#1897]
I already have 63 redirects working just fine.

### Summary

I click to Add New redirect.  I put in the redirect information and click save.

### Actual Behavior
The interface shows a confirmation that it was saved, but it is not actually saved.

I also cannot delete or edit any existing redirects. When I edit and save, or try to delete, or import redirects, I get an error. *No route was found matching the URL and request method (rest_no_route)*

Here is the more robust error content.
`Plugin: 4.3.1
WordPress: 5.2.2 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
JavaScript: /wp-content/plugins/redirection/redirection.js
REST API: https://kbmax.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/redirect/51/ POST
Params: {"id":51,"url":"^/.*","title":"","match_data":{"source":{"flag_regex":true,"flag_trailing":true,"flag_case":true,"flag_query":"exact"}},"match_type":"server","action_type":"url","position":34,"group_id":3,"action_code":301,"action_data":{"server":"https://blog.kbmax.com","url_from":"/blog","url_notfrom":""}}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}`

The "Plugin status" comes back clean, Rest API and all items in Plugin status are green/Good.

### Environment
Tested in Chrome and Firefox with same result. Running WP v5.22 and Redirects v4.3.1

**Comment by djmonzyk** [comment]
I just thought of one environmental change I made last week that I should probably mention, I have no idea if it would impact Redirection plugin.

This WP env is running on Azure with PHP hosted in IIS.  I had recently put this entry into the web.config (equivalent to Apache's .htaccess) that has the following rule, to redirect from any URL with a trailing slash, to remove the trailing slash (301 redirect).

<rule name="Remove trailing slash" stopProcessing="true">
     <match url="(.*)/$" ignoreCase="true" />
         <conditions>
               <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Redirect" redirectType="Permanent" url="{R:1}" />
</rule>

**Comment by johngodley** [comment]
That is a probable cause of the error - your WordPress REST API is being redirected, which could cause problems:

https://kbmax.com/wp-json/ => https://kbmax.com/wp-json

**Comment by djmonzyk** [comment]
Wow.  Good insight, and super fast response, thank you!  Now I need to figure out how to create an exception to that rule in my web.config and test it.  I will let you know what I find out.  THANK YOU!
