### ISSUE TITLE
Problem starting Redirection 3.6.3

### ISSUE THREAD

**Issue by Batin63** [johngodley/redirection#1898]
```
Uncaught SyntaxError: Invalid or unexpected token https://www.capvacances.fr/wp-content/plugins/redirection/redirection.js 33
```

Plugin: 3.6.3
WordPress: 5.2.2 (single)
PHP: 7.3.7
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
JavaScript: https://www.capvacances.fr/wp-content/plugins/redirection/redirection.js
REST API: https://www.capvacances.fr/wp-json/

**Comment by johngodley** [comment]
Your file https://www.capvacances.fr/wp-content/plugins/redirection/redirection.js is corrupted:

![https___www_capvacances_fr_wp-content_plugins_redirection_redirection_js](https://user-images.githubusercontent.com/1277682/61953619-c4a79c80-afae-11e9-8e78-ec32a8462c36.jpg)

You should re-install the plugin.
