### ISSUE TITLE
Better handling of encoded URLs in redirects

### ISSUE THREAD

**Issue by johncrenshaw** [johngodley/redirection#19]
Redirection sometimes fails for URLs that should successfully redirect when portions of the URL have been encoded. There's also a need to handle '?' more intelligently sometimes in the redirects (yes, I know this is a totally invalid to include in the URL in this way, but not everyone publishing content online is savvy enough to get it right every time) This small tweak for Red_Item::get_for_url addresses both issues.

```
    $sql = $wpdb->prepare( "SELECT @redirection_items.*,@redirection_groups.tracking,@redirection_groups.position AS group_pos,@redirection_modules.id AS module_id FROM @redirection_items INNER JOIN @redirection_groups ON @redirection_groups.id=@redirection_items.group_id AND @redirection_groups.status='enabled' INNER JOIN @redirection_modules ON @redirection_modules.id=@redirection_groups.module_id AND @redirection_modules.type=%s WHERE( @redirection_items.regex=1 OR @redirection_items.url=%s)", $type, $url );
```

Becomes:

```
    $sql = $wpdb->prepare( "SELECT @redirection_items.*,@redirection_groups.tracking,@redirection_groups.position AS group_pos,@redirection_modules.id AS module_id FROM @redirection_items INNER JOIN @redirection_groups ON @redirection_groups.id=@redirection_items.group_id AND @redirection_groups.status='enabled' INNER JOIN @redirection_modules ON @redirection_modules.id=@redirection_groups.module_id AND @redirection_modules.type=%s WHERE( @redirection_items.regex=1 OR @redirection_items.url=%s OR @redirection_items.url=%s OR @redirection_items.url=%s)", $type, $url, urldecode($url), str_replace('?', '', urldecode($url)));
```

**Comment by johngodley** [comment]
I know this is a few years old but just adding a note that currently you need to manually encode special characters in the URL when you create the redirect.

Adding the `urldecode` works fine, but will break existing encoded URLs - this could affect a lot of people.

I intend to fix this properly, but it's a little more complicated than it initially seems.

**Comment by PoundXI** [comment]
> I know this is a few years old but just adding a note that currently you need to manually encode special characters in the URL when you create the redirect.
> 
> Adding the `urldecode` works fine, but will break existing encoded URLs - this could affect a lot of people.
> 
> I intend to fix this properly, but it's a little more complicated than it initially seems.

Can you add encoding tool to your plugin ? It's may help users to know non-english url must be encoding.

eg. Adding auto encode checkbox. [ / ] check this if your url is not in english or have any symbols.

**Comment by johngodley** [comment]
Support has been added in [4.3 alpha 1](https://github.com/johngodley/redirection/releases/tag/4.3-alpha-1), which will be released at some point in the future. Please let me know how it goes.

Closing this issue as complete.
