### ISSUE TITLE
Log Files Not Generating

### ISSUE THREAD

**Issue by bradwbowman** [johngodley/redirection#190]
I'm not a programmer so I don't really know what other information to provide but my log files for this plugin stopped collecting data on my main website.  I also started a brand new site and redirection is literally the only plugin installed, I'm using the default wordpress theme and everything is up to date.  No log files or entries in the log table in the DB.  I do have one older website that has also been updated and that is still collecting data.    I have the "Keep logs forever" clicked and on the page that shows my list of redirects, it shows tons of hits and recent dates.

The site that is working is on a Godaddy shared server and the ones that are not working are on Digital Ocean Cloud servers. 

Any help would be appreciated as I love your plugin.

**Comment by johngodley** [comment]
Are you using WordPress or Apache redirects?
Are the redirects working?
Does the number of hits increase when a URL is redirected?

**Comment by johngodley** [comment]
Closing for now but please reopen if you have more details
