### ISSUE TITLE
Redirects Will Not Save

### ISSUE THREAD

**Issue by imullan83** [johngodley/redirection#1902]
Hello, 
My redirect plugin says that it is saving the redirects that I enter but nothing is actually being saved. I've created a number of successful redirects so I'm not sure why all of a sudden it's not working. I've updated to the most recent version and am not running any caching software; do you have any suggestions on what I can try?

**Comment by johngodley** [comment]
You say you aren't using any caching software but this is almost certainly a caching issue, and your host could be running caching software for you. You could check and see if this is the case

**Comment by sitamet** [comment]
Almost same problem:

Does not save the redirect
Sample tested:

Source URL:  /hello
Target Url: /goodby

## RESULT: 
only saved Target Url

## EXPECTED RESULT:
Source and Destination targets Saved

## ENVIRONMENT
- Hosting provider [wetopi.com](https://wetopi.com/) (no cache: not in provider nor wp side).
- clean WordPress 5.2.2 install
- WP Current health score:100%
- nginx/1.14.2
- PHP version | 7.3.6
- 5.5.5-10.3.15-MariaDB
- permalinks enabled
Log errors (only during install):
```

Aug 5, 2019 7:35:39 AM | PHP message: WordPress database error Table 'wordpress.NjU0_redirection_groups' doesn't exist for query SHOW FULL COLUMNS FROM `NjU0_redirection_groups` made by require_once('wp-admin/admin.php'), do_action('load-tools_page_redirection'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, Redirection_Admin->redirection_head, Red_Database_Status->get_json, Red_Database_Status->get_manual_upgrade, Red_Database_Upgrader->get_queries_for_stage, Red_Latest_Database->create_groups
-- | --
Aug 5, 2019 7:35:39 AM | PHP message: WordPress database error Table 'wordpress.NjU0_redirection_groups' doesn't exist for query SHOW FULL COLUMNS FROM `NjU0_redirection_groups` made by require_once('wp-admin/admin.php'), do_action('load-tools_page_redirection'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, Redirection_Admin->redirection_head, Red_Database_Status->get_json, Red_Database_Status->get_manual_upgrade, Red_Database_Upgrader->get_queries_for_stage, Red_Latest_Database->create_groups
Aug 5, 2019 7:35:39 AM | 2019/08/05 07:35:39 [error] 97#97: *29 FastCGI sent in stderr: "PHP message: WordPress database error Table 'wordpress.NjU0_redirection_groups' doesn't exist for query SELECT COUNT(*) FROM NjU0_redirection_groups made by require_once('wp-admin/admin.php'), do_action('load-tools_page_redirection'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, Redirection_Admin->redirection_head, Red_Database_Status->get_json, Red_Database_Status->get_manual_upgrade, Red_Database_Upgrader->get_queries_for_stage, Red_Latest_Database->create_groups
Aug 5, 2019 7:35:39 AM | PHP message: WordPress database error Table 'wordpress.NjU0_redirection_groups' doesn't exist for query SELECT * FROM NjU0_redirection_groups LIMIT 1 made by require_once('wp-admin/admin.php'), do_action('load-tools_page_redirection'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, Redirection_Admin->redirection_head, Red_Database_Status->get_json, Red_Database_Status->get_manual_upgrade, Red_Database_Upgrader->get_queries_for_stage, Red_Latest_Database->create_groups" while rea
```

## How to reproduce:

- open free account in [wetopi.com](https://wetopi.com/)
- launch a devel server (1 click)
- install plugin

**Comment by johngodley** [comment]
Ok, this seems to be caused because Wetopi has a missing PHP module, or is using a version of PHP with a bug in it. I will add a workaround to Redirection so it doesn't blank out the URL

**Comment by sitamet** [comment]
We have tested in PHP 5.6, 7.1 and 7.3
The WordPress Health Check give us 100% on on server setup
If you guess something we can fix, please let me know
thanks a lot

**Comment by johngodley** [comment]
Sure, it's not related to the major PHP version or health check, but to the modules PHP is compiled with. The only report of this is on Wetopi, and having debugged it is specific to that host.
