### ISSUE TITLE
Feature request: making logging optional per rule

### ISSUE THREAD

**Issue by brofield** [johngodley/redirection#1906]
### Summary

I have a virtual URL that is linked to from all over my site, e.g. "/book". I have a rule to redirect the /book URL to the actual URL that I want. This allows me to update this actual URL just once rather than in 30 different places around the site. This URL / redirect rule is triggered by 30% of the visitors to the site leading to a lot of log entries. I would like to not log this redirection as the log entries get in the way of seeing more useful information.

### Actual Behavior

Every rule is logged every time.

### Steps to reproduce

I would like an option for a rule to not generate a log entry.

### Environment

WordPress 5.2.2 Redirection 4.3.2

**Comment by johngodley** [comment]
The next version will allow logging to be disabled on each redirect.

**Comment by johngodley** [comment]
You can try this in the 4.9 beta:

https://github.com/johngodley/redirection/releases/tag/4.9-beta

Let me know how it goes.
