### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by dmauryatech** [johngodley/redirection#1915]
```
Plugin: 4.3.3
WordPress: 4.9.10 (single)
PHP: 7.3.8
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
JavaScript: https://getsetwild.com/wp-content/plugins/redirection/redirection.js
REST API: https://getsetwild.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/group/
on this server.<br />
</p>
</body></html>

```

**Comment by dmauryatech** [comment]
Check out this screenshot too : [https://prnt.sc/oqvxn6](https://prnt.sc/oqvxn6)

Discussed with Hosting/Server Experts already for Last 2 days. They said nothing related to this plugin is blocked by server security. And Suggested to report this issue to the plugin provider.

Please Help. Thanks!

**Comment by johngodley** [comment]
Something is blocking your WordPress REST API, probably a security plugin.

https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
