### ISSUE TITLE
Problem starting Redirection 4.3.3

### ISSUE THREAD

**Issue by crschwarz** [johngodley/redirection#1917]
Plugin: 4.3.3
WordPress: 5.0.4 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
JavaScript: https://johnbarneswindowtinting.com/wp-content/plugins/redirection/redirection.js
REST API: https://johnbarneswindowtinting.com/wp-json/

**Comment by johngodley** [comment]
Another plugin is likely causing this problem. Open your browser's developer console and see if any extra information is shown
