### ISSUE TITLE
Problem starting Redirection 4.3.3

### ISSUE THREAD

**Issue by Newtrack** [johngodley/redirection#1919]
Plugin: 4.3.3
WordPress: 5.2.2 (single)
PHP: 7.2.15
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
JavaScript: https://vitamedlaserclinic.ca/wp-content/plugins/redirection/redirection.js
REST API: https://vitamedlaserclinic.ca/wp-json/

**Comment by johngodley** [comment]
This is likely a problem with another plugin. Please open your browser's developer console and see if any more information is shown.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
