### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by annalinneajohansson** [johngodley/redirection#1921]
```
Plugin: 4.3.3
WordPress: 5.2.2 (single)
PHP: 7.3.8-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
JavaScript: https://scandinavianracehorses.wpmudev.host/wp-content/plugins/redirection/redirection.js
REST API: https://scandinavianracehorses.wpmudev.host/wp-json/

Error: Unexpected token N in JSON at position 1 (SyntaxError)
Raw: 
Notice: Only variables should be passed by reference in /var/web/site/public_html/wp-content/object-cache.php on line 309

Notice: wp_cache_flush() used, this is broadly not recommended. Called in /var/web/site/public_html/wp-content/plugins/redirection/database/database-status.php line 368 in /var/web/site/public_html/wp-content/object-cache.php on line 314
{"status":"need-update","inProgress":true,"current":"2.4","next":"4.1","time":1565878785.9838631,"manual":["ALTER TABLE `wp_scr_redirection_items` ADD `match_url` VARCHAR(2000) NULL DEFAULT NULL AFTER `url`","ALTER TABLE `wp_scr_redirection_items` ADD INDEX `match_url` (`match_url`(191))","ALTER TABLE `wp_scr_redirection_items` ADD `match_data` TEXT NULL DEFAULT NULL AFTER `match_url`","UPDATE `wp_scr_redirection_items` SET match_url='regex' WHERE regex=1","UPDATE `wp_scr_redirection_items` SET match_url=SUBSTRING_INDEX(LOWER(url), '?', 1) WHERE regex=0","UPDATE `wp_scr_redirection_items` SET match_url=LEFT(match_url,LENGTH(match_url)-1) WHERE regex=0 AND match_url != '\/' AND RIGHT(match_url, 1) = '\/'","UPDATE `wp_scr_redirection_items` SET match_url='\/' WHERE match_url=''","UPDATE `wp_scr_redirection_items` SET match_url=LOWER(LEFT(SUBSTRING_INDEX(url, '?', 1),LENGTH(SUBSTRING_INDEX(url, '?', 1)) - 1)) WHERE RIGHT(SUBSTRING_INDEX(url, '?', 1), 2) = '\/\/' AND regex=0","UPDATE `wp_scr_redirection_items` SET match_url='\/' WHERE match_url=''"],"complete":40,"result":"ok","reason":"Expand size of redirect titles"}
```

**Comment by annalinneajohansson** [comment]
Log without any other plugins active.

`Plugin: 4.3.3
WordPress: 5.2.2 (single)
PHP: 7.3.8-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
JavaScript: https://scandinavianracehorses.wpmudev.host/wp-content/plugins/redirection/redirection.js
REST API: https://scandinavianracehorses.wpmudev.host/wp-json/

Error: Unexpected token N in JSON at position 1 (SyntaxError)
Raw: 
Notice: Only variables should be passed by reference in /var/web/site/public_html/wp-content/object-cache.php on line 309

Notice: wp_cache_flush() used, this is broadly not recommended. Called in /var/web/site/public_html/wp-content/plugins/redirection/database/database-status.php line 368 in /var/web/site/public_html/wp-content/object-cache.php on line 314

Notice: Only variables should be passed by reference in /var/web/site/public_html/wp-content/object-cache.php on line 309

Notice: wp_cache_flush() used, this is broadly not recommended. Called in /var/web/site/public_html/wp-content/plugins/redirection/database/database-status.php line 368 in /var/web/site/public_html/wp-content/object-cache.php on line 314
{"status":"need-update","inProgress":true,"current":"4.0","next":"4.1","time":1565878876.744714,"manual":["UPDATE `wp_scr_redirection_items` SET match_url=LOWER(LEFT(SUBSTRING_INDEX(url, '?', 1),LENGTH(SUBSTRING_INDEX(url, '?', 1)) - 1)) WHERE RIGHT(SUBSTRING_INDEX(url, '?', 1), 2) = '\/\/' AND regex=0","UPDATE `wp_scr_redirection_items` SET match_url='\/' WHERE match_url=''"],"complete":50,"result":"ok","reason":"Add missing IP index to 404 logs"}`

**Comment by annalinneajohansson** [comment]
Object cache was flushed before trying to upgrade the database also.

**Comment by johngodley** [comment]
Something on your site is outputting that message, maybe another plugin. You'll need to investigate which plugin this might be. Also, you should disable error messages from being displayed as this can pose a security risk.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
