### ISSUE TITLE
Feature request: support for http error 451 unavailable for legal reasons

### ISSUE THREAD

**Issue by przepla** [johngodley/redirection#1922]
### Summary

Sometimes it is needed to delete or otherwise restrict a page/post due to legal reasons (court injunction/order, cease and desist letter, law change etc.) Currently available redirects when 404 error are insufficient. RFC 7725 (https://tools.ietf.org/html/rfc7725) provides solution.

### Actual Behavior

Possibility of adding 404 Redirect with HTTP Code "451 - Unavailable For Legal Reasons".

.

**Comment by johngodley** [comment]
Added in 2ecc4ccf9d7c154b561a2ebf8bfeca084e625656, available in the next version
