### ISSUE TITLE
[Enhacement] Ignoring 404 of static assets

### ISSUE THREAD

**Issue by dmpinder** [johngodley/redirection#1926]
It would be great if we can filter out static files (like .css or .js) from the 404 log. We see a bunch of irrelevant requests like autodiscover.xml which we just don't use.

Thanks!

**Comment by johngodley** [comment]
There is an 'ignore' option on the 404 page:

https://redirection.me/support/tracking-404-errors/

**Comment by dmpinder** [comment]
Thanks for the reply John. I can see the ignore option, that's good to know. However, I still think it would be an enhancement to be able to ignore file types before they become log entries that need manual cleanups. Thanks for the great work, your plugin is great!

**Comment by johngodley** [comment]
Sure. Once you've ignored a file it won't appear in the logs again - you are marking which ones you want to ignore.
