### ISSUE TITLE
404 errors - 88K of them

### ISSUE THREAD

**Issue by NaomiDorland** [johngodley/redirection#1929]
I am on Version 4.3.3 of Redirection and WP 5.2

I was adding in a 301 redirect when curiosity made me click on the 404 error tab.  I nearly fell off my chair when I saw I had over 88 000 of them!

Why do I have so many???  The file names are not even files names I would use.   

Is this affecting my SEO? 

Help - Im freaking out!   

Thanks

![image](https://user-images.githubusercontent.com/44248458/63476935-2849ba80-c4c6-11e9-8cbe-d08073d223cd.png)

**Comment by johngodley** [comment]
You have as many entries as 404s have been recorded, which in your case is 88,000. I can't tell you why you have that number other than that's how many you've got.

Please see https://redirection.me/support/faq/#weird
