### ISSUE TITLE
WordPress_Module and Red_Item get_ip() -methods differ

### ISSUE THREAD

**Issue by aksl** [johngodley/redirection#193]
Red_Item->get_ip() tries to use HTTP_X_FORWARDED_FOR for IP and only afterwards the REMOTE_ADDR. This is used for redirection hit logs.

WordPress_Module->get_ip() uses REMOTE_ADDR first, and only if it doesn't exist, tries to use HTTP_X_FORWARDED_FOR (which likely never happens). This is used for 404 logs.

As a end result, if the site is running behind a proxy (like nginx), the 404 logs will always have invalid client IP (the IP of the proxy server).

Additional feature request: implement a filter for get_ip() functionality, so the behavior can be controlled to further extent. One such case would be to only trust HTTP_X_FORWARDED_FOR from certain proxy servers.

**Comment by johngodley** [comment]
Thanks. This has been added in 2.6.1
