### ISSUE TITLE
Redirect 301 with accents

### ISSUE THREAD

**Issue by fran775** [johngodley/redirection#1931]
Hi!
I try redirect 301 but the URL have accents:
recetas.asp?categoria=Jam%F3n
but when i add "Jam%F3n" automatically saves it as "Jamn" and it does not work.
how can I do it?
Thanks

**Comment by johngodley** [comment]
The %F3 is an invalid character. What is it supposed to be?

**Comment by fran775** [comment]
Hello, thanks for answering,
one of the old pages is indexed by google as:
http://www.carniceriasherrero.com/recetas.asp?categoria=Jam%F3n

and I want to redirect it to:
https://www.carniceriasherrero.com/receta-de-secreto-iberico-con-salsa-de-vino-y-fresas/

"%F3" corresponds to the accent (tilde) in Spanish "ó"

But the problem is that Google has indexed these and many other pages that way and I'm afraid of not being able to redirect. Is there a solution? Thank you very much

**Comment by johngodley** [comment]
%F3 is an invalid character, not a Spanish one. You can test this by trying to decode it here: https://www.urldecoder.org/

Could the URL be the text `%F3n` - that is `%25F3n` when encoded, and `%F3n` when decoded?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
