### ISSUE TITLE
redirection error

### ISSUE THREAD

**Issue by atmakurig** [johngodley/redirection#1943]
To help track problems please follow this template. If you can provide screenshots then that will help.

Trying to add a new redirect or edit old redirects.

Throws this error:
Plugin: 4.3.3
WordPress: 5.2.2 (single)
PHP: 7.1.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
JavaScript: https://www.mysite.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.mysite.com/wp-json/
Buster: 4.3.3 === 4.3.3

TypeError: o.replace is not a function

    in t
    in p
    in div
    in div
    in div
    in t
    in td
    in tr
    in t
    in p
    in tbody
    in Ua
    in table
    in Unknown
    in div
    in t
    in p
    in div
    in t
    in p
    in t
    in Unknown

### Steps to reproduce

I went to redirection section and tried to add a new redirect and also tried to edit an existing redirect.

### Environment
chrome browser, Version 72.0.3626.119 (Official Build) (64-bit), WordPress: 5.2.2 (single), Plugin: 4.3.3

**Comment by johngodley** [comment]
Please see #1927

**Comment by atmakurig** [comment]
#1927 is also closed without a resolution.

**Comment by johngodley** [comment]
Yes, please see #1927 for more information.
