### ISSUE TITLE
After saving a redirect, Source URL is set to blank

### ISSUE THREAD

**Issue by gilletty** [johngodley/redirection#1947]
After saving a valid redirect, the source URL is set to blank. In the `wp_redirection_items` table, `url` is blank and `match_url` is `/`.

I've tried this using Safari and Chrome with the same result. The plugin version is **4.3.3** and the Wordpress version is **5.2.2**.

Here are screenshots to demonstrate:

<img width="1010" alt="Screen Shot 2019-09-03 at 11 06 00 AM" src="https://user-images.githubusercontent.com/332306/64189959-f4ae4f00-ce3a-11e9-905b-f8238366ecce.png">
<img width="1001" alt="Screen Shot 2019-09-03 at 11 06 17 AM" src="https://user-images.githubusercontent.com/332306/64189967-f841d600-ce3a-11e9-875d-0f0114b76800.png">
<img width="1001" alt="Screen Shot 2019-09-03 at 11 06 33 AM" src="https://user-images.githubusercontent.com/332306/64189971-faa43000-ce3a-11e9-8b1b-5b4b19823225.png">

Here is the JSON payload that is getting sent as part of the request by the plugin:
```
{
    "id": 21,
    "url": "/test123",
    "title": "",
    "match_data":
    {
        "source":
        {
            "flag_regex": false,
            "flag_trailing": false,
            "flag_case": false,
            "flag_query": "exact"
        }
    },
    "match_type": "url",
    "action_type": "url",
    "position": 15,
    "group_id": 3,
    "action_code": 301,
    "action_data": {
        "url": "/test1234"
    }
}
```

Here is the response:
```
{
    "item": {
        "id": 21,
        "url": false,
        "match_url": "/",
        "match_data": {
            "source": {
                "flag_query": "exact",
                "flag_case": false,
                "flag_trailing": false,
                "flag_regex": false
            }
        },
        "action_code": 301,
        "action_type": "url",
        "action_data": {
            "url": "/test1234"
        },
        "match_type": "url",
        "title": "",
        "hits": 0,
        "regex": false,
        "group_id": 3,
        "position": 15,
        "last_access": "-",
        "enabled": true
    }
}
```

**Comment by johngodley** [comment]
This is because your PHP is not set up with appropriate UTF modules. You'll need to use this beta https://github.com/johngodley/redirection/releases/tag/4.4-beta-1 which contains a workaround, until it is released properly

**Comment by gilletty** [comment]
I looked in your prior commits and noticed an `iconv` check you added. Is that the issue? If not, what modules/extensions would I need to add to support the current version?

**Comment by johngodley** [comment]
I don't know exactly what module is missing. The majority of installations contain the required modules. If you use the beta then it works around the missing module.

**Comment by collinbarrett** [comment]
I'm seeing the same symptoms:

```
Plugin: 4.3.3
WordPress: 5.2.3 (single)
PHP: 7.3.9
Browser: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
JavaScript: https://collinmbarrett.com/wp-content/plugins/redirection/redirection.js
REST API: https://collinmbarrett.com/wp-json/

Error: Invalid redirect details (80)
Action: redirection/v1/redirect/298/ POST
Params: {"id":298,"url":"/resume/pdf","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":true,"flag_case":true,"flag_query":"pass"}},"match_type":"url","action_type":"url","position":93,"group_id":1,"action_code":301,"action_data":{"url":"/media/resume_collinmbarrett_20190907.pdf"}}
Code: 400 Bad Request
Raw: {"code":"redirect","message":"Invalid redirect details","data":{"status":400,"error_code":80}}
```

On the `collinmbarrett` site whose infrastructure is defined [here](https://github.com/collinbarrett/wp-host-on-containers). It's using the official `wordpress:php7.3-fpm-alpine` docker image.

**Comment by johngodley** [comment]
@collinbarrett see https://github.com/johngodley/redirection/issues/1947#issuecomment-527570148

**Comment by collinbarrett** [comment]
Yep, beta works. Thanks.

Will the beta prompt for update to the latest stable release when it's available through the regular WordPress update mechanism? Or will I need to manually upload the next stable when it's released? I didn't see mention of that [here](https://redirection.me/support/beta-release/), apologies if I missed it.

Thanks for the great plugin! Been using it for years.

**Comment by rgilletteex** [comment]
The beta works for me as well. Thank you John!

**Comment by gilletty** [comment]
The beta works for me as well. Thank you John!
