### ISSUE TITLE
FEATURE REQUEST:  Search matches destination or source url vs. just source

### ISSUE THREAD

**Issue by jakebohall** [johngodley/redirection#1952]
### Summary

When I search within the redirection interface, I would like to be able to see destination matches so I can quickly find/update existing redirects based on the destination url.

### Actual Behavior

The current search filters all redirects to those where the origin url matches the search.  

### Why

This would be immensely helpful when fixing redirect chains, or trying to find all the urls that have been redirected to a specific page to find better alternatives, etc.    Our current method is to export the list of redirects..  and then manually go one by one to search on source and update  (or go one by one to delete, and then bulk upload the change)

**Comment by johngodley** [comment]
Please try the 4.4 beta : https://github.com/johngodley/redirection/releases/tag/4.4-beta-1

**Comment by jblifestyles** [comment]
@johngodley  ... Realized I posted this with the wrong account, and missed this response.  Sorry!   Really appreciate you rolling this feature out :)
