### ISSUE TITLE
RegEx redirection to filenames with spaces

### ISSUE THREAD

**Issue by gkboyles** [johngodley/redirection#1957]
### Summary

I am trying to redirect a directory to a directory of PDF files some of which have spaces in the filenames.

### Actual Behavior

Desired result - /wp-content/uploads/pdf/newsletter/July%20GE%20Newsletter%202019.pdf
Actual result - /wp-content/uploads/pdf/newsletter/JulyGENewsletter2019.pdf

### Steps to reproduce

I set the source to - /Websites/greatexpectations/images/pdf/(.*)$
and the target to - /wp-content/uploads/pdf/$1

This works fine for files with no spaces in the filenames. Filenames with spaces will have the spaces removed causing a 404.

### Environment
Chrome
Version 76.0.3809.132 (Official Build) (64-bit)
Wordpress 5.2.3
Plugin 4.3.3
![image](https://user-images.githubusercontent.com/55212176/64734213-d506ce80-d4ab-11e9-8e75-023f2b80c613.png)

**Comment by johngodley** [comment]
Please try version 4.4:

https://github.com/johngodley/redirection/releases/tag/4.4-beta-1

**Comment by gkboyles** [comment]
Thank you! The beta is working with the space character now.



<http://www.greatexpectations.org/>
<http://www.facebook.com/Great.Expectations.Foundation>
<http://www.twitter.com/GreatExpOrg>
<http://www.youtube.com/user/GreatExpectationsOrg>

*Good judgment comes from experience, and a lot of that comes from bad
judgment. - Will Rogers*
