### ISSUE TITLE
404 logs showing signs of malicious sites - is redirect pluign infected

### ISSUE THREAD

**Issue by jasonsgithub** [johngodley/redirection#1963]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Redirect plugin log is catching instances of a referral that seems suspicious - no referrer and source url does not and has never existed on any of my sites:
  
/wp-content/plugins/social-warfare/readme.txt

AND there is no referrer listed with that url... see image attached:
![1 social warfare](https://user-images.githubusercontent.com/4920303/64911080-5ef0aa80-d6eb-11e9-8609-1fb2ae5b5134.JPG)

5th record down in image

### Actual Behavior

just appears in logs

### Steps to reproduce

not sure

### Environment

does not matter - any browser on any computer displays the same

**Comment by johngodley** [comment]
The log records all instances of URLs requested on your site that result in a 404
