### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by yyil** [johngodley/redirection#1965]
Hi/
I think this error is because I enabled "force SSL" on my local dev machine, but SSL is not available. Now I can't load the settings page to disable SSL.I'm just getting errors.

```
Plugin: 4.3.3
WordPress: 5.2.3 (single)
PHP: 7.1.25
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
JavaScript: http://practicepulse.localhost/wp-content/plugins/redirection/redirection.js
REST API: http://practicepulse.localhost/wp-json/

Error: Failed to fetch
```

**Comment by johngodley** [comment]
You will need to remove the plugin by deleting or renaming it inside your plugins directory.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
