### ISSUE TITLE
Feature Request: Ability to send HTTP status 410 (Gone)

### ISSUE THREAD

**Issue by pan-kar** [johngodley/redirection#1966]
Dear John,

it would be great if we could send the status code 410. Based on my experience, it is very useful, when you need to remove indexed urls from google.
[You already provide the option](https://imgur.com/Ih8zkId) for the user to select the status code, so i think that the addition of an extra status code, it will not be a big deal.

More on 410 http status code [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410).

Thank you in advance!
Panos

**Comment by johngodley** [comment]
Please see here: https://redirection.me/support/redirect-actions/
