### ISSUE TITLE
Passing Results not found via Groups

### ISSUE THREAD

**Issue by RoccoSaccente** [johngodley/redirection#1974]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Our url is being passed with a string with an optional group in the end which we want to pass.  

Example URL/L100000 OR URL/L100000P or URL/L100000WX

to go to URL/?value=L100000WX

Screen shot of the rule is attached. 

I tried $1$2 even $1 even $1$2$3 and $& which is supposed to pass all groups. 

Nothing worked. 

### Actual Behavior

URL/?value=L100000

(missing the second group passing)

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Redirection: Plugin: 4.4 
WordPress: 5.2.3 (single) 
PHP: 7.0.33 
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

![image](https://user-images.githubusercontent.com/55711256/65449835-c9030100-de09-11e9-9d69-2708ce7a05a2.png)
![image](https://user-images.githubusercontent.com/55711256/65450010-36169680-de0a-11e9-8e51-9ec17e59c1ce.png)

**Comment by johngodley** [comment]
PHP regular expressions are used. You only listed the source URL in a screenshot so I can't copy/paste it to test. Also clear your browser cache.

**Comment by RoccoSaccente** [comment]
The true source url is https://why.oxzgen.com/L100000WX should be https://why.oxzgen.com/?rin=L100000WX but it's not doing that.  Cache was cleared.  (the source url is actually private, can you hide this from Public? )

**Comment by johngodley** [comment]
I meant your source URL in Redirection is only shown in a screenshot. In order to test the regular expression it would help to copy and paste it.

I don't know what you mean about the true source URL. In what way is it private? It's shown above.

I note you are using Cloudflare and this may cause problems.

**Comment by RoccoSaccente** [comment]
My apologies sir, it seems like it's working now.  Maybe it is Cloudflare, I assume using $1$2$4 or $& is the correct way to pass values in the regex statement? 

The source was ^/([lL][0-9]{6,10})(|[pP]|[Ww][Xx])$ and target was /?rin=$1$2$3

**Comment by johngodley** [comment]
You refer to each capture group using `$1`, `$2` etc. I am unaware of `$&`. You only appear to have 2 capture groups in your regular expression, so `$3` is unnecessary.

**Comment by RoccoSaccente** [comment]
What value do you use to pass all groups?

**Comment by johngodley** [comment]
As far as I'm aware there is no 'all'. You pass the groups individually using `$1`, `$2`, etc

**Comment by RoccoSaccente** [comment]
Thank you so much John, you've been excellent!
