### ISSUE TITLE
Won't redirect if URL has a { sign.

### ISSUE THREAD

**Issue by vladpoly90** [johngodley/redirection#1976]
Tried implementing deeplinking of an affiliate partner, but they have {var} in their URL. The redirection does not pass these or just removes the { and } sign altogether,

**Comment by johngodley** [comment]
The `{` is removed by WordPress as an invalid character:

https://developer.wordpress.org/reference/functions/wp_sanitize_redirect/

The only way around this is to supply your own `wp_sanitize_redirect` function.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
