### ISSUE TITLE
Temporary Redirect Home Page

### ISSUE THREAD

**Issue by BrucieTom** [johngodley/redirection#1978]
### I'm trying to redirect my home page but the plugin doesn't seem to like this. Is there a way to do it? I'm completely new to WP...

**Comment by johngodley** [comment]
### Doesn't seem to like what? How have you done this?

**Comment by BrucieTom** [comment]
Maybe I should ask how should I set this up / is it possible?

**Comment by johngodley** [comment]
Sure, you can redirect from any URL on your site to any other URL.

Details can be found here:

https://redirection.me/support/
