### ISSUE TITLE
Redirect Error

### ISSUE THREAD

**Issue by whiwo** [johngodley/redirection#1982]
I've been having a lot of problems with redirect lately. When you try to validate a redirect it no longer works. 

Today, I'm searching for a specific redirect that ends with ?ND and I keep getting the error "something went wrong" please see attached screenshot. 

I've already cleared my caching plugin, my CDN and my browser to no avail. I thought it might be a conflict with the premium version of Yoast SEO but I deactivated it and the issue persists. 

[https://drive.google.com/open?id=1QrpNCNyLQsUKDOgJdBuQaZPXdXvYtqQk](url)

**Comment by johngodley** [comment]
What URL are you trying to validate?

There is a bug when searching for things with a `?`, which will be fixed in the next release. For now you will have to search without the `?`

**Comment by whiwo** [comment]
I went ahead and exported the SQL file is it’s just not there. The Redirection plugin I’m using now is acting up and I can’t search anything. I’ve put out an issue ticket on Github. I remember redirecting this – I just don’t remember which platform.

Anyway, I cannot find it in my database. I’ll keep trying.

Thanks!

K

**Comment by johngodley** [comment]
I'm confused. What is not there? As I mentioned, there is a bug when searching for `?ND`. If you clear the search field and search again then it will clear the problem.

**Comment by whiwo** [comment]
Don't worry about it. It's definitely not there. I had Yoast SEO premium previously and reactivated it thinking all my redirects would show up but they didn't.

I reached out to them and they said they were in the database - they're not, even though the original redirects used with their premium plugin still works.

So, it's there somewhere in my file manger or hidden in the database but I can't find it. It's just one URL that needs to be deleted and I'm not going to spend any more time on it.

Thanks!

K

On Sep 25, 2019 9:26 AM, John <notifications@github.com> wrote:

I'm confused. What is not there? As I mentioned, there is a bug when searching for ?ND. If you clear the search field and search again then it will clear the problem.
