### ISSUE TITLE
Falses positives, incompatibility

### ISSUE THREAD

**Issue by jcabezasv** [johngodley/redirection#1985]
I've installed this plugin and other called "404 to similar post". With the second plugin my web will not return 404 status anymore but this plugin "Redirection" still getting 404 errors on the list.

**Comment by johngodley** [comment]
Redirection records any request that WordPress determines as a 404. If the request is subsequently changed to something other than a 404 that is out of Redirection's control.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
