### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by CaryLeibowitz** [johngodley/redirection#1988]
```
Plugin: 4.4
WordPress: 5.2.2 (single)
PHP: 7.2.22-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
JavaScript: https://everything-pr.com/wp-content/plugins/redirection/redirection.js
REST API: https://everything-pr.com/wp-json/

Error: Failed to fetch
```

**Comment by johngodley** [comment]
Can you go to the options page and try one of the other REST API settings. If you are still having a problem then if it's possible to login and see the problem that would help. If this is ok please get in touch at https://redirection.me/contact/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
