### ISSUE TITLE
Saving apache .htaccess dir settings on option page

### ISSUE THREAD

**Issue by cantoute** [johngodley/redirection#1990]
### Summary

when on setting plugins options page you save first time the setting it only accepts the folder name without .htaccess

so second time you save those settings, it complains that it can't open /path/docroot/.htaccesss/.htaccess

I believe this cause me a big crash of all my redirections 

### Environment

Debian server running php7.3

**Comment by cantoute** [comment]
And it seems that using the plugin interface behaves buggos when combined with the plugin SuperPWA

Redirections and Groups disappear from settings pages and when using plugin "delete all" comes ut a "Saving" message ... I tried to investigate but could not get more details sorry

**Comment by johngodley** [comment]
I wasn't able to reproduce any conflict with SuperPWA. Disappearing data is usually caused by misbehaving cache software.

What do you mean by 'big crash'?

Accidentally including `.htaccess` will not cause a problem.

**Comment by cantoute** [comment]
Hi,
I managed to fix the issue by deleting app storage (I hadn't realized that clearing cache wasn't going to help me)
The problem probably started when I entered a regex rule and forgot to say it was a regex
It was a rule added to a group using the Apache module
From then on I started having issues with stange rules appearing here disappearing there.

After total remove and reinstall of your plugin it all seemed to go fine until I went back to change a setting a second time and there the /path/docroot/.htaccess changed into /path/docroot/.htaccess.htaccess and complaining about wrong path... and started having phantom rules again.

I believe there is one issue with setting the path to .htaccess where it appends ".htaccess" when already there
and an other one with regex spelling into a none regex rule in a group using Apache module that starts phantom rule (my mistake but this kind of things happen...)

I thought I'd let you know there is something to watch for, but sorry I can't help you more... 


Thanks for your attention
