### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by keifit** [johngodley/redirection#1993]
```
Plugin: 4.4
WordPress: 4.9.8 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
JavaScript: https://keifit.com/wp-content/plugins/redirection/redirection.js
REST API: http://keifit.com/index.php?rest_route=/

Error: Failed to fetch
```

**Comment by johngodley** [comment]
Can you go to the options page and try one of the other REST API settings. If you are still having a problem then if it's possible to login and see the problem that would help. If this is ok please get in touch at https://redirection.me/contact/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
