### ISSUE TITLE
Wishlist: Programmatically add to 404 from CPT

### ISSUE THREAD

**Issue by AndrassGray** [johngodley/redirection#1994]
I somehow have the feeling that what I want is already possible, so in this case my wishlist item is to amend the FAQ for people trying to programmatically feed into the logs.

I have a custom page that frequently gets called with outdated parameters, result from restructuring the site without consideration. These are not 404s, properly speaking, as I correctly land on the right page. But still 404s in the sense that the slugs points to the wrong data.

What I would love to do is feed these wrong calls into the logs, so I can slowly clean up behind me. I

Many thanks in advance !

**Comment by johngodley** [comment]
This is the code that creates the 404 logs:

https://github.com/johngodley/redirection/blob/master/modules/wordpress.php#L57

You should be able to re-use that for your own purposes.

**Comment by AndrassGray** [comment]
That looks perfect for what I need to do. Thanks a lot.

Closing this. Thanks for a beautifully helpful plugin!
