### ISSUE TITLE
Database error when adding (or importing)

### ISSUE THREAD

**Issue by steveshaddick** [johngodley/redirection#2001]
Cannot add or import any redirection rule, I receive the error below:

```
Plugin: 4.4.2
WordPress: 5.2.1 (single)
PHP: 7.3.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
JavaScript: http://example.local:8888/wp-content/plugins/redirection/redirection.js
REST API: http://example.local:8888/wp-json/

Error: Unable to add new redirect (58): Unknown column 'match_data' in 'field list'
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"/source-url/","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"/target-url/"}}
Code: 400 Bad Request
Raw: {"code":"redirect","message":"Unable to add new redirect","data":{"status":400,"error_code":58,"wpdb":"Unknown column 'match_data' in 'field list'"}}
```

**Comment by johngodley** [comment]
Go to the 'support' page, change the database version to 2.4, and follow the instructions.

**Comment by steveshaddick** [comment]
Ah okay - thanks, for your quick response - that worked! Would you mind giving me a quick overview on what the issue might have been? Is there some sort of issue with the combination of wordpress/mysql/php version? From the error message, I'm guessing there was a problem with the initial plugin install (by not creating the proper columns), and changing the database version down kick starts those columns again - is there some way I might anticipate this issue when I install for other sites in the future?

**Comment by johngodley** [comment]
Somehow the plugin thinks it has been upgraded, but the database hasn't. 

I suspect it may be related to caching in some way, but I haven't been able to reproduce it, and by the time it happens, it's too late to debug (unless you just happened to have made a site backup before). This should only happen on upgraded sites.

**Comment by steveshaddick** [comment]
Interesting. FWIW I've now seen this twice when installing the plugin for the first time. However - to be honest, it's possible that the sites may have had Redirection plugin installed in the past, and then removed, so that would explain it. Thanks again!
