### ISSUE TITLE
Redirection Error - Unable to update database 

### ISSUE THREAD

**Issue by mitchjlb** [johngodley/redirection#2003]
Hello I am unable to update database as prompted, both through wordpress or manually.
i have disabled caching on securi firewall and on website
and disabled other plugins as recommended.

Any assistance would be appreciated. 

Thanks,

```
Plugin: 4.4.2
WordPress: 5.2.3 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
JavaScript: http://www.weahomes.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.weahomes.com/wp-json/

Error: Failed to fetch
```

**Comment by mitchjlb** [comment]
Starts at 60-70% and doesn't complete.
![redirect1](https://user-images.githubusercontent.com/13408297/66138569-79b88f80-e5c4-11e9-9949-9fc338994954.png)
![screencapture-weahomes-wp-admin-tools-php-2019-10-03-09_58_42](https://user-images.githubusercontent.com/13408297/66138582-7e7d4380-e5c4-11e9-9555-f75404ae6e43.png)

**Comment by johngodley** [comment]
Something on your site is blocking the POST requests, and this is likely to be Sucuri.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
