### ISSUE TITLE
Redirection Error - 404 Not Found

### ISSUE THREAD

**Issue by diegomanuel** [johngodley/redirection#2005]
It was working fine until yesterday, but now I can't disable, edit, create or delete any rule anymore!
Any action ends with the same 404 error.
REST API testing and everything about plugin status is good (green).

It's a problem with multilang redirection, so the POST to API receives a 302 status code:
https://mydomain.com/wp-json/ => https://mydomain.com/en/wp-json/

```
Plugin: 4.4.2
WordPress: 5.2.3 (single)
PHP: 7.0.18
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
JavaScript: https://mydomain.com/wp-content/plugins/redirection/redirection.js
REST API: https://mydomain.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Action: redirection/v1/bulk/redirect/disable/?orderby=id POST
Params: {"items":"6"}
Code: 404 Not Found
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment]
That sounds like your URL settings are inconsistent. Have a look on the Settings > General page and make sure they are both https.

**Comment by diegomanuel** [comment]
Thanks for your response, John. They are both https.
Seems to be a problem with qtranslate-x option: "Detect the language of the browser and redirect accordingly."

To make it work again, I had to disable that option and open a new private browsing with developers console open and "disable cache" option enabled.
As soon as I re-enabled language detection, it stopped working again.

**Comment by shayanabbas** [comment]
hats off to this developer, more than a dozen developers reported this issue and his answer was closing the issue without making effort to look into this.

**Comment by johngodley** [comment]
@shayanabbas what are you referring to and what dozen developers? The problem was identified to be q-translate, and so I closed the issue.
