### ISSUE TITLE
Problems when updating a big redirection db

### ISSUE THREAD

**Issue by vmgornelas** [johngodley/redirection#2006]
### Screenshots.

![Datadog](https://user-images.githubusercontent.com/56204232/66259714-fa6cbc80-e779-11e9-8fa2-0235ba728ecf.jpg)

### Summary
This is a high volume redirection urls news site... 700,000+ so it´s a big thing for us.

We where going to update wordpress until last month after a lot of tests, trainings, and a few other updates, everything worked fine in test servers.

The upgrade went well and the last thing we´ve updated was redirection plugin, then it asked us to upgrade data base, after we did, the server went crazy, we did it in a low traffic hour but live, as we did before with previously tested plugins, safely.  We couldnt get it right so we rolled back.

We´ve spent last weeks making test and almost everything works with our having to serve traffic.

We now started updating only redirection DB and when we saw that everything seemed to be finished started sending traffic and without any other update, it again sky rocketed memory and cpu, apache workers and server load mainly, and it started getting lots of 404 and 500´s with a very slow site.

We really dont know how to deal with this, we cant see querys to the new fields taking a lot of time and stopping everything behind, as we did last time, everything in the database seemed fine.

### Yoast premium with redirection features.
Well we use it because we cant turn it out or off; So it´s intended to serve redirections for editors that need to change an indexed URL semi-automatically.

We havent been able to update Yoast Premium, because we WP version, but planning to do it tonight. 

### Actual Behavior

The plugin was left updated to 4.4.2  since there´s no rollback version for it.

With the DB rollback, the site is working fine, but we cannot use redirection and it seems that something is not working ok, since we are getting 404 to regex urls that we have already solved.

### Steps to reproduce

To reproduce, just need to update the database with the link provided, and send traffic.

### Environment
Plesk Onyx 17.8.11
os_Ubuntu 16.04
PHP 7.2.22 FastCGI 
Wordpress 4.9.8
Redirection Ver 4.4.2
Yoast Premium Ver 11.3
DB Server SSD 
WWW Server

**Comment by johngodley** [comment]
Ok, I'm not really sure I fully understand everything there, what the current situation is, and what Yoast has to do with it. Do you have a lot of regular expressions?

**Comment by vmgornelas** [comment]
Thanks John. Sorry english is not my first language. I´ll try to better explain.

Current situation is that we rolled back to prevoius database format, but plugin is updated (it seems we cannot undo that)

Everytime we´ve tried to update database and get some traffic, the servers collapse.

about Yoast... since it has a redirection feature, I dont know if there could be a compatibility issue, there´s no evidenc for the time, just thought that I should not levae that info for myself.

It would help to know if someone has allready had same kind of trouble and fixed it, and read how to go through with a trustable upgrade.

Is there anything I can provide for your to have a closer look and better diagnose?

Thank You, very, very much :)

**Comment by vmgornelas** [comment]
And about Regex  we dont have that many (proportionally) but we do get a lot of request that will end up asking for regex redirections.

Indeed, sometimes are so much that we set rules at the CDN/WAF to decrese the amount of requests

**Comment by johngodley** [comment]
Older versions of the plugin are available here:

https://wordpress.org/plugins/redirection/advanced/

Would it be possible to get an export of the old data and see if I can recreate the problem locally? That way I'd know if it's a problem with the plugin, or with your setup.

**Comment by vmgornelas** [comment]
OK I´ll try to recreate the problem, but the only problem we see is with traffic, in test servers we have updated without trouble, until we send some traffic.

I will let you know how it goes.

Thanks!

**Comment by johngodley** [comment]
I meant, is it possible for me to recreate the problem on my own setup using your list of redirects? Then I can see if the data is affecting performance.

**Comment by vmgornelas** [comment]
Sure, how do I send the info? it might be a huge file...

**Comment by johngodley** [comment]
I can be contacted through the support page inside the plugin or at https://redirection.me/contact/

Depending on the size you may be able to send it directly, alternatively if I could download it from some location.

**Comment by vmgornelas** [comment]
OK just send a link using the contact form. Hope it works... there's my personal e-mail if anything.

**Comment by johngodley** [comment]
Following up here, the problem is that there were a lot of redirects that differed only by query parameters, and the plugin was not designed to handle this.

Version 5.0 should handle this situation, and a beta can be found here:

https://github.com/johngodley/redirection/releases/tag/5.0-beta
