### ISSUE TITLE
How to bulk redirect to "gone"

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#2007]
I had a temporary set of content on my site for a few days in the past and as a result (now that it has all been removed) I am flooded with redirects.

I would like to setup a single redirect that with states that all https://www.trucklesoft/test/<whatever is here> is now gone. Basically, that "test" folder is no longer there.

How do I do this?

Thanks.

**Comment by johngodley** [comment]
You can create a regular expression that matches /test/ and performs whatever action you want - a 410 error, for example.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
