### ISSUE TITLE
Feature/Advice - Create redirects in Functions.php when WooCommerce product is bought.

### ISSUE THREAD

**Issue by DavidTully13** [johngodley/redirection#2011]
Hi - sorry if this has been covered - I had a look online but could not see anything that suited.

I am building a WooCommerce subscription store and I would like to create a unique URL to the person content.
Is there a way I can make an easy to read URL
www.example.com/Dave
and redirect it to a complicated one.
www.example.com/path/to/item/index.php?id=*user_id*

but through functions.php, or another hook?

When a user buys a product, I don't want to do this by hand (which is how i am doing it) and to automate it. 
Thanks
David - great plugin btw

**Comment by johngodley** [comment]
You can use either the REST API or the PHP API, as described here:

https://redirection.me/developer/

**Comment by DavidTully13** [comment]
Thanks very much for the link - i will check it out. 
I will close the ticket - thanks again pal!!!
