### ISSUE TITLE
Getting 200 error on attempted redirect 

### ISSUE THREAD

**Issue by lancehelms** [johngodley/redirection#2021]
I just added a new redirect and it's not working or recording any hits. When I use the Check Redirect function I get the attached error message that says "Found: 200 / Agent: Not using Redirection". 
<img width="883" alt="Screen Shot 2019-10-13 at 18 44 25" src="https://user-images.githubusercontent.com/56521959/66724092-617c1800-edef-11e9-8e0d-6b8549e597b5.png">

Here's the new redirect that's not working: 
Source URL: http://whosoever.org/v18i2/index.shtml
Target URL: http://whosoever.org/volume-18-issue-2-justice/
<img width="1047" alt="Screen Shot 2019-10-13 at 19 25 40" src="https://user-images.githubusercontent.com/56521959/66724091-617c1800-edef-11e9-9844-14ac4485b5e7.png">

I'm on Mac Chrome Version 69.0.3497.100 (Official Build) (64-bit), WordPress 5.2.3, and Redirection version 4.4.2. The site is hosted on 1&1/Ionos. I've cleared my browser cache and attempted to clear my WordPress cache using WP Fastest Cache, and I've also disabled all other plugins.  

I have 110 other redirects live in the plugin and they all appear to be running. I see up to date logging information with 42,895 items logged since I installed the plugin about six months ago.

Here's an example redirect that's working, with 260+ recorded hits: 
Source URL: http://whosoever.org/aian.html
Target URL: http://whosoever.org/v1i1/aian.shtml 
<img width="1039" alt="Screen Shot 2019-10-13 at 19 25 59" src="https://user-images.githubusercontent.com/56521959/66724090-60e38180-edef-11e9-8ae0-15118e1d552b.png">

Very much appreciate any insight you can provide. The plugin has worked quite well up to now.

**Comment by johngodley** [comment]
This is probably your server configuration, as explained here:

https://redirection.me/support/faq/#pdf

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
