### ISSUE TITLE
Duplicate entries?

### ISSUE THREAD

**Issue by kalvan81230** [johngodley/redirection#2024]
### Summary
I am using Redirection to track and redirect 404 errors on my web page.  The page was just converted from html, so there are lots of people with links into the old site.  I want to help people get to where they want to go.

### Actual Behavior

The log file has many duplicate entries.  Is there a way to consolidate the duplicates and have a hit count on them?

### Steps to reproduce

Turn on redirection and wait a few minutes

### Environment

Firefox, nginx, WP

**Comment by johngodley** [comment]
Yes, press the 'group by' dropdown at the top of the page.

**Comment by kalvan81230** [comment]
Thank you!
