### ISSUE TITLE
Error loading csv in plugin redirection

### ISSUE THREAD

**Issue by tiendasexpress** [johngodley/redirection#2027]
[siete.zip](https://github.com/johngodley/redirection/files/3736048/siete.zip)
Hi, I try to load csv in the redirection plugin and it doesn't load, I've tried hundreds of ways and there's no way to load it
can you help me?
Thanks!

))))

To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
That's a semi-colon separated file, not a comma separated file:

`/10452-autosave-v1/;https://ibizabyday.com`

It should be:

`/10452-autosave-v1/,https://ibizabyday.com`

**Comment by tiendasexpress** [comment]
It was that!! Thank you very much for your help!! 

Thanks!!
