### ISSUE TITLE
Redirection Error occurs when searching for .png but not png

### ISSUE THREAD

**Issue by davidshq** [johngodley/redirection#2029]
Error seems to indicate a nonce issue, but works fine when searching for "png" only becomes problematic when attempting to search for ".png"

Does not occur when searching with . for other extensions, e.g. ".tar" works fine.
```
Plugin: 4.4.2
WordPress: 5.2.4 (single)
PHP: 7.3.10-1+0~20191008.45+debian8~1.gbp365209
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
JavaScript: http://wpdeveloping.com/wp-content/plugins/redirection/redirection.js
REST API: http://wpdeveloping.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/404/?filterBy%5Burl%5D=.png GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment]
I wasn't able to reproduce this on my sites. I wonder if there is some other software running, either in WordPress or at the server level, that is intercepting the `.png` and doing something different?

For example, could your server be configured such that it sees the request to `/wp-json/redirection/v1/404/?filterBy%5Burl%5D=.png` and thinks it's a PNG file, and bypasses WordPress?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
