### ISSUE TITLE
Merge log URLs and exclude some pages

### ISSUE THREAD

**Issue by Dibbyo456** [johngodley/redirection#203]
Would you like to add these feature? I know many would want this too.

- More HTTP Codes - **410 Content Deleted** (A must have)
- There is no custom HTTP options in "Add new redirection" column, there should be.
- [Optional] Don't keep logs same 404 Pages if already a log exists even on the different IP
- Exclude some pages from Tracking (CSS, JS, IMGs)

Edit: First 2 features are already exists, you can ignore them.

**Comment by johngodley** [comment]
HTTP 410 is already available.

What's a custom HTTP option?

**Comment by Dibbyo456** [comment]
Where?

**Comment by Dibbyo456** [comment]
@johngodley 

> HTTP 410 is already available.

Where? [It's not here](http://prntscr.com/ffogkz)

There is no option to set HTTP Codes - [HERE](http://prntscr.com/ffogpr)

**Comment by johngodley** [comment]
Add a 404 action then edit it and change the code to 410

Yes, you cannot set custom HTTP codes. Can you describe how this would be used?

**Comment by Dibbyo456** [comment]
@johngodley Oh. Found it. You can ignore the first 2 issues now. Can you do something about the last 2 ?

**Comment by johngodley** [comment]
I know it's a while since this was opened, and I'm going back to clean up older items.

Regarding the last two items:

- I don't think ignoring duplicate log entries is a good thing as it defeats the purpose of a log
- You can ignore URLs by adding a 'do nothing' action for that URL. They then won't be logged
