### ISSUE TITLE
Problem starting Redirection 4.4.2

### ISSUE THREAD

**Issue by BlaireMclaren** [johngodley/redirection#2032]
Plugin: 4.4.2
WordPress: 5.2.4 (single)
PHP: 7.2.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
JavaScript: https://deaddeath.com/wp-content/plugins/redirection/redirection.js
REST API: https://deaddeath.com/wp-json/

**Comment by johngodley** [comment]
This is probably caused by another plugin. If you open your browser's developer console it may show other errors.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
