### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by Tiphaine450** [johngodley/redirection#2039]
Bonjour,
J'ai un souci de redirection une erreur 310 s'affiche. Du coup mon blog n'est pas indexé. Quelqu'un peut m'aider?
Message affiché par le plugin redirection : 
Plugin: 4.4.2
WordPress: 5.2.4 (single)
PHP: 7.3.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
JavaScript: https://comback.alwaysdata.net/blog/wp-content/plugins/redirection/redirection.js
REST API: https://comback.alwaysdata.net/blog/index.php/wp-json/
Buster: 4.4.2 === 4.4.2

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in span
    in div
    in div

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if more information is shown?

**Comment by Tiphaine450** [comment]
Excusez-moi c'est à dire ?
Un ami m'a aidé il y avait une application qui faisait bugger mon site par contre j'ai toujours un souci, impossible de mettre à jour ou d'installer un nouveau plugin et un tout petit message s'affiche au moment du chargement : '; ?>

**Comment by Tiphaine450** [comment]
... s'affiche à chaque chargement de page.

**Comment by johngodley** [comment]
I don't know what you mean by that.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
