### ISSUE TITLE
rules with .php extention not working

### ISSUE THREAD

**Issue by cyfox1** [johngodley/redirection#2045]
For some reason rules that has .php extention are not working, if they end with a / or .html they work fine, the error  that I'm getting is a  File not found error and when I check the redirect on the under the rules options this is what I get

Expected: 301 to https://www.rhcinsurance.com/service/business-insurance/

Found: 404

Agent: Not using Redirection

could you please advise

**Comment by johngodley** [comment]
Please see https://redirection.me/support/faq/#pdf

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
