### ISSUE TITLE
problem with my website, somehow is redirecting to 404 empty pages 

### ISSUE THREAD

**Issue by repunto** [johngodley/redirection#2048]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### need urgent help i deactivated the plugin but still is redirecting to 404 pages

Please list your browser, browser version, version of WordPress and Redirection plugin.
chrome, firefox and brave updated
last version wordpress and plugin

**Comment by repunto** [comment]
Dear friend you can see here  https://inkajungletour.com/
go to any other language version and you will see

I dont know whats happening and need help because is not the cache, im
cleaning cache and trying with different browsers

**Comment by johngodley** [comment]
Ok, but if you have disabled the plugin it is impossible for it to be redirecting anything.

Looking at https://inkajungletour.com/fr/

https://redirect.li/http/?url=https%3A%2F%2Finkajungletour.com%2Ffr%2F

You will see that Redirection is not redirecting this URL. You will need to look elsewhere.

**Comment by repunto** [comment]
Hello John

Check again https://inkajungletour.com/
I just deactivated plugins "redirection" , "yoast" but still the same
problem

**Comment by johngodley** [comment]
Please re-read my last message. Nothing has changed, and Redirection is **not** redirecting the URL https://inkajungletour.com/fr/, nor is it redirecting https://inkajungletour.com/en/

**Comment by repunto** [comment]
Dear John could you tell me some advice what can be the problem if is not
the plugin

**Comment by repunto** [comment]
If you know how to solve this problem let me know if you can do it and how
much can cost for your service please
