### ISSUE TITLE
import 410 redirects

### ISSUE THREAD

**Issue by afonyatorta** [johngodley/redirection#2050]
I have around 16 000 urls that I would like to delete with the 410 code, so I would like to use the import feature (as .csv).

Once I imported my .csv all redirects got the 310 code. 

How can I import 410 redirects properly?

Safari 12.1.1., wordpress 5.2.4., redirection 4.4.2.

Thanks for your help in advance!

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
