### ISSUE TITLE
Redirection Plugin: Idea for improvement 

### ISSUE THREAD

**Issue by Fonda61** [johngodley/redirection#2052]
Hello John,
I have modified hundreds of media file names using a plugin called Media File Renamer. It works pretty well and is able to generate a csv file with all the redirections from old to new names. Unfortunately it only applies to the main jpg files and not the various thumbnails files (e.g.  image-150-150.jpg). To manage this, I have manually modified all redirections using regular expressions and activated Regex for the redirections. Pretty tedious for hundreds of images!
I have just sent a note to the author of the plugin, asking him if he could generate the csv file with regular expressions already embedded.
For the Redirection plugin, what would help in this case is to be able to activate Regex as a bulk action for all redirections within a group. Please consider this.
Thank you
Patrick

**Comment by johngodley** [comment]
The plugin will import regular expressions with the regular expression option enabled.

**Comment by Fonda61** [comment]
Sorry I don't understand your response.  Is there a global option for regex?  I don't see it.

**Comment by johngodley** [comment]
When you import a redirect via CSV that a contains regular expression it will automatically be marked as regex. There is no need to enable an option for this.

**Comment by Fonda61** [comment]
Very clear, thank you.
