### ISSUE TITLE
Ideas for improvement: select on delete, etc

### ISSUE THREAD

**Issue by andersalhbin** [johngodley/redirection#2053]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Suggestion to get a perfect action-on-delete-posts handling :-)

### Actual Behavior

Love your redirection plugin. But I would love it even more if it could have the following functionality:

When deleting post - automatically set redirection to pre-set URL. Today you almost have this, but you know need to manually activate it and it per default sets root page /.
The option to decide the default redirection page and the option to make it happens automatically would be great.

And to make it excellent (this functionality I had in a CMS of my own before and it was very appreciated by the users...) is to in the deleting process get an option to set a redirection URL for the specific page I am deleting.
First you could have a based option saying something like:

On delete 
O - Always set default redirection URL (/my-preset-default-url/) 
O - Decide for each post when deleting
and could you set this decision per post-type (page/post/activities/etc/etc) it would be perfect!

That is - when set to decide for each post - you click on delete post - you get a flag saying something like: 

---------------------------------------------------------------------------------------------
You are now deleting this post

O - Permanent redirect (301)
O - Temporary redirect (307)
O - possibly other types?

O - Redirect to default URL (/my-preset-default-url/)
O - Redirect to this URL ______________________________ (bonus if you could search existing posts as when you set a link!!)
O - No redirection

SAVE
---------------------------------------------------------------------------------------------  

This would make it a perfect redirection tool!
Not sure how complicated it would be to interact with the post delete process though...?

I would happily donate for this functionality!

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Moving to #3349
