### ISSUE TITLE
Problem starting from 4.3.1 version with usage of +

### ISSUE THREAD

**Issue by ukaradhyula** [johngodley/redirection#2056]
### Summary
Our redirect URL which is encoded, has %2B and the redirection plugin seems to be turning this into + and when the URL reaches its destination after the redirect, it is having + and is becoming a wrong URL now. 

### Actual Behavior
The redirect plugin is changing %2B to +. + in the URL decodes to space, so space reaches the backend.

### Steps to reproduce
This is an example URL – https://www.example.com/app/showPage?Parameter=2r8b%2B6h
where example.com WordPress site uses the redirection plugin to redirect to another server. Now if you see the parameter, there is %2B in it. This seems to be getting changed to + by the plugin when the URL is redirected.
Before URL: https://www.example.com/app/showPage?Parameter=2r8b%2B6h
After URL : https://anotherserver.com/app/showPage?Parameter=2r8b+6h
Redirect rule:
Source URL: ^/app/(.*)$
Target URL: https://anotherserver.com/app/$1

### Environment
WordPress version: 4.9.8
Redirection plugin version w/ issues: Starting from 4.3.1

## Additional details
- [Changelog](https://wordpress.org/plugins/redirection/#developers) for 4.3.1 on 8th June 2019 has _Fix + character being removed from source URL_

**Comment by johngodley** [comment]
This was a lot trickier than it seems. I've got a working fix in #2088, which will make it into a future version. I'll probably release it as to beta soon too.

**Comment by ukaradhyula** [comment]
Thanks for addressing this issue. We will give it a test once it is in beta.
