### ISSUE TITLE
Redirection Error - rest_forbidden 401

### ISSUE THREAD

**Issue by madwort** [johngodley/redirection#2057]
```
Plugin: 4.4.2
WordPress: 5.1.3 (single)
PHP: 5.5.9-1ubuntu4.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0
JavaScript: https://www.woodlands.co.uk/wordpress/wp-content/plugins/redirection/redirection.js
REST API: https://www.woodlands.co.uk/wp-json/

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```
Attempting to update `Your database is at version 2.4 and the latest is 4.1.`

The regular setup has CloudFlare, WP-Optimize & Wordfence, but completely disabling WP-Optimize & Wordfence & flushing Cloudflare cache doesn't seem to help.

**Comment by johngodley** [comment]
Something on your site is blocking your WordPress REST API. Usually this is a security plugin. Until that problem is resolved you won't be able to complete the upgrade.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
