### ISSUE TITLE
I was wondering if you could know how many hits a 404 URL. Had the same IP.

### ISSUE THREAD

**Issue by PauloBoaventura** [johngodley/redirection#2058]
### Summary

I was wondering if you could know how many hits a 404 URL. Had the same IP. I believe this information is important.

### Actual Behavior

Current version does not have visit / hit option as 404 behavior URLs

### Environment

Plugin: 4.4.2
WordPress: 5.2.4 (unique)
PHP: 7.3.11
Browser: Mozilla / 5.0 (X11; Linux x86_64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 77.0.3865.120 Safari / 537.36

**Comment by johngodley** [comment]
On the 404 page you can group by IP or URL

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
