### ISSUE TITLE
Problem starting Redirection 4.4.2

### ISSUE THREAD

**Issue by fernandoruizanton** [johngodley/redirection#2059]
```
Uncaught SyntaxError: Unexpected token ';' https://--------------------.com/wp-content/plugins/redirection/redirection.js?ver=4.4.2-dd4f7bc71ce67ad6763df5e0b4a4886a 33
```

Plugin: 4.4.2
WordPress: 5.2.4 (single)
PHP: 7.1.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
JavaScript: https://f--------------------.com/wp-content/plugins/redirection/redirection.js
REST API: https://f--------------------.com/wp-json/

**Comment by johngodley** [comment]
Can you provide a working link to the file?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
