### ISSUE TITLE
Unable to perform action - bad nonce

### ISSUE THREAD

**Issue by broekmancomm** [johngodley/redirection#206]
I'm building a massive list of redirects for a new website. Plenty of dead pages that were lost in translation and weren't relevant to Organic search.

Challenge is that some are now getting this "Unable to perform action - bad nonce" error. 

Any reason for that? Anyone know how to fix?

**Comment by johngodley** [comment]
Are you adding redirects from the main redirection page? How frequently does it happen? When it does happen, how do you resolve it? (i.e. does refreshing the page make it work again)

**Comment by johngodley** [comment]
This message is no longer part of the plugin and so I will close this issue. If you have more information then please reopen
