### ISSUE TITLE
Trailing Slash on URL Redirects to Wrong Page

### ISSUE THREAD

**Issue by kevinbooth** [johngodley/redirection#2062]
### Summary

It looks like URLs with similar WordPress permalink naming are resolving to the wrong page if a trailing slash is added to the URL.

### Actual Behavior

I have two landing pages that have two redirects setup to direct to the WordPress Permalinks:
/mortgage-bankhometown
/mortgage-bankesb

The redirects are setup as (See below for more in depth setup):
/bankHometown/Mortgage
/bankESB/Mortgage

If I add a trailing slash to the url, /bankHometown/Mortage/, it redirects me to the target /mortgage-bankesb (redirect source url: /bankESB/Mortgage).

The only way I am able to get around it is by changing the bankESB WordPress permalink to something that comes alphabetically after the bankHometown link (ex: /landing/mortgage-bankg). If you would like the domain name of the development site, I can send it privately for you to take a look at.

### Steps to reproduce

Go to:
/bankHometown/Mortgage
* You will be redirected to the bankHometown Mortgage landing page
* WordPress URL: /landing/mortgage-bankhometown
* Proper redirect

Go to:
/bankHometown/Mortgage/
* You will be redirected to the bankESB Mortgage landing page
* WordPress URL: /landing/mortgage-bankesb
* Improper redirect

The WordPress Permalink naming for both landing pages are as followed:
/landing/mortgage-bankhometown
/landing/mortgage-bankesb

### Environment

WordPress: 5.3
Redirection: 4.4.2

The redirection for bankHometown is setup as followed:
Source URL: /bankHometown/Mortgage
Query Parameters: Ignore & pass parameters to the target
Title:
Match: URL only
When Match: Redirect to URL with HTTP code 308 - Permanent Redirect
Target URL: /landing/mortgage-bankhometown
Group: Redirections Position 3
No Regex, Ignore slash, or Ignore case applied

The redirection for bankESB is setup as followed:
Source URL: /bankESB/Mortgage
Query Parameters: Ignore & pass parameters to the target
Title:
Match: URL only
When Match: Redirect to URL with HTTP code 308 - Permanent Redirect
Target URL: /landing/mortgage-bankesb
Group: Redirections Position 3
No Regex, Ignore slash, or Ignore case applied

WordPress permalink setup:
/mortgage-bankhometown
/mortgage-bankesb

**Comment by johngodley** [comment]
This doesn't sound like something Redirection is doing. Can you include some URLs to test with?

**Comment by kevinbooth** [comment]
I just sent you the URLs to your contact form on your website, as I don't want to show the domain publicly. Thanks!

**Comment by johngodley** [comment]
The URL without a slash is being redirected by Redirection. The one with a slash is being redirected by something else.

**Comment by kevinbooth** [comment]
I was able to fix it by adding both ignore case and ignore slash rules. Thank you for your help!
