### ISSUE TITLE
Problem starting Redirection 4.4.2

### ISSUE THREAD

**Issue by jhosepbarbera** [johngodley/redirection#2067]
```
Uncaught SyntaxError: Unexpected token ';' https://pelis28.co/wp-content/plugins/redirection/redirection.js?ver=4.4.2-dd4f7bc71ce67ad6763df5e0b4a4886a 33
```

Plugin: 4.4.2
WordPress: 5.3 (single)
PHP: 7.2.24
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
JavaScript: https://pelis28.co/wp-content/plugins/redirection/redirection.js
REST API: https://pelis28.co/wp-json/

**Comment by johngodley** [comment]
This URL doesn't work:

https://pelis28.co/wp-content/plugins/redirection/redirection.js

There is no way for Redirection to load.

**Comment by jhosepbarbera** [comment]
uninstall the plugin and reinstall it you can check it now

**Comment by johngodley** [comment]
You may need to clear your browser cache.

**Comment by jhosepbarbera** [comment]
Solved, thank you very much for your help I had forgotten to clear the cache
