### ISSUE TITLE
check redirect shows red X for working server redirects

### ISSUE THREAD

**Issue by OlafEichstaedt** [johngodley/redirection#2069]
### Summary
I have server redirects from www.oldserver.com to www.newserver.com/subpage. When I test them, with "Check redirect" I get the pop-up with an red X but I can see no difference between "expected" and "found". 

### Actual Behavior
The following information is shown  with red "x" that indicates failure:
`Check redirect for: https://www.oldserver.com/`
`Expected: 301 to https://www.newserver.com/subpage`
`Found: 301 to https://www.newserver.com/subpage`
`Agent: Using Redirection`

A redirect that was created automatically for a change of a page's slug works as expected with a green check mark.

`https://www.newserver.com/old_slug`
`Expected: 301 to /new_slug/`
`Found: 301 to /new_slug/`
`Agent: Using Redirection`

### Steps to reproduce
Create a server redirect ... and "Check redirect". 

### Environment
'Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)'
'Wordpress 5.3'
'customized WP BOOTSTARTER theme'

`Advanced Custom Fields PRO	Version 5.8.7 by Elliot Condon`
`Bootstrap 3 Shortcodes	Version 3.3.12 by Michael W. Delaney, Filip Stefansson, and Simon Yeldon`
`Contact Form 7	Version 5.1.5 by Takayuki Miyoshi`
`Custom Post Type UI	Version 1.7.1 by WebDevStudios`
`Email Subscribers & Newsletters	Version 4.3.2 by Icegram`
`Google XML Sitemaps	Version 4.1.0 by Arne Brachhold`
`Really Simple CAPTCHA	Version 2.0.2 by Takayuki Miyoshi`
`Redirection	Version 4.4.2 by John Godley`
`Regenerate Thumbnails	Version 3.1.2 by Alex Mills (Viper007Bond)`
`User Role Editor	Version 4.52.1 by Vladimir Garagulya`

![image](https://user-images.githubusercontent.com/24755597/69478161-49ee7100-0e2a-11ea-929e-f3be42b3ab51.png)

**Comment by johngodley** [comment]
What is the actual URL being checked?

**Comment by OlafEichstaedt** [comment]
there are several, 1 example is `https://linova.org/`

**Comment by johngodley** [comment]
And can you show the settings for this redirect?

**Comment by OlafEichstaedt** [comment]
![image](https://user-images.githubusercontent.com/24755597/69479246-0c8fe080-0e36-11ea-9017-aa42643e1686.png)

**Comment by johngodley** [comment]
Ok, it is misinterpreting the results because of the server redirect. You can ignore this result for now until it is fixed.

**Comment by OlafEichstaedt** [comment]
no problem, I could see it worked, just wanted to let you know that the display is confusing ... and I completely forgot: thanks for the nice plug-in!

**Comment by johngodley** [comment]
This will be fixed by 71160e563b3d78d78f1acbef1d270accf34fb700 and released in the next version
