### ISSUE TITLE
referer for server redirects does no show up in logs

### ISSUE THREAD

**Issue by OlafEichstaedt** [johngodley/redirection#2070]
### Summary
I have server redirects from www.oldserver.com to www.newserver.com/subpage. 
Successful 301 redirects show up in the log, but the column "referrer" is empty ... except for 1 case in 30 that I cannot reproduce. 

### Actual Behavior
see summary

### Expected Behavior
referrer column shows "www.oldserver.com" as referrer

### Steps to reproduce
Create a server redirect ... and check the log

### Environment
'Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)'
'Wordpress 5.3'
'customized WP BOOTSTARTER theme'

`Advanced Custom Fields PRO	Version 5.8.7 by Elliot Condon`
`Bootstrap 3 Shortcodes	Version 3.3.12 by Michael W. Delaney, Filip Stefansson, and Simon Yeldon`
`Contact Form 7	Version 5.1.5 by Takayuki Miyoshi`
`Custom Post Type UI	Version 1.7.1 by WebDevStudios`
`Email Subscribers & Newsletters	Version 4.3.2 by Icegram`
`Google XML Sitemaps	Version 4.1.0 by Arne Brachhold`
`Really Simple CAPTCHA	Version 2.0.2 by Takayuki Miyoshi`
`Redirection	Version 4.4.2 by John Godley`
`Regenerate Thumbnails	Version 3.1.2 by Alex Mills (Viper007Bond)`
`User Role Editor	Version 4.52.1 by Vladimir Garagulya`

**Comment by johngodley** [comment]
Referrer information is dependant on the browser and is not guaranteed to be sent.

**Comment by OlafEichstaedt** [comment]
I tried with Google Chrome, Firefox 70.0.1 (64-bit), IE 11.476.18362.0, Microsoft Edge 44.18362.449.0 ... none of them shows the referrer ...

**Comment by johngodley** [comment]
Ok. You can find more information about referrer information by searching:

https://en.wikipedia.org/wiki/HTTP_referer

Redirection will log it if present.

**Comment by OlafEichstaedt** [comment]
I see ... my mistake ... I assumed that in the context of the log, "referer" would have been the server part of the request that triggered the redirect. Unfortunately, the "source URL" column does not contain the server part for server redirects. 

![image](https://user-images.githubusercontent.com/24755597/69479356-3f86a400-0e37-11ea-98b8-21cd56a1eb5a.png)

**Comment by johngodley** [comment]
No, the domain is not currently included in the log. See this issue to track that:

https://github.com/johngodley/redirection/issues/816

The domain could be included in the referrer if the information is passed by the browser, but this is not guaranteed.
