### ISSUE TITLE
Fatal bug

### ISSUE THREAD

**Issue by JailbreakVideo** [johngodley/redirection#2071]
Hi, John, and thank you for _**Redirection**_ 🖐
Unfortunately today's **_Redirection_** update kills my site.
More info in this video: https://drive.google.com/open?id=1Z7XWtR9asZd2GBzhxj6IHoK1P3LL9I4c

**Comment by johngodley** [comment]
Please see the version 4.5.1 fix!

**Comment by JailbreakVideo** [comment]
Yes. Now it works perfectly 👏
Thank you 🤝
