### ISSUE TITLE
Clashes with elementor plugin

### ISSUE THREAD

**Issue by lonix1** [johngodley/redirection#2076]
When this plugin is active, elementor doesn't load.

I'm using the very latest of wordpress, elementor and redirection. Doesn't work even if I bump the memory to 512MB.

Has anyone else had this problem? How can I get them to coexist? Strange thing is they worked for a long time, it's only now they refuse to cooperate.

I have one redirection only, from `/` to `/foo`,

**Comment by johngodley** [comment]
What is elementor and how doesn't it load? Do you have any redirects that could affect it?

**Comment by lonix1** [comment]
[Elementor](https://wordpress.org/plugins/elementor/) is the most popular page builder for wordpress. It's huge.

When I try to load it doesn't load. I read on many of their forums that there are problems when redirects are on.

So I came here hoping to find out how others dealt with the problem. I'm hoping someone will advise me about a fix or workaround.

I have only one redirect like I wrote above, but frankly I don't understand why it would affect elementor as it's a server-side thing.

**Comment by lonix1** [comment]
BTW, is there a way to force this plugin to only work for client-side requests? So it wouldn't work for any server-side / admin stuff?

**Comment by johngodley** [comment]
I don't know how Elementor works. How doesn't it load? Is there an error? Can you open your browser's developer console and see if any network requests are made that fail?

The concept of server/client doesn't really apply to the plugin. It redirects a URL to another URL. If Redirection is redirecting elementor then you will see that in the Redirection logs

**Comment by lonix1** [comment]
I have a redirect from `/` to `/example`.

So when I load elementor it redirects from `/?post_type=elementor_library&p=1324&elementor-preview=1324` to `/example?post_type=elementor_library&p=1324&elementor-preview=1324`. I think that causes the problem.

Is there a way to make this plugin check whether the user is logged in or is an admin? In such a case there's a good chance the user is doing something on the admin pages which shouldn't lead to a redirect. Maybe that could be an option.

Is there a way I can make it work like that? A hook or something perhaps?

**Comment by johngodley** [comment]
Alright, yep that's probably the problem. Elementor should really use the standard WordPress request mechanisms through either admin ajax or the REST API and then it wouldn't be affected by these kind of issues.

You can configure a redirect to use the logged in status:

https://redirection.me/support/matching-redirects/

**Comment by lonix1** [comment]
Great! I missed that little cog icon so I didn't see the advanced options.

Thanks for your help... appreciate it!
