### ISSUE TITLE
the regular expression to the url like ^/wp-content/plugins/.*  is source url and it is not getting redirected.

### ISSUE THREAD

**Issue by Srimani1997** [johngodley/redirection#2077]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by Srimani1997** [comment]
i wrote  a source url ^/wp-content/plugins/.* is not redirecting all the urls like this.

**Comment by johngodley** [comment]
The plugin performs regular expressions according to what you specify. Also, have you looked at https://redirection.me/support/problems/url-not-redirecting/ ?

It does not seem wise to redirect the plugins directory.

**Comment by Srimani1997** [comment]
tq for your support but the code inside those directories is visible soo
can you please tell me how to handle it.


Best regards
Srimani

**Comment by johngodley** [comment]
Why is the code in those directories visible? How is it visible?

Redirecting that directory will cause you problems with plugins, and will break Redirection.

**Comment by Srimani1997** [comment]
Can u please tellme how to hide that code from external accessing using
urls.
my plan is that by redirecting atlest i can hide the code.

Best
Srimani,

**Comment by johngodley** [comment]
Hide what code? Can you give an example

**Comment by Srimani1997** [comment]
hi john
for example, the backend folders maybe like  inside plugins I will have all
folders of plugins and subfolders.
with mydomain.com/wp-content/plugins/elementor/........  something like
this are active and they display some random code on browser which will
affect seo. I want to handle the situation.
best
Srimani

**Comment by johngodley** [comment]
Can you give a specific example of something that is being indexed and shouldn't be? There is generally nothing in plugin directories that is accessible to search engines, other than resources that need to be available, because they are not linked by anything. A search engine cannot find anything if it is not linked.

I really don't think you need to be doing anything for this, and it will just cause problems for your site.

**Comment by Srimani1997** [comment]
Hi john,

https://www.kinaracapital.com/wp-includes/js/mediaelement/mediaelement-and-player.min.js?ver=4.2.6-78496d1

Here is on of the link like that is this not a problem can you please make
it clear.


Best
Srimani

**Comment by johngodley** [comment]
That is a core WordPress file. If you block redirect that then it will break anything that uses it.

It does not affect SEO.

Again, I do not think you should do anything for this, and it will negatively affect your site. URLs like the above are perfectly fine.

**Comment by Srimani1997** [comment]
Hi john

Thanks a lot for your help

Best Regards

Srimani
