### ISSUE TITLE
Add 2 new actions for enable/disable

### ISSUE THREAD

**Issue by iruzevic** [johngodley/redirection#2081]
Hi,

I was wondering can 2 new do_action hooks be added to the plugin.
I see you have a do_action for “redirection_redirect_deleted” that triggers on item delete and another one “redirection_redirect_updated” for whey item details is updated.

I’m missing a hook for “redirection_redirect_enabled” and “redirection_redirect_disabled”. I’m hooking WP Rocket cache plugin to manually delete site cache when a new redirection is created/delete/edited.

It works awesome for the 2 provided hooks but I can’t do anything for enable/disable because there are no hooks.

Is there a way you could add it?

tnx

**Comment by avblink** [comment]
Hi,

I need this feature too.
Is there any plans to add this hook any time soon.

Thank you for the great plugin.
