### ISSUE TITLE
Request: Hide Site menu and Apache .htaccess option for multisite

### ISSUE THREAD

**Issue by JonTheWong** [johngodley/redirection#2084]
### Summary

On a multisite installation giving admins permission to edit .htaccess and force http to https options could break the multisite.

### Actual Behaviour

When a site admin accesses tools.php?page=redirection.php&sub=site they could break other redirect plugins or custom methods.

Writing to htaccess directly isn't advised on most scenarios, especially for site admins.
I would feel safer if site admins didn't have this option. Also exposing file paths is not ideal.

### Suggestions

Wrap both features in if statements, or add filters so we can hide the options in a custom functions/plugin.

**Comment by johngodley** [comment]
Please see https://github.com/johngodley/redirection/releases/tag/4.6-beta-1

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
