### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by thomas-contact** [johngodley/redirection#2085]
```
Plugin: 4.5.1
WordPress: 5.3 (single)
PHP: 7.3.12
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 Avast/77.2.2153.120
JavaScript: https://www.winckelmans.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.winckelmans.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/redirect/
on this server.<br />
</p>
</body></html>

```
Hi ! I encounter an issue with the plugin redirection, See the joined pdf. 
I don't know what to do, Please, be precise.
( I have only two redirections and I use regex. Example : `^/cat/(.*) `    vers 
`/$1`
=
`https://www.mysite.com/cat/(.*)`     vers 
`https://www.mysite.com/$1 `
Maybe it's possible to use  these redirections in .htaccess but I don't know what I have to write exactly and I don't find on the web.)
Thanks very much for your help !
[Redirection PBS09-12-2019‹ Winckelmans — WordPress.pdf](https://github.com/johngodley/redirection/files/3939315/Redirection.PBS09-12-2019.Winckelmans.WordPress.pdf)

**Comment by thomas-contact** [comment]
I add that since today sometimes redirection works sometimes it does not work, for one of the 2 redirections. The problem is that I did not write the second redirection elsewhere than in the plugin. How do I access the redirects list?

**Comment by johngodley** [comment]
Redirects do not randomly swap between working and not working. This is unrelated to the above message and likely to be a browser caching thing.

The error message is likely caused by a security plugin. You may find more info here: https://redirection.me/support/problems/rest-api/

**Comment by thomas-contact** [comment]
Thank you for answering. I’ll look into that : security plugin. Too bad I don’t know the code to put regular expression redirect in htaccess file.

**Comment by thomas-contact** [comment]
One question : if I deactivate the plugin, I lose, in the plugin backoffice, all the redirects it contained, (redirects I can't see since the issue) ?
Thanks to answer
.....................
I find nothing except these 3 posts about syntax error : 

URL: https://www.winckelmans.com/wp-json/
GET SyntaxError: Unexpected token < in JSON at position 0
Unexpected token < in JSON at position 0 (SyntaxError)
WordPress returned an unexpected message. This is probably a PHP error from another plugin.
Possible cause: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden</h1> <p>You don't have permission to access /wp-json/redirection/v1/plugin/test/ on this server.<br /> </p> </body></html>

URL: https://www.winckelmans.com/index.php?rest_route=/
GET SyntaxError: Unexpected token < in JSON at position 0

URL: /wp-json/
GET SyntaxError: Unexpected token < in JSON at position 0
