### ISSUE TITLE
Multisite Redirections from Main Blog? Possible?

### ISSUE THREAD

**Issue by derpoho** [johngodley/redirection#209]
Hey,

we have a special usecase: ~60 Sites combined as Multisite which represent one website.
It would be nice to be able to set redirections for "Sub Sites" in the Main Site. Do you see any possibility to set this up with the most recent version?

Greets

**Comment by johngodley** [comment]
If I understand correctly I think what you are suggesting is covered by this issue?

https://github.com/johngodley/redirection/issues/112

**Comment by derpoho** [comment]
mhm.. kind of. But this issue is suggesting absolute urls which is an option, but not the best one i guess. I have no idea currently how to set this up, since Multisites are handling the site decision in sunrise.php (if you have one) and there is no way currently to hook into that.

I am going with the .htaccess option, it should work across the multisite for now.

**Comment by johngodley** [comment]
The reason I asked is that it sounds like you have one WP install, and want one Redirection plugin to handle the redirects for the 60 subsites? I am assuming the subsites will have different URLs, and so being able to add an absolute URL means you can add redirects for each of the subsites.

I'm not super familiar with multisite though, so if that's not the case then I'd be interested to know what the situation is.

**Comment by johngodley** [comment]
It's been a while since this was posted and the plugin now supports multisite, and it's possible to have different redirects on subdomains. I will close this as 'fixed', but please reopen if it doesn't do what you want
