### ISSUE TITLE
Most of my redirects are not working

### ISSUE THREAD

**Issue by mbeckman13** [johngodley/redirection#2091]
### Summary

I had Chatra running today, and when someone came to my site, the page they were on said 'page not found'. When I clicked on it, I realized it was an old page that I thought I had redirected. I did have a redirect set up, but when I checked the redirect from within the tool, it did not work.

I only mention Chatra b/c this could have been happening for a while, but I didn't notice until today.

### Actual Behavior
There are 4 redirects that are working, and 6 that are not.

This is an example of one redirect that's not working:

Check redirect for: https://www.sundaydinnerstories.com/memoirservices/
Expected: 301 to https://www.sundaydinnerstories.com/services/

Found: 301 to https://sundaydinnerstories.com/memoirservices/

Agent: Not using Redirection

### Steps to reproduce
Here are all the steps I tried so far to no avail:

Multiple times, I tried clearing the cache on my laptop and also using an incognito window.
I tested on another laptop and on an iOS phone.
I deactivated all plugins, but the problem was still an issue. (I've since activated them again.)
I tried using the Microsoft Edge browser.
I deleted the redirect and created a new one.

### Environment
I'm using WP 5.3.1
Browser on my laptop is Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Redirection version: Version 4.5.1 

###Question
I don't know where else to go from here. When I installed Redirection, it all worked.
Thank you for your help.

**Comment by johngodley** [comment]
What is Chatra?

What redirect have you created for the URL that isn't working? Note that for the above example URL you are first redirecting from www to no www.

**Comment by mbeckman13** [comment]
Chatra is an instant messaging service you can add to your site, and you can see which pages the user is on real time. That's why I saw the error.

I deleted the redirect I referenced above and created a new one to make sure I'm setting this up correctly. The target URL exists, but the redirect says the page cannot be found. Here's the redirect I have right now and then the results of the Check Redirect. What am I missing?

![memoirservices](https://user-images.githubusercontent.com/58866778/71028363-2215c480-20db-11ea-9a3a-e05e003881a7.PNG)

![check redirect](https://user-images.githubusercontent.com/58866778/71028856-1aa2eb00-20dc-11ea-9f82-b9586ea5fa7c.PNG)

**Comment by johngodley** [comment]
Your site appears to be cached. If this URL is part of the cache then you will need to clear it.

**Comment by mbeckman13** [comment]
Do you mean clearing my browsers? I've done that multiple times. Is there something else I should be trying to clear?

**Comment by johngodley** [comment]
No, clearing whatever caching system you are using on your site.

**Comment by mbeckman13** [comment]
Thank you. I figured out how to clear the site's cache (I've never had to do that before.) All redirects appear to be working now. Thanks so much.
