### ISSUE TITLE
Hello John

### ISSUE THREAD

**Issue by Chloedigi** [johngodley/redirection#2094]
Hello,

I have this issues in wordpress, 
Wordpress version is WordPress 4.6.17,
Can you help me please ?

Thank you,

Here the link of my screenshot :

<img width="863" alt="2019-12-17 15_23_39-Redirection ‹ N Séguin inc  Syndic autorisé en insolvabilité — WordPress" src="https://user-images.githubusercontent.com/58995184/71033280-e9222380-20cb-11ea-847b-7044dad8dba9.png">

**Comment by johngodley** [comment]
What are you doing to receive that message?

Redirection requires WordPress 4.9 or newer, and may not work on earlier versions.

**Comment by Chloedigi** [comment]
Ok thx you for your answer !
