### ISSUE TITLE
Pass-through with media files doesn't set content-type

### ISSUE THREAD

**Issue by mortoray** [johngodley/redirection#2099]
I'm trying to make short links to PDF files (stored in media). I use the pass-through option to keep the URL. I should be able to download/view the PDF with the new link. 

Unfortunately the original content-type is not maintained and the browser renders the PDF as HTML (garbage output).

Plugin Version 4.5.1

**Comment by johngodley** [comment]
Yes, the plugin is not designed to do this.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.

**Comment by Freundschaft** [comment]
I have exactly the same problem. wouldnt it be possible to add this functionality?

**Comment by omric-axonize** [comment]
I have the same issue with json files, it would be great if content-type will stay the same as original
Thanks!
