### ISSUE TITLE
No IP is saved in 404 Logs (version 2.6.2)

### ISSUE THREAD

**Issue by kadai** [johngodley/redirection#210]
Greetings,

I have been noticing the issue in my WordPress install... I am unsure when it actually started, but nowadays I only get "0.0.0.0" as the IP for any visitor that lands on a non-existant page. Even when I try and check the 404 pages myself, I get the 0.0.0.0 in me.

Attached the picture with the problem, the hidden referrals shows when I made the tests.

Please note that I am behind a reverse proxy (CloudFlare) and that I have added the next in order to restore a server variable (in wp-config.php):

```
if ( !empty( $_SERVER['REMOTE_ADDR'] ) && !empty( $_SERVER['HTTP_CF_CONNECTING_IP'] ) )
    $_SERVER['REMOTE_ADDR'] = $_SERVER['HTTP_CF_CONNECTING_IP'];
```

As an additional side note, I am on a multisite install, with SSL enabled.

While not critical, recovering this data can be useful to track better malicious people behaviors.

![no-ips](https://user-images.githubusercontent.com/1930055/27099594-0c3d2ddc-5041-11e7-9bb6-263b53709b16.png)

EDIT: Whoops, forgot to mention that I am running Apache + PHP 7.0.16 on that server.

**Comment by kadai** [comment]
Whoops, forgot to mention that I am running Apache + PHP 7.0.16 on that server.

**Comment by johngodley** [comment]
There was a recent change to unify the IP collection. It uses `HTTP_X_FORWARDED_FOR` first, and `REMOTE_ADDR` if that doesn't exist. Does your server happen to defined `HTTP_X_FORWARDED_FOR`?

**Comment by kadai** [comment]
Yes, it assigns it... BUT I noticed it does it like this:
<remote_ip>, <cloudflare_ip>

EJ: 54.xxx.137.xx, 162.xxx.224.xx

No idea if this is an expected output. Could be that this is causing issues? The cloudflare IP always goes last.

Sadly, I can't change the way this is set, maybe just then stripping the other IP via PHP in wp-config or in the plugging?

I mean, without having look at the code, I believe that the additional colon there (and that the IP is larger than expected) just defaults the value to "0.0.0.0" as a fallback when trying to save it to the database?
