### ISSUE TITLE
Problem starting Redirection 4.5.1

### ISSUE THREAD

**Issue by thesoulwithin** [johngodley/redirection#2106]
Plugin: 4.5.1
WordPress: 5.3.2 (single)
PHP: 7.2.26
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
JavaScript: https://www.citywidecpr.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.citywidecpr.com/wp-json/

**Comment by johngodley** [comment]
Please open your browser's developer console and see if any more errors are shown. This is likely caused by another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
