### ISSUE TITLE
*.jpg redirection doesn't work with certain nginx configuration

### ISSUE THREAD

**Issue by vperep** [johngodley/redirection#2109]
Good day!

### Summary

I am trying to make redirect 
from https://dom-noi.ru/images/stories/content/dsc_3047m.jpg
to https://dom-noi.ru/wp-content/uploads/2019/12/dsc_3047m.jpg

This is the rule: https://i.imgur.com/53rIPvA.png
the environment looks fine: https://i.imgur.com/YPF2erd.png

The redirection doesn't work if this nginx rule exists:
```
location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|webp)$ {
        expires max;
        add_header Cache-Control "public, no-transform";
}
```

If I remove this rule completely, the redirection and "Check Redirect" works fine.

I tried to disable next plugins:
404page - your smart custom 404 error page | Version 11.1.4 by Peter Raschendorfer
Autoptimize | Version 2.6.1 by Frank Goossens (futtta)
Broken Link Checker | Version 1.11.9 by ManageWP

But - no success.

Would you please help me understand the reason.

Regards,
Vladimir

### Actual Behavior

With nginx rule mentioned above ( https://i.imgur.com/bcZIPsh.png ) and redirection rule ON, I got 404 error: https://i.imgur.com/52WYU0B.png
and https://i.imgur.com/lWsKfjP.png

### Steps to reproduce

If I comment nginx code block https://i.imgur.com/MJC8JZs.png
then reload nginx:
`nginx -s reload`

I have the redirect working:
https://i.imgur.com/2jaohHH.png
https://i.imgur.com/segKCtj.png

### Environment

Ubuntu 18.04.3 LTS
nginx/1.16.1
Wordpress Version | 5.3.2
theme: Avada 6.1.2
mysqli version | 8.0.18
Chrome 79.0.3945.88

**Active plugins:**
404page - your smart custom 404 error page | Version 11.1.4 by Peter Raschendorfer
Autoptimize | Version 2.6.1 by Frank Goossens (futtta)
Broken Link Checker | Version 1.11.9 by ManageWP
Classic Editor | Version 1.5 by WordPress Contributors
Contact Form 7 | Version 5.1.6 by Takayuki Miyoshi
Contact Form CFDB7 | Version 1.2.4.8 by Arshid
Crop Thumbnails | Version 1.2.6 by Volkmar Kantor
Cyr-To-Lat | Version 4.3.2 by Sergey Biryukov, Mikhail Kobzarev, Igor Gergel
Duplicate Post | Version 3.2.4 by Enrico Battocchi
Fusion Builder | Version 2.1.2 by ThemeFusion
Fusion Core | Version 4.1.2 by ThemeFusion
Google Tag Manager for Wordpress | Version 1.11.2 by Thomas Geiger
Media Library Assistant | Version 2.81 by David Lingren
Nginx Cache | Version 1.0.4 by Till Krüss
Phoenix Media Rename | Version 1.3.4 by crossi72
Post SMTP | Version 2.0.6 by Yehuda Hassine
Redirection | Version 4.5.1 by John Godley
Regenerate Thumbnails | Version 3.1.2 by Alex Mills (Viper007Bond)
WebP Express | Version 0.17.2 by Bjørn Rosell
WP-Optimize - Clean, Compress, Cache | Version 3.0.15 by David Anderson, Ruhani Rabin, Team Updraft
Yandex.Metrica Counter | Version 1.4.1 by Alexander Semikashev
Yoast SEO | Version 12.7.1 by Team Yoas

**Comment by johngodley** [comment]
Your Nginx rule will always take precedence. You can find more details about this situation here:

https://redirection.me/support/problems/url-not-redirecting/

**Comment by vperep** [comment]
Dear John!

In the documentation, I only found this suggestion "If your URL is a file then your web server may be configured to handle it directly rather than pass the request through to PHP and WordPress."

Is it means that I must redirect such "file" URLs on the webserver level?

It is strange because even this empty rule makes such negative issue:
location ~* \.(?:jpg|jpeg)$ {
        #empty
}
This rule does nothing actually but, in a strange manner, prevents the redirection for  https://dom-noi.ru/images/stories/content/dsc_3047m.jpg .

OK, if so, would you please tell me what server response your plugin needs to process such redirections in the plugin code?

Maybe I can to add on server level some response like"=404".. or something else
Or I can wrap "location ~* \.(?:jpg|jpeg" into location ~* \.php

The things are that PHP pages also "configured to handle it directly" inside location ~* \.php but your plugin works fine with them.

Sorry, I have lack of skills, but please give me ideas for experiments..

**Comment by johngodley** [comment]
> please tell me what server response your plugin needs to process such redirections in the plugin code?

That's not how things work, and Redirection does not need any special server response.

A request for a URL arrives at your web server (Nginx), which has a set of rules that determine what to do with the request. Some of those rules, such as for real files, may cause Nginx to immediately return a response. One of those rules will pass the request through to PHP, on to WordPress, and ultimately to Redirection.

If the request does not get passed to WordPress then Redirection doesn't even run.

You will need to configure your server so that requests go to WordPress, or you will need to put the redirect in Nginx and ensure it runs before any other rule. Redirection can export to Nginx.

**Comment by vperep** [comment]
Thanks for the clarification, John. Happy New Year!
