### ISSUE TITLE
PHP 5.4 Parse Error in Admin Panel code

### ISSUE THREAD

**Issue by imnotjames** [johngodley/redirection#2113]
### Summary

The redirection plugin purports to be 5.4+ compatible, however in the admin panel it uses `empty` on an expression.  This is not available until 5.5+

https://github.com/johngodley/redirection/blob/95d0f84f4cb503bbacfe35e6e1e315f18c87e690/redirection-admin.php#L390

https://www.php.net/manual/en/function.empty.php

> Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.

### Actual Behavior

A parse error occurs, `cannot use function return value in write context`

### Steps to reproduce

* Install redirection 4.0+ on PHP 5.4.
* Attempt to login to the admin panel.
* View the parse error.

**Comment by johngodley** [comment]
Yep, an update will be released soon. The next version will increase the minimum supported PHP to match that of WordPress.

**Comment by imnotjames** [comment]
Seems reasonable to me.  My suggestion to the person who pointed out the error to me was to upgrade to a reasonable PHP version :)

**Comment by johngodley** [comment]
> My suggestion to the person who pointed out the error to me was to upgrade to a sane PHP version

Absolutely the best option!

I assumed the unit tests covered this situation, but apparently they only go back to 5.6.

Don't worry about a PR, I've got it fixed locally and am just waiting for a clear slot in my schedule to release - probably tomorrow. Appreciate the report though.

**Comment by johngodley** [comment]
This was deployed in 4.6.2, so closing this issue. Thanks!
