### ISSUE TITLE
Feature request: Drop tracking pixels on during redirect

### ISSUE THREAD

**Issue by BenJackGill** [johngodley/redirection#2116]
I would love to be able to drop a tracking pixel for anyone that clicks a link.

Example:

1) Setup redirect on mywebsite.com that points www.mywebsite.com/some-cool-article to www.news.com/really-cool-article
2) Include Facebook tracking pixel on the redirect so that it drops a pixel when someone clicks the link
3) Now when I share www.mywebsite.com/some-cool-article on social media or email or somewhere else off my site, it will pixel them and send them off to the news article without any interruption
4) And since they have now been exposed to my Facebook tracking I can re-market and advertise to them easily

If mywebsite.com has a Facebook tracking pixel installed in the header, does this already work with the current plugin? Will the pixel fire? If not, can I please suggest it as a new feature to be added.

P.S. I found a similar request here, but I think it is asking for something else, I'm not sure because it's not clear: https://github.com/johngodley/redirection/issues/477

**Comment by johngodley** [comment]
#477 is the same. It is not possible to put a pixel on a redirect because that is not how redirects work, and  so #477 talks about integrating with Facebook in a different way. I will close this in favour of the other issue.
