### ISSUE TITLE
Redirect Login Condition Not Working Properly

### ISSUE THREAD

**Issue by James-Did-It** [johngodley/redirection#2117]
### Summary

I manage a streaming video site and am using Groups to control users' access… but when Google encounters a restricted page, it gets a 404 error.

So I am attempting to redirect non-logged-in users to the login page. You can see my setup in the screen shot. When someone who is not logged in visits a child page of "streaming-videos" they should redirect to the My Account page. Otherwise, they should see the video as expected.

![Screen Shot 2020-01-06 at 11 03 02 AM](https://user-images.githubusercontent.com/14076021/71830900-bf7a6d80-3075-11ea-98ba-0f14a9243d4d.png)

### Actual Behavior

Whether a user is logged in or not, all children AND the parent "streaming-videos" redirect to the account page.

### Environment

Tried in Safari 13 and Chrome 79. Mac OS 10.15.2
Wordpress v 5.3.2
Redirection v 4.6.2

## NOTE
Currently disabled the redirect.

**Comment by johngodley** [comment]
What do you mean by Groups? Do you have a URL to look at?

**Comment by James-Did-It** [comment]
If you're not familiar with https://www.itthinx.com/plugins/groups/ it's
pretty stellar.

And in finding that link for you, I found that they offer a 404-redirect
plugin, which is doing the trick. So you may mark this issue RESOLVED. So
sorry to have bothered you.


Best,
James Donegan
James Did It, LLC
jamesdidit.net
