### ISSUE TITLE
Removing the "-" from File Name

### ISSUE THREAD

**Issue by babytoboomer** [johngodley/redirection#212]
/2017/06/07/diy-hanging-lamp/ is supposed to redirect to /2017/06/14/diy-hanging-light/ - but instead, it removes the "-" and redirects to /2017/06/14/diyhanginglight/ which obviously isn't a page. Renaming the new page isn't an option. How can I force it to leave the "-" in the redirect?

Thanks.

**Comment by johngodley** [comment]
Can you show me the redirect in Redirection handling this?

**Comment by johngodley** [comment]
Closing for now, please reopen if you have more info
