### ISSUE TITLE
301 Moved Permanently on Facebook Preview

### ISSUE THREAD

**Issue by amalia-llc** [johngodley/redirection#2121]
When sharing any of our site's pages on Facebook the preview was 301 Move Permanently. Confirmed this with the Facebook Debugger. When Redirection plugin was disabled it went away and the debugger listed no errors and showed the correct preview. Once the plugin was reactivated, the preview seemed to work with showing the image and excerpt but still listed 3 errors which you can see in the attached screenshot. 
![Screenshot 2020-01-07 15 46 23](https://user-images.githubusercontent.com/55495195/71904036-aa7d0780-3165-11ea-85bd-70f1d0d6902d.png)

This is with WordPress updated to latest version and all plugins updated. Using Google Chrome on Mac for the browser. The site is https://cryptotaxaudit.com/.

**Comment by johngodley** [comment]
Ok, this is entirely based on how you have configured Redirection. You will need to look through your configuration and see if any applies to the above screenshot.

**Comment by amalia-llc** [comment]
I've looked through the Redirection settings several times and am not sure what could be causing it. 
Can you please take a look at the two attached screenshots and let me know what I should adjust that can resolve this? Will I need to wait some time to see if it works? 

Also, I have now seen that our other website that uses Redirection (https://donnellytaxlaw.com/) also shows the same errors in the Facebook Debugger. Why is this 301 coming up first? 

![Screenshot 2020-01-08 12 45 32](https://user-images.githubusercontent.com/55495195/71975697-e7540780-3214-11ea-90a2-ff998f56b97e.png)
![Screenshot 2020-01-08 12 45 42](https://user-images.githubusercontent.com/55495195/71975703-ea4ef800-3214-11ea-9e9a-3588237c8d23.png)

Thank you for the help!

**Comment by johngodley** [comment]
There are other settings on other pages.

I don't see a redirect on either of those sites. What URL is actually being redirected?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
