### ISSUE TITLE
Old Domain Still Accessible But Showing New Website

### ISSUE THREAD

**Issue by wardy84** [johngodley/redirection#2123]
Hi,

We have successfully 301 redirected the desired URLs from an old to a new domain and all of the URLs that we requested to be redirected are working. However, we have a problem in that the old domain is still accessible but is showing content from the new website. 

This does not happen on the URLs that were redirected but if we combine the old domain with a new URL from the new website, like below:

_old-domain.com/new-url/_

The content from on the new URL is also showing on this URL even though it has the old domain and not the new one. We are unable to redirect this as it was not a URL on the old website.

The URL canonicals to the new URL so it is not being indexed but obviously it is not really ideal for it to be happening and we would like to stop it.

This is happening across all browsers, version of WordPress - 5.3.2 Version of Redirection - Version 4.6.2 (it occurred on older versions too).

Many thanks for any insights!

**Comment by johngodley** [comment]
Redirection is only responsible for URLs that you do redirect. If you haven't redirected something then it won't do anything. You can redirect URLs that never existed.

**Comment by wardy84** [comment]
Hi John, 
Thanks for the reply. I am aware that it will only redirect ones we have asked, but the point is that in this way we would have to add a redirect for URLs that didn't exist on our old website and exist on the new one only. Does that make sense?
Thanks

**Comment by johngodley** [comment]
Typically you redirect everything from an old site instead of specific URLs. The new site can then determine if the request is valid.

**Comment by wardy84** [comment]
Okay thanks, is there the option in the plugin to force every URL from the old domain to redirect to the new one?

**Comment by johngodley** [comment]
You can use a regular expression:

https://redirection.me/support/redirect-regular-expressions/

It seems you have the old domain on the same server as the new, so you'll also need to use a 'URL and server' match to restrict it to the old domain only:

https://redirection.me/support/matching-redirects/

**Comment by wardy84** [comment]
Thank you very much, John!
