### ISSUE TITLE
Conflict with Custom Permalinks plugin

### ISSUE THREAD

**Issue by plethoradesign** [johngodley/redirection#2125]
I'm running WordPress 5.3.2 and Redirection 4.6.2.

I have it set to monitor posts and pages for URL changes. When I change a page URL alias on the main site, no redirect gets created.

**Comment by johngodley** [comment]
How doesn't it work? Is it just the URL monitoring? Can you create redirects manually and do other things?

**Comment by plethoradesign** [comment]
I did some more testing and it looks like this is caused by a conflict with the Custom Permalinks plugin.

**Comment by plethoradesign** [comment]
Yes, I can create redirects manually. It is just the URL monitoring that is the issue.

**Comment by plethoradesign** [comment]
I did some further testing. The Custom Permalinks plugin prevents the Redirection plugin from monitoring post/page alias changes, and as a result no redirects are automatically created.

**Comment by plethoradesign** [comment]
Feel free to close this issue. Hopefully it will help someone else using Custom Permalinks.
