### ISSUE TITLE
Feature Request: Redirect custom post compatibility with notification plugins

### ISSUE THREAD

**Issue by webmaster-cob** [johngodley/redirection#2126]
I'm trying to set up email notifications for when a new redirect is created by our content editors. Even though I can see Redirects as a custom post type in the [User Role Editor](https://wordpress.org/plugins/user-role-editor/) plugin, I'm not seeing Redirects detected as custom post types in notification plugins like [Notifications](https://wordpress.org/plugins/notification/) and [Better Notifications for WP](https://wordpress.org/plugins/bnfw/). I'm wondering if there's a way Redirects could be updated to allow it to show up in the custom posts these plugins detect. According to notification plugin authors, all custom post types should be supported. 

**Testing:**

1. Install Redirection
2. Install [Notifications](https://wordpress.org/plugins/notification/)
3. Menu > Notifications > Settings > Triggers > Posts > Post Types
4. Try to add Redirects as a Post Type

Thanks for considering this request.

**Comment by johngodley** [comment]
Redirection doesn't use post types, so I dont think it could be used in conjunction with those plugins.

**Comment by SJNBham** [comment]
Ah - OK. I'll open a different feature request then related to sorting redirects by creation and last updated dates. Hopefully that will give the visibility needed to quickly review any new or recently changed redirects.

**Comment by johngodley** [comment]
I'm going to close this one in favour of the other you created.

**Comment by Kubitomakita** [comment]
The Notification plugin can work with the Redirection plugin, but it will need a custom trigger to cover the action when new redirection is created
