### ISSUE TITLE
New custom post create a redirect from / to this post

### ISSUE THREAD

**Issue by ced64k** [johngodley/redirection#214]
Hello,

I'm using this code in my functions.php to automatically create post name and post slug with the firstname and lastname:

```php

// Auto-populate people post title with ACF firstname and lastname
function jb_update_postdata( $value, $post_id, $field ) {
	$people_firstname = get_field('people_firstname', $post_id). ' ' . $value;
	$people_lastname = get_field('people_lastname', $post_id). ' ' . $value;
	$title = $people_firstname;
	$slug = sanitize_title( $title );
	$postdata = array(
		'ID'          => $post_id,
		'post_title'  => $title,
		'post_type'   => 'people',
		'post_name'   => $slug
	);
	wp_update_post( $postdata );
	return $value;
}
add_filter('acf/update_value/name=people_firstname', 'jb_update_postdata', 10, 3);
add_filter('acf/update_value/name=people_lastname', 'jb_update_postdata', 10, 3);
```

It was working before but last week a new post was added and a redirection was created from the homepage:
`/                      /custom-post/custom-post-name`
So everytime you hit the homepage, you are redirected to this post.

I don't know if my code is wrong or if this is a bug in Redirection plugin.

Thank you!

**Comment by johngodley** [comment]
I've not been able to reproduce this, and I don't know when/what triggers your hook.

I've put an additional check in 2.6.3 to prevent an auto-redirect from `/`, so hopefully that will catch it whatever the reason.

**Comment by ced64k** [comment]
Thanks! I'll check.

**Comment by ced64k** [comment]
Hi John, has the additional check been added to latest version ?
