### ISSUE TITLE
REST API: 'enum' is not a valid JSON-Schema type

### ISSUE THREAD

**Issue by pbiron** [johngodley/redirection#2143]
### Summary

When declaring `args` in several places (`orderby` & `direction` for all "filter args" and `upgrade` on the `redirection/v1/plugin/database` route), you use `enum` as their type.  `enum` is a not a valid JSON-Schema type.

In all these cases, I believe the type should be `string`.

### Environment

WP: 5.3.2
Redirection: 4.5.1

**Comment by pbiron** [comment]
Similarly, the type for the `items` arg of the `/redirection/v1/bulk/group/(?P<bulk>delete|enable|disable)` route with methods `WP_REST_Server::EDITABLE` is declared incorrectly: `string|integer` isn't a valid JSON-Schema type.

I'm not sure what the correct declaration should be.

The `description` on that arg says:

> Comma separated list of item IDs to perform action on

If that `description` is 100% correct, then the type should be just `string`.

However, if you also also accept an array of int IDs (I haven't dug into the code enough to know), then the `type` should be `array` and you need to declare the types of the items in the array, e.g.

```
array(
	'items' => array(
		'description' => List of item IDs to perform action on',
		'type' => 'array',
		'items' => array(
			// not sure whether you accept strings here or just ints
			'type' = array( 'string', 'integer' ),
		),
		'required' => true,
	),
)
```

You can read more about how to declare args at [https://json-schema.org/understanding-json-schema/reference/index.html](https://json-schema.org/understanding-json-schema/reference/index.html)

**Comment by johngodley** [comment]
Thanks
