### ISSUE TITLE
Total hit count significantly different in "Redirects" vs "Log" tabs when searching?

### ISSUE THREAD

**Issue by rob** [johngodley/redirection#2145]
Why is the total number under "Hits" in the "Redirects" section for a particular URL different from the total number of results for that same URL when searching for it in the "Log" section?

For example, on our website, "/curiosities-2/" in the "Redirects" search field brings up 82 hits.

The same "/curiosities-2/" search in the "Log" section brings up only 12 hits.

Under "Options", "Redirect Logs" and "404 Logs" is set to "Forever."

Any idea why the two numbers are off? It's like this for pretty much all of our URLs.

Really love this plugin compared to some others out there so I'm hoping we aren't doing something wrong!

**82 hits**
![Screen Shot 2020-01-15 at 14 50 47](https://user-images.githubusercontent.com/503/72466532-11727000-37a7-11ea-8542-162cf14ef925.png)

**12 hits**
![Screen Shot 2020-01-15 at 14 50 35](https://user-images.githubusercontent.com/503/72466542-19caab00-37a7-11ea-8a20-04da4b207119.png)

**Comment by johngodley** [comment]
I couldn't say why, in your instance, the numbers are off. When a redirect occurs the hit counter is incremented, and a log entry is recorded. If you have deleted logs (either manually or automatically) at any point then the numbers could differ.

**Comment by rob** [comment]
Looking at everything more, the logs section only goes back to December 23, but we've definitely been running the plugin since before then. I could have deleted the logs at one point which could explain it.

At any rate, I don't think there's an issue with the plugin looking at it more - apologies! I'll close this ticket.
