### ISSUE TITLE
wp-staging issue

### ISSUE THREAD

**Issue by aurifil-auribuzz** [johngodley/redirection#2147]
### Summary

I installed the redirection plugin to my company's blog this morning to work through a needed redirection and it shifted our subdomain from auribuzz.wordpress.com to auribuzz.wpstaging.com. I've not been able to find anything about this shift online. I immediately deactivated and deleted the plugin, but the wpstaging remains. I would REALLY like to get this back to wordpress.com. We are working toward a custom site name, but for the last 10 years, the URL has been auribuzz.wordpress.com and I truly don't want to confuse anyone with this change. Hope you might be able to offer some assistance as I've not found any helpful answers (for a non-coder). Thank you!

**Comment by johngodley** [comment]
The plugin does not have the ability to change your domain. I do not know what wpstaging.com is, and I don't think it was connected to activating Redirection.

If you have deactivated the plugin then it is no longer running or having any effect on your site.

**Comment by aurifil-auribuzz** [comment]
Hi John -- 

When I activated the plugin, it switched my site to auribuzz.wpcomstaging.com (I was off when I wrote it earlier). I've never seen something like that before and it was directly related to the plugin installation. I understand that it likely wasn't connected with the actual plugin since it still exists after deleting, but the installation process is what triggered the shift. You've never seen something like this before? Because now I'm stuck and seemingly have no way of changing it back...

**Comment by johngodley** [comment]
The installation process does not have any way of changing your domain, and there is no code within the plugin to do that.

You had the plugin active for 9 seconds and you initiated a change of primary domain before activating the plugin. The change of domain name is unconnected to activating the plugin.

You will need to change your primary domain back to the one you want.

**Comment by johngodley** [comment]
Your domain is hosted on wordpress.com and the only way that the domain can be changed is from wordpress.com, not from a plugin.

**Comment by aurifil-auribuzz** [comment]
Thanks John -- I'm not quite sure what happened then. I did not change anything other than installing the plugin. I do not determine the wordpress.com -- we don't yet have a custom site, so it is the supplied by Wordpress. Thanks anyway.
