### ISSUE TITLE
Prevent hit from being logged for blacklisted IP?

### ISSUE THREAD

**Issue by rob** [johngodley/redirection#2149]
One of our redirects was being pinged ~200 times from Mailchimp's servers as part of their anti-spam / fraud checks (completely normal) but we didn't want those showing up in the 'Log' section. So I wrote a quick function to check the IP versus a subnet and if it matches, ignore the log:

```php
function ip_in_range() {...}

add_filter( 'redirection_log_data', function( $data ) {

	$blacklist = array(
		'0.0.0.0/20', // Mailchimp
	);

	foreach( $blacklist as $ip_range ) {
		if ( ip_in_range( $data[ 'ip' ], $ip_range ) ) {
			return false;
		}
	}

	return $data;

} );
```

This works great, and nothing shows up under 'Log' for Mailchimp hits... but the total 'Hits' count under 'Redirects' is still being updated. How can I prevent a 'hit' from being registered as well?

I do know there's the `redirection_redirect_counter` filter, but this is called before the `redirection_log_data` filter above, and is only a boolean true/false and doesn't include $data like IP, etc.

Only thing I can think of is adding a filter for `redirection_redirect_counter` and then checking $_SERVER manually as the IP isn't actually passed.

Thanks for any suggestions.

**Comment by johngodley** [comment]
Yep, you'll have to check the IP data yourself. The function `Redirection_Request::get_ip()` is used by Redirection.

**Comment by rob** [comment]
@johngodley Thanks - worked perfectly.
