### ISSUE TITLE
Feature Request - Ability to Delete all 404s

### ISSUE THREAD

**Issue by rodneyjoyce** [johngodley/redirection#2150]
Hi John,

This module is a life-saver.

I did a huge site migration from DotNetNuke to Wordpress and as such have hundreds of 301 rules. I let the site run for a few days, then group by URL and make rules for the important pages (I have almost 100 000 unique pages). However, there are 3000 or so 404s and I can only delete 200 at a time max, so I go to settings, turn off logging of 404 and wait until they are deleted (or I run some SQL). 

It would be nice to have an "DElete All" option on the pages.

Thanks

**Comment by johngodley** [comment]
Are you filtering the data in anyway? There is a delete all button at the bottom of the 404 page when unfiltered.

**Comment by rodneyjoyce** [comment]
Yes, usually always in a filtered view so must not have noticed it - fantastic thanks.
