### ISSUE TITLE
Redirection domain to domain error

### ISSUE THREAD

**Issue by pierreantoinegay** [johngodley/redirection#2151]
Hi,

I have change the domain of a website from https://merci-victor.fr to https://www.lesautonomieplanners.com.
Configuration of my hotsting and wordpress went well, and now the old home page URL is redirecting to my new homepage domain.

Now I'm struggling redirecting subfolders to the new domain.

Here is the only redirection rule I added from the Redirection plugin :
[https://ibb.co/cLRpJwy](url)

Something also very strange : https://merci-victor.fr/nos-valeurs seams redirected, but not other similar URL like https://merci-victor.fr/mieux-nous-connaitre/
 

Thanks for your help !

**Comment by johngodley** [comment]
That redirect won't work at all. You seem to be trying to match the domain name, but without providing the full URL. If you want to match a domain you need to put `https://` on it otherwise it is trying to match `/merci-victor.fr/something`

https://merci-victor.fr/nos-valeurs/ is not redirected

**Comment by pierreantoinegay** [comment]
Hi @johngodley , thanks for your answer. 
I have now put the complete URL to redirect : https://merci-victor.fr/(.*) 
After saving, the plugin automatically change the configuration to URL+Server, and change the minimize the redirected URL to /(.*)
And it seems to work fine now :)

Screenshot here of the final conf https://ibb.co/sFkkrBv
