### ISSUE TITLE
Group position interferes with Priority

### ISSUE THREAD

**Issue by joetek** [johngodley/redirection#2153]
Hi John, 

Thanks for a great plugin!  I've been chasing down an issue on my site and noticed an issue.

I have several redirects that look like this:
```
#1 - ^(?i)/parks/booking(/.*)?$   position: 400
#2 - ^(?i)/parks/permits(/.*)?$   position: 760
#3 - ^(?i)/parks(/.*)?$           position: 772
```

.. and I was troubleshooting why #1 redirects to the url for #3.  Digging around, I see that in `models/redirect.php`, line 91, the SQL query does an:

```
ORDER BY {$wpdb->prefix}redirection_groups.position,{$wpdb->prefix}redirection_items.position",
```

It turns out that redirect #1 was in a different Group with a higher position value.  The position value for the Groups seem to be incremental based on when the Group was added, and not editable within the UI.  This seems arbitrary, and it means that any redirect in any Group added recently will have a lower priority that those in older Groups.

I see a few possible fixes: 
1- Remove `redirection_groups.position` from the ORDER BY, and simply go by the `redirection_items.position`, or 
2 - Add an option in the UI to view/modify the Group position
3 - Add a filter on the query, so we can remove that clause

Personally, I'd go with Option 1, but I don't know if there was originally a reason for sorting by Group.

**Comment by johngodley** [comment]
It is a consequence of groups in the past having had an editable priority. Changing the query and potentially affecting how redirects work on a million sites is not a trivial decision.

At some point this will be changed as part of a larger update, but until then I think if you have redirects complicated enough to be affected that you put them into the same group.

Also noting that you don't need `(?i)` and can mark a redirect as case insensitive.

**Comment by johngodley** [comment]
Noting that the above ORDER BY is only used in the admin UI, and is not used on the front end.

**Comment by johngodley** [comment]
Noting that the above query is only used in older versions of the plugin. Any version 4.0 or greater will not use that query. As such I'm closing this issue as not applicable.
