### ISSUE TITLE
Posting link to WordPress site from Facebook shows a 301 Moved Permanently error instead of an image of the website

### ISSUE THREAD

**Issue by pfarikrispy** [johngodley/redirection#2154]
### Summary
I'm either adding a post to Facebook manually with text and an URL to the website that uses the redirect plugin (force http to https enabled), or using the cross-post feature from WordPress that auto-posts any post from WordPress to a Facebook page.

Facebook used to show a featured image and a small excerpt from the website below the article on facebook. Now it shows a 301 moved permanently error and I can't figure where the redirect is coming from. 

### Actual Behavior

I'm posting a summary of a blog post from WordPress to my Facebook page and include a deep link to the blog post.
Facebook used to fetch a preview of that link and include it as an image below the post.
Now it only shows an 301 Moved Permanently error and I can't figure which rule is causing the redirect that doesn't allow facebook to create the preview.

I don't think it's a rule I added because it happens for any link to the site that's using the redirect plugin. I don't think it's related to Facebook passing ?fbclid= tracking parameters but it could be

### Steps to reproduce

activate redirection plugin on wordpress site
include the default suggested redirects for internal permalink pages
Goto a facebook page or profile
add a new post with a little text 
paste a deep link URL to your site and hit enter
Facebook shows "fetching..."
followed by a 301 error 

### Environment

wordpress.com latest
plugin latest
chrome OSX latest
redirect option http -> https is active (but same thing happens with http/https deep links)
![301-error-facebook](https://user-images.githubusercontent.com/12430683/73093144-37ea8680-3ede-11ea-9f5d-10a86aa37b3b.png)

**Comment by johngodley** [comment]
Enter the URL in https://redirect.li/http/ and see if it says Redirection anywhere in the results. If it does then you have a rule for it, otherwise it is not from Redirection.

**Comment by johngodley** [comment]
Ok, and what was the result of following my above instructions?

**Comment by pfarikrispy** [comment]
I just checked your suggestion...
![redirection-test-wordpress](https://user-images.githubusercontent.com/12430683/73136488-6be4b980-404e-11ea-8183-10ea749ffd3f.png)

**Comment by johngodley** [comment]
No, can you enter the URL into redirect.li, not enter redirect.li into Facebook.

**Comment by johngodley** [comment]
The plugin does not cause problems with Facebook. If you have created redirects that cause problems with Facebook then we may be able to determine that.

**Comment by pfarikrispy** [comment]
Ah I see, I was wondering what was wrong with me deduction but couldn't figure iot out :) Sorry, thank you. Trying again...

**Comment by pfarikrispy** [comment]
No mention of "redirection" anywhere I can see
`

URL | https://byami.nl/2020/01/22/valentines-day-arrangement/
-- | --
200 - Ok
nginxA name for the servervendornginx | nginx
nginx
Sun, 26 Jan 2020 14:38:59 GMTThe date and time that the message was sent - more info
text/html; charset=UTF-8The MIME type of this contenttypetext/htmltypeDescriptionHTML filecharsetUTF-8 | text/html | HTML file | UTF-8
text/html
HTML file
UTF-8
chunked
closeControl options for the current connection and list of hop-by-hop response fields.
max-age=86400A HSTS Policy informing the HTTP client how long to cache the HTTPS only policy and whether this applies to subdomains.maxAge86400includeSubdomains preload | 86400 |   |  
86400
 
 
Accept-Encoding, CookieIndicates that different content may be provided to different clients, depending on the vary header.Accept-EncodingCookie | Accept-Encoding | Cookie
Accept-Encoding
Cookie
https://byami.nl/xmlrpc.php
<https://byami.nl/wp-json/>; rel="https://api.w.org/", <https://wp.me/pa86jO-1Gv>; rel=shortlinkUsed to express a typed relationship with another resource - more info"https://api.w.org/"https://byami.nl/wp-json/shortlinkhttps://wp.me/pa86jO-1Gv | https://byami.nl/wp-json/ | https://wp.me/pa86jO-1Gv
https://byami.nl/wp-json/
https://wp.me/pa86jO-1Gv
3.ewr _atomic_dca

`

**Comment by pfarikrispy** [comment]
Posting from Facebook still gives a 301, to verify the unexpected behavior

**Comment by johngodley** [comment]
Ok. That URL isn't redirecting though?

> include the default suggested redirects for internal pages

What suggested redirects? Include them where?

> Posting from Facebook still gives a 301, to verify the unexpected behavior

What do you mean by this? Where is Facebook redirecting to?

**Comment by pfarikrispy** [comment]
> include the default suggested redirects for internal pages
I mean the default permalinks that wordpress maintains were imported into the the plugin. They're in the form of /path/NNN/ or /NNN/ (N=1..9) for when you rename internal pages.

So the deep link to a blog post on the byami.nl website is not redirecting when I use your test.
However, when I paste that link on a FB page post and FB fetches the link for a preview, the result of that fetch is a 301 error.

Does it makes more sense now?

**Comment by johngodley** [comment]
Not especially.

What I'm trying to find out is:

- What is the URL that Facebook says is being redirected?
- What URL does Facebook say it is redirected to?

At the moment the URL you have provided is not redirecting, and does not appear to be affected by Redirection. If you have created (or imported) a redirect that is causing problems with Facebook then you will need to remove that redirect. The plugin will not affect Facebook on its own.

**Comment by pfarikrispy** [comment]
ok.

If I post the URL https://byami.nl/2020/01/22/valentines-day-arrangement/ on facebook to make a post on either a profile or page, Facebook fetches a preview and that generates the plain 301 moved permanently error since I've activated the redirect plugin.
![redirect-301-facebook1](https://user-images.githubusercontent.com/12430683/73140517-f42c8400-4079-11ea-8802-377944b13f2c.png)

* If I click on the URL, Facebook takes me to the original URL but postfixed with a facebook tracker parameter: https://byami.nl/2020/01/22/valentines-day-arrangement/?fbclid=IwAR0vl7gsv7lQ4J__ig4ITEaXMbwDpXNe0EYHKrpkZgf73ZkJnBk-lN7JywE
* If I click on the 301 moved preview, I'm taken to the same postfixed URL.

Default URL settings are now: ignore trailing slashes
Default query matching is now: ignore all query parameters
All rules are also now disabled and I'm waiting to invalidate cache (which was set to one hour).
redirect HTTP to HTTPS is still active in settings of redirect is still active.

Any way to flush cache?

**Comment by johngodley** [comment]
Sorry, but I don't think Redirection is doing anything here, and I don't see any evidence that it is causing a problem. If you have disabled everything then it is not possible for any redirect to be taking place. You should disable the HTTP to HTTPS option unless you need that enabled.

You keep posting the 301 moved screenshot but I don't know what that is or where the redirect is going to.

Your browser cache does not affect Facebook.

Do you have a URL that I can access that is redirecting when it shouldn't be?

**Comment by pfarikrispy** [comment]
Yes I agree with you it is hard to pin in it on the redirect plugin, but... If I disable the plugin, everything works as expected. I paste a deep link on Facebook, Facebook postfixes a tracking parameter and I see a preview of the mentioned URL in the post.
![redirect-301-facebook2](https://user-images.githubusercontent.com/12430683/73141453-6f933300-4084-11ea-9263-d3601bce731f.png)

It may be the HTTP/HTTPS rule but I've tried to include the same link with both HTTP and HTTPS and they both yield the unexpected 301 error.

**Comment by pfarikrispy** [comment]
The problem may be that it's only for traffic coming from Facebook but I don't know why or how a rule would affect only that traffic. It just makes no sense. However, disable the plugin and the 301 error goes away. So something somehow must get triggered... :(

**Comment by johngodley** [comment]
I think that the plugin being enabled or disabled is coincidental. If you have no rules, and do not have the HTTP to HTTPS option enabled then the plugin has no effect.

If I could see the redirect occurring then it would be easier to track down.

Are you using any caching plugin? It is more likely that is having an effect that may be changed when you enable/disable Redirection.

**Comment by johngodley** [comment]
Is it possible that Facebook has cached the URL? I do not use Facebook and do not know how it works.

Without any rules in Redirection there is absolutely no way it is doing anything.

**Comment by pfarikrispy** [comment]
> I think that the plugin being enabled or disabled is coincidental. If you have no rules, and do not have the HTTP to HTTPS option enabled then the plugin has no effect.
> If I could see the redirect occurring then it would be easier to track down.
agreed, I fail to understand why the fetch from facebook would cause a redirect when all rules are off, makes no sense
> 
> Are you using any caching plugin? It is more likely that is having an effect that may be changed when you enable/disable Redirection.
No, no caching plugin active

It is possible Facebook has cached the url, not sure, no way of knowing I think

**Comment by johngodley** [comment]
I'm sure there's a way of knowing, and I'm sure this is not the first time this problem has ever happened. This is not happening for anyone else so seems specific to your site.

You could try adding a query parameter to the URL. For example, https://byami.nl/2020/01/22/valentines-day-arrangement/?v=1

This could force it re-request the URL properly rather than using a cached version.

https://stackoverflow.com/questions/9026448/how-can-i-force-facebook-to-purge-its-cache-and-use-newer-meta-description-of-a

**Comment by pfarikrispy** [comment]
When I test both the original deep link URL on redirect.li as well as the deep link URL with the parameter fbclid postfixed, then both URL do not show any signs of being redirected. However, Facebook somehow manages to "detect" or "cause" a redirect. If plugin is disabled, it goes as expected

OK I'm ready to give up. I cannot cause a redirect to happen any other way then to use the Facebook fetch preview... :(

**Comment by pfarikrispy** [comment]
> https://byami.nl/2020/01/22/valentines-day-arrangement/?v=1

yes that gives a proper preview! :D So you were right, Facebook was caching requests;.
If I know paste the original link https://byami.nl/2020/01/22/valentines-day-arrangement, Facebook also shows the preview so perhaps it has updated the cache :) Haha
