### ISSUE TITLE
Problem starting Redirection 4.6.2

### ISSUE THREAD

**Issue by mtomczak123** [johngodley/redirection#2156]
Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.3.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0
JavaScript: https://mywspieramy.org/wp-content/plugins/redirection/redirection.js
REST API: https://mywspieramy.org/wp-json/

**Comment by johngodley** [comment]
Please open your browser's developer console and see if any other information is shown. This is likely caused by another plugin.

**Comment by mtomczak123** [comment]
Failed to load resource: the server responded with a status of 599 ()

load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils&ver=5.3.2:8 JQMIGRATE: Migrate is installed, version 1.4.1

redirection.js:1 Failed to load resource: the server responded with a status of 599 ()

 

Od: John <notifications@github.com>
Odpowiedź do: johngodley/redirection <reply@reply.github.com>
Data: poniedziałek, 27 stycznia 2020 07:52
Do: johngodley/redirection <redirection@noreply.github.com>
DW: mtomczak123 <tomczak-mariusz@wp.pl>, Author <author@noreply.github.com>
Temat: Re: [johngodley/redirection] Problem starting Redirection 4.6.2 (#2156)

 

Please open your browser's developer console and see if any other information is shown. This is likely caused by another plugin.

**Comment by johngodley** [comment]
Ok, does that help you find the problem? Why is your server responding with a 599 error? Have you tried disabling other plugins?

**Comment by johngodley** [comment]
FYI, HTTP 599:

> 599 Network connect timeout error (Unknown)
> This status code is not specified in any RFCs, but is used by Microsoft HTTP proxies to signal a network connect timeout behind the proxy to a client in front of the proxy.

**Comment by mtomczak123** [comment]
Problem solved by the hosting company

thx.

 

 

Od: John <notifications@github.com>
Odpowiedź do: johngodley/redirection <reply@reply.github.com>
Data: poniedziałek, 27 stycznia 2020 08:46
Do: johngodley/redirection <redirection@noreply.github.com>
DW: mtomczak123 <tomczak-mariusz@wp.pl>, Author <author@noreply.github.com>
Temat: Re: [johngodley/redirection] Problem starting Redirection 4.6.2 (#2156)

 

Ok, does that help you find the problem? Why is your server responding with a 599 error? Have you tried disabling other plugins?
