### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by organicnz** [johngodley/redirection#2157]
```
Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.2.24-0ubuntu0.18.04.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0
JavaScript: https://foodshare.club/wp-content/plugins/redirection/redirection.js
REST API: https:/foodshare.club/index.php?rest_route=/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 404 Not Found
Raw: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

```

**Comment by johngodley** [comment]
Your REST API URL is invalid and is missing a `/` - have you entered URLs wrong in your WordPress Settings?

**Comment by organicnz** [comment]
Thanks for the quick response. I've got an issue with duplicated the root url like so: https://foodshare.club/foodshare.club/

It looks fine isn't it?
# Define URLs edit wp-config.php 
define('WP_HOME','https:/foodshare.club');
define('WP_SITEURL','https://foodshare.club');

**Comment by johngodley** [comment]
No, the `WP_HOME` value is not a valid URL . Compare the two URLs:

`https:/foodshare.club`
`https://foodshare.club`

The top one is missing a `/`

**Comment by organicnz** [comment]
Thanks for the quick response mate. My deep apologies and sorry that deleted the first reply. It's my bad I didn't notice it at first look and run quickly to make a reply than realised how clueless I'm lol. Anyway, it's worked out just fine :)
