### ISSUE TITLE
Issue when activating the plugin

### ISSUE THREAD

**Issue by anssilaitila** [johngodley/redirection#2158]
After installing the plugin, Start setup -> Continue setup -> this happens (every time, multiple sites):

Something went wrong 🙁

Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

If that doesn't help, open your browser's error console and create a new issue with the details.

Please mention redirect, and explain what you were doing at the time

Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.3.4-2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0
JavaScript: https://www.EXAMPLE.COM/wp-content/plugins/redirection/redirection.js
REST API: https://www.EXAMPLE.COM/wp-json/
Buster: 4.6.2 === 4.6.2

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bstatus%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    in p
    in ai
    in div
    in div
    in mi
    in div
    in bi
    in div
    in t
    in p
    in div
    in div
    in t
    in p
    in t
    in p
    in M
    in py

**Comment by johngodley** [comment]
Have you opened your browser's developer console and looked for other information? This error is very likely caused by another plugin.

**Comment by anssilaitila** [comment]
To be more precise, this happens when the plugin is testing REST API, it crashes at 83 %.

![Screenshot 2020-01-28 at 11 23 54](https://user-images.githubusercontent.com/29924442/73251072-e6354b00-41c0-11ea-8bb4-330085c48cd8.png)

**Comment by johngodley** [comment]
Ok, so your server is returning a 500 error when accessing the REST API , and it appears to be blocked in general. You will need to allow REST API requests.

**Comment by anssilaitila** [comment]
Oh yes, that was the reason. Thank you.
