### ISSUE TITLE
Redirections with regex doesn't work as expected

### ISSUE THREAD

**Issue by loicparent** [johngodley/redirection#2162]
_Hello,_

I encounter a problem with some redirections using regex.
In fact, when I add a redirection without regex, the redirection works correctly but, when I use regex, the redirection works but, the "after" url data are added.

**Example**: 
url : https://mywebsite.com/fr/category/cat1
source_url : ^/fr/category/*
target_url : https://mywebsite.com/fr/categories/
redirected_url : https://mywebsite.com/fr/categories/cat1

So in this example, the string cat1 stay after the redirection.

Do you have an idea of what I have to do to fix this ?
_Thanks for your help and have a nice day_ :)

**Additionnal information**:
WP Version : 5.3.2.
Redirection Plugin Version : 4.6.2
Browser : Chrome (latest version with private navigation so without browser cache)
Server type : Nginx

**Comment by johngodley** [comment]
`^/fr/category/*` is not a regular expression. It would need to be `^/fr/category/.*`

**Comment by loicparent** [comment]
Oh thanks for you quick reply !
(I just came to change the status of my comment after noticing ^^).
