### ISSUE TITLE
Insane Amount of 404 to pages that are Backend 

### ISSUE THREAD

**Issue by rgarrod** [johngodley/redirection#2166]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

Howdy - We recently build a new website and we're seeing an INSANE amount of 404 errors being logged every day. 99% of them go to .php, .js, .css or other backend files that no user should be able to get to regardless. Is this normal? I can't imagine it is normal. Many of the files, like .png files. are no longer being used and have since been removed from our database. Is there anyway to redirect file extensions? 

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

Not spend a ton of time constantly clearing out the 404 log and adding redirects. Currently have over 600 redirects.....

Explain what actually happened. If suggesting a new feature then explain what currently happens.

See screenshot. 

Please list your browser, browser version, version of WordPress and Redirection plugin.
Browser: Chrome
Version: Version 79.0.3945.130 (Official Build) (64-bit)
Wordpress: 5.3.2
Redirection: 4.6.2 
![Annotation 2020-02-04 093357](https://user-images.githubusercontent.com/60659095/73754344-46cd0680-4732-11ea-8db6-af24beb8cdbd.png)

**Comment by johngodley** [comment]
https://redirection.me/support/faq/#weird

You can use the 'group by' dropdown to help. Remember that bots will make requests on any site. 640 items in a 404 log is quite small. You don't have to fix everything

**Comment by rgarrod** [comment]
Oh, OK. Thanks for the quick response! I went into panic mode because I had no idea what was going on. As a general rule, is there any redirects I should prioritize, other than the obvious live pages a user sees?

**Comment by johngodley** [comment]
Whatever is important to your site, I couldn't say what that is. Use the group by to focus on the URLs causing the most 404s

**Comment by rgarrod** [comment]
Sounds good. OK I will see what I can do. Thanks John.
