### ISSUE TITLE
Maybe I am misunderstanding how redirection with Regex Works?

### ISSUE THREAD

**Issue by pdeitel** [johngodley/redirection#2167]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary
I have a regex of the form

`^/resourcecenters/.*`

If i understand correctly, that should take any request to https://mydomain.com/resourcenters/... and redirect it to my target page.

### Actual Behavior
I am still seeing 404 notifications in the plugin's 404s tab for URLs that begin with https://mydomain.com/resourcenters/.

### Environment
Wordpress 5.3.2, Redirection 4.6.2.

**Comment by johngodley** [comment]
Can you post a screenshot of your redirect settings? Also, can you give an example of a URL that is not matching this?

**Comment by pdeitel** [comment]
![Screen Shot 2020-02-05 at 11 40 06 AM](https://user-images.githubusercontent.com/4549557/73862250-4f920b00-480c-11ea-830a-a8368f20cce7.png)

As for an example of a URL, this one just appeared in my 404s log:
/resourcecenters/web20/recommendersystems/recommendersystemstools/tabid/1322/default.aspx

**Comment by johngodley** [comment]
Sorry, not the general settings, but the settings for the redirect itself.

**Comment by pdeitel** [comment]
oh, sorry :-)

![Screen Shot 2020-02-05 at 11 44 36 AM](https://user-images.githubusercontent.com/4549557/73862684-eb237b80-480c-11ea-81b3-ed00a664c103.png)

Also, is there a way to clear the entire 404s list?

**Comment by johngodley** [comment]
Are the 404s all .aspx files, or some other specific kind of URL?

> is there a way to clear the entire 404s list

There is a 'delete all' button at the bottom of the page.

**Comment by pdeitel** [comment]
Some are a Sox, others are html

________________________________

**Comment by johngodley** [comment]
Can you provide a full URL to one of these files so I can test it? Also can you include a screenshot of the 404 entry?

**Comment by pdeitel** [comment]
Hi John, I provided those up above. One example of a URL was /resourcecenters/web20/recommendersystems/recommendersystemstools/tabid/1322/default.aspx

The screen capture of the redirect is in my response from 3 days ago above.

**Comment by johngodley** [comment]
I'm looking for a full URL - one I can access. That is only the path.

The screenshot shows your redirect settings. I'd like to see the log entry in 404 page.

**Comment by pdeitel** [comment]
The full URL would be http://deitel.com/resourcecenters/web20/recommendersystems/recommendersystemstools/tabid/1322/default.aspx 

The 404 log pages shows only the paths, and as I create each redirect I delete the entries. When I try this URL, it tells me too many redirects.

**Comment by pdeitel** [comment]
Nevermind. It appears to have been a caching issue. I apologize for wasting your time.
