### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jehanf** [johngodley/redirection#2168]
```
Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.4.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0
JavaScript: https://dooweet.org/wp-content/plugins/redirection/redirection.js
REST API: https://dooweet.org/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/group/ GET
Code: 400 Bad Request
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

```

**Comment by johngodley** [comment]
Are you using a security plugin of some kind?

**Comment by jehanf** [comment]
There is SecuPress installed, also WP Rocket, but deactivating both does not solve the problem sadly.

**Comment by johngodley** [comment]
The above error is almost always caused by something blocking your REST API so it very likely to be one of those plugins. You may need to clear any caches your site or browser might have as the response could be cached.

**Comment by jehanf** [comment]
I can confirm it is not the plugins, this bug started when we've moved the site to another server (two years on the previous server, never had this problem), and I really don't have a clue why, since the environment is the same (or at least almost, since something seems to be blocking the Rest API now).

**Comment by jehanf** [comment]
Ok, it was a server issue.

Did some research in the log, and found there was some mod_security lines, with this particular error:
`ModSecurity: JSON parser error: parse error: premature EOF`

With the help [of this post](https://github.com/SpiderLabs/ModSecurity/issues/2052) to understand the "why", I just added these lines to disable a Apache2 mod_security rule : 
```
<ifmodule mod_security2.>  
    SecRuleRemoveById 200002  
</ifmodule>
```

Hope it helps someone someday.
