### ISSUE TITLE
Changing a target URL for same source URL not going to new target

### ISSUE THREAD

**Issue by BunnyMuffins** [johngodley/redirection#2170]
### Summary

Hi I am trying to have a URL that is easily remembered by visitors, such as mysite.com/newfood and have that forward to my latest post in a category and not just most recent post.  I am currently trying to achieve this through changing the redirection of mysite.com/newfood every time I post, but many links such as from facebook or youtube are redirecting to the old post every time I update.  

If you have a better method on achieving this requirement (whether through Redirection or something else), I would really appreciate it!  Clearing browser cache would solve this, but I can't expect visitors to clear their cache every time I make a new post.

Currently using "Ignore & Pass Parameters"

### Actual Behavior

URL not redirecting when changing the target URL on a periodic basis (weekly).  It 'sometimes' works such as if I type the URL directly into the browser, but even then it still makes mistakes and goes to the old site.  However, the links from youtube/facebook never work and always go to an older post.  

### Steps to reproduce

1. have a redirect already existing
2. change target URL of the redirect
3. Old target URL still being redirected to

### Environment

This happened to me in Chrome Wordpress 5.3.2 and Redirection 4.6.2

**Comment by johngodley** [comment]
Answered in email. Please only post to one place.
