### ISSUE TITLE
Target URL is appending non-captured regex results.

### ISSUE THREAD

**Issue by 541joehill** [johngodley/redirection#2173]
###Summary
Goal: extract first two words from end of URL. 
Example: /product/grasspave2/westminster-green-knoxville-tennessee/

I want to capture: "westminster-green".
I am doing so successfully with this regex: ^/product/.*?/(.*?-.*?)-

My Target URL is: /project/$1/
in this example the target URL should be: /project/westminster-green/

### Actual Behavior
What my target URL actually ends up being is: /project/westminster-green/knoxville-tennessee.

After some testing it appears as the non-captured data from the original URL are being appended to my target URL.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Chrome v79, Wordpress 5.2.4, Redirection v4.6.2

**Comment by johngodley** [comment]
The source must match the whole URL, not part of it.

**Comment by 541joehill** [comment]
Sorry, I'm not sure I understand your explanation.

I had success capturing the group I wanted from the original URL - placed into: /project/$1/. So I am able to capture part of the URL and place it into my target URL. Then everything I didn't capture is _appended_ after the last slash.  Seems like very strange behavior to me.

**Comment by johngodley** [comment]
Your expression matches everything up to the bit you capture. However, the URL continues after this and you must still match the rest. If you don't then when the replacement happens you will find that the unmatched data is appended. This is how regular expressions work.

**Comment by 541joehill** [comment]
Thank you very much! Solved my issue by capturing the rest of the URL and just disregarding it.
Always learning new things about regex.
