### ISSUE TITLE
Redirect type in CSV import not adhered to

### ISSUE THREAD

**Issue by tcbarrett** [johngodley/redirection#2174]
### Summary

Upload redirects using a CSV file, the 302 type is not adhered to - always shows as 301.

### Actual Behaviour

The redirects are marked as 302 in the CSV, but show as 301 once imported.

### Steps to reproduce

Import a CSV with a 302 redirect. Sample file included.

[redirection-type-issue-csv.txt](https://github.com/johngodley/redirection/files/4192187/redirection-type-issue-csv.txt)

### Environment

WordPress 5.3.2 - plugin 4.4.2

**Comment by johngodley** [comment]
As per the documentation on the import page the format is:

`source, target, regex, http code`

Your file format is:

`source, target, regex, redirect type, http code`

**Comment by tcbarrett** [comment]
Thanks. I was using an exported file and reproducing that.
