### ISSUE TITLE
Install Redirection plugin gives error in options page

### ISSUE THREAD

**Issue by madeITBelgium** [johngodley/redirection#2179]
# Summary

After installing the Redirection plugin the 'option' page is not working.

![image](https://user-images.githubusercontent.com/20304892/74528255-194d3d80-4f28-11ea-8ad9-04da473b90b2.png)

Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.2.26
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
JavaScript: https://justimagine-events.be/wp-content/plugins/redirection/redirection.js
REST API: https://justimagine-events.be/wp-json/
Buster: 4.6.2 === 4.6.2

TypeError: Cannot read property 'toLowerCase' of null

    in t
    in p
    in div
    in t
    in p
    in div
    in StrictMode
    in t
    in p
    in M
    in py

![image](https://user-images.githubusercontent.com/20304892/74528286-3124c180-4f28-11ea-959e-e63419147f6b.png)

**Comment by johngodley** [comment]
Does this only happen on the options page? What kind of post types do you have on your site?

**Comment by madeITBelgium** [comment]
Yes only on the options page.  I added 2 custom post types, when I disable them the page is working. So probably I did something wrong. Will check it further.

**Comment by johngodley** [comment]
This is fixed in 63289a55dd78cbb7ab4a84f07bcaff5cdd44e81f and will be included in the next version.
