### ISSUE TITLE
Receive IIS Error: HTTP Error 404.0 - Not Found

### ISSUE THREAD

**Issue by mrito** [johngodley/redirection#218]
Hi,
After creating a Redirect to my invalid pages link I receive now an IIS error below:
Server Error in Application "mydomain.com"
Internet Information Services 7.5
Error Summary
HTTP Error 404.0 - Not Found
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

Regards,
Malvin
![error screenshot](https://user-images.githubusercontent.com/18394924/27323833-96d83a06-55d5-11e7-956d-163889f1c467.png)

**Comment by johngodley** [comment]
I don't have any experience with IIS, but this just looks like a 404 page? What is the redirect in Redirection you created, and what is the URL you used to get the above page?

**Comment by mrito** [comment]
Well, I've tried putting only the website address, e.g. www.mydomain.com
But still receive that error.

**Comment by johngodley** [comment]
Just to confirm you created a redirect and now when you access your home page it shows a 404?

What is the redirect? Do you have anything in your PHP error logs? If you remove the redirect does it work again?

**Comment by johngodley** [comment]
Closing until further information is received - please reopen then

**Comment by jtinsky** [comment]
I have the same issue. I've created several pages as blank placeholders and then created redirects for them and they all return a 404. The redirects are in a group that's using the WordPress module instead of Apache or Nginx (or anything else that's sane rather than IIS).

**Comment by johngodley** [comment]
Can you provide a URL that I can use to check? Also, can you show a screenshot of the redirect you created for that URL.

As mentioned above I don't have any experience with IIS and dont have access to it, so it's hard to say what the problem. If there is an error log then have a look in that. How do WP permalinks work?

**Comment by jtinsky** [comment]
I think we're just going to move the installation to a linux distribution off of IIS. In this case WordPress is being used for our intranet so access is behind a firewall and limited to staff.

Thanks for replying and have a great weekend.
