### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Aleandrus** [johngodley/redirection#2183]
```
Plugin: 4.6.2
WordPress: 5.3.2 (single)
PHP: 7.1.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
JavaScript: https://edicolablack.altervista.org/wp-content/plugins/redirection/redirection.js
REST API: https://edicolablack.altervista.org/wp-json/

Error: NetworkError when attempting to fetch resource.
```

**Comment by johngodley** [comment]
Can you try some of the other REST API options?

**Comment by Aleandrus** [comment]
Hi,
thank you for your reply.

I think I solved the problem, whilst tweaking around with the Redirection
plugin and some other plugins settings.

Kind regards
Aleandrus

Il giorno dom 23 feb 2020 alle ore 16:18 John <notifications@github.com> ha
scritto:
