### ISSUE TITLE
404s - Group by URL - "Delete all" not working

### ISSUE THREAD

**Issue by IsaiahBS** [johngodley/redirection#2188]
Although it is clickable, it does not delete the rows.

**Comment by pixelated-au** [comment]
Can confirm. Not working for me either. Neither is deleting groups by using the bulk action feature

**Comment by matt12321** [comment]
Same problem for me as well. Just started happening today.

**Comment by johngodley** [comment]
Understood. Please, no more reports are necessary

**Comment by johngodley** [comment]
Fixed by 53981b2b99ae9b77458e8be315604174d3d71171 and included in the next release.

**Comment by matt12321** [comment]
> Fixed by [53981b2](https://github.com/johngodley/redirection/commit/53981b2b99ae9b77458e8be315604174d3d71171) and included in the next release.

Hi there, do you know when the next release is dropping? I used to use this feature regularly to sort through pages and pages of URLs found by bots

**Comment by johngodley** [comment]
You can find a beta release here:

https://github.com/johngodley/redirection/releases/tag/4.7.1-beta-1

**Comment by matt12321** [comment]
Thank you so much,  I appreciate all of the efforts you are putting into this.
