### ISSUE TITLE
A LOT of redirects in my list that I did not add...

### ISSUE THREAD

**Issue by bdusablon** [johngodley/redirection#2191]
I had a user report an issue with redirection. I went to look at the redirects. I only have 2-3 on the site. When I logged in to look, there were 530+. I'm going through and deleting all the wrong ones now, but I did not add these. I also can't see when these redirects were added. I would like to see that as an option in the view.

How might this have happened?
<img width="1255" alt="Screenshot 2020-02-19 20 48 26" src="https://user-images.githubusercontent.com/5025428/74896213-59158a00-5359-11ea-896b-67538fc62d1b.png">

**Comment by johngodley** [comment]
Closing in favour of #573
