### ISSUE TITLE
Redirection Error - multisite

### ISSUE THREAD

**Issue by heximcz** [johngodley/redirection#2199]
```
Plugin: 4.7
WordPress: 5.3.2 (multi)
PHP: 7.3.15
Error: Failed to fetch
```

**Comment by johngodley** [comment]
Can you include the full details?

**Comment by heximcz** [comment]
Sorry. Problem fixed in URL address (http vs. https). But I have another issue. The plugin cannot be deactivated on the specific site in multisite network.

**Comment by johngodley** [comment]
Redirection has no control over your ability to activate or deactivate it. That is a WordPress issue, and you will need to do that in the appropriate place. On multisite this is typically on the network admin page.
