### ISSUE TITLE
Re-ordering rules not working in WP 4

### ISSUE THREAD

**Issue by mrklaw** [johngodley/redirection#22]
There appears to be no way to re-order redirection rules, though the documentation suggests that it is possible.  I'm using Wordpress 4.0 with redirection version 2.3.10

**Comment by earnjam** [comment]
It appears that he stripped that out when he converted them to using the WP core style tables. Not sure why exactly as that is pretty vital for regex redirects. 

Would love to see this get added back, as it's pretty limiting without it.

**Comment by galbaras** [comment]
+1

As per https://wordpress.org/support/topic/sorting-redirects?replies=8#post-7094719, there are several open threads on wordpress.org requesting that this feature be reinstated.

**Comment by orangepineapple** [comment]
+1

**Comment by Enchiridion** [comment]
+1

**Comment by twiginteractive** [comment]
+1000

I've been requesting this multiple times on the WP plugin support page. Maybe github will get the author's attention to this crucial element of a great plugin?

**Comment by jproffitt3ge** [comment]
+1

This is the only plugin that nails all of the other requirements of redirection (I've spent a solid 2 hours searching for something else that'd work and haven't even come close). I'm currently writing rules to map a site with one complex hierarchical  inventory system to a site with a different hierarchical inventory system, and there is just no way to get all the rules in the right order in one go.

I see that the rules have a non-unique "position" property that they get sorted by already. Would it be possible to simply add a field on front end called "Priority" that sets that position?

**Comment by twiginteractive** [comment]
I don't think the plugin author reads github or WP issues. He's released several new versions in the > 1 year I've been asking him to restore this critical feature (it used to be in the plugin) and he's never once commented. Without it, this plugin goes from a 10 to a 6.

I don't know what post type he uses for the redirect menu entries - I was hoping a simple jQ drag/drop could be hooked to a SQL update - that's all it would take. So sad.

**Comment by jproffitt3ge** [comment]
I looked at the plugin internals and it has a dedicated "position" field that it already orders rules by (currently the position gets set on creation, to the count of rules in that group). It then executes the redirects from highest position to lowest (I confirmed by playing with positions of the rules).

I submitted a pull-request adding the ability to set this position directly in the advanced settings for each rule, and ordering the rules in the admin table from highest position to lowest (or order of execution). It actually only took editing < 10 lines across 3 files. The author appears to have merged in community pull requests before, so perhaps they'll notice the issue now. You could probably help by also +1 there: https://github.com/johngodley/redirection/pull/111

**Comment by galbaras** [comment]
Asked him to look via https://twitter.com/all_noodles

**Comment by johngodley** [comment]
Sorry for the extreme delay in restoring this, and also in not replying. Position editing will make a comeback in #268 (landing in 2.7, after a 2.6.6 release)
