### ISSUE TITLE
Help with setup - "Not Using Redirection" Found: 500?

### ISSUE THREAD

**Issue by cy80rg101** [johngodley/redirection#2204]
### Summary
 Wanting to use Redirections on our WP site as a central repository for all our redirects. 
Wanting to redirect from external URL, to a url on a subdomain of our WP domain, BUT not actually part of the WP site. 

For example: 

https://abcd.com/

redirect to 

https://apply.thecheesecompany.co.uk/new/ref=1234?utm_source=abcd&utm_medium=Paper&utm_campaign=abcd

Our WP instance is installed on the root domain, at thecheesecompany.co.uk in this example. 

The "apply.*" subdomain is NOT a WP site. 
We own all the external subdomains we wish to redirect, by default directed at the DNS level to https://apply.thecheesecompany.co.uk . 

### Actual Behavior

"Check Redirect" function shows this failed,  

Found: 500
Agent: Not using Redirection

###Questions

1. Should I be able to use Redirect like this, or is it simply not mean to work in this way?
2. If so, how can I fix this issue?

**Comment by johngodley** [comment]
How have you configured the redirect?

A redirect can only happen if the request passes through Redirection. You can redirect another domain provided you use a 'URL and server' match, and have requests for that domain pass through the site where Redirection is installed.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
