### ISSUE TITLE
No option to delete 404 history manually

### ISSUE THREAD

**Issue by nabtron** [johngodley/redirection#2209]
There is no option to delete 404 errors history.

I tried option > delete option too, and then re-setup the plugin, but the old history was still there.

Please help / fix.

**Comment by johngodley** [comment]
404s > Delete
404s > Bulk Action > Delete

Options > Delete will remove all data. The old history will not remain.

**Comment by nabtron** [comment]
@johngodley it's not possible to delete all one page at a time when you have thousands of pages of entries. 
Please make a button to delete all at once (not on that page only)

**Comment by johngodley** [comment]
There is a button to delete all log entries at the bottom of the log page. What do you mean not on that page only?

**Comment by nabtron** [comment]
sorry, it does delete but shows the results due to caching.
can you please look into issue related to redis caching using w3 total cache on nginx?

**Comment by johngodley** [comment]
Redirection is not involved in caching, and has no control over your setup. You should configure your caching software to not cache any wp-admin or REST API pages.
