### ISSUE TITLE
Redirection WP Plugin - Caching

### ISSUE THREAD

**Issue by Bertakos** [johngodley/redirection#221]
Hi guys,
I have a weird issue with Redirection WP Plugin. The redirections I setup only work when I am connected to the WP Admin panel. When I am not connected then I am getting 404 pages.
It looks like this is a caching issue but I am not able to find a fix. 
For example 
http://blogg.careerbuilder.se/2016/03/31/5-tips-for-en-perfekt-elevator-pitch?siteid=int_seb2cutskick201610 is a 404 and should be redirected to 
http://blogg.careerbuilder.se/5-tips-for-en-perfekt-elevator-pitch?siteid=int_seb2cutskick201610

If you are connected to the WP Admin Panel then the above redirection works as expected.

thanks

**Comment by johngodley** [comment]
Can you try disabling other plugins? Do you have any kind of cache software running on your server? Are you using Cloudflare?

**Comment by johngodley** [comment]
Closing for now, please reopen if you have more info
