### ISSUE TITLE
Problem starting Redirection 4.5.1

### ISSUE THREAD

**Issue by bhimani7** [johngodley/redirection#2213]
Plugin: 4.5.1
WordPress: 5.3.2 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
JavaScript: https://taxstorestalbans.com.au/wp-content/plugins/redirection/redirection.js
REST API: https://taxstorestalbans.com.au/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. What information is shown in your developer console?

**Comment by bhimani7** [comment]
No it's now okay my WordPress version is new and the plugin is old so, my post edit is stopped working then I realize with wp_debug redirection is make an issue because a plugin is a too old version
