### ISSUE TITLE
Question. How to migrate from 3.7 to 4.7

### ISSUE THREAD

**Issue by Daisuke-sama** [johngodley/redirection#2214]
Hello, 
I have installed the 3.7 version, and I am going to upgrade. But I am afraid of errors since the database manipulation mechanism has been changed significantly. And I have 1000+ sites set in multisite install. I would be happy being reassured that everything will continue to work smoothly.

Thank you

**Comment by johngodley** [comment]
Having no knowledge of your setup it would be impossible for me to give any reassurances. The upgrade process has upgraded over a million sites. You are advised to make a backup.

**Comment by Daisuke-sama** [comment]
Thank you for the response. Of course, I do the backup. But having thousands of sites makes me dreaded checking each one for consistency...

**Comment by johngodley** [comment]
Sure. I think it unlikely that something will be inconsistent. The upgrade will generally either work or not work - it won't work, and then become inconsistent. However, it would be impossible for me to offer any kind of guarantee.

**Comment by Daisuke-sama** [comment]
Sure. Sure. I am avoiding to ask any guarantee - I understand it. I am just wondering about any kind of additional preparations, except backing up, or other approaches.
I also thought about creating a tool for WP-CLI that exports data and imports it after the update or even run the existing import/export via CSV.

**Comment by Daisuke-sama** [comment]
Does it run updates automatically for the whole multisite network, or will I need to update every site manually?

**Comment by johngodley** [comment]
There's no other preparations. The upgrade will notify you of any problems.

There are existing WP CLI commands here:

https://redirection.me/developer/wp-cli/

**Comment by Daisuke-sama** [comment]
Yes, I saw the implementation. Since I have a veeeery big database of the network I have to be more accurate. I decided to write the wrapper for your existing CLI tools, that will help me export, upgrade, and remediate if needed per single site.
If you are interested in I probably will have a chance to share the results.

**Comment by johngodley** [comment]
Ok, closing for now. Please reopen when you have more details
