### ISSUE TITLE
search parameter not remembered when clicking "search target url"

### ISSUE THREAD

**Issue by YesThatAllen** [johngodley/redirection#2217]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

I'm trying to fix a number of redirections in order of most accessed, but last_count sort isn't remembered

### Actual Behavior

the sort of `orderby=last_count` isn't remembered on searching

### Steps to reproduce

- I visit my redirection list at this url

`wp-admin/tools.php?page=redirection.php&filterby%5Btarget%5D=%241&orderby=last_count`

 - I make some edits

 - I click "Search Target URL" again

 - I expect the list to still be sorted by last_count, but there is no default sort

### Environment

- Chrome Version 80.0.3987.132 on mac
- Wordpress 5.3.2
- php 7.3.14-1+ubuntu16.04.1+deb.sury.org
 - redirection 4.7.1

**Comment by johngodley** [comment]
This will be added in the next version.

**Comment by johngodley** [comment]
You can try this in the 4.9 beta:

https://github.com/johngodley/redirection/releases/tag/4.9-beta

Let me know how it goes.

**Comment by YesThatAllen** [comment]
Just saw this note.. and thank you yes, this is working as desired 💪
