### ISSUE TITLE
Custom 404 Page in Redirection

### ISSUE THREAD

**Issue by Grubstomper** [johngodley/redirection#2219]
I recently updated my site to PHP 7.4, my custom 404 page was referenced in the .htaccess and now that .htaccess is discontinued I need to set up the custom 404 another way.

How do I set up the custom 404 page in Redirection?

Thanks

**Comment by johngodley** [comment]
What do you mean by a custom 404 page?

**Comment by Grubstomper** [comment]
What I mean by custom 404 page is a page that was created so that when a user gets a 404 page, it is formatted and designed to better reflect the company branding and site design.

**Comment by johngodley** [comment]
Ok, that's not something Redirection is involved with. You can modify the 404.php template in your WordPress theme so it matches your branding.
