### ISSUE TITLE
wp plugin install redirection --version=4.7.1 --activate --force

### ISSUE THREAD

**Issue by adamoverbeeke** [johngodley/redirection#2220]
I am unable to activate the redirection plugin using the CLI command:

wp plugin install redirection --version=4.7.1 --activate --force

I am forced to do this by hand with is not expected. I have automatic builds scripts that will create my Wordpress site using ansible. I am not looking to have any manual process; I would like to activate plugin programatically. 

Is this a restriction on this plugin?

**Comment by johngodley** [comment]
The plugin does not prevent this. In what way are you unable to activate it? Is there an error?

You will need to set the plugin up after activation:

https://redirection.me/developer/wp-cli/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
