### ISSUE TITLE
Backlink redirection not working

### ISSUE THREAD

**Issue by NEC-AnGeL** [johngodley/redirection#2221]
Hello Admin or Reader,

We have set a backlink redirect but it is not working. Does anyone see what we are doing wrong?

See the image with settings on https://drive.google.com/file/d/1s3Q48-PfDNgPS2pxKfPcVoFCQ0w1a-73/view?usp=sharing

We click on the link on open-txt.nl/linkpartners/ (anchor: houten horloge)

greetz

**Comment by johngodley** [comment]
Hello User or Person

You have created a 'URL and server' redirect. Is there a specific reason for this?

**Comment by NEC-AnGeL** [comment]
Hello John,

Wehe we do only URL the plugin set it onto 'URL and server'. What can we do so these wil not happen ?

**Comment by johngodley** [comment]
Don't enter a source URL that includes a domain for another site. You can put the path only.

**Comment by NEC-AnGeL** [comment]
Hello John,

You mean these https://drive.google.com/open?id=1sujdkJVldsozNaKyh0WsU17cbuCIpj4Z ? Then i get the message: (This will be converted to a server redirect for the domain .)

maybe you have a example.

**Comment by johngodley** [comment]
I can't view that. Can you post it directly here?

**Comment by NEC-AnGeL** [comment]
Ok see the image

![Knipsel1](https://user-images.githubusercontent.com/62393034/77615497-d4a5c080-6f2f-11ea-851a-8f055eac7ed0.PNG)

**Comment by johngodley** [comment]
Yep, as I said, don't put the domain in the source URL.

**Comment by NEC-AnGeL** [comment]
The problem then is that we have 1000+ of backlinks and not all of these we have to redirect. Only from a couple of urls.

![image](https://user-images.githubusercontent.com/62393034/77615989-ed62a600-6f30-11ea-921e-c16418da41b0.png)

**Comment by johngodley** [comment]
What are you trying to do? I really don't understand what you mean about backlinks or that you don't need to redirect all of them. Is that a list of redirects or your log? If they are redirects, it is not possible to redirect external domains unless you also host them.

**Comment by NEC-AnGeL** [comment]
On https://open-txt.nl/linkpartners/ there is a link to our website. Only these go to the homepage and not to the sub-page.

https://open-txt.nl/linkpartners/ is not our domain.

**Comment by NEC-AnGeL** [comment]
![image](https://user-images.githubusercontent.com/62393034/77616607-55fe5280-6f32-11ea-9cab-24e21428e84d.png)

**Comment by johngodley** [comment]
Right. There is no such thing as a backlink redirect. You may be able to use a 'URL and referrer' redirect:

https://redirection.me/support/matching-redirects/

However, referrer information is not guaranteed and it is unlikely to work. Your best solution is to change the link on the site, otherwise there is nothing you can do.

**Comment by johngodley** [comment]
What you have configured will not work and it is impossible for it to work, whether using Redirection or anything else - this is not how redirects work.

**Comment by NEC-AnGeL** [comment]
> Right. There is no such thing as a backlink redirect. You may be able to use a 'URL and referrer' redirect:
> 
> https://redirection.me/support/matching-redirects/
> 
> However, referrer information is not guaranteed and it is unlikely to work. Your best solution is to change the link on the site, otherwise there is nothing you can do.

ok i think to take a another solution. Thanks for your help.
