### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by billigan** [johngodley/redirection#2222]
Having an unknown error in the plugin. I made a local copy on MAMP, works fine, uploaded to the server -Godaddy hosting... and the redirection is showing these errors on the live site only.
Not sure what the difference would be.

![Screen Shot 2020-03-20 at 2 34 41 PM](https://user-images.githubusercontent.com/8698426/77204315-165de380-6ab8-11ea-82ec-ee5d70ee5f13.png)

```
Plugin: 4.7.1
WordPress: 5.3.2 (single)
PHP: 7.2.22
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
JavaScript: https://newcompass:8890/wp-content/plugins/redirection/redirection.js
REST API: https://newcompass:8890/wp-json/

Error: Unknown error [object Object] (unknown)
Action: redirection/v1/setting/ GET
Code: 500 Internal Server Error
Raw: {"settings":{"support":false,"token":"1e2360b299524994e35ae974d27a670d","monitor_post":1,"monitor_types":["post","page"],"associated_redirect":"","auto_target":"","expire_redirect":7,"expire_404":7,"modules":[],"newsletter":false,"redirect_cache":1,"ip_logging":0,"last_group_id":1,"rest_api":0,"https":false,"database":"4.1","flag_query":"exact","flag_case":false,"flag_trailing":false,"flag_regex":false,"headers":[],"relocate":"","preferred_domain":"","aliases":[]},"groups":[{"label":"WordPress","value":[{"label":"Redirections","value":1},{"label":"Modified Posts","value":2}]}],"installed":"\/Applications\/MAMP\/htdocs\/newcompass\/","canDelete":true,"post_types":{"post":"Posts","page":"Pages","popup":"Popups","wp-timeline":"Timeline","avada_portfolio":"Portfolio","avada_faq":"FAQs","slide":"Fusion Slides","fusion_template":"Fusion Templates","trash":"Trash"}}
```

**Comment by johngodley** [comment]
Your REST API is returning a 500 error, but also returning the expected data. It might be worth checking your error logs, and/or seeing if any plugins could be interfering.

**Comment by billigan** [comment]
Thanks John. Godaddy is the hosting co. and they had migrated the site and it was coming from http & https for longer than it probably should have been and apparently this was causing the errors. 

I also wasn't able to upload images also and some of the images were missing, and when I replaced them, they disappeared again. 
A real pain because we didn't know the cause and their "tech support" told me that "the server is working correctly because the site is visible on the web..." yep, actual statement. Anyhow, I appreciate your time and response. Thanks!
