### ISSUE TITLE
Error: Unable to add new redirect (58): Unknown column 'match_data' in 'field list'

### ISSUE THREAD

**Issue by bellivychris** [johngodley/redirection#2240]
I'm trying to redirect https://launchcenters.com/blog/young-adult-drug-rehab-los-angeles/ to https://launchcenters.com/young-adult-drug-rehab-los-angeles/

Attached is the error I'm receiving

![image](https://user-images.githubusercontent.com/63268274/78614376-3d8c1300-7823-11ea-80a8-f6ba2b152c75.png)

I'm using Google Chrome.

**Comment by johngodley** [comment]
Please go to the support page, change the database version to 2.4, and follow the instructions.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
