### ISSUE TITLE
Canonical Settings - Force a redirect from HTTP to HTTPS not working

### ISSUE THREAD

**Issue by mikgol** [johngodley/redirection#2245]
Hi John,

Firstly, thanks for  making such a great plugin.  I'm finding it very useful.

I'm finding that the "Force a redirect from HTTP to HTTPS" isn't working.  I have it ticked and clicked Update, but the http:// pages load as normal.

I refreshed the redirection settings page in WP, to make sure that it was still ticked (in case the setting didn't save) and it was.

Do you know what could be causing it to not work?

Thanks,
Michael

**Comment by johngodley** [comment]
Do you have a URL I can test this with?

**Comment by mikgol** [comment]
Hi John... thanks for the quick reply. URL is dev.ezyonlinebookings.com

Cheers,
Michael

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by johngodley** [comment]
It seems to be redirecting when I try it now?

**Comment by mikgol** [comment]
Hi John,

Thanks for looking into this.  Yep it's all working now... i found an option in CPanel to force HTTPS which seems to have done it, so all good.
100% sure that it wasn't working before I ticked the CPanel option (and did tick it in the plugin)... it might be something to look into, but at least there's a CPanel workaround.
Fantastic work on the plugin btw ... I'll definitely contribute a small donation soon once I get some money come through.

Cheers,
Michael

________________________________
