### ISSUE TITLE
I can not CSV import

### ISSUE THREAD

**Issue by Zexler** [johngodley/redirection#2247]
I want to create many 410 redirects from remote pages. But your plugin does not want to accept import CSV-files. File contents (I took an example from the export file.):

source,target,regex,type,code,match,hits,title
/119082348203948,"*","0","error","410","error","32",""

Anyway, this page is displayed in the plugin list as 301.

**Comment by johngodley** [comment]
In what way is it not working? The plugin does not support importing 410 by CSV

**Comment by Zexler** [comment]
Oh, unexpectedly. Then there are no questions. It's sad of course. Export is available, but no import.

**Comment by johngodley** [comment]
There is an onscreen message that CSV does not support everything and that you can use JSON instead.
