### ISSUE TITLE
Plugin Not Redirecting

### ISSUE THREAD

**Issue by carterusm29** [johngodley/redirection#2250]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

I have just installed your plugin and imported from 301 redirects.  But it doesn't seem to be redirecting.  Have the browser message that it isn't redirecting properly or there is a chain of too many redirects.  I have tried on several browsers.  One of the pages I am trying to redirect is from:

https://www.guymilnes.com/ultimate-wedding-photography-guide-hints-tips/

to

https://www.guymilnes.com/ultimate-wedding-photography-guide/

### Steps to reproduce

Copy and paste the first URL.

### Environment

Firefox and Explorer and Redirection plugin.

Many thanks for your help.

**Comment by johngodley** [comment]
Yes, you've created a redirect from https://www.guymilnes.com/ultimate-wedding-photography-guide-hints-tips/ to https://www.guymilnes.com/ultimate-wedding-photography-guide-hints-tips/ - an infinite loop.

You'll need to edit your redirects so this loop doesn't exist.

**Comment by carterusm29** [comment]
Hi John,

 

Many thanks for your very quick reply.

 

In the plugin I have the source URL as /ultimate-wedding-photography-guide-hints-tips/ and the target URL as https://www.guymilnes.com/ultimate-wedding-photography-guide/ which shouldn’t create a loop.

 

I have cleared all Wordpress and browser caches etc.

 

Best wishes and speak soon,

Guy

 

TEL: 07947 613070

WEB:  <https://www.guymilnes.com/> www.guymilnes.com/

FACEBOOK:    <http://www.facebook.com/guymilnes> facebook.com/guymilnes

INSTAGRAM:    <https://www.instagram.com/guymilnesphotos/> instagram.com/guymilnesphotos

**Comment by johngodley** [comment]
Ok, but do you have other redirects or are using a regular expression? The plugin will only redirect to a URL you instruct it to, and at the moment it is redirecting to itself.

**Comment by carterusm29** [comment]
Hi John,

 

Yes, I have about three pages of redirects which I will go through.  I’ve noticed that the plugin is putting a slash in front of everything even if it’s a complete URL such as “/guymilnes.com”.  Could this be the reason?

 

Best wishes and speak soon,

Guy

 

TEL: 07947 613070

WEB:  <https://www.guymilnes.com/> www.guymilnes.com/

FACEBOOK:    <http://www.facebook.com/guymilnes> facebook.com/guymilnes

INSTAGRAM:    <https://www.instagram.com/guymilnesphotos/> instagram.com/guymilnesphotos

**Comment by carterusm29** [comment]
Hi John,

 

I found the reason – previous URL changes I hadn’t altered.  Thanks so much for your help.  Glad the fault was with me.

 

Best wishes,

Guy

 

TEL: 07947 613070

WEB:  <https://www.guymilnes.com/> www.guymilnes.com/

FACEBOOK:    <http://www.facebook.com/guymilnes> facebook.com/guymilnes

INSTAGRAM:    <https://www.instagram.com/guymilnesphotos/> instagram.com/guymilnesphotos
