### ISSUE TITLE
Problem starting Redirection 4.7.1

### ISSUE THREAD

**Issue by traviskorns** [johngodley/redirection#2256]
To help track problems please follow this template. If you can provide screenshots then that will help.

https://www.dropbox.com/s/wmncdelh7ihqftd/PROBLEMS.png?dl=0

I'm wanting to add more redirects.   I try to open the redirect plugin and it won't open, it says it most often is because of a conflict with other plugins.  Redirection is the only plug in I have activated and running on my wordpress right now. 

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

CHROME, Version 81.0.4044.113 (Official Build) (64-bit)
Redirection v4.7.1

**Comment by johngodley** [comment]
Something else is stopping Redirection from loading. This may be your theme.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
