### ISSUE TITLE
/%day%/ chnages to /y%/ 

### ISSUE THREAD

**Issue by nextinweb** [johngodley/redirection#2257]
Recently I changes my WordPress website's URL pattern from %year%/%monthnum%/%day%/%postname%/
to
%postname%/

Now I want to redirect all old links to new, but the "%year%/%monthnum%/%day%/%postname%/" to saving as "%year%/%monthnum%/y%/%postname%/".
What could be the issue?

Also tried another plugin, it also has the same issue.

**Comment by johngodley** [comment]
I don't understand what you've tried to do. Can you explain more, maybe using a screenshot?

**Comment by nextinweb** [comment]
> I don't understand what you've tried to do. Can you explain more, maybe using a screenshot?

Old url format was "https://sitename.in/2020/04/07/i-love-yoga/"
new url format "https://sitename.in/i-love-yoga/"

There are 3500+ similar links.
How can I achieve that ?

**Comment by johngodley** [comment]
See https://redirection.me/support/redirect-regular-expressions/

It is not possible to use WordPress permalink settings in a redirect.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
