### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by kaward04** [johngodley/redirection#2261]
### Summary

Trying to add a new redirect to my existing set

### Actual Behavior

Error: No route was found matching the URL and request method (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

On previous attempts today the plugin displayed a success message but the redirect was not created. Same with Group

### Steps to reproduce

Redirects>Add New

Source URL /st-marys-fund/

Query Parameters None

Target URL https://st-marys.richmond.sch.uk.sch.uk/fosm-st-marys-fund/

Group Redirections

>Save

### Environment

```
Plugin: 4.7.1
WordPress: 5.4 (single)
PHP: 7.3.15
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
JavaScript: https://st-marys.richmond.sch.uk/wp-content/plugins/redirection/redirection.js
REST API: https://st-marys.richmond.sch.uk/wp-json/

```
Many thanks!

**Comment by johngodley** [comment]
Your WordPress REST API is probably being blocked by a security plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
