### ISSUE TITLE
Problem starting Redirection 4.7.1

### ISSUE THREAD

**Issue by bhavyachauhan32** [johngodley/redirection#2264]
Plugin: 4.7.1
WordPress: 5.4 (single)
PHP: 7.3.16
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
JavaScript: https://www.rkumar.in/wp-content/plugins/redirection/redirection.js
REST API: https://www.rkumar.in/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. You will need to disable them until you find the one causing the problem.
