### ISSUE TITLE
Problem starting Redirection 4.7.1

### ISSUE THREAD

**Issue by reaksi** [johngodley/redirection#2267]
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined https://www.aksi.co/wp-admin/load-scripts.php?c=1&load%5Bchunk_0%5D=hoverIntent,common,hoverintent-js,admin-bar,svg-painter,wp-hooks,heartbeat,wp-auth-check,jquery-ui-core,jquery-ui-widget,jquery-&load%5Bchunk_1%5D=ui-mouse,jquery-ui-sortable&ver=5.3.2 250
```

Plugin: 4.7.1
WordPress: 5.3.2 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
JavaScript: https://www.aksi.co/wp-content/plugins/redirection/redirection.js
REST API: https://www.aksi.co/wp-json/

**Comment by johngodley** [comment]
That looks like an error with another plugin on your site. You can try disabling other plugins and see which one stops the error.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
