### ISSUE TITLE
[Feature Suggestion] Ability to group by User Agent

### ISSUE THREAD

**Issue by adevade** [johngodley/redirection#2275]
### Summary

I would like to have the ability to group 404 logs by the User Agent. This would be useful to quickly sort and delete all entries by a certain user agent, for example a bot.

I often delete unnecessary entries to easier find the more useful ones.

### Actual Behavior

Right now we are able to group by URL and IP, but I would like to see this extended to include User Agent strings.

![image](https://user-images.githubusercontent.com/1066486/80277754-841db080-86f1-11ea-9ea8-85fd00b6071c.png)
(Screenshot in Swedish)

### Environment

I'm using the latest versions of WordPress (5.4) and Redirection (4.7.1).

**Comment by johngodley** [comment]
This will be available in the next version.
