### ISSUE TITLE
"Delete all matching" button only available when searching for URLs

### ISSUE THREAD

**Issue by adevade** [johngodley/redirection#2276]
### Summary

I don't know if it's a bug, but if it's not, consider this a Feature Suggestion.

When searching for an URL, I get the option to **Delete all matching [search-term]**, but not when searching for IP or User Agent.

![image](https://user-images.githubusercontent.com/1066486/80277949-db705080-86f2-11ea-8383-cf0f8eb8e6eb.png)

### Actual Behavior

Currently we're only able to delete all matching search results for URLs.

### Steps to reproduce

1. Search for a string that matches some URLs
2. See button on bottom of table "Delete all matching [search-term]"
3. Search for a string that matches some User Agents
4. Don't see button on bottom of table

### Environment

Using latest versions of WordPress (5.4) and Redirection (4.7.1).

**Comment by johngodley** [comment]
It's not a bug, and the next version will expand the places that the delete button works.
