### ISSUE TITLE
Problem starting Redirection 4.7.1

### ISSUE THREAD

**Issue by mysmsmart** [johngodley/redirection#2278]
Plugin: 4.7.1
WordPress: 5.4 (single)
PHP: 7.3.8
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
JavaScript: https://www.techjogi.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.techjogi.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. You will need to disable them until you find the one causing the problem.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
