### ISSUE TITLE
301 redirect n redirection

### ISSUE THREAD

**Issue by Gaspari11** [johngodley/redirection#2284]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

i uploaded a csv of 301 redirects it accepted all of them 

### Actual Behavior

however the pages are 404 and are not bing redirected 

### Steps to reproduce

go to url, also when i check the re direct with the plugin it tells me its redirecting fine but it is not 
![Screen Shot 2020-05-01 at 4 54 49 PM](https://user-images.githubusercontent.com/64664082/80841027-948bca80-8bcc-11ea-8c23-d69bb7103270.png)

### Environment

safari, chrome, firefox

**Comment by johngodley** [comment]
The URL `https://windowbroker.ca/Yongehurst-York-ON.\*,/window-replacement-Yongehurst-York-ON,1,301` is redirecting fine, as indicated by the checker.

However, I suspect that is not the URL you want, and your CSV file was not in the correct format.

**Comment by Gaspari11** [comment]
The plugin tells you it’s redirecting when you check with the plugin but
when you visit the link on the browser it goes to 404
This is the same for all the links in the csv there are over 7000 links it
accepted the upload so I assume it was correct I have tried many different
ways been trying for hrs can’t get this to work

Follow the example csv file as well as tried a combination of different
thing in csv can’t get it to work

Any help would make my day

**Comment by johngodley** [comment]
As I said, the URL in Redirection is working fine and the redirect checker is correct.

However, I don't think `https://windowbroker.ca/Yongehurst-York-ON.*,/window-replacement-Yongehurst-York-ON,1,301` is the URL you want or the one that you are trying in your browser. This leads me to think that your CSV is not of the correct format. Just because it accepted your CSV file does not mean that it was the correct format, and the plugin will do it's best to interpret your data. This may not always be what you want.

**Comment by Gaspari11** [comment]
What is the correct format for the excel column A with old and B with new
with out the domain name? I tried this, also tried leaving in the domain
name

Also combined into one column with , separator non of these have worked for
me

**Comment by Gaspari11** [comment]
Tried uploading new csv old in a new in b and this was the result and error 
Now a second file and second error

**Comment by Gaspari11** [comment]
I tried all day with your plugin I just uploaded another plugin and it worked right away
