### ISSUE TITLE
Disable Logging not working

### ISSUE THREAD

**Issue by renduples** [johngodley/redirection#2285]
### Summary
We have a high traffic website 
In the UI all logs are set to "no logs" and "no IP logging" yet our database is flooded with thousands of queries per minute:

UPDATE wp_redirection_items SET last_count=last_count+1, last_access=NOW() WHERE id=51

### Environment
Redirection Version 4.7.1
Wordpress 5.4.1

**Comment by johngodley** [comment]
Currently the only way to disable this with the `redirection_redirect_counter` filter described here:

https://redirection.me/developer/wordpress-hooks/

**Comment by renduples** [comment]
Thanks John
Please provide a code snippet of how to remove the log filter

**Comment by johngodley** [comment]
Examples of using WordPress hooks can be found here: https://codex.wordpress.org/Plugin_API
