### ISSUE TITLE
Redirection showing a 404 page

### ISSUE THREAD

**Issue by roobens-batg** [johngodley/redirection#2290]
### Summary

Sorry, rookie question! I'm SEO-optimizing old content on my travel blog right now. That means changing titles, meta descriptions, keywords... and URLs! Everyone kept raving about the Redirection plugin so I decided to give it a try. Plus I watched Youtube tutorials and it looked easy (I'm not a techie guy at all!). So I installed and did a test on one of my articles... and unfortunately it's not working!

### Actual Behavior

I filled the fields, and although it looks simple, for some reason it's not working. I put the old URL in the "Source URL" field, the new one in the "Target URL" field, and clicked on "Add redirect". I didn't touch anything else (screenshot attached). Actually, the redirection is working... but the new page shows an error 404 (screenshot attached).

Went back to Tools->Redirection. Clicked on "Check redirect" and it says it's working. (screenshot attached). I clicked on "Support", then tried the Redirect tester and clicked on "Check". It says it's working (screenshot attached). But the new page keeps showing an error 404. I tried on 4 different browsers plus on mobile, nothing changes.

### Steps to reproduce

It was my first redirect so maybe something's wrong with the settings. There's nothing special to do, apart from adding a redirection. Since this one isn't working, I didn't try with another one, don't wanna mess with all my pages.

### Environment

I use Brave 1.8.95. Also tried the new URL on Internet Explorer, Mozilla Firefox and Google Chrome, it shows the 404 page everywhere. I use Wordpress 5.4.1 and Redirection plugin 4.7.2. And yes, I cleared my cache before sending this ticket. And tried deactivating all my other plugins too!

Thank you!

![check redirect](https://user-images.githubusercontent.com/65124608/81504122-ce08b800-92e7-11ea-8d45-085d8912e44e.PNG)
![didn't touch anything](https://user-images.githubusercontent.com/65124608/81504123-cea14e80-92e7-11ea-805a-c3bac49ce6d7.PNG)
![error 404](https://user-images.githubusercontent.com/65124608/81504124-cea14e80-92e7-11ea-82ff-faaf10715e6d.PNG)
![redirect tester](https://user-images.githubusercontent.com/65124608/81504125-cf39e500-92e7-11ea-8697-d7c3b3121c7d.PNG)

**Comment by johngodley** [comment]
You have a redirect for https://www.beenaroundtheglobe.com/discovering-munich-germany/ which is sending you to https://www.beenaroundtheglobe.com/3-days-in-munich/

This is working fine.

There is no page at https://www.beenaroundtheglobe.com/3-days-in-munich/ though.

**Comment by roobens-batg** [comment]
Thanks for responding.

Yes as I said, the redirect is working, but there used to be an article with photos, etc... on the old URL. Everything disappeared on the new URL, it just shows a 404. Do you know why? I still see the post on my admin.

**Comment by johngodley** [comment]
As far as Redirection is concerned you have created a redirect from one URL to another, and this is working fine. If the target page isn't valid then that's unrelated to Redirection - it has no control over the target URL, and just sends your browser there.

You will need to find out why the page itself isn't working. Redirection isn't causing the 404.

**Comment by roobens-batg** [comment]
All right thanks

**Comment by roobens-batg** [comment]
Fixed the issue, thanks for your quick response!

**Comment by roobens-batg** [comment]
Fixed the issue, thanks for your quick response!
