### ISSUE TITLE
Can't finish setup: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by jaamo** [johngodley/redirection#2294]
### Summary

I'm trying to install the plugin with relative REST path. The REST API method detection works fine and detects that only working option in my case is the relative path: `/wp-json/`. Both GET and POST requests are ok. Installation still fails.

### Actual Behavior

After REST detection I continue the wizard and the database setup fails.

Issue is that the database setup REST request (`/wp-json/redirection/v1/plugin/database/`) is not made with the relative url even though that has been tested to be the only working option.

There's a bug in getFirstApi method on `client/component/welcome-wizard/index.js` file.

apiTest has following indices:
```
{
  0:{
    GET: {status: "fail"},
    POST: {status: "fail"}
  },
  1: {
    GET: {status: "fail"},
    POST: {status: "fail"}
  },
  3: {
    GET: {status: "ok"},
    POST: {status: "ok"}
  }
}
```

**However you are looping apiTest with numeric index (0, 1, 2) and therefore the index 3 is never reached and never returned.**

For example this could work:
```
getFirstApi() {
	const { apiTest } = this.props;
	const keys = Object.keys( apiTest );

	for ( let index of keys ) { // changed line
		if ( apiTest[ index ] && apiTest[ index ].GET.status === 'ok' && apiTest[ index ].POST.status === 'ok' ) {
			return index;
		}
	}

	return 0;
}
```

### Steps to reproduce

1. Start setup
2. REST methods are detected and only working option is relative call (rest_api 3). 
3. Continue to database setup
4. Installation fails with message: NetworkError when attempting to fetch resource

### Environment

As a background I'm behind a load balancer and SSL termination is done on the load balancer. WordPress url is non-SSL (http) but the public url is with SSL (https). The redirection plugin should work normally with relative REST url. 

```Plugin: 4.7.2
WordPress: 5.2.6 (multi)
PHP: 7.2.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:76.0) Gecko/20100101 Firefox/76.0
JavaScript: https://********/wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

Error: NetworkError when attempting to fetch resource.```

**Comment by johngodley** [comment]
Thanks, I'll look into this.
