### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by maazsq** [johngodley/redirection#2296]
```
Plugin: 4.7.1
WordPress: 5.3.3 (single)
PHP: 7.3.17
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
JavaScript: https://isak.us/wp-content/plugins/redirection/redirection.js
REST API: https://isak.us/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

I've tried refreshing my session and cache multiple times but I'm still seeing this error.

**Comment by johngodley** [comment]
Data is being cached, maybe on the server. You will also need to clear that cache. You can then ensure that `/wp-admin/` and `/wp-json` is excluded from your cache setup.

**Comment by maazq-od** [comment]
Thanks, I just used a different browser instead and it worked.

**Comment by maazsq** [comment]
I used a different browser and it worked. Must be something wrong with Chrome.
