### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by sherrigoodman** [johngodley/redirection#2299]
Hi!

I've been working with iThemes on this error I keep getting - if I deactivate iThemes Security Pro plugin - Redirection will work. 

We've gone through the settings on Security to make sure it's not set to block the REST API as well. They've been testing on another site and a fresh install of Security and Redirection works for them. Yet, my site is not working regardless of a fresh install of these plugins.

I'm attaching the error messages (screenshot) of what I'm seeing and wondering if one of the options might be worth a try? I don't really understand what these mean and if they don't work, how can I reset them back to what they were before? I didn't want to click on anything until I asked...

Please review and let me know what you think.
Attached: Redirection ‹ Marroquin Organic — WordPress_ERROR-on-Set-Up.png

```
Plugin: 4.7.2
WordPress: 5.4.1 (single)
PHP: 7.2.30-1+ubuntu18.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0
JavaScript: https://marroquin-organics.com/wp-content/plugins/redirection/redirection.js
REST API: https://marroquin-organics.com/wp-json/

Error: <p>There has been a critical error on your website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p> (internal_server_error)
Action: redirection/v1/redirect/?orderby=id GET
Code: 500 Internal Server Error
Raw: {"code":"internal_server_error","message":"<p>There has been a critical error on your website.<\/p><p><a href=\"https:\/\/wordpress.org\/support\/article\/debugging-in-wordpress\/\">Learn more about debugging in WordPress.<\/a><\/p>","data":{"status":500},"additional_errors":[]}
```

I hope you can help or advise what I could try to resolve the conflict. 

FYI - I had these working together before and didn't change anything in the settings... the only change that happened as far as I can tell were updates made in the last couple months.

Please advise.
Thank you!
Sherri Goodman :-)
sherri@goodman-graphics.com
![Redirection ‹ Marroquin Organic — WordPress_ERROR-on-Set-Up](https://user-images.githubusercontent.com/49343745/81884092-c77a7a80-954b-11ea-8cc0-34e38d40ec30.png)

**Comment by sherrigoodman** [comment]
Oh - one more thing - the screenshot is not showing that there's a button next to each of these gray sections that says "Switch to this API" --- that's what I was referring to in clicking on one of these to see if it would help.

Thanks,
Sherri :-)

**Comment by johngodley** [comment]
If you access your WordPress REST API you will find it doesn't work:

https://marroquin-organics.com/wp-json/

This is not caused by Redirection, but by something else.

You can use the WordPress Site Health function to test this further and you will see the same problem. This is not connected to an update in Redirection. It may be connected to an updated in WordPress.

You might find more information in your server error log.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
