### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by timgrable** [johngodley/redirection#23]
I just moved hosting to godaddy's Managed WordPress hosting. I am now getting the following error:

Catchable fatal error: Argument 2 passed to Redirection_Table::__construct() must be an instance of Red_Group, boolean given, called in /home/content/p3pnexwpnas03_data01/25/2313525/html/wp-content/plugins/redirection/redirection.php on line 371 and defined in /home/content/p3pnexwpnas03_data01/25/2313525/html/wp-content/plugins/redirection/models/pager.php on line 10

Is there a fix for this?

https://wordpress.org/plugins/redirection/

**Comment by social-ink** [comment]
Any news on this? We get same error on fresh install.

**Comment by timgrable** [comment]
Never got it fixed.  I'm using another plug in for this

**Comment by social-ink** [comment]
Yeah I found other bugs with this - what do you like nowadays?

**Comment by timgrable** [comment]
yoast seo

Tim Grable
562 Natchez Bend Rd, Nashville, TN 37221

1 615 283 0039, phone/fax
