### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Christophe-Renou** [johngodley/redirection#2300]
Hi

I am trying to upgrade my the database of my Wordpress site, and something is going wrong. 
Anyone can help me solving it please :-)?```

Plugin: 4.7.2
WordPress: 4.9.8 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
JavaScript: https://www.orizontal.com.co/wp-content/plugins/redirection/redirection.js
REST API: https://www.orizontal.com.co/wp-json/

Error: Unexpected end of JSON input (SyntaxError)
Raw: -no data-
```

**Comment by Christophe-Renou** [comment]
And here are the indications given by Wordpress

![Screen Shot 2020-05-14 at 19 52 23](https://user-images.githubusercontent.com/65376630/82000256-5acfb080-961d-11ea-8ad5-5f4abeda69ae.png)

**Comment by johngodley** [comment]
As the messages suggest, your WordPress REST API is not working:

https://www.orizontal.com.co/wp-json/

You will need to fix whatever is causing that problem, then Redirection will be able to work.

**Comment by Christophe-Renou** [comment]
Thanks johngodley, I will investigate in this direction
