### ISSUE TITLE
Google still seeing amp pages I'm trying to redirect from

### ISSUE THREAD

**Issue by jamminjames** [johngodley/redirection#2302]
### Summary

I'm using your fine plugin on Wordpress to redirect old /amp pages (I've deleted the amp plugin). It seems Google is still seeing those pages, though, and giving me "mobile usability" errors, namely, text that's too small, clickable elements too close together. 

### Actual Behavior

I tested the redirects, and they are working. However, looking at what Google Search Console shows in the tested page screenshot, it's the old amp page, not what's really showing -- on my phone, at least. 

I know it's not your plugin that's the problem, but I was hoping you might be able to tell me what to do about this problem. Thanks!

### Environment

I'm using the latest version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
It will probably take some time for Google to update.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
