### ISSUE TITLE
PHP version mis-match

### ISSUE THREAD

**Issue by Markshall** [johngodley/redirection#2306]
### Summary

After updating to Redirection 4.7.2, I'm being told that the plugin is disabled as it requires PHP 5.4+, yet the plugin tells me I'm running PHP 5.5.38

![Screenshot_1](https://user-images.githubusercontent.com/7685469/82201535-72968580-98f8-11ea-916c-7634a11789a1.png)

### Actual Behavior
Theoretically, the plugin should not be disabled as my local version of PHP is greater than the required version Redirection is prompting me to have installed.

### Steps to reproduce
I simply updated the plugin on a Centos distro running PHP 5.5.38

### Environment
* Google Chrome (latest as of writing this issue)
* WordPress 5.1.5
* Redirection 4.7.2

**Comment by johngodley** [comment]
The message is incorrect, sorry I'll update that. The plugin requires PHP 5.6, as shown here:

https://wordpress.org/plugins/redirection/

**Comment by Markshall** [comment]
Thanks for the fast reply John. Would downgrading the plugin version re-activate it without any breaking changes? If so, where can I find these files?

I feel that there should've been some clear indication before updating the plugin that it would automatically deactivate itself as not all sites will be immediately able to upgrade PHP versions.

**Comment by johngodley** [comment]
There is an [upgrade warning on the plugin](https://github.com/johngodley/redirection/blob/master/readme.txt#L167) before you upgrade and this is shown by WordPress.

The message you've seen is the last-step protection to stop it crashing your site.

Downgrading should be fine. Different versions can be found on the plugin page:

https://wordpress.org/plugins/redirection/advanced/

**Comment by Markshall** [comment]
Sorry John, my problem not reading clearly enough. I've downgraded to an older version and it's working as expected now.

Thanks for your help, and thanks for the work you do on the plugin!
