### ISSUE TITLE
Apostrophes cause a slash to be added

### ISSUE THREAD

**Issue by shepherd67** [johngodley/redirection#2312]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Apostrophes cause a slash to be added. 

### Actual Behavior

https://overpowered.createaforum.com/havoc-shows/havoc-17-'fateful-five'/ 

sends to:

https://overpowered.createaforum.com/havoc-shows/havoc-17-/'fateful-five/'/

### Steps to reproduce

All I did was add the first link as the result of a redirect from my web site. 

### Environment

Google Chrome, latest build. Word Press, current version. Redirection 4.8.  

I did search the backlogs and saw this issue was said to have been fixed in 4.3.1, but I am still having issues. I even tried to add %27 in place of the apostrophe. The result was the same.

The link I'm redirecting from is:

https://wearesplat.com/overpowered-havoc-17-fateful-five

**Comment by johngodley** [comment]
I'm not able to reproduce this, and Redirection contains no code to perform this transform. It is likely either WordPress itself, or something on your site.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
