### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by andreassletten** [johngodley/redirection#2315]
```
Plugin: 4.8
WordPress: 5.4.1 (single)
PHP: 7.0.30-1~dotdeb+8.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
JavaScript: https://nordic-crisis.no/wp-content/plugins/redirection/redirection.js
REST API: https://nordic-crisis/wp-json/

Error: Failed to fetch
```

**Comment by johngodley** [comment]
One of your URL settings on Settings > General is incorrect: `https://nordic-crisis.no` and `https://nordic-crisis`

**Comment by andreassletten** [comment]
Hi

[cid:image001.png@01D6335A.152ECC30]

Both have full URL under settings



Med vennlig hilsen
Andreas Femtegjeld Sletten
Designer

Mobil: +47 97 56 70 85
E-post: andreas@imbera.no

[cid:image006.png@01D6335A.15456170]<https://imbera.no/>

Besøksadresse: Karl Johans gate 18C, 0159 Oslo
[cid:image007.png@01D6335A.15456170]<https://www.facebook.com/imbera/>[cid:image008.png@01D6335A.15456170]<https://www.instagram.com/imbera.no/> [cid:image009.png@01D6335A.15456170] <https://www.linkedin.com/company/imbera>

Fra: John <notifications@github.com>
Sendt: tirsdag 26. mai 2020 12.31
Til: johngodley/redirection <redirection@noreply.github.com>
Kopi: Andreas Sletten <andreas@imbera.no>; Author <author@noreply.github.com>
Emne: Re: [johngodley/redirection] Redirection Error (#2315)


One of your URL settings on Settings > General is incorrect: https://nordic-crisis.no and https://nordic-crisis

**Comment by johngodley** [comment]
I can't see that image, but something is returning an incorrect domain:

```
JavaScript: https://nordic-crisis.no/wp-content/plugins/redirection/redirection.js
REST API: https://nordic-crisis/wp-json/
```

Maybe you are running a plugin that is doing this. Redirection is using whatever WordPress supplies it.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
