### ISSUE TITLE
Regex redirection not working

### ISSUE THREAD

**Issue by oloccina2** [johngodley/redirection#2317]
Hello,
I am trying to create a regex redirection
FROM: ^/wp-login.php?redirect_to(.*)
TO: https://aikyam.net/accedi?redirect_to$1

settings: https://www.screencast.com/t/RpsGmXCvfn

is this correct?

For example test: https://aikyam.net/wp-login.php?redirect_to=https%3A%2F%2Faikyam.net%2Fcerchio-abbondanza%2F

Because as far as I see it does not work
Thank you

### Environment

Wordpress V 5.4.1
Redirection plugin V 4.8.
Google Chrome V 81.0.4044.138

**Comment by johngodley** [comment]
`?` is a regular expression character and will need to be escaped as `\?`

**Comment by oloccina2** [comment]
That works perfectly, thanks! Your plugin is extremely handy, will donate :)

**Comment by oloccina2** [comment]
You should put a more visible donate button, I am sure you would get more donations.
