### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by mrfenix** [johngodley/redirection#2323]
```
Plugin: 4.8
WordPress: 5.4.1 (single)
PHP: 7.2.31-1+0~20200514.41+debian9~1.gbpe2a56b
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
JavaScript: https://www.mydomain.co.za/wp-content/plugins/redirection/redirection.js
REST API: https://www.mydomain.co.za/wp-json/

Error: NetworkError when attempting to fetch resource.
```
![image](https://user-images.githubusercontent.com/234915/83422187-13209580-a421-11ea-9225-a32762f23ff8.png)

**Comment by johngodley** [comment]
Without knowing the actual domain I can't provide much information other than saying this is likely caused by a security issue on your site.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
