### ISSUE TITLE
How to redirect URL that changed permalinks several times to another domain?

### ISSUE THREAD

**Issue by ooker777** [johngodley/redirection#2324]
### Summary

I want to redirect any URL that contains:

    tu-dien-chuyen-nganh-tong-hop

to a new domain

    https://quảcầu.com/tu-dien-chuyen-nganh

and pass the parameters to it (e.g. Google Analytics tracking link). I'm using this regex:

```
(.*)/tu-dien-chuyen-nganh-tong-hop/(.*)
https://xn--qucu-hr5aza.com/tu-dien-chuyen-nganh/$2
```
But say the source is 

    http://lyminhnhat.com/2019/04/26/tu-dien-chuyen-nganh-tong-hop/?utm_source=Spiderum&utm_medium=Science2vn&utm_campaign=Translation

Then the output is

    https://xn--qucu-hr5aza.com/tu-dien-chuyen-nganh/2019

Do you know how to fix this?

I'm using Firefox with the latest versions of WordPress and Redirection.

**Comment by johngodley** [comment]
That URL is not redirecting as you state:

https://redirect.li/http/?url=http%3A%2F%2Flyminhnhat.com%2F2019%2F04%2F26%2Ftu-dien-chuyen-nganh-tong-hop%2F%3Futm_source%3DSpiderum%26utm_medium%3DScience2vn%26utm_campaign%3DTranslation

Also, it would be better to use the 'ignore and pass' option:

https://redirection.me/support/matching-a-url/

**Comment by ooker777** [comment]
hmm. Is there any time lag between the moment I click save and the moment it actually works?

Also, do I need to have the first `(.*)` in the regex, or just using a slash at the start is enough?

And if I want to use the non-regex redirection, would this setup be good?
![image](https://user-images.githubusercontent.com/6695517/83541117-6844d000-a523-11ea-8f07-f111f9786f9f.png)

**Comment by johngodley** [comment]
If that is the source and target you want, sure.

**Comment by ooker777** [comment]
Is there any time lag between the moment I click save and the moment it actually works?

If the article has many slashes before the article's title (e.g. `http://example.com/xxx/yyy/zzz/article-name`), do I need to have `(.*)` in regex, or just using a slash at the start (`/article-name`) is enough?

**Comment by johngodley** [comment]
No, there is no lag.

Your source has to fully match. If you want to match that URL then put `/xxx/yyy/zzz/article-name`
