### ISSUE TITLE
Redirection errors

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#2327]
All of a sudden my redirections seem to be failing. I have not made any changes at my end.

The first I knew about it was when Google send me a email says I had redirection problems.

For example:

https://www.publictalksoftware.co.uk/msa/HelpOnline/source/helpdemonstrations.html
https://help-msa.publictalksoftware.co.uk/mwb-editor-manage-demos.html

It appears to work:

![Results](https://user-images.githubusercontent.com/7985331/83635351-fe1c4180-a59b-11ea-9f0c-df87cd2b95e3.png)

But if I go to the old link in a browser:

> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at support@one.com to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.

Ok, I just checked my website with FTP and the target page is not there. I now remember that I had deleted this help topic. So why did that "Check" appear to imply it was all OK? And the 404 log is not listing these html links at all.

**Comment by johngodley** [comment]
Your redirects are working fine, and the checker is working correctly - the URL is redirecting.

It is entirely up to you to ensure the target URL is valid. Redirection does not play any part in this, it just does the redirect.

The 404 page is on another server subdomain. You will need Redirection installed and tracking 404s there.

**Comment by ajtruckle** [comment]
I am still confused.

Take:

https://help-msa.publictalksoftware.co.uk/mwb-editor-manage-demos.html

And I want to redirect it to:

https://help-msa.publictalksoftware.co.uk/msa.html

I can't do it.

I know that help-msa is subdomain but I have not had these issues before. How do I redirect back to the primary help page?

**Comment by johngodley** [comment]
Why can't you do it?

**Comment by ajtruckle** [comment]
It does not show as a redirect. I will show you later. Got to go out. Probably something I am doing wrong.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johngodley** [comment]
That seems unrelated to your original message.

See https://redirection.me/support/redirecting-another-site/ for redirecting external URLs.

**Comment by ajtruckle** [comment]
But I can’t install “redirection” on the old site.  Here is some context.

I have a online help system that is in a subdomain (purely cosmetic really).  It is not wordpress. I can’t run redirection in that folder.

I deleted a help topic as it was obsolete so it no longer existed.

I wish I never deleted the help topic now! Haven’t had any problems for years with these redirections.

I can’t map old domains to new sites. I only have one domain (publictalksoftware.co.uk). I simply have a subfolder “msa-help” that has the help file system in it. There is no DNS stuff os anything. Just a simple help documentation system that sits on my wordpress website (but outside of wordpress itself and I just link to it).

I find a lot of this stuff a bit complicated if I am honest. ☹

Andrew

**Comment by johngodley** [comment]
Redirection can only function when it runs. 

I don't know how you have your server configured, but I don't think it is running on https://help-msa.publictalksoftware.co.uk. That means there is nothing it can do.

**Comment by ajtruckle** [comment]
As mentioned, that url is just a folder.on my domain so it is actually:

https://www.publictalksoftware.co.uk/help-msa/

But I know you knew that!

Is this something I can ask my hosting provider?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johngodley** [comment]
I don't know. This is something specific to your setup, not to Redirection. As I mentioned above, Redirection can only work when it runs. You should check your setup for the folder and ensure that WordPress is running when requests are made there.

You may also be able to export the redirects to a .htaccess file too.

**Comment by leeroy122** [comment]
Hi, I love your software, but Im having that same problem he's having. Whenever you edit the old url to a new url that you want to redirect to, it goes back to the old redirect url you were using before the edit. So it is not accepting your new url that you are trying to redirect to.

**Comment by johngodley** [comment]
@leeroy122 that does not sound the same problem. Can you create a new issue?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.

**Comment by ajtruckle** [comment]
This is resolved. In my HelpNDoc software I can add **aliases** for other URL links to the same topic:

![Alias](https://user-images.githubusercontent.com/7985331/85988280-ba73f680-b9e6-11ea-8363-6f21be1f84df.png)

You click on the **...** to display the list where you can add / remove alias' as required:

![alias2](https://user-images.githubusercontent.com/7985331/85988363-d1b2e400-b9e6-11ea-89aa-16e64cd1597f.png)

It still creates a HTML so it will not 404 out but then automatically redirects to the specified topic.
