### ISSUE TITLE
Redirection failing to edit

### ISSUE THREAD

**Issue by leeroy122** [johngodley/redirection#2328]
Hi, whenever I change the old URL to a new Redirect URL it does not work. For some reason its going back to the old URL and not the new redirect url you changed it to.

**Comment by johngodley** [comment]
Can you describe this further, with screenshots? Do you mean that you change a URL, save, and then the old URL appears?

If this is the case then your site is being cached and you will need to stop the cache being applied to `/wp-admin/` and `/wp-json/`

**Comment by leeroy122** [comment]
thank you so much!! its working now. Keep up the great work, you're a genius!! I know this statement is not for this topic but can you make a bulk copy paste feature of redirects?

**Comment by johngodley** [comment]
If you save the redirects in CSV format to a file you can bulk import that way.
