### ISSUE TITLE
All 404s are cleared since upgrade

### ISSUE THREAD

**Issue by KennyWilliamsonMagic** [johngodley/redirection#233]
Hello John, all the 404s from which I could work out what needed to be redirected are gone after upgrade. It cant be that there are none, as everyday I used to get a lot... maybe some others also experiencing this.

**Comment by johngodley** [comment]
Which version are you referring to? The latest 2.6.3 has a bug where the 404 log page isn't showing - does this describe your problem?

**Comment by KennyWilliamsonMagic** [comment]
Hello John,

 

I upgraded to the latest version on two sites... yes, that is correct, it just shows a support page.

 

Magically yours

 

Kenny Williamson

Site Author

Description: _P4N0302 (100x91)

 

Web: https://magiciansandmagic.com/
