### ISSUE TITLE
Dynamic Variables Within Redirect Links

### ISSUE THREAD

**Issue by Elxafil** [johngodley/redirection#2331]
Basically wanting to do something simple when a user is logged in they're redirected to a buddypress profile of their own like /members/someusername/ so I can use the redirect with login status but use a dynamic variable to grab the slug of their username for use in the link.

**Comment by Beee4life** [comment]
can't you use [template_redirect](https://developer.wordpress.org/reference/hooks/template_redirect/) for this ?

**Comment by johngodley** [comment]
Some variables are supported:

https://redirection.me/support/dynamic-urls/
