### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by lucky0011** [johngodley/redirection#2337]
```
Uncaught SyntaxError: Invalid or unexpected token https://kenya4life.com/wp-content/plugins/redirection/redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e 61
```

Plugin: 4.8
WordPress: 5.4.2 (multi)
PHP: 7.4.6
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
JavaScript: https://kenya4life.com/wp-content/plugins/redirection/redirection.js
REST API: https://kenya4life.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. Try disabling them and see which one is causing the problem

**Comment by lucky0011** [comment]
Duplicate of # unfortunately that did not work

**Comment by johngodley** [comment]
Duplicate of what?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
