### ISSUE TITLE
How do I fix the compatibily with Redirections and the Rank Math Seo plugin I have installed on my site?

### ISSUE THREAD

**Issue by cheyennecuellar** [johngodley/redirection#2338]
### Summary

I want to figure out how to get rid of the message that comes up when I activate the Redirections plugin. I looked for what SEO plugin I had installed and it was Rank Math SEO, so I'm guessing that plugin is causing the issue with Redirections but I don't want to delete it.

### Actual Behavior

The plugin says "Please keep only one SEO plugin active, otherwise, you might lose your rankings and traffic." It then asks me to deactivate Redirections.

### Steps to reproduce

To reproduce the problem, I just have to install and activate Redirections.

### Environment

My browser is Chrome 83 on Windows 10. My Wordpress version is 5.4.2 and Redirection version 4.8.

**Comment by johngodley** [comment]
You will need to talk to Rank Math about this.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
