### ISSUE TITLE
Redirecting random pages in Wordpress WooCommerce pages

### ISSUE THREAD

**Issue by teamsportsplanet** [johngodley/redirection#234]
Hello,

Redirect is redirecting many "page 2" sections within WooCommerce - we never intentionally wanted this, but it is happening all of a sudden. In some instances, when you click to the "page 2" link within products, it redirects it back into the first page. Very weird and I'm wondering why these are being created by the Redirection app.

Here's an example - this page will redirect to the first page for no reason:

www.teamsportsplanet.com/product-category/baseball/baseball-helmets/page/2/

www.teamsportsplanet.com/product-category/football/football-equipment/page/2/

Thank you for your help!

**Comment by johngodley** [comment]
Can you provide detailed steps to reproduce the problem? I am unfamiliar with WooCommerce and do not know how to make what you say happen.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
