### ISSUE TITLE
How can I do this?

### ISSUE THREAD

**Issue by Christian-CFP** [johngodley/redirection#2341]
Its not an issue. Need advice.

how can I redirect all
http://www.domain.com/something/XXX/

to

http://www.domain.com/something/XXX/yyy

XXX is variable but redirect to a "subfolder".

http://www.domain.com/something/*
to
http://www.domain.com/something/*/yyy

Does not work.

**Comment by johngodley** [comment]
You can use a regular expression, wildcards are not supported. There are details and examples here:

https://redirection.me/support/redirect-regular-expressions/

**Comment by Christian-CFP** [comment]
Thx! But it does not seem to work for me with:
/something/(.*)
to
/something/$1/yyy/

= /something//yyy/yyy/yyy/yyy/yyy/

**Comment by Christian-CFP** [comment]
I do not have any clou how to test any of this... but thanks... :(

**Comment by johngodley** [comment]
Regular expressions are a complicated subject, and one that is not specific to Redirection.

As detailed on the support page there are many resources for understanding regular expressions, as well as sites where you can test them.

In your above expression you are redirecting to a URL that matches the expression again. This will keep looping until your browser gives up. It is possible that swapping `(.*)` for `(.*?)/$` will do what you want.

Again, you can use the expression test site to test it out.
