### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by mouhsineR** [johngodley/redirection#2342]
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.2.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
JavaScript: https://proactcoach.com/wp-content/plugins/redirection/redirection.js
REST API: https://proactcoach.com/wp-json/
Buster: 4.8 === 4.8

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in span
    in div
    in div
    in div
    in a
    in p
    in div
    in div
    in a
    in p
    in a
    in p
    in StrictMode
    in G
    in Kb

**Comment by johngodley** [comment]
What are you doing when this is shown?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
