### ISSUE TITLE
Redirection Error at staging site

### ISSUE THREAD

**Issue by oshima-being** [johngodley/redirection#2347]
I'm using the plugin WP Staging Pro.
When the Redirection page is displayed on the staging site, the following error is displayed and the settings cannot be saved. I can save my settings on the live site.

```
Plugin: 4.7.2
WordPress: 5.2.3 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
JavaScript: https://sample.com/staging-test/wp-content/plugins/redirection/redirection.js
REST API: https://sample.com/staging-test/wp-json/

Error: その操作を実行する権限がありません。 (rest_forbidden)
Raw: {"code":"rest_forbidden","message":"\u305d\u306e\u64cd\u4f5c\u3092\u5b9f\u884c\u3059\u308b\u6a29\u9650\u304c\u3042\u308a\u307e\u305b\u3093\u3002","data":{"status":401}}
```

**Comment by johngodley** [comment]
Is `https://sample.com/staging-test/wp-json/` a valid REST API?

The message `rest_forbidden` indicates something is blocking the REST API. You will need to find out what that is and disable it.

**Comment by oshima-being** [comment]
https://sample.com/wp-json is OK
https://sample.com/staging-test/wp-json is NG
Is there a problem with the server settings? or WP Staging Pro Plugin?

**Comment by johngodley** [comment]
I really couldn't say. It appears to be the staging plugin, which should not change your REST API URL. Redirection is just using whatever WordPress provides.

**Comment by oshima-being** [comment]
I understand that there seems to be a problem on the Staging Plugin side.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
