### ISSUE TITLE
Problem starting Redirection 4.7.2

### ISSUE THREAD

**Issue by aqsa321** [johngodley/redirection#2357]
Plugin: 4.7.2
WordPress: 5.4.2 (single)
PHP: 7.2.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

**Comment by aqsa321** [comment]
but how am gonna know  which plugin is causing errors ? Kindly suggest me

**Comment by johngodley** [comment]
Try disabling them?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
