### ISSUE TITLE
UTM parameters not passing to target URL

### ISSUE THREAD

**Issue by johnnywandering** [johngodley/redirection#2358]
Hi John,

It seems like UTM values are not persisting to the target url for a range of our redirects. I've tried disabling the vast majority of plugins on the website in staging to see if this fixes the issue, but not having any luck. I've also reviewed the WordPress.org forum for any issues relating to UTM params and couldn't find any that explain my issue. The 'Ignore & pass' setting doesn't seem to be working, and older threads suggest using regex to capture the utm values but I'm assuming the 'Ignore & pass' setting would replace this fix?

Ideal scenario:
301	https://www.bucketlistbombshells.com/skills-workshop?utm_source=testing2&utm_medium=testing2
301	https://bucketlistbombshells.com/skills-workshop?utm_source=testing2&utm_medium=testing2
200	https://bucketlistbombshells.com/workshop?utm_source=testing2&utm_medium=testing2

Actual behaviour:
301	https://www.bucketlistbombshells.com/skills-workshop?utm_source=testing2&utm_medium=testing2
301	https://bucketlistbombshells.com/skills-workshop?utm_source=testing2&utm_medium=testing2
200	https://bucketlistbombshells.com/workshop

One thing that's quite peculiar is that the parameters successfully are ignored and passed when I'm logged in to WordPress (ideal scenario works), but not in incognito mode or using another Chrome profile (actual behaviour).

Any thoughts as to why this might be happening? Cheers

Chrome v83.0.4103.116
WordPress v5.4.2
Redirection plugin v4.8

**Comment by johngodley** [comment]
I think WP Engine removes the UTM parameters:

https://wpengine.co.uk/support/utm-gclid-variables-caching/

**Comment by johnnywandering** [comment]
Thanks for the quick reply! I'll look into this, many thanks

**Comment by johnnywandering** [comment]
@johngodley confirming that this was the issue! Thanks for your help
