### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by andrenoari** [johngodley/redirection#2360]
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.4.5
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
JavaScript: https://andrenoari.com/wp-content/plugins/redirection/redirection.js
REST API: https://andrenoari.com/wp-json/

**Comment by johngodley** [comment]
Please follow the instructions and open your browser's developer console and see if any errors are shown. This is likely caused by another plugin.
