### ISSUE TITLE
Invalid default datetime value in Red_Latest_Database::create_items_sql()

### ISSUE THREAD

**Issue by stavinoj** [johngodley/redirection#2363]
Plugin: 4.8
WordPress: Any
PHP: Any
MySQL: Any (with strict SQL mode and the NO_ZERO_DATE SQL mode enabled)

```
class Red_Latest_Database {
...
	private function create_items_sql( $prefix, $charset_collate ) {
		return "CREATE TABLE IF NOT EXISTS `{$prefix}redirection_items` (
			`...
			`last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
			...
	  ) $charset_collate";
	}
...
}
```

Should be
```
class Red_Latest_Database {
...
	private function create_items_sql( $prefix, $charset_collate ) {
		return "CREATE TABLE IF NOT EXISTS `{$prefix}redirection_items` (
			`...
			`last_access` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
			...
	  ) $charset_collate";
	}
...
}
```

Note: it is also necessary to change Red_Item::load_from_data() to adhere this change.

refs:
- https://dev.mysql.com/doc/refman/8.0/en/datetime.html
- https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html

**Comment by e2-robert** [comment]
> MySQL: Any (with strict SQL mode and the NO_ZERO_DATE SQL mode enabled)

Thing is, MySQL 8 has got those turned on by default and Wordpress does not attempt to change it.
