### ISSUE TITLE
Redirection removes $ from destination URL

### ISSUE THREAD

**Issue by justinhaaheim** [johngodley/redirection#2366]
To help track problems please follow this template. If you can provide screenshots then that will help.

Hi John.

It looks like redirection is removing a $ from my destination URL when the redirection is made. The $ shows in the UI correctly, but when actually redirecting it is removed.

You can see in these examples:

![Screen Shot 2020-07-01 at 11 43 49 PM](https://user-images.githubusercontent.com/3389743/86325347-be756380-bbf4-11ea-9e45-18a8ab8e5615.png)

![Screen Shot 2020-07-01 at 11 43 29 PM](https://user-images.githubusercontent.com/3389743/86325363-c2a18100-bbf4-11ea-9cf6-b5f464ebf212.png)

![Screen Shot 2020-07-01 at 11 42 11 PM](https://user-images.githubusercontent.com/3389743/86325385-c7fecb80-bbf4-11ea-80aa-20369478430b.png)

As a workaround it is possible to use %24 if the value is going to be decoded before being used:

![Screen Shot 2020-07-01 at 11 42 30 PM](https://user-images.githubusercontent.com/3389743/86325456-ea90e480-bbf4-11ea-9f34-0bd710a70d33.png)

### Environment

I disabled all my plugins (except Cornerstone and All in one favicon) and this still repros.

MacOS 10.15.5, Chrome 83.0.4103.116, Wordpress Version 5.4.2, Redirection v4.8

**Comment by johngodley** [comment]
`$` is not allowed by WordPress. See the `wp_sanitize_redirect` core function

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
