### ISSUE TITLE
Screen Options > Log Entries Bug

### ISSUE THREAD

**Issue by dkChase** [johngodley/redirection#2367]
Great plugin. I found a bug on multiple different sites I control hosted on Siteground.

On the "Redirects", "404s", and "Log" tabs. When I go to "Screen Options" -> "Pagination Log entries" and change the number and hit apply. It always reverts back to 25.

Everything on the "Support" tab is green and says "Good."

**Comment by johngodley** [comment]
This will be fixed in the next version.
