### ISSUE TITLE
Feature: Hide or not register some 404

### ISSUE THREAD

**Issue by maxime-pasquier** [johngodley/redirection#2369]
### Summary

Hi, it will be so great, if we could add to a list: all the 404 uri that we don't want to see anymore!
It could be a simple list (like the redirection tab) and we could just add a 404 that we know it's a 404 and we don't want monitoring anymore.

### Actual Behavior

NA

### Steps to reproduce

NA

### Environment

NA

**Comment by johngodley** [comment]
There is an ignore option on a 404 log entry

**Comment by maxime-pasquier** [comment]
So great, exactly perfect!
I'm sorry I never use the select group actions.

Did I miss it in a tutorial or FAQ?

**Comment by ajtruckle** [comment]
I don't see this "Ignore" option when I examine a 404 entry? Can you please show me on a screen grab?

For example, this is listed:

> /xxxx/support-forums/topic-tag/portrait-schedule/

Well, I actually want to ignore all:

> /xxxx/*

links.

**Comment by johngodley** [comment]
https://redirection.me/support/tracking-404-errors/
