### ISSUE TITLE
Cannot delete 404 log file in Redirection 2.6.4

### ISSUE THREAD

**Issue by kadai** [johngodley/redirection#237]
After updating discovered and confirmed (here: https://wordpress.org/support/topic/delete-not-working-2/) that there is an active issue with the 404 log segment.

Currently, it is not possible to delete any entry from such section.

Rolling back to version 2.6.3 fixed the issue for me. So, therefore, the problem might have been added with any code change done in the new version (need to compare both versions to detect what might be causing this, and kind of quickly saw that redirection-ui.js was updated).

I have been searching for logged errors without any success so far.

Then, updated back to 2.6.4 and cleared cloudflare cache, server cache, browser cache and even w3 cache and started to see mixed results. Sometimes the single deletion worked and other times did not. The option that definitively worked was "Delete all logs", what did not before.

Reporting just to have the evidence and to confirm if others have come across this or not at all. As apparently there is a problem for those that have been using caching but need full confirmation on that.

Thanks.

**Comment by johngodley** [comment]
This was fixed in 2.6.5
