### ISSUE TITLE
Redirect results for end user are inconsistenent

### ISSUE THREAD

**Issue by jshan999** [johngodley/redirection#2372]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary - I have redirection setup on our website.  It is configured and working for the most part.
The issue is that some people get redirected and others do not.

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment - some are at home, some on their iphone, it is not narrowed down to one location.
Using wordpress 5.4.2 and the latest of redirector.  Just installed it yesterday.

Please list your browser, browser version, version of WordPress and Redirection plugin.

On one computer where it does not work on chrome, it will work with Internet Explorer 11.  I have disabled any add-ins and even tried in incognito mode with no success.  It does not redirect on one iphone running safari, but it will on an ipad running safari.
I have read the FAQ and the common issues.  I have cleared cashes and cookies,etc.  The issue is just inconsistent all around.   I am not able to pinpont one thing.  Any other issues that would prevent a device from redirection?

Thank you,
Jeff

**Comment by johngodley** [comment]
Redirects work the same on every browser. If they don't then it is always related to a cache.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
