### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by delaneycloss** [johngodley/redirection#2373]
```
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.173
JavaScript: http://rulesofadulting.com/wp-content/plugins/redirection/redirection.js
REST API: http://delaneycloss.com/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/setting/ GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment]
Please follow the onscreen instructions and log out, clear your cache, and log in again.

**Comment by delaneycloss** [comment]
Huh? What onscreen instructions and where?

**Comment by johngodley** [comment]
The above message is shown in a large box with a lot of information about how to proceed, including clearing your cache.

**Comment by delaneycloss** [comment]
I don’t see anything? I will check on my computer but there is nothing but you telling me to follow on screen instructions but no link to where these are.

**Comment by johngodley** [comment]
![image](https://user-images.githubusercontent.com/1277682/87966110-af2b5c80-cab4-11ea-9f77-5ec4242df3fd.png)

**Comment by johngodley** [comment]
Also, your site URLs are http://rulesofadulting.com/ and http://delaneycloss.com. This sounds like you should update your URL settings in General > Settings to be one or the other, whichever is correct.
