### ISSUE TITLE
Can we ignore certain 404s?

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#2379]
I have a staging site that is online for any duration of time and gets deleted as needed. I never intend it being online too long. And I have set it so that search engines won't crawl it.

That said, I am now starting to get quite a lot of the staging site links in my 404 log. I am simply not interested in them. They all start with a certain prefix. Is there a way to omit these from the log ...? I simply don't want any "staging" links listed.

**Comment by johngodley** [comment]
You can use a 'do nothing' redirect:

https://redirection.me/support/redirect-actions/
