### ISSUE TITLE
Redirecting a whole group of links

### ISSUE THREAD

**Issue by LazyLen** [johngodley/redirection#238]
Hi,

Im currently migrating a section on my website to another section. The old area contains something like 300 different pages with unique URLs. 

Is it possible to redirect an entire section with just one redirection? The first two parts of the slug are identical for all pages..

websitename/category/page url

I would like to redirect everything behind

websitename/category/

to then new area.

Is that possible?

**Comment by johngodley** [comment]
A regular expression should do what you want. Enable the regex checkbox and then create a regular expression pattern that matches the URL.

http://www.regular-expressions.info/

For example:

Source: `^/category/(.*)$`
Target: `/newcategory/$1`

**Comment by LazyLen** [comment]
Thanks for answering John!
