### ISSUE TITLE
Double-slash when creating redirection using PHP API

### ISSUE THREAD

**Issue by FeIix** [johngodley/redirection#2382]
Hi,

I'm inserting some redirections like this :

```
$redirect = [
    'status' => 'enabled',
    'action_code' => 301,
    'url' => $old_url,
    'action_data' => [
        'url' => $target,
    ],
    'match_type' => 'url',
    'action_type' => 'url',
    'group_id' => 1,
];
Red_Item::create($redirect);
```

The insertion works fine, but the source url is modified and wrong.
/mypage becomes //mypage

The redirection is not working.

I can howerer edit it manually, like this :
/mypage

And it works fine.
Is this a bug, or something wrong with my code ?

Thanks.

Good plugin 👍 

Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.2.32

**Comment by johngodley** [comment]
Without knowing what `$target` is I can't say. As the plugin correctly saves and updates the target then I would guess your code is wrong. Have a look at what is being saved when you update a redirect and check it matches what you are doing.

**Comment by FeIix** [comment]
Sorry i made a mistake in my post, it's the source URL that is wrong, the target URL is fine.
$old_url is url_encoded, and just the relative path, without the full domain. 
For example : 

"%2Flamborghini-lamborghini%2Cfr%2C4%2CPML005.cfm"

**Comment by johngodley** [comment]
There is no need to URL encode the source, and that may be causing the problem

**Comment by FeIix** [comment]
It worked ! I'm not sure why i thought it needed to be encoded.

Thanks a lot for this fast answer
