### ISSUE TITLE
Redirection for  multilanguage website in Woocommerce

### ISSUE THREAD

**Issue by SocialBrothersDEV** [johngodley/redirection#2385]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### The following URL has been redirected to a redirect which we cannot find in the overview in the backend of the website. The URL which is wrongly redirected is the following:

https://www.easy-noisecontrol.nl/geluidsisolatie-auto

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### 

The URL is redirected as the following:

1. https://www.easy-noisecontrol.nl/geluidsisolatie-auto

2. https://www.easy-noisecontrol.nl/oplossingen/auto (via .htacces, which is oke!)

3. https://www.easy-noisecontrol.com/solutions/sound-insulation-car/ (this one is wrong, but cannot be found in the redirection overview)

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

WordPress latets version, Redirection Latest version, PHP 7.4

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Redirection is not redirecting this:

https://redirect.li/http/?url=https%3A%2F%2Fwww.easy-noisecontrol.nl%2Foplossingen%2Fauto

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
