### ISSUE TITLE
Correctly setting the wild card

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#2387]
![Ignore](https://user-images.githubusercontent.com/7985331/87855802-9a16c800-c912-11ea-85cb-bac93eb7e7d8.png)

Hi

I would like to be able to ignore all URLs where the start is "/~~~~~~/...". It is just: "~~~~~~~~/*"?

**Comment by johngodley** [comment]
Wild cards are not supported. You will need to use a regular expression:

https://redirection.me/support/redirect-regular-expressions/

**Comment by ajtruckle** [comment]
I added:

`^/stg_~~~~~/.*`

And set the regex option and check box to delete from the log all matching. But nothing was removed.

**Comment by ajtruckle** [comment]
I tried:

`^https://www.publictalksoftware.co.uk/~~~~/.*`

**Comment by johngodley** [comment]
Please, this is not a support forum.

You can use https://regex101.com/ to test your expression. `^https://www.publictalksoftware.co.uk/~~~~/.*` is not valid.

**Comment by ajtruckle** [comment]
It is a support forum for your plugin, which is for redirections! But I get your point and understand where you are coming from. Either way, even after making the link correct:

`^https:\/\/www.publictalksoftware.co.uk\/stg_~~~~~\/.* ` 

They are still not all removed from the 404 log when I add it to the redirection arsenal.

But don't worry. If I find a solution I will add it here for others. Have a good day.

**Comment by ajtruckle** [comment]
I used `^/stg_~~~~~` and verify it works. But I had to delete all the other `stg~~~` from the log myself. I assumed it would detect those and delete them at the same time. All good.
