### ISSUE TITLE
www Issue

### ISSUE THREAD

**Issue by melissamc26** [johngodley/redirection#2389]
### Summary

Can't access our website when "www" is included in the URL. 

<img width="1325" alt="Screenshot 2020-07-20 at 15 45 51" src="https://user-images.githubusercontent.com/7379703/87947049-19d39c80-caa3-11ea-8c40-875ecfd1b61d.png">

### Actual Behavior

Go to https://www.waroncancer.com/ and instead of seeing the website, we see the following error message:

> User-agent: * Disallow: /wp-admin/ Allow: /wp-admin/admin-ajax.php

Go to https://waroncancer.com/ and see the website as per normal.

### Environment

All browsers. Plugin Version 4.8

**Comment by johngodley** [comment]
Are you saying that Redirection is causing this, or that you want to use Redirection to fix this?

**Comment by melissamc26** [comment]
We're not sure what is causing it yet, but wondering if it could be the Redirection plugin. Just posting in case anyone else has had a similar issue. It could be completely unrelated (we are looking into all plugins). I will update the post when we know more.

**Comment by johngodley** [comment]
This is a robots.txt file, the same as https://waroncancer.com/robots.txt

> User-agent: * Disallow: /wp-admin/ Allow: /wp-admin/admin-ajax.php

I would imagine this is something to do with your server setup, and it is unlikely to be a plugin.

**Comment by melissamc26** [comment]
Great, thanks for the help John, much appreciated. Should I close the issue?
