### ISSUE TITLE
Force HTTPS redirect breaks cron

### ISSUE THREAD

**Issue by BrianHenryIE** [johngodley/redirection#2390]
### Summary

I installed this on a new site, got a warning from another plugin ([WP Offload SES](https://deliciousbrains.com/wp-offload-ses/)) that cron is not running. I installed [WP Control](https://wordpress.org/plugins/wp-crontrol/) and could see cron jobs queuing up for the past week. After disabling this plugin and invoking cron from the terminal, the jobs ran. After enabling the plugin but disabling "Force a redirect from HTTP to HTTPS", cron jobs run as normal.

### Actual Behavior

I'm not sure where it's failing.

There is nothing in my PHP error logs.

### Steps to reproduce

Enable "Force a redirect from HTTP to HTTPS".

### Environment

WordPress 5.4.2
Redirection 4.8

Running on [Nexcess managed WooCommerce hosting](https://www.nexcess.net/woocommerce/).

Cron invoked with `/usr/sbin/relax php -f /chroot/home/acea7a3b/domain.com/html/wp-cron.php`

**Comment by johngodley** [comment]
Have you updated your site URL settings to also be https? The plugin won't change anything else, so if your site settings are not correct then it is likely some things wont work

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.

**Comment by PJ-developer** [comment]
I had exactly the same issue: envoking wp-cron.php by Cron did not work. Calling wp-cron.php in the browser did. Disabling "Force a redirect from HTTP to HTTPS" solved the issue: wp-cron.php now can be envoked by Cron. URL of site in the global settings starts with "https://".

WordPress: 5.7
Redirection: 5.0.1
