### ISSUE TITLE
error when clicking on options

### ISSUE THREAD

**Issue by vollachr** [johngodley/redirection#2392]
### Summary

I've installed redirection plugin on my wordpress installation, the plugin seems to function fine mostly but whenever I click on the OPTIONS tab of the plugin I get an error.

### Actual Behavior

when I click on options I get an error as follows:
"Something went wrong" 

Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

If that doesn't help, open your browser's error console and create a new issue with the details.

Please mention options, and explain what you were doing at the time

`Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.4.8
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
JavaScript: https://localhost/VisRes/wp-content/plugins/redirection/redirection.js
REST API: https://localhost/VisRes/wp-json/
Buster: 4.8 === 4.8

TypeError: Failed to execute 'appendChild' on 'Node': 1 argument required, but only 0 present.

    in div
    in Unknown
    in p
    in div
    in a
    in p
    in div
    in StrictMode
    in a
    in p
    in StrictMode
    in G
    in Kb`

Also, this is the error from the browser console:

`TypeError: Failed to execute 'appendChild' on 'Node': 1 argument required, but only 0 present.
    at HTMLDivElement.Element.appendChild (<anonymous>:39:362)
    at zi (redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33)
    at Ki (redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33)
    at sc (redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33)
    at uc (redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33)
    at lc (redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33)
    at Zl (redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33)
    at redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33
    at t.unstable_runWithPriority (redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:41)
    at Ho (redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33)
el @ redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e:33`

### Steps to reproduce

Simply go to the plugin in wordpress and click on the options tab.

### Environment

Browser: Google Chrome 84.0.4147.89 (Official Build) (64-bit)
Wordpress 5.4.2
Redirection Plugin v4.8

**Comment by johngodley** [comment]
Can you try temporarily disabling other plugins to see if the problem goes away?

**Comment by vollachr** [comment]
> Can you try temporarily disabling other plugins to see if the problem goes away?

I just did, I disabled almost everything, only redirection and Simple SSL remained on, the problem is still there.

**Comment by johngodley** [comment]
Ok. This seems specific to your site. Could you open your browser's developer console, and in the console type:

`Redirectioni10n`

Then click open all the details and [email](https://redirection.me/contact/) them to me?

**Comment by vollachr** [comment]
> Ok. This seems specific to your site. Could you open your browser's developer console, and in the console type:
> 
> `Redirectioni10n`
> 
> Then click open all the details and [email](https://redirection.me/contact/) them to me?

OK, I just sent you that information.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
