### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by visitasegovia** [johngodley/redirection#2404]
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.3.18
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
JavaScript: https://visitasegovia.es/wp-content/plugins/redirection/redirection.js
REST API: https://visitasegovia.es/wp-json/

**Comment by johngodley** [comment]
This is almost certainly caused by another plugin. Open your browser's developer console and look for any errors.
