### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by OliverHuntsman** [johngodley/redirection#2405]
Hi there, I am getting this issue with the plugin - can someone please help?

Thank you so much!

`Plugin: 3.4.1
WordPress: 4.9.15 (single)
PHP: 7.2.24-0ubuntu0.18.04.6
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
JavaScript: https://gemmasutton.com/wp-content/plugins/redirection/redirection.js
REST API: https://gemmasutton.com/wp-json/

Error: Unexpected token N in JSON at position 0
Action: redirection/v1/setting/ GET
Code: 200 OK
Raw: NULL
bool(true)
{"settings":{"monitor_post":4,"monitor_category":2,"support":false,"token":"a0bb894ae40e78e1426eb26a60c62aa8","auto_target":"","expire_redirect":7,"expire_404":7,"modules":{"2":{"location":""}},"newsletter":false,"monitor_types":["post"],"associated_redirect":"","redirect_cache":1,"ip_logging":1,"last_group_id":1,"rest_api":0,"https":false,"version":"3.4.1"},"groups":[{"text":"WordPress","value":[{"text":"Redirections","value":1},{"text":"Modified Posts","value":2},{"text":"Hubspot Blog","value":3},{"text":"Hubspot blog inner","value":4}]}],"installed":"\/home\/gemmasutton\/gemmasutton.com\/","canDelete":true,"post_types":{"post":"Posts","page":"Pages","proteam":"Pro Team","awards":"Awards","testimonials":"Testimonials","proteamprices":"Pro Team Prices","gsportfolio":"GS Portfolio","trash":"Trash"}}

Error: Unexpected token N in JSON at position 0
Action: redirection/v1/plugin/ GET
Code: 200 OK
Raw: NULL
bool(true)
[{"name":"WordPress REST API","id":"rest","status":"problem","message":"REST API returned invalid JSON data. This is probably an error page of some kind and indicates it has been disabled - Syntax error (200 - https:\/\/gemmasutton.com\/wp-json\/)"},{"name":"Redirection routes","id":"routes","status":"problem","message":"REST API is not working so routes not checked"},{"id":"db","name":"Database tables","status":"good","message":"All tables present"},{"name":"Valid groups","id":"groups","message":"Valid groups detected","status":"good"},{"name":"Valid redirect group","id":"redirect_groups","message":"All redirects have a valid group","status":"good"},{"name":"Post monitor group","id":"monitor","message":"Post monitor group is valid","status":"good"},{"name":"Site and home protocol","id":"redirect_url","message":"Site and home are consistent","status":"good"}]
```

`

**Comment by johngodley** [comment]
You can see the problem when you access this: https://gemmasutton.com/wp-json/

This is appearing at the top:

```
NULL
bool(true)
```

It shouldn't appear there and is breaking your WordPress REST API. You will need to discover what is outputing it.

It is also appearing on your main website.

![image](https://user-images.githubusercontent.com/1277682/89431689-26f5ba00-d738-11ea-9613-b93a59b0cbf6.png)

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
