### ISSUE TITLE
Changed after updating: grouping get reset when you use search within a grouped display

### ISSUE THREAD

**Issue by yulumadavid** [johngodley/redirection#2406]
### Summary

After a recent update something has changed. When you used 'grouped display by url' https://prnt.sc/tuy9f0 and then you use the search bar https://prnt.sc/tuya3n the grouped display gets a reset.

### Environment

WP: 5.4.2
Redirection plugin: 4.8

**Comment by johngodley** [comment]
I don't think this was ever an option, but it will be included in the next version of the plugin.

**Comment by johngodley** [comment]
You can try this in the 4.9 beta:

https://github.com/johngodley/redirection/releases/tag/4.9-beta

Let me know how it goes.

**Comment by yulumadavid** [comment]
Thanx John. Getting this error when installing:

Cannot use object of type stdClass as array in .../public/wp-content/plugins/redirection/redirection-admin.php:249 Stack trace: #0 .../public/wp-includes/class-wp-hook.php(288): Redirection_Admin->redirection_head('') #1 ..../public/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #2 .../public/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 .../public/wp-admin/admin.php(232): do_action('load-tools_page...') #4 .../public/wp-admin/tools.php(40): require_once('/srv/users/baby...') #5 {main}

**Comment by johngodley** [comment]
Sorry, there was a problem with the locale loading if it had different pluralisations, which caused a crash. I've fixed this in beta 2, which is available from the same page.

**Comment by yulumadavid** [comment]
Yes, works like a rocket!

I did saw some text flaws here https://prnt.sc/ugvhgq with the update message.

**Comment by johngodley** [comment]
Great. Yeah, that looks like a problem with the translation itself. Hopefully it will get cleaned up by a translator.
