### ISSUE TITLE
"Force a redirect from HTTP to HTTPS" lacks [L,R=301] - which results in 302 error

### ISSUE THREAD

**Issue by zevrix** [johngodley/redirection#2408]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I tried to use "Force a redirect from HTTP to HTTPS" option. 

But it resulted in error in browsers: "The document has moved here. Additionally, a 302 Found error was encountered while trying to use an ErrorDocument to handle the request."

This error happened when I entered http://mysite.com

Redirection writes this to .htaccess:

RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}

After doing search on the error, I found suggestion to add [L,R=301] to rewrite rule:

RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

This solved the issue: http:// address was redirected to https://

Conclusion:  

 [L,R=301] should be added to the "Force a redirect from HTTP to HTTPS" option

**Comment by johngodley** [comment]
Fixed in 67acfbe9abd478f4caacc819d47daf0cbc9b6f4f, released in the next version.

**Comment by johngodley** [comment]
You can try this in the 4.9 beta:

https://github.com/johngodley/redirection/releases/tag/4.9-beta

Let me know how it goes.

**Comment by zevrix** [comment]
Thanks for prompt fix!

I'll give it a try once the final release is out.
