### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by MilaFabio** [johngodley/redirection#2409]
```
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.3.20
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
JavaScript: /wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

Error:  Invalid nonce parameter in the cookie (rest_cookie_invalid_nonce)
```

**Comment by MilaFabio** [comment]
`You are not authorised to access this page.

This is usually fixed by doing one of these:

Reload the page - your current session is old.
Log out, clear your browser cache, and log in again - your browser has cached an old session.
Your admin pages are being cached. Clear this cache and try again.
The problem is almost certainly caused by one of the above.`
 **it didn't help**

**Comment by johngodley** [comment]
It is very likely the problem though. Your website is blocking access, and this is because something is being cached, or maybe because your REST API is redirecting.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
