### ISSUE TITLE
2.6.4 Does Not Redirect

### ISSUE THREAD

**Issue by aljohn4** [johngodley/redirection#241]
Options, 404s, Log won't load

**Comment by johngodley** [comment]
Can you provide more information?

What happens on those pages? Do you have any errors? What browser are you using? How does it not redirect?

**Comment by Kadjar2016** [comment]
I do not know if I can but I have the same problem using chrome

**Comment by Kadjar2016** [comment]
Also in section 404 if I try to delete entries it does not delete them

**Comment by johngodley** [comment]
@Kadjar2016 so you can load your 404 page? If so, are you having the same problem as reported here, or a different problem? If a different problem can you create a new issue?

**Comment by johngodley** [comment]
@Kadjar2016 the original report is that the 404 page doesn't load. You say your 404 page loads so it doesn't sound like the same problem? What do you mean by 'and how redirects work'?

**Comment by johngodley** [comment]
Closing for now. Please reopen if you have more information
