### ISSUE TITLE
After disabling a redirect, I can no longer select it to either re-enable it or delete it.

### ISSUE THREAD

**Issue by theheartypixel** [johngodley/redirection#2413]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

After disabling a redirect, I can no longer select it to either re-enable it or delete it. I recorded a short Loom video you can check out here: https://www.loom.com/share/f9aadac1ae384efd92f2032e13f81210

### Actual Behavior

Rolling over the disabled redirect doesn't show any options, and I'm unable to click on the checkbox next to it. I'm a WP admin, so I don't think it would be a user permissions error.

### Steps to reproduce

Disabled a redirect in order to test a page. Then wanted to delete the redirect and couldn't.

### Environment

Mac OS, Chrome Version 84.0.4147.105, WordPress 5.4.2, Redirection plugin Version 4.8

**Comment by johngodley** [comment]
Yes, this is intentional. People have a habit of not reading things, and they try and edit a disabled redirect and then contact me about why it's not working.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
