### ISSUE TITLE
Redirect Searches

### ISSUE THREAD

**Issue by PandaWhoCodes** [johngodley/redirection#2417]
To help track problems please follow this template. If you can provide screenshots then that will help.
Unable to redirect wordpress searches

Settings - URL only with Regex 
Source - \/?s=(.+)
Redirect = /search?q=$1

For some reason it is being redirected to - /?%2Fsearch%3Fq=test insread of /search?q=test

I am trying to redirect search queries from wordpress search to Google custom search page.
Currently using the latest chrome / wordpress and redirection plugin.

**Comment by johngodley** [comment]
You can use https://regex101.com to test your regular expression. A `?` character needs escaping if you want to match it
