### ISSUE TITLE
Simple User Question: How To redirect all paths typed as a URL that are not in the directory

### ISSUE THREAD

**Issue by MovingUp7** [johngodley/redirection#242]
Allow me to elaborate. Say my website has pages at ....com/home and ....com/about-us. If a visitor types ANYTHING other than those paths, I want them to be redirected to my home page and not land on any kind of error page. I've googled this for an hour and can not find a solution though it seems simple!

**Comment by YesThatAllen** [comment]
Let me know what you find, because my site behaves like this - every 404 lands at the homepage - and I'm not sure why. 🤔

**Comment by johngodley** [comment]
@MovingUp7 I don't recommend doing that and there is no feature in the plugin to do so. A 404 is the correct code to return to someone visiting a page that doesn't exist. If you redirect it to another page you are essentially saying that the page used to exist, and now lives somewhere else - this has a very different meaning and could dilute your search ranking. If you want a better 404 page then I suggest modifying your theme.

@YesThatAllen that sounds like a different problem
