### ISSUE TITLE
URL Tracking doesn't work properly when custom permalinks plugin is enabled

### ISSUE THREAD

**Issue by wnolfm** [johngodley/redirection#2420]
### Summary
When permalinks are changed while the custom permalinks plugin is active and URL monitoring is enabled on pages, a redirect is not created

### Actual Behavior

The redirect was not created when URL monitoring was enabled.

### Steps to reproduce

* Install https://wordpress.org/plugins/custom-permalinks/ 
* Ensure URL Monitoring is enabled for pages
* Create page
* Update Permalink of created page

### Environment

* Chrome Stable
* WordPress 5.5
* Redirection 4.8
* Custom Permalinks 1.6.2

**Comment by johngodley** [comment]
Redirection only monitors permalinks that change via the standard WordPress methods. If another plugin changes this then it is possible it wont be detected,

**Comment by wnolfm** [comment]
@johngodley I figured as much. I'll see if i can work something out.
