### ISSUE TITLE
New strict-origin-when-cross-origin policy on Chrome causing 403 on admin panel settings

### ISSUE THREAD

**Issue by ferares** [johngodley/redirection#2421]
We're having this pretty common issue but the cause might not be one of the common ones listed as possible solutions

When trying to access the plugin's settings we're getting the following message:

```
You are not authorised to access this page.
This is usually fixed by doing one of these:

Reload the page - your current session is old.
Log out, clear your browser cache, and log in again - your browser has cached an old session.
Your admin pages are being cached. Clear this cache and try again.
The problem is almost certainly caused by one of the above.
```

```
Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.3.21-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
JavaScript: https://[client's URL]/wp-content/plugins/redirection/redirection.js
REST API: https://[client's URL]/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

This is only happening to us on Chrome 84 or Edge 84

Taking a look into the network requests we saw that this GET request `https://[client's URL]/wp-json/redirection/v1/redirect/?orderby=id&_wpnonce=816d2fac75` returned a 403 and that its `Referrer Policy` was set to `strict-origin-when-cross-origin`

Looking into that we found that Chrome recently pushed to its stable version this change: https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default

To confirm that this was causing the issue we followed the instructions on that post to disable this new default setting:
[chrome://flags/#reduced-referrer-granularity](chrome://flags/#reduced-referrer-granularity) => Disabled
Doing this did indeed fix that 403 error and solved the issue we were having.

Please let us know if we can provide further information or help in solving this issue.

**Comment by johngodley** [comment]
This probably indicates that the domain you are using this on is changing in some way. This could be that the REST API is being redirected, or is on a different URL to the main site.

**Comment by ferares** [comment]
> This probably indicates that the domain you are using this on is changing in some way. This could be that the REST API is being redirected, or is on a different URL to the main site.

Thanks for the reply, it seems like the problem was with our cache server provider, thank you!
