### ISSUE TITLE
Server block should be optional in NGINX Output

### ISSUE THREAD

**Issue by aidik** [johngodley/redirection#2423]
Consider making the server block on lines [19](https://github.com/johngodley/redirection/blob/master/fileio/nginx.php#L19) and [30](https://github.com/johngodley/redirection/blob/master/fileio/nginx.php#L30) of the NGINX Output file optional.

It is very likely that if the output should be used it will be included into already existing server block.

Another option would be adding a filter. 

Thank you for considering my enhancement proposition.

**Comment by johngodley** [comment]
The output is designed to be a complete piece of Nginx code. It doesn't get automatically added anywhere, and if it doesn't suit your particular set up then you shouldn't copy/paste directly.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.

**Comment by aidik** [comment]
@johngodley Thank you for your response. I understand what you mean, but while the piece is syntactically correct I can't really imagine it being directly usable. That is the reason why I'm suggesting your plugin produces a raw list of rules which can be easily imported into existing Nginx config. So my suggestion can boil down to usability over formal correctness. 

Anyway using **`sed`** command after running `export all` with **`wp-cli`** is not a big deal.

Thank you again.
