### ISSUE TITLE
2.6.4 & 2.6.5 Menus Broken

### ISSUE THREAD

**Issue by sharifjameel** [johngodley/redirection#243]
After updating to 2.6.4 much seems to be broken - the primary menu links: Groups, Modules, Log, 404s all display nothing but the following:

> Sorry but something went wrong loading the data - please try again

> Loading chunk 0 failed.

I have this happening on 3 different sites all immediately after the 2.6.4 update. I waited for 2.6.5 assuming it would be fixed however it's not.

**Comment by johngodley** [comment]
Can you provide some details about your setup? For example, what browser are you using? What version of PHP?

**Comment by sharifjameel** [comment]
Now that you mention it, looks like it only happens when I'm administering the site using Safari. Chrome works just fine. I can live with that however in case you want to investigate further it's, Version 10.0.3 (11602.4.8.0.1) of Safari, PHP 5.6.30.

**Comment by johngodley** [comment]
Thanks! I'll check Safari and see what the problem is
