### ISSUE TITLE
Failed to import some Apache .htaccess rules

### ISSUE THREAD

**Issue by mcascardi** [johngodley/redirection#244]
Hi,

I work with a staging and production environment that is managed with the RAMP plugin by Crowd Favorite.  https://shop.crowdfavorite.com/ramp/docs/

To make the redirects able to be "Ramped" to production, they need to use the post type API so the data is stored in the posts and postmeta table so Ramp can find it and transfer it.  Can you update your plugin so that the redirection_items and redirection_groups are crated using a new post type and store the info in posts and post_meta?  Otherwise I will need to use the import feature to clear and re-import a new text file of redirects each time to be sure they are matching.  I have ~1500 redirects to import and manage from file already. They do not all import correctly now without modification to format them properly.

I think your plugin is solid enough to use in the production environment for a large site with constant traffic, but we must have compatibility with our ramp plugin.
Please let me know what you think about this task and the possibility of starting work on it?  Thank you.

**Comment by johngodley** [comment]
> Can you update your plugin so that the redirection_items and redirection_groups are crated using a new post type and store the info in posts and post_meta

That would involve a total rewrite of how Redirection works - sorry, I don't think I'll be doing that!

> They do not all import correctly now without modification to format them properly.

How don't they import correctly?

**Comment by mcascardi** [comment]
I have 2 files.  redirects.conf uses "Redirect" or "RedirectMatch" directive, this seems to import fine. rewrite.conf uses "RewriteRule" directives and on my first attempt it seemed like a lot of these did not import correctly but I will test again and look at the results more closely.

**Comment by mcascardi** [comment]
I thought I submitted a second issue but I don't see it now.  Would you be able to build an export/import feature that would dump all the current redirects (and associated groups) to CSV or XML that could then be imported to backup/restore all the redirects?  This will help my need to keep staging and production synced if we do not have compatibility with our Ramp plugin.

**Comment by mcascardi** [comment]
`Redirect permanent "/products/threat Emulation/Threat emulation.html" /products/threat-emulation-sandboxing/`

This line didn't import properly with the quoted string
![image](https://user-images.githubusercontent.com/282176/28290756-83d6e466-6afc-11e7-804b-a43f79912e4e.png)

A few other lines imported just "permanent", "/"

**Comment by mcascardi** [comment]
All the entries from rewrite.conf imported with the type "pass" and they do not redirect, but looks like the target URL is right.



![image](https://user-images.githubusercontent.com/282176/28291759-adb82b42-6b00-11e7-945d-6cbd00e28fb4.png)

Format:
`RewriteRule ^products/reporting /products/ [R,L]`

**Comment by johngodley** [comment]
Thanks, I've added tests for those specific lines in #290 - this will be included in the plugin soon
