### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by LucaSannadesign** [johngodley/redirection#2442]
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.21
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
JavaScript: https://www.lucasanna.eu/wp-content/plugins/redirection/redirection.js
REST API: https://www.lucasanna.eu/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions and look in your developer console. This is likely caused by another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
