### ISSUE TITLE
Redirect Error 404 to another page in Wordpress

### ISSUE THREAD

**Issue by aboooodaj** [johngodley/redirection#2443]
I'm trying to redirect Error 404 to a custom page, but this option doesn't exists in the Plugin.
How can I do it with this Plugin?

**Comment by johngodley** [comment]
Error 404 is to return a 404.

I don't advise you redirect all 404s. This can harm your site.

**Comment by aboooodaj** [comment]
Thank you
but I want to design a custom page for 404 page
What is the solution?

**Comment by johngodley** [comment]
You don't need a redirect for that. You need to edit your 404 page in your theme, or use a plugin that does that for you:

https://wordpress.org/plugins/404-page/

**Comment by aboooodaj** [comment]
Thank you 😀
