### ISSUE TITLE
Bypass on-board steps with default values

### ISSUE THREAD

**Issue by claytoncollie** [johngodley/redirection#2444]
I am using Composer to install this plugin from Wpackagist. I am wondering if there is a CLI command to run or a filter to use that bypasses the setup script after the installation and activation. Something on the lines as if I hit "yes" on every onboarding step. Create DB tables, create options, etc all with default values.

**Comment by johngodley** [comment]
Details here: https://redirection.me/developer/wp-cli/

**Comment by claytoncollie** [comment]
Thanks John. I was looking in there for a specific filter or specific command.

On further investigation, I think the command would be below. This removes the setup admin notice, installs DB tables, and adds basic settings to the options table.

```
wp redirection database install
```
