### ISSUE TITLE
Permissions: register capabilities for Members plugin

### ISSUE THREAD

**Issue by philipsteffan** [johngodley/redirection#2448]
I want to give different users/roles of my site the capabilities to add redirections. I have read your helpful [permissions documentation](https://redirection.me/developer/permissions/) on how to do that manually.

To map the roles and capabilities on my site, I use the popular "Members" plugin. It would be helpful if the redirection plugin registered its capabilities in the way [documented in the Members howto](https://github.com/caseproof/members/blob/master/readme.md#registering-capabilities) so that they appear in the Members UI.

**Comment by johngodley** [comment]
The plugin doesn't add any capabilities, so I'm not sure if there is anything needed for other capability plugins. The permissions documentation shows how you can change the default capabilities to suit your own site - it's not adding capabilities.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
