### ISSUE TITLE
REST API status good but REST API warning (without endpoint information)

### ISSUE THREAD

**Issue by kuzmandi** [johngodley/redirection#2450]
Hello there,

I've installed the Redirection plugin for a new WP installation and got the strange state that a REST API problem is displayed, but without having locked anything on the REST API. I also don't use any of the suspicious plugins that could influence it. In addition, the error message does not list any REST API endpoints, so I could manually try whether they work or not. What can I do?

<img width="1521" alt="error" src="https://user-images.githubusercontent.com/28785168/92867128-937f6b00-f400-11ea-8221-df685e106350.png">

**Comment by johngodley** [comment]
Sorry, I don't know what the message says, and I can't copy and paste it into Google Translate from a screenshot.

**Comment by kuzmandi** [comment]
Sorry for that. Translation is this:

"One or more WordPress plugins tried to call the WordPress REST API, which failed. Most likely a security plugin or a web server configuration has deactivated the REST API. Please ensure that the following REST API namespaces are accessible in order to be able to use the respective plugin without problems:

What is the WordPress REST API and how can it be activated? Click here to learn more about it."

(note that the area in which the endpoints should be listed is empty.)

Additional info: I have also deactivated unsuspicious plugins for testing purposes and. also changed the template. Without change. It would be helpful if I knew the endpoints that are queried here, but unfortunately none are displayed.

**Comment by johngodley** [comment]
I don't think that message is shown by Redirection.

**Comment by kuzmandi** [comment]
I've already suspected something like that. But it's strange. The cause seems to be a REST API call through Redirection. If Redirection is satisfied and everything is green, why is Wordpress complaining?

**Comment by kuzmandi** [comment]
I think I've found the cause: it appears to be from Real Media Library. I have no idea why this message appears on the Redirection page and what it means.

**Comment by johngodley** [comment]
Ok. Some plugins have a habit of running on pages where they shouldn't, and this looks like a false positive.

**Comment by kuzmandi** [comment]
I opened a support ticket at the plugin page and guess the problem will be fixed. Thank you!
