### ISSUE TITLE
`.hidden` notices are always visible

### ISSUE THREAD

**Issue by matzeeable** [johngodley/redirection#2454]
## Summary

Your implementation to always show notices also shows notices from other plugins.

https://github.com/johngodley/redirection/blob/d503568e9f44a2c39771bb373cf33bcc14e72c5c/client/page/home/style.scss#L114-L117

![image](https://user-images.githubusercontent.com/1008534/93073958-f9c7f000-f683-11ea-8495-f79c7cb8b812.png)

### Actual Behavior

All notices (also hidden) from other vendors are always visible.

### Steps to reproduce

- Install https://wordpress.org/plugins/real-media-library-lite/
- Navigate to your Redirection plugin

Real Media Library shows a notice for failing WP REST API requests (using the WP Core class `.hidden`).

### Proposal

First proposal, do not force showing notices with explicit `.hidden` class.

```diff
/* Some plugins hide .notice - ensure our stuff always shows */
- .notice {
+ .notice:not(.hidden)
	display: block !important;
}
```

Second proposal, only apply this CSS rule to your known notices.

### Environment

Not relevant.

**Comment by johngodley** [comment]
Interesting. The plugin forces the notices because some other plugins inject CSS onto the page that hides them. I'll have a think about this some more

**Comment by matzeeable** [comment]
Hi again and thanks for your reply.

Yeah, I am the developer of Real Media Library and I need to always render the notice, but hidden so our "Corrupt REST API" detector can show that notice. I think the best solution is to go with the above CSS selector. I have started a PR for this.

Regards,
Matthew :-)
