### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by yshanthipriya** [johngodley/redirection#2458]
Hello Team,

We are trying to update Redirection plugin to latest version, we are getting below issue. Can you please help us to fix this?

Plugin: 4.8
WordPress: 5.4.1 (single)
PHP: 7.3.19
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
JavaScript: https://qa.arre.co.in/wp-content/plugins/redirection/redirection.js
REST API: https://qa.arre.co.in/wp-json/

Error: Cookie nonce is invalid (rest_cookie_invalid_nonce)
Action: redirection/v1/plugin/database/ POST
Params: {}
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"Cookie nonce is invalid","data":{"status":403}}
```

**Comment by johngodley** [comment]
Please follow the onscreen instructions and log out, clear your cache, and log in again

**Comment by yshanthipriya** [comment]
Hello

We have followed all steps as given on screen but still we are facing issue.

**Comment by johngodley** [comment]
Your site is cached, including the REST API. The REST API should never be cached. You will need to clear all caches, and ensure that the REST API is not cached.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
