### ISSUE TITLE
Can your plugin setup batch redirections?

### ISSUE THREAD

**Issue by adrimaximus** [johngodley/redirection#2460]
Hi, 

I want to ask you about plugin capability. Can it redirect pages globally? I mean automatically create redirection from product page to post page. Here is the case:

- My website: anoas.id using listeo pro theme. This theme is a listing theme. When we create a new listing page (custom post page with booking feature), then, automatically, woocommerce also create a new product page listing booking.
- When we visit shop page, we find a new product page (type: listing booking, category product: listeo booking), but we can't at to cart to buy it. The system made it. We just can book it on the listing page.
- I don't need the product listeo booking single page, but I can't delete it, because it connected with woocommerce for payment system for listing booking.
- I want to use the listeo booking product so that can be filtered on shop page (so people can find a product either via shop page or directory listing page). How do I use it, by redirecting 'listeo booking product' to 'listing booking page'. So when people click 'listeo booking product' they don't open the single product page, but they directly go to 'listing booking page'

The following link https://anoas.id/estore/ella-yullya-furnama/ we don't use redirection. as we see:
1. we go to product listeo booking single page
2. we can't add to cart or do buying action

I use redirection plugin for following link: https://anoas.id/estore/dewisalju-com-3/
It goes to https://anoas.id/provider/

I need some configuration so that listeo booking products like https://anoas.id/estore/ella-yullya-furnama/ can directly go to listing pages https://anoas.id/provider/ same as redirection does but it is done globally for typical listeo product pages. 

Is it possible?

Regards
Adri

**Comment by johngodley** [comment]
That's a lot of very specific information that I don't really understand and it's a little bit beyond what I can reasonably give feedback on.

You will need to investigate further yourself. You may be able to use a regular expression:

https://redirection.me/support/redirect-regular-expressions/

Or you may be able to use the developer information:

http://redirection.me/developer/

**Comment by adrimaximus** [comment]
Hi John,

I think regex function is near with what I mean. But there is a condition, not all product on shop page are made to be redirected. But only products on listeo product category which I want to be redirected. 

Is it possible to be done?

**Comment by johngodley** [comment]
Again, I can't really say - your requirements are very specific. The information about what the plugin can do is available, and you will need to decide if it suits your purpose.

**Comment by adrimaximus** [comment]
Okay. Thank you for your information. 

Have a good day 👍
