### ISSUE TITLE
URL search doesn't work for hostname

### ISSUE THREAD

**Issue by LizLord** [johngodley/redirection#2468]
### Summary

Search within the Redirection plugin doesn't match when using the Search URL function to match to text in the hostname. Why won't you let me search by hostname?

### Actual Behavior

Uploaded 185 URLs with the domain operationhomefront.wordpress.com in error. Would like to find all 185 error URLs among 300 URLs with different/correct hostname `operationhomefront.org` and delete by searching for `wordpress` in the URL field to match to operationhomefront.**wordpress**.com  Search returns 0 results.

### Steps to reproduce
Search for text in hostname of URL

### Environment

Chrome Version 85.0.4183.102
WordPress Version 5.4.2
Redirection Version 4.8

### Screenshots
operationhomefront.wordpress.com URLs
![image](https://user-images.githubusercontent.com/16021927/94465198-88ad3000-018d-11eb-9fb9-ee5f23ac3297.png)
Search for `word` in URL only returns results where the match occurs in the URI
![image](https://user-images.githubusercontent.com/16021927/94465267-a2e70e00-018d-11eb-9d40-5a25a1b9b67d.png)
Search for `wordpress` in URL
![image](https://user-images.githubusercontent.com/16021927/94465308-b2feed80-018d-11eb-84b1-38ef4f7d68c0.png)

**Comment by johngodley** [comment]
Sorry, searching by domain name is not supported, and is not easily added.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
