### ISSUE TITLE
Redirection is not working

### ISSUE THREAD

**Issue by proszynskamagda** [johngodley/redirection#2469]
I started working with the plug and this is the first message that met me.
I cleared the cache.

Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.2.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
JavaScript: https://proszynskamagda.com/wp-content/plugins/redirection/redirection.js
REST API: https://proszynskamagda.com/wp-json/
Buster: 4.8 === 4.8

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in span
    in div
    in div
    in div
    in a
    in p
    in div
    in div
    in a
    in p
    in a
    in p
    in StrictMode
    in G
    in Kb

**Comment by johngodley** [comment]
Does this always happen?

**Comment by johngodley** [comment]
See #2487
