### ISSUE TITLE
Need redirection with single redirection rule 

### ISSUE THREAD

**Issue by zonalteam** [johngodley/redirection#2471]
Hi Team,

Hi My website is a forum based on zenforo ,It was running previously on abc.com , now i moved it to abc.com/community
and installed WordPress on abc.com, now all the URLs are broken now which was linked to old path i.e **abc.com/threads-abc-xyz-rts-mmm-ppp**. If I use /community for all broken URL's it works. But i don't know how to redirect all to that specific path.

 **abc.com/community/threads-abc-xyz-rts-mmm-ppp**

Only i want to add the prefix **community/** on every path.

old was  abc.com/threads-abc-xyz-rts-mmm-ppp
new I want is  abc.com/community/threads-abc-xyz-rts-mmm-ppp

i don't know if i am able to make you understand, what all I need.

I don't have any skills in coding ,I just came to know with my friends , that Github will solve my query , then i saw this plugin and installed on my WordPress.

Please help...

**Comment by johngodley** [comment]
You can use a regular expression for this kind of thing:

https://redirection.me/support/redirect-regular-expressions/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
