### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by leecollings** [johngodley/redirection#2476]
Note: This is a website taken from online and set up as a local vhost in WAMP (hence the nirvanalight.local hostname). The REST API is working as I can access it locally in a browser.

Please advise as I need to create entries in my local development machine and then re-upload to our staging environment.

Many thanks.

```
Uncaught SyntaxError: Invalid or unexpected token http://nirvanalight.local/wp-content/plugins/redirection/redirection.js?ver=4.8-7acce5951ed37d0a438ffb92e849136e 33
```

Plugin: 4.8
WordPress: 5.4.2 (single)
PHP: 7.4.9
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
JavaScript: http://nirvanalight.local/wp-content/plugins/redirection/redirection.js
REST API: http://nirvanalight.local/wp-json/

**Comment by johngodley** [comment]
Being able to access it from your browser doesn't necessarily mean it is working, just that you can access it from your browser. However, I don't think that is the issue here anyway. It looks more like the redirection.js file is corrupted - maybe it wasn't downloaded properly?

**Comment by leecollings** [comment]
Thanks for the reply, understand where you're coming from. How can I generate a clean version of this? I've tried clearing the browser cache, and also disablign the plugin and re-enabling. Next step would be to completely remove it and install it again. Just wondering if you have any other suggestions aside from the basics?

**Comment by leecollings** [comment]
All fixed and working, sorry for wasting your time, but thanks for replying!
