### ISSUE TITLE
Position is not visible, cannot be maintained. Solutions provided.

### ISSUE THREAD

**Issue by TonyGravagno** [johngodley/redirection#248]
The order in which redirections are processed is not obvious, and that order cannot easily be changed. I've mad enhancements to allow the Position field to be seen and modified in the admin UI. Ref pull request #247.

**Comment by johngodley** [comment]
Thanks Tony. Just a warning that the UI is undergoing major work, and most of this code will soon be no longer applicable. However, one of the reasons for the work is so I can bring back an old feature which was drag-and-drop ordering. The UI changes will be coming very soon, and the reordering should be sometime after.

I appreciate the work you've done here though!

**Comment by TonyGravagno** [comment]
No prob. Given the realities of time limitations if you think you might be more than a month or two off from the next major release, what do you think about me moving forward with a couple of these small patches to the 2.6 series? People are concerned about deleting logs, re-ordering, and a few other things that I can probably address until a QA'd 2.7 or 3.0 is ready for production. Thanks for the cordial exchanges.

**Comment by johngodley** [comment]
The major UI changes are already in, and I've added a position field. This won't necessarily stay as-is in the future, but is a stop-gap measure until I sort out some subtle problems with how ordering works. See #268. The UI changes will go out in 2.6.6, and ordering in 2.7
