### ISSUE TITLE
Deleting 404 log lines

### ISSUE THREAD

**Issue by yulumadeploy** [johngodley/redirection#2480]
### Summary

I am trying to delete 404 logs in 2 ways
Way 1: By selecting multipe and select bulk action delete
Way 2: By selecting 1 and select bulk action ignore URL, check delete logs and choose redirect to 404

### Actual Behavior

Way 1: Nothing happens
Way 2: The amount field gets resetted in all entries of the search result.

### Steps to reproduce

How to reproduce: https://www.youtube.com/watch?v=e5uUQTBjOAA

### Environment

Chrome version 85.0.4183.121
WP version 5.3.4
Redirection version 4.9-beta-2

Could you help us?

**Comment by johngodley** [comment]
Can you try beta 5 instead?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
