### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by serg-odessa** [johngodley/redirection#2481]
Hi there,
The plugin stopped working in my website.
Whenever I try to edit a redirecton rule it says:
"Something went wrong 🙁
No route was found matching the URL and request method (rest_no_route)

Your REST API is returning a 404 page. "

Could you help me with that?

Serge

```
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.19-1~deb10u1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
JavaScript: https://nektony.com/wp-content/plugins/redirection/redirection.js
REST API: https://nektony.com/wp-json/

Error: No route was found matching the URL and request method (rest_no_route)
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment]
Your WordPress REST API is likely being blocked by a security plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
