### ISSUE TITLE
Redirection error

### ISSUE THREAD

**Issue by Soullighter** [johngodley/redirection#2487]
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
JavaScript: https://www.turner.nl/wp-content/plugins/redirection/redirection.js
REST API: https://www.turner.nl/wp-json/
Buster: 4.8 === 4.8

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in div
    in a
    in p
    in a
    in p
    in StrictMode
    in G
    in Kb

**Comment by johngodley** [comment]
Are you using any browser extensions? Maybe to do with translation?

**Comment by Soullighter** [comment]
I was using just Default browser translation in Chrome

**Comment by johngodley** [comment]
So you are translating the page and modifying the contents?

**Comment by Soullighter** [comment]
I just right click on page and translate to English, there is no additional functionality that i use.
https://ibb.co/6R7qR95

**Comment by johngodley** [comment]
Ok. Does the error occur if you don't translate?

**Comment by Soullighter** [comment]
No. Everything is fine if i don’t translate

**Comment by johngodley** [comment]
Right, I'm afraid you'll have to not use that translate tool with Redirection. It seems to cause problems with React by changing the page. Redirection uses React.

You can change your user account setting to English, for example, and that should work fine.

**Comment by Soullighter** [comment]
When i turn back to original language, redirection was working, so that is
a solution also ;)
