### ISSUE TITLE
John - from Steve (much appreciated)

### ISSUE THREAD

**Issue by SteveA8888** [johngodley/redirection#2491]
John, my site is https://WalkTheRidge.com - it was formerly .org, and now I have the .org and .net variants forwarding the .com.

The issue is I have page that doesn't seem to want to redirect. An old homepage here:
https://walktheridge.com/home01042019/

I want to redirect here:
https://walktheridge.com

Just not taking for some reason. I have tried it with the ignore slash checked and unchecked. 

Thoughts appreciated
Steve

**Comment by johngodley** [comment]
The page is being redirected:

https://redirect.li/http/?url=https%3A%2F%2Fwalktheridge.com%2Fhome01042019%2F

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
