### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by MichelaGenoni** [johngodley/redirection#2493]
```
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.2.28
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
JavaScript: https://avocadomallorca.com/wp-content/plugins/redirection/redirection.js
REST API: https://avocadomallorca.com/wp-json/

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Action: redirection/v1/group/ GET
Code: 404 Not Found
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /wp-json/redirection/v1/group/ was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

```

WHEN  FIRST INSTALLED THE PLUG IN THE FIRST 2 BLOCK  WERE TICKED AS WORKING. THEN I CHANGED THE PERMALINKS, SINCE THEN THE PLUG IN STARTED SHOWING 2 PROBLEMS RATHER THAN ONE 
![ERROR 1](https://user-images.githubusercontent.com/73140712/96512032-33ca7a00-1260-11eb-8114-72f3dd19e763.PNG)
![ERROR 2](https://user-images.githubusercontent.com/73140712/96512036-34631080-1260-11eb-81ce-922badaabaa6.PNG)

**Comment by johngodley** [comment]
As the errors indicate, your REST API is returning a 404:

https://avocadomallorca.com/wp-json/

You will need to fix whatever is causing that.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
