### ISSUE TITLE
Redirection is not working

### ISSUE THREAD

**Issue by alzaabi1234** [johngodley/redirection#2494]
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
JavaScript: https://azmods.co/wp-content/plugins/redirection/redirection.js
REST API: https://azmods.co/wp-json/
Buster: 4.8 === 4.8

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in div
    in a
    in p
    in a
    in p
    in StrictMode
    in G
    in Kb

**Comment by johngodley** [comment]
Are you running any browser extensions? Maybe a translation one?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
