### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by m0rtione** [johngodley/redirection#2496]
```
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.4.10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
JavaScript: https://www.riegelprofi.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.riegelprofi.com/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/plugin/ GET
Code: 404 Not Found
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>

```

Hello,
after updating the Plugin i receive this error and none of my redirections (aff-links) are working anymore. Can u please tell me how to fix that?
kind regards

**Comment by johngodley** [comment]
This is not affecting your existing redirects, and is unconnected with updating the plugin. Your REST API is broken:

https://www.riegelprofi.com/wp-json/

You will need to fix that.

**Comment by m0rtione** [comment]
Hey johngodley,

there must be a connection, because i did nothing more than updating "redirection".

But... i found this: https://mfcoding.wordpress.com/2020/01/31/wordpress-rest-api-404-error/

It worked for me, even though i sometimes get "service not available" messages on Dashboard pages until i reload them, but the plugin/links are working again. 

cheers

**Comment by johngodley** [comment]
I would imagine the connection is something to do with a site cache, and updating the plugin caused it to be invalidated. There is nothing in the plugin that could affect your site in such a way.

Thanks for the tip about permalinks. That's useful for anyone else who has the same problem.
