### ISSUE TITLE
Problem starting Redirection 4.8

### ISSUE THREAD

**Issue by ahmadraza6** [johngodley/redirection#2497]
Plugin: 4.8
WordPress: 5.5.1 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
JavaScript: https://wpsites.6flicks.com/wp-content/plugins/redirection/redirection.js
REST API: https://6flicks.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin.

Also, you have two different site URLs - wpsites.6flicks.com and 6flicks.com. They should be the same

**Comment by ahmadraza6** [comment]
thanks for reply
