### ISSUE TITLE
White site home site

### ISSUE THREAD

**Issue by saso94** [johngodley/redirection#250]
You do not see anything on my home page, I've updated the plugin but nothing. I hope this issue is resolved soon because this plugin has helped me a lot

**Comment by johngodley** [comment]
Can you provide more details?

Have you tried disabling the plugin?

Do you have any errors in your server error log?

**Comment by saso94** [comment]
I've disabled all plugins, tried to reactivate them one by one, as soon as I reactivated redirection I updated the home page and was completely white. I'll look for more information about it, also because it does not conflict with other plugins. I will do another test by disabling everything and only activating redirection

**Comment by saso94** [comment]
I did more tests. I disable all plugins except wp statistics, wordpress ping optimizer and redirection. Activating in a certain sequence all the plugins, gave me a white page with several plugins including jetpack, dfactory coockie notice, better stop adblock, but activating them in a certain sequence the error is gone. The page is visible and I do not know where this error comes from. I will try to activate the log and give you more info

**Comment by saso94** [comment]
With all plugins activated and a couple of page recharges nothing happens, everything works. If the problem comes back, I will write again. thanks for the support
