### ISSUE TITLE
Time no longer shows in date column

### ISSUE THREAD

**Issue by matheuscfernandes** [johngodley/redirection#2500]
Thank you so much for this awesome release. Everything is working great for me, except for the following: 

The date column of logs and 404s does not show the time stamp. This used to be a feature but it is no longer working.

Thanks,
Matt

**Comment by johngodley** [comment]
I'm not seeing any problems with the time stamp, and nothing has changed with regard to that piece of data. Is this a new install or an upgraded one?

**Comment by matheuscfernandes** [comment]
This is an upgrade. I reverted my installation back to 4.8, but when I update to 4.9 the date shows but the time stamp no longer shows.  The screenshot attached shows what it looks like in 4.8. The 4.9 version gets rid of the line that says 8:33 pm, 7:34 PM etc. Thanks!
![Screen Shot 2020-10-25 at 10 00 04 AM](https://user-images.githubusercontent.com/8809429/97110754-fa9f6900-16a8-11eb-95ba-b5a0bd9999e8.png)

**Comment by johngodley** [comment]
Oh ok, the time itself is missing. I thought you meant there was no information at all.

**Comment by matheuscfernandes** [comment]
Sorry about my unclarity. Thank you so much for looking into this.

**Comment by johngodley** [comment]
This should be fixed in 4.9.1

**Comment by matheuscfernandes** [comment]
Thank you! Works like a charm. :)
