### ISSUE TITLE
404 errors grouping and ordering by count fails.

### ISSUE THREAD

**Issue by thelevicole** [johngodley/redirection#2506]
When I try to group 404 errors by either URL or user agenct and then clicking the Count column to order my results I get the following...

> Bad data
> 
> There was a problem making a request to your site. This could indicate you provided data that did not match requirements, or that the plugin sent a bad request.
> 
> Please review your data and try again.

**Debug log**

```
Action: https://mysite.com/wp-json/redirection/v1/404/?orderby=count&groupBy=url&per_page=100 GET
Code: 400 Bad Request

Error: Invalid parameter(s): orderby (rest_invalid_param)
Raw: {"code":"rest_invalid_param","message":"Invalid parameter(s): orderby","data":{"status":400,"params":{"orderby":"orderby is not one of url, ip, total, ."}}}
```

**Comment by johngodley** [comment]
This should be fixed in 4.9.1
