### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Alb-a** [johngodley/redirection#2511]
Plugin: 4.9
WordPress: 5.5.1 (single)
PHP: 7.3.21
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
JavaScript: https://frimaq.com/wp-content/plugins/redirection/redirection.js?ver=4.9-2dd41d397208f86537f3e2656caeb502
REST API: https://frimaq.com/wp-json/
Query: ?page=redirection.php

Error: REST API desactivada (rest_disabled)
Raw: {"code":"rest_disabled","message":"REST API desactivada","data":{"status":403}}

**Comment by johngodley** [comment]
As the message states, your REST API is disabled. You will need to enable it.
