### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by rhw2008** [johngodley/redirection#2512]
```
Plugin: 4.9
WordPress: 5.5.1 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
JavaScript: https://www.xxxx.com/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10
REST API: https://www.xxx.com/wp-json/
Query: ?page=redirection.php

Action: https://www.xxxx.com/wp-json/redirection/v1/plugin/database/ POST
Params: {"upgrade":"skip"}
Code: 404 Not Found

Error: No route was found matching the URL and request (rest_no_route)
Raw: {"code":"rest_no_route","message":"Aucun itin\u00e9raire n\u2019a \u00e9t\u00e9 trouv\u00e9 correspondant \u00e0 l\u2019URL et \u00e0 la m\u00e9thode de requ\u00eate","data":{"status":404}}
```

**Comment by johngodley** [comment]
This may be caused by a security plugin. You could also try re-saving your permalink settings.

**Comment by rhw2008** [comment]
thank you so much for your quick response, really appreciated. Actually, I re-saved the permalinks and did not work. I'm using WordFence as a security plugin. Should I disable it 
thanks a lot

**Comment by johngodley** [comment]
I can't really say, but it's worth trying.

**Comment by rhw2008** [comment]
I have deactivated WF as well as the redirection option of RankMath but still not working :(

**Comment by johngodley** [comment]
Maybe you need to clear your browser and site caches?

Basically this is specific to your site and something is returning a 404 error on your WordPress REST API. Redirection uses this to upgrade the database, and the error stops it functioning.

You can try using your Site Health option and see if more details are shown.

**Comment by rhw2008** [comment]
I did but without any success.. I think I have to move all the redirection to RankMath instead :(

**Comment by johngodley** [comment]
Ok, well that's an unfortunate choice and there are many better.

If you are ok sending a login to your site then I can take a look and see if anything stands out.

https://redirection.me/contact/

**Comment by rhw2008** [comment]
Hello John, 

Did you get my last email with credentials to access our website ?

 

Thanks 

 

 

Équipe TopHebergeur.com

 

 <http://www.tophebergeur.com/> www.tophebergeur.com

**Comment by johngodley** [comment]
I did not, and I don't see anything in spam either.

**Comment by rhw2008** [comment]
I have used the contact form you’ve send me. Can you please send me your email so I can resend you the credentials 

 

Thank you so very much 

 

 

Équipe TopHebergeur.com

 

 <http://www.tophebergeur.com/> www.tophebergeur.com

**Comment by johngodley** [comment]
The contact form has it's own spam queue, and I found it there

**Comment by rhw2008** [comment]
Ok thanks  a lot 

 

 

Équipe TopHebergeur.com

 

 <http://www.tophebergeur.com/> www.tophebergeur.com

**Comment by johngodley** [comment]
After some investigation it turns out that there was a .htaccess redirect rule to remove trailing slashes:

```
# BEGIN Remove Slash from url
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)/$ /$1 [R=301,L]
# END Remove Slash from url
```

This was breaking POST requests.

Changing this to exclude POST requests and the REST API makes it work:
```
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{REQUEST_URI} !^/wp-json/.*
RewriteRule ^(.*)/$ /$1 [R=301,L]
```
