### ISSUE TITLE
Strict Standards: Static function Red_Log::get_table_name() should not be abstract in

### ISSUE THREAD

**Issue by zerotransform** [johngodley/redirection#2515]
This is now showing up on my site after the 4.9 update.  4.9.1 too.  I'm noticing this on many sites

Strict Standards: Static function Red_Log::get_table_name() should not be abstract in /wp-content/plugins/redirection/models/log/log.php on line 118

Strict Standards: Static function Red_Log::get_csv_filename() should not be abstract in /wp-content/plugins/redirection/models/log/log.php on line 445

Strict Standards: Static function Red_Log::get_csv_header() should not be abstract in /wp-content/plugins/redirection/models/log/log.php on line 452

Strict Standards: Static function Red_Log::get_csv_row() should not be abstract in /wp-content/plugins/redirection/models/log/log.php on line 460

Is there any way to revert to 4.8?

**Comment by johngodley** [comment]
You can ignore the messages until I have chance to look into them - it won't affect your site.

**Comment by zerotransform** [comment]
This message is showing at the top of all of my pages.  I'm having to
disable the plugin until I can find a way to hide it.

**Comment by johngodley** [comment]
You should disable errors from appearing on your site as they can reveal sensitive information:

https://codex.wordpress.org/WP_DEBUG

**Comment by johngodley** [comment]
Also, previous versions can be found here: https://wordpress.org/plugins/redirection/advanced/

**Comment by johngodley** [comment]
What version of PHP are you using?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
