### ISSUE TITLE
Redirection not working for same directory folder

### ISSUE THREAD

**Issue by cervinmedia** [johngodley/redirection#252]
Hi there.

We have a directory that follows the URL /directory/listing/URI

I added a couple of redirections for pages that are on the same directory, like:

source: /directory/listing/URI
action: /directory/listing/URI2
301

The page is not redirected, there is no record on the log of 404 (although it displays a 404 error page). There is no record on the redirect log either.

I can't identify why it is not working only for this specific scenario (it works fine for other pages).

Any suggestions?

Thanks,
Mariana

**Comment by johngodley** [comment]
Do you have something outside of WordPress that may be intercepting the request? For example, maybe you have an Apache .htaccess file that is handling it

**Comment by johngodley** [comment]
Closing for now but please reopen if you have more details
