### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by vamsitallapudi** [johngodley/redirection#2528]
```
Plugin: 4.9
WordPress: 5.5.1 (multi)
PHP: 7.3.18
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
JavaScript: https://www.coderefer.com/wp-content/plugins/redirection/redirection.js?ver=4.9-c383de96c0b7e38459253ead4f6e9b10
REST API: https://www.coderefer.com/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect details (redirect_update_failed)
Raw: {"code":"redirect_update_failed","message":"Invalid redirect details","data":{"status":400,"error_code":323}}
```

**Comment by johngodley** [comment]
What are you doing when this happens?

**Comment by vamsitallapudi** [comment]
I am just trying to add a new redirect.

**Comment by johngodley** [comment]
Can you include a screenshot of the redirect you are trying to add?

**Comment by vamsitallapudi** [comment]
Hi John, here is the screenshot:
<img width="1253" alt="Screenshot 2020-10-29 at 9 41 08 PM" src="https://user-images.githubusercontent.com/20869935/97600853-84479180-1a2f-11eb-8aa6-f7ee08f39cf3.png">

**Comment by vamsitallapudi** [comment]
Hi John, my issue is - I want to redirect all urls other than home page. My website is coderefer.com. I want to move all the content to subdirectory. For that I used the redirect and following is my regex pattern:
<img width="1123" alt="Screenshot 2020-10-30 at 9 16 20 AM" src="https://user-images.githubusercontent.com/20869935/97657734-9dccf580-1a90-11eb-8bbb-a043f6416e68.png">
But now home page is also redirecting to coderefer.com/blog. I don't want to redirect home page. Is there anyway I can achieve that?

**Comment by vamsitallapudi** [comment]
I figured out using + instead of * will serve my purpose. I modified my regex code as ^\/(.+)$. John, is that fine or is there any other way to do it?

**Comment by johngodley** [comment]
Sure, if it works then it's fine

**Comment by vamsitallapudi** [comment]
Thanks for your help John. The original issue was caused due to some cache plugin while I am trying to create same redirect over and over. I disabled the plugin temporarily to make it work. Now everything is working fine as expected with the help of your plugin.
