### ISSUE TITLE
Automatic 301 Redirection Not Working on Posts - Posts

### ISSUE THREAD

**Issue by katteyspares** [johngodley/redirection#253]
Feature “automatically add redirection if post URL changes” is not working in my case on posts also. I know it will not work on pages but in my case not working on posts.

When ever i change the post URL, automatic redirection is not working and i need to add redirection manually in order to make the URL work........Its a wordpress default feature that if you modify slug then 301 redirection will work automatically but after installing redirection its not working with my case.

Using: WP 4.8 , PHP 7.0.21, MySQL 5.6.35, Theme- Newspaper 8

Note: And when i turned off redirection plugin, the changed URL slug redirect normally..I need redirection plugin to find 404 and to redirect them through redirection plugin but plugin stop normal wordpress redirection. I can deactivate the plugin to normal WP redirection works but then it will stop other redirection. So please advice what to do?

**Comment by johngodley** [comment]
Can you give some specific details, maybe with screenshots? What does 'find 404 and redirect them' mean?

**Comment by katteyspares** [comment]
Point 1: More Details with Screen shot

Original Post link is this :  [http://lethow.com/home-remedies/avoid-bed-bugs/](url)
See Screen Shot: [https://ibb.co/iD4ppk](url)

I want to change the link since google is ranking this article for some other keyword, so we decide to change the slug of post and new post link become this:

New Post Link: [http://lethow.com/home-remedies/what-do-bed-bugs-look-like/](url)
See Screen Shot: [https://ibb.co/hkB8h5](url)

Now if i change the slug so either wordpress or redirection plugin automatically do the job and create a 301 redirect automatically but its is not happening and to make a redirect work from old to new post link we need to enter it manually in redirection plugin.

This time we are not enter it manually so that you can check and we already share the details of hosting environment with you and after deactivating redirection plugin automatically this link will redirect to new link without doing anything. Please check the same at your end or please ask if more details required.

Point No 2:  What does 'find 404 and redirect them' mean?

We need redirection plugin to keep on finding 404 error URL for us and if we think that they are relevant, so we can redirect them to correct URL. For example we got so many link where third party website enter some link to our website for reference and in last they are broken or they enter incorrect link......instead of telling them to correct the link we redirect the broken link to correct article on our website.

**Comment by johngodley** [comment]
Can you confirm that you have the Redirection settings enabled for monitoring post changes?

**Comment by katteyspares** [comment]
Its set to don't monitor and now i set to modified posts and now its working...

In default setting it should be to "modified posts". Sorry for trouble form my side.
