### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by rlilova** [johngodley/redirection#2533]
To help track problems please follow this template. If you can provide screenshots then that will help.

Hi John,

I just installed the Redirection plugin this morning.

I am just trying to add a my first redirection.

### Actual Behavior

The error message on Firefox, Chrome 

"The page is not redirected correctly

An error occurred while connecting to www.institut-g4.fr.

    The cause of this problem may be the deactivation or refusal of cookies."

### Steps to reproduce

I'm trying de redirect this URL https://www.institut-g4.fr/2020/04/01/inscription-a-la-journee-portes-ouvertes-virtuelle/ on this one : https://www.institut-g4.fr/inscription-a-la-journee-portes-ouvertes-virtuelle/

### Environment

FIREFOX Version 81.0.2 (64 bits) , version of WordPress : 5.5.2 and Redirection plugin : Version : 4.9.1.
But i'm also using Chrome at the same time Version 86.0.4240.111 (Build officiel) (64 bits)
But this task was maked on Firefox
![error redirection](https://user-images.githubusercontent.com/73696169/97697656-97964380-1aa7-11eb-8f70-bb700c7e6f68.JPG)
![redirection](https://user-images.githubusercontent.com/73696169/97697753-bd234d00-1aa7-11eb-89e3-9fe09d9c1258.JPG)

**Comment by johngodley** [comment]
https://www.institut-g4.fr/inscription-a-la-journee-portes-ouvertes-virtuelle/ redirects to https://www.institut-g4.fr/2020/04/01/inscription-a-la-journee-portes-ouvertes-virtuelle/ and you have created an infinite redirect.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
