### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by gtalev-bianor** [johngodley/redirection#2534]
```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.2.32
Browser: Amazon CloudFront
JavaScript: https://www.bianor.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.bianor.com/wp-json/
Query: ?page=redirection.php

Error: REST API forbidden. (rest_forbidden)
Raw: {"code":"rest_forbidden","message":"REST API forbidden.","data":{"status":403}}
```

**Comment by johngodley** [comment]
As shown in the message, your REST API is blocked:

https://www.bianor.com/wp-json/

**Comment by gtalev-bianor** [comment]
Thanks, and in my case, it was due to functions.php of a Divi theme in
combination with the Soil plugin, which disabled the rest-api....

Bianor <http://www.bianor.com/> | Georgi Talev | CTО | +359-2-4604200
Connect to us on LinkedIn <http://www.linkedin.com/companies/bianor>.
Got a few minutes? Get to know us better. <https://www.bianor.com>
