### ISSUE TITLE
Export options hidden until mouseover.

### ISSUE THREAD

**Issue by TonyGravagno** [johngodley/redirection#254]
Go to the Modules tab. Mouse-over each module for options. The WordPress module will show export in formats RSS, CSV, Apache, and Nginx.

I consider it a bug that the options are not immediately visible. We shouldn't need to mouse-over an area to find hidden options. I'm guessing that UX wasn't intentional.

**Comment by johngodley** [comment]
It was intentional and isn't a bug - it works like the options in other parts of WP, such as editing a post

**Comment by johngodley** [comment]
Note that I'm not against improving it

**Comment by TonyGravagno** [comment]
I must disagree with the premise. Import is clearly visible, Export is not. Someone else asked about this in the Support forum, I couldn't find any info, needed to look at code to find that the UI was hiding the feature. I'm all for closing containers like metaboxes that aren't currently used. That unclutters the UI without making the user what happened to the feature. Similarly, in the Customizer we only see theme features that apply to specific pages when it's required. In this case there is no opportunity for a user to create that kind of context - opening a page to see related options. The user can look right at the Import section on the Options page, and not see what they need. There's plenty of room on that page and I can't think of a good reason for this condition to persist. Beyond theories of why it might be good practice in some areas, it's proven in the field that in this case it's not. So with your agreement I'd like to make those controls visible at all times.

I'm curious about which post edit controls aren't visible unless you mouse-over. It makes me think I've been missing a feature ... for all the same reasons. Thanks.

**Comment by johngodley** [comment]
Hover links are a standard part of WordPress - you can't edit a post without hovering over the 'edit' button. Redirection was just using existing WordPress UI behaviour.

It's a moot point now anyway as import/export has been moved to a separate page and the modules table has disappeared.
