### ISSUE TITLE
Any Setting for Products Changed from Published to Draft?

### ISSUE THREAD

**Issue by sknichols** [johngodley/redirection#2541]
### Summary

First, thank you for the awesome plugin! It's saved me LOTS of time. I'm wondering if you could help me figure out how to create a redirect rule when a product/page/post/etc. is changed from "published" to "draft." For a variety of reasons, this is often better for our store than deleting products or setting them as "hidden" (which never seems to actually hide them in most places across the site). The problem is that when a product is set to draft, the once-live URL is now a 404, and I can't find an option in the plugin to handle this situation.

Otherwise, the plugin is handling everything else just fine.

### Actual Behavior

When a product, post, page, etc. is changed from "published" to "draft", visiting the previously published URL leads to a 404 page.

### Steps to reproduce

You can visit https://kingdomrec.com/product/sa-sports-empire-kryptek-beast-400-reverse-cam-crossbow to see the behavior. Just a standard 404 page because the product URL is no longer published. All we did was take the live product and switch it to "Draft" mode.

### Environment

Happens in all browsers (Opera, Chrome, etc.)

WP: 5.4.3
Woo: 4.5.2
Redirection: 4.9.2

Thanks in advance for any help you can offer!

**Comment by johngodley** [comment]
This is an interesting situation and I can see it being quite a useful feature. However, right now it's something you would need to do yourself using a custom plugin that monitors for status changes in products, and then creates a redirect.

I will have a think about it some more and see how it could be made more general purpose.

**Comment by johngodley** [comment]
Moved to #3349
