### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Ironmano** [johngodley/redirection#2543]
```
Plugin: 4.8
WordPress: 5.5.3 (single)
PHP: 7.3.21
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
JavaScript: https://vestiaires.org/wp-content/plugins/redirection/redirection.js
REST API: https://vestiaires.org/wp-json/

Error: Le nonce du cookie n’est pas valide (rest_cookie_invalid_nonce)
Raw: {"code":"rest_cookie_invalid_nonce","message":"Le nonce du cookie n\u2019est pas valide","data":{"status":403}}
```

**Comment by Ironmano** [comment]
and since 2 weeks, my redirection is not working anymore, I have the following error in the browser:
"This page isn’t workingvestiaires.org redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS"

**Comment by johngodley** [comment]
These are not connected. For the first, please read the onscreen instructions and log out, clear your cache, and log in again.

For the second you have likely created an infinite redirect. You will need to find that and fix it.

**Comment by Ironmano** [comment]
All good now! Thanks a lot :)
