### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by GermanPearls** [johngodley/redirection#2550]
Received an error after upgrading Redirection database.

Debug report:

```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.4.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36 Edg/86.0.622.56
JavaScript: https://www.logicallytech.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.logicallytech.com/wp-json/
Query: ?page=redirection.php

Action: https://www.logicallytech.com/wp-json/redirection/v1/group/ GET
Code: 400 Bad Request

Error: Missing parameter(s): moduleId, name (rest_missing_callback_param)
Raw: {"code":"rest_missing_callback_param","message":"Missing parameter(s): moduleId, name","data":{"status":400,"params":["moduleId","name"]}}
```

**Comment by johngodley** [comment]
What are you doing when this message appears?

**Comment by GermanPearls** [comment]
Thank you for quick response. This was a problem with another plugin.

For future reference:
This was happening as soon as I opened the Redirection app admin page.
The offending plugin (one I am developing) had an error in a php function which was causing a 404 on my site's /wp-json.
After fixing the typo, the /wp-json was again visible and the error in redirection disappeared.
