### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by slovisa** [johngodley/redirection#2558]
```
Uncaught SyntaxError: Unexpected identifier https://wegrowdreams.org/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863 2
```

Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
JavaScript: https://wegrowdreams.org/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://wegrowdreams.org/wp-json/

**Comment by johngodley** [comment]
This is caused by another plugin

**Comment by slovisa** [comment]
Thanks so much for your quick response. For what it's worth, I deactivated the "Duplicate Page & Post" plugin, and then Redirection started working normally. And then I reactivated "Duplicate Page & Post" and Redirection was still working... So I'm not sure what the actual issue was, but the important part is that it's working. Thank you again for your help!
