### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by cbstudiomx** [johngodley/redirection#2559]
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.4.10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
JavaScript: https://jorjette.ro/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://jorjette.ro/wp-json/

**Comment by johngodley** [comment]
This is almost certainly caused  by another plugin. Please open your developer console and see if any more information is shown

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
