### ISSUE TITLE
Regex Expression Fail

### ISSUE THREAD

**Issue by kay2thebee** [johngodley/redirection#2572]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Attempting to redirect
/?p=54667
but not
/?p=54667&preview=true
*nor*
/?p=54667&preview=1

Redirect Rule:
^\/\?p=\d+\/?$

### Actual Behavior
/?p=54667 - redirects
/?p=54667&preview=true - does not redirect
However, 
/?p=54667&preview=1 - redirects (even though the Redirect Tester on the Support page says it won't)

### Expected Behavior
/?p=54667&preview=1 does not redirect

I tested the expression on regex101.com and verified that /?p=54667&preview=1 does not match ^\/\?p=\d+\/?$

Please list your browser, browser version, version of WordPress and Redirection plugin.
Chrome - latest version
WP and Redirect also current versions

**Comment by johngodley** [comment]
Bear in mind that those URLs have special meaning in WordPress, and it will do its own thing regardless of what Redirection does.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
