### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by mrdenny** [johngodley/redirection#2582]
When I do the database upgrade it times out.

```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.22
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
JavaScript: https://www.dcac.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.dcac.com/wp-json/
Query: ?page=redirection.php

Action: https://www.dcac.com/wp-json/redirection/v1/plugin/database/ POST
Code: 500 Internal Server Error

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Raw: <html><head><title>500 - The request timed out.</title></head><body>  <font color ="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the specified time.</body></html>
```

**Comment by johngodley** [comment]
Can you increase the server time out? There is a manual upgrade option if you are unable to change your server.

**Comment by mrdenny** [comment]
I scaled up the database server size at that solved it.

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting, an Inc. 5000 company
denny@dcac.com<mailto:denny@dcac.com>
(o) +1 (323) 686-1478<tel:3236861478> | (d) +1 (213) 973-3669<tel:2139733669>
Online Calendar Bookings<https://calendly.com/mrdenny>
[cid:image001.png@01D6BC69.FA54D5A0]<http://www.dcac.co/>
[cid:image002.jpg@01D6BC69.FA54D5A0]
[cid:image003.png@01D6BC69.FA54D5A0]
[cid:image004.jpg@01D6BC69.FA54D5A0]
