### ISSUE TITLE
URL sub-string replacing is problematic

### ISSUE THREAD

**Issue by kylewetton** [johngodley/redirection#2583]
### Summary

With both regex on and off, redirector can sometimes cause errors to URLs that share the same sub-string 

### Actual Behavior

For instance, if i have an entry to redirect **gibson.com/customs** to **gibson-customs.com** 

My entry will be /customs redirects to https://gibson-custom.com

This works fine.

However, if I publish a blog post with the url **gibson.com/articles/customs-comes-to-namm**

Then, that article will redirect to the url **gibson.com/articleshttps://gibson-custom.com-comes-to-namm**

Notice that the /customs gets replaced here, I can't find a setting to fix this.

### Steps to reproduce

As above

### Environment

Not client side related, latest WP

**Comment by johngodley** [comment]
Can you show the redirects you have created where this is happening?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.

**Comment by kylewetton** [comment]
@johngodley Respectively, that is plenty information enough. To clarify I was merely reporting a bug, I'm not after support on this one.

**Comment by johngodley** [comment]
Thank you for the report. Unfortunately there isn't enough information for me to reproduce the problem, and it doesn't appear to be affecting anyone else. If you have more details then please do add them here.
