### ISSUE TITLE
Ghost URL page + redirect present but not configured

### ISSUE THREAD

**Issue by momentoresort** [johngodley/redirection#2591]
Hello, First of all, I would point out that before posting, I have been looking (in vain) for a solution for 2 days (and all the last night), but the various searches have led me to “nothing”.

**###Summary**

the URL of an old page is still active (when the page no longer exists) and an automatic redirection is active
=> I have not configured any redirect for this old page to the new one
=> I want to delete this redirect so that I can declare my old page as obsolete at Google (I’m not able to do it if this redirection still present : Google check the page and mark it like still existing) EXAMPLE (because I have about twenty pages in this case):

Old page URL that no longer exists:
		[https://www.momento-resort.com/contact-et-infos/newsletter/](https://www.momento-resort.com/contact-et-infos/newsletter/)
URL to which it is referred:
		[https://www.momento-resort.com/infos-services/newsletter/](https://www.momento-resort.com/infos-services/newsletter/)

**###CHECKS**

	##CHECK #1
		I checked on RedirectCheck (http://redirectcheck.com)
		here is the result (with LsCache deactivated):
		—————————
		Results: https://www.momento-resort.com/contact-et-infos/newsletter/
		HTTP/2 301
		date: Thu, 19 Nov 2020 08:33:10 GMT
		content-type: text/html; charset=UTF-8
		content-length: 0
		location: https://www.momento-resort.com/infos-services/newsletter/
		x-powered-by: PHP/7.4.12
		expires: Wed, 11 Jan 1984 05:00:00 GMT
		cache-control: no-cache, must-revalidate, max-age=0
		x-redirect-by: WordPress
		server: o2switch-PowerBoost-v3 https://www.momento-resort.com/infos-services/newsletter/
		HTTP/2 200
		date: Thu, 19 Nov 2020 08:33:12 GMT
		content-type: text/html; charset=UTF-8
		vary: Accept-Encoding
		x-powered-by: PHP/7.4.12
		link: ; rel=”https://api.w.org/”, ; rel=”alternate”; type=”application/json”, ; rel=shortlink
		server: o2switch-PowerBoost-v3
		————————— 
	##CHECK #2
		With your plugin « support / check redirection »
		—————————
		Result :
		HTTP 301 moved permanently - This and all future requests should be directed to the given URL-
		URL is not redirected with Redirection.
		Redirect Source
		redirect_canonical
		do_action('template_redirect')
		—————————

**###SOLUTIONS SOUGHT**
		1) see in .htaccess file
		— no redirection present
		2) deactivation plugin Redirection
		— problem still present
		(note : I have RankMath for SEO but, of course, the redirection module is always off)
		3) désactivante my cache plugin (LsCache)
		— problem still present
		4) see in the database
		— nothing found about the old URL
		5) update of the permalinks
		— nothing found about the old URL 
		and of course, I have emptied (several times) all the caches (wordpress ; browser ; server)

**###ENVIRONMENT**

SITE_URL https://www.momento-resort.com
HOME_URL https://www.momento-resort.com

TLWP Version 1.6.6
WordPress Version 5.5.3
Permalink Structure /%year%/%monthnum%/%day%/%postname%/

PHP Version 7.4.12
MySQL Version 5.5.5
Web Server Info Apache
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
Multi-site No

WP_DEBUG Enabled
DISPLAY ERRORS N/A

ACTIVE PLUGINS
amr shortcode any widget: 3.7
Awesome Weather Widget: 3.0.2
Broken Link Checker: 1.11.15
Data Tables Generator by Supsystic: 1.9.96
Easy Google Fonts: 1.4.4
Easy Social Feed: 6.0.2
Easy Table of Contents: 2.0.11
Enable Media Replace: 3.5.0
GTranslate: 2.8.60
LiteSpeed Cache: 3.5.2
MetaSlider: 3.19.0
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: 3.1.0
Rank Math SEO: 1.0.52.3
Real Media Library (Free): 4.10.6
Redirection: 4.9.2
Shortcode Widget: 1.5.2
Temporary Login Without Password: 1.6.6
WP Activity Log: 4.1.5.1
WPForms Lite: 1.6.3.1
WP Mail SMTP: 2.5.1

**Comment by johngodley** [comment]
`x-redirect-by: WordPress`
`Redirect Source: redirect_canonical`

WordPress is performing the redirect

**Comment by johngodley** [comment]
If you create your error in Redirection for that page that it probably override whatever WordPress is doing.

**Comment by momentoresort** [comment]
Hello
Thanks so much for your answer
1) Yes, I saw that this redirection is performing by wordpress
2) I already tried (and I tried one more time just now), to create this redirection in Redirection plugin.
When it's done, the checks show that the redirection is well performing by Redirection
=> When I cancel the redirection, Wordpress take back the hand and continue to keep this redirection available :-((

So, the problem stayed...
Thanks for your following

**Comment by johngodley** [comment]
>  When I cancel the redirection

Why do you need to cancel it? If Redirection is working fine I'm not sure I understand the problem.

**Comment by momentoresort** [comment]
This is an old URL for an old page that no longer exists and I don't want this redirect anymore.
In more :
1) for pratical reason : I will be able to declare this old URL as obsolete at Google Search (I’m not able to do it if this redirection still present : Google check the URL and mark it like still existing)
2) this is not the only one that I have in this case : I have around 10 - 15 URL like this that I want delete 
3) for technical reason : we must be able to delete this kind of redirection and knows where the problem come from if one time in the futur this kind of redirection makes more problems. 
Thanks so much for your attention

**Comment by johngodley** [comment]
Ok. You can configure Redirection to return a 410 error.

If you want to delete the redirect then you'll need to find out what is redirecting it and remove it there. This is not something that Redirection is involved with. As described above, it seems to be part of the WP canonical redirect, so that is the place to start looking.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
