### ISSUE TITLE
Bulk Action deleted ALL items rather than selected items only 

### ISSUE THREAD

**Issue by stefanhz** [johngodley/redirection#2593]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

Bulk deleting redirection items deleted ALL items I had set up, not only the ones I had selected for deletion.

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

I wanted to delete 5 redirect items that I did not need anymore. Rather than deleting them individually, I wanted to select those 5, and then use Bulk Action to delete them in one go.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

I had selected several items to be deleted, selected "Delete" from the Bulk Action drop-down, and confirmed deletion. All items were deleted.

Explain the steps involved to reproduce the problem

see above

Please list your browser, browser version, version of WordPress and Redirection plugin.

All the latest versions as of now: 
Firefox 83.0 (64-bit) Mac 
WP 5.5.3 
Redirection 4.9.2

Thank you

**Comment by johngodley** [comment]
Did you press the 'bulk delete all' dropdown?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
