### ISSUE TITLE
Feature request: Make it possible to redirect to URLs with custom schemes like myapp://somepage

### ISSUE THREAD

**Issue by mehlkelm** [johngodley/redirection#2596]
### Summary

At the end of an OAuth signup process that starts in my app I want to redirect the user from a wordpress page back into the mobile app. The app uses a custom URL scheme and can be opened from the mobile browser like so: myapp://someplace

### Actual Behavior

It's not allowed to register a redirect from https://mypage/oauthlandingpage to myapp://oauthlandingpage - I can't save the redirect like that.

**Comment by johngodley** [comment]
There's no restriction on the target URL, and you can use any valid scheme.

**Comment by mehlkelm** [comment]
Oh, sorry. I think I was confused by the warning that appears and thought I couldn't save the redirect…
