### ISSUE TITLE
Redirection of deleted items

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#26]
https://wordpress.org/support/topic/term-redirection-and-deletions?replies=1#post-5957669

**Comment by Sophist-UK** [comment]
Do we need also to be able to choose the status code when we do this redirect i.e. 301 410 etc.?

**Comment by johngodley** [comment]
The problem is what to redirect a deleted post too. A simple solution is to redirect to a fixed URL, set on the options page, but this doesn't sounds especially useful. There are many ways to delete a post (admin UI, JSON API etc) so it's not practical to add extra UI.

As such I'm going to close this as a redirection can always be manually created.
