### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jamiljonna** [johngodley/redirection#2606]
```
Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.3.23
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
JavaScript: https://monthlyreview.org/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://monthlyreview.org/wp-json/
Query: ?page=redirection.php

Action: https://monthlyreview.org/wp-json/redirection/v1/redirect/?orderby=id&per_page=100 GET
Code: 200 OK

Error: JSON Parse error: Unexpected identifier "wp" (SyntaxError)
Raw: wp-json/redirection/v1/redirect
```

**Comment by johngodley** [comment]
Your REST API is not working and is just returning the URL:

https://monthlyreview.org/wp-json/

**Comment by jamiljonna** [comment]
Thanks, I can see this as well in the Site Health: "The REST API did not process the context query parameter correctly." Do you have any idea what may be causing the REST API to stop functioning? Should I try reinstalling Wordpress?

**Comment by johngodley** [comment]
I've never seen that behaviour before. It might be worth asking in the WordPress support forums.

**Comment by jamiljonna** [comment]
Actually, I don't even get the error in Chrome—only Safari. So I guess it is somehow browser related. Thanks for the reply!
