### ISSUE TITLE
REDIRECT PROBLEM

### ISSUE THREAD

**Issue by jeanamazone** [johngodley/redirection#2609]
We use the Redirect WP plugin, we create a direct redirect form an old site to new site url.

We also put somme genéral ruels in the htacces file and the rules overide the redirection we put in the plugin.

Those are our général rules.
# BEGIN : redirection 
# fr
# ex : ceci sera redirigé https://www.cdsboutique.com/enfants/chaise-ray-lax-lavable.html
# vers https://cdsboutique.com/enfants/produits/chaise-ray-lax-lavable/
RewriteRule ^(enfants)\/(.*)\.html$ https://cdsboutique.com/enfants/produits/$2/ [R=301,L]
RewriteRule ^(accueil)\/(.*)\.html$ https://cdsboutique.com/enfants/produits/$2/ [R=301,L]

# ex : ceci sera redirigé https://www.cdsboutique.com/fr/assiette-antiderapante-gripware.html
# vers https://cdsboutique.com/aines/produit/assiette-antiderapante-gripware/
RewriteRule ^(fr)\/(.*)\.html$ https://cdsboutique.com/aines/produits/$2/ [R=301,L] 

# en  
# ex : ceci sera redirigé https://cdsboutique.com/en/champion-sand-bag-game.html
# vers https://cdsboutique.com/aines/en/produits/champion-sand-bag-game/
RewriteRule ^(en)\/(.*)\.html$ https://cdsboutique.com/aines/en/produits/$2/ [R=301,L]  
# END : redirection

**Comment by johngodley** [comment]
I don't really understand what you put above. What part is the problem?

**Comment by jeanamazone** [comment]
Sorry Iw ill try to be more clear

We install your plugin to be able to do some specifi redirection from our old site to our new site 
We create a first redirection for those url
Exemble 
https://www.cdsboutique.com/fr/nos-produits/jeux-varies/bingo-cartes.html
redirect to
https://cdsboutique.com/aines/categorie-produit/jeux-varies/bingo-et-cartes/

In the same time, we put some general rules to redirect all the old product url to the new product url.

Those rules ovewrite the specifi rules we put in the plugin

**Comment by jeanamazone** [comment]
The general ruels are in the htaccess file

**Comment by johngodley** [comment]
Ok, so you will need to either not put those rules in .htaccess, or modify them not to affect Redirection.

**Comment by jeanamazone** [comment]
Yes if I cant put thos rule in the plugin that's ok for us

**Comment by jeanamazone** [comment]
Can we put this kind of redirect in you plugin

RewriteRule ^(enfants)\/(.*)\.html$ https://cdsboutique.com/enfants/produits/$2/ [R=301,L]
RewriteRule ^(accueil)\/(.*)\.html$ https://cdsboutique.com/enfants/produits/$2/ [R=301,L]

**Comment by johngodley** [comment]
You can put redirects into Redirection.
