### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by MDFIRAN786** [johngodley/redirection#2613]
```
Uncaught SyntaxError: Unexpected identifier https://www.studywindows.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863 2
```

Plugin: 4.9.2
WordPress: 5.4.2 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
JavaScript: https://www.studywindows.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.studywindows.com/wp-json/

**Comment by MDFIRAN786** [comment]
Hi, I am not able to install the plugin REDIRECTION. I am using wordpress 5.5.2

**Comment by johngodley** [comment]
Your plugin is corrupted. You will need to install it again

**Comment by MDFIRAN786** [comment]
Hi John, thank you so much for your reply. So, I have deactivated and again installed it, still, the same message is coming.

**Comment by johngodley** [comment]
Ok. Your plugin is still corrupted. This is not connected to Redirection, so is likely a problem with your site. You can see the corruption in this file:

https://www.studywindows.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863

**Comment by MDFIRAN786** [comment]
I hope, my developer can correct it..right

**Comment by MDFIRAN786** [comment]
Thank you so much....John, nice time
