### ISSUE TITLE
Parameters not being passed even though set to pass parameters

### ISSUE THREAD

**Issue by spanishgringo** [johngodley/redirection#2616]
### Summary

Parameters not being passed even though set to pass parameters

### Actual Behavior

I'm trying to have a redirect ignore parameters and pass those to the destination.

Current settings:
- **Source URL:**  Ignore Case Ignore Slash
- **Query Parameters** Ignore & pass parameters to the target
- **Target URL** /request-demo/
 
![redirection-setting-not-working](https://user-images.githubusercontent.com/642689/101108709-00cb1400-358a-11eb-86da-213863ae62da.png)

I try this URL in my browser:
https://certent.com/see-a-demo?utm_campaign=EM_Services_eBook_Just_Got_Handed_Equity_Compensation%3F&utm_source=eBook&utm_medium=eBook

I get redirected to this URL (without Parameters)
https://certent.com/request-demo/

### Steps to reproduce

- Check settings (see above)
- Clear cache
- Enter URL with correct parameters
- See redirected URL with no parameters

### Environment

Hosting: WPEngine
WP: 5.5.3
Redirection: 4.9.2

**Comment by johngodley** [comment]
I have seen problems before with WP Engine not passing utm parameters in a redirect, and you will need to speak to them about that.

**Comment by spanishgringo** [comment]
Thank you. I'll file a ticket with them now.

**Comment by spanishgringo** [comment]
Confirmed. It was an NGINX VCL setting that their support had to fix.
