### ISSUE TITLE
Destination url in Automatically 301 redirect after change post address

### ISSUE THREAD

**Issue by naghmesara** [johngodley/redirection#263]
Hi john

Destination url in Automatically 301 redirect after change post address is relative but according to [this topic](https://moz.com/community/q/301-redirect-relative-or-absolute-path) in Moz.com Destination url in 301 redirect should 100% be absolute.

Please Fix This Problem.

regards

**Comment by johngodley** [comment]
You can use either a relative or absolute URL for the target - it's up to you.
