### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by cobaltgraphics** [johngodley/redirection#2631]
```
SyntaxError: missing } after function body https://www.stellarkids.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863 2
```

Plugin: 4.9.2
WordPress: 5.5.3 (single)
PHP: 7.4.10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0
JavaScript: https://www.stellarkids.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.stellarkids.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. Your browser's developer console may provide more information.

**Comment by cobaltgraphics** [comment]
Hi John - Thanks for the response. This is what the browser console
reveals:

SyntaxError: missing } after function body           tools.php:484:12
    onerror
https://www.stellarkids.com/wp-admin/tools.php?page=redirection.php:484

Uncaught SyntaxError: missing } after function body.
 redirection.js:2:533959
note: { opened at line 2, column 533946
redirection.js:2:533946

​Still think it’s another plugin? 🤔 🤷‍♂️

*DUSTIN *
cobalt.graphics  *•  * https://www.cobalt.graphics <https://cobalt.graphics>


On December 9, 2020 at 12:39:09 AM, John (notifications@github.com) wrote:

This is likely caused by another plugin. Your browser's developer console
may provide more information.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/johngodley/redirection/issues/2631#issuecomment-741593727>,
or unsubscribe

**Comment by johngodley** [comment]
Actually, I've spotted the problem. Your plugin is corrupt. The redirection.js file above contains this:

![image](https://user-images.githubusercontent.com/1277682/101658357-d7ecc800-3a3c-11eb-940b-c3541c543c0d.png)

It should not contain those characters.

**Comment by cobaltgraphics** [comment]
Hi John - good discovery! I tried deleted and reinstalling the plugin but
doesn’t seem to make a difference. Is there some else I should be doing to
retrieve a clean version?



*DUSTIN *
cobalt.graphics  *•  * https://www.cobalt.graphics <https://cobalt.graphics>


On December 9, 2020 at 9:38:16 AM, John (notifications@github.com) wrote:

Actually, I've spotted the problem. Your plugin is corrupt. The
redirection.js file above contains this:

[image: image]
<https://user-images.githubusercontent.com/1277682/101658357-d7ecc800-3a3c-11eb-940b-c3541c543c0d.png>

It should not contain those characters.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/johngodley/redirection/issues/2631#issuecomment-741892958>,
or unsubscribe

**Comment by johngodley** [comment]
How are you installing the plugin? I don't have any control over the process and it should always be a clean version

**Comment by cobaltgraphics** [comment]
I just deactivated/deleted and then through the repository,
installed/activated the plugin again.



*DUSTIN *
cobalt.graphics  *•  * https://www.cobalt.graphics <https://cobalt.graphics>


On December 9, 2020 at 11:30:17 PM, John (notifications@github.com) wrote:

How are you installing the plugin? I don't have any control over the
process and it should always be a clean version

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/johngodley/redirection/issues/2631#issuecomment-742273044>,
or unsubscribe

**Comment by johngodley** [comment]
What repository? The wp.org plugin repo? Did you install from inside WP itself, or download the plugin and install it manually?

As I mentioned I don't have any control over the installation process. This problem doesn't seem to be affecting other people so it's likely something specific about your site.

**Comment by cobaltgraphics** [comment]
Yeah, the .org repository from within the site. I’ll try downloading it
from outside and see what it does.


*DUSTIN *
cobalt.graphics  *•  * https://www.cobalt.graphics <https://cobalt.graphics>

**Comment by cobaltgraphics** [comment]
Hi John - despite deleting and reinstalling the plugin in various ways,
clearing the caching in Autoptimize, WP-Rocket, and Flywheel cache. Nothing
seemed to make a difference. Then, I turned on Development Mode in Flywheel
and Wha’La! The corrupt files in the plugin went away and was able to
upgrade the database and carry on. Thanks for your help and support!



*DUSTIN *
cobalt.graphics  *•  * https://www.cobalt.graphics <https://cobalt.graphics>


On December 11, 2020 at 1:17:20 AM, Dustin Olsen (dustin@cobalt.graphics)
wrote:

Yeah, the .org repository from within the site. I’ll try downloading it
from outside and see what it does.


*DUSTIN *
cobalt.graphics  *•  * https://www.cobalt.graphics <https://cobalt.graphics>

**Comment by johngodley** [comment]
Interesting. I'll look into Flywheel's development mode and what it does. Thanks for adding the info
