### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by kachmul2004** [johngodley/redirection#2635]
```
Plugin: 4.9.2
WordPress: 5.6 (single)
PHP: 7.4.3
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
JavaScript: https://www.gsmzambia.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.gsmzambia.com/wp-json/
Query: ?page=redirection.php

Error: Sorry, you are not allowed to do that. (rest_forbidden)
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by kachmul2004** [comment]
1. **Redirection's database needs to be updated - click to update.**

2**. all security plugins disabled.** 
- Wordfence
- Sucuri
- Jetpack
- Cloudflare

3. ![redirection](https://user-images.githubusercontent.com/34398375/101878574-7b9ebb00-3b98-11eb-8edc-955d3a431c64.png)

**Comment by kachmul2004** [comment]
I disabled all plugin but Redirection, even disable cloudflare dns, and I still get the same problem. Is it Nginx related maybe, seeing that others reported exactly the same problem on nginx

**Comment by johngodley** [comment]
You REST API is still using Cloudflare.

https://redirect.li/http/?url=https%3A%2F%2Fwww.gsmzambia.com%2Fwp-json%2F

**Comment by kachmul2004** [comment]
> You REST API is still using Cloudflare.
> 
> https://redirect.li/http/?url=https%3A%2F%2Fwww.gsmzambia.com%2Fwp-json%2F

Well, I used my server IP directly and still doesn't work

144.91.73.109

**Comment by johngodley** [comment]
I don't know what that means. Something on your server is blocking your REST API, and so Redirection is unable to run. You REST API is still going through Cloudflare and that is a likely cause. You may find other information here:

https://redirection.me/support/problems/rest-api/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
