### ISSUE TITLE
Feature Request | Sequential redirect correction

### ISSUE THREAD

**Issue by tfk2** [johngodley/redirection#2638]
Feature request:

ability to tidy up deeply nested redirects of redirects

**Comment by johngodley** [comment]
What would this look like?

**Comment by tfk2** [comment]
1. sort redirects by destination url
2. amend the sort so that destination URLs that no longer exist are moved to instead be indented beneath the URL that represents the end of the redirect chain

**Comment by johngodley** [comment]
I'm not sure I really understand what you mean. Can you give an example of a nested redirect that is a problem, and what the result would be afterwards?

**Comment by tfk2** [comment]
current
B redirects to A
C redirects to A
D redirects to B
E redirects to C
F redirects to C
G redirects to B

Final
B redirects to A
C redirects to A
D redirects to A
E redirects to A
F redirects to A
G redirects to A

**Comment by johngodley** [comment]
Ok. This kind of thing is very complicated to do and would have the potential to cause a host of unintended problems. I'm not sure it's really practical

**Comment by tfk2** [comment]
OK
simple version: a 'flag' that indicated the current destination URL is also redirected.
this would give the means to investigate and simplify the chain manually

**Comment by johngodley** [comment]
Moving to #1676
