### ISSUE TITLE
importing from csv is not working

### ISSUE THREAD

**Issue by ksjhdasdkj** [johngodley/redirection#264]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by ksjhdasdkj** [comment]
helppppppp

**Comment by ksjhdasdkj** [comment]
can you explain how this works??  **Source URL, Target URL, [Regex 0=false, 1=true], [HTTP Code]**

i guess this is why i cant import.....

**Comment by johngodley** [comment]
It is the format for the CSV file - you need to supply the source URL and target URL as minimum. You can ignore the rest

**Comment by dlipper2** [comment]
I am also having this problem. When I import the two column CSV, nothing happens.
