### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by millerg** [johngodley/redirection#2652]
```
Plugin: 4.9.2
WordPress: 5.6 (single)
PHP: 7.0.33-0ubuntu0.16.04.16
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
JavaScript: https://www.millernet.ca/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.millernet.ca/wp-json/
Query: ?page=redirection.php

Error: JSON Parse error: Unrecognized token '<' (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at www.millernet.ca Port 443</address>
</body></html>
```

**Comment by johngodley** [comment]
The details are shown above. Your REST API https://www.millernet.ca/wp-json/ is not working

**Comment by millerg** [comment]
Thanks for the quick reply. I have no idea when and what broke. Would it be worth removing the redirection extension (if it is even possible ) and re-installing. I built this site for my wife a number of years ago and suddenly discovered that none of the navigation links work and I believe it is related to the broken REST API.

When I go to tools > redirection page and click the "Upgrade Database” button, I get the following:


If you can point me to some resources, it would be greatly appreciated.

Cheers,

Greg Miller
(403) 471-8139
greg@millernet.ca

**Comment by johngodley** [comment]
I don't think this is connected to Redirection, and I dont think it is connected to your broken links.

There could be any number of reasons for the problem. I can only suggest you start with your WordPress Site Health, see what it says, and take it from there.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
