### ISSUE TITLE
404 Tab and functionality broken. 

### ISSUE THREAD

**Issue by Chalakilaw** [johngodley/redirection#266]
404 Tab and functionality broken.  Displays the following:

Sorry but something went wrong loading the data - please try again

Loading chunk 0 failed.

***
301 Tab and functionality seems to work

**Comment by johngodley** [comment]
What browser and version are you using?

**Comment by Chalakilaw** [comment]
------ Original Message ------

**Comment by johngodley** [comment]
There is a problem with some older browsers, which will be fixed in the next release.
