### ISSUE TITLE
Redirection Error — Unknown column 'match_data' in 'field list'

### ISSUE THREAD

**Issue by neilwhitespace** [johngodley/redirection#2662]
```
Plugin: 4.9.2
WordPress: 5.2.3 (multi)
PHP: 7.4.3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0
JavaScript: <redacted>/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API:  <redacted>/wp-json/
Query: ?page=redirection.php

Action: <redacted>/wp-json/redirection/v1/redirect/?orderby=id&direction=desc&per_page=25 POST
Params: {"id":0,"url":"/neiltest","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"},"options":{}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"<redacted>/"}}
Code: 400 Bad Request

Error: Unable to add new redirect (redirect_create_failed)
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":295,"wpdb":"Unknown column 'match_data' in 'field list'"}}
```

Looks like the plugin is trying to reference a column the table doesn't have?

Update: I've searched existing issues on this and it looks like a schema update was needed in the plugin. Submitting this issue anyway as it occured on a fresh install of the plugin.

**Comment by johngodley** [comment]
For some reason the plugin wasn't able to create the expected tables. I don't know why, and it doesn't make sense on a new install. This only affects a small number of sites and I'm not sure what is different about them. Had you installed the plugin previously?

You can fix it by going to the support page and changing the database version to 2.4

**Comment by neilwhitespace** [comment]
Hi there John — Unfortunately we inherited the site so can't be absolutely sure whether it was previously installed. I suspect not, though.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
