### ISSUE TITLE
Existing page creates 404 logs

### ISSUE THREAD

**Issue by R2-JorgeRamirez** [johngodley/redirection#2677]
I have several working redirects. Everything seems to work ok. 

However I am getting several 404 redirect logs from a page that actually exists.

Lets say "/en/contact" is the page, i get several 404 logs for that page in redirect but the page /en/contact exists and have no aparent problems.

Any ideas?

**Comment by johngodley** [comment]
Can you give a real URL, and a screenshot of a logged 404?

**Comment by R2-JorgeRamirez** [comment]
Sure:

![imagen](https://user-images.githubusercontent.com/75426705/103448191-3bfa5900-4c96-11eb-9aae-64ddf6d3c8e6.png)

URL is: https://www.r2docuo.com/en/contact

Curious that referrer is same address

**Comment by johngodley** [comment]
That is from the 404 log and not the redirect log? Does every page request generate a 404 or just some?

**Comment by R2-JorgeRamirez** [comment]
It seems to happen in just some pages and 404 on them eventually disappear after a couple of days.

Now I think this could be related to cache plugins as WP-Rocket or AutoOptimize.

I think we can close this bug. If I can isolate a persistent problem (that lasts for a couple of weeks) I will reopen.

Thanks!
