### ISSUE TITLE
Mutlisite Subdomain Site Homepage Redirection 

### ISSUE THREAD

**Issue by restyles4** [johngodley/redirection#2685]
Is it possible to redirect "only the homepage" of a subdomain to the main domain in a multisite setup? 

If yes, please direct accordingly. It does not work so far. 

I cannot find a single thing on this anywhere, searched for hours. Thank you!

**Comment by johngodley** [comment]
Details can be found under 'URL and server' - https://redirection.me/support/matching-redirects/

**Comment by restyles4** [comment]
Thank you. I looked there with the query "multisite" which is why I missed it. Subdomain, in many cases, references to pure subdomain schema based on added domains not multisite.  That why I missed it although your instruction works the same way.
