### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by Benflow** [johngodley/redirection#2686]
Plugin: 4.9.2
WordPress: 5.6 (single)
PHP: 7.4.13
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
JavaScript: https://www.chweya.com/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://www.chweya.com/wp-json/

**Comment by johngodley** [comment]
This is caused by another plugin. Open your developer console to see what may be causing it.

**Comment by Benflow** [comment]
I worked perfectly fine

**Comment by Benflow** [comment]
I meant it worked. I think there was a plugin conflict.
