### ISSUE TITLE
Delete selected redirections deletes ALL redirections

### ISSUE THREAD

**Issue by jeffmcneill** [johngodley/redirection#2689]
When selecting some redirections for deletion, when clicking the delete button, even though only some checkboxes are checked. All of the redirections are deleted. This is repeatable behavior.

Expected behavior: only the selected redirections will be deleted

Current behavior: all redirections are deleted.

Version: 4.9.2 on the latest Wordpress 5.6 Multisite. Note that I've been using this plugin for more than 10 years. Love it.

**Comment by johngodley** [comment]
Are you using the 'bulk action **all**' dropdown? This affects all redirects matching the current set of filters

**Comment by jeffmcneill** [comment]
Yes, Bulk Actions, but only check mark a few of them. However it says "Apply to All" on the button. Presumably that means to all checked. However it always deletes ALL of the redirections, including those not checked. How else would I delete more than one but less than all of the redirections?

**Comment by johngodley** [comment]
There are two bulk action dropdowns. One says `all` and the other doesn't. The one that doesn't applies only to the selected items, the other one applies to all items that match the current filter.

**Comment by jeffmcneill** [comment]
Well well. Ok. Might I suggest a change to the interface? Apply to All is ambiguous as it can mean "all checked". I'm assuming that if one wants to apply to all then just check the checkbox (both at top and at bottom) to select all, then click the Apply button.

Another option: from the LOG tab, have an option to recreate the redirect if it had been deleted.

Thanks for your assistance.

**Comment by jeffmcneill** [comment]
If you want to keep the "Apply to All" then having it as a button next to "Apply" both on the top and on the bottom would remove the ambiguity.

**Comment by johngodley** [comment]
This has changed in version 5.0

https://github.com/johngodley/redirection/releases/tag/5.0-beta
