### ISSUE TITLE
Conflict with Beaver Builder

### ISSUE THREAD

**Issue by jointjacked** [johngodley/redirection#2690]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Javascript (?) conflict with Beaver Builder

When the Redirection plugin is active along with Beaver Builder, Beaver Builder reports reports an error that prevents saving Beaver Builder templates/layouts. This is confirmed by disabling plugins 1 by 1 until until the error in Beaver Builder stopped showing up. T

"Beaver Builder has detected a plugin conflict that is preventing the page from saving.
( In technical terms there’s probably a PHP error in Ajax. )"

Console: 

jquery-migrate.min.js?ver=3.3.2:2 JQMIGRATE: Migrate is installed, version 3.3.2
embedded.js:19 Embedded.Rpc#listen(page.loaded)
embedded.js:19 Embedded.Rpc#listen(close)
embedded.js:19 Embedded.Rpc#listen(goTo)
embedded.js:19 Embedded.Rpc#listen(bounceToMemberful)
embedded.js:19 Embedded.Rpc#listen(performSilentLogin)
embedded.js:19 Embedded.Rpc#listen(redirectOnOverlayCloseTo)
embedded.js:19 Embedded.Rpc#listen(scrollToTop)
embedded.js:19 Embedded.Rpc#listen(reloadOnCloseWith)
embedded.js:19 OverlayController#openOverlayAfterRedirect, hash: 
embedded.js:19 Embedded.LinkInterceptor:intercepting-link https://jointjacked.memberful.com/account
embedded.js:19 Embedded.LinkInterceptor:intercepting-link http://jjmemberdev.wpengine.com/?memberful_endpoint=auth
embedded.js:19 Embedded.LinkInterceptor:intercepting-link https://jointjacked.memberful.com/checkout?plan=55498&return_to=http%3A%2F%2Fjjmemberdev.wpengine.com%2Ffl-theme-layout%2Fheader%2F%3Ffl_builder
member-8d008527ff2e6a5d47fc9aff61bc8bda447a01842fceb52d51c286eeede0de0a.js:47 Memberful.Rpc#listen(visit)
member-8d008527ff2e6a5d47fc9aff61bc8bda447a01842fceb52d51c286eeede0de0a.js:47 Memberful@turbolinks:load @showAnimation=undefined
member-8d008527ff2e6a5d47fc9aff61bc8bda447a01842fceb52d51c286eeede0de0a.js:47 Memberful.Rpc#call(page.loaded, [])
embedded.js:19 OverlayController@rpc: page.loaded
embedded.js:19 Overlay#showIframe
embedded.js:19 MemberfulIframe#show
jquery.min.js?ver=3.5.1:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js?ver=3.5.1:2
fl-builder.min.js?ver=2.4.1.3:6 ************************************************************************
fl-builder.min.js?ver=2.4.1.3:6 Beaver Builder caught the following JavaScript error. If Beaver Builder is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Beaver Builder while reactivating each to determine if the issue is related to a third party plugin.
fl-builder.min.js?ver=2.4.1.3:6 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object._jsonParse (fl-builder.min.js?ver=2.4.1.3:6)
    at Object.renderLegacySettingsComplete (fl-builder.min.js?ver=2.4.1.3:10)
    at Object.<anonymous> (fl-builder.min.js?ver=2.4.1.3:10)
    at Object.success (fl-builder.min.js?ver=2.4.1.3:6)
    at c (jquery.min.js?ver=3.5.1:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=3.5.1:2)
    at l (jquery.min.js?ver=3.5.1:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js?ver=3.5.1:2)
fl-builder.min.js?ver=2.4.1.3:6 Debug Info
fl-builder.min.js?ver=2.4.1.3:6 AJAX returned HTML page instead of data. (Possible 404 or max_input_vars)
fl-builder.min.js?ver=2.4.1.3:6 PHP Version: 7.4.13
fl-builder.min.js?ver=2.4.1.3:6 Memory Limit: 512M
fl-builder.min.js?ver=2.4.1.3:6 max_input_vars: 10000
fl-builder.min.js?ver=2.4.1.3:6 modsecfix: Disabled
2fl-builder.min.js?ver=2.4.1.3:6 ************************************************************************
fl-builder.min.js?ver=2.4.1.3:6 Beaver Builder caught the following JavaScript error. If Beaver Builder is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Beaver Builder while reactivating each to determine if the issue is related to a third party plugin.
fl-builder.min.js?ver=2.4.1.3:6 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object._jsonParse (fl-builder.min.js?ver=2.4.1.3:6)
    at Object.renderLegacySettingsComplete (fl-builder.min.js?ver=2.4.1.3:10)
    at Object.<anonymous> (fl-builder.min.js?ver=2.4.1.3:10)
    at Object.success (fl-builder.min.js?ver=2.4.1.3:6)
    at c (jquery.min.js?ver=3.5.1:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=3.5.1:2)
    at l (jquery.min.js?ver=3.5.1:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js?ver=3.5.1:2)
fl-builder.min.js?ver=2.4.1.3:6 Debug Info
fl-builder.min.js?ver=2.4.1.3:6 AJAX returned HTML page instead of data. (Possible 404 or max_input_vars)
fl-builder.min.js?ver=2.4.1.3:6 PHP Version: 7.4.13
fl-builder.min.js?ver=2.4.1.3:6 Memory Limit: 512M
fl-builder.min.js?ver=2.4.1.3:6 max_input_vars: 10000
fl-builder.min.js?ver=2.4.1.3:6 modsecfix: Disabled
fl-builder.min.js?ver=2.4.1.3:6 ************************************************************************
embedded.js:19 Overlay#hide
embedded.js:19 MemberfulIframe#hide
embedded.js:19 MemberfulIframe#visitDefaultUrl
embedded.js:19 Embedded.Rpc#call(visit, [https://jointjacked.memberful.com/turbolinks_preload])
member-8d008527ff2e6a5d47fc9aff61bc8bda447a01842fceb52d51c286eeede0de0a.js:47 Memberful@rpc: visit(https://jointjacked.memberful.com/turbolinks_preload)
member-8d008527ff2e6a5d47fc9aff61bc8bda447a01842fceb52d51c286eeede0de0a.js:47 Memberful@turbolinks:load @showAnimation=true
member-8d008527ff2e6a5d47fc9aff61bc8bda447a01842fceb52d51c286eeede0de0a.js:47 Memberful.Rpc#call(page.loaded, [])
embedded.js:19 OverlayController@rpc: page.loaded
embedded.js:19 Overlay#showIframe
embedded.js:19 MemberfulIframe#show
fl-builder.min.js?ver=2.4.1.3:6 ************************************************************************
fl-builder.min.js?ver=2.4.1.3:6 Beaver Builder caught the following JavaScript error. If Beaver Builder is not functioning as expected the cause is most likely this error. Please help us by disabling all plugins and testing Beaver Builder while reactivating each to determine if the issue is related to a third party plugin.
fl-builder.min.js?ver=2.4.1.3:6 SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object._jsonParse (fl-builder.min.js?ver=2.4.1.3:6)
    at Object.renderLegacySettingsComplete (fl-builder.min.js?ver=2.4.1.3:10)
    at Object.<anonymous> (fl-builder.min.js?ver=2.4.1.3:10)
    at Object.success (fl-builder.min.js?ver=2.4.1.3:6)
    at c (jquery.min.js?ver=3.5.1:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=3.5.1:2)
    at l (jquery.min.js?ver=3.5.1:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js?ver=3.5.1:2)
fl-builder.min.js?ver=2.4.1.3:6 Debug Info
fl-builder.min.js?ver=2.4.1.3:6 AJAX returned HTML page instead of data. (Possible 404 or max_input_vars)
fl-builder.min.js?ver=2.4.1.3:6 PHP Version: 7.4.13
fl-builder.min.js?ver=2.4.1.3:6 Memory Limit: 512M
fl-builder.min.js?ver=2.4.1.3:6 max_input_vars: 10000
fl-builder.min.js?ver=2.4.1.3:6 modsecfix: Disabled
fl-builder.min.js?ver=2.4.1.3:6 ************************************************************************
<img width="1022" alt="Screen Shot 2021-01-10 at 4 48 15 PM" src="https://user-images.githubusercontent.com/77253254/104140089-71710780-5364-11eb-9a59-0e4ec0f27fdf.png">

**Comment by johngodley** [comment]
What is beaver builder? How do you think Redirection is interfering with it?

**Comment by jointjacked** [comment]
@johngodley Beaver Builder is a Wordpress page builder plugin: https://www.wpbeaverbuilder.com/

I _only_ get the above plugin conflict error message when I have the Redirection active. I've tested this by disabling every other plugin aside from Beaver Builder (which I need to create my site) and the Redirection plugin being active is the only variable that causes the above error.

**Comment by johngodley** [comment]
Redirection makes no changes that would affect another plugin, unless you have created a redirect that might do so.

As it's a paid product I have no way of investigating further and you will need to see if any errors are logged, maybe in your server log file.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
