### ISSUE TITLE
Can't connect to the rest api on docker / traefik

### ISSUE THREAD

**Issue by danielgroen** [johngodley/redirection#2699]
Hi,
The redirection can't connect to the rest API on my site. It wants to connect to http while the site is running on https.

I am running on a docker environment. The routing is as followed:
1. Nginx | internal routing (http, port 80)
2. Traefik | edge router (https, port 443)

So the redirection module wants to connect via http since it thinks that it is running on port 80. (because it is looking to the wp_home protocol which is port 80 while it actually runs on https.

What i wonder. Isn't there a hook on the module where i can force the module to look for https?
Or
that the rest api is called by a relative url?

*On localhost, the module works fine (because it got served over http).
See screenshot below about the errors i got:
![image](https://user-images.githubusercontent.com/6578052/104593000-586f9b80-566f-11eb-8309-668d1e0e7ead.png)

**Comment by johngodley** [comment]
The plugin connects to whatever WordPress tells it to connect to, which is derived from your Settings > General URLs.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
