### ISSUE TITLE
Redirection doesn't work under some conditions

### ISSUE THREAD

**Issue by rootion** [johngodley/redirection#270]
I have issues redirecting some urls. I am still trying to understand what exactly the issue is and I would appreciate some help tracking this down.

### Summary

Some redirects work and some redirects don't work.

- domain.com/en/ to domain.com = works
- domain.com/en/blog/post-title to domain.com = works
- domain.com/anywordhere/ to domain.com = doesn't work (404)

I have a multilanguage environment running Polylang Pro 2.1.5
Tested with and Polylang activated. There are no other plugins active.
Disabled Polylang, saved permalinks again, but redirection still doesn't work in the cases that were marked.

### Redirection parameters used

Source url: /app/
Match: URL only
Action: Redirect to URL
Target URL: domain.com
Group: Redirection

### Environment

Wordpress 4.8, nginx, PHP 7.
Redirection 2.6.5
Polylang Pro 2.1.5

**Comment by johngodley** [comment]
Does the non-working get recorded in 404 log in Redirection?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details

**Comment by rootion** [comment]
Sorry, I was on holidays.
The non-working link gets recorded in the 404 log in redirection, yes. It also logs my IP address.
