### ISSUE TITLE
Manual redirection of an old HTTP page

### ISSUE THREAD

**Issue by shanknik** [johngodley/redirection#2706]
### Summary

I am trying to use this plugin to redirect an old url that google thinks is still available.  I enabled HTTPS for my entire site and everything is working, however google thinks www.mysite.com.au/blog still exists.  I want to redirect this to https://www.mysite.com.au.

### Actual Behavior

When clicking on the above mysite.com.au/blog, it takes me to a 404 page.  I wanted to use your plugin to redirect the url to the main page.  After clicking apply it changes www.mysite.com.au/blog to /blog.  Which looks like it is trying to redirect https://www.mysite.com.au/blog to https://www.mysite.com.au.  So it looks like the site wide redirect is also occurring on this plugin?

### Environment

Wordpress 5.6, Redirection 5.0

**Comment by johngodley** [comment]
I'm not sure I fully understand. Are you describing a problem, or describing it working?

**Comment by shanknik** [comment]
It's a problem, the site has a forced https redirect, however WP thinks there is still a http page somewhere.  However, when I try to redirect that page, the plugin automatically picks up the https.. thus cannot redirect the http page.

This is the test.
![image](https://user-images.githubusercontent.com/77602295/104883127-5d5a8500-59b8-11eb-942b-4bfdefa443be.png)

This is the rule;
![image](https://user-images.githubusercontent.com/77602295/104883153-6d726480-59b8-11eb-8c9a-c2a8152b07d2.png)

The page is actually www.<site>.com.au/blog.  Not https://www....

**Comment by johngodley** [comment]
Sorry I still don't fully understand. Your redirect is working? You have a https => http redirect and it is... not working?

Is it possible to put a real URL?

**Comment by shanknik** [comment]
Sorry would rather not, if there is a way to PM I can do that.

The entire site is HTTPS, there used to be a page that was http.  This page no longer exists.
I want to redirect any attempts from said page to the home page with https.  

When entering the redirect source of www.site.com.au/blog, it corrects it to https://www,site.com.au/blog.  It overrides what I enter essentially to what the site default is.

**Comment by johngodley** [comment]
Is your http => https redirect working? Why doesn't it redirect the http request?

The plugin, as described above, is working as expected.

**Comment by shanknik** [comment]
As mentioned, the page no longer exists. Hence not redirecting.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by johngodley** [comment]
Sure, I understand the page doesnt exist - that's why a redirect is being used - but you said there was a http => https redirect. Why isn't this handling the http request?

**Comment by shanknik** [comment]
Ah, good question.  Not entirely sure.  I did also ‘fix’ all the links to change them to https with search and replace.

**Comment by shanknik** [comment]
All good, ended up fixing it with search and replace.

Thanks for your time!
