### ISSUE TITLE
Success message overlapping in Footer area when updating settings

### ISSUE THREAD

**Issue by speedyprem** [johngodley/redirection#2707]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Success message is overlapping in footer area when adding new redirection rules from Redirections page.

### Actual Behavior

The Success message should appear on the top of the page without overlapping with admin menu bar.

### Steps to reproduce
1. Install the plugin.
2. Navigate to the Tools => Redirections.
3. Click Add new and add old and new URL to redirect.
4. Click on Add redirect button.
5. Success message overlapping in Footer area.

![image](https://user-images.githubusercontent.com/20163248/104876521-dc7e9780-597d-11eb-8fef-d2973221695c.png)

### Environment

**Browser:** Google Chrome Version 87.0.4280.141 (Official Build) (x86_64)
**WordPress:** 5.6
**Redirection plugin** 5.0

**Comment by johngodley** [comment]
Do you have another plugin running that might be interfering? I can't reproduce this problem and I suspect something else is affecting the layout.

**Comment by speedyprem** [comment]
Yes @johngodley you are right I have just tested with WordPress trac version and it is working fine. It seems it has some conflict with other plugins.

One more thing, I have added only one redirection rule but it is showing added 3. Please check the screenshot.

![image](https://user-images.githubusercontent.com/20163248/104942516-8ee44800-59da-11eb-949e-d76585d62052.png)

**Comment by johngodley** [comment]
If you know which plugin is causing the problem I might be able to update the plugin to prevent it.

The (3) just means that it's the third occurence of the message, not that 3 items were saved.
