### ISSUE TITLE
saving the htaccess path in options

### ISSUE THREAD

**Issue by bwragg** [johngodley/redirection#2709]
### Summary

When I enter the htaccess path in the options tab and save it, it says settings saved, but if I refresh the page the input box is now blank and if I go to the htaccess file the usual parts the the Redirection plug creates are not there

### Actual Behavior
As above

### Steps to reproduce
Click options tab, enter the path for htaccess, press Update, refresh page. Setting is gone.

### Environment
Any browser inc Chrome and Safari.
Wordpress 5.5.3 
Latest Redirection plugin 5.0

##Things I've Tried
Host is Closte which I think might have something to do with it as are a specialised wordpress host. They run LiteSpeed server on Google Cloud.  I assumed it was probably some write permission issue to htaccess but I noticed numerous other plugins I often use are all able to write to the htaccess file. e.g LiteSpeed, shortpixel are able to add their entries ok. So permissions seem ok.

I've disabled every other plugin and just had Redirection turned on and it has the same issue.

There are no wordpress errors getting thrown I the log file.

**Comment by bwragg** [comment]
Update to the above. So seems it is working but the path isn't getting saved in the input field on the options tab so it made us think it wasn't functioning. But if we add a redirect to the plugin it creates the entries in the htaccess file.

**Comment by johngodley** [comment]
This will be fixed in the next version.
