### ISSUE TITLE
410 error should be "Gone"

### ISSUE THREAD

**Issue by Mirucon** [johngodley/redirection#271]
On the latest version, I have found a string that says "410 - Found".
The HTTP code should be "Gone".

https://github.com/johngodley/redirection/blob/master/redirection-strings.php#L123

I think this is just a typo or something, just jetting you to know it.

Cheers,
Mirucon

**Comment by johngodley** [comment]
Ah thanks, fixed in bc6b3a427c73e47bbdd3996a4376b377c077494f

**Comment by Mirucon** [comment]
I can now translate it properly. Thanks!
