### ISSUE TITLE
Redirects with regex no longer work.

### ISSUE THREAD

**Issue by tnagels** [johngodley/redirection#2710]
### Summary

Regex redirections no longer work - they used to wotk, but now they no longer do, I guess since the last update to 5.°

### Actual Behavior

The redirect was setup with Regex enabled:

From: /sites/default/(.*)$
To: https://static.nexuzhealth.com/$1

I now get the error that the target URL contains an invalid character:  "Jouw doel-URL bevat het ongeldige teken % (invalid) s"

![image](https://user-images.githubusercontent.com/22787213/105015173-8d019f80-5a41-11eb-8528-921c87433257.png)

Other redirects work.

### Steps to reproduce

Create a Regex redirection with part of the url passed to the target.

### Environment

Win 10, Chrome and Edge
Wordpress 5.6 on wp.com, plugin version 5.0

**Comment by johngodley** [comment]
How many regex redirects do you have in total?

**Comment by tnagels** [comment]
Just one. But I have an update, the problem seems to be something different:
Our site has as primary domain nexuzhealth.**com**, but there is an alias configured in wp.com so that nxh.be and nexuzhealth.**be** also end up at the site. This is handled by wp.com.
What I see now is:
Target file is here: https://static.nexuzhealth.com/files/20171123_143613%20(2).jpg
Works: https://www.nexuzhealth.com/sites/default/files/20171123_143613%20(2).jpg
Does not work: https://www.nexuzhealth.be/sites/default/files/20171123_143613%20(2).jpg

Is this an issue caused by wp.com? Can you confirm that this works on other providers?

**Comment by johngodley** [comment]
A redirect happens on the site where the plugin is running using the site's configured address. It does not matter what aliases you have outside of that site.

You can read this for more information about external domains: https://redirection.me/support/redirecting-another-site/

**Comment by tnagels** [comment]
But both domains are linked to the new site:
![image](https://user-images.githubusercontent.com/22787213/105017463-174b0300-5a44-11eb-8f19-92dd5545309e.png)

**Comment by johngodley** [comment]
Sure. More details are found in the link I posted.

**Comment by tnagels** [comment]
Sorry, but don't get how anything in the article solves my issue. All other redirects I have set up work as expected for both the .be and the .com; it is only this one regex redirect that does not.
Example: https://nexuzhealth.be/privacy and https://nexuzhealth.com/privacy both redirect correctly to https://nexuzhealth.com/nl/privacyverklaring/.

And that still does not explain why I get an error in the settings panel.

**Comment by johngodley** [comment]
https://nexuzhealth.com/privacy is not being redirected by Redirection. The plugin is not affecting that domain.

https://www.nexuzhealth.be/sites/default/files/20171123_143613%20(2).jpg is being served by something else and is not redirecting the same as the above URL is.

The problem here is not with Redirection. If you read the guide it describes how to redirect domains that are not the configured domain. However, as explained in the guide, your server setup needs to allow this to happen. The plugin cannot do anything about that.

> still does not explain why I get an error in the settings panel.

It's a warning, not an error. You are free to ignore a warning.

**Comment by tnagels** [comment]
### 

> https://nexuzhealth.com/privacy is not being redirected by Redirection. The plugin is not affecting that domain.

**But it is!** The site running redirection is _nexuzhealth.com_, this is the primary domain of our site!

_Let me explain once more because maybe it did not come across clearly:_
My wp.com site (with the plugin) has as primary domain _nexuzhealth.com_, and secondary domains _nxh.be_ and _nexuzhealth.be_. We have our domains set to use the wp.com name servers for those domains, and they are added to the site in the wp.com config panel (see in earlier screenshot). For all regular content this works fine.

On top of this I have installed redirection to map some of the ulr's used in our old site structure to the new content. (such as the privacy link I just sent you before). This is 100% handled by redirection; I just tested again to be sure and when I switch the rule off I get a 404-page for the link, switch it on and it works again.

Again, this works fine for all "regular" redirects. I use these because when we switched to our new site, a lot of our partners still had links to content locations on the old site. I use these redirects to map the old to the new.

The problem I am seeing now is that with the regex redirect it only works when the link uses the primary domain of the site, not with any of the secondary domains, as explained before. 

Only reason I can think of why this does not work is that the wp.com cdn is doing some strange things here. That is why I asked if you have seen this work with other sites that have multiple domains pointing to them.

**Comment by johngodley** [comment]
Ok, I feel like we're going in circles here.

Redirects on your .com site are working. Some redirects on .be are working, but Redirection is not doing these - something else is.

I meant to use the statement 'the plugin is not affecting that domain' for this .be domain. I'm sorry if this added to the confusion, but I am not familiar with your setup.

The guide I referenced explains how to use the plugin across multiple domains. Yes it is possible, and is explained in the guide.

Possibly wp.com is handling a 404 on the other domain differently. I do not know, and it is something that the plugin cannot change.

At this point I don't think there is anything more I can add. The problem is not with Redirection and is almost certainly with the setup of your server. Maybe this is something wp.com can help you with.

**Comment by tnagels** [comment]
Almost there ;-) I'm struggling to come across clearly as there are few things going on at the same time. We are hosting our site on wp.com and it seems that was not the best choice as it complicates things when going beyond plain vanilla Wordpress.

What happens when you go to the .be domain is that the _wp.com cdn_ redirects this to the .com. This is how they handle what they call "secondary domains". So you are never served any actual content from the .be domain, but always redirected to the .com. We don't have any other active server or site on either of these domains.

Normally any parts of the url and parameters are passed on in this forwarding (or redirection) process. So when I surf to, for example, nexuzhealth.be/nl/ this is what happens:
nexuzhealth.be/nl   >===(wp.com cdn)===>   nexuzhealth.com/nl

So: anything that goes to the .be is first redirected to the .com by the wp.com cdn and then the site does the rest.

As Redirection runs on this site, it can handle further redirections. So when I surf to https://nexuzhealth.be/privacy, what actually happens is:
nexuzhealth.be/privacy   >===(wp.com cdn)===>   nexuzhealth.com/privacy   >===(Redirection)===>   nexuzhealth.com/nl/privacyverklaring

It also works when I redirect to content on external sites:
nexuzhealth.be/nl/contactformulier-mynexuzhealthpro   >===(wp.com cdn)===>   nexuzhealth.com/nl/contactformulier-mynexuzhealthpro   >===(Redirection)===>  forms.nexuzhealth.be/questionnaires/contactformulier-mynexuzhealthpro?lang=nl&target=clinicus

So far this works as expected. The problem arises when I try to do this with my regex redirect. Then all of a sudden the first step seems to fail. The .be domain does not get converted to the .com, I just get a 404. So what happens is this:
Does not work:
nexuzhealth.be/sites/default/files/20171123_143613%20(2).jpg   >=== (wp.com cdn)===>   404-error
Works:
nexuzhealth.com/sites/default/files/20171123_143613%20(2).jpg   >===(Redirection)===>  static.nexuzhealth.com/files/20171123_143613%20(2).jpg

Additionally, the 404-page in this case is not my site-specific page, but a generic wp.com 404-page. So, this seems to indicate that links to regex redirects are "seen" differently by the wp.com cdn compared to the "normal" redirects. For some reason it does not understand that these links need to be forwarded to the primary domain and they get "lost" in the cdn triggering a 404.

If that is the case I just wonder:
- Is this a known limitation?
- Do you have this behavior on not-wp.com hosted sites running on multiple domains?
- Is there anything which can be done to resolve this on your end?

If the cdn is at fault and you can't or won't (which I would understand) do anything to resolve this on your end, we will have to move our site to another host. I'm willing to do that, if only I could be sure this would solve my problem.

And, maybe, it would be helpful for others to document this limitation.

_PS. I blamed this on the upgrade because I seemed to remember that the redirect used to work, however, I am no longer sure of having tested it with the regex version or only the "plain" redirect._

**Comment by johngodley** [comment]
> this seems to indicate that links to regex redirects are "seen" differently by the wp.com cdn compared to the "normal" redirects

No, at this point Redirection is not involved. Anything that wp.com is doing probably happens at the server level, before WordPress and plugins run. I imagine that because the URL is a file it is checking if the file exists, and then returning a server 404 before anything else happens.

> Is this a known limitation
> Do you have this behavior on not-wp.com hosted sites running on multiple domains
> Is there anything which can be done to resolve this on your end

Redirection is not involved in this, is not limiting anything, and has no ability to change anything. These are questions for wp.com.

**Comment by tnagels** [comment]
> I imagine that because the URL is a file it is checking if the file exists, and then returning a server 404 before anything else happens.

AHA! That must be what is happening; this is not related to the regex, but to the fact that the url is a **file**. Now I see.

> Redirection is not involved in this, is not limiting anything, and has no ability to change anything. These are questions for wp.com.

Might still be a good idea to include this in documentation. Unfortunately I have come across many plugins with "disclaimers" when hosting on wp.com, so I guess I'll be changing hosting provider soon.

>>> Closing the issue; thanks for your time & patience.
