### ISSUE TITLE
Beginner question: Redirecting domain.com/brandname to affiliate link not working

### ISSUE THREAD

**Issue by barzor** [johngodley/redirection#2711]
Good day community, 

It's nice to see this community being active. I am a total beginner with this tool and I need help with the basics.
I am trying to redirect http://www.chartmonkey.co/binance to a Binance affiliate link but I can't get it to work.

Server: chartmonkey.co
Source: /binance
match: url and server
301 redirection
matched target: Binance affiliate link

Do I need to make a new map in FTP, or so?

**Comment by johngodley** [comment]
You appear to have solved the problem
