### ISSUE TITLE
Redirections does not work when it's over 2000 and using version 5.0

### ISSUE THREAD

**Issue by nat330** [johngodley/redirection#2715]
### Summary

I have a website which has around 5k redirections. With using plugin version 5.0 none of the redirects work. When any of the Source URL is hit it does nothing. It seems up to 2000 redirections it works fine. Also if i downgrade the plugin back to version 4.9.2 it works ok. Redirections are imported through wp cli in csv format. I have tried to import it in htaccess format or from the wp-admin page but got the same result.

### Actual Behavior

None of the redirections work if you have more than 2000 redirections in place.

### Steps to reproduce

Simply add more than 2000 redirections. I used wp cli to import it from a csv/htaccess file.

### Environment

Chrome Version 87.0.4280.141 (Official Build) (x86_64)
Wordpress version 5.6
Redirection plugin version: 5.0 (with previous version there is no issue)

**Comment by johngodley** [comment]
Are your redirects all regular expressions?

**Comment by nat330** [comment]
Yes.
An example in csv format:
^/source-url(/)?(\?.+)?$,/target-url,1,301

**Comment by johngodley** [comment]
Ok, that is the problem - you have too many regular expressions. It's not very performant to have so many, and version 5 enforces a limit that I thought would never be exceeded. It seems I was wrong about this.

For now you will need to use the last version. I will put a temporary workaround in the next version that will help, but I would strongly suggest looking at your redirects and reducing the number of regular expressions.

**Comment by nat330** [comment]
Yeah, I am already having a fight with SEO guys to chop off some redirects here. :)
I am using regex all the time as that provides quite a good flexibility when defining the redirections.

Thanks for the update!

**Comment by johngodley** [comment]
Sure, I understand that a regex is very flexible. Compared to a plain redirect they are a lot less performant though, and with 5000 of them I'm surprised your website loads!
