### ISSUE TITLE
Changed product permalink slug in WooCommerce

### ISSUE THREAD

**Issue by benjaminburkhardt** [johngodley/redirection#2718]
### Summary

By default my slug for all products was "/prodcut". Now I would like to change this to "/summary". I know that I can do this in the Wordpress Settings > Permalinks.

Unfortunately I already created a lot of QR codes to the old URLs.

### What I want to do

Now I need to create a redirection for all /product/* URLs to /summary/* that the old QR codes still work.

Any help appreciated - may using Regex could help? 

Thanks!

**Comment by johngodley** [comment]
Details here: https://redirection.me/support/redirect-regular-expressions/

**Comment by benjaminburkhardt** [comment]
> Details here: https://redirection.me/support/redirect-regular-expressions/

Perfect, thanks!
