### ISSUE TITLE
redirect issue

### ISSUE THREAD

**Issue by sunilprotein** [johngodley/redirection#2719]
My website is not stripping the text in * condition.

Website URL is like http://www.domain.com/search/adasd I want to redirect it to https://www.domain.com/noindex-page

Using below redirect
FROM :

^search/* 

TO:

https://www.domain.com/noindex-page?

but it is redirecting to https://www.domain.com/noindex-pageadasd and giving 404 not found.

Please suggest how to strip adasd from this.

Using * is necessary as there are number of URLs with this prefix.

**Comment by johngodley** [comment]
`*` is not supported. Please read the guide: https://redirection.me/support/redirect-regular-expressions/
