### ISSUE TITLE
Redirection goes to 404

### ISSUE THREAD

**Issue by ixodid2** [johngodley/redirection#272]
I am trying to make YourArtYourStory.com/world redirect to https://www.YourArtYourStory.com/signature but I get a 404

I installed the Redirect plugin and attempted to set up my first 301 - see screenshot
![301is404](https://user-images.githubusercontent.com/30603947/28792989-8ca54944-75ff-11e7-949e-7a500f6113f6.JPG)

For the source URL, I tried both with and without a trailing slash. I also tried regex [/]? in place of the trailing slash (and I did check the Regex box). None of those attempts worked.

Redirect v2.6.6; WP v4.8; Firefox 54.0.1; Chrome 60.0

There is no page at the source URL - it is my understanding that no source page is required for a 301 to work.

Please advise how to troubleshoot.

Thank you

**Comment by johngodley** [comment]
The source URL should be relative to your site, so you can remove the `yourartyourstory.com` and just have `/world`
