### ISSUE TITLE
getting the "Your target URL contains the invalid character $"

### ISSUE THREAD

**Issue by richtrefz** [johngodley/redirection#2723]
Short story
using the regex matching, get "Your target URL contains the invalid character $", but the redirects seem fine

```
source
^/redirection-test-regex-(.*)/

target
/newpg-$1/
```

WP 5.6 / Redirection 5.0

![Screenshot-2021-01-25-16-43-59](https://user-images.githubusercontent.com/1500959/105771756-0e1fd180-5f2f-11eb-9639-2e38b15c7b0d.png)

**Comment by johngodley** [comment]
Please ignore the message.
