### ISSUE TITLE
Redirection issue (JSON at position 0 (SyntaxError) or alike) - RESOLVED!

### ISSUE THREAD

**Issue by KickingKing** [johngodley/redirection#2729]
Hi guys, 

I have been banging my head for an hour with my WordPress site as no redirections were working and I had an error similar to:
"Unexpected token < in JSON at position 0 (SyntaxError)". So I hope this helps for some of you, as I see there are a lot of topics about this. I am a noob WP user, but it worked for me.
- In the help for the REST API (https://redirection.me/support/problems/rest-api/) at the bottom there is something about different URLs of the side and the WP files. So I checked it out and the REST API (whatever that is) was working but not on the right URL. So you could check if it is the same way with you:
- GO to WordPress-->Settings-->General. Check what is the WP folder URL and the site URL.
- When opening to test /wp-json/ try adding the WP folder. Example: mysite.com/wp-json/ does not work and retuns 404. But if you add WPfolder like "mysite.com/WPFOLDER/wp-json/" it works

- Good, now that we know where is the issue how to fix it? I tried to uninstall redirect.me plugin but it did not help.
- I updated PHP version (was with very old one) and it did not help. SO update yours and try it
- To update the redirection database or whatever it is WP --> Settings --> Permalinks
	Mine were set to "Post-name" and the only way i found to rewrite them is to change them (I used Numeric). It gave me an warning that this is very dangerous bla bla, but they are not really working so what can I loose :D. 
	Saved, changed back to "Post name" it rewrites it's data and now it is working.

Hope this helps somebody

**Comment by SpikeyMuscle** [comment]
It didn't work for me :(
