### ISSUE TITLE
Redirections view is blank

### ISSUE THREAD

**Issue by priit2000** [johngodley/redirection#273]
### Summary

Everything is working but the "Redirections" view is just empty page.

### Actual Behavior

On the redirections view there's nothing there. Screenshot https://www.dropbox.com/s/0ae9g9vmnz1lpaj/Screenshot%202017-08-01%2012.25.58.png?dl=0

### Steps to reproduce

No ideas

### Environment

Chrome, Version 59.0.3071.115, WordPress 4.6.3 and Redirection Version 2.6.6.

**Comment by johngodley** [comment]
From Chrome can you pick the 'JavaScript Console' option in the View > Developer menu, and then refresh page and see if any errors are shown.

**Comment by priit2000** [comment]
No errors:

jquery-migrate.js:1 JQMIGRATE: Migrate is installed with logging active, version 1.4.1
jquery-migrate.js:4 JQMIGRATE: 'hover' pseudo-event is deprecated, use 'mouseenter mouseleave'
migrateWarn @ jquery-migrate.js:4
jquery-migrate.js:4 console.trace
migrateWarn @ jquery-migrate.js:4
[Violation] Forced reflow while executing JavaScript took 44ms

**Comment by johngodley** [comment]
Hmm, can you try another browser or clear your browser cache.

Do the other pages work?

**Comment by priit2000** [comment]
Microsoft Edge same result.

1 thing that may shed light on this. I replaced all the http:// URLs on the database to https:// directly in MySQL. The site is on https for months now.

Log page works and shows new redirects being recorded as they happen.

**Comment by Nicscott01** [comment]
Having a similar issue, using Safari 10. In console, I'm getting a 404 error for the file redirection-combat-bace59f2d78f2e916a9.js. Its trying to load a relative URL so its coming up as http://www.mydomain.com/wp-admin/wp-admin/redirection-compat-bace59f2d78f2fe916a9.js.

I looked in the source, but couldn't figure out how that got loaded...so that may be the root of some of this? Additionally, everything loaded for me in Chrome 59.

**Comment by priit2000** [comment]
Is there an easy way to reinstall without losing current redirects?

**Comment by johngodley** [comment]
@priit2000 I dont think it has to do with your database changes. There is a problem with the current release not showing in IE or Safari

**Comment by johngodley** [comment]
Can you try the beta release to see if it fixes your problem?

https://github.com/johngodley/redirection/releases/tag/2.7b1

**Comment by priit2000** [comment]
Now I don't even have the "Groups | Modules | Log | 404s | Options | Support" part. Just empty screen with "Loading the bits, please wait..." But redirects still work.

**Comment by johngodley** [comment]
@priit2000 ok, thanks. That would happen if the plugin wasn't able to load the JavaScript file, and may be something specific to your site.

From the developer tools can you open the Network tab and see if there are any errors (they will appear in red). Specifically look for the request to `redirection.js`

**Comment by priit2000** [comment]
No errors on network tab, but now got this:

Uncaught ReferenceError: redirection is not defined
    at HTMLDocument.<anonymous> (tools.php?page=redirection.php:761)
    at i (jquery.js:1)
    at Object.fireWith [as resolveWith] (jquery.js:1)
    at Function.ready (jquery.js:1)
    at HTMLDocument.K (jquery.js:1)

**Comment by johngodley** [comment]
Yep, it's not loading the JavaScript. In the Network tab can you find the request for `redirection.js` - you can use the search box to help.

This is what I see on my site:

<img width="739" alt="request" src="https://user-images.githubusercontent.com/1277682/29023332-1b2b9d66-7b65-11e7-85e8-afecbbe49751.png">

Is there a redirection.js file in your Redirction plugin directory and is it readable?

Can you try disabling other plugins and see if that helps.

If the problem still exists then is it possible to give me access to the site so I can take a look? If this is ok then you can contact me by email (click my profile to see my website and use the contact form there)

**Comment by priit2000** [comment]
I'm really sorry! 2.7 works! I just had redirection.js in disk cache and forgot to clean up after I installed 2.7beta.

**Comment by johngodley** [comment]
Ok great! I'll close this issue

**Comment by priit2000** [comment]
Thank you!

**Comment by Nicscott01** [comment]
Thanks, v2.7 works for me on Safari!
