### ISSUE TITLE
Google indexing issue upload redirect

### ISSUE THREAD

**Issue by kuodagu** [johngodley/redirection#2732]
Hi,

I am uploading 100+ redirect through .csv file by this plugin and have successfully doing this without any issue. 

I have 2 question

1:   I want to block google to indexing/crawling the uploaded redirect or i want a 302 redirect option

2:  I want a proper column of CSV file (temporary 302 or 307 methods).

I will explain my current redirect Colum style here

Eg: 

oldsiteabc.com     newsitexyz.com      302

Once I upload this type of CSV file the redirection code automatically going to 301

Looking support from the team

**Comment by johngodley** [comment]
You can find information about the CSV format here:

https://redirection.me/support/import-export-redirects/

**Comment by kuodagu** [comment]
Thank you
I have successfully added 302 redirect through csv file

How we can block by google indexing these 302 redirected file from my website.

**Comment by johngodley** [comment]
https://duckduckgo.com/?q=google+noindex&t=brave&ia=web

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
