### ISSUE TITLE
Unwanted redirects to Port preview

### ISSUE THREAD

**Issue by vitorgomateus** [johngodley/redirection#2733]
### Summary

I have a redirect from `/` to `/foo` with exact match and no options. I basically want to override the index page, but only the index page. When I try to preview a post, however, sometimes it will trigger my redirection rule.

### Actual Behavior

`https://domain.com/sponsors/?preview_id=2605&preview_nonce=63dc8958df&preview=true` -> this also redirects and I believe is not supposed to.

All logs show the original url as only  `/`.

### Environment

Redirection: Plugin: 5.0.1
WordPress: 5.6 (single)
PHP: 7.3.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
JavaScript: https://conftele2021.ipleiria.pt/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3

REST API: https://conftele2021.ipleiria.pt/wp-json/

TIA

**Comment by johngodley** [comment]
Can you show your redirect settings?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
