### ISSUE TITLE
don't know how to do if my source url is a link on a page

### ISSUE THREAD

**Issue by HysteriaKa** [johngodley/redirection#2734]
Hey,
I ma on wordpress with woocommerce last version and i am just trying to avoid non logged visitors to see products or shop page.
But those pages are not in menu, you can only access them on a button content in home page (list of product but i need people to be connected to see more or buy) and shop link is in a button on another page ! So can i do that with your plugin ??
Thanks a lot

**Comment by johngodley** [comment]
A redirect works on a URL. What you have on your page does not affect a redirect. You can redirect product pages if they have a separate URL.

**Comment by HysteriaKa** [comment]
thanks ! yes i can do that for my products ! will see hat i can do for my other issue ! but it helps a lot !!
