### ISSUE TITLE
Stuck in installation of Redirection Plugin 

### ISSUE THREAD

**Issue by gsneildesai** [johngodley/redirection#2735]
Hello concern,
We want to use Redirection plugin on our wordpress installation. We are facing issue while installing it.

OverView:
Our Website structure consists of multiple domains & as per regulatory formed all our API requests on First Domain gets redirected to Second Domain through serverside redirection. Now, we want to use Redirection Plugin on our first domain only.

Issue We are Facing:
When we try to install it below Requests returns 403 .
https://www.mypandit.com/wp-json/redirection/v1/plugin/test/?_wpnonce=0a30bc8726
We have also tried to disable our caching plugin (Wp-rocket) but that too doesnt seem to make any difference. When we tried Manual install, we were able to create redirection tables in our database but post that operation, we got stuck at Finish stage.

Kindly guide us to resolve the issue.

**Comment by johngodley** [comment]
> all our API requests on First Domain gets redirected to Second Domain through serverside redirection

This does not sound like a good idea and it will break things.

> When we try to install it below Requests returns 403 .

Can you provide the full details?

**Comment by gsneildesai** [comment]
> Can you provide the full details?
What exact details do you require ?

**Comment by johngodley** [comment]
The full error details provided by the plugin

**Comment by gsneildesai** [comment]
![errorimg3](https://user-images.githubusercontent.com/56347817/106265744-7b907280-624d-11eb-9358-49de58414fd8.png)
![errorimg2](https://user-images.githubusercontent.com/56347817/106265760-80552680-624d-11eb-9b26-922689829877.png)
![errorimg1](https://user-images.githubusercontent.com/56347817/106265761-80edbd00-624d-11eb-99b7-46cd8ec10d74.png)
Please find images for errors that are being displayed while instalation. Also same continues when we proceed to finish install directly.

**Comment by johngodley** [comment]
There are guides for REST API problems here:

https://redirection.me/support/problems/rest-api/
https://redirection.me/support/problems/cloudflare/

**Comment by gsneildesai** [comment]
We have redirection rule on server side which will redirect all Rest API's to another sub domain. Despite of the Rest API error's, we were able to finish setup of plugin in our development environments. Also , after installation it worked properly. Only thing is on our main server when we click finish setup it doesnt proceed ahead. 
Our development environment was able to proceed despite of Rest API errors.
