### ISSUE TITLE
404s and redirects not showing.

### ISSUE THREAD

**Issue by KennyWilliamsonMagic** [johngodley/redirection#274]
I have 2 sites using redirection.
The one that i updated to redirection v2.6.6. 
When viewed in Internet explorer 11, shows "failed to load data" (I have never had a problem with redirection till v2.6.5).
![screen shot 08-01-17 at 02 39 pm](https://user-images.githubusercontent.com/29889256/28825761-ddb225b4-76c7-11e7-95d5-07e0979d472c.PNG)
This is the same under "redirects"/ "groups"/ "options".
Under "modules"- the options of modules show.
Under "log" and "4o4s" I get "failed to load data.
![screen shot 08-01-17 at 02 47 pm](https://user-images.githubusercontent.com/29889256/28825911-5eb0ea24-76c8-11e7-8e8e-303cfc080844.PNG)

When I switch to chrome (v 60.0.3112.78)
I get the options page coming up under the tabs for "redirects" and "Groups" and "options"
The 404 and the log page show details for the pages.

Both sites using latest wordpress (4.8)

**Comment by johngodley** [comment]
There is a problem with the latest versions and IE which has been fixed in the upcoming version. The second problem sounds like a bug that was fixed a few versions back, and so maybe you are using an older version of the plugin

**Comment by KennyWilliamsonMagic** [comment]
Nope John, using 2.6.6.... the problems only started occurring from 2.6.5.... did firefox have any issues/?

**Comment by johngodley** [comment]
Possibly. What you described matches the exact problems that others have had. I'm going to put together a new beta release with the fixes soon so I'll mention it here, and if you get chance to test it out and see if it fixes your sites then that would be great

**Comment by johngodley** [comment]
Can you try this beta release?

https://github.com/johngodley/redirection/releases/tag/2.7b1
