### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by aswathi-sv** [johngodley/redirection#2741]
Plugin: 5.0.1
WordPress: 5.6 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
JavaScript: https://beta.nehrucentre.org.uk/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://beta.nehrucentre.org.uk/wp-json/

**Comment by johngodley** [comment]
Please read the onscreen instructions.

Your plugin is not installed correctly:

https://beta.nehrucentre.org.uk/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
