### ISSUE TITLE
Site aliases failing when the path is only present via WordPress redirect

### ISSUE THREAD

**Issue by danielfdickinson** [johngodley/redirection#2744]
### Summary

I expected that a site alias would act the same as if accessing via the primary domain. In particular I would expect that,
for example, accessing https://www2.example.com/slug1 would redirect to
https://www.example.net/2020/01/30/slug1/, which is what happens if
you access https://www.example.net/slug1/.

I have a site (like www2.example.com) configured as a 'Site Alias'  and the 'WordPress domain and URL is like https://www.example.net.

### Actual Behavior

Accessing https://www2.example.com/slug1/ gets a 404 error.

### Steps to reproduce
1. Have a primary domain (e.g. https://www.example.net)
2. Set permalinks to include month day and year, then post name. 
3. Force HTTPS (may not be required, but it's my setup)
4. Configure 'Add www' (may not be required, but is my setup)
5. Configure a site alias (e.g. https://www2.example.com)
6. Attempt to access post via the site alias and post name (no date)
7. Get 404

### Environment

Firefox 85.0 (64-bit) for Ubuntu (when logging see other UA's have same problem though)

WordPress 5.6.0 and 5.6.1
Redirection plugin version 5.0.1

**Comment by johngodley** [comment]
A site alias redirects the path from one domain to another. It doesn't look at the path, your permalinks, or do any other processing.

Is there anything on your site that could be affecting this? I get a lot of 403 errors when trying various URLs.

**Comment by danielfdickinson** [comment]
The 403's were a result of having OVH 'application firewall' enabled
(which basically uses an Apache security module which, among other
things, dislikes cURL). I've now disabled that.

I've also removed many redirects that might have been an issue or were
at best taking up space, but still having the same issue.

I'm taking a closer look at my hosting (on OVH) to see if I can find
anything that explains the mystery.  For example checking .htaccess at
root and for the WordPress directory.

Also checking DNS to see if there is anything there.

Will let you know.

Regards,

Daniel


On Thu, 2021-02-04 at 08:23 -0800, John wrote:
> A site alias redirects the path from one domain to another. It
> doesn't look at the path, your permalinks, or do any other
> processing.
> Is there anything on your site that could be affecting this? I get a
> lot of 403 errors when trying various URLs.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
https://www.wildtechgarden.ca -- technical and professional website

**Comment by danielfdickinson** [comment]
Sorry for the noise, the main problem was changing the primary site URL
via the Settings page. Looks like I have some site fixing to do. (And
if I just didn't notice a warning file a WP bug that there should be a
warning on changing primary domain/URL and/or it should be locked once
posts exist unless one 'unlocks' with a blurb on why this isn't going
to work the way you expect).

This can be closed.
-- 
https://www.wildtechgarden.ca -- technical and professional website

**Comment by danielfdickinson** [comment]
So I figured a way to get what I want (for whatever reason after updating gids, exporting, creating a replacement site, important etc, it was doing the same thing).

Since what I wanted, really, was for all 'fallback' rule such that all domains other than the primary domain get redirected to the primary domain, I:

1. Create a URL and server match 'Redirect URL' rule
2. Gave it priority 99999
3. Match on URL ``^/(.*)``
4. Match on server matches the primary domain (e.g. www.example.com)
5. Empty match target
6. Unmatched target ``https://www.example.com/$1``

It seems to work the way I want.

**Comment by danielfdickinson** [comment]
I wonder if 'site aliases' are either
1. terminal (i.e. no more processing of redirects after them, in which internal WP redirect from /pretty-name to /year/month/day/pretty-name doesn't occur for site aliases)
2. occur after all other redirects and do not recurse (so the lists of redirects is not applied with the new address, same effective problem as indicated in 1.)

**Comment by johngodley** [comment]
A site alias redirects the path on the aliased domain to the current domain. They only occur on the aliased domain, and there is no further processing.

**Comment by danielfdickinson** [comment]
Ok, I found part of the answer:

Non-working redirect with site-alias:

```
https://www.danielfdickinson.ca/a-font-for-all-ages/
Host: www.danielfdickinson.ca
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-GPC: 1

GET: HTTP/2.0 404 Not Found
date: Sat, 06 Feb 2021 15:43:46 GMT
content-type: text/html; charset=UTF-8
server: Apache
x-powered-by: PHP/7.4
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
link: <https://www.wildtechgarden.ca/wp-json/>; rel="https://api.w.org/"
X-Firefox-Spdy: h2
```

working redirect with site alias (this time in a privacy window in Firefox):

```
https://www.danielfdickinson.ca/a-font-for-all-ages/
Host: www.danielfdickinson.ca
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1

GET: HTTP/2.0 301 Moved Permanently
date: Sat, 06 Feb 2021 16:04:51 GMT
content-type: text/html; charset=UTF-8
server: Apache
x-powered-by: PHP/7.4
expires: Sat, 06 Feb 2021 17:04:51 GMT
cache-control: max-age=3600
x-redirect-by: redirection
location: https://www.wildtechgarden.ca/a-font-for-all-ages/
X-Firefox-Spdy: h2
```
The problem is somehow related to `Sec-GPC: 1` which is Firefox's 'supercookie' protection.

**Comment by johngodley** [comment]
I can't find any information about `Sec-GPC`. Redirection does not look at the HTTP headers, so it isn't involved in the difference.

**Comment by danielfdickinson** [comment]
Ok, I did more testing; the success was due to caching (I think) not the difference in header or non-privacy vs privacy mode. Bah.

Anyway, For `Sec-GPC` info: https://globalprivacycontrol.github.io/gpc-spec/

This time I did all testing in Firefox 85 with Privacy Mode enabled:

with site alias and not my redirect rule from above AND no path component to the URL:
```
https://thewildtechgarden.com/
Host: thewildtechgarden.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1

GET: HTTP/2.0 301 Moved Permanently
date: Sat, 06 Feb 2021 16:51:18 GMT
content-type: text/html; charset=UTF-8
server: Apache
x-powered-by: PHP/7.4
expires: Sat, 06 Feb 2021 17:51:18 GMT
cache-control: max-age=3600
x-redirect-by: WordPress
location: https://www.wildtechgarden.ca/
X-Firefox-Spdy: h2
```

with site alias and not my redirect rule from above:
```
https://thewildtechgarden.com/data-responsibly/
Host: thewildtechgarden.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1

GET: HTTP/2.0 404 Not Found
date: Sat, 06 Feb 2021 16:50:03 GMT
content-type: text/html; charset=UTF-8
server: Apache
x-powered-by: PHP/7.4
expires: Wed, 11 Jan 1984 05:00:00 GMT
cache-control: no-cache, must-revalidate, max-age=0
link: <https://www.wildtechgarden.ca/wp-json/>; rel="https://api.w.org/"
X-Firefox-Spdy: h2
```

without site alias and with my redirect rule from above:
```
https://thewildtechgarden.com/data-responsibly/
Host: thewildtechgarden.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1

GET: HTTP/2.0 301 Moved Permanently
date: Sat, 06 Feb 2021 16:55:12 GMT
content-type: text/html; charset=UTF-8
server: Apache
x-powered-by: PHP/7.4
expires: Sat, 06 Feb 2021 17:55:12 GMT
cache-control: max-age=3600
x-redirect-by: redirection
location: https://www.wildtechgarden.ca/data-responsibly/
X-Firefox-Spdy: h2
```

I have a workaround that works for me, and you don't seem to be interested in debugging this, so I'm not going to do more on this, unless you have some suggestions of where to look.

If there is a way to privately send you a list of plugins privately, in case it is a conflicting plugin situation, I'm happy to do that.

To me your description of the site alias 'ought' to do the same thing as the redirect rule I described. So my question is what technical manner does the redirect rule I described differ from a site alias, and why would that be a problem?

**Comment by danielfdickinson** [comment]
Also, if I can privately send you anything I could include the OVH generated `.htaccess` files, in case that would make sense as the cause. (Maybe checking for path existence on site alias but not for a redirect rule?)

**Comment by danielfdickinson** [comment]
I realize one other thing: the failure occurs only for paths that do not exist but are redirect internally by WordPress.

**Comment by johngodley** [comment]
> you don't seem to be interested in debugging this

I'm interested in debugging a problem with the plugin, but not your site configuration. Also, you said this issue can be closed.

I can be contacted through the plugin or the support website. However I can only support the plugin itself and not site configuration.

If you have a setup that does what you want then is the problem solved?

> the failure occurs only for paths that do not exist but are redirected internally by WordPress

The failure with what? What do you mean by internally redirected by WordPress?

**Comment by danielfdickinson** [comment]
On Sat, 2021-02-06 at 09:42 -0800, John wrote:
> > you don't seem to be interested in debugging this
> I'm interested in debugging a problem with the plugin, but not your
> site configuration. Also, you said this issue can be closed.

Sorry, I reread that part and realized it had the wrong 'tone'. For my
purposes I have a solution that meets my needs; I was trying to do
enough investigation and such to verify that it was indeed a site
configuration issue and not a plugin issue. My comment was only meant
to say that you seem pretty convinced it's the former and not the
latter, and that unless you see the value in investigating further,
it's not worth either of our time for me to keep digging.

> I can be contacted through the plugin or the support website. However
> I can only support the plugin itself and not site configuration.
> If you have a setup that does what you want then is the problem
> solved?

> > the failure occurs only for paths that do not exist but are
> > redirected internally by WordPress
> The failure with what? What do you mean by internally redirected by
> WordPress?

Ok, 'the failure' is that with a site alias:

https://thewildtechgarden.com/data-responsibly gives a 404

however,

https://thewildtechgarden.com/ redirects to
https://www.wildtechgarden.ca/ (as it should)

https://thewildtechgarden.com/2021/01/02/data-responsibly/ redirects to
https://www.wildtechgarden.ca/ (as it should)

/data-responsibly/ is not the permalink but /2021/01/02/data-
responsibly/ is. This is why I say /data-responsibly is internally
redirected. (generates a redirect is perhaps a better way of putting
it).

(...pause while I watch headers for a 'pretty name' vs permalink...)
From watching the headers, I think the latter is accurate.

If it **is** a website configuration issue I'd like to know in order to
get on my hosting company's case, but that is not your problem. (I
didn't set up the configuration, and when I do set up websites I prefer
a different server, so I'm not familiar enough with the details of the
site configuration to see where there might be an issue with that
rather than what looked to me like a plugin issue).

I apologize for taking up so much time, especially if it isn't the
plugin that's the issue -- I don't have enough information at present
to be certain.

Regards,

Daniel

**Comment by danielfdickinson** [comment]
I think I might have a way to test that will settle the question in my
mind, and possibly be useful to you (at least I hope so).

If there is a 'bare-bones' WordPress KVM VM that I can just spin up
with a configuration which you know ought to work, add the redirection
plugin and test locally, then if the issue doesn't appear I know the
issue is with OVH config.

If it does show up in such a scenario, would you be interested in the
results? If so, I'm game to try that.

Regards,

Daniel

**Comment by danielfdickinson** [comment]
I might be a bit late thinking of this, but I know what would settle
things in my mind:

Does your CI have a the following test scenario:

1. Primary domain is www.somedomain.example.com
2. Another domain is anotherdomain.example.com and
www.anotherdomain.example.com
3. Permalinks are configured as the 'Day' option (which means
/year/month/day/slug is the permalink and accessing
www.somedomain.example.com/slug redirects to
somedomain.com/year/month/day/slug
4. HTTPS required
5. Canonicalization of somedomain.example.com to
www.somedomain.example.com
6. A site alias of www.anotherdomain.example.com to
www.somedomain.example.com
7. Given a post with slug' slugtest' and permalink
'/2020/11/28/slugtest'
8. Test fails if https://www.anotherdomain.example.com/slugtest/ fails
to redirect to https://www.somedomain.example.com/2020/11/28/slugtest/

If you already have that test, then I absolutely apologize for doubting
your assumption that this is not a plugin issue.

Regards,

Daniel

**Comment by johngodley** [comment]
No, that specific scenario is not tested. Most of your points won't affect the plugin so it's also not necessary.

If you had provided real URLs then I could have tested them myself.

I've just tested this and it worked as expected. Every URL on the aliased domain was redirected to the same path on the site domain.

**Comment by danielfdickinson** [comment]
Well, since I figured out a workaround and had it applied to my site,
testing my real URLs wouldn't do you any good because you would not
demonstrate the errors.

This interaction didn't go as I had planned; I was trying to alert to
what I thought was a plugin issue (especially since it makes no sense
to me that the workaround works, but the site alias thing doesn't, but
empirically, that is the case).

Instead I've annoyed you and gotten frustrated. I also had hope to have
the information to do the testing work myself instead of you doing it
(it was not my intent to suck up your time).

It does show me where I need to recognize, early, when more information
and more investigation is not going to help, unless I pull up the code
and do a really serious and in-depth 'root cause' so that I know
exactly where the problem lies (For a site configuration issue from the
provider, it allows to document and/or contact the provider about how
their configuration break a service they are trying to provide; for a
plugin it avoids the assumption the automatic, it's not in my code
response by either instead being about documenting how a particular
configuration causes an issue, or creating an issue/PR pair that
clearly and completely describes the issue and the solution).

I'm still going to dig further because I'd still like to know what is
the 'root cause' and at least document how and why it occurs, for the
benefit of other and, if applicable, to convince the provider to issue
a fix (or, if provable, warn others that on this provider they'll need
to a workaround instead of the usual method (in this case the site
alias)).

I'll close the template update offer as well, because it's pretty clear
we don't mix well, and probably would just be frustrating for both of
us.

Regards,

Daniel

**Comment by danielfdickinson** [comment]
To clarify: I disabled the workaround when originally reporting so that
you could see the error, but unfortunately the Apache security module
that was active treats cURL as a rogue bot.

For the most recent set-by-step, it was intended to be about a CI test
in a pristine environment and automated probably via API calls and use
of cURL in a sandbox, not about testing in a messy environment that I
didn't build from scratch.

**Comment by johngodley** [comment]
> Instead I've annoyed you and gotten frustrated
> it's pretty clear we don't mix well, and probably would just be frustrating for both of us.

I'm sorry you feel that way. For the record I've tried to answer your questions as direct as I can, and don't believe I've expressed any frustration or annoyance.

There are no other reports of problems with this feature (currently, and in the past), it works in my own setup, and the code involved is relatively simple (check domain name, if it matches an alias then redirect). With this in mind my assumption is that it is more likely a problem with the setup.

I have a certain amount of time I can provide for support. The scope of the plugin means it is greatly affected by a wide range of problems outside of the plugin itself. Experience has shown that these are often big time sinks, and I try and avoid those.

With real URLs I can make a few simple checks for obvious problems. For example, the vast majority of issues are caused by over-zealous security software, or caches. Your site did have some security issues, so that further added to my assumption.

I am not saying the plugin is free of problems and I will fix known bugs, or try to make allowances to avoid problematic hosts (within limits).

**Comment by johngodley** [comment]
Also, I will add, the plugin provides different ways of achieving the same result as some methods don't work on some environments.

**Comment by danielfdickinson** [comment]
On Sun, 2021-02-07 at 04:18 -0800, John wrote:
> > Instead I've annoyed you and gotten frustrated
> > it's pretty clear we don't mix well, and probably would just be
> > frustrating for both of us.
> I'm sorry you feel that way. For the record I've tried to answer your
> questions as direct as I can, and don't believe I've expressed any
> frustration or annoyance.

It is how I read it — I suppose lacking body language and tone of
voice, I read too much into the words you used and how they were
written, based on how people I have known have used the same language
in person.

> There are no other reports of problems with this feature (currently,
> and in the past), it works in my own setup, and the code involved is
> relatively simple (check domain name, if it matches an alias then
> redirect). With this in mind my assumption is that it is more likely
> a problem with the setup.
> I have a certain amount of time I can provide for support. The scope
> of the plugin means it is greatly affected by a wide range of
> problems outside of the plugin itself. Experience has shown that
> these are often big time sinks, and I try and avoid those.

That is fair.

> With real URLs I can make a few simple checks for obvious problems.
> For example, the vast majority of issues are caused by over-zealous
> security software, or caches. Your site did have some security
> issues, so that further added to my assumption.
> I am not saying the plugin is free of problems and I will fix known
> bugs, or try to make allowances to avoid problematic hosts (within
> limits).
Thank you for clarifying.

I will try and investigate further on my own to figure out why things
are not working on my hosting with the sitealias, if for no other
reason
than it irks me that something that should be quite basic is an issue,
and if my hosting is doing something weird, I'd like to know about.

**Comment by danielfdickinson** [comment]
> Also, I will add, the plugin provides different ways of achieving the
> same result as some methods don't work on some environments.

For that I would suggest the help/information text is a little
over-zealous in recommending a particular way of doing things (such as
coming out quite strongly for using site aliases instead of regex
redirects). I understand when it is possible to use site aliases that
that there reasons to prefer site aliases, but it's not always an
option.
