### ISSUE TITLE
Add already-disabled redirects?

### ISSUE THREAD

**Issue by wescouch** [johngodley/redirection#2747]
### Summary

Hi, I'm trying to add some already-disabled redirects for a client that can be turned on in a few days when needed.

### Actual Behavior

I was hoping to use one of two options:

1. Import redirects with disable turned on
2. Create a new group, disable the group, import redirects to this disabled group

### Steps to reproduce

I tried the disabled group route, but redirects that are categorized into a group like that still work unless each redirect is set to disabled. Is this intended? Is there a way to have an entire group of redirects disabled without going on a per-redirect basis or select all -> disable? Thanks in advance!

![redirection-group-disabled](https://user-images.githubusercontent.com/19677687/107073547-bc840c00-67a4-11eb-8e54-9d4d572b016d.PNG)

### Environment

Browser: Google Chrome Version 88.0.4324.146 (Official Build) (64-bit)
WordPress version: 5.5.3
Redirection version: 5.0.1

**Comment by johngodley** [comment]
Disabling a group will disable all redirects in that group.
