### ISSUE TITLE
Can not leave "Source URL" with blank when use "Auto-generate URL"

### ISSUE THREAD

**Issue by runbing** [johngodley/redirection#275]
Hi john,

First, thanks for your amazing work.

I'd like use the "Auto-generate URL" to generate redirect urls. before I upgrade to the latest version (2.6.6), just type a link into "Target URL" field and click the "Add Redirect" button, I can get a redirect url with hex automatically.

But the latest version make me confused, when I try to do the same thing, I found the "Add Redirect" button was disabled, is this a bug or just my mistake? Thank you very much!

regards

**Comment by johngodley** [comment]
Ooops, yeah, fixed with d6f9df603786ebbc0aeee06e21e9c61d3747286c

**Comment by runbing** [comment]
On version 4.2.3 this problem happening again, could you please check it again?
