### ISSUE TITLE
JSON Import not working

### ISSUE THREAD

**Issue by small-fork** [johngodley/redirection#2751]
Apologies if I have missed this being covered. I did search the tickets and the Wordpress Repository support forum but very well may have missed something.

### Summary

I'm attempting to import redirections in the JSON format as I want to include titles from another plugin. I've tried following the format given on the [doc page for JSON Import/Export](https://redirection.me/developer/json-export/), as well as exporting my current redirects and following that format (there seem to be slight variances between the doc page and what is exported - possibly only the inclusion of "Modulename"). However, it always results in the message:

"Finished importing
Total redirects imported: 0
Double-check the file is the correct format!"

### Actual Behavior

No redirects are imported. This is the case even if directly copying the example JSON on the docs page and attempting to import that.

### Environment
Browser: Chrome
Version: 88.0.4324.146
Wordpress: 5.6.1
Redirection: 5.0.1

I've attached the two JSON texts (removed my specific URLs). It wouldn't let me upload as a JSON file, so I just have them as txt files. I also, as mentioned, tested using exactly what's present on the docs page.

[Version1.txt](https://github.com/johngodley/redirection/files/5937714/Version1.txt)
[Version2.txt](https://github.com/johngodley/redirection/files/5937715/Version2.txt)

Thank you so much!

**Comment by johngodley** [comment]
The JSON needs to be valid:

https://jsonlint.com/

**Comment by small-fork** [comment]
@johngodley Sorry, I'm confused. If I even paste in exactly the example from https://redirection.me/developer/json-export/ that validation site throws errors back:

Error: Parse error on line 34:
..."enabled": true	}, ]}
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got ']'

I'm not savvy enough to understand what needs to be corrected. I was working off of the given example, and also tried basing it off of my own export. I'd appreciate some guidance and apologize for my lack of experience with this.

**Comment by johngodley** [comment]
The documentation had an extra comma. I've removed this from the documentation.

Exporting a JSON file and then re-importing should work fine.

**Comment by small-fork** [comment]
@johngodley thank you! I'm trying to import redirects from the plugin "Pretty Links" which only exports as a CSV. So I'll have to construct my own JSON as I want to preserve the titles from the Pretty Links. I appreciate your time!

**Comment by johngodley** [comment]
Is that plugin available to download? If it is appropriate I can look at building an importer for it.

**Comment by small-fork** [comment]
@johngodley  Yes it is. The basic version is in the repository: https://wordpress.org/plugins/pretty-link/

The exporting available doesn't include the hits. Those seem to be in a separate table of "clicks". Being able to bring in the hit count would be great, but if nothing else, being able to pull in the redirects with their existing titles would be a huge help.

**Comment by johngodley** [comment]
Thanks. I'll look at that for the next release.

**Comment by small-fork** [comment]
Thank you @johngodley - much appreciated.

**Comment by small-fork** [comment]
@johngodley Apologies for the re-reply, but I was just wondering if the timeline for such an addition would be a matter of months or weeks or what? Please know I'm not asking out of an expectation of prompt turn-around—you provide this and other plugins for free and I have no presumption of adding something like this being simple. I only ask so that I can gauge whether to keep fiddling about with this or if it's possible that an importer would become available before my site goes live.

If you have no idea atm, that is more than okay as well! I really do appreciate your time.

**Comment by johngodley** [comment]
I haven't set aside time at the moment so I can't really say, but it's unlikely to be in the next few weeks.

**Comment by small-fork** [comment]
Hi again @johngodley - hope it's okay to tack a follow up on here. If not, let me know if I should post elsewhere.

1. I was wondering if it's at all possible to import logs for imported redirections? (I do see that hits are importable with the actual redirects import, but not the other data available in the logs)
2. Is it possible to partially update already imported redirects (like if you wanted to change the hit number or other aspects for multiple in bulk ?)

Thank you again!

**Comment by johngodley** [comment]
There is no facility to import logs.
An import adds new entries, it doesn't update existing ones.
