### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by julincicel93** [johngodley/redirection#2752]
```
Uncaught SyntaxError: Unexpected identifier https://moshammer-automotive.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3 2
```

Plugin: 5.0.1
WordPress: 5.6.1 (single)
PHP: 7.4.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
JavaScript: https://moshammer-automotive.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://moshammer-automotive.com/wp-json/

**Comment by johngodley** [comment]
Your plugin is corrupt. You will need to install it again.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
