### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by pferdetermine** [johngodley/redirection#2754]
the plugin says that I need to update the database. When I try to do so, the following error occurs:
"Etwas ist schiefgelaufen 🙁
<strong>FEHLER:</strong> That action is currently not allowed.<br /><br /> (wp_die)

Etwas ging schief beim Upgrade von Redirection.
"....

I disabled all Caching- and Security-Plugins.... What can I do?
```
Plugin: 5.0.1
WordPress: 5.1.1 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
JavaScript: https://www.petra-koepcke.de/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://www.petra-koepcke.de/wp-json/
Query: ?page=redirection.php&sub=options

Error: <strong>FEHLER:</strong> That action is currently not allowed.<br /><br />

 (wp_die)
Raw: {"code":"wp_die","message":"<strong>FEHLER:<\/strong> That action is currently not allowed.<br \/><br \/>\n\n","data":{"status":"403"},"additional_errors":[]}
```

**Comment by johngodley** [comment]
The problem is shown in the message:

`<strong>FEHLER:</strong> That action is currently not allowed.<br /><br />`

That is from your website and is not from the plugin. You will need to find out what is returning it.

**Comment by pferdetermine** [comment]
it was one of the plugins... I deactivated everything and the update worked. Now I activated everything again...
