### ISSUE TITLE
Redirect not working with Oxygen Builder

### ISSUE THREAD

**Issue by Pasadena-SEO** [johngodley/redirection#2758]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary
Redirection not working with page built with Oxygen Builder

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do
I'm using a relatively new but extremely cool page builder: OXYGEN BUILDER
I'm sending traffic through a clickmagick tracking link to the landing page which is built with Oxygen
I want the option of being able to redirect incoming traffic to a target page (vendor's URL)

### Actual Behavior
Tracking link path to landing page and outbound links works correctly
When I create a redirect --- nothing happens -- ie the tracking link points to the landing page but does not redirect to the vendors sales page.

### Steps to reproduce

here's my clickmagick link:  https://www.clkmg.com/fromthiscentury/leanbelly3x

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
This is a new WP install (2 weeks ago), Plugins are Oxygen Builder, Redirection and not much else
Problem is the same on Firefox, Chrome, and Safari

**Comment by johngodley** [comment]
Can you give an example of a URL on your site that is not redirecting?

**Comment by Pasadena-SEO** [comment]
Hi John,
Thank you for your quick response.
Attached txt  (.rtf) file has site details, login creds and links for my oxygen test site.
I'm not sure where the problem is but this is a fresh installation of WP so it should be clean. But the problem could be compatibility with Oxygen Builder since this is a fairly new page builder.
I noticed on 'redirection' setup that there was a non-critical error - not connecting to a REST API - but message said Redirection should work anyway.
I appreciate any ideas you have to fix this.
Thanks,Bill
Please respond to my new email:bill@from-this-century.com


    On Tuesday, February 9, 2021, 10:36:16 PM PST, John <notifications@github.com> wrote:  
 
 


Can you give an example of a URL on your site that is not redirecting?

**Comment by johngodley** [comment]
You've posted this to a public site.

Rather than including login details to a site can you give me an example URL on your site that is not redirecting, and show the redirect you created for this? I don't understand what part of your issue is related to Redirection.

**Comment by Pasadena-SEO** [comment]
Hi John,Sorry for making this overly complicated.
Here's the scenario.
external link to inner page:  Test Links - My WordPress


| 
| 
|  | 
Test Links - My WordPress


 |

 |

 |




Here's the redirect (redirection plugin)

/test-links
https://6dcef84pr7f6x8gozex4zyel05.hop.clickbank.net/?tid=%5Bcm_s1%5DEdit | Delete | Disable | Check Redirect
I set up a second redirect, this time from /test-links/  (note closing '/')
They both work when I go to the page URL either oxygensandbox '.' besthealthsupplements '.' info/test-links or /test-links/
But redirect does not fire when I use the click magic tracking link
https://www.clkmg.com/fromthiscentury/oxy-redirect

where the primary url is:https://oxygensandbox.besthealthsupplements.info/test-links/?cm_s1=[clickid]

So I'm not sure if this is a Redirection problem or a ClickMagick link problem.
Any thoughts?
Thanks,Bill





| 
| 
|  | 
Test Links - My WordPress


 |

 |

 |




| 
| 
|  | 
Test Links - My WordPress


 |

 |

 |






    On Friday, February 12, 2021, 02:30:44 AM PST, John <notifications@github.com> wrote:  
 
 


You've posted this to a public site.

Rather than including login details to a site can you give me an example URL on your site that is not redirecting, and show the redirect you created for this? I don't understand what part of your issue is related to Redirection.

**Comment by johngodley** [comment]
> where the primary url is:https://oxygensandbox.besthealthsupplements.info/test-links/?cm_s1=[clickid]

Ok, then your redirect needs to match this. You can use the 'ignore query parameters' option.

**Comment by Pasadena-SEO** [comment]
OK that works for the redirect 
but since it's 'ignore' it drops the query parameter.
 tried this with 'ignore' and with 'ignore and pass variable'

Will let you know if I find a solution.

Thanks again,
Boill
