### ISSUE TITLE
Historical post URL changes not being honoured

### ISSUE THREAD

**Issue by Webreaper** [johngodley/redirection#276]
Wordpress tracks modified URLs for articles, and auto-redirects to them, so for example, changing:

     /2017/06/how-to-fix-my-car

to

     /2017/06/fix-car

both URLs should work. 

Since I installed the Redirection plugin, this no longer works, and there are many 404s on the site now that weren't happening before. I went through and started to manually create redirections for all of them, but realised that deactivating the plugin just fixes them all. 

So it looks like something in the Redirection plugin is interfering with the WP redirection process.

This is using the latest Wordpress and Redirection plugin: 2.6.6, WP4.8.

**Comment by johngodley** [comment]
Yes, Redirection disables the WP check as it assumes you want it to handle redirects, and having both running could cause some problems. I've been meaning to add something to import existing WordPress redirects.

**Comment by Webreaper** [comment]
Okay, makes sense. 

Unfortunately that kills redirection for me as a plugin; what I want (need) is something to allow me to write a custom URL and have it direct specifically to a post or archive, but if I enable redirection and a bunch of other modified posts now go to 404s, it breaks half my site. :(
