### ISSUE TITLE
Problem starting Redirection 5.0

### ISSUE THREAD

**Issue by aps-ohnmar** [johngodley/redirection#2761]
Plugin: 5.0
WordPress: 5.3.3 (single)
PHP: 7.3.3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
JavaScript: https://dev.mens-svenson.net/content/plugins/redirection/redirection.js?ver=5.0-3451e9c29beac3055f61a8e45f1bf15e
REST API: https://dev.mens-svenson.net/wp-json/

**Comment by johngodley** [comment]
The plugin is not loading properly:

https://dev.mens-svenson.net/content/plugins/redirection/redirection.js?ver=5.0-3451e9c29beac3055f61a8e45f1bf15e

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
