### ISSUE TITLE
Siteground Migration from cPanel to Site Tools

### ISSUE THREAD

**Issue by dbetlow** [johngodley/redirection#2763]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

All of our redirects using Wordpress engine stopped working after Siteground switched us from cPanel to Site Tools.

### Actual Behavior

If I create a new redirect, it works, but all of our existing redirects don't work.  I tried exporting them as .htaccess and importing them into a new Apache group, with the option to use .htaccess file specified, but these don't seem to work either.  The .htaccess file does not appear to be getting updated.  If I paste in the path to the Options page and click Update, the path doesn't stick.  The permissions of the .htaccess file are 644.
![image](https://user-images.githubusercontent.com/42045043/107673112-aaeaaa80-6c63-11eb-8742-6166ad9f0d8e.png)

### Steps to reproduce

Host updated back end management tools.

### Environment

Using latest version of Chrome in incognito window with Wordpress 5.5.3 and Redirection 5.0

**Comment by johngodley** [comment]
Can you explain what part of the above is related to Redirection? I'm not sure what you are reporting.

**Comment by dbetlow** [comment]
A) the Redirection plugin doesn't seem to survive this migration of a very popular hosting platform

B) Was looking for a way to get all of our redirects working again without having to manually create each one again.  Realized that the folder path gets blanked out, but it was working anyway with updating .htaccess file.  Switched all the redirects to the Apache group manually and that fixed it.  The import didn't work, but that could have been because the existed twice.

**Comment by johngodley** [comment]
Ok, I don't think there's much I can do here as I can't control the site migration. You'll need to bring that up with the host provider.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
