### ISSUE TITLE
Redirects don't seem to work for PDF posts

### ISSUE THREAD

**Issue by cincolaters** [johngodley/redirection#2764]
Hello,

Love the plugin. Have a question though -

We are updating a number of blog post publish-on dates due to a migration issue. All of the blogs migrated over and inherited the date of the migration, not the actual date of publishing. So, we're going back and manually changing these dates. This changes the permalink, naturally. 

Here's the problem: Many of these wrongly dated blog posts simply open up a PDF file. When the publish-on date is changed, the redirect works great, but no longer opens the associated PDF. 

Here is an example:
This is an existing blog post that leads to a PDF. The publish-on date is wrong, so we'll need to change it. It was actually published in 2014 - not 2020.
https://everytexan.org/2020/03/12/new-report-shows-surprise-medical-bills-taking-toll-on-texans-little-known-practice-of-balance-billing-takes-advantage-of-consumers-during-medical-emergencies/

If I were to change the publish date, the URL updates and redirects - but no longer opens this PDF. It's more a less just a blank screen. Like this: https://everytexan.org/2017/01/23/put-on-the-brakes-congress-the-damage-in-texas-if-congress-repeals-the-affordable-care-act-without-an-immediate-replacement/
This post used to be: https://everytexan.org/2020/03/12/put-on-the-brakes-congress-the-damage-in-texas-if-congress-repeals-the-affordable-care-act-without-an-immediate-replacement/ (had the wrong date in the URL, so we changed it)

Does that make sense? I don't know if I'm explaining it well enough. 

Thank you for your consideration

**Comment by johngodley** [comment]
I'm unsure which part of the above is related to Redirection. Can you explain what redirect you have created and how it's not working?

**Comment by cincolaters** [comment]
Thanks for replying. I'll do my best to explain better:

We've got a blog post with URL: https://everytexan.org/2020/03/12/put-on-the-brakes-congress-the-damage-in-texas-if-congress-repeals-the-affordable-care-act-without-an-immediate-replacement/
Upon clicking this post, it opens up a PDF - https://everytexan.org/images/HW_2017_01_ACA_RepealOutcomes.pdf

When we modify the publish date, the URL changes to: https://everytexan.org/2017/01/23/put-on-the-brakes-congress-the-damage-in-texas-if-congress-repeals-the-affordable-care-act-without-an-immediate-replacement/
But the PDF link seems to have gotten lost. Would redirection know that the updated URL with the new date to open the PDF linked from the old/out of date URL that was updated?

Maybe I am using the plugin wrong?

**Comment by johngodley** [comment]
Sorry, I'm still not clear.

Which part is using Redirection?

https://everytexan.org/2020/03/12/put-on-the-brakes-congress-the-damage-in-texas-if-congress-repeals-the-affordable-care-act-without-an-immediate-replacement/ is being redirected to https://everytexan.org/images/HW_2017_01_ACA_RepealOutcomes.pdf - this is not Redirection

https://everytexan.org/2017/01/23/put-on-the-brakes-congress-the-damage-in-texas-if-congress-repeals-the-affordable-care-act-without-an-immediate-replacement/ is a page on your site.

How have you used Redirection here? Have you created a redirect?

**Comment by johngodley** [comment]
> But the PDF link seems to have gotten lost

Lost from where?

**Comment by cincolaters** [comment]
I'm new to Redirection and clearly not sure what I'm doing.

I guessed that the[ link that redirects](https://everytexan.org/2020/03/12/put-on-the-brakes-congress-the-damage-in-texas-if-congress-repeals-the-affordable-care-act-without-an-immediate-replacement/) to the [PDF file](https://everytexan.org/images/HW_2017_01_ACA_RepealOutcomes.pdf) was Redirection. But it is not. So, I'm going to try to figure out what is going on here. 

I think the puzzle I need to solve is how can I edit a URL that is redirecting to a PDF, and keep it directing to the PDF and not creating a blank page on the site. 

I realize you provide your time and services at no charge, and I don't want to waste any of it! I'll donate to the plugin though. I'm appreciative of you replying so quickly! I think this is a larger issue than what I thought it might be at first

**Comment by johngodley** [comment]
Redirection will only redirect things you tell it to redirect, and these will be listed on the admin page. Outside of that it's not caused by Redirection, and it's harder to track down. Maybe it's in your .htaccess file, or maybe it's something that Flywheel can help you with.

**Comment by cincolaters** [comment]
Thank you, John. I'll ask Flywheel. Cheers
