### ISSUE TITLE
Import from CSV only imports a specific line

### ISSUE THREAD

**Issue by robinraymann** [johngodley/redirection#277]
[beblog redirections.zip](https://github.com/johngodley/redirection/files/1196637/beblog.redirections.zip)

### Summary

Hi, I'm trying to add some redirections from dead links to our main site by uploading a csv file but for some reason it only imports line 154 and nothing else.  Maybe I'm just generating the csv file incorrectly?

### Actual Behavior

Nothing apart from line 154 is imported from the CSV file

### Environment

WordPress Version 4.8
Redirection Version 2.6.2

**Comment by johngodley** [comment]
The attached file is a semicolon separated file, not comma. You will need to generate the file again using commas as the separator.
