### ISSUE TITLE
table dosen't exist issue while clone website

### ISSUE THREAD

**Issue by patidarmangal** [johngodley/redirection#2771]
I always find this issue when I make a site clone.
The following errors were found :
Could not make the query numbered : 0
MySQL Error No : 1146
MySQL Error : Table 'dbname.wp_redirection_items' doesn't exist

Then to solve this each time I need to import all the related plugin table into the database.
so can you help me or suggest me why this error occur repeatedly.

**Comment by johngodley** [comment]
> I always find this issue when I make a site clone.

You clone does not appear to be including all database tables. You will need to contact the clone support.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
