### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by kursadsert** [johngodley/redirection#2777]
```
Plugin: 5.0.1
WordPress: 5.6.2 (single)
PHP: 7.4.14
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
JavaScript: https://www.ugurpano.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://www.ugurpano.com/wp-json/
Query: ?page=redirection.php&sub=support

Error: Unexpected token { in JSON at position 1 (SyntaxError)
Raw: 9{"status":[{"id":"db","name":"Database tables","status":"good","message":"All tables present"},{"name":"Valid groups","id":"groups","message":"Valid groups detected","status":"good"},{"name":"Valid redirect group","id":"redirect_groups","message":"All redirects have a valid group","status":"good"},{"name":"Post monitor group","id":"monitor","message":"Post monitor group is valid","status":"good"},{"name":"Site and home protocol","id":"redirect_url","message":"Site and home are consistent","status":"good"}],"debug":{"database":{"current":"4.2","latest":"4.2"},"ip_header":{"HTTP_CF_CONNECTING_IP":false,"HTTP_CLIENT_IP":false,"HTTP_X_FORWARDED_FOR":false,"HTTP_X_FORWARDED":false,"HTTP_X_CLUSTER_CLIENT_IP":false,"HTTP_FORWARDED_FOR":false,"HTTP_FORWARDED":false,"HTTP_VIA":false,"REMOTE_ADDR":"88.230.31.146"}}}
```

**Comment by johngodley** [comment]
The number `9` appears on every page of your site and is breaking the plugin.

**Comment by kursadsert** [comment]
how can i solve the problem?


Kimden: John<mailto:notifications@github.com>
Gönderilme: 24 Şubat 2021 Çarşamba 10:34
Kime: johngodley/redirection<mailto:redirection@noreply.github.com>
Bilgi: kursadsert<mailto:galatasaraykrst@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [johngodley/redirection] Redirection Error (#2777)


The number 9 appears on every page of your site and is breaking the plugin.

**Comment by johngodley** [comment]
The problem is not caused by Redirection, so I cant provide support. It is probably a plugin or theme.

**Comment by kursadsert** [comment]
I uninstalled all the plugins and tried one by one. My problem was not fixed?
Kimden: John<mailto:notifications@github.com>
Gönderilme: 24 Şubat 2021 Çarşamba 10:37
Kime: johngodley/redirection<mailto:redirection@noreply.github.com>
Bilgi: kursadsert<mailto:galatasaraykrst@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [johngodley/redirection] Redirection Error (#2777)


The problem is not caused by Redirection, so I cant provide support. It is probably a plugin or theme.

**Comment by johngodley** [comment]
Ok, but as I said, I cannot provide support for this. Maybe your host can help.
