### ISSUE TITLE
404s list not displaying more than 25

### ISSUE THREAD

**Issue by gmdavenport** [johngodley/redirection#278]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

Since the last update of Redirection... The screen option is set to 100, as the max says 100, but only 25 are lists.

### Actual Behavior

Only 25 404s are listed when the screen options are set to list 100

### Steps to reproduce

Just using it
### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Any browser tried them all. Same issue on several wordpress sites, WP 4.8.1, Redirection 2.6.6

**Comment by johngodley** [comment]
Fixed in cf92e5023f6176dbf74aa2229bf777cdadb91737

**Comment by gmdavenport** [comment]
@johngodley Am I suppose to change my code per the link you sent or is there going to be an update soon?

**Comment by johngodley** [comment]
The bug has been fixed in the code contained here. You may update it if you wish, or use the unreleased beta version https://github.com/johngodley/redirection/releases, or wait until it is released to wordpress.org
