### ISSUE TITLE
Redirection & changes in WPML settings

### ISSUE THREAD

**Issue by Datajam** [johngodley/redirection#2780]
### Redirection when language URL was changed in WPML settings

Is there a way to redirect all pages when the WPML settings are changed from 
https://domainname.com/projects/projectname/?lang=de 
to
https://domainname.com/de/projects/projectname/

or simply from 
https://domainname.com/pagetitle/?lang=de 
to
https://domainname.com/de/pagetitle/ 
?

### Actual Behavior

At the moment search engines show the old URL https://domainname.com/pagetitle/?lang=de but the website shows the same page in the main language (french).

### Steps to reproduce

I've installed the Redirection plugin, configured it to track changes on all content types, then changed the URL settings in WPML. On other websites I manage the plugin creates redirections automatically when I change the page title e.g. 

### Environment

Mac OS / Google Chrome Version 87.0.4280.141 / Wordpress 5.6.2 / Redirection Plugin 5.0.1

Thanks for your help. 

Regards. Chris

**Comment by johngodley** [comment]
You will need to create a regular expression:

https://redirection.me/support/redirect-regular-expressions/

It is not possible for this to track when WPML settings are changed.

**Comment by Datajam** [comment]
Hi. Thanks for your super quick reply (thumbs up!). I'll try that. 
Regards. Chris
