### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by Jack-0009** [johngodley/redirection#2781]
Why not add a roll to choose who can use the add-on members?
Because I have a lot of members, and in order to allow some of them to use the plugin, I give them the highest powers, and this may threaten the integrity of the site
So I suggest adding a roll to determine who can use the add-on this would be better security

**Comment by johngodley** [comment]
You can find more information here:

https://redirection.me/developer/permissions/

**Comment by Jack-0009** [comment]
This message has appeared
An E_ERROR error occurred due to line 13 in the file
/home/mangqsxj/public_html/wp-content/plugins/advanced-redirection-permissions/advanced-redirection-permissions.php.
Error message: Uncaught ArgumentCountError: Too few arguments to function
{closure} (), 1 passed in
/home/mangqsxj/public_html/wp-includes/class-wp-hook.php on line 289 and
exactly 2 expected in / home / mangqsxj
/public_html/wp-content/plugins/advanced -redirection-permissions/advanced
-redirection-permissions.php:13
Stack trace:
# 0 /home/mangqsxj/public_html/wp-includes/class-wp-hook.php(289):
{closure} ('edit_posts')
# 1 /home/mangqsxj/public_html/wp-includes/plugin.php(212): WP_Hook->
apply_filters ('edit_posts', Array)
# 2
/home/mangqsxj/public_html/wp-content/plugins/redirection/redirection-capabilities.php(80):
apply_filters ('redirection_cap ...', 'edit_posts', 'redirection_cap ...')
# 3
/home/mangqsxj/public_html/wp-content/plugins/redirection/redirection-admin.php
(88): Redirection_Capabilities :: has_access ('redirection_cap ...')
# 4 /home/mangqsxj/public_html/wp-includes/class-wp-hook.php(287):
Redirection_Admin-> update_nag ('')
# 5 /home/mangqsxj/public_html/wp-includes/class-wp-hook.php(311):
WP_Hook-> apply_filters (NULL, Array)
# 6 /

‫في الجمعة، 26 فبراير 2021 في 1:26 م تمت كتابة ما يلي بواسطة ‪John‬‏ <‪
notifications@github.com‬‏>:‬
