### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Jack-0009** [johngodley/redirection#2782]
This message has appeared When I was trying to add the roller
https://redirection.me/developer/permissions/
An E_ERROR error occurred due to line 13 in the file /home/mangqsxj/public_html/wp-content/plugins/advanced-redirection-permissions/advanced-redirection-permissions.php. Error message: Uncaught ArgumentCountError: Too few arguments to function {closure} (), 1 passed in /home/mangqsxj/public_html/wp-includes/class-wp-hook.php on line 289 and exactly 2 expected in / home / mangqsxj /public_html/wp-content/plugins/advanced -redirection-permissions/advanced -redirection-permissions.php:13
Stack trace:
# 0 /home/mangqsxj/public_html/wp-includes/class-wp-hook.php(289): {closure} ('edit_posts')
# 1 /home/mangqsxj/public_html/wp-includes/plugin.php(212): WP_Hook-> apply_filters ('edit_posts', Array)
# 2 /home/mangqsxj/public_html/wp-content/plugins/redirection/redirection-capabilities.php(80): apply_filters ('redirection_cap ...', 'edit_posts', 'redirection_cap ...')
# 3 /home/mangqsxj/public_html/wp-content/plugins/redirection/redirection-admin.php (88): Redirection_Capabilities :: has_access ('redirection_cap ...')
# 4 /home/mangqsxj/public_html/wp-includes/class-wp-hook.php(287): Redirection_Admin-> update_nag ('')
# 5 /home/mangqsxj/public_html/wp-includes/class-wp-hook.php(311): WP_Hook-> apply_filters (NULL, Array)
# 6 /

**Comment by johngodley** [comment]
Have you typed everything correctly?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
