### ISSUE TITLE
What are these weird redirections?

### ISSUE THREAD

**Issue by ooker777** [johngodley/redirection#2783]
I really don't know how these redirections show up. Can you take a look?

![image](https://user-images.githubusercontent.com/6695517/109310976-c8309300-7877-11eb-99c0-cffa0dbef875.png)

WP version 5.6.2, Redirection version 5.0.1

**Comment by johngodley** [comment]
See monitoring options: https://redirection.me/support/options/

**Comment by ooker777** [comment]
Do you mean the URL monitor option: ![](https://redirection.me/wp-content/uploads/2017/11/redirection_monitor_options-768x168.png)?

Well yes I selected "Monitor change to trash", and for the last couple days I did trash some posts and reorganize my categories and tags. But (1) they are not that much, and (2) the URL should be the old links, not random sequences like that?

**Comment by johngodley** [comment]
Those are posts on your site that have been picked up by the monitor. I don't know what they are, but they are likely the result of some actions you have performed. They are not random sequences, but a post title for something that has been deleted (even if you don't know what that is).

**Comment by ooker777** [comment]
does it track for changes in category? I put many categories as a child of another one, but I need to add redirects manually. It doesn't automatically create redirects like posts

**Comment by johngodley** [comment]
It doesn't track changes in categories.

**Comment by ooker777** [comment]
I wonder why you don't make it track category and tag changes too?
