### ISSUE TITLE
REDIRECTION NOT WORKING WHEN CAPS IS USED

### ISSUE THREAD

**Issue by vvolz** [johngodley/redirection#2784]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

When CAPS is on, the page doesn't redirect.

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

It shouldn't matter if CAPS is on, pages should still redirect.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

Try this: 
https://blending.education/library-k12/       **works**
https://blending.education/LIBRARY-K12/   **gives error page**

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Mac Catalina, Safari, Chrome, Firefox latest versions

**Comment by johngodley** [comment]
It does matter as they are different URLs. There are options for case sensitivity.

https://redirection.me/support/matching-a-url/

**Comment by vvolz** [comment]
I've turned on Ignore Case now it works.
