### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by jardelcavalcante** [johngodley/redirection#2785]
```
Uncaught SyntaxError: Unexpected identifier https://www.oskaras.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3 2
```

Plugin: 5.0.1
WordPress: 5.6.2 (single)
PHP: 7.4.15
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
JavaScript: https://www.oskaras.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://www.oskaras.com/wp-json/

**Comment by johngodley** [comment]
Your plugin is corrupt. This file contains invalid characters:

https://www.oskaras.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3

**Comment by jardelcavalcante** [comment]
Dear John,
I am using a translator.

I deleted and installed the plugin again
same error appears see the print.

https://www.oskaras.com/img//2021/02/redirection1.jpg

**Comment by johngodley** [comment]
Your plugin file still contains corrupted characters. I don't know how you are installing it, but until the file is uncorrupted you won't be able use the plugin:

![image](https://user-images.githubusercontent.com/1277682/109389877-594e4b00-7906-11eb-8420-7388a5861a98.png)

**Comment by jardelcavalcante** [comment]
Thanks Jonh for the remark
I uploaded it again via ftp, cleared the Cloudflare cache, page speed Ninja and cloud server. Then the error is gone.
