### ISSUE TITLE
GUI with iPad problems after latest update

### ISSUE THREAD

**Issue by rruyter** [johngodley/redirection#2787]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

on at least the log tab, but also on some other tabs, the GUI shows issues. Text and fields overlap eachother.

### Actual Behavior

This behavior makes it cumbersome to use the interface.

### Steps to reproduce

go to the log tab of redirects. And view the GUI.

### Environment

As of 20210228. iPad Air, Wordpress, woocommerce, redirects, safari all latest versions

How can I upload a screenshot with an iPad here please?

**Comment by johngodley** [comment]
The plugin is not really aimed for use on an iPad. It may be improved in the future.

**Comment by rruyter** [comment]
Ah, okay. Well the interface worked beautifully before and after the update there are some issues. So that made me think it was also css-ed for iPad.

Looking forward to the improvement. It’s a invaluable tool already. Thanks.
