### ISSUE TITLE
Question regarding multipe redirections

### ISSUE THREAD

**Issue by udarts** [johngodley/redirection#2788]
I am currently using redirection (v:5.0.1) for one of my website and loving it.
But I have one question.

I need to add 800 redirections (don't ask why), but it seems I can only add 1 at the time.

I tried importing a csv file, but that didn't do the trick.
It seems on the redirections tab, the source-url can only have 1 url at the time.

Would like to know how to do this

**Comment by johngodley** [comment]
> that didn't do the trick.

Why not?

**Comment by udarts** [comment]
Because it only imported 1, but I am 100% sure that there are many more that needed to be imported.

The csv file (origionally google spreadsheet) had 1 column, and about 800 rows with urls (without domain naam, so just /rest-of-url-that-needs-to-be-removed)

**Comment by johngodley** [comment]
The correct format for the CSV can be found here:

https://redirection.me/support/import-export-redirects/

**Comment by udarts** [comment]
Hmm, I see that uses target url, but what I need to do is set all those urls (source) as 404 redirect (410 gone).

**Comment by johngodley** [comment]
Ok, you didn't mention that before. You will need to use the JSON format for that as the CSV format doesn't support it.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
