### ISSUE TITLE
Invalid redirect details (127)

### ISSUE THREAD

**Issue by taipan666** [johngodley/redirection#279]
Hi,

  Thanks for the good work.
  Do you know what problem is lying under this : 

Error: Invalid redirect details (127)
Raw: {"error":"Invalid redirect details (127)"}

The redirection can not be set...

Any clue about this? Thank you!

**Comment by johngodley** [comment]
Can you supply the full error details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
