### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by Astrid-dots** [johngodley/redirection#2790]
Plugin: 5.0.1
WordPress: 5.6.2 (single)
PHP: 7.3.7
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
JavaScript: https://www.simplidots.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://www.simplidots.com/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This is almost certainly caused by another plugin.
