### ISSUE TITLE
Regex Import Problem

### ISSUE THREAD

**Issue by Jfidler22** [johngodley/redirection#280]
Trying to import redirects via CSV for WordPress, and we can't get it to accept regex statements.

We have to manually tick the box in each individual redirect.  

What's the format for importing [Regex 0=false, 1=true] Regex true???

Driving us crazy!!!

Please help!

Jeff Fidler

![redirects](https://user-images.githubusercontent.com/30733324/28981456-e6f7d844-791f-11e7-83c9-fb55a4d3ffe6.JPG)

**Comment by johngodley** [comment]
Fixed in 2ade62528597ff07fcc3bcc4a3b3592f2946cf09

**Comment by Jfidler22** [comment]
Sorry - could you provide some direction here?  

Jeff

**Comment by johngodley** [comment]
A bug was fixed (the one in the link) and will be included in the next release. It's now available here if you want to manually install a beta release https://github.com/johngodley/redirection/releases/tag/2.7b1
