### ISSUE TITLE
"Unexpected token < in JSON at position 0 (SyntaxError)" Message When Using Search Field

### ISSUE THREAD

**Issue by algis100** [johngodley/redirection#2802]
Hi. Whenever I enter something in the search field in the Redirection plugin and click on the "Search URL" button I get the error in the attached screenshots.

I am using Google Chrome version 88.0.4324.190 (Official Build) (64-bit), WordPress version 5.6.2 and Redirection plugin version 5.0.1

![Redirections Plugin Error Screenshot III](https://user-images.githubusercontent.com/58431940/110462052-1d667300-80c8-11eb-80ce-fa11c771e22d.jpg)
![Redirections Plugin Error Screenshot II](https://user-images.githubusercontent.com/58431940/110462055-1dff0980-80c8-11eb-9b67-5f153d1e1d23.jpg)
![Redirections Plugin Error Screenshot I](https://user-images.githubusercontent.com/58431940/110462061-1e97a000-80c8-11eb-841f-65ac1219bfe8.jpg)

**Comment by johngodley** [comment]
The message contains the relevant information: `access denied goddady website firewall`

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
