### ISSUE TITLE
all the subpages show the same content

### ISSUE THREAD

**Issue by matteino55** [johngodley/redirection#281]
### Summary

Since the last wordpress update, all the Redirection subpages show exactly the same content.
see here: http://imgur.com/a/iVgUu

### Actual Behavior

The only subpage which seems to behave correctly is the last one (Support)
see here: http://imgur.com/a/xCWZ9

### Steps to reproduce

I just opened the Redirection tab and noticed I can't edit/add/remove redirections anymore

### Environment

I tried using firefox for mac and latest wordpress version.
Thank you

**Comment by johngodley** [comment]
Are you using the latest version of the plugin? Can you try another browser?

**Comment by matteino55** [comment]
Hello John,
yes, I'm using version 2.6.6 and I've also tried with other browsers 
(like Chrome)

Unfortunately the problem remains...
Thank you for your help!

**Comment by johngodley** [comment]
Can you try this beta release?

https://github.com/johngodley/redirection/releases/tag/2.7b1

**Comment by matteino55** [comment]
Yes... But will I lose the current redirections?

**Comment by johngodley** [comment]
No, it's just an new version of the plugin

**Comment by matteino55** [comment]
I tried manually installing the latest beta but I receive this message: 
"/Destination folder already exists"

/See here for the screenshot: https://imgur.com/a/qZghQ

What can I do in order to update the plugin without losing the current 
redirections?

Thank you in advance

**Comment by johngodley** [comment]
You'll need to delete the existing plugin directory. This doesnt delete your data, just the plugin files.

**Comment by matteino55** [comment]
Thank you!

I renamed the old directory, uploaded/installed the beta version, and 
now I can see all the redirections again.

What should I do now? Just leave the new plugin installed (will it 
update automatically when you release future versions)?

Thanks for your help

**Comment by johngodley** [comment]
If everything works fine then I'll close this issue. The plugin will get updated normally in the future
