### ISSUE TITLE
Passthrough to #tab-anchor results in 404

### ISSUE THREAD

**Issue by zee3h** [johngodley/redirection#2819]
### Summary

I am trying to create a passthrough to a URL that points to a tab within a page, i.e. /forum/#tabs_desc_31427_1. I would like to mask it with /forum/cfa rather than using the original anchor name (which I can't change).

### Actual Behavior

Setting it as a passthrough results in a 404 error. Setting this as a regular redirection works though.

### Steps to reproduce

Here are the settings I used:
![Screenshot 2021-03-16 at 21 01 56](https://user-images.githubusercontent.com/80262866/111379299-df0a1e80-869a-11eb-8b39-926d02930cc4.png)

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Browser: Chrome
Browser version: Version 89.0.4389.82 (Official Build) (x86_64)
Wordpress version: 5.7
Redirection version: 5.0.1

**Comment by johngodley** [comment]
It's not possible to do that, you can only do a whole page not part of a page.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
