### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by actiontours** [johngodley/redirection#2821]
Plugin: 5.0.1
WordPress: 5.7 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
JavaScript: https://actiontours.com.et/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://actiontours.com.et/wp-json/

**Comment by johngodley** [comment]
Please follow the instructions and check your developer console. This is almost certainly caused by another plugin
