### ISSUE TITLE
redirecting from nonsecure site to new subdomain

### ISSUE THREAD

**Issue by garthmoore** [johngodley/redirection#2822]
To help track problems please follow this template. If you can provide screenshots then that will help.

 

### Summary

We just migrated the site https://ihep.org from Drupal to Wordpress, but we left the former Drupal website live for two microsites they had under the domain. We changed the old Drupal site to sites.ihep.org for these sites to stay active.
 
New site: https://ihep.org
Microsites: https://sites.ihep.org/postsecdata (formerly http://www.ihep.org/postsecdata) and https://sites.ihep.org/cpaguidebooks (formerly http://www.ihep.org/cpaguidebooks)
 
The issue we’re having is the client has a number of links for the PostSecData microsite that no longer work with the domain change, so for example:

http://ihep.org/sites/default/files/uploads/postsecdata/docs/resources/postsecdata_comments_on_ipeds_outcome_measures_trp_dec_2014.pdf (a 404 page) 

should go to 

https://sites.ihep.org/sites/default/files/uploads/postsecdata/docs/resources/postsecdata_comments_on_ipeds_outcome_measures_trp_dec_2014.pdf

### Actual Behavior

Trying to set http://ihep.org/sites/default/files/uploads/postsecdata/docs/resources/*

to go to 

https://sites.ihep.org/sites/default/files/uploads/postsecdata/docs/resources/*

### Steps to reproduce

The issue we're having in WordPress is we can't make these wildcards work, also wonder if our newly secures domain is throwing the 404 for https://www.ihep.org instead of http://www.ihep.org

### Environment

Chrome 89, Mac, redirection DB 4.2, WP 5.6

**Comment by johngodley** [comment]
Please see https://redirection.me/support/problems/url-not-redirecting/ for problems redirecting PDFs.

Also, wildcards aren't allowed. You can use a regular expression: https://redirection.me/support/redirect-regular-expressions/

**Comment by garthmoore** [comment]
Thanks for the docs. I used a regex, see below. I wonder if the pdf file extension is the issue, but shouldn't' with a regex expression: 

^http://www.ihep.org/sites/default/files/uploads/postsecdata/docs/resources/*
to 
https://sites.ihep.org/sites/default/files/uploads/postsecdata/docs/resources/*

**Comment by johngodley** [comment]
That's still not a regular expression. Please take a look at the link I posted above. You should not put the domain name in the source.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
