### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by robeadam** [johngodley/redirection#2823]
### Summary
I'm building a new server to self-host our website (currently hosted at wpengine) and just installed the redirection plugin as we have currently on our existing server.  I'm getting error's showing the REST API is unavailable but when I go to ```http://<domain>/?rest_route=/ ``` I get data so it seems that it is enabled and working.  Plus the plugin tells me I need to upgrade my database form 2.4 to 4.2 and when I try I get "Database error" 

### Actual Behavior
Redirection is not working, pages on our site are unavailable

### Steps to reproduce
Enabled plugin, got error

### Environment

```
Plugin: 5.0.1
WordPress: 5.6.2 (single)
PHP: 7.2.24
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
JavaScript: http://<domain>/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: http://<domain>/wp-json/
Query: ?page=redirection.php&sub=support

Action: http://<domain>/wp-json/redirection/v1/plugin/data/ POST
Params: {"upgrade":"skip"}
Code: 404 Not Found

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

Thanks,
Robert

**Comment by johngodley** [comment]
Your REST API is returning an error and you'll need to fix whatever is causing that.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
