### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by iyyappann** [johngodley/redirection#2828]
```
Plugin: 5.0.1
WordPress: 5.7 (single)
PHP: 7.2.34
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
JavaScript: https://avanos.co.uk/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://avanos.com.au/?rest_route=/
Query: ?page=redirection.php

Error: undefined
```

**Comment by iyyappann** [comment]
John
I try to set up a new "Redirect" , type inputs and click "Add Redirect" and I get this error.
"Group" drop-down is empty. 
Then same redirect is working in our staging ok.

**Comment by johngodley** [comment]
Your site URL settings (Settings > General) are different. You need to have one or the other domain.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
