### ISSUE TITLE
2 feature requests: IP range + hostname

### ISSUE THREAD

**Issue by SwissSpaceboy** [johngodley/redirection#2831]
### Summary

cf. https://wordpress.org/support/topic/2-feature-requests-ip-range-hostname/#post-14213065

Hello,

I would like to log 2 requests for additional redirection patterns:

1. IP range (currently we can only check IP per IP)
2. substrings in the hostname like *tor*, *sme*, *schools*, *res* (=residential) -> visits from these hostnames will be redirected to a smaller, static website instead of giving access to the rich website.

### Actual Behavior

1. not able to indicate a range of IP
2. not able to filter on hostnames. Examples of 'hosting” names:

    res.cust.bluewin.ch

    sme.cust.bluewin.ch

    adsl.cust.bluewin.ch

    sunrise.ch

I want to redirect only parts of ‘res’ or only ‘sme’ included in the ‘bluewin’. 

Or … I want to redirect all sunrise.ch or all adsl.ch 

The most important request is the **IP Range.**

### Environment

WP 5.5.3, Plugin 5.9.1

Thanks,

Didier.

**Comment by johngodley** [comment]
Moving to #1878
