### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by Wouwouw-YB** [johngodley/redirection#2833]
```
Uncaught TypeError: bad map https://salonboest.nl/wp-content/themes/solvi/uix/assets/es-shim.js?ver=2.0.3 5,Uncaught TypeError: bad map https://salonboest.nl/wp-content/themes/solvi/uix/assets/es-shim.js?ver=2.0.3 5
```

Plugin: 5.0.1
WordPress: 5.7 (single)
PHP: 7.4.16
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
JavaScript: https://salonboest.nl/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://salonboest.nl/wp-json/

**Comment by johngodley** [comment]
> Uncaught TypeError: bad map https://salonboest.nl/wp-content/themes/solvi/uix/assets/es-shim.js?ver=2.0.3 5,Uncaught TypeError: bad map https://salonboest.nl/wp-content/themes/solvi/uix/assets/es-shim.js?ver=2.0.3 5

You should direct the problem to the theme in question
