### ISSUE TITLE
Redirection Critical Error 

### ISSUE THREAD

**Issue by globalleadership** [johngodley/redirection#2834]
```
Plugin: 5.0.1
WordPress: 5.6.2 (single)
PHP: 7.1.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
JavaScript: https://globalleadership.org.au/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://globalleadership.org.au/wp-json/
Query: ?page=redirection.php&sub=site

Error: <p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p> (internal_server_error)
Raw: {"code":"internal_server_error","message":"<p>There has been a critical error on this website.<\/p><p><a href=\"https:\/\/wordpress.org\/support\/article\/debugging-in-wordpress\/\">Learn more about debugging in WordPress.<\/a><\/p>","data":{"status":500},"additional_errors":[]}
```

I'm not a web developer, just a designer so have no idea how or where to fix code. Yesterday I installed GIVE WP plugin which I think uses the same /wp-json/ API - could this be the cause of the error? I can't remove the GIVE plug in as it is vital for processing donations to our organisation. Is there any way to resolve this error?

**Comment by johngodley** [comment]
I don't know what GIVE is, but your REST API is broken:

https://globalleadership.org.au/wp-json/

This will be broken for whatever plugin uses it, and it is not specific to Redirection

**Comment by globalleadership** [comment]
Oh ok - can you point me to somewhere that will help me understand how do I fix the REST API?

**Comment by johngodley** [comment]
The error contains a link to the WordPress debugging guide, which is probably the best place to start. It's hard to give any more information as anything could be causing the problem.

You could try checking your error log.

**Comment by globalleadership** [comment]
Ok thanks for your help. I will contact my host server and see if they can help with the debug process.
