### ISSUE TITLE
Auto redirection to same URL

### ISSUE THREAD

**Issue by thecancerus** [johngodley/redirection#2852]
Sometimes Redirection plugin automatically adds a URL for redirection and then it redirects it to the same URL, resulting in an infinite loop on those pages.

Is this a bug, or under what circumstances will the redirection plugin will end up adding a redirection rule to the same URL?

### Environment

WordPress Version  5.5.3 
Redirection Plugin Version 4.8
PHP 7.4

**Comment by johngodley** [comment]
Can you give an example? Is this the result of multiple changes to the same post?

**Comment by thecancerus** [comment]
It could be, our posts get edited multiple times. It has happened 2-3 times in past, I have deleted the redirection rule that was auto-added, Next time time it happens I will share more details.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
