### ISSUE TITLE
Problem starting Redirection 5.0.1

### ISSUE THREAD

**Issue by akhils7834** [johngodley/redirection#2855]
Plugin: 5.0.1
WordPress: 5.7 (single)
PHP: 7.4.16
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
JavaScript: https://www.shipmethis.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://www.shipmethis.com/wp-json/

**Comment by johngodley** [comment]
Please read the instructions provided in the error message. This file is missing:

https://www.shipmethis.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3

**Comment by akhils7834** [comment]
How to make this file work

**Comment by johngodley** [comment]
It is part of the plugin. I couldn't say why it's not on your site, and you will need to investigate and see.

**Comment by johngodley** [comment]
This is not a problem with the plugin, but with your site. You are using Cloudflare and it could be caching an error.

**Comment by akhils7834** [comment]
i did cache bypass and purged cache as per the guide. Still not working

**Comment by akhils7834** [comment]
Any ideas pls

**Comment by akhils7834** [comment]
https://www.shipmethis.com/wp-content/plugins/redirection/redirection.js is accessible from my end

**Comment by akhils7834** [comment]
Its the cloudflare issue. I contacted them and they added a bypass of security and it works now. Thank you
