### ISSUE TITLE
Redirection error when not being logged in.

### ISSUE THREAD

**Issue by wpbuffs** [johngodley/redirection#2858]
When the plugin is active and the user is not logged in the following URL https://inbodyusa.com/?eid=27183&utm_source=ExhibitorLP&utm_medium=PersonalisedLP&utm_term=&utm_content=&utm_campaign=Elumatec%20Middle%20East%20LLC

This page isn’t workinginbodyusa.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

The URL is not set up on the redirection plugin
![image](https://user-images.githubusercontent.com/39532094/113911805-05a20d80-97a0-11eb-8587-82ec96bc7fae.png)

The issue when not logged in
![image](https://user-images.githubusercontent.com/39532094/113911891-21a5af00-97a0-11eb-8b61-17f143ca9cf2.png)

Works just fine when logged in
![image](https://user-images.githubusercontent.com/39532094/113911935-2cf8da80-97a0-11eb-91a3-ee8d5eae4f8b.png)

WordPress version 5.7
Redirection Version 5.0.1

**Comment by johngodley** [comment]
I don't know what the question is, but as this URL is not being redirected with Redirection then I will close this issue.

**Comment by wpbuffs** [comment]
Is not a question, is an issue, the problem is, when I deactivate the plugin, the URL redirects properly. So this is an issue with the Redirection plugin.
