### ISSUE TITLE
Prevent/flag source and target URL's that differ only by domain

### ISSUE THREAD

**Issue by danielck** [johngodley/redirection#286]
Currently the plugin UI will prevent me from typing in the exact same source and target URL. This is a good thing. 
However it will allow me to create a rule where the URL's are otherwise the same but the target URL includes the site domain. e.g. if the site URL is example.com, I am able to create a redirect where the source is /path-to-page and target is http://example.com/path-to-page. In my view this should not be allowed or at least should be flagged to the user to catch potential redirect loops before they happen.

**Comment by johngodley** [comment]
Moving to #82 as it's essentially the same.
