### ISSUE TITLE
Problem starting Redirection 5.1

### ISSUE THREAD

**Issue by nextlevelwebdesign** [johngodley/redirection#2864]
Plugin: 5.1 4.2
WordPress: 5.7 (single)
PHP: 7.3.3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
JavaScript: https://waystomove.co.uk/wp-content/plugins/redirection/redirection.js?ver=5.1-a303333ae5185be5433467d110cae802
REST API: https://waystomove.co.uk/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions and see if another plugin is causing the problem.

Also, your plugin file does not seem complete: https://waystomove.co.uk/wp-content/plugins/redirection/redirection.js?ver=5.1-a303333ae5185be5433467d110cae802

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
