### ISSUE TITLE
404

### ISSUE THREAD

**Issue by riyadhali** [johngodley/redirection#2865]
Hello
Once you apply the plugin upgrade to 5.1
All 404 pages of the site 

all best

**Comment by johngodley** [comment]
Can you explain more what you mean there?

**Comment by riyadhali** [comment]
Thank you so much
I am a fan of this great plugin.
I Working on:
litespeed + php74
I have over 50,000 redirects.
More than 150 regex
I work via the plugin, normally, however
Once you apply the plugin upgrade to 5.1
All 404 pages of the site
404
Page Not Found !! "
After attempts to update and restart the server, I had to revert to
5.0.1

all best

**Comment by johngodley** [comment]
Sorry, I still don't understand what you mean. Are you saying that with 5.1 all pages on your site are 404s? Can you give an example that I can look at? What settings do you have?

**Comment by riyadhali** [comment]
Yes in deed
Today plugin  redirection update 5.1
Turn off all pages,
The home page & wp admin opens, but when you click on any titles, what appears is a 404 page
My site is an example that could be of great interest to you, due to its heavy reliance on  plugin redirection.
Currently
I reverted to version 5.0.1 and blocked automatic updating

**Comment by johngodley** [comment]
There's not much I can do without more details or a way to reproduce the problem. What settings do you have?

**Comment by riyadhali** [comment]
Is it possible to speak through the mail or any special form? So I can give you more information

**Comment by johngodley** [comment]
All my contact details are available in the plugin or on the plugin website https://redirection.me/contact/

**Comment by riyadhali** [comment]
Message sent
best

**Comment by Mifayo** [comment]
Hello @riyadhali did you found the solution i had been hacked and after i restore my website all the link goes 404 :/
