### ISSUE TITLE
Problem after updating the redirect extension

### ISSUE THREAD

**Issue by Fabrice-DENIS** [johngodley/redirection#2866]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Hello,
Since the update of the redirect extension all articles have the code 404 ????????
Example: https://www.fabricedenisphotography.fr/fujifilm-decouverte-le-nouveau-x-s10/

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Chrome Version 89.0.4389.114 (Build officiel) (x86_64)
Wordpress 5.7
Redirection 4.2

**Comment by johngodley** [comment]
What settings are you using? What is different about that page compared to other pages on your site that are working?

**Comment by Fabrice-DENIS** [comment]
Seul les articles sont impactés par la dernière mise à jour. Si je supprime la ligne de code dans le "Permalink Migration" tout va bien pour le site mais bien entendu tout va mal pour le référencement dans Google !!!

**Comment by johngodley** [comment]
Ok, so what you are saying is that the permalink migration setting is affecting the articles? Is the above URL one that should be migrated to another URL? What is your permalink setting migration?

**Comment by Fabrice-DENIS** [comment]
Oui c'est exact, maligne de commande est : /%year%/%monthnum%/%day%/%postname%/

**Comment by Fabrice-DENIS** [comment]
En fait je m'aperçois que les anciennes url avec la date de l'article sont dans Google avec la bonne url !!!! Comment est-ce possible ? Donc la ligne de commande dans "Permalink Migration" n'a plu lieu d'être ???

**Comment by Fabrice-DENIS** [comment]
Bon et bien j'ai retrouvé des anciennes URL de type : https://www.fabricedenisphotography.fr/2016/12/01/le-fujifilm-x-a10-nouvel-appareil-a-objectif-interchangeable-de-la-serie-x-le-partenaire-de-tous-les-instants/ ou la redirection fonctionne mais l'article a un code erreur 404 tout de même ???

**Comment by johngodley** [comment]
I don't really know what you're asking there. I've made a slight modification to something that may be affecting it. Can you try this and see if it helps?

[redirection-5.1.zip](https://github.com/johngodley/redirection/files/6291835/redirection-5.1.zip)

**Comment by Fabrice-DENIS** [comment]
Merci à vous !!!!
Tout fonctionne normalement, c'est vraiment sympathique de vous être penché sur ce problème un DIMANCHE !!!
Bonne fin de week-end,
Cordialement,
Fabrice DENIS

**Comment by johngodley** [comment]
Great. I will release this as version 5.1.1

**Comment by Fabrice-DENIS** [comment]
OK et bon courage pour la suite...
Je ferme le ticket et encore merci de votre réactivité.
