### ISSUE TITLE
Problem starting Redirection 5.1.1

### ISSUE THREAD

**Issue by vivekparase** [johngodley/redirection#2868]
```
Uncaught SyntaxError: Invalid or unexpected token https://vedicstore.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667 2
```

Plugin: 5.1.1 4.2
WordPress: 5.7 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
JavaScript: https://vedicstore.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://vedicstore.com/wp-json/

**Comment by johngodley** [comment]
Please read the onscreen instructions. Your plugin is not installed properly and this file is missing: https://vedicstore.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667

**Comment by vivekparase** [comment]
Where can I get this file to rectify the error? Please help to troubleshoot
this issue, thanks.

**Comment by johngodley** [comment]
It is in the plugin when you install it. You will need to look at your site why it isn't present or isn't available. You do not need to download anything else.

**Comment by vivekparase** [comment]
I had this plugin installed nearly a year, I just removed to reinstall now
this problem. I am not expert on this, hence cannot resolve, I will look
for another plugin. Thanks.

**Comment by johngodley** [comment]
Then something on your site is blocking the URL. Sorry, but this is a problem that only you will be able to fix on your site - it is not a problem with the plugin. If this sort of problem occurs on your site then it is likely to occur to other plugins. Maybe you can talk to your host provider.
