### ISSUE TITLE
Weird redirects appeared on my site

### ISSUE THREAD

**Issue by bookdreamer** [johngodley/redirection#2869]
Hello!

I haven't visited the plugin for a while and today I opened it and saw a lot of weird redirects on top of the ones I had. They all look like hashcode or something and redirect to home. There are no hits or access data. I'm attaching the screenshot.

<img width="1183" alt="Screenshot 2021-04-14 at 22 09 44" src="https://user-images.githubusercontent.com/32674679/114766139-b6934400-9d6e-11eb-8265-0cffc6017b2a.png">

How could these get added and what are they for? Can something break if I remove them?

**Comment by johngodley** [comment]
They're all disabled, so will have no effect and can be deleted. More than likely you have the 'monitor trashed posts' option enabled, and these are things that are being picked up as trashed post - maybe from a custom post type, or something like that

**Comment by bookdreamer** [comment]
Thank you so much for a quick response! I deleted them.
