### ISSUE TITLE
Can't find redirects since updating plugin

### ISSUE THREAD

**Issue by Rachelhenke** [johngodley/redirection#287]
To help track problems please follow this template. If you can provide screenshots then that will help.

### My redirect wasn't working so I updated plugin. Now I can't find the redirect area under redirects. Seems to have disappeared.

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Trying to find redirects.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Redirects weren't working and now can't find them in the settings.

Explain the steps involved to reproduce the problem

### Clicking 'redirects' but they're not there. Is the plugin no longer working?

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Try a different browser or install 2.7 beta 1 https://github.com/johngodley/redirection/releases/tag/2.7b1

**Comment by skynet** [comment]
2.7 beta 1 is even worst

**Comment by johngodley** [comment]
Even worse how? Can you provide more details?
