### ISSUE TITLE
Problem starting Redirection 5.1.1

### ISSUE THREAD

**Issue by nileshchakraborty** [johngodley/redirection#2877]
```
Uncaught SyntaxError: Invalid or unexpected token https://nileshchakraborty.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667 2
```

Plugin: 5.1.1 4.2
WordPress: 5.7.1 (single)
PHP: 7.4.16
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
JavaScript: https://nileshchakraborty.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://nileshchakraborty.com/wp-json/

**Comment by nileshchakraborty** [comment]
`Unable to load Redirection â˜¹ï¸ v5.1.1
This may be caused by another plugin - look at your browser's error console for more details.

If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

Also check if your browser is able to load redirection.js:

https://nileshchakraborty.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667

Please note that Redirection requires the WordPress REST API to be enabled. If you have disabled this then you won't be able to use Redirection

Please see the list of common problems.

If you think Redirection is at fault then create an issue.`

**Comment by nileshchakraborty** [comment]
Some how there is some encoding issue in the Error message itself above

**Comment by johngodley** [comment]
Sounds like your plugin isnt installed properly. Maybe try reinstalling it.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
