### ISSUE TITLE
Redirect active despite not being in redirect list

### ISSUE THREAD

**Issue by MIY2021** [johngodley/redirection#2884]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Redirect active despite not being in redirect list

### Actual Behavior

Redirect active despite not being in redirect list - https://www.makeityork.com/york-business-week/ redirects to https://www.makeityork.com/news/2020/10/york-business-week-makes-a-virtual-return-for-2020/ and shows in the redirect log but when you click on 'view redirect' it loads the redirect list but it is empty... (spooky)

![Capture](https://user-images.githubusercontent.com/83291521/116258566-f8f45200-a76c-11eb-84d7-f7a66244cf95.JPG)

It seems as though there was a redirect, it was deleted but it is still active?

It's happening on mutliple devices.

### Steps to reproduce

Open https://www.makeityork.com/york-business-week/ 

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Chrome - Version 90.0.4430.85 (Official Build) (64-bit)
Redirection version - 5.1.1
WordPress 5.7.1

**Comment by johngodley** [comment]
Unless the URL is listed in your redirects then it is not being redirected by Redirection.

That one is being redirected by something else:

https://redirect.li/http/?url=https%3A%2F%2Fwww.makeityork.com%2Fyork-business-week%2F

**Comment by MIY2021** [comment]
OK great, thanks. Weirdly working now without doing anything!

Ben
