### ISSUE TITLE
Can no longer delete current search results

### ISSUE THREAD

**Issue by lklawless** [johngodley/redirection#289]
It used to be that when you searched the 404 logs for, say, **jpg** you'd get a list of results, sometimes several pages of them, and with one click you could delete just those results without affecting the rest.

Now it's all or nothing: there's no longer an option to delete just the current results. Worse, it seems like these results are listed by log page so they take forever to delete.

For example, if I search for **jpg** and get 300 results, in theory that should be 3 pages with 100 results each, so if I click the "check all button" on each of those three pages, I should be able to clear them from the log with three clicks. In reality, only 40-50 are cleared with each click, so it takes like 10 clicks to clear those results from the log.

Is there any chance of bringing the efficient "clear these results from the logs" option back?

Win 10 FF, WP 4.8.1, latest version of Redirection

**Comment by johngodley** [comment]
It will come back in #288 when that gets released.
