### ISSUE TITLE
Pb with hydro-armor.com

### ISSUE THREAD

**Issue by SupportProWeb** [johngodley/redirection#2891]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

On the website https://hydro-armor.com/ I have set redirections from the older website http://hydro-armor.fr/. 
But the following is not working : http://www.hydro-armor.fr/propulseurs.php

### Actual Behavior
The domain hydro-armor.fr is well redirected with 01 redirection to hydro-armor.com.
But the different redirections. set with the plugin are not working…
By exammple : http://www.hydro-armor.fr/propulseurs.php
When I check the plugin interface, it seems OK 
![Capture d’écran 2021-05-03 à 09 48 50](https://user-images.githubusercontent.com/51416808/116865412-e1ecae80-ac09-11eb-87fd-f49bf1c71525.png)
![Capture d’écran 2021-05-03 à 10 17 49](https://user-images.githubusercontent.com/51416808/116865419-e5803580-ac09-11eb-98ae-2b1a503e767b.png)
It's the same with another one like http://hydro-armor.fr/propulseurs_relevables.php

### Steps to reproduce

The redirections have been set on April 26th…

### Environment

The pb is seen on different browsers and you can see it yourself…

**Comment by johngodley** [comment]
A 200 response is a web page, not a redirect.

See this guide: https://redirection.me/support/problems/url-not-redirecting/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
