### ISSUE TITLE
Problem starting Redirection 5.1.1

### ISSUE THREAD

**Issue by ahmedshakeel083** [johngodley/redirection#2894]
Plugin: 5.1.1 4.2
WordPress: 5.7 (single)
PHP: 7.3.19
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
JavaScript: https://www.medlife.com/blog/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://www.medlife.com/blog/wp-json/

**Comment by johngodley** [comment]
This is almost certainly a problem caused by another plugin. Try disabling them.
