### ISSUE TITLE
500 Error after re-introducing a deleted redirection

### ISSUE THREAD

**Issue by GavOutdoors** [johngodley/redirection#2896]
### Summary
I am getting an HTTP 500 error on this url https://www.getoutwiththekids.co.uk/camping/tents/robens-kiowa-tent-review/
<img width="806" alt="image" src="https://user-images.githubusercontent.com/79079903/117248998-c1ef0200-ae38-11eb-8ca1-1d3be9a674a8.png">

This was a redirection I had accidentally deleted and re-added. 

### Actual Behavior
Here are its details.
![image](https://user-images.githubusercontent.com/79079903/117249191-16927d00-ae39-11eb-85c8-d561ff88a3ee.png)

I have flushed all the caches (several times), and it didn't make a difference. 
I also did this with the Beta Cache Redirects settings on and off.

### Environment
![image](https://user-images.githubusercontent.com/79079903/117249138-037fad00-ae39-11eb-8271-5e9247e2d994.png)

PHP (7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1)
Redirection Version 5.1.1 
wp-core version: 5.7.1
Browser Firefox 88.0

**Comment by johngodley** [comment]
This is likely caused by your theme - what are you using?

**Comment by GavOutdoors** [comment]
ReHub https://themeforest.net/item/rehub-directory-multi-vendor-shop-coupon-affiliate-theme/7646339

**Comment by johngodley** [comment]
Ok, I can't test a premium theme. Redirection is sending the correct codes, and something else is modifying it

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
