### ISSUE TITLE
redirect with/ without trailing slash

### ISSUE THREAD

**Issue by mustafauysal** [johngodley/redirection#29]
I guess ignoring latest slash of redirect URL could be helpful.

For example, when I want to redirect `/test`, at the same time want to redirect `/test/` as well. So don't need to add same rule twice (with or without slash)

What are you think about this John? (I can work on this enhancement) 
Prop @johngodley

**Comment by mattbeck** [comment]
Just use a regex rule for that

^/test/?$

**Comment by Sophist-UK** [comment]
There appears to be some code already present for this, though it is buggy.

My suggestion is that we might want this to be default i.e. for non-regex redirects, remove trailing slashes from both the actual url and the redirection from url before making the comparison.

This does of course mean that you cannot redirect `/something` to one page and `/something/` to a different page, but again you could achieve this with a regex.

On balance, I believe that non-regex should be  made to be as easy as possible for non-techies who don't want anything complex and don't understand regex.

This is something I plan to look at imminently, so feedback would be useful.

**Comment by johngodley** [comment]
This is something I already have in the works, along with changes for case insensitivity and other things. However it requires a lot of changes and I'm more concerned with getting the plugin into a position where these changes won't break any sites.

**Comment by Sophist-UK** [comment]
I don't think specific item needs a lot of changes. Two lines in one file as far as I can tell.

**Comment by johngodley** [comment]
> I don't think specific item needs a lot of changes. Two lines in one file as far as I can tell.

There are complications around it and other changes like this that I'd like to see tackled at the same time, once confident it won't break any site using the plugin.

I'll add that I'm not trying to dissuade help! But rather than tack on new features my personal focus for the plugin is to simplify what's already there (it's a 9 year old plugin with a lot of cruft), then expand from a solid base.

**Comment by Sophist-UK** [comment]
Ok - I will concentrate on fixing other minor bugs I have found.

**Comment by johngodley** [comment]
Merging with #176
