### ISSUE TITLE
Problem starting Redirection 5.1.1

### ISSUE THREAD

**Issue by vinc53** [johngodley/redirection#2903]
```
Uncaught SyntaxError: Invalid or unexpected token https://www.jah-star.com/newshop/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667 2
```

Plugin: 5.1.1 4.2
WordPress: 5.7.1 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
JavaScript: https://www.jah-star.com/newshop/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://www.jah-star.com/newshop/wp-json/

**Comment by johngodley** [comment]
This is most likely another plugin causing the problem.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
