### ISSUE TITLE
Redirect Loop Bug While Using Plugin

### ISSUE THREAD

**Issue by rohankleem** [johngodley/redirection#2906]
### Summary
Plugin has resulted in all users on different browsers getting in redirect loops from the home page of the site.

### Actual Behavior
Website has been failing because of redirect loops, affects for all users (extenal users on different browsers, new/different users, who all experience the issue). A temporary fix was found from our end, but problem became re-introduced every 30 minutes or so after the temporary fix was applied - the temp fix that was discovered was to clear SiteGround's server cache at their server level (SiteGround), but the problem would then would re-occur after a short period of time. And this was verified and validated over 3 days of seeing this behaviour re-occur about a total of 40 times. While this may sound like a cache or server related item, diagnostics and testing at the hosting level, both from us and the SiteGround support staff, and looking into Redirection Plugin logs, show that a redirect has been sending all visitors into redirect loops, and that this redirect was being triggered by Redirection Plugin. 

An example would be:
- User visits https://www.oursite.com.au/
- Browser shows redirect loop error
- URL address shows https://www.oursite.com.au/?utm_source=fb&utm_medium=ads&utm_campaign=Sheds%20-%20VIC&utm_content=Sheds%20-%20VIC%20-%20Male%20-%20DIY&fbclid=IwAR2Gu5Xka56z1RG66A9Gts4P17A7MpCmzox1_AO8g1svp-nbp2wqhLJ5Gn8

All examples of this bug we have experienced are similar to above, where users were being redirected to a URL with a UTM_SOURCE facebook campaign (one of ours at facebook). The trigger for the reoccurrence of the problem was probably when any external user clicked on facebook campaign URLs to access the site. Possible that characters in the URL parameters are creating some type of catch all condition/bug that applies to every home page request.

Evidence of this can be seen in the database logs for the Redirection Plugin. Screenshots are provided, note also the "redirection_id" set in these logs is 0, seems to imply that it is not based on any rule that exists.
Screenshot shows where the plugin is creating the redirect loops.

![image](https://user-images.githubusercontent.com/6668421/117906925-2e766f00-b319-11eb-965a-bff33a2f9573.png)

### Steps to reproduce
A fix has been discovered by adding the following code to our htaccess file
<IfModule mod_headers.c>
Header set Cache-Control "max-age=0,no-store"
</IfModule>
and so the error is currently avoided.
Currently treading water til we find another plugin or confirm actual cause.
Given that this code prevents the redirect from occurring, it cannot currently be replicated (a good thing for our live site)
We are not able to produce an environment for this to be replicated because it would affect all our site visitors in a live environment.

### Environment
Browsers tested and replicated: Chrome, Firefox, Edge ... not browser specific.
Wordpress version 5.7.1

**Comment by johngodley** [comment]
The plugin only redirects when you tell it to do so. If you have a redirect loop then it is either because you have created a loop, or Redirection is not causing the redirect.

You've shown the log using phpMyAdmin, not the plugin, and it looks like you have the enhanced logging enabled. This can log other redirects that happen outside of Redirection, and these will be logged with an ID of 0. You can also see that the `redirect_by` is set to `wordpress`, so Redirection is not involved.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
