### ISSUE TITLE
Redirection error

### ISSUE THREAD

**Issue by laylaroberts** [johngodley/redirection#2913]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

I have set up 2 redirections from one of my websites to one of my others:
* https://www.sydneyconcierge.com.au/shop/sydney-quarantine-packages - should redirect to https://quarantinecare.com.au
* https://www.sydneyconcierge.com.au/hotel-quarantine-in-sydney should redirect to https://quarantinecare.com.au/quarantine-faqs

### Actual Behavior

It is redirecting for some but not other people. I want to ensure both links redirect for everyone, so that I can delete the page from my 'old site' and Google doesn't penalise me for duplicate content. One person thought it was redirecting for the non-www version, but not the www version, but everyone who has tested it is clicking on the same link, so I am unsure how that is possible.

### Environment

Google Chrome, wordpress 5.7.2, redirection plugin 5.1.1

browser version

**Comment by johngodley** [comment]
A redirect behaves the same for all users.

https://www.sydneyconcierge.com.au/shop/sydney-quarantine-packages does not redirect

https://www.sydneyconcierge.com.au/hotel-quarantine-in-sydney redirects to https://www.sydneyconcierge.com.au/hotel-quarantine-in-sydney/ (not Redirection)

https://www.sydneyconcierge.com.au/hotel-quarantine-in-sydney/ redirects to https://quarantinecare.com.au/quarantine-faqs/ (Redirection)

Please note the trailing slash.

**Comment by laylaroberts** [comment]
Hello, thank you for replying so quickly! I just added the / to the end of the url and I thought it worked. It does work on my laptop, but not my mobile.

I'm very confused. How can I fix this?

**Comment by johngodley** [comment]
You will need to clear your browser cache. Also, you may want to use the ignore trailing slash option:

https://redirection.me/support/matching-a-url/

**Comment by laylaroberts** [comment]
Hi John.

I ticked the ignore trailing slash and cleared my browser cache.

Now, both links redirect for me on my laptop and my phone. They also both work on my partner's phone, but this one doesn't work on his laptop: https://www.sydneyconcierge.com.au/shop/sydney-quarantine-packages 

We are both on the same wifi and he has never visited that page on his laptop before.

It's extremely confusing.

**Comment by johngodley** [comment]
As I mentioned before, a redirect works the same for all users. This never changes. Some people may be affected by local caches, and this is not something the plugin can affect.

That URL does not redirect:

https://redirect.li/http/?url=https%3A%2F%2Fwww.sydneyconcierge.com.au%2Fshop%2Fsydney-quarantine-packages

You are one who probably has a cached redirect.

**Comment by laylaroberts** [comment]
Thank you for clarifying. Do you know why the link is not redirecting? I have been struggling to fix this for about a week now.

Also, if it has a green tick on the backend like my other link, does that mean it is definitely redirecting for everyone? I am asking as I want to delete the page from https://www.sydneyconcierge.com.au, so that Google doesn't penalise me for dupliacte content.

![2021-05-17 (6)](https://user-images.githubusercontent.com/6530961/118492372-4b6cd100-b763-11eb-822f-d20f07187707.png)

**Comment by johngodley** [comment]
I don't know why that URL is not redirecting. What is your redirect for it?

The URL checker is not affected by user caches and shows what is actually happening. If it says a URL is redirecting then it is redirecting.

**Comment by laylaroberts** [comment]
It should direct here: https://quarantinecare.com.au/

![2021-05-17 (7)](https://user-images.githubusercontent.com/6530961/118498315-3eeb7700-b769-11eb-8f97-fe57c04b8688.png)
