### ISSUE TITLE
Change csv import separator

### ISSUE THREAD

**Issue by wojsmol** [johngodley/redirection#292]
### Summary
Change csv import separator from `,` to `, ` or `|`
### Actual Behavior
If csv contents urls with `,` then this urls are badly imported.
### Steps to reproduce
Create csv with `,` in urls and try to import it.
### Environment
Firefox 54.0.1
WordPress 4.7.5
Redirection 2.6.6

**Comment by johngodley** [comment]
Where is the CSV file from? If it's not from Redirection itself, are you putting quotes around the URL? I've just tested Redirection and it correctly handles a comma in a field when quoted. If the quotes aren't present and you have a comma then it's not a valid CSV file.

**Comment by wojsmol** [comment]
The csv is generated from Microsoft Excel 2016. Excel produces csv with `;` as a separator and without `"`. Now I see the error and can fix this.
