### ISSUE TITLE
Ability to change user roles access?

### ISSUE THREAD

**Issue by Rhyspacker** [johngodley/redirection#2924]
### Summary

I'm working on a website with multiple user roles with me as the main Admin, and there's mainly Editor accounts. Is there a way to add an option into the plugin to allow Editors or other user roles access to the plugin?

As this would allow my client to make the occasional redirect, without having to make them an Admin and thus potentially break things on the site. 

### Actual Behavior

Currently only an Admin can access the Redirection plugin options

Thanks for any help on this, no worries if it's a big task not worth doing but I would greatly appreciate a feature like this.

**Comment by johngodley** [comment]
Details here: https://redirection.me/developer/permissions/

**Comment by Rhyspacker** [comment]
Sorry I forgot to reply, but that was exactly what I needed. Thank you!
