### ISSUE TITLE
Some question on redirect for multiple domain

### ISSUE THREAD

**Issue by manuelvita96** [johngodley/redirection#2925]
Hi, first of all I think this plugin is awesome. I have some question about config.

I have 4 domain that I want to use on my website.

The first one is "manvitech.it" and is the default domain of default language of the website, so this domain didn't have redirects.

The second is "manvitech.eu" that I want to use al domain for english version of website and I want to keep the domain in address bar instead redirect to "manvitech.it/en" but if I configure pass-trough redirect, the page is in english but menus are in italian (I use Polylang) so I need to figure out how I can make this redirect correctly.

The third an fourth domain are "manvite.ch" and "bu.lc", this domain needs to be used like first one domain. For example if visit "bu.lc/articoli" I want to see the same content of "manvitech.it/articoli" without change the address. I have tried with alias but they made only a redirect to manvitech.it.

I hope that my explanation is clear, and thank you for help

**Comment by johngodley** [comment]
Redirection is not really suitable for those kind of things. You could look at rewrites instead.
