### ISSUE TITLE
Redirection Error (with WAF activated)

### ISSUE THREAD

**Issue by ZEROF** [johngodley/redirection#2926]
```
Plugin: 4.6.2
WordPress: 5.x (single)
PHP: 7.2.34
Browser: Mozilla/5.0 Firefox/88.0
JavaScript: https://www.xxxx/wp-content/plugins/redirection/redirection.js
REST API: https://www.xxxx/wp-json/

Error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data (SyntaxError)
Action: redirection/v1/redirect/?orderby=last_count GET
Code: 400 Bad Request
Raw: -no data-
```

Hi, 

After activating WAF (included with my CDN), your plugin stop working and only way to use it is to disable WAF , make changes, and activate WAF again. I tried to use "switch to this API, but it's not working.

Best regards

**Comment by johngodley** [comment]
What is the WAF? The plugin just uses the WordPress REST API so it is likely blocking that too

**Comment by ZEROF** [comment]
I can just provide you this https://docs.ovh.com/gb/en/hosting/web_hosting_activating_an_application_firewall/. It's included with their " CDN Advanced" package.

**Comment by johngodley** [comment]
It may be worth speaking to OVH and see why the request is being blocked - they should know more.

**Comment by ZEROF** [comment]
I have already open ticket with them, and I shared this "issue" url with them. Thanks

**Comment by ZEROF** [comment]
Hi,

I'm not sure if you can provide solution for this, because OVH is not going to change anything on their side. That is their "short" version for answer.

Thanks

**Comment by johngodley** [comment]
They have no logs and can't provide any information? There must be more than 1 person using this plugin on OVH, and more than one person using the WordPress REST API.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
