### ISSUE TITLE
Blank Settings Screen for Redirects, Groups, 404s

### ISSUE THREAD

**Issue by thelogosmith** [johngodley/redirection#293]
![screenshot 2017-08-10 10 51 49](https://user-images.githubusercontent.com/22678934/29165349-4be474ee-7dba-11e7-8cb6-46e68f69e62b.jpg)
![screenshot 2017-08-10 10 51 28](https://user-images.githubusercontent.com/22678934/29165348-4be1d45a-7dba-11e7-9d0b-dd81f823f6a4.jpg)

To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

Blank Settings screen for: Redirects, Groups, 404s but 'Something Went Wrong' screen for Options, Modules and Support. 

### Actual Behavior

Blank Settings screen for: Redirects, Groups, 404s but 'Something Went Wrong' screen for Options, Modules and Support.  Means no way to add, change, view anything in the plug-in.

See screenshots

I disabled all plug-ins, and the problem still persists.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment
Versions: Plugin 2.6.6, WordPress 4.8.1, PHP 7.0.22
Nonce: 888fb32a49

Action: red_load_settings
Code: undefined
Error: Loading chunk 0 failed.
Raw: null
Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Please use Chrome or the 2.7 beta https://github.com/johngodley/redirection/releases/tag/2.7b1
