### ISSUE TITLE
Problem starting Redirection 5.1.1

### ISSUE THREAD

**Issue by manojkumar001** [johngodley/redirection#2939]
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
JavaScript: https://astrosubbu.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://astrosubbu.com/wp-json/

**Comment by johngodley** [comment]
This file does not exists:

https://astrosubbu.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667

It will need to exist.
