### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by mostlyjan** [johngodley/redirection#294]
on various sites (all use AVADA theme in case relevant), the log pagination no longer works.

Mine were set to 200 from a previous version. After the update, 100 is the limit. But when i pick anything OTHER than 25, those entries are lost, the page count is off, searching for non 'visible' items don't work, etc.

Right now, this plugin only works well if you use 25 as the log entry count. Any other number (eg the max 100 as stated) will not work.

**Comment by johngodley** [comment]
This was fixed in cf92e5023f6176dbf74aa2229bf777cdadb91737 and will make it into the next version of the plugin
