### ISSUE TITLE
Log disappeared!

### ISSUE THREAD

**Issue by sdavid99** [johngodley/redirection#295]
Some days ago I found out that all the logs have disappeared!

![image](https://user-images.githubusercontent.com/18059308/29215218-6fbda0ca-7eaa-11e7-874e-931a380d2086.png)

Although redirects are active and up-to-date

![image](https://user-images.githubusercontent.com/18059308/29215211-675d9c32-7eaa-11e7-8615-0798675f87a0.png)

I also updated the plugin to version 2.7 but nothing happens.

Help!
David

**Comment by johngodley** [comment]
What do you have set for '404 logs' and 'Redirect logs' on the options page?

**Comment by sdavid99** [comment]
![image](https://user-images.githubusercontent.com/18059308/29215523-95baefd4-7eab-11e7-98cc-b061938d3c2f.png)

**Comment by sdavid99** [comment]
I haven't problems with 404s logs

![image](https://user-images.githubusercontent.com/18059308/29215553-c652f8a8-7eab-11e7-823f-7eb61c0eb070.png)

**Comment by johngodley** [comment]
Is it possible the logs have expired?

Could you have deleted the logs (accidentally or otherwise)?

**Comment by sdavid99** [comment]
John, thank you for your answers.

2 days ago I found that the logs had stopped at July 29, 2017. I thought the database was full and so I deleted the logs. I then waited a day to see if anything changes. This morning I also updated the version.

Nothing happens...

**Comment by johngodley** [comment]
So the logs haven't disappeared - you deleted them - but they are no longer being recorded?

**Comment by sdavid99** [comment]
Yes, sorry I wrote badly. English is not my mother tongue.
The logs log was stopped from July 29, 2017. I deleted the logs just to make sure there was no size problem.

**Comment by sdavid99** [comment]
But I did not stop logging recording.

**Comment by johngodley** [comment]
Do the redirects still show a hit? By that I mean, if you visit the `/cdbannermenu` redirect you have in the screenshot, does the number of hits go up from 757 to 758?

If it does, but you have no log entry for it, can you look in your server `error_log` and see if there are any errors related to Redirection? It is possible the database insert is failing

**Comment by sdavid99** [comment]
John,
I did the tests. I noticed that logs are working now. I do not understand. I had done several tests from different computers before writing the request for help. I must have touched something. Now everything works.

**Comment by johngodley** [comment]
No worries. Closing

**Comment by sdavid99** [comment]
Thx u, John.
