### ISSUE TITLE
Redirection Error (when trying to add new redirect)

### ISSUE THREAD

**Issue by sorrow-poetry** [johngodley/redirection#2953]
hello
I'm having an issue with creating new redirects. ( I cant edit or delete old redirects )

i think the main reason is this part `Field 'last_access' doesn't have a default value`
and looks like it's a database error

here is the log from plugin: 

```
nginx version: nginx/1.21.0
mysql  Ver 15.1 Distrib 10.5.10-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 7.4.20
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
JavaScript: https://www.example.com/mag/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://www.example.com/mag/?rest_route=/
Query: ?page=redirection.php

Action: https://www.example.com/mag/?rest_route=/redirection/v1/redirect/&orderby=id&direction=desc&per_page=200 POST
Params: {"id":0,"url":"https://www.example.com/mag/8best-animation-of-pixars-based-on-metacritic-score/","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"pass"},"options":{}},"match_type":"url","action_type":"url","position":0,"group_id":5,"action_code":301,"action_data":{"url":"https://www.example.com/mag/8best-animation-of-pixars-based-on-metacritic-score-2/"}}
Code: 400 Bad Request

Error: Unable to add new redirect (redirect_create_failed)
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":295,"wpdb":"Field 'last_access' doesn't have a default value"}}
```

**Comment by sorrow-poetry** [comment]
I've fixed the problem by changing the default value of `last_access` field in `wp_redirection_items` table.
it has to be a date or it's not acceptable and also you can't leave the field empty when you're creating a new redirect.
please consider fixing this problem permanently because my solution doesn't look right.
`ALTER TABLE wp_redirection_items MODIFY_COLUMN last_access datetime NOT NULL DEFAULT '2000-01-01 00:00:00';`

**Comment by johngodley** [comment]
The table does have a default:

https://github.com/johngodley/redirection/blob/master/database/schema/latest.php#L189

I do not know why yours doesn't.
