### ISSUE TITLE
Using redirection to disable category pages

### ISSUE THREAD

**Issue by ErinPo** [johngodley/redirection#296]
### Summary

Trying to use the plugin to disable all category pages and show a 404 instead.

### Actual Behavior

Category pages remain accessible with HTTP code 200. The hit counter in redirection increments, but the error 404 fails to be generated. Also tried with 401 (fails) and 410 (works).

### Steps to reproduce

Create a redirect using the WordPress module with:
source URL: /category/.*
Regex: checked
Match: URL only
when matched: Error (404)
HTTP code: 404. 

### Environment

Chrome, Redirection Version 2.7, WP version 3.8.1

**Comment by johngodley** [comment]
It seems something has changed in WordPress, and category pages override the 404 that Redirection is trying to set. I'll include a fix for this in a future version

**Comment by ErinPo** [comment]
Cool, great to hear!

**Comment by ErinPo** [comment]
The bug ist still present in version 2.7.3.

**Comment by johngodley** [comment]
Yep, when it is fixed this issue will be closed.

**Comment by johngodley** [comment]
Fixed in #422
