### ISSUE TITLE
Slash added in target-URL after URL but before query

### ISSUE THREAD

**Issue by jpveen** [johngodley/redirection#2962]
### Summary
When targetting to an URL with a URI without a slash in the end it seems that the Redirection plugin adds a slash to the URI, which is not working for one of my important targets.

### Configuration and steps to reproduce
Config in Redirection:
Source-URL: /test
Target-URL: https://some.site/somepage?q=somequery

### Actual behavior
The result is that Redirection redirects to: https://some.site/somepage/?q=somequery
As you can see a **/ is inserted before the questionmark**.

### Versions
Wordpress 5.7.2, Redirection 5.1.1, PHP 7.3.28, webserver nginx/1.20.1, browser indepentent.

I tested on multiple Wordpress installations, different themes, and with different Redirection settings, but am unable to fix it myself. Can you check if this can be changed in the plugin?

Thanks,
Jan-Pieter

**Comment by johngodley** [comment]
Redirection doesn't change the target at all, and the slash is likely added by something else. The URLs aren't real so I can't test to see what might be causing it.

**Comment by jpveen** [comment]
I checked with redirect.nl and indeed seems to come from the target webserver and not from the plugin. Thanks for the quick answer, sorry for the too fast posting of this issue.... I am closing right away !
