### ISSUE TITLE
Temporary problem starting Redirection 5.1.1 - QUIC Protocol Error (Cloudflare)

### ISSUE THREAD

**Issue by JPBarringer** [johngodley/redirection#2964]
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 7.3.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
JavaScript: https://www.domain.com/app/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://www.domain.com/wp-json/

===
Dev Tools was showing the following error: 
"Failed to load resource: net::ERR_QUIC_PROTOCOL_ERROR" for redirection.js

This site is behind Cloudflare's DNS, WAF and Caching layer. A reload of the page seemed to fix it, so this report is mostly just informational.

**Comment by johngodley** [comment]
The message is from your browser:

https://stackoverflow.com/questions/28195610/why-is-this-error-appearing-in-chrome-load-resource-neterr-quic-protocol-erro
