### ISSUE TITLE
Problem starting Redirection 5.1.1

### ISSUE THREAD

**Issue by Bayaola** [johngodley/redirection#2968]
Plugin: 5.1.1 4.2
WordPress: 5.4.2 (single)
PHP: 7.3.27-1~deb10u1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
JavaScript: http://www.univ-ndere.cm/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: http://www.univ-ndere.cm/index.php?rest_route=/

**Comment by johngodley** [comment]
Please read the onscreen instructions and look at your developer console.

This file does not load: http://www.univ-ndere.cm/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
