### ISSUE TITLE
Porto theme - modal window

### ISSUE THREAD

**Issue by PetrJ82** [johngodley/redirection#2972]
### Summary

The popup (modal) will not open on the product detail (woocommerce). When I disable the Redirection plugin it works.

### Actual Behavior

The class button to open the modal window works on all regular wordpress pages. However, if it is placed in the product description, it does not work. If plugin redirection is disabled, the button works.

You can see it here, button "modal" in "POPIS" tab:
https://kamna.semtix.top/staging/produkt/nania-eris-premium-denim-blue-0-25-kg/

### Environment

All browsers
WP version: 5.7.2
Template: PortoVerze: 6.1.2
Redirection: 5.1.1

**Comment by johngodley** [comment]
Unless you are redirecting something that is needed then I don't see how Redirection could be involved here.

**Comment by PetrJ82** [comment]
After further testing, I found that the Redirection plugin is not the one causing the problem. The bug is elsewhere (unknown where yet). Sorry for the false alarm.
