### ISSUE TITLE
Trigger webhook with new redirection?

### ISSUE THREAD

**Issue by bogdancss** [johngodley/redirection#2973]
I am looking into a way of triggering a new Gatsby build when there is a new/changed/removed redirection. I have not seen any option in the Redirection plugin itself, but was wondering if it's possible to trigger the webhook somewhere else - maybe in the functions file?

**Comment by johngodley** [comment]
All available hooks are listed here:

https://redirection.me/developer/wordpress-hooks/

**Comment by bogdancss** [comment]
> All available hooks are listed here:
> 
> https://redirection.me/developer/wordpress-hooks/

Thank you for the reference - can you please provide an example of how I would call these?
As I mentioned - I do not want to modify the behaviour of Redirection - I simply need to trigger a webhook when a redirect has been removed or edited.

I assume I would need to use `redirection_redirect_deleted` and `redirection_redirect_updated` but not sure how.

Regards

**Comment by johngodley** [comment]
They are WordPress hooks. A reference is provided at the top of the page to the WordPress guide/

**Comment by bogdancss** [comment]
Thank you for your help.

For reference, if anyone else has the same requirement, this is the php code I've added to the functions.php file:

`add_action('redirection_redirect_deleted','trigger_build_webhook');
add_action('redirection_redirect_updated','trigger_build_webhook');

function trigger_build_webhook() {
    $webhook = curl_init('your_webhook_url');
    curl_setopt($webhook, CURLOPT_CUSTOMREQUEST, 'POST');
    curl_exec($webhook);
}`

**Comment by alexgarciab** [comment]
Is it possible to use a Wordpress plugin to do this? (If so, please recommend such plugin) - For example, use the **redirection_log_data** to send a webhook to a URL including the data collected in the redirect. Or is custom PHP code the only way to set this up?
