### ISSUE TITLE
In version 2.6.6 no more type (pass-thru) option available

### ISSUE THREAD

**Issue by skynet** [johngodley/redirection#298]
### Summary

Add new pass-thru redirect.

### Actual Behavior
Trying this:
![image](https://user-images.githubusercontent.com/139233/29220155-37c8dfe4-7e88-11e7-90af-4a076abde6e6.png)

I get this Error.
![image](https://user-images.githubusercontent.com/139233/29220223-673dfd54-7e88-11e7-8d2b-553ca0130510.png)

### Steps to reproduce

Try adding a new entry. Besides not seeing option for redirect type an error will surface.

### Environment

Redirection 2.6.6
WP 4.7.4

**Comment by johngodley** [comment]
Can you copy/paste the content from 'please include these details in your report' as text? There is more data inside the box than is shown, and it's the missing data that is important.

**Comment by johngodley** [comment]
Also, to get a pass-through just click the cog icon. I don't know why it's not showing in your screenshot.

<img width="552" alt="cog" src="https://user-images.githubusercontent.com/1277682/29239013-7f14eb88-7f3a-11e7-9f8f-163f750c8265.png">

**Comment by amhislop** [comment]
Looks like I'm getting the same error. I can see all the options are still there but I can't edit current redirects or add new ones. 

Here are the details I'm receiving.

Versions: Plugin 2.7.1, WordPress 4.8, PHP 5.6.30-1+wpengine8
Nonce: a6d0a170b6

Action: red_set_redirect
Params: {"orderBy":"id","selected":[],"filterBy":"","filter":"","id":0,"url":"/about","title":"","regex":false,"match_type":"url","action_type":"url","group_id":1,"action_code":301,"action_data":"/about-us"}
Code: 200 
Error: Invalid data
Raw: 0

**Comment by johngodley** [comment]
The only thing that stands out is that you are both using PHP 5.6. I'll have to try and install 5.6 and see if there's any issue there.

If it's possible to have a login to one of these sites that would also be very helpful - I might be able to track down the issue. If that sounds ok I can be contacted from the error page in Redirection.

**Comment by johngodley** [comment]
This should be fixed in the next version.
