### ISSUE TITLE
redirect www -> ()

### ISSUE THREAD

**Issue by acmqe** [johngodley/redirection#2988]
### Summary

I use the feature canonical  site, remove www.  My sitename is without www and I want to redirect visitor to my  non-www version.
This redirect does not work anymore. If a visitor uses www.kynogedrag.nl he gets a white page with an error message:

too many redirects
![image](https://user-images.githubusercontent.com/87533715/125960650-f1d5d8a5-b8ef-4ebd-86d7-cc3cb69e8241.png)

I tried deactivating different plugins and it is the redirection plugin that causes the problem.
If you deselect 'remove www' and select 'no preference', there is no error message (of course the site also does not redirect anymore).
If you select 'remove www' again, the white page with error message wil return.

### Environment
chorme v91, wp 5.7.2, plugin 5.1.1

**Comment by johngodley** [comment]
As noted at the top of the page, some of the settings can break your site. You will need to update your site settings yourself otherwise you can create a loop.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
