### ISSUE TITLE
Lowercase substitution doesn't work

### ISSUE THREAD

**Issue by roman-ianchenko** [johngodley/redirection#2990]
### Summary

Hi John, I wonder why the lowercase substitution is not working.

### Actual Behavior

Lowercase substitution doesn't work

### Steps to reproduce

I'm trying to create a redirect to lowercase version of the url with regex:
`^((?=.*[A-Z]).+)$`
and substitution rule:
`https://flores-shop.com.ua\L$1`
and it doesn't work as expected with the url like this
`/cat/VIP-bukety/`
It redirects me to 
`https://flores-shop.com.ual/cat/VIP-bukety/`
instead of 
`https://flores-shop.com.ua/cat/vip-bukety/`

when I try the same regex and substitution on the 
https://regex101.com/r/wMAfF0/1
it simply works

### Environment

Any browser

**Comment by johngodley** [comment]
I do not think PHP supports that.

You can use this instead: https://redirection.me/support/dynamic-urls/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
