### ISSUE TITLE
"Please keep only one SEO plugin active" issue with Rank Math 1.0.68

### ISSUE THREAD

**Issue by dvjrickkraft** [johngodley/redirection#2991]
### Summary
The plugin works perfectly right now, this is just a note/feedback for you.  There's a message at the top of the dashboard after installing Redirection.  "Please keep only one SEO plugin active, otherwise, you might lose your rankings and traffic. Click here to Deactivate."  If you click Deactivate, Redirection is disabled... not good. :)  Rank math is version 1.0.68.  In testing, deactivating/reactivating Redirection brought back the message.

I deactivated Rank Math, the notice went away, and reactivated Rank Math, and the message didn't come back.
After, I de/reactivated Redirection, and the top message notification came back.

### Environment
Firefox 89.0.2 64bit, WordPress Current version: 5.7.2 and Redirection plugin Version 5.1.2

![Capture](https://user-images.githubusercontent.com/5501662/126132174-35bb67f5-24a7-479e-87ea-33b77bfe3589.JPG)

![Capture2](https://user-images.githubusercontent.com/5501662/126133006-c6c89cc7-f800-4cf8-91f0-3074ed651489.JPG)

**Comment by johngodley** [comment]
Yep 🤷 

It may be worth directing this to rank math and asking them not to put unnecessary notices on your dashboard. I don't think it helps their reputation, and seems a little unpleasant.

**Comment by dvjrickkraft** [comment]
Oh okay, will do.  Didn't know if this notice was coming from Wordpress or something else.  I'll pass this along to Rank Math, thank you!  Consider this closed then.
