### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Ayanei** [johngodley/redirection#2993]
Hello,
Could you please help me with this issue ? 

```
Plugin: 5.1.2 4.2
WordPress: 5.7.2 (single)
PHP: 7.4.18
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
JavaScript: https://www.geekjunior.fr/wp-content/plugins/redirection/redirection.js?ver=5.1.2-f552e95c1d86a233313e7d65e8888ef5
REST API: https://www.geekjunior.fr/wp-json/
Query: ?page=redirection.php

Error: Unable to add new redirect (redirect_create_failed)
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":295,"wpdb":"Unknown column 'match_data' in 'field list'"}}
```

Here are some details  :
- I tried to repair my whole database (with a plugin) and to downgrade the version of the database Redirection plugin (in the "support" menu).
- I've no cache plugin and I emptied the server cache (with my hoster).
- I've the error both on my production site and developpement site.
- I tested the plugin with several url's with no success either.
- It's all green (good) in the support menu as well (about Rest API, database etc.)
![Uploading Capture d’écran 2021-07-22 à 00.23.36.png…]()

Thank you !

**Comment by johngodley** [comment]
On the support page change the database version to 2.4 and follow the instructions.

**Comment by Ayanei** [comment]
Ok, it's good now. Thank you !
