### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by tquenan-tiger** [johngodley/redirection#2999]
Getting an error even though the API test comes back as Good. I'm able to Create new redirects, but if I try to update, disable, or delete an existing redirect I run into problems.

```
Plugin: 5.0.1
WordPress: 5.6.4 (single)
PHP: 7.3.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
JavaScript: https://connect.tiger21.com/wp-content/plugins/redirection/redirection.js?ver=5.0.1-3aaca2e8b96d0af2cc585f8590d6feb3
REST API: https://connect.tiger21.com/wp-json/
Query: ?page=redirection.php

Error: Authorization header missed (rest_forbidden)
Raw: {"code":"rest_forbidden","message":"Authorization header missed","data":null}
```

**Comment by johngodley** [comment]
The message is caused by something on your site, possibly a security plugin.

You can see some code at the top of your REST API here:

https://connect.tiger21.com/wp-json/

![image](https://user-images.githubusercontent.com/1277682/127059830-8d9e159a-580f-4572-b5db-8c7e2253516d.png)

That should not exist and will also break things.

**Comment by tquenan-tiger** [comment]
Found I had to disable the Firewall setting on a security plug-in to get by the issue.

Would be beneficial if the API test was able to capture this failure (instead saying everything was good), so it could be addressed prior to putting any redirects in place.

**Comment by johngodley** [comment]
What is the firewall setting? There's only so much the plugin can detect, and so many more possible causes of problems. The plugin already contains a lot of unnecessary code to detect things when really it should only contain code to do with redirecting.
