### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by nickzou** [johngodley/redirection#3008]
```
Uncaught ReferenceError: wp is not defined https://touchbistro.local/wp-admin/tools.php?page=redirection.php 418,Uncaught ReferenceError: wp is not defined https://touchbistro.local/wp-admin/tools.php?page=redirection.php 424,Uncaught ReferenceError: wp is not defined https://touchbistro.local/wp-admin/tools.php?page=redirection.php 435,Uncaught ReferenceError: wp is not defined https://touchbistro.local/wp-admin/tools.php?page=redirection.php 453
```

Plugin: 5.1.3 4.2
WordPress: 5.8 (single)
PHP: 7.3.5
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
JavaScript: https://touchbistro.local/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://touchbistro.local/wp-json/

**Comment by johngodley** [comment]
This is caused by another plugin.

**Comment by nickzou** [comment]
Figured it out. I was trying to defer all my JS to improve performance but the way I wrote it I was during ALL JS everywhere not just on the frontend.
