### ISSUE TITLE
A LOT of 404 Errors from one IP Address

### ISSUE THREAD

**Issue by theinspiringdad** [johngodley/redirection#301]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

In the list of 404 Errors, there is one particular IP address that appears all the time. I guess I'm trying to understand what exactly the IP address field is about and why all of my RSS feeds are getting 404 errors from them. When I look up the IP address on Google, it's from a company in Texas. Are they blocking my pages? Can somebody tell me what exactly the issue is? 
### Actual Behavior

A lot of 404 Errors showing up and pointing to one IP address

### Steps to reproduce

I don't know what exactly the problem is. 

### Environment

![screen shot 2017-08-13 at 4 54 49 pm](https://user-images.githubusercontent.com/30988148/29253637-4710cde2-8048-11e7-9392-4450d2bc0e31.JPG)

Thanks for the help!

**Comment by johngodley** [comment]
If you hover/click on the referrer links it will show you the URL of the page where the request came from. It appears to be on your site, so you should look at that page and see if there are any references to the URL that is 404ing.

**Comment by theinspiringdad** [comment]
Hi John, I appreciate the reply!
All it says is "Wordpress/4.8.1; http://theinspiringdad.com" Does that make sense?

**Comment by johngodley** [comment]
Sorry, I didn't make that very clear - you need to look at the URL of the theinspiringdad.com link. It will appear in your browser status bar. Or you can click the link to be taken to the page. The grey text underneath is the  user agent that was used.

A user agent of WordPress/4.8.1 implies that a copy of WordPress is itself is requesting the URL. I don't know why that would be. Maybe something in WordPress (a plugin?) is requesting an incorrect RSS feed.

Overall it doesn't seem like anything to be worried about unless it's overloading your site, although it would be nice to stop the requests.

**Comment by theinspiringdad** [comment]
Last night, I cleared the log and now this morning, there are 2,929 of them... the thing is, I don't know if this is causing issues with some articles or not. When I click on the links, the page says "Oops, that page can't be found"... but when I go to the actual blog post for them, I can't seem to find the culprit because everything is displaying properly and when I click on the links to the RSS feed, it takes me to the website in which the article is published. 

Do you know if this will cause issues with Google and other search engines? 

I don't know if this matters or not, but I get most of the RSS feeds from google news. 

Sorry, I know this really doesn't have anything to do with your plugin, I'm just trying to see if you had any thoughts or workarounds for this issue. 

Thanks again for your help! I hope you have an awesome Monday!

**Comment by johngodley** [comment]
I noticed that the user agent is your own domain, and sure enough that IP address in Texas is your own website!

```
ping theinspiringdad.com
PING theinspiringdad.com (108.167.164.66): 56 data bytes
```

The address is probably of the server where your site is being hosted.

I don't think it will cause an issue with Google, but it seems like you are basically spamming your own server. It's hard to know why this is happening, but I'd start by disabling all plugins and whatever else you have running, and work you way back up. Hopefully at some point you'll re-enable the thing that is fetching the URLs

**Comment by johngodley** [comment]
Going to close this as resolved
