### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by zaatt** [johngodley/redirection#3011]
```
SyntaxError: Unexpected end of script https://www.imaiko.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717 2
```

Plugin: 5.1.3 4.2
WordPress: 5.8 (single)
PHP: 7.3.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
JavaScript: https://www.imaiko.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.imaiko.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
