### ISSUE TITLE
Import redirects into a specific group via json doesn't seem to work

### ISSUE THREAD

**Issue by awakash** [johngodley/redirection#3016]
Hello,

I'm working on importing a number of redirects into a group called 'Redirects' with id=25 which I pulled from the database.

<img width="568" alt="fish__Users_abodiwala_www_sites_aclu-wp" src="https://user-images.githubusercontent.com/5031120/129105677-4dcb0274-e8cc-47a7-aa36-fbe8dfdfe8b1.png">

Within the import file, group_id matches the `id` of 25
```
{
  "redirects": [
        {
            "url": "\/source",
            "action_type": "url",
            "action_data": {
                "url": "\/target"
            },
            "hits": "3914",
            "match_type": "url",
            "group_id": 25,
            "last_access": "July 4, 2021"
        }
  ]
}
```

I should see this redirect get created within the Redirects group but what I see happening is that a group called `Group` is created and the redirect is added to this.

<img width="817" alt="Redirection_‹_ACLU_—_WordPress" src="https://user-images.githubusercontent.com/5031120/129105904-a7e586b0-941c-44f4-9ba9-e1ebb03c83df.png">

I tried `"group_id": "25"` as well but saw the same issue.

Are you witnessing the same?

**Comment by johngodley** [comment]
Moving to #2263
