### ISSUE TITLE
Wrong parsing of permalinks

### ISSUE THREAD

**Issue by emsi** [johngodley/redirection#3018]
When adding source link of 
`/%category%/%postname%/%year%-%monthnum%-%day%/%hour%:%minute%:%second%`
It's saved as
`/tegory%/%postname%/%year%-%monthnum%-y%/%hour%:%minute%:%second%`

![image](https://user-images.githubusercontent.com/433383/129356059-1cd2f1ee-1745-497e-908c-540c8720a848.png)

![image](https://user-images.githubusercontent.com/433383/129356083-ee7a3742-b292-4cfb-8a7b-1b70d6dd0fa5.png)

**Comment by johngodley** [comment]
When adding that where?

**Comment by emsi** [comment]
> When adding that where?

I've added some screenshots.

**Comment by johngodley** [comment]
Redirection redirects URLs, not permalinks. What you have shown will not work.

See https://redirection.me/support/site-options/ for permalinks.

**Comment by emsi** [comment]
I understand. I tried that too but it does not seem to do anything.

![image](https://user-images.githubusercontent.com/433383/129356510-b5061993-e4ce-4247-8ffc-5ac436f78eb8.png)

**Comment by johngodley** [comment]
Have you cleared all your caches? 

As it states, the feature is in beta. It might not work for every combination of permalink.

**Comment by emsi** [comment]
Yes. I'm convenient it's not related to cache.

Is there any way I can debug it or see what it does and potentially identify why it does not work?

**Comment by emsi** [comment]
I'm guessing it's the `:` in the permalink that causes the issue.

**Comment by johngodley** [comment]
No, there is no debugging for this. It doesn't work because the feature does not cover all combinations of permalinks. You will need to wait until it does for this particular combination.

**Comment by emsi** [comment]
What are the prospects? Any chance for it in the next release?

**Comment by johngodley** [comment]
I cannot provide a timeline for it.

**Comment by johngodley** [comment]
I'm closing this issue as it relies on the beta feature being completed
