### ISSUE TITLE
Redirct not working

### ISSUE THREAD

**Issue by WPUncode221** [johngodley/redirection#3019]

**Comment by WPUncode221** [comment]
Hello
I appreciate the unpaid work!
I have Wordpress 5.8 latest. I have your redirect latest. I have added 20 redirects, but none will run.
![redirect-status](https://user-images.githubusercontent.com/89106356/129801598-a3125858-c5ef-450a-88ac-a2001f7d61f9.jpg)
![redirect](https://user-images.githubusercontent.com/89106356/129801606-e63f615f-196e-40e7-b8f7-696243743fc9.jpg)
I have set the old url and then the target new url. On checking the url in a browser, it shows url not found:

Not Found

**The requested URL /buy-magnetic-glass-dry-wipe-boards/ was not found on this server.**

Can you advise please? I am stuck. Thanks.

**Comment by johngodley** [comment]
You seem to have created 'URL and server' redirects. You probably want 'URL only' redirects.
