### ISSUE TITLE
export 404 log

### ISSUE THREAD

**Issue by Jeroenleender** [johngodley/redirection#3022]
This is not really a bug issue or feature request but more like a question.

I would like to export the 404 logs so i can parse them in a log reader and filter out the bad ones that are clearly guessing for vulnerabilities. Instead of logging into each site to press a button to manually download the log is there an easier way to get the log file created?

I did find `wp eval 'RE_404::export_to_csv();' | tail -n+2` but i think this will need wpcli access.
Is there a better way to at least create the log file and save it locally on the system?

This is mainly needed on sites where there is no access to apache/nginx log files.

Thanks in advance!

**Comment by johngodley** [comment]
There is no easier way to do this.

**Comment by Jeroenleender** [comment]
thx for the update
