### ISSUE TITLE
CSP - unsafe-inline : generated by redirection

### ISSUE THREAD

**Issue by tornadou** [johngodley/redirection#3029]
Hi,
just to informed you that I had to desactivate your (nice) plugin.
the reason was that since 18/8, I had trouble on our website, and did not get any new orders.
the stripe/paypal steps was freezing, just like continuously looking for data.

I opened a ticket on the host side, and I finally pointed out that it was a CSP problem generated by Redirection.

Here is what helped me (support for the hosting company): 

"Le header HTTP suivant est retourné par le site : 
content-security-policy: default-src 'self'; script-src 'unsafe-inline' 'unsafe-eval' http:; style-src 'unsafe-inline' http:; img-src http: data:; font-src http: data:; sandbox allow-forms allow-scripts"

On the 18/8 I made the migration from WP 5.7.2 > 5.8

before this, everything was fine.

Hope this can help,

Regards
Bruno

**Comment by johngodley** [comment]
You enabled the above header and you should make sure it is appropriate for your site. If it is blocking your payment scripts then you should not enable it.

This has nothing to do with WP 5.8

**Comment by tornadou** [comment]
ok... but I was using redirection since months without any troubles, and did non change ant configuration last weeks.
where do you expect me to have "enabled the above header?"

**Comment by johngodley** [comment]
Nothing has changed in Redirection here. You have enabled this as part of the site headers, and it is likely that your payment scripts have changed.

**Comment by tornadou** [comment]
ok thx ;)
