### ISSUE TITLE
How do I dynamically redirect ?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [johngodley/redirection#303]
How do I dynamically redirect ?

I'm going to put the old link xxx.com/?paged=123
Redirected to the new link xxx.com/?pages=123

How should write code?

**Comment by johngodley** [comment]
Use a regular expression such as: `\?paged=(\d*)$` => `/?pages=$1`

This is untested
