### ISSUE TITLE
A Redirect Is "Stuck" In Browsers after Deletion

### ISSUE THREAD

**Issue by Mike-Reid-Marketing** [johngodley/redirection#3030]
Summary:
I'm trying to change a redirect on one of my urls, pointing it to a new location. Any help would be much appreciated!

Actual Behavior:
I deleted the old redirect and added a new one in the same group. 
However, browsers are still redirecting to the old destination url. 
I have tested with curl, which shows the redirect going to the correct place!
I have tested Chrome (incognito) on mobile as well as desktop, Firefox, and Brave.
I have cleared the cache via WP Rocket. 

Environment:
Redirection 5.1.3
WordPress 5.8

**Comment by johngodley** [comment]
If you deleted a redirect then it is no longer redirecting. You have tested with curl and it is correct. Your browser is caching the old redirect.
