### ISSUE TITLE
Can't get plugin to add security headers

### ISSUE THREAD

**Issue by DougNix** [johngodley/redirection#3034]
### Summary

I tried to add HTTP security headers using the site tab and was unable to make it work.

### Actual Behavior

When I select "add security presets" and click Update, none of the headers are added to the list.

### Steps to reproduce

Go to settings>redirection>sites and then down to HTTP Headers.
Pull down the add headers list and select "add security presets"
Click the Update button

### Environment

Firefox 91.0.2
WordPress 5.8
Redirection 5.1.3

**Comment by johngodley** [comment]
You need to press the 'add security presets' button.

**Comment by DougNix** [comment]
I selected them from the pull down, then hit “update”. I don’t see a button to add presets. 

Doug

**Comment by johngodley** [comment]
The dropdown is a button.

**Comment by DougNix** [comment]
OK, thanks. That’s a bit unintuitive.

Doug

**Comment by DougNix** [comment]
All good now, and thank you for the quick support.
