### ISSUE TITLE
Automatic creation of wrong redirection with WPML

### ISSUE THREAD

**Issue by calixtofernandez** [johngodley/redirection#3038]
Hi,

This problem has appeared in the last updates of redirection plug-in, or at least I didn't notice it before.

With WPML plug-in and when "monitor URL changes" option is active, when we update a translation of a post (or portfolio) then a "mixture" of URL redirection is automatically generated between languages resulting in a 404 error page.

Example:

Original URL spanish:
        https://domain.com/es/vino/roble/
Translated URL in english:
       https://domain.com/en/wine/roble/

However after updating the translation with WPML, 3 new redirections are generated automatically:
       /en/wine/roble/  -> /es/wine/roble/  (3 times)

As this page doesn't exist a 404 error is  returned. I have to remove manually the 3 redirections to solve the issue.

Regards,
Alejandro.

![Captura de pantalla 2021-08-31 a las 11 44 33](https://user-images.githubusercontent.com/29119482/131481002-e9146c86-6e4d-4d9f-b014-39ffca3194f7.png)

**Comment by johngodley** [comment]
Nothing has changed in the plugin that would cause this to happen. Has anything changed in WPML?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
