### ISSUE TITLE
Redirection prevents post tags from not being recorded.   Redirection impedi que TAGs dos post não sejam gravadas.

### ISSUE THREAD

**Issue by Idelfonsorobertosantos** [johngodley/redirection#3046]
Redirection prevents post tags from not being recorded.
TESTS PERFORMED
1 - disable all plugins - write normally.
2 - switch with active redirection, do not record TAGs.
3 - Activate all Plugins, and not activate Redirection, it normally records Tags.
4 - leaving only the Redirection active does not record the tags.

active redirection https://i.imgur.com/ySHhu5D.png
does not record the tags in the post using gutemberg blocks editor.
https://i.imgur.com/VnLlEUi.png
updating https://i.imgur.com/NLa2LMU.png.
if you return to the post later , the TAGS are not recorded
watch the time of prints
https://i.imgur.com/1HK1jZs.png

WORDPRESS Version | 5.8
Site language | pt_BR
User language | pt_BR
Time Zone | America/Sao_Paulo
Home page URL | https://2e4rodas.com.br
Website URL | https://2e4rodas.com.br
Permanent Link Structure | /site/%category%/%postname%
Is this site using HTTPS? | Yes
Is this a multisite? | Not
Can everyone register on this site? | Yes
Is the site blocking search engines? | Not
Default status for comments | Open
Type of environment | production
User count | 41
Communication with WordPress.org | WordPress.org is accessible

Server Architecture | Linux 3.12.18-clouder0 x86_64
Web server | Apache
PHP Version | 7.4.23 (Supports 64bit values)
PHP SAPI | apache2handler
Max input variables in PHP | 3000
PHP Time Limit | 120
PHP Memory Limit | 768M
Maximum time for entries | 120
Max. upload | 256M
Max. post content | 256M
cURL version | 7.66.0 OpenSSL/1.1.1l-fips
Is SUHOSIN installed? | Not
Is the Imagick library available? | Not
Are permanent links supported? | Yes
.htaccess rules | Custom rules have been added to your .htaccess file.

The WordPress Main Directory | writable
The wp-content | writable
The upload directory | writable
The plugins directory | writable
The themes directory | writable
Impedi que os TAGs dos postes sejam gravadas de redirecionamento.
TESTES QUE REALIZADOS
1 - desativar todos os plugins - normalmente.
2 - trocar com redirecionamento ativo, não grava como TAGs.
3 - ativar todos os Plugins, e não ativar o Redirecionamento grava normalmente como Tags.
4 - deixar somente o Redirecionamento ativo não grava como TAGs.

redirecionamento ativo https://i.imgur.com/ySHhu5D.png
não grava as TAGs no post usando o editor gutemberg blocos.

https://i.imgur.com/VnLlEUi.png
atualizando https://i.imgur.com/NLa2LMU.png.
se voltar ao post depois, pois os TAGS não estão foram gravadas
observar o horario dos impressos
https://i.imgur.com/1HK1jZs.png
***********************************

wordpress Versão | 5.8
Idioma do site | pt_BR
Idioma do usuário | pt_BR
Fuso horário | America/Sao_Paulo
URL da página inicial | https://2e4rodas.com.br
URL do site | https://2e4rodas.com.br
Estrutura de links permanentes | /site/%category%/%postname%
Este site está usando HTTPS? | Sim
Este é um multisite? | Não
Todos podem se cadastrar neste site? | Sim
O site está impedindo buscadores? | Não
Status padrão para comentários | Aberto
Tipo de ambiente | production
Contagem de usuários | 41
Comunicação com o WordPress.org | WordPress.org está acessível

Arquitetura do servidor | Linux 3.12.18-clouder0 x86_64
Servidor web | Apache
Versão do PHP | 7.4.23 (Suporta valores de 64bits)
PHP SAPI | apache2handler
Máx. de variáveis de entrada no PHP | 3000
Limite de tempo do PHP | 120
Limite de memória do PHP | 768M
Tempo máximo para entradas | 120
Tamanho máx. de upload | 256M
Tamanho máx. de post PHP | 256M
Versão do cURL | 7.66.0 OpenSSL/1.1.1l-fips
O SUHOSIN está instalado? | Não
A biblioteca Imagick está disponível? | Não
Os links permanentes são suportados? | Sim
Regras .htaccess | Regras personalizadas foram adicionadas ao seu arquivo .htaccess.

O diretório principal do WordPress | Gravável
O diretório wp-content | Gravável
O diretório dos uploads | Gravável
O diretório dos plugins | Gravável
O diretório de temas | Gravável

**Comment by johngodley** [comment]
I am unable to reproduce this problem. Redirection does not use tags in anyway, and there are no other reports of this. It is more likely that this is something specific to your site or setup.

**Comment by Idelfonsorobertosantos** [comment]
Hello John  
thanks for your answer.

also thought about it.

Then I reviewed the Redirection settings, and left everything with basic.

Your plugin is very important to our site, so I would like to find a solution.

basically
we use the DIVI theme.

We use few plugins, as you can see in the window's print.


has how to send you an access to our wordpress dashboard.

could create a user.

anyway I will continue to look for a solution

thanks

damn me my english is basic.

**Comment by johngodley** [comment]
Did you mean to leave a screenshot? Nothing has been attached

**Comment by Idelfonsorobertosantos** [comment]
Name 2e4 Wheels (2e4-Wheels)
Version 0.5
Author 2e4 Wheels
Author of the website http://www.alinhador.com.br
Divi ascending theme (Divi)
Theme features core-block-patterns, widgets-block-editor, post-thumbnails, custom-background, automatic-feed-links, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc -product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets
Location of themes directory /home/customer/www/2e4rodas.com.br/public_html/wp-content/themes/2e4-rodas
Automatic Updates Disabled

![plugins](https://user-images.githubusercontent.com/39732097/132139123-cdb001de-862d-4f4a-a1c6-dd065038fb95.png)

Name Divi (Divi)
Version 4.10.5 (Latest Version: 4.10.6)
Author Elegant Themes
Author of the website http://www.elegantthemes.com
Location of themes directory /home/customer/www/2e4rodas.com.br/public_html/wp-content/themes/Divi
Auto update Disabled
Twenty Seventeen (twentyseventeen) Version 2.8 by the WordPress team | Automatic updates disabled

Brazilian Market on WooCommerce Version 3.7.2 by Claudio Sanches | Automatic updates disabled
Broken Link Checker Version 1.11.15 by WPMU DEV | Automatic updates disabled
Captcha Version 4.4.5 by simplywordpress | Automatic updates disabled
Cloudflare Version 4.5.1 by Cloudflare, Inc. | Automatic updates disabled
Elegant Themes Updater Version 1.1 by Elegant Themes | Automatic updates disabled
Product Feed PRO for WooCommerce Version 10.5.6 by AdTribes.io | Automatic updates disabled
Redirection Version 5.1.3 by John Godley | Automatic updates disabled
SiteGround Optimizer Version 5.9.6 by SiteGround | Automatic updates disabled
WooCommerce Version 5.6.0 by Automattic | Automatic updates disabled
Yoast SEO Version 17.0 by Team Yoast | Automatic updates disabled
Yoast SEO Premium Version 17.0 by Team Yoast | Automatic updates disabled


Claudio Sanches - Correios for WooCommerce Version 3.8.0 by Claudio Sanches | Automatic updates disabled
Elegant Themes Support Version 1.5 by Elegant Themes | Automatic updates disabled
Frenet Shipping Gateway for WooCommerce Version 2.1.10 by Rafael Mancini | Automatic updates disabled
Monarch Plugin Version 1.4.14 by Elegant Themes | Automatic updates disabled
Product CSV Import Export (BASIC) Version 2.0.8 by WebToffee | Automatic updates disabled
WooCommerce Admin Version 2.6.1 by WooCommerce | Automatic updates disabled

![servidor](https://user-images.githubusercontent.com/39732097/132139184-cdf0042b-9f13-491a-8864-a434ea3e37de.png)

![redirection1](https://user-images.githubusercontent.com/39732097/132139238-5ac9f616-9c3d-4ce2-bb30-9bd662ce4ba8.png)
![redirection2](https://user-images.githubusercontent.com/39732097/132139239-d10f1446-2784-40b4-b413-8a583bd346c2.png)

**Comment by johngodley** [comment]
It is more likely this is a caching issue, possibly caused by Cloudflare.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
