### ISSUE TITLE
Redirection not working on mobile browsers

### ISSUE THREAD

**Issue by johnmurd** [johngodley/redirection#305]
### Summary

I'm doing the following redirect.  www.sitename.com 

redirected to www.sitename.com/home

### Actual Behavior

It works great on desktop but somehow it hasnt had any effect on mobile browser.  Have tried deleting cache, cookies etc... no joy

Any idea how I can remedy this?

**Comment by johngodley** [comment]
Fixed via email - cache needed an extra clear!
