### ISSUE TITLE
Problem with user agent match

### ISSUE THREAD

**Issue by taraktalluri** [johngodley/redirection#3052]
To help track problems please follow this template. If you can provide screenshots then that will help.

*redirection plugin not working after update of word press*

### Summary

im trying to redirect my content from all browsers except mobile browser.

### Actual Behavior

not redirect pages

### Steps to reproduce

should recirect pages

### Environment

Google Chrome is up to date
Version 93.0.4577.63 (Official Build) (64-bit)
wordpress 5.8.1
redirection plugin 5.1.3

**Comment by johngodley** [comment]
The plugin does work with WP 5.8.1.

Can you provide more details about your problem?

**Comment by taraktalluri** [comment]
i have used user agents

iPad|iPod|iPhone|Android|BlackBerry|SymbianOS|SCH-Md+|Opera Mini|Windows
CE|Nokia|SonyEricsson|webOS|PalmOS|chrome|mozilla

and trying in chrome and mobile devices and mozilla also. but not
redirecting. after sometime it showing 404 error. when i save permalinks
the links working. but not redirecting. please check configure
configuration screenshot and redirection url ( not redirecting to playstore)

**Comment by johngodley** [comment]
So it is working with WP 5.8.1, but your agent match is not matching. More than likely this is not correct and you will need to use a value that matches the whole user agent.

**Comment by taraktalluri** [comment]
i mean some urls from wordpress should redirect to single url(playstore url)
