### ISSUE TITLE
User Agent Redirect Failing

### ISSUE THREAD

**Issue by JaxTerra** [johngodley/redirection#3058]
![image](https://user-images.githubusercontent.com/22583404/133428890-830e2d5b-0bf5-4ff2-897f-ef0a904a6eb9.png)

Hi, Im having an issue with user agent based redirects. WP version = 5.8 Redirection Plugin version = 5.1.3

I setup the rediction for android as above, i use my samsung galaxy fold3 running Android version = 11, as a user i expect the url to redirect to the play store url. Actual response is im routed to the site url with no redirection.

Same result using iPod|iPhone|iPad user agent settings and using an iPhone 11.

**Comment by johngodley** [comment]
The user agent must match exactly. I don't think Android devices have a user agent that exactly matches 'Android'

**Comment by JaxTerra** [comment]
Thanks for your reply. I actually think now my best use case here would be to use native smart banners.

All the best.
