### ISSUE TITLE
Create wp_options-entry for 'redirection_database_stage' with autoload=yes

### ISSUE THREAD

**Issue by cwe1ss** [johngodley/redirection#3062]
Hello John,

thank you for this great plugin! Love it so far!

While looking through all queries that are executed in our Wordpress site, I noticed that the following DB query is executed for each page:

```sql
SELECT option_value
FROM wp_options
WHERE option_name = 'redirection_database_stage'
LIMIT 1
```

Our `wp_options`-table doesn't contain a row with this option_name, so WP obviously doesn't load it with all other "autoload=yes"-options and needs to do a separate query.

IIUC, this seems to be called by this code: https://github.com/johngodley/redirection/blob/7d9b22aa9644a032f3e68bc0ad4c5ea69b799d37/database/database-status.php#L34

If the plugin still needs this option on each request, I think it would be great if it could create a wp_options-entry with `autoload=true` as this will remove the additional query.

This obviously is a rather small detail and it can easily be fixed by manually inserting the wp_options-entry. Just thought I'd report it anyway as it would make the plugin slightly more performant! 🚀

**Comment by johngodley** [comment]
Thanks. This will be removed in the next release.

**Comment by cwe1ss** [comment]
Thank you very much!!
