### ISSUE TITLE
howto set 404 to redirect to real 404?

### ISSUE THREAD

**Issue by humpataa** [johngodley/redirection#3063]
Hi,

we're getting lots of 404 requests from Google / Petal / Bing bots. They all get forwarded to a basic webpage showing a Wordpress message "nothing here" or similar. I know this may nothing really bad, but it is very annoying.

Since we have set all redirects from not longer existing real content to new pages, we would like to replace this message so that 404 requests really produce a webserver reply 404. How to do this?

Any hint is appreciated.
Thank you!

**Comment by johngodley** [comment]
The WordPress 404 page is a real 404 page. You can modify that to appear how you like, but you do not need to change anything else.

**Comment by humpataa** [comment]
Thank you John!
