### ISSUE TITLE
Problem with 404

### ISSUE THREAD

**Issue by mateo10009992** [johngodley/redirection#3066]
Hello,
I noticed problem on my domains.  I tried to go on www.pagename.com/bank/ - this page doesn't exist, but I was redirected to www.pagename.com/bank-xxx/ - this page exist on my site. How can I change this issue? When someone want to go on page which doesn't exist it must be 404.

**Comment by johngodley** [comment]
How is this related to Redirection?

**Comment by mateo10009992** [comment]
Maybe redirection create this problem?

**Comment by johngodley** [comment]
Redirection only redirects things that you tell it to redirect. Have you created a redirect for the above page?

**Comment by mateo10009992** [comment]
My page create randomly 301 when the name url is similar to existing.

**Comment by johngodley** [comment]
I'm not sure what you mean by that. Can you add some more details about the problem? It's hard to help with so little information. For example, a real URL instead of a fake URL helps a lot.

**Comment by mateo10009992** [comment]
Sure,
take a look at:

https://mieszkanienakredyt.pl/pko/ (doesn't exist)  --> redirect to https://mieszkanienakredyt.pl/pko-bp-infolinia-calodobowa-numer-telefonu/, but I didn't set this rediection. 

https://mieszkanienakredyt.pl/santander(doesn't exist) --> redirect to https://mieszkanienakredyt.pl/wp-content/uploads/2020/08/Santander.png

**Comment by johngodley** [comment]
https://redirect.li/http/?url=https%3A%2F%2Fmieszkanienakredyt.pl%2Fpko%2F
https://redirect.li/http/?url=https%3A%2F%2Fmieszkanienakredyt.pl%2Fsantander

**Comment by mateo10009992** [comment]
so it means that the problem come from Wordpress not from Redirection

**Comment by johngodley** [comment]
The information shows that the redirects come from WordPress and Yoast.

**Comment by mateo10009992** [comment]
Do you know how to solve this problem?

**Comment by johngodley** [comment]
I do not. You can contact WordPress and Yoast support for that.

**Comment by mateo10009992** [comment]
Thanks
