### ISSUE TITLE
How can I redirect every page of a site where the old site used to end every page with .php?

### ISSUE THREAD

**Issue by kiloj757** [johngodley/redirection#3069]
I have rebuilt a site and each page of the site ends with '.php'.

Examples from old site:

```
http://www.dynamicdrain.net/about.php
http://www.dynamicdrain.net/cipp-process.php
http://www.dynamicdrain.net/work-history.php
```
Examples of new site pages respectively are:

```
https://www.dynamicdrain.net/about/
https://www.dynamicdrain.net/cipp-process/
https://www.dynamicdrain.net/work-history/
```
I am looking for a way to permanently redirect all traffic from domain names ending with `*.php to */`.

Is this possible? I fear I may have already ruined their SEO link juices by doing this.

I have currently tried to have the source URL defined as `(php)` force a regex to redirect to the target URL of `/` but it is not working for me.

I also tried to enable: Canonical Settings
 Force a redirect from HTTP to HTTPS -

and redirect `/about.php`
to `/about/`

And I still can not get it to work. Any help is greatly appreciated!

**Comment by johngodley** [comment]
From the support site:

https://redirection.me/support/redirect-regular-expressions/
https://redirection.me/support/problems/url-not-redirecting/
