### ISSUE TITLE
Can't view 404s

### ISSUE THREAD

**Issue by SQLMac** [johngodley/redirection#307]
To help track problems please follow this template. If you can provide screenshots then that will help.
![screenshot 2017-08-15_09-13-37](https://user-images.githubusercontent.com/1228957/29322236-1178b994-819a-11e7-96f0-916c08352e69.png)

### Summary

I was trying to check on any 404s that were logged. 

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

any time I check on 404s

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Chrome 59, WP 4.8.1, Redirect 2.7.1 

Error Message:

Versions: Plugin 2.7.1, WordPress 4.8.1, PHP 7.0.21
Nonce: 6af9a0decb

Action: red_get_logs
Params: {"orderBy":"","selected":[],"filterBy":"","filter":"","logType":"404"}
Code: 403 
Error: Unexpected end of JSON input
Raw:

**Comment by johngodley** [comment]
The request is returning HTTP 403, which means forbidden access. Do you have anything installed that could be blocking requests? For example, WordFence, or a firewall etc

Does it only happen for the 404 log page?

**Comment by SQLMac** [comment]
Wordfence is installed as well as wp security. However, everything worked fine until the recent update. 

Garland MacNeill
gmacneill@sqlmac.com
Twitter - @sqlmac
phone 720.583.5018
www.sqlmac.com

On August 15, 2017 at 10:34:10, John (notifications@github.com) wrote:

The request is returning HTTP 403, which means forbidden access. Do you have anything installed that could be blocking requests? For example, WordFence, or a firewall etc

Does it only happen for the 404 log page?

**Comment by johngodley** [comment]
Redirection is now mostly JavaScript based, which is something that has changed recently. I ask about Wordfence because I know it has a setting where it can [block ajax requests](https://docs.wordfence.com/en/Web_Application_Firewall_-_Blocked_Ajax_Requests), and that is possibly something that could block the requests that Redirection makes - a HTTP 403 code indicates that the server has refused the request. Redirection itself doesn't have any code to do this, so it makes me think that something else is blocking the request.

**Comment by SQLMac** [comment]
A refresh of the page actually brings up the 404 logs. 

Garland MacNeill
gmacneill@sqlmac.com
Twitter - @sqlmac
phone 720.583.5018
www.sqlmac.com

On August 15, 2017 at 14:48:30, John (notifications@github.com) wrote:

Redirection is now mostly JavaScript based, which is something that has changed recently. I ask about Wordfence because I know it has a setting where it can block ajax requests, and that is possibly something that could block the requests that Redirection makes - a HTTP 403 code indicates that the server has refused the request. Redirection itself doesn't have any code to do this, so it makes me think that something else is blocking the request.

**Comment by johngodley** [comment]
So when you first load the page you get the error, but when you refresh it's ok?

**Comment by SQLMac** [comment]
Yep. Also see the same behavior on the options page as well. 

Garland MacNeill
gmacneill@sqlmac.com
Twitter - @sqlmac
phone 720.583.5018
www.sqlmac.com

On August 16, 2017 at 23:53:35, John (notifications@github.com) wrote:

So when you first load the page you get the error, but when you refresh it's ok?

**Comment by johngodley** [comment]
Would it be possible to get a login to this site to see if I can debug it further? If so I can be contacted by the email listed on the support page of the plugin.

**Comment by SQLMac** [comment]
I dont see why not. Is there a better email address to use than this one? 

Garland MacNeill
gmacneill@sqlmac.com
Twitter - @sqlmac
phone 720.583.5018
www.sqlmac.com

On August 17, 2017 at 10:45:30, John (notifications@github.com) wrote:

Would it be possible to get a login to this site to see if I can debug it further? If so I can be contacted by the email listed on the support page of the plugin.

**Comment by johngodley** [comment]
My email is on the support page of the plugin, or you can click the 'email' button in the error shown above

**Comment by johngodley** [comment]
I received an invite to a website. If that is yours then the link doesn't work, and the return email address on the invite bounces.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
