### ISSUE TITLE
Skip "monitor changes to posts" redirection creation only on certain posts

### ISSUE THREAD

**Issue by Startouf** [johngodley/redirection#3072]
I am not sure this is the best place to ask this question, but I could not find any reference to a support forum or anything in the readme so here I am:

I have a backend service that published a lot of posts on wordpress, and handles creating redirections
For example, my backend services publishes `/[category]/[random-id]-[slug]` and creates a redirection url to redirect all other urls starting by `/[category]/[random-id]` to `/category/random-id-an-awesome-product` (using a catch all regex like `^\/category\/random-id((?!slug).)*$`)

When the slug changes (and it may happen often), my backend service updates the post and the redirection manually : this avoids creating too many redirections. In this case, I do not want to the "post change URL monitor" behavior to automatically create a redirection, since I already handle that. But on other posts not managed by my backend, I do want to have the "post change URL monitor" to create redirections.

Is it possible to skip creating a redirection in this case ? 

When reading the FAQ "Note that any custom post types you have on your site will also appear in this list. For example, WooCommerce products." it came to my mind that maybe it would be possible to register a particular post category as a "custom post type" to appear in the list... but maybe there are other solutions.

Or am I going the wrong way ? (I am planing to have my backend manage ~25k posts and redirections like this, I'm a bit worried about performance if I use too many complex regex)

**Comment by johngodley** [comment]
> Is it possible to skip creating a redirection in this case

You will need to create your own exceptions:

https://redirection.me/developer/wordpress-hooks/

I would avoid having a lot of regexes, especially 25k of them. You would be better having many simple redirects.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
