### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by andrewchaika** [johngodley/redirection#3075]
```
Uncaught SyntaxError: Invalid or unexpected token https://passapassa.pl/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717 2
```

Plugin: 5.1.3 4.2
WordPress: 5.8.1 (single)
PHP: 7.4.20
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
JavaScript: https://passapassa.pl/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://passapassa.pl/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This is almost certainly caused by another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
