### ISSUE TITLE
Redirect happening without configuration.

### ISSUE THREAD

**Issue by macdabby** [johngodley/redirection#3079]
### Summary

Users who visit /shop are redirected to /affiliate-area. However, there is no redirect set up for that, and the /shop page is supposed to go to /shop-nugg. /shop is a hardcoded value for the woocommerce plugin.

there is also a redirect from /affiliates to /affiliate-area. this is not managed by redirection.

I have confirmed that disabling the redirection plugin does prevent the unwanted behavior of redirecting /shop to /affiliate-area

### Actual Behavior

Users who visit /shop are redirected to /affiliate-area.

### Steps to reproduce

Visitng /shop

### Environment

This happens on all browsers when not logged in, including desktop and mobile.

These are the only redirects set.

![Screen Shot 2021-09-29 at 8 47 09 AM](https://user-images.githubusercontent.com/176957/135272673-5903a518-3f16-459c-bd45-41bdaf44e2c0.png)

**Comment by johngodley** [comment]
The plugin only redirects things you configure and will never do anything not in the list.

You haven't provided a real URL so I can't test, but is it possible something else is redirecting after the initial Redirection redirect?

**Comment by macdabby** [comment]
I understand that's what it's SUPPOSED to do. 

This is the url:
https://nuggofknowledge.com/shop

I'm sure this is some sort of conflict with another plugin, but i can't figure out which one, and this type of behavior shouldn't be mixing information between two plugins - eg listening to a redirect source from one plugin and sending to a redirect location in another plugin.

**Comment by johngodley** [comment]
![image](https://user-images.githubusercontent.com/1277682/135277870-adbaa856-0bf3-4bbd-9cd7-ba0846abf4e6.png)

https://redirect.li/http/?url=https%3A%2F%2Fnuggofknowledge.com%2Fshop

**Comment by macdabby** [comment]
i see - then i agree - it's definitely not this plugin. i'll keep looking. thanks.
