### ISSUE TITLE
I can't control the redirection of the URL per agent!

### ISSUE THREAD

**Issue by zetagalactic** [johngodley/redirection#308]
![secreen-01](https://user-images.githubusercontent.com/31048397/29334920-5672a91e-8209-11e7-91e2-860375eb8834.jpg)
Hello,
I'm trying to make a mask for my website that allows me to show different pages to my visitors per their browser agents, Chrome, Mozilla, or even google crawlers...etc.
I tried that and it did work out, I'm not sure what I made wrong, that's why I'm writing this issue to get some help.

Best regards,

**Comment by johngodley** [comment]
Fixed in #344
