### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by ldashdesigns** [johngodley/redirection#3083]
```
Plugin: 5.1.3 4.2
WordPress: 5.8.1 (single)
PHP: 7.4.24
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
JavaScript: https://www.l-designs.co/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.l-designs.co/wp-json/
Query: ?page=redirection.php

Error: Failed to fetch
```

Hi i recently changed my website permalinks,, its a new website....with a couple of pages.. tried using the redirection plugin but it doesnot seem to be working with the above error i receive nor the redirection as well... 

any answers on how to fix this issue will be appreciated.

**Comment by johngodley** [comment]
Your site has a redirect that is removing the trailing `/`. This is causing the above error.

https://redirect.li/http/?url=https%3A%2F%2Fwww.l-designs.co%2Fwp-json%2F

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
