### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by sanaglobalsia** [johngodley/redirection#3088]
Plugin: 5.1.3 4.2
WordPress: 5.8.1 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
JavaScript: https://footballbetting365.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://footballbetting365.com/wp-json/

**Comment by johngodley** [comment]
Please read the onscreen instructions. This is most likely caused by another plugin.
