### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by JBCSU** [johngodley/redirection#3093]
I installed the plugin on a dev server, activated it, and went through the setup. When I go to the Redirection tab, I see **Something went wrong** 🙁 , and I am unable to create a redirect. The REST API section shows a green **Good** button. I've been through all the steps in **What do I do next?**. Plugin Status shows all green. I've cleared all my caches. I can't disable all the plugins on Stanford's homesite. The only issue in Site Health is `define( 'WP_AUTO_UPDATE_CORE', false );`, which I doubt affects this plugin.

Debugging info follows. Any help would be greatly appreciated.

```
Plugin: 5.1.3 4.2
WordPress: 5.7.2 (single)
PHP: 7.4.24
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
JavaScript: https://dev-stanford-homesite.pantheonsite.io/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://dev-stanford-homesite.pantheonsite.io/wp-json/
Query: ?page=redirection.php

Error: Failed to fetch
```

**Comment by JBCSU** [comment]
In the meantime, we've installed [Safe Redirect Manager](https://wordpress.org/plugins/safe-redirect-manager/), which does allow us to create redirects. It has fewer options, though.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
