### ISSUE TITLE
Passing the HTTP_REFERER to the redirection URL

### ISSUE THREAD

**Issue by celltrackingapps** [johngodley/redirection#3098]
Hey, I've written a plugin for [my website](https://celltrackingapps.com/) that passes on the $_SERVER['HTTP_REFERER'] as __referrer__ - this way I can track the page URL where my clicks are coming from (I have 1 redirect link spread across the whole website).

Here's an example of my URL: https://prnt.sc/1w8vlz2
Here's how it should look in practice:

1. A user goes to, let's say, https://celltrackingapps.com/spy-app-iphone/, and clicks on a redirection link
2. `__redirection__` will be replaced by `spy-app-iphone` and the end URL becomes: `https://track.mspy.click/aff_ad?campaign_id=633&aff_id=5548&aff_sub=spy-app-iphone&aff_sub2=download&source=celltrackingapps.com`
3. The partner network records `aff_sub` as `spy-app-iphone`

For some reason though, half of the clicks show up as `empty`.

I have a hunch it's either:
a) the plugin
b) the server
c) my code
d) some other plugins
e) combination of above

All my redirects are default 301s to an HTTPS URL.

Here's the code: https://pastebin.com/q2b9hGyQ

**Comment by celltrackingapps** [comment]
Hey John, the question is: why is __referrer__ empty? I'm using your Redirection plugin, so that's why I'm not sure whether it's my code or the plugin stripping something?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
