### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by SamiAibeche** [johngodley/redirection#310]
Error Message : 
Nonce: 19d5e8aae1

Action: red_get_group
Params: {"selected":[],"filterBy":"","filter":""}
Code: 500 Internal Server Error
Error: Unexpected end of JSON input
Raw: 

### Summary
I work on a multisite and it is impossible to try this plugin, a PHP error block the process.

### Actual Behavior

That happen only when I select '404s' on the admin menu.
I tried to refresh the page a lot of unfortunately
![capture d ecran 2017-08-17 a 10 27 20](https://user-images.githubusercontent.com/16844082/29402880-dc814b40-8336-11e7-8176-fea6876d1564.png)
 without success 

### Steps to reproduce

1. Plugin Installation
2. Plugin Activation
3. Simulate a 404 with a wrong URL (http://mysite.com/fakeexample/)
4. Check the 404logs
5. PHP Plugin Error showing up

### Environment

Google Chrome Browser Version 60.0.3112.90 (Build officiel) (64 bits)
Versions: Plugin 2.7.1
WordPress 4.7.3
PHP 5.6.30

**Comment by johngodley** [comment]
A 500 error generally means that something went wrong on your server. Can you look in your server's error_log and see if there is anything that looks related?

**Comment by ogierschelvis** [comment]
This also occurred to me when using the latest Redirection plugin with an outdated version of Wordpress. So first check if your Wordpress version is up to date. I thought 2.7.1. is compatible with Wordpress 4.4 and higher.

**Comment by johngodley** [comment]
Closing for now due to lack of information, please provide more details if the problem still exists
