### ISSUE TITLE
[Suggestion] Add new header templates

### ISSUE THREAD

**Issue by Xelium** [johngodley/redirection#3100]
Hi,

Is it maybe possible to add the following headers to the standard list:

- Permissions-Policy (Replacement of Feature-Policy)
- X-Powered-By (To unset it)
- Server (To unset it)

Thanks!

**Comment by johngodley** [comment]
It's not possible to unset a header that is set by your server.

Additional headers will be coming in a future version, although I cannot give a timeline for that.
