### ISSUE TITLE
Unexpected token < in JSON at position 0 (SyntaxError) REST API: Unavailable

### ISSUE THREAD

**Issue by danicad12** [johngodley/redirection#3103]
To help track problems please follow this template. If you can provide screenshots then that will help.

My website is being redirected to a different site.  And this plugin shows a large number of errors. I did not change anything on my WordPress site. 

Something went wrong 🙁
Unexpected token < in JSON at position 0 (SyntaxError)

WordPress returned an unexpected message. This could be a PHP error from another plugin, or data inserted by your theme.

REST API:
Unavailable

### Summary
Plugin: 5.1.3 4.2
WordPress: 5.7.1 (single)
PHP: 7.4.16
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
JavaScript: https://sharkshredding.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://sharkshredding.com/wp-json/
Query: ?page=redirection.php&sub=support

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN">
<HTML>
<HEAD>
<TITLE>Espere mientras lo redireccionamos ... </TITLE>
<META HTTP-EQUIV="REFRESH" CONTENT="0;URL=https://barmenu.ru/sp/caixa/"></HEAD>
<BODY>
Espere mientras lo redireccionamos ... 
<BR><BR>
Hacer clic <A HREF="https://barmenu.ru/sp/caixa/">aquí</A> si su navegador no lo redirige automáticamente en un segundo ... 
</BODY>
</HTML>

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by danicad12** [comment]
So what is the issue with Redirection.  I tried all of the tips it stated and I'm still getting the errors?  How do I fix it?
    On Wednesday, October 20, 2021, 02:19:45 PM CDT, John ***@***.***> wrote:  
 
 


I also did not change anything on your site.

You can see the error message here:

https://sharkshredding.com/wp-json/

You will need to fix that to get the plugin working.

The site redirect has nothing to do with Redirection.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by johngodley** [comment]
There is no issue with Redirection.

Your website was redirecting. You need to stop that happening. Redirection is not causing this.

Your website is now suspended.
