### ISSUE TITLE
tools.php?page=redirection.php don't load the list

### ISSUE THREAD

**Issue by arashnz** [johngodley/redirection#3107]
Hello,
### Summary

wp-admin/tools.php?page=redirection.php don't load the list, it just blinking, but don't show the list of urls
### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

I added about 10 000 urls in the past, right now i tried to access that page (wp-admin/tools.php?page=redirection.php) to check things and add few more urls, i waited for long time but it didnt't load the list.
also in the tools.php?page=redirection.php&sub=support page it blinking on "REST API:Testing - 0%" if it helps..

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

I juse chrome, Version 94.0.4606.81 (Official Build) (64-bit)
here is the screenshot :
https://pasteboard.co/YJYTIJUR0A7L.png

**Comment by johngodley** [comment]
It's a while since you posted this so I will close it, but if you are still having problems you can re-open with more details.
