### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by hanilifecapture** [johngodley/redirection#3113]
Plugin: 5.1.3 4.2
WordPress: 5.8.1 (single)
PHP: 7.3.18
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
JavaScript: https://www.hanthuong.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.hanthuong.com/wp-json/

**Comment by johngodley** [comment]
This is caused by another plugin. Use your developer's browser console to investigate further.
