### ISSUE TITLE
RegEx Redirection with 404 Errors

### ISSUE THREAD

**Issue by kisekae** [johngodley/redirection#3118]
Hi. I recently consolidated a number of redirections for individual missing pages into a consolidated redirection that would recognize missing page 404 errors and redirect to a common upper level page.  I wanted to catch 404 errors on missing or deleted products in my shop and redirect to the common `/shop/` url.

My regex was:  `^.*\/shop\/.*`  
match on URL and Wordpress page type
redirect with http code 301 to: `/shop/`

This works.  Redirections happen.  However, before I did this I previously saw entries showing in to 404 log for all sorts of URLs on my website.  There are many probes by bots.  After I implemented this 404 regex I no longer see any entries showing in the 404 log for any 404 error on any URL.  

OK.  I could live with this.

However, I recently tried to duplicate my 404 error redirection for another directory.  This second redirection doesn't work.  Nothing happens.  

My regex is:  `^.*\/product-category\/figures\/.*`
match on URL and Wordpress page type
redirect with http code 301 to: `/product-category/figures/`

I think this failure on the second redirection may be related to the missing entries in the 404 log.  I wonder if you could look into this?

Thank you.

**Comment by johngodley** [comment]
You don't need to escape the `/` - `/` is fine instead of `\/`

Your expressions should not prevent 404s being logged on the rest of your site.

I don't have enough information to know why the second one isn't working. If it matches then it will work, unless something else prevents it from doing so.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
