### ISSUE TITLE
Interesting redirection issue

### ISSUE THREAD

**Issue by mulligan87** [johngodley/redirection#3119]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Just looking to see if anyone has any idea why checking a redirect gives this message, yet the redirect works...  I might get in trouble with my company if I show the url, but I'm hoping there is still enough information for someone to help me.  The edited text simply shows that the "expected" url is the same as the "found" url.  I'm not sure if that's how the plugin is designed to work, but that's how it works every time for us when making redirects.

![image](https://user-images.githubusercontent.com/93616239/139942400-28585e2f-d677-48c7-919c-193395d81f79.png)

### Environment

Newest version of Chrome and WordPress Redirection plugin.

**Comment by johngodley** [comment]
As it shows, something else is performing the redirect.

**Comment by mulligan87** [comment]
Hi John,

Thank you for replying!  How do I find out what that something else is?  We only use WordPress for our redirects; specifically, the plugin we are talking about.  So even though it says something else is performing the redirect, nothing else should be.  At least, we are unaware of what is redirecting at the same time this plugin in.

**Comment by johngodley** [comment]
You may be able to use the 'log external redirects' https://redirection.me/support/options/

**Comment by mulligan87** [comment]
I noticed my organization has a different, albeit inactive, redirection plugin.  Could it somehow be conflicting with the current redirection plugin?

**Comment by johngodley** [comment]
If it is inactive then I doubt it.

**Comment by mulligan87** [comment]
Thanks again John; I will probably reach out to our IT department to see if they have any advice; I assume they will then direct me to either WordPress' or the Plugin's IT team(s).
