### ISSUE TITLE
CSV of Redirects Exporting Blank

### ISSUE THREAD

**Issue by daveeddy** [johngodley/redirection#312]
### Summary

I'm trying to export a CSV of all the redirects from my Wordpress install and the CSV is exporting as a blank file except for this at the top:

source,target,regex,type,code,match,hits,title
--

### Steps to reproduce

Went to Redirection plugin > Modules > Wordpress (There are 3288 redirects in there) > CSV > Download. 

The file downloaded is blank except for this at the top: source,target,regex,type,code,match,hits,title 

Explain the steps involved to reproduce the problem

### Environment

Chrome on Mac latest version, WordPress Version 4.8.1, latest version of Redirection plugin

Thanks!

**Comment by johngodley** [comment]
Have you selected the right item from the left dropdown? If you press 'view' rather than 'download', can you see the redirects?

**Comment by daveeddy** [comment]
I can't see a "View" option...? 
![screenshot-www turnbullhill com au-2017-08-23-05-13-51](https://user-images.githubusercontent.com/20780659/29582941-e30ed484-87c1-11e7-925f-73ce580425cc.png)

**Comment by johngodley** [comment]
This isn't the latest version of the plugin. Can you update to 2.7.2

**Comment by daveeddy** [comment]
Ahhhhh I see. Thanks John! :)





Watch our video <https://www.youtube.com/watch?v=7q7yEKbGWMc> 📽

Dave Eddy Director

p: +61 2 4036 1369 | m: +61 499 111 123

71/137 Hunter St, Newcastle NSW 2300

dave@vicinity.marketing w: vicinity.marketing

[image: fb.png] <https://www.facebook.com/vicinitymarketing>  [image:
in.png] <https://www.linkedin.com/in/daveeddy>  [image: instagram.png]
<https://www.instagram.com/vicinitymarketing>

Listen to The Location Station Podcast
<https://vicinity.marketing/1-introducing-location-station-local-marketing-podcast/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
🎙
   *Video directions to our office via:* Hunter Street Mall
<https://www.youtube.com/watch?v=YDUJV3akrZA&feature=youtu.be> / King Street
<https://www.youtube.com/watch?v=pV6ijaojFEQ&feature=youtu.be>
