### ISSUE TITLE
Redirect as Cache

### ISSUE THREAD

**Issue by geobehr** [johngodley/redirection#3129]
### Summary

Several hundred pages using Elementor and ACF that change infrequently, I'd like to use redirection plugin as a cache to speed page download: URL remains the same, but points to a static page I've generated for that URL. Every time I change the page I regenerate the static page and change the redirect.

Do you see any alligators in this approach? Can I use APIs or functions to change the redirect when I save the post?

Thanks!

**Comment by johngodley** [comment]
I don't really understand what you are trying to do, but my usual response to these type of questions is that Redirection can redirect one URL to another URL. If that helps you achieve your aim then that's great.

Developer information can be found here: https://redirection.me/developer/
