### ISSUE TITLE
Redirect not taking

### ISSUE THREAD

**Issue by vincentnero** [johngodley/redirection#313]
### Summary

Set Redirect and it's not redirecting - tried 2 browsers to confirm it wasn't a caching issue.

### Actual Behavior

Attempting to redirect:
http://www.successories.com/blog/2014/06/30/how-to-plan-a-baseball-outing-for-your-workplace/
to:
http://www.successories.com/blog/2014/06/18/the-top-corporate-events-for-the-work-place/
<img width="726" alt="screen shot 2017-08-18 at 12 19 25 pm" src="https://user-images.githubusercontent.com/7606125/29467857-f83aa956-840f-11e7-9903-1894727f8bca.png">

Original url still 404s

### Steps to reproduce & Environment

Wordpress: Version 4.1.1
Redirection: Version 2.6.5
WordPress SEO: Version 1.7.3.3
I can give you a temporary login to my account if you want.

**Comment by johngodley** [comment]
A temporary login would be useful yes - I can be contacted through the website on my profile

**Comment by nikolov-tmw** [comment]
@johngodley was this resolved? I'm experiencing the same issue where redirects are no longer working on a client website. I haven't had the chance to dig deeper into this. However from the surface of it - the hit to the redirect is logged and displayed, however I only get the 404 page and I'm not redirected to the Target URL. The module used is WordPress.

**Comment by johngodley** [comment]
No, it wasn't resolved. I believe it's the same problem a couple of others have reported where Redirection is sending the redirect, but something else is changing it to a 404. I suspect it may be a another plugin update, but I haven't been able to confirm this. If you can list your URL here that would help me confirm if it's the same problem.

**Comment by oplf** [comment]
Same problem here.  I am testing the redirect which is supposed to start with https://blog.oppedahl.com/test.htm and redirect to https://blog.oppedahl.com/?page_id=464 .And instead, I simply receive a 404 error.
![image](https://user-images.githubusercontent.com/12816367/30253407-99652ab6-9641-11e7-9c23-4aa49e5dbd6f.png)

**Comment by nikolov-tmw** [comment]
On this client's site, they disabled the plugin "Duplicate Page And Post" and *in theory* that solved the problem.

However, on my local install, having both that plugin and Redirection active does not break the redirects, which makes me think the mentioned plugin might not have had anything to do with the issue. So basically right now I have no way of reproducing the broken redirects in order to give you something more useful :disappointed:

**Comment by johngodley** [comment]
I'm going to close this ticket for now, but if anyone is able to reproduce it then please reopen and I would be interested to know. I suspect that another plugin is causing the redirect to continue on through to a 404.
