### ISSUE TITLE
Redirection loop brakes access to wp-admin

### ISSUE THREAD

**Issue by johnkorn** [johngodley/redirection#3130]
I wanted to redirect the old website url to a new one. But I did it the wrong way. 

First, I changed both site’s url and wordpress' url in wp-admin's Settings->General. 

Later I enabled redirection plugin, configuring it to redirect from what I thought is the old url to a new one I set in the previous step. As a result I cannot access wp-admin anymore.

When I try to access old-url/wp-admin it gets redirected to new-url/wp-admin?redirect_to=old_url%2Fwp-admin%2F&reauth=1

how can break this redirection loop and regain access to wp-admin?

Thanks.
Best,
Evgenii

**Comment by johngodley** [comment]
The support site has details of all the plugin's features:

https://redirection.me/support/disable-redirection/
