### ISSUE TITLE
Redirect 200 error

### ISSUE THREAD

**Issue by homear1234** [johngodley/redirection#3133]
Need to redirect old URL to new Wordpress page

Receiving 200 error when checking redirect

added old url and updated worldpress pages
### Environment

Safari plug in version 5.1.3

**Comment by johngodley** [comment]
Can you provide more details?

**Comment by homear1234** [comment]
Good Morning,

I submitted a redirect from our old URL (https://americaneaglebuilders.arhomes.com) to direct to our new Wordpress URL (https://www.arhomes.com/builder/american-eagle-builders-inc/) for each source URL and received this message.

***@***.***

Best,

Nicole


[AR Homes logo]<http://www.arhomes.com/>
Nicole Barnard
Marketing Specialist
AR Franchising, Inc.

O: (727) 536-5900 ext. 291

Facebook<https://www.facebook.com/ArthurRutenbergHomes>  | LinkedIn<https://www.linkedin.com/company/arthur-rutenberg-homes/>  | Twitter<https://twitter.com/arthurutenberg>



From: John ***@***.***>
Date: Friday, November 19, 2021 at 5:40 AM
To: johngodley/redirection ***@***.***>
Cc: Nicole Barnard ***@***.***>, Author ***@***.***>
Subject: Re: [johngodley/redirection] Redirect 200 error (Issue #3133)
External Sender


Can you provide more details?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_johngodley_redirection_issues_3133-23issuecomment-2D973959554&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=eusw3YvZChjD1-uJYdQMsLV9nbnx1FYTWcyZFhuj-4E&m=irPNzWZqmuwmNCwE_0OICALSF0jf_rrVi2v7MJ7eftc&s=a2DzI9h45tLuRwxzH_RSfcVXKc_eCS4eM08WepQraBs&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWR6PPZPH3LUCHOH2AITE5DUMYSTBANCNFSM5IJ3NQCQ&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=eusw3YvZChjD1-uJYdQMsLV9nbnx1FYTWcyZFhuj-4E&m=irPNzWZqmuwmNCwE_0OICALSF0jf_rrVi2v7MJ7eftc&s=VUt9GG82U-tnuYkXS0-CQodmTmqn23GoCeVILYaD8N8&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=eusw3YvZChjD1-uJYdQMsLV9nbnx1FYTWcyZFhuj-4E&m=irPNzWZqmuwmNCwE_0OICALSF0jf_rrVi2v7MJ7eftc&s=Pcf55pnefLBgtenPJUGjvrvjxgfkTYb6NWZOYYnb-bc&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=eusw3YvZChjD1-uJYdQMsLV9nbnx1FYTWcyZFhuj-4E&m=irPNzWZqmuwmNCwE_0OICALSF0jf_rrVi2v7MJ7eftc&s=SVqFmFBO10WLufpILMuleKhJ6hugiLz1mvxO8bR_piY&e=>.



________________________________

This email has been scanned for spam and viruses by Proofpoint Essentials. Click here<https://us4.proofpointessentials.com/index01.php?mod_id=11&mod_option=logitem&mail_id=1637318449-Zj43ENaQATY8&r_address=nbarnard%40arhomes.com&report=1> to report this email as spam.

**Comment by johngodley** [comment]
This seems to be redirecting now.
