### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by itsikram** [johngodley/redirection#3135]
Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.3.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
JavaScript: https://pvgt.net/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://pvgt.net/wp-json/

**Comment by johngodley** [comment]
This is caused by another plugin. Use your developer's browser console to investigate further.
