### ISSUE TITLE
Site-Aliases don't work since 5.1.3 (WP 5.8.2)

### ISSUE THREAD

**Issue by andyreutimann** [johngodley/redirection#3140]
### Summary

Redirection based on site alias doesn't work anymore.
Site (marketing-abteilung.ch) remains on alias domain (mkab.ch).

### Actual Behavior

Entering the alias domain https://mkab.ch results in a page load instead of redirect to https://marketing-abteilung.ch
Site alias has always worked but does not recently.

Tried removing alias and reentering but did not change anything.
Feature is important, because due to security settings no attachments (images etc.) will be delivered on alias domain.

### Environment

WordPress 5.8.2
Redirection 5.1.3
Browsers: Safari, Firefox + Chrome (all on latest version)

**Comment by johngodley** [comment]
Nothing has changed in the plugin recently, so what could have changed on your site?

**Comment by andyreutimann** [comment]
I always keep plugin's up-to-date when I see there are updates.
Besides this nothing changed here..

If I can help debugging this, please let me know.

**Comment by andyreutimann** [comment]
The problem occurs only when requesting the home site (site alias).

**Comment by andyreutimann** [comment]
Seems I could find the root cause with deactivating all plugins and step-by-step activating the plugins again.
Therefore Borlabs Cache (caching plugin) seems to cause it. After re-caching all sites it currently works again, but in the end I don't know if it's just in the browsers cache now or if it really works..
