### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by Spxc** [johngodley/redirection#3141]
```
Uncaught SyntaxError: Invalid or unexpected token https://digitalopptur.no/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717 2
```

Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
JavaScript: https://digitalopptur.no/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://digitalopptur.no/wp-json/

**Comment by johngodley** [comment]
The plugin isnt installed properly. If you open https://digitalopptur.no/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717 you will see some corrupted characters.

**Comment by johngodley** [comment]
cfn
