### ISSUE TITLE
Redirection error leading to 404 page

### ISSUE THREAD

**Issue by mattrosler** [johngodley/redirection#3142]
Hello,
I’ve been using your Redirection plugin and I can’t seem to get it to work.

Using a bogus site, I recently changed a link from

http://www.mysite.com/gadgets/21-gifts-for-kids

to

http://www.mysite.com/gadgets/2**3**-gifts-for-kids

![Redirection](https://user-images.githubusercontent.com/65367572/143180325-1a08991f-ac8b-4677-a4ad-429a3d4cd9fa.jpg)

When i go to http://www.mysite.com/gadgets/21-gifts-for-kids, sometimes it works and other times it leads to a 404 page instead of the redirect.

Not sure what the issue is.

Happy to share my exact site via private email.

thank you,
Matt

**Comment by johngodley** [comment]
A redirect always works the same unless affected by something external (a cache), or it isn't matched.

**Comment by johngodley** [comment]
cfn
