### ISSUE TITLE
Detecting unnecessary redirections

### ISSUE THREAD

**Issue by petapixel** [johngodley/redirection#3146]
### Summary

If we set a particular URL to redirect but in the future decide to use that URL, is there any easy way for us to detect when an old redirection has become unnecessary so that we can delete the redirection?

For example, if we have a deleted tag page /tag/example/ that we set to redirect, and then in the future we use that "example" tag and therefore need the page to NOT redirect, is there any way for us to easily see when this conflict arises?

**Comment by johngodley** [comment]
Not really, no. You will need to check yourself.

**Comment by petapixel** [comment]
Thanks for the fast response!!

Followup question: Is there any easy way to delete duplicate redirection entries in which the source URL and target URL are the same?

**Comment by johngodley** [comment]
Again, not really. There are too many variables involved for the plugin to realistically determine what is a good redirect or not, and so it leaves it entirely up to you.
