### ISSUE TITLE
Problem with linked widgets on different devices

### ISSUE THREAD

**Issue by SASINTERIORISMO** [johngodley/redirection#3147]
Hi, I am having problems with the mobile version of my site. I used the redirections plugin for each product category. The idea was to redirect to page templates made with Elementor. It works perfectly on desktop, but doesn´t work on mobile. ( I haven´t prove with tablets).

The site I am reffering is: https://sasinteriorismo.wpcomstaging.com/

1. Buttons: These buttons on the home page are supposed to redirect to the product category template. For some reason, on mobile devices, it redirects to the home page. - https://snipboard.io/RkEd1u.jpg

2. Category Widget: This category widget on the shop page should also redirect to each template. Also, works perfect on desktop, but fails to redirect correctly on mobile devices, and redirects to the homepage too. - https://snipboard.io/geGiWZ.jpg

Please help!!

**Comment by johngodley** [comment]
The plugin works the same on any device. You may need to clear your browser cache.

It works on URLs, not widgets or buttons.

**Comment by SASINTERIORISMO** [comment]
Hi, I created this video before clearing the chache, so I could explain the problem more specifically. Now, after clearing the cache, I see that the redirections are not working on desktop devices either.

Please help!!!

Video: https://streamable.com/deuf0u

**Comment by SASINTERIORISMO** [comment]
Hi, when I desactivate the redirection plugin, the links are still redirected ( correctly on desktop and incorrectly on mobile devices)

Please help!!

**Comment by johngodley** [comment]
If the plugin is not activated then Redirection is not performing the redirect - something else is.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
