### ISSUE TITLE
Get all redirects via REST API without being logged in

### ISSUE THREAD

**Issue by thelucre** [johngodley/redirection#3149]
### Summary

I'd like to get all Redirects (`GET /wp-json/redirection/v1/redirect`) publicly without user auth for headless WP implementations during static generation deploys.

I see that [permissions can be customized](https://redirection.me/developer/permissions/) but these all assume a User-level role. Is it possible to open a single endpoint to the public for GET requests only?

### Actual Behavior

The REST route returns a 401 error when requested directly from a browser. 

Side note: returning `true` from [this function](https://github.com/johngodley/redirection/blob/master/api/api-redirect.php#L229-L231) allows the endpoint to be called without a User role.

### Steps to reproduce

1. Install the plugin
2. Visit `https://yoursite.com/wp-json/redirection/v1/redirect`
3. See the 401 error 

### Environment

- Wordpress 5.8.2
- Redirection 5.1.3

**Comment by johngodley** [comment]
Possibly, but this is something you'll need to hook into the REST API using WordPress filters to do.

**Comment by thelucre** [comment]
Thanks for your quick response! Is there a specific filter to allow this functionality?

**Comment by johngodley** [comment]
Possibly, but it's not part of Redirection. You can find more information about the WordPress REST API here:

https://developer.wordpress.org/rest-api/

**Comment by thelucre** [comment]
Just to close the loop here, I ended up making my out REST endpoint and grabbing the Redirection data manually using this class method:

```php
// If Redirection is active and the class method exists
if(class_exists('Red_Item') && method_exists(Red_Item::class, 'get_filtered')) {
        
  // Force filter only for enabled Redirects 
  $request->set_param('filterBy', array('status' => 'enabled'));
        
  // Run Redirection plugin query
  return Red_Item::get_filtered( $request->get_params() );
}
```
