### ISSUE TITLE
Unable to access Redirects from wp-admin tools

### ISSUE THREAD

**Issue by arbo629** [johngodley/redirection#315]
### Summary

I am trying to access the redirects to add more. 

### Actual Behavior

When I click on Tools > Redirection, I get this (I've cleared my cache, and this same issue is happening on multiple sites too, all with different hosts and different caching):

Something went wrong 🙁
Redirection is not working. Try clearing your browser cache and reloading this page.
If that doesn't help, open your browser's error console and create a new issue with the details.
Please mention redirect, and explain what you were doing at the time.

### Steps to reproduce

Select Tools > Redirection

### Environment

IE11 (hangs head in shame) and Chrome, WordPress 4.8.1, Redirection 2.7.1

**Comment by johngodley** [comment]
Do you have any errors in your browser's error console?

**Comment by arbo629** [comment]
Hi John.  I did an Inspect and viewed the console and this is the message:

SCRIPTS: Access is denied.
File: notifications, Line: 1, Column: 1

I'm having the same trouble on many sites but I just Inspected a couple to
see if the errors were the same and they are.  The urls that I checked are
https://mylongislandcarservice.com
http://thebostonhometeam.com

All sites affected are current with WP core and plugins.  They are all
using the Divi theme.  Some have the most current version of Divi, some do
not. The only common plugin with all of them is Yoast but I've disabled
that to see if it solved the problem, but it did not. There is no common
thread with hosting.  On all sites, I didn't start noticing a problem until
August 11th, though there was no specific action that day that i can
pinpoint as a trigger.  All clients have their own, unique hosting and
there's nothing that I do in bulk or from a central dash of any kind.

Alicia

**Comment by johngodley** [comment]
Can you try adding this to `wp-config.php`:

`define( 'REDIRECTION_FLYING_SOLO', true );`

**Comment by arbo629** [comment]
Hi John. I'm looking at a wp-config file that is in the public-html folder.
It's got 98 lines of code. Just copy and paste the line you sent me
anywhere or does it need to go somewhere specific?

**Comment by johngodley** [comment]
You'll see a lot of other `define('something')` lines - put it somewhere with those, the exact location isn't important as long as it's not the first or last line

**Comment by arbo629** [comment]
Hi John, I put it in line 43-44 but I still get the same error message,
even after clearing and disabling the caching plugin. Screen shots
attached.

**Comment by arbo629** [comment]
Oops, I think it might actually be a little worse after adding that line to
the wp-config file.  Before, I only got the error message if I went to
Tools>Redirects, but I could still go to the plugin screen and select
settings there to access my groups and add a new redirect, if needed.  Now,
the Plugins>Settings route is throwing an error also so I cannot access the
redirects at all.

**Comment by johngodley** [comment]
I'm very surprised if things got worse. You didn't include a screenshot, but if it's the same error then that's ok. At this point the easiest way to debug further is if I had access to the site. If you are ok with that then you can contact me through the contact form on my website found by clicking on my avatar.

**Comment by arbo629** [comment]
Hi John. There wasn't an avatar here but I went a round about way thru the
plugin details and found your blog. I sent the creds for a couple of sites
to you via that contact form. Thank you!

**Comment by johngodley** [comment]
This was an IE problem, which has now been fixed in 2.7.3. Thanks for access

**Comment by arbo629** [comment]
Hi John. I worked on a couple sites today and it appears to be working
perfectly again. Thank you!
