### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by vomo2021** [johngodley/redirection#3152]
I tried to switch my wordpress site from subdomain matchbirdnew.matchbird.com to main domain matchbird.com on the same server. I changed the websites address in the wp-admin-settings and the admin site was not reachable anymore. So I tried to change the wp-config file and wrote the lines:
define( 'WP_SITEURL', 'https://matchbirdnew.matchbird.com' );
define( 'WP_HOME', 'https://matchbirdnew.matchbird.com' );
to make it reachable again. Now I can reach the admin panel via my hoster's admin site but can't login via my subdomain. Now, the SITEURL and the HOME URL in the settings are grey and not editable. The Redirection-Plugin shows following error:
```
Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.4.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
JavaScript: https://matchbirdnew.matchbird.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://matchbirdnew.matchbird.com/wp-json/
Query: ?page=redirection.php&sub=options

Error: Failed to fetch
```

**Comment by johngodley** [comment]
It doesn't sound like this is caused by Redirection, and you need to fix your website.

**Comment by vomo2021** [comment]
But what did I wrong?

**Comment by johngodley** [comment]
Your site URL isn't set up correctly.

This Github is for Redirection questions. If you have need WordPress support you can find it on the wordpress.org support forum.

**Comment by vomo2021** [comment]
But I can't change the fields in the wp-admin settings. the word-press URL and the website URL fields are grayed.

**Comment by johngodley** [comment]
Ok, then that's something you can bring up on the wordpress.org support forum.

**Comment by vomo2021** [comment]
thanks
