### ISSUE TITLE
Redirects loading to blank page

### ISSUE THREAD

**Issue by pawlmichael** [johngodley/redirection#3158]
I have several redirects set up on a website with subdomains. For several years things were finr. They have all stopped working across all subdomains and will only load to a blank page. Examples...

https://independence.lifeconnectionkc.org/hello
https://independence.lifeconnectionkc.org/groups
https://lifeconnectionkc.org/cars

Thank you for your help as I am currently stuck. All plugins and Wordpress are up to date. 

Paul Jeffries

**Comment by johngodley** [comment]
Ok, what changed to cause them to stop working?

**Comment by yeshourunr** [comment]
They're not loading blank for me. Assuming you want https://independence.lifeconnectionkc.org/hello to redirect to https://mailchi.mp/lifeconnectionkc/welcome, and so on, everything seems to be working.

What I see: [https://send.yeshou.run/upload/files/1638835484-6c89a17fc6f2ccab97905f08673de59da46115a7-Screen-Recording-2021-12-06.mp4](https://send.yeshou.run/upload/files/1638835484-6c89a17fc6f2ccab97905f08673de59da46115a7-Screen-Recording-2021-12-06.mp4)

**Comment by johngodley** [comment]
It seems to be redirecting ok now.
