### ISSUE TITLE
Redirect to random post not working

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#316]
Redirecting to a random post is broken

**Comment by SYOBco** [comment]
Kindly let us know if you need history of the logs.

**Comment by Solboch** [comment]
boa tarde, alguem pode otimizar meu site? por favor?
http://brindesevidencia.com.br/site/ 
nao sei fazer

**Comment by SYOBco** [comment]
@johngodley By when do you think this will be fixed?

**Comment by johngodley** [comment]
Fixed in #422
