### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by smurfz90** [johngodley/redirection#3163]
Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.4.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
JavaScript: https://wanduslab.karunahost.asia/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://wanduslab.karunahost.asia/wp-json/

**Comment by johngodley** [comment]
Your plugin is not installed properly: https://wanduslab.karunahost.asia/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
