### ISSUE TITLE
PHP Fatal error:  Uncaught ValueError: version_compare()

### ISSUE THREAD

**Issue by gino0631** [johngodley/redirection#3165]
### Summary

Database upgrade crashes with the following PHP error on PHP 8.1:
`PHP Fatal error:  Uncaught ValueError: version_compare(): Argument #3 ($operator) must be a valid comparison operator in /var/www/html/wp-content/plugins/redirection/database/database.php:31`

### Steps to reproduce

After installing a new version of the Redirection and enabling it, click on "Upgrade Database".

The cause of the problem is 'g' operator used in `version_compare()`, which is not among the possible ones:
https://www.php.net/manual/en/function.version-compare.php

### Environment

Redirection: 5.1.3
WordPress: 5.8.2
PHP: 8.1.0

**Comment by johngodley** [comment]
The plugin is not compatible with PHP 8.1. It is compatible with 8.0

**Comment by gino0631** [comment]
Thanks for the prompt response. In this case, maybe it is possible to state that more explicitly (now it says "PHP Version: 5.6 or higher"), or make it compatible?

**Comment by johngodley** [comment]
It will be made compatible in the future. Right now it does state 'including 8.0'. WordPress does not allow a great deal of options when specifying versions.

**Comment by gino0631** [comment]
Thank you, I'll be waiting for the news.

**Comment by johngodley** [comment]
Fixed in 5.2: https://github.com/johngodley/redirection/releases/tag/5.2-beta
