### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by gis1** [johngodley/redirection#3174]
```
SyntaxError: illegal character https://test.pooltime.se/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717 2
```

Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 7.4.27
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:62.0) Gecko/20100101 Firefox/62.0
JavaScript: https://test.pooltime.se/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://test.pooltime.se/wp-json/

**Comment by johngodley** [comment]
The URL https://test.pooltime.se/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717 does not exist
