### ISSUE TITLE
Error when trying to delete or disable a redirection

### ISSUE THREAD

**Issue by javierBairesDev** [johngodley/redirection#3178]
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 7.4.18
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
JavaScript: https://www.bairesdev.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://www.bairesdev.com/wp-json/
Query: ?page=redirection.php

Action: https://www.bairesdev.com/wp-json/redirection/v1/bulk/redirect/delete/?orderby=id POST
Params: {"items":[9014111222753600]}
Code: 400 Bad Request

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}

**Comment by johngodley** [comment]
Your site is aggressively cached. Please clear your cache and ensure that /wp-json/ is excluded.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.

**Comment by javierBairesDev** [comment]
I've created a bypass for /wp-json/ in all our cache services, and purged them. The issue persits returning a "status":400

```
Plugin: 5.1.1 4.2
WordPress: 5.7.2 (single)
PHP: 7.4.18
Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
JavaScript: https://www.bairesdev.com/wp-content/plugins/redirection/redirection.js?ver=5.1.1-accf9923c797504c858f60338da73667
REST API: https://www.bairesdev.com/wp-json/
Query: ?page=redirection.php&filterby%5Burl%5D=duplicate

Action: https://www.bairesdev.com/wp-json/redirection/v1/bulk/redirect/delete/?orderby=id&filterBy%5Burl%5D=duplicate POST
Params: {"items":[9014111222753600]}
Code: 400 Bad Request

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":343}}
```

Thanks for your help
