### ISSUE TITLE
One of the redirects not working

### ISSUE THREAD

**Issue by monisien** [johngodley/redirection#3184]
Hi. Why is one of the words I type in the Source URL field not working?
Source URL: /cele
It shows 
Expected: 301 to https://www.subscribepage.com/webinarcele2022
Found: 404
Agent: Not using Redirection

When I use other words like:
/cel
/cele2

with the same parameters:
Query Parameters: Ignore all
Target URL: https://www.subscribepage.com/webinarcele2022
Group: Redirections

they work: cel and cele2 works.
Only the one cele is not working. What is the problem?

Firefox newest, Windows 10, newest WP, Redirections plugin. 
![obraz](https://user-images.githubusercontent.com/74245584/147781608-be7920f9-53e5-427e-a81d-b59aeb0f8a2d.png)

**Comment by johngodley** [comment]
What is the full URL of that page?

**Comment by monisien** [comment]
www.monikapredka.pl/cele < not working
www.monikapredka.pl/cel < working
www.monikapredka.pl/cele2022 < wotking

Why is that?


Pozdrawiam
Monika Prędka


czw., 30 gru 2021 o 20:57 John ***@***.***> napisał(a):

**Comment by johngodley** [comment]
It works fine:

https://redirect.li/http/?url=http%3A%2F%2Fwww.monikapredka.pl%2Fcele

**Comment by monisien** [comment]
Yes, it worked, because I used a different plugin than yours: 301 Redirects.
Now I deleted it.
And added this redirection back to your plugin 2 minutes ago. Please
recheck if it works now.

Do you know what might be the reason that it didn't work before?? So I can
avoid this mistake in the future?

And also please have a look at the attachment - where do all those 404 come
from since I set up as "ignore all parameters"?

Pozdrawiam
Monika Prędka


pt., 31 gru 2021 o 11:53 John ***@***.***> napisał(a):

**Comment by johngodley** [comment]
It still works.

https://redirect.li/http/?url=https%3A%2F%2Fmonikapredka.pl%2Fcele

Attachments don't work with Github. You will need to upload it directly.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
