### ISSUE TITLE
Redirection Error (Failed to fetch)

### ISSUE THREAD

**Issue by rh-mup** [johngodley/redirection#3185]
Hello there,

after troubleshooting I've found the culprit: "**qtranslate-x**"
While qtranslate-x is active I get always following error:
"**Failed to fetch - 
Your REST API is showing a deprecated PHP error. Please fix this error.**"

Knowing well that qtranslate-x is well over EOL I'll rebuild the site as soon as possible.
Is there a known workaroud to at least win some time?
In another thread I've seen a recommendation to reduce the database version to 2.4 - might this help in my case?

```
Plugin: 5.1.3 4.2
WordPress: 5.8.2 (single)
PHP: 8.0.13
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
JavaScript: https://www.vila-kristina.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.vila-kristina.com/wp-json/
Query: ?page=redirection.php

Error: Failed to fetch
```
PS: I've tested several PHP versions. I still use 7.4 in production...

**Comment by johngodley** [comment]
I don't use that plugin so can't comment about a workaround. You may find picking another REST API helps.

> I've seen a recommendation to reduce the database version to 2.4 - might this help in my case?

No, that was for an unrelated problem.

**Comment by rh-mup** [comment]
Hi johngodley,

thank you for the advise! But all three APIs show the same error.

The website is now somehow working with manuall redirects and we decided to start immediatelly with the new site, without the translation plugin...
