### ISSUE TITLE
Redirection sur la mise en cache du html statique

### ISSUE THREAD

**Issue by 19Jasonzhong89** [johngodley/redirection#3189]
Hi Author, I am using this redirect plugin and have a problem that I have not been able to solve.

My site is now using the wp-rocket plugin as a cache and he will automatically generate static URLs and as soon as I need to do a redirect to a static HTML file, the redirect is lost. I also know what the reason is. I think it's because Nginx's rules come first and find the static URL directly and return it, so the redirect doesn't work.

Because my needs are specific, I need to determine, based on my API, whether or not to do a redirect before I redirect, and if I write the redirect to Nginx, my API will fail and I won't be able to determine whether or not I need to do a redirect.

Can I remove the Nginx rule and write that rule to wp-config and then write my API request before the redirect rule? And, if the Nginx rule is removed, will the redirect plugin go to the HTML file that has already been statically processed?
I want to go back to the statically processed HTML file after the API request

Thank you, this question has been bugging me for a long time. Have been unable to find a way to handle it.

**Comment by johngodley** [comment]
I don't fully understand what you've put so I can't answer most of the questions.

Usually when a cache or your server is interrupting Redirection the solution is to export the rules from the plugin to the server:

https://redirection.me/support/problems/url-not-redirecting/

**Comment by 19Jasonzhong89** [comment]
If I need to use custom filter in config.php, how should I use it?
I would like to add judgment code to config.php to control whether the
redirect is executed or not.

John ***@***.***> 于2022年1月7日周五 01:05写道：

**Comment by johngodley** [comment]
That's a question best suited for WordPress itself. This may help: https://developer.wordpress.org/plugins/hooks/filters/

**Comment by 19Jasonzhong89** [comment]
Dear John

I read the advice you gave me, but my code base is very poor and I didn't
understand much.

I now need to decide the redirection in config.php, based on the parameter
see_FP.

if(see_FP)
define( Matched Target );
}else{
define( Unmatched Target );
}

Can you take a few minutes to guide me? Or give me a copy of the code that
solves the problem. I'd appreciate it, have a great day!

Sincerely
Melody

John ***@***.***> 于2022年1月7日周五 16:06写道：

**Comment by 19Jasonzhong89** [comment]
Dear John

To follow up on the last question, it would be best if he could define
Groups, the group I specified to execute this plan

Sincerely
Melody

city panda ***@***.***> 于2022年1月7日周五 18:21写道：

**Comment by johngodley** [comment]
Sorry, this is beyond the kind of support I can provide. All the developer information for the plugin is here:

https://redirection.me/developer/

If you have something specific to ask about Redirection then I can help with that, but general WordPress questions can be directed to the WordPress forums.

I still don't understand your problem but I think you are maybe overthinking it. The plugin does not need special code to work with caching plugins, and what you are trying to do does not seem necessary.

**Comment by 19Jasonzhong89** [comment]
Dear John

I need the See_FP parameter to decide if I need to specify a URL for
redirection, because I want to redirect to different users and See_FP can
identify the user, so it is important.

So does the redirection plugin support my needs please?

Sincerely
Melody

John ***@***.***> 于2022年1月7日周五 18:30写道：

**Comment by johngodley** [comment]
I don't know. As I've said, I don't understand the problem. I don't know what See_FP means. All the developer information is here:

https://redirection.me/developer/

It is up to you to determine if it provides what you need, not for me to tell you.

**Comment by 19Jasonzhong89** [comment]
Hi John

I want to use this redirection, but I don't know how to use it in the theme
file Function.php, I wrote the relevant code but it doesn't work, I think
there is something wrong with my code, can you give me an example of a call
that can Custom redirection

[image: image.png]
[image: image.png]

John ***@***.***> 于2022年1月7日周五 18:44写道：
