### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by vineetag** [johngodley/redirection#3194]
Plugin: 5.1.3 4.2
WordPress: 5.8.3 (single)
PHP: 7.4.3
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0
JavaScript: https://www.heartyyfresh.com/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://www.heartyyfresh.com/?rest_route=/

**Comment by johngodley** [comment]
Please read the message on the page. This is probably caused by another plugin.
