### ISSUE TITLE
Trying to sort logs by HTTP Code produces error.

### ISSUE THREAD

**Issue by joris2110** [johngodley/redirection#3197]
### Summary

I am trying to sort the logs by HTTP code

I have tried this with redirection 5.1.2 and 5.1.3 Error is the same

### Actual Behavior

Error loading results and error listed under "Environment"

### Steps to reproduce

Go to redirection tool. Press the log button. And click the HTTP Code filter

### Environment

`Plugin: 5.1.2 4.2
WordPress: 5.8.3 (single)
PHP: 7.4.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
JavaScript: http://mysite.net/wp-content/plugins/redirection/redirection.js?ver=5.1.2-f552e95c1d86a233313e7d65e8888ef5
REST API: http://mysite.net/wp-json/
Query: ?page=redirection.php&sub=log&orderby=code

Action: http://mysite.net/wp-json/redirection/v1/log/?orderby=code GET
Code: 400 Bad Request

Error: Ongeldige parameter(s): orderby (rest_invalid_param)
Raw: {"code":"rest_invalid_param","message":"Ongeldige parameter(s): orderby","data":{"status":400,"params":{"orderby":"orderby is niet een van url, ip, total, count en ."},"details":{"orderby":{"code":"rest_not_in_enum","message":"orderby is niet een van url, ip, total, count en .","data":null}}}}`

**Comment by johngodley** [comment]
Yes, this is not something you should be able to do. It has been removed in the 5.2 beta:

https://github.com/johngodley/redirection/releases/tag/5.2-beta
