### ISSUE TITLE
Redirection export gives the * in all target url's. How can I get a proper export?

### ISSUE THREAD

**Issue by totoweb** [johngodley/redirection#3198]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
It is not possible to export whatever the redirect is to CSV. You will need to pick another export format

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
