### ISSUE TITLE
302 Redirects changing back to 301's when importing .CSV file

### ISSUE THREAD

**Issue by Codesesh** [johngodley/redirection#3199]
### Summary

When exporting a .CSV file of redirects from the plugin - making edits to the .csv in google sheets - changing the "code" column from a 301 to a 302, upon successful import of .csv file the items that were changed to a 302 in the .csv are now showing as a 301.

Can you please advise if something extra is needed when importing a .csv and using a code other than 301?

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Browser: Version 94.0.4606.61 (Official Build) (x86_64) - Mac osx
Wordpress: 5.8.3
Redirection plugin version: Version 5.1.3

**Comment by johngodley** [comment]
This will be fixed in the next release.
