### ISSUE TITLE
Is "time to keep logs for" ignored?

### ISSUE THREAD

**Issue by bobcanthelpyou** [johngodley/redirection#32]
"Redirect Logs" & "404 Logs" are set to "A week" but the logs are available since May

**Comment by lembitk** [comment]
I'm observing the following with a Multisite install (WP v4.4.2, Redirection v2.4.3, WP Cron is not disabled).

- For the main/root site (ID 1), the setting to keep logs for is set to "A day" for both "Redirect Logs" and "404 Logs". 
    - Both redirect and 404 logs are available for last 32 days (since 17 January 2016) – an outcome that would be expected with the "A month" setting..?
- For all other sub-sites, "Redirect Logs" and "404 Logs" are both set to "A week". 
    - Logs are available for last 7 days, as expected.

**Comment by lembitk** [comment]
Re: log-keeping inconsistencies (on a Multisite install). 

Status update on the same site which now runs WP v4.7.3 and Redirection v2.5. 

- For the main/root site, the setting to keep logs for is still set to "A day" for both "Redirect Logs" and "404 Logs". 
  - Both redirect and 404 logs are available for last 48 hours – an almost expected outcome :)

As this tiny +1 day difference doesn't matter (and might well be related to our server specifics (?)), and for all other sub-sites logs continue to behave as expected, I say there are no issues with Redirection's log-keeping for me anymore.

P.S. Thanks again for such a useful plugin.

**Comment by johngodley** [comment]
I know this ticket has been open a few years, but based on Lembit's response and lack of other information I'm going to close it as fixed
