### ISSUE TITLE
Redirect with language in URL

### ISSUE THREAD

**Issue by cgidds** [johngodley/redirection#320]
The default language for our site is English, and we use qTranslate to manage the different languages available. If we're in English, the "/en/" of the URL is suppressed so instead of /en/url-of-page/, you'll see /url-of-page/. If I'm in another language though, the redirect returns a 404.

For example, I want a redirect as follows:
/conference/london --> /conference/london18 ...OR even
/conference/london --> /en/conference/london18 (returns a 404 when in another language)

In French, this would look like:
/fr/conference/london --> /conference/london18

However, I don't want to create a redirect for every language we support. Is this a bug or is there a way to accomplish this with the current version?

**Comment by johngodley** [comment]
Redirection works on URLs, so you would need to create a redirect for each language, or create a regular expression that captures all URLs.

**Comment by cgidds** [comment]
Ok, so strip out the language portion and redirect based on the rest of the URL?

**Comment by johngodley** [comment]
Something like:

Source: ^/\w{2}/(.*)
Target: /$1

Would probably do the trick. I haven't tested this

**Comment by cgidds** [comment]
Great, thanks John. Closing the issue now.
