### ISSUE TITLE
Redirection Plugin

### ISSUE THREAD

**Issue by JohnstonLowry** [johngodley/redirection#3202]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Yesterday I bought Redirection Plugin having made a contribution. Now I find it does not work with an external host. This was not explicit and as such, I am disappointed and would like my contribution refunded, please. Thank you in anticipation, Johnston

**Comment by johngodley** [comment]
You made a donation, you didn't buy it - it's not a product, and this is made very clear. I don't know what you mean by not working with an external host. Everything the plugin does is listed in the plugin and on the plugin website. It does not list things it doesn't do. If you are trying to redirect a domain you don't own then that is impossible, and nothing will be able to help you.

Github is not the best place to ask for a refund of a donation. I have refunded the donation. Just to be clear, this ends up costing me money.

**Comment by JohnstonLowry** [comment]
Thanks. I will respond fully later. Perhaps too remove about being a nice guy and making a donation. I was and the product didn’t work. So no more Mr Nice Guy. Sorry
J
