### ISSUE TITLE
Redirection issues with Category or Tag URLs ending with Character "s"

### ISSUE THREAD

**Issue by UltraBurstXD** [johngodley/redirection#3203]
### Summary
Hi,

I've been using Redirection plugin in my my site for some quite time, it helps so much! However, there seems to be issues when redirecting Category or Tag URLs ending with "_s_" word. When that happens, Redirection is unable to redirect properly - which results on 404 Not Found HTTP Code!

![Screenshot from 2022-01-16 13-59-49](https://user-images.githubusercontent.com/55871338/149659068-6fba866c-3455-4b84-bb3b-cce1b27c1d00.png)
![Screenshot from 2022-01-16 13-58-46](https://user-images.githubusercontent.com/55871338/149659034-e303b2e8-c71b-493c-9aed-e161d6520b60.png)
![Screenshot from 2022-01-16 13-53-46](https://user-images.githubusercontent.com/55871338/149658863-f21a24a4-8f59-479f-a8e9-b522daaace15.png)
![Screenshot from 2022-01-16 13-54-01](https://user-images.githubusercontent.com/55871338/149658867-b86cfc5a-3c7a-42b2-aa44-95a442c530cd.png)

### Actual Behavior
Redirection is unable to redirect any Category or Tag URL ending with character "_s_".

### Steps to reproduce
1. Change a Category or Tag URL and Slug ending with "_s_" character. Or Create new one of any of both type.
2. Create Manual Redirection (Since there isn't support yet to detect URL changes in WordPress Categories or Tag for case that URL was modified) for the WordPress Category or Tag.
3. Test the URL Redirection.

### Environment
Mozilla Firefox 96.0.1 (64-bit)
WordPress 5.8.3
Redirection 5.2

**Comment by johngodley** [comment]
You say it can't redirect a category ending in an s, but then show something that doesn't end in an s.

The plugin doesn't care what the URL is, or whether it ends in an s, and I am unable to reproduce any issue with it there.

Based on your screenshots your redirect is for `/category/bollywood` and you are testing `/category/bollywood/` - note the slash at the end. These won't match unless you enable the 'ignore trailing slash' option.

**Comment by UltraBurstXD** [comment]
Indeed, the trailing slash was the root of everything. Thanks!
