### ISSUE TITLE
Possible bug when Rule is active it affects all the URL from the website not only 404

### ISSUE THREAD

**Issue by blastwavehosting** [johngodley/redirection#3205]
### Summary

Hello, i think i found a bug, the plugin is redirecting even if the URL is not actualy a 404 page not found.

### Actual Behavior

Test URL Deleted product 
This is a product that was deleted and it appears in 404 tab as it shoud. 
https://etoc.ro/produse/pc-periferice-software/software/sisteme-de-operare/sisteme-de-operare-licenta-oem-microsoft-windows-11-pro-64-bit-english-fqc-10528/

### Steps to reproduce

I applied the Rule to this 404 url:
Ignore Case and Regex are On
Source URL: ^/produse(/(?:[^\n/]+?/)+?)(?:[^\n/]+?(?:/|$))(?:\?[^\n/]+?(?:/|$))?(?:feed)?/?$
Match: URL only
When matched: Redirect to URL -> 301
Target URL: /categorie$1

If the Rule is active the final URL will be:
https://etoc.ro/categorie/pc-periferice-software/software/sisteme-de-operare/

So far so good, the Rule and Plugin are operating as it shoud.

Now comes the problem:
Test URL with a product that is NOT deleted so will NOT return a 404:
https://etoc.ro/produse/pc-periferice-software/software/office-aplicatii-desktop/licenta-electronica-microsoft-office-365-personal-all-languages-subscriptie-1-an-1-utilizator/

The problem is that the Rule is affecting this URL as well and return:
https://etoc.ro/categorie/pc-periferice-software/software/office-aplicatii-desktop/

The plugin shoud only apply the Rule given if a 404 exist and then make the redirect.

Do i made a mistake in my configuration, is this a bug or this is normal and i should find another way to obtain this redirect? 

### Environment

Browser:
Chrome 97.0.4692.71 on Windows 10
Safari on iOS 15
Firefox 95.0.2 on Windows 10

Wordpress 5.8.3

WooCommerce 6.1.0

Redirection 5.2.1

PHP 7.4

Apache 2.4.52

Please list your browser, browser version, version of WordPress and Redirection plugin

![redirect](https://user-images.githubusercontent.com/76013770/149666807-54fc3e2a-24f0-4f39-a098-624ae70acc97.png)
.

**Comment by johngodley** [comment]
> The plugin shoud only apply the Rule given if a 404 exist and then make the redirect.

Why should it do that?

**Comment by blastwavehosting** [comment]
That's what I thought, my mistake then. Is there a way to achive what i was saying above using this plugin or shoud i start looking for other ways? Thank you.

**Comment by johngodley** [comment]
I'm not really sure what you are trying to do. The available URL matches can be found here:

https://redirection.me/support/matching-redirects/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
