### ISSUE TITLE
Redirection checker says "It's not working" but actually it is

### ISSUE THREAD

**Issue by alessandrofrancesconi** [johngodley/redirection#3207]
### Summary

Just wanted to check one of my 307 redirects **(handled via Apache module, not Wordpress)**. I confirm it is working, but Redirect checker says _"It's not working and it's likely not the fault of Redirection."_:

![image](https://user-images.githubusercontent.com/1595223/149739722-a374c1f2-20eb-4075-8696-354826aeff25.png)

I've already deleted all the browser's cache.

### Steps to reproduce

Create a 307 redirect handled by Apache module and ensure it is working, then use "Check Redirect" function

### Environment

Wordpress 5.8.3
Redirect 5.2.1

**Comment by johngodley** [comment]
The conclusion maybe needs a bit of rewording. All it is saying is that Redirection is not performing the redirect - something else is.

**Comment by alessandrofrancesconi** [comment]
I confirm the redirection is made via htaccess, sorry if not written before

**Comment by johngodley** [comment]
Ok. I just need to clarify the text message so it doesn't cause alarm, but otherwise everything is working.

**Comment by johngodley** [comment]
This will be improved in 5.2.2.
