### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by tiffanyweb1901** [johngodley/redirection#3215]
I am getting a 404 error at https://redrocksstickers.com/wp-json/
This link seems to work: http://www.redrocksstickers.com/index.php?rest_route=/
But I don't know how to change my Rest API url or what I should do. I tried disabling Defender Pro and I put Cloudflare in Development mode and it still doesn't work. Thanks for your help!

```
Plugin: 5.2.2 4.2
WordPress: 5.8.3 (single)
PHP: 7.4.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
JavaScript: https://redrocksstickers.com/wp-content/plugins/redirection/redirection.js?ver=5.2.2-e97dc2feda27f080b79bb711d176f7aa
REST API: https://redrocksstickers.com/wp-json/
Query: ?page=redirection.php

Error: Unexpected token F in JSON at position 0 (SyntaxError)
Raw: File not found.
```

**Comment by johngodley** [comment]
I don't know why it's returning that error. You probably should speak to your hosting provider about it - it's not part of Redirection.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
