### ISSUE TITLE
Redirection url

### ISSUE THREAD

**Issue by ajohnhoja** [johngodley/redirection#3216]
I want to change the path of urls with the Wordpress redirection tool, e.g.:
/product-category/computers
/product-category/notepads
/product-category/screens
must become
/allproducts/product-category/computers
/allproducts/product-category/notepads
/allproducts/product-category/screens

It does not work if I change it to:
Source URL:
/product-category/(.*)$
Target URL:
/allproducts/product-category/(.*)$
What code will work for this?

**Comment by johngodley** [comment]
You can find details about regular expressions here:

https://redirection.me/support/redirect-regular-expressions/

Your target is not correct.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
