### ISSUE TITLE
passthrough redirect to a pdf file

### ISSUE THREAD

**Issue by etech0** [johngodley/redirection#3221]
### Summary

I am trying to set up a pass-through redirect to a pdf file which is stored in Media. That way I can upload a new version and update my redirect, and the url will stay the same.

### Actual Behavior

When the redirect is set to Pass-through, I get a Page Not Found error. When the same redirect is set to Redirect to URL, it works fine (but the url isn't masked, which is what we want here.)

### Steps to reproduce

Upload a pdf file to Media. Set up a redirect with the target url as the url to the pdf (eg: `/wp-content/uploads/myfile.pdf`). Set the redirect to Pass-through. Save it and try to visit the url. You will get a page not found error. Then change the redirect to Redirect to URL, save, and try it again. You will be redirected to the pdf file.

### Environment

Chrome 97, Redirection 5.0.1, WordPress 5.8.3

Thank you!

**Comment by johngodley** [comment]
As mentioned in the support guide, the pass through is only for WordPress pages, not PDF files.

https://redirection.me/support/redirect-actions/

**Comment by etech0** [comment]
Got it. Thanks for answering!
