### ISSUE TITLE
Redirect - Something Went Wrong - Error in IE

### ISSUE THREAD

**Issue by dnicinski** [johngodley/redirection#323]
We can not access Tools > Redirection from any IE browser. 

We are getting an error...

Something went wrong 🙁
Redirection is not working. Try clearing your browser cache and reloading this page.
If that doesn't help, open your browser's error console and create a new issue with the details.
Please mention redirect, and explain what you were doing at the time

Chrome, Safari and Firefox still work fine. 

Do you have a fix for this? 

![screen shot 2017-08-22 at 10 19 54 am](https://user-images.githubusercontent.com/13800933/29570618-fd172acc-8724-11e7-800b-5b2cc373c8ea.png)

**Comment by johngodley** [comment]
What version of IE? Can you look in the browser error console and see if any errors are showing?

**Comment by dnicinski** [comment]
No errors. Just warnings. 

This screenshot is from IE11 for the console...

![screen shot 2017-08-22 at 11 07 41 am](https://user-images.githubusercontent.com/13800933/29572406-3c6d45c6-872a-11e7-8237-b9f68cd1ee16.png)

**Comment by dnicinski** [comment]
Any luck with this?

**Comment by johngodley** [comment]
You'll need to use another browser for now

**Comment by johngodley** [comment]
Fixed in 2.7.3
