### ISSUE TITLE
Wont Load any of the tab contents

### ISSUE THREAD

**Issue by johnswot** [johngodley/redirection#3231]
Installed and setup lots of redirects perfectly fine, the next day when I go in it wont load any of the tables for any of the tabs, just see this:

<img width="1254" alt="Screenshot 2022-02-11 at 09 41 53" src="https://user-images.githubusercontent.com/99475026/153569557-10275cec-2a56-4ab8-8ccb-97a5d2b5ecf6.png">

Dev Console Shows these 403s loading one after the other... thoughts?

<img width="1421" alt="Screenshot 2022-02-11 at 09 42 12" src="https://user-images.githubusercontent.com/99475026/153569619-bb5af6d9-10f5-4f93-8331-8f7c3e813d7c.png">

**Comment by johngodley** [comment]
Your REST API is returning a 403 error. I can't say why that is, but you may find more details by clicking on the errors in the console.

The plugin should detect this and show an error message. I'm not sure why it's not doing that here, but if you go to the support page it may show more details.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
