### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by TunedWP** [johngodley/redirection#3233]
### Summary

Redirect is not working for the URL: https://saxschoolonline.com/wp-content/uploads/2017/06/BakerStreet-FullSongAltoSax.pdf

### Actual Behavior

I already added the 301 redirects for the URL the pdf files for the site: https://saxschoolonline.com/ only this URL is not working: https://saxschoolonline.com/wp-content/uploads/2017/06/BakerStreet-FullSongAltoSax.pdf

### Steps to reproduce

Go to https://saxschoolonline.com/wp-content/uploads/2017/06/BakerStreet-FullSongAltoSax.pdf and it doesn't redirect

### Environment

Chrome browser version: Version 98.0.4758.82 (Official Build) (64-bit)
WordPress version: 5.9
Redirection plugin: Redirection 
![not working](https://user-images.githubusercontent.com/76083537/153797526-e1ec642e-8b15-4a41-aa80-509396331b8b.PNG)
Version 5.2.3 by John Godley

**Comment by johngodley** [comment]
The plugin warns you for those URLs:

![image](https://user-images.githubusercontent.com/1277682/153811513-e98538df-376e-4f63-800b-2b9cafce34f6.png)

https://redirection.me/support/problems/url-not-redirecting/

**Comment by TunedWP** [comment]
I got same error "Some servers may configured to serve ..." to all redirections I have set but they are all working except for the link that I posted initially. Kindly check. Thanks

<img width="1227" alt="Screen Shot 2022-02-15 at 8 13 49 PM" src="https://user-images.githubusercontent.com/76083537/154061507-7488c84d-8eef-4781-88f7-804fec9c9911.png">

**Comment by johngodley** [comment]
Sure, please read the guide that I referenced. This is not a problem with Redirection but the configuration of your site.
