### ISSUE TITLE
Strings not available for translation

### ISSUE THREAD

**Issue by kebbet** [johngodley/redirection#3234]
### Summary

The strings found in these files (among other) are not available for translations.  Are they extracted to the strings file?

#### Update notice
https://github.com/johngodley/redirection/blob/master/client/page/home/update-notice.js

####  Permalink module
https://github.com/johngodley/redirection/blob/master/client/page/site/permalink/index.js 

#### URL options
The string ”Exact match in any order” can not be found in the translation GUI att wp.org
https://github.com/johngodley/redirection/blob/master/client/page/options/options-form/url-options.js

### Steps to reproduce

Search in the translation-gui at wordpress.org for a string, and it is not found.
https://translate.wordpress.org/projects/wp-plugins/redirection/stable/sv/default/?filters[term]=Enter+old+permalinks+structures+to+automatically+migrate+them+to+your+current+one.&filters[term_scope]=scope_any&filters[status]=current_or_waiting_or_fuzzy_or_untranslated&filters[user_login]=&filter=Apply+Filters&sort[by]=priority&sort[how]=desc

### Environment

Latest WP, latest plugin version at trac.

**Comment by johngodley** [comment]
They are available for translation:

https://translate.wordpress.org/projects/wp-plugins/redirection/dev/es/default/?filters%5Bterm%5D=release+notes&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

I don't know why they only appear in the development version and not the stable version. Once they appear in the stable version they will be downloaded in the next plugin release.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
