### ISSUE TITLE
UTM Parameter Keyword issue

### ISSUE THREAD

**Issue by stormbrain-agency** [johngodley/redirection#3235]
**Summary**

We believe that the redirect plugin, in certain cases, is creating issues with our URL parameters. We are running search campaigns and capturing UTM tracking data in the URL. 

For example, between keywords, two ++ are being added, instead of the correct one +. See an example URL below 

EXAMPLE URL:
https://www.safesteptub.com/products/walk-in-tub-bathtub-features/?phone=8776311617&promo=0146&campaign=312476425&keyword=%2B safe+%2B step+%2B walk-in+%2B tub&content=578500231819&gclid=EAIaIQobChMI7qnzsOCB9gIVqBitBh0wqwC1EAAYASACEgKWoPD_BwE

When we look at our reporting and the keywords this is happening to they all are occurring on the below pages that we have redirects in place for via this plugin 

/products/walk-in-shower-features/
/products/walk-in-tub-bathtub-features/
<img width="1055" alt="Screen Shot 2022-02-16 at 9 18 50 AM" src="https://user-images.githubusercontent.com/73203051/154320638-52710695-fdb8-4e27-9783-3f0eaa837dcb.png">

/pricing-information/
/products/the-hybrid-walk-in-tub-bathtub-features/
/products/walk-in-tub-bathtub-features/walk-in-tub-therapeutic-features/

It is our thought that when the redirect happens it affects the UTM parameters in the tracking URL and is adding extra spaces causing the error with the keywords.

### Actual Behavior

We need the UTM tracking to work correctly and not be alerted when a redirect is in place. We already have a the ignore and pass all query parameters selected in the settings but it seems that something is taking place during the redirect causing the error in formatting of the redirected URL 

### Steps to reproduce

See screenshot of the leads in our reporting platform WhatConverts. You can see the ++ and this is happening on similar landing pages that we have redirects for 

### Environment

Redirection Version: 2.4.0 
WordPress Version: 5.8.3

Occurring across all browser types Safari, Chrome, Edge 
Happening with both Bing and Google cpc campigns

**Comment by johngodley** [comment]
Can you provide the redirect you have created for this and a proper URL to test with? The one above doesn't work.

**Comment by stormbrain-agency** [comment]
This entire URL does work 

https://www.safesteptub.com/products/walk-in-tub-bathtub-features/?phone=8776311617&promo=0146&campaign=312476425&keyword=%2B%20safe+%2B%20step+%2B%20walk-in+%2B%20tub&content=578500231819&gclid=EAIaIQobChMI7qnzsOCB9gIVqBitBh0wqwC1EAAYASACEgKWoPD_BwE

You'll need to grab the entire string and paste it in 

This is an example of a redirect 

Original URL 
safesteptub.com/walk-in-showers redirecting to safesteptub.com/products/walk-in-shower-features/

**Comment by johngodley** [comment]
Ok, that is a valid URL now. The URL doesn't redirect though.

The 'Original URL' you mentioned does redirect:
- https://safesteptub.com/walk-in-showers redirects to https://www.safesteptub.com/walk-in-showers
- https://www.safesteptub.com/walk-in-showers redirects to https://www.safesteptub.com/products/walk-in-shower-features/

At no point are there any UTM parameters.

Where am I looking for problems?

Also, can you show the redirect you have created? As in, a screenshot of the settings. I can't really say anything without knowing what you have created.

**Comment by stormbrain-agency** [comment]
Again that is an example you would need to go through a paid ad in google or bing and click on that ad to see the UTM parameters in the URL. In some cases, these spaces are getting added to the keyword. 

Try with this keyword 

Disabled Walk-in bathtubs 
walk in tubs 
handicapped bathrooms 
lowes walk in tubs 

These are all keywords that we have seen the error on

**Comment by stormbrain-agency** [comment]
But you would need to test with an ad that is redirecting to one of the features not the homepage

**Comment by stormbrain-agency** [comment]
Hi John, 

We have provided this. 

This is an example of a full URL with the error 

https://www.safesteptub.com/products/walk-in-tub-bathtub-features/?phone=8776311617&promo=0146&campaign=312476425&keyword=%2B safe+%2B step+%2B walk-in+%2B tub&content=578500231819&gclid=EAIaIQobChMI7qnzsO
<img width="1916" alt="Screen Shot 2022-02-16 at 10 14 12 AM" src="https://user-images.githubusercontent.com/73203051/154329329-8007b901-60aa-4d8d-8411-42bef51adf76.png">
CB9gIVqBitBh0wqwC1EAAYASACEgKWoPD_BwE

You can see the extra spaces being added in this part after the keyword %2B safe+%2B step+%2B walk-in+%2B tub

Screenshot attached

**Comment by johngodley** [comment]
Sure, but that's the URL *after* being redirected. I need the one before it is redirected.

**Comment by stormbrain-agency** [comment]
https://www.safesteptub.com/walk-in-tub?phone=8776311617&promo=0146&campaign=312476425&keyword=%2B safe%2B step%2B walk-in%2B tub&content=578500231819&gclid=EAIaIQobChMI7qnzsO

**Comment by johngodley** [comment]
Assuming that this is the URL (I've added the `+` myself)

https://www.safesteptub.com/walk-in-tub?phone=8776311617&promo=0146&campaign=312476425&keyword=%2B+safe%2B+step%2B+walk-in%2B+tub&content=578500231819&gclid=EAIaIQobChMI7qnzsO

Then Redirection is not redirecting that:

https://redirect.li/http/?url=https%3A%2F%2Fwww.safesteptub.com%2Fwalk-in-tub%3Fphone%3D8776311617%26promo%3D0146%26campaign%3D312476425%26keyword%3D%252B%2Bsafe%252B%2Bstep%252B%2Bwalk-in%252B%2Btub%26content%3D578500231819%26gclid%3DEAIaIQobChMI7qnzsO

**Comment by stormbrain-agency** [comment]
Hi John, 

We do not have the UTM parameters added in redirection they are dynamically added when an add is clicked because the content is changing so that is why we have the setting ignore and pass parameters on then it seems to occur during that process

**Comment by stormbrain-agency** [comment]
https://www.safesteptub.com/shower-tub-combo/ --->
https://www.safesteptub.com/products/the-hybrid-walk-in-tub-bathtub-features/

For example that is a redirect in place and then once an is clicked the UTM parameters are added after the / which sometimes causes an issues with keyword spaces

**Comment by johngodley** [comment]
We seem to be going round in circles a bit here.

The only way I can test this is if you provide the full URL, including UTM parameters, of the original request that is made before being redirected. That is the only thing that is needed.

There are many URLs above, but they either seem to be the URLs after being redirected, or URLs that don't include UTM parameters.

**Comment by stormbrain-agency** [comment]
Yes I see but we do not have access to that in our reporting side we can just see the redirected URL with parameters but we know that these have redirects in place for them since it is a new website and these URLs were not there before

**Comment by stormbrain-agency** [comment]
We found an example of the original request before the redirect takes place. See below and screenshots. You can see here that the source URL does not have additional + but in the target URL after the redirect those are added for some reason see this snippet utm_term=%2Bdisabled+%2Bwalk-in-baths

Should we adjust our redirect passing setting to avoid this 

Source URL:
https://www.safesteptub.com/walk-in-showers/?phone=8007701936&promo=0158&msclkid=c33247cb66311f6a502f25c67edcb49c&utm_source=bing&utm_medium=cpc&utm_campaign=B_Safe%20Step%20Walk-In%20Tubs_NB%20Handicap&utm_term=%2Bdisabled%20%2Bwalk-in-baths&utm_content=Disabled%20Bathroo
![Screen Shot 2022-02-16 at 11 27 21 AM](https://user-images.githubusercontent.com/73203051/154341738-2c28bad0-9f97-4da0-869f-0708d3fc9abe.png)
![Screen Shot 2022-02-16 at 11 27 32 AM](https://user-images.githubusercontent.com/73203051/154341747-50333e1f-ed74-4a02-a668-7cebc6824d61.png)
![Screen Shot 2022-02-16 at 11 32 38 AM](https://user-images.githubusercontent.com/73203051/154341752-c7fa6a1d-ce96-4f4c-bfe1-2b4f67f4beb1.png)
m_MB&campaign=171417370&keyword=%2Bdisabled%20%2Bwalk-in-baths&content=&msclkid=c33247cb66311f6a502f25c67edcb49c&utm_source=bing&utm_medium=cpc&utm_campaign=B_Safe%20Step%20Walk-In%20Tubs_NB%20Handicap&utm_term=%2Bdisabled%20%2Bwalk-in-baths&utm_content=Disabled%20Bathroom_MB

Target URL:
https://www.safesteptub.com/products/walk-in-shower-features/?phone=8007701936&promo=0158&msclkid=c33247cb66311f6a502f25c67edcb49c&utm_source=bing&utm_medium=cpc&utm_campaign=B_Safe+Step+Walk-In+Tubs_NB+Handicap&utm_term=%2Bdisabled+%2Bwalk-in-baths&utm_content=Disabled+Bathroom_MB&campaign=171417370&keyword=%2Bdisabled+%2Bwalk-in-baths&content=

**Comment by stormbrain-agency** [comment]
Sorry looks like the source original URL got cut off by the screenshots 

See below 


Source URL:
https://www.safesteptub.com/walk-in-showers/?phone=8007701936&promo=0158&msclkid=c33247cb66311f6a502f25c67edcb49c&utm_source=bing&utm_medium=cpc&utm_campaign=B_Safe%20Step%20Walk-In%20Tubs_NB%20Handicap&utm_term=%2Bdisabled%20%2Bwalk-in-baths&utm_content=Disabled%20Bathroom_MB&campaign=171417370&keyword=%2Bdisabled%20%2Bwalk-in-baths&content=&msclkid=c33247cb66311f6a502f25c67edcb49c&utm_source=bing&utm_medium=cpc&utm_campaign=B_Safe%20Step%20Walk-In%20Tubs_NB%20Handicap&utm_term=%2Bdisabled%20%2Bwalk-in-baths&utm_content=Disabled%20Bathroom_MB

**Comment by stormbrain-agency** [comment]
The +%2B is where the ++ issue is being created

**Comment by stormbrain-agency** [comment]
Hi John, 

Any thoughts or updates here?

**Comment by johngodley** [comment]
I am still investigating

**Comment by stormbrain-agency** [comment]
We got it fixed all good

Thanks,

Jared Kavalle
————————

| Storm Brain |
Digital Account Manager
http://www.stormbrain.us<http://www.stormbrain.us/>
+1 (866) 778-6279 <tel:+1%20(866)%20778-6279;101>
________________________________
