### ISSUE TITLE
Feature request: Custom URL Protocols

### ISSUE THREAD

**Issue by xkasprx** [johngodley/redirection#3238]
Allowing the use of non-standard (http, https) protocols such as application urls:

Example: appurl://path/to/myapp

For a better example and mainly because it's the protocol I'd like to use:

fivem://ipaddress:port#

**Comment by johngodley** [comment]
You can use whatever URL you want in the target.

**Comment by johngodley** [comment]
Sure, it's just a warning to help the majority of cases - people often put broken URLs.

**Comment by xkasprx** [comment]
Ok cool so then ignore this too right?
![image](https://user-images.githubusercontent.com/71482506/154695031-2cb4af75-9128-46cd-8eae-1c79ade50cac.png)

**Comment by johngodley** [comment]
The redirect checker won't be able to check your custom protocol, so yes you can ignore it.
