### ISSUE TITLE
The translated file does not work and the results are not displayed.

### ISSUE THREAD

**Issue by hcllmsx** [johngodley/redirection#3244]
The translated file does not work and the results are not displayed.

After translating the plug-in's pot file into simplified Chinese through poedit, I get the "po" and "mo" files, and I name the translated files "redirection-zh_CN.po" and "redirection-zh_CN.mo". In addition, my site language is also set to simplified Chinese.

Then I put these two files under "/wp-content/languages/loco/plugins" and it doesn't work, either "/wp-content/plugins/redirection/locale" or "/wp-content/languages/plugins". 

Where do I put the translated two files?

**Comment by johngodley** [comment]
Translations should be added to https://translate.wordpress.org/locale/es/default/wp-plugins/redirection/ which will then be included with the next release of the plugin.

**Comment by hcllmsx** [comment]
Can I only add translation files here? Can I debug it on my own website first?

**Comment by hcllmsx** [comment]
All right, then use your method first. But for simplified Chinese, it should be this link: https://translate.wordpress.org/projects/wp-plugins/redirection/stable/zh-cn/default/

**Comment by johngodley** [comment]
Sure, the translations page contains all the available languages. Only languages translated there will be included in the plugin.

**Comment by hcllmsx** [comment]
thank you.
