### ISSUE TITLE
Redirection is working partially

### ISSUE THREAD

**Issue by hookedupon** [johngodley/redirection#325]
Hi,

Thank you for this wonderful Wordpress plugin. I am currently facing an issue and would really appreciate your help. I am renaming my Wordpress articles and have been using the plugin to do redirects. The issue I am facing is as follows:

**Scenario 1**
Original URL: www.hookedupon.com/10-alternative-ways-of-using-common-salt
Redirect URL: www.hookedupon.com/alternative-ways-of-using-common-salt

**Scenario 2**
Original URL: www.hookedupon.com/10-alternative-ways-of-using-common-salt/
Redirect URL: www.hookedupon.com/alternative-ways-of-using-common-salt/

Scenario 1 works fine but scenario 2 gives 404 page not found error. Do I need to set two redirects for a particular URL or am I setting the redirect incorrectly?

Regards

**Comment by johngodley** [comment]
So it's not redirecting the one with the slash on the end? Or you want to redirect both with and without a slash?

**Comment by hookedupon** [comment]
It's not redirecting the one with the slash in the end. Do I need to set redirect for both slash and without slash?

**Comment by johngodley** [comment]
Yes, the plugin looks at URLs without context - one with a slash and without are considered different URLs. You could also use a regular expression to match multiple URLs

**Comment by hookedupon** [comment]
How can I set regex? (Sorry I am a novice)

**Comment by johngodley** [comment]
Its... complicated! If you don't have too many redirects then I'd recommend just adding them all individually. At some point in the future Redirection will likely have a feature to ignore trailing slashes.

If you have a lot of redirects then a regular expression may allow you to match them all. If you click the ? link next to the regex checkbox when editing a redirect it will take you to a page with more details about them, and there are a lot of resources on the web.

**Comment by hookedupon** [comment]
Great thanks!

**Comment by aeromusek** [comment]
>At some point in the future Redirection will likely have a feature to ignore trailing slashes

Yes, please so much on this! It is also an issue with automatic redirects on renamed posts, especially when incoming requests have query params attached to the URL.
