### ISSUE TITLE
Problem starting Redirection 5.2.3

### ISSUE THREAD

**Issue by novingram** [johngodley/redirection#3250]
Plugin: 5.2.3 4.2
WordPress: 5.9.1 (single)
PHP: 8.0.15
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
JavaScript: https://ticket.media/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://ticket.media/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions and check your browser developer console. This is likely caused by another plugin.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
