### ISSUE TITLE
Feature request:  Ability to check for redirect loops

### ISSUE THREAD

**Issue by randallhedglin** [johngodley/redirection#3254]
Great plugin, works well and easy to use.  It would be nice to have a tool to check for redirect loops (i.e., /A redirects to /B, /B redirects to /C, and /C redirects back to /A).  Even a hastily done import could have /A redirecting to /A, and the plugin doesn't catch this.  Would be a helpful feature to just click a button and check all the currently active redirects for loops and be able to edit them easily from those results.

**Comment by fcharrasse** [comment]
Hello,

Allow me to elaborate on the second point concerning csv imports.
Would it be possible to automatically exclude lines where the old url is equal to the new url.
Example :

```
/toto/, /tata/
/contact/, /contact/
/contact/, /contact
/titi/, /tutu/
```

In the 2nd and 3rd case, this will create an infinite redirection loop. 
When the import file is large it is difficult to check line by line.

Thanks !

**Comment by johngodley** [comment]
Moving to #82
