### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by awakash** [johngodley/redirection#3256]
```
Plugin: 5.1.3 4.2
WordPress: 5.9.1 (single)
PHP: 7.4.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
JavaScript: https://ab-red-news-aclu-wp.pantheonsite.io/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://ab-red-news-aclu-wp.pantheonsite.io/wp-json/
Query: ?page=redirection.php&sub=io

Error: Unexpected token T in JSON at position 0 (SyntaxError)
Raw: The application did not respond in time.
```

**Comment by johngodley** [comment]
The message 'The application did not respond in time.' is from your server. I don't know what it means or what it refers to but it's not part of the plugin.

**Comment by awakash** [comment]
Thanks @johngodley I think it's a timeout on the server since it's hitting the ~60 sec mark.

**Comment by johngodley** [comment]
What are you doing that could be causing it to timeout after 60 seconds? I can't think of anything that would take so long.

**Comment by awakash** [comment]
Importing about 12k+ redirects via a json file

**Comment by johngodley** [comment]
Ok, you'll either need to split the import up, or increase the timeout limit.
