### ISSUE TITLE
Problem starting Redirection 5.1.3

### ISSUE THREAD

**Issue by grilomkt** [johngodley/redirection#3263]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/101997222/159186276-01d6876c-ec9f-4134-a833-6c03de6c3f33.png">

I would like to understand what i can do to fix this.

**Comment by johngodley** [comment]
Everything should be detailed on the error page. This is almost certainly caused by another plugin on your site, or something else outside of Redirection.

**Comment by grilomkt** [comment]
it was a plugin - optin monster - the problem. thank you.
