### ISSUE TITLE
405 method not allowed with Awin network

### ISSUE THREAD

**Issue by berryhc** [johngodley/redirection#3266]
Hello nice people!!

### Summary

Unfortunately with the Awin affiliate network links, the check redirect (from redirection plugin) gives me a 405 method not allowed

### Actual behavior

The links seem to take to the target page, but I guess that it is not tracked (affiliate cookie), then I would not get my reward. 

### Steps to reproduce

I send you the screenshot down here.

### Environment

Firefox browser version 98-0.1   -    WordPress Version 5.9.2   -   Redirection plugin Version 5.2  

### Request

ANYONE CAN HELP ME?  THAT' S CRUCIAL.. IT' S A HUGE PROJECT, I SPENT MORE THAN 1 YEAR TIME!

Thank you a lot in advance!!

![pkaVQjhanKI9SqUp](https://user-images.githubusercontent.com/102314056/159982435-6bcc06fd-ce24-47ac-ab43-becb183432b8.png)
![Osdl9V1Liez9n07n](https://user-images.githubusercontent.com/102314056/159982429-3ba84ee4-6139-47fb-866a-678a73b5c548.png)

**Comment by johngodley** [comment]
What are you expecting to happen? Everything seems to be working ok as far as Redirection is concerned.

**Comment by berryhc** [comment]
> What are you expecting to happen? Everything seems to be working ok as far as Redirection is concerned.

Does that not depends on the redirection plugin in your opinion?  Maybe some changes in the setting, might avoid the 405.. or how else can i work on that?

**Comment by johngodley** [comment]
No, you can see that Redirection is only involved in the first redirect. Everything else after that is not Redirection.

**Comment by johngodley** [comment]
The redirect checker does not pass cookies.

**Comment by berryhc** [comment]
> The redirect checker does not pass cookies.

Does this mean that affiliate links are not trackable if using redirection plugin? Hope it's not what you mean...

**Comment by johngodley** [comment]
That's not what I'm saying. Redirection does redirects. Based on your screenshot it is working fine. Any other problems you are seeing are not caused by Redirection.

I said that the redirect checker does not pass cookies. That is not Redirection.

**Comment by berryhc** [comment]
> I said that the redirect checker does not pass cookies. That is not Redirection.

Hello John, sorry if I'm wasting your time, but I do not totally understand, I'm quite new in this area.

Could you tell me exactly what you mean with: I said that the redirect checker does not pass cookies. That is not Redirection. please?

**Comment by johngodley** [comment]
No, the redirect checker is not Redirection. It is a service that checks redirects. It does not use cookies. If you require cookies then you cannot use the redirect checker to check your redirect. This is not part of Redirection.

Redirection is working fine. This can be seen in your screenshot - step 1. All other steps are not part of Redirection.
