### ISSUE TITLE
Redirection doesn't work on URLs with "/" at the end

### ISSUE THREAD

**Issue by alanaschmidt01** [johngodley/redirection#3268]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I'm trying to redirect pages from my blog, with source URLs that end with "/", but the redirect is not done, the URL remains with status 200.

Note: Destination URLs are from an external website.

### Actual Behavior

I updated the plugginr edirection database, but it still doesn't happen.

If I leave without the "/" at the end, the redirect works, but the urls indexed in google contain the "/"

### Steps to reproduce

Steps: https://prnt.sc/AEGT3wgCH1pW
How to inform: https://prnt.sc/IL5EKiAVj58S

### Environment

Google Chrome, Wordpress 5.7, Redirection Versão 5.2.3

**Comment by johngodley** [comment]
It does work with URLs with `/` at the end. If you want it to ignore the trailing slash there is an option to do so.

**Comment by alanaschmidt01** [comment]
I've already tested this function, the redirection doesn't happen the same way. I need it to work with URLs with / at the end.

**Comment by johngodley** [comment]
Can you provide the full URL to what is and isn't working?

**Comment by johngodley** [comment]
You should fix the certificate, yes.

However, it is not Redirection that is doing the redirect but WordPress itself. Why Redirection isn't doing the redirect I don't know, and that's a separate issue.

**Comment by alanaschmidt01** [comment]
I don't know if we will solve the certificate problem, because we are redirecting precisely because the site will cease to exist

OK. But do you have any idea how I can work around this and make the redirects work?

**Comment by johngodley** [comment]
This seems to be working so closing this issue.
