### ISSUE TITLE
Granting user rights to redirect

### ISSUE THREAD

**Issue by justanotherentrepreneur** [johngodley/redirection#3269]
I would like to grant a single user the rights to access Redirect plugin and make changes without making them a full on administrator. 

I currently use the Memberpress plugin that allows me to grant specific roles to various user types. For this blog manager position, I would like to grant them access to the redirect plugin, but I don't see the option there.

Is there any way to do this without making the user an administrator?

Thank you!

**Comment by johngodley** [comment]
Details here: https://redirection.me/developer/permissions/

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
