### ISSUE TITLE
Where are nginx redirects saved?

### ISSUE THREAD

**Issue by columbian-chris** [johngodley/redirection#3272]
My nginx redirects aren't working so I'm wondering if there's an nginx file saved somewhere that I need my server's nginx setup to pick up?

**Comment by columbian-chris** [comment]
Thanks for the reply, John.  Maybe an improvement to the plugin would be to have a setting to specify where you want nginx redirects saved and have them save there instead of requiring you to export and manually put them in, like how the plugin handles apache redirects (I could be mistaken about this)?  Then all that would need to be done is to tell nginx on the server side to include that file.

Thanks for the great plugin, seriously. 👍

**Comment by johngodley** [comment]
Due to the nature of Nginx it's not really practical to save it directly to the server files.

**Comment by columbian-chris** [comment]
Why not?  I use other plugins like iThemes Security that do it.
