### ISSUE TITLE
Feature request: Mass update HTTP Code

### ISSUE THREAD

**Issue by tomas-eklund** [johngodley/redirection#3275]
It would be very useful to be able to change the HTTP code for large chunks of redirects in one go. For example, during development/staging it might be useful to use a forgiving temporary status code (such as 307), that won't be cached by browsers, and change to a permanent redirect (such as 308) once the link structure have been finalized. If you have a lot of redirects set up, doing this manually is a very tedious and time-consuming task.

**Comment by johngodley** [comment]
You've already suggested this here: #3154

**Comment by tomas-eklund** [comment]
Oh! I had completely forgotten about that. Sorry. Getting old, I guess...
