### ISSUE TITLE
Sorry, you are not allowed to access this page.

### ISSUE THREAD

**Issue by damelco** [johngodley/redirection#328]
this is an odd one?
we are reviving a site that was offline for 4 years ... very large and fully functional (then).
we updated wp and all plugins
changed domains
did the standard updates to the wp-config files
a few glitches ...
we cannot view the Redirection plugin ... we get the error;
Sorry, you are not allowed to access this page.
about 30 plugins ... this is the only one giving us this response ...
hopefully it is a simple fix ... btw: this IS superadministrator access.
what say thou?

-DJ

**Comment by johngodley** [comment]
As far as I know this is a WordPress thing, and not something that the plugin itself does. I don't know why it would occur for Redirection only. My only suggestion is to delete the plugin and reinstall it

**Comment by damelco** [comment]
I'm pretty sure there is a huge list of "re-directs" within ... they'll survive a plugin delete, and reinstall?

**Comment by johngodley** [comment]
No, they probably wont. Having a backup of the redirection database tables would be advisable

Some other things to try:
- You could try reverting the plugin to the last version you had working and see what happens.
- You could look also in your server error log to see if anything is happening there

**Comment by damelco** [comment]
I deleted and re-installed
oddly, nothing changed, still same error!
how is that for weird?!

**Comment by johngodley** [comment]
So I think that message is shown by this function returning false:

https://developer.wordpress.org/reference/functions/user_can_access_admin_page/

As you can see, the function has many ways of returning false.

Do you have any other plugins that are to do with permissions?

Without having access to the server itself it's hard for me to debug further, but one thing you could try is editing the function in the file mentioned in the above URL and for every time the function `return false;` you replace it with:

`{ error_log(__LINE__); return false; }`

Then if you try and access Redirection your server's error_log should show what line is returning false, and that may help track down why it's not allowing you access.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
