### ISSUE TITLE
Problem starting Redirection 5.2.3

### ISSUE THREAD

**Issue by nahid-hridoy** [johngodley/redirection#3281]
Plugin: 5.2.3 4.2
WordPress: 5.9.3 (single)
PHP: 7.3.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
JavaScript: https://miamigas.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://miamigas.com/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This URL is not accessible:

https://miamigas.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
