### ISSUE TITLE
Problem starting Redirection 5.2.3

### ISSUE THREAD

**Issue by clotrvs** [johngodley/redirection#3283]
```
Uncaught SyntaxError: Unexpected end of input https://prague.org/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be 2
```

Plugin: 5.2.3 4.2
WordPress: 5.8.4 (single)
PHP: 7.3.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
JavaScript: https://prague.org/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://prague.org/wp-json/

**Comment by johngodley** [comment]
As described on the error page this is almost certainly caused by another plugin on your site.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
