### ISSUE TITLE
User Role Permission not working

### ISSUE THREAD

**Issue by MarkRA312** [johngodley/redirection#3284]
I entered the "sample permission plugin" code on this page: https://redirection.me/developer/permissions/

However, I'm getting this error when logged in as an editor:

- Something went wrong 🙁
- Sorry, you are not allowed to do that. (rest_forbidden)

- REST API:
- Unavailable
- Check Again
- Summary: Your REST API is not working and the plugin will not be able to continue until this is fixed.
-

**Comment by johngodley** [comment]
It sounds like you've not copied it exactly. You can download the plugin instead.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
