### ISSUE TITLE
Redirections Question 

### ISSUE THREAD

**Issue by company15** [johngodley/redirection#3289]
### Summary

Hello i had a question in the redirects page I saw that on some it shows /page then at the bottom of the redirect it shows https//[www.company.com/new](http://www.company.com/new) should the top show the https or is it fine ass is some show it some show the full https on top and bottom  just wanted to see if it’s normal or what should i do about it.

### Environment

Redirects Version 5.2.3

**Comment by johngodley** [comment]
I don't know what you mean by this. Can you add more details?

**Comment by company15** [comment]
Ok thanks they are all set like the top one but just wanted to see if it should have set like the second one so i will let them stay as is like the top one.
