### ISSUE TITLE
Http Protocol Error(Error 302)

### ISSUE THREAD

**Issue by remymumoh** [johngodley/redirection#329]
after adding a redirect to a certain page, the plugin somehow overwrite all the website addresses to that new  redirection even the menus are being taken to that new redirection. After deleting the redirection and the redirection pages am getting the error 302 when i try to access the main link of the website. Please help

**Comment by johngodley** [comment]
What was the redirect? Can you show a screenshot of it?

> the plugin somehow overwrite all the website addresses to that new redirection even the menus are being taken to that new redirection

I don't know what this means. Can you explain further and/or show a screenshot?

> After deleting the redirection and the redirection pages am getting the error 302

A 302 is a redirect. If you delete the redirect from redirection then it is no longer working. Your browser may have cached the redirect so you should clear your browser cache.

**Comment by remymumoh** [comment]
can the plugin be conflicting with a theme?

**Comment by johngodley** [comment]
> can the plugin be conflicting with a theme

Anything is possible, but I don't know the situation enough to say if that's the problem here.syn

**Comment by remymumoh** [comment]
So i manage to revive the website, but still the plugin is redirecting me to the wrong address. When i try to go home from my website, the url the site picks is the one i added on the redirection plugin. 

I need to go here www.atpsnet.org but the url its redirecting me to is http://www.atpsnet.org/news-archives/ and thats not my home

**Comment by johngodley** [comment]
Can you include a screenshot of your redirects?

**Comment by remymumoh** [comment]
![capture](https://user-images.githubusercontent.com/10322082/29654886-afd3a58a-88b7-11e7-8e0e-d874d5ae44b7.PNG)

**Comment by remymumoh** [comment]
after adding that redirection my front page goes to that redirection,and all other links clicked within the website go to that link

**Comment by johngodley** [comment]
Ok, then that redirection is working fine and will not be affecting anything else.

Do you have a static home page? Do you have any other redirects? If you disable the redirect does it keep happening?

**Comment by remymumoh** [comment]
yes  i have a static home page, and yes i have other redirects. If i disable the redirect, the home page is still being redirected to  http://www.atpsnet.org/news-archives/

**Comment by johngodley** [comment]
I don't think that redirect has anything to do with the problem. It will only redirect when the URL is `/media_centre/news_archive/`.

If you can list your other redirects that will help. Also, your front page configuration may be causing a problem.

**Comment by remymumoh** [comment]
but all the other links are being affected and being redirected to this http://www.atpsnet.org/news-archives/ why is that so. They are independent and not front pages

**Comment by remymumoh** [comment]
fixed it thanks for the quick response

**Comment by johngodley** [comment]
> fixed it thanks for the quick response

Can you provide more details?

**Comment by remymumoh** [comment]
It worked after i went and personally deleted the page news-archives. 

Seems like deleting the redirection from the plugin doesn't delete the details permanently. Deleting the page stops the website from following that url added by the redirection plugin. 

Regards
