### ISSUE TITLE
Redirect to old page

### ISSUE THREAD

**Issue by kakat10** [johngodley/redirection#3290]
We are trying to use a redirect to send users from a URL to a signup page at another URL.

We have a redirect in place for page www.fullerheaven.com/vbs that is supposed to forward them to a signup page for an event. The problem is this, it sends them to a page that was used last year and is incorrect/not working this year.

![github1](https://user-images.githubusercontent.com/105082099/167214682-10a8f3af-f9ba-454f-a2be-eb7bc594dd00.png)

![github2](https://user-images.githubusercontent.com/105082099/167214673-c639e13f-7b4d-466a-933d-073d09da91b4.png)

I have included photos of where it is supposed to redirect via the settings and a photo of what actually loads when you go there. In addition, I tested the redirect to the page by creating one at www.fullerheaven.com/tacos to see if it would work and it does. You can try it to see where the /VBS should be going.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Chrome - Version 101.0.4951.54 (Official Build) (64-bit)

Wordpress Version 5.9.3

Redirection Version 5.2.3

**Comment by johngodley** [comment]
Your redirect is for `/VBS` not `/vbs`. The plugin will only ever redirect to what you configure.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
