### ISSUE TITLE
Problem starting Redirection 5.2.3

### ISSUE THREAD

**Issue by affykhan** [johngodley/redirection#3293]
Plugin: 5.2.3 4.2
WordPress: 5.9.3 (single)
PHP: 7.4.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
JavaScript: http://www.aparnagovilbhasker.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: http://www.aparnagovilbhasker.com/wp-json/

**Comment by johngodley** [comment]
As described in the error page this is almost certainly caused by another plugin.
