### ISSUE TITLE
Lowercase conversion doesn't work

### ISSUE THREAD

**Issue by garzettone** [johngodley/redirection#3295]
I setup a "regex" rule to redirect AND convert destination address to lowercase:

Source URL:  ^/eng/(.*)
Destination ULR: /en/\L$1

but the "\L"  (it means convert to lowercase anything follow) doesn't work.
See https://www.regular-expressions.info/replacecase.html for reference

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
