### ISSUE TITLE
Redirections duplicates the URI in the Location header

### ISSUE THREAD

**Issue by bpfh** [johngodley/redirection#3296]
### Summary

Thanks for a wonderful plugin!

When creating a redirect for an entire site using a regular expression, Redirection duplicates the URI in the Location header (see screenshot).

### Actual Behavior

The location header contains:

```
location: https://example.net/foobar/https://example.net/foobar/
```

### Steps to reproduce

Create a redirect rule as per the screenshot.

### Environment

WordPress 5.9.3
Redirection 5.2.3

<img width="980" alt="Screenshot 2022-05-13 at 12 49 16" src="https://user-images.githubusercontent.com/822210/168259257-982d6814-56cc-4795-af21-6540b79fb1dd.png">

**Comment by johngodley** [comment]
Your source URL should be `^.*`, as suggested in the warning, or even better `^/.*`
