### ISSUE TITLE
A link redirect is pointing to an image file. It says "Redirected by Yoast SEO" but I do not have the Yoast redirection feature.

### ISSUE THREAD

**Issue by mglcarina** [johngodley/redirection#3297]
I am trying to redirect https://www.rsisecurity.com/compliance-advisory-services/hipaa-3/ to https://www.rsisecurity.com/compliance-advisory-services/hipaa/

What is happening is that https://www.rsisecurity.com/compliance-advisory-services/hipaa-3/ is being redirected to https://www.rsisecurity.com/compliance-advisory-services/hipaa/ and then it shows that it is Redirected by Yoast SEO to https://www.rsisecurity.com/wp-content/uploads/2020/09/hipaa.png but i do not have a yoast redirection feature.

Using Chrome, Version 101.0.4951.54, WordPress 5.9.3, Redirection plugin 5.2.3

**Comment by johngodley** [comment]
That URL is not being redirected as you describe:

https://redirect.li/http/?url=https%3A%2F%2Fwww.rsisecurity.com%2Fcompliance-advisory-services%2Fhipaa-3%2F

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
