### ISSUE TITLE
Add support for IPv6

### ISSUE THREAD

**Issue by bobcanthelpyou** [johngodley/redirection#33]
Sometimes the IP addresses at the 404s log is show as 0.0.0.0, why that?

**Comment by bobcanthelpyou** [comment]
Maybe an issue with IPv6 and ip2long()? http://php.net/manual/en/function.ip2long.php

Is it possible to save IPv4 and IPv6 as strings or as an other data type (but not long)?

**Comment by bobcanthelpyou** [comment]
An idea could be to save the IP as binary with
inet_pton() instead of ip2long() and
inet_ntop() instead of long2ip()
http://php.net/manual/en/function.inet-pton.php
http://php.net/manual/en/function.inet-ntop.php

**Comment by johngodley** [comment]
Thanks! I haven't thought about IPv6 yet. I've renamed this issue to be 'Add support for IPv6'

**Comment by johngodley** [comment]
Merging with #265
