### ISSUE TITLE
Complete website redirect - trouble with wildcards working

### ISSUE THREAD

**Issue by John-toaks** [johngodley/redirection#330]
I have 262 blogposts at http://www.toaksgogreen.org a WP site that I need to redirect to the City's new (non-wp) website to our sustainability page http://www.toaks.org/departments/public-works/sustainability 

I can get specific pages to transfer and I watched one YouTube video with Optimwise that covered wild cards, but I think it was an earlier version of Redirection because I can't find anything related to regular expressions. I tried a bunch of other internet searches and YouTube but was not able to figure out. 

I have also attempted multiple variations on the wild cards to get all posts to transfer, but have been unsuccessful. Appreciate any insight you could share - John

Chrome Version 60.0.3112.101 (Official Build) (32-bit) 
Wordpress Version 4.8.1
Redirection 2.7.1

**Comment by johngodley** [comment]
Regular expressions are still available, just make sure to check the 'regex' checkbox.

**Comment by johngodley** [comment]
Closing for now, please provide more details if the problem still exists
