### ISSUE TITLE
please add more parameters for importing a csv file, like: (status: Enabled, disabled), (query_parameters: excat match, ignore all) , etc..    ASAP!!

### ISSUE THREAD

**Issue by MiladDadosh** [johngodley/redirection#3300]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
You will need to use the JSON format for this. CSV will not support all of those parameters.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
