### ISSUE TITLE
Issue with Page Loading After Redirections

### ISSUE THREAD

**Issue by zheern** [johngodley/redirection#3304]
### Summary

I'm trying to access the front end of our beta site and I'm getting the following error after I imported all my 301 redirects:

"Load cannot follow more than 20 redirections."

### Actual Behavior

The beta site will not load in the browser (using Safari). 

### Steps to reproduce
Typing in the URL in the search bar of the Safari browser. http://commercialwarehousing.com.216-70-96-51.jvv2-rfnp.accessdomain.com/

Explain the steps involved to reproduce the problem

### Environment

Safari 15.4, Wordpress, Redirection plugin 5.2.3.

**Comment by johngodley** [comment]
You will need to delete whatever redirect is looping back to the home page.

**Comment by zheern** [comment]
Okay - I will try that. Thank you!

**Comment by zheern** [comment]
It worked! Thank you!
