### ISSUE TITLE
# is being changed to %23 and getting a 404 error

### ISSUE THREAD

**Issue by raesiebels** [johngodley/redirection#3308]
Summary
I am trying to redirect a page to /legal#warranty/

Actual Behavior
When I test the redirect it goes to /legal/%23warranty/ and I get a 404 error.

I do not have this issue on another site I manage, so I don't understand why this is happening.

Blue Host hosting
Chrome 
Wordpress 6.0
Redirection 5.2.3

**Comment by johngodley** [comment]
Can you add more details including the redirect you have created and the full URL?

**Comment by raesiebels** [comment]
Yes, I just didn't want to put the full URL on a public forum

**Comment by johngodley** [comment]
Closing for now please reopen with more information.
