### ISSUE TITLE
Redirect 404s

### ISSUE THREAD

**Issue by mrinalrx** [johngodley/redirection#3310]
On this website, 404 errors are generated automatically. How can I fix these error links?
![image](https://user-images.githubusercontent.com/98554629/172067942-29ec96d0-7cb1-4c5f-ad95-daa8f2837a64.png)

**Comment by johngodley** [comment]
Use Redirection in a way that is appropriate to your website, creating a redirect or error response, or just ignoring them - 404s are not bad.
