### ISSUE TITLE
Update Database version problem and PHP warning

### ISSUE THREAD

**Issue by alessandrocarrera** [johngodley/redirection#3311]
### Summary

In this Issue I report a bug that generate many occurrences of a PHP warning and a potential big problem for the updating of the Redirection database version.

### Actual Behavior

In my PHP log file I have many occurrences of this error:

```

Got error 'PHP message: PHP Warning: version_compare() expects parameter 1 to be string, array given in /EXAMPLE-PATH/wp-content/plugins/redirection/database/database-status.php on line 71

```

I think that something in this function not working because it returning an array (not a string):

https://github.com/johngodley/redirection/blob/master/database/database-status.php#L88

### Steps to reproduce

I don't know how and why the function `get_current_version()` is returning an array and not a string but you can temporarily return an array in the function for managing the error better and avoid the PHP warning (if there aren't other problems).

### Environment

Google Chrome version 102.0.5005.61
Wordpress version 5.5.9
Redirection version 5.2.3

**Comment by alessandrocarrera** [comment]
> Your settings appears to contain bad data. What version does it say on the support page of the plugin?

Thank @johngodley for you reply. This is a screenshot:

![Immagine](https://user-images.githubusercontent.com/74904794/177125185-c98ea027-d4d4-4184-bc55-6b6cca5f7b06.png)

So the Database version is 2.3.1 the first of the list.

**Comment by johngodley** [comment]
Does https://github.com/johngodley/redirection/releases/tag/5.3-beta help?
