### ISSUE TITLE
Redirection setup options not respected

### ISSUE THREAD

**Issue by andreslotta** [johngodley/redirection#3316]
### Summary

After installing the plugin I go through the redirection setup process. In there I choose to monitor permalink changes and keep a log of all redirects and 404 errors **but not to store IP information**. After finishing the setup process I go to the plugin options and see that "Full IP logging" is enabled. Also the "URL Monitor" checkboxes are unchecked for all post types.

Screencast of the problem: https://cln.sh/uqoQEv

### Actual Behavior

The "Monitor permalink changes" and "Store IP information" settings from the redirection setup process are not respected.

### Steps to reproduce

1. Install the plugin on a website
2. Go through the redirection setup process and choose to monitor permalink changes and not to store IP information
3. Check the plugin options and see that permalink changes are **not** monitored and "Full IP Logging" is enabled

### Environment

Local by Flywheel, WordPress 6.0, PHP 7.4.1 (also reproduced on multiple "real" servers with similar setups)

**Comment by johngodley** [comment]
Yep, this is a known problem and will be fixed in the next release.
