### ISSUE TITLE
Problem starting Redirection 5.2.3

### ISSUE THREAD

**Issue by Sigga-Bopha** [johngodley/redirection#3317]
Plugin: 5.2.3 4.2
WordPress: 6.0 (single)
PHP: 7.4.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
JavaScript: https://www.littlelotsonline.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://www.littlelotsonline.com/wp-json/

**Comment by johngodley** [comment]
This doesn't work:

https://www.littlelotsonline.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
