### ISSUE TITLE
Blank screen on Redirection settings page

### ISSUE THREAD

**Issue by yondershore** [johngodley/redirection#3319]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

We are running a site on DIVI, Flywheel is the host. Installed Redirection plugin with the onboard installer

### Actual Behavior

When I go to the settings page, it is blank save for the link to report an issue.

### Steps to reproduce

Install the plugin. Nothing.

### Environment

Mac, latest Chrome, Divi theme

**Comment by johngodley** [comment]
Can you include a screenshot?

**Comment by yondershore** [comment]
Todd Dengler
***@***.***

**Comment by johngodley** [comment]
You need to upload screenshots on the web, not an email.

**Comment by yondershore** [comment]
![PastedGraphic-1](https://user-images.githubusercontent.com/2893302/174298442-a4bf38f3-c2f1-4314-ae73-4005c270cff1.png)

**Comment by johngodley** [comment]
That's not a page the plugin displays, and there should be a lot more information. If you open your browser's developer console it may show more information. It's also possible that you have another plugin or browser extension running that is breaking the plugin.

**Comment by yondershore** [comment]
I click on redirection on the tools tab and this is the screen I get. I have switched themes and turned off plugins. 

I’ll try more things.
