### ISSUE TITLE
Using Pipe in Redirect for Tab links

### ISSUE THREAD

**Issue by GlenAllan888** [johngodley/redirection#3320]
So I found a solution to have a link that opens a specific tab in a page in Wordpress, and it uses a vertical bar/Pipe "|" to assign the particular tab to open using the link. Your plugin strips the Pipe out of the URL, making the URL ineffective.

The way you do it is assign a CSS id to the tab module, then on reload of the saved page the URL for the specific tab show up as an anchor link, formatted like this: https://www.website.com/support/#support-tab|5

How do I keep Redirection from stripping that character out of the URL so I can actually redirect to the actual tab? It's a built in WP function to add the Pipe to the URL, so for WP this is obviously not an illegal character, even though your plugin thinks it is.

**Comment by GlenAllan888** [comment]
Here, I'll leave a real link so you can see it works.... Also, click on any other tab to see the URL change to the different tabs using the same format. It's built in to WP when you add the CSS ID to the module. No coding hacks at all.

https://www.bassboss.com/support/#support-tab|3

**Comment by GlenAllan888** [comment]
Apparently you'll have to copy that as text, as it gets stripped out as a clickable link here. But I have tested it in internal links in WP and it works perfectly.

**Comment by johngodley** [comment]
The pipe support is something specific to your theme or a plugin on your site, not to WordPress. It is WordPress itself that removes the pipe character, not the plugin.

**Comment by GlenAllan888** [comment]
No, I did not add anything other than the CSS ID. It automatically added the function without any code.

Here is another site: https://wordpress-562251-1810889.cloudwaysapps.com/blob/#Tabs-here|2

Your plugin says it is invalid
<img width="543" alt="Screen Shot 2022-06-16 at 11 43 19 PM" src="https://user-images.githubusercontent.com/37121971/174240963-4de6a8bf-0dcd-4413-9c90-4b72f94f4b7d.png">

Are you saying this isn't your plugin deciding this?

**Comment by johngodley** [comment]
Sure, that is another site with the same theme.

The plugin is showing you a warning, it is not deciding anything. WordPress itself does not allow the pipe, and the plugin is warning you about that.

**Comment by GlenAllan888** [comment]
So there theme allows it, and enables its use, but the plugin displays the WP warning of it being invalid. And it cannot ignore it? That's what I'm asking since it does work internally.

**Comment by GlenAllan888** [comment]
Can you allow the plugin to ignore the warning since it does work? I guess the question is will you, since that requires work. So maybe not?

**Comment by GlenAllan888** [comment]
It is the most used theme in WP anywhere. Divi.

**Comment by johngodley** [comment]
The message is just a warning. The plugin isn't removing anything and isn't preventing you from using it. The plugin doesn't really care what you put there.

WordPress removes the pipe when you redirect. There is nothing that can be added to the plugin to work around this, and the only way to change this it is by editing some core WP files.

The warning is shown to try and prevent people blaming the plugin when they enter a URL and it doesn't work.

**Comment by GlenAllan888** [comment]
I see... So there theme allows it in its own modules, but WP itself will not. Okay... Well that's highly annoying. Guess I'll open a ticket with Elegant Themes about it. Not that they are small enough anymore to care about such things, but who knows. I'd bet too many people use it for normal linking for them to change the behaviour.

**Comment by johngodley** [comment]
It's not really the theme allowing it but WP doesn't. WP is only preventing the pipe in a redirect. It's not preventing it on a page view. Maybe the theme provider could support another character as well as the pipe.

It may be better to have proper pages for the different tabs and then it will help your SEO and remove this problem.

**Comment by GlenAllan888** [comment]
I thought that as well, but getting them to do anything will be difficult. Also the way tabs work is not to be as different pages, and we are inserting the page content per tab is using shortcodes as well. Not that that is unusual, but it's how you get around the tabs not being pages. What would really help is if each tab could at least have a separate CSS ID. I might be able to find a different solution.

Thanks for clearing up the issue though.

**Comment by GlenAllan888** [comment]
For anyone else who may have this issue (not sure why it's not a big thing already really).

Seems it’s part of the wp_sanitize_redirect core function to remove the “|” from URLs on redirect calls, thus making using these anchor links in redirects impossible. 

It does work everywhere else in WP however. In Divi anywhere, in the Block editor, and in the Classic editor. No issue. It's just a problem in redirects. It doesn't work in this plugin (Redirection), Yoast Redirects, or WPSearch, all as redirects.

I've reached out to Elegant Themes, we'll see what they say. if anything useful come up I'll add a response here. Otherwise that's what you have to deal with.
