### ISSUE TITLE
Unable to ignore query strings when using regexp redirections

### ISSUE THREAD

**Issue by rbairwell** [johngodley/redirection#3331]
### Summary

I am trying to setup a redirect using a regular expression similar to:

> **Source** URL: ^/reviews.*    **[Regex]**
> **Match:** URL only
> **When matched:** Redirect to URL
> **with HTTP code:** 301-Moved Permanently
> **Target URL:** https://example.com/what-do-i-think/
> **Group:** MyApache

The group "MyApache" is setup using the "Apache" module.

I expect any URL starting with "reviews "to go to exactly to the "what-do-i-think" page URL with nothing else set (if I wanted a query string set, I would have set it in the direct).

### Actual Behavior

When a user goes to:
`https://example.com/reviews-was-the-goonies-a-good-movie?vote=yes
`they are redirected to:
`https://example.com/what-do-i-think/?vote=yes
`

## Wanted Behavior

When a user goes to:
`https://example.com/reviews-was-the-goonies-a-good-movie?vote=yes
`they are redirected to:
`https://example.com/what-do-i-think/
`

## Requested Change
An option on regular expressions to ignore query strings:

For example, with Apache redirects to add the ["query string discard](https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_qsd)" flag "QSD"  to the RewriteRule (Apache's default is "query string append" aka QSA).

(Just worth noting that the QSD flag is only available in Apache 2.4 or later - so since 21st of February 2012 - over 10 years ago!)

### Environment

**Redirection plugin: version:** 5.2.3
**WordPress version:** 6.0
**Browser:** Brave 100.x Chromium based (not relevant)
**Apache version:** 2.4.54

**Comment by johngodley** [comment]
Have you tried this using a WP redirect? Exporting to Apache is not perfect and some features are missing.

**Comment by rbairwell** [comment]
Hi @johngodley ,

Thanks - that does seem to have worked. I don't know why it didn't occur to me to try that first. It'll be good to keep the redirects in Apache .htaccess if possible though as it'll be slightly faster.

Feel free to close this issue for now if you want, or leave it open to track the feature enhancement 😄 .

Many thanks!
