### ISSUE TITLE
Redirection between subdomain and domain

### ISSUE THREAD

**Issue by whyhelper** [johngodley/redirection#3334]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### I can't redirect

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### I'm trying to redirect a page in the subdomain to a page in the main domain.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### It keeps opening the normal page without redirection

Explain the steps involved to reproduce the problem

### I tried to redirect this page: https://files.minecraftshader.com/dl/tea
For this page: https://minecraftshader.com/downloads/tea

Settings: https://prnt.sc/AUg6D2cCQbXh

Please list your browser, browser version, version of WordPress and Redirection plugin.

Google Chrome, Version 103.0.5060.66 (Official Version) 64-bit, Wordpress and plugin updated to the latest version.

**Comment by johngodley** [comment]
You have created a URL and server redirect. However, your subdomain appears to be on a different server. You can only redirect domains that are served by Redirection

**Comment by whyhelper** [comment]
how can i redirect this page then please?

**Comment by johngodley** [comment]
https://redirection.me/support/redirecting-another-site/

**Comment by whyhelper** [comment]
so I must install wordpress on this website and install the vcs plugin to redirect

**Comment by johngodley** [comment]
I don't know what vcs is, but Redirection can only redirect things it has control over. The support page has the different options you can use and you'll need to use whichever one makes the most sense for your setup.

**Comment by johngodley** [comment]
Closing for now please reopen with more information.
