### ISSUE TITLE
How to redirect pages from a Subdomain (Blog.PsychTimes.com) to the main domain (PsychTimes.com)

### ISSUE THREAD

**Issue by Psych1111** [johngodley/redirection#3336]
Hi, I'm trying to move 100+ articles from my subdomain Blog.PsychTimes.com over to my main domain PsychTimes.com. I tried to do this using the redirect plugin, but it is not working. 

Does anyone know how I can accomplish this?

![Screenshot (100)](https://user-images.githubusercontent.com/108680898/177174151-2b345ed6-2b8f-4ce8-88f6-d2a387b84baa.png)

**Comment by johngodley** [comment]
Please read this page about external domains  https://redirection.me/support/redirecting-another-site/

**Comment by Psych1111** [comment]
Thanks so much!
