### ISSUE TITLE
No redirecciona

### ISSUE THREAD

**Issue by Jmarangito** [johngodley/redirection#3339]
No redirecciona el siguiente link: https://www.servir.gob.pe/servir-implementa-nuevo-sistema-de-reserva-de-citas-para-atender-consultas-laborales-de-la-ciudadania/ a https://www.gob.pe/institucion/servir/noticias/629880-servir-implementa-sistema-de-citas-virtuales-para-atencion-de-consultas-laborales

![image](https://user-images.githubusercontent.com/108896144/177844743-14966513-c818-4262-90c8-b881385c33ff.png)

**Comment by johngodley** [comment]
You can find details here:

https://redirection.me/support/problems/url-not-redirecting/
https://redirection.me/support/problems/redirect-returning-404/

**Comment by johngodley** [comment]
Closing for now please reopen with more information.
