### ISSUE TITLE
Redirection Plugin: Image 301 redirects not working

### ISSUE THREAD

**Issue by Mellyod** [johngodley/redirection#3340]
Often times I have to replace an image in a page or post. Therefore, so that I don't loose any SEO links attached to the original image, I set up a 301 redirect for the image. About 20% of the time the redirect works. The other 80% of the time the redirect does not work resulting in a 404.

I need to be able to redirect a jpg/png image URL to a different jpg/png URL.

Currently, I go to "Redirects" tab and at the bottom of the page I use the "Add new redirection" feature and where it says "Source URL", I input the old jpg/png URL. To the right of that, I keep the default "Ignore Case" "Ignore Slash". At "Query Parameters", I  keep the default "Ignore & pass parameters to the target". Then for "Target URL", I input the new jpg/png URL (which I double check via the Media Library). For "Group", I keep the default "Redirections". Then I click on "Add Redirect". Unfortunately though, after I create the redirect, I click on "Check Redirect", and like I said, 80% of the time I get a 404 message.

I have tried switching up all the default settings, I have tried using both relative and absolute URLs, and I have cleared the cache, but still, the redirect does not work and I get a 404 message 80% of the time.

I always use the most recent version of WordPress (currently 6.0) and I always update the Redirection Plugin to the most recent version (currently 5.2.3) via the WP Admin Dashboard always using the most recent version of Mozilla Firefox browser (currently 102.0 64-Bit) via a Microsoft Windows 10 desktop computer.

My website URL is https://collectiblesandmoreinstore.com and here are several of the screenprints and 404 messages I receive:

![image-redirect-404-example1](https://user-images.githubusercontent.com/39532810/177845086-31209030-fd85-4992-b627-002f621d3524.jpg)
![image-redirect-404-example2](https://user-images.githubusercontent.com/39532810/177845126-c5d81027-8eb8-4922-ab0d-84755c1dfdc0.jpg)
![image-404s](https://user-images.githubusercontent.com/39532810/177845158-1be0278c-16d6-4861-bd54-66b42dc2ee71.jpg)

Please can you help me so that my images get redirected correctly? Thank you for your time. I appreciate you!

**Comment by johngodley** [comment]
I couldn't say. Again it's down to your server. The pages above should contain enough information.

**Comment by Mellyod** [comment]
I contact my hosting provider, A2 Hosting, and they said it is an issue with the plugin. Please read their response email in the attached image
![redirection-img-404-a2hosting-response](https://user-images.githubusercontent.com/39532810/177888382-02c72172-b6c4-4eb8-8761-af94efa6b942.jpg)
.

**Comment by johngodley** [comment]
They haven't said it's an issue with the plugin. The have agreed it is the issue I referenced above. Specifically:

> Server Configuration
> If your URL is a file then your web server may be configured to handle it directly rather than pass the request through to PHP and WordPress.
> 
> This means that Redirection could be unable to redirect it. For example, a URL that ends with .pdf, .html, .doc, .png, .jpg, .php, .mp3, .zip, .aspx etc.
> 
> Solutions:
> 
> Delete the file from your server. If the file exists then it may prevent any redirects.
> [Save the redirect to Apache](https://redirection.me/support/import-export-redirects/) .htaccess or as Nginx rewrite rules.

And

> The source URL is returning a 404
> You’ve created a redirect on /old-url and the redirect checker is showing that this is returning a 404. There are many reasons for this and they are detailed in the [URL is not redirecting](https://redirection.me/support/problems/url-not-redirecting/) guide.
> 
> Sometimes your server can return a 404, not WordPress. You can tell this because the 404 page has no style and does not match your WordPress theme.
> 
> 
> When this happens then you will need to reconfigure your server to pass 404s through to WordPress. This is not something that Redirection can do. If you are unsure how to do this then contact your hosting provider.

You will need to resolve it using the instructions.

**Comment by johngodley** [comment]
Closing for now please reopen with more information.
