### ISSUE TITLE
Suggestions for UI improvements

### ISSUE THREAD

**Issue by steve6375** [johngodley/redirection#3342]
**Summary**
First let me say how great this plugin is - thank you very much!
The main issue I had/have is that the tabs are not clear for newbies and idiots! 
I was very confused when first trying to use this plugin.
Mainly because of the tab headings.

**Actual Behaviour**

The tabs at the moment are
**Redirects | Groups | Site | Log | 404s | Import/Export | Options | Support**  

but they are rather confusing.
Redirects - could mean it shows a list of all redirects that have occurred??
Log - could mean a log of all attempted website accesses (not just redirected urls)???
404s - For idiots like me, what this really mean is  'log the pages which gave a 'page not found' error to the user'

**Suggestion**
May I respectfully suggest the following headings which would be far less confusing:

**Set redirects | Groups | Site | Redirect log | Failed redirects | Import/Export | Options | Support**

Thanks!

**Comment by johngodley** [comment]
Thanks for the suggestion. I don't think this particularly helps clarify things, and the new titles aren't fully accurate, so for the moment I'm going to keep using the existing titles.

**Comment by steve6375** [comment]
OK - I realise now my suggested titles were not fully accurate!
I think I have got used to it now. Really useful - thanks.
