### ISSUE TITLE
Problems deleting 404s and Log entries

### ISSUE THREAD

**Issue by steve6375** [johngodley/redirection#3343]
**Summary**
Deleting all entries seems strange.
Also doesn't seem to update with new entries until I delete all old entries.

Behaviour may be affected by number of number of items per page, so I set Screen Options to 50 log entries.
Time to keep logs = 1 week.

I select all 404s entries (or Log entries) - wait 5 minutes to allow for more 404s or log entries (which dont appear) - then click Bulk Delete - Apply -> all entries disappear (or new entries made in last 5 minutes are now listed). Now click Date column heading to re-order -> nothing is listed  (new entries in last 5 mins, if there were any, have disappeared!).

![image](https://user-images.githubusercontent.com/1469350/178137551-b38c9aed-25ee-43b5-9ad7-f8a6f36f4d56.png)

 Now click Date column header again and the old entries now appear!

![image](https://user-images.githubusercontent.com/1469350/178137588-387764be-d6ca-4135-a66c-dd6f1381e2f3.png)

 Now click Date column header again and no entries.
![image](https://user-images.githubusercontent.com/1469350/178137616-a2cb4a8d-5877-4065-b551-92b98c73b2b9.png)

P.S. How often do logs/404s refresh/update?  Is there a Refresh button anywhere to update Logs and 404s  before bulk action?

### Environment

Chrome, Win10 x64, WP 5.9.3,  current version Redirection

**Comment by steve6375** [comment]
Demo of old results re-appearing after deletion

https://user-images.githubusercontent.com/1469350/178253011-7393eaad-7bfa-4b5f-a120-324853efec55.mp4

**Comment by steve6375** [comment]
Would any site caching cause this behaviour. If I wait a while (10/30/60 mins???) and then click on 404s tab - I get latest results.

**Comment by johngodley** [comment]
> Would any site caching cause this behaviour

Possibly, but that's something you will know about as you control the site. The plugin does not cache this data.

I am unable to reproduce the problem so it does seems specific to your site.

Why do you keep pressing on the date column? If you want new entries you can just reload the page.

**Comment by steve6375** [comment]
reloading the page just shows old list.
I can do a block delete of 404s - then click on Log tab - then click on 404s tab ... and old (deleted) list now appears!

**Comment by johngodley** [comment]
Ok, then I would investigate your site caching and try disabling or clearing it

**Comment by johngodley** [comment]
I don't know. The plugin uses the standard WordPress REST API. Maybe that is being cached on your site when it shouldnt be? There may be settings you can configure in the cache software

**Comment by steve6375** [comment]
Ok, I have another quick Q. I really dont want bad URLs going to a 404 error page. I would prefer unhandled 404s to go to the home page or the site map page. However, if I add a general 404 redirect plugin, your 404s log does not log anytht. Is there an option to send all 404 errors to a default page in your plugin?

**Comment by johngodley** [comment]
No, the plugin does not support that option as it's not a good thing to do. A page that does not exist should return a 404. A page that has moved should be redirected.

Redirecting a page that does not exist to the home page makes no sense and is likely detrimental to your site. You can use a 410 to remove pages that no longer exist.

**Comment by johngodley** [comment]
A 301 is a permanent redirect. Using that for a temporary situation is not a good thing to do. It would be better just to let them return a 404. A 404 is not a bad thing.

No, it's not possible to detect if the data is cached. Your caching plugin shouldn't really cache things on the REST API as it will affect every plugin, not just Redirection.

**Comment by steve6375** [comment]
LiteSpeed Cache plugin has a setting to cache REST - it is set to enable by default. Disabling it fixed the issues.
Maybe you could warn people as it is quite a popular plugin?

**Comment by johngodley** [comment]
Sure. The problem is that there are many caching plugins and detecting them all is quite an overhead. It would be nice if a plugin didn't break things for people, and didn't require every single other plugin that uses the REST API to incorporate warnings and workarounds.

I've made a note of LiteSpeed on the support site https://redirection.me/support/problems/data-is-not-saved/

**Comment by steve6375** [comment]
Maybe as a 'on load' test, make a REST API call to get data, then delete a piece of data (some inconsequential bit?), then repeat the same REST API request again - if the same data is returned then you know caching is on and you can warn the user that REST API cache is enabled somewhere on the site?
OR, if the user deletes an entry or multiple entries from the Log or 404s form and you repeat the API to get new data for the form, if the new data is the same as it was before, you know REST API caching is enabled?
