### ISSUE TITLE
HTTP Code column sort in Logs page gives error

### ISSUE THREAD

**Issue by steve6375** [johngodley/redirection#3344]
in Logs view - Display all: clicking on HTTP Code column header gives 'error'
![image](https://user-images.githubusercontent.com/1469350/178138132-9d792090-a405-488e-b701-9e0324e5fef2.png)

Plugin: 5.2.3 4.2
WordPress: 5.9.3 (single)
PHP: 7.4.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
JavaScript: https://rmprepusb.com/wp-content/plugins/redirection/redirection.js?ver=5.2.3-cb109e7c800603ff2d5cc098451320be
REST API: https://rmprepusb.com/wp-json/
Query: ?page=redirection.php&sub=log&orderby=code&direction=asc

Error: Invalid parameter(s): orderby (rest_invalid_param)
Raw: {"code":"rest_invalid_param","message":"Invalid parameter(s): orderby","data":{"status":400,"params":{"orderby":"orderby is not one of url, ip, total, count and ."},"details":{"orderby":{"code":"rest_not_in_enum","message":"orderby is not one of url, ip, total, count and .","data":null}}}}

**Comment by johngodley** [comment]
Yep, this is covered by https://github.com/johngodley/redirection/releases/tag/5.3-beta
