### ISSUE TITLE
redirect help

### ISSUE THREAD

**Issue by columbian-chris** [johngodley/redirection#3347]
I have a redirection entry that is causing me a headache and I'm hoping maybe someone can help.

I have a ton of old links in my site that are indexed in search engines that I'm trying to implement a 301 for that are all based with a redundant extra "news" like this:

`https://www.example.com/news/news/hello-world/`

I'm trying to redirect them to (removing the redundant "news"):

`https://www.example.com/news/hello-world/`

I am using a regex entry like this that for 99% of URL's works perfectly:

Source: `^/news/news/*`
Target: `/news/$1`

There are a couple one-offs that are redirecting badly (to confirm this, they don't happen when I disable the Redirection plugin).  Here is one:

Visiting the URL `https://www.example.com/news/newsletter/` redirects to `https://www.example.com/news/letter/` (I wasn't expecting a redirection to fire at all).

Is there a better approach than the one I'm using to prevent this bad redirect from happening?

**Comment by johngodley** [comment]
`^/news/news/*` is not a valid regular expression, and I'm surprised anything is working at all. It may not even be Redirection that is handling your URLs.

At the very least it should be something like `^/news/news/(.*)`

**Comment by columbian-chris** [comment]
Oh my gosh, me too.  Thanks for the quick help; that of course worked fine.
