### ISSUE TITLE
Redirection not working anymore

### ISSUE THREAD

**Issue by Yuzan55** [johngodley/redirection#335]
Hi, 
Sorry for disturbing. 
I try to update the plugin but it's not working anymore. I have a message saying : 

Something went wrong 🙁

Redirection is not working. Try clearing your browser cache and reloading this page.
If that doesn't help, open your browser's error console and create a new issue with the details.
Please mention options, and explain what you were doing at the time
*Please replace this template with your own details!*

In the console it's written : /wp-admin/tools.php?page=redirection.php&sub=options:471 Uncaught TypeError: Cannot read property 'style' of null 

I cleared the cache, changed the navigator, etc... Nothing is working. 

Please help me.

**Comment by johngodley** [comment]
What browser are you using?

**Comment by Yuzan55** [comment]
I tried with Chrome and Firefox

**Comment by Yuzan55** [comment]
Also with Opera

**Comment by johngodley** [comment]
Is it possible to get a login to your site to try and debug the problem? If so, please contact me through the contact form on my website (click my avatar)

**Comment by Yuzan55** [comment]
Hi John, 

It was a problem with the cache. Now it's okay ! :) Thank for your quick reply ;) Have a good WE !

**Comment by johngodley** [comment]
Great, glad it works. In case anyone else has the same problem, was it the browser cache, or something like Cloudflare etc?

**Comment by Yuzan55** [comment]
I went to OVH CDN and did clear cache. I also completly remove the browser cache (not the last 24th hours as I firstly did) and now it's working :)
