### ISSUE TITLE
Can't export on multiple sites

### ISSUE THREAD

**Issue by LoboCreative** [johngodley/redirection#3354]
### Summary

Can't export the redirects as any file type.

### Actual Behavior

Tried to export redirects, but nothing is happening. Tried this on 4 different wordpress websites. All plugins and websites are fully up to date.

### Steps to reproduce

Try and export.

### Environment

Chrome, Desktop, fully up to date products.

**Comment by johngodley** [comment]
What are you exporting and how? What do you mean by nothing happens? Do you have other plugins or browser extensions running that could cause problems?

**Comment by LoboCreative** [comment]
Export "everything" in all file format available.

Nothing happens. I click export, and nothing happens.
I have lots of plugins and browser extensions.

Many thanks,

The Support Team
at Lobo Creative

+44 (0) 1202 065 760
lobocreative.studio (https://www.lobocreative.studio)

This email may be confidential or privileged.
Please act responsibly.

**Comment by johngodley** [comment]
Are you viewing the export or downloading it?

Could any of those plugins or extensions be blocking the export? No one else is reporting any problems exporting so it seems likely this is specific to your site or browser.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
