### ISSUE TITLE
Unknown Column 'match_data'

### ISSUE THREAD

**Issue by TaoWallop** [johngodley/redirection#3355]
Try to import a new CSV into the Redirection plugin for a newly published website. Even try to import an exported CSV from the last version of the website into the new website. Both imports fail. Debug log shows "WordPress database error Unknown column 'match_data' in 'field list' for query INSERT INTO `wp_redirection_items`" for each row. Open phpMyAdmin and find the column 'match_data' is not in `wp_redirection_items' table.

WordPress: 5.9.1
Redirection: 5.2.3
Exported CSV from old site: [exported-old.csv](https://github.com/johngodley/redirection/files/9143240/exported-old.csv)
Database Table Screenshot: <img width="1011" alt="Screen Shot 2022-07-19 at 10 09 57" src="https://user-images.githubusercontent.com/45243595/179809548-eb1eba0b-5e74-48e6-86e7-859703599d4d.png">

**Comment by johngodley** [comment]
Go to the support page in the plugin, change the database version to 2.4, and follow the instructions.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
