### ISSUE TITLE
Fail status on all existing redirects

### ISSUE THREAD

**Issue by Archie22is** [johngodley/redirection#3360]
### Issue: Redirect plugin gives a "Fail" status on redirects that used to work.

Hello everyone.

I have some serious issues with a project. The IT person from the client’s side has locked everything up to a point where updates are deployed via git and nothing can breathe. I think the htaccess also doesn’t work as it should and I installed the Redirection plugin to redirect pages. It worked briefly for a few months until this morning when I ran a scan.

The error I’m getting looks like this: https://prnt.sc/gzB4XyY4T4Dl

Is there anything I can do to resolve the issue without fighting with the IT guy over permissions and server config? I understand that the redirects can work without htaccess.

**Comment by johngodley** [comment]
I can't see all the details but the message indicates the check failed. This does not indicate the redirect has stopped working, just that the checker can't check the URL.

This doesn't really have anything to do with the plugin, or htaccess, and probably indicates some security change on your server.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
