### ISSUE TITLE
fix Url with accents

### ISSUE THREAD

**Issue by mvneobux** [johngodley/redirection#3368]
My redirects are to url with accents and when I export to apache .htaccess format, they look like this:

```
<IfModule mod_rewrite.c>

RewriteRule ^Materias/Post/57173$ https://www.saraivaconteudo.com.br/blog/materias/dez-romancistas-feministas-importantes-na-hist%C3%B3ria-da-literatura/ [R=301,L]
RewriteRule ^Noticias/Post/45006$ https://www.saraivaconteudo.com.br/blog/noticias/ivete-vai-gravar-cd-com-m%C3%BAsicas-da-trilha-do-cabar%C3%A9-da-novela-gabriela/ [R=301,L]
RewriteRule ^Noticias/Post/51313$ https://www.saraivaconteudo.com.br/blog/noticias/v%C3%B3-holandesa-de-z%C3%A9-carioca-chega-ao-brasil/ [R=301,L]
RewriteRule ^Materias/Post/56180$ https://www.saraivaconteudo.com.br/blog/materias/a-import%C3%A2ncia-da-cole%C3%A7%C3%A3o-vaga-lume-na-forma%C3%A7%C3%A3o-de-novos-leitores/ [R=301,L]

</IfModule>
```

As expected the redirect does not work as it lands on a 404 page. How to solve this?

**Comment by johngodley** [comment]
What part isn't working? The URLs seem to work fine.

**Comment by mvneobux** [comment]
> What part isn't working? The URLs seem to work fine.

my destination urls have accents. In the plugin, when I add them they keep the accents, but in htacces or when I export to htaccess the accents are converted into strange characters. For example this would be a landing page:
  https://www.saraivaconteudo.com.br/blog/materias/a-import%C3%A2ncia-da-cole%C3%A7%C3%A3o-vaga-lume-na-forma%C3%A7%C3% A3o-of-new-readers/

But the trailer url looks like this:

https://www.saraivaconteudo.com.br/blog/materias/a-importância-da-coleção-vaga-lume-na-forma-de-novos-leitores/

That is, it redirects to the wrong landing page and returns a 404 error, as it does not match the urls with accents.

How do I resolve this?

**Comment by mvneobux** [comment]
But if you test through the github app itself, you'll notice that it works, but this happens because it treats the url as utf8 , so even with the accents converted into codes, they will open correctly. But this doesn't work on most browsers or websites to test redirects. And I believe that google may not understand too, because in the web search console when I try to inspect the url, it does not understand and does not convert to url with accents

**Comment by johngodley** [comment]
What Github app? What is a trailer URL? What is the source URL for one of these?

**Comment by mvneobux** [comment]
Sorry for any mistakes, but I'm using translator.

the source url for the example I gave you is this: 
www.saraivaconteudo.com.br/Materias/Post/56180

Which in my htaccess looks like this:

`
<IfModule mod_rewrite.c>

RewriteRule ^Materias/Post/56180$ https://www.saraivaconteudo.com.br/blog/materias/a-import%C3%A2ncia-da-cole%C3%A7%C3%A3o-vaga-lume-na-forma%C3%A7%C3%A3o-de-novos-leitores/ [R=301,L]

</IfModule>

`
It ends up on page 404 when I access the browser or even when I use some tool to test the redirect

**Comment by mvneobux** [comment]
did you get it ??

**Comment by mvneobux** [comment]
A summary:

**Origin link:** http://www.saraivaconteudo.com.br/Materias/Post/56180

**destination link:** https://www.saraivaconteudo.com.br/blog/materias/a-importância-da-coleção-vaga-lume-na-formação-de-novos-leitores/

But in htaccess the plugin adds the destination link like this: https://www.saraivaconteudo.com.br/blog/materias/a-import%C3%A2ncia-da-cole%C3%A7%C3%A3o-vaga-lume-na-forma%C3%A7%C3%A3o-de-novos-leitores/

As a result, the redirect does not work. I need the plugin to add it in htaccess exactly as I put it in the plugin, that is, with the accents, in utf8 format.

help me solve this please

**Comment by johngodley** [comment]
Yes, I have read your information. I am not able to instantly look further and some patience is required.

**Comment by mvneobux** [comment]
> Yes, I have read your information. I am not able to instantly look further and some patience is required.

OK thank you. I'm waiting

**Comment by johngodley** [comment]
The encoding is correct, but it was missing a flag. This is now in version 5.3.1

**Comment by mvneobux** [comment]
I updated but it didn't solve the problem:

in plugin: 
https://prnt.sc/PjwFQusNQB6R

in htaccess:

https://prnt.sc/wbaSGyfoKyu3

Can you help me ?

**Comment by johngodley** [comment]
Yes, the encoding is correct. However I don't think you are using the updated version.

**Comment by mvneobux** [comment]
I'm using the updated version, cleared cache, deactivated and reactivated the plugin and it still doesn't work for me, see:

https://prnt.sc/GUmMeX4RdW02

plugin version:

https://prnt.sc/bQ1BefGrzAH4

**Comment by johngodley** [comment]
Have you updated the .htaccess file?

**Comment by mvneobux** [comment]
Yea! I also cleaned everything that was there, put a new htaccess path in the plugin settings and still it keeps saving the urls with wrong accents.

Even if I go to export in the plugin, it generates the wrong file too, see:

https://prnt.sc/Ciqc4AUHAihc

**Comment by johngodley** [comment]
As I've said, the accents are correct. You should see `NE` at the end:

```
<IfModule mod_rewrite.c>
RewriteRule ^x$ https://www.saraivaconteudo.com.br/blog/materias/a-import%C3%A2ncia-da-cole%C3%A7%C3%A3o-vaga-lume-na-forma%C3%A7%C3%A3o-de-novos-leitores/ [R=301,L,NE]
</IfModule>
```

**Comment by mvneobux** [comment]
It's still not working buddy.

First, I had to remove and re-install the plugin to insert the flag. But the flag it is including is NC, see: 

https://prnt.sc/Palul_bY-Fjq

I entered htaccess and put NE, and when I test the redirect in the plugin it returns that it was redirected:

https://prnt.sc/pQO1EcbUIaVm

But when I try to enter the test url through the browser, which would be https://www.saraivaconteudo.com.br/aaaa , I get a 404 error:

https://prnt.sc/ozLqXXnbKaBt

**Comment by mvneobux** [comment]
even if the NE flag returns status 200, it doesn't seem valid, because if someone enters the url of origin it will fall on a broken and non-existent page in the same way. In addition, google may not understand the content of the page and not attribute relevance (SEO) in the redirect.

**Comment by johngodley** [comment]
> But when I try to enter the test url through the browser, which would be https://www.saraivaconteudo.com.br/aaaa , I get a 404 error:

You need to clear your browser cache. The redirect is working fine.

> even if the NE flag returns status 200, it doesn't seem valid, because if someone enters the url of origin it will fall on a broken and non-existent page in the same way. In addition, google may not understand the content of the page and not attribute relevance (SEO) in the redirect.

Google understands it fine because it is correct as shown by the redirect checker.

**Comment by mvneobux** [comment]
But it adds the "NC" flag and not "NE", when I manually put NE and clear the cache it really works, but the plugin is adding "NC" and it doesn't work:

https://prnt.sc/omoh05SWXMZM

And there was another problem after the update. I added the htaccess path but the plugin is not adding the redirects to it:

https://prnt.sc/qaSHnvmgMFBx

the path is correct but it doesn't add the redirects in the .htaccess

**Comment by johngodley** [comment]
Nothing has changed with regards to saving to a .htaccess file.

`NC` is another flag. I don't know why you are not seeing `NE`, and I am unable to not get it to appear. However, based on your problem with saving I suspect that this is a problem local to your site (maybe permissions).

**Comment by mvneobux** [comment]
Friend, today I had a time and decided to delete everything. I deleted the database, installed wordpress and redid everything. And the same is happening. It keeps adding the NC flag instead of NE, and my htaccess path the plugin is not recognizing. Since I already checked with the server and the path has all permissions.

And reinforcement in saying that the htaccess path was working perfectly, until I upgraded to the version that should add the NE flag, but adds NC. Since then the htaccess path stopped working and the plugin keeps adding the NC flag

**Comment by mvneobux** [comment]
Another detail, when I put the htaccss path, the date of last modification of the htaccess file is updated. But the plugin does not insert the redirection lines, I tried with htaccess files in other folders and the same thing happens.

**Comment by johngodley** [comment]
> But the plugin does not insert the redirection lines

First you say it does add the lines and then you say it doesn't add the lines. Is the plugin updating the file?

**Comment by mvneobux** [comment]
I didn't understand what you meant.

But simulate what I said and see for yourself.

when I put the htaccess directory in the plugin, it has the updated modification date, but it doesn't include the apache redirect lines.


besides, it insists on putting the NC flag instead of NE... and this happens on all sites, on different servers.

take a test and see for yourself

**Comment by johngodley** [comment]
Here you say it is saving:

> It keeps adding the NC flag instead of NE

Here you say it isn't saving:

> But the plugin does not insert the redirection lines

Is it saving or is it not saving?

> take a test and see for yourself

I am not able to reproduce the problem and it always works. This leads to me think that yours is not saving.

**Comment by mvneobux** [comment]
> It keeps adding the NC flag instead of NE

I can only see because I go to "export" and then click "VIEW" to see how the redirect was saved. And there the NC flag appears and not NE

But in the htaccess defined in the settings it is not saving and including the lines. The strange thing is that the modification date of the .htaccess file is changed, but the lines are not inserted.

**Comment by johngodley** [comment]
Can you export your redirect as JSON and upload it here? I am unable to reproduce
