### ISSUE TITLE
Doesnt Show All Redirects

### ISSUE THREAD

**Issue by caiohsamaral** [johngodley/redirection#337]
### Summary

Im trying to see all my redirects but it doesnt show all of them, just a little percentage. 

### Actual Behavior

It should show all of my redirects, because I want to manage them all.

### Steps to reproduce

Just simply enter in the redirects section and it isn't showing all of them. 

### Environment

Google Chrome 60.0.3112.101, Wordpress 4.7.5, Redirection Plugin: 2.7.1

**Comment by johngodley** [comment]
Do you have the paging buttons to move between pages? It only shows 25 items by default

**Comment by caiohsamaral** [comment]
Yes. And it just show 2 pages. But I had more than 1000 itens. If a search for them, they appear. But not in "all redirects" list, without searching

Enviado do meu iPhone

Em 26 de ago de 2017, às 11:03, John <notifications@github.com<mailto:notifications@github.com>> escreveu:


Do you have the paging buttons to move between pages? It only shows 25 items by default

**Comment by johngodley** [comment]
Can you show a screenshot of the page you are looking at?

**Comment by caiohsamaral** [comment]
The main screen.


But I've already resolved by my self.


Looks like the maximum results per page was limited to 200 and before I could use until 999.


Then when I changed to 200, the plugin "recalculated" my pages and all results were shown.


Best regards

________________________________
De: John <notifications@github.com>
Enviado: sábado, 26 de agosto de 2017 11:27:23
Para: johngodley/redirection
Cc: Caio Amaral; Author
Assunto: Re: [johngodley/redirection] Doesnt Show All Redirects (#337)


Can you show a screenshot of the page you are looking at?
