### ISSUE TITLE
Two redirections aren't working.

### ISSUE THREAD

**Issue by Marly132** [johngodley/redirection#3376]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

My redirection is not working on two pages. when they click sign in on menu, it should take them to the login screen. Then when they login they should be redirected to the the student dashboard. These two aren't working with the last update to the redirection plugin in I did on Friday. 

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

When I click sign in, it says, you are already signed it, but I am not. The login page never appears. When I finally am at the login page, I put in the credentials, and the submit button doesn't activate. I have to refresh the screen in order to get to the dashboard. 

Explain what actually happened. If suggesting a new feature then explain what currently happens.

I tried to locate the redirections but they seemed to disappear along with the new format on the redirection page. 
If you can tell me how to undo the latest
![login page](https://user-images.githubusercontent.com/110402819/182164131-a67b5e27-6193-493c-ba85-57ebfada0e31.png)
 update, I think that will solve my problem. 
(I can't attach the sign in button, but here is the link - https://cedaron.flywheelstaging.com/login

Please list your browser, browser version, version of WordPress and Redirection plugin.
Edge, Version 103.0.1264.77 (Official build) (64-bit), Wordpress 6.0.1,
Redirections Plugin -Version 5.3.1 | By John Godley | [View details](http://cedaron.flywheelstaging.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=redirection&TB_iframe=true&width=600&height=550)

**Comment by johngodley** [comment]
I don't really understand what the question is here. What URL isn't redirecting, and what redirect have you created for it?

> I tried to locate the redirections but they seemed to disappear along with the new format on the redirection page.

The latest update will not have changed any of your redirects.

**Comment by Marly132** [comment]
Hi, it will be easier to explain if I can set up a quick zoom with you so I can physically show you what is going wrong. Or if you can give me the steps to uninstall the latest update (that's when these problems occurred). That will work as well.

**Comment by johngodley** [comment]
A zoom is not something I do. It shouldn't be too difficult to show the URL and settings for the redirect.

I do not think this is related to the latest update. All older versions are available on the plugin page.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
