### ISSUE TITLE
404 error no matter what I try

### ISSUE THREAD

**Issue by ChristopherBurns11** [johngodley/redirection#3380]
**### Summary**
I've used redirection for about half a dozen sites in the past and it always worked as intended. For some reason when attempting to use on LeonaSchrock.com it's not working, I keep getting a 404 error. Wondering if you can help me debug this? 🙏

**### Actual Behavior**
Instead of redirecting to the target URL, I get an error stating the following:
"Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."

**### Steps to reproduce**
Trying to use any source URL and target URL - none of them redirect.

Tried clearing cache.
Tried deleting Wordpress from server and reinstalling.
Tried turning off all plugins.

**### Environment**
Brave - [Version 1.41.100 Chromium: 103.0.5060.134 (Official Build) (x86_64)]

Chrome - Version 103.0.5060.134 (Official Build) (x86_64)

Safari - Version 15.4 (17613.1.17.1.13)

Wordpress - 6.0.1 

Redirection - Version 5.3.1

Host - Bluehost - Server info in screenshot below

**Thank you for any help you can provide! :)** 

![Screen Shot 2022-08-05 at 8 01 20 AM](https://user-images.githubusercontent.com/110682493/183106452-27f703be-ec6e-4c5a-b45d-c4249374c323.png)
<img width="1295" alt="Screen Shot 2022-08-05 at 8 02 29 AM" src="https://user-images.githubusercontent.com/110682493/183106458-f01e1e8f-ee12-4d6e-952b-a3d995c97aa5.png">
<img width="1247" alt="Screen Shot 2022-08-05 at 8 05 15 AM" src="https://user-images.githubusercontent.com/110682493/183106463-f4d6d1b1-0231-4a4b-b172-d4316e805ce3.png">
<img width="778" alt="Screen Shot 2022-08-05 at 8 10 28 AM" src="https://user-images.githubusercontent.com/110682493/183106696-99397edc-4266-4aef-8713-57779efe9123.png">

**Comment by johngodley** [comment]
Details can be found here:

https://redirection.me/support/problems/redirect-returning-404/

**Comment by ChristopherBurns11** [comment]
Appreciate it John! Had to change .htaccess - You rock!
