### ISSUE TITLE
NULL in the 404 logs

### ISSUE THREAD

**Issue by mikezielonka** [johngodley/redirection#3385]
### Summary

We have been seeing a lot of 404's in the logs with "null" apended to the end of the URL

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/1565502/184450815-99003bc0-02a0-44d9-a3ed-f02387d7753d.png)

### Actual Behavior

We think these are false positives that are showing up but never ran into this before with redirection.  

### Environment

Latest versions of Redirection and WP

**Comment by johngodley** [comment]
Why do you think they are false positives?

**Comment by mikezielonka** [comment]
I've seen it come up in the logs of 3 sites now.


(ps sorry for the delay! my notification got buried in gmail!)

**Comment by johngodley** [comment]
Sure, but why do you think they are false positives? At the moment there doesn't appear to be anything to suggest that, and it is likely they are just 404s.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
