### ISSUE TITLE
Regression in version 5.3.1, query params are again converted to lowercase

### ISSUE THREAD

**Issue by sweber83** [johngodley/redirection#3386]
### Summary

If the "ignore case" option is set for a redirect, the query params are converted to lowercase.
This issue was already fixed in version 5.2 but now resurfaced in 5.3.1.

A colleague of mine initially reported the issue (for 5.1.3) here https://wordpress.org/support/topic/ignore-case-causes-query-parameters-to-be-lower-cased/

### Actual Behavior

```
curl -I https://www.amdnet.de/studiengang/fashionjournalismus-medienkommunikation-studium-bachelor/\?Test\=WithUpperCase
HTTP/2 301 
server: nginx
date: Wed, 17 Aug 2022 12:54:03 GMT
content-type: text/html; charset=UTF-8
expires: Wed, 17 Aug 2022 13:54:03 GMT
cache-control: max-age=3600
location: /studium/modejournalismus-bachelor/?test=withuppercase
strict-transport-security: max-age=63072000
x-cache: BYPASS
x-cache-type: NGINX
x-cache-skip-reason: QUERY STRING
x-cache-device-type: responsive
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```
As you can see, the query param / value are converted to lowercase.

### Steps to reproduce

Configure redirect to ignore case and pass params.
Update redirection from 5.3.0 to 5.3.1.

### Environment

Redirection Version 5.3.1
WordPress Version 6.0.1

**Comment by johngodley** [comment]
The problem was only partially fixed and it wasn't properly working. This should be fixed in the latest release.
