### ISSUE TITLE
Redirecting base url not working

### ISSUE THREAD

**Issue by dantheinfoman** [johngodley/redirection#3387]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary
I want to redirect the site URL itself if no subdirectory exists. For example, https://xlninja.pro would redirect to https://www.excelvbaisfun.com/excel-ninja-pro/

I have some other redirects that are working fine, but they have subdirectories, such as https://xlninja.pro/excelfree takes them to the free offer, etc.

### Environment

Using Private Firefox browser v,103.0.2. Redirection 5.3.2, Wordpress 6.0.1.

Thanks for a fantastic plugin!
Dan

**Comment by johngodley** [comment]
Source: `/`
Target: `https://target.com`

**Comment by dantheinfoman** [comment]
Thanks, John! I tried using a slash, but it simply redirects to the homepage https://xlninja.pro
Thanks so much for the quick reply, though! :)

**Comment by johngodley** [comment]
It seems to be working fine:

https://redirect.li/http/?url=https%3A%2F%2Fxlninja.pro%2F

**Comment by dantheinfoman** [comment]
crap. I had reset all the cache, but apparently it took a minute! WOW! Thanks so much, man. Your plugin blows RankMath's redirection out of the water. Making a donation, thank again!
