### ISSUE TITLE
Critical error (HTTP code 500) returned when creating a redirection through the REST API

### ISSUE THREAD

**Issue by elietheocari** [johngodley/redirection#3388]
### Summary

I try creating a redirect using the REST API and get a HTTP 500 error in return. Most requests are working fine (GET /redirect, POST /group for instance).

I followed [this documentation](https://redirection.me/developer/rest-api/#api-Redirect-CreateRedirect) in order to create and format my payload.

### Actual Behavior

The body of my request is as follows:
```
{
    "status": "enabled",
    "match_data": {
        "source": {
            "flag_regex": false,
            "flag_query": "exact",
            "flag_case": true,
            "flag_trailing": true
        }
    },
    "url": "/some-url/",
    "match_type": "url",
    "group_id": 3,
    "action_type": "url",
    "action_code": 301,
    "action_data": "/some/destination-url/"
}
```

An error 500 is returned along with this body in the response (which translates in English as: "There was a critical error on this website. Learn more on debugging WordPress."):

```
{
    "code": "internal_server_error",
    "message": "<p>Il y a eu une erreur critique sur ce site.<\/p><p><a href=\"https:\/\/fr.wordpress.org\/support\/article\/faq-troubleshooting\/\">En apprendre plus sur le d\u00e9bogage de WordPress.<\/a><\/p>",
    "data": {
        "status": 500
    },
    "additional_errors": []
}
```

### Steps to reproduce

Create a POST /wp-json/redirection/v1/redirect request with the payload provided above.

It works when I slightly change the action_data parameter as follows:
```
"action_data": {
    "url": "{{destination_url}}"
}
```

instead of:
```
"action_data": "{{destination_url}}"
```

Maybe the documentation needs to be updated, but in any case I would have expected a 400 Bad Request error rather than a 500 Internal Server Error one.

Apart from that, thank you for creating this awesome plugin, which works great!

### Environment

WordPress 5.9.3
Redirection 5.3.2
Postman 9.28.1

**Comment by johngodley** [comment]
The 500 error is probably an error, and not the response being returned by Redirection.

**Comment by johngodley** [comment]
I will update the docs to match, and prevent any errors from an incorrect payload.

**Comment by elietheocari** [comment]
Thank you @johngodley !

**Comment by brooklynguan** [comment]
@elietheocari this saved my day! Thank you.
