### ISSUE TITLE
All redirects stopped working

### ISSUE THREAD

**Issue by NHS-CBA** [johngodley/redirection#3389]
Checking first to see if there are any known issues because literally every redirect on my site stopped working and they were working the last time I checked! (4 days or so ago?) Apologies because I'm not remotely savvy on how to use Wordpress -- this whole operation was handed over to me having been created by someone else who left without notice.

**Comment by johngodley** [comment]
There are no known issues. The plugin doesn't generally stop working on it's own, so there is probably an external reason for the change.

**Comment by NHS-CBA** [comment]
Thanks for the quick answer. And, of course, I figured it out right after I posted this. Thanks. It si fun stumbling around in the dark with a live product. LOL.
