### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by mvissers** [johngodley/redirection#3390]
This happens when I select the "ignore parameters" option.

```
Plugin: 5.3.2 4.2
WordPress: 5.9.3 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
JavaScript: https://www.laserkabinet.be/wp-content/plugins/redirection/redirection.js?ver=5.3.2-c785eb862c23d732cc3689b27f4eec09
REST API: https://www.laserkabinet.be/wp-json/
Query: ?page=redirection.php

Error: Unable to add new redirect (redirect_create_failed)
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":295,"wpdb":"INSERT command denied to user 'xxx'@'xxx' for table 'wp_redirection_items'"}}
```

**Comment by johngodley** [comment]
The error is shown above:

`INSERT command denied to user 'xxx'@'xxx' for table 'wp_redirection_items'`

Your user doesn't have INSERT permissions.

**Comment by mvissers** [comment]
I honestly don't think that is the real problem, despite this message.

It works fine when I add a redirect with "query parameters = exact match in any order" (which is also an insert).

The error is thrown when I change this option to "query parameters = ignore all parameters".

Other insert actions in the database (cfr add new page, ...) works all fine.
This makes me think something else is going on here.

**Comment by johngodley** [comment]
Sure, something else may be going on, but the error is from your database, and is not something that the plugin can generate itself.

No one else has reported a problem with the ignore all parameters option, and I am unable to reproduce one myself, so it is likely this is something specific to your site.

Maybe something else on your site is incorrectly blocking the insert and causing an error - some kind of security software?

Could you show all of the details you are using in the redirect?

**Comment by mvissers** [comment]
Hi John

I've found the problem, and it's a pitty one.

The database was full (I've checked this days before), but the control panel usage indicator from the hoster contained a bug. Because of this, the real usage stats (and warnings) were not displayed.
The problem is gone now. 

I'm sorry for using your valuable time for this.
