### ISSUE TITLE
Losing source/medium on traffic from Google Ads

### ISSUE THREAD

**Issue by zachvinson** [johngodley/redirection#3394]
We just launched this site for a client (https://janarus.com/) and used redirection to set up 301 redirects. However, since that point, we are losing source/medium attribution in Google Analytics on all traffic from Google Ads.

I thought it was due to the default "case insensitive matches" setting, since the URL parameters from Google Ads are case sensitive. However, I unchecked that box and it has not fixed the problem. 

This is happening across all browsers/devices, using Redirection v 5.3.2 and WordPress v 5.9.3. 

Any help is much appreciated!

**Comment by johngodley** [comment]
I'll need some more details. What redirect did you create?

**Comment by zachvinson** [comment]
A handful of them:

https://janarus.com/church-cleaning/
https://janarus.com/janitorial-cleaning/
https://janarus.com/construction-cleaning/
https://janarus.com/professional-cleaning/
https://janarus.com/school-cleaning/

Screenshot attached so you can see the settings we're using on each redirect:

![Screen Shot 2022-08-24 at 2 17 37 PM](https://user-images.githubusercontent.com/111995719/186504444-5b7d95a5-4691-416b-9d6a-cd55c8e0962a.png)

**Comment by johngodley** [comment]
You are using a 'URL and server' match - is there a reason for this?

You also aren't using the 'ignore and pass query parameters option'.

**Comment by johngodley** [comment]
More details here:

https://redirection.me/support/matching-a-url/
https://redirection.me/support/matching-redirects/

**Comment by zachvinson** [comment]
Hey John,

Thanks for the info. My usual process for implementing redirects on a new site launch is to export a CSV of all the URLs from the current site, delete the rows that don't need a redirect, and add a relative URL path to Column B with the new URL path.

When I upload this CSV into Redirection, it automatically selects that "URL and server" setting...I'm guessing because Column A of my spreadsheet has the full URL? Is it best practice to just use a relative URL path in Column A as well?

I'm looking into the other details you sent over and should be able to sort out this query parameters issue from here. Thanks!

**Comment by johngodley** [comment]
A URL and server is chosen if the source URL is different from the current site - you are indicating you want to redirect a different site. If that is not what you want then making it relative is an easy way to make the redirect apply to whatever the current site is.

**Comment by zachvinson** [comment]
Ahh got it. Thanks for the help!

**Comment by zachvinson** [comment]
Unfortunately, this is still not working properly. The traffic is being counted as organic instead of paid search in Google Analytics. Here's my current settings for one of the URLs that is not cooperating:
<img width="1260" alt="Screen Shot 2022-09-02 at 8 58 00 AM" src="https://user-images.githubusercontent.com/111995719/188165287-6e0bb6c8-239f-4fb6-909d-7d289d058764.png">

Any idea why this would be? Thanks!

**Comment by johngodley** [comment]
This is not caused by the plugin.

Works with other parameters:
https://redirect.li/http/?url=https%3A%2F%2Fjanarus.com%2Fchurch-cleaning%2F%3Ftest%3D1

Does not work with UTM:
https://redirect.li/http/?url=https%3A%2F%2Fjanarus.com%2Fchurch-cleaning%2F%3Futm_source%3D1

You should speak to your host and ask them why they are removing UTM parameters.

**Comment by zachvinson** [comment]
Oh weird. I will do that.

Thank you!
