### ISSUE TITLE
Problem starting Redirection 5.3.2

### ISSUE THREAD

**Issue by anil-gohil** [johngodley/redirection#3395]
```
Uncaught SyntaxError: Unexpected string https://avsarjewellers.com/wp-content/plugins/redirection/redirection.js 2
```

Plugin: 5.3.2 4.2
WordPress: 6.0.1 (single)
PHP: 7.4.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
JavaScript: https://avsarjewellers.com/wp-content/plugins/redirection/redirection.js?ver=5.3.2-c785eb862c23d732cc3689b27f4eec09
REST API: https://avsarjewellers.com/?rest_route=/

**Comment by johngodley** [comment]
Your plugin file is corrupt and contains weird characters:

![image](https://user-images.githubusercontent.com/1277682/186624690-92afe112-7536-4075-a7e9-847538ebf157.png)

I don't know how you installed it but you will need to install it again.
