### ISSUE TITLE
Error when running PHP via the command line: Call to a member function url() on a non-object

### ISSUE THREAD

**Issue by henare** [johngodley/redirection#34]
`PHP Fatal error:  Call to a member function url() on a non-object in /var/www/wp-content/plugins/redirection/modules/wordpress.php on line 49`

I'm guessing this is something to do with other plugins on my install. CiviCRM leaps to mind :(

**Comment by johngodley** [comment]
What version are you running? That error refers to a line of code that doesn't exist!

**Comment by henare** [comment]
Thanks for the plugin and reply John!

>What version are you running?

The latest from the WordPress directory: [Version 2.3.11](https://wordpress.org/plugins/redirection/)

>That error refers to a line of code that doesn't exist!

Here's the line at that version: https://github.com/johngodley/redirection/blob/e8201d3fab0a04d012264d2e27412b96e36fd9a0/modules/wordpress.php#L49

Manually upgrading to 2.3.12 makes this exception get thrown instead when running via the command line:

`PHP Fatal error:  Call to a member function hasMatched() on a non-object in /var/www/wp-content/plugins/redirection/modules/wordpress.php on line 27`

Which is this line: https://github.com/johngodley/redirection/blob/2.3.12/modules/wordpress.php#L27

**Comment by johngodley** [comment]
How are you running WordPress via the command line? The error isn't thrown when the plugin runs normally so something must be happening differently from the CLI

**Comment by henare** [comment]
It's [CiviCRM scheduled jobs](http://wiki.civicrm.org/confluence/display/CRMDOC/Managing+Scheduled+Jobs#ManagingScheduledJobs-PHPclimethod). When trying to run the scheduled job it throws the exception above.

**Comment by soulseekah** [comment]
Same error here when running with wp-cli, trying to figure it out.

**Comment by soulseekah** [comment]
Directly related to: https://github.com/wp-cli/wp-cli/issues/2289

**Comment by soulseekah** [comment]
Adding `global` to `$redirection =` in the last line of redirection.php fixes this error. WP-CLI is able to import the variable into the scope only when explicitly set as global.

**Comment by pj-dave** [comment]
@johngodley is this something you can fix? It's a shame to have to add `--skip-plugins` to every single WP-CLI command. I'm happy to create a pull request if you prefer, though @soulseekah's solution in the comment above is simple enough. Thanks!

**Comment by johngodley** [comment]
Sorry for the length of time between replying. The code has changed significantly since this bug was raised and I don't think it applies any more. I'm closing it for now, but please reopen if its still a problem
