### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by stefanvr82** [johngodley/redirection#3400]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

again there is a redirection problem ... 

### Actual Behavior

to many redirects result in internal server error 500 ... 

### Steps to reproduce
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@*** to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

### Environment
Firefox, Plugin Version 5.3.2  Wordpress Version 6.0.2

**Comment by stefanvr82** [comment]
Server Error Log: AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

**Comment by johngodley** [comment]
Please keep this together with #3378. Starting a new thread doesn't help, and #3378 is still waiting feedback.
