### ISSUE TITLE
I can't find all redirects in your tool

### ISSUE THREAD

**Issue by Misael-voicebooking** [johngodley/redirection#3401]
### Summary

We've recently had a site redesign, with this came a bunch of technical issues, which include redirect chains. To fix these redirect chains my intention was to go into the redirection tool, and intercept the destination URL to ensure there is no bounce between pages. When attempting to do this, the redirects involved in the chains could not be found in the existing redirection list. 

### Steps to reproduce

I spot checked a few URLs after the first few didn't work, which can be found here:

https://www.voicebooking.com/blog/nl/
https://www.voicebooking.com/nl/voiceover-gezocht/nederlandse-voice-over-gezocht/
https://www.voicebooking.com/en/voiceactor-needed/native-swedish-voice-actor/man/bnh170
https://www.voicebooking.com/blog/en/5-tips-from-a-morgan-freeman-sound-alike-that-will-make-your-script-stronger-interview/amp/?utm_campaign=Voice-search%20ontwikkelingen%20in%20Cannes:%20Who%20owns%20the%20dialogue?&utm_source=hs_email&utm_medium=email&utm_content=74683044&_hsenc=p2ANqtz-_h91L5

I essentially wanted to change their location to point to the final page the chains landed on, but when searching for them, they were nowhere to be found within the tool; I added another CSV file to account for those missing URLs, but the chain problem persists as those older redirects are still in the tool, somewhere. 

### Environment

Granted my browser is older, as my laptop is outdated, I'm using un-updated Chrome as a result, but this isn't an issue as it still picks up the redirects.  

Wordpress version 6.0.1, redirection tool is version 5.3.

**Comment by johngodley** [comment]
What are the above URLs? They all return a 403 error.

The redirect log will show you what redirects are occurring.

The plugin doesn't hide any redirects, and everything it redirects is visible in the list or from the other settings that might cause a redirect.

**Comment by Misael-voicebooking** [comment]
Hey John, 

The above URLs are examples of chain redirects currently in place, they all return 301 status codes, not 4xx errors. 

This URL (https://www.voicebooking.com/blog/nl/) for example, is one of these chains, where it bounces to https://www.voicebooking.com/nl/blog/ then https://www.voicebooking.com/nl/blog (the live, 200 page). I wanted to intercept this to go from A to B, as opposed to A, to B then C (if that makes sense). 

Are you suggesting the redirect could be coming from somewhere else other than the redirection tool?

Within this team I've been informed this is the only place where we place manual redirects. Do get back to me with an update/your 2 cents, thanks.

**Comment by johngodley** [comment]
The URLs are returning 403s for me:

https://redirect.li/http/?url=https%3A%2F%2Fwww.voicebooking.com%2Fblog%2Fnl%2F

**Comment by Misael-voicebooking** [comment]
Thanks for raising this, I appreciate the outside perspective here, no idea how this can be returning a 403 instead of 301, even the crawlers pick it up as a 301. 

I can see it's got nothing to do with you guys, probably a server thing, thanks for your insights!

**Comment by Misael-voicebooking** [comment]
One more on this John, I just noticed, of the redirects I did import that I couldn't find, how do we explain them going missing?

**Comment by johngodley** [comment]
The plugin will tell you how many redirects it imported. If you have redirects that weren't imported then you will need to look at your source file and see what is wrong with the data
