### ISSUE TITLE
410 Redirect Option Not available

### ISSUE THREAD

**Issue by maamirh** [johngodley/redirection#3404]
I want to apply 410 Redirect on some URLs but I am unable to find the 410 Redirect option in the plugin.
![image](https://user-images.githubusercontent.com/46965638/188844540-2b305486-53ea-4453-9ded-92fab4447d2a.png)

**Comment by johngodley** [comment]
A 410 is not a redirect, it's an error code.

https://redirection.me/support/redirect-actions/
