### ISSUE TITLE
Exclude redirected pages from Yoast Sitemap

### ISSUE THREAD

**Issue by GitHub-Mike** [johngodley/redirection#3408]
I currently use the Yoast Sitemap functionality and your redirection plugin.

Is there a way to programmatically detect if a page was redirected with the redirection plugin? Then I could determine the ID and exclude it via the wpseo_exclude_from_sitemap_by_post_ids filter.

**Comment by johngodley** [comment]
When you say 'was redirected', do you mean after a redirect has happened? Or at run time?

**Comment by GitHub-Mike** [comment]
From Yoast website:

"The Yoast plugin create sitemaps on the fly. This means sitemaps are updated automatically when you add, edit, or delete content."

The answer would be at runtime when the sitemap is created. With this call, the sitemap filter must determine the IDs that are forwarded.

Is that possible?

**Comment by johngodley** [comment]
You can get a list of redirected URLs and then work backwards to the post ID, if any exists. I don't know what effect it will have on performance.

https://redirection.me/developer/rest-api/

**Comment by GitHub-Mike** [comment]
It's not as easy as I thought it would be.

I will then probably build a functionality that checks after saving a page whether it is redirected to a page with a different ID.

I will write these IDs into the DB with the Transients API and then use this value in the Yoast filter to determine the exceptions.

I have to save the currently affected pages once so that they are taken into account.

Thank you for the quick answers and the excellent plugin including the documentation.
