### ISSUE TITLE
What does Pos mean?

### ISSUE THREAD

**Issue by XarahD** [johngodley/redirection#341]
It's not an issue just a question. I have just now discovered this "Pos":

https://www.screencast.com/t/JTATjcgz

What does this Pos mean? I'm not sure I've seen it before.

Thanks, Xarah

**Comment by johngodley** [comment]
It affects the order in which redirects are processed, if you have several matching a URL. You don't need to use it unless you have a specific use.

**Comment by XarahD** [comment]
ok, thank you John!
