### ISSUE TITLE
Add redirect is grayed out. 

### ISSUE THREAD

**Issue by theword4life** [johngodley/redirection#3410]
I have 38 active redirects and now I can't add any. Here's a print screen.

![image](https://user-images.githubusercontent.com/113382891/189731047-79fe5eb5-8a18-41b7-a8e1-258a11376a23.png)

I use Chrome, 6.0.2 version of WP and 5.3.3 Redirection

[Print Screen for Redirection Issue - Writing for JESUS 9-1-22.docx](https://github.com/johngodley/redirection/files/9550928/Print.Screen.for.Redirection.Issue.-.Writing.for.JESUS.9-1-22.docx)

**Comment by johngodley** [comment]
Why can't you add any?

**Comment by johngodley** [comment]
I see you put the reason in the title. You need to put information into the form before the button is enabled.

**Comment by theword4life** [comment]
On the day I tried to enter a redirect, that didn't work (really). Not sure why. Entered information today, it works. Thank you - love your product.
