### ISSUE TITLE
Problem starting Redirection 5.3.1

### ISSUE THREAD

**Issue by linsiyun** [johngodley/redirection#3414]
Plugin: 5.3.1 4.2
WordPress: 5.8.5 (single)
PHP: 7.4.11
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
JavaScript: https://hkcasino.org/wp-content/plugins/redirection/redirection.js?ver=5.3.1-861e7f0132a71a1fdb94b8db22f36d35
REST API: https://hkcasino.org/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This is probably caused by another plugin
