### ISSUE TITLE
Summary: Your REST API is not working

### ISSUE THREAD

**Issue by GitMitter** [johngodley/redirection#3417]
Hello,

Are you able to help with this error:

Summary: Your REST API is not working and the plugin will not be able to continue until this is fixed.

Plugin: 5.3.4 4.2
WordPress: 6.0.2 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
JavaScript: https://paulmittermillermd.com/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://paulmittermillermd.com/wp-json/
Query: ?page=redirection.php

Error: undefined

**Comment by johngodley** [comment]
As should be explained in the error you will need to look at your site and see if you have any security plugins or other things that might be affecting your REST API.

**Comment by GitMitter** [comment]
Thank you. It turned out being an issue with the Chrome browser. It worked
fine on other browsers. A totally clean install of Chrome fixed the issue.
