### ISSUE TITLE
countdown

### ISSUE THREAD

**Issue by uselessgames** [johngodley/redirection#3419]
### Summary

show a temporary page informing the viewer "the page has moved" + new link and with redirect countdown

### Actual Behavior

n/a - question

### Steps to reproduce

n/a

### notes
this is a question or possibly a feature request. 

Does this plugin allow delayed redirect? see aforementioned summary for additional info. 
cheers

**Comment by johngodley** [comment]
No, this isn't something the plugin does and it is unlikely to do so. These aren't real redirects, don't get picked up by search engines, and generally aren't good user experiences. If you need to do them then you'll have to use JavaScript on the page itself.

**Comment by uselessgames** [comment]
ok thank you
