### ISSUE TITLE
Problem starting Redirection 5.3.4

### ISSUE THREAD

**Issue by LinusChidi** [johngodley/redirection#3421]
Plugin: 5.3.4 4.2
WordPress: 6.0.2 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
JavaScript: https://bakup.com.ng/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://bakup.com.ng/wp-json/

**Comment by johngodley** [comment]
As explained in the message this is caused by another plugin on your site.
