### ISSUE TITLE
Redirect suddenly stops working

### ISSUE THREAD

**Issue by benjamin-inspectly** [johngodley/redirection#3422]
### Summary

I have a website (ikontrol.dk) where I have setup redirects up a long time ago and it has worked for a long time. (redirects to inspectly.com)

Suddenly, this month, it stopped working and i'm unsure where to look. I have a bunch of redirects and they all seem to work, but the only page that's not working is the frontpage.

This is an image of 2 redirects where one of them are working
![image](https://user-images.githubusercontent.com/114057836/191442946-32fc2896-8d71-4cc4-8523-0c16d9daf78b.png)

This is the advanced settings:
![image](https://user-images.githubusercontent.com/114057836/191443182-e366bff0-6fe3-4a2a-be70-50e0b89fb916.png)

Another funfact - it seems that if I clear the cache (using WP rocket) it starts working again for a couple of days and then the frontpage-redirect stops working.
Is this a known issue?

I have experienced this recently on both "ikontrol.dk" (which redirects to inspectly.com) and from "inspectly.com" (which redirects to inspectly.com/da). It seems it is always when the redirect is from the frontpage and I'm pretty clueless as to why.

Hope any of this makes sense to you.

### Actual Behavior

The frontpage redirect stops working.

### Steps to reproduce

Setup redirects on the frontpage, make sure they work and wait a week or so :)

### Environment

Tested in both Google Chrome and Mozilla Firefox.

**Comment by johngodley** [comment]
> it seems that if I clear the cache (using WP rocket) it starts working again for a couple of days and then the frontpage-redirect stops working.

It sounds like you've found the cause. I don't know what settings you need in your caching software, but it is almost always the cause of anything that works then doesn't work.

**Comment by benjamin-inspectly** [comment]
Thank you for your very quick response!
I should be able to exclude scripts from being cached but cannot find a .js script for the "Redirection" plugin. Do you know if there are a script that I should exclude to make sure your plugin wont be cached?

**Comment by johngodley** [comment]
That's not really how a redirect works, and no scripts are involved. Your caching system is somehow caching the home page without the redirect being applied, but isn't doing the same on other pages. I don't know enough about your system to say why this would be the case, but the authors of the plugin may know more.

**Comment by benjamin-inspectly** [comment]
Oh damn :) I'll get in touch with them.
Thank you very much for your time!
