### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by moabi** [johngodley/redirection#3426]
```
Plugin: 5.3.4 4.2
WordPress: 6.0.2 (multi)
PHP: 8.0.23
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
JavaScript: https://www.example.com/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://www.example.com/wp-json/
Query: ?page=redirection.php

Error: Invalid group when creating redirect (redirect)
Raw: {"code":"redirect","message":"Invalid group when creating redirect","data":{"status":400,"error_code":295}}
```
Process : 

1. Created a custom group
2. Added some redirects
3. Deleted the 2 default groups

Consequences : 

- lost all the redirects
- impossible to create a new redirect (whatever group it is assigned to)
- issues when viewing the groups, no groups are shown except the 2 default, Tried to re-create them. Only when I create a new group with a new name, I'm able to see all created groups
- seems to come back after a 5mn pause. maybe a story of cache ? (hosting is wpengine)

**Comment by johngodley** [comment]
It sounds like your site is caching things it shouldn't. Try clearing any caches and ensure that your REST API is not cached.
