### ISSUE TITLE
Site Header Issue - Access-Allow-Control-Origin not passing through

### ISSUE THREAD

**Issue by Zdubs91** [johngodley/redirection#3429]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

We have setup a new page https://www.acornfinance.com/acorn-lender-list/ however we are getting our cdn from pressable blocked according to Chrome Inspector
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/107435326/192392453-595492a2-6134-4e45-bea2-0205aead07e2.png">

We have set a wildcard for this Header in the Redirection Site settings: 
<img width="783" alt="image" src="https://user-images.githubusercontent.com/107435326/192392565-35797dd7-a23b-4091-9a9e-c9fadb40b1e2.png">

However it doesnt appear to be picked up by the browser even when we see it in the header under inspection: 
![image](https://user-images.githubusercontent.com/107435326/192392781-b0630bb8-d278-48e8-86bc-d20e8235b119.png)

This may not be a redirection plugin issue but wondering if there is something that has cropped up before when using this plugin. 

### Actual Behavior

This error returns instead of what should be a json derived table:

Access to XMLHttpRequest at 'https://149360533.v2.pressablecdn.com/wp-content/plugins/lenders-list/json/AC_PLMP_Lender_Table_final_minV2.json' from origin 'https://www.acornfinance.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Steps to reproduce

Go to https://
www.acornfinance.com/acorn-lender-list/ 
### Environment

Chrome, Version 105.0.5195.125 (Official Build) (arm64), Wordpress 6.0.2, PLugin v 4.2

**Comment by johngodley** [comment]
You can see in the last screenshot that the header is being set by something. Redirection is unable to remove or override a header that is already set.

**Comment by Zdubs91** [comment]
Understood. I appreciate your swift response and it turns out that the issue was the CDN involvement with the called JSON file so you can close this issue as it’s clearly not valid (if you haven’t already ha).

Thanks again!

Regards,

Zach
