### ISSUE TITLE
Blog redirect not working

### ISSUE THREAD

**Issue by Winder78** [johngodley/redirection#3431]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Blog page won´t redirect as expected

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### I´m trying to redirect a WP blog page / created in Optimizepress. All other pages redirects, just not this one.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### 1. Page redirect is entered 2. Page seems to quickly redirect, only to jump back to it´s own url. 

Explain the steps involved to reproduce the problem

### One step: I just enter the source page after having "programmed" the redirect to another page. But it keeps jumping back to source page.

Please list your browser, browser version, version of WordPress and Redirection plugin.

Browser: Google / Duckduckgo
Browser version: Google Version 104.0.5112.101 (Official Build) (x86_64)
Wp version:  WordPress 5.5.10 
Redirect plugin version: Version 5.2.3

**Comment by johngodley** [comment]
That sounds like something on the target page is redirecting you back, and this is unlikely to be caused by Redirection. You can use https://redirect.li/http/ to find out what is happening.

**Comment by Winder78** [comment]
Thank you. It seems though that it redirects well on the page you kindly sent.

But it doesn´t in real life.
________________________________

**Comment by johngodley** [comment]
The page I sent is real life, the one in your browser is affected by a cache and isn't real life. Clear your cache.

**Comment by Winder78** [comment]
Thank you very much, John.

Problem solved it seems.
________________________________
