### ISSUE TITLE
redirect from a automatic unique url creation

### ISSUE THREAD

**Issue by oreldorf** [johngodley/redirection#3432]
I'm trying to create a redirection to a "coming soon" page from each page of my site
The problem is, that when someone clicks on a link from a social media button, It creates a unique /link each time and it doesn't work with the redirection settings... 
is there any solution for that?

**Comment by oreldorf** [comment]
Basically, I want any /url to redirect to the coming soon page

**Comment by johngodley** [comment]
What is a /link? Your redirect will need to fully match every variation of a URL.

Also, please try to keep your questions to one place to avoid creating additional work.

**Comment by oreldorf** [comment]
Sorry about that.

Yes, I need every vartiation of a URL to redirect.

How do I do that?

בתאריך יום ה׳, 29 בספט׳ 2022, 19:51, מאת John ***@***.***>:

**Comment by johngodley** [comment]
What is every variation? Can you give some specifics?

**Comment by oreldorf** [comment]
I want that any URL will redirect to a specific page. Simple as that.

בתאריך יום ה׳, 29 בספט׳ 2022, 20:40, מאת John ***@***.***>:

**Comment by johngodley** [comment]
Ok, but what is any URL? Do you mean every URL on your site? You can use a regular expression for that:

https://redirection.me/support/redirect-regular-expressions/

**Comment by oreldorf** [comment]
![image](https://user-images.githubusercontent.com/56199428/193452159-aa9d8388-b62d-476f-9c59-1e980cab6ef7.png)

I don't manage to understand the correct settings :\ 
Right now my website is still under construction. I want any www.domain/[something] will redirect to a specific page.
Can someone please screenshot the correct setting for that?

**Comment by johngodley** [comment]
Sorry, as explained in https://redirection.me/support/what-support-is-provided/ this is a self-service plugin. You will need to read the support guide and provide your own settings.

https://redirection.me/support/redirect-regular-expressions/ has examples that can be adapted for your needs.
