### ISSUE TITLE
Loosing utm_ and any parameters with underscore when redirect

### ISSUE THREAD

**Issue by mzaqout** [johngodley/redirection#3434]
I'm trying to make a redirect from one page to another.
I am using 'Ignore and pass parameters to the target' for the redirect but when I try to add ?utm_medium=any
of add ?param_any=any. these will not present in the URL after the redirect.

It will work for any ?query=any but not ?query_param=any

**Comment by johngodley** [comment]
Some hosts remove utm parameter. You should check with them.

**Comment by mzaqout** [comment]
@johngodley Thanks for your reply. I will check with them
