### ISSUE TITLE
Error in disabling redirection 

### ISSUE THREAD

**Issue by Annepernille** [johngodley/redirection#3435]
### Summary

I want to disable a redirection on a single page, but when I disable the redirection (and I've deleted the redirection-line completely to see if that helps), the page stille shows the content on the redirect-url. Not the actual content that is on the site.

### Actual Behavior

I've first disabled and later deleted the redirection from the plugin for https://annepernille.dk/skyggearbejde (the original page)

I've cleared cache in my browser. 
I've tried to access it through an incognito browser to see if that helps.

The page was redirected to https://annepernille.dk/skyggesider-hvadermine (the redirection page), but after having used this plugin, the content from the redirection page is loaded TO the original page. 

When I try to edit the original page and opens the modules in Divi Builder (from Elegant Themes), the page keeps showing the redirection pages' content. When I look in development code on the page, I can see that the original text is in the code.

I experienced the same problem with another page last week and thougth, that it must have been I who have done something wrong (although it would require a string of wrong clicks in the right sequence, which I have a hard time believing I would do by mistake). 

But now that I see the exact same problem on this page - I doubt that the problem has to do with errors on my end :)

### Steps to reproduce

1. I delete the redirection in the Redirection plugin.

2. I delete browser cache  (pictures and files) 

3. I open the page that has been redirected previously.

4. I only get to see the content on the redirection page - not the original page. But I see the original URL in the browser and I can click edit page, where I also see the original page URL in the visual builder - but the content in the modules in the visual builder is the content from the redirection page.

### Environment

Browser: Google Chrome
Browser version: 106.0.5249.103 (Officiel version) (64-bit)
WordPress: WordPress 6.0.2
Redirection plugin: Redirection version 5.3.4

I hope you can help me, please. 

All the best
Anne Pernille Fischer

**Comment by johngodley** [comment]
If you've deleted or disabled something in Redirection then it is no longer redirecting that URL.

I don't know what you mean by 'content on the redirection page not the original page'. Redirection is not involved in anything to do with the page mentioned above and it does not alter what is displayed on a page (even if it was redirecting it).

**Comment by Annepernille** [comment]
Thank you, John. I've reached out to the developers of the theme instead to
get their help.

All the best
*Anne Pernille Fischer *
*Business Mentor & Mindsetcoach for selvstændige*

Nattergalevej 6, 8210 Aarhus V | +45 26 36 10 22  |
***@***.*** | www.annepernille.dk  | CVR-nr. 33527594



Den lør. 8. okt. 2022 kl. 09.24 skrev John ***@***.***>:

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
