### ISSUE TITLE
Error on plugin options page

### ISSUE THREAD

**Issue by MicNak123** [johngodley/redirection#3436]
### Summary

Error on plugin options page

### Actual Behavior

Plugin: 5.3.4 4.2
WordPress: 6.0.2 (single)
PHP: 7.4.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Query: ?page=redirection.php&sub=options
TypeError: Cannot read properties of undefined (reading 'prevOffset')

**Comment by johngodley** [comment]
You should use version 5.3.5
