### ISSUE TITLE
Continues to show 404 error page

### ISSUE THREAD

**Issue by kyang8** [johngodley/redirection#3437]
To help track problems please follow this template. If you can provide screenshots then that will help.

![image](https://user-images.githubusercontent.com/115478613/194880973-4a3e800a-9e0a-4aa6-8e6b-07e4bbc033e6.png)

### Summary

I would like this outdated link to redirect to the home page. It used to point to a PDF which has recently been deleted.

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

The link continues to show a 404 error page instead of being redirected back to the home page. The original PDF at this location was deleted.

Explain the steps involved to reproduce the problem

Navigating to this link: https://www.nvfs.org/wp-content/NVFS_Images/Summer2014-2web.pdf

Please list your browser, browser version, version of WordPress and Redirection plugin.

Google Chrome Version 105.0.5195.127
Wordpress 6.0.2
Redirection Plugin Version 5.3.4

**Comment by johngodley** [comment]
Details here:

https://redirection.me/support/faq/
https://redirection.me/support/problems/redirect-returning-404/

**Comment by kyang8** [comment]
I've reuploaded a PDF at the original URL, but the new PDF loads instead of being redirected to the home page or shown a 404 error. Do you know what can be done to resolve this? So it goes to the home page instead of loading the PDF?

**Comment by johngodley** [comment]
As mentioned in the support links, you need to either reconfigure your server so that it doesn't directly serve PDFs before going to WordPress, or you need to export to .htaccess
