### ISSUE TITLE
AMP Redirect

### ISSUE THREAD

**Issue by mycsplace** [johngodley/redirection#3441]
I tried to use an AMP plugin on my WordPress site and several plugins are not compatible so I had to uninstall it.  Google indexed the site and now has all the AMP pages indexed and showing up as 404's.  Is there a way to set up a redirect to fix this?  

Thank you,

Myc

**Comment by johngodley** [comment]
You can find details on the support site:

https://redirection.me/support/redirect-regular-expressions/

**Comment by mycsplace** [comment]
Thank you
