### ISSUE TITLE
Problem starting Redirection 5.3.4

### ISSUE THREAD

**Issue by alannxd** [johngodley/redirection#3444]
Plugin: 5.3.4 4.2
WordPress: 6.0.2 (single)
PHP: 7.4.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
JavaScript: https://dev-funyteca.pantheonsite.io/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://dev-funyteca.pantheonsite.io/wp-json/

**Comment by johngodley** [comment]
You haven't said what the problem is?
