### ISSUE TITLE
Problem starting Redirection 5.3.4

### ISSUE THREAD

**Issue by kuna91** [johngodley/redirection#3445]
Plugin: 5.3.4 4.2
WordPress: 6.0.3 (single)
PHP: 8.0.12
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
JavaScript: https://adwokat-kunicka.pl/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://adwokat-kunicka.pl/wp-json/

**Comment by johngodley** [comment]
As detailed in the error this is almost certainly caused by another plugin.
