### ISSUE TITLE
Unable to Export Logs

### ISSUE THREAD

**Issue by maamirh** [johngodley/redirection#3446]
I have 18K+ redirects and I am able to export the redirects file in csv but I am unable to export Logs file .When I am clicking on to export logs then after some time page is redirecting to our default 404 page.

/wp-admin/tools.php?page=redirection.php&sub=log

**Comment by johngodley** [comment]
Probably your server is timing out if you are exporting a lot of entries. There's not much that can be done about this right now, other than increasing your server resources.
