### ISSUE TITLE
A Hidden Undiscoverable Issue | Redirects with gclid

### ISSUE THREAD

**Issue by Lear95** [johngodley/redirection#3449]
Hey there!

First off, I love using this plugin, I have used it in many sites and really appreciate all the hard work that was put into this. 

I do however, have experienced an issue.

### Summary

My case is a special one, but because it's almost "invisible" to normal tests there might not be a lot of reports of it, just confused webmasters and users.

The problem, in a nutshell, is that when entering an arbitrary URL parameter to a redirected URL user encounters 404.

### Actual Behavior

So basically, the referring site (may it be google ads, an affiliate website or anything else) is redirecting to URL X, URL X is set to be redirected to URL Y.

But, when the referring site adds a parameter to it, let's say Google Click ID (gclid), or any other parameter to the URL - the plugin sees the URL X as an entirely different URL and goes over his head, then the site gives a 404.

### Steps to reproduce

To reproduce, add a redirect to a site, than add a parameter. so for example:

Original URL:
/products.asp?product_catid=61

Target URL:
/category/tablets

User URL:
/products.asp?product_catid=61&gclid=CjwKCAjw5u3WcbpRatIAlEiwApsm7-diLyo9KrosAdY7dP2aBhIE_GAWHOV9oBz

### Environment

This will work at any environment and with any browser.

The main reason why this won't be detected is that whenever an automated system detects a 404, it will test the original URL instead of the URL with the unique user parameters. which will result in a successful test. 

Normally I would of course change the URL to the new target URL, but with many ads/referrals/affiliates it can be quite troublesome. and again - that's what the plugin is for. To make sure that if someone is coming from an old link he will be redirected to a new one. 

I am using the most recent plugin version with Chrome on a windows PC, but again - it will happen on any enviroment.

**Comment by johngodley** [comment]
You can use the ignore query parameter option:

https://redirection.me/support/matching-a-url/

**Comment by Lear95** [comment]
You are a beautiful and smart man. Thank you my friend.

BTW, might be good to set "pass" as default.  

Thank you again!

**Comment by Lear95** [comment]
Hey [John](https://github.com/johngodley)!

A quick question, I sometimes have two parameters, one from the previous site and another one from google click id.

I believe "ignore" should ignore the parameters not in my redirection table, but when testing it doesn't do that.

for example, a link could be:

example?category1?gclid=fdanidsain

the plugin will only use:

example

even though it will still pass the rest of the parameters - it will ignore them. even though the first parameter, ie:

example?category1

Is a redirect in the redirection table.

is there a way to set an ignore function per parameter? am I doing maybe something wrong?

**Comment by johngodley** [comment]
No, that's not correct. The plugin will ignore additional parameters, but does match the ones specified.

Your example URL is not valid and it may help to use a valid example.
