### ISSUE TITLE
Non of the redirections works - error 500

### ISSUE THREAD

**Issue by VZcoding** [johngodley/redirection#3459]
Works fine only when logged in as admin. Simple visitors or customers get an instant error(in all redirects):

This page isn’t working mywebsite.com is currently unable to handle this request.
HTTP ERROR 500

Server is based on litespeed.

**Comment by johngodley** [comment]
This sounds like a configuration error with your server. The plugin doesn't cause 500 errors, and especially not just for logged out users.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
