### ISSUE TITLE
Problem starting Redirection 5.3.4

### ISSUE THREAD

**Issue by fokazaki2** [johngodley/redirection#3461]
Plugin: 5.3.4 4.2
WordPress: 5.8.6 (single)
PHP: 7.4.21
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
JavaScript: https://recruit-ikeda.jp/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://recruit-ikeda.jp/wp-json/

**Comment by johngodley** [comment]
Please follow the on screen instructions. This is almost certainly caused by another plugin.
