### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by gcolette** [johngodley/redirection#3464]
**Hi, Sorry if my english will not be so good. I'll try to do the best.
I have a problem on my site 1 (and the multisitex2) I can have my wordpress administration. I can have the first page of the website
but no the others one. Each page when click shows an 404 error not found the page. 
What can Y do ? Can you help me. Thank you.**

Plugin: 5.3.4 4.2
WordPress: 6.1 (multi)
PHP: 7.4.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:106.0) Gecko/20100101 Firefox/106.0
JavaScript: https://www.penser-la-photographie.com/wp-content/plugins/redirection/redirection.js?ver=5.3.4-04d536d277e6e20820f24f21d395db08
REST API: https://www.penser-la-photographie.com/wp-json/
Query: ?page=redirection.php

Action: https://www.penser-la-photographie.com/wp-json/redirection/v1/redirect/?orderby=id GET
Code: 404 Not Found

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

**Comment by johngodley** [comment]
This is not a problem with Redirection. You will need to configure your site properly. Maybe contact your host provider.
