### ISSUE TITLE
Cloudflare - Why check disable and delete but not check import URLs? Please don't check.

### ISSUE THREAD

**Issue by inboundasia-it** [johngodley/redirection#3468]
### Summary

https://redirection.me/support/problems/cloudflare/

I understand Redirection plugin check WordPress version and Cloudflare Version to prevent potential problem

But the question is why you check disable group and delete group but not check import URLs?

### Actual Behavior

Don't check, please.   It's hard to predirect when Cloudflare cache purged even we request cache purging.

### Steps to reproduce

1. prepare a site behind cloudflare
2. add a redirection group
3. disable group

it shows error

### Environment

N/A

**Comment by johngodley** [comment]
I don't understand what you mean here.

>  why you check disable group and delete group but not check import URLs

Can you explain more about this?

> Don't check, please.

Check what?

> it shows error

What error?

**Comment by inboundasia-it** [comment]
I found the problem is caused by plugin, not cloudflare.

close this issue. thank you.
