### ISSUE TITLE
https Headers Strict-Transport-Security; combine options

### ISSUE THREAD

**Issue by rgrv** [johngodley/redirection#3469]
### Summary

For inclusion into the [HSTS preload list](https://hstspreload.org/) the recommended setting is

`Strict-Transport-Security: max-age=63072000; includeSubDomains; preload`

Currently there are 3 options in the plugin Site settings for Strict-Transport-Security 

- 'max-age=<expire-time>',
- 'max-age=<expire-time>; includeSubDomains',
- 'max-age=<expire-time>; preload',

Could there be a fourth option; _includeSubDomains; preload_ 

### Steps to reproduce

Go to /wp-admin/tools.php?page=redirection.php&sub=site under http Headers
Add Strict-Transport-Security header

Adding both as separate option does not seem to work. 
I managed to add a Custom header with 'max-age=63072000; includeSubDomains; preload' 

### Environment

- Redirection Version 5.3.5 
- WP 6.1

**Comment by johngodley** [comment]
This will be added to the next version.
