### ISSUE TITLE
The 301 Redirect is no longer working.  I did install the update and it still did not work.

### ISSUE THREAD

**Issue by KThomas89011** [johngodley/redirection#347]
To help track problems please follow this template. If you can provide screenshots then that will help.

The 301 redirect is not working any longer.  I did install the update.

### Summary

I am trying to redirect a page to my Shopify store.

### Actual Behavior

The redirect does not work.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Can you provide some more details please?

**Comment by KThomas89011** [comment]
I had your 301 redirect on a page from my website and it was working perfectly forwarding to my shopify store. It is currently not working. That's all I meant to tell you. Karen

Sent from my iPad

On Aug 29, 2017, at 10:19 PM, John <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you provide some more details please?

**Comment by johngodley** [comment]
By more details I meant actual details about the URL so I can help work out why it's not working. Can you provide the URL that isnt working, can you include a screenshot of the redirect inside Redirection?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
