### ISSUE TITLE
Error: Unexpected token '<', "    <!DOCTYPE "... is not valid JSON (SyntaxError)

### ISSUE THREAD

**Issue by deepti4666** [johngodley/redirection#3473]
Plugin: 5.3.5 4.2
WordPress: 6.1 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
JavaScript: https://www.boardroominabox.co.za/wp-content/plugins/redirection/redirection.js?ver=5.3.5-f0dac5b2b3267cd737c1a679e4c1fac3
REST API: https://www.boardroominabox.co.za/wp-json/
Query: ?page=redirection.php

Error: Unexpected token '<', "    <!DOCTYPE "... is not valid JSON (SyntaxError)
Raw:     <!DOCTYPE html>
    <html style="height: 100%;">
    <head>
        <meta charset="UTF-8">
        <title>403 Access Forbidden</title>
        <style>
            @media screen and (max-width: 800px) {
                body > div > div > div div {
                    display: block !important;
                    padding-right: 0 !important;
                }

                body {
                    text-align: center !important;
                }
            }
        </style>
    </head>
    <body style="height: 90%;">
    <div style="display: flex; align-items: center; justify-content: center; height: 90%;">
        <div style="background-color: #eee; width: 70%; border: solid 3px #ddd; padding: 1.5em 3em 3em 3em; font-family: Arial, Helvetica, sans-serif;">
            <div style="display: table-row;">
                <div style="display: table-cell; font-size: 150px; color: red; vertical-align: top; padding-right: 50px;">
                    &#9995;
                </div>
                <div style="display: table-cell; vertical-align: top;">
                    <h1 style="margin-top: 0;">We're sorry, you are not allowed to proceed</h1>
                    <p>Your request looks suspiciously similar to automated requests from spam posting software or it has been denied by a security policy configured by the website administrator.</p>
                    <p>If you believe you should be able to perform this request, please let us know.</p>
                    <p style="margin-top: 2em;">
                    <pre style="color: #777">RID: YEGDP4XQVXNY6ZNKUEWTIOLD</pre>
                    </p>
                </div>
            </div>
        </div>
    </div>
    </body>
    </html>

**Comment by johngodley** [comment]
You can see the message being returned by your REST API. You will need to stop whatever is causing that.

**Comment by deepti4666** [comment]
Yeah, I picked up the security plugin that blocked the access.

Thank you though
