### ISSUE TITLE
Redirect based on device type

### ISSUE THREAD

**Issue by rafaviana** [johngodley/redirection#3478]
Hello, I'd like to know if it's possible to create a redirect based on device type, i.e, Android and iPhone with different redirect rules. 
Thank you in advance.

**Comment by johngodley** [comment]
All the available ways of matching can be found here:

https://redirection.me/support/matching-redirects/

**Comment by rafaviana** [comment]
What are the available user agents? I'm tried this redirect but it doesn't work

![image](https://user-images.githubusercontent.com/5817213/203733666-3adb5501-526f-49ce-be03-3850d02d437f.png)

**Comment by johngodley** [comment]
As it explains in the guide you need to supply the user agent yourself. 'Android' is not a valid user agent.

**Comment by rafaviana** [comment]
I extract 'Android' from this list:

![image](https://user-images.githubusercontent.com/5817213/203750528-9f0f7040-4b21-4d72-9c5f-31184c3646be.png)

I tried to search on the web for a user agent list but everything I found is very different from that you have on 'Mobile' dropdown. 

Do you know what are the user agents for Android and iOS ?

**Comment by johngodley** [comment]
That's part of a regular expression. You will need to create an expression that matches the agents you want.

**Comment by rafaviana** [comment]
> That's part of a regular expression. You will need to create an expression that matches the agents you want.

Can’t you give me an example? As far as I can see, it’s simple to you…

**Comment by johngodley** [comment]
I understand that some of the concepts in the plugin are difficult but it's designed as a self-service tool and you will need to provide your own definitions for matches. You can find more details about this here:

https://redirection.me/support/what-support-is-provided/

**Comment by rafaviana** [comment]
Hi, I figured out the issue. The redirect wasn't working because I had to check this option:
![Motorline](https://user-images.githubusercontent.com/5817213/204252366-ec0aab4a-5a89-442a-9da0-a90f00e0953f.png)
