### ISSUE TITLE
Redirect from FaceBook

### ISSUE THREAD

**Issue by KeithSloan** [johngodley/redirection#3489]
I have configured redirect for www.sloan-home.co.uk/xmas/

Which works if I enter the URL in a browser.

I have references in FaceBook where the page shows as a link (Underlined blue) but the redirection fails.
I note that if I copy the link from FaceBook I get
https://l.facebook.com/l.php?u=http%3A%2F%2Fwww.sloan-home.co.uk%2Fxmas%2F%3Ffbclid%3DIwAR35LkhOO0VQ6_h7oGG9-6QXBmK0wImxZXX9awD8mBxofo7VBKf-s23oGkQ&h=AT27coI1d6dxBSqi4iAHC_QRKo_5mAYZ4sLv3u5yRc57rSg6JqxcadSRWHxRfpGC4vdZQ35Ns5Y-IzdEPccVhL0DOLusCHymSCGA0tn61GCzLg9d0iomK6d4HNVmg1L0z2NSyeE&__tn__=-UKH-R&c[0]=AT3rGBgidCBTT9dsmuo7h7Tndj7jCRd-ryhD-qA-SomjuqT7c6ZIfpwwSAE-iibkbUSiTvjtpUt5_KTDcEzv9XSKERaD3HbWOnNzMhZa-6re9wpIyV5yQyMsR5_cBJU2j_AlWP8Ltze9FIKpgiDXu7xTlYh5wd_pvqjlLIoS3Vfm-eQ

Is there anything I can do about this?

Thanks

**Comment by johngodley** [comment]
See the ignore query parameters option

https://redirection.me/support/matching-a-url/
