### ISSUE TITLE
Action is applied to all redirects instead of just one

### ISSUE THREAD

**Issue by JessiFTO** [johngodley/redirection#3492]
### Summary

When I select an action in the menu bar below a redirect, it is not applied to the individual redirect, but to all of them. As a result, I unintentionally deleted all my redirects yesterday :/

### Steps to reproduce

I created new redirects several times yesterday and the same thing always happens, for example, when I click on "Deactivate" or "Delete", it is applied to all redirects. However, editing or checking works for the individual redirect.

### Environment

Firefox 107.0.1 (64-Bit), WordPress 6.1.1

![20221206_Redirect-Bug](https://user-images.githubusercontent.com/119931205/205875160-d5601978-36ad-4128-8ebc-cda4c3a83348.png)

**Comment by johngodley** [comment]
I can't replicate that and no one else has raised this as an issue. Are you running other plugins or maybe even a browser extension that could be triggering the effect you described?

**Comment by johngodley** [comment]
Closing for now please reopen with more information.
