### ISSUE TITLE
Problem starting Redirection 5.3.5

### ISSUE THREAD

**Issue by atoosaz** [johngodley/redirection#3494]
Plugin: 5.3.5 4.2
WordPress: 6.1.1 (single)
PHP: 8.0.25
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56
JavaScript: https://atpasargad.com/wp-content/plugins/redirection/redirection.js?ver=5.3.5-f0dac5b2b3267cd737c1a679e4c1fac3
REST API: https://atpasargad.com/wp-json/

**Comment by johngodley** [comment]
As described on the page this will be caused by another plugin.
