### ISSUE TITLE
Ignore blank redirects in CSV

### ISSUE THREAD

**Issue by gamebits** [johngodley/redirection#3495]
Some spreadsheet programs (such as Excel or Google Sheets) may append empty rows to the bottom of an exported CSV. These lines will consist of nothing but a comma `,` character (either single or multiple). When imported into Redirection, it creates a redirect from `/` to `/` — an infinite loop that can cause an HTTP 429 error.

It'd be a good safety check for Redirection to somehow detect and ignore these erroneous redirects upon import.

**Comment by gamebits** [comment]
Is this fixed by https://github.com/johngodley/redirection/pull/3524?

**Comment by johngodley** [comment]
Yes this should be fixed, closing.
