### ISSUE TITLE
WordPress and Site URL settings are inconsistent in redirection plugins issue

### ISSUE THREAD

**Issue by narasimma-webdev** [johngodley/redirection#3510]
I have developed react site which depends on rest api by wordpress. I have placed wordpress in a subdomain and placed react site in main domain. Now I would like to redirect all links from wordpress site to react site except for /wp-admin an /wp-json/* links.

can i use redirection plugin?

currently we are using wordpress url - sub domain and site url - main domain is this condition will work in redirection plugin?

because we have developed site before in wordpress, now we migrate into react site. so, we want existing and expired pages to redirect to new site.

**Comment by johngodley** [comment]
I'm not really sure what you are asking but you can find all details about using the plugin here:

https://redirection.me/support/
