### ISSUE TITLE
Problem starting Redirection 5.3.6

### ISSUE THREAD

**Issue by blockchainarchi** [johngodley/redirection#3511]
Plugin: 5.3.6 4.2
WordPress: 6.1.1 (single)
PHP: 7.3.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
JavaScript: https://buycheapest.in/wp-content/plugins/redirection/redirection.js?ver=5.3.6-16d9cc72e7ac56bb977b78fce03e6ba0
REST API: https://buycheapest.in/wp-json/

**Comment by johngodley** [comment]
This file doesnt exists: https://buycheapest.in/wp-content/plugins/redirection/redirection.js?ver=5.3.6-16d9cc72e7ac56bb977b78fce03e6ba0
