### ISSUE TITLE
Translation files not loaded in certain directory constellation

### ISSUE THREAD

**Issue by shiftpi** [johngodley/redirection#3516]
### Summary

If WordPress is installed inside a directory with a `-` and a `.` in some directory of WordPress' path, Redirection will try to load translation files from a directory it perhaps has no access to and/or might not exist.
This is especially relevant if PHP is configured to not allow loading files from outside WordPress' installation path by setting the [open_basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) directive. In this case additional warnings will be thrown.
Anyways the translation files won't be loaded.

### Actual Behavior

Warnings like `Warning:  is_readable(): open_basedir restriction in effect. File(/var/www/example.com/httpdocs/wp-content/plugins/redirection/locale/json/redirection-de_DE.json) is not within the allowed path(s): /var/www/example-domain.com/httpdocs in /var/www/example-domain.com/httpdocs/wp-includes/l10n.php on line 1222` are thrown.
Also the translation file is obviously not loaded, even if `open_basedir` is not set.

### Steps to reproduce

1. Setup WordPress inside a folder like `/var/www/example-domain.com/httpdocs`
2. Set open_basedir directive to `/var/www/example-domain.com/httpdocs`
3. Open `https://example-domain.com/wp-admin/tools.php?page=redirection.php`

### Environment

Tested with Chrome 108, WordPress 6.1.1 and Redirection 5.3.6.

**Comment by shiftpi** [comment]
I think the Regex in [load_script_translation_file](https://github.com/johngodley/redirection/blob/trunk/redirection-admin.php#L58) on line 60 is causing the issue:
`preg_replace( '/-\w*\./', '.', $file )` will replace `-domain.` with `.` from `/var/www/example-domain.com/httpdocs/wp-content/plugins/redirection/locale/json/redirection-de_DE.json`.
However I'm not sure what the whole method is used for 🤔

**Comment by johngodley** [comment]
This should be fixed.
