### ISSUE TITLE
URl with special characters after WP and plugins updates

### ISSUE THREAD

**Issue by PaulineM9** [johngodley/redirection#3517]
Hi, 
I need your help because i have the same issue in 2 of my clients e-commerce websites. 

### Summary

When i made this 2 website, i used Redirections with the news url. Everything was ok, no issue. But recently, i have updated WP version and plugins. And now i have really big problem : all my url has changed with special caracters. 

### Actual Behavior

So now, my url are www.mywebsite.com/?_gl=1%2A1xel8s0%2A_ga%2ANjczNjczNzI0LjE .... 
It's a big problem because i don't how it impact my SEO : this new weird url do not appear into my sitemap nor in the search console. 
First, I though it was hacking so :
- i tried to uninstall all the plugins : not working
- i made a clone into my personal server to find the problem and clean database and wordpress files
- i reinstalled all Wordpress files
- i cleaned my database
- i made a scan with Wordfence but no malware detected
- then i reinstalled this new cleaning version without activating Google Site kit / Redirection / Yoast SEO (freemium)
=> everything was ok before activating this 3 plugins
- the issue again when plugins are activated
- the only solution i found is to restore the old version of all the plugins but it's really not a good solution and it bad issues with security

### Steps to reproduce

- i have created my websites
- i made about 300 redirections 301 old url to new url => it worked perfectly
- 404 errors redirections => it worked perfectly
- updates: Wordpress / Plugins / php 
=> issue with wrong url 

### Environment

Wordpress (last version), host with php 8.0 (recommanded) = Infomaniak for one of the website and Ionos for the other one, theme Hello child version 
Plugins : 
WooCommerce / Stripe for WC / acf / cpt ui / antispam bee / back in stock notifier / cookiebot / multicurrency for WC / duplicate page / dynamic conditions / Elementor Pro / Flexibel shipping / Twint for WC / Sendinblue / redirection / safe svg / Google Site kit / Yoast / Wordfence

Thanks for your answer and your help.

**Comment by johngodley** [comment]
I don't really understand the problem. Can you explain it further, how it relates to Redirection, and what you are trying to do that isn't working?

**Comment by PaulineM9** [comment]
Hi and thanks for your answer. When a make a new version of my websites, i used redirection for my Seo (301 / 404 …). Everything was allright. A few days ago, a made updates of my plugins and wordpress and know i have bad url. Please go to one of my website alguathera.ch. As you can, urls has special characters know. I just want to make my url correctly. Thanks SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 09:14, John ***@***.***> a écrit :﻿
I don't really understand the problem. Can you explain it further, how it relates to Redirection, and what you are trying to do that isn't working?

**Comment by johngodley** [comment]
I don't see any special characters on your website?

**Comment by PaulineM9** [comment]
It’s ok when you go first on the home page. Choose an other page and as you can all the url are changed with special caracters included the home page SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 10:36, John ***@***.***> a écrit :﻿
I don't see any special characters on your website?

**Comment by PaulineM9** [comment]
https://www.alguathera.ch/produits-alguathera/cosmetiques/soins-visage/cremes-de-jour-et-nuit/?_gl=1*mwsv3t*_up*MQ..*_ga*NTQ1NTk1MzU3LjE2NzE3ODgyNTc.*_ga_9KZ4JNBH90*MTY3MTc4ODI1Ny4xLjAuMTY3MTc4ODI1Ny4wLjAuMA..SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 10:38, Pauline Martin ***@***.***> a écrit :﻿It’s ok when you go first on the home page. Choose an other page and as you can all the url are changed with special caracters included the home page SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 10:36, John ***@***.***> a écrit :﻿
I don't see any special characters on your website?

**Comment by johngodley** [comment]
I don't see this on any URL.

This does not seem like something suitable for Redirection. You should find whatever is causing the characters to be added and fix that instead.

**Comment by PaulineM9** [comment]
Ok. Everybody can see it but you don’t. It’s a really stranger think … SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 10:42, John ***@***.***> a écrit :﻿
I don't see this on any URL.
This does not seem like something suitable for Redirection. You should find whatever is causing the characters to be added and fix that instead.

**Comment by johngodley** [comment]
> Ok. Everybody can see it but you don’t. It’s a really stranger think 

No, I would say the majority of people don't see it. URLs are not modified with no reason, so you need to work out what that reason is. Trying to fix it with redirects is not really going to help.

**Comment by PaulineM9** [comment]
Ok thanks. I don’t want to fix it with redirections. I think this is a problem with the installation of my redirections and the plugin. But i don’t know what is really the probleme because before the updates it was ok, after the updates it do not work and i have this bad url know. I do not change anything else. Sorry for the misunderstanding and to have disturb you. SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 11:29, John ***@***.***> a écrit :﻿

Ok. Everybody can see it but you don’t. It’s a really stranger think

No, I would say the majority of people don't see it. URLs are not modified with no reason, so you need to work out what that reason is. Trying to fix it with redirects is not really going to help.

**Comment by johngodley** [comment]
Redirection is not adding things to your URLs and does not have the capability to do that. As mentioned, this does not appear to be affecting most people, so it seems specific to your or logged in people.

**Comment by PaulineM9** [comment]
I’m sorry, maybe you thought i was ironic but i don’t. I don’t just want to solve my problem, i want to understand my mistake and what’s wrong in ly installation. SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 11:57, Pauline Martin ***@***.***> a écrit :﻿Ok thanks. I don’t want to fix it with redirections. I think this is a problem with the installation of my redirections and the plugin. But i don’t know what is really the probleme because before the updates it was ok, after the updates it do not work and i have this bad url know. I do not change anything else. Sorry for the misunderstanding and to have disturb you. SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 11:29, John ***@***.***> a écrit :﻿

Ok. Everybody can see it but you don’t. It’s a really stranger think

No, I would say the majority of people don't see it. URLs are not modified with no reason, so you need to work out what that reason is. Trying to fix it with redirects is not really going to help.

**Comment by PaulineM9** [comment]
Ok and thanks for this information. First, i thought to this possibility. But people who are not logged has the same url. And i tried on others navigator with no log access and it was the same issue. SUPER!Pauline MARTIN Web designer, rédactrice web, développeur web 06 18 06 19 ***@***.*** 23 déc. 2022 à 12:05, John ***@***.***> a écrit :﻿
Redirection is not adding things to your URLs and does not have the capability to do that. As mentioned, this does not appear to be affecting most people, so it seems specific to your or logged in people.
