### ISSUE TITLE
Language redirect issue

### ISSUE THREAD

**Issue by Plovst** [johngodley/redirection#3518]
Hi

A client of mine is having issues with a redirect. The client has Danish and Swedish language options, which means that both a .dk and .se domain exists. The issue is, that www.zurface.se redirects to zurface.dk, where as zurface.se (without www) does not. I can see that Redirection is responsible for the redirect, but I do not see it in Wordpress.

How can I fix this? In the attached image you can see, what I've found.

Site is running Wordpress 6.1.1 with Redirection 5.3.6.

<img width="1275" alt="Screenshot 2023-01-03 at 10 00 51" src="https://user-images.githubusercontent.com/104761214/210327678-2da1a0dc-0859-4394-bd0b-59ea2950e2cf.png">

![Screenshot 2023-01-03 at 10 08 37](https://user-images.githubusercontent.com/104761214/210327824-7726d4df-6b15-464f-af5d-a2b9b5a6adef.png)

**Comment by johngodley** [comment]
Redirection will only do what you instruct it to do. What redirect have you created for this?

**Comment by Plovst** [comment]
That's my understanding as well, but there is no redirect created for this.

In the list of redirects I only see on .se redirect, and it's not that one. The redirect doesn't appear in the log either.

**Comment by johngodley** [comment]
What about on the site page?

**Comment by Plovst** [comment]
It's set to remove www from the domain, but I've tried all three options with no luck.
<img width="937" alt="Screenshot 2023-01-03 at 15 13 36" src="https://user-images.githubusercontent.com/104761214/210374457-87b9ebee-6c1c-4475-b916-a5c3688e3548.png">

**Comment by johngodley** [comment]
I would disable all options. You haven't shown the other sections on the page, but disable all those too. Is the plugin installed on both zurface.dk and zurface.se? Or is .se mapped to .dk?

**Comment by Plovst** [comment]
There are no site aliases and no http headers. I've disabled force HTTPS now and no preferred domain - no luck.

.se is mapped to .dk with WPML.

**Comment by johngodley** [comment]
I don't know how WPML works and can't say if that is going to affect anything.

If you have disabled everything then Redirection is no longer performing a redirect. You should look at any caching you have.

**Comment by Plovst** [comment]
I just tested the redirect again, and now Wordpress is responsible for it. I'll look into that.

Thank you for your help so far.
