### ISSUE TITLE
"URL and server" redirection, doesn't show target url on "Redirects" page

### ISSUE THREAD

**Issue by kapela86** [johngodley/redirection#3519]
If you have "URL only" redirects, then both Source and Target are shown on "Redirects" page in main table view. But if you have "URL and server" redirects, then only Source is shown there. Can you fix it?
![image](https://user-images.githubusercontent.com/60604554/210521294-1cbf5af9-e48a-4afb-ad26-41e5e39ae79d.png)

**Comment by johngodley** [comment]
Yes, it's not shown as there can be two targets and I don't have a way of showing both consistently.
