### ISSUE TITLE
Problem starting Redirection 2.7.3

### ISSUE THREAD

**Issue by AZobenko** [johngodley/redirection#352]
```

```

Plugin: 2.7.3
WordPress: 4.8
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by johngodley** [comment]
Do you have any more details?

**Comment by johngodley** [comment]
Closing for now, please provide more details if the problem still exists
