### ISSUE TITLE
Redirect all the urls on my website

### ISSUE THREAD

**Issue by atsapepas** [johngodley/redirection#3526]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by atsapepas** [comment]
I want to change to the url structure on my website by removing the date. To do so I want to redirect all the older urls on my website. What are the steps tp do so?

**Comment by johngodley** [comment]
You can find out how to use the plugin here: https://redirection.me/support/
