### ISSUE TITLE
Regex working only when logged in

### ISSUE THREAD

**Issue by mcprod** [johngodley/redirection#3527]
Hi - I am trying to send all search results to a filtered archive page. So I created a regex redirect, which is working when logged in to WordPress, but it does not work for public users. I have tried clearing cache and turning off the HTTP Cache Header in Redirection. Any ideas on what might be going on, or what I am doing wrong?

Source URL:
`^.*\?s\=(.*?)\&jet.*`

Target URL:
`/articles/?_sf_s=$1`

**Comment by johngodley** [comment]
It will be a cache, either on your site or in your browser.

**Comment by mcprod** [comment]
I assumed so, but I have cleared site cache and tried it on different machines/browsers. All the other redirects work except that one.

**Comment by johngodley** [comment]
You may have more than one cache.

What is a URL that should be redirected with that?

**Comment by mcprod** [comment]
Here is an example (it is meant for anything entered into the offcanvas menu search).

https://founders.org/?s=parenting&jet_ajax_search_settings=%7B%22search_source%22%3A%5B%22post%22%2C%22podcast%22%2C%22library%22%2C%22study%22%2C%22review%22%2C%22message%22%5D%2C%22results_order_by%22%3A%22relevance%22%2C%22results_order%22%3A%22asc%22%2C%22search_in_taxonomy%22%3A%22yes%22%7D&post_type=post%2Cpodcast%2Clibrary%2Cstudy%2Creview%2Cmessage

Should redirect to (and does when logged in):

https://founders.org/articles/?_sf_s=parenting

**Comment by mcprod** [comment]
Any ideas on this? I tried clearing and turning off all site caching, deleting and re-adding the redirect with slight tweaks to the regex, and the result is the same. It works while logged in but not on the public front end. Super confused!

**Comment by mcprod** [comment]
Ok, this is fixed...turns out there was some conflict with the web host. Moving to a different server fixed it. Thanks!
