### ISSUE TITLE
Problem starting Redirection 5.3.6

### ISSUE THREAD

**Issue by Siphah** [johngodley/redirection#3528]
```
Uncaught SyntaxError: Unexpected identifier 'use' https://saruni.com/wp-content/plugins/redirection/redirection.js?ver=5.3.6-16d9cc72e7ac56bb977b78fce03e6ba0 2,Uncaught SyntaxError: Invalid or unexpected token https://saruni.com/wp-content/plugins/salient-core/includes/admin/assets/js/chosen/chosen.jquery.min.js?ver=1.9.7 2,Uncaught SyntaxError: Invalid or unexpected token https://saruni.com/wp-content/plugins/all-in-one-seo-pack/dist/Lite/assets/js/_plugin-vue2_normalizer.d86aa1f3.js 5,Uncaught SyntaxError: Invalid or unexpected token https://saruni.com/wp-content/plugins/all-in-one-seo-pack/dist/Lite/assets/js/_plugin-vue2_normalizer.d86aa1f3.js 5,Uncaught SyntaxError: Invalid or unexpected token https://saruni.com/wp-content/plugins/all-in-one-seo-pack/dist/Lite/assets/js/_plugin-vue2_normalizer.d86aa1f3.js 5
```

Plugin: 5.3.6 4.2
WordPress: 6.1.1 (single)
PHP: 8.0.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
JavaScript: https://saruni.com/wp-content/plugins/redirection/redirection.js?ver=5.3.6-16d9cc72e7ac56bb977b78fce03e6ba0
REST API: https://saruni.com/wp-json/

**Comment by johngodley** [comment]
Your file https://saruni.com/wp-content/plugins/redirection/redirection.js?ver=5.3.6-16d9cc72e7ac56bb977b78fce03e6ba0 seems to be corrupted. You might want to reinstall the plugin and make sure it isn't corrupted.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
