### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by Cycymap** [johngodley/redirection#3529]
I did a redirect from one site to this site: https://cyrilsansano.com.au/

And now Google is not opening https://cyrilsansano.com.au/

Saying cyrilsansano.com.au redirected you too many times.

![image](https://user-images.githubusercontent.com/117604801/213043104-bfcecfca-bef4-40e6-8f87-a05ba159c475.png)

**Comment by johngodley** [comment]
Your site is operating fine: https://redirect.li/http/?url=https%3A%2F%2Fcyrilsansano.com.au%2F

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
