### ISSUE TITLE
Is there a way to delete all redirects in one go? (We have over 3,000 pages of wrong redirects!)

### ISSUE THREAD

**Issue by Tagmeapp** [johngodley/redirection#353]
We have uploaded the wrong urls and would like to delete everything

**Comment by johngodley** [comment]
Yes, press the red delete button on the settings page to delete everything (all redirects, logs, and settings). You can then reactivate the plugin and start again

**Comment by Tagmeapp** [comment]
Perfect, thank you

Guy Ullmann
Sales & Marketing Director
Process Industry Informer
+44 (0) 1428 751188
guyullmann@piimag.com
www.piimag.com


<http://www.linkedin.com/in/guyullmann>




*PS. *Would you like to write for us? We're currently searching for
contributors for an exciting new section we're introducing! Find out more
here <http://www.processindustryinformer.com/landing-pages/write-for-us/>
