### ISSUE TITLE
Redirect Apache 403 or other error code pages to custom URL / WP page / post

### ISSUE THREAD

**Issue by MomentumRising** [johngodley/redirection#3534]
When I am not logged into the wp-admin, and browse to urls on the server that result in a 403 error, I get the default Apache 403 page displayed. Is it possible to display a custom WP page instead? Is it possible to have various WP pages be used for the various possible Apache error codes?

**Comment by johngodley** [comment]
Yes, but this is not something that Redirection can do. You will need to configure Apache to serve error pages in WordPress.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
