### ISSUE TITLE
Problem starting Redirection 5.3.9

### ISSUE THREAD

**Issue by AzharNiazi** [johngodley/redirection#3542]
Plugin: 5.3.9 4.2
WordPress: 6.1.1 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
JavaScript: https://speaksbeauty.com/wp-content/plugins/redirection/redirection.js?ver=5.3.9-d9e6fbf82d86a7f9b256e669c214cb3a
REST API: https://speaksbeauty.com/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This will be caused by another plugin.
