### ISSUE TITLE
URL redirects should be editable by selected users, NOT just administrators

### ISSUE THREAD

**Issue by yyil** [johngodley/redirection#3546]
### Summary

Certain plugins such as Yoast enable new WP user types, such as "SEO manager" and "SEO editor".
It makes sense for these types of users to be able to manage redirect URLs at minimum.

It makes sense to add this option under the plugin settings' "Options" page.
It can be offered as "Role Based Access", with a set of checkboxes for each type of user available.
It makes sense that "Admin" users are always selected (can't be changed)

### Actual Behavior

Redirect plugin settings are currently only available for Administrator users.
When logged in as a "SEO manager", I don't see the Redirect settings in the WP menu.

### Steps to reproduce

Create edit user who is not "admin", and try to add/edit the redirect URLs for the website.

**Comment by johngodley** [comment]
You can find informaiton about permissions here:

https://redirection.me/developer/permissions/

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
