### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by henryclarke10** [johngodley/redirection#3547]
Getting the error below, thanks for your help.

To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

Bad Data

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

Redirect https://aerobiotix.com/products/illuvia-500uv-2/ to https://aerobiotix.com/aerobiotix-hospital-air-disinfection-systems-illuvia-sense/

Explain what actually happened. If suggesting a new feature then explain what currently happens.

Bad data
There was a problem making a request to your site. This could indicate you provided data that did not match requirements, or that the plugin sent a bad request.

Please review your data and try again.

Plugin: 5.3.9 4.2
WordPress: 6.1.1 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
JavaScript: https://aerobiotix.com/wp-content/plugins/redirection/redirection.js?ver=5.3.9-d9e6fbf82d86a7f9b256e669c214cb3a
REST API: https://aerobiotix.com/wp-json/
Query: ?page=redirection.php

Error: Unable to add new redirect (redirect_create_failed)
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":297,"wpdb":"Unknown column 'match_data' in 'field list'"}}

Explain the steps involved to reproduce the problem

Source URL:
/products/illuvia-500uv-2/ 

Ignore case, Ignore slash

Target URL:
https://aerobiotix.com/aerobiotix-hospital-air-disinfection-systems-illuvia-sense/

Please list your browser, browser version, version of WordPress and Redirection plugin.

Chrome latest, 6.1.1, 5.3.9

**Comment by johngodley** [comment]
Go to the 'support' page, change the database version to 2.4, and follow the instructions.
