### ISSUE TITLE
Plugin Error on setting HTTP headers giving server error 500

### ISSUE THREAD

**Issue by LincT** [johngodley/redirection#3548]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Attempting to set more than one header under the site tab results in a server 500 error.

from php logs I found this in the logs:
 [10-Feb-2023 17:10:19 UTC] PHP Fatal error:  Uncaught TypeError: iconv(): Argument #3 ($string) must be of type string, array given in ./wp-content/plugins/redirection/models/header.php:115

### Actual Behavior

This seems to occur regardless of the order the headers are entered, but once getting to more than 1-2 headers and clicking save, it seems to come up.

### Steps to reproduce

using current wordpress installation in LAMP stack:
- ensure at least one header already exists, such as X-Content-Type-Options with value of "nosniff"
- set another header of Header set Strict-Transport-Security with value of "max-age=31536000; includeSubDomains"
- attempt to set a third such as Header set Referrer-Policy "strict-origin-when-cross-origin"

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
occurs across multiple clients wordpress installations
tested in chrome and firefox
php ranging from 7.4 to 8.0, this current report is from:
Plugin: 5.3.9 4.2
WordPress: 6.1.1 (single)
PHP: 8.0.27

**Comment by codepuncher** [comment]
I too am having this issue; I just add `X-Content-Type-Options` with `nosniff`, click Update and this will replicate the error for me.

Seems to be a bug introduced in 5.3.3. It is not an issue on older versions.

**Comment by johngodley** [comment]
This should be fixed.
