### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by JaegerKaiser** [johngodley/redirection#3549]
![image](https://user-images.githubusercontent.com/32634834/218424446-b0d68d59-6a12-4486-a91f-d298b4e6bdb9.png)

![image](https://user-images.githubusercontent.com/32634834/218424572-4ecf14f7-7dbf-476e-a7f0-9c0f31dc015b.png)

I can't seem to be able to add any redirects at all, probably an environment issue but not sure if you can point me in the right direction.

```
Plugin: 5.3.9 4.2
WordPress: 6.1.1 (single)
PHP: 7.4.28
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
JavaScript: https://lee-soft.com/wp-content/plugins/redirection/redirection.js?ver=5.3.9-d9e6fbf82d86a7f9b256e669c214cb3a
REST API: https://lee-soft.com/wp-json/
Query: ?page=redirection.php&sub=404s&groupby=url

Error: Invalid group when creating redirect (redirect)
Raw: {"code":"redirect","message":"Invalid group when creating redirect","data":{"status":400,"error_code":297}}
```

**Comment by johngodley** [comment]
How are you adding redirects? The usual method is not in a modal window like in your screenshot.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
