### ISSUE TITLE
https redirect issue

### ISSUE THREAD

**Issue by jeromee-zylun** [johngodley/redirection#355]
So we've recently moved our hosting server to a new provider. And during the process we've updated wordpress and all plugins.
We've also added ssl/https certificate for the main site.
Listings were migrated successfully and can be viewed on http, the issue is when you browse it on https, it says "The page or listing you are trying to reach no longer exists or has expired."

here are the links to our site:

working -> http://www.beyondcebu.com/cebu/argao-resorts/bamboo-paradise-beach-resort-argao
not working -> https://www.beyondcebu.com/cebu/argao-resorts/bamboo-paradise-beach-resort-argao

Please help.

browser: Chrome, Firefox
Redirection Plugin Version 2.7.3

**Comment by johngodley** [comment]
Can you explain how Redirection isnt working?

**Comment by jeromee-zylun** [comment]
Hi John,

if I rename the post_meta key "custom_permalink" the https url is working

working -> http://www.beyondcebu.com/cebu/argao-resorts/bamboo-paradise-beach-resort-argao
not working -> https://www.beyondcebu.com/cebu/argao-resorts/bamboo-paradise-beach-resort-argao

**Comment by johngodley** [comment]
I'm still not sure how this relates to Redirection? Have you created a redirect in Redirection that isn't working?

`custom_permalink` is not used by Redirection

**Comment by johngodley** [comment]
Closing for now, please provide more details if the problem still exists
