### ISSUE TITLE
Extension does 302 redirects instead of 301 redirects

### ISSUE THREAD

**Issue by brthiess** [johngodley/redirection#3555]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

Our team is using this extension to add redirects to our blog.  The extension shows that the redirects will be 301, but when we go to the urls, the redirect is actually a 302.

### Actual Behavior

The redirect is a 302

### Expected Behavior

The redirect is a 301

### Environment

Redirection version: 5.3.4
WP Version: 6.0.3
IIS: Window Server 2019

### Quick Fix

I dug into the source code to try and fix this.

Commenting out `status_header( $status );` in `redirection/modules/wordpress.php::wp_redirect` seems to fix the issue and make it use 301 redirects.  I have no idea why it fixes it, but the function has a comment which says: _"Fix for incorrect headers sent when using FastCGI/IIS"_.  Our PHP in IIS uses FastCGI, so presumably there is some connection.

**Comment by johngodley** [comment]
I don't have access to IIS and am not familiar with it. However, I'm sure that some of the users of the plugin are using it and given that this isn't happening for other people I suspect there is something specific to your setup or configuration.

Can you give an example URL where this is happening and show the redirect you have created for it?

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
