### ISSUE TITLE
Redirection doesn't load - Problem starting Redirection 2.7.3

### ISSUE THREAD

**Issue by 82concepts** [johngodley/redirection#356]
The plugin doesn't load and just repeatedly says "An error occurred loading Redirection" after the latest update. No other plugins were installed or anything else changed except for plugin updates. Any ideas on what could be causing this? Let me know what information you need.

```

Plugin: 2.7.3
WordPress: 4.8.1
PHP: 5.6.31
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by johngodley** [comment]
Can you look in your browser's error console and see if anything is shown there?

**Comment by 82concepts** [comment]
Hi there,

Crazy enough, it wasn't working the last two days for me but then I tried refreshing it again just now and everything is back up! There were no errors in the console and I didn't see anything else that stood out. Honestly, it was probably a server issue, our host is no good. 

Thank you for the quick response!!


Shane Pilster

Web.Print.Murals.Photography
w: www.82concepts.com
e: shane@82concepts.com
ph: 412.407.7ART
