### ISSUE TITLE
Redirect In Bulk

### ISSUE THREAD

**Issue by airdos360** [johngodley/redirection#3560]
In the latest versions, bulk redirect does not work when you "select all".   It will only do bulk redirects for one page (20) results.

**Comment by johngodley** [comment]
Yes, it's not really designed to do that. I would say that if you are trying to redirect everything then you are probably using the plugin incorrectly - it's generally not necessary to do that.

**Comment by johngodley** [comment]
Closing for now please reopen with more details.
