### ISSUE TITLE
Search Improvement

### ISSUE THREAD

**Issue by airdos360** [johngodley/redirection#3561]
I would like to request a feature to search 404s with a Regex.

**Comment by johngodley** [comment]
What kind of things are you wanting to search for?

**Comment by airdos360** [comment]
I would like to be able to search something like ^\/news\/(.*?)\/feed

**Comment by johngodley** [comment]
Ok, the plugin is unlikely to provide a regex search as it's a complicated thing to add. There are a lot of other search filters that may help you narrow down the search results.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
