### ISSUE TITLE
Bymistakenly we have delte redirection instead of disable...

### ISSUE THREAD

**Issue by Jineshpanchal** [johngodley/redirection#3563]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Bymistakenly we have delete redirection instead of disable...
Now how to stop redirection, because we could not see any that one in redirect tab...

**Comment by johngodley** [comment]
If you deleted or disabled the plugin then it is not doing anything.
