### ISSUE TITLE
Redirections do not work when "undefined" is in the path

### ISSUE THREAD

**Issue by chrisdpeters** [johngodley/redirection#3564]
### Summary

When setting up a Source URL like `/login/undefined` or RegEx like `^\/login\/undefined\/?`, the redirection is not triggered. 

### Actual Behavior

Accessing the redirection URL throws a 404 and does not perform the redirection.

### Steps to reproduce

1. Add new redirection
2. Enter `/login/undefined` as the Source URL
3. Enter anything for the Target URL. In this case, I did `https://www.example.com/login/?undefined=true`
4. Choose 302 as the HTTP code (guessing this has no effect but was what I was trying to do)
5. Access the redirection URL to test: https://www.example.com/login/undefined
6. See 404 error instead of redirection

### Environment

Redirect v5.3.9
WordPress v6.1.1
Chrome v110.0.5481.100 (or using the tool at www.redirect-checker.org)

**Comment by chrisdpeters** [comment]
FWIW, I suspect that the word "undefined" in the path is causing the issue. If I change it to "undefine" without the "d," the redirection works.

**Comment by johngodley** [comment]
`/undefined` works fine for me, and there is no reason why it wouldnt work. I would imagine this is something else on your site.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
