### ISSUE TITLE
Permalink Migration deletes query strings, although setup to pass-through

### ISSUE THREAD

**Issue by larsschellhas** [johngodley/redirection#3571]
### Summary

Previously I would link to an article like this: https://theclimateinnovator.com/2023/03/space-based-solar-power-is-our-renewable-future/?utm_source=LinkedIn&utm_medium=social&utm_campaign=post-sbsp-overview

I moved the page to https://schellhas.engineering. A first 301 redirect (outside of wordpress) forwards to **https://schellhas.engineering**/2023/03/space-based-solar-power-is-our-renewable-future/?utm_source=LinkedIn&utm_medium=social&utm_campaign=post-sbsp-overview

Then, the permalink redirect is used (I guess that this might be causing problems) to remove "/2023/03/" and the slug of the article has changed. so that the final redirect actually leads to: https://schellhas.engineering/space-based-solar-power/

As you can also see in the screenshot below, on the redirect handled by the plugin, all query strings are removed.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/14281234/224513144-d6bff803-e79e-40fd-86e7-c3b50942f6c7.png">

This shouldn't happen, as I have setup query matching as "Ignore & pass all query parameters"
<img width="593" alt="image" src="https://user-images.githubusercontent.com/14281234/224513237-a3c40b1d-2b58-429a-8e9d-a095cd1ec087.png">

Equally so on the individual redirect:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/14281234/224513264-c41cac70-e043-41e7-ac8f-937a75150648.png">

### Steps to reproduce

Open the link on the top and see for yourself in the dev tools.

### Environment

Microsoft Edge 110.0.1587.63
WordPress 6.1.1
Redirect 5.3.9

**Comment by johngodley** [comment]
Redirection is not involved in any part of this:

https://redirect.li/http/?url=https%3A%2F%2Ftheclimateinnovator.com%2F2023%2F03%2Fspace-based-solar-power-is-our-renewable-future%2F%3Futm_source%3DLinkedIn%26utm_medium%3Dsocial%26utm_campaign%3Dpost-sbsp-overview

**Comment by larsschellhas** [comment]
What?

What about the part "redirected by WordPress"?

I mean, literally, I have setup the redirects in Redirect.
How else would WordPress redirect from the old permalink structure and the old slug to the correct one?

**Comment by johngodley** [comment]
Sure, it says WordPress. It does not say Redirection.

> How else would WordPress redirect from the old permalink structure and the old slug to the correct one?

I can't tell you how that is happening - that is something you will need to investigate (Redirection may be able to help there with it's logging feature). I can tell you that it is not Redirection.

**Comment by larsschellhas** [comment]
You are right. Apparently, because I changed the slug, wordpress also added a "_wp_old_slug" entry to the postmeta table, that's why it's redirecting there.

However, when I look at pages where I haven't changed the slug, the redirect comes from Redirection and also removes the parameters: 
https://redirect.li/http/?url=https%3A%2F%2Ftheclimateinnovator.com%2F2022%2F08%2Fcarbon-offsetting-should-be-your-priority%2F%3Futm_source%3Dcarbonside%26utm_medium%3Dguest-post%26utm_campaign%3Dguest-post-carbonside-measuring-business-emissions

**Comment by johngodley** [comment]
That doesn't match the redirect you originally showed so I don't know what settings you have used. Redirection will only redirect to the URL you configure. It won't remove parameters unless you have told it do that.

Either your settings are not right, or your server is removing the parameters. This can happen with some hosts with UTM parameters and you will need to contact your provider about it.

**Comment by larsschellhas** [comment]
Alright, thank you for your support.

**Comment by larsschellhas** [comment]
I was able to fix it for the posts where I had changed the slug, by manually adding a redirect from the previous slug+permalink structure directly to the new slug+new permalink structure.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/14281234/224546557-72993c94-1036-4e54-9388-6a6b39dca78f.png">

This works fine now, as you can see (although it would be nice, if Redirect was able to compose all redirects into a single redirect from the beginning. 
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/14281234/224546586-c8491dea-5bf5-40b3-91cf-0dfa696e22e8.png">

**However** for posts handled only by the **Permalink Migration** feature, the problem persists - although it is handled by Redirection and is setup to pass query params by default.

**Comment by johngodley** [comment]
> it would be nice, if Redirect was able to compose all redirects into a single redirect from the beginning

It is your responsibility to do this as it's impractical for the plugin to handle, particularly over multiple domains.

> However for posts handled only by the Permalink Migration feature, the problem persists - although it is handled by Redirection and is setup to pass query params by default.

Redirection does pass query parameters in a permalink migration. As mentioned above this is likely a problem with your server removing them.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
