### ISSUE TITLE
List of past redirections disappeared

### ISSUE THREAD

**Issue by GwenetteWriter** [johngodley/redirection#3574]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

List of redirections prior to 03.13,2023 has disappeared.

### Actual Behavior

Opened Redirection tool today to add a new redirection and saw list with only 2 redirections. Yesterday I saw many more.

### Steps to reproduce

See above

### Environment Identical to yesterday

WP 6.03 Redirection 5.3 Chrome Version 111.0.5563.65 (Official Build) (64-bit) Windows 10
Site: youthtoday.org

**Comment by johngodley** [comment]
Why would they have disappeared? The plugin doesn't auto-delete things, so the items have either been deleted (intentionally or otherwise), or something has affected the database. I'm not sure what else I can say here.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
