### ISSUE TITLE
Mention X-WP-Nonce in Common Problems

### ISSUE THREAD

**Issue by mackensen** [johngodley/redirection#3575]
This is a documentation suggestion for https://redirection.me/support/problems/. If you're using an allowlist with headers, you need to allow `X-WP-Nonce`, or Site Health checks will always fail with `rest_forbidden`. It's not obvious and nothing really calls it out. See also this entry in the [REST API Handbook](https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/):

> For developers making manual Ajax requests, the nonce will need to be passed with each request. The API uses nonces with the action set to wp_rest. These can then be passed to the API via the _wpnonce data parameter (either POST data or in the query for GET requests), or via the X-WP-Nonce header. If no nonce is provided the API will set the current user to 0, turning the request into an unauthenticated request, even if you’re logged into WordPress.

I suspect this is at the bottom of a number of the 401 issues folks report here. Thanks for all the work you do to maintain this plugin.

**Comment by johngodley** [comment]
Thanks. I've updated the documentation.
