### ISSUE TITLE
REST API doesn't work.

### ISSUE THREAD

**Issue by devmoonho** [johngodley/redirection#3579]
Plugin: 5.3.9 4.2
WordPress: 6.1.1 (single)
PHP: 8.0.16
Browser: Chrome/110.0.5481.178
JavaScript: https://www.tptmusk.net/wp-content/plugins/redirection/redirection.js?ver=5.3.9-d9e6fbf82d86a7f9b256e669c214cb3a
REST API: https://www.tptmusk.net/wp-json/
Query: ?page=redirection.php

Hello

As shown in the attached picture, the REST API progress stays at 0%. And I don't see the Redirects list.
However, you can check the data by checking the file when exporting.

I tried disabling all plugins, but it doesn't improve.
What action should I take in this case?

Thank you

![2023-03-16 21 06 26](https://user-images.githubusercontent.com/26807805/225620877-92bd7d26-9ebd-4f58-86ae-2174e6c90ed7.jpg)

![2023-03-16 21 40 36](https://user-images.githubusercontent.com/26807805/225620704-e89de244-e88b-42a7-97da-bee31bf44cdc.jpg)

**Comment by johngodley** [comment]
You can see that the requests are returning a 403 error. What is causing that on your site? It is not standard behaviour.

**Comment by devmoonho** [comment]
I tried to analyze why, but I'm not sure.
However, the first symptom occurred after saving the redirect below.

Source : ^/\d{4}/\d{2}/\d{2}/(.*)
Target : https://www.tptmusk.net/$1

What actions can I take?
For example, delete the corresponding row from the database or is there another way?

**Comment by devmoonho** [comment]
After logging out and logging in again, it works normally.
thank you.
