### ISSUE TITLE
Query parameter redirect giving 404 in the redirect checker tool

### ISSUE THREAD

**Issue by justinmaurerdotdev** [johngodley/redirection#3580]
### Summary
The redirect checker is incorrectly handling the question mark for query parameters, even though **the actual redirect does work**.

### Actual Behavior
When I use the redirect checker, it looks like it urldecode()s the question mark, so the redirect doesn't even happen. 

<img width="790" alt="Screenshot 2023-03-17 at 10 27 06 AM" src="https://user-images.githubusercontent.com/3308529/225965210-46c7f089-a3b5-40fd-9338-46da7ce8f8ac.png">

### Steps to reproduce
I set up a new redirect with /?p=8226720 as the source, with the default "ignore slash" setting and "exact match in any order" for the parameter handling. 

<img width="1164" alt="Screenshot 2023-03-17 at 10 26 55 AM" src="https://user-images.githubusercontent.com/3308529/225965208-b38f0602-1265-456e-ba69-c0b447e449be.png">

### Environment
Firefox on Mac
WordPress 6.1.1
Redirection 5.3.9

**Comment by johngodley** [comment]
Even though the display is encoding the redirect, it still seems to be performing correctly. I think that something else is performing the above redirect.
