### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by NucleuxCO** [johngodley/redirection#3586]
```
Plugin: 5.3.9 4.2
WordPress: 6.1.1 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
JavaScript: /wp-content/plugins/redirection/redirection.js?ver=5.3.9-d9e6fbf82d86a7f9b256e669c214cb3a
REST API: /wp-json/
Query: ?page=redirection.php&filterby%5Burl%5D=

Error: Invalid redirect details (redirect_update_failed)
Raw: {"code":"redirect_update_failed","message":"Invalid redirect details","data":{"status":400,"error_code":325}}
```

**Comment by johngodley** [comment]
What are you doing when this happens?

**Comment by skyechilton** [comment]
same issue. trying to update a redirect. 

Plugin: 5.3.10 4.2
WordPress: 6.2 (single)
PHP: 8.1.17
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
JavaScript: DOMAIN/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: DOMAIN/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect details (redirect_update_failed)
Raw: {"code":"redirect_update_failed","message":"Invalid redirect details","data":{"status":400,"error_code":325}}
