### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by AXJNEWS** [johngodley/redirection#3588]
```
Plugin: 5.3.9 4.2
WordPress: 6.1.1 (single)
PHP: 8.0.28
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
JavaScript: https://axjnews.uk/wp-content/plugins/redirection/redirection.js?ver=5.3.9-d9e6fbf82d86a7f9b256e669c214cb3a
REST API: https://axjnews.uk/wp-json/
Query: ?page=redirection.php&sub=options

Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON (SyntaxError)
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

**Comment by johngodley** [comment]
As shown above you will need to fix your REST API: https://axjnews.uk/wp-json/

**Comment by AXJNEWS** [comment]
Thank you but no luck?
Best wishes,

**Comment by johngodley** [comment]
Your WordPress REST API is broken. You will need to fix it. It is not connected to Redirection itself.

**Comment by AXJNEWS** [comment]
Thank you John. Our Team in the UK was able to sort it out.
** AXJ UK GLOBAL NEWS NETWORK **


| 
| 
|  | 
** AXJ UK GLOBAL NEWS NETWORK **

AXJ UK GLOBAL NEWS NETWORK
 |

 |

 |


You and your Team are welcome to join us any time on AXJ as we grow our global network.
Best wishes,
***@***.*** ® GLOBAL NEWS NETWORK


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
AXJ ® GLOBAL NEWS NETWORK

Social justice through legal action Breaking news and analysis from AXJ.NEWS,Politics, world news, photos, video...
 |

 |

 |

 

    On Monday, March 27, 2023 at 04:53:32 AM PDT, John ***@***.***> wrote:  
 
 This message is eligible for Automatic Cleanup! ***@***.***) Add cleanup rule | More info
 


Your WordPress REST API is broken. You will need to fix it. It is not connected to Redirection itself.
