### ISSUE TITLE
https redirection issue

### ISSUE THREAD

**Issue by editeca** [johngodley/redirection#359]
Hello,

I have my web with https protocol. However, I have done a redirection with your plugin and it sends me to an unsafe protocol page.

To text this example you can go to https://online.revitalacarta.com/cursos-online/, then click on the second image. The page opened after it is not safe.

The redirection I have done is 
/course/curso-revit-gratis-inicio/
https://online.revitalacarta.com/curso-revit-gratis/

Could you help me understand the problem, please?

Thanks in advance.

**Comment by johngodley** [comment]
The page is redirecting to an https URL:

```
curl -v https://online.revitalacarta.com/course/curso-revit-gratis-inicio/                                                                                                                 ⏎
*   Trying 46.30.213.159...
* TCP_NODELAY set
* Connected to online.revitalacarta.com (46.30.213.159) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.revitalacarta.com
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> GET /course/curso-revit-gratis-inicio/ HTTP/1.1
> Host: online.revitalacarta.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 04 Sep 2017 17:20:59 GMT
< Server: Apache
< X-Powered-By: PHP/5.6.31
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Vary: Accept-Encoding,Cookie
< Set-Cookie: wordpress_test_cookie=WP+Cookie+check; path=/; domain=online.revitalacarta.com; expires=Tue, 05-Sep-2017 17:20:59 GMT
< Set-Cookie: PHPSESSID=avsb3v91mrccm42s413kebdvn1; path=/
< Location: https://online.revitalacarta.com/curso-revit-gratis/
< Content-Type: text/html; charset=UTF-8
< X-Varnish: 732172352
< Age: 0
< Via: 1.1 varnish (Varnish/5.1)
< Transfer-Encoding: chunked
< Connection: keep-alive
```

Please clear your browser cache.

**Comment by editeca** [comment]
Hello,

However, the result page is not safe. Please, see attachment.
![https error](https://user-images.githubusercontent.com/31628770/30038528-f92a97f4-91c5-11e7-9aba-74625d54b0c8.png)

**Comment by johngodley** [comment]
Can you explain more about what you are referring to - I don't understand. Redirection has nothing to do with your SSL certificate. The debug I listed above shows that the redirect is happening. Is there another reason why you think Redirection is affecting your SSL certificate?

**Comment by johngodley** [comment]
Closing, please reopen with more information.
