### ISSUE TITLE
Not exactly a bug, more like a feature request

### ISSUE THREAD

**Issue by iced-queen** [johngodley/redirection#3590]
I think it'd be pretty useful if you could see **when a redirection was added** instead of just **Last Access**.
So maybe add a field called **Added** with the date when it was added, just like **Last Access** has.

![img](https://i.gyazo.com/4e681d373a77ecfdb367387b463d1470.png)
![img](https://i.gyazo.com/8e5deeda399710acd1cbdfb7ecde3cb1.png)

**Comment by johngodley** [comment]
See https://github.com/johngodley/redirection/issues/573
