### ISSUE TITLE
Missed sprintf

### ISSUE THREAD

**Issue by Beee4life** [johngodley/redirection#3592]
I wanted to add a redirect and delete the items with that url.

I got this notice, which has a sprintf value missing.

![Screenshot 2023-03-30 at 12 23 23](https://user-images.githubusercontent.com/4508731/228807897-7c1aa310-19fc-4197-9288-d140b61da6b1.png)

WP 6.2  
Plugin version 5.3.9
PHP 8.x

**Comment by johngodley** [comment]
Sure, please see #3513 for more details.

**Comment by Beee4life** [comment]
sorry, missed that one while searching.
