### ISSUE TITLE
Update redirect error - Invalid Redirect Action

### ISSUE THREAD

**Issue by fusionzz** [johngodley/redirection#3594]
### Summary

Trying to update a redirect

### Actual Behavior

{
    "code": "redirect",
    "message": "Invalid redirect action",
    "data": {
        "status": 400,
        "error_code": 319
    }
}

### Steps to reproduce

POST Request
URL: https://website.com/wp-json/redirection/v1/redirect/2?status=disabled

### Environment

Postman
Redirection version 5.3.9

**Comment by johngodley** [comment]
Trying to update it how? It is refusing the action

**Comment by fusionzz** [comment]
> Trying to update it how? It is refusing the action

@johngodley 
Update it in any way, in this case I'm trying to update the status to disabled through a parameter in the URL. Am I performing the request incorrectly? Even if I just send a post request with no parameters (/redirection/v1/redired/2) I get the same error.

**Comment by johngodley** [comment]
If you monitor what the plugin does when it disables a redirect you will be able to see how your request differs.
