### ISSUE TITLE
Sitemap has redirected urls with 301 error

### ISSUE THREAD

**Issue by staffcosy** [johngodley/redirection#3598]
Hello

I contact you after having performed all the checks mentioned in the "Reporting Bugs" guide and I have not found an answer in the support forums, but I apologize if I missed the information that was already present.

I'm opening this ticket because we're encountering a problem with some urls redirected via Redirection: it happens that **some of these redirected urls with the following characteristics (I attach screenshots) end up in sitemaps with a 301 error return**.
These are exclusively /portfolio/ pages, if this information can be useful.

Could this be due to the plugin?
How could we avoid this situation?

Browsers: Google Chrome 111.0.5563.110
WordPress version: 6.1.1
PHP version: 7.4.33
Plugin version: 5.3.10

Thanks in advance!
Best regards

**Comment by johngodley** [comment]
I don't know what the screenshot is showing and there isn't enough information to answer the question itself. What do you mean by they end in a sitemap? What URL and what redirect have you created for it?

**Comment by staffcosy** [comment]
I'll try to be more specific: Redirection was used (automatically by Wordpress) to redirect portfolio pages to which the url was changed.
All right up to here, except that the old urls (the redirected ones) keep appearing in the current sitemap

**Comment by johngodley** [comment]
Ok, but Redirection isn't involved with sitemaps. Whatever produces the sitemap will need to remove pages that no longer exist.

**Comment by staffcosy** [comment]
Ok, no problem. Thank you
