### ISSUE TITLE
Possible to have a "Hits" column in the 404's logs?

### ISSUE THREAD

**Issue by jordymeow** [johngodley/redirection#36]
With robots, hacker's scripts and other garbage is very hard to actually analyze this log; I need to export it and analyze it. Actually what I need is mainly a "Hits" column in the 404's logs and to order it by this number of occurrences. That way I could easily detect the most visited 404 pages and they should be the ones requiring a fix. Would that be possible to add? Thanks a lot, this plugin is awesome otherwise.

**Comment by johngodley** [comment]
Yep, planning to add this soon!

**Comment by tigroumeow** [comment]
Super, that's excellent! I have been (silently) been waiting for this for almost two years I think, I didn't knew it was planned!

**Comment by josefresco** [comment]
Is this feature still planned?  I too would love this ability.  Making use of the 404 log can be difficult.

Grouping and providing a "hit count" for each 404 would help me identify which 404's to focus on.

**Comment by sconnellcom** [comment]
These SQL strings will give you the report(s) you are looking for. 

**Top 20 404 paths**
`Select url, count(*) as hits from wp_redirection_404 group by url order by hits desc limit 20`

**Top 20 404 paths excluding the Query String**
`Select SUBSTRING_INDEX(url,'\?',1) as path, count(*) as hits from wp_redirection_404 group by path order by hits desc limit 20`

**Comment by johngodley** [comment]
Added in #1232
