### ISSUE TITLE
Subdomain to domain

### ISSUE THREAD

**Issue by trassuchine** [johngodley/redirection#360]
I had a subdomain for my ecommerce site but I moved the ecommerce site into the normal domain structure.

ie  subdomain.mysite.com to now mysite.com/store

When I try and add a redirection and put the source url as the subdomain it just automatically converts it to a "*" on save. Is it not possible to do subdomain redirections?

**Comment by johngodley** [comment]
Redirection works on the domain it is installed on. If you want to redirect from another domain (sub or otherwise) then it needs to be installed on that domain too.

**Comment by trassuchine** [comment]
Thank you John! The subdomain had a cname that pointed to a 3rd party location, so I changed that cname in my DNS editor to just point back at my root site. So it should be...
