### ISSUE TITLE
increased 404s on set redirects

### ISSUE THREAD

**Issue by justinsykes31** [johngodley/redirection#3601]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

We are seeing 100s of 404s a day on our site. 175,240 items in total. Some are already set up redirects. On Monday our homepage redirected to "target URL" which obviously threw a 404. 

### Actual Behavior

Redirects to redirect to target url without 404ing

### Steps to reproduce

Each day new redirects which did work are redirecting to 404 pages

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Chrome Version 111.0.5563.146 (Official Build) (x86_64)
WordPress - Version 6.1.1
Plugin - Version 5.3.6

**Comment by johngodley** [comment]
I don't understand the problem. What isn't working? Can you give an example?

**Comment by justinsykes31** [comment]
thanks for the fast response. 

Redirects are randomly redirecting to the 404 page. 

e.g. https://humentum.org/policy/ was redirecting to https://humentum.org/advocacy/ but then yesterday just started redirecting to 404. We recreated the redirect and its working. 

Also the homepage randomly redirected to https://humentum.org/target%20%url I went into the dashboard and there was a redirect set to redirect the homepage to https://humentum.org/target%20%url two or three times. I deleted them and fixed that.

**Comment by johngodley** [comment]
Why are things randomly redirecting? That isn't something the plugin can do and it wouldn't make sense for it to start behaving differently.  

> yesterday just started redirecting to 404

Specifically what do you mean by this? Was it redirecting to another URL that doesn't exist? If so what was that URL? Or was the URL returning a 404 without redirecting?

> there was a redirect set to redirect the homepage

Redirects will only be created if you manually create them yourself, or you have URL monitoring enabled and have changed something (and it will then redirect from the old page to the new one). Is it possible someone created it? Is it possible something else created it?

I will note you are using an older version of the plugin too.

**Comment by justinsykes31** [comment]
hi, thanks, ok we are in the process of updating the plugin. 

it was returning a 404 without redirecting https://humentum.org/policy/ 

The homepage, a redirect was set up to redirect to /target url which 404'd which we did not set up. I'll get the plugin updated and troubleshoot some more. 

Thanks
