### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Yossifsolman** [johngodley/redirection#3602]
The new configuration of your plugin not working.
First things are not clear, for example:

![image](https://user-images.githubusercontent.com/104964400/231634042-298e9eef-6526-4d11-a2d4-b652ff4ec911.png)

What needs to be here?
And why the plugin not configure that automatically.

The second issue, plugin not process himself and show blank page:
![image](https://user-images.githubusercontent.com/104964400/231634241-a28ceea6-4ba0-4b1d-b077-6a658d900727.png)

The plugin was working before this “Testing” and all the new configuration you did for the plugin.

I am, personally, try to delete the old permalinks redirect by the WordPress Core.
I know your plugin do it perfectly.
But for that he must to work, and be more friendly for the user.

Be happy for your help.

**Comment by johngodley** [comment]
> What needs to be here?

Nothing. It's an example and says it is an example

> The second issue, plugin not process himself and show blank page:

You will need to see what is happening on your site to cause this to happen. You can look in your browser's developer console, for example.

> I am, personally, try to delete the old permalinks redirect by the WordPress Core.

The plugin does not do this.
