### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by mdpixelz360** [johngodley/redirection#3605]
Plugin: 5.3.10 4.2
WordPress: 6.2 (single)
PHP: 8.0.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 X-Middleton/1
JavaScript: /wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: /wp-json/

**Comment by johngodley** [comment]
The details are shown in the message. The plugin file cannot be loaded: https://hippainhelp.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
