### ISSUE TITLE
Updating Redirect Not Working

### ISSUE THREAD

**Issue by mg-cam** [johngodley/redirection#3607]
When I try to POST on any of my redirects, no matter what I do, I get an error. All of the GET requests that I make work. What am I missing here. It doesn’t seem to matter how I add in the :id into the URL, it still fails. Am I formatting this incorrectly or is there another error?

<img width="756" alt="image" src="https://user-images.githubusercontent.com/77744684/233503660-423f9c74-4591-43c1-b25e-7a674cbc43ef.png">

**Comment by johngodley** [comment]
I don't really know what I'm looking at there or what you are trying to do. The plugin uses the WordPress REST API so your request will need to match whatever requirements that enforces. The error message indicates you have not met those requirements.

You may want to look at how the plugin makes requests when in use and try and match those.

**Comment by mg-cam** [comment]
I'm simply trying to make a POST request and it isn't working. If, for example, I wanted to make a POST request to update a redirect with an ID of 6, gore would I need to format that?

Is it one of these formats?
- HTTPS://www.example.com/wp-json/redirection/v1/redirect/:id (and adding id=6 as a parameter)
- HTTPS://www.example.com /wp-json/redirection/v1/redirect/:6
- some other way

It all fails when I try to specify the ID of the redirect I want to update.

**Comment by johngodley** [comment]
The second one - `:1` is a placeholder.

If it fails then it is because something is wrong with your request. It doesn't necessarily mean the URL is wrong. You should look at what the plugin does when updating a redirect and compare yours to that.

**Comment by mg-cam** [comment]
This screenshot shows a simple iOS shortcut I am trying to run. You can see the request type and details, minus the URL domain. It is a GET that used basic authentication and calls the plugin in the way you mentioned, but the return shows no such route. Any ideas on what needs to be updated?

![image](https://user-images.githubusercontent.com/77744684/234137588-e3a049bf-e6db-4c59-8565-2f7f1ed4c61e.jpeg)

**Comment by johngodley** [comment]
Basic authorisation is unlikely to be supported.

You still have `:1` in the URL.

There are other places where you find help about general WordPress REST API questions.
