### ISSUE TITLE
Redirect from folder to link

### ISSUE THREAD

**Issue by cardinalservices** [johngodley/redirection#361]
### Summary

our marketing department would like to track 2 links they want to create, domain.com/location1 > http://domain.com/somethingthatisalreadysetup/

and domain.com/location2 > http://domain.com/somethingthatisalreadysetup/ (yes same link)

### Actual Behavior

page not found, keeps adding the /location1 to the end of http://domain.com/somethingthatisalreadysetup/location1

**Comment by johngodley** [comment]
How have you created the redirects? Can you share a screenshot when editing each of the two redirects?

**Comment by johngodley** [comment]
I tried accessing the URL but I just get a 503 error. There's not much I can say based on the information above and it would help to test a URL to see what the response is.

**Comment by cardinalservices** [comment]
What exactly are you not getting to?

http://www.cardinal-services.com/oregon-retirement-plan/ works fine

if I goto http://www.cardinal-services.com/compliant it is going to page not found and not redirecting

That is the issue.

**Comment by johngodley** [comment]
```
Your access to this site has been limited

Your access to this service has been temporarily limited. Please try again in a few minutes. (HTTP response code 503)

Reason: Access from your area has been temporarily limited for security reasons.
```

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
