### ISSUE TITLE
hi my new issue with redirection plugin 

### ISSUE THREAD

**Issue by bsd-group** [johngodley/redirection#3610]
when i try to redirect a url in the plugin redirection section some pages of my website returns this error in the browser

This page isn’t working right nowbsd-group.ir redirected you too many times.
To fix this issue, try [clearing your cookies](https://go.microsoft.com/fwlink/?linkid=2112473).
ERR_TOO_MANY_REDIRECTS

**Comment by johngodley** [comment]
You have created a loop. You will need to edit your redirect so the loop doesn't occur.

**Comment by bsd-group** [comment]
thanks

**Comment by bsd-group** [comment]
hi
i was unable to resolve that issue
 i could not find any option to change the setting to prevent the loop
i need more detailed information and guidance to where i can stop that loop
please guide me more precisely
thanks

**Comment by johngodley** [comment]
There is no setting to prevent a loop.

You have created a redirect. It is redirecting to itself.

You should edit that redirect so it doesn't do that.

I do not know what you have created or what the URL is so I am unable to give more specifics - maybe you want to include that in your report.

There is full documentation for the plugin here:

https://redirection.me/support/

This is not a support forum but a place to report bugs.

**Comment by bsd-group** [comment]
hi
i use a plugin called digits which gives the facility to my website allowing new users to sign up using their phone number via sms confirmation code so when someone logs in to my website if the person directly clicks on login button it returns 404 error
otherwise everything is ok now that the 404 page appears due to a bug in the plugin
i need to redirect the page in to my account page so the redirection plugin works well in that condition but the issue of loop happens in other page like when someone logs out and the error of redirection loop appears in the browser
i should mention that that because the digits plugin i use for my website is a manipulated one i don't have access to the developer 
now i'll try what the documentation of the plugin offers me to solve and inform you if it resolves
thanks

**Comment by johngodley** [comment]
If you put the URL here I can look directly.

**Comment by bsd-group** [comment]
hi 
I resolved the issue by changing the URL of the redirect and removing the HTTPs:// before it
thanks
