### ISSUE TITLE
When I try the redirection I see it don't work

### ISSUE THREAD

**Issue by VictorE100** [johngodley/redirection#3611]
For example I tried to redirect from this link https://www.investigacionesdevictore100.com/2023/01/teoria-de-calculo-de-que-astro.html to this link https://elcaminoquecreas.com/2023/01/teoria-de-calculo-de-que-astro-encarnamos/ and at least in my computer and smartphone it don't work. I don't know what is happening, could you help me?

**Comment by johngodley** [comment]
What redirect did you create?

Did you look at https://redirection.me/support/problems/url-not-redirecting/ ?

**Comment by VictorE100** [comment]
The redirection has a code 301. I tried to clear my browser cache but I have the same problem.

**Comment by johngodley** [comment]
Please check the guide again, specifically around server configuration.

**Comment by VictorE100** [comment]
I don't know much of this topic, I read that part of F.A.Q. and it leads me to the same page 'Why is a URL not redirecting?'. A year ago or more I used the platform blogger, where I made my old blog, to redirect the errors page 404 to a link, I did this several times with several posts but not to all and the example I gave here is not using redirection to that link of blogger (https://www.investigacionesdevictore100.com/2023/01/teoria-de-calculo-de-que-astro.html). I don't know if there is my problem.

**Comment by johngodley** [comment]
> Server Configuration
> If your URL is a file then your web server may be configured to handle it directly rather than pass the request through to PHP and WordPress.
> 
> This means that Redirection could be unable to redirect it. For example, a URL that ends with .pdf, .html, .doc, .png, .jpg, .php, .mp3, .zip, .aspx etc.
> 
> Solutions:
> 
> Delete the file from your server. If the file exists then it may prevent any redirects.
> [Save the redirect to Apache](https://redirection.me/support/import-export-redirects/) .htaccess or as Nginx rewrite rules.

**Comment by VictorE100** [comment]
Thank you very much for your explanation. Oh now I understand, the links ends with .html but I don't have these files, blogger creates posts that ends with .html by default, so I can't redirect these post from blogger to wordpress?

**Comment by johngodley** [comment]
No, that's not what it says. You may need to export to .htaccess. You could also speak to your host provider and ask them why you cannot redirect a .html file.

**Comment by VictorE100** [comment]
I'm asking to my host provider, I'll tell you latter.

**Comment by VictorE100** [comment]
I solved this in other form, with coding in blogger, my host provider told me there was not a problem with the host with redirectioning links.

**Comment by johngodley** [comment]
The URLs were on blogger? Then of course it's not possible to use Redirection for them.

**Comment by VictorE100** [comment]
The URLs are from blogger to wordpress.
