### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by mauamolat** [johngodley/redirection#3612]
Plugin: 5.3.10 4.2
WordPress: 6.2 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 X-Middleton/1
JavaScript: https://www.mauwiks.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.mauwiks.com/wp-json/

**Comment by johngodley** [comment]
Please read the onscreen instructions. This is likely caused by another plugin.
