### ISSUE TITLE
Exported CSV Not Providing Hit Values

### ISSUE THREAD

**Issue by exclaimer** [johngodley/redirection#3613]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

When exporting to a CSV file the Hits Column is not populating

### Actual Behavior

Hits Column Contains No Values in Exported CSV

### Steps to reproduce

In the Import/Export Tab I navigate to Export.  From the Dropdown Menu I select WordPress redirect and CSV and click Download

### Environment

Chrome, Version 112.0.5615.138 (Official Build) (64-bit), WordPress 6.2, Redirection Plugin Version 5.3.10

**Comment by johngodley** [comment]
Correct, as documented in the plugin and the support site the hits column is not exported.
