### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by bwood1993** [johngodley/redirection#3618]
```
SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list. https://www.jrsusa.org/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2
```

Plugin: 5.3.10 4.2
WordPress: 6.2 (multi)
PHP: 7.4.15
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
JavaScript: https://www.jrsusa.org/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.jrsusa.org/wp-json/

**Comment by johngodley** [comment]
As explained on the page this is likely caused by another plugin.
