### ISSUE TITLE
Unable to run unit tests locally

### ISSUE THREAD

**Issue by hellatan** [johngodley/redirection#3619]
### Summary

I'm trying to run the php unit tests locally but am unable to. I'm trying to run these locally so I can test out a use case when there is an `?amp` query parameter in the URL that was put there by the AMP plugin.

### Actual Behavior

When running `yarn php:tests`, I keep on receiving this error:

```
🌯  /plugins/redirection 🌮  trunk 🍔
yarn test:php
yarn run v1.22.19
$ composer run-script test
> ./vendor/bin/phpunit
PHP Warning:  require_once(/tmp/wordpress-tests-lib/includes/functions.php): Failed to open stream: No such file or directory in /plugins/redirection/tests/bootstrap.php on line 12

Warning: require_once(/tmp/wordpress-tests-lib/includes/functions.php): Failed to open stream: No such file or directory in /plugins/redirection/tests/bootstrap.php on line 12
PHPUnit 9.5.23 #StandWithUkraine

Error in bootstrap script: Error:
Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php' (include_path='.:/usr/local/Cellar/php/8.2.5/share/php/pear')
#0 /plugins/redirection/vendor/phpunit/phpunit/src/Util/FileLoader.php(65): include_once()
#1 /plugins/redirection/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/plugins/redirection/...')
#2 /plugins/redirection/vendor/phpunit/phpunit/src/TextUI/Command.php(562): PHPUnit\Util\FileLoader::checkAndLoad('/plugins/redirection/...')
#3 /plugins/redirection/vendor/phpunit/phpunit/src/TextUI/Command.php(344): PHPUnit\TextUI\Command->handleBootstrap('/plugins/redirection/...')
#4 /plugins/redirection/vendor/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit\TextUI\Command->handleArguments(Array)
#5 /plugins/redirection/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#6 /plugins/redirection/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#7 /plugins/redirection/vendor/bin/phpunit(123): include('/plugins/redirection/...')
#8 {main}
Script ./vendor/bin/phpunit handling the test event returned with error code 1
error Command failed with exit code 1.
```

I'm not sure where the `/tmp/wordpress-tests-lib/includes/functions.php` file comes from. It is not included in this repo nor are there any docs on how to run php unit tests. I did notice that there is an env var of `WP_TESTS_DIR` that can be set, but if it is not, then the default directory is `/tmp/wordpress-tests-lib`, which does not exist on my local file system. Even if i were to create it, I still do not know what `includes/functions.php` is supposed to be or where it is supposed to come from.

```
🌯  /plugins/redirection 🌮  trunk 🍔
ls /tmp/wordpress-tests-lib
ls: /tmp/wordpress-tests-lib: No such file or directory
```

### Steps to reproduce

- Set up the a fresh install of this repo and install appropriate dependencies (ie. `yarn install`, installing xdebug.so, etc)
- make sure the `/tmp/wordpress-tests-lib/includes/functions.php` file is not present on your file system
- Run `yarn test:php`

The error above will be output the console.

### Environment

No browser, just terminal
WordPress: n/a, ran in terminal
Redirection plugin: `trunk` branch

**Comment by johngodley** [comment]
The tests require the WP unit test system to be setup. They're mostly for my benefit.

It might be easier to create an issue for whatever you are trying to test

**Comment by hellatan** [comment]
@johngodley Are there docs on how to set that up? I'd like to run these locally to get a better understanding of how things work under the hood so i can adjust my regexes accordingly. Also, if there is something that doesn't work, I'd also like to submit any patch(es) that I may come across. I'm seeing some weird issue with specifically `amp` as a query parameter (added by the AMP plugin) and now i'm also seeing an issue where the regex field does not respect the word boundary `\b` character

**Comment by hellatan** [comment]
ok, i see my mistake with the `?amp` query param- i was actually testing `\?amp=?` but on your site the suggestion is `\?amp=.*`. This works but not really with additional query parameters since `.*` is capturing those as well. 

I was able to get something working like this:

```
source: ^\/(.*)\/\?amp=(\w+)?(\&(\w+=.*))
target: /$1/?$4
```

The AMP plugin just adding `?amp` or `&amp` to the query params was really throwing me off because I had this working a couple weeks ago using just a regex like `(\?|\&)amp`
