### ISSUE TITLE
csv export header errors

### ISSUE THREAD

**Issue by airdrummer** [johngodley/redirection#3623]
### Summary

export csv with valid header for import

### Actual Behavior

exported csv header contains extra column, invalid name:

source,target,regex,code,type,match,hits,title,status
<src>,<tgt>",0,308,"url",5,"directly logout","active"

extraneous "hits" column, "code" s.b. "http code" as stated in dox
https://redirection.me/support/import-export-redirects/

### Steps to reproduce

export csv

### Environment

all

**Comment by johngodley** [comment]
Exported CSVs contain additional information that isn't used when importing. A note has been added to the documentation.
