### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by bvttle** [johngodley/redirection#3625]
### Summary

We've had this issue a while, and it seems to be some conflict with the plugin and our website. I've only noticed it on this site, but the debug info doesn't help me much, maybe you can see something?

### Steps to reproduce

Visit Tools > Redirection

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

### Error Information

Plugin: 5.3.10 4.2
WordPress: 6.2 (single)
PHP: 8.0.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
JavaScript: https://www.aura-consulting.co.uk/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.aura-consulting.co.uk/wp-json/
Query: ?page=redirection.php

Action: https://www.aura-consulting.co.uk/wp-json/redirection/v1/plugin/data/ POST
Params: {"upgrade":"retry"}
Code: 200 OK

Error: Unexpected token '<', "<script>wi"... is not valid JSON (SyntaxError)
Raw: <script>window.oncontextmenu = function(){return false;}</script>{"status":"ok","inProgress":false,"current":"4.2","next":"4.2","time":1683793334.738217,"complete":0,"result":"error","reason":"Your database does not need updating to 4.2.","debug":["CREATE TABLE `wp_redirection_items` (","  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,","  `url` mediumtext COLLATE utf8mb4_unicode_520_ci NOT NULL,","  `match_url` varchar(2000) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  `match_data` text COLLATE utf8mb4_unicode_520_ci,","  `regex` int(11) unsigned NOT NULL DEFAULT '0',","  `position` int(11) unsigned NOT NULL DEFAULT '0',","  `last_count` int(10) unsigned NOT NULL DEFAULT '0',","  `last_access` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',","  `group_id` int(11) NOT NULL DEFAULT '0',","  `status` enum('enabled','disabled') COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'enabled',","  `action_type` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL,","  `action_code` int(11) unsigned NOT NULL,","  `action_data` mediumtext COLLATE utf8mb4_unicode_520_ci,","  `match_type` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL,","  `title` text COLLATE utf8mb4_unicode_520_ci,","  PRIMARY KEY (`id`),","  KEY `url` (`url`(191)),","  KEY `status` (`status`),","  KEY `regex` (`regex`),","  KEY `group_idpos` (`group_id`,`position`),","  KEY `group` (`group_id`),","  KEY `match_url` (`match_url`(191))",") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci","","CREATE TABLE `wp_redirection_groups` (","  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,","  `name` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL,","  `tracking` int(11) NOT NULL DEFAULT '1',","  `module_id` int(11) unsigned NOT NULL DEFAULT '0',","  `status` enum('enabled','disabled') COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'enabled',","  `position` int(11) unsigned NOT NULL DEFAULT '0',","  PRIMARY KEY (`id`),","  KEY `module_id` (`module_id`),","  KEY `status` (`status`)",") ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci","","CREATE TABLE `wp_redirection_logs` (","  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,","  `created` datetime NOT NULL,","  `url` mediumtext COLLATE utf8mb4_unicode_520_ci NOT NULL,","  `domain` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  `sent_to` mediumtext COLLATE utf8mb4_unicode_520_ci,","  `agent` mediumtext COLLATE utf8mb4_unicode_520_ci,","  `referrer` mediumtext COLLATE utf8mb4_unicode_520_ci,","  `http_code` int(11) unsigned NOT NULL DEFAULT '0',","  `request_method` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  `request_data` mediumtext COLLATE utf8mb4_unicode_520_ci,","  `redirect_by` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  `redirection_id` int(11) unsigned DEFAULT NULL,","  `ip` varchar(45) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  PRIMARY KEY (`id`),","  KEY `created` (`created`),","  KEY `redirection_id` (`redirection_id`),","  KEY `ip` (`ip`)",") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci","","CREATE TABLE `wp_redirection_404` (","  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,","  `created` datetime NOT NULL,","  `url` mediumtext COLLATE utf8mb4_unicode_520_ci NOT NULL,","  `domain` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  `agent` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  `referrer` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  `http_code` int(11) unsigned NOT NULL DEFAULT '0',","  `request_method` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  `request_data` mediumtext COLLATE utf8mb4_unicode_520_ci,","  `ip` varchar(45) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,","  PRIMARY KEY (`id`),","  KEY `created` (`created`),","  KEY `referrer` (`referrer`(191)),","  KEY `ip` (`ip`)",") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci","","Stage: "]}

**Comment by johngodley** [comment]
`<script>window.oncontextmenu = function(){return false;}</script>` should not appear on your REST API

**Comment by bvttle** [comment]
> `<script>window.oncontextmenu = function(){return false;}</script>` should not appear on your REST API

Sorry – I don't know how to change this, can you advise?

**Comment by johngodley** [comment]
Sorry, I have no idea what it might be and can only help with Redirection, not general WordPress. Something is outputting that on every page of your site. It looks to be stopping right clicks.

**Comment by bvttle** [comment]
> Sorry, I have no idea what it might be and can only help with Redirection, not general WordPress. Something is outputting that on every page of your site. It looks to be stopping right clicks.

That's helpful thanks, we have a DMCA plugin as the site got duplicated a few times, which disables right click... I've disabled this and it works. Much appreciated, have a nice day :)
