### ISSUE TITLE
Problem starting Redirection 5.3.9

### ISSUE THREAD

**Issue by schipkeb** [johngodley/redirection#3628]
```
Uncaught TypeError: Cannot read properties of null (reading 'id') https://overcomingptsd.com/wp-content/plugins/copy-delete-posts/banner/assets/index.min.js?ver=1679635134 1
```

Plugin: 5.3.9 4.2
WordPress: 6.2 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
JavaScript: https://overcomingptsd.com/wp-content/plugins/redirection/redirection.js?ver=5.3.9-d9e6fbf82d86a7f9b256e669c214cb3a
REST API: https://overcomingptsd.com/wp-json/

**Comment by johngodley** [comment]
The details are all there:

Uncaught TypeError: Cannot read properties of null (reading 'id') https://overcomingptsd.com/wp-content/plugins/copy-delete-posts/banner/assets/index.min.js?ver=1679635134 1

I don't know what that is, but it's not Redirection.
