### ISSUE TITLE
Is it possible to create a redirection via PHP?

### ISSUE THREAD

**Issue by jam1e** [johngodley/redirection#3629]
I'm currently working on updating a city portal website that uses a custom theme with ACF, and your plugin.
When a business closes down, sometimes it is reopened under another company/name. Via a custom ACF field, we mark the business as "closed", and select a new business that has taken over.

We are then having to manually create a redirection via your plugin to match this.
Is it possible to manually create redirections via PHP to automate this process?

For example:

```
add_action( 'acf/save_post', function( $post_id ) {
    $redirect_to = get_field( 'redirect_to', $post_id );    
    
    if ( $redirect_to ) {
        $old_url   = get_permalink( $post_id );
        $new_url = get_permalink( $redirect_to );

        // Manually  create redirection
    }
} );
```

**Comment by johngodley** [comment]
There are a couple of ways of creating redirects, which you can find listed here:

https://redirection.me/developer/
