### ISSUE TITLE
Plugin settings won't open

### ISSUE THREAD

**Issue by Slyx2** [johngodley/redirection#363]
I cannot open the plugin settings but I get this error message below. I've used the plugin for a long time, but it seems that after the latest update somethings changed that is causing the problem. As far as I can see all the redirects are still working, but I cannot edit them or create new ones.

Something went wrong 🙁
WordPress did not return a response. This could mean an error occurred or that the request was blocked. Please check your server error_log.

It didn't work when I tried again

Plugin: 2.7.3
WordPress: 4.8.1
PHP: 5.6.30
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
Nonce: 19dd2f8751
URL: http://<site>/wp-admin/admin-ajax.php

Error: No response returned
Action: red_get_group
Params: {"filterBy":"","filter":""}
Code: 200 OK
Raw: 0

Error: No response returned
Action: red_get_redirect
Params: {"orderBy":"id","filterBy":"","filter":""}
Code: 200 OK
Raw: 0

**Comment by johngodley** [comment]
Are there any errors in your `error_log`? Can you try disabling other plugins and see if it works?

The message above indicates that it is making the request, but nothing is being returned by the server

**Comment by Slyx2** [comment]
I did not find anythiing in the error log and I've tried to deactivate all my plugins, but the problem remains. But I will check again to be sure.

**Comment by Slyx2** [comment]
The issues is resolved. It turned out that my site was hacked and it shut down the plugin. In any case, it's resolved. Sorry about that.
