### ISSUE TITLE
Importing into a disabled group does not disable the imported entries

### ISSUE THREAD

**Issue by 0x04** [johngodley/redirection#3631]
### Summary

I imported a CSV file into a disabled group and assumed that this would disable the imported entries.

### Actual Behavior

Importing into a disabled group does not disable the imported entries.

### Steps to reproduce

Import a CSV file into a disabled group. The imported entries are not set to disabled status as assumed.

### Environment

N/A

**Comment by johngodley** [comment]
This will be fixed in the next version.
