### ISSUE TITLE
Can't redirect to a single URL

### ISSUE THREAD

**Issue by Hody72** [johngodley/redirection#3634]
I want to redirect all posts from my old domain to a different domain and used this plugin

the syntax would be oldurl.com/2015/02/07/post-name/

it end up in a 404 on newurl.com/2015/02/07/post-name/

as the 2015/02/07/post-name/ dont exist on the new url

rather than copying the name one to one, I would want that all post, regardless of the content behind the slash after oldurl.com
end up on the startpage on newurl.com (ignoring post categories, names etc.)

I have read the tutorial/help a few times, but cant figure it myself - English is also not my mother tongue

Some help would be great

**Comment by johngodley** [comment]
You will need to use a regular expression:

https://redirection.me/support/redirect-regular-expressions/

**Comment by Hody72** [comment]
hello, thanks for getting back. I read that linked informed already

I think the syntax has to be **source url** oldurl.com/.*

but I dont understand who I restrict the target url from adding the part after the slash. What I want to receive that bascially all sites/pages are redirected to a single URL like if no matter what source url it was it ends up on www.google.com for example

**Comment by johngodley** [comment]
The target URL will only ever be what you put. If you want it to be a single URL then put that URL.

**Comment by Hody72** [comment]
I ran an old word press blog an example url would be https://www.hody.de/2015/02/07/sick-like-me/ 

I want to redirect all posts to another wordpress page called www.tribe-online.de

the above example ends up as https://www.tribe-online.de/2015/02/07/sick-like-me/ which does not exist and will end up in a 404 page - while I would it to land on the start page with is www.tribe-online.de

**Comment by johngodley** [comment]
Ok, and from my suggestions what have you tried? The support page should be sufficient.

**Comment by Hody72** [comment]
> Ok, and from my suggestions what have you tried? The support page should be sufficient.

I have read https://redirection.me/support/redirect-regular-expressions/ a few times and tried a few things. But I can't get it to work. I consider my English as pretty good, but I have to admit I either have a translation or a understanding problem

my current setup is

^//www.hody.de/ (with regular expression enabled)
//www.tribe-online.de

the result is as stated above. 

I am really sorry to bother you, but I really have a hard time figuring it out. trying since 2 or 3 hours now, dont know what to input anymore

**Comment by johngodley** [comment]
> I really have a hard time figuring it out. trying since 2 or 3 hours now, dont know what to input anymore

I appreciate that, but as It states on the page, helping with expressions consume a lot of time. The internet has a lot of information about this in languages other than English.

`^//www.hody.de/` does not match any of the examples on that page
`//www.tribe-online.de` is not a URL

This shows you what to put for the source.

![image](https://github.com/johngodley/redirection/assets/1277682/0a61858a-941f-4d82-be15-250a15bf7d6b)

You would then put the target as your target site. It needs to be a proper URL.

You should read this guide about redirecting another site: https://redirection.me/support/redirecting-another-site/

**Comment by Hody72** [comment]
Thanks I managed at the end, it seems this fixed it

/(.*) (regular expressions activated)
http://www.tribe-online.de/

Seems to work, thanks so much
