### ISSUE TITLE
Ignore case defaults not working

### ISSUE THREAD

**Issue by deanpain** [johngodley/redirection#3635]
Hi Great plugin firstly

Im just finding that the when i have a Uppercase link i.e. /Capetown with a redirect setup for /capetown and system default of ignore case, the redirect does not work. Unfortunately I have hundreds of these links which now no longer work with having to set each one now manually

**Comment by johngodley** [comment]
Do you have a URL to test? I am unable to reproduce the problem.

**Comment by deanpain** [comment]
Hi John - yes sir
https://www.capestay.co.za/Bakoven/
https://www.capestay.co.za/bakoven/

Below copied from WP Admin screen:
[/bakoven](https://www.capestay.co.za/bakoven)
https://www.capestay.co.za/search-results/?city=bakoven
Ignore Case
[Edit](https://www.capestay.co.za/wp-admin/tools.php?page=redirection.php&filterby%5Burl%5D=bakoven#) | [Delete](https://www.capestay.co.za/wp-admin/tools.php?page=redirection.php&filterby%5Burl%5D=bakoven#) | [Disable](https://www.capestay.co.za/wp-admin/tools.php?page=redirection.php&filterby%5Burl%5D=bakoven#) | [Check Redirect](https://www.capestay.co.za/wp-admin/tools.php?page=redirection.php&filterby%5Burl%5D=bakoven#)

**Comment by johngodley** [comment]
I'm unable to reproduce this problem. Can you include a screenshot?

**Comment by deanpain** [comment]
Hi John  - simple pal. I sent the links - just follow them?
Two different links - one has uppercase. 

The setting has the ignore uppercase set but doesn't work

**Comment by johngodley** [comment]
Sure, but I am not able to reproduce the problem, and it doesn't seem to be affecting anyone else. If you could include a screenshot then I can see exactly what settings you have used.
