### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by ALGuevara** [johngodley/redirection#3636]
```
Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
JavaScript: https://tucsoncomputerrepair.net/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://tucsoncomputerrepair.net/wp-json/
Query: ?page=redirection.php

Error: Invalid redirect (redirect_bulk_failed)
Raw: {"code":"redirect_bulk_failed","message":"Invalid redirect","data":{"status":400,"error_code":345}}
```

**Comment by ALGuevara** [comment]
This error happened several times when I was trying to delete several identical redirects (https://tucsoncomputerrepair.net/contact)

**Comment by johngodley** [comment]
This is caused by a cache on your site. You should clear that cache and exclude your REST API.

**Comment by ALGuevara** [comment]
Thank you John. Do these newer era "caching plugins" bring a whole new set
of probs?

**Comment by johngodley** [comment]
I can't say about that, but some can be quite aggressive. The error is when you've deleted something, but the cache is saying it is still there. Then you try and delete again and it throws an error because it doesnt exist.

**Comment by ALGuevara** [comment]
Exactly what happened. I removed the cache plugin. I really cant
imagine how their helpful to small player, small qty page websitses
Thanks John.
How do I buy you a coffee?
