### ISSUE TITLE
Problem starting Redirection 4.9.2

### ISSUE THREAD

**Issue by christiansammmm** [johngodley/redirection#3637]
Plugin: 4.9.2
WordPress: 5.6 (single)
PHP: 7.3.19-1~deb10u1
Browser: Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1
JavaScript: https://turbo.net.id/wp-content/plugins/redirection/redirection.js?ver=4.9.2-b1c9e2f6a1c3f8b6cc251a44757c6863
REST API: https://turbo.net.id/wp-json/

**Comment by johngodley** [comment]
Please read the onscreen details. This is most likely caused by another plugin.
