### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by gulamjilaniweb1** [johngodley/redirection#3638]
*Database problem*

We are facing the error 404

We tried changing the permalink from custom to postname and saved the changes. 
after that, still showed 404.

we also cleared the cache but didn't get the result.

so that's why we installed your plugin, but your plugin is telling us database problems. we don't have a c-panel because we installed aws ec2
<img width="1440" alt="Screenshot 2023-05-25 at 4 35 48 PM" src="https://github.com/johngodley/redirection/assets/32295356/fea92b9e-792a-4623-8dd3-d16e985f7286">

**Comment by johngodley** [comment]
I can't read the message because it's scrolled off the top of the screen. You should probably fix that first.

**Comment by gulamjilaniweb1** [comment]
HI,
could you go through this website you will understand
what am I trying to say

https://mymagnet.io/blog/how-to-increase-real-estate-sales-with-new-technologies/

**Comment by johngodley** [comment]
Ok, it's showing a 404. Redirection can't help you with that 404 and it's something you will need to fix properly.

**Comment by gulamjilaniweb1** [comment]
okay
