### ISSUE TITLE
Security Headers causing critical error

### ISSUE THREAD

**Issue by cr-alex** [johngodley/redirection#3639]
### X Content Type Options -> Nosniff & Referrer Policy -> Origin When Cross Origin Produce 500

When adding the above headers there is a critical error. Tested this on 3 sites and recieved the same error. 

 PHP Fatal error: Uncaught TypeError: iconv(): Argument #3 ($string) must be of type string, array given in /nas/content/live/example/wp-content/plugins/redirection/models/header.php:115\nStack trace:\n#0 /nas/content/live/example/wp-content/plugins/redirection/models/header.php(115): iconv('UTF-8', 'UTF-8//IGNORE', Array)\n#1 /nas/content/live/example/plugins/redirection/models/header.php(25): Red_Http_Headers->sanitize(Array)\n#2 [internal function

### Steps to reproduce

Save the security header. 

### Environment

Redirection : 5.3.10
WP: 6.2
Chrome: Latest

**Comment by dawnerd** [comment]
Running into this as well, same error.

**Comment by johngodley** [comment]
This will be fixed in the next version
