### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by x3blondie** [johngodley/redirection#3641]
```
Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 8.1.18
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
JavaScript: https://bj.org/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://bj.org/wp-json/
Query: ?page=redirection.php&filterby%5Burl%5D=test

Error: Invalid parameter(s): filterBy (rest_invalid_param)
Raw: {"code":"rest_invalid_param","message":"Invalid parameter(s): filterBy","data":{"status":400,"params":{"filterBy":"Filter is not an array"},"details":{"filterBy":{"code":"rest_invalid_param","message":"Filter is not an array","data":{"status":400}}}}}
```

When i try to search the redirects I get this message.

**Comment by johngodley** [comment]
What filter settings are you using?

**Comment by x3blondie** [comment]
It looks like I'm getting the same error with any filter. I'm not getting any results either.

**Comment by johngodley** [comment]
Sure, but can you show me what settings you have? You probably have something enabled.

**Comment by x3blondie** [comment]
Here are my current settings. 

![Screenshot 2023-06-06 at 9 53 44 AM](https://github.com/johngodley/redirection/assets/8069456/ad26004c-efc4-407f-a01b-3386a181b050)
![Screenshot 2023-06-06 at 9 53 57 AM](https://github.com/johngodley/redirection/assets/8069456/c48eedad-a461-41a6-a3fb-73770cacb0ca)

**Comment by johngodley** [comment]
This is what I mean so I can see what filters you are using
![image](https://github.com/johngodley/redirection/assets/1277682/a582c570-5ecc-476e-9053-7d99620cf960)

**Comment by x3blondie** [comment]
My bad, here's the filters I'm using.
![Screenshot 2023-06-07 at 8 51 46 AM](https://github.com/johngodley/redirection/assets/8069456/895ab09b-b5e8-49c3-9159-83e683393f17)

**Comment by incraigulous** [comment]
@x3blondie would you post a screenshot of your request body from Chrome DevTools network tab? I'm curious what that Chrome is sending in that `filterBy` parameter.

**Comment by x3blondie** [comment]
@incraigulous Is this what's you're looking for?
![Screenshot 2023-06-09 at 9 49 21 AM](https://github.com/johngodley/redirection/assets/8069456/79fc58f9-bdce-4b7d-bd3a-fc826572f211)

**Comment by incraigulous** [comment]
@x3blondie, click on the network tab, find the request under Fetch/XHR, and click on "Payload"

**Comment by x3blondie** [comment]
![Screenshot 2023-06-09 at 10 02 02 AM](https://github.com/johngodley/redirection/assets/8069456/42b2274e-d73f-4854-94d7-0b01bd0c7e53)
I do not see payload @incraigulous

**Comment by incraigulous** [comment]
It shows up if you click the request, @x3blondie 

https://www.loom.com/share/3358714928714fe98c23f487e0d55889?sid=8b7f9fbf-63c4-485e-af66-f4028b34c06a

**Comment by x3blondie** [comment]
@incraigulous 
![Screenshot 2023-06-13 at 9 53 38 AM](https://github.com/johngodley/redirection/assets/8069456/ae510169-e362-432d-a767-83e0f59cb16a)
