### ISSUE TITLE
Non fonctionnement des redirections

### ISSUE THREAD

**Issue by resthe27** [johngodley/redirection#3642]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Nous avons monté un nouveau site sur WordPress, en gardant le même nom de domaine mais en changeant de CMS (OVH vers FAAASTER).
J'essaye de faire des redirections sur mon site mais ça ne fonctionne pas avec le plugin Redirections. 
Tous les liens de notre ancien site se termine par .html

### Actual Behavior

Lorsque nous mettons les anciens liens en .html, aucune redirection ne fonctionne. En revanche, si nous essayons avec un lien qui ne contient pas .html à la fin, la redirection fonctionne. Or, il faut absolument que les anciens liens du site puissent être redirigés vers le nouveau. 

### Steps to reproduce

Nous avons utilisé le plugin redirections 
nous avons mis l'ancien lien (exemple : https://comda.fr/Com-Da-Magazine.html)
nous avons mis la redirection 301 vers notre page d'accueil : www.comda.fr
Enregistrement 
Nous rechargeons la page https://comda.fr/Com-Da-Magazine.html, mais nous tombons toujours sur une erreur 404. Cela arrive avec toutes nos pages. 

### Environment

Nous avons la version 6.1.3 de WordPress et le PlugIn Redirections a été mis à jour avec la dernière mise à jour. 
Nous avons essayé sur plusieurs types de PC.

**Comment by johngodley** [comment]
You can find details here:

https://redirection.me/support/problems/url-not-redirecting/
