### ISSUE TITLE
impossible ta access wordpress admin dashboard (too many redirection)

### ISSUE THREAD

**Issue by karemkadidola** [johngodley/redirection#3647]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

trying to access my wordpress admin dashboard not working no more.

### Actual Behavior

i get an error message saying i have been redirected too many times.

### Steps to reproduce

https://taxi-brussels.com/wp-admin/ but it works if i type this www.taxi-brussels.com/wp-admin/ but i created my website without www

### Environment

shared server so i do not know.

**Comment by johngodley** [comment]
Did you create a redirect to do this? If so you will need to disable it.

**Comment by karemkadidola** [comment]
no i did not create a redirect to do that

regards

**Comment by johngodley** [comment]
Ok, the plugin won't do this by itself. So either the plugin is not performing the redirect (i.e. something else is), or you have (accidentally) created a redirect that is looping.

**Comment by karemkadidola** [comment]
Ok I will never know

Regards
