### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by DaveDevelops** [johngodley/redirection#3650]
No screenshots necessary, redirection pages are blank. When I remove them from the redirection section, they are no longer blank
I take it back, I am including the redirection setting screenshot
### Summary

When I add a page to the redirection section of the plugin, and test the page, with private browser, deleted cache, etc, the page is completly blank. nothing happen, no html is rendered.

### Actual Behavior

This happened after we got a virus on our page.
Before that, it worked perfectly. The virus has been removed. I uninstalled and removed the redirection plugin and installed it again.
The behaviour prevails. Blank screen on all redirects.

### Steps to reproduce

If you go to this page: https://test2.miracleleaguepalmbeachcounty.com/player-registration/
it is supposed to redirect you to:
https://app.myezreg.com/leagues/login/mlpbc
<img width="1595" alt="Screenshot 2023-06-09 at 11 27 52 AM" src="https://github.com/johngodley/redirection/assets/30532440/55b5bd9a-bc8e-4231-a4c2-9a0cb7d02802">

### Environment
MacOS 13.4 (22F66)
Chrome (Version 114.0.5735.90 (Official Build) (x86_64)) 
Safari (Version 16.5 (18615.2.9.11.4))

**Comment by johngodley** [comment]
You will need to figure out what on your site is causing the blank page. Once you have done that the redirects should work.
