### ISSUE TITLE
Redirection that looks OK but doesn't work

### ISSUE THREAD

**Issue by Giacomo420** [johngodley/redirection#3651]
### Summary

I tried to redirect a category after I changed its name and url, as I did a few days ago for another category with no problems.
If I check the redirect from the plugin, it looks correct. The category has correctly changed its name and url, but if I try to enter from the old link, it still brings me back to the 404 error. This is from both a phone and a PC, both from a normal browser and from incognito browsing.

### Environment

Brave/Google Chrome, Wordpress 7.7.0

**Comment by Giacomo420** [comment]
this is the link that shows 404 error: https://www.hemport.it/infiorescenze-cbd

**Comment by Giacomo420** [comment]
So, I noticed now that if i click the link, I saw the new correct page. But if i try to search it from google, and click the result "infiorescenze cbd Hemport" (the old ink), i still see an 404 error.

**Comment by johngodley** [comment]
The URL is redirecting fine:

https://redirect.li/http/?url=https%3A%2F%2Fwww.hemport.it%2Finfiorescenze-cbd

Maybe the one in Google is not the same.

**Comment by Giacomo420** [comment]
Hi there, thanks for your quick response.. i think that the link on google is the same

**Comment by Giacomo420** [comment]
Attached a screenshot that shows that the link is the same. You can try by yourself if you want..
![Schermata 2023-06-09 alle 6 46 40 PM](https://github.com/johngodley/redirection/assets/71820345/8bcdb9a2-a074-4188-9311-11e590306401)

**Comment by johngodley** [comment]
It's not the same. One has a `/` at the end and the other doesn't

**Comment by Giacomo420** [comment]
Hi there, thank you for made me notice it. Now It all works right. Thank you!
