### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by jisanpolara** [johngodley/redirection#3657]
```
Uncaught SyntaxError: Unexpected end of input https://www.greencorpmarine.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 3
```

Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
JavaScript: https://www.greencorpmarine.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.greencorpmarine.com/wp-json/

**Comment by johngodley** [comment]
As described on the error page this is almost certainly caused by another plugin, or something like that.
