### ISSUE TITLE
 redirected you too many times.

### ISSUE THREAD

**Issue by barkha06456** [johngodley/redirection#3660]
Hi, I am getting this error on my home page:

This page isn’t workingviscosity.com redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS

this is my site:https://viscosity.com/...all pages are working fine not this one...i deactivate the plugin site works fine..when i activate the plugin it gives me the error on the home page...please help me how to fix this.

**Comment by johngodley** [comment]
You should delete the redirect causing an infinite loop.

**Comment by barkha06456** [comment]
can you please elaborate ?

**Comment by johngodley** [comment]
You have created an infinite loop - a redirect that redirects to itself. You will need to edit your redirects so that doesn't happen.

**Comment by jignesh-travelopia** [comment]
@johngodley Is there any permanent solution to this problem? Plugin seems to be creating automatic redirection with same URL which shouldn't be happening in the first place. 
A few of our sites are having the same issue and they have to manually remove the redirct.

**Comment by johngodley** [comment]
Is this related to the original problem, or is it a different one? It seems like it is a different problem.

**Comment by jignesh-travelopia** [comment]
thanks @johngodley  for the prompt reply. It's not related to exact original problem. But what I meant was can we not prevent plugin from adding the same URLs in redirection?

Whether redirection is created manually or created by external custom logic or from plugin itself, It shouldn't be allowing the same URLs in redirection entry. What do you think?

**Comment by johngodley** [comment]
The plugin shouldn't create redirects to the same place, and doesn't appear to be doing so for the majority of users. A new issue with details of your specific setup is probably the best way to proceed.

**Comment by jignesh-travelopia** [comment]
Thanks, @johngodley  will gather some info from my setup and possibly create an issue too. Have a nice day!
