### ISSUE TITLE
file_get_contents('php://input' ) doesn't work if the Redirection plugin is enabled

### ISSUE THREAD

**Issue by jdorner4** [johngodley/redirection#3661]
### Summary

file_get_contents('php://input' ) returns an empty string if the Redirection plugin is enabled.
Disabling the plugin gets the contents.

### Actual Behavior

We are trying to use a Postmark Webhook https://postmarkapp.com/developer/webhooks/webhooks-overview, but if Redirection is enable, we get nothing from file_get_contents('php://input' ).

### Steps to reproduce

Create test.php (in WP root folder)
```
<?php
require 'wp-load.php';

$input = ( json_decode( file_get_contents('php://input' ) ) );

echo print_r( $input, true );
```

Redirection has no redirections added and is using the default settings
Use Postman to send a POST request to test.php 
Headers: Content-Type: application/json
Body: 
```
{
  "RecordType": "Bounce",
  "MessageStream": "outbound",
  "ID": 42,
  "Type": "HardBounce",
  "TypeCode": 1,
  "Name": "Hard bounce",
  "Tag": "Test",
  "MessageID": "00000000-0000-0000-0000-000000000000",
  "ServerID": 1234,
  "Description": "The server was unable to deliver your message (ex: unknown user, mailbox not found).",
  "Details": "Test bounce details",
  "Email": "john@example.com",
  "From": "sender@example.com",
  "BouncedAt": "2019-10-30T16:28:14.7011290Z",
  "DumpAvailable": true,
  "Inactive": true,
  "CanActivate": true,
  "Subject": "Test subject",
  "Metadata": {
    "example": "value",
    "example_2": "value"
  }
}
```

### Environment

Not browser dependent. 
WordPress 6.2.2
Redirection 5.3.10

Thank you for this awesome plugin!

Let me know if you need anything else.
jdorner@sare.org

**Comment by johngodley** [comment]
I'm not able to test this right now, but there is nothing in the plugin that would cause this to happen. Is it possible that something else is causing this effect as it seems unlikely to be Redirection.

**Comment by jdorner4** [comment]
We figured the cause of our problem. 
I'm not sure if it is anything that can be or should be "fixed", but just wanted to close this discussion and bring this issue to your attention.

When referencing the url of an aliased domain via a POST method, the body payload is lost in the redirection.
The solution on our end was to stop using the aliased domain - which was unintentional on our part.

Example:
aliased domain: staging.www.example.com
actual domain: www.staging.example.com

a POST request to staging.www.example.com (alias) with body data (php://input) is redirected to  www.staging.example.com, but without the body data (php://input).

Thank you!
