### ISSUE TITLE
Valid regex is resulting in an odd outcome

### ISSUE THREAD

**Issue by inspiredearth** [johngodley/redirection#3663]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I am doing a Regex based redirection.
The **Source URL** is, `^(\/wp-content\/uploads\/2022\/05\/cropped-mckays_icon_512-1-)(?!150x150)(\d+x\d+)(\.png)$`
It should match all instances of that image URL with various image dimensions in the URL, except those that have `150x150`. 

The Target URL is:  `https://www.mydomain.com.au$1150x150$3`

A URL such as, `https://www.mckaysgrassseeds.com.au/wp-content/uploads/2022/05/cropped-mckays_icon_512-1-210x201.png` should redirect to, `https://www.mckaysgrassseeds.com.au/wp-content/uploads/2022/05/cropped-mckays_icon_512-1-150x150.png`

This regex works perfectly in the various Regular Expression dev tools I use for sure purposes.

### Actual Behavior

It is redirecting to:  `https://www.mckaysgrassseeds.com.au50x150.png/`

You can see this here:  https://redirect.li/http/?url=https%3A%2F%2Fwww.mckaysgrassseeds.com.au%2Fwp-content%2Fuploads%2F2022%2F05%2Fcropped-mckays_icon_512-1-210x201.png

### Steps to reproduce

Set up a redirection with the source and target as per what I've indicated above.

Browse to a URL such as `https://www.mydomain.com.au/wp-content/uploads/2022/05/cropped-mckays_icon_512-1-210x201.png`

### Environment

I have tested with curl, in order to avoid browser issues. However, I've also tested in macOS Chrome, and in the `https://redirect.li/` tool online.

Wordpress version:  6.1.3
Redirection version: 5.3.10

**Comment by johngodley** [comment]
The plugin uses PHP regular expressions and does no processing itself. Your expression will need to be valid for PHP. The one you put above shows an error when I try it in an expression tester

**Comment by inspiredearth** [comment]
@johngodley , Thanks for getting back to me. I've been away for past month, so just getting back to this now.

What is the error you're seeing in the expression tester you are using? 
Which expression tester are you using?

As far as I can tell, it's a perfectly valid regular expression, so I am curious why it has issues in PHP.

**Comment by inspiredearth** [comment]
Further to reply above ... I asked both Google Bard and OpenAI ChatGPT for whether there was anything about the expression that would prevent it working in PHP. Both came back saying it should be fine, using `pre_match()`. Here is the full response from Bard:


> No, there is nothing in the regular expression that would prevent it from being processed by PHP. The regular expression is valid and matches the string "/wp-content/uploads/2022/05/cropped-mckays_icon_512-1-100x100.png".
> 
> The `?!150x150` part of the regular expression is a negative lookahead assertion. This means that the expression will only match if the string does not contain the substring "150x150". This is used to ensure that the regular expression only matches images that are not 150x150 pixels in size.
> 
> The regular expression can be processed by PHP using the `preg_match()` function. The following PHP code will match the string "/wp-content/uploads/2022/05/cropped-mckays_icon_512-1-100x100.png" and return the matched substring:
> 
> ```php
> <?php
> $regex = '/^(\/wp-content\/uploads\/2022\/05\/cropped-mckays_icon_512-1-)(?!150x150)(\d+x\d+)(\.png)$';
> $string = '/wp-content/uploads/2022/05/cropped-mckays_icon_512-1-100x100.png';
> 
> $match = preg_match($regex, $string);
> 
> if ($match) {
>     echo $match[0];
> }
> ?>
> ```
> 
> This code will output the following:
> 
> ```
> /wp-content/uploads/2022/05/cropped-mckays_icon_512-1-100x100.png
> ```
> 
> As you can see, the regular expression is successfully processed by PHP and the matched substring is returned.
> 

So I'd love to know what error you saw, and in what testing tool.

**Comment by inspiredearth** [comment]
I've done some testing using this PHP regex tester: https://www.phpliveregex.com/#tab-preg-replace

I can see that the issue is the way PHP is handling the replacements string, `$1150x150$3`. 

It is interpreting the first replacement group identifier as `$11` and not `$1`. Basically, PHP can't handle having a number immediately after the capture identifier.

So I am going to need use a regular expression that incorporates the preceding `-` in the image dimensions (which is in the second capture group). E.g., `-200x200` so that it's not part of the first capture group. That way I can include a hyphen in the replacement text. E.g, `$1-150x150$3`. This effectively ensures there are no numbers after the first capture group identifier.

According to the above-mentioned testing tool, the following will work:

1. Regular expression: `(\/wp-content\/uploads\/2022\/05\/cropped-mckays_icon_512-1)-(?!150x150)(\d+x\d+)(\.png)$`
2. Replacement: `$1-150x150$3`

As shown [here](https://www.phpliveregex.com/p/JDG).

**Comment by johngodley** [comment]
>  I asked both Google Bard and OpenAI ChatGPT for whether there was anything about the expression that would prevent it working in PHP.

I would not rely on AI being correct, and certainly not as proof of why something should work. What will be correct is how PHP itself behaves, and for that Redirection has no control. As originally described, Redirection passes control directly to PHP - there is no additional processing. Whatever variant of regular expression processing that PHP provides is the one that Redirection uses.

**Comment by inspiredearth** [comment]
Thanks John. Agreed. I also wouldn't rely on AI as being entirely accurate. But it can be a useful way to get some further insight into what might be going on with programming related issues. 

Hence why I continued with further testing. I assume you've seen my more recent comments.

Thanks for your time.
