### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by jacquelinelynch** [johngodley/redirection#3664]
```
SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list. https://xoxojackie.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2
```

Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 8.0.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
JavaScript: https://xoxojackie.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://xoxojackie.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. Please read the onscreen instructions.
