### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by khabirdada** [johngodley/redirection#3667]
Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
JavaScript: https://sportsbrowser.net/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://sportsbrowser.net/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. Please read the onscreen instructions.
