### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by mysuitcasejourneys** [johngodley/redirection#3668]
```
SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list. https://www.mysuitcasejourneys.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2,TypeError: null is not an object (evaluating 'document.getElementById("discard_content").classList') https://www.mysuitcasejourneys.com/wp-admin/tools.php?page=redirection.php 269
```

Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 8.0.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
JavaScript: https://www.mysuitcasejourneys.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.mysuitcasejourneys.com/wp-json/

**Comment by johngodley** [comment]
As the message states this is caused by another plugin.
