### ISSUE TITLE
Searching in the plugin results in a REST API error

### ISSUE THREAD

**Issue by Shidougit** [johngodley/redirection#3669]
When I try to search a URL it returns a REST API error: Failed to fetch. In the error screen is shows te REST API is OK and when I manually run the rest api url I get a proper JSON result.

Browser is Chrome: 114.0.5735.199
Plugin: 5.3.10 4.2
WordPress: 5.8.6 (single)
PHP: 7.4.33

**Comment by johngodley** [comment]
What are your search terms?

**Comment by Shidougit** [comment]
A single word test.
Query: ?page=redirection.php&filterby%5Burl%5D=test

**Comment by johngodley** [comment]
Ok, well the error message is from your browser, not the plugin, and is probably related either to a security plugin, or you need to logout, clear your cache, and log in again
