### ISSUE TITLE
How to download 404 errors?

### ISSUE THREAD

**Issue by Tagmeapp** [johngodley/redirection#367]
Hello

We have just migrated our large website to WP and there are many 404 errors. Is there a way to download the entire 404 error database?

**Comment by johngodley** [comment]
There is a CSV button at the bottom of the 404 page.

**Comment by Tagmeapp** [comment]
Ahh OK thanks!

Guy Ullmann
Sales & Marketing Director
Process Industry Informer
+44 (0) 1428 751188
guyullmann@piimag.com
www.piimag.com


<http://www.linkedin.com/in/guyullmann>




*PS. *Would you like to write for us? We're currently searching for
contributors for an exciting new section we're introducing! Find out more
here <http://www.processindustryinformer.com/landing-pages/write-for-us/>
