### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by ajaxStardust** [johngodley/redirection#3674]
```
Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 8.1.21
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
JavaScript: https://wordpresscenter.net/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://wordpresscenter.net/wp-json/
Query: ?page=redirection.php

Action: https://wordpresscenter.net/wp-json/redirection/v1/redirect/?orderby=id&direction=desc&per_page=25 POST
Params: {"id":0,"url":"/%year%/%monthnum%/%day%/%postname%/","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":true,"flag_case":true,"flag_query":"exact"},"options":{}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"https://wordpresscenter.net/%postname%/"}}
Code: 400 Bad Request

Error: Invalid source URL (redirect)
Raw: {"code":"redirect","message":"Invalid source URL","data":{"status":400,"error_code":297}}
```

**Comment by ajaxStardust** [comment]
also, for some reason the "301" plugin keeps changing "`%day%`" to "`y%`"
see here: 
https://imgur.com/gallery/zuHN3A8
just seems super weird to me. clearly something is not correct, perhaps on my server configuration as something else strange was noticed elsewhere (tables not being created for caching thumbs for a different plugin). on investigation, that issue had to do w/ WP setting table charset incorrectly (i think). 

This .gif should illustrate your plugin:
https://imgur.com/gallery/wtHnpps

**Comment by johngodley** [comment]
One of those screenshots is for another plugin.

You can't use `/%year%/%monthnum%/%day%/%postname%/` as a source URL as it's not a valid URL. The plugin shouldn't show an error like that, but it is showing a message underneath telling you what you should do instead.

**Comment by ajaxStardust** [comment]
appreciate your work, but your commentary is less than useful. 

Cheers!

**Comment by johngodley** [comment]
I'm sorry that my commentary doesn't meet your needs. The comment I left contains all the information regarding your problem. If you don't understand some of it then the usual process is to ask for clarification.

**Comment by ajaxStardust** [comment]
&quot;Redirection uses regular expressions&quot; would have been the useful answer

No one has time for nonsense. Whatever pleases you man. Wasted your time, and mine. It is what it is.
https://imgur.com/GvcrokQ
https://wpmarmite.com/en/wordpress-redirect/#groupes

**Comment by johngodley** [comment]
Ok. I don't know how you've interpreted this so badly. You've already made you mind up, and decided on your own answer. That's fine. Best of luck to you.
