### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by tabtxx88** [johngodley/redirection#3675]
```
SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list. https://www.welcometosedgebrook.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2
```

Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 7.4.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
JavaScript: https://www.welcometosedgebrook.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.welcometosedgebrook.com/wp-json/

**Comment by johngodley** [comment]
As detailed on the page this is likely caused by another plugin.

**Comment by tabtxx88** [comment]
I've checked the plugins that are active on the site and none being deactivated seems to fix the issue
