### ISSUE TITLE
Duplicate redirects generated

### ISSUE THREAD

**Issue by johnny-solargard** [johngodley/redirection#3679]
When Redirection is set to monitor pages for URL changes and when updating an existing page with a new URL, duplicate links are generated.  (relevant screenshots attached)

![redirect-update-url](https://github.com/johngodley/redirection/assets/47791525/9dd5dee2-f31e-4f21-a1f7-6d6b391a859b)
![redirect-posts](https://github.com/johngodley/redirection/assets/47791525/07dfbc74-2e20-4cf5-b9cd-7b71832d25f6)
![redirect-settings](https://github.com/johngodley/redirection/assets/47791525/524d8f82-3699-4122-8178-c12226b33681)

### Summary

Update page URL and have Redirection generate redirect URL

### Actual Behavior

Duplicate redirect URLs are generated

### Steps to reproduce

Click "Quick Edit" on Page screen, update URL and click "Update"

### Environment

Chrome:  Version 114.0.5735.110 (Official Build) (32-bit)
Wordpress Version: 6.2.2
Redirection Version: 5.3.10

**Comment by johnny-solargard** [comment]
Any update here?

**Comment by johngodley** [comment]
I am unable to reproduce this. Is it maybe connected to the language plugin you are using?
