### ISSUE TITLE
404 redirect forcing "select all"

### ISSUE THREAD

**Issue by ccgdigital** [johngodley/redirection#3680]
![Screen Shot 2023-08-01 at 1 48 40 PM](https://github.com/johngodley/redirection/assets/141173249/65030916-8dfc-45f6-b14c-ac8550d32ec7)

![Screen Shot 2023-08-01 at 1 43 03 PM](https://github.com/johngodley/redirection/assets/141173249/10f97dc0-76d7-441d-97e3-7f405b2b4a71)

When 1 redirect is selected it forces all redirects in that group to also be selected. 

We are trying to delete specific redirects and when selecting a redirect in the 404 group - any given redirect it will force a select all action. This makes deleting a selected group of redirects impossible.

### Steps to reproduce
1. open left nav Tools>Redirects
2. navigate to the 404 group
3. selected any redirect
4. all redirects within the 404 group will auto select 

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Google chrome | Chrome Version 114.0.5735.248 | WP version 6.2.2 | Redirection by: John Godley | Redirection version 5.3.10

**Comment by johngodley** [comment]
I can't reproduce this. Do you have any other plugins that could be causing this? Some plugins do interfere with other pages.

**Comment by ccgdigital** [comment]
We recently migrated to Cloudways but the error does not occur on our unchanged migrated installation. Since then, we've been working with another team who placed the 5 plugins below -  we're not 100% sure on how deeply they've been configured. Outright deactivation + deletion of the 5 plugins did not solve the error - though the Perfmatters was our initial conflict assumption due to its related settings to REST API + Rss feeds that appeared unset. But as noted, no luck so far. 

- Head, Footer and Post Injections
- OMGF
- Perfmatters
- WP Rocket
- WP Rollback
