### ISSUE TITLE
Regex redirects always append the content captured by the regular expression to the target

### ISSUE THREAD

**Issue by akafaust** [johngodley/redirection#3684]
### Summary

Regex redirects always append the content captured by the regex to the target

### Actual Behavior

Redirect must have static target

### Steps to reproduce

add redirect with "/author/*" Source URL and "/blog/" target

it should redirect from "/author/test/" to just "/blog/", but it redirects to "/blog/test/"

### Environment

It happens for all environments because it's backend issue

**Comment by johngodley** [comment]
`/author/*` is not a regular expression. As per the documentation you must use a valid regular expression that matches the whole URL

**Comment by akafaust** [comment]
I tried using "`/author/.*`" and "`/author/(.*)`" and I had the same problem but now it works, maybe it was some kind of cache (I cleared the browser cache every time)
Thanks for such a quick response!
