### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by olospo** [johngodley/redirection#3685]
```
Plugin: 5.3.10 4.2
WordPress: 6.2.2 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0
JavaScript: https://www.extreme-design.co.uk/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.extreme-design.co.uk/wp-json/
Query: ?page=redirection.php

Action: https://www.extreme-design.co.uk/wp-json/redirection/v1/redirect/?orderby=id&direction=desc&per_page=25 POST
Params: {"id":0,"url":"/test","title":"","match_data":{"source":{"flag_regex":false,"flag_trailing":false,"flag_case":false,"flag_query":"exact"},"options":{}},"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"/testing"}}
Code: 400 Bad Request

Error: Unable to add new redirect (redirect_create_failed)
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":297,"wpdb":"Duplicate entry '0' for key 'PRIMARY'"}}
```

We've recently moved the client to a new server, i'm not sure if it was working before the move. We do have "Redirection for Contact Form 7" installed but disabling that still causes an error. I've attempted in Chrome as well, with no browser extensions added. Are there any plugins in particular that might cause a conflict or is this something else?

Thanks
Tom

**Comment by johngodley** [comment]
Probably in moving to another server you have not copied the database tables correctly and are probably missing some of the indices. You should make sure the Redirection database tables are exactly the same as on your old server.

**Comment by olospo** [comment]
Hi John, Thanks for getting back to me. I've still got the old website is there a way to do a manual export of the redirects and import them into the new site?

**Comment by johngodley** [comment]
Sure, you can use the import and export feature.
