### ISSUE TITLE
Admin dashboard working but direct REST-API call not

### ISSUE THREAD

**Issue by marco910** [johngodley/redirection#3686]
When using the plugin in the Wordpress dashboard, everything works fine without any errors. Also redirects are working fine.

If I try to use the REST-API route `/wp-json/redirection/v1/redirect` in the same browser window and with the same user (admin user) as before in the Wordpress dashboard, I get the API error: `401 rest_forbidden`.

I have no idea what could cause this problem, because I'm trying this will I'm in an active admin session with an admin user which has all capabilities. I've also disabled all active plugins (expect for 'Redirection') and switched the theme without any difference - the error still occurs.

Any ideas what could cause this or how can I fix this?

**Comment by johngodley** [comment]
Try to use the route how?

**Comment by marco910** [comment]
I want to use the REST-API route `https://mywebsite.com/wp-json/redirection/v1/redirect` to query redirects which are created in the CMS.

When requesting the URL in the browser, I get an error even if I'm logged in as admin in the WordPress back-end in another browser tab: 
```
{
  "code": "rest_forbidden",
  "message": "Du bist leider nicht berechtigt, diese Aktion durchzuführen.",
  "data": {
    "status": 401
  }
}
```

When creating, removing or editing redirects in the back-end with the same user, everything works fine.

**Comment by johngodley** [comment]
It's not really designed to be used like that. You can find more details about using the WordPress REST API here:

https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

Redirection doesn't handle any of this so that is your best source of information.

It may be worth looking at the request the plugin makes and replicating that.
