### ISSUE TITLE
Redirection not always working

### ISSUE THREAD

**Issue by agencyb1** [johngodley/redirection#3688]
### Summary

Redirects initially worked, and seem to mostly be functioning as it should - some of the redirects, namely the home pages of the websites we have redirected, switch back to the original link. This has happened across most of the websites we've used the redirection on - and does eventually switch itself back after a few refreshes, but hoping there's a permanent fix to it. 
![Screen Shot 2023-08-16 at 1 00 07 pm](https://github.com/johngodley/redirection/assets/142369091/9faad75a-b57b-4f61-9274-2ca8b95d03fd)
![Screen Shot 2023-08-16 at 1 00 18 pm](https://github.com/johngodley/redirection/assets/142369091/a9d7ce7f-026a-4dbd-b66d-40ed73565ce6)
![Screen Shot 2023-08-16 at 1 00 47 pm](https://github.com/johngodley/redirection/assets/142369091/6b503910-058f-4fdc-b259-72e6d8918fb4)

### Environment

Google Chrome - 115.0.5790.170
WordPress - 6.0.05
Redirection - 5.3.10

**Comment by johngodley** [comment]
I don't know what the screenshots are showing, but the URL seems to be redirecting without problem.

A redirect will not switch back or change in any way. If you are seeing something other than the expected redirect then you should clear your browser cache.
