### ISSUE TITLE
Redirected posts still showing up in my site search

### ISSUE THREAD

**Issue by mhlebaron** [johngodley/redirection#369]
When I type a keyword into my site's search bar, redirected links are still showing up with the title and link. When I click the link, it does redirect, but I don't want it showing up in my search at all. 

Thoughts?

Thanks :)

**Comment by johngodley** [comment]
Redirection won't change the links on your site, it just redirects from one URL to another. If you have a page that you are redirecting appear in your search you will need to delete the original page.

**Comment by mhlebaron** [comment]
Ok. On that note, can I delete that url on my site, but keep the redirect? Will the redirect still work on a deleted post? 

Thanks :)

**Comment by johngodley** [comment]
Yep, you don't need the original post.
