### ISSUE TITLE
Redirection Plugin Not Working

### ISSUE THREAD

**Issue by rhagge** [johngodley/redirection#3690]
I get the "405 Method Not Allowed" error on nearly **EVERY** single redirect I have. 

Here is an example of what I have a redirect set up for: 

https://www.pathguide.com /9-qualities-to-look-for-in-a-warehouse-management-system/ to 
https://www.pathguide.com/news/9-qualities-to-look-for-in-a-warehouse-management-system/

I've gone to https://redirect.li/ to research and I've also cleared my browser cache.

Chrome is my browser. I am using Chrome 116.0.5845.97 (Official Build) (64-bit). I am current with WordPress (6.3). The Redirection version I am using is 5.3.10.

_As a side note, my indexed pages on Google Search Console have dropped quite a bit._

My email is rhagge@pathguide.com. I'd love to know what's going on as quickly as possible, please.

Thanks!

Rebecca

**Comment by rhagge** [comment]
The correct redirect example above should read:

https://www.pathguide.com/9-qualities-to-look-for-in-a-warehouse-management-system/
https://www.pathguide.com/news/9-qualities-to-look-for-in-a-warehouse-management-system/

**Comment by johngodley** [comment]
The 405 is not caused by Redirection. You will need to figure out what is causing this. It may be a security plugin of some kind.

**Comment by rhagge** [comment]
I guess I don’t understand. This is the error message I get when I check to make sure the redirects are working within the plugin.

Do you have any recommendations of who I should contact to investigate? My knowledge is quite limited, but I’d like to get this fixed.

***@***.***




Rebecca Hagge
Marketing Communications Manager
***@***.******@***.***>

**Comment by johngodley** [comment]
Sure. However, you get the same 405 error regardless of what URL you enter:

https://redirect.li/http/?url=https%3A%2F%2Fwww.pathguide.com%2Fcat%2F

This is your website causing the error, not Redirection.

**Comment by rhagge** [comment]
Interesting.

Okay, thank you.




Rebecca Hagge
Marketing Communications Manager
***@***.******@***.***>
