### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by dicofle** [johngodley/redirection#3693]
```
Uncaught ReferenceError: wp is not defined https://dicofle.net/wp-admin/tools.php?page=redirection.php&sub=options 267
```

Plugin: 5.3.10 4.2
WordPress: 6.3 (single)
PHP: 7.4.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
JavaScript: https://dicofle.net/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://dicofle.net/wp-json/

**Comment by johngodley** [comment]
This error is not caused by Redirection. You will need to resolve whatever is causing it.
