### ISSUE TITLE
Redirect only if post does not exist

### ISSUE THREAD

**Issue by chrisGeonet** [johngodley/redirection#3695]
I have a client that for various reasons has multiple posts with the same title, therefore getting a number appended to the permanlink.
When they delete one of the posts (eg post-2) they create a redirect for it to the appropriate destination.
But.. when they add a new post with the same title it will reuse the gap in the permalink numbering, so post-2 is used.

Because the redirection still exists, post-2 is not accessible.

Is there any way to configure this plugin so that it only redirects if there isn't a post with that permalink, ie it would get a 404 response?

Thanks

**Comment by johngodley** [comment]
You could use a 'URL and WordPress page type' match. It is specific to each redirect.

**Comment by chrisGeonet** [comment]
> You could use a 'URL and WordPress page type' match. It is specific to each redirect.

That works. Thanks, big help.
