### ISSUE TITLE
Adding redirections using PHP

### ISSUE THREAD

**Issue by design311** [johngodley/redirection#37]
I'm not sure if this is possible already but it would be great if we could add redirections using PHP, for example after publishing a post.

I want to redirect domain.com/xyz to domain.com/posttype/long-title-for-custom-post-type, this could be easily achievable if we could add redirects using PHP.

**Comment by johngodley** [comment]
Where is the PHP you want to use? Are you talking about another plugin?

**Comment by design311** [comment]
Sorry for the misunderstanding, I am not talking about a different plugin. I am currently building a custom WordPress theme and I want the link it with Redirections.

Does the plugin provide any way to add redirections in code?

**Comment by johngodley** [comment]
Hi,

Sorry, I still don't understand. Yes, the plugin does have a way to add redirections in code - this is how the plugin does it. I don't understand how or why you'd do this from outside the plugin though? Can you describe more about what you are trying to achieve and how it relates to a custom theme?

**Comment by design311** [comment]
It is a custom theme, only going to be used for this specific client. I would like to forward a custom short URL to the longer URL, the short URL will be used in print advertising so we do not want to use a bitly service or something like that.

Of course your plugin adds the redirections in the code, but does the user have the option to do something like that outside the plugin as well?

**Comment by johngodley** [comment]
Ok, so in the theme you want to be able to call Redirection directly?

**Comment by design311** [comment]
Correct. I want to do something like:

add_redirection('domain.com/short', 'domain.com/customposttype/post-with-a-very-long-title/');

**Comment by design311** [comment]
Is something like this possible?

**Comment by Stoux** [comment]
@design311 @johngodley I'm also wondering if this is possible.

**Comment by alpipego** [comment]
@design311 @Stoux If you're still trying to figure this out... the main portion is the [`Red_Item::create`](https://github.com/johngodley/redirection/blob/master/models/redirect.php#L145-L214) method. 

For adding a 301 redirect, you should be able to call it with:

```
Red_Item::create( [
	'source'     => (string) $source,
	'target'     => (string) $target,
	'regex'      => (bool) $regex,
	'group_id'   => (int) $groupId,
	'red_action' => 'url',
	'match'      => 'url',
] );
```

**Comment by johngodley** [comment]
Closing this as I think it's been answered.
