### ISSUE TITLE
Problem starting Redirection 2.7.3

### ISSUE THREAD

**Issue by abinrimal** [johngodley/redirection#370]
```
Uncaught SyntaxError: Unexpected end of input https://bhugarva.com/book/wp-content/plugins/redirection/redirection.js?ver=2.7.3-a27c77af0d47abb92ce2f83236f9986b 11
```

Plugin: 2.7.3
WordPress: 4.8.1
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by johngodley** [comment]
Can you include the full error details?

**Comment by johngodley** [comment]
The file redirection.js on your website is only 94KB. The file contained with the plugin is 376KB. You will need to reinstall the plugin
