### ISSUE TITLE
404 redirect forcing "select all"

### ISSUE THREAD

**Issue by ccgdigital** [johngodley/redirection#3700]
![Screen Shot 2023-09-01 at 2 12 43 PM](https://github.com/johngodley/redirection/assets/141173249/66ac0756-eed0-411f-b492-a3183f0f0420)
![Screen Shot 2023-09-01 at 2 12 55 PM](https://github.com/johngodley/redirection/assets/141173249/aee200b9-bc3b-46c1-a9bd-764547bf485a)

When 1 redirect is selected it forces all redirects in that group to also be selected.

We are trying to delete specific redirects and when selecting a redirect in the 404 group - any given redirect it will force a select all action. This makes deleting a selected group of redirects impossible.

Steps to reproduce
open left nav Tools>Redirects
navigate to the 404 group
selected any redirect
all redirects within the 404 group will auto select
Environment
Please list your browser, browser version, version of WordPress and Redirection plugin.

Google chrome | Chrome Version 114.0.5735.248 | WP version 6.2.2 | Redirection by: John Godley | Redirection version 5.3.10

additional notes:

We recently migrated to Cloudways but the error does not occur on our unchanged migrated installation. Since then, we've been working with another team who placed the 5 plugins below - we're not 100% sure on how deeply they've been configured. Outright deactivation + deletion of the 5 plugins did not solve the error - though the Perfmatters was our initial conflict assumption due to its related settings to REST API + Rss feeds that appeared unset. But as noted, no luck so far.

Head, Footer and Post Injections
OMGF
Perfmatters
WP Rocket
WP Rollback

**Comment by johngodley** [comment]
What is the 404 group? The 404 log page shows 404 errors, not redirects. I am unable to reproduce any issue with a checkbox selecting everything. Is it possible this is caused by another plugin?

**Comment by ccgdigital** [comment]
These are all added under 404s. The redirect tab works as expected we are only seeing this issue under the 404s tab and there is no grouping selected for the filters. 

Could it be one of these 5 plugins causing conflict?

Head, Footer and Post Injections
OMGF
Perfmatters
WP Rocket
WP Rollback

**Comment by johngodley** [comment]
I don't know if those plugins are causing the problem. You will need to experiment and see if disabling one stops the problem happening.

**Comment by johngodley** [comment]
Please don't create duplicate issues #3680
