### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by Nlansong** [johngodley/redirection#3701]
Plugin: 5.3.10 4.2
WordPress: 6.3.1 (single)
PHP: 8.0.25
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
JavaScript: https://www.glusea.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.glusea.com/wp-json/

**Comment by johngodley** [comment]
As the page describes this is almost certainly caused by another plugin.
