### ISSUE TITLE
Error 410

### ISSUE THREAD

**Issue by RennesleChateau** [johngodley/redirection#3704]
Good morning,
When I select "when matched" error (404) with HTTP code 410 - gone, the 410 error does not appear on the page but the 404 error! Is this normal?
Do search engines understand error 404 or error 410?
THANKS !

**Comment by johngodley** [comment]
Can you give an example of what you mean? If you pick 410 then you will get a 410. How does 404 come into this?

**Comment by RennesleChateau** [comment]
Settings in "Redirection" ![parametres-error-410](https://github.com/johngodley/redirection/assets/144523753/6e56fecc-1fce-4098-b8af-e8d8452d4085)

Test of the link in the "Redirection" support: error 410! ![test-redirection-410](https://github.com/johngodley/redirection/assets/144523753/780cf1b6-119d-47a0-8f76-4a6d48337112)
!

But on the (events) page of my site, I have a 404 error [site-error-404](https://github.com/johngodley/redirection/assets/144523753/5432c17c-15ba-49a8-8d41-809e4f0b0cad)

Or do you have to wait a while?

**Comment by RennesleChateau** [comment]
I tell you that I had emptied the cache!

**Comment by johngodley** [comment]
You don't need to wait, you just need to clear your cache. The URL seems to be working

**Comment by RennesleChateau** [comment]
I tell you that I had emptied the cache! I just checked just now!

I have an additional question: what is the syntax to put the entire "events" directory in 410 error?
To be clearer: what should be added to this url (https://portail-rennes-le-chateau.com/evenements/) to put all the urls in the “events” directory in error 410?

**Comment by johngodley** [comment]
Sure, but the checker is showing it is returing a 410. Therefore your cache is the only thing that can be affecting it. You may have more than one cache.

You can use a regular expression, as detailed on the support site: https://redirection.me/support/redirect-regular-expressions/

**Comment by RennesleChateau** [comment]
Thanks for the link, I just changed the syntax :-)
So I should have a page with code 410? I just used CCleaner and I still get 404! 
But the most important thing is what the search engines see: if I understand correctly, they see the code 410! ?

**Comment by johngodley** [comment]
How is CCcleaner involved?

What is the URL you are checking?

**Comment by RennesleChateau** [comment]
Ccleaner: cache, cookies, history, download history, download location, recently typed address, temporary files, etc.

URL : https://portail-rennes-le-chateau.com/evenement/
https://portail-rennes-le-chateau.com/evenements/
https://portail-rennes-le-chateau.com/evenements/2023-10-28/

**Comment by johngodley** [comment]
It is working fine:

https://redirect.li/http/?url=https%3A%2F%2Fportail-rennes-le-chateau.com%2Fevenement%2F

It is also a 410 for me, and will be a 410 for everyone else.

Typically you use your browser to clear your cache.

**Comment by RennesleChateau** [comment]
Thank you very much, John 👍 
Have a nice week end.
