### ISSUE TITLE
Duplicate Header Problem in Redirect.li

### ISSUE THREAD

**Issue by ChrisBocay** [johngodley/redirection#3706]
Hello John!

I am using your excellent WP plugin called "Redirection" and it seems to work perfectly for me.
I am an ex-developer who is very detail-oriented, so when I say that it works perfectly, I really mean it.

However, today when I was editing some URLs, I was checking out the "Check Redirect" function for one of my redirects. (This is a wonderful feature, by the way!)

In any case, I then didn't just settle with that initial screen, but went ahead to the "View full redirect.li results" web page. And I then expanded that view by clicking on the "Show Details" button (upper right corner).

And then, when I inspected that long page, I discovered an error saying:

_"Problems were detected with this header: 
Duplicate header. There is another header 
with this name and this may cause problems."_

Since I know nothing about HTTP headers, I have little more "solid" info to give. But I am guessing that the problem is that there are TWO "Vary" entries for the target URL (Vary: Accept-Encoding; and Vary: Cookie), while there is only ONE "Vary" entry for the source URL (Vary: Cookie).

So here is an example of the two "Vary" entries for a target URL....
![RedirectLi_Source_TwoVaryEn](https://github.com/johngodley/redirection/assets/110173958/2562cfe0-ebea-4084-a139-0536ed2d2fe7)

...and here is an example of the corresponding singular "Vary" entry for the source URL: 
![RedirectLi_Source_OneVaryEn](https://github.com/johngodley/redirection/assets/110173958/aa64be2f-6305-4085-b465-5f56e6291897)

-----------------------
To Replicate
-----------------------

And this behavior is consistent for all redirected URLs I have tried. Here are some redirected URLs that you can try for yourself in redirect.li to verify this particular error:

https://chrisbocay.com/revised-master-the-law-of-attraction/

https://chrisbocay.com/2022/05/01/the-9-best-ways-to-improve-your-positivity-and-happiness/

https://chrisbocay.com/2022/05/31/what-is-self-acceptance/

It would be great to know if this is something that I have caused myself (with my Redirection settings, or with some other WP setting), or whether this is a thing generated by the Redirection plugin regardless of settings. Or perhaps it is just a redirect.li "idiosyncracy", that one should just ignore?

-----------------------
Redirection settings
-----------------------

Worth noting is also that all options for Redirection are left as they were when I installed the plugin (Mon 28 Aug 2023). Also worth noting: Rest API status and Plugin Status buttons are all green with the text "Good". Database version is 4.2.

-----------------------
Environment
-----------------------

Fujitsu Celsius workstation W510
Windows 10 Pro (Version 22H2)
Google Chrome (Version 116.0.5845.188 (Official Build) (64-bit))

Best wishes!
Chris Bocay
https://chrisbocay.com/science-and-the-law-of-attraction/

**Comment by johngodley** [comment]
The checker is just reporting that there are duplicate headers. Whether this is an problem or not is another matter, and it's not something I would worry about. Redirection is not adding the header, so it's likely out of your control anyway, and as such is probably fine.

**Comment by ChrisBocay** [comment]
Hello John,

Thank you very much for this answer!! It is very good to know that Redirection is not adding the header, and that this behavior, most probably, is not anything to worry about.

Hoping you'll have a GREAT week!
Chris Bocay
https://chrisbocay.com/
