### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by stephencodes2017** [johngodley/redirection#3707]
```
Uncaught SyntaxError: Unexpected end of input https://www.g2ref.co.uk/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2
```

Plugin: 5.3.10 4.2
WordPress: 6.3.1 (single)
PHP: 8.2.9
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by johngodley** [comment]
As described in the error this is almost certainly caused by another plugin.

**Comment by stephencodes2017** [comment]
It was working fine as of yesterday and I have not uploaded another plugin
or add anything else. So its kinda strange.

**Comment by johngodley** [comment]
The plugin hasn't changed so something else on your site will have changed to cause this.

**Comment by stephencodes2017** [comment]
Alright no worries, I will try to redownload and install it
