### ISSUE TITLE
Redirects with Source URLs containing German Umlauts not working

### ISSUE THREAD

**Issue by nancyfancy** [johngodley/redirection#371]
We have a redirect issue with an urls that contain a German Umlaut (like ä, ü, ö or ß ).

Whenever we have a source URL that contains a German Umlaut the redirect does not work.
Instead of the target page we get a 404 Error Page.
On one of our other wordpress sites we still use your plugin version 2.5 and with this version it is possible to set redirects with a source URL containing a German umlaut.
So we thought this issue might be related to the new version?

We checked the redirect issue with German Umlauts on several machines: Mac (Chrome, Firefox both newest version), PC (Chrome, Firefox both newest version)

Please list your browser, browser version, version of WordPress and Redirection plugin.
On the Site with non working German Umlauts we have Wordpress 4.8 and Redirection plugin version 2.7.3

On the Site with working German Umlauts we have 4.8 Wordpress Version and Redirection Plugin Version 2.5

**Comment by johngodley** [comment]
You will need to URL encode the umlaut. For example, ä becomes %C3%A4. You can do this with a tool such as http://meyerweb.com/eric/tools/dencoder/

**Comment by tjkelly** [comment]
@johngodley could you demonstrate how to do this? I'm having the same problem with French, specifically the é character in the word résumé.

Eric's dencoder tool says to use **_%C3%A9_**

My redirect rule includes _**-r**_%C3%A9_**sum**_%C3%A9_**/**_ for _**-résumé/**_

But it's still not working. All I want to do is replace _**-résumé/**_ with _**-resume/**_. I don't need to maintain the é characters in the URL.

Given that, can you explain what the proper redirect syntax would be?

**Comment by nancyfancy** [comment]
It works now at least for the https URL version of the website, as the website is running on https.
ususally the http version is redirecting to https - which works fine for all redirected URL not containing a German Umlaut. 
We have e.g. a redirect from /home/symptome/ to https://www.my-domain/ursachen-und-symptome/ works fine (for source URL with https and http).
But as soon as the source URL contains a German Umlaut the redirect only works for the source URL in its https version. source URL with http is not being redirected and I get a 404.
Would be great, if you could give advice what to do.
many thanks
nancyfancy

**Comment by johngodley** [comment]
Can you show a URL that isnt working in http?

**Comment by nancyfancy** [comment]
http://www.darmsprechstunde.de/home/diagnosen/hämorrhoiden/

**Comment by johngodley** [comment]
Gosh, sorry for missing this so long. I checked the above URL and it seems to be redirecting so I will assume you fixed the problem or are using something else. I'll close this for now, but do reopen or file a new issue if you need any other help.
