### ISSUE TITLE
New behavior: #038; showing up after & in url

### ISSUE THREAD

**Issue by Scottj711** [johngodley/redirection#3711]
### Summary

Ampersand converts to &\#038;

### Actual Behavior

For years, redirection successfully redirected to a link that contained an ampersand. The latest version adds #038; after the ampersand, like so: website.org/forums/viewtopic.php?f=8&\#038;t=7

### Steps to reproduce

1. Create a redirection to a link with an ampersand
2. Type that redirection into the browser
3. Notice that it has been replaced with a code that all three browsers are not interpreting as an ampersand

### Environment

Browsers: Chrome, Edge, Firefox, Version of WordPress: 6.3.1, Redirection plugin 5.3.10

**Comment by johngodley** [comment]
Nothing has changed in the plugin for quite a while now. Meanwhile, WordPress has changed. Is it possible that is the cause?

https://gaais.org/meeting-etiquette does not show any error

**Comment by Scottj711** [comment]
Thanks for responding! Yes, must be WordPress.
