### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by VIPTRIPSFORKIDS** [johngodley/redirection#3716]
```
SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list. https://viptripsforkids.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2
```

Plugin: 5.3.10 4.2
WordPress: 6.3.1 (single)
PHP: 8.0.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
JavaScript: https://viptripsforkids.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://viptripsforkids.com/wp-json/

**Comment by VIPTRIPSFORKIDS** [comment]
Hi, can someone help, please?

**Comment by johngodley** [comment]
As the error states this is almost certainly caused by another plugin.

**Comment by VIPTRIPSFORKIDS** [comment]
I deactivated all plugins and then activated one by one but it didn't solve it?

**Comment by johngodley** [comment]
Have you tried clearing your browser cache? Maybe another browser?

**Comment by VIPTRIPSFORKIDS** [comment]
Yes and tried incognito also

**Comment by johngodley** [comment]
I am unable to reproduce this. If it is still a problem please contact me with login details where I can see it in action.
