### ISSUE TITLE
bulk redirection / 404 log clear buttons

### ISSUE THREAD

**Issue by adambcohen** [johngodley/redirection#3717]
My logs hit tens of thousands by the end of the day, and I'd love to have functional buttons to drop the logs upon pressing the button vs going into phpmyadmin and truncating the logs.

**Comment by adambcohen** [comment]
My logs hit tens of thousands by the end of the day, and I'd love to have functional buttons to drop the logs upon pressing the button vs going into phpmyadmin and truncating the logs.

**Comment by johngodley** [comment]
You can use the checkboxes and the bulk action to delete everyting.

**Comment by dawnerd** [comment]
@johngodley I was looking for a similar feature, the bulk action ends up timing out when you have a lot (like you forget to turn logging off, etc). Would it be possible to maybe have a cli cmd? Truncating the db isn't always an option on our production sites with some clients and environments, at least not easily.
