### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Movieslists02** [johngodley/redirection#3719]
keep getting this error: 
GET POST TypeError: Failed to fetch

Failed to fetch

Unable to make request due to browser security. This is typically because your WordPress and site URL settings are inconsistent, or the request was blocked by your site CORS policy. 

I tried every api suggested by your plugin fix but nothing worked. The plugin status all good. I am wondering if its the url I want my site to redirect to is because its an expired url and I have no access to it due to it being sale?

**Comment by johngodley** [comment]
I don't know what you mean about an expired URL.

The error is from your browser, not the plugin, and the main causes are given in the message. Something is preventing requests being made.

**Comment by Movieslists02** [comment]
Let me explain. The domain I want to redirect my current domain to is
expired. I did not renew the domain contract, so the domain merchant offer
it up for sale. Is it possible to still point current domain including
website to such a domain using your plugin?

**Comment by johngodley** [comment]
You can redirect to any URL, whether you own it or not.

**Comment by Movieslists02** [comment]
Thanks for the tip!

**Comment by Movieslists02** [comment]
It redirects but doesn't show what's on the current site domain. It show
website cannot be reached. Says site unexpectedly closed the connection.
Why is this please?

**Comment by johngodley** [comment]
That is not a question related to Redirection
