### ISSUE TITLE
All 301 redirects are now 0 and no redirects work anymore

### ISSUE THREAD

**Issue by CraigT543** [johngodley/redirection#372]
My redirects have all stopped working recently.  I had a client end up on a page that was redirected last week and found that all my redirects are now showing up as 0 and when I look at them in the settings I see that they are all blank in the log in log out fields.  What do I need to do?

**Comment by johngodley** [comment]
What do you mean they are showing as 0 and the log in log out fields are blank?

Can you list a URL here that isn't working?

**Comment by CraigT543** [comment]
Thanks for the reply, in the settings, type column, all are now showing up as 0, most of which were 301, and when looking at the settings for each entry, they are now blank for 
Logged In
Logged Out

Where before they contained the redirected link.

When I try to enter a new entry, I see all the settings for the new entry but it does not work.  The old entries do not work either.  This became apparent over the last two weeks.

**Comment by CraigT543** [comment]
I am looking at the wp_redirection_items table and I see that all the action_code items are set to 0.  I went through and reset them to the correct nunber, 308 and 301.  So, for some reason every thing reset to 0 after one of the updates.  Then I checked the settings and the redirect url's were not showing up.  In the wp_redirection_items all the redirects were there.  So, what I did was extract all the data from that table and re-enter all the redirections in the settings.  I did that and now it works as before.  So I am not sure what caused this glitch: all action_items turned to 0 and for some reason action_data did not parse out and load.  After re-entering it all, it works again.

**Comment by johngodley** [comment]
That's strange. There's nothing in Redirection to update anything in that way. You mention that it happened after an update - do you happen to know what version you were running before the update?

**Comment by p-cx** [comment]
This is also happening for me. Old redirections had type 0 and all new redirects also default to type 0 (although they say 301 in the settings when I click the gear icon). I have to save it as another type, then resave it as 301 to get it to save as 301. I didn't bother going to the database directly as I didn't have too many redirects to correct.
