### ISSUE TITLE
Critical error when editing custom post types

### ISSUE THREAD

**Issue by janine** [johngodley/redirection#3723]
**Description:**
When attempting to edit custom post types, a critical error occurs, preventing any editions from being made to custom post types.

**Steps to Reproduce:**

**Expected Behavior:**
The custom post types should be editable without any issues.

**Actual Behavior:**
A critical error message is displayed, and the changes to the custom post type are not possible.

**Error Message:**
"There has been a critical error on this website. Please check your site admin email inbox for instructions."

**Additional Information:**

- The issue is consistent across different browsers and devices.
- The issue occurs irrespective of the theme in use.
- Deactivating other plugins to check for conflicts did not resolve the issue.

**Comment by johngodley** [comment]
What is the critical error?

There have been no reports of this for other people.

**Comment by johngodley** [comment]
Closing for now, please re-open with more information.
