### ISSUE TITLE
Alias fails to match when using a specific port.

### ISSUE THREAD

**Issue by Chris--S** [johngodley/redirection#3724]
### Summary

Alias fails to match when using a specific port.

### Actual Behavior

Attempting to create an alias with a port strips the port from the saved alias value,  but when attempting to match the request against the alias list the server port is included (when part of the url request).   Should either, allow alias with port or strip the port from the server when matching to the alias.

E.g.
Attempting to create this alias...
some.domain:1234 => my.site 

After update the page shows the alias saved as
some.domain => my.site

When making a request to some.domain:1234
The code (~/wp-content/plugins/redirection/models/canonical.php line #70) attempts to match 
(the request $server) "some.domain:1234" to the alias "some.domain"
and the match fails, so no redirect happens.

### Environment

WordPress: 6.3.1
Redirection 5.3.10.

**Comment by johngodley** [comment]
The port will be ignored in the next version of the plugin.
