### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by pedroaleluia00** [johngodley/redirection#3725]
```
Uncaught TypeError: Cannot read properties of null (reading 'id') https://www.eyeqgaming.com/wp-content/plugins/copy-delete-posts/banner/assets/index.min.js?ver=1696804755 1
```

Plugin: 5.3.10 4.2
WordPress: 6.3.1 (single)
PHP: 8.2.11
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
JavaScript: https://www.eyeqgaming.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.eyeqgaming.com/wp-json/

**Comment by johngodley** [comment]
The problem is shown in the message above. It does not seem related to Redirection.
