### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by Manhique84** [johngodley/redirection#3726]
Plugin: 5.3.10 4.2
WordPress: 6.3.2 (single)
PHP: 8.1.24
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
JavaScript: https://todasvagas.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://todasvagas.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. Please read the onscreen instructions.
