### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by stayjournalive** [johngodley/redirection#3728]
Your WordPress REST API is returning a 404 page. This is almost certainly an external plugin or server configuration issue.

You will need to fix this on your site. Redirection is not causing the error.
Can you access your without it redirecting?.
Check your and fix any issues.
Your server configuration is blocking access to the REST API.
A security plugin or firewall is blocking access. You will need to whitelist the REST API.
[Read this REST API guide for more information.](https://redirection.me/support/problems/rest-api/)

**Comment by johngodley** [comment]
Please follow the instructions. This is caused by your site, not the plugin.
