### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by dinwal** [johngodley/redirection#3729]
```
Uncaught SyntaxError: Unexpected token '}' https://recurpost.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2
```

Plugin: 5.3.10 4.2
WordPress: 6.3.2 (single)
PHP: 8.0.28
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
JavaScript: https://recurpost.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://recurpost.com/wp-json/

**Comment by johngodley** [comment]
Something is wrong with your installation. Compare https://recurpost.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 with https://urbangiraffe.com/wp-content/plugins/redirection/redirection.js - the end of the file is very different.

**Comment by johngodley** [comment]
It looks like your file has extra code at the end. I dont know what that is, but it's not part of the plugin.

**Comment by dinwal** [comment]
I deleted the plugin and installed it again. The files look the same but still the same error.

**Comment by dinwal** [comment]
Thanks for your prompt reply though.

**Comment by johngodley** [comment]
Try clearing your browser cache. The file looks correct now.
