### ISSUE TITLE
Using a different WordPress Address (URL) and Site Address (URL)

### ISSUE THREAD

**Issue by samholguin** [johngodley/redirection#3732]
I am using the [Roots Bedrock](https://roots.io/bedrock/) WordPress framework which uses a different WordPress Address (URL) to the Site Address (URL). I believe this is triggering the error stated in the docs [here](https://redirection.me/support/problems/rest-api/#url), causing the plugins search functionality to be unusable. 

Is there a workaround?

Thanks

**Comment by johngodley** [comment]
The example given in the support guide is referring to the different of http and https. I do not know about your framework, but it needs to be compatible with any plugin accessing the WordPress REST API. This is not specific to Redirection.

**Comment by samholguin** [comment]
Thanks John, my apologies, I misread the docs, I thought the following would be an issue:

Site Address: https://mydomain.com
WordPress Address: https://mydomain.com/wp

I have tested a similar build and that works, so it must be something else.
