### ISSUE TITLE
Problem starting Redirection 3.4

### ISSUE THREAD

**Issue by rajwebindia** [johngodley/redirection#3733]
```
Uncaught ReferenceError: _ is not defined https://bengaluru.urbanwaters.in/wp-admin/tools.php?page=redirection.php 646,Uncaught ReferenceError: moment is not defined https://bengaluru.urbanwaters.in/wp-admin/tools.php?page=redirection.php 650,Uncaught TypeError: Cannot read properties of undefined (reading 'setLocaleData') https://bengaluru.urbanwaters.in/wp-admin/tools.php?page=redirection.php 666
```

Plugin: 3.4
WordPress: 5.4.13 (multi)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
JavaScript: https://bengaluru.urbanwaters.in/wp-content/plugins/redirection/redirection.js
REST API: https://bengaluru.urbanwaters.in/wp-json/

**Comment by johngodley** [comment]
As detailed on the error page this is caused by another plugin.
