### ISSUE TITLE
wp_redirection_404 table keeps on filling up

### ISSUE THREAD

**Issue by wadih** [johngodley/redirection#3734]
Hi,

The wp_redirection_404 table keeps on filling up, although under Options > 404 Logs = 1 week . 

I found out doing a routine check for large tables in the database, and noticed this table not following the 1 week limit.

The earliest entries in the table are dating March 2022.

Is there something I can test before clearing out the table? 
![2023-10-28_11-38](https://github.com/johngodley/redirection/assets/1222066/1bf81fb7-32b2-44a2-8bf4-426578aafb60)
![Screenshot from 2023-10-28 11-37-44](https://github.com/johngodley/redirection/assets/1222066/c545943f-06be-429d-95f1-c7a2bca615f9)
![Screenshot from 2023-10-28 11-39-20](https://github.com/johngodley/redirection/assets/1222066/db28d722-7094-4c4c-8048-3846165d3d00)

**Comment by johngodley** [comment]
The expiry uses WP Cron. If this is not active on your site then it won't clear stuff out.

**Comment by wadih** [comment]
Hi thank you

I ran the domain.tld/wp-cron.php and it got cleared afterwards.

I thought wordpress ran it sporadically on page visits when there was no cron job, appears that is not the case.

many thanks

**Comment by johngodley** [comment]
> I thought wordpress ran it sporadically on page visits when there was no cron job, appears that is not the case.

It does, but it's possible this has been disabled on your site, or isn't functioning properly.
