### ISSUE TITLE
PHP 8.1: auto_detect_line_endings INI directive is deprecated

### ISSUE THREAD

**Issue by Nikschavan** [johngodley/redirection#3737]
### Summary

The ini directive is deprecated since PHP 8.1 - https://php.watch/versions/8.1/auto_detect_line_endings-ini-deprecated

This is used in the CSV importer logic here - https://github.com/johngodley/redirection/blob/8c334ddc7e28b20824d0612e671ce9c05ad1a968/fileio/csv.php#L63-L67

### Actual Behavior

1. PHP warnings generated
2. Errors reported by PHPCS

### Steps to reproduce

This can be reported locally in WPCS/PHPCS with PHP Compatibility standards.

### Environment

Local environment.

**Comment by johngodley** [comment]
These will be removed in the next version.
