### ISSUE TITLE
Redirecting sub folders under folders

### ISSUE THREAD

**Issue by QwertyOK1** [johngodley/redirection#374]
Is there a way to redirect all subfolders under a folder. For example, I have a site that has URL's like domain.com/uncategorized/1, domain.com/uncategorized/2, domain.com/uncategorized/3 that I want to redirect all of these. I attempted to use /uncategorized/ and /uncategorized/* but neither of these seem to work. How can I say I want anything that has uncategorized in the URL to be redirected?

**Comment by johngodley** [comment]
Yes, you need to use a regular expression and check the regex checkbox. `*` on its own is not a regular expression. You can press the `?` next to the regular expression checkbox to get more help

**Comment by QwertyOK1** [comment]
Thanks for the information. That worked perfectly.
