### ISSUE TITLE
Redirections and encoding

### ISSUE THREAD

**Issue by blorange2** [johngodley/redirection#3740]
Hi,

I have been using this plugin for a while and it works very well, I just have a question around a specific use case which is when URLs have random extras at the end. 

For instance: /privacy-and-cookies-policy-for-newable-business-loans/**?_gl=1*1xwq8gj*_gcl_au*Mzk4MjM3MTY4LjE2OTY4NDk2MjY.**

If I make a redirect like so:

![image](https://github.com/johngodley/redirection/assets/13929733/755b8109-1ce2-492c-bda9-69c2fb0268f5)

The plugin will say that the redirect is working.

![image](https://github.com/johngodley/redirection/assets/13929733/145a309d-2e6f-4b7f-abc6-a248b8fccea6)

How do I stop it from encoding the URL as that would seem to be the issue?

I am using the latest version of the plugin, WordPress and Google Chrome.

Thanks in advance for your support.

**Comment by johngodley** [comment]
That would seem to be what issue? Is the redirect not working?

**Comment by blorange2** [comment]
Hi,

Apologies for the delay in coming back on this. 

Essentially what I've found is that if you're using cross domain tracking in GA4 it'll add the `_gl` parameter parts and what I was finding is that these would throw off the redirects.

I would much rather `example.com` redirected to `example.com/home` irrespective of whether there were any extra parameters.

This is because at my place of work I don't manage Google Ads and the like so never know what Ad links are being generated.

In summary is there a way to have a "catch all" redirection?  

E.g.

`newable.co.uk/example?someotherstuff` and `newable.co.uk/example` should both redirect to `services.newable.co.uk/someother example`.

I added the following directly into my `.htaccess` file.

```
# BEGIN manual redirects
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^privacy-and-cookies-policy-for-newable-business-loans/?$ https://services.newable.co.uk/privacy-and-cookies-policy-for-newable-business-loans/? [R=301,L,NC]
RewriteRule ^(money/private-investing)/ https://www.newable.co.uk/ [R=301,L,NC]
</IfModule>
# END manual redirects
```

But I'd love to do everything within the plugin itself.

Thanks in advance.

**Comment by johngodley** [comment]
You can ignore query parameters. All the details are in the support guide:

https://redirection.me/support/matching-a-url/
