### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by mysuitcasejourneys** [johngodley/redirection#3741]
```
SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list. https://www.mysuitcasejourneys.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2
```

Plugin: 5.3.10 4.2
WordPress: 6.3.2 (single)
PHP: 8.0.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
JavaScript: https://www.mysuitcasejourneys.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.mysuitcasejourneys.com/wp-json/

**Comment by mysuitcasejourneys** [comment]
How do I find out which plugin is causing the issue?

**Comment by johngodley** [comment]
> How do I find out which plugin is causing the issue?

I cannot say which plugin is causing the problem. You will need to figure this out.
