### ISSUE TITLE
Creating new redirection or editing old ones do not reflect until after cache clear

### ISSUE THREAD

**Issue by cristian-dan-f** [johngodley/redirection#3745]
### Summary

I was creating multiple redirections and editing old ones, and after a while I came back to see the list of redirections and for my surprise there where only 10 old redirects. The changes I have made did not apear. I started to think I lost my time configuring and now I have to re-do it. My head hurts...

The problem was solved after clearing WP cache. So the conclusion is:
caching should be disabled on WP admin. Or better said, disable caching of WP-REST data while in WP admin looking at the Redirections.

### Actual Behavior

Redirections list should show updated data always, and not have to worry about clearing cache.

### Steps to reproduce

Create a Redirection.
Refresh browser window.
Newly created Redirection will not be there

OR 

Edit an already existing Redirection.
Refresh browser window.
Recently edited Redirection will show old configuration.

**Comment by johngodley** [comment]
This is not really something that Redirection can control. If you use external plugins that cause caching issues then you will need to be aware of that and clear that cache.

**Comment by cristian-dan-f** [comment]
Yes, thank you for clearing that out. The cache plugin is configured to not cache WP admin, still your plugin was the only one showing this strange behavior. Is a simple line in the Header that instructs all server cache mechanisms that the request should not be cached. You can say is something out of your hands or add that simple line in the Header.
Thank you for your time.
