### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by Developerjoker** [johngodley/redirection#3752]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace') https://lakeshoreguys.com/wp-admin/tools.php?page=redirection.php 614,Uncaught SyntaxError: Unexpected end of input https://lakeshoreguys.com/wp-content/plugins/redirection/redirection.js 2
```

Plugin: 5.3.10 4.2
WordPress: 6.4.1 (single)
PHP: 7.4.33.4
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
JavaScript: https://lakeshoreguys.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://lakeshoreguys.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. Please read the onscreen instructions.
