### ISSUE TITLE
Site went down totally on regex rule

### ISSUE THREAD

**Issue by attila-albert** [johngodley/redirection#3754]
<img width="981" alt="image" src="https://github.com/johngodley/redirection/assets/35459454/3404cd1b-6275-488e-acb5-5b1ad1f6811a">

### Summary

I have added the rule below and the site went totally down. I guess it would be a great idea if the plugin would validate entries before applying them.
^prognostico-de-apostas/([^/]+)/$
/noticias/$1/
301

### Actual Behavior

The plugin should check and validate regex rules before applying them. At the moment it can break the site easily.

### Steps to reproduce

Add this rule:
^prognostico-de-apostas/([^/]+)/$
/noticias/$1/
301

### Environment

Wordpress.

**Comment by johngodley** [comment]
That doesn't break a site. You didn't provide enough detail from the error to see what it actually said, but I do not think a regex can cause an error like that.
