### ISSUE TITLE
Trailing slash in wordpress archive failure

### ISSUE THREAD

**Issue by ghost** [johngodley/redirection#3757]
I'm currently working on a project that requires some redirection, and I've been using your redirection plugin for this. I'm using it to redirect the slug of the wordpress archive slug with a dynamic last part of the slug. 

A link such as:
https://veel-voordeel.nl/product_brands/vanguard/ becomes https://veel-voordeel.nl/merken/vanguard/
However, I've been running into a problem, as the following link:
https://veel-voordeel.nl/product_brands/vanguard does not become https://veel-voordeel.nl/merken/vanguard/

I have the setting "Ignore trailing slashes" turned on, which in the documentation does say should take the link without the trailing slash (at least thats how i read it).

I have added screenshots with the setting on the redirection and the page that breaks.

I'm looking forwards to your response,
Maarten

![Scherm­afbeelding 2023-12-07 om 09 22 03](https://github.com/johngodley/redirection/assets/118976853/be29277a-a16f-48ed-92c0-5b824253081e)
![Scherm­afbeelding 2023-12-07 om 09 25 04](https://github.com/johngodley/redirection/assets/118976853/3b6cfcc4-0a6b-4696-b15d-4dac58e01b29)

**Comment by johngodley** [comment]
The ignore slash option doesn't apply in your regular expression as you are putting the slash directly in the expression. You will need to modify the expression so the slash is optional.

**Comment by ghost** [comment]
This fixed it! Thank you very much.
