### ISSUE TITLE
Can't correct misstyped redirect

### ISSUE THREAD

**Issue by rhinmass** [johngodley/redirection#376]
### Summary

I am trying to redirect http://uubelmont.org/testimonials/ -> http://uubelmont.org/about-us/our-stories/

I had mistyped "our-stories" as "out-stories", and now no matter what I do it continues to redirect to /about-us/out-stories/ which is a 404.

I've cleared the cache, and it hasn't helped. Also tried an incognito browser, as well as a completely different browser. I can't get it to stop redirecting to the typo.

Note "/testimonials" without the trailing slash works fine.

![image](https://user-images.githubusercontent.com/12512051/30251884-bc3b6cd6-9636-11e7-9f9b-ef6bc5c5fa35.png)

### Actual Behavior

I expect http://uubelmont.org/testimonials/ to redirect to http://uubelmont.org/about-us/our-stories

### Steps to reproduce

Create a redirect with a typo.  Notice that it doesn't work.  Go back and fix the typo.  Still redirects to the old place.

### Environment

WordPress 4.8.1 running UUA Congregations theme.
Redirects version 2.7.3

Occurs on all browsers, Chrome, IE, Safari on my phone, so browser version seems to be unimportant.

**Comment by johngodley** [comment]
You must still be using a cached version, or maybe your ISP is caching it:

```
curl -v -I http://uubelmont.org/testimonials/
*   Trying 65.254.227.240...
* TCP_NODELAY set
* Connected to uubelmont.org (65.254.227.240) port 80 (#0)
> HEAD /testimonials/ HTTP/1.1
> Host: uubelmont.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Sun, 10 Sep 2017 19:05:17 GMT
< Content-Type: text/html; charset=iso-8859-1
< Connection: keep-alive
< Server: Apache/2
< X-Powered-By: PHP/5.6.30
< Location: /fcbwp5/wordpress/about-us/our-stories/
< Age: 1
```

**Comment by rhinmass** [comment]
Yes, I agree this must be being cached by my router.  I turned wifi off on my phone so that it had to use 4G and it worked fine.

**Comment by rhinmass** [comment]
I killed my site with too many redirects.  How do you disable all the redirects when you can't get to the dashboard?
