### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by RomanSagan2** [johngodley/redirection#3760]
```
Uncaught ReferenceError: wp is not defined http://apr-wp.local/wp-admin/js/common.min.js?ver=6.3.1 2,Uncaught ReferenceError: wp is not defined http://apr-wp.local/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2,Uncaught TypeError: Cannot read properties of undefined (reading '__') http://apr-wp.local/wp-admin/js/color-picker.min.js?ver=6.3.1 2
```

Plugin: 5.3.10 4.2
WordPress: 6.3.1 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
JavaScript: http://apr-wp.local/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: http://apr-wp.local/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin. Please read the onscreen instructions.
