### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by arhamdeerham** [johngodley/redirection#3763]
Plugin: 5.3.10 4.2
WordPress: 5.7.10 (single)
PHP: 7.3.26
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
JavaScript: https://www.sheinterior.com.sg/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://www.sheinterior.com.sg/wp-json/

**Comment by johngodley** [comment]
As shown on the error screen this is likely caused by another plugin.
