### ISSUE TITLE
Error uploading a CSV of all redirects

### ISSUE THREAD

**Issue by torquereport** [johngodley/redirection#377]
Error uploading a CSV of all redirects

1. Tried creating a CSV with both the source and target urls in the same row, with a comma between it one per each redirect

source, target

This returned a zero uploaded response from the system

2. Tried creating a CSV with source in column A and target in column B

This returned an error

Can you please explain further on how to do this. Somehow I got it to work last week, but now it isn't working.

**Comment by johngodley** [comment]
Can you upload the CSVs you are trying?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
