### ISSUE TITLE
301 Redirect Issue

### ISSUE THREAD

**Issue by MadREP** [johngodley/redirection#3772]
### Summary
We are trying to do a 301 redirect. 

### Actual Behavior

The URL is being overridden.

### Steps to reproduce

Screenshot of steps: 
![image](https://github.com/johngodley/redirection/assets/30052323/0214ee94-92c2-4fc0-94b1-34521e8fbf0c)

### Environment
Chrome, 6.4.2

Screenshot Image: 
![image](https://github.com/johngodley/redirection/assets/30052323/ebbdc565-d89a-411f-ad00-7f28041a6789)

**Comment by johngodley** [comment]
What exactly is the problem you are trying to describe? The URL appears to be redirected as requested.

**Comment by MadREP** [comment]
Hello, thank you for your reply. The URL is not redirecting as expected. The URL <<https://madisonregion.org/elementor-landing-page-37748/>> is supposed to be found via <<madisonregion.org/pathways>> using a 301 redirect but instead loads <<
https://madisonregion.org/pathways-wisconsin-cultivating-the-talent-businesses-need-for-the-future-economy/>>, which is an entirely different page. Hope this helps!

**Comment by johngodley** [comment]
Your screenshot shows that the correct URL is being loaded, and that the redirect is working as expected.

Your target URL is then redirecting elsewhere, as shown in the screenshot. This is outside of Redirection.

**Comment by MadREP** [comment]
Thank you for pointing us in the right direction.
