### ISSUE TITLE
problem with WPML/bilinugal site

### ISSUE THREAD

**Issue by jamieboot1979** [johngodley/redirection#3773]
I am trying to redirect my old bilingual site to a new domain. I use WPML and a different domain for each language (.co.uk for English and .jp for Japanese)- within the same Wordpress installation. Each page has a japanese and English version.

**Example- old site** English- www.cotswoldsadventures.co.uk Japanese- www.cotswoldsadventures.jp
**being redirected to** www.cotswolds-tours.co.uk/www.cotswolds-tours.jp

I setup the 301 redirects for the English pages no problem but had a few issues with the japanese pages, where it is being redirected to the .co.uk version of the page rather than the japanese one I selected. I resolved this by choosing to match by 'URL and language' (.jp) rather than 'URL and server'

The homepage (www.cotswoldsadventures.jp) is still being redirect to the English version (www.cotswolds-tours.co.uk) rather than the japanese one I chose in the plugin (www.cotswolds-tours.jp). You can see it shows correctly in the redirection settings but when you check it it shows the .co.uk version

Can you help?

<img width="1280" alt="Screenshot 2024-01-11 at 15 05 06" src="https://github.com/johngodley/redirection/assets/156337339/c0af802c-3be3-4e1b-af09-67df20a639c9">
<img width="1280" alt="Screenshot 2024-01-11 at 15 21 24" src="https://github.com/johngodley/redirection/assets/156337339/d016b011-474d-4bda-b265-6ff9c848055d">

Using versions browsers, Wordpress 6.42, redirection 5.41

**Comment by johngodley** [comment]
You also emailed this. Please keep support to one place as it creates additional work to triage this across multiple places.
