### ISSUE TITLE
301 redirect not working when deleting a page in Trash

### ISSUE THREAD

**Issue by antwake** [johngodley/redirection#3774]
I deleted a page and got the notification to create a redirect to another page. i entered the target URL but it doesn't work. I went to the Redirections tool page and search for this URL and it wasn't saved

edit a page. click on Move to Trash. see the notification that propose to redirect the deleted page to a new page. enter the new URL. open a browser and type the deleted page's URL

macos sonoma 14.2.1 / safari 17.2.1 / wordpress 6.2.3 / Redirections 5.4.1

**Comment by johngodley** [comment]
There is no notification in Redirection for this.
