### ISSUE TITLE
New redirection with 05 ignores URL and goes to 04 instead

### ISSUE THREAD

**Issue by dandr69** [johngodley/redirection#3775]
I want to count my posts with each redirection so I call them news-001, news-002.
I first noticed at news 002 that it redirects to 001 instead.
I thought is a bug or that I typed somethig wrong.
I changed to news_003 and than forgot about this.
Today it was news-005 and guess what, this also redirects to 004. No idea why and how. But news_005 works properly.

**Comment by johngodley** [comment]
I don't really understand this. Can you give more specific details?

**Comment by dandr69** [comment]
I set up this redirection: /news-01 -> /real-url-01
The next day, i set up; /news-02 -> /real-url-02
Yet when you access 02 it redirects to /real-url-01 instead. 
If I use _ instead of - the redirect works normally.

**Comment by johngodley** [comment]
That doesn't sound like something the plugin is doing. Can you give a real URL to test this with?

**Comment by dandr69** [comment]
https://www.computerblog.ro/stiri-007
I set it up to redirect to https://www.computerblog.ro/stiri/stiri-pe-scurt-15-ianuarie-2024.html
but you can see its redirecting elsewhere. It chooses randomly where it goes. Not the previous. 
https://imgur.com/a/J7BS7Ap

Video:
https://www.youtube.com/watch?v=2YzzYO-rPnU

**Comment by johngodley** [comment]
That URL is redirecting to the target specified, and no where else:

https://redirect.li/http/?url=https%3A%2F%2Fwww.computerblog.ro%2Fstiri-007

Your source does not look like a valid regular expression. It doesn't even seem that it's necessary for it to be a regular expression.

**Comment by dandr69** [comment]
As you can see, the target specified is this https://www.computerblog.ro/stiri/stiri-pe-scurt-15-ianuarie-2024.html
it redirects to an older URL with different words and figures (11 ianuarie instead of 15).  
How come?

**Comment by johngodley** [comment]
> Your source does not look like a valid regular expression. It doesn't even seem that it's necessary for it to be a regular expression.

You should either use a valid regular expression, or not use a regular expression at all. You should also look at any other redirects you have created and see if they are matching.

**Comment by dandr69** [comment]
Please show me a valid regular expression to understand the issue...

**Comment by johngodley** [comment]
Details can be found here:

https://redirection.me/support/redirect-regular-expressions/

I do not think you need a regular expression and it would be better if it wasn't.

**Comment by dandr69** [comment]
The issue is with Facebook and Twitter, that append ?trash_002234 at the end of the url. So if you click on it, it gives a 404 not found. I could fix it with that .* at the end.

**Comment by johngodley** [comment]
>  I could fix it with that .* at the end.

You appended `*.` not `.*`. They are different.

It would be easier to use the 'ignore query parameters' option:

https://redirection.me/support/matching-a-url/

**Comment by dandr69** [comment]
Well, this could  be it. Never had this issue before.
