### ISSUE TITLE
Bulk import with ignore query - passing to destination... and maybe ignore case & slash

### ISSUE THREAD

**Issue by mrwizard64** [johngodley/redirection#3784]
Hey guys, 

Truly, thank you for this plugin.

Wordpress user here.  

I have 650 previously protected pages that were just migrated to a new URLS and new membership software.   I would love to turn off that original buggy membership software and redirect all 650 of the pages to the new location.  

(I have the URLS in a CSV file with the SOURCE in column A and the DESTINATION in column B)

However, I need to make sure that these redirections can't be broken by just adding some kind of query parameter to the end of the URL.  So for example, https://howtofightnow.com/PAGE1 was a protected, paid only page.  If the bulk redirection runs, would https://howtofightnow.com/PAGE1?bypass just bypass my redirection rules if I turn off that original membership plugin?  

Is there any way to import this list while making sure to ignore case, ignore slash, and ignore any query strings that could be added, just to bypass this redirection system?

Thank you for your time and help!!!!

**Comment by johngodley** [comment]
You can set the default options on the options page.
