### ISSUE TITLE
Certain Redirects Not Working

### ISSUE THREAD

**Issue by lspt** [johngodley/redirection#379]
I've been trying to establish 301 redirects from old site pages that are obsolete or deleted. Most of my 301s work fine, but several stubborn ones aren't redirecting, and just keep going to the old link.

Here are two examples:

![unresponsive redirect 1](https://user-images.githubusercontent.com/31854929/30279849-49ca47fc-96dc-11e7-9d26-43f213c37f19.PNG)

![unresponsive redirect 2](https://user-images.githubusercontent.com/31854929/30279861-51d812c6-96dc-11e7-963c-217a9c808143.PNG)

I am a novice when it comes to this stuff, but I have successfully managed a handful of 301s using this plugin, so I can't figure out why these particular pages just go to the original URL. I am trying to cleanup a site I inherited, so I'm planning to eliminate a number of old URLs and redirect to better pages. I appreciate any help you can give with these issues, and advice if I encounter this with other 301 attempts.

WordPress 4.8.1 Toolbox Theme
Redirection 2.7.3
Chrome 61.0.3163.79

**Comment by johngodley** [comment]
Do the original files still exist? If they do then its likely that your server is serving the files up before WordPress gets chance to run. You can fix this by deleting the original files.

**Comment by lspt** [comment]
Deleting those files solved my problem. Thank you so much!
