### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by trrill** [johngodley/redirection#3796]
```
Plugin: 5.4.1 4.2
WordPress: 6.3.2 (multi)
PHP: 8.0.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
JavaScript: https://breakingdefense.sites.breakingmedia.com/wp-content/plugins/redirection/redirection.js?ver=5.4.1-4921947a93e8d2bdecfa002a29093c22
REST API: https://breakingdefense.sites.breakingmedia.com/wp-json/
Query: ?page=redirection.php

Error: Unable to add new redirect (redirect_create_failed)
Raw: {"code":"redirect_create_failed","message":"Unable to add new redirect","data":{"status":400,"error_code":297,"wpdb":"Field 'last_access' doesn't have a default value"}}
```

**Comment by johngodley** [comment]
Is this happening for every redirect? Do you have access to your database? If so could you paste here the `wp_redirection_items` table schema? It looks like somehow it isn't setup correctly.

**Comment by trrill** [comment]
+-------------+----------------------------+------+-----+---------+----------------+
| Field       | Type                       | Null | Key | Default | Extra          |
+-------------+----------------------------+------+-----+---------+----------------+
| id          | int(11) unsigned           | NO   | PRI | NULL    | auto_increment |
| url         | mediumtext                 | NO   | MUL | NULL    |                |
| match_url   | varchar(2000)              | YES  | MUL | NULL    |                |
| match_data  | text                       | YES  |     | NULL    |                |
| regex       | int(11) unsigned           | NO   | MUL | 0       |                |
| position    | int(11) unsigned           | NO   |     | 0       |                |
| last_count  | int(10) unsigned           | NO   |     | 0       |                |
| last_access | datetime                   | NO   |     | NULL    |                |
| group_id    | int(11)                    | NO   | MUL | 0       |                |
| status      | enum('enabled','disabled') | NO   | MUL | enabled |                |
| action_type | varchar(20)                | NO   |     | NULL    |                |
| action_code | int(11) unsigned           | NO   |     | NULL    |                |
| action_data | mediumtext                 | YES  |     | NULL    |                |
| match_type  | varchar(20)                | NO   |     | NULL    |                |
| title       | text                       | YES  |     | NULL    |                |
+-------------+----------------------------+------+-----+---------+----------------+
15 rows in set (0.01 sec)

**Comment by trrill** [comment]
<img width="609" alt="Screenshot 2024-06-15 at 11 00 21 AM" src="https://github.com/johngodley/redirection/assets/1945555/5b729b17-2ac2-462d-b2db-aa45271c434e">

**Comment by johngodley** [comment]
Yes, the `last_access` column should be:

``last_access` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',`

What version of MySQL are you using?

**Comment by trrill** [comment]
Hi, John. 

I'm gonna close this out. Our company has migrated to WP Engine since this incident, and it's no longer an issue.
