### ISSUE TITLE
Google Maps API Key? 

### ISSUE THREAD

**Issue by postapollo** [johngodley/redirection#3797]
### Summary

Found a Google Maps API key in the latest version of the redirection code. 

### Actual Behavior

Security scanning tool found an API key in our repo - this isn't our API key and it's not causing a problem, I'm just raising this in case it needs to be removed - I'm not sure if this is a valid key. 

### Steps to reproduce

Open `redirection/redirection.js` and go to character 560147 **or** search for `AIzaSy`

**Comment by johngodley** [comment]
Yep, it's not used and isn't valid
