### ISSUE TITLE
Monitor Permalink Changes - Redirects for new Permalink

### ISSUE THREAD

**Issue by SimsAdvertising** [johngodley/redirection#3798]
I'm trying to have Redirect monitor for changes to the permalink. We want to update the post permalink from: /%postname%/ to /blog/%postname%/ - but don't want to manually add the redirects for each blog. 

In the past, there used to be a setting for this, but it doesn't look to be an option now:
![Screenshot 2024-02-06 at 1 59 22 PM](https://github.com/johngodley/redirection/assets/79714091/141f2708-c10d-4135-896a-f650935d3796)

I tried enabling it to monitor changes to posts and pages, but when I update the permalink, it doesn't catch the redirects. 
Any help would be greatly appreciated. 

Thanks

**Comment by johngodley** [comment]
There has never been an option to monitor for permalink changes. You can use the permalink migration option from the site page.
