### ISSUE TITLE
WordPress site getting "too many redirects" error

### ISSUE THREAD

**Issue by seesharpgroup** [johngodley/redirection#3799]
### Summary

We have "redirections" plugin installed on all our websites. We have been noticing that some of our website has started getting errors with "too many redirects". As soon as we deactivate the "redirections" plugin, issue resolved.

### Actual Behavior

Website appears to be offlined, with "too many redirects" error
![WhatsApp Image 2024-02-06 at 2 42 30 PM](https://github.com/johngodley/redirection/assets/159206422/46eb530e-2fa9-4810-8aeb-f06306849270)

### Steps to reproduce

Example: https://www.middleboroughdental.com.au, as soon as we activate "redirections" plugin, we will get website offline notification within 60 minutes. We then deactivate the plugin, website back online with no issue again.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Browser:
- Safari 17.2.1 (19617.1.17.11.12)
- Chrome 121.0.6167.139 (Official Build) (arm64)

WordPress Version: 6.4.3

Redirection plugin version: 5.4.2

**Comment by johngodley** [comment]
You will need to fix whatever redirect loop you have created.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
