### ISSUE TITLE
Action "redirect to post/page"

### ISSUE THREAD

**Issue by tamaskan** [johngodley/redirection#38]
1. show the "Add new redirection"-form under the clicked link, not at the bottom of the page and hide the entry when a redirect was created.
2. new redirect-action "redirect to post/page" with a dropdownmenu of available posts/pages
3. option to group 404s

if you need examples: https://wordpress.org/plugins/404-redirected/

**Comment by johngodley** [comment]
I know it's a very long time since this issue was added. The first item has been added to the plugin. The second one is something I don't think is necessary. I'm not sure what you mean about grouping 404s.

I'll close this issue for now
