### ISSUE TITLE
Redirection and SSL

### ISSUE THREAD

**Issue by Gordan10** [johngodley/redirection#380]
Hi John,
I wonder whether you can help with my issue.
I have domain that I just moved to my hosting and previous host has installed SSL certificate on the domain therefore Google displays domain with https at the moment. When customers click on the search results that are https in Google, they get error 404 as domain is currently http. By using your plugin, how can I redirect https results in google to the current http site?
Client does not want SSL certificate on the domain any longer.

**Comment by dovy** [comment]
That's actually impossible to do because the entry point IS the https:// URL.

How about you give them a FREE SSL cert?

* https://letsencrypt.org
*  https://certbot.eff.org/ 

These are your new best friends.

**Comment by johngodley** [comment]
Yeah, echoing dovy you need an SSL certificate for https requests, even if you just want to redirect them - there's no way round this. Let's Encrypt is free and works well.
