### ISSUE TITLE
Redirection is not detecting existing redirect rules

### ISSUE THREAD

**Issue by bigoper** [johngodley/redirection#3802]
### Summary

New and exiting redirect rules are not working

### Actual Behavior

- I've tried browsing a page that does not exist
- That page was recoded in the `404s` tab
- Creating a `redirect` for that `specific 404`
- Browsing that `missing page` one more time > getting `HTTP 404`

### Steps to reproduce

- See above
- The `redirect tester` is showing good results, still the plugin is not working as expected
- Testing using different browser, mobile phones, etc, same results > not working as expected

### Environment
- latest version of WordPress + plugin

**Comment by johngodley** [comment]
Can you give some specific details? You say the redirect tester shows it is working. Why do you say it is not working?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
