### ISSUE TITLE
Redirects Hidden in the Database? 

### ISSUE THREAD

**Issue by tjscott0310** [johngodley/redirection#3808]
I am pretty sure I have redirects in the database that are not showing up in Redirection. SEMrush is reporting redirects that are causing a problem that I don't see. 

About 2013, I had a WordPress.com website. In about 2017, I moved to a full website of my own built on WordPress using the same domain name. That left a lot of broken links per Google Search Console. As they showed up, I created a redirect. 

In 2022, we built a new WordPress site, a new theme, and all. I think those redirects stayed in the database but didn't show up in the Redirection plug-in, base on what I am seeing in SEMrush. 

Is that possible? 

If so, how do I access the redirects that are in the database and get them into the Redirection plug in? 

Thanks,

**Comment by johngodley** [comment]
There are no hidden redirects and the plugin shows everything. What you are probably seeing is redirects being performed by something else.
