### ISSUE TITLE
Redirect from http to https not working

### ISSUE THREAD

**Issue by jillii** [johngodley/redirection#3811]
### Summary

Hi! Our client uses Redirection to force redirect from HTTP to HTTPS (and much more). But, it doesn't seem to be working on one page: quorumfcu.org/learn/. All other pages are behaving as expected.

### Actual Behavior

The user does not get redirected to HTTPS on this page, but they should.

### Steps to reproduce

Type quorumfcu.org/learn/ into your browser's address bar, and hit enter. Then, click on the URL to view the entire string. You should see the page is served over HTTP.

### Environment

Chrome: 121.0.6167.185
WordPress: 6.4.3
Redirection: 5.4.2

**Comment by jillii** [comment]
Sorry, I have an update on my question:

HTTP to HTTPS is actually not working for any page on the site.

**Comment by johngodley** [comment]
It seems to be working now.
