### ISSUE TITLE
screamingfrog shows 308 redirect for a 301 in Redirections

### ISSUE THREAD

**Issue by antwake** [johngodley/redirection#3813]
### Summary

using Redirection, I did a 301 redirect but it shows as a 308 in screaming frog in the URL status code 

### Steps to reproduce

create a redirect (defaults settings). confirm redirection is a 301 in Redirections UI
open screamingfrog and paste redirected URL
see 308 status code instead of 301

same for redirect.li

### Environment

Please list your browser safari, browser version 17.2.1 (19617.1.17.11.12), version of WordPress: 6.4.3 and Redirection plugin Version 5.4.2.

<img width="1237" alt="Screenshot 2024-02-29 at 15 45 25" src="https://github.com/johngodley/redirection/assets/630800/08ae465f-f3e1-4d1c-897d-c6ba73275a3b">
<img width="950" alt="Screenshot 2024-02-29 at 15 45 33" src="https://github.com/johngodley/redirection/assets/630800/e20a30a4-a526-4ee2-86ab-850ff7e7c78b">

**Comment by antwake** [comment]
does this repo still maintain?

**Comment by antwake** [comment]
bump?

**Comment by johngodley** [comment]
I don't know what screamingfrog is. Your screenshots show one URL is being redirected by Redirection and one that isn't. Where is the problem?

**Comment by antwake** [comment]
the problem (if it is one) is that I created a 301 in Redirections and it shows a 308 on redirect.li https://redirect.li/http/?url=https%3A%2F%2Fwww.bettingnews.com%2Fsportsbooks%2Ffanduel%2F
maybe it's not a problem per se :)

**Comment by johngodley** [comment]
But that shows that Redirection isn’t doing the redirect?

**Comment by antwake** [comment]
no the redirect works. just that it's shown as a 308 instead of a 301

**Comment by johngodley** [comment]
Sure, but Redirection isn't performing the redirect. Something else is and you will need to look at whatever is performing it.

**Comment by antwake** [comment]
ok thank you, I'll look it up
