### ISSUE TITLE
Authentication for API

### ISSUE THREAD

**Issue by benatwalkly** [johngodley/redirection#3815]
I am trying to use your API to add new redirects from our proprietary software. But I am not able to get passed the `401 rest_forbidden`response.

I am trying basic authentication protocol

When I call https://walkly.app/wp-json/wp/v2/users it works, but with the same authentication it does not work to call https://walkly.app/wp-json/redirection/v1/redirect

**Comment by johngodley** [comment]
The plugin uses the standard WordPress API. As such the best place to look is https://developer.wordpress.org/rest-api/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
