### ISSUE TITLE
Redirection plugin not masking URL

### ISSUE THREAD

**Issue by jbacall** [johngodley/redirection#3816]
I'm using Chrome,Version 122.0.6261.94, Word press 6.4.3, Redirection 5.4.2, John Godley

I'm following all the instructions for the redirection to hide the destination URL but it's not working.  I've disabled all plugins except that on and I still can't get it to work.  I clear the cache after each attempt

**Comment by johngodley** [comment]
What instructions are you following? Redirection does not do 'masking'. A redirect will always show the destination URL.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
