### ISSUE TITLE
Redirecting all visitors not logged in and excluding wp-admin

### ISSUE THREAD

**Issue by Oclair** [johngodley/redirection#3817]
### Summary

I am trying to redirect all visitors who are not logged in to another domain where the old website has been moved to.  
This enables me to work on the new website on the current url and not need to change the hardcoded url in the database.

The only problem is wp-admin is also included in the rule ^/*  so if the logged in status requires to login again the admins are locked out.

Is there a way to whitelist wp-admin or exclude it from the rules?

Thanks in advance!
Jason

**Comment by johngodley** [comment]
You can create for a 'do nothing' redirect for any URL you don't want to redirect. As long as this has a higher priority (a lower position number) then it will fire first.
