### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by sergiosala** [johngodley/redirection#382]
To help track problems please follow this template. If you can provide screenshots then that will help.

I've been getting error problems that says "Undefined property", from time to time.

### Summary

It just happens sometimes, when I go to my homepage (and I'm logged in). Not sure how, but I can send you a screenshot here:

https://cl.ly/mRwR

and it says:

Notice: Undefined property: Agent_Match::$agent in /www/wp-content/plugins/redirection/matches/user-agent.php on line 28 Notice: Undefined property: Agent_Match::$regex in /www/wp-content/plugins/redirection/matches/user-agent.php on line 29

### Environment

Safari, latest WP 4.8.1 and Redirection version 2.7.3.

**Comment by johngodley** [comment]
I've put a check in for this. I would advise you disable the output of errors on your production site as you are exposing sensitive information.
