### ISSUE TITLE
problem with regex

### ISSUE THREAD

**Issue by antwake** [johngodley/redirection#3820]
trying to redirect all URL under a subfolder to the subfolder main page
original URL: https://onlinecasinogames.com/casinos/lupin-casino
redirected URL: https://onlinecasinogames.com/casinos/n-casino-welcome-bonus-quick-payments/
see screenshot
<img width="544" alt="Screenshot 2024-03-07 at 19 26 49" src="https://github.com/johngodley/redirection/assets/630800/06619a1e-2ee7-407b-8c7a-700fe24944a4">

this URL pattern matches my URL on regex tools

**Comment by johngodley** [comment]
Do you have the regex setting enabled? I can't provide support for specific expressions, and the plugin uses PHP to perform the expression. If it is valid as per what is supported by PHP then it will work, otherwise you will need to modify it.

**Comment by antwake** [comment]
thank you John, as you mentioned I didn't enable regex 🙄. Sorry!
