### ISSUE TITLE
Stuck in Loop: "Redirection database needs upgrading"

### ISSUE THREAD

**Issue by DougJoseph** [johngodley/redirection#3822]
### Summary
Stuck in Loop: "Redirection database needs upgrading" — database table was already updated, and manually checked. The ding dong alert that "Redirection database needs upgrading" won't go away. Clicking manual and then clicking to finish, does nothing.  

### Environment

Chrome — Version 122.0.6261.94 (Official Build) (arm64)
WordPress — Version: 6.4.3
Redirection plugin — Version 5.4.2
"Database version" — 4.1

**Comment by johngodley** [comment]
Is your site cached in anyway? Typically this is caused by excessive caching.

**Comment by DougJoseph** [comment]
Thanks for answering. It's been a while since the report, and at this time I don't remember which of many domains was the source of this report.
