### ISSUE TITLE
Redirect logging throws exception - unknown column request_method

### ISSUE THREAD

**Issue by backcode-dev** [johngodley/redirection#3826]
*Logging for redirects throws an exception*

### Summary

I enabled redirection logs for my site. Logs were always blank so I checked the php errors. In the debug php logs, I see many exceptions for an unknown column "request_method".  I'm running 5.4.2 . M

### Actual Behavior

This exception is thrown on every redirect:

`[13-Mar-2024 04:15:39 UTC] WordPress database error Unknown column 'request_method' in 'field list' for query INSERT INTO `wp_redirection_logs` (`url`, `domain`, `ip`, `created`, `agent`, `request_method`, `http_code`, `redirection_id`, `sent_to`, `redirect_by`) VALUES ('/go/my-old-page', 'https://mysiteurl.com', 'ffff:ffff:ffff:9518:d046:ffff:497:d54a', '2024-03-12 23:15:39', 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Mobile/15E148 Safari/604.1', 'GET', '301', '232', 'http://www.theredirect.com/page.aspx', 'redirection') made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->init, Red_Item->get_match, do_action('redirection_visit'), WP_Hook->do_action, WP_Hook->apply_filters, WordPress_Module->redirection_visit, Red_Item->visit, Red_Redirect_Log::create`

### Steps to reproduce

For me, just have the plugin on. There are no "steps". It's constant.

### Environment

Server side error - browser is not relevant.  Version of WordPress is 6.4.3 and Redirection plugin is 5.4.2
Support tab on the plugin reports database version 4.2

**Comment by johngodley** [comment]
Somehow an upgrade has failed. You will need to change the database version back to a previous one, maybe 2.4, and then proceed through the upgrade again.
