### ISSUE TITLE
Problem starting Redirection 5.3.10

### ISSUE THREAD

**Issue by Tbs-Rachit** [johngodley/redirection#3827]
```
Uncaught ReferenceError: wp is not defined https://mindtechconsultancy.com/wp-admin/tools.php?page=redirection.php 815,Uncaught ReferenceError: wp is not defined https://mindtechconsultancy.com/wp-admin/js/common.min.js?ver=6.4.3 2,Uncaught ReferenceError: wp is not defined https://mindtechconsultancy.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49 2,Uncaught TypeError: jQuery(...).live is not a function https://mindtechconsultancy.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1 2
```

Plugin: 5.3.10 4.2
WordPress: 6.4.3 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
JavaScript: https://mindtechconsultancy.com/wp-content/plugins/redirection/redirection.js?ver=5.3.10-948a20e46d8617ec7b6cf37114495e49
REST API: https://mindtechconsultancy.com/wp-json/

**Comment by johngodley** [comment]
This is caused by another plugin. Also, you should use the latest version of the plugin
