### ISSUE TITLE
Problem starting Redirection 5.4.2

### ISSUE THREAD

**Issue by stmertes** [johngodley/redirection#3828]
Plugin: 5.4.2 4.2
WordPress: 6.4.3 (multi)
PHP: 8.1.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
JavaScript: https://www.screenprintingnow.com/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://www.screenprintingnow.com/wp-json/

**Comment by johngodley** [comment]
Do you have any details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
