### ISSUE TITLE
Bulk redirects with Ignore & Pass Parameters to the target

### ISSUE THREAD

**Issue by elisamz** [johngodley/redirection#3833]
Hello, 

I need help to upload 301s with the option "Ignore & Pass Parameters to the target"
but I can't find how to do it. 
![image](https://github.com/johngodley/redirection/assets/164343789/5fb2ae2b-3027-42aa-8849-851b190e137e)

Also, is it possible to edit in bulk and change this in bulk to every of my 301s? 
![image](https://github.com/johngodley/redirection/assets/164343789/d345dd72-5100-445e-b652-e7d9fbfc47d5)

I need a solution to work with a lot of redirects. 

Thanks in advance!

**Comment by wojsmol** [comment]
Hi
I have this issue to, AFAIK for now the only option is to use [JSON import](https://redirection.me/developer/json-export/) but it will be nice to add support for additional column in csv import.

**Comment by travismathews** [comment]
JSON Import is probably the best bet but my lazy work around was to enable it as the default in the settings and then import my redirects again.

**Comment by johngodley** [comment]
Yes, you can enable it as a default option. There is no plan to add additional columns to the CSV file, and JSON should be used if it needs to be done on an individual redirect basis.
