### ISSUE TITLE
Emoji in string

### ISSUE THREAD

**Issue by helemerada** [johngodley/redirection#3838]
### Summary

WPML throws an error and it’s caused by an emoji in a Redirection text’s string

![redirection_string_emoji](https://github.com/johngodley/redirection/assets/142982486/dd2770b3-41f7-45e0-b214-5daa23016cfc)

Is it possible to fix this emoji issue on a future update of Redirection?

### Steps to reproduce

Go to **WPML** -> Theme and plugins localization -> Scan Redirection plugin for strings 

Result after scanning
![Screenshot 2024-03-28 105918](https://github.com/johngodley/redirection/assets/142982486/5f76ddc2-0640-4da4-aa9c-94fd6a3830db)

Now go to WPML String Translation -> Choose domain **redirection**

![image](https://github.com/johngodley/redirection/assets/142982486/62130901-f854-439b-ab9b-c446ffafe277)

### Environment

WordPress 6.4.3
Redirection vs 5.4.2
WPML String Translation vs 3.2.9

**Comment by johngodley** [comment]
Fix it how? The strings work fine in WordPress and have done so for many years. The problem seems to be with WPML?

**Comment by helemerada** [comment]
Remove emoji

**Comment by johngodley** [comment]
Ok, well, it seems like the problem is with WPML. I see no reason to remove the emoji from Redirection.
