### ISSUE TITLE
404 page wordpress page type multiple redirects

### ISSUE THREAD

**Issue by maxmullerman** [johngodley/redirection#3841]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

It does not seem possible to create more than 1 redirect that uses the function:

- "URL and WordPress page type: Only the 404 page type is currently supported. Please do not try and redirect all your 404s - this is not a good thing to do."

We have set up multiple redirects that want to use this option but only the lowest position is active. 

Would it be possible to make a change in the code so that multiple redirections can use this feature? 

- Please list your browser, browser version, version of WordPress and Redirection plugin.

<img width="943" alt="Scherm­afbeelding 2024-04-05 om 14 31 49" src="https://github.com/johngodley/redirection/assets/34793749/be0a45e9-9c2a-4599-a3e1-16cc0de363ce">

-Version 5.4.1 of plugin

**Comment by maxmullerman** [comment]
This works:<img width="992" alt="Scherm­afbeelding 2024-04-05 om 14 33 23" 
src="https://github.com/johngodley/redirection/assets/34793749/4c6692d0-c143-49e7-88d9-565fcbb0b4ff">
This doesnt:
<img width="987" alt="Scherm­afbeelding 2024-04-05 om 14 34 00" src="https://github.com/johngodley/redirection/assets/34793749/7ed809bd-83be-46a4-ad23-70d3e75aa41a">

Test with:
https://www.willemsen.nl/bedrijven/object/testadress/
https://www.willemsen.nl/wonen/object/testadress/

**Comment by johngodley** [comment]
Yep. I'm not sure why that is the case but it will be fixed in the next version.
