### ISSUE TITLE
Redirect isn't recognized from Facebook

### ISSUE THREAD

**Issue by VVopni** [johngodley/redirection#3846]
### Summary

Redirect my wordpress site to my linktree url. It doesn't work from Facebook or Messenger.

### Actual Behavior

It works if you use Chrome.
If you click http://www.violetvopni.com from Facebook or Messenger however, it takes me to a sample website.

### Steps to reproduce

From wordpress admin, if I click "visit site" I get taken to my linktree.
In Facebook messenger, I typed in www.violetvopni.com and it shows the linktree in the preview, but when I click on it, I get taken to a sample wordpress site, NOT linktree.
I go to my facebook profile, click on the violetvopni.com link, it ALSO goes to the sample site, NOT the linktree.

Here's where it gets weird, my boyfriend tried it, HE gets taken to the sample site, NOT to linktree, both from my FB profile AND from the messenger convo.

He tries it by typing it directly into Chrome, it works. 

### Environment

Chrome, 124.0.6367.29, wordpress 6.5.2, redirection version 5.4.2
Plugins are all shut off . . . 

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
You need to use 'ignore query parameters'
