### ISSUE TITLE
File created/modified outside of plugins folder: expected behavior?

### ISSUE THREAD

**Issue by ashgoodman** [johngodley/redirection#3847]
### Summary

The security plugin I use (Sheild) indicates your plugin created or modified a file outside of the plugin's folder. Just want to be sure this is the expected behavior and I can tell the security plugin to ignore the change

The file name: redirection-en_GB.l10n.php

File path: wp-content/languages/plugins/redirection-en_GB.l10n.php

Latest version of WP, Redirection plugin

**Comment by johngodley** [comment]
The plugin is not doing this. WordPress may do this as part of it's locale support.
