### ISSUE TITLE
Question - Setup redirect based on Environment

### ISSUE THREAD

**Issue by abiseks** [johngodley/redirection#3848]
### Summary

I am trying to figure out if we can redirect to different URLs based on environment.
For Example: I would like to set a different target URL for Dev/QA and Prod. Could you please let me know if this is possible from within the Redirection plugin. The other option that I have is to do this using "Better Search and replace Plugin" but I am trying to find if it can be achieved from within "Redirection" Plugin.

**Comment by johngodley** [comment]
I don't know what you are trying to do. How would this work?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
