### ISSUE TITLE
Redirection  5.4.2 cuts destination URLS creating 404 errors

### ISSUE THREAD

**Issue by WEBCREATIVI** [johngodley/redirection#3849]
we have redirected 
https://www.sforza.tech/categoria-prodotto/ferrari-portofino/
to
https://www.sforza.tech/categoria-prodotto/componenti-carbonio-ferrari/ferrari-portofino/

the destination URLS seems to be authomatically rewritten to
https://www.sforza.tech/categoria-prodotto/componenti-fibra-carbonio-ferrari/-portofino/  (lacking the second ferrari tem occurrence in the last part pf the permalink) 

this happens with many internal links

I attach the screenshot of the URL in Redirection backend and what comes out when we test the redirection

<img width="810" alt="Screenshot 2024-04-22 at 16 33 34" src="https://github.com/johngodley/redirection/assets/167816655/fdbb0ce0-7c9b-4144-8f54-208afe875ce6">
<img width="486" alt="Screenshot 2024-04-22 at 16 33 23" src="https://github.com/johngodley/redirection/assets/167816655/30bf42ed-158e-4ced-8ade-4af49656e29e">

**Comment by johngodley** [comment]
This does not seem to be a problem anymore
