### ISSUE TITLE
Problem starting Redirection 5.4.2

### ISSUE THREAD

**Issue by yourkalon000** [johngodley/redirection#3852]
Plugin: 5.4.2 4.2
WordPress: 6.5.2 (single)
PHP: 8.1.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
JavaScript: https://wordpress-1255634-4508375.cloudwaysapps.com/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://wordpress-1255634-4508375.cloudwaysapps.com/wp-json/

**Comment by johngodley** [comment]
Please provide some more details

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
