### ISSUE TITLE
Unable to create redirect to a wordpress url 

### ISSUE THREAD

**Issue by Be-DoWn** [johngodley/redirection#3853]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

creating a redirect to a url - 

current url - https://www.butterflyfields.com/wp-content/uploads/2020/09/MagneticShapes-Puzzles-ButterflyFields.pdf

needs to redirect - https://butterflyfields.com/wp-content/uploads/2023/08/MagneticShapes-Puzzles-ButterflyFields.pdf

but its showing 404.

### Environment

Chrome - Version 124.0.6367.119
version of WordPress - 6.5.2
Redirection plugin Version 5.4.2

**Comment by johngodley** [comment]
Please see the support guide: https://redirection.me/support/problems/url-not-redirecting/
