### ISSUE TITLE
Problem starting Redirection 5.4.2

### ISSUE THREAD

**Issue by renataiglesias** [johngodley/redirection#3856]
Plugin: 5.4.2 4.2
WordPress: 6.5.3 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
JavaScript: https://renataiglesias.com.br/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://renataiglesias.com.br/wp-json/

**Comment by johngodley** [comment]
Do you have any other details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
