### ISSUE TITLE
Problem starting Redirection 5.4.2

### ISSUE THREAD

**Issue by Sebultura2** [johngodley/redirection#3864]
Plugin: 5.4.2 4.2
WordPress: 6.5.3 (single)
PHP: 7.3.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
JavaScript: https://guncelbilgihavuzu.com/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://guncelbilgihavuzu.com/wp-json/

**Comment by johngodley** [comment]
Do you have any more details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
