### ISSUE TITLE
Domain being added before the url to redirect to

### ISSUE THREAD

**Issue by nickmercer92** [johngodley/redirection#3865]
see screenshots.

this works on another one of my sites but not this one for some reason.

![Screenshot 2024-06-02 154318](https://github.com/johngodley/redirection/assets/171513281/9c704fed-bdf4-4535-abc5-c47334170200)
![Screenshot 2024-06-02 154331](https://github.com/johngodley/redirection/assets/171513281/bbee06f3-5d5b-488f-b928-86d243daf47c)

**Comment by johngodley** [comment]
The domain will not be added and it is likely you have another redirect that is incorrectly configured.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
