### ISSUE TITLE
wordpress plug in stopped redirecting and now I only get 404s.

### ISSUE THREAD

**Issue by lzuckerm** [johngodley/redirection#3866]
*Please replace this template with your own details!*

### Summary

The Wordpress plug previously worked for me, and I just discovered that it likely hasn't been working for some time. When I check the redirects, they're all 404s. 
### Actual Behavior

The redirects stopped working and are now giving me 404s.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

WordPress 6.5.3, Redirection Version 5.4.2

**Comment by johngodley** [comment]
Can you provide more details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
