### ISSUE TITLE
WP CLI docs unclear for updating settings

### ISSUE THREAD

**Issue by dalepgrant** [johngodley/redirection#3867]
https://redirection.me/developer/wp-cli/#settings

As it stands the docs on using WP CLI to set settings are unclear or incorrect. It's not obvious for example you have to use the `--set` flag to pass the value.

## Original
>You can get or set Redirection options using WP CLI. The format is:
>
>`wp redirection setting <name> [value]`
>
>Where `<name>` is the [setting name](https://redirection.me/developer/rest-api/#api-Settings-GetSettings). If you pass a `[value]` the it will set the value, otherwise it will get the value. The value should be in JSON format if it is anything other than a string or number.
>
>Note that the value will be validated according to the setting.

## Suggested
You can get or set Redirection options using WP CLI. The format is:

`wp redirection setting <name> [--set=<value>]`

Where `<name>` is the [setting name](https://redirection.me/developer/rest-api/#api-Settings-GetSettings). Passing a `<value>` using the `--set` flag will set the value, otherwise it will get the value. The value should be in `string[]` format if it is anything other than a string or number.

Note that the value will be validated according to the setting.

Examples:

Set 'Redirect Logs' to 2 months
`wp redirection setting expire_redirect --set="60"`

Set Post types to monitor.
`wp redirection setting monitor_types --set='["page","post"]'`

<details open>
  <summary>Change comparison</summary>

```diff
You can get or set Redirection options using WP CLI. The format is:

- `wp redirection setting <name> [value]`
+ `wp redirection setting <name> [--set=<value>]`

Where `<name>` is the [setting name](https://redirection.me/developer/rest-api/#api-Settings-GetSettings). 
- If you pass a `[value]` the it will set the value, otherwise it will get the value.
+ Passing a `<value>` using the `--set` flag will set the value, otherwise it will get the value. 
- The value should be in JSON format if it is anything other than a string or number.
+ The value should be in `string[]` format if it is anything other than a string or number.

Note that the value will be validated according to the setting.
```
</details>

**Comment by johngodley** [comment]
Updated. Thanks.

**Comment by dalepgrant** [comment]
Thanks to you for this plugin! Happy I can help in some small way.
