### ISSUE TITLE
User agent dropdown list

### ISSUE THREAD

**Issue by ymao14** [johngodley/redirection#387]
Hi!

I am wondering what happened to the user agent dropdown menu? My redirects are for specific platforms, and I'm not a developer nor do I know anything about code, so if someone could tell me what I could put in for "user agent" now that we can only type in it, that's be really appreciated. 

Thanks!

**Comment by johngodley** [comment]
The dropdown was added in 015a269d0a2e2534bc3b8f76fdde6d4253cdf1b5, which will make it into the next version of the plugin
