### ISSUE TITLE
Feature Request: add warning if the source URL is not part of this WP

### ISSUE THREAD

**Issue by jhard** [johngodley/redirection#3870]
Redirection should warn the user if they add a redirect that will not function because the URL is not within the scope of the installation.

Right now, I can have a WP at https://example.com/blog/ and set up a redirect from `/something/` to `/blog/something/`. This redirect will not work unless the server is configured in a strange way, and a warning should be issued.

The same problem exists in multi-site installations. If I have a setup with `https://example.org/` being blog_id = 1, and `https://example.org/fr/` being blog_id = 2, I can set up a redirect on / (blog_id 1) that targets `/fr/something/`, but WP will run this request in the context of `https://example.org/fr/` and Redirection will not be able to see that redirect.

I believe that the warning should be displayed immediately during creation of redirects (much like the reminder to set the regex option if the source URL looks like a regex), but should also have a dedicated place to be seen since a user might naively ignore the initial warning, or the source URL might only become invalid after the home url has been changed.

In the interest of not making people mad that do have strange server configurations, it will probably need to be optional. However, I do think it should be opt-out, because most setups will not be that strange, and most warnings will not be false positives.

**Comment by johngodley** [comment]
The plugin warns you about many things, but some things are difficult to detect and people have different setups. I think this kind of warning would cause more problems than it solves. Based on the feedback I get it doesn't seem to be a common problem.

**Comment by jhard** [comment]
Understandable, and I agree that not everything needs to be a built-in feature.

Is there a good place I could hook into and throw warnings and rejections to get that kind of thing going?
Ideally it would be client-side of course, but that's often harder since there aren't really nice APIs defined by WP core for interaction there.
