### ISSUE TITLE
Problem starting Redirection 5.4.2

### ISSUE THREAD

**Issue by omarnavico** [johngodley/redirection#3874]
```
Uncaught SyntaxError: Unexpected token ';' https://cosmeticoplasty.com/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd 2
```

Plugin: 5.4.2 4.2
WordPress: 6.5.5 (single)
PHP: 7.4.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
JavaScript: https://cosmeticoplasty.com/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://cosmeticoplasty.com/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This is probably caused by another plugin.
