### ISSUE TITLE
SEO warning

### ISSUE THREAD

**Issue by Jim-Sharp** [johngodley/redirection#3876]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### I get the following warning on my WP Plugins page when Redirection plugin is active.
"Please keep only one SEO plugin active, otherwise, you might lose your rankings and traffic."
I also run Rank Math, so I'm sure that's where this warning is coming from.

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment
CPanel running Wordpress

Please list your browser, browser version, version of WordPress and Redirection plugin.
Chrome browser, auto-updates
Wordpress 6.5.5
Redirection 5.4.2

**Comment by johngodley** [comment]
Please contact Rank math about this warning. They are trying to scare you into thinking that it is a problem. It is up to you to decide whether this is good behaviour for a plugin.
