### ISSUE TITLE
Log / 404 lifetime

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#3877]
### Logs are not being deleted

In the settings it has that redirect logs will be kept for a week and 404 logs a day.

### Actual Behavior

I just checked the 404 log and it goes back to 06/01/2024. The redirect log seems ok with the oldest date being  25/06/2024.

Now the 404 log goes back to 05/03/2024. Why is it not 01/07/2024?

### Steps to reproduce

In Options set the retention to 1 day for 404 log.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Using latest of all. Do you have a shortcut to provide this info?

**Comment by johngodley** [comment]
Logs are deleted gradually according to the setting, and require WP cron to work.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
