### ISSUE TITLE
Regex example

### ISSUE THREAD

**Issue by ylluminate** [johngodley/redirection#388]
So I just got done importing a boatload of redirects for a user and then suddenly found out that they've got a whole bunch more.  Turns out that a regex will be much easier in this particular situation.  I have the following original pattern:
`https://www.domain.tld/news/2017/01/13/some-crazy-names-here/`

The new pattern:
`https://www.domain.tld/blog/news/some-crazy-names-here/`

A simple regex should do the trick:
`(\/news\/\d{4}\/\d{2}\/\d{2}\/)(*)` -> `/blog/news/$2/`

![image](https://cl.ly/0A3r0q3F1G0z/Image%202017-09-14%20at%207.21.53%20PM.png)

But it's not working and there doesn't really appear to be any log that I can watch to see what this plugin is actually doing or if it's hitting a problem with the regex...

Could you throw an example my way here of what should actually work in this use case as I have to think I'm probably just missing a minor technicality that this plugin's regex library needs.

**Comment by johngodley** [comment]
The plugin uses PHP's regular expressions, which are pretty standard. Your above expression is incorrect for your source URL. You can test regular expressions using something like https://regexr.com/

If you change the `(*)` to `(.*)` then it does match.

**Comment by ylluminate** [comment]
Hah, I had that at one point and it didn't work. I'll have to go back as it's possible that through so many iterations I may have slipped up at some point... Now the client is dealing with other items and has me in a holding pattern on this issue so I'll let you know when I can verify this works. :)
