### ISSUE TITLE
Redirection?

### ISSUE THREAD

**Issue by usasca** [johngodley/redirection#3881]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I am trying to redirect a site to another website under a different domain. I entered the source URL and the target URL into the fields and didn't change any of the settings. Is this a viable method of redirection?
### Actual Behavior

Still waiting if it's going to reflect.

### Steps to reproduce

Entered "https://courses.bethnydick.com/the-fame-formula" into the source URL and "https://bethnydick.myflodesk.com/10kinterview" into the target.

### Environment

Google Chrome latest version; Plugin latest version as of July 8.

**Comment by johngodley** [comment]
I'm not really sure of the question. If you put a source URL and a target URL then it will redirect from that source to that target.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
