### ISSUE TITLE
404 error on sitemap url

### ISSUE THREAD

**Issue by dalton1958** [johngodley/redirection#3882]
### Summary

For some reason, when redirection is activated any attempted access to the sitemap url is redirected to a 404 error, the page exists and can be accessed if redirection plugin is deactivated.

I have reviewed the settings and redirections that are in place and cannot see any element that would cause this, yet deactivated and the issue is resolved.

I have attached the exported json file in case anyone with more experience than myself can see an obvious issue that would casue the problem.

Any help in resolving the issue would be greatly appreciated as having just done a site rewrite we need the site to be indexable and we also need redirections to be in place so are somewhat stuck between the devil and the deep blue sea in respect of whether or not to deactivate the plugin to allow access to the sitemap.

[redirection-bridlington-net-9-july-2024.json](https://github.com/user-attachments/files/16145553/redirection-bridlington-net-9-july-2024.json)

### Environment

Wordpress version 6.5.5 
redirection version 5.4.2

**Comment by johngodley** [comment]
The plugin only does what you instruct it to do. If a URL is redirecting somewhere else then it is because that redirect exists in your list, or something else is doing it.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
