### ISSUE TITLE
Problem starting Redirection 5.4.2

### ISSUE THREAD

**Issue by mm-ft** [johngodley/redirection#3885]
Plugin: 5.4.2 4.2
WordPress: 6.5.5 (single)
PHP: 7.4.14
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
JavaScript: https://www.finanztrends.de/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://www.finanztrends.de/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This is probably caused by another plugin.
