### ISSUE TITLE
Problem starting Redirection 5.4.2

### ISSUE THREAD

**Issue by wiraadhitama** [johngodley/redirection#3886]
Plugin: 5.4.2 4.2
WordPress: 6.5.5 (multi)
PHP: 8.1.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
JavaScript: https://wiraelectrical.com/id/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://wiraelectrical.com/id/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This is probably caused by another plugin.
