### ISSUE TITLE
Incorrect alert when regex is selected

### ISSUE THREAD

**Issue by hivehousedigital** [johngodley/redirection#3888]
### Summary

I use the regex option and ignore case for my redirects.
The format I use for the expression is:
^/pagename/?$

I want to ignore any variations that might precede pagename (www or non-www as an example).
I want to ignore the trailing slash but also stop the match after pagname so that the match isn't greedy.

### Actual Behavior

When I have regex selected, I still get an alert about escaping out the ? character, which if I do, makes the regex not work.

### Steps to reproduce

Using a pagename called corporate

1. add new
2. choose ignore case and Regex
3. source URL ^/corporate/?$
4. target URL /industries/corporate/
5. add redirect
6. test redirect

When I tried a different various of this:

1. add new
2. choose ignore case, ignore slash, and Regex
3. source URL ^/corporate/$
4. target URL /industries/corporate/
5. add redirect
6. test redirect

I noticed that it would redirect for /corporate/
but
it would not redirect for /corporate (missing the trailing slash)

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Brave
Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (arm64)

WordPress v 6.5.5

Redirection v 5.4.2

![Screenshot 2024-07-25 at 9 33 32 AM](https://github.com/user-attachments/assets/8bc77ef1-a0d3-4640-a68f-0872c1d7f4f7)

**Comment by johngodley** [comment]
It is a warning, not an alert. If it doesnt apply then you can ignore it.
