### ISSUE TITLE
Encountering a database problem while setting up the Redirection plugin

### ISSUE THREAD

**Issue by wikiwyrhead** [johngodley/redirection#3889]
**Summary**
Encountering a database problem while setting up the Redirection plugin. The setup progress is stuck at 50%, and there is a message indicating that the database does not need updating to version 4.2, though the installation shows version 4.2.

**Actual Behavior**
During the setup of the Redirection plugin, the progress bar reaches 50% and displays a database problem message. The system states that the database does not require an update to version 4.2. The following SQL queries are provided for table creation:

wp_redirection_items
wp_redirection_groups
wp_redirection_logs
wp_redirection_404
The setup process appears to be halted at the "create_groups" stage.

**Steps to Reproduce**

- Initiate the setup process for the Redirection plugin.
- Proceed through the setup steps until the progress reaches 50% then it stop with the database error.
- Observe the database problem message and the progress halt at the "create_groups" stage.

**Environment**
Browser: [Chrome]
Browser Version: [Version 127.0.6533.72 (Official Build) (64-bit)]
WordPress Version: [6.6.1]
Redirection Plugin Version: [5.4.2]

![Screenshot 2024-07-26 183849](https://github.com/user-attachments/assets/4f5c4f6a-c058-48c4-a979-da286143b859)

**Comment by johngodley** [comment]
Have you pressed the skip button?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
