### ISSUE TITLE
Staging Site Question

### ISSUE THREAD

**Issue by benchrevival** [johngodley/redirection#3890]
Apologies if this is not allowed. This is not an issue, but a quick question about setting up redirections on a staging site. 

I have imported the CSV of redirections from my live site. They get imported with the "staging" prefix. 

For anyone with experience doing this, when you push to your live site, are the "staging" prefixes automatically removed again?

**Comment by johngodley** [comment]
The plugin does not modify your redirects and has no concept of a staging site.
