### ISSUE TITLE
Problem starting Redirection 5.4.2

### ISSUE THREAD

**Issue by ntcuongth** [johngodley/redirection#3893]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'setLocaleData') https://daily98news.com/wp-admin/tools.php?page=redirection.php&sub=options 295,Uncaught TypeError: Cannot read properties of undefined (reading '__') https://daily98news.com/wp-admin/js/common.min.js?ver=6.6.1 2,Uncaught TypeError: Cannot read properties of undefined (reading '__') https://daily98news.com/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd 2
```

Plugin: 5.4.2 4.2
WordPress: 6.6.1 (single)
PHP: 8.1.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
JavaScript: https://daily98news.com/wp-content/plugins/redirection/redirection.js?ver=5.4.2-2dfac6cbb88915145528d6945ba453dd
REST API: https://daily98news.com/wp-json/

**Comment by johngodley** [comment]
This is caused by something else, maybe another plugin.
