### ISSUE TITLE
Use regex capture in target URL

### ISSUE THREAD

**Issue by ocgltd** [johngodley/redirection#3896]
This is a support question - maybe becoming a feature request.  But I can't figure this out.

I want to match the regex "/en/(.*)" and redirect to "/\1".  I can't figure the syntax (if this plugin even supports using the capture group).

Is there an example available that shows this?  Is use of capture groups supported?

**Comment by johngodley** [comment]
The plugin uses standard PHP regular expressions and does not implement it's own expression support.

Support can be found here: https://redirection.me/support/redirect-regular-expressions/
