### ISSUE TITLE
404 export only exports the amount of how many redirection log rows there are

### ISSUE THREAD

**Issue by synchronos-t** [johngodley/redirection#39]
Currently the 404 export counts the number of 404 reports incorrectly, taking the count from the redirection log table and not from the 404 table. This means the export stops e.g. after first 300 404s, if there are 201 to 300 redirection log items. This is just a typo on the file **models/log.php**, on the line 244:

```
$sql = "SELECT COUNT(*) FROM {$wpdb->prefix}redirection_logs";
```

This should of course be:

```
$sql = "SELECT COUNT(*) FROM {$wpdb->prefix}redirection_404";
```

**Comment by johngodley** [comment]
This was fixed
