### ISSUE TITLE
Case-sensitive URL

### ISSUE THREAD

**Issue by hecsan** [johngodley/redirection#390]
Hi.  I'm not sure if it's been like this or something has changed.  I just noticed that to be able for the Redirections to work, the user needs to type the old URL the same way as it was typed on the Redirections table.  In other words, it is case-sensitive.  This address, https://fa.ucf.edu/merchant/publications/publications.cfm will not redirect but this one will, https://fa.ucf.edu/Merchant/Publications/Publications.cfm

Is it possible to remove case-sensitive or I will have to type all possible URLs to redirect to one particular page?  Thanks in advance.

**Comment by johngodley** [comment]
Merging with #166
