### ISSUE TITLE
The 404 redirection doesn't work properly

### ISSUE THREAD

**Issue by educanin** [johngodley/redirection#3900]
Yesterday I had 22 pages of errors on "404". I corrected 4 pages and, this morning it was back to 22 pages of errors.

**Comment by johngodley** [comment]
As the name implies, the 404 is a log. It just shows things that have happened. How did you 'correct' things?

**Comment by educanin** [comment]
I tried to delete a 301 redirection by clicking on delete under de redirection. But just after I checked with the redirected URL and it was still redirected to the same URL.

 

I have to delete a lot of redirections because over 10% of them go to the same URL ☹

 

Do you have any video link or reading to help me understanding all the redirections and how to do it? Because I got over 250 404 or 301  redirections and I don’t understand why there are so many ☹

 

AND… what happens to an URL when the redirection is deleted? Does it comme back to 404 or what ?

**Comment by johngodley** [comment]
> after I checked with the redirected URL and it was still redirected to the same URL.

Clear your browser cache.

> Because I got over 250 404 or 301  redirections and I don’t understand why there are so many 

These are different things. A redirect is something you create. A 404 is something that happens on your site.

> what happens to an URL when the redirection is deleted? Does it comme back to 404 or what

The redirect is deleted. What happens to the URL is up to your site.

**Comment by educanin** [comment]
So,

 

What is the proper procedure to delete a redirection made with 301. So the redirection doesn’t exist any more?

**Comment by johngodley** [comment]
> What is the proper procedure to delete a redirection made with 301. So the redirection doesn’t exist any more?

There is no procedure. You select the redirect and delete it - that's it.

**Comment by johngodley** [comment]
Closing for now.
