### ISSUE TITLE
Typing redirect as root slash redirect causes unexpected behavior

### ISSUE THREAD

**Issue by chellerobinson** [johngodley/redirection#3902]
### Summary

A redirect that has been created resolves to the homepage instead of the proper URL when typed out using "domain" dot com slash redirect. Typing www.domain.com/redirect resolves as expected.

### Actual Behavior

Type opisnet.com/global-lpg-outlook in the web browser and it resolves to the homepage. Clicking the redirect, or typing www.opisnet.com/global-lpg-outlook functions as expected.

### Steps to reproduce

This video shows the steps to reproduce: https://www.awesomescreenshot.com/video/30516945?key=5196bd8bb925a97c642c1a4626adb31e

### Environment

Google Chrome, Version 127.0.6533.100 (Official Build) (64-bit)
WordPress 6.5.5
Redirections Version 5.4 installed! 
Also tried in MS Edge, Version 127.0.2651.98 (Official build) (64-bit) with same behavior

**Comment by johngodley** [comment]
I don't understand what the problem is you have described.

What URL isn't working?

**Comment by chellerobinson** [comment]
Hello John,

The problem is that the redirect does not work if a user types each
individual character into a browser window as below:

opisnet.com/global-lpg-outlook

It does work if 'www' dot is appended to the domain, ie.
www.opisnet.com/global-lpg-outlook

We are using this on print materials, so the shortened version is preferred.

Does this help to clarify the problem we are having?

Thanks,
Chelle

--
Chelle Robinson
WEBSITE AND SEARCH MANAGER


P: +1 301-245-3307 (Zoom) | C: +1 828-365-6526

E: ***@***.***

**Comment by johngodley** [comment]
I'm not sure why you mention typing characters into a browser - this makes no difference in the URL.

`opisnet.com/global-lpg-outlook` - does not work
`www.opisnet.com/global-lpg-outlook` - works

These are different URLs.

https://redirect.li/http/?url=https%3A%2F%2Fopisnet.com%2Fglobal-lpg-outlook
https://redirect.li/http/?url=https%3A%2F%2Fwww.opisnet.com%2Fglobal-lpg-outlook

You will need to fix the one that doesn't work. This has nothing to do with Redirection.

**Comment by chellerobinson** [comment]
Thank you for the clarification. I was able to get it to work using the
second server redirect:
[image: image.png]

I appreciate your assistance with this!

~Chelle
