### ISSUE TITLE
Filter for getHttpCodes

### ISSUE THREAD

**Issue by furai** [johngodley/redirection#3905]
Hello!

Would it be possible to change what redirection codes are available in dropdown when setting up a redirect? I'd like to be able to limit users to be able to specify 301/302 types of redirects.

I've analysed the source code and it seems that the values for the dropdown come from JS constant array. 

Is it something possible to do at all?

Cheers,
Furai

**Comment by johngodley** [comment]
Sorry no, this is not possible.
