### ISSUE TITLE
Fatal Error: Uncaught Error: Failed opening required '/srv/htdocs/wp-content/plugins/redirection/models/redirect/redirect.php'

### ISSUE THREAD

**Issue by NathanFreshy** [johngodley/redirection#3906]
Plugin causes website to crash when active. Full error report is below: 

PHP Fatal error: Uncaught Error: Failed opening required '/srv/htdocs/wp-content/plugins/redirection/models/redirect/redirect.php' (include_path='/:.') in /srv/htdocs/wp-content/plugins/redirection/redirection.php:47 Stack trace: #0 /wordpress/core/6.6.1/wp-settings.php(522): include_once() #1 /srv/htdocs/wp-config.php(86): require_once('/wordpress/core...') #2 /wordpress/core/6.6.1/wp-load.php(55): require_once('/srv/htdocs/wp-...') #3 /wordpress/core/6.6.1/wp-login.php(12): require('/wordpress/core...') #4 {main} thrown in /srv/htdocs/wp-content/plugins/redirection/redirection.php on line 47

**Comment by johngodley** [comment]
Why does the file not exist? You will need that file for the plugin to work.

**Comment by johngodley** [comment]
Closing for now
