### ISSUE TITLE
Problem starting Redirection 5.5.0

### ISSUE THREAD

**Issue by e-SerdarK** [johngodley/redirection#3908]
```
Uncaught SyntaxError: Unexpected token '<' https://adminguide.info/wp-content/plugins/redirection/redirection.js?ver=5.5.0-eff218e8a6050e14b616f8d6629e0ae4 1
```

Plugin: 5.5.0 4.2
WordPress: 6.6.1 (single)
PHP: 8.0.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
JavaScript: https://adminguide.info/wp-content/plugins/redirection/redirection.js?ver=5.5.0-eff218e8a6050e14b616f8d6629e0ae4
REST API: https://adminguide.info/wp-json/

**Comment by johngodley** [comment]
As shown on the error page this is likely caused by another plugin.
