### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by kaiconan** [johngodley/redirection#391]
I am a Chinese (Taiwan) #zh_TW Translator.

I do not see any #zh_TW .mo and .po files in this plugin project, therefore I try to make one, and I go to either "https://translate.wordpress.org/projects/wp-plugins/redirection" or translate my own .mo and .po files, I can not successfully to see the what I translated.

Also, I try to put .mo and .po files under:
/wp-content/plugins/redirection/locale with named redirection-zh_TW .mo and .po
or
/wp-content/languages/plugins with named redirection-zh_TW .mo and .po

So, I try to change my WordPress to other languages, which already translated, such as Japanese and Chinese (China), and I find out it would not show those the languages that I choose.

I need help for the translation to Chinese (Taiwan) #zh_TW.

Did I make any mistakes? Please help me.

[redirection-zh_TW.zip](https://github.com/johngodley/redirection/files/1307449/redirection-zh_TW.zip)

**Comment by johngodley** [comment]
Some additional processing steps are required before a translation will appear in the plugin.

If you provide the translation on translate.wordpress.org then it will be automatically included in the next version of the plugin.
