### ISSUE TITLE
Problem starting Redirection 5.5.0

### ISSUE THREAD

**Issue by HMDberrichi** [johngodley/redirection#3914]
Plugin: 5.5.0 4.2
WordPress: 6.4.5 (single)
PHP: 7.3.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 CCleaner/127.0.0.0
JavaScript: https://kideg.com/wp-content/plugins/redirection/redirection.js?ver=5.5.0-eff218e8a6050e14b616f8d6629e0ae4
REST API: https://kideg.com/wp-json/

**Comment by johngodley** [comment]
Please follow the onscreen instructions. This is likely caused by another plugin.
