### ISSUE TITLE
Is redirection generating content-security-policy: headers?

### ISSUE THREAD

**Issue by peppertreeit** [johngodley/redirection#3917]
### Summary

Recently I migrated a site from CentOS7 to AL23 and this resulted in everything getting upgraded.

Since then the site has been generating the following header which is breaking a lot of things like the hubspot plugin, any external images, fonts, or JS libraries.

content-security-policy: default-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';img-src 'self' data:

The only file I can track this down to is redirection.js

grep -ir 'style-src' wordpress/ | more
wordpress/wp-content/plugins/redirection/redirection.js

### Actual Behavior
This CSP policy is stopping the browser from downloading any content from other sites such as fonts, images, styles etc.
In inspect I see the following sorts of errors:

Refused to load the font 'data:application/x-font-woff;charset=utf-8;base64<snip>' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

Refused to load the image 'https://secure.gravatar.com/avatar/<snip>?s=128&d=mm&r=g' because it violates the following Content Security Policy directive: "img-src 'self' data:".

HubSpot plugin Iframe not rendered {portalId: '', container: div#leadin-iframe-container, appName: 'integrated-plugin-app', hasIntegratedAppEmbedder: false}
<snip>
useAppEmbedder.ts:105 Refused to connect to 'https://exceptions.hubspot.com/api/1/store/?sentry_version=7&sentry_client=raven-js%2F3.19.1&sentry_key=<snip>' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

I am not sure if this plugin is at fault here but this is where I have tracked the problem down to so far.
if not I would appreciate any hints you my have on where I should be looking.

I have tried installing "HTTP Headers from Dimitar Ivanov" & that will add a second line of content-security-policy header but least  permissive wins so the first can't be overridden.

many thanks
Alan

### Steps to reproduce
Don't know, not presently prepared to risk a second site.

### Environment
Redirection Version 5.5.0
WordPress 6.6.1
PHP 8.3.7 (cli) (built: May  7 2024 16:35:26) (NTS gcc aarch64)
PHP 8.3.7 (fpm-fcgi) (built: May  7 2024 16:35:26)
Server version: Apache/2.4.62 (Amazon Linux)
Linux  6.1.102-111.182.amzn2023.aarch64

Chome Version 128.0.6613.114 (Official Build) (x86_64)
iMac18,3 (2017,27") Ventura 13.6.9

**Comment by johngodley** [comment]
The plugin only adds the headers you configure on the site page. It does not add anything otherwise.

**Comment by johngodley** [comment]
Closing for now.
