### ISSUE TITLE
Create Bulk Redirects Using a .csv File

### ISSUE THREAD

**Issue by Incosi** [johngodley/redirection#392]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I'va made a .csv file for my redirects according to your explanation. Column A the old urls, in column B the new, without the domain name

### Actual Behavior

I uploadet that file to the plugin and nothing happened. About 700 urls, but nothing was importetd. Total redirects imported: 0

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Chrome 60, wordpress 4.8.1 and latest Redirection plugin.

please help!!!!! I'm trying to fix this all day now..... 16 hours in a row

**Comment by escrevapromarcos** [comment]
Same issue here.

**Comment by mustafauysal** [comment]
Hello folks,

I guess, it can be formatting problem. What is the type of CSV file? (semicolon or comma separated) 
Can you upload to google drive and download as a comma separated CSV. 

I've tried and its working pretty fine.

**Comment by Incosi** [comment]
I tried both and didn't work unfortunately....

**Comment by mustafauysal** [comment]
@Incosi If the CSV file is not confidential, can you share? I'd like to take a look.

**Comment by Incosi** [comment]
Hi Mustafa, that's no longer necessary. Because there was some time pressure, I did the redirects manually. I do not have to use any csv anymore.

**Comment by mustafauysal** [comment]
@Incosi Oh, sorry to hear that! 
@escrevapromarcos is the problem persist for you? Can you provide example CSV file?

**Comment by escrevapromarcos** [comment]
Hi @mustafauysal ! Yes, you can take a look at my CSV. It's attached. 

Also, I will show you my screen right after I imported it: http://prntscr.com/gpnfr9

[301 Redirect.zip](https://github.com/johngodley/redirection/files/1330977/301.Redirect.zip)

**Comment by mustafauysal** [comment]
@escrevapromarcos thanks for the file.

I see the problem;

* first of all, you should use comma delimited csv file. (your file using semicolon)
* second; use `csv` extension, not capitalized `CSV`  

You can see the corrected file:
[301 Redirect.csv.zip](https://github.com/johngodley/redirection/files/1331145/301.Redirect.csv.zip)

Also, can use relative path instead of full url in the `B` column. 

@johngodley filename is not allowing capitalized CSV. Could you take a look?

Cheers,

**Comment by escrevapromarcos** [comment]
@mustafauysal worked like a charm. Thank you so much! I would have never guessed that! Excel outputs is automatically with capitalized .CSV
