### ISSUE TITLE
Problem starting Redirection 5.5.0

### ISSUE THREAD

**Issue by anilmeena** [johngodley/redirection#3924]
Plugin: 5.5.0 4.2
WordPress: 6.6.2 (single)
PHP: 8.1.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
JavaScript: https://staging.avdheshsharma.com/wp-content/plugins/redirection/redirection.js?ver=5.5.0-eff218e8a6050e14b616f8d6629e0ae4
REST API: https://staging.avdheshsharma.com/wp-json/

**Comment by johngodley** [comment]
This is likely caused by another plugin.
