### ISSUE TITLE
How to redirect UTM and other paramters

### ISSUE THREAD

**Issue by tomas-velech** [johngodley/redirection#3925]
Hi, I would like to ask you.

We have a landing page on which UTM parameters and other parameters such as fbclid are written from the ad. There will be a link to our second website on the landing page and we need these parameters to be entered after clicking through. Is it possible to achieve this with a plugin? If so, can you help me set it up?

Thank you,
Tom

**Comment by vaz** [comment]
You're saying you need to pass along the same utm parameters to the URL of a link on your page?

This isn't really about redirection (the plugin or the concept). You need that page to render those links with the parameters you want appended to the link itself (in the `href=""` attribute.
