### ISSUE TITLE
Problem starting Redirection 3.7.3

### ISSUE THREAD

**Issue by muzi-thinkvacuums** [johngodley/redirection#3927]
```
SyntaxError: illegal character U+FFFD https://www.thegroutcleaningstore.com/wp-content/plugins/redirection/redirection.js?ver=3.7.3-a878595a6024a1bf169ca4237eb6ffa7 33
```

Plugin: 3.7.3
WordPress: 5.1.19 (single)
PHP: 5.6.40
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
JavaScript: https://www.thegroutcleaningstore.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.thegroutcleaningstore.com/wp-json/

**Comment by johngodley** [comment]
The file https://www.thegroutcleaningstore.com/wp-content/plugins/redirection/redirection.js is corrupt. You will need to install it again

**Comment by muzi-thinkvacuums** [comment]
The plugin is not compatible with my current version of WordPress as it says

**Comment by johngodley** [comment]
You are using a 5 year old version of the plugin. You should update to the latest version and then maybe the plugin file won't be corrupt
