### ISSUE TITLE
How to fix this issue

### ISSUE THREAD

**Issue by Harrold1995** [johngodley/redirection#3930]
Unable to load Redirection ☹️ v5.5.0
This may be caused by another plugin - look at your browser's error console for more details.

If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

Also check if your browser is able to load redirection.js:

https://opolis.co/wp-content/plugins/redirection/redirection.js?ver=5.5.0-eff218e8a6050e14b616f8d6629e0ae4

Please note that Redirection requires the WordPress REST API to be enabled. If you have disabled this then you won't be able to use Redirection

Please see the [list of common problems](https://redirection.me/support/problems/).

If you think Redirection is at fault then create an issue.

Plugin: 5.5.0 4.2
WordPress: 6.6.2 (single)
PHP: 8.1.29
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
JavaScript: https://opolis.co/wp-content/plugins/redirection/redirection.js?ver=5.5.0-eff218e8a6050e14b616f8d6629e0ae4
REST API: https://opolis.co/wp-json/

**Comment by johngodley** [comment]
The error message contains all the details, and the `redirection.js` cannot be loaded from the above URL. You will need to fix this.
