### ISSUE TITLE
Problem starting Redirection 5.5.0 - redirection.js return 403

### ISSUE THREAD

**Issue by liammcluckie** [johngodley/redirection#3934]
Plugin: 5.5.0 4.2
WordPress: 6.6.1 (single)
PHP: 8.1.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
JavaScript: https://www.orangutans-sos.org/content/plugins/redirection/redirection.js?ver=5.5.0-eff218e8a6050e14b616f8d6629e0ae4
REST API: https://www.orangutans-sos.org/wp-json/

This site is not using Cloudflare and I have excluded the redirection.js file from any caching. Checking in the network tab the redirection.js files are not loading and are returning a 403 error. This is the same if I try to load the url's for these files in the browser.

**Comment by johngodley** [comment]
This problem is caused by your site setup and not something I can help with. You should contact Cloudflare or your hosting provider.
