### ISSUE TITLE
preg_match() Compilation failed for Redirection from Query Monitor

### ISSUE THREAD

**Issue by robbie-hunt** [johngodley/redirection#3939]
Hi,

In debugging my site speed, I disabled plugins and slowly enabled them while watching Query Monitor across my pages. When I enabled Redirection, I saw a PHP error of Warning status in Query Monitor that seems to be Redirection. I've attached a screenshot  below of the entire error shown in Query Monitor.

### Environment
Brave Browser 1.71.121 on macOS 14.7.1
WordPress 6.6.2
PHP 8.3.12
nginx 1.18.0
Redirection 5.5.0 

![Screenshot 2024-11-06 at 17 21 13](https://github.com/user-attachments/assets/74e02ba5-c706-4f55-9719-235b996f98b6)

**Comment by johngodley** [comment]
You will need to fix whatever invalid regular expression you have created.
