### ISSUE TITLE
Why it's not working in WP.com?

### ISSUE THREAD

**Issue by mikhailgrozovskiy** [johngodley/redirection#394]
### Summary

I installed it on WP.com, and it doesn't provide actual redirects.

### Actual Behavior

Redirects are all setup, but when I click the link it ends in 404. Nothing happens.

### Steps to reproduce

I setup redirects from the log, click the link, have 404.

### Environment

It's the latest version, and I'm on WP.com.

**Comment by johngodley** [comment]
How did you install it on WP.com?

**Comment by mikhailgrozovskiy** [comment]
It's now available as a part of Business plan. Moreover, your plugin said to be tested for WP.com.
<img width="1272" alt="screen shot 2017-09-21 at 16 36 04" src="https://user-images.githubusercontent.com/32029967/30698622-2ff7231a-9eeb-11e7-9f24-4220534756a3.png">

**Comment by johngodley** [comment]
Hmm ok thanks. I have done nothing to test on WP.com, or said anywhere in the plugin that it will run on WP.com so I don't know where that information is coming from. I will investigate myself and see what the situation is.

**Comment by johngodley** [comment]
I've had reports from people that it does work on wp.com. I'll close this for now, but if you still have a problem can you provide details of the URL you are using so I can check.
