### ISSUE TITLE
Problem starting Redirection 2.7.3

### ISSUE THREAD

**Issue by leosaraceni** [johngodley/redirection#396]
```

```

Plugin: 2.7.3
WordPress: 4.8
PHP: 5.4.24
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by leosaraceni** [comment]
Plugin shows "loading" and then goes to the error page. Console dash shows nothing wrong , only 1 -2 warnings.

**Comment by johngodley** [comment]
Was there a message shown there? What are the warnings?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
