### ISSUE TITLE
Problem starting Redirection 2.7.3

### ISSUE THREAD

**Issue by itbulu** [johngodley/redirection#397]
```

```

Plugin: 2.7.3
WordPress: 4.8.1
PHP: 7.0.21
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by johngodley** [comment]
Can you post the full details please?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
