### ISSUE TITLE
"Delete All" button for specific search output

### ISSUE THREAD

**Issue by moses10960** [johngodley/redirection#398]
Hi,
There used to be 2 options when deleting logs - one to delete all logs, and the other to delete all items after searching for a specific phrase. This used to help me a lot, say if I want to search for all ".php" items and delete them. After one of the recent upgrades, I have to manually delete page by page. Any chance we get that back? I hope I'm clear enough.
Best,
Moses

**Comment by johngodley** [comment]
It was added in https://github.com/johngodley/redirection/pull/288 and will be in the next released version.

**Comment by moses10960** [comment]
Thanks John
