### ISSUE TITLE
Error to activate the plugin - Database - Starting Redirection 2.7.3

### ISSUE THREAD

**Issue by osprofanos** [johngodley/redirection#399]
I installed the plugin and at the time of activation, the error message appears.

I have already uninstalled and uploaded directly through FTP, but the error continues to appear.

Would anyone have the solution?

**Erro no banco de dados do WordPress: [Unknown collation: 'utf8']**
CREATE TABLE IF NOT EXISTS `apswp_redirection_items` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `url` mediumtext NOT NULL, `regex` int(11) unsigned NOT NULL DEFAULT '0', `position` int(11) unsigned NOT NULL DEFAULT '0', `last_count` int(10) unsigned NOT NULL DEFAULT '0', `last_access` datetime NOT NULL, `group_id` int(11) NOT NULL DEFAULT '0', `status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled', `action_type` varchar(20) NOT NULL, `action_code` int(11) unsigned NOT NULL, `action_data` mediumtext, `match_type` varchar(20) NOT NULL, `title` varchar(50) DEFAULT NULL, PRIMARY KEY (`id`), KEY `url` (`url`(191)), KEY `status` (`status`), KEY `regex` (`regex`), KEY `group_idpos` (`group_id`,`position`), KEY `group` (`group_id`) ) DEFAULT CHARACTER SET utf8 COLLATE=utf8

**Erro no banco de dados do WordPress: [Unknown collation: 'utf8']**
CREATE TABLE IF NOT EXISTS `apswp_redirection_items` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `url` mediumtext NOT NULL, `regex` int(11) unsigned NOT NULL DEFAULT '0', `position` int(11) unsigned NOT NULL DEFAULT '0', `last_count` int(10) unsigned NOT NULL DEFAULT '0', `last_access` datetime NOT NULL, `group_id` int(11) NOT NULL DEFAULT '0', `status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled', `action_type` varchar(20) NOT NULL, `action_code` int(11) unsigned NOT NULL, `action_data` mediumtext, `match_type` varchar(20) NOT NULL, `title` varchar(50) DEFAULT NULL, PRIMARY KEY (`id`), KEY `url` (`url`(191)), KEY `status` (`status`), KEY `regex` (`regex`), KEY `group_idpos` (`group_id`,`position`), KEY `group` (`group_id`) ) DEFAULT CHARACTER SET utf8 COLLATE=utf8

**Fatal error**: Uncaught exception 'Exception' with message 'There was a database error installing Redirection - please post these details to https://github.com/johngodley/redirection/issues - CREATE TABLE IF NOT EXISTS `apswp_redirection_items` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `url` mediumtext NOT NULL, `regex` int(11) unsigned NOT NULL DEFAULT '0', `position` int(11) unsigned NOT NULL DEFAULT '0', `last_count` int(10) unsigned NOT NULL DEFAULT '0', `last_access` datetime NOT NULL, `group_id` int(11) NOT NULL DEFAULT '0', `status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled', `action_type` varchar(20) NOT NULL, `action_code` int(11) unsigned NOT NULL, `action_data` mediumtext, `match_type` varchar(20) NOT NULL, `title` varchar(50) DEFAULT NULL, PRIMARY KEY (`id`), KEY `url` (`url`(191)), KEY `status` (`status`), KEY `regex` (`regex`), KEY `group_idpos` (`group_id`,`position`), KEY `group` (`group_id`) ) DEFAULT CHARACTER SET utf8 COLLATE=ut in **/usr/share/nginx/www/osprofanos.com/wp-content/plugins/redirection/models/database.php on line 132**

### Version

WordPress 4.8.1
Redirection 2.7.3

**Comment by johngodley** [comment]
It seems WordPress is unable to create the Redirection database tables using your configured character set (utf8).

Redirection gets the value for the character set from your `wp-config.php` file - `DB_CHARSET` and `DB_COLLATE`. Have a look there and see if it is set to `utf8`. If it is you may need to change it to something your database server accepts. The default is typically `utf8mb4`.

It's probably worth looking at your existing database tables and seeing what character set they are in. You can find more details about that here:

https://codex.wordpress.org/Converting_Database_Character_Sets

**Comment by osprofanos** [comment]
Thank you for the answer.

I passed the information to the programmer of the page and am waiting if he can do the configuration of the database.

I'll let you know when he has news.

**Comment by ethanpil** [comment]
Same problem here. Unable to create the tables.

**Comment by johngodley** [comment]
@ethanpil same for you as well - can you check your site's DB_CHARSET and DB_COLLATE?

**Comment by johngodley** [comment]
Note that the 2.8 beta will check your database tables and attempt to fix the problem

https://github.com/johngodley/redirection/releases/tag/2.8-beta-1

Go to the support page once installed.

**Comment by johngodley** [comment]
Version 2.8 has been released with the feature to repair this problem. Closing this for now, but please reopen if you continue to have a problem
