### ISSUE TITLE
Redirection error. I can't back to my original site

### ISSUE THREAD

**Issue by arsens24** [johngodley/redirection#401]
- Chrome
- Macbook 
--------------

 I used to redirect site from http://www.jdsinside.co.kr to http://www.jdsbest.co.kr.
Both sites are mine, but I tried to change 'jdsinside' to 'jdesbest' experimentally.
But, I wanted to back to my original jdsinside.co.kr URL. but I couldn't.
Now if someone tried to enter the jdsinside.co.kr, it goes to jdsbest.co.kr. I don't want to do that.

I tried to many times and many ways.
I changed my redirection option back again, and deleted redirection plugin, and used "delete option " by redirection plugin.
But I can't.

How can I fix this issue? I really want to back to my original web address http://www.jdsinside.co.kr

**Comment by johngodley** [comment]
Your URL is working fine:

`
curl -v jdsinside.co.kr
* Connected to jdsinside.co.kr (183.111.138.170) port 80 (#0)
> GET / HTTP/1.1
> Host: jdsinside.co.kr
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 20 Sep 2017 08:12:28 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Powered-By: PHP/7.0.0p1
`

Clear your browser cache if it is still redirecting.

**Comment by arsens24** [comment]
Um.. when I deleted my browser cache, I can enter the jdsinside.co.kr directly.
but. I have a question.

When it come to again, user can't go to re-changed site when he still have a cache in his browser.
I don't understand this structure. Isn't there no way?
