### ISSUE TITLE
404 errors on redirects  - redirected too many times

### ISSUE THREAD

**Issue by Trishabc** [johngodley/redirection#402]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

I am trying to redirect my domain variations to the preferred domain address. (eg. non-www to www and http to https)

Behaviour

Having set this up (see below on how) I am now getting 404 errors 'redirected you too many times' (see screenshot 1). i have cleared my cache and closed the browser, but 404 still occurring.

Steps to reproduce the problem

This is a new site, which at the time of setting up the redirect had not been indexed (not sure if this is relevant?)

my preferred domain is: https://www.thebackroomchiropracticclinic.uk

I set the target url as my preferred domain (https://www)

and did 3 source urls to this target url

the source urls were:

https://thebackroomchiropracticclinic.uk
http://thebackroomchiropracticclinic.uk
http://www.thebackroomchiropracticclinic.uk

I have attached a screenshot (screenshot 2) of the redirects dashboard. as you will see, in the summary of the redirects only the target url is showing not the source url.

prior to this I set my preferred domain with Google Console as www. and submitted a sitemap to Google for the https:/www property. I have created Google Console properties for each of the domain variations (not sure if any of this is relevant!)

I have also attached a screenshot of the 404 error log from Redirections (screenshot 3)

Environment

I am using Google Chrome (latest version). Wordpress Version 4.8.2.  redirection plug in 2.7.3

This is a client's site. Please help me rectify asap! Thank you, Trish

![screenshot 1](https://user-images.githubusercontent.com/32126057/30637348-fbf91aba-9def-11e7-989b-35e113fafa59.png)

![screenshot 2](https://user-images.githubusercontent.com/32126057/30637332-ee69298a-9def-11e7-8760-939a0825dffc.png)

![screenshot 3](https://user-images.githubusercontent.com/32126057/30637361-063eace2-9df0-11e7-9745-3cc5ac2ffbcf.png)

**Comment by johngodley** [comment]
You've created an infinite redirect by redirecting the root to the same site - each time you load the site it will redirect, and your browser eventually gives up.

It would be better to do a global http => https redirect directly using your server.

For example, if you are using Apache then something like this would handle everything:

https://stackoverflow.com/questions/16200501/http-to-https-apache-redirection.

You could then delete the redirects from `/` and just use Redirection to manage URL redirects.

**Comment by Trishabc** [comment]
HI John, thank you for your quick reply.

Unfortunately, I do not understand what you are requesting me to do. I am only have basic skills and do not know how to go about doing global http ...

Is it safe for me to just delete the current redirects (the / ones) set up on Redirection PRIOR to trying to work out how to do the global http?

Is this global http something I could approach my hosting provider to do for me?

or can you give me a some step by step direction?

sorry for being such a novice!

**Comment by johngodley** [comment]
Yes you should delete the current redirects in Redirection - these are causing the infinite loop.

https://wiki.apache.org/httpd/RewriteHTTPToHTTPS

The above link contains what you need to change for Apache. I don't know if you are using Apache but if you are then you can edit your `.htaccess` file and add the lines mentioned in the link.

Your hosting provider may be able to do this for you, and it may be something you can set up from your providers admin panel.

**Comment by Trishabc** [comment]
ok, thanks John
