### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by vikweb** [johngodley/redirection#403]
```
Plugin: 2.7.3
WordPress: 4.8.2
PHP: 7.0.21
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Nonce: 5379448bb1
URL: http://<site>/wp-admin/admin-ajax.php

Error: Invalid group or parameters (165): Table 'vwtest_etophones.wp_redirection_groups' doesn't exist
Action: red_set_group
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"name":"Old Url Pages","moduleId":"1"}
Code: 200 OK
Raw: {"error":{"message":"Invalid group or parameters","code":165,"wpdb":"Table 'vwtest_etophones.wp_redirection_groups' doesn't exist"}}
```

**Comment by johngodley** [comment]
The error shows that your `wp_redirection_groups` table does not exist. I don't know why this table is missing, but if you can restore it then things will work.

If you can't restore it then the best thing to do is:

- Export any important data from Redirection
- Press the red delete button on Redirection settings page to delete everything
- Reactivate the plugin to re-install all database tables
- Import your data back into the plugin

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
