### ISSUE TITLE
Probably a stupid question but i have to know where the redirect data goes

### ISSUE THREAD

**Issue by lucky7t** [johngodley/redirection#404]
I apologize but i cannot see any changes to my htaccess file but your plugin works like a charm!

I'm confused as to where the data goes or how its being redirected. Are these 301 true redirects?

Thank you again for your plugin. Look forward to hearing from you

**Comment by mustafauysal** [comment]
hey @lucky7t 

I'm not author of this plugin but I can say; redirect items are stored in `{$wpdb->prefix}redirection_items` (usually `wp_redirection_items`) table on database, hope it helps.

**Comment by johngodley** [comment]
Yes, they are true 301 redirects (if you've configured them to be 301). As mentioned above they are implemented in code and use a database table to store them.
