### ISSUE TITLE
Redirection logging external forum links as 404

### ISSUE THREAD

**Issue by mattbrett** [johngodley/redirection#405]
Hi there,

I'm using Redirection on a WP site that has a phpBB installation inside the WP root, but it's not associated with WP in any way, other than sharing some theme assets (images, stylesheets, and scripts). Redirection seems to be logging every forum hit as a 404.

While doing some digging in the support forum on wordpress.org, I saw someone mention adding a regex rule that "does nothing" to remove unwanted 404 entries from the log, but that's not working. It is tracking the rule, as it has 26k hits in just a couple days, but the 404s persist.

Any suggestions on how to exclude the forum links from being tracked?

The forum is installed in /forum, and the regex rule I've added is /forum(.*)

**Comment by johngodley** [comment]
If Redirection is logging 404s for phpBB then it means that every page is running through WordPress before hitting phpBB. You will need to investigate this further and potentially add something to your Apache/Nginx rewrite rules so that requests for phpBB go direct to phpBB.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
