### ISSUE TITLE
Feature Request: Point and Click 404 new page mapping

### ISSUE THREAD

**Issue by noahkuhn** [johngodley/redirection#406]
A common way I use this plugin is when launching a new site that has slightly different URL structures than an old site. For example: /portfolio/project-name/ becomes /work/project-name-again/

I could go through manually and map all these, which I often do, but it would be super helpful to use the 404 area to quickly map missing pages to new existing pages. Obviously this can be done by finding the 404 and pasting in the new URL, but what if you could click the 404 to add a redirect, and then quickly search/pick from a list of all your content. Kind of like the new built-in WordPress "link" tool. That way I click, type the first few chars of the project name, click it, and click done. Saves having to browse the new site, find the full URL, and paste it in.

Just an idea...

**Comment by johngodley** [comment]
The target URL now suggests existing posts.
