### ISSUE TITLE
exception rule for admins 

### ISSUE THREAD

**Issue by trishiss** [johngodley/redirection#407]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary
Is it possible to set an exception rule for admins? or a static IP address to input? 

### Actual Behavior

i am redirecting my new website homepage to an old site as an interim solution but i still need to be able to access it when i do my content changes.

### Steps to reproduce

-

### Environment

Chrome, WP 4.8.2

**Comment by johngodley** [comment]
In #1232 you can add a 'do nothing' redirect that will override any other redirect
