### ISSUE TITLE
DNS error for wp-login.php when Redirection is activated

### ISSUE THREAD

**Issue by HThurm** [johngodley/redirection#408]
Started within the last 24 hours. When Redirection is activated, I receive this error: wp-login.php’s server DNS address could not be found 
DNS_Name_Not_Found 

This occurs when I try to access the /login.php or admin page of my website. Error comes up on both Chrome and IE. The website itself will still run. Deactivating the plugin solves the issue. Deactivating all plugins and only activating Redirection still causes the error to occur, so I doubt it's a plugin conflict with another plugin.

### Environment

Chrome, Wordpress 4.8.2, Redirection 2.7.3

**Comment by johngodley** [comment]
I cannot think of anything in the plugin that could cause such a message, and don't see how it would even be possible.

Where does it show this message? Do you have a URL I can look at?

**Comment by HThurm** [comment]
http://prvteye.com/wp-admin login page is working now because I deactivated redirection. I can reactivate it for you if you need.

**Comment by johngodley** [comment]
Sure. I note that your site is using Wordfence, and is blocking access to wp-admin. It is Wordfence that is probably responsible for any blocking.

**Comment by HThurm** [comment]
I reactivated the plugin for a bit.

> I note that your site is using Wordfence

 Wait where are you seeing that information? I don't see that listed in my plugin files

**Comment by johngodley** [comment]
<img width="771" alt="your_access_to_this_site_has_been_limited" src="https://user-images.githubusercontent.com/1277682/30757930-4b81eb8c-9fc8-11e7-97c1-7ab4c95a9c1a.png">

I'm not seeing any difference with Redirection activated.

**Comment by HThurm** [comment]
![dnserror](https://user-images.githubusercontent.com/31487175/30758065-f0965cea-9f9e-11e7-90a9-3f375966126f.PNG)
This is the only error I see when I go to that link

**Comment by johngodley** [comment]
You will need to configure Wordfence to allow me access to the page.

The URL in your screenshot is wrong. I don't know why it would be missing a slash.

**Comment by johngodley** [comment]
The bad URL is what is responsible for the DNS error as you are trying to load prvteye.comwp-login.php. Do you have a redirect setup that is causing this?

**Comment by HThurm** [comment]
found it, did a redirect of /website. that cause a redirect error. Sorry about that!
