### ISSUE TITLE
Redirect with dynamic HTTP query string variables

### ISSUE THREAD

**Issue by viana007** [johngodley/redirection#410]
I think it was nice, to add a option to pass query string variables from source url to target url.

**Comment by johngodley** [comment]
This is planned for a future version

**Comment by spieglio** [comment]
I would love to see this. 100% necessary for being useful. All those `?utm_source=...` links 🙈.

Is there an ETA for this fix?

**Comment by johngodley** [comment]
I don't have an ETA

**Comment by johngodley** [comment]
This will be added as part of #1377

This is marked as alpha. If you are interesting in testing it then you can find a download at https://github.com/johngodley/redirection/releases/tag/4.0-alpha-1

I would appreciate any feedback, either here on Github, or directly at https://redirection.me/contact/

I'll close this as 'done'.

**Comment by pratham2003** [comment]
This should have been an optional feature and not forced onto the users.

Proposing a deprecation in next major release.

For the time being can a backend setting be provided to turn this off?

**The Problem**
From: /some-page/\??(page=\d+)?  (regex)
To: /new-page/

I don't want ?page=10 parameter to be passed on to /new-page/

This adds the query string automatically without an option to turn it off.
The default behaviour should have been to not automatically add it.

**Comment by johngodley** [comment]
This is an optional feature and is not forced onto users.

**Comment by pratham2003** [comment]
How do we turn this off? If I enable regex it always passes the query parameters.
I tried looking through the documentation and closed issues but didn't find anything relevant.

**Comment by johngodley** [comment]
This feature is in 4.0, not 3.4.1

Your regular expression is probably passing the param.

**Comment by pratham2003** [comment]
```
From: /some-page/\??(page=\d+)?  (regex)
To: /new-page/
```

**Test URL:**
https://example.com/some-page/?page=10

**Expected result/redirect:**
https://example.com/new-page/

**Actual result/redirect:**
https://example.com/new-page/?page=10

I don't want ?page=10 parameter to be passed on to /new-page/
Is this possible in 3.4.1 or 4.x?

**Comment by johngodley** [comment]
`/some-page/\??(page=\d+)? ` => `/new-page/` does not pass any parameters. I've just tried the same redirect and it works as expected.

You may need to clear your browser cache, or there may be another redirect in action (either in Redirection or otherwise).

**Comment by johngodley** [comment]
Can you move this over to a new issue as it is unrelated with this one?
