### ISSUE TITLE
redirects to html.html

### ISSUE THREAD

**Issue by Maz999** [johngodley/redirection#411]
I've just noticed  many of my urls are being redirected to html.html whereas before, they were normal (ending in just html). I think it was since I updated the plugin. 
Can anyone help/advise how to fix this?

**Comment by johngodley** [comment]
Can you provide details of these URLs and how you have set them up?

**Comment by Maz999** [comment]
Here's one of them; https://lovefoodies.com/spiced-pecan-carrot-cake-html-html.html 
It looks like the redirection plug in is changing them to show the extra html's on the end as in this screen shot. (I've just changed that second one for the cabbage manually and then noticed all the others which will need changing too but it will take me a long time to do each one individually. 
![html](https://user-images.githubusercontent.com/32266428/30810239-50ac4270-a1fc-11e7-8d8b-3e7e95eea58f.jpg)

**Comment by johngodley** [comment]
Sorry I'm a bit confused.

Using https://lovefoodies.com/spiced-pecan-carrot-cake-html-html.html as the base alongside your screenshot I can see the source URL is:

https://lovefoodies.com/spiced-pecan-carrot-cake-html.html

And you have this redirected to:

https://lovefoodies.com/spiced-pecan-carrot-cake-html-html.html

This is working as expected.

I've tried a few other URLs from your screenshot and they also seem to be working as expected.

Can you explain more about what isn't working? What should be happening in the above instance?

**Comment by Maz999** [comment]
By the way, I haven't actually redirected anything, this is just what I have seen when I went in to the redirects page then noticed all these url's had changed (on their own)

**Comment by johngodley** [comment]
Ok, so I think what you are saying is that the `-html-html.html` target is not what you have added? Or are you saying that you haven't created any redirects at all and these are all new?

There is nothing in the Redirection plugin to modify URLs like this, and it doesn't pay attention to file extensions. About the only thing I can think is that something else on your site is triggering post updates, and this is causing Redirection to think that a post has changed and so it creates a new redirect. This is the monitoring section from Redirection's settings page.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
