### ISSUE TITLE
Problem starting Redirection 2.7.3

### ISSUE THREAD

**Issue by thomasvanderbeek** [johngodley/redirection#412]
```
Uncaught SyntaxError: Invalid or unexpected token http://{{valid_domain}}/app/plugins/redirection/redirection.js?ver=2.7.3-a27c77af0d47abb92ce2f83236f9986b 11
```

Plugin: 2.7.3
WordPress: 4.8.2
PHP: 7.1.9-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by johngodley** [comment]
There's not enough information in the other issues to know if they're duplicates.

The message seems to suggest a JS error in the file redirection.js. If you load this directly does it look like JavaScript? Has anything else been added to the file? I'm unable to access the file on your dev server so can't check for myself.

**Comment by thomasvanderbeek** [comment]
Yes, the redirection.js file is loaded and looks like a Javascript file. However, when I scroll down, there are many questionmarks, see example below.

```
function(e,t,n){"use strict";function r(){this.protocol=null,this.slashes=null,this.auth=null,this.h`�����`���������������������`��������������P���������������������������@��������������������=null
```

When you check the redirection.js in an IDE, you'll find something like DC1 Ë SOH NUL NUL NUL etc. etc.

**Comment by johngodley** [comment]
Can you zip up your redirection.js and post it here? I suspect it's an incomplete file

**Comment by thomasvanderbeek** [comment]
Resolved it by deleting the plugin and reinstalling it. I guess it got corrupted during a (S)FTP transfer.
