### ISSUE TITLE
Redirect all URLs beginning with XX to a single web page?

### ISSUE THREAD

**Issue by danyork** [johngodley/redirection#413]
@johngodley - THANK YOU for your awesome plugin! It is enormously helpful!

### Summary

With the launch of our new website, we have discontinued support of 3 languages. I would like to set up a redirect so that visitors to any page under the those previous languages get sent to a single page outlining our new policy for languages -

 https://www.internetsociety.org/about-web-site/language-support/

### Actual Behavior

All of our past Arabic, Russian and Chinese content has URLs starting with one of:

* /ar/
* /ru/
* /zh-hans/

I can set up a redirect using a regex for "/ar/*" pointing to that page - but the plugin does what I want it to do most other times and tries to find the old URL under that single page.  Instead I want it to NOT look for the URL that matched the wildcard, but instead to simply point to the single page.

Is there a way to do this simply?  Or do I need to just go down through each of the individual URLs and set up a redirection to the single page?

Thanks again for the awesome plugin.

**Comment by johngodley** [comment]
I'm not entirely sure I understand the problem. Can you give an example URL of something that isn't working, and what you want it to do?

**Comment by danyork** [comment]
John, Sure. Here are two of the URLs that used to work on our old site for Arabic (these actually point to a development server for this testing):

- https://dev.internetsociety.org/ar/issues/supporting-women
- https://dev.internetsociety.org/ar/tags/konojel-project

Since we are not supporting Arabic on our new site any more, I want to direct those URLs - and any other URLs starting in "/ar/" to this ONE page:

https://dev.internetsociety.org/language-support/

In the list of redirections, I now have one set as a regex with the following info:
```
/ar/*
/language-support/
```
However, what that does is naturally append the URL slug to the end of `/language-support/` so that my URLs are now:

- https://dev.internetsociety.org/language-support/issues/supporting-women
- https://dev.internetsociety.org/language-support/tags/konojel-project

and they are both 404s.

What I really want is a way to do a regex on an entire set of pages and point them to one single page. In this particular case, I don't want the slug appended to the redirected URL. (In almost every other case, I *do* want this!)

Does that make sense?

Obviously I could go through my 404 logs and find every /ar/ page and redirect it to this one URL, but I'm wondering if there is a way I can do it with a regex of some type.

**Comment by johngodley** [comment]
`*` on its own is not a valid regular expression. You will need to put something like `.*` and then the pattern will correctly match.

**Comment by danyork** [comment]
John, I changed the expression to ".*" and it is still behaving the same, i.e.

- https://dev.internetsociety.org/ar/issues/supporting-women

goes to:

- https://dev.internetsociety.org/language-support/issues/supporting-women

which is a 404.  (Again, I'd note that 90% of the time this is exactly the behavior I *WANT* with a regex redirect. I am typically redirecting from one directory tree to another. In this particular case, I do NOT want the slug to be appended to the target URL. I just want the target URL to be displayed.)

It's okay... if there's not an easy way to do this, I can just sit and go through the 404 logs and change every "/ar/..." error to point to this one page.  I was just curious if there was an easier way to do this so that I'm not adding hundreds of extra redirects. (I also have to do it for all of our "/ru/" and "/zh-hans/" pages.

**Comment by johngodley** [comment]
You need to clear your browser cache. Your URL is working differently now

**Comment by johngodley** [comment]
```
curl -v -I https://dev.internetsociety.org/ar/issues/supporting-women

*   Trying 46.43.36.222...
* TCP_NODELAY set
* Connected to dev.internetsociety.org (46.43.36.222) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=dev.internetsociety.org
*  start date: Sep 13 22:01:00 2017 GMT
*  expire date: Dec 12 22:01:00 2017 GMT
*  subjectAltName: host "dev.internetsociety.org" matched cert's "dev.internetsociety.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> HEAD /ar/issues/supporting-women HTTP/1.1
> Host: dev.internetsociety.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 02 Oct 2017 14:22:11 GMT
< Server: Apache/2.4.10 (Debian)
< Location: /language-support/
< Access-Control-Allow-Origin: *
< Content-Type: text/html; charset=UTF-8
```
