### ISSUE TITLE
302 redirect instead of 301 for modified posts

### ISSUE THREAD

**Issue by katteyspares** [johngodley/redirection#418]
Hello!

If we add something to redirect then it create a 301 redirect, which is fine and correct since we need 301 redirect.

But problem is when we change the post slug then it create a redirect in redirection with Type "0". Monitor changes to posts is enable and its to modified posts. The redirection is working but its a 302 redirection instead of 301 redirection.

We believe it has to be 301 redirection instead of 302.

You can check the following two url and in redirection they are marked as type 0 instead of 301.

[http://howrid.com/home-remedies/peeling-skin-treatment/](
http://howrid.com/home-remedies/peeling-skin-treatment/)

[http://howrid.com/skin/have-light-skin/](http://howrid.com/skin/have-light-skin/)

Please check and advice.

**Comment by johngodley** [comment]
This is fixed in #422 and will be included in the next version of the plugin.
