### ISSUE TITLE
What does "Auto-generate URL:" do?

### ISSUE THREAD

**Issue by tobyfoote** [johngodley/redirection#419]
I currently use two redirection plug-ins. I use your "Redirection" for known 301 errors (redirecting to specific pages) and the plugin called "404 To Start" for catch-all 301 errors (redirecting to the homepage). I'd like to just use Redirection, if possible, to redirect all the unscripted redirects to the homepage. In looking at the settings for Redirection, there's a setting for "Auto-generate URL:" which sounds like it might do what I'm looking for, but I can't find documentation that makes sense what this is for.

- How can I redirect all traffic to homepage that doesn't have a rule already?
- What does "Auto-generate URL:" do?

**Comment by johngodley** [comment]
Redirection doesn't have a catch-all feature as I think it's a bad idea to redirect all 404s. There's more details about this on the plugin support page.

Auto-generate is used if you leave a URL blank it will use the auto-generate URL instead.

**Comment by tobyfoote** [comment]
What does it mean "if you leave a URL blank"? Sorry if this seems like a stupid question, I just don't understand.

Thank you for the clarification on the catch-all feature not being in the product.

**Comment by johngodley** [comment]
If the target URL is blank when you create a redirect it will be replaced by the contents of the auto-generate URL
