### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by dalefletcher3** [johngodley/redirection#42]
Hi John,

Your plugin has been helpful for us. I am unable to get into the Redirection area of the WP Dashboard as I receive the following error when I try:

Catchable fatal error: Argument 2 passed to Redirection_Table::__construct() must be an instance of Red_Group, boolean given, called in /home3/jelcoach/public_html/wp-content/plugins/redirection/redirection-admin.php on line 329 and defined in /home3/jelcoach/public_html/wp-content/plugins/redirection/models/pager.php on line 10

Cab you guide me as to how this should be fixed?

Thanks so much!

Dale

**Comment by johngodley** [comment]
It means you have deleted the modules from Redirection. You can verify this by clicking on the Redirection menu option, then adding `&sub=modules` to the URL. You should see an empty list.

I'm not sure how this would happen, but the easiest way to recreate them is to go the Redirection options page, press on the `delete redirection` button, then re-activate the plugin.

Note that this will delete everything in Redirection, so if you have data you want to keep then you'll need to export and the import it back.

If you are familiar with editing the database it is possible to do this without deleting everything first.

**Comment by nickkuijpers** [comment]
This fixes it indeed. It happend when duplicating a website in our multisite.

Thanks John!
