### ISSUE TITLE
Recursive redirect

### ISSUE THREAD

**Issue by Kilwag** [johngodley/redirection#423]
Pulling my hair out, probably something dead simple I'm missing. Too close to it to see. 

### Summary

There is a custom post type with the slug "resources."  I'm trying to redirect old posts that used to be at the root of the site to the new custom posts. Slugs are all the same, under the /resources/ directory. 

Old Site: http://fakedomain.com/title-of-this-page/
Old Site: http://fakedomain.com/title-of-this-page/?something=added_by_a_referrer

New Site: http://fakedomain.com/resources/title-of-this-page/

### Actual Behavior

 /resources/resources/resources/resources/resources/resources/resources/resources/resources/
 and so on... 

### Steps to reproduce

Source (REGEX): /accommodating-the-rise-in-enterprise-video/(.*)
Target:  /resources/accommodating-the-rise-in-enterprise-video/ 

I need that pattern match at the end because Wordpress gives a 404 on any file redirects that have POST data tacked on the end, and there are a lot from social media posts that already exist.

Makes no difference if I take change the target to something else, it will still recursively redirect to the first part of whatever I change it to, the second I turn on Regex.

HOWEVER: The following works fine.

Old Site: http://fakedomain.com/old-blog-slug/
New Site: http://fakedomain.com/NEW-blog-slug/

with the following:

SOURCE (REGEX) : /old-blog-slug/(.*)
/NEW-blog-slug/$1

### Environment

Wordpress: 4.8.2, Redirection: 2.7.3
happens on all browsers I've tried, Firefox, Chrome, Safari, latest versions

I've disabled every plugin except Redirection

**Comment by Kilwag** [comment]
Should mention, I have the default Wordpress htaccess

===========================

RewriteEngine on

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

**Comment by johngodley** [comment]
Your target URL is matching the source URL pattern. You will need to use `^` or `$` to tie the pattern to the start or end. For example:

`^/accommodating-the-rise-in-enterprise-video/(.*)`

**Comment by Kilwag** [comment]
GAH!  I tried that to no avail, the redirect must have been cached in my browser. Now it works as it should. Man I feel dumb.

**Comment by Kilwag** [comment]
I owe you a pint. Hit me with a PayPal address so I can thank you properly.
