### ISSUE TITLE
Pass Through not working

### ISSUE THREAD

**Issue by khartline** [johngodley/redirection#424]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I have Redirections set up on business site and have multiple redirects set up as pass through, for instance, reinventingevents.com/makemoremoney. When I try to set up a pass through on a new site, it's not taking.

### Actual Behavior

I'm trying to get poshkaren.com/fizi to redirect to http://bit.ly/poshkarenfizi (or https://docs.google.com/forms/d/e/1FAIpQLSfK7veALRZLSTwF2WkV5fFDv8zjZJFNgUZGoNB2_rR0LiZPNw/viewform).

### Steps to reproduce

**I'm sure this is user error but I've followed the same setup as what I have on my business site and it doesn't seem to be working.
Source URL: /fizi
Match: URL only
When matched: Pass-through
Target URL: https://docs.google.com/forms/d/e/1FAIpQLSfK7veALRZLSTwF2WkV5fFDv8zjZJFNgUZGoNB2_rR0LiZPNw/viewform
Group: Redirection    Position: 0

poshkaren.com/fizi is showing:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

### Environment
Chrome, Version 60.0.3112.113 (Official Build),  WP version 4.8.2, Redirection Version 2.7.3

**Comment by johngodley** [comment]
Does your server's error log have any errors in it?

**Comment by khartline** [comment]
Hi John,

Any ideas on this? Not sure if it's a server thing or redirection. This is
the first redirect I've tried setting up with the plug-in on this site.

Thanks!
Karen

**Comment by johngodley** [comment]
Does your server's error log have any errors in it?

**Comment by khartline** [comment]
Not sure. How do I check that?

**Comment by khartline** [comment]
Here's a screenshot of the server issues log:


*Karen Hartline** | *CEO

Reinventing Events <http://reinventingevents.com/>
e: karen@reinventingevents.com
c: 415.683.6945

Find us online:  [image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2FReinventEvents&sn=bWFyaWFAcmVpbnZlbnRpbmdldmVudHMuY29t>
 [image: pinterest]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fpinterest.com%2FReinventEvents&sn=bWFyaWFAcmVpbnZlbnRpbmdldmVudHMuY29t>

<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Freinventing-events%2F&sn=bWFyaWFAcmVpbnZlbnRpbmdldmVudHMuY29t>Want
to sign up for our newsletter? Click here
<http://reinventingevents.us5.list-manage.com/subscribe?u=b3399d09efa76ab2b582aa7c4&id=53dcf472a8>
!

**Comment by johngodley** [comment]
Sorry, the image didn't make it through. You may need to add it directly from the website.

**Comment by khartline** [comment]
![redirection issues](https://user-images.githubusercontent.com/32423218/31135567-3c555fd6-a81a-11e7-9f0e-9b55bc21196c.png)

**Comment by khartline** [comment]
Any thoughts on the issues?

**Comment by khartline** [comment]
Bluehost finally found the issue and resolved it on my last chat with them. Thanks for the help!

**Comment by johngodley** [comment]
Can you describe the problem here so it may help others? Thanks

**Comment by khartline** [comment]
It was something to do with the htmfiles or something like that. I'm really
not sure. It wasn't something I edited but something Bluehost changed on
their side.

*Karen Hartline** | *CEO

Reinventing Events <http://reinventingevents.com/>
e: karen@reinventingevents.com
c: 415.683.6945

Find us online:  [image: Twitter]
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftwitter.com%2FReinventEvents&sn=bWFyaWFAcmVpbnZlbnRpbmdldmVudHMuY29t>
 [image: pinterest]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fpinterest.com%2FReinventEvents&sn=bWFyaWFAcmVpbnZlbnRpbmdldmVudHMuY29t>

<http://s.wisestamp.com/links?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Freinventing-events%2F&sn=bWFyaWFAcmVpbnZlbnRpbmdldmVudHMuY29t>Want
to sign up for our newsletter? Click here
<http://reinventingevents.us5.list-manage.com/subscribe?u=b3399d09efa76ab2b582aa7c4&id=53dcf472a8>
!
