### ISSUE TITLE
301 redirect timing out (old domain to new domain)

### ISSUE THREAD

**Issue by Trishabc** [johngodley/redirection#426]
hya,

### Summary

I am trying to redirect the old domain website to the new domain website. I have, so far, just done the homepage.

### Actual Behavior

When i test the redirect for the homepage it is 'timing out' - see screenshot below

### Steps to reproduce

in redirection plug in  'add new redirect', on the old domain wordpress site,  i put in the following instructions: (also see screen capture below)

(old domain) source url: http://www.thebackroom.org.uk
(new domain) target url: https://www.thebackroomchiropracticclinic.uk

the urls are as per the respective wordpress settings for the individual domains.

### Environment

browser: google chrome
wordpress: 4.8.2
redirection: 2.7.3

attachments x 2

![screenshot 2017-10-02 16 58 45](https://user-images.githubusercontent.com/32126057/31087683-dec8ae42-a795-11e7-8306-ec950ff0f70e.png)

![redirect](https://user-images.githubusercontent.com/32126057/31087698-ec49dc94-a795-11e7-8ff3-d770047c696b.PNG)

please advise where I am going wrong or what I need to do to rectify - I'm not techy so simple language please! 

many thanks, Trish

**Comment by johngodley** [comment]
You are redirecting to a misspelled domain - https://www.thebackroomchiropracticclnic.uk/ - with the `i` in clinic.

**Comment by Trishabc** [comment]
oh my! so sorry to have wasted your time! thank you for quick response!
