### ISSUE TITLE
Plugin Failed to Load with Error 'Redirect'

### ISSUE THREAD

**Issue by Wisedemic** [johngodley/redirection#428]
### Summary
Opening the plugin redirection menu under tools. Fails to load.

### Actual Behavior
Plugin fails to load with this message: 
"Redirection is not working. Try clearing your browser cache and reloading this page.
If that doesn't help, open your browser's error console and create a new issue with the details.
Please mention redirect, and explain what you were doing at the time"

### Steps to reproduce
Open the plugin (tools > redirection) and wait for the fields to load. 

### Environment
Chrome, Firefox, Windows & Mac os. 
Latest version of WP. Plugin is updated.
Cache was cleared from browsers and from WP cache.

**Comment by johngodley** [comment]
Have you looked in your browser's error console for any messages?

If you open the network tab in your browsers developer tools, can you see a request for `redirection.js`? Does it succeed?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
