### ISSUE TITLE
Redirects to WP Media Library Items (PDFs) With HTTPS Not Working In Chrome (Redirects to Blank Page)

### ISSUE THREAD

**Issue by RoryAnon** [johngodley/redirection#429]
### Summary
I am attempting to create vanity URLs for print which redirect to PDFs saved within WordPress Media Library (following example URI structure wp-content/uploads/XXXXX.pdf).  The was created with an without UTM parameters to test issue. 

### Actual Behavior
I set up redirect as follows (also tested proper Regex and box checked to make sure)
![2017-10-03_1114](https://user-images.githubusercontent.com/32489096/31132983-2e969790-a82c-11e7-9cb9-d5d879d80ff6.png)

Source URL:  /update
Target URL (to PDF):  https://al-anon.org/members/pdf/GR1.pdf
Vanity URL on print would be; al-anon.org/update

On Chrome (tested by me and other staff on their PCs) this leads to a blank page eveb after attempting multiple cache clearing.
![2017-10-03_1118](https://user-images.githubusercontent.com/32489096/31134390-ef12b6d6-a82f-11e7-97c0-dd40c97a9d72.png)

When tested using IE, Firefox, Safari, the issue did not occur.

As a test, I changed target URL for the redirect by changing https: to http:  The redirect worked after this, but it having people follow HTTP links to our site is not a solution we are comfortable with long term.

I have had no issue with any other redirect (regex or non-regex) that is sent to a non media library URL on any browser.

### Steps to reproduce
Upload a PDF to Wordpress Media Library
Create a redirect target to PDFs created URL
Test with Chrome

### Environment
Browser: Chrome
Version: 61.0.3163.100
WordPress Version: 4.8.2
Redirection Version: 2.7.3

**Comment by johngodley** [comment]
It works for me in Chrome, and the browser used shouldn't make any difference.

```
curl -v -I http://al-anon.org/update              
*   Trying 173.247.245.102...
* TCP_NODELAY set
* Connected to al-anon.org (173.247.245.102) port 80 (#0)
> HEAD /update HTTP/1.1
> Host: al-anon.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 03 Oct 2017 15:59:32 GMT
< Server: Apache
< Set-Cookie: wfvt_4136808874=59d3b3e54cb9f; expires=Tue, 03-Oct-2017 16:29:33 GMT; Max-Age=1800; path=/; HttpOnly
< Location: http://al-anon.org/wp-content/uploads/GR1.pdf?utm_source=TheForum&utm_medium=print&utm_campaign=NewGroupRegistration
< Vary: User-Agent
< Content-Type: text/html; charset=UTF-8
```

You can try opening Chrome's network tools on a blank page and then visiting the address. You should see the request being made by Chrome and maybe an indication of why its not working for you.

**Comment by RoryAnon** [comment]
Hi John.

Thank you very much for quick response.

I am sorry, I had the redirect going to HTTP address (which is working) not the HTTPS address (which is not working and which is causing the issue).

I have reset the redirect to the HTTPS address.  
The URL is still al-anon.org/update 

When I checked Chrome developer tools, and from what I am seeing, I believe this issue might be this?
Set-Cookie: path=/; HttpOnly

![2017-10-03_1332](https://user-images.githubusercontent.com/32489096/31139429-84d72eae-a83f-11e7-8260-1d36a6d7dca8.png)

Could you check one more time if you don't mind to see if the redirect is working for you?  I just need to narrow down what the issue might be.

Thanks!

**Comment by johngodley** [comment]
Yeah, still works fine for me.

The cookie is being set on the http domain so is fine there.

Here's the new request. You can see the `Location` parameter is set. This won't change if a different browser is used.

```
curl -v -I http://al-anon.org/update             
*   Trying 173.247.245.102...
* TCP_NODELAY set
* Connected to al-anon.org (173.247.245.102) port 80 (#0)
> HEAD /update HTTP/1.1
> Host: al-anon.org
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 03 Oct 2017 17:44:05 GMT
< Server: Apache
< Set-Cookie: wfvt_4136808874=59d3cc65e9a83; expires=Tue, 03-Oct-2017 18:14:05 GMT; Max-Age=1800; path=/; HttpOnly
< Location: https://al-anon.org/wp-content/uploads/GR1.pdf?utm_source=TheForum&utm_medium=print&utm_campaign=NewGroupRegistration
< Vary: User-Agent
< Content-Type: text/html; charset=UTF-8
```

Is it possible you might have a Chrome extension or firewall that may be blocking the request?

**Comment by RoryAnon** [comment]
Hi John,

Thanks again for the followup.  Still getting the issue here at work (checked on other PCs on Chrome with different extensions) and still got the blank page so it might indeed be a office firewall issue.

Interestingly enough, I think the issue is actually that when a URL is typed into a browser (like in our case al-anon.org/update) browsers default to http rather than https which is possibly a reason the issue is happening when the redirect is trying to 301 to a https address if our firewall doesnt like that.

Cheers for the hard work!
