### ISSUE TITLE
Feature Request: 404 hits count indicator on the admin menu

### ISSUE THREAD

**Issue by theflowmachine** [johngodley/redirection#43]
I don't know if I missed it completely, but it would be nice  to have an 404 hits indicator directly on the admin menu link, see the screenshot example below.

![capture](https://cloud.githubusercontent.com/assets/10844654/6036794/dad757b4-ac4a-11e4-9e14-6c6ec4d18e55.PNG)

**Comment by johngodley** [comment]
#1232 adds 404 totals. I don't think it makes sense to put it on the admin menu as typically the numbers will be very large
