### ISSUE TITLE
Error downloading redirects

### ISSUE THREAD

**Issue by Tagmeapp** [johngodley/redirection#431]
I am trying to downloading all redirects

In the import/export screen, under ‘Export’ I select ‘Wordpress redirects’ and then CSV > Download

I then get a ‘This page isn’t working’ message

This is the url 
/wp-admin/tools.php?page=redirection.php&sub=modules&export=1&exporter=csv

I am using Chrome,Version 61.0.3163.100, WordPress 4.8.2, Redirection Version 2.7.3

**Comment by johngodley** [comment]
Is there an error message? Can you add a screenshot of what you are seeing?

**Comment by Tagmeapp** [comment]
![screen shot 2017-10-04 at 10 02 16](https://user-images.githubusercontent.com/31508405/31167796-2fbe7eca-a8eb-11e7-883c-de41f68ba8e6.png)

**Comment by johngodley** [comment]
You'll need to look at your server's error log file to see what is going on. A 500 error usually indicates it has crashed, or is blocking the request for some reason.

**Comment by Tagmeapp** [comment]
OK, thanks for your help John

**Comment by Tagmeapp** [comment]
Hi John

I've looked at our error logs and the only errors we have are 404, 200

Any ideas??

Guy Ullmann
Sales & Marketing Director
Process Industry Informer
+44 (0) 1428 751188
guyullmann@piimag.com
www.piimag.com


<http://www.linkedin.com/in/guyullmann>




*PS. *Would you like to enhance your own reputation in the industry? -
Write for our new Viewpoints section
<http://www.processindustryinformer.com/viewpoints/>

**Comment by johngodley** [comment]
If your log is showing 404 and 200 codes then it sounds like you're looking at the access log, which is not the same as the error log. The error log just deals with server and PHP errors and doesn't contain HTTP codes.

For example, I'm using Nginx on my site and it stores the access log and error log separately in `/var/log/nginx`. If my server is configured to only allow a certain size upload and I try and upload something larger than that then it will log an error in the error log and return a 50x error to the browser.

**Comment by Tagmeapp** [comment]
Hi John

Thanks for the previous notes.

I contacted our hosting company to see if they could shed any light and
they said the limit was being reached, so they had to increase this.

They also commented:

Also it is not normal for a scrip to use that much resources so maybe the
plugin developer should check why this is happening.

I hope that helps

Many thanks,

Guy Ullmann
Sales & Marketing Director
Process Industry Informer
+44 (0) 1428 751188
guyullmann@piimag.com
www.piimag.com


<http://www.linkedin.com/in/guyullmann>




*PS. *Would you like to enhance your own reputation in the industry? -
Write for our new Viewpoints section
<http://www.processindustryinformer.com/viewpoints/>

**Comment by johngodley** [comment]
What resource was having its limit exceeded? Time? Memory?

**Comment by Tagmeapp** [comment]
It was the memory

Guy Ullmann
Sales & Marketing Director
Process Industry Informer
+44 (0) 1428 751188
guyullmann@piimag.com
www.piimag.com


<http://www.linkedin.com/in/guyullmann>




*PS. *Would you like to enhance your own reputation in the industry? -
Write for our new Viewpoints section
<http://www.processindustryinformer.com/viewpoints/>
