### ISSUE TITLE
All my 301 redirects are showing as 302

### ISSUE THREAD

**Issue by Pittare** [johngodley/redirection#432]
I have installed the redireccion Plugin in hopes of it solving all broken links issues with permanent redirects. The Plugin options are fine, however whenever I generate a 301 redirect, either manually ou through CSV file, somehow these are being set as 302, at least its how they are being picked up by every Crawler.

### Actual Behavior

On the plugin BO, for example the broken link https://www.april-seguros.pt/pt/resultados-do-1o-semestre-de-2017-grupo-april/ is showing as a 301 Permanent redirect.

When I use a redirect checker (http://www.redirect-checker.org/index.php) on this it feedsback a 302 redirect. Actually all web-crawllers like DeepCrawl are picking this up as 302 and not 301.

Both Wordpress and the Plugin are on their latest versions.

**Comment by johngodley** [comment]
The URL https://www.april-seguros.pt/pt/resultados-do-1o-semestre-de-2017-grupo-april/ returns a 404 for me. Is the URL correct?

**Comment by Pittare** [comment]
sorry,
https://www.april-portugal.pt/pt/resultados-do-1o-semestre-de-2017-grupo-april/

**Comment by johngodley** [comment]
Ok, I see the 302. If you disable Redirection does the redirect still work?

**Comment by Pittare** [comment]
It does

**Comment by johngodley** [comment]
If it still works then I don't think Redirection is handling the redirect. You should keep Redirection disabled and try and work out what is sending the redirects.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
