### ISSUE TITLE
AnonIP

### ISSUE THREAD

**Issue by ganti** [johngodley/redirection#440]
For privacy reasons I do want to keep my users information private in logfiles, therefore it is an important feature to me masking the last two octets of an ip-address. 
the functionality is pretty simple, see example. I struggled to integrate it as a Option, otherwise I'd made a pull-req. I'd really appreciate if you would add this  low-hanging-fruit :) 

```
//$isAnonIP reads value from options
if($isAnonIP== True){
      $ip = implode( ".", array_slice(explode( ".", $ip ), 0, 2 ) ) . '.0.0';
}
```
IMHO this snippet goes into: `models/requests.php line 46` create an Option and thats it.

**Comment by johngodley** [comment]
You can add a filter for `redirection_request_ip` to modify the IP address

**Comment by ganti** [comment]
i don't get what you

**Comment by johngodley** [comment]
You can add a WordPress filter to your site to perform whatever modification you need:

```php
add_filter( 'redirection_request_ip', 'modify_ip' );

function modify_ip( $ip ) {
  return implode( ".", array_slice(explode( ".", $ip ), 0, 2 ) ) . '.0.0';
}
```

This doesn't require modifying the plugin.

**Comment by ganti** [comment]
thx!
