### ISSUE TITLE
Redirection error

### ISSUE THREAD

**Issue by marrow13** [johngodley/redirection#444]
Error: Unable to add new redirect (204): Field 'last_access' doesn't have a default value
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"url":"/about/","title":"","regex":false,"match_type":"url","action_type":"url","group_id":1,"action_code":301,"action_data":"/about/company/"}
Code: 200 OK
Raw: {"error":{"message":"Unable to add new redirect","code":204,"wpdb":"Field 'last_access' doesn't have a default value"}}

How should I fix it?

**Comment by johngodley** [comment]
Did you fix the problem? The 2.8 beta should help: https://github.com/johngodley/redirection/releases/tag/2.8-beta-1

**Comment by marrow13** [comment]
Thanks) I'll check it up)



11 октября 2017, 10:56:40, от "John" <notifications@github.com>:


Did you fix the problem? The 2.8 beta should help: https://github.com/johngodley/redirection/releases/tag/2.8-beta-1

**Comment by marrow13** [comment]
Hi, John

How could it be solved and what does it mean? 




Plugin: 2.8
WordPress: 4.8.2
PHP: 7.0.10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36


Error: Unable to add new redirect (205): Field 'last_access' doesn't have a default value
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"url":"/main-backup/","title":"","regex":false,"match_type":"url","action_type":"url","group_id":1,"action_code":301,"action_data":"https://jelastic.com/"}
Code: 200 OK



11 октября 2017, 10:56:40, от "John" <notifications@github.com>:


Did you fix the problem? The 2.8 beta should help: https://github.com/johngodley/redirection/releases/tag/2.8-beta-1

**Comment by johngodley** [comment]
It's the same problem as before so I guess version 2.8 didn't help. Basically your database is configured in some way that it's causing an error with Redirection.

The simplest solution will be to press the red delete button on Redirection's settings page to remove the plugin and delete all database tables. Then you can activate the plugin again and the error should go away.

Note this will remove any existing data. If you have anything you want to keep then you'll need to export it from the import/export page.

**Comment by marrow13** [comment]
Thanks, so, there is no another fix and the problem based only on server configurations?



20 октября 2017, 12:51:16, от "John" <notifications@github.com>:


It's the same problem as before so I guess version 2.8 didn't help. Basically your database is configured in some way that it's causing an error with Redirection.
The simplest solution will be to press the red delete button on Redirection's settings page to remove the plugin and delete all database tables. Then you can activate the plugin again and the error should go away.
Note this will remove any existing data. If you have anything you want to keep then you'll need to export it from the import/export page.

**Comment by johngodley** [comment]
If you have access to your database then you can run this SQL:

`ALTER TABLE `wp_redirection_items` CHANGE `last_access` `last_access` DATETIME  NOT NULL  DEFAULT '0000-00-00 00:00:00';`

You may need to change `wp_` to reflect your WordPress database prefix.

**Comment by marrow13** [comment]
Hi, thanks, it was really problem with DB, it's already fixed



20 октября 2017, 13:46:12, от "John" <notifications@github.com>:


If you have access to your database then you can run this SQL:
ALTER TABLEwp_redirection_itemsCHANGElast_accesslast_accessDATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
You may need to change wp_ to reflect your WordPress database prefix.
