### ISSUE TITLE
410 csv import doesn't works

### ISSUE THREAD

**Issue by cicciobimbo** [johngodley/redirection#446]
### Summary

I try to import a csv for a mass 410 redirection. I follow the template generated by plugin but when i try to import, plugin save all row as redirection type 0 instead of 410.

### Environment

Wordpress 4.8.2
Redirection plugin 2.7.3

**Comment by johngodley** [comment]
Can you add your CSV here?

**Comment by cicciobimbo** [comment]
Sure, tnx a lot for help.

Max

2017-10-14 15:26 GMT+02:00 John <notifications@github.com>:

**Comment by johngodley** [comment]
Hi, the file didn't make it. Can you upload directly through the website?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
