### ISSUE TITLE
How do I give Shop Manager access to redirection?

### ISSUE THREAD

**Issue by gmedhouse** [johngodley/redirection#448]
### Summary

The redirection tool is not available when the user type "Shop Manager" (woocommerce) is logged in.  How can I make it so they have access to this please?

**Comment by johngodley** [comment]
What is user type shop manager, and how do I reproduce the problem?

**Comment by gmedhouse** [comment]
Shop manager is a user type created with Woocommerce.
Really my question is can i modify the settings so i can choose which type
of user can use the redirection tool?

On 11/10/2017 7:35 PM, "John" <notifications@github.com> wrote:

What is user type shop manager, and how do I reproduce the problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/johngodley/redirection/issues/448#issuecomment-335697388>,
or mute the thread

**Comment by johngodley** [comment]
By default Redirection requires administrator permissions, but you can modify this here: https://github.com/johngodley/redirection#permissions

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
