### ISSUE TITLE
Redirect with querystrings

### ISSUE THREAD

**Issue by mmprojects2** [johngodley/redirection#450]
### Summary

I am trying to redirect old URL's with querystrings to new static pages which work fine until there are spaces in the querystring data.

### Actual Behavior

I am getting a 404 error
 
### Steps to reproduce

/oldpage?lnk=401&featureid=740&description=a description with spaces 

redirect to

/newpage/

produces a 404 error.

### Environment

Google Chrome 
Version 61.0.3163.100 (Official Build) (64-bit), Windows 10

**Comment by johngodley** [comment]
You need to URL encode the spaces:

`/oldpage?lnk=401&featureid=740&description=a%20description%20with%20spaces`

**Comment by mmprojects2** [comment]
Thanks John - will give that a try.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.

**Comment by mmprojects2** [comment]
The spaces encoding worked although other URLs with brackets causing the same problem. I assume these also need to be encoded?

**Comment by johngodley** [comment]
Yep, anything that's not an allowed URL character has to be encoded. You can use something like http://meyerweb.com/eric/tools/dencoder/ to encode things
