### ISSUE TITLE
Redirection works on computer but not on mobile

### ISSUE THREAD

**Issue by Haydee1** [johngodley/redirection#451]
Hi, 

Everything is said in the title.

My page https://1k1mois.com/rejoins-le-cours has a redirection on https://1k1mois.com/demandeinfo.

It works perfectly on my computer but doesn't redirect on mobile.

I get a "Page not found" on mobiles.

I use Chrome for both mobiles I tried.

I use de WorpPress version : 4.8.2

Can you please help ?

**Comment by johngodley** [comment]
https://1k1mois.com/rejoins-le-cours is a 404 - is that the correct URL?

**Comment by Haydee1** [comment]
OK !

Asking me this question John, I realised that it was my mistake !

I had putten my page in "Private" in Wordpress and I had putten the redirection. (on my side I could see the redirection because I was connected to my wordpress).

So I put it in "Public" and now it works on mobile.

Sorry to have disturb and thanks for your quick answer.
