### ISSUE TITLE
Doesn't work on HTTPS

### ISSUE THREAD

**Issue by apollollc** [johngodley/redirection#452]
Hey guys, have used this plugin for a long time, but now as I've began having SSL's on all my sites I've noticed the plugin doesnt redirect anymore unless they add the "https*" before the URL

So i can't just use example.com/newpage to redirect to something, it will just not go anywhere.

**Comment by apollollc** [comment]
Tried both relative(which is what I've always used) and absolute and still nothing for the non https version. Tried on Chrome and safari

apolloartistry.com/deck vs https://apolloartistry.com/deck

**Comment by ggg333111** [comment]
having the same problem and the above did not work either. Am redirecting from the home page / to a different website (which is not https) - am getting 404 error - worked fine before https....

**Comment by ggg333111** [comment]
just spoke to hosting and they said the plugin is not using mod-rewrite and didn'T place the redirect in -htaccess ?? - it worked fine before the SSL was installed.

**Comment by johngodley** [comment]
@apollollc that URL seems to work fine for me. Note the `location`:

curl -v -I https://apolloartistry.com/deck
*   Trying 45.79.128.56...
* TCP_NODELAY set
* Connected to apolloartistry.com (45.79.128.56) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=apolloartistry.com
*  start date: Jul 14 12:07:00 2017 GMT
*  expire date: Oct 12 12:07:00 2017 GMT
*  subjectAltName: host "apolloartistry.com" matched cert's "apolloartistry.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fd0a1806400)
> HEAD /deck HTTP/2
> Host: apolloartistry.com
> User-Agent: curl/7.54.0
> Accept: */*
< HTTP/2 301
< date: Thu, 12 Oct 2017 06:02:03 GMT
< content-type: text/html; charset=UTF-8
< location: https://apolloartistry.com/wp-content/uploads/2017/08/apollo-deck-3.pdf
< x-fw-hash: crn2b4ou3t
< server: Flywheel/4.1.0
< x-fw-serve: TRUE
< x-cache: MISS
< x-fw-static: NO
< x-fw-type: VISIT
```

Try clearing your browser cache.

@ggg333111 yes, but that doesn't mean anything. Also try clearing your browser cache.

**Comment by apollollc** [comment]
Crome, safari, cleared cache and incognito mode all don't work. Without the https it won't forward. We're talking about specifically redirects without the "https" before hand, which worked fine before SSL. Which now multiple people have reported. 

so "apolloartistry.com/deck", if I type that in as is into a browser... doesnt do anything. But if I add the https before hand then it works, but that isn't a thing people do.

**Comment by johngodley** [comment]
It works for me:

```
curl -v -I http://apolloartistry.com/deck                                                                                                                             master ✭ ✱
*   Trying 45.79.128.56...
* TCP_NODELAY set
* Connected to apolloartistry.com (45.79.128.56) port 80 (#0)
> HEAD /deck HTTP/1.1
> Host: apolloartistry.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 12 Oct 2017 06:09:40 GMT
< Content-Type: text/html
< Content-Length: 178
< Location: https://apolloartistry.com/deck
< X-FW-Hash: crn2b4ou3t
< Server: Flywheel/4.1.0
< X-FW-Serve: TRUE
< X-Cache: HIT
< X-Hits: 2
< X-FW-Static: NO
< X-FW-Type: VISIT
< Connection: keep-alive
```

It forwards from the http to https, and then to the PDF.

If you are not seeing this then your connection is probably cached at some point, maybe by your ISP.

**Comment by apollollc** [comment]
Interesting, how bizarre, great point though, definitely could be ISP cache, will look into this

**Comment by ggg333111** [comment]
mine is working now - didn't do anything, but it may have been the propagation period after they installed the SSL and dedicated IP. Let's hope that's all it is. Will redirection work regardless of what source url people put in? http or https? - I just put in / - thanks!

**Comment by johngodley** [comment]
@ggg333111 the plugin doesn't look at the http/https value so as long as you have things setup so http and https go to the same site then it should work fine.

**Comment by ggg333111** [comment]
actually, just tried on another device and same problem again. Instead of redirecting to the target url, it's redirecting to a combined url of:

http://sourceurl.com/http/:targeturl.com

any thoughts? - thanks!

**Comment by johngodley** [comment]
@ggg333111 as described above it is likely a caching thing. If you list the actual source URL I can check.

**Comment by ggg333111** [comment]
dreamclientsonautopilot.com

**Comment by johngodley** [comment]
You have some mod_security setting that is blocking access from anything other than a browser.

The target of `http/:SassyZenGirl.com/Dream-Clients/` looks like a typo - it should be `http://sassyzengirl.com`

**Comment by ggg333111** [comment]
I never changed any settings - it worked fine until yesterday - and no, it's not a typo, that's exactly what came out

**Comment by ggg333111** [comment]
of course, I set it up with double // - but the plugin changes it to the above and combines it with the source url. Like I said, I changed absolutely nothing, I have no special settings. All that was changed is that a SSL certificate was installed that created a dedicated IP for all involved domains.

**Comment by johngodley** [comment]
I don't know how it worked yesterday, all I know is how it's working today and the target URL is incorrect. There is nothing in Redirection that changes URLs.

Can you show a screenshot of the URL inside Redirection?

**Comment by ggg333111** [comment]
![screen shot 2017-10-12 at 11 38 08](https://user-images.githubusercontent.com/32720798/31489742-fc5accd4-af41-11e7-8f3c-d5777a1b1e34.png)

**Comment by johngodley** [comment]
Ok, you have it incorrect as `http//:` and it should be `http://`

**Comment by ggg333111** [comment]
changed it - but still same result.

**Comment by johngodley** [comment]
Please can you clear your browser cache as well, it is working for me now.

**Comment by ggg333111** [comment]
seems to work now - thanks very much!!

**Comment by ggg333111** [comment]
can you please delete my urls above? thanks!

**Comment by johngodley** [comment]
delete

**Comment by ggg333111** [comment]
in your message above
