### ISSUE TITLE
Add multisite support

### ISSUE THREAD

**Issue by carloscaro** [johngodley/redirection#455]
```
Versions: Plugin 2.7.1, WordPress 4.8.2, PHP 5.6.30
Nonce: 6fa477ad3c

Action: red_set_group
Params: {"orderBy":"id","selected":[],"filterBy":"","filter":"","id":0,"name":"Soporte","moduleId":1}
Code: 200 OK
Error: Invalid group or parameters (135)
Raw: {"error":"Invalid group or parameters (135)"}
```

**Comment by carloscaro** [comment]
We have installed this plugin under WordPress multisite environment. For the main domain works great, but not on subdirectory multisite network.

**Comment by johngodley** [comment]
Can you use the latest version of the plugin and try again?

**Comment by carloscaro** [comment]
I did and got this new error when creating a group: 
"Error: Invalid group or parameters (165): Table 'wp_2_redirection_groups' doesn't exist"

Tables are not created for multisite. Question: "If each table for a multisite it's created manually based on original schema, will it solve the problem?"

**Comment by johngodley** [comment]
I don't know what happens on a multisite - you can try it and see.

Also, if you go to the support page there is a new feature to identify and fix problems. It's worth giving this a try and see if there are any extra error messages.

**Comment by carloscaro** [comment]
I created all tables from scratch. All plugin options like Redirects, Groups, Log, 404s, Import/Export and Options started to work from the sub-directory multisite, however, when we create a redirect, it appends the Target URL to the actual URL. 

For example, let's say we have this sub-directory multisite: `https://www.example.com/es/` ... then, we create a redirection from here `https://www.example.com/es/` to `https://help.example.com/` ... this will be the result: **https://www.example.com/eshttps://help.example.com/.**

**Comment by carloscaro** [comment]
John, do you have any ideas how could we solve this problem? Thanks!

**Comment by johngodley** [comment]
Sorry I don't.  I will rename this as a feature request for multisite support
