### ISSUE TITLE
Don't know how to redirect a domain

### ISSUE THREAD

**Issue by seosg** [johngodley/redirection#456]
Hi! Sorry I'm kinda noob. I don't know exactly how to use the plugin. I want to redirect an entire domain to another one. How can I do that? Please anyone explain me
Thanks

**Comment by johngodley** [comment]
You can, but if that's all you want to do then you'd be better using Apache or Nginx to redirect your old domain to the new domain.

**Comment by johngodley** [comment]
Closing for now, please reopen if there's more you need to ask.
