### ISSUE TITLE
Conditional redirection for existing URL?

### ISSUE THREAD

**Issue by JnLlnd** [johngodley/redirection#460]
Hi John,

For an URL to an existing file, is it possible to redirect to another file only for requests from a given referrer? The URL would be still available for request from other referrers?

Thanks for this great plugin 👍

**Comment by johngodley** [comment]
You can use the 'URL and referrer' match option to redirect based on referrer (click the cog icon when creating/editing a redirect to see more redirect options).

Note that if the URL you want to redirect already exists then your web server may be configured to serve the file directly, without running WordPress. If this is the case then Redirection won't have chance to run. You will either need to reconfigure your server to pass everything through WordPress, or you will need to use Redirection to save the redirect to a .htaccess/rewrite.rules file.

**Comment by JnLlnd** [comment]
Thank you John for this quick and complete answer.

Jean
