### ISSUE TITLE
Apache redirect not writing to .htacces

### ISSUE THREAD

**Issue by CharlesGodwin** [johngodley/redirection#461]
### Summary
I set up a redirect using the Apache redirect but it doesn't write to .htaccess file.

### Actual Behavior

I define a redirect using a group in the Apache module and it doesn't seem to work.

### Steps to reproduce

1 - create a group in the apache Module
2 - add a redirect entry. In my case it as /membersonly/filename.php redirect to /my-account/ but it doesn't redirect.
3 I looked at the .htaccess file in my public_html directory and it is not changed.

### Environment
Redirect Version 2.7.3
PHP 7.0.2
WP  4.8.2
Various browsers.

**Comment by johngodley** [comment]
Have you set the path to the .htaccess file on the settings page?

Does your web server have write permission to the file? If not you'll need to give it permission to update the file.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
