### ISSUE TITLE
Redirect part of url - www.kunstinkaart.nl/de/... to www.kunstinkaart.nl/...

### ISSUE THREAD

**Issue by fcujorick** [johngodley/redirection#463]
Hi Guys, 

After using Gtranslate plugin for a while it has broken my url links so I deleted the plugin. 
Google, unfortunately, still indexing these sub pages with the translate url part in it. 

Like: www.kunstinkaart.nl/nl/product/bunnik-spring-city-map/
Has to be: www.kunstinkaart.nl/product/bunnik-spring-city-map/

Right now you will come on a 404, which I redirect to the homepage, but that's not the best idea..

Is there a way to redirect / delete these /sub/ url parts?

**Comment by mustafauysal** [comment]
Hi @fcujorick,

You could add redirection rule by using regex, something like:
<img width="815" alt="screen shot 2017-10-18 at 16 10 39" src="https://user-images.githubusercontent.com/1421387/31720331-f59dbf3c-b41e-11e7-94e2-9d18a9499a23.png">

**Comment by fcujorick** [comment]
Great, thank you!
