### ISSUE TITLE
Problem starting Redirection 2.7.3

### ISSUE THREAD

**Issue by yenyrubiano** [johngodley/redirection#464]
```

```

Plugin: 2.7.3
WordPress: 4.8.2
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by johngodley** [comment]
Can you try version 2.8 and see if there is any other information?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
