### ISSUE TITLE
Problem with associated redirect

### ISSUE THREAD

**Issue by mustafauysal** [johngodley/redirection#465]
### Summary

Hello @johngodley ,

I've left the comment before but you may not have seen yet. (#291)
Anyway,  associated redirect generates prefixed url something like `/amp/example-post/` instead of `/example-post/amp/`

### Actual Behavior

<img width="557" alt="screen shot 2017-10-18 at 16 28 35" src="https://user-images.githubusercontent.com/1421387/31721225-7af5c25e-b421-11e7-8092-9990d187528d.png">

### Steps to reproduce

* Enable monitoring post changes on plugin and associated redirection feature (use '/amp')
* Create a new post named as `foo`
* Update post slug with `bar`
* And check the redirection rules. 

### Environment

WordPress: 4.8.2
Redirection: 2.8

**Comment by johngodley** [comment]
Huh, I totally didn't think that through fully - thanks!

Fixed in bdf6f127b2fbde003bbb3c303cf373a9f351070b
