### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by damian1231** [johngodley/redirection#466]
```
Plugin: 2.8
WordPress: 4.8.2
PHP: 7.0.24
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (undefined)
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"url":"/home/join-n7/","title":"","regex":false,"match_type":"url","action_type":"url","group_id":1,"action_code":301,"action_data":"n7gaming.co.uk/forums/index.php?sid=48ba26dcfa77fdc7fcb08a6c4d7f6c19"}
Code: 404 Not Found
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /register/logout was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

```

Literally was fine until new update came today

**Comment by johngodley** [comment]
Does that happen all the time? Any idea why it is trying to access /register/logout? It should be trying to access /wp-admin/admin-ajax.php

**Comment by damian1231** [comment]
Yes everytime i try to access a redirect i have no idea..
When users press logout it takes them there it should be /home/register/logout any idea how to fix this?

**Comment by damian1231** [comment]
its working now but logout is still messed up any help?

**Comment by johngodley** [comment]
Messed up how? Do you have a redirect for it?

**Comment by damian1231** [comment]
no just when they click logout 
it takes them to /register/logout
should be home/register/logout?

**Comment by johngodley** [comment]
Can you paste the link here?

**Comment by damian1231** [comment]
www.n7gaming.co.uk/home

**Comment by damian1231** [comment]
let me readd the login and log out widgit as ive removed cos of this

**Comment by damian1231** [comment]
the register button dosnt even work on it wtf

**Comment by johngodley** [comment]
I see the login widget, and I can also see that the URLs are kinda wonky:

http://n7gaming.co.uk/home/index.php//?mode=login
http://n7gaming.co.uk/home/index.php//?mode=register

Neither http://n7gaming.co.uk/home/register/logout or http://n7gaming.co.uk/register/logout exist.

I'm not really sure what I'm looking for. Can you paste the full URL of the logout link?

Where is the register link supposed to go?

**Comment by damian1231** [comment]
the register link is supposed to register on the forums
why does WP Not just redirect back to home page after logging out?

**Comment by johngodley** [comment]
Ok, your registration link is supposed to go to http://n7gaming.co.uk/forums/ucp.php?mode=register and the login link to http://n7gaming.co.uk/forums/ucp.php?mode=login

Your widget is not showing the correct links.

I don't think this is related to Redirection.

**Comment by damian1231** [comment]
no this bit is not i was just asking if i could use redirect to redirect where they send it too?

**Comment by johngodley** [comment]
Probably, but it depends on how your server is setup. Try creating a redirect:

Source: `/home/index.php//?mode=login`
Target: `/forums/ucp.php?mode=register`

**Comment by damian1231** [comment]
ok now i cannot login to admin area :/ it redirects me to http://n7gaming.co.uk/register/logout?redirect=http%3A%2F%2Fn7gaming.co.uk%2Fhome%2Fwp-login.php%3Fredirect_to%3Dhttp%253A%252F%252Fn7gaming.co.uk%252Fhome%252Fwp-admin%252F%26reauth%3D1 

when i try login ?

**Comment by damian1231** [comment]
ok so now its broke :<

**Comment by johngodley** [comment]
I don't know how you've got your site setup or what is supposed to happen.

Does this have anything to do with Redirection? If it does then I would suggest disabling the plugin to get your site back to how it was.

If it doesn't then you should head over to the forums on wordpress.org for general help.

**Comment by johngodley** [comment]
Closing this for now but please reopen if you have more details about a problem with Redirection.
