### ISSUE TITLE
Redirection dashboard opens at the bottom of the page

### ISSUE THREAD

**Issue by ShoreBudMike** [johngodley/redirection#468]
Following the latest Redirection update, when selecting it from the WordPress menu, Redirection opens at the bottom of the Redirections page, with the cursor already in the Source URL field under "Add new redirection."

Due to this, the Redirection menu at the top of the page is not visible, and I have to manually scroll to the top of the page, because my computer's Page Up and Home buttons do not work, because the cursor has been automatically placed in a text field.

A similar issue occurred following an update several months ago: while Redirection opened at the top of the page, as expected, when selecting 404s from the menu and browsing the 404 logs, upon clicking the next page button, each subsequent page opens at the bottom instead of at the top. This issue still exists.

My site is using Redirection 2.8 under WordPress 4.8.2, and I am using Firefox 56.0.

Thank you for looking into this. I appreciate the work you've put into Redirection!

**Comment by johngodley** [comment]
Yeah, that was annoying! Fixed in 371206ae4c711a62403792b37343c6b5673ad74f, will be released in 2.8.1
