### ISSUE TITLE
Cannot edit WP redirections of type 404

### ISSUE THREAD

**Issue by ErinPo** [johngodley/redirection#469]
Delete and disable work fine, but trying to edit any redirection of type 404 throws an error.

Error message: 

`Something went wrong
Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.`

I am not using any cache though.

Plugin: 2.8
WordPress: 4.8.2
PHP: 7.0.24
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38

**Comment by johngodley** [comment]
Fixed in https://github.com/johngodley/redirection/commit/a13bf83b62dd59634ce5ac8c331b9fea2b44e551 and will be released in 2.8.1
