### ISSUE TITLE
Redirect log changes

### ISSUE THREAD

**Issue by JuliusGetzMork** [johngodley/redirection#47]
First of all, thank you for making it a bit easier to replace an old website.

I have however some suggestions that, in my opinion, would make Redirection a lot more effective.
1. Add option to combine identical URLs in the 404s tab, and let me match all occurances in one operation.
2. In addition, add option to delete URL from log once redirected.
3. When clicking the "Add redirect" link, move focus and view to the Target URL input box.

If this was implemented it would make replacing a site hell of a lot easier! :)

**Comment by johngodley** [comment]
I know this is a couple of years old but 2 & 3 are added in #288 !

1 is being looked at in #36
