### ISSUE TITLE
Redirection Error 403

### ISSUE THREAD

**Issue by etech0** [johngodley/redirection#470]
Hi! I'm getting the following error when trying to add a new redirection. Any advice?

```
Plugin: 2.8
WordPress: 4.8.2
PHP: 5.3.24
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Error: Unexpected token < in JSON at position 0 (undefined)
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"url":"/fm","title":"","regex":false,"match_type":"url","action_type":"url","group_id":1,"action_code":301,"action_data":"http://52.58.59.209/fmi/webd"}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-admin/admin-ajax.php
on this server.</p>
</body></html>


Error: Unexpected token < in JSON at position 0 (undefined)
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":28,"url":"/fm","title":"","regex":false,"match_type":"url","action_type":"url","position":20,"group_id":1,"action_code":301,"action_data":"http://52.58.59.209/fmi/webd"}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-admin/admin-ajax.php
on this server.</p>
</body></html>

```

Thanks for a great plugin!

**Comment by johngodley** [comment]
The error is: `403 Forbidden You don't have permission to access /wp-admin/admin-ajax.php`

Is there a reason your server would forbid access to that URL? Are you running some kind of firewall or protection software like Wordfence?

**Comment by etech0** [comment]
I don't know why it wouldn't work - I don't have wordfence (and don't know what it is :) ). I have lots of other redirects that work.

**Comment by etech0** [comment]
Could it be because this redirection is trying to redirect to an ip address instead of a regular website?

**Comment by johngodley** [comment]
> Could it be because this redirection is trying to redirect to an ip address instead of a regular website?

It's possible, but I don't know what is blocking the request so can't say for sure.

You could try changing the target and see if it works. If it is the IP causing the block then you'll need to contact your host provider and see if they are running any software that might be blocking the request

**Comment by etech0** [comment]
Changing the target works. I'll contact my host - what should I ask them? If they have a software that blocks  redirects?

**Comment by etech0** [comment]
Okay will do - thanks for your help!

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
