### ISSUE TITLE
Problem starting Redirection 2.8

### ISSUE THREAD

**Issue by consultoravento** [johngodley/redirection#471]
```
Uncaught ReferenceError: jQuery is not defined http://wsecuritysolutions.cl/wp-admin/load-scripts.php?c=1&load%5B%5D=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-dragg&load%5B%5D=able,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,jquery-ui-position,wp-pointer&ver=4.8.2 2
```

Plugin: 2.8
WordPress: 4.8.2
PHP: 5.6.31
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by LordLibidan** [comment]
I have the same issue.

Uncaught ReferenceError: jQuery is not defined http://wsecuritysolutions.cl/wp-admin/load-scripts.php?c=1&load%5B%5D=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-dragg&load%5B%5D=able,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,jquery-ui-position,wp-pointer&ver=4.8.2 2

Plugin: 2.8
WordPress: 4.8.2
PHP: 7.1.7
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0
Buster: 2.8 === 2.8

**Comment by johngodley** [comment]
Does http://wsecuritysolutions.cl mean anything to either of you? When I go to that URL it redirects to a scam website containing malware.

I don't want to raise an alarm but I would check your site and plugins for malware. The `wsecuritysolutions.cl/wp-admin/load-scripts.php` file referenced above contains bad code and you should stop using it immediately.

If you don't know anything about the file then I would suggest disabling all your plugins and see if it goes away. Then you can enable your plugins individually until the problem occurs. If you find the plugin causing the problem please post its name here.

**Comment by johngodley** [comment]
Ok, then @consultoravento you definitely need to clean your site as it's been infected! See [this](https://www.hackjungle.com/news/caution-var-0xaae8-wordpress-virus-spreading-attacking-the-jqueryjs-2017) for more details

@LordLibidan the CSS messages can be ignored -  it looks like warnings from WP and other plugins. I'd still suggest disabling other plugins to see if the problem goes away. This error is usually caused by a conflict somewhere.

**Comment by LordLibidan** [comment]
Thanks @johngodley 
I checked my plugins and it appears it was "404page" plugin. I disabled and re-enabled and its working again.

**Comment by johngodley** [comment]
Great, thanks for letting me know. I'll take a look and see if there's anything I can to prevent that plugin conflicting.
