### ISSUE TITLE
Redirect not working unless logged in

### ISSUE THREAD

**Issue by bradley2083** [johngodley/redirection#472]
We are seeing inconsistencies with a redirect for a page within our site.  

To replicate, visit https://authorcats.com/pricing - this should redirect you to https://authorcats.com.  In some cases it does.  However, if you go to our 404 page for example (https://authorcats.com/asdfsda) and then click the "lifetime special" link in the header (which links to https://authorcats.com/pricing), you'll likely be taken to https://authorcats.com/pricing (which is incorrect - you should be redirected to https://authorcats.com based on the redirect we have setup). 

We are on 4.8.2 of WP and 2.8 of the Redirection plugin. 

See screenshot of our redirect setup. 

Thank you!
Brad
<img width="620" alt="screen shot 2017-10-20 at 9 50 57 am" src="https://user-images.githubusercontent.com/1781226/31826999-48cc49d6-b57c-11e7-9609-993e89d017ba.png">

**Comment by johngodley** [comment]
Redirection only looks at the URL being visited - it doesn't look at where the user was before, and it's not possible for it to be inconsistent in that way.

If you look at the link on the 404 page it is actually to https://authorcats.com/pricing/ (with a trailing slash). This is not the same as the one you have in Redirection. It seems that page does exist and so it is served.

**Comment by bradley2083** [comment]
Perfect!  Added an additional redirect with a trailing slash and all is working well.  Thanks for the quick reply!
