### ISSUE TITLE
I have several images with error 404, how do I add a redirect massively?

### ISSUE THREAD

**Issue by dtchodjuklian** [johngodley/redirection#475]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Sorry for taking so long to reply. I'm not sure exactly what you mean, but you can use a regular expression to match multiple targets. Does that help?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
