### ISSUE TITLE
Feature request: Ifelse handlers for redirection

### ISSUE THREAD

**Issue by haneef95** [johngodley/redirection#478]
Advanced option to only apply redirection rule if a certain condition is met.

For e.g.:
```
If(currentstate=404_page_not_found && sourceurl="/^abc$"){
targeturl="/def"
}

```
This way website owners can implement some kind of AI into the redirection process.

**Comment by johngodley** [comment]
There's already a system for conditional redirects - you can redirect based on a user agent, referrer, or login status. I'm not sure I understand why you'd redirect only if its a 404 though - would the page ever change status? A simple redirect would seem to be better.

**Comment by haneef95** [comment]
Right now, I can think of two benefits from having this feature
## 1. Avoid redirect loops
You see, once [this feature](https://github.com/johngodley/redirection/issues/476) is added, it might cause redirect loops, even with the example that I've mentioned in there.
```
Source URL: ^/%post_id%/(.*)
Target URL: /%post_id%/%category%/%postname%
```
In the above example, the target URL will still match the condition of the source URL, therefore, it would cause a redirect loop. But, if I'm able to add a condition that the redirection is triggered based on source URL and if the source URL currently returns a 404, then, even if the target URL matches, it won't cause a redirect loop.

## 2. Enhance WP's [redirect_guess_404_permalink](https://codex.wordpress.org/Function_Reference/redirect_guess_404_permalink) function
This function only servers some types of 404 errors, and redirects with strict 301, it should rather be a 302, as it is a guess.

This WP function also comes with its errors. For e.g.: https://techcrunch.com/anythinghere/snapchat redirects to https://techcrunch.com/topic/company/snapchat/ and this an unintended consequence, even the term 'snapchat' is ambiguous.
Same with this: https://techcrunch.com/anythinghere/why-snapchat-spectacles

If the [above suggested feature](https://github.com/johngodley/redirection/issues/478#issue-268021128) is added to your plugin, we can disable WP's function and rewrite the function to our desires.

**Comment by johngodley** [comment]
I'm still not sure I fully understand. Where are the conditions added?

Regarding the permalinks that may not become part of the plugin.

**Comment by haneef95** [comment]
> 1. Avoid redirect loops
> 2. Enhance WP's redirect_guess_404_permalink function

The above two I've mentioned are benefits of implementing this feature, not actual features itself.

So, essentially what I'm asking for is:
![2017-10-30 10_18_31-redirection wordpress](https://user-images.githubusercontent.com/298208/32165805-e6031ee6-bd5b-11e7-850d-362d28d44c90.png)
![2017-10-30 10_23_01-redirection wordpress edited](https://user-images.githubusercontent.com/298208/32166221-0d074fb6-bd5d-11e7-9277-6dbbd701a06a.png)


This way, I can make it a condition that the redirection is only triggered when a HTTP status is matched, for example 404.

**Comment by johngodley** [comment]
Noting that 'URL and WordPress page type` matches this request.
