### ISSUE TITLE
301 redirects to .pdf files are redirecting to home page, not the proper file

### ISSUE THREAD

**Issue by iamtheneonguy** [johngodley/redirection#480]
### Summary

I am trying to create short a URL that 301 redirects visitors to PDF in my Wordpress media library that has the longer Wordpress media URL.

Desired Redirect URL Format: http://www.mywebsite.com/mypdf
Shortened URL Format Used in Plugin: /mypdf
Destination File URL Format: http://www.mywebsite.com/wp-content/uploads/2017/10/my-pdf-form.pdf

### Actual Behavior

In Firefox and Internet Explorer, visitors are redirected to the homepage, not the PDF file in all URL formats: Beginning with "http://www.", no "http://www." or just "www.".

In Chrome, visitors are directed to the proper file if beginning their URL with "http://www." and "www.", but are redirected to the homepage if the URL contains no no "http://www.".

are redirected to the homepage, not the PDF file in all URL formats:

### Steps to reproduce

Typing the following URL format in Chrome redirects visitors to the PDF file:
http://www.mywebsite.com/mypdf
www.mywebsite.com/mypdf

Typing the following URL format in Chrome redirects visitors to the site's homepage, not the PDF:
mywebsite.com/mypdf

Typing the following URL in any format in Firefox and Internet Explorer redirects visitors to the site's homepage, not the PDF:
http://www.mywebsite.com/mypdf
www.mywebsite.com/mypdf
mywebsite.com/mypdf

### Environment

I'm using Redirection version 2.8.1 and Wordpress version 4.8.2.

**Comment by johngodley** [comment]
Are those real URLs? If not, can you provide real URLs?

**Comment by iamtheneonguy** [comment]
It looks like the issue is also happening on redirects to other websites as well, not just the PDF in questions. 

Here is a 301 redirect you can test.

http://www.redautocompanies.com/redshield should redirect to http://www.redshieldds.com

When I click the "/redshield" link in Redirection's list of redirects in Wordpress (which indicates the link is "http://www.redautocompanies.com/redshield"), the redirect works and registers a hit. It also works when I'm pasting it into Chrome (the browser I'm logged into Wordpress with).

However, pasting the link into Firefox or Internet Explorer takes you to the site's homepage and doesn't register a hit in the plugin.

**Comment by johngodley** [comment]
There should be no difference between browsers. It's possible your browser may have cached something, so you could try clearing your browser cache in the browser where it's not working.

The URL you provide is returning a 302 for me and seems like something else may be caching things.

Can you also try updating to the latest version of the plugin?

**Comment by iamtheneonguy** [comment]
Not sure why it is showing as a 302. I didn't set it up that way (see screenshot). I'm already using version 2.8.1 and there is no update option for anything higher. I also cleared the cache previously in all three browsers. The link still forwarded to the proper redirect in Chrome, but redirects to the home page instead of the intended redirect in IE and Firefox.

![capture](https://user-images.githubusercontent.com/33073828/32020549-66ccbb7a-b985-11e7-8bb3-70e0e25d1c91.PNG)

**Comment by johngodley** [comment]
Sorry, I somehow read the version as 2.7.1

I don't think Redirection is providing the redirect. This is what your server is returning:

```
curl -v -I http://www.redautocompanies.com/redshield                                                                                                                  
*   Trying 198.71.233.135...
* TCP_NODELAY set
* Connected to www.redautocompanies.com (198.71.233.135) port 80 (#0)
> HEAD /redshield HTTP/1.1
> Host: www.redautocompanies.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 302 Found
< Content-Type: text/html; charset=UTF-8
< X-Port: port_10405
X-Port: port_10405
< X-Cacheable: YES:Forced
< Location: http://www.redautocompanies.com/
< Date: Wed, 25 Oct 2017 19:59:49 GMT
< Age: 6055
< Vary: User-Agent
< X-Cache: cached
< X-Cache-Hit: HIT
< X-Backend: all_requests
```

Redirection will add it's own header in there, but it isn't present and so it means that Redirection is not doing this redirect. Also it's a 302 and you have it configured as 301, and the `Location` here is http://www.redautocompanies.com/ not http://www.redshieldds.com

Notice all the `x-cache` things too? That suggests to me you are using some caching software (maybe in WordPress or on your server), and it may be doing the redirect before Redirection has a chance to run.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
