### ISSUE TITLE
Admin page error

### ISSUE THREAD

**Issue by krafthandmedien** [johngodley/redirection#481]
Hello,

when i try opening the admin page for Redirection. I get the follwing error message:

![redirection_error](https://user-images.githubusercontent.com/33082724/31988603-f8754116-b96f-11e7-8bef-9a74daf8cb46.png)

### Actual Behavior

Display the plugin settings screen.

### Steps to reproduce

Go to the plugin settings page. ( /wp-admin/tools.php?page=redirection.php )

### Environment

Plugin: 2.8.1
WordPress: 4.8.2
PHP: 7.0.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Buster: 2.8.1 === 2.8.1
TypeError: t[0] is undefined

**Comment by johngodley** [comment]
Can you disable all other plugins and see if the error goes away? If it does you can then re-enable plugins until the problem occurs again, and then you will have identified a conflict - please post the details here.

**Comment by krafthandmedien** [comment]
I had already disabled all other plugins, switched to default theme. And still doesn't fixed the error.

After checking the error log if found the solution, the required database tables doens't exists. I have no clue how they got deleted. Haven't changed anything on the site. Deactivating and activating didn't solve it, had to delete the plugin and reinstall.
