### ISSUE TITLE
Redirection: Issues after latest update

### ISSUE THREAD

**Issue by DuurzaamMedia** [johngodley/redirection#482]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

![screen shot 2017-10-25 at 10 47 15](https://user-images.githubusercontent.com/33085771/31989207-eac2792e-b971-11e7-8d90-f8dc624358da.png)

Error after update plugin. We use a wordpress multi site enviroment

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

Trying to use the redirection plugin

### Actual Behavior

We updated to your latest version some days ago.

### Steps to reproduce

Selecting the plugin will load the correct page but within a splitsecond is shows the error settings.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Plugin: 2.8.1
WordPress: 4.8.2
PHP: 5.6.31
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:56.0) Gecko/20100101 Firefox/56.0
Buster: 2.8.1 === 2.8.1
TypeError: t[0] is undefined

**Comment by johngodley** [comment]
Can you disable all other plugins and see if the error goes away? If it does you can then re-enable plugins until the problem occurs again, and then you will have identified a conflict - please post the details here.

**Comment by DuurzaamMedia** [comment]
We can't disable plugins as we have 600 website running on =our multi website. ;-( is there another way

Sincerely yours
Harvey Blom

**Comment by johngodley** [comment]
If you are comfortable using your browser's developer tools (in Chrome - View > Developer > Developer Tools, a similar exists in Firefox and Edge) you could load the page with that enabled and it should stop on the error and show you more context. You can then either paste that here, or a screenshot if you're not sure what to look for.

**Comment by krafthandmedien** [comment]
Can you please check if the following tables exists in your database? 
- wp_redirection_404
- wp_redirection_groups
- wp_redirection_items
- wp_redirection_logs

(Note: The prefix "wp_" might be different based on your configuration)

I had the same error, and these tables missed in my database. I fixed it resotring the tables from by backup.

**Comment by DuurzaamMedia** [comment]
Not sure what I am looking for ;-(

**Comment by johngodley** [comment]
Add `&sub=support` to the URL and see what the support page has to say.

**Comment by johngodley** [comment]
Please try version 2.9 which should notify you about the status of your database tables

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
