### ISSUE TITLE
is the symbol "|" disappears to load the web of the translator of google

### ISSUE THREAD

**Issue by hugoalva** [johngodley/redirection#483]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

Hello
I try to make a redirect to point to the translator of google but some of the elements that make up the url is the symbol "|" and when loading the web of the translator of google, this symbol disappears and for that google to tell that it can not translate the page .

### Actual Behavior
![sin titulo](https://user-images.githubusercontent.com/25032068/32012466-37eaf320-b9b8-11e7-992b-86580121df3d.png)

in attempting to code the symbol for "% 7C" but same goes away when loading the google translate web

### Steps to reproduce

http://test.youghalinternationalcollege.es/pt/

goto       

http://test.youghalinternationalcollege.es/support/#googtrans(es|it)

or

http://test.youghalinternationalcollege.es/it/

goto

http://translate.google.com/translate?client=tmpg&hl=es&u=http://test.youghalinternationalcollege.es/&langpair=es%7Cit
--

### Environment

all browser (Firefox, Chrome, edge) Windows 10, Wordpress 4.8.2; redirection 2.7.3

**Comment by johngodley** [comment]
The first URL doesn't work, the second one does. Can you clear your browser cache? It may have cached a broken redirect.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
