### ISSUE TITLE
Problem starting Redirection 2.8.1

### ISSUE THREAD

**Issue by anjrah2006** [johngodley/redirection#484]
cant started.
maybe crash with other plugin.
this is my plugin list:
<img width="880" alt="list plugin anjrahweb" src="https://user-images.githubusercontent.com/16219444/32086130-5170d774-bafd-11e7-9f5e-84c03220af39.png">

also, eror like this
<img width="1288" alt="ligshot eror" src="https://user-images.githubusercontent.com/16219444/32086102-31213f22-bafd-11e7-9881-1dd555c8d43d.png">

Plugin: 2.8.1
WordPress: 4.8.2
PHP: 7.1.10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by johngodley** [comment]
Hi,

Can you disable your plugins and then re-enable them one by one until you find the one causing the problem?

**Comment by anjrah2006** [comment]
okey, i' ll try it.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details. Also try version 2.9
