### ISSUE TITLE
Redirect not working when referral source gets added to the URL

### ISSUE THREAD

**Issue by dalelowry** [johngodley/redirection#485]
I'm seeing a lot of 404 errors for a redirect I already have in my redirects. The 404s happen when Facebook or Twitter add a "?referral=blahblahblah" or a "?refSource=blahblahblah" to the redirected address. 

For example, I have the address https://dalecameronlowry.com/myths-moons-mayhem-giveaway/ set to redirect to https://dalecameronlowry.com/books/myths-moons-mayhem/giveaway/. But "https://dalecameronlowry.com/myths-moons-mayhem-giveaway/?referral=B1m7iNLTb&refSource=twitter", produces a "Page not found." 

I'm using WordPress 4.8.2, the current Redirection plugin. and the current Chrome browser.

**Comment by johngodley** [comment]
Yes, the plugin exactly matches URLs unless you use a regular expression

**Comment by dalelowry** [comment]
Thanks. Are there any workarounds for this? Someone must be posting an old URL to FB and Twitter, and they automatically add the referral code. I'd love a way to get people to the right page.

Sorry if I'm missing something obvious. I'm not a developer.

**Comment by dalelowry** [comment]
Okay, nevermind. I wasn't familiar with regular expressions but just found a tutorial. Maybe an explanation or link to information about regular expressions in the support section of the plugin's admin dashboard would be a good addition. Thanks!
