### ISSUE TITLE
No AutoIncrement and Items ID = 0

### ISSUE THREAD

**Issue by acs-ferreira** [johngodley/redirection#487]
I don't know why, but all my items have a ID = 0, without AUTO INCREMENT and no PRIMARY KEY.

Is there a way to fix these? Is it normal that items can be saved without AUTO INCREMENT?

Of course, i can't apply this now with all values equal zero:
````
ALTER TABLE `wp_redirection_items` MODIFY COLUMN `id` int(11) unsigned NOT NULL AUTO_INCREMENT;
````

![image](https://user-images.githubusercontent.com/12234510/32100666-ebb730aa-bb14-11e7-8db6-3016452e51a5.png)

![image](https://user-images.githubusercontent.com/12234510/32100570-8b12b652-bb14-11e7-9270-02e9821a80b3.png)

v2.8.1 and WP 4.8.2

Thanks.

**Comment by johngodley** [comment]
No, it isn't normal, and it shouldn't be possible to do this through the plugin.

Can you copy the table creation syntax here? So `SHOW CREATE TABLE `wp_redirection_items`.

You'll have to fix it with something like described here:

https://stackoverflow.com/questions/5035836/how-to-add-auto-increment-to-an-existing-column

**Comment by johngodley** [comment]
Closing for now, please reopen with more details.
