### ISSUE TITLE
Problem starting Redirection 2.8.1

### ISSUE THREAD

**Issue by moffill** [johngodley/redirection#489]
```

```

Plugin: 2.8.1
WordPress: 4.8.2
PHP: 5.6.31
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38

**Comment by johngodley** [comment]
Are there any more details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details. Also try version 2.9
