### ISSUE TITLE
Redirection went wrong

### ISSUE THREAD

**Issue by YardenF** [johngodley/redirection#491]
### Summary

I tried to do a redirection:

 from this page:
http://reshet.tv/writer/survivor-villa/

to this page:
http://reshet.tv/tags/survivor-villa/

and I got an error message.

--------------------------------------------------------------------------------------------
Versions: Plugin 2.6.6, WordPress 4.8, PHP 7.0.8-0ubuntu0.16.04.3
Nonce: ca378fd501

Action: red_set_redirect
Params: {"orderBy":"id","selected":[],"filterBy":"","filter":"","id":0,"url":"/writer/survivor-villa/","title":"","regex":false,"match_type":"url","action_type":"url","group_id":5,"action_code":301,"action_data":"http://reshet.tv/tags/survivor-villa/"}
Code: 200 OK
Error: Unable to perform action - bad nonce "wp_rest" (31)
Raw: {"error":"Unable to perform action - bad nonce \"wp_rest\" (31)"}

**Comment by johngodley** [comment]
Can you use the latest version of the plugin?

**Comment by YardenF** [comment]
I don't know. This is a big site and probably would be very complicated. 
Normally I am doing redirection the same way and not having any difficulties. 
Is there any other way that I can try solve it?

**Comment by YardenF** [comment]
Hello again,
I tried once again to redirect and now it's working!
Anyway, we will check the update of the plugin.
Thank you!

**Comment by johngodley** [comment]
Ok great it's working. I can only provide support for the latest version of the plugin.
