### ISSUE TITLE
Redirection logs empty. Redirection with regex confirmed working. WP 4.8.2 all wp_redirection tables in database. No server errors. Any ideas?

### ISSUE THREAD

**Issue by m-miller** [johngodley/redirection#493]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Can you copy/paste a working redirected URL here?

**Comment by m-miller** [comment]
https://granicus.com/blog/blog/4-signs-account-need-checkup/

https://granicus.com/blog/blog/summit-recap-4-steps-better-citizen-engagement/

**Comment by m-miller** [comment]
​

**Comment by johngodley** [comment]
Ok, those URLs are not being redirected with Redirection - something else is performing the redirect instead. To confirm if you disable Redirection then the URLs should still redirect.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
