### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by gamejump** [johngodley/redirection#494]
### Summary

not going through the plugin page

### Actual Behavior

Something went wrong 🙁

Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

### Steps to reproduce

When i am going to the plugin page getting this error

### Environment

Plugin: 2.8.1
WordPress: 4.8.2
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Buster: 2.8.1 === 2.8.1
TypeError: Cannot read property 'id' of undefined

**Comment by johngodley** [comment]
Can you provide some context?

**Comment by gamejump** [comment]
@johngodley well i activated the plugin and facing this error

![ss 2017-10-31 at 12 41 38](https://user-images.githubusercontent.com/24908945/32211526-ea536a36-be38-11e7-8ad8-6d92115bf184.png)

**Comment by johngodley** [comment]
Ok. Can you open your browser's error console and see if any errors are shown?

Can you try adding `&sub=support` to the URL and see if the support page appears and if it shows you any issues?

**Comment by gamejump** [comment]
@johngodley &sub=support works great

there is problem with Valid groups with the magic fixed it get fixed

thank you :+1:
