### ISSUE TITLE
Please Help, Error 404 Not Found

### ISSUE THREAD

**Issue by lythien** [johngodley/redirection#495]
Plugin: 2.8.1
WordPress: 4.8.2
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Error: Unexpected token < in JSON at position 0 (undefined)
Action: red_get_group
Params: {"filterBy":"","filter":""}
Code: 404 Not Found

**Comment by johngodley** [comment]
Redirection is trying to access `wp-admin/admin-ajax.php` on your site but your server is returning a 404. Does the file exist? Do you have a security/firewall plugin running that may be blocking the request?

**Comment by lythien** [comment]
Hi johngodley,
I have use plugin iThemes Security ,  error is it ? I try Deactivate Plugin, but the error still exists.

And Wp-admin/admin-ajax.php does not exist on my website. Please help !

**Comment by johngodley** [comment]
`wp-admin/admin-ajax.php` is a core part of WordPress and it should exist where you have WordPress installed. Without this many things will not work.

**Comment by lythien** [comment]
I have update admin-ajax.php from wordpress.org to host, but the error still exists. 
I've been using Plugin Redirection for 3 years, but today it's this error.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
