### ISSUE TITLE
New redirect at the end of the list.

### ISSUE THREAD

**Issue by Narga** [johngodley/redirection#497]
In the old version of redirection, the newest redirect items appeared at the end of the list, so it's convenient for me to copied the pasted. But in recent version, it goes on top so I need to scroll up to find them.
Do I miss the configuration or it's need to fix?
Thanks

**Comment by johngodley** [comment]
The way it's working now is the correct way. The items are ordered by date, and adding to the end of the list doesn't make any sense as it's not correct by date, or even position within the pages.

Why do you need to scroll up to find them? What are you copy/pasting?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
