### ISSUE TITLE
Feature Suggestion: Add support to redirect based on Accept-language

### ISSUE THREAD

**Issue by salam** [johngodley/redirection#499]
It would be great if one can select an option to have redirections based on the "Accept-language" header. It is not enough to filter with the user-agent string and look for .* en-.* for instance since not many browsers include the language in the user-agent.

**Comment by johngodley** [comment]
That's a good idea, I like it.

**Comment by johngodley** [comment]
Added in #728 via the 'HTTP header' match. Will be released in 3.2
