### ISSUE TITLE
Log rotation not 'working'

### ISSUE THREAD

**Issue by Beee4life** [johngodley/redirection#500]
### Summary
Log rotation is ignored. My setting is to keep 404 logs for one day but the logs don't get flushed after a day. I just checked and it has entries dating back 7 days.

This is my setting.
<img width="492" alt="screen shot 2017-11-01 at 17 49 44" src="https://user-images.githubusercontent.com/4508731/32286351-7b269df4-bf2d-11e7-8fcc-f91ed9bc5dc3.png">

This is a screenshot of the log pages taken a few minutes ago.

![171101-404-logs](https://user-images.githubusercontent.com/4508731/32286392-9d78646e-bf2d-11e7-91f0-c38bc7fd3098.jpg)

### Environment
Browser: Chrome (62.0.3202.75)
WP: 4.8.3
Redirection: 2.7.3

**Comment by johngodley** [comment]
Does WordPress cron work on your site? That is needed for the log rotation to work.

**Comment by Beee4life** [comment]
Yes.... all other cron actions (such as membership expiration etc) work.

**Comment by Beee4life** [comment]
sorry I was wrong. Cron appears to not be working. So I'll close this until it's fixed.
