### ISSUE TITLE
Original HTTP_USER_AGENT Removed in Pass-through Mode

### ISSUE THREAD

**Issue by kenyowu** [johngodley/redirection#501]
### Summary

Original HTTP_USER_AGENT is removed in pass-through mode

### Actual Behavior

Original HTTP_USER_AGENT is replaced by something like
WordPress/[WP_VERSION]; https://[DOMAIN_NAME]

### Steps to reproduce

Simply setup a pass-through direction and 
use $_SERVER['HTTP_USER_AGENT'] in php to find out

### Environment

WordPress 4.8.3
Redirection plugin Version 2.8.1

**Comment by johngodley** [comment]
Yes, if you use a pass through and have a remote URL as the target then WordPress will make a request to that URL.

**Comment by johngodley** [comment]
Closing this as expected behaviour
