### ISSUE TITLE
Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

### ISSUE THREAD

**Issue by Larsen-Jeanette** [johngodley/redirection#504]
Something went wrong 🙁

Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.
If that doesn't help, open your browser's error console and create a new issue with the details.
Please mention redirect, and explain what you were doing at the time

Plugin: 2.8.1
WordPress: 4.8.3
PHP: 5.5.38
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
Buster: 2.8.1 === 2.8.1
TypeError: Cannot read property 'status' of undefined

**Comment by johngodley** [comment]
Can you try version 2.9?

**Comment by MattHoneycutt** [comment]
I'm seeing this, too, in version 2.9.1.

**Comment by johngodley** [comment]
Can you try version 2.10 and see what happens?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
