### ISSUE TITLE
Unable to add new redirections

### ISSUE THREAD

**Issue by RedSentence** [johngodley/redirection#505]
HI there. When trying to add a new direct I am getting the below error, any ideas on what might be causing the primary key to go back to 0?

Many thanks
Jason

```
Plugin: 2.8.1
WordPress: 4.8.1
PHP: 5.6.30-0+deb8u1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Error: Unable to add new redirect (205): Duplicate entry '0' for key 'PRIMARY'
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"url":"/home.htm","title":"","regex":false,"match_type":"url","action_type":"url","position":12,"group_id":3,"action_code":301,"action_data":"https://www....","perPage":200}
Code: 200 OK
Raw: {"error":{"message":"Unable to add new redirect","code":205,"wpdb":"Duplicate entry '0' for key 'PRIMARY'"}}
```

**Comment by johngodley** [comment]
Hmm, that's an unusual one. If you have access to the database could you possibly paste the results of this SQL statement:

`SHOW CREATE TABLE wp_redirection_items`

You may need to change the `wp_` prefix to whatever your system is using.

Also, does an entry exist in that table for id 0?

**Comment by RedSentence** [comment]
Hi John

 

Thanks for the reply – it seems deleting and resetting the redirection solved it.

 

Thanks

Jason
