### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS 

### ISSUE THREAD

**Issue by mrPeshi** [johngodley/redirection#508]
Hi John!
Thank you very much for your plugin!!!
I got an error when redirecting from the address in Cyrillic.
I checked it on a default WP Version : 4.8.3 installation with only one Redirection plugin.

Sours URL: /%D1%82%D0%B5%D1%81%D1%82
Target URL: /test
Result: ERR_TOO_MANY_REDIRECTS

<img width="1004" alt="2017-11-05 15 16 56" src="https://user-images.githubusercontent.com/18233208/32414629-6ea11886-c23c-11e7-91a7-9d50ce4f8130.png">

**Comment by johngodley** [comment]
Somehow the cyrillic word must be matching the /test target. You don't need the regex checkbox enabled there and disabling it will probably fix the infinite redirect.

**Comment by mrPeshi** [comment]
John, thanks you for the quick response!
Without regex checkbox enabled it doesn't work at all - show page 404

**Comment by johngodley** [comment]
Can you copy/paste the full URL here so I can have a look at it?

**Comment by mrPeshi** [comment]
http://wordpress/%D1%82%D0%B5%D1%81%D1%82

**Comment by johngodley** [comment]
Can you copy/paste the real URL?

**Comment by mrPeshi** [comment]
http://devis.ru/тест

**Comment by mrPeshi** [comment]
Hi John!
Did I give enough information to identify this error?

**Comment by johngodley** [comment]
In the original message you say the source is `/%D1%82%D0%B5%D1%81%D1%82`, but the screenshot shows `/тест`. Can you change the source to be `/%D1%82%D0%B5%D1%81%D1%82` and then disable the regex?

When I try `/%D1%82%D0%B5%D1%81%D1%82` on my own server I get a correct redirect, but `/тест` does nothing. I don't get the infinite redirect you have though.

**Comment by mrPeshi** [comment]
Hi John! 
Thanks a lot for the answer!
Everything fell into place.

%D1%82%D0%B5%D1%81%D1%82 -> тест 
URL-encoded -> UTF-8

Thats happend because in redirection.php&sub=404s page we can add new redirect from data table as it is - in UTF-8

<img width="867" alt="2017-11-09 21 56 55" src="https://user-images.githubusercontent.com/18233208/32624984-089896a0-c59c-11e7-8a22-a0bae60ea913.png">

In other words, now to add a new redirect with non-ASCII characters, you need an additional service for convert URL from UTF-8 to URL-encoded
Not very convenient, but it works.

Once again, thank you very much!!!

**Comment by johngodley** [comment]
Ah, that's a good point - I didn't realise it wasn't encoding them there. I'll get that fixed in the next release, thanks!
