### ISSUE TITLE
Not Able To Import CSV

### ISSUE THREAD

**Issue by picolo85** [johngodley/redirection#510]
I've tried different csv format to upload on redirection, however none of them is working. Can someone please provide me with a working format.

**Comment by johngodley** [comment]
The format is listed on the import/export page.

If you're having problems can you upload the file here?

**Comment by picolo85** [comment]
Yes I've seen it but not working, here is a file, its only a replica, the original one contain much  more URLs.
[FRREDIRECTS.xlsx](https://github.com/johngodley/redirection/files/1447565/FRREDIRECTS.xlsx)

**Comment by picolo85** [comment]
Please check this one instead 
[FRREDIRECTS.xlsx](https://github.com/johngodley/redirection/files/1447568/FRREDIRECTS.xlsx)

**Comment by johngodley** [comment]
Ok, that's an Excel xlsx file. Redirection only works with .csv files. You can export from Excel to CSV format.

https://support.office.com/en-us/article/Import-or-export-text-txt-or-csv-files-5250ac4c-663c-47ce-937b-339e391393ba

**Comment by picolo85** [comment]
Yes I used csv format for the redirection..... Here I sent you the excel xlsx because github doesn't support the csv format... Now can you can please identified this issue and why its not workig?

**Comment by johngodley** [comment]
Not really, I'll need to see the actual CSV file. You should be able to zip it and then upload

**Comment by AytacM** [comment]
Hi picolo85,
I had the same issue when I saved the file from Excel. My solution was:

1) Go to desktop, right click and create a new txt file.

2) Write down URL's on each line like this:
Source URL, Target URL, [Regex 0=false, 1=true], [HTTP Code]
Example:
https://mydomain.id/scopus-list/xxx,https://www.targetdomain.com/sourceid/abc,1,301

3) Save txt file and close it. Rename its extension to .csv and use that file.

**Comment by johngodley** [comment]
While that works it's perfectly possible to use Excel, you just need to save as CSV format.

**Comment by johngodley** [comment]
@picolo85 if you can upload the actual CSV (as a zip) then I'll be able to tell you what's wrong with the file. Your Excel spreadsheet seems fine as-is. I'll close this for now, but please reopen with more details.
