### ISSUE TITLE
Sorting 404 errors alphabetically

### ISSUE THREAD

**Issue by WebroMarketing** [johngodley/redirection#512]
I'm trying to sort the 404 errors alphabetically so I can delete the ones we don't need to take any action on. Since the last Redirection update, this functionality appears to have disappeared. 

Or I'm being daft, which is something that can never be ruled out!

 Go to the '404' section of the plugin. I used to be able to sort them alphabetically by clicking on the 'source URL' header of the table, but it appears that functionality has gone. Being able to do this makes the job just that little bit easier.

Using Redirection 2.9.1, WP version 4.8.3, & Chrome. Hope this is enough info. Thanks.

**Comment by johngodley** [comment]
No, you're not daft, I accidentally disabled the sortable headers! Soon to be restored in the next version, which I'm aiming to release tomorrow.

**Comment by WebroMarketing** [comment]
Great, thanks a lot.
