### ISSUE TITLE
Updated redirects don't go to the new location

### ISSUE THREAD

**Issue by dcranmer** [johngodley/redirection#515]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

I created a redirect that points to a PDF document. I updated the PDF document, including the URL, and updated the redirect to point to the new location. However, after clearing both my site and browser caches, the redirect is still pointing to the old PDF location. 

### Environment

Firefox 56.0.2, browser version, WordPress 4.8.3 and Redirection plugin v. 2.7.3.

**Comment by johngodley** [comment]
Can you include the URL and what it should redirect to here?

**Comment by dcranmer** [comment]
Hi John!

Somehow the edited redirects are now working. However, the new redirects that I set up are still not working:

https://accountability-framework.org/wp-content/uploads/2017/10/Accountability-Framework-core-document_Spanish_2017-10-25.pdf
should go to:
https://accountability-framework.org/wp-content/uploads/2017/11/accountability-framework-core-document_spanish_2017-11-3.pdf

https://accountability-framework.org/wp-content/uploads/2017/10/Accountability-Framework-core-document_2017-10-09.pdf
should go to:
https://accountability-framework.org/wp-content/uploads/2017/11/accountability-framework-core-document_english_2017-11-3.pdf

https://accountability-framework.org/wp-content/uploads/2017/10/Accountability-Framework-core-document_Portuguese_2017-10-25.pdf
should go to:
https://accountability-framework.org/wp-content/uploads/2017/11/accountability-framework-core-document_portuguese_2017-11-3.pdf

https://accountability-framework.org/wp-content/uploads/2017/11/Accountability-Framework-core-document_Bahasa_2017-10-25.pdf
should go to:
https://accountability-framework.org/wp-content/uploads/2017/11/accountability-framework-core-document_bahasa_2017-11-3.pdf

Let me know if you have any idea what might be wrong.

Thanks!
Danielle

**Comment by jodavaga** [comment]
only redirection that seems to be working is the 404. all other redirects don't go anywhere...old urls are being loaded

**Comment by dcranmer** [comment]
@johngodley - do you have any advice as to how to get these working?

**Comment by jodavaga** [comment]
Only way to I have to resolved this, was by the .htaccess file

**Comment by johngodley** [comment]
@jodavaga yes, your server is configured to serve files that exist first. This means that WordPress isn't loaded, and so Redirection doesn't have chance to run. You will either need to delete the old files, or use Redirection to export to the .htaccess file.
