### ISSUE TITLE
PDF redirect Not working

### ISSUE THREAD

**Issue by Mitsuhiko-Hojo** [johngodley/redirection#522]
Sorry my English is very very poor.

I have two redirect settings.

**setteing 1**

source url
https://ayatori/test/

target url
https://ayatori.co.jp/company-guide/

**setteing 2**

source url
https://ayatori.co.jp/uploads/2017/11/test.pdf

target url
https://ayatori.co.jp/company-guide/

setting1 is ok.
setting2 is not working.

Anyone, please tell me my mistake.

**Comment by johngodley** [comment]
The file https://ayatori.co.jp/uploads/2017/11/test.pdf still exists and so your server will serve this before Redirection is able to run. You will need to delete test.pdf

**Comment by Mitsuhiko-Hojo** [comment]
Sorry I late reply.
I tried your advice, then I got expected behavior.
Thank you
