### ISSUE TITLE
RegEx-rules not being adhered...

### ISSUE THREAD

**Issue by E-VANCE** [johngodley/redirection#523]
#### Summary
Trying to make use of RegEx redirection-rules.

#### Actual Behavior
Unfortunately nothing much happens which is the problem – the redirection engine doesn't trigger... I have tested and it *does* recognize RegEx-rulesets and performs redirects just fine but I assume that the rule needs different formatting maybe?

#### Steps to reproduce
Please view a working example of a RegEx rule [here](https://regex101.com/r/HsIDkQ/16). I have used the exact same format in the WordPress backend.

#### Environment
Tested with FF 56.0.2 (Mac) -- WP 4.8.3, plugin is at 2.9.1.

Thanks!!

**Comment by johngodley** [comment]
Matches are performed against the URL path, not including the domain. Your regexes in the link above seem to be matching the domain as well.

**Comment by E-VANCE** [comment]
My bad, thanks for clearing things up...!
