### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by carlodamo** [johngodley/redirection#526]
```
Plugin: 2.7.3
WordPress: 4.8.3
PHP: 7.0.25
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Nonce: 722a7ed372
URL: https://<site>/wp-admin/admin-ajax.php

Error: Unexpected end of JSON input (undefined)
Action: red_get_group
Params: {"orderBy":"","filterBy":"","filter":"","perPage":200}
Code: 500 
Raw: -no data-
```

**Comment by carlodamo** [comment]
Maybe conflict with w3 total cache... deactivanting the W3 plugin the alert is disappeared and the Redirection Plugin come back to work

**Comment by johngodley** [comment]
Do you have any messages in your PHP error log that may help? How do you have W3 total cache setup?

**Comment by carlodamo** [comment]
We deactivate w3 total cache and the error disappeared.

Another issue. Now we could not import csv file, so we imported with htaccess text file.

**Comment by osimakoff** [comment]
Having the same problem. Using w3tc on our site is a hard requirement. Is Redirection simply not going to work now? The two plugins coexisted perfectly fine before

**Comment by johngodley** [comment]
@osimakoff I currently don't know what the problem is, and disabling it in this instance may have caused Redirection to work again but that doesn't mean it was the cause. I will investigate w3tc and see if I can reproduce

**Comment by johngodley** [comment]
I've tried w3tc but I haven't been able to reproduce a problem. The plugin is very complicated, so it may be related to a particular configuration.

If either of you can provide a login to a site with the problem then I'll take a look see what's happening.

**Comment by carlodamo** [comment]
I removed W3 Total Cache, searching for other plugin

**Comment by osimakoff** [comment]
Hi John,

Thanks so much for your help! We did find the issue - for anyone else having these weird problems - got to your theme functions.php and check for hidden characters!

We spent two full days battling this issue then tried as a last resort and it worked!

Thanks again, John! Our problem is now resolved

**Comment by johngodley** [comment]
@osimakoff thanks for letting me know! Yes, unfortunately theme functions.php can affect Ajax requests by adding stuff to them. Redirection depends on Ajax requests, so is particularly affected.
