### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by osimakoff** [johngodley/redirection#529]
Please help! I have 3 identical environments. It's working in 2 others and one would not work under any conditions - I reinstalled the auto way, the manual way and any page I got to gives me this error. There is nothing I can do. Please help! 

```
Plugin: 2.9.2
WordPress: 4.7.4
PHP: 7.0.20
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Error: Unexpected token ﻿ in JSON at position 0 (undefined)
Action: red_get_redirect
Params: {"orderBy":"id","filterBy":"","filter":""}
Code: 200 
Raw: ﻿{"items":[],"total":0}

Error: Unexpected token ﻿ in JSON at position 0 (undefined)
Action: red_get_group
Params: {"filterBy":"","filter":""}
Code: 200 
Raw: ﻿{"items":[{"id":2,"name":"Modified Posts","redirects":0,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":1,"name":"Redirections","redirects":0,"module_id":1,"moduleName":"WordPress","enabled":true}],"total":2}
```

**Comment by johngodley** [comment]
This is not the same problem you mentioned [here](https://github.com/johngodley/redirection/issues/526#issuecomment-344083269) - the response codes are different.

Saying that, I do not know why the error is being caused because the response looks valid. Would it be possible to access the site causing the problem and investigate further? If so I can be contacted [here](https://redirection.me/contact/)

**Comment by osimakoff** [comment]
Hi John, thanks for a quick reply! The issue is that these are all my client's environments and I sadly can't give access to any of these...  There are also no meaningful PHP logs or anything in the server logs either. I alos tried restoring the DB to the older version ....well.... as you may guess the issue still exists.

I did try disabling the W3TC but it's the same. I think the problem is somewhere in the environment but since there are no logs for me to prove it.

Every time I open ANY Redirection page, I see that error screen popup and the messages keep being appended

**Comment by johngodley** [comment]
Can you open your browsers developer console and then access the page. This should show any errors. If you look at the console's 'network' tab you will also see a request being made to admin-ajax.php. Click on this to grab the details. Depending on your browser you may be able to right-click and copy the information, or take a screenshot etc.

If you do the same on a site that is working and one that isn't then there may be enough information to see what the difference is.

**Comment by osimakoff** [comment]
﻿{"items":[{"id":2,"name":"Modified Posts","redirects":0,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":1,"name":"Redirections","redirects":0,"module_id":1,"moduleName":"WordPress","enabled":true}],"total":2}

**Comment by johngodley** [comment]
That's not quite what I meant. What I'm trying to see are the request and response headers. This is what I see on my own site:

<img width="311" alt="devtools" src="https://user-images.githubusercontent.com/1277682/32790407-460de04a-c956-11e7-9f25-a1e0e3b69748.png">

Note that if you can find this then don't include the cookie value.

My hope is that by seeing this it might help identify the difference between the servers.

**Comment by osimakoff** [comment]
Request URL:https://dev/wp-admin/admin-ajax.php
Request Method:POST
Status Code:200 
Remote Address:162.221.74.150:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
access-control-allow-credentials:true
access-control-allow-origin:https://dev
cache-control:no-cache, must-revalidate, max-age=0
content-encoding:gzip
content-type:application/json
date:Tue, 14 Nov 2017 14:34:48 GMT
expires:Wed, 11 Jan 1984 05:00:00 GMT
pragma:no-cache
server:openresty/1.11.2.3
set-cookie:wfvt_686410540=5a0afef65edaa; expires=Tue, 14-Nov-2017 15:04:30 GMT; Max-Age=1800; path=/; HttpOnly
status:200
vary:Accept-Encoding
x-content-type-options:nosniff
x-frame-options:ALLOWALL
x-powered-by:PHP/7.0.20
x-robots-tag:noindex
Request Headers
:authority:devwww.outdoors.org
:method:POST
:path:/wp-admin/admin-ajax.php
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.8,ru;q=0.6
content-length:391
content-type:multipart/form-data; boundary=----WebKitFormBoundaryB7vBC3BShX1q32Z4
....{cookie value}
origin:https://dev
referer:https://dev/wp-admin/tools.php?page=redirection.php
user-agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Request Payload
------WebKitFormBoundaryB7vBC3BShX1q32Z4
Content-Disposition: form-data; name="action"

red_get_redirect
------WebKitFormBoundaryB7vBC3BShX1q32Z4
Content-Disposition: form-data; name="_wpnonce"

c0625e256c
------WebKitFormBoundaryB7vBC3BShX1q32Z4
Content-Disposition: form-data; name="data"

{"orderBy":"id","filterBy":"","filter":""}
------WebKitFormBoundaryB7vBC3BShX1q32Z4--

**Comment by johngodley** [comment]
I think you got this fixed, as detailed https://github.com/johngodley/redirection/issues/526#issuecomment-345842955 - closing for now
