### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Jariten-kun** [johngodley/redirection#533]
Trying to use the plugin, and getting this after the first install:

### Actual Behavior
`Plugin: 2.9.2
WordPress: 4.8.3
PHP: 7.1.10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5
Buster: 2.9.2 === 2.9.2
TypeError: undefined is not an object (evaluating 'e.request.status')`

### Steps to reproduce

Simply trying to use it; it only worked once.

### Environment
Tried with two browsers; Safari and Chrome - same result. WordPress is ver. 4.83

**Comment by johngodley** [comment]
Can you try version 2.10 and see what happens?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
