### ISSUE TITLE
Moved to HTTPS but adresses are still linking to HTTP

### ISSUE THREAD

**Issue by Suffokate** [johngodley/redirection#534]
### Summary

Hello we made redirections but we also moved to SSL.
Our redirestions looks like:
Sourceurl: /oldproductlink
Targeturl: /newproductlink

We dont set there www.domain.com just path after domain and the problem is all redirections are pushing to http://www.domain.com/newproductlink instead use HTTPS. I cant find the setting of these so my question is can i globally set plugin to use https insted of http ??? we have so many redirections and manually it will take hours to change.
Thank you

**Comment by johngodley** [comment]
You don't need to change anything, the redirections will carry on working. Please clear your browser cache.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
