### ISSUE TITLE
Import file doesn't work

### ISSUE THREAD

**Issue by oscarvanheeswijk** [johngodley/redirection#535]
Hi,

I try to import a redirect csv file. I created this in Excel with 4 columns:
Source URL, Target URL, Regex, HTTP Code

When I "Save as" CSV and import it doesn't import anything.
[test-redirect.zip](https://github.com/johngodley/redirection/files/1475252/test-redirect.zip)

How can I fix this? Or better, could you make a template which i can just fill out?

Thanks on behave!
Oscar

**Comment by johngodley** [comment]
Here's the contents of your file:

```csv
Source URL;Target URL;Regex;HTTP code
/test;/thisisthedestination;1;301
```

You can see that it is using a semicolon to separate the columns. Redirection is expecting it to be CSV format, so requires commas.

Also, your file needs a .csv extension

**Comment by johngodley** [comment]
Closing for now, please reopen if you still can't import
