### ISSUE TITLE
All 301 redirects stopped working

### ISSUE THREAD

**Issue by Stipend** [johngodley/redirection#537]
### Summary

All 301 redirects have stopped working for a site (www.fitbark.com)
We have setup a staging  site to  to test this.

We used curl to call :  https://staging-fitbarkgc.kinsta.com/help-user/
 In Wordpress:
![screenshot 2017-11-16 15 54 02](https://user-images.githubusercontent.com/1816336/32918221-5a46ca26-cae7-11e7-995e-f6c17924c4e0.png)

We expected the curl command to return the data from the redirect.
Going to the final target worked 
 https://staging-fitbarkgc.kinsta.com//help/?utm_campaign=user-help&utm_medium=app&utm_source=fitbark

Curious are the Link and Location lines.

- < Link: <https://staging-fitbarkgc.kinsta.com/wp-json/>; rel="https://api.w.org/"
- < Location: /help/?utm_campaign=user-help&utm_medium=app&utm_source=fitbark

Curl Command:
curl  -v  "https://staging-fitbarkgc.kinsta.com/help-user/"

curl output:
```
*   Trying 104.197.69.102...
* Connected to staging-fitbarkgc.kinsta.com (104.197.69.102) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.kinsta.com
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
> GET /help-user/ HTTP/1.1
> Host: staging-fitbarkgc.kinsta.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: kinsta-nginx
< Date: Thu, 16 Nov 2017 21:14:10 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< Vary: Accept-Encoding
< X-Powered-By: PHP/7.0.25-1+ubuntu16.04.1+deb.sury.org+1
< Location: /help/?utm_campaign=user-help&utm_medium=app&utm_source=fitbark
< Expires: Sat, 26 Jul 1997 05:00:00 GMT
< Last-Modified: Thu, 16 Nov 2017 21:14:09 GMT
< Cache-Control: max-age=0, no-cache, no-store, must-revalidate
< Pragma: no-cache
< Link: <https://staging-fitbarkgc.kinsta.com/wp-json/>; rel="https://api.w.org/"
<

```
Please list your browser, browser version, version of WordPress and Redirection plugin.

- WordPress 4.8.3 running
- Redirection: 2.9.2

**Comment by johngodley** [comment]
I'm not seeing the same:

```
curl -v -I -s https://staging-fitbarkgc.kinsta.com/help-user/
*   Trying 104.197.69.102...
* TCP_NODELAY set
* Connected to staging-fitbarkgc.kinsta.com (104.197.69.102) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=EssentialSSL Wildcard; CN=*.kinsta.com
*  start date: Jul  5 00:00:00 2017 GMT
*  expire date: Oct  4 23:59:59 2018 GMT
*  subjectAltName: host "staging-fitbarkgc.kinsta.com" matched cert's "*.kinsta.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fdfc4009c00)
> HEAD /help-user/ HTTP/2
> Host: staging-fitbarkgc.kinsta.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 301
< server: nginx
< date: Fri, 17 Nov 2017 09:09:00 GMT
< content-type: text/html
< content-length: 178
< location: https://staging-fitbarkgc.kinsta.com/help/?utm_campaign=user-help&utm_medium=app&utm_source=fitbark
< x-content-type-options: nosniff
```

Note this redirect is not from Redirection.

If you get a `Location` header and a 404 then usually it means you have a plugin or theme that is hooking into `wp_redirect`, but not returning `true` or `false`, as per the WordPress documentation.

**Comment by Stipend** [comment]
Thanks for the quick response John. 

In-between my report and your test, my CTO changed from using your wp redirection to the Kinsta redirection (our hoster). That is why you did not see the issue.

We had meant to only use the Kinsta version on our production servers, however it also got applied to our staging server.

If you would like to debug this we can make the staging server use your redirection. This seemed to just stop working.

**Comment by johngodley** [comment]
Sure, if you want to enable it again I'll take another look. As mentioned above if you are getting a `Location` header along with a 404 status then I would look at your theme and other plugins and see if they are misusing `wp_redirect`.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
