### ISSUE TITLE
Problem starting Redirection 2.9.2

### ISSUE THREAD

**Issue by unduhkeygen** [johngodley/redirection#538]
Plugin: 2.9.2
WordPress: 4.9
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by johngodley** [comment]
Do you have any more details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
