### ISSUE TITLE
Make advanced 404 options available when adding via 404 logs

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#539]
Make the advanced 404 options available when adding a redirect via the 404 page.

https://wordpress.org/support/topic/a-404-log-suggestion/

**Comment by josepiratilla** [comment]
Also it would be great to not to log a 404 that is caused by a redirect rule. This would fulfill another feature that I asked for. Thank you very much for your work.

**Comment by johngodley** [comment]
Additional options available in #1232
