### ISSUE TITLE
New Feature: Ignore URL from 404 log

### ISSUE THREAD

**Issue by josepiratilla** [johngodley/redirection#541]
### Summary

Include a quick option to ignore a URL from the 404 log. This will add the URL to a do nothing redirect. Thus all 404 comming from hacking tryouts can be filtered after a proper maintenance. 

### Actual Behavior

You can add a redirect from the 404 log, But no option to add a do nothing redirect is available.

### Steps to reproduce

Go to a 404 log, click it and a new option "Ignore" could appear.

### Environment

Not Apply.

**Comment by josepiratilla** [comment]
Thank you very much in advance.

**Comment by johngodley** [comment]
See https://redirection.me/support/redirect-actions/#do-nothing

**Comment by josepiratilla** [comment]
Yes, but it can't be created from the 404 log, if I'm not wrong. So I need to create a dummy, and then go to the redirect list and change it to a do nothing.

**Comment by johngodley** [comment]
Added in #1232
