### ISSUE TITLE
Redirection Groups Break Priority

### ISSUE THREAD

**Issue by stevewcox** [johngodley/redirection#542]
### Summary

I was trying to create two levels of redirects for a site move. High priority rules (position=1)  would use regex to match the full path. The lower priority (position=101) would catch those not matched by using part of the URL.

It works when they are in the same redirection group. If I put them in different redirection groups, then the position is unpredictable

### Actual Behavior

It appears that the rewrite rules are created by processing each group in turn (then ordered on priority) - rather than ignoring groups and just using priority. If they are to be processed by groups first, then this should be documented and groups should be given their own meta-priority.

### Steps to reproduce

Create two groups - "Old Site Redirects" and "Old Site General Redirects" - create two rewrites rules as attached.

![screen shot 2017-11-21 at 11 26 30](https://user-images.githubusercontent.com/6909986/33082992-119ffde0-ced6-11e7-93b4-c351c31b7fe0.png)

### Environment

Chrome, WP 4.8.3 hosted on wp-engine. Plugin version 2.10

**Comment by johngodley** [comment]
I know it's a while since this ticket was created, but the group is not used since version 4 of the plugin. Closing this as finished.
