### ISSUE TITLE
Wildcard-card redirection not working

### ISSUE THREAD

**Issue by louiswalch** [johngodley/redirection#543]
Hello. It's prepending a question mark before my target url upon redirection. My config is as follows:

Source URL `\/?section=exhibitions.*`
Target URL `/exhibitions/`

When viewing a URL like:
www.example.com/index.php?section=exhibitions&expid=332
I am redirected to:
www.exaple.com/?/exhibitions/

**Comment by johngodley** [comment]
You are escaping the wrong character - the `/` doesn't need to be escaped, but `?` does:

`/\?section=exhibitions.*`
