### ISSUE TITLE
Enhance search in list view

### ISSUE THREAD

**Issue by tschortsch** [johngodley/redirection#545]
Would it be possible to enhance the search in the list view to also search inside the `Target URL`? Right now the search only includes the `Source URL`.

**Comment by jshuusko** [comment]
I would also like to extend the search to include the agent. Sometimes it would be helpful to drop all bots or any weird browsers to get an idea where from and how much the manual 404 traffic is.

Thank you in advance.

-jari

**Comment by johngodley** [comment]
Added in 4.4
