### ISSUE TITLE
Wrong rule?

### ISSUE THREAD

**Issue by ManfredMeise** [johngodley/redirection#549]
Hi John,

in order to outdate content with Google, I created a simple RegEx-Rule:
/.*

which results in a 404/410-gone, when matched.

I do get the expected result with "CURL -I www.baustellen-it.de" but not for "CURL -I www.baustellen-it.de/something". In this case I get a 404.

How to specify to result in 410 for every URL?

Thanks,
Manfred

**Comment by johngodley** [comment]
Sorry for the delay in responding. The above rule works fine when I try it on my own site. Do you have a site where this isn't working - baustellen-it doesn't seem to be working anymore.

**Comment by ManfredMeise** [comment]
As the desired functionality was not given, we took the machine out of service. Now back online...

**Comment by johngodley** [comment]
Thanks. I can verify your issue, although I can't recreate it. Do you have anything else running on that site - other plugins that might be related, for example?

**Comment by ManfredMeise** [comment]
NO. very pure installation - just for the purpose of redirections. No other plugins installed.

**Comment by johngodley** [comment]
Ok, again, sorry for taking so long - Christmas got in the way! If you are still having a problem here would it be possible to get access to the site? If so I can be contacted through the plugin's support page.

Is this running on Raidbox? I recall we had some issues there before so I don't know if it may be related.

**Comment by ManfredMeise** [comment]
Hi John, yes it's still running on raidboxes. They have implemented fixes in December based on your suggestions. All previous redirections now working - except this one.....

I am prepared to grant access to you - how to send login data (other than this forum)??

**Comment by johngodley** [comment]
There's a link on the support page of the plugin to contact me by email. That'll be the best way

**Comment by johngodley** [comment]
After looking it seems to be a server config issue. Closing this ticket for now, but please reopen if you have more details
