### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by inseev** [johngodley/redirection#551]
Plugin: 2.10.1
WordPress: 4.8.3
PHP: 5.6.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

When I tried to load `redirection.js` manually I was getting a 404. I updated the plugin and still got a 404

**Comment by johngodley** [comment]
Does the file redirection.js exist on your server?

**Comment by inseev** [comment]
It does. I just checked.

So maybe it's not even an issue with the plugin, but the site itself

**Comment by johngodley** [comment]
Did you resolve this problem?

**Comment by inseev** [comment]
Yeah, turned out it was due to conflicts with other files. I'm going to close this. Thank you for following up
