### ISSUE TITLE
Redirection error

### ISSUE THREAD

**Issue by adtajo** [johngodley/redirection#556]
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 7.0.19
Browser: Mozilla/5.0 (Windows NT 6.1; rv:57.0) Gecko/20100101 Firefox/57.0

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data (undefined)
Action: red_redirect_action
Params: {"orderBy":"id","filterBy":"","filter":"","items":"3","bulk":"disable"}
Code: 200 OK
Raw: <html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("d525d30ea02aaf94a3419534c334e6f0");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://healthmarket.byethost7.com/wp-admin/admin-ajax.php?i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>

**Comment by johngodley** [comment]
Your site is outputting that script (aes.js) in places it shouldn't. This could be caused by a theme or a plugin. You will need to locate what is causing it, and stop it outputting during ajax requests.

**Comment by adtajo** [comment]
How do i locate it

**Comment by johngodley** [comment]
It's something specific to your site. You could try changing theme, disabling plugins, etc. More than likely it is some kind of security plugin.

**Comment by adtajo** [comment]
I've changed the theme and I've tried deactivating all the plugins but its
still giving me the same error message

**Comment by johngodley** [comment]
What is your website URL?

**Comment by adtajo** [comment]
http://healthmarket.byethost7.com

**Comment by johngodley** [comment]
I get a '403 forbidden' message when accessing that. If you are using any kind of security software then it may be blocking me, and it may also be blocking Redirection.

**Comment by adtajo** [comment]
can you try using this http://healthmarket.byethost7.com/?i=1

**Comment by johngodley** [comment]
Ok, yes. Then I'm pretty sure it's whatever software you are using that does the protection as ?i=1 is mentioned inside your original message. How are you blocking people to your site? Is it something like Cloudflare or Wordfence?

**Comment by adtajo** [comment]
I dont really understand those two words but were you able to access the
site with the second link?

**Comment by adtajo** [comment]
I can access the site with the first link here

**Comment by johngodley** [comment]
Yes I was.

How did you know to put `?i=1` on the URL? What does that do?

**Comment by adtajo** [comment]
waow! its finally working. I noticed a lock on the url and i granted the
permission. Thanks so much

**Comment by johngodley** [comment]
Can I ask what you changed? It would be useful to know if anyone else has the same problem
