### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by JayMacApple** [johngodley/redirection#558]
```
Plugin: 2.10.1
WordPress: 4.8.4
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Error: Unable to add new redirect (206): Unknown column 'title' in 'field list'
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"url":"http://newsummitcover.staging.wpengine.com/keystone-colorado-travel-info/colorado-snow-reports/","title":"","regex":false,"match_type":"url","action_type":"url","group_id":2,"action_code":301,"action_data":{"url":"http://newsummitcover.staging.wpengine.com/keystone-colorado-travel-info/keystone-weather-forecast/"}}
Code: 200 OK
Raw: {"error":{"message":"Unable to add new redirect","code":206,"wpdb":"Unknown column 'title' in 'field list'"}}
```

**Comment by JayMacApple** [comment]
This happens on both live and staging sites. We are unable to add any new redirects.

**Comment by johngodley** [comment]
The error message indicates that one of your database tables is missing a column. I don't know how this situation would occur, but without it you will continue to get errors. Your options are:

- Delete and re-install the plugin to get a fresh install with new database tables. If you have existing data you can export and then import
- Manually modify the `wp_redirection_items` table and add the column yourself. You can see the SQL for the database in `redirection/models/database.php`, and you need to add the `title` column

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
