### ISSUE TITLE
Redirect Plugin Not Working

### ISSUE THREAD

**Issue by tvt4892** [johngodley/redirection#561]
RecentlyShifted from http to https

Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Buster: 2.10.1 === 2.10.1
TypeError: Cannot read property 'status' of undefined

**Comment by johngodley** [comment]
Can you open your browser's developer console and see what is shown there when you try to load the plugin? If possible a screenshot would be very useful

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
