### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by giosyst3m** [johngodley/redirection#564]
```
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.6.31
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Error: No response returned - WordPress did not understand the AJAX request
Action: red_redirect_action
Params: {"orderBy":"","filterBy":"","filter":"ejercicios","items":"108","bulk":"delete"}
Code: 200 OK
Raw: 0
```

**Comment by johngodley** [comment]
Your WordPress is not returning any data when asked to delete data. Are you running any kind of security plugins?

**Comment by giosyst3m** [comment]
Yes, I have these 
Wordfence Security
HTTP Headers

thanks

**Comment by giosyst3m** [comment]
I did that and work, however, this error is very strange when appears

**Comment by johngodley** [comment]
So it works if you disable the plugins, and it stops working if you enable the plugins? Do you know which one causes the problem - Wordfence or HTTP headers?

**Comment by giosyst3m** [comment]
It's working. All plug-in are enable.

I am not sure if Wordfence or HTTP headers are problems.

Thank you for hepping.
