### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by yoshinori63** [johngodley/redirection#565]
```
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 7.1.12
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

Error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data (undefined)
Action: red_get_group
Params: {"filterBy":"","filter":""}
Code: 403 Forbidden
Raw: -no data-

Error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data (undefined)
Action: red_get_redirect
Params: {"orderBy":"id","filterBy":"","filter":""}
Code: 403 Forbidden
Raw: -no data-
```

**Comment by johngodley** [comment]
Your WordPress is returning a 403 forbidden error when Redirection makes a request. Are you running any kind of security plugin?

**Comment by yoshinori63** [comment]
Yes , I use "ip geo block" plugin which block to access from CN,RU. Does Redirection access form CN,RU.

**Comment by johngodley** [comment]
No, it is only local to your site. Could you try temporarily disabling the security software and see if it fixes the problem?

**Comment by yoshinori63** [comment]
Thank youfor your support! it work well after disabling "ip geo block".  I will review its setting
