### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by tvt4892** [johngodley/redirection#566]
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by johngodley** [comment]
Can you include more details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
