### ISSUE TITLE
Feature request: Redirect only if page not found

### ISSUE THREAD

**Issue by mat-de-mystify** [johngodley/redirection#568]
### Summary

I manage a wordpress site with many different contributors who are always making new categories or tags that are not needed or better suited to a different existing category. I wanted to setup a redirect to search for tag or catagory pages **only** if they don't exist.

### Actual Behavior

This is a request for a new feature, execute a regex **only if** a page doesnt exist

**Comment by mat-de-mystify** [comment]
any movement on this?

**Comment by johngodley** [comment]
See 'URL and WordPress page type': https://redirection.me/support/matching-redirects/
