### ISSUE TITLE
URL parameters to new site

### ISSUE THREAD

**Issue by x10sys** [johngodley/redirection#569]
Old address: https://site.old-site.com/?promo-kod=CODE-X17-BOX#order
Desired new address (final redirection): https://newsite.com/?promo-kod=CODE-X17-BOX#order

Is this even possible?

**Comment by johngodley** [comment]
Yes, without `#order`. This isn't sent to the server and it's not possible, using Redirection or anything else, to redirect using it.

**Comment by x10sys** [comment]
So it's not possible with #order. Thank you for the reply. Glad to know that now.

Happy holidays! :)
