### ISSUE TITLE
Return HTTP 410 for deleted posts

### ISSUE THREAD

**Issue by michaelnordmeyer** [johngodley/redirection#57]
I'd like Redirection to monitor deleted posts and return a 410 as an option.

**Comment by CrisHazzard** [comment]
Same, this would be really helpful.

**Comment by kurtschlatzer** [comment]
Yes, please! This would make an indispensable plugin over-the-top better.

**Comment by Sophist-UK** [comment]
👍

**Comment by johngodley** [comment]
This was added sometime around 2.2.5
