### ISSUE TITLE
Redirect of php page fails

### ISSUE THREAD

**Issue by tomelevated** [johngodley/redirection#570]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

We have some .php pages that people are trying to access and we want to redirect those. When I click on add redirect from the 404 tab and enter the target url, it goes to a 404 error page, not the site 404 page anymore.
![screen shot 2017-12-14 at 9 54 43 am](https://user-images.githubusercontent.com/23390618/34006911-d9cbb3e6-e0b4-11e7-8508-f8e98bd449f4.png)

### Actual Behavior

It used to go to the site 404 page, but now it shows
![screen shot 2017-12-14 at 9 55 23 am](https://user-images.githubusercontent.com/23390618/34006933-ed3a3290-e0b4-11e7-9854-537f3fb828c5.png)

### Steps to reproduce

Go to the link I provided.

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
This is what is happening when a request is made to that URL:

```
curl -v -I https://visitcarlsbad.com/tom.php                                                                                                                                
*   Trying 45.33.41.69...
* TCP_NODELAY set
* Connected to visitcarlsbad.com (45.33.41.69) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; CN=visitcarlsbad.com
*  start date: Sep  8 18:39:00 2017 GMT
*  expire date: Nov  9 23:55:00 2019 GMT
*  subjectAltName: host "visitcarlsbad.com" matched cert's "visitcarlsbad.com"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> HEAD /tom.php HTTP/1.1
> Host: visitcarlsbad.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: nginx/1.4.6 (Ubuntu)
< Date: Wed, 20 Dec 2017 09:18:50 GMT
< Content-Type: text/html
< Connection: keep-alive
< X-Powered-By: PHP/5.5.9-1ubuntu4.20
< Vary: Cookie
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Location: https://visitcarlsbad.com/attractions
< X-Redirect-Agent: redirection
```

You will notice that at the bottom is a `Location` with the correct target URL, and `X-Redirect-Agent` with `redirection`. Even though Redirection is correctly redirecting the URL the code returned is 404 and not 301.

This tells me that you are running another plugin (or maybe even your theme) that is incorrectly changing the redirect process. You will need to locate the plugin and see if it can be fixed or disabled.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
