### ISSUE TITLE
Automatic term redirection

### ISSUE THREAD

**Issue by cedriccharles4** [johngodley/redirection#572]
Hi John,

It seems that the plugin doesn’t create automatic redirections when the slug of a term (custom taxonomy) is changed. Could you please add this useful feature :) ?

Thank you !

**Comment by johngodley** [comment]
This was added in #575, and will be released in the next version

**Comment by geminorum** [comment]
@johngodley Still an issue since the update added support for custom **post-types** and not the custom **taxonomies**.
