### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by CaptSpaceBat** [johngodley/redirection#578]
```
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.6.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Error: Unexpected end of JSON input (undefined)
Action: red_get_group
Params: {"filterBy":"","filter":""}
Code: 500 Internal Server Error
Raw: -no data-

Error: Unexpected end of JSON input (undefined)
Action: red_get_redirect
Params: {"orderBy":"id","filterBy":"","filter":""}
Code: 500 Internal Server Error
Raw: -no data-
```
Hi John,

I hope you can help: I was accessing the plugn and received the message above

The next error message in the log is

500 | POST /newsite/wp-admin/admin-ajax.php HTTP/1.1

Please let me know if you need any further information.

Thanks in advance for any help or suggestions.

Kind regards,

Ian

**Comment by johngodley** [comment]
Your server is returning a 500 error. Sometimes this can be caused by an error on your server, or some security software you are running (such as Wordfence, Cloudflare etc) that is blocking the request

**Comment by CaptSpaceBat** [comment]
Thanks, John, it turned out to be a problem with another - ecommerce-related - plugin that was causing all manner of problems.  Now all resolved.
