### ISSUE TITLE
Redirection: 404s no longer appearing

### ISSUE THREAD

**Issue by CommunicationDirector** [johngodley/redirection#58]
I have Redirection on 2 sites. On one, all remains normal. On the other (with Karma theme) all was normal., then it changed. Re-directs continue to work, but 404s no longer show up. I've tried changing the length of time logs are stored, but still no 404 ever appears. Is there an easy fix?
Thanks, Mike, Communication Director, EndHunger.org

**Comment by johngodley** [comment]
Sorry for the response time. Do you still have this problem? It's kind of hard to say if there's a fix without knowing more details, and it sounds unlikely the plugin would just change how it works. Did you install or update any other plugin?

**Comment by johngodley** [comment]
Closing for now, please reopen if you have more information
