### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by Erik2605** [johngodley/redirection#580]
I have a problem when importing redirections trough csv import.
The error below still comes back.

My csv file is like:

/product/P0000003,/product/laptop-accu-4400mah-voor-protective/
/product/P0000005,/product/laptop-accu-4400mah-voor-fujitsu-siemens-amilo-m8800/
/product/P0000007,/product/laptop-accu-extended-8800mah-voor-acer-aspire-4710g-4310-4520-4920g/
(It is about 55.000 lines long and about 3.7 MB size.

The error:

```
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.4.28
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

Error: Invalid file (84)
Action: red_import_data
Params: {"group":3}
Code: 200 OK
Raw: {"error":{"message":"Invalid file","code":84}}
```

What can go wrong ?

**Comment by Erik2605** [comment]
It seems to work when I only do steps at 5000 lines per upload.

**Comment by johngodley** [comment]
You could try a smaller file - your server might be rejecting the file.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
