### ISSUE TITLE
Bulk import of redirects incorrectly changes code 302 to 301 redirect

### ISSUE THREAD

**Issue by thangarajj** [johngodley/redirection#583]
### Summary

We are trying to test our redirects for some of our pages by redirecting about 1000 urls temporarily for about 24 hours. We tried to import a sample, but everytime the http code gets changed to 301 after import
### Actual Behavior

Switches http code to 301 instead of maintaining as it was uploaded in the source (302)

### Steps to reproduce

Upload a csv file with the columns:
source, target, regex, http code
Sample content of csv:
/blog/lifestyle/bharat-the-power-of-a-name/,https://example.org/in/en/wisdom/article/bharat-the-power-of-a-name,0,302
/blog/yoga-meditation/demystifying-yoga/transfroming-mind-into-wishing-tree/,https://example.org/in/en/wisdom/article/transfroming-mind-into-wishing-tree,0,302

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Browser: Fx 57
Wordpress version: 4.6.8  (not updated beyond this since the wp api change causes some issues in our system)
redirection plugin version: Version 2.10.1

**Comment by johngodley** [comment]
The importer was incorrectly looking for the HTTP code in the wrong column. This has been fixed and will be in the next release. In the meantime you can create an empty 4th column and put the code into the 5th column and it should work
