### ISSUE TITLE
URLs with Hebrew chars not redirecting

### ISSUE THREAD

**Issue by abuyoyo** [johngodley/redirection#585]
### Summary

I'm trying to redirect URL's with Hebrew characters in them to English/Latin character permalinks.
Source URL's with Hebrew characters are not redirecting. At all. 

### Actual Behavior / Steps to reproduce

This does not work:
Source URL: /אודות
Target URL: /about

It leads to a 404 page (if page does not exist) or to the actual page (if it still exists)
Strangely enough - the Hebrew link  /אודות appears in the 404 logs.
Opting to 'Add Redirect' creates a rule that does not work (same as above).

I can get around this by manually typing the Hebrew URLs into a URL encoder and then pasting that into the plugin's source URL field

This DOES works:
Source URL: /%D7%90%D7%95%D7%93%D7%95%D7%AA
Target URL: /about

But it's a hassle and creates rules that are non-human-readable.
I have to hover over the individual links to see the decoded source URL in the status bar (encoded source URL:  /%D7%90%D7%95%D7%93%D7%95%D7%AA will actually show correctly as /אודות in the status bar)

### Environment
Chrome 63.0.3239.84
Redirection 2.10.1
WordPress 4.9.1
PHP 5.3.23
mysql 5.5.52

Thank you :)

**Comment by johngodley** [comment]
Yes, for now you will need to URL encode things.

**Comment by abuyoyo** [comment]
Oh well,
Thanks anyway :)

Alternatively, could you point me in the general direction of the code where:

1. Before the Source URL/Redirect item is sent to be sanitized/processed/saved etc.
(I can attempt to hack a PHP url_encode around the string before the plugin does its things)

-or-

2. Where the saved rule is printed onscreen
(I can attempt to wrap results in a PHP url_decode for presentation purposes, if not for the actual creation of rules)

I'll take my chances with future updates.
And if I do a passing job of it, I can submit it.

Other than all of this, it's the best wp redirection plugin I've found.

**Comment by johngodley** [comment]
Closing in favour of #19
