### ISSUE TITLE
All Redirections lost :( 

### ISSUE THREAD

**Issue by SimonKWilliams** [johngodley/redirection#586]
Trying to add a new Redirection.
Actions:
• Click on Tools > 'Redirection'
• Result - Shows error message "Something went wrong" - read below…
• Does not list any of my previously created re-directions

iMac (3 months old)
Safari: 11.0.2
<img width="1220" alt="screen shot 2017-12-29 at 14 59 25" src="https://user-images.githubusercontent.com/34934784/34432339-ef06e42e-eca8-11e7-99d9-a3a863a2eb04.png">

Versions: Plugin 2.6.6, WordPress 4.3.13, PHP 5.6.32
Nonce: a1bef88151

Action: red_get_module
Params: {}
Code: 200 OK
Error: JSON Parse error: Unrecognized token '<'
Raw: <br />
<b>Fatal error</b>:  Call to undefined function wp_get_raw_referer() in <b>/home/nakeddiv/public_html/wp-content/plugins/foogallery/freemius/includes/class-freemius.php</b> on line <b>7148</b><br />

Action: red_get_module
Params: {}
Code: 200 OK
Error: JSON Parse error: Unrecognized token '<'
Raw: <br />
<b>Fatal error</b>:  Call to undefined function wp_get_raw_referer() in <b>/home/nakeddiv/public_html/wp-content/plugins/foogallery/freemius/includes/class-freemius.php</b> on line <b>7148</b><br />

To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Judging by the error you are using a plugin called foogallery, and it is running when it shouldn't be (i.e. when Redirection is running), and it is causing an error to occur because you are using WordPress 4.3 and it is expecting you to be using WordPress 4.5.

You will either need to update foogallery to a version that has been fixed, or upgrade your WordPress to the latest

**Comment by SimonKWilliams** [comment]
Big thanks John - 
Think that plugin may be causing some issues with another plugin too.

Have great New Year - 
Simon
