### ISSUE TITLE
redirection doesnt work when redirecting a non Wordpress page to a Wordpress page

### ISSUE THREAD

**Issue by avalon1957** [johngodley/redirection#587]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by avalon1957** [comment]
when redirecting a non-WP page to a WP page on the same web server, the redirection does not work

**Comment by johngodley** [comment]
Can you give more details?

**Comment by avalon1957** [comment]
This doesnt work (screen capture below) 

https://caringcouples.com/couples.html ... 
should redirect to https://caringcouples.com/couples/

The first page is a hand written HTML page ... the 2nd page is a page created in wordpress

![redir](https://user-images.githubusercontent.com/34936597/34434123-ec85d75c-ec51-11e7-961c-f93bfc8ec7c1.jpg)

**Comment by johngodley** [comment]
Ok so probably your server is setup to serve the couples.html file directly, without giving WordPress a chance to load.

You can either:
- Delete the original file, forcing the request to go through WordPress
- Configure Redirection to save the redirects to Apache .htaccess file

**Comment by avalon1957** [comment]
ok thanks ...

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
