### ISSUE TITLE
Can't select the type of redirect.

### ISSUE THREAD

**Issue by mikezielonka** [johngodley/redirection#59]
Can't select the type of redirect.  This is using match of login in status and url and regex

For example I woul like to select a 302 and it the docs it says thats possible but there is no option.

![by default 2015-05-29 at 7 33 32 pm](https://cloud.githubusercontent.com/assets/1565502/7894903/d05a0824-0639-11e5-93a6-aee7b56ce211.png)

**Comment by johngodley** [comment]
Press the cog icon to get advanced options including type of redirect.

**Comment by mikezielonka** [comment]
@johngodley that only shows the description.

Made a quick video showing what happens: http://cloud.tunas.co/3p2S1y2s3I0u

**Comment by johngodley** [comment]
Sorry I didn't notice that you specified the login status match. Currently picking a HTTP code is only available for a standard redirection, and is available by pressing the cog button. For a login redirect it defaults to a 301. I'll mark this as an enhancement for a future version.

**Comment by mikezielonka** [comment]
I had to set a 302.  Our use case was the entire site was requested to be taken down but we were allowed to leave a splash page.




There are several maintainance mode plugins, but none allow you to set a WP page as your splash page and most didn't support 302s.




Thanks for adding an enhancement request.
