### ISSUE TITLE
Translation of plugin is not loaded

### ISSUE THREAD

**Issue by dodog** [johngodley/redirection#590]
Translation of plugin is not loaded. I tried clean wordpress installation, no plugins, tried to switch to other languages, none of them are displayed in Redirection plugin. Always stays in English.
I also tried to force translation with "define ('WPLANG', 'de_DE');" - does not work either. 

Is this a bug or there is some secret option to change the language?

Info:
Redirection: Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.6.21  and  PHP: 7.0.14
Browser: Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by johngodley** [comment]
Yep, it seems something changed in the translation system and it stopped working. Fixed in bfcf739ddc924f9690164cdf8dc47aa8129cb665 and released in the next version
