### ISSUE TITLE
Missing ) in models/redirect.php

### ISSUE THREAD

**Issue by Beee4life** [johngodley/redirection#591]
I was visiting a post on the front-end when this popped up in my debug bar.

<img width="1412" alt="screen shot 2017-12-31 at 16 30 44" src="https://user-images.githubusercontent.com/4508731/34462632-6d796066-ee48-11e7-9116-e5fe6f9248c8.png">

Seen on Mac with Chrome. All WP + plugins latest versions.

**Comment by johngodley** [comment]
You have an invalid regular expression in your redirect list. You'll need to locate it and add the missing bracket.

**Comment by Beee4life** [comment]
Gotcha. Will check. Kudos for quick response !

**Comment by Beee4life** [comment]
Found it... There was a ( which shouldn't be there. Thanks again.
