### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by usaksaco** [johngodley/redirection#596]
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined https://usa-ksa.com/health/wp-admin/load-scripts.php?c=1&load%5B%5D=hoverIntent,common,admin-bar,jquery-ui-widget,jquery-ui-position,wp-pointer,svg-painter,heartbeat,wp-auth-check,jquery-ui-core,j&load%5B%5D=query-ui-mouse,jquery-ui-sortable&ver=4.9.1 269
```

Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.3.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by johngodley** [comment]
Can you try temporarily disabling other plugins and see if the error goes away?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
