### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'There was a database error installing Redirection

### ISSUE THREAD

**Issue by jdistad** [johngodley/redirection#597]
TFatal error: Uncaught exception 'Exception' with message 'There was a database error installing Redirection - please post these details to https://github.com/johngodley/redirection/issues - CREATE TABLE IF NOT EXISTS `vUpwp_redirection_items` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `url` mediumtext NOT NULL, `regex` int(11) unsigned NOT NULL DEFAULT '0', `position` int(11) unsigned NOT NULL DEFAULT '0', `last_count` int(10) unsigned NOT NULL DEFAULT '0', `last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `group_id` int(11) NOT NULL DEFAULT '0', `status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled', `action_type` varchar(20) NOT NULL, `action_code` int(11) unsigned NOT NULL, `action_data` mediumtext, `match_type` varchar(20) NOT NULL, `title` varchar(50) DEFAULT NULL, PRIMARY KEY (`id`), KEY `url` (`url`(191)), KEY `status` (`status`), KEY `regex` (`regex`), KEY `group_idpos` (`group_id`,`position`), KEY `group` (`group_id`) ) DEFAULT in /home/vibesup/public_html/wp-content/plugins/redirection/models/database.php on line 112

this occurs when trying to activate the plugin... latest version of WP and plugin.

**Comment by johngodley** [comment]
It looks like your WordPress doesn't have any character set or collation settings defined. This is not standard, and is causing the error.

These can be set by adding something like this to your `wp-config.php`:

```php
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', 'utf8mb4_unicode_ci');
```

**Comment by johngodley** [comment]
Closing for now, please reopen with more information

**Comment by jokr0815** [comment]
Hi @johngodley ,

I have the same issue, with these parameters.

My values are:
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

Exception thrown

There was a database error installing Redirection - please post these details to https://github.com/johngodley/redirection/issues - CREATE TABLE IF NOT EXISTS `wp_redirection_items` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `url` mediumtext NOT NULL, `regex` int(11) unsigned NOT NULL DEFAULT '0', `position` int(11) unsigned NOT NULL DEFAULT '0', `last_count` int(10) unsigned NOT NULL DEFAULT '0', `last_access` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `group_id` int(11) NOT NULL DEFAULT '0', `status` enum('enabled','disabled') NOT NULL DEFAULT 'enabled', `action_type` varchar(20) NOT NULL, `action_code` int(11) unsigned NOT NULL, `action_data` mediumtext, `match_type` varchar(20) NOT NULL, `title` text, PRIMARY KEY (`id`), KEY `url` (`url`(191)), KEY `status` (`status`), KEY `regex` (`regex`), KEY `group_idpos` (`group_id`,`position`), KEY `group` (`group_id`) ) DEFAULT CHARACTER SET utf8mb4 COLLATE=utf8mb4_unicode_520_ci = 

Even after trying to manually creating the table, it is not working. 
I'm wondering about the equal sign at the end.

Thanks and kind regards
Jo
