### ISSUE TITLE
URL Monitor of custom post types

### ISSUE THREAD

**Issue by littlbr** [johngodley/redirection#599]
Hi all,

I may have missed something but is it possible to monitor url changes on custom post types?

I've actived the plugin (version 2.10.1 on wp 2.9.1). Then I actived the URL Monitor for pages and posts.  

The monitoring works perfectly for pages and create 301 on slug modifications but does not work for custom post types (a "team" post type in this instance).

Does the plugin url monitor only works for pages and regular posts? Is there a setting I missed? Is there a specific argument that needs to be set in the custom post type registration function to make it work? A filter?

Thanks!

**Comment by johngodley** [comment]
Added in #575, and due to be released in the next version!

**Comment by littlbr** [comment]
That's great!
Thanks for the quick turnaround!
