### ISSUE TITLE
2 different domains but the same path

### ISSUE THREAD

**Issue by nori832** [johngodley/redirection#601]
I have 2 urls. www.aaa.ca/abc and www.bbb.ca/abc (2 different domains but the same path). Then I want to set up the following redirection.
From www.aaa.ca/abc to www.aaa.ca/english
From www.bbb.ca/abc to www.bbb.ca/french

Because Redirections plug-in only accepts relative URLs, both redirects to www.aaa.ca/english. Are there any ways to redirect to a different page?

**Comment by johngodley** [comment]
Sorry, at the moment there is no way to do this. There is a feature request for this ability in #112
