### ISSUE TITLE
Redirect Page by Page to a New URL

### ISSUE THREAD

**Issue by aparsai** [johngodley/redirection#607]
### Summary

I would like to redirect every single on my original website to a new website. For example

http://www.abc.com/G232h2m ----> http://www.xyz.com/G232h2m

I want to be able to do it bulk to every single page.

### Actual Behavior

None

### Steps to reproduce

None

### Environment

Wordpress 4.9.1

**Comment by johngodley** [comment]
See https://redirection.me/support/redirect-regular-expressions/#common
