### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by rets85** [johngodley/redirection#609]
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any errors are shown?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
