### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by kpirnie** [johngodley/redirection#611]
```
Plugin: 2.10.1
WordPress: 4.9.1
PHP: 7.0.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: Invalid file (84)
Action: red_import_data
Params: {"group":2}
Code: 200 OK
Raw: {"error":{"message":"Invalid file","code":84}}
```

File is structured like:
/old-url, /new-url

**Comment by kpirnie** [comment]
I have tried single file with 2360 redirects
I have tried seperating them out into 1180 chunks, as well as 550 chunks.

Every time, produces the exact issue above

**Comment by kpirnie** [comment]
I have now split it into 100 line chunks, and the error still ocurrs

**Comment by kpirnie** [comment]
I have even gone so far as manually adding a redirect.  Exporting it through the plugin, deleted it, and then attempted to re-import it.  That also fails with the same message above.

**Comment by johngodley** [comment]
Can you upload one of the files here?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
