### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by Geppe1990** [johngodley/redirection#615]
Plugin: 2.10.1
WordPress: 4.4.2
PHP: 5.3.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

It worked fine until i had updated the plugin to 2.10.1

**Comment by johngodley** [comment]
The minimum requirement for Redirection is PHP 5.4, and you are using 5.3.29. I don't know what the behaviour of this will be.

Can you open your browser's developer console and see if any errors are shown?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
