### ISSUE TITLE
User agent match + do nothing

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#619]
If a user agent match is used in conjunction with a Do Nothing action, the action fires regardless of whether the agent matches.

This is because the user agent match in `Agent_Match::get_target` is assuming the target action will be a URL

**Comment by johngodley** [comment]
I believe this is working as intended. The returned page is whatever the page is expected to be, but the request is not logged.

**Comment by silentjon** [comment]
this still isn't working for me if 'do nothing' is chosen.. I have a custom user_agent and even if my user_agent doesn't match that, it still does nothing.
