### ISSUE TITLE
URL Monitoring option is not saved

### ISSUE THREAD

**Issue by yliharma** [johngodley/redirection#622]
### Summary

The option chosen for URL monitoring is not saved permanently.

### Steps to reproduce

1. Select the checkbox to monitor changes to posts and save settings.
2. Modify the slug of a post: the redirection is created.
3. Modify again the slug of the same post: no new redirection.
4. Save settings again and modify the slug of the same post: the redirection is created.

### Environment

Browser Chrome 62.0
WordPress 4.9.1 
Redirection 3.0 beta 1

**Comment by johngodley** [comment]
Fixed in 3.0 release
