### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by qqpokeronline** [johngodley/redirection#625]
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined http://grand77bet.live/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,jquery-ui-widget,jquery-ui-position,wp-pointer&ver=4.9.2 246
```

Plugin: 2.10.1
WordPress: 4.9.2
PHP: 5.4.45
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by johngodley** [comment]
Can you temporarily disable other plugins and see if the error goes away?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
