### ISSUE TITLE
Enhancement request: Description

### ISSUE THREAD

**Issue by ElectricFeet** [johngodley/redirection#626]
Hi there. Thanks for a really great plugin.

One enhancement I would really  like to see would be a "description" (or comment) field, which would be optional.

Reason: I often create redirects to solve a particular issue or deal with a site-wide change I made. I then forget why I did it. Was it to fix a problem last month? Or was it that big change I made 5 years ago that the search engines have got over by now? I perhaps delete it if it looks obsolete. Then it comes up in the 404s. Wash, rinse, repeat.

A "description" field would really help in remembering why the redirect was/is necessary. It needn't be shown on the main screen, but if it were shown when editing it would be super-useful.

**Comment by johngodley** [comment]
You can use the title field for this purpose. Click on the cog icon:

https://redirection.me/support/create-redirects/#advanced

**Comment by ElectricFeet** [comment]
Oh great. Thanks. That does the job!
