### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by golaspl** [johngodley/redirection#627]
Plugin: 2.10.1
WordPress: 4.9.2
PHP: 7.1.13
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by johngodley** [comment]
Can you open your browser's error console and see if anything appears there?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
