### ISSUE TITLE
Apache module doesn't write to .htaccess without setting Apache Module

### ISSUE THREAD

**Issue by garrett-eclipse** [johngodley/redirection#628]
### Summary

I created a new Group using the Apache option. Adding new redirects to this group fail to work as nothing gets written to .htaccess. After messing around I finally found this was because the Apache Module setting wasn't filled in. Adding the default path there (the same as what's shown in placeholder) caused entries to start writing to .htaccess

### Actual Behavior

Nothing was being written to the .htaccess file until I specified the Apache Module setting. It would be nice if it just took the default value which is shown in placeholder text and test if there's an .htaccess there and then use it. OR if that's not wise then when you create an Apache group it should give you a error notice if you haven't set the Apache Module.
I would prefer it just use the default, but maybe we do that plus add a notice to indicate don't forget to update your Apache Module.

### Steps to reproduce

Create a new group with Apache as the type, then add redirects to it. Check your .htaccess to find it empty.

### Environment

Chrome 63.0.3239.132
WordPress 4.9.2
Redirection 2.10.1
Apache/2.4.29 (cPanel)

**Comment by johngodley** [comment]
Sorry for the delay! Until I come up with a decent way of showing the Apache stuff I've added a note as you described - it's best if Redirection doesn't use a default. This will be in the next released version.

**Comment by garrett-eclipse** [comment]
Thanks @johngodley much appreciated
