### ISSUE TITLE
Problem starting Redirection 2.10.1

### ISSUE THREAD

**Issue by qqpokeronline** [johngodley/redirection#630]
Plugin: 2.10.1
WordPress: 4.9.2
PHP: 5.5.38
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by johngodley** [comment]
Closing as you already have the same issue reported here #625
