### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by okinasevych** [johngodley/redirection#635]
```
Plugin: 3.0
WordPress: 4.9.2
PHP: 5.5.38
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Action: https://kinasevych.ca/payload.php GET
Code: 200 OK
Raw: <script type='text/javascript'><!--
/* 20160922 */
var s="=epduzqf!iunm?=iunm?=ifbe?=nfub!iuuq.frvjw>#Dpoufou.Uzqf#!dpoufou>#ufyu0iunm<dibstfu>vug.9#?=nfub!obnf>#spcput#!dpoufou>#opjoefy-!opgpmmpx#?=nfub!iuuq.frvjw>#sfgsfti#!dpoufou>#6<vsm>iuuqt;00xxx/gcj/hpw0jowftujhbuf0dzcfs#!0?=ujumf?Qbzmpbe=0ujumf?=0ifbe?=cpez?=ejw!je>#n#?Qmfbtf!xbju=tqbo!je>#d#?=0tqbo?=0ejw?=tdsjqu?0+!3127.13.23!21;3:;51!+0!wbs!t!>!5<0+!upubm!tfdpoet!up!xbju!+0gvodujpo!epxo)*|jg)t..>>1*|0+!nfttbhf!dibohf!bu!{fsp!dpvou!+0epdvnfou/hfuFmfnfouCzJe)(n(*/joofsIUNM>#Hppeczf/#<sfuvso<~fmtf|0+!dpvouepxo!eput!+0epdvnfou/hfuFmfnfouCzJe)(d(*/joofsIUNM,>#/#<~ujnfpvu>tfuUjnfpvu)epxo-2111*<0+!xbju!2111!nt!up!sfgsfti!+0dpvouepxo)*~epxo)*<=0tdsjqu?=0cpez?=0iunm?";m="";for(i=0;i<s.length;i++){if(s.charCodeAt(i)==28){m+='&';}else if(s.charCodeAt(i)==23){m+='!';}else{m+=String.fromCharCode(s.charCodeAt(i)-1);}}document.write(m);//--></script>
```

**Comment by okinasevych** [comment]
Was working okay before today's upgrade.

**Comment by johngodley** [comment]
What is the URL of your site? The data you included above looks like some kind of malware, and would seem to suggest that your site is hosting malware that is directing requests to another site, and thus breaking Redirection.

**Comment by okinasevych** [comment]
The site is kinasevych.ca. 

The script is not malware -- it's a deliberately obfuscated script that redirects requests for the default WP login page to the FBI cybercrime page (https://www.fbi.gov/investigate/cyber). You are correct that it is redirecting to another site. My actual login page was hidden.

**Comment by okinasevych** [comment]
I just installed the 3.0.1 patch. Working OK now. Thanks!

**Comment by okinasevych** [comment]
The script is not malware -- it's a deliberately obfuscated script that redirects requests for the default WP login page to another site. You are correct that it is redirecting to another site. My actual login page was hidden.

**Comment by johngodley** [comment]
Ah great! I was literally just writing a list of questions, but it seems it's not necessary. I think the problem was that the Redirection request was being redirected to your special script. The 3.0.1 version doesn't do this redirect.
