### ISSUE TITLE
Add ability to ignore certain URLs from the logs

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#64]
This may be useful if a URL is repeatedly hit, but you don't care about it.

**Comment by lembitk** [comment]
+1

(I personally would find this especially useful w/ the 404 logs.)

**Comment by lumberjackshaw** [comment]
Per the [documentation](http://urbangiraffe.com/plugins/redirection/), I thought this was possible, but I can't seem to get it to work.

>If you do want to ignore a 404 error (for example, you site may not have a favicon.ico and you don’t want this recorded) then you should create redirections as normal, but set the action to ‘Do nothing’. As for other modules you can create redirections based upon any action or rule, or matching a particular regular expression.

**Comment by johngodley** [comment]
Long time coming, but the 'do nothing' will work as advertised in version 2.9, which along with the various other filters will allow URLs to be ignored.
