### ISSUE TITLE
Redirection not saving

### ISSUE THREAD

**Issue by Sambombe** [johngodley/redirection#641]
### Summary

After i update the plugin, today, it seems that i cant add more redirections. When i put source and target urls, it shows the "redirection saved" message, but it does not add to the list.

### Environment

Tried in chrome, firefox. Wordpress 4.9.2. Redirection 3.0.1

**Comment by johngodley** [comment]
I've released version 3.1 which may help. I will close this ticket for now, but please reopen if the problem persists
