### ISSUE TITLE
Error when trying to create a new redirection

### ISSUE THREAD

**Issue by iuato** [johngodley/redirection#643]
Plugin: 2.10.1
WordPress: 4.9.2
PHP: 5.3.3
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: Unable to add new redirect (206): Field 'last_access' doesn't have a default value
Action: red_set_redirect
Params: {"orderBy":"id","filterBy":"","filter":"","id":0,"url":"/22452847/ISTOE_Internas.*","title":"","regex":true,"match_type":"url","action_type":"url","group_id":1,"action_code":301,"action_data":{"url":"/"}}
Code: 200 OK
Raw: {"error":{"message":"Unable to add new redirect","code":206,"wpdb":"Field 'last_access' doesn't have a default value"}}

**Comment by johngodley** [comment]
Closing for now, please reopen if the problem persists
