### ISSUE TITLE
redirect error

### ISSUE THREAD

**Issue by iamallyniam** [johngodley/redirection#645]
### Summary

After activating the plugin and going to tools > redirection, this error appears.

Plugin: 3.0.1
WordPress: 4.9.2
PHP: 5.6.22
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Buster: 3.0.1 === 3.0.1
TypeError: Cannot read property 'status' of undefined

### Steps to reproduce

Explain the steps involved to reproduce the problem

-Activate plugin
-Go to tools > redirection

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Chrome  63.0.3239.132
mac os 10.12.6
Wordpress 4.9.2
Redirection 3.0.1

**Comment by johngodley** [comment]
I've now released version 3.1. I will close this ticket for now, but please reopen if the problem persists
