### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by GodThor** [johngodley/redirection#647]
I deleted a post and I have the plugin setup to monitor post changes. I then went to the redirects and clicked on enable for it. That's when I got the below error.

Oh, the URL it's being set for is: /making-a-list-reining-in-my-scattered-mind/
to go to: /

```
Plugin: 3.0.1
WordPress: 4.9.2
PHP: 7.0.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: No route was found matching the URL and request method
Action: redirection/v1/bulk/redirect/enable/?filter=making&per_page=50 POST
Params: {"items":"2238"}
Code: 404 
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
```

**Comment by johngodley** [comment]
Can you try the 3.1 beta?

https://github.com/johngodley/redirection/releases/tag/3.1

**Comment by GodThor** [comment]
No luck I'm afraid.

> Plugin: 3.1
WordPress: 4.9.2
PHP: 7.0.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: https://creativetwilight.com/wp-json/

Error: No route was found matching the URL and request method
Action: redirection/v1/bulk/redirect/enable/?orderby=id&per_page=50&_wpnonce=7d13f8aac4 POST
Params: {"items":"2238"}
Code: 404 
Raw: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
>

**Comment by johngodley** [comment]
Hmm, that's very strange. I can see that the route exists on your site. Do the other Redirection functions work ok?

**Comment by GodThor** [comment]
The redirections already in place are working still.

**Comment by johngodley** [comment]
Ok I think the problem is that you have a redirect setup on your site that is adding a trailing slash to all URLs. This is unfortunately breaking the REST API.

If you are able to go to the 'options' page in Redirection, can you try the other options for 'REST API' at the bottom of the page?

If you are unable to load the options page then go to the 'support' page and click the magic fixer button

**Comment by GodThor** [comment]
You were right about the trailing slash redirect. I forgot I had set that up. I removed that and everything is back to normal now. Also, I did try the other two REST API options prior to removing my trailing slash redirect and it didn't work.

I appreciate the quick responses and helping me resolve this.

**Comment by johngodley** [comment]
I'll see if I can reproduce the same problem and get the fix working for that situation. Thanks for the details.
