### ISSUE TITLE
Failed Update Subsequently Updated

### ISSUE THREAD

**Issue by deliadis** [johngodley/redirection#658]
I updated was updating the plugin today and got a failure. On retry it appeared to have worked. Later went in to add a Redirecy and found the following error information.

Plugin: 3.0.1
WordPress: 4.9.2
PHP: 5.6.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: Unexpected token < in JSON at position 9118
Action: redirection/v1/404 GET
Code: 200 OK
Raw: {"items":[{"ip":"0.0.184.92","id":131042,"created":"January 23, 2018","created_time":"3:42 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=4058&action=edit"},{"ip":"0.0.184.92","id":131041,"created":"January 23, 2018","created_time":"3:40 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=4058&action=edit"},{"ip":"0.0.184.92","id":131040,"created":"January 23, 2018","created_time":"3:40 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=4058&action=edit"},{"ip":"0.0.184.92","id":131039,"created":"January 23, 2018","created_time":"3:40 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=4058&action=edit"},{"ip":"0.0.211.192","id":131038,"created":"January 23, 2018","created_time":"3:39 pm","url":"\/finding-your-fire-again\/","agent":"Mozilla\/5.0 (compatible; Shareaholic\/1.0; +http:\/\/www.shareaholic.com\/steve)","referrer":null},{"ip":"0.0.211.192","id":131037,"created":"January 23, 2018","created_time":"3:38 pm","url":"\/find-fire-sm-promos\/","agent":"Mozilla\/5.0 (compatible; Shareaholic\/1.0; +http:\/\/www.shareaholic.com\/steve)","referrer":null},{"ip":"0.0.211.192","id":131036,"created":"January 23, 2018","created_time":"3:37 pm","url":"\/find-your-fire-aain\/","agent":"Mozilla\/5.0 (compatible; Shareaholic\/1.0; +http:\/\/www.shareaholic.com\/steve)","referrer":null},{"ip":"0.1.151.7","id":131035,"created":"January 23, 2018","created_time":"3:37 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Mozilla\/5.0 (compatible; +http:\/\/tweetedtimes.com)","referrer":null},{"ip":"0.0.211.192","id":131034,"created":"January 23, 2018","created_time":"3:37 pm","url":"\/auto-draft\/","agent":"Mozilla\/5.0 (compatible; Shareaholic\/1.0; +http:\/\/www.shareaholic.com\/steve)","referrer":null},{"ip":"0.0.184.92","id":131033,"created":"January 23, 2018","created_time":"3:36 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post-new.php"},{"ip":"0.0.184.92","id":131032,"created":"January 23, 2018","created_time":"3:29 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=3571&action=edit"},{"ip":"0.0.184.92","id":131031,"created":"January 23, 2018","created_time":"3:29 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=3571&action=edit"},{"ip":"0.0.184.92","id":131030,"created":"January 23, 2018","created_time":"3:29 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=3571&action=edit"},{"ip":"0.0.184.92","id":131029,"created":"January 23, 2018","created_time":"3:29 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=3571&action=edit"},{"ip":"0.0.184.92","id":131028,"created":"January 23, 2018","created_time":"3:29 pm","url":"\/wp-includes\/js\/tinymce\/skins\/wordpress\/wp-content.css?ver=4.9.2&wp-mce-4607-20171116","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/yoursmallbusinessgrowth.com\/wp-admin\/post.php?post=3571&action=edit"},{"ip":"0.0.211.177","id":131027,"created":"January 23, 2018","created_time":"2:37 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/35.0.1916.153 Safari\/537.36","referrer":null},{"ip":"0.0.211.185","id":131026,"created":"January 23, 2018","created_time":"2:13 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Java\/1.7.0_151","referrer":null},{"ip":"0.2.140.202","id":131025,"created":"January 23, 2018","created_time":"1:55 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.96 Safari\/537.36","referrer":null},{"ip":"0.0.211.177","id":131024,"created":"January 23, 2018","created_time":"1:28 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/35.0.1916.153 Safari\/537.36","referrer":null},{"ip":"0.2.250.82","id":131023,"created":"January 23, 2018","created_time":"1:28 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.21 (KHTML, like Gecko) wpif Safari\/537.21","referrer":null},{"ip":"0.0.69.198","id":131022,"created":"January 23, 2018","created_time":"1:26 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Mozilla\/5.0 (compatible; AndersPinkBot\/1.0; +http:\/\/anderspink.com\/bot.html)","referrer":"http:\/\/bit.ly\/2FZQlno"},{"ip":"0.0.61.253","id":131021,"created":"January 23, 2018","created_time":"1:25 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko\/20100101 Firefox\/53.0","referrer":null},{"ip":"0.2.164.199","id":131020,"created":"January 23, 2018","created_time":"1:22 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Mozilla\/5.0 (compatible; EveryoneSocialBot\/1.0; support@everyonesocial.com http:\/\/everyonesocial.com\/)","referrer":null},{"ip":"0.0.20.139","id":131019,"created":"January 23, 2018","created_time":"1:18 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Go-http-client\/1.1","referrer":"http:\/\/bit.ly\/2FZQlno"},{"ip":"0.0.137.154","id":131018,"created":"January 23, 2018","created_time":"1:14 pm","url":"\/6-step-to-creating-a-high-impact-growth-strategy\/?utm_sq=fnnpzjp6fa&utm_source=Twitter&utm_medium=social&utm_campaign=BizGrowSimplifd&utm_content=Passion and Self-Knowledge","agent":"Ruby","referrer":null}],"total":1516}

Error: Unexpected token < in JSON at position 332
Action: redirection/v1/group GET
Code: 200 OK
Raw: {"items":[{"id":3,"name":"Remove Year and Month","redirects":17,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":2,"name":"Modified Posts","redirects":43,"module_id":1,"moduleName":"WordPress","enabled":true},{"id":1,"name":"Redirections","redirects":26,"module_id":1,"moduleName":"WordPress","enabled":true}],"total":3}

![image](https://user-images.githubusercontent.com/8095740/35305145-47b4c0ac-0066-11e8-9a14-854381429ad1.png)

**Comment by johngodley** [comment]
Does this happen all the time, or just the once?

**Comment by deliadis** [comment]
It just happen with this last update that I applied yesterday.  - Dino

Dino Eliadis
-------------------------
DE, Inc.
117 N. Florida Ave.
Tarpon Springs, FL 34689
P: 727-421-5579
E: dino@dinoeliadis.com
W<mailto:dino@dinoeliadis.com>: www.dinoeliadis.com<http://www.dinoeliadis.com/>
Blog: www.yoursmallbusinessgrowth.com<http://www.yoursmallbusinessgrowth.com/>

**Comment by johngodley** [comment]
I've released version 3.1 which should help with this. Please let me know how it goes

**Comment by deliadis** [comment]
John, I got your email and know how important it is to know a fix worked. Applied the update and it does appear to have fixed this problem. Thanks for getting this resolved, I appreciate it. - Dino
