### ISSUE TITLE
URL Modification redirect is not created for normal pages

### ISSUE THREAD

**Issue by benjaminpick** [johngodley/redirection#66]
I am using Wordpress 4.2. 

When I change the slug of a standard wordpress page, a modified posts redirect is not created and the old URL return an 404 error. 

Browsing your code, I probably found the culprit: 
https://github.com/johngodley/redirection/blob/1e79f039511d4ef678c07ab49cd3425dec60a428/models/monitor.php#L30

`is_post_type_hierarchical` returns true and prevents the creation. When I comment out this condition, everything works again. This check has been introduced long ago in 1e79f039511d4ef678 so I wonder if a recent Wordpress version changed behavior, I cannot imagine a bug this grave be unnoticed for years. Do you remember why you introduced this check in the first place?

**Comment by johngodley** [comment]
Merging in with #143
