### ISSUE TITLE
Error when importing 301

### ISSUE THREAD

**Issue by naisgrup** [johngodley/redirection#667]
Hi, 

I created 1202 redirections with your plugin on a testing site.
Now I want to import all of them to the production site but it gives this error.
It says it does not find a matching path with the URL and the petition method.
All URLs are according to the actual production site.

I also tried to import them from .htaccess file but same problem.

Plugin: 3.0.1
WordPress: 4.9.2
PHP: 7.0.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: No se encontró la ruta que coincida con la URL y el método de la petición
Action: redirection/v1/import/file/1/ POST
Code: 404 
Raw: {"code":"rest_no_route","message":"No se encontr\u00f3 la ruta que coincida con la URL y el m\u00e9todo de la petici\u00f3n","data":{"status":404}}

**Comment by johngodley** [comment]
This is probably fixed in the 3.1 beta:

https://github.com/johngodley/redirection/releases/tag/3.1

**Comment by johngodley** [comment]
I've now released version 3.1. I will close this ticket for now, but please reopen if the problem persists
