### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by brechtp** [johngodley/redirection#674]
```
Plugin: 3.0.1
WordPress: 4.9.2
PHP: 7.0.25
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: Unexpected token < in JSON at position 0
Action: redirection/v1/404?filterBy=url&filter=goal&per_page=200 DELETE
Code: 403 
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
<script type="text/javascript">
//<![CDATA[
window.__cfRocketOptions = {byc:0,p:1516866751,petok:"3442281eef21946a2271a452e009156b8b9d96e0-1516901109-1800"};
//]]>
</script>
<script type="text/javascript" src="https://ajax.cloudflare.com/cdn-cgi/scripts/b7ef205d/cloudflare-static/rocket.min.js"></script>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/404
on this server.<br />
</p>
</body></html>

```

**Comment by johngodley** [comment]
Can you try the 3.1 beta?

https://github.com/johngodley/redirection/releases/tag/3.1

**Comment by johngodley** [comment]
I've now released version 3.1. I will close this ticket for now, but please reopen if the problem persists

**Comment by brechtp** [comment]
Does this plugin self-update or do I need to delete the old plugin and upload a new one? I’m getting a lot or “Division by 0” errors right now.

* E_WARNING : Division by zero
in cm_ tt_ grid: : build_ layout called at / www/ wp- content/ plugins/ testimonials- showcase/ ttshowcase. php (449) in ttshowcase_ show_ testimonials called at / www/ wp- includes/ shortcodes. php (319) in do_ shortcode_ tag called at ? (?) in preg_ replace_ callback called at / www/ wp- includes/ shortcodes. php (197) in do_ shortcode called at / www/ wp- content/ plugins/ testimonials- showcase/ ttshowcase. php (418) in ttshowcase_ show_ testimonials called at / www/ wp- includes/ shortcodes. php (319) in do_ shortcode_ tag called at ? (?) in preg_ replace_ callback called at / www/ wp- includes/ shortcodes. php (197) in do_ shortcode called at / www/ wp- includes/ class- wp- hook. php (286) in WP_ Hook: : apply_ filters called at / www/ wp- includes/ plugin. php (203) in apply_ filters called at / www/ wp- includes/ post- template. php (240) in the_ content called at / www/ wp- content/ themes/ genesis/ lib/ structure/ post. php (348) in genesis_ do_ post_ content called at / www/ wp- includes/ class- wp- hook. php (286) in WP_ Hook: : apply_ filters called at / www/ wp- includes/ class- wp- hook. php (310) in WP_ Hook: : do_ action called at / www/ wp- includes/ plugin. php (453) in do_ action called at / www/ wp- content/ themes/ genesis/ lib/ structure/ loops. php (92) in genesis_ standard_ loop called at / www/ wp- content/ themes/ genesis/ lib/ structure/ loops. php (41) in genesis_ do_ loop called at / www/ wp- includes/ class- wp- hook. php (286) in WP_ Hook: : apply_ filters called at / www/ wp- includes/ class- wp- hook. php (310) in WP_ Hook: : do_ action called at / www/ wp- includes/ plugin. php (453)

Brecht Palombo

I’m on the twitters ( https://twitter.com/brechtify ).

**Comment by brechtp** [comment]
Ack! Sorry that was for another plugin. Sorry :/

Brecht Palombo

I’m on the twitters ( https://twitter.com/brechtify ).
