### ISSUE TITLE
Bug on settings page

### ISSUE THREAD

**Issue by mrbm** [johngodley/redirection#676]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary
Console:
Failed to load https://www.mymappeddomain.com/wp-json/redirection/v1/group: Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.
tools.php?page=redirection.php:1 
Failed to load https://www.mymappeddomain.com/wp-json/redirection/v1/redirect?orderby=id: Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.

ON page:
Plugin: 3.0.1
WordPress: 4.9.2
PHP: 7.1.13
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Buster: 3.0.1 === 3.0.1
TypeError: Cannot read property 'status' of undefined

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do

### Actual Behavior
Set up the plugin to work in multisite environment. Activated plugin and went to settings page

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce
Activate plugin, then go to settings of plugin.  Using ubuntu 16. server pilot, digital ocean

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Can you try the 3.1 beta here?

https://github.com/johngodley/redirection/releases/tag/3.1

**Comment by johngodley** [comment]
I've now released 3.1. I will close this ticket for now, but please reopen if the problem persists
