### ISSUE TITLE
Redirection_Items is not defined

### ISSUE THREAD

**Issue by ghost** [johngodley/redirection#68]
I cannot edit existing redirects. This error is displayed in the console:

`Redirection_Items is not defined`

And when I create a new redirect it does save, but I am taken to the /wp-admin/admin-ajax.php file and this displays the source of that file on screen.

I'm using WordPress 4.3 on Azure.

**Comment by jaime8111** [comment]
I have the same problem. Anyone found the solution??

**Comment by johngodley** [comment]
The plugin has changed a lot since this report was created - are you still having the same problem? I will close this issue, but if you are then please reopen it.
