### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by gregsutliff** [johngodley/redirection#682]
I get this error when I navigate to the Redirection plugin and attempt to view my existing redirects 

```
Plugin: 3.0.1
WordPress: 4.7
PHP: 7.1.10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: Invalid JSON body passed.
Action: redirection/v1/group GET
Code: 400 
Raw: {"code":"rest_invalid_json","message":"Invalid JSON body passed.","data":{"status":400,"json_error_code":4,"json_error_message":"Syntax error"}}
```

**Comment by johngodley** [comment]
I've not see that error before. Can you try the new version 3.1 and see if it helps?

If it doesnt can you open your browser's developer console and see if any extra information is shown.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
