### ISSUE TITLE
403 error when bulk deleting (Cannot read property 'error_code' of undefined)

### ISSUE THREAD

**Issue by Beee4life** [johngodley/redirection#683]
I'm trying to bulk delete 404 items, with the button [Delete all matching "term"]. When I click the button, a 403 error shows.

Single item delete works as does deleting multiple selected items.

Plugin: 3.0.1
WordPress: 4.9.2
PHP: 5.6.30
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: Cannot read property 'error_code' of undefined
Action: redirection/v1/404?filterBy=url&filter=%2Fwp%2F&per_page=100 DELETE
Code: 403 Forbidden
Raw: {"items":[{"ip":"68.180.230.34","id":30057,"created":"January 27, 2018","created_time":"04:49","url":"\/?p=2871","agent":"Mozilla\/5.0 (compatible; Yahoo! Slurp; http:\/\/help.yahoo.com\/help\/us\/ysearch\/slurp)","referrer":null},{"ip":"62.163.255.83","id":30056,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/img\/favicons\/favicon.ico","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30055,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/img\/favicons\/favicon.png","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30054,"created":"January 27, 2018","created_time":"04:48","url":"\/wp\/wp-includes\/js\/wp-embed.min.js?ver=4.9.2","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30053,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/js\/app.js?ver=1510103154","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30052,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/plugins\/ultimate-wp-query-search-filter\/classes\/scripts\/uwpqsfscript.js?ver=1.0","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30051,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/img\/icons.svg","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30050,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/img\/logo-sk8whls.png","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30049,"created":"January 27, 2018","created_time":"04:48","url":"\/wp\/wp-includes\/js\/admin-bar.min.js?ver=4.9.2","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30048,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/plugins\/fitvids-for-wordpress\/jquery.fitvids.js?ver=1.1","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30047,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/js\/app.js?ver=1510103154","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30046,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/plugins\/ultimate-wp-query-search-filter\/classes\/scripts\/uwpqsfscript.js?ver=1.0","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30045,"created":"January 27, 2018","created_time":"04:48","url":"\/wp\/wp-includes\/js\/wp-embed.min.js?ver=4.9.2","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30044,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/css\/plugins.css?ver=1514764800","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30043,"created":"January 27, 2018","created_time":"04:48","url":"\/wp\/wp-includes\/css\/admin-bar.min.css?ver=4.9.2","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30042,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/css\/layout.css?ver=4.9.2","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30041,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/themes\/sk8whls\/assets\/js\/head.js?ver=1510103154","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30040,"created":"January 27, 2018","created_time":"04:48","url":"\/content\/plugins\/ultimate-wp-query-search-filter\/themes\/default.css?ver=all","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30039,"created":"January 27, 2018","created_time":"04:48","url":"\/wp\/wp-includes\/css\/dashicons.min.css?ver=4.9.2","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php"},{"ip":"62.163.255.83","id":30038,"created":"January 27, 2018","created_time":"04:48","url":"\/wp\/wp-admin\/tools.php?page=redirection.php","agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","referrer":"http:\/\/www.sk8whls.com\/wp\/wp-admin\/tools.php?page=redirection.php&sub=404s"},{"ip":"0.1.100.64","id":30036,"created":"January 27, 2018","created_time":"03:37","url":"\/wp-content\/plugins\/wpwhatsmyrankvideoregular-unlimited\/php-ofc-library\/ofc_upload_image.php","agent":"Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/42.0.2311.152 Safari\/537.36","referrer":"http:\/\/sk8whls.com\/wp-content\/plugins\/wpwhatsmyrankvideoregular-unlimited\/php-ofc-library\/ofc_upload_image.php"},{"ip":"0.0.72.153","id":30035,"created":"January 27, 2018","created_time":"02:34","url":"\/wp-login.php","agent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/51.0.2704.103 Safari\/537.36","referrer":null},{"ip":"0.0.77.115","id":30034,"created":"January 27, 2018","created_time":"01:09","url":"\/license.php","agent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.94 Safari\/537.36","referrer":null},{"ip":"0.1.2.201","id":30033,"created":"January 27, 2018","created_time":"00:27","url":"\/content\/plugins\/jetpack\/css\/jetpack.css?ver=5.4","agent":"Mozilla\/5.0 (compatible; Googlebot\/2.1; +http:\/\/www.google.com\/bot.html)","referrer":"http:\/\/www.sk8whls.com\/wheel\/classic-full-shape-mariano-praise\/"},{"ip":"0.0.144.249","id":30032,"created":"January 27, 2018","created_time":"00:10","url":"\/skateboard-wheels\/index.php","agent":"Mozilla\/5.0 (Windows NT 5.0; rv:44.0) Gecko\/20100101 Firefox\/44.0","referrer":"http:\/\/www.sk8whls.com\/index.php"}],"total":707}

Latest Chrome browser
WordPress 4.9.2
Redirection 3.0.1

**Comment by johngodley** [comment]
Can you try version 3.1? I will close this ticket for now, but please reopen if the problem persists

**Comment by Beee4life** [comment]
With 3.1 I don't get any errors, but I also don't get a confirmation that my action was successful. Instead I get forwarded to the (unfiltered) 404 log.

**Comment by Beee4life** [comment]
Unfortunately can't update it on some sites, since they rely on wpackagist and fetching the latest release doesn't seem to work.
