### ISSUE TITLE
Problem on Plugin Status

### ISSUE THREAD

**Issue by MamCastro** [johngodley/redirection#689]
### There is an problem on Plugin Status

I had a problem with version 3.01 so I tried de 3.1 Beta. Anyway, it's the first time I am triyng your plugin. Although it looks like ok now, I have this message even after clicking on Magic Fix:

"Problem REST API returns an error code (40x - https://hotelcoquille.com.br/wp-json/)"

All the other lines are "Good".

### Environment

I am using Google Chrome (63.0.3239.132 64 bits), WP 4.9.2, Redirection 3.1

Do you think I need to do somehing?
Thank you.

**Comment by johngodley** [comment]
Apart from the message does the plugin work ok?

**Comment by MamCastro** [comment]
Yes... It is working. :)

**Comment by johngodley** [comment]
Ok, I think I might know why it's reporting an error when there isn't one. This is probably fixed in 3.1, but even if it isn't you can safely ignore the warning. I'll close this for now
