### ISSUE TITLE
It doesn't redirect

### ISSUE THREAD

**Issue by frappacchio** [johngodley/redirection#695]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

After a redirect (type URL) has been addded to the redirect list it doesn't works.

### Actual Behavior

I add a redirect to the list within a specific group. I save and it seems ok. But if i visit the old url it doesn't redirect me to the new url.

I'm using Chrome/Firefox for Mac, Wordpress 4.9.2 and Redirection 3.1

**Comment by johngodley** [comment]
What is the URL and what is the redirect you created for it?

**Comment by frappacchio** [comment]
You need specific url?

**Comment by johngodley** [comment]
Yes. The only information I have at the moment is 'it doesnt work'

**Comment by frappacchio** [comment]
the old url is
https://www.cinemagay.it/classifiche/2017/10-v-i-p-dellanno-2017/
the new one is 
https://www.cinemagay.it/classifiche/2018/10-v-i-p-dellanno-2017/
Thanks

**Comment by johngodley** [comment]
What source URL do you have in Redirection to match this?

**Comment by frappacchio** [comment]
It seems not saved in the list. 
I'm tryng to add it again but it doesn't save it.
It tells me "Redirection saved" but it's not
<img width="1129" alt="schermata 2018-01-29 alle 09 03 34" src="https://user-images.githubusercontent.com/4427246/35499591-5fa3ed84-04d3-11e8-9bab-48f22ff22e15.png">

**Comment by johngodley** [comment]
Sorry for taking so long to reply. Version 3.2 has some changes in it that might help. Can you try that and let me know?

**Comment by frappacchio** [comment]
It seems fixed the problem. I will try to import/export redirections and i
will tell you.
Thanks for your support!

Il giorno sab 17 feb 2018 alle 19:51 John <notifications@github.com> ha
scritto:
