### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by joethunderbolt** [johngodley/redirection#699]
Redirection tool isn't working.

Deleted cache history.

![screen shot 2018-01-29 at 11 12 49](https://user-images.githubusercontent.com/35920259/35507676-7fd80010-04e5-11e8-80ed-42baaa5f192e.png)

**Comment by deLisle** [comment]
Same here!

**Comment by johngodley** [comment]
Version 3.1 was released at the weekend. Can you try that?

**Comment by deLisle** [comment]
That is the one i have that gives that error

**Comment by deLisle** [comment]
Actually my error is a little different from original poster.
Image is attached.
<img width="1285" alt="screen shot 2018-01-29 at 13 56 58" src="https://user-images.githubusercontent.com/195763/35511476-60175eb2-04fc-11e8-9fc7-ac9a77b90e84.png">

**Comment by johngodley** [comment]
Can you post that as a separate issue? The original poster is using version 3.0 and that's the probably the problem there, while yours looks like something else.

**Comment by deLisle** [comment]
Done.

**Comment by johngodley** [comment]
@joethunderbolt are you seeing the same problem after updating?

**Comment by johngodley** [comment]
Closing this for now, please reopen with more details
