### ISSUE TITLE
Can't save or edit redirects with version 3.1 and 3.1.1

### ISSUE THREAD

**Issue by deLisle** [johngodley/redirection#700]
When saving a new redirect or editing a new redirect i get this error. See screenshot.
<img width="1285" alt="screen shot 2018-01-29 at 13 56 58" src="https://user-images.githubusercontent.com/195763/35511662-15ec0274-04fd-11e8-98be-be414f383cdb.png">

**Comment by deLisle** [comment]
Even with version 3.1.1 it still gives the same error.

**Comment by johngodley** [comment]
Yes, 3.1.1 fixes another problem.

I don't currently know what is causing the missing route message. When I look at your /wp-json/ I can see the route is defined.

Are you running any code that might be modifying the REST API in anyway?

Is this error only when adding a redirect? For example, can you see a list of your redirects? Can you view your logs? Can you create a group on the groups page?

**Comment by deLisle** [comment]
We are not modifying the rest api in anyway.
The error is when adding a new redirect or editing a redirect.
We can see the list of already created redirects etc.

**Comment by johngodley** [comment]
Can you create a group or save the settings? I'm wondering if the error occurs when data is saved as opposed to read.

**Comment by deLisle** [comment]
New groups cannot be created. It says group saved but it does not show up even after reload.
No error is shown here.

**Comment by johngodley** [comment]
Would it be possible to get a login to the site to see if I can find out what's happening? I suspect there's a server configuration that I'm not able to reproduce. If that's ok I can be contact at https://redirection.me/contact/

**Comment by deLisle** [comment]
Let's start with you explaining how your debugging would be done and if i can do it on my end first. Then we might give you access.

**Comment by deLisle** [comment]
I thought it would go quicker if you just tested yourself.
I've sent you a message through the contact form provided.
Please keep me posted. Thank you.

**Comment by johngodley** [comment]
👍 I will just be trying to reproduce the problem and then see what the request data is, and then see if I can modify this to avoid the error

**Comment by johngodley** [comment]
To finish this off I discovered that a redirect was adding a trailing slash to the requests, causing POSTS to fail. Adding an exception for /wp-json/ fixed the problem, and I'll look into seeing if it can be worked around or identified in the plugin.

**Comment by thatwpdeveloper** [comment]
@johngodley how exactly did you fix this part? I am facing the same issue.
