### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by logcontrol-hcs** [johngodley/redirection#701]
I'm getting the "Something went wrong" message after installing the plugin to our site (http://www.logcontrol.hu) and clicked Setting in WP's plugin manager. Tried to disable all other plugins, cleared cache, tried another browser - no success. 
I tried it on my local XAMPP, and I don't get this error. Please help. Thx.

```
Plugin: 3.1
WordPress: 4.9.2 (single)
PHP: 5.6.31
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: http://www.logcontrol.hu/wp-json/

Error: Unexpected token < in JSON at position 0
Action: redirection/v1/setting GET
Code: 400 Bad Request
Raw: <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by johngodley** [comment]
The server is blocking requests. This may be caused by a security plugin. Are you running anything on the live site that you aren't on the local site?

Does the error occur on every page or just the settings page?

**Comment by logcontrol-hcs** [comment]
Thanks for your reply. The live site and the local site are identical. I've
disabled all other plugins but it did not resolve the problem. The error
shows up on every page of the plugin, not just on settings.


Tisztelettel:

*Horváth Csaba*
horvath.csaba@logcontrol.hu | +36 30 643-5477


* <http://www.logcontrol.hu>*
LogControl Kft. | 4028 Debrecen, Sámsoni út 16/A

2018-01-30 20:48 GMT+01:00 John <notifications@github.com>:

**Comment by johngodley** [comment]
Sorry for the delay. I think you've now removed Redirection from your site?

**Comment by logcontrol-hcs** [comment]
No problem. I've removed the plugin from the live site, and using another redirection plugin. In case wo need advanced redirection features, I will give it another try and if the problem arises again, I will make a publicly available site where you may test the behaviour.
