### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by tarousan** [johngodley/redirection#702]
Nice to meet you, I will contact you from Japan.
My name is tarousan.
I started using Redirection,
It seems that reading failed.
Please teach me how to solve it.
I have little knowledge, so please teach it easier to understand and easy.
I look forward to hearing from you.

It is the contents of the following.

```
Plugin: 3.1
WordPress: 4.9.2 (single)
PHP: 7.0.18
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: https://〇〇〇.com/wp-json/

Error: Failed to fetch

Error: Failed to fetch
```

〇〇〇.com・・・domein

**Comment by tarousan** [comment]
> bloglabs

ゥ

**Comment by johngodley** [comment]
Did you fix the problem? If so, how did you do that?
