### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by schubertb2b** [johngodley/redirection#703]
```
Plugin: 3.1
WordPress: 4.9.2 (single)
PHP: 7.0.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: https://dev-camfil-apc.pantheonsite.io/wp-json/

Error: Failed to fetch

Error: Failed to fetch
```

**Comment by schubertb2b** [comment]
Version 3.0.1 worked. The latest update causes plugin to stop working. Wondering if the code is trying to load using the SERVER_NAME or other variable, and not HTTP_HOST.

**Comment by bfalla** [comment]
I am having this same issue. To make matters worse, I need to remove an active redirect that was created through the plugin but because of this issue, no redirects are visible. Where can I manually remove it?

**Comment by schubertb2b** [comment]
@bfalla I restored the previous version, 3.0.1 and that resolved the issue for me.

If you need it, I can upload the previous version of the plugin files.

**Comment by bfalla** [comment]
@schubertb2b Yes, that would be great. Thank you!

**Comment by schubertb2b** [comment]
Sure. Just comment out the current version you have running now, extract these files and put them in its place.
[redirection.zip](https://github.com/johngodley/redirection/files/1675303/redirection.zip)

**Comment by bfalla** [comment]
Awesome. Thanks again!

**Comment by johngodley** [comment]
You can find older versions of the plugin on the plugin page:

https://wordpress.org/plugins/redirection/advanced/

Version 3.1.1 should fix the original problem.
