### ISSUE TITLE
Redirection Error/ please help me why is that happening?

### ISSUE THREAD

**Issue by mawaw1** [johngodley/redirection#707]
my website is www.freedom-pdf.com without https 
the problem happened after updating to last version :(

WordPress REST API | Problem REST API returns an error code (40x - https://www.freedom-pdf.com/wp-json/)
-- | --
Problem REST API is not working so routes not checked
Good All tables present
Good Valid groups detected
Good All redirects have a valid group
Good Post monitor group is valid

```
Plugin: 3.1
WordPress: 4.9.2 (single)
PHP: 7.2.1
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: https://www.freedom-pdf.com/wp-json/

Error: Failed to fetch

Error: Failed to fetch
```

**Comment by johngodley** [comment]
Reposted from #691. Please dont post the same problem multiple times. It just means I have to spend more time reading these and less time finding the problem.

**Comment by mawaw1** [comment]
thank you so much, Sir
it is now fixed after new update
