### ISSUE TITLE
Redirection not working

### ISSUE THREAD

**Issue by jessmindelll** [johngodley/redirection#715]
On managewp I am getting an error message when I try and make redirects for any of our sites.
![something wrong with redirects](https://user-images.githubusercontent.com/36037141/35677132-5e7afffe-0746-11e8-91cc-65ec55629c96.PNG)
Any ideas?

**Comment by johngodley** [comment]
Can you try version 3.1.1?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
