### ISSUE TITLE
Can't Delete Redirection

### ISSUE THREAD

**Issue by ChrisWebAdmin** [johngodley/redirection#717]
### Summary

Not sure how it happened but I discovered a redirection was created from an existing page back to itself. When Google Search Console alerted me to the issue I tried to delete the redirect but, although it will allow an edit, nothing happens when I click Delete. 

### Actual Behavior

I have solved the temporary issue of the page by editing the Source URL to something that doesn't exist so anyone now trying to access the page will be able to get through but I would like to be able to delete it permanently. Also for a future update perhaps you could create an error message that alerts the user if they accidentally create a redirect using the same Source and Target URLs.

### Steps to reproduce

I created a new redirect and used the same URL for the Source and the Target. It created the redirect just fine. Tried to then delete the redirect but it didn't. Then edited the URL to point to the correct page so it will work.

### Environment

Google Chrome, Redirection Version 3.1.1, WordPress 4.9.2.

**Comment by johngodley** [comment]
Can you open your browser's developer console and try and delete something - are any errors shown?

**Comment by ChrisWebAdmin** [comment]
Oddly enough after two days of not being able to delete anything I can now do so. 

I would like to request that you consider the infinite loop prevention feature though to make sure that we aren't redirecting to the same page. I don't know how they got added but they made several pages inaccessible.
