### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by thomascreative** [johngodley/redirection#721]
```
Plugin: 3.1.1
WordPress: 4.9.2 (single)
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: https://operative2018.wpengine.com/wp-json/

Error: Failed to fetch

Error: Failed to fetch
```

**Comment by johngodley** [comment]
I think this may be fixed with the 3.2 beta:

https://github.com/johngodley/redirection/releases/tag/3.2-beta

You may need to visit the 'support' page of the plugin.

**Comment by thomascreative** [comment]
Thanks! Gave it a try an no luck, still erroring out. I'll check on the author support page.

**Comment by thomascreative** [comment]
Nevermind. I clicked the "Magic Fix" button and it fixed! Thanks again.
