### ISSUE TITLE
Show more log information

### ISSUE THREAD

**Issue by johngodley** [johngodley/redirection#722]
For a given logged URL show more information such as:

- HTTP code returned to the user
- The redirect that handled it

<blockquote>
It would be nice to know which redirect handled the log entry.

Right now, you have the following columns on the log page: Date, Source URL, Referrer, and IP. You also show the transformed URL and User Agent, but only when hovering over a row,

I would like to see columns that include: Date, Source/Transformed URL, Return Status, Redirect, and IP.

Source/Transformed URL would be similar to how it is now, but the Transformed URL should be always visible. Return Status would be the HTTP Status that was returned. Redirect would show the first 20'ish characters of the redirect URL and have an Edit action that would be like the one of the Redirects page.

Here is an example of the contrast issue I'm talking about...it has to do with the text only visible when hovering over a row...
</blockquote>

<img width="638" alt="redirection-contrast" src="https://user-images.githubusercontent.com/1277682/35767952-f877e2be-08ec-11e8-9b7a-a379437feba1.png">

**Comment by darklx** [comment]
+1

**Comment by darklx** [comment]
+1 I want to see whith page cause the 404 error by referrer.

**Comment by SherylHohman** [comment]
I concur. I often wish I could see which redirect rule was invoked, via the log entries.  
Is this information currently stored in the db?   If so, I'll take a look to see if this is something I can do.   

I do not think I would venture into modifying the database, though, even for a personal customized fork.  
At least not at this time.
