### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by legarreta** [johngodley/redirection#725]
Not sure why I am getting this error...turned off all my plugins and everything. Any help would be appreciated! 

```
Plugin: 3.1.1
WordPress: 4.9.2 (single)
PHP: 7.0.26
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: https://freshlypoppedculture.com/wp-json/

Error: Cookie nonce is invalid

Error: Cookie nonce is invalid
```

**Comment by johngodley** [comment]
Can you try the 3.2 beta and let me know how it goes?

https://github.com/johngodley/redirection/releases/tag/3.2-beta

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
