### ISSUE TITLE
Rest-Api Error

### ISSUE THREAD

**Issue by scshuttergirl** [johngodley/redirection#729]
Hi,

I’m getting a rest api issue under the support tab that looks something like this. 
------------
WordPress Problem REST API returns an error code (40x -
Redirection routes Problem REST API is not working so routes not checked
------------

I tried adding the /wp-json/ to my url, and it came up with a lot of data. I tried the magic fix. I tried installing the beta. 

Under Options - Rest api, it was set for this:
Proxy over Admin ajax (depracated)

Tried changing to the default wp-jason (preferred). That didn’t work I tried the magic fix after that. It changed it back and still didn’t work.

I’m using: 

Google Chrome is up to date
Version 64.0.3282.140 (Official Build) (64-bit)

Wordpress version 4.9.2

Redirection Beta 3.2

I am running the wordfence plugin for security, not sure if that would cause a problem. I didn’t see any data about the rest-api in the options for it.

I also recently did an SSL certificate for my website through bluehost. Bluehost support told me that they took care of any backend needed things to redirect http: to https. 

I have spent all day reading support and googling this and trying to fix it and am at a loss. Any ideas as to what is causing this and how to fix it?

Thanks!

**Comment by johngodley** [comment]
Is Redirection otherwise working? What is your site's URL?

**Comment by scshuttergirl** [comment]
Thank you, and i appreciate your help, but I decided to go another route.
