### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by hsuanhan** [johngodley/redirection#737]
```
Plugin: 3.1.1
WordPress: 4.9.3 (single)
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
REST API: http://threatready.staging.wpengine.com/index.php?rest_route=/

Error: NetworkError when attempting to fetch resource.
```

**Comment by johngodley** [comment]
Does this always happen? A NetworkError is usually caused because you have no internet connection

**Comment by hsuanhan** [comment]
No this just started happening. I've tried to deactivate all the plugins on the staging site.

Here's what I see on the production site:

Plugin: 3.1.1
WordPress: 4.9.3 (single)
PHP: 5.6.31-4+wpengine10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
REST API: http://www.getthreatready.com/index.php?rest_route=/

Error: Failed to fetch

**Comment by johngodley** [comment]
Can you try the 3.2 beta? It has several changes that may help here:

https://github.com/johngodley/redirection/releases/tag/3.2-beta

If it doesn't can you open your browser's developer console and see if any errors are shown?

**Comment by hsuanhan** [comment]
Ah the developer tools helped. It was an SSL issue. I'm all set now. Thanks!

**Comment by johngodley** [comment]
Great! Can I ask what the SSL issue was? It might help me track down some other related issues

**Comment by hsuanhan** [comment]
The console message said that something was being blocked because it was http instead of https.

I used my existing Really Simple SSL plugin to flush the rewrite rules and that resolved the issue.
