### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by MarceloPedra** [johngodley/redirection#740]
Hello! Just updated the plugin and this happened. 
I'm using Cloudflare with Supersonic plugin which is know to block some nonces. It implements Page Rules at Cloudflare: see its FAQ about Page Rules, https://wordpress.org/plugins/supersonic/#faq

Let me know what other information may you need.
Please tell if there is any workaround that don't consist in uninstalling Supersonic :-)

```
Plugin: 3.1.1
WordPress: 4.9.4 (single)
PHP: 7.1.13
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: http://serfiscal.org/wp-json/

Error: La cookie nonce no es válida
Action: redirection/v1/setting GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"La cookie nonce no es v\u00e1lida","data":{"status":403}}

Error: La cookie nonce no es válida
Action: redirection/v1/plugin GET
Code: 403 Forbidden
Raw: {"code":"rest_cookie_invalid_nonce","message":"La cookie nonce no es v\u00e1lida","data":{"status":403}}
```

Best regards
Marcelo

**Comment by johngodley** [comment]
I haven't used the plugin, but can you modify the rules to also bypass /wp-json/ ?

**Comment by johngodley** [comment]
Can you try the 3.2 beta and let me know how it goes?

https://github.com/johngodley/redirection/releases/tag/3.2-beta

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
