### ISSUE TITLE
Even after deleting the redirection rule it is still shown in list

### ISSUE THREAD

**Issue by rpanday** [johngodley/redirection#741]
### Summary
Even after deleting the redirection rule it is still shown in list

I click the delete button below a rule, I see the loader icon and after that the rule is still visible in the list. The behavior is same if I select rule/many rules, select delete option from drop down on top left and hit apply.
In fact the reset hits button also doesn't do anything and I still see the count as it is. I expected the hit count to go to zero after resetting.

### Steps to reproduce
Just try to delete a rule or try to reset hits.

### Environment
Google Chrome, WP 4.9.3, Latest redirection plugin 3.1

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
