### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by creizic** [johngodley/redirection#749]
can you help me ? 

Plugin: 3.1.1
WordPress: 4.9.4 (single)
PHP: 5.6.33
Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
REST API: https://we-expert.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

Error: Unexpected token < in JSON at position 0
Action: redirection/v1/redirect POST
Params: {"id":0,"url":"http://we-expert.com/qui-suis-je/","title":"","regex":false,"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"https://we-expert.com/pawinee-klinkhajorn-2/"}}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-admin/admin-ajax.php
on this server.<br />
</p>
</body></html>

Error: Unexpected token < in JSON at position 0
Action: redirection/v1/redirect POST
Params: {"id":0,"url":"http://we-expert.com/qui-suis-je/","title":"","regex":false,"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"https://we-expert.com/pawinee-klinkhajorn-2/"}}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-admin/admin-ajax.php
on this server.<br />
</p>
</body></html>

```

**Comment by johngodley** [comment]
Does this error only happen when you try and create something? Are you running any kind of security plugins?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
