### ISSUE TITLE
redirection error

### ISSUE THREAD

**Issue by yeniugo** [johngodley/redirection#750]
##　error message
Plugin: 3.1.1
WordPress: 4.9.1 (single)
PHP: 5.4.16
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
REST API: http://www.yeniugo.com/wp-json/

Error: Failed to fetch

Error: Failed to fetch

----------------------------------------------------------------------------------------

and i donot know，how to fix it?

**Comment by johngodley** [comment]
Can you try the 3.2 beta and let me know how it goes?

https://github.com/johngodley/redirection/releases/tag/3.2-beta

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
