### ISSUE TITLE
.htaccess not being updated

### ISSUE THREAD

**Issue by hariv1505** [johngodley/redirection#754]
### Summary

.htaccess not being updated

### Actual Behavior

-  When I go to visit a page with the correct redirect URL, I get a 404
- I checked the .htaccess file and saw nothing has been updated
- Back on the 'Options' screen, there's no evidence that the Apache module was populated (not sure if that textbox where its filled out should show where it is currently set to) 

### Steps to reproduce

- Set up redirects, and ensured redirections group is enabled
- Set custom Apache module, then clicking 'Update' it says everything is saved

### Environment

- Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- WordPress 4.9.4
- Redirection plugin is the latest version (just downloaded it)

**Comment by johngodley** [comment]
Can you tell me what your setting is for the Apache module? Does your server have the ability to write to that location?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details

**Comment by sgjackman** [comment]
Hi, I'm having this issue as well. The .htaccess file is writeable, but nothing ever gets added to it if I enter the path to the htaccess file in the options screen:
eg. /home/user/public_html/.htaccess

Also, if I enter a different filename, the file gets created, but is empty:
/home/ionline/public_html/.htaccess_tmp

**Comment by okadots** [comment]
also having this issue, but only on production.  locally, i add the htaccess path, the option is saved when i go back to the options page.  on the production site, i add the path, save and then go back to the options page and the path is gone.
