### ISSUE TITLE
[question] Avoid redirection chain.

### ISSUE THREAD

**Issue by jd440** [johngodley/redirection#756]
Hi John,

This is not an issue but a question.
I check on FAQ but I didn't find answer.

If we create successive redirection, is there a way to correct any rule matching to avoid, redirection chain.

Example.
Day 1
/a/ -> /b/

day 2
/b/ -> /c/

day 3
/c/ -> /d/

so if we call /a/ we will get a chain of redirection as
/a/ -> /b/ -> /c/ -> /d/
Is there any way get 
/a/ -> /d/
by correcting to 
Rules:
- /a/ -> /d/
- /b/ -> /d/
- /c/ -> /d/

thanks

**Comment by johngodley** [comment]
You'll need to do this yourself, there's no automatic checking as it could get very complicated with regular expressions and different matching rules.

**Comment by jd440** [comment]
Thanks @johngodley for your answer

That's what i will do But it will very interesting to get this feature, at least for the simpliest one.

**Comment by johngodley** [comment]
There is a feature request to do something here:

https://github.com/johngodley/redirection/issues/82

It's certainly something I intend to include at some point.
