### ISSUE TITLE
Problem with redirection

### ISSUE THREAD

**Issue by sco33** [johngodley/redirection#757]
Hi.  I am getting problem with redirection. I can't edit, remove, add new redirection or change plugin options. All other plugin is disable. Plugin status all green. Always get this error.
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 5.6.32
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
JavaScript: http://********/wp-content/plugins/redirection/redirection.js
REST API: http://********/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Action: redirection/v1/setting/ POST
Params: {"support":false,"token":"****************","monitor_post":0,"auto_target":"","expire_redirect":7,"expire_404":7,"modules":[],"newsletter":false,"lookup":"http://urbangiraffe.com/map/?ip=","monitor_types":[],"associated_redirect":"","redirect_cache":1,"ip_logging":1,"last_group_id":0,"rest_api":0,"version":"3.2","location":""}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/setting/
on this server.<br />
</p>

**Comment by johngodley** [comment]
So you can view data, but you can't update it?

Are those URLs edited by you, or did the plugin output them?

**Comment by sco33** [comment]
Hi. I changed those URL to ******* I wanted to hide my site address. Site is working without any problem. I can view all data, but I can't edit, delete, disable old redirection and add new. Always 403 error. Those old redirection is working good, I see in logs. I try to change REST API option in plugin setup but the same error 403 occur. I stop all plugin but nothing helps.

**Comment by johngodley** [comment]
Are you running any kind of security plugin, or maybe an IP blocker?

**Comment by sco33** [comment]
I only use wordfence plugin but I tested with plugin deactivated - nothing help. I also tested with 3.2.1 but problem still occur - error 403. I must use Import/Export for example redirection JSON or . htaccess and manually add new redirections.

**Comment by johngodley** [comment]
Sorry for the delay. I am seeing this error for a few people, but for different reasons.

In one instance Varnish was removing cookies, and so the request wasn't authenticated. In another I found the server was rejecting `application/json` requests for some reason.

I have a new version 3.2.1 which I think works around the application/json issue.

https://github.com/johngodley/redirection/releases/tag/3.2.1

Can you give it a try and see if it helps? If you still get the error you should try the other 'REST API' settings in the error message.
