### ISSUE TITLE
Inclompete page number, "von %(Seite)n" instead of numerical value

### ISSUE THREAD

**Issue by AlphaDE** [johngodley/redirection#758]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

Since the release of the new 3.2, the log and 404 page show a wrong string in xx entries x of y pages. German language is used.

### Actual Behavior

Instead of the numerical max page number, it shows "von %(Seite)n".

### Steps to reproduce

Install plugin, have log entries and go to the 404 or log page.

### Environment

WP 4.9.4, Redirection 3.2

**Comment by johngodley** [comment]
Can you add a screenshot showing what you mean?

**Comment by johngodley** [comment]
Ah ok. Yeah it seems to be a bad translated string:

https://translate.wordpress.org/projects/wp-plugins/redirection/stable/de/default?filters%5Bterm%5D=von+%25%28Seite%29n&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

I've added a suggestion to fix it. I'm not entirely sure how the translation process works, but I think it will have to be approved by a German translator. Thanks for noticing!

**Comment by johngodley** [comment]
I'm going to mark this as fixed, although it is pending approval by the German translation team. I don't have the ability to do this myself
