### ISSUE TITLE
PB Error  403 Forbidden

### ISSUE THREAD

**Issue by chinouk** [johngodley/redirection#761]
Hello,
i have pb for create ou modifie my redirection since few days. I was security pluging but i trash it. 
i clearing my caches.

 **************************************

WordPress REST API | Problem REST API returns an error code (40x - http://www.lesbougiesdechinouk.net/wp-json/redirection/v1/)
-- | --
Problem REST API is not working so routes not checked
***************

when i test /wp-json/ in manual he is goog !

Thanks for your help

Plugin: 3.2-beta-3
WordPress: 4.9.4 (single)
PHP: 5.5.38
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
JavaScript: http://www.lesbougiesdechinouk.net/wp-content/plugins/redirection/redirection.js
REST API: http://www.lesbougiesdechinouk.net/wp-json/

Error: Unexpected token < in JSON at position 0
Action: redirection/v1/redirect/44/ POST
Params: {"id":44,"url":"/chocolat-oranges-confites-le-the-noir-de-maison-bourgeon/","title":"","regex":false,"match_type":"url","action_type":"url","position":17,"group_id":2,"action_code":301,"action_data":{"url":"/chocolat-oranges-confites-the-maison-bourgeon/"}}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/redirect/44/
on this server.<br />
</p>
</body></html>

**Comment by johngodley** [comment]
I think you have some security software still running. If I do:

`curl -v http://www.lesbougiesdechinouk.net/wp-json/`

I get a 403 error. If I do it in the browser it's ok. It's possible that whatever is causing the 403 is being triggered by Redirection.

**Comment by chinouk** [comment]
Hello,
pourtant j'ai supprimé mon plugin  de securité et vidé mon cache j 'ai aussi desactivé aussi wp-optimise... peut etre est ce du a la nouvelle mise a jour de Wp car avant cela je n'avais aucun pb

**Comment by johngodley** [comment]
Did that fix the problem?

**Comment by chinouk** [comment]
No  :( same probleme

**Comment by chinouk** [comment]
So I: Disable all my plugin except redirection -> unsuccessful

upgrade to version 7 of php without my plugins reactivated -> without success

install an earlier version of Wp (4.8) -> without success !!

I made a reinstal of my blog to S-1 as OVH allows me (unsuccessful)

I am still stuck with this error:

**Comment by johngodley** [comment]
Would it be possible to get access to the site so I can investigate for myself? If you're ok with that I can be contacted from https://redirection.me/contact/

**Comment by johngodley** [comment]
As discussed over email, OVH seems to be blocking a POST where the content-type is set to `application/json`.

As a workaround the next version of Redirection will not set this on admin-ajax.php requests.
