### ISSUE TITLE
Pass-Through redirects stopped working after latest update

### ISSUE THREAD

**Issue by AmpInterA** [johngodley/redirection#764]
### Summary

My existing redirects stopped working after updating the plugin to its latest version. They were set up as follows:

![redirect-pass-through-screencap](https://user-images.githubusercontent.com/36412135/36101692-07931bdc-0fd8-11e8-8bf0-a7801705fd0e.jpg)

Using RegEx, btw, to handle people who can't type a URL as written (some people lowercase things).

The old behavior was simple: for example when a user manually inputs a URL or clicks on an ad with an HREF of http://www.[domain].com/Test, their browser would change the displayed URL to something like http://www.[domain].com?utm_source=Test&utm_medium=Test&utm_content=Test. This would properly trigger our google analytics and we had a script that read the URL and changed out things like the phone number on the page.

### Actual Behavior

After the plugin update to 3.2, when a user inputs the URL or clicks an ad, the URL displayed in the browser does not change.

A temporary fix involves changing the redirect to a 302 and using the full URL path as the target. This is sometimes unreliable when the user does not use www.[domain].com (i.e. they use http://[domain].com).

### Steps to reproduce

Manually typing in existing urls.

### Environment

Chrome 64.0.3282.140
WordPress 4.9.4
PHP 5.6.30
Redirection 3.2

**Comment by johngodley** [comment]
I don't think anything changed with passthroughs on the last update.

How you describe the URL changing is what a redirect does, not a passthrough - it should keep the URL the same, but load another page (pass one URL through to another).

Do you have a full URL I can test with?

**Comment by AmpInterA** [comment]
That's...interesting...apparently, I had it set up wrong for weeks yet it was working beautifully for 128 unique vanity URLs. Thinking out loud...must have something to do with it being on GoDaddy Managed Wordpress (*cough* client choice *cough*). They have not yet rolled out PHP 7 support, so we're stuck on 5.6.

Below are two testing URLs. So it seems the plugin is working as intended, but in the older version, something was amiss for me (at least in my installation).

This URL is set up as pass-through:
http://www.summitatmagnoliagreen.com/Test2
Target URL: /?utm_source=Test2&utm_medium=Test2&utm_content=Test2
Prior to the latest update, it changed the URL; now, it doesn't change the URL at all.

This URL is set up as a proper 30X redirect:
http://www.summitatmagnoliagreen.com/Test
Target URL: /?utm_source=Test&utm_medium=Test&utm_content=Test
It works for me, and you should see a phone number change in the header to 000-000-0000.

So I guess the issue was — I had it set up wrong in the first place, but for some reason, in the older plugin version, it was working like a 301 instead of a pass-through. So I guess there's actually no issue with the current plugin version. Blargh. Mondays...

**Comment by johngodley** [comment]
😄 glad it worked out in the end!
