### ISSUE TITLE
Log Rotation with WP-CLI cron not working

### ISSUE THREAD

**Issue by pfiled** [johngodley/redirection#766]
### Summary

Attempting to purge logs older than 7 days.

### Actual Behavior

No logs are removed.

### Steps to reproduce

Set `DISABLE_WP_CRON` in `wp-config.php`, run cron with wp-cli:

`wp --url=https://site-url/ cron event run redirection_log_delete`

### Environment

Multisite, Redirection v3.1.1, Wordpress 4.9, wp-cli cron

### Possible fix

The method `clean_redirection_logs()` only exists in `redirection-front.php`, which is not loaded when using wp-cli due to a check in `redirection.php` around line 67: `if ( red_is_admin() || red_is_wpcli() )`

This can be resolved by duplicating the `clean_redirection_logs()` method to the `Redirection_Admin` class, and adding the appropriate action to the constructor. However, this does result in code duplication, so another way may be preferred.

**Comment by johngodley** [comment]
Thanks for the details. For now I've just duplicated the code in e991ef1e4579876d7ceaaf7e8e8660d09d542a9a
