### ISSUE TITLE
Permissions still "Administrator"

### ISSUE THREAD

**Issue by peterdarthur** [johngodley/redirection#767]
### Summary

The following version note for Version 3.0 seems **not** to be applied in the most recent versions:

> "Permissions changed from 'administrator' role to 'manage_options' capability"

I tested with 3.1.1 and 3.2.

I've been able to manually replace the code with the capability I wanted it to be (search for "administrator" in redirection-admin.php, but I thought you should know.

**Comment by johngodley** [comment]
Yep, I see I changed it in one place but not another. Thanks for reporting.

Note you can use the filter `redirection_role` to change the capability without modifying the plugin

**Comment by johngodley** [comment]
Fixed in 1c4adfc3897cbf21b36e2c8416de8d0e488eca97
