### ISSUE TITLE
Issue with Regular Expressions

### ISSUE THREAD

**Issue by ethicssystems** [johngodley/redirection#768]
### Summary

I am trying to create a redirect that will redirect all instances of  these 404s:
![image](https://user-images.githubusercontent.com/36428462/36128629-3dba181a-1018-11e8-9837-bf6bc328c7e3.png)

I want to redirect to the hapge https://ethics.lacity.org/view/?document_id=(same number), so I set up a few reg expression redirect rules:
![image](https://user-images.githubusercontent.com/36428462/36129064-2fd9c5fe-101a-11e8-8761-f9bc1d867852.png)
![image](https://user-images.githubusercontent.com/36428462/36129071-373038ce-101a-11e8-940a-2a82cb17c866.png)

### Actual Behavior / Steps to reproduce
So when I add this redirect, then try one of those pages, it does not redirect and it still returns a 404.
![image](https://user-images.githubusercontent.com/36428462/36129080-421e5aae-101a-11e8-95f4-3cc2ef4d7cf1.png)

I have had success with other regular expression redirects, but not this one. 

I have also had no problem redirecting URLs of CFM files using Redirection.

### Environment
Google Chrome Version 63.0.3239.132
WordPress Version 4.8.5
Redirection Version 3.2

**Comment by johngodley** [comment]
You need to escape any character that is a regular expression character that you don't want treated as a regular expression character. For example, you have `?` and `.` that you want treated as normal characters, and not matches. These will need to be escaped like `\?` and `\.`

**Comment by ethicssystems** [comment]
Thank you!

---
Timothy Grant
Information Technology Director
Los Angeles City Ethics Commission
ethics.lacity.org
(213) 978-1977

*This email is not formal advice and does not provide the associated
protections.  This email may contain confidential information that is
protected from disclosure under City law.  If you are not the intended
recipient, please notify the sender and delete the message, and please do
not forward or duplicate the message.*

On Feb 14, 2018, at 11:18 PM, John <notifications@github.com> wrote:

You need to escape any character that is a regular expression character
that you don't want treated as a regular expression character. For example,
you have ? and . that you want treated as normal characters, and not
matches. These will need to be escaped like \? and \.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/johngodley/redirection/issues/768#issuecomment-365844018>,
or mute the thread
