### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by AmyWW1** [johngodley/redirection#774]
Hi there,

I am getting this error screen as soon as I open the plugin.  I have tried all the suggested fixes. The REST API is working, no security software, no caching software. I have the latest version. Can you help?

Amy

![redirect errors 2](https://user-images.githubusercontent.com/36462254/36182677-07fa23fc-10e8-11e8-87ea-a904c9d63cb6.png)
![redirect errors](https://user-images.githubusercontent.com/36462254/36182678-080dc222-10e8-11e8-929b-2b830f47fa23.png)

```
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.0.22
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
JavaScript: http://aewasp.com/wp-content/plugins/redirection/redirection.js
REST API: http://aewasp.com/wp-json/

Error: Sorry, you are not allowed to do that. (unknown)
Action: redirection/v1/redirect/?orderby=id GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

Error: Sorry, you are not allowed to do that. (unknown)
Action: redirection/v1/group/ GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by johngodley** [comment]
Something on your server is blocking the request. First could you try changing the dropdown in the error message from 'default' to one of the other options. This may help.

**Comment by johngodley** [comment]
Also, what kind of user are you logged in as - is it an admin?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
