### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by developerjillur** [johngodley/redirection#775]
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 5.6.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
JavaScript: https://devssquad.com/wp-content/plugins/redirection/redirection.js
REST API: https://devssquad.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

Problem: 
Unable to load Redirection ☹️ v3.2
This may be caused by another plugin - look at your browser's error console for more details.
If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

Also check if your browser is able to load redirection.js:

https://devssquad.com/wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75

Please note that Redirection requires the WordPress REST API to be enabled. If you have disabled this then you won't be able to use Redirection

Please see the list of common problems.

If you think Redirection is at fault then create an issue.

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any errors are shown?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
