### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by fabiostocco** [johngodley/redirection#781]
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.2.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
JavaScript: https://static.wpuphost.net/plugins/redirection/redirection.js
REST API: https://wpuphost.net/wp-json/

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if there are any errors?

**Comment by johngodley** [comment]
Closing for now. Please reopen with more details
