### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by andy7777777777** [johngodley/redirection#783]
Plugin: 3.2
WordPress: 4.9.1 (single)
PHP: 5.6.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
JavaScript: https://iteknoline.altervista.org/wp-content/plugins/redirection/redirection.js
REST API: https://iteknoline.altervista.org/wp-json/
Buster: 3.2 === 3.2

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in a
    in div
    in t
    in Connect(t)
    in n
    in np
    in t

**Comment by johngodley** [comment]
This is an interesting one. Can you open your browser's developer tools, reload the page, and see if anything is shown?

**Comment by johngodley** [comment]
Closing for now. Please reopen with more details

**Comment by andy7777777777** [comment]
Continue the problem

**Comment by johngodley** [comment]
Ok, can you post more details?

**Comment by andy7777777777** [comment]
in a
    in div
    in t
    in Connect(t)
    in n
    in np
    in t

**Comment by andy7777777777** [comment]
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 5.6.29
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
JavaScript: https://iteknoline.altervista.org/wp-content/plugins/redirection/redirection.js
REST API: https://iteknoline.altervista.org/wp-json/
Buster: 3.2 === 3.2

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    in a
    in div
    in t
    in Connect(t)
    in n
    in np
    in t

**Comment by johngodley** [comment]
> Can you open your browser's developer tools, reload the page, and see if anything is shown?

**Comment by andy7777777777** [comment]
no work

**Comment by andy7777777777** [comment]
now ok

**Comment by andy7777777777** [comment]
thanks.
