### ISSUE TITLE
Re-direction problems

### ISSUE THREAD

**Issue by Mills13** [johngodley/redirection#786]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Two problems:

if you Google Softworks AI contact us, the contact us page shows up "https://www.softworksai.com/contact-us/https://www.softworksai.com" In addition, the login page now does something goofy with the re-direct. Can you please help?

### Actual Behavior

See above
### Steps to reproduce

For the first problem, Google "SoftWorks AI contact" For the second problem, go to softworksai.com and try to press login.
### Environment

Not sure

**Comment by johngodley** [comment]
The contact page works fine for me, as does the login page.

Can you try clearing your browser cache?

**Comment by Mills13** [comment]
Hi John,

Sorry for the late response. The contact form works fine, but it doesn't work when you search on Google. See attached. Why doesn't the contact form have a www in front of it?
![contact us](https://user-images.githubusercontent.com/9371708/36437002-cfa38ba0-1633-11e8-80ba-c060e9bcfbdd.png)

**Comment by johngodley** [comment]
The contact us page has a trailing slash on the URL. If you access that then it isn't redirected. If you remove the slash it is redirected. You'll need to add a redirect for the trailing slash too.

**Comment by johngodley** [comment]
Closing for now. Please reopen with more details
