### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by notyoravggeek** [johngodley/redirection#787]
```
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.1.12
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
JavaScript: http://www.coderkick.com/wp-content/plugins/redirection/redirection.js
REST API: http://coderkick.com/wp-json/

Error: Failed to fetch
```

**Comment by johngodley** [comment]
If you open your browser's developer console are there any errors?

Just looking at the two URLs above you have one at www.coderkick.com and the other at coderkick.com. What have you configured WordPress with on the Settings > General page?

**Comment by johngodley** [comment]
Closing for now. Please reopen with more details
