### ISSUE TITLE
Immediately after update, Redirection is causing 404s

### ISSUE THREAD

**Issue by ShoreBudMike** [johngodley/redirection#793]
To help track problems please follow this template. If you can provide screenshots then that will help.

/wp-admin/admin-ajax.phpredirection/v1/?_wpnonce=e5ebf88374

The characters following the equal sign change if I log out and then back in again. But each action generates a new 404.

Explain what you are trying to do. If you want to suggest a new feature then explain what you want it to do.

All I did was install the newest Redirection update.

Explain what actually happened. If suggesting a new feature then explain what currently happens.

Every action I take while logged into my dashboard generates a new 404 (see above).

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Firefox 58.0.2, WordPress v 4.9.4, latest version of Redirection.

**Comment by johngodley** [comment]
Every action you take anywhere in WordPress, or anywhere in Redirection?

**Comment by johngodley** [comment]
Also, can you tell me what the user agent and referrer is for these 404 logs?

**Comment by ShoreBudMike** [comment]
Every action I take anywhere in WordPress. When I go back to see the 404s in Redirection, there is an almost 20-second delay before the page displays. User agent is my website.

**Comment by ShoreBudMike** [comment]
My Bulletproof Security Plugin is reporting these PHP errors beginning immediately after updating Redirection and the attempt to use the "Magic Fix."

[18-Feb-2018 19:57:56 UTC] PHP Fatal error:  Call to undefined method Red_Fixer::fix_redirect_url() in /home/content/76/6863576/html/wp-content/plugins/redirection/models/fixer.php on line 113
[18-Feb-2018 19:59:15 UTC] PHP Fatal error:  Call to undefined method Red_Fixer::fix_redirect_url() in /home/content/76/6863576/html/wp-content/plugins/redirection/models/fixer.php on line 113

**Comment by johngodley** [comment]
Ok, the last error is unrelated

**Comment by ShoreBudMike** [comment]
(Referrer is also my website) sorry.

**Comment by johngodley** [comment]
I'm unable to reproduce the original issue, but it sounds serious enough that I've reverted the version back to 3.2. I don't suppose you have a site where I can look at this problem in action?

**Comment by ShoreBudMike** [comment]
Not sure what you mean.

**Comment by johngodley** [comment]
I have reverted the plugin back to version 3.2.

You can re-install that version if you want to fix the problem immediately.

**Comment by ShoreBudMike** [comment]
When I go to the Redirection support page, it immediately shows issues with the following:
–WordPress Rest API
–Redirection routes
–Site and Home Protocol
But after a few seconds, Site and Home Protocol issue clears, leaving the other two.

**Comment by ShoreBudMike** [comment]
How do I get version 3.2?

**Comment by johngodley** [comment]
It's available from the plugin page:

https://wordpress.org/plugins/redirection/

You will need to manually install. This means downloading the file, unzipping it, and then using FTP to delete the old plugin directory and transfer the new unzipped directory into place.

See 'installing the plugin manually' here: https://redirection.me/support/installation/

Note, do not delete the plugin from your WordPress plugins list otherwise it will delete existing data.

**Comment by ShoreBudMike** [comment]
OK. Thanks.

**Comment by johngodley** [comment]
Once you've got everything back to normal can you tell me what the URLs are for 'WordPress Address' and 'Site Address' on your Settings > General page? Please can you give the full URL including http or https

**Comment by ShoreBudMike** [comment]
Reinstalling the complete Redirection plugin directory WILL NOT destroy my redirects?

**Comment by ShoreBudMike** [comment]
WordPress AND site address are both http://mike-harrison.com/

**Comment by ShoreBudMike** [comment]
Manual installation instructions say to activate the plugin after installing, but the instructions do not say to DEactivate it before installing. I need to do this correctly, please.

**Comment by ShoreBudMike** [comment]
I deactivated first, then installed, then reactivated. Installed and functioning successfully. 404s are no longer being generated. If it's helpful to you, here are the only other plugins I use:

– All In One Webmaster
– BulletProof Security Pro
– Make Plus (website theme)
– MP3-jPlayer
– Platinum SEO Pack
– WCP Contact Form
– WP Retina 2x

Thanks again for your help, John. If you need to contact me, please use the contact form on my site (mike@mike-harrison.com).
