### ISSUE TITLE
Not working Redirect in the admin panel of WP does Not add new redirects

### ISSUE THREAD

**Issue by alligatorkrk** [johngodley/redirection#794]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Not working Redirect in the admin panel of WP does Not add new redirects

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
Can you explain more about your problem?

**Comment by johngodley** [comment]
Closing for now please reopen with more information
