### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by bearonawalk** [johngodley/redirection#797]
### Summary

Updated everything on WP and your plug in. Can't find the plug in anywhere. It's activated and Installed.
If I deactivate the site works. If I activate the site gets a http 500 error.

I use around 30 redirections so this Site is basically only useful with your plug in.

Please give me an idea asap

### Environment

everything latest... firefox / edge

**Comment by johngodley** [comment]
You mean you get a 500 error everywhere on your site when the plugin is activated?

Do you have access to your server's error log?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
