### ISSUE TITLE
Redirection Plugin Conflict

### ISSUE THREAD

**Issue by jdexheimer** [johngodley/redirection#80]
I have recently discovered that this plugin conflicts with the latest versions of Jet Pack and Word Press. When activated it blocks/disables the link between Jet Pack and Word Press. I have turned all plug-ins off on our website and discovered that this plug-in was causing the issue. Any suggestions on how to fix this? I would hate to loose any blog posts that have had URLs edited. Thanks!

**Comment by FamilyFunCanada** [comment]
I'm having a similar problem. Its not letting me create groups or set up any redirection on a new addition to my multisite set up.

**Comment by johngodley** [comment]
What do you mean by 'it blocks the link between Jetpack and WordPress'? Do you see an error anywhere?
