### ISSUE TITLE
Monitor changes: WooCommerce

### ISSUE THREAD

**Issue by strarsis** [johngodley/redirection#800]
### Summary

WooCommerce related posts (products, categories, attributes, ...) are not monitored for changes.

### Actual Behavior

When a WooCommerce related post title, name, slug is changed, resulting in change of its permalink, 
the redirection plugin doesn't automatically add new redirections as it would do for pages.

### Steps to reproduce

E.g. cause change in permalink for a WooCommerce product.
Check Redirection table afterwards.

**Comment by johngodley** [comment]
Have you enabled the custom post types on the Redirection options page?

**Comment by strarsis** [comment]
Under `Options`, `URL Monitor` all have been enabled: `Monitor changes to posts`, `Monitor changes to pages`, `Monitor trashed items (will create disabled redirects)`.
Do I need a filter?

**Comment by johngodley** [comment]
Are they custom post types?

**Comment by strarsis** [comment]
@johngodley: Albeit they are added by WooCommerce, they don't belong to WordPress core, so they are custom post types (I think?).

**Comment by johngodley** [comment]
When I enable WooCommerce I see the custom types listed on Redirection's options page:

![plugin](https://user-images.githubusercontent.com/1277682/36642663-b6054db8-1a3a-11e8-985b-15ada29f23b6.jpg)

Any custom post type will appear there

**Comment by strarsis** [comment]
@johngodley: This option doesn't appear on my site at all:
![fireshot capture 120 - redirection t_ - https___www teekontor-warnemuende de_wp_wp-admin_tools php](https://user-images.githubusercontent.com/9271436/36642835-83669c12-1a45-11e8-9704-7b2bd03944b1.png)

**Comment by johngodley** [comment]
Are you using the latest versions of the plugins? I don't know a lot about WooCommerce but as mentioned before, Redirection will only look for custom post types. I don't know how 'related posts' relates to this, but if the data you want to monitor is stored in any other way than custom post types it wont be monitored.

**Comment by strarsis** [comment]
@johngodley: Indeed, updating to latest release made the new option appear.
