### ISSUE TITLE
500 Server Error with Nginx

### ISSUE THREAD

**Issue by ryansain** [johngodley/redirection#801]
Greetings, I'm trying to change permalinks on Wordpress to 'post name'. I pulled a list of my current URLs. Then I made the switch to 'post name'. I then pulled a second list of URLs and matched them up accordingly to create a CSV file of redirects. 

Old - www.mysite.com/?p=527
New - www.mysite.com/homerun/

I imported the CSV file - and all links cause a 500 server error. 

I tried a single redirect instead of a full imported list. I got the same result. 

_Nginx on ubuntu. 
Wordpress 4.5.13
Plugin 3.2
Browsers - chrome, safari_

Any advice would be appreciated. Thank you!

**Comment by johngodley** [comment]
Do you have access to your server's error log? That will probably tell you what is causing the 500 error

**Comment by ryansain** [comment]
I'll check them ASAP and reply accordingly. 

Thank you.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
