### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by dpanfili** [johngodley/redirection#803]
Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

If that doesn't help, open your browser's error console and create a new issue with the details.

Please mention redirect, and explain what you were doing at the time

Plugin: 3.0.1
WordPress: 4.9.4
PHP: 7.0.25-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Buster: 3.0.1 === 3.0.1
TypeError: Cannot read property 'status' of undefined

https://www.dropbox.com/s/27tvzxifr6iw3ic/Screenshot%202018-02-22%2014.31.45.png?dl=0

**Comment by johngodley** [comment]
Can you try upgrading to version 3.2?

**Comment by dpanfili** [comment]
Yup, that resolved. Thanks.
