### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by josegarcia74** [johngodley/redirection#804]
```
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.1.14
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
JavaScript: http://mydomain.com/wp-content/plugins/redirection/redirection.js
REST API: http://mydomain.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

Error: Invalid endpoint. (unknown)
Action: redirection/v1/setting/ GET
Code: 404 Not Found
Raw: {"code":"rest_invalid_endpoint","message":"Invalid endpoint.","data":{"status":404}}

Error: Invalid endpoint. (unknown)
Action: redirection/v1/plugin/ GET
Code: 404 Not Found
Raw: {"code":"rest_invalid_endpoint","message":"Invalid endpoint.","data":{"status":404}}
```

**Comment by johngodley** [comment]
Are you using a plugin that blocks the REST API in any way? The error message seems to be from a custom plugin

**Comment by josegarcia74** [comment]
Thank you for your quick answer John :-)
Yes, you are right. 
Is there way to jump that?

**Comment by josegarcia74** [comment]
Thank you Jhon.
Just if you think it would be possible to fix it without enabling the REST API feature?

**Comment by johngodley** [comment]
No, it requires the REST API in order to communicate with WordPress. Is there a specific reason you have disabled it?

**Comment by josegarcia74** [comment]
Just to improve security of that WP website. Do you think that is bad idea?

**Comment by johngodley** [comment]
I personally wouldn't think it improves security - the REST API is as secure as the rest of WordPress. If you wish to disable it then that's fine, although more software is likely to use it in the future.

**Comment by josegarcia74** [comment]
I really appreciate your kindness and help. I'll follow your advice. Thanks for such an excellent plugin.
