### ISSUE TITLE
Bulk Action Delete Timing Out

### ISSUE THREAD

**Issue by johnnyhimms** [johngodley/redirection#805]
### Summary

I had 655 items in the Redirect tool. I am trying to delete ALL of them and then import a new spreadsheet. It seems as if I have to delete each line item one at a time. 

### Steps to reproduce

First, I choose to show all 655 items. Then, I click the checkbox that chooses all items, choose "Delete" from the drop down, and finally hit "Apply". It loads a new page, with the left and top nav displaying, but nothing else.

### Environment

I have tried in Chrome 64 on a Mac Version 10.13.3

**Comment by johngodley** [comment]
The max visible is 200. How are you showing all 655?

Can you paste a screenshot of what you are seeing?

There is a 'delete all' button at the bottom of the page.

**Comment by johnnyhimms** [comment]
I click on the down arrow for "Screen Options," type 655, and hit apply. 

![showentries](https://user-images.githubusercontent.com/1239194/36616825-0af4e5a6-189a-11e8-9311-a876205fdf8f.png)

I don't see any "delete all" button at the bottom of the page. 

![bottom_page](https://user-images.githubusercontent.com/1239194/36616845-18511788-189a-11e8-8ec6-a6505d36990b.png)


And then this is what I see after I hit apply, after choosing them all to delete. 

![delete_screen](https://user-images.githubusercontent.com/1239194/36616854-253243dc-189a-11e8-8ee6-24affb20cc1a.png)

**Comment by johngodley** [comment]
Yeah, it could be a server timeout issue. Can you open your browser's developer tools and see if any errors are shown? If you click on the 'network' tab you should see a request to the server and it might show how long it is taking, and if it failed in some way.

An easy way to reset the plugin is to press the red 'delete plugin' button on the options page. This will clear everything from the database, allowing you to re-activate and start afresh.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
