### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by juliavaldez** [johngodley/redirection#806]
```
Plugin: 3.1.1
WordPress: 4.9.4 (single)
PHP: 5.6.32
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
REST API: https://freeeup.com/wp-json/

Error: Invalid group (46)
Action: redirection/v1/import/file/0 POST
Code: 400 Bad Request
Raw: {"code":"redirect","message":"Invalid group","data":{"status":400,"error_code":46}}
```

**Comment by johngodley** [comment]
Can you go to the plugin's 'support' page and see if the status shows any problems.

**Comment by juliavaldez** [comment]
Hi John,

The CSV was already imported successfully according to the plugin, Then the
redirects were tested working (at random) but now we see that some have
failed.
There are a few groups there (screenshot). The one where errors were
discovered is the permalinks one.

Thanks!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


*Julia Valdez*
eCommerce Content & Project Management Contractor Phone: +639154229883 | Skype:
julia_lee30
          There's a fine line between wrong and visionary.
       Unfortunately, you have to be a visionary to see it.
                                  - Sheldon, The Big Bang Theory
