### ISSUE TITLE
After Activating compression tool is not working anymore

### ISSUE THREAD

**Issue by jokr0815** [johngodley/redirection#808]
```
Plugin: 3.2.1
WordPress: 4.9.4 (single)
PHP: 5.6.33
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0
JavaScript: https://teutonia-grossenlueder.de/wp-content/plugins/redirection-master/redirection.js
REST API: https://teutonia-grossenlueder.de/wp-json/

Error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Action: redirection/v1/setting/ GET
Code: 200 OK
Raw: -no data-
```

**Comment by johngodley** [comment]
What compression tool?

**Comment by jokr0815** [comment]
Hi,
compression over .htaccess, but only in Firefox. In Chrome it is working.

BTW: https://github.com/johngodley/redirection/issues/597 - solved it by removing the creation from database.php and manually created the table ...

My compression parrt:

`# enable php compression
php_value zlib.output_compression 1
php_value zlib.output_compression_level -1

# enable apache compression
<IfModule mod_deflate.c>
	<IfModule mod_filter.c>
		SetOutputFilter DEFLATE
		AddOutputFilterByType DEFLATE application/javascript
		AddOutputFilterByType DEFLATE application/rss+xml
		AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
		AddOutputFilterByType DEFLATE application/x-font
		AddOutputFilterByType DEFLATE application/x-font-opentype
		AddOutputFilterByType DEFLATE application/x-font-otf
		AddOutputFilterByType DEFLATE application/x-font-truetype
		AddOutputFilterByType DEFLATE application/x-font-ttf
		AddOutputFilterByType DEFLATE application/x-javascript
		AddOutputFilterByType DEFLATE application/xhtml+xml
		AddOutputFilterByType DEFLATE application/xml
		AddOutputFilterByType DEFLATE font/opentype
		AddOutputFilterByType DEFLATE font/otf
		AddOutputFilterByType DEFLATE font/ttf
		AddOutputFilterByType DEFLATE image/svg+xml
		AddOutputFilterByType DEFLATE image/x-icon
		AddOutputFilterByType DEFLATE text/css
		AddOutputFilterByType DEFLATE text/html
		AddOutputFilterByType DEFLATE text/javascript
		AddOutputFilterByType DEFLATE text/plain
		AddOutputFilterByType DEFLATE text/xml
	</IfModule>
</IfModule>`

Kind regards
Johannes

**Comment by johngodley** [comment]
That seems like it's probably an incorrect server setting. Redirection has no control over your compression, and is just sending data. If you are then compressing this and it isn't working in a particular browser you'll need to figure out what you need to change in your compression to make it work in that browser.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
