### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by iambz** [johngodley/redirection#81]
PHP7 is coming in the next days/weeks, with many improvements and a boost in the engine. 
But some practices are deprecated.

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; RE_Log has a deprecated constructor in /var/www/vhosts/i-am.bz/htdocs/wp-content/plugins/redirection/models/log.php on line 3

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; RE_404 has a deprecated constructor in /var/www/vhosts/i-am.bz/htdocs/wp-content/plugins/redirection/models/log.php on line 140

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Red_Match has a deprecated constructor in /var/www/vhosts/i-am.bz/htdocs/wp-content/plugins/redirection/models/match.php on line 3

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Red_Action has a deprecated constructor in /var/www/vhosts/i-am.bz/htdocs/wp-content/plugins/redirection/models/action.php on line 3

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Red_Item has a deprecated constructor in /var/www/vhosts/i-am.bz/htdocs/wp-content/plugins/redirection/models/redirect.php on line 3

Changing these by __construct will do!

**Comment by aekab-servers** [comment]
+1 on this one!

**Comment by ekandreas** [comment]
+1

**Comment by aaemnnosttv** [comment]
:+1: :+1: :+1:

**Comment by perssonmattias91** [comment]
+1

**Comment by johanlinander** [comment]
+1

**Comment by vburlak** [comment]
+1

**Comment by landerss0n** [comment]
+1

**Comment by addedlovely** [comment]
+1

**Comment by addedlovely** [comment]
Great, thanks @johngodley!
