### ISSUE TITLE
Apostrophes are dropped from a regex redirect 

### ISSUE THREAD

**Issue by rekliner** [johngodley/redirection#811]
To help track problems please follow this template. If you can provide screenshots then that will help.

### Summary

redirecting from url1/(.*) to url2/$1 with regex... anything matched by .* has apostrophes stripped from the link rather than escaping them as an html entity.

### Actual Behavior

http://link1.com/directory/file's.pdf   becomes  http://link2.com/directory/files.pdf

### Steps to reproduce

Reproduces with any link containing an apostrophe

### Environment

Multiple browsers.  Server is ubuntu 16.04 xenial running apache & php7.0

**Comment by johngodley** [comment]
You will need to encode the apostrophe as %27 - it's not a valid URL character.
