### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by chachacallis** [johngodley/redirection#812]
```
Uncaught ReferenceError: Set is not defined wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75 28
```

Plugin: 3.2
WordPress: 4.9.4 (multi)
PHP: 7.0.25-0ubuntu0.16.04.1
Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Safari/537.36
JavaScript: wp-content/plugins/redirection/redirection.js
REST API: /wp-json/

using varnish caching system

**Comment by johngodley** [comment]
Could you open your browser's developer console and reproduce the error? Hopefully it will pause when the error happens. Could you then post the screenshot here?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
