### ISSUE TITLE
Multilingual install: Domain is missing in the Logs and 404's columns

### ISSUE THREAD

**Issue by jordymeow** [johngodley/redirection#816]
Hi,

My website is multilingual. I am personally using Polylang (definitely the best translation plugin now) but in the past, I have also used WPML which is even more widely used. 

In Redirection, showing only the URL without the domain is not enough. I get a lot of 404's on URLs which work, so now I wonder if those requests were on the right domain, but I have no way to check this. So it would be good to have one more column "Domain" if WPML or Polylang is installed (because people using your plugin + a multilingual plugin definitely need this, but not the others).

I have checked in the DB but this info is missing and is not being logged currently. So I guess this would be the first step. Then, we should see how it impacts the redirections more in details but to have those information logged would be a nice first step :)

Thanks,
Jordy.

**Comment by johngodley** [comment]
This was added in version 4.9
