### ISSUE TITLE
Redirection plugin doesn't work

### ISSUE THREAD

**Issue by sunnysusanna** [johngodley/redirection#818]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*
Hello,

### Summary

I have uploaded the redirection plugin today and for some reason it doesn't work on my site. I have already deactivated existing plugins, cleared cache, etc. Still nothing

### Actual Behavior

I tried several redirection following the explanation guide although it does seem easy anyway. Unfortunately, none of my redirects worked except one (not sure why that particular redirect decided to work - I didn't do anything dissimilar to the rest). I also found a thread on forum about cyrillic urls issues and tried to use the encoding tool you provided with - that completely took me off my website to an generic error page

### Steps to reproduce
An example of the redirect
So I am trying to redirect from
http://www.londonbestschools.com/государственные-бесплатные-начальны/
to
http://www.londonbestschools.com/лучшие-университеты-великобритании/

and several others.

I'll be very grateful if you could help me resolve the issue,
Many thank,
Susanna

### Environment
Modzilla, Wordpress 4.9.4, plugin was uploaded today so I assume it is the latest version
Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by johngodley** [comment]
How did you encode it?

I tried this:

/%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D1%8B%D0%B5-%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B/

And the redirect worked fine.

**Comment by sunnysusanna** [comment]
Hi John,
Thank you for replying. The way how I did it was I took for example this
http://www.londonbestschools.com/самые-дорогие-города-англии-для-студе/,
copied it to the URL decoder you provided the link for in one of the posts
on the forum and pressed encode. Then I put the encoded URL into Source URL
in the Redirection plugin. Then I took for example this
http://www.londonbestschools.com/государственные-школы-англии/, encoded
this too and copy-pasted the encoded URL into Target URL in the
redirection. Then, I saved it. It takes me to 404 generic website page. I
tried many times with different urls and I obviously do something wrong
here but I can't figure out what it is (((
If you could guide me through what exactly I am doing wrong, that would be
truly great.
Thank you,
Susanna

**Comment by johngodley** [comment]
Ok, if you copy and pasted those URLs exactly then you would also be URL encoding things that dont need encoding.

In the first case the URL you are trying to encode is:

/самые-дорогие-города-англии-для-студе/

You don't need the domain. From this, you don't want to encode the slashes. So in the encoder you should enter:

самые-дорогие-города-англии-для-студе

Then copy/paste this into Redirection and add the slashes back:

/%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D1%8B%D0%B5-%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B/

This should then work.

I appreciate this is a chore, and a future version of the plugin will do this for you.

**Comment by sunnysusanna** [comment]
Hi John,
Thanx so much!!! It worked this time!!! Thank you again, I'd never have
figured that out myself. Your help is so very much appreciated!!!
