### ISSUE TITLE
WordPress REST API and Redirection routes

### ISSUE THREAD

**Issue by tokar86a** [johngodley/redirection#819]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

I end up whit this kind of problem on the status of my plugin

WordPress REST API | Problem  REST API returns an error code (40x -  http://www.myabdllife.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=redirection/v1/)
-- | --
Problem REST API is not working so routes not checked

What should i do to fix this? 

### Actual Behavior

Explain what actually happened. If suggesting a new feature then explain what currently happens.

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Use the lates version of the plugin and wordpress.

**Comment by johngodley** [comment]
Are you experiencing any problems using the plugin? If everything is working then please ignore the message

**Comment by tokar86a** [comment]
I dont think so.
