### ISSUE TITLE
Redirection 403 Error - made all checks on my side, out of options?

### ISSUE THREAD

**Issue by jcass1** [johngodley/redirection#820]
Hi, 

I get the following screen when i go to the Redirection plugin:
http://prntscr.com/im2nhi

1. Please take a look at the plugin status. It may be able to identify and "magic fix" the problem.
- Status is all good, http://prntscr.com/im2ov2 

2. Redirection is unable to talk to your REST API. If you have disabled it then you will need to enable it. 
- Status shows this to be fine, perhaps not? 

3. Security software may be blocking Redirection. You will need to configure this to allow REST API requests.
- not using any security software which could tamper here, i use Loginizer, and i disabled this to check, when disabled there is still this issue.

4. Caching software, in particular Cloudflare, can cache the wrong thing. Try clearing all your caches.
- Cleared caches, removed caching plugins, still have the issue

5. Please temporarily disable other plugins! This fixes so many problems.
- Disabled all other plugins, still have the 403 issue

I've run out of ideas and i'm hoping you can help?

Best, 
Jake

```
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.0.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
JavaScript: https://inplayempire.com/wp-content/plugins/redirection/redirection.js
REST API: https://inplayempire.com/wp-json/

Error: Cookie nonce is invalid (unknown)

Error: Cookie nonce is invalid (unknown)
```

**Comment by johngodley** [comment]
Can you clear your cookies and logout and login again?
