### ISSUE TITLE
Redirection throws an REST API error, 2 plugin status problems are listed

### ISSUE THREAD

**Issue by MichaelvanLohuizen** [johngodley/redirection#821]
### Summary
When opening the redirection screen in **/wp-admin/tools.php?page=redirection.php** after clicking on **Add new**,  I would expect a new redirect to be added.

### Actual Behavior
Instead the REST API error shown in the link below appeared. 
[https://prnt.sc/imc8fr](https://prnt.sc/imc8fr)

I investigated and checked the plugin status (great feature). 
The 2 problems are shown below: [https://prnt.sc/imcb7w](https://prnt.sc/imcb7w)

`
WordPress REST API | ProblemREST API returns an error code (40x - https://xxxxxxxx/wp-admin/admin-ajax.php?action=red_proxy&rest_path=redirection/v1/)
-- | --
Problem REST API is not working so routes not checked
`

I have cleared cookies, restarted the browser, the 2 listed REST API problems are still there.

(Opening the REST API url manually returns a 200 status.)

###Current situation:
The first error does not appear at the moment, I can add redirects, but the status page still lists the 2 problems. I'm not sure my installation is now running 100% ok, so I'll investigate further on a testing environment and update this issue with my findings.

### Environment
Browser: chrome Versie 64.0.3282.186 (mac)
WordPress: 4.9.4
Redirection: 3.2

**Comment by johngodley** [comment]
Can you show the full error message?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details

**Comment by kamaldeepoodles** [comment]
I am getting the same problem. Please have a look at the attached screenshot.

![screencapture-insuropedia-securenow-in-wp-admin-tools-php-2018-07-19-01_01_18](https://user-images.githubusercontent.com/10527158/42903416-60eec194-8aef-11e8-8105-5e5d7a75867d.png)

**Comment by johngodley** [comment]
Did you try the steps outlined in the message? Did you press the magic fix button?

**Comment by kamaldeepoodles** [comment]
Yes I did try all the steps i.e.

1. Disabled all other plugins
2. Cleared the Cloudflare cache
3. Tried magic button
4. Updated all the plugins.
5. Updated WordPress.
6. Temporarily granted 777 permission to all the files and folders.
7. Disable then Enable the Redirect plugin.

**Comment by johngodley** [comment]
Step 1 in the list is to change the REST API option. Have you tried that?

**Comment by kamaldeepoodles** [comment]
Sorry for delayed response.
Yes checked the response on https://insuropedia.securenow.in/wp-json
Rest I am not sure what exactly has to be done in Step 1.

**Comment by kamaldeepoodles** [comment]
Hi @johngodley ,
Any update on this?

**Comment by kamaldeepoodles** [comment]
Hi @johngodley 
Any update on the issue?
