### ISSUE TITLE
Some redirections not work

### ISSUE THREAD

**Issue by mabehiry** [johngodley/redirection#822]

**Comment by mabehiry** [comment]
Summary
Some of redirections not work and others work. Although my plugin status is good:

WordPress REST API | Good WordPress REST API is working at http://www.allabout-cook.com/wp-json/
Good Redirection routes are working
Good All tables present
Good Valid groups detected
Good All redirects have a valid group
Good Post monitor group is valid

Actual Behavior
When I add a redirect to some 404s it doesn't work in some links, this is an example:
https://prnt.sc/in0rkz
When I click most of these links, I get the page not found error.

Steps to reproduce
From 404s list point to the link, add redirect, type the new link and click add redirect. then open the link, I get the error

Environment
Chrome last version

**Comment by stevepett** [comment]
Thanks for all your hard work John.

My issues are similar in that pages which are already redirected come up as 404s - but if you click on the link you get redirected.  In just 2 days the 404 page has grown to 34 pages long!
Many of the 404s also seem to relate to css on plugins such as cherry-plugin which does not appear on my list of plugins and some to Author pages (we only have one author but apparently multiple author pages!!

Appreciate some of this may be nothing to do with your plugin!

Steve

**Comment by Iva83** [comment]
This is the same issue I've been having for a couple of months - already redirected pages come up as 404s, while they actually exist. Google reports soft 404s.

**Comment by johngodley** [comment]
@mabehiry you need to URL encode Arabic characters. You have that in the target, but not in the source. Without that the URLs will not match

@stevepett can you provide some examples? I don't think it's related to the original poster

**Comment by mabehiry** [comment]
@johngodley I've encoded source and target, but it didn't work also!
http://prntscr.com/j6u0md

**Comment by orjhor** [comment]
I have the same issue as @stevepett and @Iva83. Redirects are in place, but somehow I am getting sporadic 404s in the 404-log none the less. When testing those reported 404 urls, I _am_ being redirected though.  

I wonder if the user actually getting a 404 or if is it the 404-reporting that itself is having an issue.

**Comment by johngodley** [comment]
@mabehiry I don't have access to the URL to check, but it seems from your screenshot that the redirect is working as I can see that hits are being recorded. Can you copy the URL here?

**Comment by johngodley** [comment]
Closing for now, please reopen with more infromation
