### ISSUE TITLE
Arabic to Roman links not supported

### ISSUE THREAD

**Issue by fedibelkacem** [johngodley/redirection#825]
### Summary

I can not redirect from a URL with arabic characters like /wp/عروض/?locale=en to a URL with roman characters like /wp/offers/?locale=en
?locale=en is used to change localization (in session) of the whole website.

### Actual Behavior

When a redirection (301) is created from /wp/عروض/?locale=en to /wp/offers/?locale=en, (the whole website localization change to english but) /wp/عروض/?locale=en remains as is instead to change to /wp/offers/?locale=en
Reverse is working fine, that means /wp/offers/?locale=ar redirects to /wp/عروض/?locale=ar (and the whole website changes from english to arabic).

### Steps to reproduce

Create 2 pages in wp/: /wp/عروض/ and /wp/offers/
Create 2 redirections: /wp/عروض/?locale=en to /wp/offers/?locale=en and /wp/offers/?locale=ar to /wp/عروض/?locale=ar
Test by entering /wp/عروض/?locale=en then by entering /wp/offers/?locale=ar or vice versa.

### Environment

I'm using Google Chrome version 65.0.3325.146 (Build officiel) (64 bits), WP is at version 4.9.4 and Redirection Plugin at version 3.2

**Comment by johngodley** [comment]
You need to URL encode the Arabic characters as these are not valid characters for URLs. You can use something like https://meyerweb.com/eric/tools/dencoder/ for this.

So /wp/عروض/?locale=en becomes /wp/%D8%B9%D8%B1%D9%88%D8%B6/?locale=en
