### ISSUE TITLE
Expresion regular para : 9238_Soy-el-titulo-de-la-entrada.html

### ISSUE THREAD

**Issue by TopCheff** [johngodley/redirection#827]
Hola, 

He cambiado y redireccionado una web con php, hacia WordPress y la ruta de enlaces que anteriormente tenia ha cambiado. Estoy intentando recuperar todos los enlaces pero no consigo hacerlo mediante una expresion regular. 

tengo estos enlaces:
_https://midominio.com/9238_Soy-el-titulo-de-la-entrada.html_

y debería redireccionar hacia:
_https://midominio.com/soy-el-titulo-de-la-entrada/_

como debo hacerlo para que se mantenga todos los enlaces? 

muchas gracias!!

**Comment by johngodley** [comment]
You will need to use a regular expression:

https://redirection.me/support/redirect-regular-expressions/

Sorry, but I can't provide specific regular expression support here.

**Comment by TopCheff** [comment]
thank you! 

i'm using 

`.*_(.*?)\.html
$1/`
