### ISSUE TITLE
REST API error

### ISSUE THREAD

**Issue by peterwesterlund** [johngodley/redirection#828]
I get Problem-status on  REST API:

- REST API returns an error code (40x - http://mywebsite.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=redirection/v1/)
- REST API is not working so routes not checked

How do I fix then?

**Comment by johngodley** [comment]
Is the plugin otherwise working?

**Comment by peterwesterlund** [comment]
Yes and now everything works fine. Or, just get those error status. But mu redirection rules works.
