### ISSUE TITLE
Infinite loop redirects only on subpages 

### ISSUE THREAD

**Issue by keesjand** [johngodley/redirection#833]
### Summary

Infinite loop 
https://www.seoeffect.com/nl/ and https://www.seoeffect.com/ are working but 'inner' pages like https://www.seoeffect.com/seo-tools/keyword-research-tool/ have a infinite loop ;-(

Its a wpml site

### Actual Behavior

even when inactivate the plugin, teh loop still excists.

### Steps to reproduce
non of the redirects are reg expresions
Dont know, first I added redirects like: (example)
/bad-url/
https://www.seoeffect.com/nl/good-url/

they all worked. Then I activated WP rocket again and it stopped working.
made wp rocket inactive again, but the problem persist

I then changed all urls to: (example)
/bad-url/
/nl/good-url/

### Environment

windows 10 > chrome
https://www.seoeffect.com/wp-json/
latest redirect plugin with wp rocket on ngnix server

**Comment by johngodley** [comment]
The only cause of an infinite loop are the redirects that you create. You'll need to look at the redirects you've created and see if there are any loops there. I don't know what WP Rocket does, but if it's caching things then it may cause things you've changed or deleted to continue working.

**Comment by keesjand** [comment]
This looks oke, isnt it?

source,target,regex,type,code,match,hits,title
"/demo-and-specs/demo-and-specs.php","/seo-tools/","0","url","301","url","0",""
"/-page1.html","/","0","url","301","url","1",""
"/help/video-tutorials.php","/nl/support/","0","url","301","url","3",""
"/.well-known/apple-app-site-association","/","0","url","301","url","0",""
"/demo-and-specs/tools-for-the-seo-pro.php","/seo-tools/seo-tools-seo-pro/","0","url","301","url","0",""
"/seo-tools/tools-for-the-seo-pro.php","https://www.seoeffect.com/seo-tools/seo-tools-seo-pro/","0","url","301","url","0",""
"/stay-tuned.php","/newsletter/","0","url","301","url","0",""
"/our-seo-tools.php","/seo-tools/","0","url","301","url","0",""
"/pricing/seo-effect-partners.php","/seo-effect-pricing/","0","url","301","url","0",""
"/seo-tools/optimize-site-pages.php","/seo-tools/optimize-site-pages/","0","url","301","url","0",""
"/nl/tools-en-demo/backlink-checker-tool.php","/nl/seo-tools/backlink-checker-tool/","0","url","301","url","0",""
"/pricing/pricing-for-our-on-line-seo-tools.php","/seo-effect-pricing/","0","url","301","url","2",""
"/nl/tools-en-demo/keyword-tool-zoekwoord-onderzoek.php","/nl/seo-tools/keyword-tool-voor-zoekwoorden-onderzoek/","0","url","301","url","0",""
"/nl/prijzen-seo-tools/","/nl/seo-effect-prijzen/","0","url","301","url","0",""
"/nl/tools-en-demo/monitor-seo-trends.php","/nl/seo-tools/rank-checker-tool/","0","url","301","url","1",""
"/homepage.php","/","0","url","301","url","1",""
"/seo-effect/participate-in-the-seo-effect-google-1-button-experiment.php","/blog-en/seo-news-posts/effects-of-the-google-1-button-researched-download-the-whitepaper/","0","url","301","url","0",""
"/about-us/seo-effect-who-we-are.php","/about-us/","0","url","301","url","0",""
"/nl/tools-en-demo/website-optimalisatie-tool.php","/nl/support/bijhouden-prestaties/hoe-bekijk-ik-mijn-rankings-in-seo-effect/","0","url","301","url","1",""
"/nl/prijzen-van-onze-online-seo-tools/seo-specialist/","/nl/seo-effect-prijzen/seo-specialist/","0","url","301","url","1",""
"/prijzen-van-onze-online-seo-tools/","/nl/seo-effect-prijzen/","0","url","301","url","0",""
"/linkbuilding-tool-voor-linkbuilding-en-linkbait/","/seo-tools/link-bait-and-link-building-tools/","0","url","301","url","0",""
"/nl/blog/seo-nieuws-posts/breaking-google-mobiel-vriendelijk-een-must/Fo","/nl/blog/seo-nieuws-posts/breaking-google-mobiel-vriendelijk-een-must/","0","url","301","url","0",""
"/seo-site-migratie-dagboek/","/nl/blog/seo-tips-en-trucs-posts/seo-site-migratie-dagboek/","0","url","301","url","0",""
"/pricing/mijnwinkel__nl-seo-actie.php","/nl/seo-effect-prijzen/","0","url","301","url","0",""
"/demo-and-specs/optimise-site-pages.php","/seo-tools/optimize-site-pages/","0","url","301","url","0",""
"/seo-effect-pricing/fair-use-policy/","/seo-effect-pricing/","0","url","301","url","9",""
"/link-building-tool/","/nl/seo-tools/linkbuilding-tool-voor-linkbuilding-en-linkbait/","0","url","301","url","2",""
"/seo-tools/seo-page-scan-more-details/","/seo-tools/optimize-site-pages/","0","url","301","url","0",""
"/keyword-tool-zoekwoorden-onderzoek/","/nl/seo-tools/keyword-tool-voor-zoekwoorden-onderzoek/","0","url","301","url","1",""
"/nl/blog/update-posts/nieuw-zie-wat-je-concurrenten-doen/","/nl/blog/update-posts/nieuw-zie-wat-je-seo-concurrenten-doen/","0","url","301","url","0",""
"/Effects-of-the-Google-%2B1-button-researched-download-the-whitepaper/","/blog-en/seo-news-posts/effects-of-the-google-1-button-researched-download-the-whitepaper/","0","url","301","url","0",""
"/nl/tools-en-demo/rank-checker-tool.php","/nl/seo-tools/rank-checker-tool/","0","url","301","url","0",""
"/nl/blog/google-1-knop-onderzocht-download-de-whitepaper.php","/nl/blog/seo-nieuws-posts/google-1-knop-onderzocht-download-de-whitepaper/","0","url","301","url","0",""
"/nl/tools-en-demo/seo-kpi-traffic-share.php","/nl/seo-tools/seo-concurrentie/","0","url","301","url","0",""
"/nl/seo-tools/seo-kpi-traffic-share/","/nl/seo-tools/seo-concurrentie/","0","url","301","url","1",""
"/seo-tools/seo-kpi-traffic-share/","/seo-tools/seo-competition/","0","url","301","url","3",""
"/nl/blog/seo-tips-en-trucs-posts/test/","/nl/blog/seo-tips-en-trucs-posts/joop/","0","url","301","url","3",""
"/blog-en/seo-effect-updates-posts/52-manieren-om-terug-te-kijken-je-seo-rankings/","/blog-en/seo-effect-updates-posts/52-ways-of-looking-back-within-your-rankings/","0","url","301","url","2",""
"/blog-en/seo-tips-and-tricks-posts/21-seo-tips-voor-bouw-nieuwe-website/","/21-seo-tips-for-building-a-new-website/","0","url","301","url","2",""

Met vriendelijke groet,

Keesjan Deelstra
Search consultant

InternetEffect<http://www.interneteffect.com/>
Zijlweg 113
<http://maps.google.com/maps?q=Zijlweg+113%2CHaarlem%2C2013+DE%2CNetherlands&hl=en>Haarlem, 2013 DE
Netherlands

Werk: 023-5749670
Mobile: 06-51700993
Email:keesjan@interneteffect.com<mailto:keesjan@internetEffect.com>
[linkedin]<http://nl.linkedin.com/in/keesjandeelstra>  [twitter] <http://twitter.com/#!/keesjandeelstra>

[InternetEffect-zoekmachine-marketing-200]<http://www.interneteffect.com/?utm_source=email-handtekening-keesjan&utm_medium=email>Zoekmachine Marketing




[kaft-managementboek]Koop de vierde geheel vernieuwde druk "Handboek Zoekmachine marketing"<http://www.interneteffect.com/handboek-zoekmachine-marketing/?utm_source=email-handtekening-keesjan&utm_medium=email>.
Met Valuepack €125,-
Nu €34,90

Ken jij   SEO Effect<http://www.seoeffect.com/nl/?utm_source=email-handtekening-keesjan&utm_medium=email>   al? We zijn live met de 6-de  release... Maak een gratis proefaccount!




The information in this electronic mail message is private and
confidential, and only intended for the addressee. Should you
receive this message by mistake, you are hereby notified that
any disclosure, reproduction, distribution or use of this
message is strictly prohibited. Please inform the sender by
reply transmission and delete the message without copying or
opening it.

Messages and attachments are scanned for all viruses known.
If this message contains password-protected attachments, the
files have NOT been scanned for viruses by the InternetEffect mail domain.
Always scan attachments before opening them.
-----------------------------------------------------------------

Van: KeesJan Deelstra
Verzonden: maandag 12 maart 2018 20:53
Aan: 'johngodley/redirection' <reply@reply.github.com>; johngodley/redirection <redirection@noreply.github.com>
CC: Author <author@noreply.github.com>
Onderwerp: RE: [johngodley/redirection] Infinite loop redirects only on subpages (#833)

Hi,
I also have this wp REST api errors: does that have to do with this to?
[cid:image015.png@01D3BA45.09899E40]

Met vriendelijke groet,

Keesjan Deelstra
Search consultant

InternetEffect<http://www.interneteffect.com/>
Zijlweg 113
<http://maps.google.com/maps?q=Zijlweg+113%2CHaarlem%2C2013+DE%2CNetherlands&hl=en>Haarlem, 2013 DE
Netherlands

Werk: 023-5749670
Mobile: 06-51700993
Email:keesjan@interneteffect.com<mailto:keesjan@internetEffect.com>
[linkedin]<http://nl.linkedin.com/in/keesjandeelstra>  [twitter] <http://twitter.com/#!/keesjandeelstra>

[InternetEffect-zoekmachine-marketing-200]<http://www.interneteffect.com/?utm_source=email-handtekening-keesjan&utm_medium=email>Zoekmachine Marketing




[kaft-managementboek]Koop de vierde geheel vernieuwde druk "Handboek Zoekmachine marketing"<http://www.interneteffect.com/handboek-zoekmachine-marketing/?utm_source=email-handtekening-keesjan&utm_medium=email>.
Met Valuepack €125,-
Nu €34,90

Ken jij   SEO Effect<http://www.seoeffect.com/nl/?utm_source=email-handtekening-keesjan&utm_medium=email>   al? We zijn live met de 6-de  release... Maak een gratis proefaccount!




The information in this electronic mail message is private and
confidential, and only intended for the addressee. Should you
receive this message by mistake, you are hereby notified that
any disclosure, reproduction, distribution or use of this
message is strictly prohibited. Please inform the sender by
reply transmission and delete the message without copying or
opening it.

Messages and attachments are scanned for all viruses known.
If this message contains password-protected attachments, the
files have NOT been scanned for viruses by the InternetEffect mail domain.
Always scan attachments before opening them.
-----------------------------------------------------------------

Van: John <notifications@github.com<mailto:notifications@github.com>>
Verzonden: maandag 12 maart 2018 20:49
Aan: johngodley/redirection <redirection@noreply.github.com<mailto:redirection@noreply.github.com>>
CC: KeesJan Deelstra <keesjan@interneteffect.com<mailto:keesjan@interneteffect.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Onderwerp: Re: [johngodley/redirection] Infinite loop redirects only on subpages (#833)


The only cause of an infinite loop are the redirects that you create. You'll need to look at the redirects you've created and see if there are any loops there. I don't know what WP Rocket does, but if it's caching things then it may cause things you've changed or deleted to continue working.

**Comment by johngodley** [comment]
https://www.seoeffect.com/seo-tools/keyword-research-tool/ is not being redirected by Redirection, and does not exist in your list above. Do you have something else that is performing redirects?

**Comment by keesjand** [comment]
can the plugin https://wordpress.org/plugins/wp-maintenance-mode/ have a conflict with redirection plugin?

**Comment by keesjand** [comment]
and a rooky kind of reamrk.
Thers is no helpfile how to fill in the URLS for redirection, with full path or only the URLs. Does it matter?

**Comment by johngodley** [comment]
I don't know if wp-maintenance-mode is causing the problem. Based on your list above, and by checking the URL itself, I can see that Redirection is not causing that particular redirect.

The source is a relative URL, the target is up to you.

https://redirection.me/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
