### ISSUE TITLE
Redirects query

### ISSUE THREAD

**Issue by marcelomazza** [johngodley/redirection#834]
It would be great to have a way (I couldn't find any) to query the list of redirects. This would allow to list the redirects in different parts of WP and reference a given redirect, without the need of doing manually.

**Comment by johngodley** [comment]
You can use the REST API to query redirects. Take a look at `/wp-json/` on your site to see what is available.

**Comment by marcelomazza** [comment]
Thanks @johngodley I didn't know. I took a look but I don't see any endpoint that would give me the redirects, is this a feature that needs to be enabled somewhere?

**Comment by johngodley** [comment]
No, the endpoints are all there. The plugin uses them to display all the redirects and perform all of the actions inside the plugin. I don't know what your website is, but if you look at https://redirection.me/wp-json/ you will see a lot of endpoints for redirection. These match up to the code in https://github.com/johngodley/redirection/tree/master/api

**Comment by marcelomazza** [comment]
Thanks! I didn't have the latest version, maybe that's the reason they weren't showing up.

In case anyone wonders, the Redirection endpoint is `/wp-json/redirection/v1/`. Thanks @johngodley for the help! Closing 😄
