### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by aworstell** [johngodley/redirection#839]
I'm getting the following error when I'm just trying to load the redirection plugin page. This is happening in all of our wordpress environemnts. I have tried disabling every other plugin, I can manually navigate to the REST API, and I am not using any other caching systems.
```
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 5.4.16
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
JavaScript: https://www.dev.terradatum.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.dev.terradatum.com/wp-json/

Error: Sorry, you are not allowed to do that. (unknown)
Action: redirection/v1/group/ GET
Code: 401 Unauthorized
Raw: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
```

**Comment by johngodley** [comment]
The error suggests that something is blocking your REST API. Are you using any security software?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
