### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by melissajclark** [johngodley/redirection#840]
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 5.6.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
JavaScript: http://dancelondonstudio.com/dlondon2018/wp-content/plugins/redirection/redirection.js
REST API: http://dancelondonstudio.com/dlondon2018/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any errors are shown there?

**Comment by melissajclark** [comment]
This is working fine now, the issue can be closed.
