### ISSUE TITLE
Empty admin page and database error

### ISSUE THREAD

**Issue by mattbob** [johngodley/redirection#842]
### The admin page loads with nothing on it

When I visit the Redirection admin page (wp-admin/tools.php?page=redirection.php) I get an empty screen and I see this in my error logs:

```[17-Mar-2018 12:17:36 EST] WordPress database error Got error 64 'Temp file write failure' from InnoDB for query ALTER TABLE `wp_redirection_404` ADD `ipaddress` VARCHAR(45) DEFAULT NULL AFTER `ip` made by require_once('wp-admin/admin.php'), do_action('tools_page_redirection'), WP_Hook->do_action, WP_Hook->apply_filters, Redirection_Admin->admin_screen, Redirection_Admin::update, RE_Database->upgrade, RE_Database->upgrade_to_24
[17-Mar-2018 12:17:36 EST] WordPress database error Unknown column 'ipaddress' in 'field list' for query UPDATE wp_redirection_404 SET ipaddress=INET_NTOA(ip) made by require_once('wp-admin/admin.php'), do_action('tools_page_redirection'), WP_Hook->do_action, WP_Hook->apply_filters, Redirection_Admin->admin_screen, Redirection_Admin::update, RE_Database->upgrade, RE_Database->upgrade_to_24```

After deactivating the plugin I can' re-activate it. When I try to activate it I get the above database error again in my logs.

### Environment

This happens in Chrome 65 on WordPress 4.9.4 and Redirection 3.2

**Comment by mattbob** [comment]
Rollinb back to 2.10.1 the issue goes away.

**Comment by johngodley** [comment]
The error indicates the plugin is unable to alter your database tables because it can't create a MySQL temp table. You will need to fix that error in order to use the new version.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
