### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by teacher4us** [johngodley/redirection#843]
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 5.6.34
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
JavaScript: https://www.teacher4us.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.teacher4us.com/wp-json/

**Comment by johngodley** [comment]
Are there any more error details?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
