### ISSUE TITLE
Import/Export tab error

### ISSUE THREAD

**Issue by Rusinante** [johngodley/redirection#849]
Hello

I want to import a csv file to one of my sites (my page is a multisite), but every time i try to enter to the tab of import/export i get this error:

```
Plugin: 3.2
WordPress: 4.8.5 (multi)
PHP: 5.6.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
JavaScript: http://cl.mwp.ajover.com/wp-content/plugins/redirection/redirection.js
REST API: http://cl.mwp.ajover.com/wp-json/?lang=es/
Buster: 3.2 === 3.2

TypeError: Cannot read property 'length' of undefined

    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in n
    in np
    in t
```

This error **only** happen on the import/export tab.

**Comment by johngodley** [comment]
Ah, that looks like an interesting error. Could you open your browser's developer tools and try again? Your browser should pause on the error. Can you take a screenshot of that?

**Comment by Rusinante** [comment]
Just right now i could find the problem.
I had to end the configuration of the **WPML plugin** to fix the problem on the Redirect plugin. 
I don't know why that triggered this issue but i hope this information can help someone else :)
Thanks for the response anyway.

**Comment by johngodley** [comment]
Just to confirm, using the WPML causes the error to happen, and disabling it stops the error? If so I can make sure WPML doesn't cause a problem

**Comment by johngodley** [comment]
Sadly I'm unable to download WPML so cannot proceed further with this. Closing for now until I can progress.
