### ISSUE TITLE
Need help with redirect Rest Api and redirect issues

### ISSUE THREAD

**Issue by acustomwedding** [johngodley/redirection#851]
Hi, I need your help with the plugin.  Yes, I have disabled all plugins and done what I can up to this point and now I am stumped. 

### Summary

I am trying to troubleshoot redirect errors

### Actual Behavior

I am getting these error messages in my dashboard

WordPress REST API | Problem REST API returns an error code (40x - https://customlasvegasweddings.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=redirection/v1/)
-- | --
Problem REST API is not working so routes not checked

I am also getting Google search console errors stating that the redirect is redirecting me too many times. 
Does this have to do with the plugin or could it be some other factor? 

### Steps to reproduce

Explain the steps involved to reproduce the problem

### Environment

Please list your browser (Chrome), browser version , version of WordPress and Redirection plugin.
![screenshot of redirect issues](https://user-images.githubusercontent.com/37611703/37697826-4a32504e-2c9c-11e8-8321-354da4ed0590.png)

**Comment by acustomwedding** [comment]
I use Malcare and Wordfence too.  Is redirect incompatible with either of these?

**Comment by johngodley** [comment]
Is the plugin working ok? If so you can ignore the status message.

It can take some time for Google to update it's information. If you have changed things recently then you'll need to keep checking.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
