### ISSUE TITLE
redirect no www to www

### ISSUE THREAD

**Issue by tricotraco** [johngodley/redirection#855]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

I can not set the redirect no www to www. how can this be done?
for esemple:
http://namesite.it
to 
http://www.namesite.it
how can this be done?
thanks

**Comment by johngodley** [comment]
Please see https://stackoverflow.com/questions/12050590/redirect-non-www-to-www-in-htaccess#12050652
