### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by semperegeorges** [johngodley/redirection#858]
```Bonjour vous pouvez m'aider ? Je ne peux pas faire de redirection ?
https://yachting-plaisance.com/tag/bateau-pneumatique-usager/
To : https://yachting-plaisance.com/reparation-de-bateaux-pneumatiques-de-semi-rigide/
Merci
Georges

Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.2.1
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
JavaScript: https://yachting-plaisance.com/wp-content/plugins/redirection/redirection.js
REST API: https://yachting-plaisance.com/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"https://yachting-plaisance.com/tag/bateau-pneumatique-usager/","title":"","regex":false,"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":308,"action_data":{"url":"https://yachting-plaisance.com/reparation-de-bateaux-pneumatiques-de-semi-rigide/"}}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/redirect/
on this server.<br />
</p>
</body></html>

```
Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.2.1
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
JavaScript: https://yachting-plaisance.com/wp-content/plugins/redirection/redirection.js
REST API: https://yachting-plaisance.com/wp-json/

Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"https://yachting-plaisance.com/tag/bateau-pneumatique-usager/","title":"","regex":false,"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":308,"action_data":{"url":"https://yachting-plaisance.com/reparation-de-bateaux-pneumatiques-de-semi-rigide/"}}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/redirect/
on this server.<br />
</p>
</body></html>

**Comment by johngodley** [comment]
This kind of error usually indicates that the REST API is being blocked. Are you using a security plugin, or something else that might affect the REST API?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
