### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by Bolag** [johngodley/redirection#864]
```
TypeError: can't redefine non-configurable property "userAgent" https://www.bolagsregistrering.eu/wp-admin/tools.php?page=redirection.php 1
```

Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.0.28
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 tSg4NFgK-33 Firefox/59.0
JavaScript: https://www.bolagsregistrering.eu/wp-content/plugins/redirection/redirection.js
REST API: https://www.bolagsregistrering.eu/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

**Comment by johngodley** [comment]
What action were you doing when this error happened?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
