### ISSUE TITLE
Feature request: check "regex" by default option

### ISSUE THREAD

**Issue by physixfan** [johngodley/redirection#868]
Hi, I love this plugin, and it is a necessary plugin to every Wordpress site in my opinion.

The "regex" function is really useful, but currently I need to check "regex" manually for all the redirections. Is it possible to add an option on the settings menu, so that I can let all new redirections be "regex" redirections automatically? 

Thanks!

**Comment by johngodley** [comment]
Your original request is still open. Merging with that:

https://github.com/johngodley/redirection/issues/514
