### ISSUE TITLE
Redirection Error - when using the search input

### ISSUE THREAD

**Issue by kfairris** [johngodley/redirection#877]
Anytime I try using the search to find a redirect, I get this error.  Everything else continues to work fine.

```
Plugin: 3.1.1
WordPress: 4.9.2 (multi)
PHP: 7.1.13
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
REST API: https://www-stage.familylife.com/wp-json/

Error: Unexpected token < in JSON at position 0
```

**Comment by johngodley** [comment]
Is there any other information in the error message? You might need to scroll down through the text area

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
