### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by bathselectblog** [johngodley/redirection#880]
```
Uncaught TypeError: Cannot read property 'hasClass' of undefined http://blog.bathselect.com/wp-admin/load-scripts.php?c=0&load%5B%5D=hoverIntent,common,admin-bar,svg-painter,heartbeat,wp-auth-check,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-dragg&load%5B%5D=able,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,thickbox,underscore,shortcode,media-upload&ver=4.9.5 246
```

Plugin: 3.2
WordPress: 4.9.5 (single)
PHP: 5.4.45
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
JavaScript: http://blog.bathselect.com/wp-content/plugins/redirection/redirection.js
REST API: http://blog.bathselect.com/wp-json/

**Comment by johngodley** [comment]
Can you open your browser's developer console and reload the page? It should pause on the error, and might show more details about what is causing it.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
