### ISSUE TITLE
BIG PROBLEM - not found the issue

### ISSUE THREAD

**Issue by Phodia** [johngodley/redirection#882]
Hello,
I can't anymore use the plugin redirection. I can't delete, add or modify the redirection. I need to fixe this error as soon is possible. Thank you for your answer.

Here the error message:

Plugin: 3.2
WordPress: 4.9.4 (single)
PHP: 7.0.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
JavaScript: https://frog-publicite.com/wp-content/plugins/redirection/redirection.js
REST API: https://frog-publicite.com/wp-json/

Error: Unexpected token < in JSON at position 0

**Comment by johngodley** [comment]
Have you tried changing the option in the dropdown that appears in the error?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information

**Comment by Phodia** [comment]
Which one do i have to choose?

**Comment by johngodley** [comment]
Whichever one works

**Comment by Phodia** [comment]
Nothing change
I have always the same error:

- **WordPress REST API**:  Problem REST API returns an error code (40x - https://frog-publicite.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=redirection/v1/)
- **Redirection routes:** Problem REST API is not working so routes not checked
