### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by sysnext** [johngodley/redirection#883]
```
Plugin: 3.2
WordPress: 4.9.5 (single)
PHP: 7.1.13
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
JavaScript: https://fr.packshot-creator.com/resources/p/redirection/redirection.js
REST API: https://www.packshot-creator.com/wp-json/

Error: Failed to fetch

Error: Failed to fetch
```

**Comment by sysnext** [comment]
Can you please help me ?

**Comment by johngodley** [comment]
Have you tried changing the option in the dropdown that appears in the error?

**Comment by johngodley** [comment]
> I have a backup, can you please tell me how to restore the redirection data

It really depends how you've backed things up?

**Comment by sysnext** [comment]
I have all the files and I can restore all my server if needed.



*De :* John [mailto:notifications@github.com]
*Envoyé :* dimanche 8 avril 2018 17:50
*À :* johngodley/redirection <redirection@noreply.github.com>
*Cc :* sysnext <laurent.wainberg@sysnext.com>; Author <
author@noreply.github.com>
*Objet :* Re: [johngodley/redirection] Redirection Error (#883)



I have a backup, can you please tell me how to restore the redirection data

It really depends how you've backed things up?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<http://s.bl-1.com/h/cfdkzxDM?url=https://github.com/johngodley/redirection/issues/883#issuecomment-379560316>,
or mute the thread

**Comment by johngodley** [comment]
Data is stored in your database. However you have backed things up you will need to restore your database.

**Comment by sysnext** [comment]
Hello John,what is the best to backup please ?Laurent2018-04-08 17:49 GMT+02:00 John <notifications@github.com>:
I have a backup, can you please tell me how to restore the redirection data

It really depends how you've backed things up?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- 
			
			
			Laurent Wainberg    

			CEO & Founder | +33 147426666

			6, rue A. Raynaud - 92300 Levallois

			  book time in my calendar
			


			
						Celebrating 15 years of success

						www.packshot-creator.com
						
			
			
						LATEST NEWS

**Comment by johngodley** [comment]
I'm not sure what you are asking.

I don't know how you have made a backup. You will need to restore using whatever method you backed up with. I don't think this is a question that is related to Redirection anymore

**Comment by johngodley** [comment]
Closing for now
