### ISSUE TITLE
 REST API returns an error code (40x -)

### ISSUE THREAD

**Issue by jonopoon** [johngodley/redirection#886]
[To help track problems please follow this template. If you can provide screenshots then that will help.
](url
![screen shot 2018-04-09 at 22 08 05](https://user-images.githubusercontent.com/25509832/38523167-8daaa5a0-3c42-11e8-9756-e709fe3196ac.png)
)

### Summary

Have tried to deactivate all plugins with Redirection being the only tool - still has the same error.

Please list your browser, browser version, version of WordPress and Redirection plugin.

**Comment by trslack** [comment]
I am having the same issue as well. Have done all trouble shooting and have done the magic fix and nothing is working. What can be done about this. The site this is on gets more then 150,000 redirection hits a day so I need this addressed asap.

**Comment by johngodley** [comment]
If your plugin is working then you can ignore this message as a false a positive.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
