### ISSUE TITLE
Urls with malformed query cause error

### ISSUE THREAD

**Issue by thomasmery** [johngodley/redirection#894]
### Summary

As I was importing urls among which some of them had malformed query strings the plugin would throw an error / notice:

`undefined index 'query' on line 106 in /redirection/models/htaccess.php`

### Steps to reproduce

Try importing an url of the form: 

`/videos/pourquoi-la-box-connait-elle-un-succes-croissant-_a-5-18.html&no_ipad_redirect`

### Possible solution

I tracked the pb down to the malformed url being evaluated as having a query string
but in fact missing the `query` part after being passed to `parse_url`

see: https://github.com/johngodley/redirection/pull/895

**Comment by johngodley** [comment]
Merged, thanks!
