### ISSUE TITLE
Redirection Error - Error: Failed to fetch

### ISSUE THREAD

**Issue by actionmatt** [johngodley/redirection#897]
Redirection plugin has stopped working. We are running Wordfence but I cannot see any settings that prevent the API working and we can't turn off that plugin for security reasons.

Can you suggest what we can do to get your plugin working again?

```
Plugin: 3.2
WordPress: 4.9.5 (single)
PHP: 7.0.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
JavaScript: https://quietgarden.org/wp-content/plugins/redirection/redirection.js
REST API: http://quietgarden.org/index.php?rest_route=/

Error: Failed to fetch

Error: Failed to fetch
```

**Comment by johngodley** [comment]
I think you have http and https set as your URLs on Settings > General. If you set them both to https then it will probably work.

**Comment by actionmatt** [comment]
Great - thanks that worked.

**Comment by MollyWeb** [comment]
This worked for me too. Thanks
