### ISSUE TITLE
Accept Language Redirects does not work

### ISSUE THREAD

**Issue by nilbob** [johngodley/redirection#899]
### Summary

I want my page to be in English and German and use the plugin to redirect users from Germany (browser language) to the equivalent German page, whereas all the other users should visit the English version
 
### Actual Behavior

After reading the documentation, I tried a couple things to actually get a redirect done. But it did not work at all.
 
### Steps to reproduce

Open www.protoplanet-studio.de
Use the navigation menu button "About" (German Version) or the url:
http://www.protoplanet-studio.de/about-protoplanet-2d-animations-studio/
Based on your browser language, you should receive the German or English version.

### Environment

I tried it in Chrome 65 with the plugin (quick language switcher), Firefox 59 with plugins (change accept language header) on macOS Sierra.

This is my rule for the "About" page:
<img width="2337" alt="bildschirmfoto 2018-04-17 um 14 55 06" src="https://user-images.githubusercontent.com/23342043/38871454-378539dc-4251-11e8-9656-5000035996a9.png">

**Comment by nilbob** [comment]
Thx a lot for the quick reply. I am new to php and Wordpress (WP). Do I have to put that line into the functions.php file in WP to check the output? And if so, where do I see the output values? In Chrome or on my Webspace/Server?

**Comment by johngodley** [comment]
Put them in a file on your server, and then call that file from a web browser.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
