### ISSUE TITLE
Unable to get into the Redirection Plugin to administer it. 

### ISSUE THREAD

**Issue by kyith** [johngodley/redirection#903]
To help track problems please follow this template. If you can provide screenshots then that will help.

I was backing up my wordpress database when i realize the wp_redirection_404 table is very very big. it is **about 400 MB** when exported alone.

So I haven't gone into redirection in wordpress for some time and tried to launch it but was unable to.

When i click on the link to redirection settings, it took a long time to load and timed out.

### Steps to reproduce

1. Login to wordpress wp_admin
2. Click on the redirection link
3. Failed to load

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.

Chrome: Version 65.0.3325.181 (Official Build) (64-bit)
Wordpress:  4.9.5
Redirection: Version 3.2

**Comment by johngodley** [comment]
I'm not sure why the page load would be slow or timeout.

You can set options to expire log entries to keep the size appropriate for your server. You can `TRUNCATE` the wp_redirection_404 table to immediately reduce the size

**Comment by kyith** [comment]
i solved the issue. I update Chrome to Version 66.0.3359.117 and this is solved
