### ISSUE TITLE
Can't add or edit redirects

### ISSUE THREAD

**Issue by zoogits** [johngodley/redirection#906]
Hi,

I've installed the plugin and added some redirections a few months ago. All ok. Today I tried to add new redirects and the error pops up.
It also happened with another site in the same server, so I suppose something with the plugin-server relation changed.
Disabled all plugins and the error still there.

![captura de pantalla 2018-04-19 a les 11 30 27](https://user-images.githubusercontent.com/8297490/38983966-dcb359aa-43c5-11e8-80e7-95c464d736b2.png)

Thanks.

```
Plugin: 3.2
WordPress: 4.9.5 (single)
PHP: 5.6.33
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
JavaScript: https://catalunyavan.com/2018/wp-content/plugins/redirection/redirection.js
REST API: https://catalunyavan.com/wp-json/

Error: Unexpected token < in JSON at position 0
Action: redirection/v1/redirect/ POST
Params: {"id":0,"url":"/dreamer-es/?lang=es","title":"","regex":false,"match_type":"url","action_type":"url","position":0,"group_id":1,"action_code":301,"action_data":{"url":"/es/dreamer/"}}
Code: 403 Forbidden
Raw: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/redirection/v1/redirect/
on this server.<br />
</p>
</body></html>

```

**Comment by MollyWeb** [comment]
This has also started happening to me on one of my client sites. My error is "Error: Failed to fetch" instead of the token error.

**Comment by johngodley** [comment]
Please try the beta here:

https://github.com/johngodley/redirection/releases/tag/3.2.1

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
