### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by arfecia** [johngodley/redirection#909]
The plugin started to have shown the error suddenly.
I tried to check the reproducibility,
use "Redirection" on my another blog, which has a few plugins, and it showed the same error too. So I judged this error is not related to my blog, probably the plugin itself.

```
Plugin: 3.2
WordPress: 4.9.5 (single)
PHP: 7.0.18
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
JavaScript: https://jp.kumi-log.com/wp-content/plugins/redirection/redirection.js
REST API: https://jp.kumi-log.com/wp-json/

Error: Unexpected token < in JSON at position 0

Error: Unexpected token < in JSON at position 0
```

![screen shot 2018-04-21 at 14 58 06](https://user-images.githubusercontent.com/8035940/39081929-7aad3ec8-4574-11e8-85d1-208a8d8e1b86.png)

**Comment by arfecia** [comment]
There is no problem with plugin status.
![screen shot 2018-04-21 at 15 50 03](https://user-images.githubusercontent.com/8035940/39082337-b6bc0348-457b-11e8-912f-7a855d2ea4d1.png)

**Comment by arfecia** [comment]
I changed REST API from Default to Raw (/index.php?rest_route=/), and it works now.
I don't know it's okay to leave it as Raw continuously.
![screen shot 2018-04-22 at 12 43 30](https://user-images.githubusercontent.com/8035940/39091966-cd784a10-462a-11e8-9f3c-9b851551a1db.png)

**Comment by johngodley** [comment]
It's fine like that. Some servers are configured in a way that prevents the REST API working in the default manner.
