### ISSUE TITLE
Import 'Code' (301/307) Ignored

### ISSUE THREAD

**Issue by 972creative** [johngodley/redirection#91]
We need to do a bulk import where some URLs will receive 301 but others will receive 307 codes. The import doesn't recognize the 'code' column.

CSV template used attached.

[Untitled spreadsheet - Sheet1.zip](https://github.com/johngodley/redirection/files/129700/Untitled.spreadsheet.-.Sheet1.zip)

**Comment by johngodley** [comment]
Yes, the import only accepts source and target URL.
