### ISSUE TITLE
Redirection does not work for 404 pages

### ISSUE THREAD

**Issue by yasinturkdogan** [johngodley/redirection#910]
When I create redirection for non existing URLs it doesn't work. But it is working fine for existing pages. I think somehow https status code remains 404 instead of 301. 

You can find the request and response headers below. As you can see Location header is there but status code is 404.

Plugin and Wordpress installations has the latest versions and I am testing on Mac Chrome Browser.

Request URL: https://www.example.com/not-existing-page.html
Request Method: GET
Status Code: 404 Not Found
Remote Address: xxx.xx.x.x
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-cache, must-revalidate, max-age=0
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Tue, 24 Apr 2018 11:35:05 GMT
Link: <https://www.example.com/wp-json/>; rel="https://api.w.org/"
Location: /existing-page.html
Server: nginx
Transfer-Encoding: chunked

**Comment by johngodley** [comment]
Are the nonexistent URLs always `.html`? If so then you may find an answer here:

https://redirection.me/support/faq/#html

**Comment by yasinturkdogan** [comment]
You are right, it is happening only for those html URLs. I checked my nginx configuration as you mentioned but those requests are passed to wordpress just like any other URL. Because it is how my permalink structure is ->  /%postname%.html

And thanks a lot for the quick response.
