### ISSUE TITLE
Illegal mix of collations errors

### ISSUE THREAD

**Issue by EPuncker** [johngodley/redirection#92]
http://pastebin.com/KxGnLZJX

Those entries are spamming my error_log file, seems like the plugin is not handling special characters like: ç,ª,ã, etc

if you need any additional info just tell me

PS: seems to be related to this https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/

**Comment by johngodley** [comment]
I think the best course of action here is to use the 'delete plugin' option in Redirection's settings menu, and then re-activate the plugin. This will ensure your tables are created with the current WordPress defaults and there should be no mix of collations.
