### ISSUE TITLE
Monitoring of URL changes & automatic updating of redirects no longer works

### ISSUE THREAD

**Issue by sporesac** [johngodley/redirection#920]
Active monitoring of URL changes no longer is updating the plugin's list of redirects.  Function used to work, but no longer. No security is running (i.e. Wordfence). Assume it still works for others.  For troubleshooting , any known conflicts that I can look at?  Will manually create redirects, but prefer the auto-generation that used to work.

**Comment by midihead7** [comment]
I have been having the same exact issue for more than 2 months (see https://wordpress.org/support/topic/no-automatic-redirects/#post-10129147). The beta version 3.3  does not correct the issue for me. I have confirmed that the REST API is working.

**Comment by midihead7** [comment]
This issue still exists on version 3.4.1. Can you please provide an update on the issue? Thank you very much.

**Comment by johngodley** [comment]
I'm unable to reproduce a problem with this feature. Can you confirm that you have enabled the option on the settings page?

**Comment by midihead7** [comment]
Yes, I can confirm that I have enabled the options to create automatic redirections in the settings:

![image](https://user-images.githubusercontent.com/28960642/45637541-90df1a80-ba5f-11e8-92fb-f3cb3ad013fa.png)

**Comment by johngodley** [comment]
Closing for now, please reopen with more information

**Comment by johngodley** [comment]
Wonderful! I can be contacted at https://redirection.me/contact/

**Comment by tirleadoru** [comment]
Hello,

I installed your latest verison of the plugin 3.6.3 and I still have this issue. I checked on settings my custom post type (checked also posts just to be sure that is not a problem how I created my custom post type), but I don't get any automatic redirects created for anything.

This is still a known problem?
