### ISSUE TITLE
Can't Add Groups

### ISSUE THREAD

**Issue by dkjensen** [johngodley/redirection#93]
When I try and add a group, I get this error:

> Please specify a group name

Yes I have entered a name for the group. 

I think this is related to not being able to monitor changes to posts, as I looked in the source code and the Monitor changes to posts dropdown seems to be populated from the groups.

**Comment by johngodley** [comment]
Does this still happen with the latest version? I think it may have been fixed.

**Comment by t-me** [comment]
I still have this problem. 
Wordpress version 4.7.2
Redirection version 2.5 

My WP says 

```
WordPress database error: [Table 'wp_redirection_groups' doesn't exist]
SELECT * FROM wp_redirection_groups

WordPress database error: [Table 'wp_redirection_items' doesn't exist]
SELECT * FROM wp_redirection_items ORDER BY id desc LIMIT 0,25

WordPress database error: [Table 'wp_redirection_items' doesn't exist]
SELECT COUNT(*) FROM wp_redirection_items

```

even when i remove en redownload this still hapens.

**Comment by saetia** [comment]
@t-me make sure your database user is allowed to create tables.
