### ISSUE TITLE
Enhance with permalink redirect capabilities from your Advanced Permalink plugin?

### ISSUE THREAD

**Issue by thompsonpaul** [johngodley/redirection#933]
Enhancement request.  [Edit: Sorry, just realised this is essentially a dupe of https://github.com/johngodley/redirection/issues/476]

Any chance you'd consider including some of the terrific functionality from your old Advanced Permalinks plugin?

In particular, the need for a blanket redirect for changing permalinks from /%year%/%monthnum%/%postname%/ to  /%category%/%postname%/ is coming up more and more often, and the other plugins for this all seem to be a bit inconsistent. Plus it would be great to keep it all in one plugin and I much prefer Redirection for putting on client sites.

Fingers crossed! 

Thanks;

Paul

**Comment by johngodley** [comment]
A long time coming, but I've added support for migrated permalinks in version 5.0. There's a beta version here:

https://github.com/johngodley/redirection/releases/tag/5.0-beta
