### ISSUE TITLE
Redirection Error: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by ComputerTinker** [johngodley/redirection#934]
```
Plugin: 3.2
WordPress: 4.9.4 (multi)
PHP: 7.1.12
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
JavaScript: https://blogs.bju.edu/pr/wp-content/plugins/redirection/redirection.js
REST API: http://blogs.bju.edu/pr/index.php?rest_route=/

Error: NetworkError when attempting to fetch resource.

Error: NetworkError when attempting to fetch resource.
```

Good afternoon. I just installed this plugin on my multisite WP server and it seems to be telling me conflicting things.  On the one hand, it clearly does not seem to be happy with the default settings and the plugin refuses to work.  

![image](https://user-images.githubusercontent.com/9611807/39887297-dc3ea68c-545f-11e8-93c0-f4e8da3f11e7.png)

On the other hand, if I click the "plugin status" link it looks as though everything is functioning normally:

![image](https://user-images.githubusercontent.com/9611807/39887117-5cc8a66e-545f-11e8-9046-5b8c1bc546b1.png)

If I change the dropdown at the top of the page to use the "Default /wp-json" option, then I see this:

![image](https://user-images.githubusercontent.com/9611807/39887191-95ec664c-545f-11e8-9d70-1f7df3f74d9b.png)

Crossing my fingers and clicking the "Magic Fix" button reverts to using the /index.php?rest_route=/ url.  Any help appreciated. Thanks!

**Comment by johngodley** [comment]
The URL given above for your REST API is not a valid REST API:

http://blogs.bju.edu/pr/index.php?rest_route=/

I don't know how you have your site setup, but that seems to be the cause of the problem

**Comment by ComputerTinker** [comment]
Sorry about the confusion. After trying to get the redirect plugin working for a bit I switched over to Simple 301, so now the URL I posted is being redirected by that plugin to our new site. I'll close this issue since you won't be able to diagnose, but thanks for trying to have a look.
