### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by hzsuda** [johngodley/redirection#938]
```
Uncaught SyntaxError: Invalid or unexpected token http://www.posbilisim.com/wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75 12
```

Plugin: 3.2
WordPress: 4.9.5 (single)
PHP: 5.6.36
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
JavaScript: http://www.posbilisim.com/wp-content/plugins/redirection/redirection.js
REST API: http://www.posbilisim.com/wp-json/

**Comment by johngodley** [comment]
Can you open your browser's developer console and load the page again? It should provide more error details
