### ISSUE TITLE
Plugin not working, empty, blinking

### ISSUE THREAD

**Issue by msongbird** [johngodley/redirection#947]
Hi
I have installed the plugin two weeks ago. I have used it to create several redirects. They work.

Today when I go to the plugin everything is empty. No log, no 404's, no list of redirects, just a blinking bar. Making a new redirect fails too, when I click the Add Redirect button nothing happens. 

I deactivated all plugins, cleared cache etc. but my plugin remains empty, non functional with a blinking bar.

Using Safari 11.1
Wordpress version 4.9.5
Plugin version 3.2

Hope someone can help.
Thank you.
Marianne

**Comment by johngodley** [comment]
Can you paste a screenshot here?

Also, can you open your browser's developer console and see if any errors are shown?

**Comment by msongbird** [comment]
Sorry for the delay. Everything is working fine again. No idea what caused it, or what solved it, but can't reproduce it anymore.
