### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by cpi83** [johngodley/redirection#948]
```
Uncaught SyntaxError: Invalid or unexpected token https://outdoorsports-mag.com/wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75 12
```

Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 7.0.25-nmm1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
JavaScript: https://outdoorsports-mag.com/wp-content/plugins/redirection/redirection.js
REST API: https://outdoorsports-mag.com/wp-json/

**Comment by johngodley** [comment]
When I view the URL mentioned in the error I can see corruption in the file:

![https___outdoorsports-mag_com_wp-content_plugins_redirection_redirection_js_ver_3_2-df1f37ef3f6aba1189b89b37737a9a75](https://user-images.githubusercontent.com/1277682/40268798-4be1b188-5b6c-11e8-93cc-98c820bfe6f9.jpg)

I don't know what has caused that but it appears that Redirection isn't installed properly, and it is this that is probably causing the error.
