### ISSUE TITLE
"Failed to fetch / REST API is being redirected" Error

### ISSUE THREAD

**Issue by Azed2018** [johngodley/redirection#950]
```
Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 5.6.33
Browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36 X-Middleton/1
JavaScript: http://officepourtous.com/wp-content/plugins/redirection/redirection.js
REST API: http://officepourtous.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

Error: Failed to fetch

Error: Failed to fetch
```
![redirection plugin status](https://user-images.githubusercontent.com/39463947/40281170-5066838c-5c4d-11e8-81a6-2b6f49df330e.png)

**Comment by johngodley** [comment]
You may find that the 3.3 beta helps:

https://github.com/johngodley/redirection/releases/tag/3.3-beta1

if the error still shows then you can change the option in the REST API dropdown to something else.

**Comment by Azed2018** [comment]
No, it doesn't work. I used the beta version and the different REST API options but it still shows the same error.
Thank you anyway.

**Comment by johngodley** [comment]
Ok, at this point it seems it's something specific to your server. Can you check if you are using any kind of security plugin such as Wordfence?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
