### ISSUE TITLE
Multiple Host+URL rules cause only one rule to match

### ISSUE THREAD

**Issue by sean-ad** [johngodley/redirection#951]
First of all, thanks for a great plugin that has performed superbly many many times!

### Summary

When consolidating two domains into a third, a user creates redirect rules matching the HTTP Host header + URL, one for each domain. The user expects each rule to function independently, with a match occurring only when the Host + URL defined in the rule matches visitor traffic. 

The user's goal is to rewrite the Host and discard the URL portion, sending traffic to a designated page which is specific for each domain. The problem only occurs when the user is attempting to match all pages for a domain. The problem is not encountered if the URL portion is page specific, such as `/my-page`.

### Actual Behavior

The first Host + URL rule encountered is the only rule to match. If Position is defined, the rule with the highest Position matches. Swapping the Position value (if defined) causes the previously matched rule to no longer match, and the previously unmatched rule to go into effect instead.

### Steps to reproduce

Create two redirect rules using a combination of Host name and URL. For the URL portion, use a regex pattern to capture all possible URLs for each matching domain.

* domain-1.local + ^/.*$ redirecting to http://domain-3.local/domain-one/, with position 1 and regex box checked
* domain-2.local + ^/.*$ redirecting to http://domain-3.local/domain-two/, with position 2 and regex box checked

Test using cURL:

```
$ curl -I -H "Host:domain-1.local" http://domain-3.local/foo
HTTP/1.1 301 Moved Permanently
X-Redirect-Agent: redirection
Location: http://domain-3.local/domain-one/

$ curl -I -H "Host:domain-2.local" http://domain-3.local/bar
HTTP/1.1 200 OK  
```

The second Host + URL should match, but does not. Swap the Position value in each rule, and the rules that match will also swap.

<img width="1100" alt="screen shot 2018-05-21 at 12 41 33 pm" src="https://user-images.githubusercontent.com/454888/40327937-422589ae-5d0a-11e8-9cf8-ce151a0edaf4.png">

### Environment

MacOSX 10.13.4 (High Sierra)
Chrome version 66.0.3359.181 (Official Build) (64-bit)
WordPress 4.9.6 running Twenty Sixteen theme.
Redirection version 3.2
Apache 2.4 and PHP 7.2.1 via MAMP Pro
All other plugins disabled

**Comment by johngodley** [comment]
Please try the 3.3 beta:

https://github.com/johngodley/redirection/releases/tag/3.3-beta1
