### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by bilisimhocasi** [johngodley/redirection#952]
```
Uncaught SyntaxError: Invalid or unexpected token https://www.gunebakisgazetesi.com/wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75 12,Uncaught SyntaxError: Invalid or unexpected token https://www.gunebakisgazetesi.com/wp-content/plugins/wordpress-seo/js/dist/commons-751.min.js?ver=7.5.1 9
```

Plugin: 3.2
WordPress: 4.9.5 (single)
PHP: 5.6.36
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
JavaScript: https://www.gunebakisgazetesi.com/wp-content/plugins/redirection/redirection.js
REST API: https://www.gunebakisgazetesi.com/wp-json/

**Comment by johngodley** [comment]
Can you try disabling other plugins? It looks like one of them is causing an error

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
