### ISSUE TITLE
Redirection is not working | Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by kamaldeepoodles** [johngodley/redirection#955]
Hi, while opening the redirect page, I am getting the following error. Moreover, no error log is getting printed in the apache2 access and error log file.
I have even cleared the cache in Cloudflare and also checked all the plugins if any doing minification and storing.
Please find the attached screenshot for reference.

![screenshot from 2018-05-23 13-59-29](https://user-images.githubusercontent.com/10527158/40412655-907d2b06-5e91-11e8-99a2-f9bf341a9e2f.png)

Please let me know how to resolve the same.

**Comment by johngodley** [comment]
Can you upgrade to the latest version and try again?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information
