### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by coolcash4live** [johngodley/redirection#958]
Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 5.6.36
Browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
JavaScript: https://dascointech.com/wp-content/plugins/redirection/redirection.js
REST API: https://dascointech.com/wp-json/

**Comment by johngodley** [comment]
You may find that the 3.3 beta helps:

https://github.com/johngodley/redirection/releases/tag/3.3-beta1

if the error still shows then you can change the option in the REST API dropdown to something else.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
