### ISSUE TITLE
Trying to include a | in the target URL

### ISSUE THREAD

**Issue by ajtruckle** [johngodley/redirection#963]
### Summary

I am trying to redirect from a source link (that uses regex) to a target link:

![redirect](https://user-images.githubusercontent.com/7985331/40577038-efc6b2b4-60f6-11e8-82ba-a66e3a94d0aa.jpg)

It should automatically translate a page with the stated language using Google Translate.

### Actual Behavior

When I try to use this redirection I am sent here:

![test2](https://user-images.githubusercontent.com/7985331/40577047-059c982e-60f7-11e8-8182-8598bf315cb8.jpg)

As you can see, it has stripped out the `|` character from the target URL.

### Steps to reproduce

I have a source link of:

`/msa/meet_sched_assist_ita.php(?:\?lang=ita)?`

I have a target link of:

`https://www.publictalksoftware.co.uk/meeting-schedule-assistant/#googtrans(en|it)`

### Environment

I have tried all the latest browsers - IE, Edge, Chrome and Firefox and they all do the same.
Wordpress is 4.9.6 and Redirect is 3.2

I have tried several things to fix this. `\|` etc but nothing works. Whatever I try the | is stripped.

**Comment by ajtruckle** [comment]
At the moment I am using my  HTACCESS and doing it that way for these links. An example:

`Redirect 301 /msa/meet_sched_assist_afk.php https://www.publictalksoftware.co.uk/meeting-schedule-assistant/#googtrans(en|ak)`

This will not strip out the `|` which the plugin is appearing to do. Using this actual redirect means the user can put in:

- `/msa/meet_sched_assist_afk.php`
- `/msa/meet_sched_assist_afk.php?lang=afk`

Both will be redirected. The only drawback is that the **query string** is also transferred. I read up on a method for not passing that over but my domain provided wants me to stick with the 301.

Either way, ideally I want to use the plugin, and I want the **source** to be:

- `/msa/meet_sched_assist_afk.php`
- `/msa/meet_sched_assist_afk.php?lang=afk`

And the **target** to be:

`meeting-schedule-assistant/#googtrans(en|ak)`

So any help in dealing with this is appreciated. As it would be nice to have it all in the plugin.

**Comment by ajtruckle** [comment]
After I worked out how to configure it to write the rules to the `htaccess` file I tried again. I removed my `redirect 301` calls and got the plugin to update it instead.

I found that no link worked at all then. It basically didn't find a redirection, even though I had set the cache value to **never** for testing.

In my plugin configurations I have two groups. One group works at the top level on the site. I adjusted that group to use **Apache** and it seems that they work file. This group is called **Legacy Website**. But all the ones for which I am having a problem, they are in the group **Meeting Schedule Assistant**. I have now disabled that group and gone back to my own redirects.

**Comment by ajtruckle** [comment]
Therefore, I kindly request again how to include | in the target URL when you are using the "Wordpress" mode for redirection. Thank you.

**Comment by ajtruckle** [comment]
Any update please? Thanks.

**Comment by johngodley** [comment]
The `|` is removed by WordPress as part of the `wp_sanitize_redirect` function. I don't know why it does this, but WordPress believes this is an invalid character to have in a redirect. The function is part of `pluggable.php`, so you can override it for your site.

**Comment by ajtruckle** [comment]
OK, thanks for the explanation. I think i will stick with doign them through the HTACCESS file directly as I am unsure as the overiding the default API calls. Thanks all the same.
