### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by divmonkey** [johngodley/redirection#966]
![wordpress rest api error report](https://user-images.githubusercontent.com/11624288/40590472-0483d2f4-6232-11e8-82c4-c95da12ade65.png)

```
Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 5.6.27
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
JavaScript: https://mtsisolutions.com/wp-content/plugins/redirection/redirection.js
REST API: https://mtsisolutions.com/wp-json/

Error: Unexpected token < in JSON at position 0

Error: Unexpected token < in JSON at position 0
```

After I clicked the Magicfix button, just went 503.

**Comment by johngodley** [comment]
You may find that the 3.3 beta helps:

https://github.com/johngodley/redirection/releases/tag/3.3-beta1

if the error still shows then you can change the option in the REST API dropdown to something else.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
