### ISSUE TITLE
Custom rol can't acces /tools.php?page=redirection.php

### ISSUE THREAD

**Issue by tatof** [johngodley/redirection#973]
Hello,

I made a custom "Admin" rol with administration capabilities but the menu option "redirections" is gone and the "Admin" user cant acces the page.

I only have this issue with this plugin.
Other plugins work fine.

**The custom "admin" role clone code**
``add_action('init', 'cloneRole');
function cloneRole()
{
    global $wp_roles;
    if ( !isset( $wp_roles ))
    $wp_roles = new WP_Roles();
    $adm = $wp_roles->get_role('administrator');
    $wp_roles->add_role('adminrol', 'Admin', $adm->capabilities);
}``

Running latest Wordpress with latest redirection plugin

Thanks!

**Comment by johngodley** [comment]
I'm not really sure what the question is, but you can find details about how to change Redirection's default capability here:

https://redirection.me/support/faq/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
