### ISSUE TITLE
wp_cache_get and wp_cache_set to save mysql calls

### ISSUE THREAD

**Issue by romulodl** [johngodley/redirection#98]
I am trying to save some calls to mysql saving using `wp_cache_get` and `wp_cache_set` on `Red_Item::get_for_url` method. I know that for the majority this will not change much, but in our case this would save a lot of calls to the database as we use the memcache drop-in.

I would like to know your thoughts about it before I go forward with this as I am getting some problems doing it and I would have to do more changes to the code

Thanks,
Romulo

**Comment by johngodley** [comment]
I'm currently ripping out all the code for this part of the plugin to make it more efficient, and hopefully more easily cacheable so it might be worth waiting a bit until that's finished.

**Comment by romulodl** [comment]
Awesome! Please let me know if you need any help and when you progress with this issue!

Thanks,
Romulo

**Comment by spacedmonkey** [comment]
@johngodley do you have a time frame for this? It is a big performance issue for us that the sql queries are running on every page. Can I still give you a pull request?
