### ISSUE TITLE
Redirection stopped working REST API STOPPED WORKING

### ISSUE THREAD

**Issue by clairesch** [johngodley/redirection#982]
### Summary

I have had the redirection plugin for years with no problem. Suddenly it has stopped redirecting so that all redirects have become 404's. I have masses of 404's over the last few days. The plugin is showing a problem with the rest API. See this screenshot. I have no idea of how to fix this?
![screenshot 2018-06-04 17 31 09](https://user-images.githubusercontent.com/39935360/40952650-f98b655e-6873-11e8-9802-2416dc4371a4.png)

### Actual Behavior

All 301's are becoming 404's

### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
Firefox, 60.01.01, wordpress 4.9.6–en_GB (latest version), Rediredction plugin,

Looking forward for some assistance

**Comment by johngodley** [comment]
The message is likely a false positive. Can you give an example of a URL that should be redirecting but is returning a 404?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
