### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by erikkowalski** [johngodley/redirection#986]
Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 5.6.27
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
JavaScript: https://demakis.com/wp-content/plugins/redirection/redirection.js
REST API: https://demakis.com/wp-admin/admin-ajax.php?action=red_proxy&rest_path=

**Comment by johngodley** [comment]
Have you installed the plugin correctly? The file at https://demakis.com/wp-content/plugins/redirection/redirection.js is for a really really old version of the plugin.

**Comment by erikkowalski** [comment]
Hi I updated the plugin, and I go that error. It was working before the update though so I reverted to the old version, which is why your seeing the old code


Erik Kowalski, MFA
Adjunct Professor of Graphic Design
Owner / edk studio
edkstudio.com
508 965 6642

**Comment by johngodley** [comment]
Ok, you'll need to install the latest version again before I can help further.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
