### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by rmshkmr** [johngodley/redirection#987]
Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 7.1.18
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
JavaScript: http://blog.printstop.co.in/wp-content/plugins/redirection/redirection.js
REST API: http://blog.printstop.co.in/wp-json/

URL is showing 502 error
`http://blog.printstop.co.in/wp-content/plugins/redirection/redirection.js?ver=3.2-df1f37ef3f6aba1189b89b37737a9a75`

**Comment by johngodley** [comment]
I'm not seeing the 502 error - did you fix it?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
