### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by jatniel** [johngodley/redirection#991]
```
Plugin: 3.2
WordPress: 4.9.6 (single)
PHP: 7.0.27
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
JavaScript: https://www.url.net/wp-content/plugins/redirection/redirection.js
REST API: https://www.url.net/wp-json/

Error: Unexpected token < in JSON at position 0
```

**Comment by patrick69FR** [comment]
Hello everyone, I have got the same issue. Deeply interested in any fix. Thanks

**Comment by johngodley** [comment]
You may find that the 3.3 beta helps:

https://github.com/johngodley/redirection/releases/tag/3.3-beta1

if the error still shows then you can change the option in the REST API dropdown to something else.

**Comment by patrick69FR** [comment]
Hi John, 

 

Many thanks for your prompt answer.

I am going to try and will let you know the result.

Have a nice day. 

 

---------------------------

Patrick Zoccolo

+33 6 62 82 29 24

 <mailto:pzoccolo@free.fr> pzoccolo@free.fr

skype : patrick.zoccolo

 

De : John [mailto:notifications@github.com] 
Envoyé : dimanche 17 juin 2018 14:15
À : johngodley/redirection
Cc : patrick69FR; Comment
Objet : Re: [johngodley/redirection] Redirection Error (#991)

 

You may find that the 3.3 beta helps:

https://github.com/johngodley/redirection/releases/tag/3.3-beta1

if the error still shows then you can change the option in the REST API dropdown to something else.

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
