### ISSUE TITLE
Problem starting Redirection 3.2

### ISSUE THREAD

**Issue by JBCouton** [johngodley/redirection#997]
```
Uncaught SyntaxError: Invalid or unexpected token https://sop-events.fr/wp-content/plugins/redirection/redirection.js 12
```

Plugin: REDIRECTION_VERSION
WordPress: 4.9.6 (single)
PHP: 5.6.30
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
JavaScript: https://sop-events.fr/wp-content/plugins/redirection/redirection.js
REST API: https://sop-events.fr/wp-json/

**Comment by johngodley** [comment]
How did you install the plugin? One of your files is very corrupt:

https://sop-events.fr/wp-content/plugins/redirection/redirection.js

Scroll down and see lots of weird characters.

You will need to re-install the plugin without the corrupted file.

**Comment by JBCouton** [comment]
Hi, the plugin was installed long time ago.
I try to delete and re-install the plugin, but the problem still here

**Comment by johngodley** [comment]
Can you open your browser's developer console and see if any more information is shown?

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
