### ISSUE TITLE
(SSL) Redirect all HTTP requests to HTTPS

### ISSUE THREAD

**Issue by LauGau** [johngodley/redirection#999]
Hi ;

First of all : thanks for your amazing plugin !!!
I was wondering if we can force HTTPS with it.

Because each time I enter `http://mysite.tld/(.*)` it's shorten by `/(.*)`
So when I try to redirect to `https://mysite.tld/$1/` I have the loop problem.

Is there a way to force HTTPS with your plugin ?
Thanks again :)

**Comment by johngodley** [comment]
If you have a loop then it's probably because your regular expression isn't exact enough. Can you list your source and target URLs, and an example URL that is looping?

**Comment by LauGau** [comment]
In fact I want ALL the requests passed through HTTP... to be displayed to HTTPS.

My website URL is : https://florencedavid-elixirsfloraux.com

This is working properly : 
```
/redirect-test/(.*)
https://florencedavid-elixirsfloraux.com/redirect-result/$1/
```
Try : `http://florencedavid-elixirsfloraux.com/**redirect-test**/this-is-my-page`
You will be well redirected to `http**s**://florencedavid-elixirsfloraux.com/**redirect-result**/this-is-my-page`

The trouble come from the rewriting of : 
`http://florencedavid-elixirsfloraux.com/(.*)` TO `/(.*)`

I really want to only redirect when the request is first through HTPP and not HTTPS.
I don't know if I'm clear... :-/

Thanks again

**Comment by johngodley** [comment]
I don't understand your second redirect - did you mean it redirects to `/$1`? If so, you can just put the full URL there: `https://florencedavid-elixirsfloraux.com/$1`

**Comment by johngodley** [comment]
Ok, it's not possible to use Redirection to redirect from http to https like that. What you have created is an infinite redirect.

You will need to use something like what is explained here:

https://stackoverflow.com/questions/4083221/how-to-redirect-all-http-requests-to-https

**Comment by LauGau** [comment]
Thank you John.
I've already tried with the .htaccess but it doesn't work... :-/ (I will try to contact my hosting)
Only the "simple SSL" plugin give me what I need. But I don't want to add a plugin just for that.
So I hope your plugin can help cause I already have it installed one some of my websites.
Thanks again for your time. 👍
